Messaging System: kcenon::monitoring::core::gauge Class Reference
kcenon::monitoring::core::gauge Class Reference
#include <monitor.h>
Public Member Functions
gauge (std::string name, std::string description="", labels labels={})
void set (double value)
void increment (double delta=1.0)
void decrement (double delta=1.0)
double get () const
std::string name () const override
metric_type type () const override
std::string description () const override
metric_value value () const override
labels get_labels () const override
Public Member Functions inherited from kcenon::monitoring::core::metric
virtual ~metric ()=default
Detailed Description
Definition at line 86 of file monitor.h.
Constructor & Destructor Documentation
gauge()
kcenon::monitoring::core::gauge::gauge (std::string name, std::string description = "", labels labels = {}) inline
Definition at line 94 of file monitor.h.
Member Function Documentation
decrement()
void kcenon::monitoring::core::gauge::decrement (double delta = 1.0) inline
Definition at line 110 of file monitor.h.
References increment().
description()
std::string kcenon::monitoring::core::gauge::description () const inline override virtual
Implements kcenon::monitoring::core::metric.
Definition at line 121 of file monitor.h.
get()
double kcenon::monitoring::core::gauge::get () const inline
Definition at line 114 of file monitor.h.
Referenced by value().
get_labels()
labels kcenon::monitoring::core::gauge::get_labels () const inline override virtual
Implements kcenon::monitoring::core::metric.
Definition at line 123 of file monitor.h.
increment()
void kcenon::monitoring::core::gauge::increment (double delta = 1.0) inline
Definition at line 103 of file monitor.h.
Referenced by decrement().
name()
std::string kcenon::monitoring::core::gauge::name () const inline override virtual
Implements kcenon::monitoring::core::metric.
Definition at line 119 of file monitor.h.
set()
void kcenon::monitoring::core::gauge::set (double value) inline
Definition at line 99 of file monitor.h.
References value().
type()
metric_type kcenon::monitoring::core::gauge::type () const inline override virtual
Implements kcenon::monitoring::core::metric.
Definition at line 120 of file monitor.h.
References kcenon::monitoring::core::GAUGE.
value()
metric_value kcenon::monitoring::core::gauge::value () const inline override virtual
Implements kcenon::monitoring::core::metric.
Definition at line 122 of file monitor.h.
References get().
Referenced by set().
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/monitoring/core/monitor.h