Messaging System: monitoring_system::stream_aggregator Class Reference
monitoring_system::stream_aggregator Class Reference
Main class for statistical stream aggregation.
#include <stream_aggregator.h>
Public Member Functions
stream_aggregator (const stream_aggregator_config &config={})
Constructor.
result_void add_observation (double value, std::chrono::system_clock::time_point timestamp=std::chrono::system_clock::now())
Add observation to stream.
stream_statistics get_statistics () const
Get comprehensive statistics.
result< double > get_percentile (double p) const
Get specific percentile.
void reset ()
Reset all statistics.
uint64_t count () const
Get current sample count.
double mean () const
Get current mean.
double variance () const
Get current variance.
const stream_aggregator_config & get_config () const noexcept
Get configuration.
Detailed Description
Main class for statistical stream aggregation.
Definition at line 465 of file stream_aggregator.h.
Constructor & Destructor Documentation
stream_aggregator()
monitoring_system::stream_aggregator::stream_aggregator (const stream_aggregator_config & config = {}) inline explicit
Constructor.
Definition at line 506 of file stream_aggregator.h.
Member Function Documentation
add_observation()
result_void monitoring_system::stream_aggregator::add_observation (double value, std::chrono::system_clock::time_point timestamp = std::chrono::system_clock::now()) inline
Add observation to stream.
Definition at line 522 of file stream_aggregator.h.
References monitoring_system::moving_window_aggregator< T >::add_value(), monitoring_system::online_statistics::add_value(), and monitoring_system::online_statistics::count().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
count()
uint64_t monitoring_system::stream_aggregator::count () const inline
Get current sample count.
Definition at line 629 of file stream_aggregator.h.
References monitoring_system::online_statistics::count().
Referenced by TEST_F(), and TEST_F().
get_config()
const stream_aggregator_config & monitoring_system::stream_aggregator::get_config () const inline noexcept
Get configuration.
Definition at line 653 of file stream_aggregator.h.
get_percentile()
result< double > monitoring_system::stream_aggregator::get_percentile (double p) const inline
Get specific percentile.
Definition at line 594 of file stream_aggregator.h.
References monitoring_system::collector_not_found, monitoring_system::invalid_argument, and monitoring_system::make_success().
Referenced by TEST_F().
get_statistics()
stream_statistics monitoring_system::stream_aggregator::get_statistics () const inline
Get comprehensive statistics.
Definition at line 553 of file stream_aggregator.h.
References monitoring_system::online_statistics::get_statistics(), and monitoring_system::stream_statistics::percentiles.
Referenced by TEST_F(), TEST_F(), and TEST_F().
mean()
double monitoring_system::stream_aggregator::mean () const inline
Get current mean.
Definition at line 637 of file stream_aggregator.h.
References monitoring_system::online_statistics::mean().
Referenced by TEST_F().
reset()
void monitoring_system::stream_aggregator::reset () inline
Reset all statistics.
Definition at line 614 of file stream_aggregator.h.
References monitoring_system::moving_window_aggregator< T >::clear(), and monitoring_system::online_statistics::reset().
Referenced by TEST_F().
variance()
double monitoring_system::stream_aggregator::variance () const inline
Get current variance.
Definition at line 645 of file stream_aggregator.h.
References monitoring_system::online_statistics::variance().
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/stream_aggregator.h