Messaging System: monitoring_module::thread_pool_analyzer Class Reference
monitoring_module::thread_pool_analyzer Class Reference
Thread pool 분석 및 비교 도구
#include <thread_pool_analyzer.h>
Classes
struct pool_comparison_result
Thread pool 비교 결과
struct pool_performance_summary
Thread pool 성능 요약
Public Types
using pool_identifier = monitoring_interface::thread_pool_identifier
using pool_metrics = monitoring_interface::process_thread_pool_metrics
using process_identifier = monitoring_interface::process_identifier
Static Public Member Functions
static pool_performance_summary analyze_pool (const pool_metrics &metrics)
Thread pool 성능 분석
static pool_comparison_result compare_pools (const pool_metrics &metrics1, const pool_metrics &metrics2)
동일 프로세스 내 thread pool 비교
static std::unordered_map< process_identifier, std::pair< pool_identifier, pool_identifier > > find_best_worst_pools_per_process (const std::unordered_map< process_identifier, std::vector< pool_metrics > > &pools_by_process)
프로세스별 thread pool 그룹 분석
static std::optional< std::string > detect_bottleneck (const pool_metrics &metrics)
Thread pool 병목 현상 감지
static std::vector< std::string > suggest_optimizations (const pool_metrics &metrics)
Thread pool 최적화 제안
static std::string classify_pool_type (const pool_metrics &metrics)
Thread pool 유형 분류
static double calculate_load_balance_score (const std::vector< std::uint64_t > &worker_loads)
워커 부하 분산 점수 계산
static double calculate_health_score (const pool_metrics &metrics)
Thread pool 건강도 점수
Detailed Description
Thread pool 분석 및 비교 도구
여러 thread pool의 성능을 분석하고 비교하는 기능 제공
Definition at line 24 of file thread_pool_analyzer.h.
Member Typedef Documentation
pool_identifier
using monitoring_module::thread_pool_analyzer::pool_identifier = monitoring_interface::thread_pool_identifier
Definition at line 26 of file thread_pool_analyzer.h.
pool_metrics
using monitoring_module::thread_pool_analyzer::pool_metrics = monitoring_interface::process_thread_pool_metrics
Definition at line 27 of file thread_pool_analyzer.h.
process_identifier
using monitoring_module::thread_pool_analyzer::process_identifier = monitoring_interface::process_identifier
Definition at line 28 of file thread_pool_analyzer.h.
Member Function Documentation
analyze_pool()
thread_pool_analyzer::pool_performance_summary monitoring_module::thread_pool_analyzer::analyze_pool (const pool_metrics & metrics) static
Thread pool 성능 분석
Parameters
metrics Thread pool 메트릭
Returns
성능 요약
Definition at line 17 of file thread_pool_analyzer.cpp.
References monitoring_module::thread_pool_analyzer::pool_performance_summary::average_worker_load, calculate_load_balance_score(), monitoring_interface::thread_pool_metrics::idle_threads, monitoring_interface::thread_pool_metrics::jobs_completed, monitoring_interface::thread_pool_metrics::jobs_pending, monitoring_module::thread_pool_analyzer::pool_performance_summary::load_balance_score, monitoring_interface::process_thread_pool_metrics::pool_id, monitoring_module::thread_pool_analyzer::pool_performance_summary::pool_id, monitoring_module::thread_pool_analyzer::pool_performance_summary::queue_saturation, monitoring_module::thread_pool_analyzer::pool_performance_summary::throughput_per_worker, monitoring_module::thread_pool_analyzer::pool_performance_summary::total_throughput, monitoring_module::thread_pool_analyzer::pool_performance_summary::worker_efficiency, monitoring_interface::process_thread_pool_metrics::worker_load_distribution, and monitoring_interface::thread_pool_metrics::worker_threads.
Referenced by calculate_health_score(), classify_pool_type(), compare_pools(), detect_bottleneck(), main(), and suggest_optimizations().
calculate_health_score()
double monitoring_module::thread_pool_analyzer::calculate_health_score (const pool_metrics & metrics) static
Thread pool 건강도 점수
Parameters
metrics Thread pool 메트릭
Returns
건강도 점수 (0-100)
Definition at line 265 of file thread_pool_analyzer.cpp.
References analyze_pool(), monitoring_interface::thread_pool_metrics::average_latency_ns, and monitoring_interface::thread_pool_metrics::jobs_completed.
Referenced by find_best_worst_pools_per_process(), monitoring_module::analysis_dashboard::generate_optimization_suggestions(), and main().
calculate_load_balance_score()
double monitoring_module::thread_pool_analyzer::calculate_load_balance_score (const std::vector< std::uint64_t > & worker_loads) static
워커 부하 분산 점수 계산
Parameters
worker_loads 워커별 작업 수
Returns
부하 분산 점수 (0-100, 100이 완벽한 분산)
Definition at line 236 of file thread_pool_analyzer.cpp.
Referenced by analyze_pool().
classify_pool_type()
std::string monitoring_module::thread_pool_analyzer::classify_pool_type (const pool_metrics & metrics) static
Thread pool 유형 분류
Parameters
metrics Thread pool 메트릭
Returns
Pool 유형 (CPU-bound, IO-bound, Balanced, Idle)
Definition at line 214 of file thread_pool_analyzer.cpp.
References analyze_pool(), monitoring_interface::thread_pool_metrics::average_latency_ns, and monitoring_interface::thread_pool_metrics::jobs_completed.
Referenced by main().
compare_pools()
thread_pool_analyzer::pool_comparison_result monitoring_module::thread_pool_analyzer::compare_pools (const pool_metrics & metrics1, const pool_metrics & metrics2) static
동일 프로세스 내 thread pool 비교
Parameters
metrics1 첫 번째 pool 메트릭
metrics2 두 번째 pool 메트릭
Returns
비교 결과
Definition at line 55 of file thread_pool_analyzer.cpp.
References analyze_pool(), monitoring_module::thread_pool_analyzer::pool_comparison_result::efficiency_difference, monitoring_module::thread_pool_analyzer::pool_comparison_result::load_balance_difference, monitoring_module::thread_pool_analyzer::pool_comparison_result::performance_winner, monitoring_module::thread_pool_analyzer::pool_comparison_result::pool1, monitoring_module::thread_pool_analyzer::pool_comparison_result::pool2, monitoring_interface::process_thread_pool_metrics::pool_id, monitoring_interface::thread_pool_identifier::pool_name, monitoring_module::thread_pool_analyzer::pool_comparison_result::recommendation, and monitoring_module::thread_pool_analyzer::pool_comparison_result::throughput_ratio.
Referenced by main().
detect_bottleneck()
std::optional< std::string > monitoring_module::thread_pool_analyzer::detect_bottleneck (const pool_metrics & metrics) static
Thread pool 병목 현상 감지
Parameters
metrics Thread pool 메트릭
Returns
병목 현상 설명 (없으면 empty)
Definition at line 158 of file thread_pool_analyzer.cpp.
References analyze_pool(), monitoring_interface::thread_pool_metrics::average_latency_ns, and monitoring_interface::thread_pool_metrics::jobs_pending.
Referenced by monitoring_module::analysis_dashboard::analyze_bottlenecks(), monitoring_module::analysis_dashboard::generate_health_report(), and main().
find_best_worst_pools_per_process()
std::unordered_map< thread_pool_analyzer::process_identifier, std::pair< thread_pool_analyzer::pool_identifier, thread_pool_analyzer::pool_identifier > > monitoring_module::thread_pool_analyzer::find_best_worst_pools_per_process (const std::unordered_map< process_identifier, std::vector< pool_metrics > > & pools_by_process) static
프로세스별 thread pool 그룹 분석
Parameters
pools_by_process 프로세스별 thread pool 메트릭
Returns
프로세스별 최적/최악 pool 정보
Definition at line 124 of file thread_pool_analyzer.cpp.
References calculate_health_score().
suggest_optimizations()
std::vector< std::string > monitoring_module::thread_pool_analyzer::suggest_optimizations (const pool_metrics & metrics) static
Thread pool 최적화 제안
Parameters
metrics Thread pool 메트릭
Returns
최적화 제안 목록
Definition at line 185 of file thread_pool_analyzer.cpp.
References analyze_pool(), monitoring_interface::thread_pool_metrics::average_latency_ns, monitoring_interface::thread_pool_metrics::jobs_completed, monitoring_interface::thread_pool_metrics::jobs_pending, monitoring_interface::process_thread_pool_metrics::memory_pool_usage_bytes, and monitoring_interface::thread_pool_metrics::worker_threads.
Referenced by monitoring_module::analysis_dashboard::generate_health_report(), monitoring_module::analysis_dashboard::generate_optimization_suggestions(), and main().
The documentation for this class was generated from the following files:
libraries/monitoring_system/sources/monitoring/thread_pool_analyzer.h
libraries/monitoring_system/sources/monitoring/thread_pool_analyzer.cpp