Messaging System: libraries/monitoring_system/benchmarks/monitoring_benchmarks/monitoring_performance_benchmark.cpp File Reference
monitoring_performance_benchmark.cpp File Reference
#include <benchmark/benchmark.h>
#include <monitoring/monitoring.h>
#include <memory>
Functions
static void setup_monitor ()
static void cleanup_monitor ()
static void BM_SystemMetricsUpdate (benchmark::State &state)
BENCHMARK (BM_SystemMetricsUpdate)
static void BM_ThreadPoolMetricsUpdate (benchmark::State &state)
BENCHMARK (BM_ThreadPoolMetricsUpdate)
static void BM_WorkerMetricsUpdate (benchmark::State &state)
BENCHMARK (BM_WorkerMetricsUpdate)
static void BM_GetCurrentSnapshot (benchmark::State &state)
BENCHMARK (BM_GetCurrentSnapshot)
int main (int argc, char **argv)
Variables
static std::unique_ptr< monitoring > monitor_instance
Function Documentation
BENCHMARK() [1/4]
BENCHMARK (BM_GetCurrentSnapshot)
BENCHMARK() [2/4]
BENCHMARK (BM_SystemMetricsUpdate)
BENCHMARK() [3/4]
BENCHMARK (BM_ThreadPoolMetricsUpdate)
BENCHMARK() [4/4]
BENCHMARK (BM_WorkerMetricsUpdate)
BM_GetCurrentSnapshot()
static void BM_GetCurrentSnapshot (benchmark::State & state) static
Definition at line 85 of file monitoring_performance_benchmark.cpp.
References monitor_instance, and setup_monitor().
BM_SystemMetricsUpdate()
static void BM_SystemMetricsUpdate (benchmark::State & state) static
Definition at line 30 of file monitoring_performance_benchmark.cpp.
References monitoring_interface::system_metrics::memory_usage_bytes, monitor_instance, and setup_monitor().
BM_ThreadPoolMetricsUpdate()
static void BM_ThreadPoolMetricsUpdate (benchmark::State & state) static
Definition at line 47 of file monitoring_performance_benchmark.cpp.
References monitor_instance, and setup_monitor().
BM_WorkerMetricsUpdate()
static void BM_WorkerMetricsUpdate (benchmark::State & state) static
Definition at line 65 of file monitoring_performance_benchmark.cpp.
References monitoring_interface::worker_metrics::jobs_processed, monitor_instance, and setup_monitor().
cleanup_monitor()
static void cleanup_monitor () static
Definition at line 23 of file monitoring_performance_benchmark.cpp.
References monitor_instance.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 102 of file monitoring_performance_benchmark.cpp.
References cleanup_monitor().
setup_monitor()
static void setup_monitor () static
Definition at line 16 of file monitoring_performance_benchmark.cpp.
References monitor_instance.
Referenced by BM_GetCurrentSnapshot(), BM_SystemMetricsUpdate(), BM_ThreadPoolMetricsUpdate(), and BM_WorkerMetricsUpdate().
Variable Documentation
monitor_instance
std::unique_ptr<monitoring> monitor_instance static
Definition at line 14 of file monitoring_performance_benchmark.cpp.
Referenced by BM_ConcurrentMetricsUpdates(), BM_GetCurrentSnapshot(), BM_GetRecentSnapshots(), BM_HighFrequencyUpdates(), BM_ManualCollection(), BM_MultithreadedUpdates(), BM_SystemMetricsUpdate(), BM_ThreadPoolMetricsUpdate(), BM_WorkerMetricsUpdate(), cleanup_monitor(), and setup_monitor().