Messaging System: kcenon::messaging::core::object_pool< T > Class Template Reference
kcenon::messaging::core::object_pool< T > Class Template Reference
#include <production_optimizations.h>
Public Member Functions
object_pool (size_t max_size=1000)
std::unique_ptr< T > acquire ()
void release (std::unique_ptr< T > obj)
size_t size () const
size_t total_created () const
size_t pool_hits () const
double hit_ratio () const
Detailed Description
template<typename T>
class kcenon::messaging::core::object_pool< T >
Definition at line 47 of file production_optimizations.h.
Constructor & Destructor Documentation
object_pool()
template<typename T > kcenon::messaging::core::object_pool< T >::object_pool (size_t max_size = 1000) inline explicit
Definition at line 56 of file production_optimizations.h.
Member Function Documentation
acquire()
template<typename T > std::unique_ptr< T > kcenon::messaging::core::object_pool< T >::acquire () inline
Definition at line 58 of file production_optimizations.h.
Referenced by kcenon::messaging::core::production_message_allocator::allocate_message(), and kcenon::messaging::core::production_message_allocator::allocate_payload().
hit_ratio()
template<typename T > double kcenon::messaging::core::object_pool< T >::hit_ratio () const inline
Definition at line 91 of file production_optimizations.h.
Referenced by kcenon::messaging::core::production_message_allocator::get_stats().
pool_hits()
template<typename T > size_t kcenon::messaging::core::object_pool< T >::pool_hits () const inline
Definition at line 90 of file production_optimizations.h.
release()
template<typename T > void kcenon::messaging::core::object_pool< T >::release (std::unique_ptr< T > obj) inline
Definition at line 72 of file production_optimizations.h.
Referenced by kcenon::messaging::core::production_message_allocator::deallocate_message(), and kcenon::messaging::core::production_message_allocator::deallocate_payload().
size()
template<typename T > size_t kcenon::messaging::core::object_pool< T >::size () const inline
Definition at line 84 of file production_optimizations.h.
Referenced by kcenon::messaging::core::production_message_allocator::get_stats().
total_created()
template<typename T > size_t kcenon::messaging::core::object_pool< T >::total_created () const inline
Definition at line 89 of file production_optimizations.h.
Referenced by kcenon::messaging::core::production_message_allocator::get_stats().
The documentation for this class was generated from the following file:
application_layer/include/kcenon/messaging/core/production_optimizations.h