Messaging System: monitoring_system::health_check_result Struct Reference
monitoring_system::health_check_result Struct Reference
Health check result.
#include <monitoring_interface.h>
Public Member Functions
health_check_result ()
bool is_healthy () const
bool is_operational () const
Static Public Member Functions
static health_check_result healthy (const std::string &msg="OK")
static health_check_result unhealthy (const std::string &msg)
static health_check_result degraded (const std::string &msg)
static health_check_result healthy (const std::string &msg="OK")
static health_check_result unhealthy (const std::string &msg="FAILED")
static health_check_result degraded (const std::string &msg="DEGRADED")
Public Attributes
health_status status = health_status::unknown
std::string message
std::vector< std::string > issues
std::chrono::system_clock::time_point check_time
std::chrono::system_clock::time_point timestamp
std::chrono::milliseconds check_duration {0}
std::unordered_map< std::string, std::string > metadata
std::optional< std::exception_ptr > error
std::chrono::steady_clock::time_point timestamp
std::unordered_map< std::string, std::string > details
Detailed Description
Health check result.
Result of a health check operation.
Definition at line 106 of file monitoring_interface.h.
Constructor & Destructor Documentation
health_check_result()
monitoring_system::health_check_result::health_check_result () inline
Definition at line 116 of file monitoring_interface.h.
Member Function Documentation
degraded() [1/2]
static health_check_result monitoring_system::health_check_result::degraded (const std::string & msg) inline static
Definition at line 147 of file monitoring_interface.h.
References monitoring_system::degraded.
Referenced by demonstrate_health_monitoring(), and TEST_F().
degraded() [2/2]
static health_check_result monitoring_system::health_check_result::degraded (const std::string & msg = "DEGRADED") inline static
Definition at line 47 of file health_monitor.h.
References monitoring_system::degraded.
healthy() [1/2]
static health_check_result monitoring_system::health_check_result::healthy (const std::string & msg = "OK") inline static
Definition at line 129 of file monitoring_interface.h.
References monitoring_system::healthy.
Referenced by demonstrate_health_monitoring(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
healthy() [2/2]
static health_check_result monitoring_system::health_check_result::healthy (const std::string & msg = "OK") inline static
Definition at line 31 of file health_monitor.h.
References monitoring_system::healthy.
is_healthy()
bool monitoring_system::health_check_result::is_healthy () const inline
Definition at line 120 of file monitoring_interface.h.
References monitoring_system::healthy, and status.
Referenced by TEST_F().
is_operational()
bool monitoring_system::health_check_result::is_operational () const inline
Definition at line 124 of file monitoring_interface.h.
References monitoring_system::degraded, monitoring_system::healthy, and status.
unhealthy() [1/2]
static health_check_result monitoring_system::health_check_result::unhealthy (const std::string & msg) inline static
Definition at line 138 of file monitoring_interface.h.
References monitoring_system::unhealthy.
Referenced by demonstrate_health_monitoring(), TEST_F(), and TEST_F().
unhealthy() [2/2]
static health_check_result monitoring_system::health_check_result::unhealthy (const std::string & msg = "FAILED") inline static
Definition at line 39 of file health_monitor.h.
References monitoring_system::unhealthy.
Member Data Documentation
check_duration
std::chrono::milliseconds monitoring_system::health_check_result::check_duration {0}
Definition at line 112 of file monitoring_interface.h.
check_time
std::chrono::system_clock::time_point monitoring_system::health_check_result::check_time
Definition at line 110 of file monitoring_interface.h.
details
std::unordered_map<std::string, std::string> monitoring_system::health_check_result::details
Definition at line 29 of file health_monitor.h.
error
std::optional<std::exception_ptr> monitoring_system::health_check_result::error
Definition at line 114 of file monitoring_interface.h.
issues
std::vector<std::string> monitoring_system::health_check_result::issues
Definition at line 109 of file monitoring_interface.h.
Referenced by TEST_F().
message
std::string monitoring_system::health_check_result::message
Definition at line 108 of file monitoring_interface.h.
metadata
std::unordered_map<std::string, std::string> monitoring_system::health_check_result::metadata
Definition at line 113 of file monitoring_interface.h.
status
health_status monitoring_system::health_check_result::status = health_status::unknown
Definition at line 107 of file monitoring_interface.h.
Referenced by is_healthy(), is_operational(), and TEST_F().
timestamp [1/2]
std::chrono::system_clock::time_point monitoring_system::health_check_result::timestamp
Definition at line 111 of file monitoring_interface.h.
timestamp [2/2]
std::chrono::steady_clock::time_point monitoring_system::health_check_result::timestamp
Definition at line 28 of file health_monitor.h.
The documentation for this struct was generated from the following files:
libraries/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_interface.h
libraries/monitoring_system/include/monitoring/health/health_monitor.h