Messaging System: fmt::formatter< thread_pool_module::thread_worker > Struct Reference
fmt::formatter< thread_pool_module::thread_worker > Struct Reference
Specialization of fmt::formatter for thread_pool_module::thread_worker.
#include <thread_worker.h>
Public Member Functions
template<typename FormatContext >
auto format (const thread_pool_module::thread_worker &item, FormatContext &ctx) const
Formats a thread_worker object as a string.
template<typename FormatContext >
auto format (const thread_pool_module::thread_worker &item, FormatContext &ctx) const
Formats a thread_worker object as a string.
template<typename FormatContext >
auto format (const thread_pool_module::thread_worker &item, FormatContext &ctx) const
Formats a thread_worker object as a string.
Detailed Description
Specialization of fmt::formatter for thread_pool_module::thread_worker.
Allows thread_worker objects to be formatted as strings using the {fmt} library.
Example
auto worker = std::make_unique<thread_pool_module::thread_worker>();
std::string output = fmt::format("Worker status: {}", *worker);
Allows thread_worker objects to be formatted as strings using the {fmt} library.
Example
auto worker = std::make_unique<thread_pool_module::thread_worker>();
std::string output = fmt::format("Worker status: {}", *worker);
Allows thread_worker objects to be formatted as strings using the {fmt} library.
Example
auto worker = std::make_unique<thread_pool_module::thread_worker>();
std::string output = fmt::format("Worker status: {}", *worker);
Definition at line 254 of file thread_worker.h.
Member Function Documentation
format() [1/3]
template<typename FormatContext > auto fmt::formatter< thread_pool_module::thread_worker >::format (const thread_pool_module::thread_worker & item, FormatContext & ctx) const inline
Formats a thread_worker object as a string.
Template Parameters
FormatContext The type of the format context.
Parameters
item The thread_worker to format.
ctx The format context for output.
Returns
An iterator to the end of the formatted output.
Definition at line 264 of file thread_worker.h.
References thread_module::thread_base::to_string().
format() [2/3]
template<typename FormatContext > auto fmt::formatter< thread_pool_module::thread_worker >::format (const thread_pool_module::thread_worker & item, FormatContext & ctx) const inline
Formats a thread_worker object as a string.
Template Parameters
FormatContext The type of the format context.
Parameters
item The thread_worker to format.
ctx The format context for output.
Returns
An iterator to the end of the formatted output.
Definition at line 264 of file thread_worker.h.
References thread_module::thread_base::to_string().
format() [3/3]
template<typename FormatContext > auto fmt::formatter< thread_pool_module::thread_worker >::format (const thread_pool_module::thread_worker & item, FormatContext & ctx) const inline
Formats a thread_worker object as a string.
Template Parameters
FormatContext The type of the format context.
Parameters
item The thread_worker to format.
ctx The format context for output.
Returns
An iterator to the end of the formatted output.
Definition at line 278 of file thread_worker.h.
References thread_module::thread_base::to_string().
The documentation for this struct was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/thread_pool/workers/thread_worker.h
libraries/thread_system/modular_structure/core/src/thread_pool/workers/thread_worker.h
libraries/thread_system/sources/thread_pool/workers/thread_worker.h