Messaging System: monitoring_module::lock_free_metrics_queue< T > Class Template Reference
monitoring_module::lock_free_metrics_queue< T > Class Template Reference
락프리 메트릭 큐
#include <optimized_storage.h>
Public Member Functions
lock_free_metrics_queue (std::size_t capacity)
bool enqueue (T item)
bool dequeue (T &item)
std::size_t size () const
bool empty () const
Detailed Description
template<typename T>
class monitoring_module::lock_free_metrics_queue< T >
락프리 메트릭 큐
고성능 메트릭 수집을 위한 락프리 큐 구현
Definition at line 119 of file optimized_storage.h.
Constructor & Destructor Documentation
lock_free_metrics_queue()
template<typename T > monitoring_module::lock_free_metrics_queue< T >::lock_free_metrics_queue (std::size_t capacity) inline explicit
Definition at line 121 of file optimized_storage.h.
Member Function Documentation
dequeue()
template<typename T > bool monitoring_module::lock_free_metrics_queue< T >::dequeue (T & item) inline
Definition at line 164 of file optimized_storage.h.
Referenced by monitoring_module::tiered_storage::perform_aging().
empty()
template<typename T > bool monitoring_module::lock_free_metrics_queue< T >::empty () const inline
Definition at line 195 of file optimized_storage.h.
References monitoring_module::lock_free_metrics_queue< T >::size().
enqueue()
template<typename T > bool monitoring_module::lock_free_metrics_queue< T >::enqueue (T item) inline
Definition at line 139 of file optimized_storage.h.
Referenced by monitoring_module::tiered_storage::store().
size()
template<typename T > std::size_t monitoring_module::lock_free_metrics_queue< T >::size () const inline
Definition at line 189 of file optimized_storage.h.
Referenced by monitoring_module::lock_free_metrics_queue< T >::empty(), monitoring_module::tiered_storage::get_memory_stats(), and monitoring_module::tiered_storage::perform_aging().
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/monitoring/optimized_storage.h