Messaging System: libraries/logger_system/tests/unit/di_test/di_container_test.cpp File Reference
di_container_test.cpp File Reference
Unit tests for DI container implementations.
#include <gtest/gtest.h>
#include "../../sources/logger/di/lightweight_di_container.h"
#include "../../sources/logger/di/di_container_factory.h"
#include "../../sources/logger/writers/base_writer.h"
#include <memory>
#include <thread>
#include <vector>
#include <chrono>
Classes
class mock_writer
class di_container_test
Functions
TEST_F (di_container_test, lightweight_container_factory_registration)
TEST_F (di_container_test, lightweight_container_resolve_factory)
TEST_F (di_container_test, lightweight_container_singleton_registration)
TEST_F (di_container_test, lightweight_container_resolve_singleton)
TEST_F (di_container_test, lightweight_container_resolve_not_found)
TEST_F (di_container_test, lightweight_container_invalid_registration)
TEST_F (di_container_test, lightweight_container_clear)
TEST_F (di_container_test, lightweight_container_thread_safety)
TEST_F (di_container_test, factory_create_lightweight)
TEST_F (di_container_test, factory_create_automatic)
TEST_F (di_container_test, factory_create_best_available)
TEST_F (di_container_test, factory_type_check)
TEST_F (di_container_test, lightweight_container_register_type)
TEST_F (di_container_test, lightweight_container_register_type_with_args)
TEST_F (di_container_test, lightweight_container_factory_returns_null)
TEST_F (di_container_test, lightweight_container_factory_throws)
Detailed Description
Unit tests for DI container implementations.
Definition in file di_container_test.cpp.
Function Documentation
TEST_F() [1/16]
TEST_F (di_container_test , factory_create_automatic)
Definition at line 252 of file di_container_test.cpp.
References kcenon::logger::di::di_container_factory::automatic.
TEST_F() [2/16]
TEST_F (di_container_test , factory_create_best_available)
Definition at line 268 of file di_container_test.cpp.
TEST_F() [3/16]
TEST_F (di_container_test , factory_create_lightweight)
Definition at line 236 of file di_container_test.cpp.
TEST_F() [4/16]
TEST_F (di_container_test , factory_type_check)
Definition at line 282 of file di_container_test.cpp.
TEST_F() [5/16]
TEST_F (di_container_test , lightweight_container_clear)
Definition at line 183 of file di_container_test.cpp.
TEST_F() [6/16]
TEST_F (di_container_test , lightweight_container_factory_registration)
Definition at line 85 of file di_container_test.cpp.
TEST_F() [7/16]
TEST_F (di_container_test , lightweight_container_factory_returns_null)
Definition at line 331 of file di_container_test.cpp.
References kcenon::logger::result< T >::error_code().
TEST_F() [8/16]
TEST_F (di_container_test , lightweight_container_factory_throws)
Definition at line 346 of file di_container_test.cpp.
References kcenon::logger::result< T >::error_code().
TEST_F() [9/16]
TEST_F (di_container_test , lightweight_container_invalid_registration)
Definition at line 160 of file di_container_test.cpp.
TEST_F() [10/16]
TEST_F (di_container_test , lightweight_container_register_type)
Definition at line 297 of file di_container_test.cpp.
TEST_F() [11/16]
TEST_F (di_container_test , lightweight_container_register_type_with_args)
Definition at line 312 of file di_container_test.cpp.
TEST_F() [12/16]
TEST_F (di_container_test , lightweight_container_resolve_factory)
Definition at line 98 of file di_container_test.cpp.
TEST_F() [13/16]
TEST_F (di_container_test , lightweight_container_resolve_not_found)
Definition at line 152 of file di_container_test.cpp.
References kcenon::logger::result< T >::error_code().
TEST_F() [14/16]
TEST_F (di_container_test , lightweight_container_resolve_singleton)
Definition at line 135 of file di_container_test.cpp.
TEST_F() [15/16]
TEST_F (di_container_test , lightweight_container_singleton_registration)
Definition at line 123 of file di_container_test.cpp.
TEST_F() [16/16]
TEST_F (di_container_test , lightweight_container_thread_safety)
Definition at line 204 of file di_container_test.cpp.