Messaging System: monitoring_system::file_storage_backend Class Reference
monitoring_system::file_storage_backend Class Reference
File storage backend - stub implementation.
#include <storage_backends.h>
Public Member Functions
file_storage_backend ()=default
file_storage_backend (const storage_config &config)
bool store (const std::string &key, const std::string &value) override
std::string retrieve (const std::string &key) override
bool remove (const std::string &key) override
result< bool > flush () override
Public Member Functions inherited from monitoring_system::kv_storage_backend
virtual ~kv_storage_backend ()=default
Detailed Description
File storage backend - stub implementation.
Definition at line 87 of file storage_backends.h.
Constructor & Destructor Documentation
file_storage_backend() [1/2]
monitoring_system::file_storage_backend::file_storage_backend () default
file_storage_backend() [2/2]
monitoring_system::file_storage_backend::file_storage_backend (const storage_config & config) inline explicit
Definition at line 90 of file storage_backends.h.
Member Function Documentation
flush()
result< bool > monitoring_system::file_storage_backend::flush () inline override virtual
Reimplemented from monitoring_system::kv_storage_backend.
Definition at line 106 of file storage_backends.h.
References monitoring_system::make_success().
Referenced by TEST_F().
remove()
bool monitoring_system::file_storage_backend::remove (const std::string & key) inline override virtual
Implements monitoring_system::kv_storage_backend.
Definition at line 102 of file storage_backends.h.
retrieve()
std::string monitoring_system::file_storage_backend::retrieve (const std::string & key) inline override virtual
Implements monitoring_system::kv_storage_backend.
Definition at line 97 of file storage_backends.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
store()
bool monitoring_system::file_storage_backend::store (const std::string & key, const std::string & value) inline override virtual
Implements monitoring_system::kv_storage_backend.
Definition at line 92 of file storage_backends.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/monitoring/storage/storage_backends.h