Messaging System: logger_module::logger_crash_safety Class Reference
logger_module::logger_crash_safety Class Reference
Logger crash safety manager.
#include <logger_crash_safety.h>
Classes
struct emergency_log_stats
Get emergency log statistics.
Public Member Functions
void initialize (logger_crash_safety_level level=logger_crash_safety_level::standard, const std::string &emergency_log_path="./emergency.log", uint32_t backup_interval_ms=5000)
Initialize crash safety for logger system.
void register_logger (const std::string &logger_name, std::function< void()> flush_callback, std::function< void(const std::string &)> backup_callback=nullptr)
Register a logger for crash protection.
void unregister_logger (const std::string &logger_name)
Unregister a logger from crash protection.
void emergency_log (const std::string &level, const std::string &message)
Write emergency log entry (signal-safe)
void set_emergency_log_path (const std::string &path)
Set emergency log file path.
void set_auto_backup (bool enable, uint32_t interval_ms=5000)
Enable/disable automatic backups.
void force_flush_all ()
Force immediate flush of all registered loggers.
void force_backup_all ()
Force immediate backup of all registered loggers.
bool is_handling_crash () const
Check if currently handling a crash.
void set_max_emergency_entries (size_t max_entries)
Set maximum emergency log entries to keep in memory.
emergency_log_stats get_stats () const
bool check_and_recover ()
Recovery check - detect and recover from previous crashes.
Static Public Member Functions
static logger_crash_safety & instance ()
Get the global logger crash safety instance.
Detailed Description
Logger crash safety manager.
Provides comprehensive crash safety for logging systems:
Emergency log flushing on crash
Backup file creation
Signal-safe logging
Log corruption prevention
Recovery mechanisms
Definition at line 53 of file logger_crash_safety.h.
Member Function Documentation
check_and_recover()
bool logger_module::logger_crash_safety::check_and_recover ()
Recovery check - detect and recover from previous crashes.
Returns
true if recovery actions were taken
emergency_log()
void logger_module::logger_crash_safety::emergency_log (const std::string & level, const std::string & message)
Write emergency log entry (signal-safe)
Parameters
level Log level as string
message Message to log
Referenced by on_logger_crash(), potentially_crashing_logging_task(), and simulate_disk_full().
force_backup_all()
void logger_module::logger_crash_safety::force_backup_all ()
Force immediate backup of all registered loggers.
force_flush_all()
void logger_module::logger_crash_safety::force_flush_all ()
Force immediate flush of all registered loggers.
get_stats()
emergency_log_stats logger_module::logger_crash_safety::get_stats () const
initialize()
void logger_module::logger_crash_safety::initialize (logger_crash_safety_level level = logger_crash_safety_level::standard, const std::string & emergency_log_path = "./emergency.log", uint32_t backup_interval_ms = 5000)
Initialize crash safety for logger system.
Parameters
level Safety level to configure
emergency_log_path Path for emergency crash logs
backup_interval_ms Backup creation interval
instance()
static logger_crash_safety & logger_module::logger_crash_safety::instance () static
Get the global logger crash safety instance.
Referenced by main(), on_logger_crash(), potentially_crashing_logging_task(), logger_module::scoped_logger_crash_protection::scoped_logger_crash_protection(), simulate_disk_full(), and logger_module::scoped_logger_crash_protection::~scoped_logger_crash_protection().
is_handling_crash()
bool logger_module::logger_crash_safety::is_handling_crash () const
Check if currently handling a crash.
Returns
true if handling crash
register_logger()
void logger_module::logger_crash_safety::register_logger (const std::string & logger_name, std::function< void()> flush_callback, std::function< void(const std::string &)> backup_callback = nullptr)
Register a logger for crash protection.
Parameters
logger_name Unique name for the logger
flush_callback Function to flush logger on crash
backup_callback Function to create backup
Referenced by logger_module::scoped_logger_crash_protection::scoped_logger_crash_protection().
set_auto_backup()
void logger_module::logger_crash_safety::set_auto_backup (bool enable, uint32_t interval_ms = 5000)
Enable/disable automatic backups.
Parameters
enable Whether to create automatic backups
interval_ms Backup interval in milliseconds
set_emergency_log_path()
void logger_module::logger_crash_safety::set_emergency_log_path (const std::string & path)
Set emergency log file path.
Parameters
path Path to emergency log file
set_max_emergency_entries()
void logger_module::logger_crash_safety::set_max_emergency_entries (size_t max_entries)
Set maximum emergency log entries to keep in memory.
Parameters
max_entries Maximum number of entries
unregister_logger()
void logger_module::logger_crash_safety::unregister_logger (const std::string & logger_name)
Unregister a logger from crash protection.
Parameters
logger_name Name of logger to unregister
Referenced by logger_module::scoped_logger_crash_protection::~scoped_logger_crash_protection().
The documentation for this class was generated from the following file:
libraries/logger_system/sources/interfaces/logger_crash_safety.h