# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _container
else:
    import _container

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


value_types_null_value = _container.value_types_null_value
value_types_bool_value = _container.value_types_bool_value
value_types_short_value = _container.value_types_short_value
value_types_ushort_value = _container.value_types_ushort_value
value_types_int_value = _container.value_types_int_value
value_types_uint_value = _container.value_types_uint_value
value_types_long_value = _container.value_types_long_value
value_types_ulong_value = _container.value_types_ulong_value
value_types_llong_value = _container.value_types_llong_value
value_types_ullong_value = _container.value_types_ullong_value
value_types_float_value = _container.value_types_float_value
value_types_double_value = _container.value_types_double_value
value_types_bytes_value = _container.value_types_bytes_value
value_types_string_value = _container.value_types_string_value
value_types_container_value = _container.value_types_container_value

def convert_value_type(*args):
    return _container.convert_value_type(*args)
class value(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.value_swiginit(self, _container.new_value(*args))
    __swig_destroy__ = _container.delete_value

    def get_ptr(self):
        return _container.value_get_ptr(self)

    def set_parent(self, parent):
        return _container.value_set_parent(self, parent)

    def set_data(self, *args):
        return _container.value_set_data(self, *args)

    def name(self):
        return _container.value_name(self)

    def type(self):
        return _container.value_type(self)

    def data(self):
        return _container.value_data(self)

    def size(self):
        return _container.value_size(self)

    def parent(self):
        return _container.value_parent(self)

    def child_count(self):
        return _container.value_child_count(self)

    def children(self, only_container=False):
        return _container.value_children(self, only_container)

    def add(self, *args):
        return _container.value_add(self, *args)

    def remove(self, *args):
        return _container.value_remove(self, *args)

    def remove_all(self):
        return _container.value_remove_all(self)

    def value_array(self, key):
        return _container.value_value_array(self, key)

    def to_bytes(self):
        return _container.value_to_bytes(self)

    def is_null(self):
        return _container.value_is_null(self)

    def is_bytes(self):
        return _container.value_is_bytes(self)

    def is_boolean(self):
        return _container.value_is_boolean(self)

    def is_numeric(self):
        return _container.value_is_numeric(self)

    def is_string(self):
        return _container.value_is_string(self)

    def is_container(self):
        return _container.value_is_container(self)

    def to_xml(self):
        return _container.value_to_xml(self)

    def to_json(self):
        return _container.value_to_json(self)

    def serialize(self):
        return _container.value_serialize(self)

    def to_boolean(self):
        return _container.value_to_boolean(self)

    def to_short(self):
        return _container.value_to_short(self)

    def to_ushort(self):
        return _container.value_to_ushort(self)

    def to_int(self):
        return _container.value_to_int(self)

    def to_uint(self):
        return _container.value_to_uint(self)

    def to_long(self):
        return _container.value_to_long(self)

    def to_ulong(self):
        return _container.value_to_ulong(self)

    def to_llong(self):
        return _container.value_to_llong(self)

    def to_ullong(self):
        return _container.value_to_ullong(self)

    def to_float(self):
        return _container.value_to_float(self)

    def to_double(self):
        return _container.value_to_double(self)

    def to_string(self, original=True):
        return _container.value_to_string(self, original)

# Register value in _container:
_container.value_swigregister(value)

class bool_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.bool_value_swiginit(self, _container.new_bool_value(*args))
    __swig_destroy__ = _container.delete_bool_value

    def to_boolean(self):
        return _container.bool_value_to_boolean(self)

    def to_string(self, original=True):
        return _container.bool_value_to_string(self, original)

# Register bool_value in _container:
_container.bool_value_swigregister(bool_value)

class bytes_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.bytes_value_swiginit(self, _container.new_bytes_value(*args))
    __swig_destroy__ = _container.delete_bytes_value

    def to_string(self, original=True):
        return _container.bytes_value_to_string(self, original)

# Register bytes_value in _container:
_container.bytes_value_swigregister(bytes_value)

class double_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.double_value_swiginit(self, _container.new_double_value(*args))
    __swig_destroy__ = _container.delete_double_value

    def to_double(self):
        return _container.double_value_to_double(self)

    def to_string(self, original=True):
        return _container.double_value_to_string(self, original)

# Register double_value in _container:
_container.double_value_swigregister(double_value)

class float_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.float_value_swiginit(self, _container.new_float_value(*args))
    __swig_destroy__ = _container.delete_float_value

    def to_float(self):
        return _container.float_value_to_float(self)

    def to_string(self, original=True):
        return _container.float_value_to_string(self, original)

# Register float_value in _container:
_container.float_value_swigregister(float_value)

class int_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.int_value_swiginit(self, _container.new_int_value(*args))
    __swig_destroy__ = _container.delete_int_value

    def to_int(self):
        return _container.int_value_to_int(self)

    def to_string(self, original=True):
        return _container.int_value_to_string(self, original)

# Register int_value in _container:
_container.int_value_swigregister(int_value)

class long_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.long_value_swiginit(self, _container.new_long_value(*args))
    __swig_destroy__ = _container.delete_long_value

    def to_long(self):
        return _container.long_value_to_long(self)

    def to_string(self, original=True):
        return _container.long_value_to_string(self, original)

# Register long_value in _container:
_container.long_value_swigregister(long_value)

class ulong_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.ulong_value_swiginit(self, _container.new_ulong_value(*args))
    __swig_destroy__ = _container.delete_ulong_value

    def to_ulong(self):
        return _container.ulong_value_to_ulong(self)

    def to_string(self, original=True):
        return _container.ulong_value_to_string(self, original)

# Register ulong_value in _container:
_container.ulong_value_swigregister(ulong_value)

class llong_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.llong_value_swiginit(self, _container.new_llong_value(*args))
    __swig_destroy__ = _container.delete_llong_value

    def to_llong(self):
        return _container.llong_value_to_llong(self)

    def to_string(self, original=True):
        return _container.llong_value_to_string(self, original)

# Register llong_value in _container:
_container.llong_value_swigregister(llong_value)

class ullong_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.ullong_value_swiginit(self, _container.new_ullong_value(*args))
    __swig_destroy__ = _container.delete_ullong_value

    def to_ullong(self):
        return _container.ullong_value_to_ullong(self)

    def to_string(self, original=True):
        return _container.ullong_value_to_string(self, original)

# Register ullong_value in _container:
_container.ullong_value_swigregister(ullong_value)

class short_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.short_value_swiginit(self, _container.new_short_value(*args))
    __swig_destroy__ = _container.delete_short_value

    def to_short(self):
        return _container.short_value_to_short(self)

    def to_string(self, original=True):
        return _container.short_value_to_string(self, original)

# Register short_value in _container:
_container.short_value_swigregister(short_value)

class string_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.string_value_swiginit(self, _container.new_string_value(*args))
    __swig_destroy__ = _container.delete_string_value

    def to_string(self, original=True):
        return _container.string_value_to_string(self, original)

# Register string_value in _container:
_container.string_value_swigregister(string_value)

class uint_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.uint_value_swiginit(self, _container.new_uint_value(*args))
    __swig_destroy__ = _container.delete_uint_value

    def to_uint(self):
        return _container.uint_value_to_uint(self)

    def to_string(self, original=True):
        return _container.uint_value_to_string(self, original)

# Register uint_value in _container:
_container.uint_value_swigregister(uint_value)

class ushort_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.ushort_value_swiginit(self, _container.new_ushort_value(*args))
    __swig_destroy__ = _container.delete_ushort_value

    def to_ushort(self):
        return _container.ushort_value_to_ushort(self)

    def to_string(self, original=True):
        return _container.ushort_value_to_string(self, original)

# Register ushort_value in _container:
_container.ushort_value_swigregister(ushort_value)

class container_value(value):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.container_value_swiginit(self, _container.new_container_value(*args))
    __swig_destroy__ = _container.delete_container_value

    def add(self, *args):
        return _container.container_value_add(self, *args)

    def remove(self, *args):
        return _container.container_value_remove(self, *args)

    def remove_all(self):
        return _container.container_value_remove_all(self)

    def to_long(self):
        return _container.container_value_to_long(self)

    def to_string(self, original=True):
        return _container.container_value_to_string(self, original)

# Register container_value in _container:
_container.container_value_swigregister(container_value)

class value_container(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _container.value_container_swiginit(self, _container.new_value_container(*args))
    __swig_destroy__ = _container.delete_value_container

    def get_ptr(self):
        return _container.value_container_get_ptr(self)

    def set_source(self, source_id, source_sub_id):
        return _container.value_container_set_source(self, source_id, source_sub_id)

    def set_target(self, *args):
        return _container.value_container_set_target(self, *args)

    def set_message_type(self, message_type):
        return _container.value_container_set_message_type(self, message_type)

    def set_units(self, target_values):
        return _container.value_container_set_units(self, target_values)

    def swap_header(self):
        return _container.value_container_swap_header(self)

    def clear_value(self):
        return _container.value_container_clear_value(self)

    def copy(self, containing_values=True):
        return _container.value_container_copy(self, containing_values)

    def source_id(self):
        return _container.value_container_source_id(self)

    def source_sub_id(self):
        return _container.value_container_source_sub_id(self)

    def target_id(self):
        return _container.value_container_target_id(self)

    def target_sub_id(self):
        return _container.value_container_target_sub_id(self)

    def message_type(self):
        return _container.value_container_message_type(self)

    def add(self, *args):
        return _container.value_container_add(self, *args)

    def remove(self, *args):
        return _container.value_container_remove(self, *args)

    def value_array(self, target_name):
        return _container.value_container_value_array(self, target_name)

    def get_value(self, target_name, index=0):
        return _container.value_container_get_value(self, target_name, index)

    def initialize(self):
        return _container.value_container_initialize(self)

    def serialize(self):
        return _container.value_container_serialize(self)

    def serialize_array(self):
        return _container.value_container_serialize_array(self)

    def deserialize(self, *args):
        return _container.value_container_deserialize(self, *args)

    def to_xml(self):
        return _container.value_container_to_xml(self)

    def to_json(self):
        return _container.value_container_to_json(self)

    def datas(self):
        return _container.value_container_datas(self)

    def load_packet(self, file_path):
        return _container.value_container_load_packet(self, file_path)

    def save_packet(self, file_path):
        return _container.value_container_save_packet(self, file_path)

# Register value_container in _container:
_container.value_container_swigregister(value_container)



