Messaging System: network_system::integration::basic_logger::impl Class Reference
network_system::integration::basic_logger::impl Class Reference
Public Member Functions
impl (log_level min_level)
void log (log_level level, const std::string &message)
void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function)
bool is_level_enabled (log_level level) const
void flush ()
void set_min_level (log_level level)
log_level get_min_level () const
Detailed Description
Definition at line 86 of file logger_integration.cpp.
Constructor & Destructor Documentation
impl()
network_system::integration::basic_logger::impl::impl (log_level min_level) inline explicit
Definition at line 88 of file logger_integration.cpp.
Member Function Documentation
flush()
void network_system::integration::basic_logger::impl::flush () inline
Definition at line 124 of file logger_integration.cpp.
get_min_level()
log_level network_system::integration::basic_logger::impl::get_min_level () const inline
Definition at line 133 of file logger_integration.cpp.
is_level_enabled()
bool network_system::integration::basic_logger::impl::is_level_enabled (log_level level) const inline
Definition at line 120 of file logger_integration.cpp.
log() [1/2]
void network_system::integration::basic_logger::impl::log (log_level level, const std::string & message) inline
Definition at line 90 of file logger_integration.cpp.
References network_system::integration::get_timestamp(), and network_system::integration::level_to_string().
log() [2/2]
void network_system::integration::basic_logger::impl::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) inline
Definition at line 104 of file logger_integration.cpp.
References network_system::integration::get_timestamp(), and network_system::integration::level_to_string().
set_min_level()
void network_system::integration::basic_logger::impl::set_min_level (log_level level) inline
Definition at line 129 of file logger_integration.cpp.
The documentation for this class was generated from the following file:
libraries/network_system/src/integration/logger_integration.cpp