Messaging System: utility_module::formatter Class Reference
utility_module::formatter Class Reference
Provides convenience methods for string formatting using either C++20 <format> or {fmt} library.
#include <formatter.h>
Static Public Member Functions
template<typename... Args>
static std::string format (const std::string &format_str, Args &&... args)
static std::string format (const std::string &format_str)
template<typename OutputIt , typename... Args>
static void format_to (OutputIt out, const std::string &format_str, Args &&... args)
template<typename... FormatArgs>
static auto format (const char *formats, const FormatArgs &... args) -> std::string
Formats a narrow-character string with the given arguments.
template<typename... FormatArgs>
static auto format (const wchar_t *formats, const FormatArgs &... args) -> std::wstring
Formats a wide-character string with the given arguments.
template<typename OutputIt , typename... FormatArgs>
static auto format_to (OutputIt out, const char *formats, const FormatArgs &... args) -> OutputIt
Formats a narrow-character string directly to an output iterator.
template<typename OutputIt , typename... FormatArgs>
static auto format_to (OutputIt out, const wchar_t *formats, const FormatArgs &... args) -> OutputIt
Formats a wide-character string directly to an output iterator.
template<typename... FormatArgs>
static auto format (const char *formats, const FormatArgs &... args) -> std::string
Formats a narrow-character string with the given arguments.
template<typename... FormatArgs>
static auto format (const wchar_t *formats, const FormatArgs &... args) -> std::wstring
Formats a wide-character string with the given arguments.
template<typename OutputIt , typename... FormatArgs>
static auto format_to (OutputIt out, const char *formats, const FormatArgs &... args) -> OutputIt
Formats a narrow-character string directly to an output iterator.
template<typename OutputIt , typename... FormatArgs>
static auto format_to (OutputIt out, const wchar_t *formats, const FormatArgs &... args) -> OutputIt
Formats a wide-character string directly to an output iterator.
template<typename... FormatArgs>
static auto format (const char *formats, const FormatArgs &... args) -> std::string
Formats a narrow-character string with the given arguments.
template<typename... FormatArgs>
static auto format (const wchar_t *formats, const FormatArgs &... args) -> std::wstring
Formats a wide-character string with the given arguments.
template<typename OutputIt , typename... FormatArgs>
static auto format_to (OutputIt out, const char *formats, const FormatArgs &... args) -> OutputIt
Formats a narrow-character string directly to an output iterator.
template<typename OutputIt , typename... FormatArgs>
static auto format_to (OutputIt out, const wchar_t *formats, const FormatArgs &... args) -> OutputIt
Formats a wide-character string directly to an output iterator.
Detailed Description
Provides convenience methods for string formatting using either C++20 <format> or {fmt} library.
The formatter class offers static functions to format strings (both narrow and wide) into a std::string / std::wstring, or directly to an output iterator. Which underlying implementation is used depends on whether USE_STD_FORMAT is defined.
Example
// Basic usage:
std::string result = formatter::format("Hello, {}", "World");
// Writing directly to a buffer:
std::array<char, 50> buffer;
auto it = formatter::format_to(buffer.begin(), "Number: {}", 42);
// 'it' now points to the end of the written text
The formatter class offers static functions to format strings (both narrow and wide) into a std::string / std::wstring, or directly to an output iterator. Which underlying implementation is used depends on whether USE_STD_FORMAT is defined.
Example
// Basic usage:
std::string result = formatter::format("Hello, {}", "World");
// Writing directly to a buffer:
std::array<char, 50> buffer;
auto it = formatter::format_to(buffer.begin(), "Number: {}", 42);
// 'it' now points to the end of the written text
The formatter class offers static functions to format strings (both narrow and wide) into a std::string / std::wstring, or directly to an output iterator. Which underlying implementation is used depends on whether USE_STD_FORMAT is defined.
Example
// Basic usage:
std::string result = formatter::format("Hello, {}", "World");
// Writing directly to a buffer:
std::array<char, 50> buffer;
auto it = formatter::format_to(buffer.begin(), "Number: {}", 42);
// 'it' now points to the end of the written text
Definition at line 19 of file formatter.h.
Member Function Documentation
format() [1/8]
template<typename... FormatArgs> static auto utility_module::formatter::format (const char * formats, const FormatArgs &... args) -> std::string inline static
Formats a narrow-character string with the given arguments.
Template Parameters
FormatArgs Parameter pack of argument types.
Parameters
formats A format string (e.g. "Name: {}, Age: {}").
args The arguments to substitute into formats.
Returns
A std::string containing the formatted result.
If USE_STD_FORMAT is defined, uses C++20's std::format API. Otherwise, falls back to the {fmt} library.
Definition at line 176 of file formatter.h.
format() [2/8]
template<typename... FormatArgs> static auto utility_module::formatter::format (const char * formats, const FormatArgs &... args) -> std::string inline static
Formats a narrow-character string with the given arguments.
Template Parameters
FormatArgs Parameter pack of argument types.
Parameters
formats A format string (e.g. "Name: {}, Age: {}").
args The arguments to substitute into formats.
Returns
A std::string containing the formatted result.
If USE_STD_FORMAT is defined, uses C++20's std::format API. Otherwise, falls back to the {fmt} library.
Definition at line 176 of file formatter.h.
format() [3/8]
template<typename... FormatArgs> static auto utility_module::formatter::format (const char * formats, const FormatArgs &... args) -> std::string inline static
Formats a narrow-character string with the given arguments.
Template Parameters
FormatArgs Parameter pack of argument types.
Parameters
formats A format string (e.g. "Name: {}, Age: {}").
args The arguments to substitute into formats.
Returns
A std::string containing the formatted result.
If USE_STD_FORMAT is defined, uses C++20's std::format API. Otherwise, falls back to the {fmt} library.
Definition at line 176 of file formatter.h.
format() [4/8]
static std::string utility_module::formatter::format (const std::string & format_str) inline static
Definition at line 39 of file formatter.h.
format() [5/8]
template<typename... Args> static std::string utility_module::formatter::format (const std::string & format_str, Args &&... args) inline static
Definition at line 23 of file formatter.h.
Referenced by BM_MaximumThreads(), BM_MemoryPressure(), BM_QueueOverflow(), BM_RapidStartStop(), BM_ThunderingHerd(), create_default(), create_default(), create_default(), create_default(), create_priority_default(), thread_pool_module::thread_worker::do_work(), std::formatter< TaskType >::format(), format_to(), format_to(), initialize_logger(), main(), main(), thread_pool_module::thread_pool::stop(), store_job(), store_job(), store_job(), thread_module::adaptive_job_queue::to_string(), thread_module::lockfree_job_queue::to_string(), container_module::container_value::to_string(), thread_module::thread_base::to_string(), thread_module::job::to_string(), thread_module::job_queue::to_string(), sample_monitoring::update_system_metrics(), sample_monitoring::update_thread_pool_metrics(), and sample_monitoring::update_worker_metrics().
format() [6/8]
template<typename... FormatArgs> static auto utility_module::formatter::format (const wchar_t * formats, const FormatArgs &... args) -> std::wstring inline static
Formats a wide-character string with the given arguments.
Template Parameters
FormatArgs Parameter pack of argument types.
Parameters
formats A wide format string (e.g. L"Count: {}, Value: {}").
args The arguments to substitute into formats.
Returns
A std::wstring containing the formatted result.
Definition at line 263 of file formatter.h.
format() [7/8]
template<typename... FormatArgs> static auto utility_module::formatter::format (const wchar_t * formats, const FormatArgs &... args) -> std::wstring inline static
Formats a wide-character string with the given arguments.
Template Parameters
FormatArgs Parameter pack of argument types.
Parameters
formats A wide format string (e.g. L"Count: {}, Value: {}").
args The arguments to substitute into formats.
Returns
A std::wstring containing the formatted result.
Definition at line 263 of file formatter.h.
format() [8/8]
template<typename... FormatArgs> static auto utility_module::formatter::format (const wchar_t * formats, const FormatArgs &... args) -> std::wstring inline static
Formats a wide-character string with the given arguments.
Template Parameters
FormatArgs Parameter pack of argument types.
Parameters
formats A wide format string (e.g. L"Count: {}, Value: {}").
args The arguments to substitute into formats.
Returns
A std::wstring containing the formatted result.
Definition at line 263 of file formatter.h.
format_to() [1/7]
template<typename OutputIt , typename... FormatArgs> static auto utility_module::formatter::format_to (OutputIt out, const char * formats, const FormatArgs &... args) -> OutputIt inline static
Formats a narrow-character string directly to an output iterator.
Template Parameters
OutputIt The type of the output iterator (e.g. a back_inserter for a container).
FormatArgs Parameter pack of argument types.
Parameters
out The output iterator where formatted text will be written.
formats The narrow format string.
args The arguments to substitute into formats.
Returns
The output iterator advanced to the end of the written text.
This method is useful when writing to a buffer, a container, or custom iterators.
Definition at line 287 of file formatter.h.
References format().
format_to() [2/7]
template<typename OutputIt , typename... FormatArgs> static auto utility_module::formatter::format_to (OutputIt out, const char * formats, const FormatArgs &... args) -> OutputIt inline static
Formats a narrow-character string directly to an output iterator.
Template Parameters
OutputIt The type of the output iterator (e.g. a back_inserter for a container).
FormatArgs Parameter pack of argument types.
Parameters
out The output iterator where formatted text will be written.
formats The narrow format string.
args The arguments to substitute into formats.
Returns
The output iterator advanced to the end of the written text.
This method is useful when writing to a buffer, a container, or custom iterators.
Definition at line 287 of file formatter.h.
References format().
format_to() [3/7]
template<typename OutputIt , typename... FormatArgs> static auto utility_module::formatter::format_to (OutputIt out, const char * formats, const FormatArgs &... args) -> OutputIt inline static
Formats a narrow-character string directly to an output iterator.
Template Parameters
OutputIt The type of the output iterator (e.g. a back_inserter for a container).
FormatArgs Parameter pack of argument types.
Parameters
out The output iterator where formatted text will be written.
formats The narrow format string.
args The arguments to substitute into formats.
Returns
The output iterator advanced to the end of the written text.
This method is useful when writing to a buffer, a container, or custom iterators.
Definition at line 287 of file formatter.h.
References format().
format_to() [4/7]
template<typename OutputIt , typename... Args> static void utility_module::formatter::format_to (OutputIt out, const std::string & format_str, Args &&... args) inline static
Definition at line 45 of file formatter.h.
Referenced by container_module::value_container::datas(), utility_module::convert_string::replace2(), container_module::value::serialize(), container_module::value_container::serialize(), container_module::value::to_json(), container_module::variant_value::to_json(), container_module::value_container::to_json(), thread_pool_module::thread_pool::to_string(), container_module::value::to_xml(), and container_module::value_container::to_xml().
format_to() [5/7]
template<typename OutputIt , typename... FormatArgs> static auto utility_module::formatter::format_to (OutputIt out, const wchar_t * formats, const FormatArgs &... args) -> OutputIt inline static
Formats a wide-character string directly to an output iterator.
Template Parameters
OutputIt The type of the output iterator (e.g. a back_inserter for a wstring).
FormatArgs Parameter pack of argument types.
Parameters
out The output iterator where formatted text will be written.
formats The wide format string.
args The arguments to substitute into formats.
Returns
The output iterator advanced to the end of the written text.
Definition at line 309 of file formatter.h.
References format().
format_to() [6/7]
template<typename OutputIt , typename... FormatArgs> static auto utility_module::formatter::format_to (OutputIt out, const wchar_t * formats, const FormatArgs &... args) -> OutputIt inline static
Formats a wide-character string directly to an output iterator.
Template Parameters
OutputIt The type of the output iterator (e.g. a back_inserter for a wstring).
FormatArgs Parameter pack of argument types.
Parameters
out The output iterator where formatted text will be written.
formats The wide format string.
args The arguments to substitute into formats.
Returns
The output iterator advanced to the end of the written text.
Definition at line 309 of file formatter.h.
References format().
format_to() [7/7]
template<typename OutputIt , typename... FormatArgs> static auto utility_module::formatter::format_to (OutputIt out, const wchar_t * formats, const FormatArgs &... args) -> OutputIt inline static
Formats a wide-character string directly to an output iterator.
Template Parameters
OutputIt The type of the output iterator (e.g. a back_inserter for a wstring).
FormatArgs Parameter pack of argument types.
Parameters
out The output iterator where formatted text will be written.
formats The wide format string.
args The arguments to substitute into formats.
Returns
The output iterator advanced to the end of the written text.
Definition at line 309 of file formatter.h.
References format().
The documentation for this class was generated from the following files:
libraries/container_system/utilities/core/formatter.h
libraries/thread_system/modular_structure/core/include/thread_system_core/utilities/core/formatter.h
libraries/thread_system/modular_structure/core/src/utilities/core/formatter.h
libraries/thread_system/sources/utilities/core/formatter.h