Messaging System: libraries/thread_system/benchmarks/thread_pool_benchmarks/stress_test_benchmark.cpp File Reference
stress_test_benchmark.cpp File Reference
Stress tests and edge case benchmarks for Thread System.
#include <benchmark/benchmark.h>
#include <chrono>
#include <vector>
#include <atomic>
#include <random>
#include <thread>
#include <future>
#include <limits>
#include <iomanip>
#include <algorithm>
#include <numeric>
#include "../../sources/thread_pool/core/thread_pool.h"
#include "../../sources/thread_pool/workers/thread_worker.h"
#include "../../sources/typed_thread_pool/pool/typed_thread_pool.h"
#include "../../sources/typed_thread_pool/scheduling/typed_thread_worker.h"
#include "../../sources/typed_thread_pool/jobs/callback_typed_job.h"
#include "../../sources/utilities/core/formatter.h"
Enumerations
enum class Type {
Highest = 1 , High = 10 , Medium = 50 , Low = 100 ,
Lowest = 1000 , Highest = 1 , High = 10 , Medium = 50 ,
Low = 100 , Lowest = 1000
}
Functions
auto create_default (const uint16_t &worker_counts) -> std::tuple< std::shared_ptr< kcenon::thread::thread_pool >, std::optional< std::string > >
template<typename Type >
auto create_priority_default (const uint16_t &worker_counts) -> std::tuple< std::shared_ptr< typed_kcenon::thread::typed_thread_pool_t< Type > >, std::optional< std::string > >
static void BM_MaximumThreads (benchmark::State &state)
Benchmark maximum thread creation.
Arg (100) -> Arg(500) ->Arg(1000) ->Arg(2000) ->Unit(benchmark::kMillisecond)
static void BM_QueueOverflow (benchmark::State &state)
Benchmark queue overflow handling.
Arg (10000) -> Arg(100000) ->Arg(1000000) ->Unit(benchmark::kMillisecond)
static void BM_RapidStartStop (benchmark::State &state)
Benchmark rapid start/stop cycles.
static void BM_ExceptionHandling (benchmark::State &state)
Benchmark exception handling under load.
Arg (1000) -> Arg(10000) ->Arg(100000) ->Unit(benchmark::kMillisecond)
static void BM_MemoryPressure (benchmark::State &state)
Benchmark memory pressure with large captures.
Args ({1, 100}) -> Args({10, 100}) ->Args({50, 20}) ->Args({100, 10}) ->Unit(benchmark::kMillisecond)
static void BM_PriorityStarvation (benchmark::State &state)
Benchmark priority starvation.
static void BM_ThunderingHerd (benchmark::State &state)
Benchmark thundering herd problem.
static void BM_CascadingFailures (benchmark::State &state)
Benchmark cascading failures.
Args ({100, 10}) -> Args({50, 20}) ->Unit(benchmark::kMillisecond)
BENCHMARK_MAIN ()
Detailed Description
Stress tests and edge case benchmarks for Thread System.
Tests extreme conditions:
Maximum load scenarios
Resource exhaustion
Error recovery
Edge cases
Definition in file stress_test_benchmark.cpp.
Enumeration Type Documentation
Type
enum class Type strong
Enumerator
Highest
High
Medium
Low
Lowest
Highest
High
Medium
Low
Lowest
Definition at line 121 of file stress_test_benchmark.cpp.
Function Documentation
Arg() [1/3]
Arg (100) -> Arg(500) ->Arg(1000) ->Arg(2000) ->Unit(benchmark::kMillisecond)
Arg() [2/3]
Arg (1000) -> Arg(10000) ->Arg(100000) ->Unit(benchmark::kMillisecond)
Arg() [3/3]
Arg (10000) -> Arg(100000) ->Arg(1000000) ->Unit(benchmark::kMillisecond)
Args() [1/2]
Args ({1, 100}) -> Args({10, 100}) ->Args({50, 20}) ->Args({100, 10}) ->Unit(benchmark::kMillisecond)
Args() [2/2]
Args ({100, 10}) -> Args({50, 20}) ->Unit(benchmark::kMillisecond)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_CascadingFailures()
static void BM_CascadingFailures (benchmark::State & state) static
Benchmark cascading failures.
Definition at line 580 of file stress_test_benchmark.cpp.
References create_default().
BM_ExceptionHandling()
static void BM_ExceptionHandling (benchmark::State & state) static
Benchmark exception handling under load.
Definition at line 306 of file stress_test_benchmark.cpp.
References create_default().
BM_MaximumThreads()
static void BM_MaximumThreads (benchmark::State & state) static
Benchmark maximum thread creation.
Definition at line 142 of file stress_test_benchmark.cpp.
References create_default(), kcenon::thread::utils::formatter::format(), kcenon::thread::result< T >::has_value(), and kcenon::thread::result< T >::value().
BM_MemoryPressure()
static void BM_MemoryPressure (benchmark::State & state) static
Benchmark memory pressure with large captures.
Definition at line 362 of file stress_test_benchmark.cpp.
References create_default(), and kcenon::thread::utils::formatter::format().
BM_PriorityStarvation()
static void BM_PriorityStarvation (benchmark::State & state) static
Benchmark priority starvation.
Definition at line 418 of file stress_test_benchmark.cpp.
References High, Highest, Low, Lowest, and Medium.
BM_QueueOverflow()
static void BM_QueueOverflow (benchmark::State & state) static
Benchmark queue overflow handling.
Definition at line 192 of file stress_test_benchmark.cpp.
References create_default(), and kcenon::thread::utils::formatter::format().
BM_RapidStartStop()
static void BM_RapidStartStop (benchmark::State & state) static
Benchmark rapid start/stop cycles.
Definition at line 242 of file stress_test_benchmark.cpp.
References create_default(), and kcenon::thread::utils::formatter::format().
BM_ThunderingHerd()
static void BM_ThunderingHerd (benchmark::State & state) static
Benchmark thundering herd problem.
Definition at line 498 of file stress_test_benchmark.cpp.
References create_default(), and kcenon::thread::utils::formatter::format().
create_default()
auto create_default (const uint16_t & worker_counts) -> std::tuple<std::shared_ptr<kcenon::thread::thread_pool>, std::optional<std::string>>
Definition at line 62 of file stress_test_benchmark.cpp.
References kcenon::thread::utils::formatter::format().
Referenced by BM_CascadingFailures(), BM_ExceptionHandling(), BM_MaximumThreads(), BM_MemoryPressure(), BM_QueueOverflow(), BM_RapidStartStop(), and BM_ThunderingHerd().
create_priority_default()
template<typename Type > auto create_priority_default (const uint16_t & worker_counts) -> std::tuple<std::shared_ptr<typed_kcenon::thread::typed_thread_pool_t<Type>>, std::optional<std::string>>
Definition at line 90 of file stress_test_benchmark.cpp.
References kcenon::thread::utils::formatter::format().