Messaging System: thread_module::result< void > Class Reference
thread_module::result< void > Class Reference
Specialization of result for void.
#include <error_handling.h>
Public Types
using value_type = void
using error_type = error
using value_type = void
using error_type = error
using value_type = void
using error_type = error
Public Member Functions
result ()
Constructs a successful void result.
result (const result_void &r)
Constructs a void result from a result_void.
result (error err)
Constructs a result with an error.
operator bool () const noexcept
Checks if the result is successful.
bool has_value () const noexcept
Checks if the result is successful.
error & get_error () &
Gets the error.
const error & get_error () const &
Gets the error.
error && get_error () &&
Gets the error.
void value_or_throw () const
Throws an exception if the result contains an error.
template<typename Fn >
auto map (Fn &&fn) const -> result< std::invoke_result_t< Fn > >
Maps the result to another type using a function.
template<typename Fn >
auto and_then (Fn &&fn) const -> std::invoke_result_t< Fn >
Maps the result to another type using a function that returns a result.
result ()
Constructs a successful void result.
result (const result_void &r)
Constructs a void result from a result_void.
result (error err)
Constructs a result with an error.
operator bool () const noexcept
Checks if the result is successful.
bool has_value () const noexcept
Checks if the result is successful.
error & get_error () &
Gets the error.
const error & get_error () const &
Gets the error.
error && get_error () &&
Gets the error.
void value_or_throw () const
Throws an exception if the result contains an error.
template<typename Fn >
auto map (Fn &&fn) const -> result< std::invoke_result_t< Fn > >
Maps the result to another type using a function.
template<typename Fn >
auto and_then (Fn &&fn) const -> std::invoke_result_t< Fn >
Maps the result to another type using a function that returns a result.
result ()
Constructs a successful void result.
result (const result_void &r)
Constructs a void result from a result_void.
result (error err)
Constructs a result with an error.
operator bool () const noexcept
Checks if the result is successful.
bool has_value () const noexcept
Checks if the result is successful.
error & get_error () &
Gets the error.
const error & get_error () const &
Gets the error.
error && get_error () &&
Gets the error.
void value_or_throw () const
Throws an exception if the result contains an error.
template<typename Fn >
auto map (Fn &&fn) const -> result< std::invoke_result_t< Fn > >
Maps the result to another type using a function.
template<typename Fn >
auto and_then (Fn &&fn) const -> std::invoke_result_t< Fn >
Maps the result to another type using a function that returns a result.
Detailed Description
Specialization of result for void.
Definition at line 437 of file error_handling.h.
Member Typedef Documentation
error_type [1/3]
using thread_module::result< void >::error_type = error
Definition at line 440 of file error_handling.h.
error_type [2/3]
using thread_module::result< void >::error_type = error
Definition at line 440 of file error_handling.h.
error_type [3/3]
using thread_module::result< void >::error_type = error
Definition at line 440 of file error_handling.h.
value_type [1/3]
using thread_module::result< void >::value_type = void
Definition at line 439 of file error_handling.h.
value_type [2/3]
using thread_module::result< void >::value_type = void
Definition at line 439 of file error_handling.h.
value_type [3/3]
using thread_module::result< void >::value_type = void
Definition at line 439 of file error_handling.h.
Constructor & Destructor Documentation
result() [1/9]
thread_module::result< void >::result () inline
Constructs a successful void result.
Definition at line 445 of file error_handling.h.
result() [2/9]
thread_module::result< void >::result (const result_void & r) inline
Constructs a void result from a result_void.
Definition at line 450 of file error_handling.h.
result() [3/9]
thread_module::result< void >::result (error err) inline
Constructs a result with an error.
Parameters
err The error to store
Definition at line 456 of file error_handling.h.
result() [4/9]
thread_module::result< void >::result () inline
Constructs a successful void result.
Definition at line 445 of file error_handling.h.
result() [5/9]
thread_module::result< void >::result (const result_void & r) inline
Constructs a void result from a result_void.
Definition at line 450 of file error_handling.h.
result() [6/9]
thread_module::result< void >::result (error err) inline
Constructs a result with an error.
Parameters
err The error to store
Definition at line 456 of file error_handling.h.
result() [7/9]
thread_module::result< void >::result () inline
Constructs a successful void result.
Definition at line 445 of file error_handling.h.
result() [8/9]
thread_module::result< void >::result (const result_void & r) inline
Constructs a void result from a result_void.
Definition at line 450 of file error_handling.h.
result() [9/9]
thread_module::result< void >::result (error err) inline
Constructs a result with an error.
Parameters
err The error to store
Definition at line 456 of file error_handling.h.
Member Function Documentation
and_then() [1/3]
template<typename Fn > auto thread_module::result< void >::and_then (Fn && fn) const -> std::invoke_result_t<Fn> inline
Maps the result to another type using a function that returns a result.
Parameters
fn The function to apply if successful
Returns
A new result with the mapped value or the original error
Definition at line 541 of file error_handling.h.
and_then() [2/3]
template<typename Fn > auto thread_module::result< void >::and_then (Fn && fn) const -> std::invoke_result_t<Fn> inline
Maps the result to another type using a function that returns a result.
Parameters
fn The function to apply if successful
Returns
A new result with the mapped value or the original error
Definition at line 541 of file error_handling.h.
and_then() [3/3]
template<typename Fn > auto thread_module::result< void >::and_then (Fn && fn) const -> std::invoke_result_t<Fn> inline
Maps the result to another type using a function that returns a result.
Parameters
fn The function to apply if successful
Returns
A new result with the mapped value or the original error
Definition at line 541 of file error_handling.h.
get_error() [1/9]
error & thread_module::result< void >::get_error () & inline
Gets the error.
Returns
A reference to the contained error
Exceptions
std::runtime_error if the result is successful
Definition at line 479 of file error_handling.h.
get_error() [2/9]
error & thread_module::result< void >::get_error () & inline
Gets the error.
Returns
A reference to the contained error
Exceptions
std::runtime_error if the result is successful
Definition at line 479 of file error_handling.h.
get_error() [3/9]
error & thread_module::result< void >::get_error () & inline
Gets the error.
Returns
A reference to the contained error
Exceptions
std::runtime_error if the result is successful
Definition at line 479 of file error_handling.h.
get_error() [4/9]
error && thread_module::result< void >::get_error () && inline
Gets the error.
Returns
An rvalue reference to the contained error
Exceptions
std::runtime_error if the result is successful
Definition at line 503 of file error_handling.h.
get_error() [5/9]
error && thread_module::result< void >::get_error () && inline
Gets the error.
Returns
An rvalue reference to the contained error
Exceptions
std::runtime_error if the result is successful
Definition at line 503 of file error_handling.h.
get_error() [6/9]
error && thread_module::result< void >::get_error () && inline
Gets the error.
Returns
An rvalue reference to the contained error
Exceptions
std::runtime_error if the result is successful
Definition at line 503 of file error_handling.h.
get_error() [7/9]
const error & thread_module::result< void >::get_error () const & inline
Gets the error.
Returns
A const reference to the contained error
Exceptions
std::runtime_error if the result is successful
Definition at line 491 of file error_handling.h.
get_error() [8/9]
const error & thread_module::result< void >::get_error () const & inline
Gets the error.
Returns
A const reference to the contained error
Exceptions
std::runtime_error if the result is successful
Definition at line 491 of file error_handling.h.
get_error() [9/9]
const error & thread_module::result< void >::get_error () const & inline
Gets the error.
Returns
A const reference to the contained error
Exceptions
std::runtime_error if the result is successful
Definition at line 491 of file error_handling.h.
has_value() [1/3]
bool thread_module::result< void >::has_value () const inline noexcept
Checks if the result is successful.
Returns
true if the result is successful, false if it contains an error
Definition at line 470 of file error_handling.h.
has_value() [2/3]
bool thread_module::result< void >::has_value () const inline noexcept
Checks if the result is successful.
Returns
true if the result is successful, false if it contains an error
Definition at line 470 of file error_handling.h.
has_value() [3/3]
bool thread_module::result< void >::has_value () const inline noexcept
Checks if the result is successful.
Returns
true if the result is successful, false if it contains an error
Definition at line 470 of file error_handling.h.
map() [1/3]
template<typename Fn > auto thread_module::result< void >::map (Fn && fn) const -> result<std::invoke_result_t<Fn>> inline
Maps the result to another type using a function.
Parameters
fn The function to apply if successful
Returns
A new result with the mapped value or the original error
Definition at line 526 of file error_handling.h.
map() [2/3]
template<typename Fn > auto thread_module::result< void >::map (Fn && fn) const -> result<std::invoke_result_t<Fn>> inline
Maps the result to another type using a function.
Parameters
fn The function to apply if successful
Returns
A new result with the mapped value or the original error
Definition at line 526 of file error_handling.h.
map() [3/3]
template<typename Fn > auto thread_module::result< void >::map (Fn && fn) const -> result<std::invoke_result_t<Fn>> inline
Maps the result to another type using a function.
Parameters
fn The function to apply if successful
Returns
A new result with the mapped value or the original error
Definition at line 526 of file error_handling.h.
operator bool() [1/3]
thread_module::result< void >::operator bool () const inline explicit noexcept
Checks if the result is successful.
Returns
true if the result is successful, false if it contains an error
Definition at line 462 of file error_handling.h.
operator bool() [2/3]
thread_module::result< void >::operator bool () const inline explicit noexcept
Checks if the result is successful.
Returns
true if the result is successful, false if it contains an error
Definition at line 462 of file error_handling.h.
operator bool() [3/3]
thread_module::result< void >::operator bool () const inline explicit noexcept
Checks if the result is successful.
Returns
true if the result is successful, false if it contains an error
Definition at line 462 of file error_handling.h.
value_or_throw() [1/3]
void thread_module::result< void >::value_or_throw () const inline
Throws an exception if the result contains an error.
Exceptions
std::runtime_error with the error message if the result contains an error
Definition at line 514 of file error_handling.h.
References thread_module::error::to_string().
value_or_throw() [2/3]
void thread_module::result< void >::value_or_throw () const inline
Throws an exception if the result contains an error.
Exceptions
std::runtime_error with the error message if the result contains an error
Definition at line 514 of file error_handling.h.
References thread_module::error::to_string().
value_or_throw() [3/3]
void thread_module::result< void >::value_or_throw () const inline
Throws an exception if the result contains an error.
Exceptions
std::runtime_error with the error message if the result contains an error
Definition at line 514 of file error_handling.h.
References thread_module::error::to_string().
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/thread_base/sync/error_handling.h
libraries/thread_system/modular_structure/core/src/thread_base/sync/error_handling.h
libraries/thread_system/sources/thread_base/sync/error_handling.h