Messaging System: database::redis_manager Class Reference
database::redis_manager Class Reference
Manages Redis database operations.
#include <redis_manager.h>
Public Member Functions
redis_manager (void)
Default constructor.
virtual ~redis_manager (void)
Destructor.
database_types database_type (void) override
Returns the specific type of the database.
bool connect (const std::string &connect_string) override
Establishes a connection to a Redis database using the provided connection string.
bool create_query (const std::string &query_string) override
Creates/configures Redis settings using the provided command.
unsigned int insert_query (const std::string &query_string) override
Executes a SET operation on the connected Redis database.
unsigned int update_query (const std::string &query_string) override
Executes an UPDATE operation on the connected Redis database.
unsigned int delete_query (const std::string &query_string) override
Executes a DELETE operation on the connected Redis database.
database_result select_query (const std::string &query_string) override
Executes a GET operation on the connected Redis database and returns the resulting data.
bool execute_query (const std::string &query_string) override
Executes a general Redis command (raw Redis command).
bool disconnect (void) override
Closes the connection to the Redis database.
bool set_key (const std::string &key, const std::string &value, int ttl_seconds=0)
Sets a key-value pair in Redis.
std::string get_key (const std::string &key)
Gets the value for a key from Redis.
bool delete_key (const std::string &key)
Deletes a key from Redis.
bool exists_key (const std::string &key)
Checks if a key exists in Redis.
bool expire_key (const std::string &key, int ttl_seconds)
Sets expiration time for a key.
int list_push_left (const std::string &key, const std::string &value)
Pushes a value to the left of a Redis list.
int list_push_right (const std::string &key, const std::string &value)
Pushes a value to the right of a Redis list.
std::string list_pop_left (const std::string &key)
Pops a value from the left of a Redis list.
std::string list_pop_right (const std::string &key)
Pops a value from the right of a Redis list.
bool hash_set (const std::string &key, const std::string &field, const std::string &value)
Sets a field in a Redis hash.
std::string hash_get (const std::string &key, const std::string &field)
Gets a field value from a Redis hash.
bool set_add (const std::string &key, const std::string &member)
Adds a member to a Redis set.
bool set_remove (const std::string &key, const std::string &member)
Removes a member from a Redis set.
bool set_is_member (const std::string &key, const std::string &member)
Checks if a member exists in a Redis set.
Public Member Functions inherited from database::database_base
database_base (void)
Default constructor.
virtual ~database_base (void)
Virtual destructor.
Detailed Description
Manages Redis database operations.
This class provides an implementation of the database_base interface for Redis databases. It defines methods for connecting, key-value operations, and disconnecting from a Redis database using the hiredis library.
Definition at line 48 of file redis_manager.h.
Constructor & Destructor Documentation
redis_manager()
database::redis_manager::redis_manager (void)
Default constructor.
Definition at line 46 of file redis_manager.cpp.
~redis_manager()
database::redis_manager::~redis_manager (void) virtual
Destructor.
Definition at line 48 of file redis_manager.cpp.
References disconnect().
Member Function Documentation
connect()
bool database::redis_manager::connect (const std::string & connect_string) override virtual
Establishes a connection to a Redis database using the provided connection string.
Parameters
connect_string Redis connection string Format: "redis://host:port" or "host:port"
Returns
true if the connection is successfully established, false otherwise.
Implements database::database_base.
Definition at line 58 of file redis_manager.cpp.
create_query()
bool database::redis_manager::create_query (const std::string & query_string) override virtual
Creates/configures Redis settings using the provided command.
Parameters
query_string Redis configuration command
Returns
true if the command is successfully executed, false otherwise.
Implements database::database_base.
Definition at line 131 of file redis_manager.cpp.
database_type()
database_types database::redis_manager::database_type (void) override virtual
Returns the specific type of the database.
Returns
An enum value of type database_types indicating that this is a Redis database.
Implements database::database_base.
Definition at line 53 of file redis_manager.cpp.
References database::redis.
delete_key()
bool database::redis_manager::delete_key (const std::string & key)
Deletes a key from Redis.
Parameters
key The key to delete
Returns
true if key was deleted, false if key didn't exist
Definition at line 346 of file redis_manager.cpp.
References delete_query().
delete_query()
unsigned int database::redis_manager::delete_query (const std::string & query_string) override virtual
Executes a DELETE operation on the connected Redis database.
For Redis, this translates to DEL command.
Parameters
query_string DELETE operation (format: "key")
Returns
The number of keys deleted, or 0 if failed.
Implements database::database_base.
Definition at line 197 of file redis_manager.cpp.
Referenced by delete_key().
disconnect()
bool database::redis_manager::disconnect (void) override virtual
Closes the connection to the Redis database.
Returns
true if the disconnection is successful, false otherwise.
Implements database::database_base.
Definition at line 309 of file redis_manager.cpp.
Referenced by ~redis_manager().
execute_query()
bool database::redis_manager::execute_query (const std::string & query_string) override virtual
Executes a general Redis command (raw Redis command).
Parameters
query_string The Redis command string to execute.
Returns
true if the command executed successfully, false otherwise.
Implements database::database_base.
Definition at line 272 of file redis_manager.cpp.
exists_key()
bool database::redis_manager::exists_key (const std::string & key)
Checks if a key exists in Redis.
Parameters
key The key to check
Returns
true if key exists, false otherwise
Definition at line 351 of file redis_manager.cpp.
expire_key()
bool database::redis_manager::expire_key (const std::string & key, int ttl_seconds)
Sets expiration time for a key.
Parameters
key The key to set expiration for
ttl_seconds TTL in seconds
Returns
true if expiration was set, false otherwise
Definition at line 374 of file redis_manager.cpp.
Referenced by set_key().
get_key()
std::string database::redis_manager::get_key (const std::string & key)
Gets the value for a key from Redis.
Parameters
key The key to retrieve
Returns
The value associated with the key, empty string if not found
Definition at line 334 of file redis_manager.cpp.
References select_query().
hash_get()
std::string database::redis_manager::hash_get (const std::string & key, const std::string & field)
Gets a field value from a Redis hash.
Parameters
key The hash key
field The field name
Returns
The field value, empty string if not found
Definition at line 512 of file redis_manager.cpp.
hash_set()
bool database::redis_manager::hash_set (const std::string & key, const std::string & field, const std::string & value)
Sets a field in a Redis hash.
Parameters
key The hash key
field The field name
value The field value
Returns
true if field was set, false otherwise
Definition at line 489 of file redis_manager.cpp.
insert_query()
unsigned int database::redis_manager::insert_query (const std::string & query_string) override virtual
Executes a SET operation on the connected Redis database.
For Redis, this translates to setting key-value pairs.
Parameters
query_string SET operation (format: "key:value")
Returns
The number of keys set, or 0 if failed.
Implements database::database_base.
Definition at line 159 of file redis_manager.cpp.
Referenced by set_key(), and update_query().
list_pop_left()
std::string database::redis_manager::list_pop_left (const std::string & key)
Pops a value from the left of a Redis list.
Parameters
key The list key
Returns
The popped value, empty string if list is empty
Definition at line 443 of file redis_manager.cpp.
list_pop_right()
std::string database::redis_manager::list_pop_right (const std::string & key)
Pops a value from the right of a Redis list.
Parameters
key The list key
Returns
The popped value, empty string if list is empty
Definition at line 466 of file redis_manager.cpp.
list_push_left()
int database::redis_manager::list_push_left (const std::string & key, const std::string & value)
Pushes a value to the left of a Redis list.
Parameters
key The list key
value The value to push
Returns
Length of the list after operation
Definition at line 397 of file redis_manager.cpp.
list_push_right()
int database::redis_manager::list_push_right (const std::string & key, const std::string & value)
Pushes a value to the right of a Redis list.
Parameters
key The list key
value The value to push
Returns
Length of the list after operation
Definition at line 420 of file redis_manager.cpp.
select_query()
database_result database::redis_manager::select_query (const std::string & query_string) override virtual
Executes a GET operation on the connected Redis database and returns the resulting data.
Parameters
query_string GET operation (format: "key" or "pattern")
Returns
A database_result containing key-value pairs.
Implements database::database_base.
Definition at line 227 of file redis_manager.cpp.
Referenced by get_key().
set_add()
bool database::redis_manager::set_add (const std::string & key, const std::string & member)
Adds a member to a Redis set.
Parameters
key The set key
member The member to add
Returns
true if member was added, false if already exists
Definition at line 535 of file redis_manager.cpp.
set_is_member()
bool database::redis_manager::set_is_member (const std::string & key, const std::string & member)
Checks if a member exists in a Redis set.
Parameters
key The set key
member The member to check
Returns
true if member exists, false otherwise
Definition at line 581 of file redis_manager.cpp.
set_key()
bool database::redis_manager::set_key (const std::string & key, const std::string & value, int ttl_seconds = 0)
Sets a key-value pair in Redis.
Parameters
key The key to set
value The value to store
ttl_seconds Optional TTL in seconds (0 for no expiration)
Returns
true if operation successful, false otherwise
Definition at line 322 of file redis_manager.cpp.
References expire_key(), and insert_query().
set_remove()
bool database::redis_manager::set_remove (const std::string & key, const std::string & member)
Removes a member from a Redis set.
Parameters
key The set key
member The member to remove
Returns
true if member was removed, false if didn't exist
Definition at line 558 of file redis_manager.cpp.
update_query()
unsigned int database::redis_manager::update_query (const std::string & query_string) override virtual
Executes an UPDATE operation on the connected Redis database.
For Redis, this is equivalent to SET operation.
Parameters
query_string UPDATE operation (format: "key:value")
Returns
The number of keys updated, or 0 if failed.
Implements database::database_base.
Definition at line 191 of file redis_manager.cpp.
References insert_query().
The documentation for this class was generated from the following files:
libraries/database_system/database/backends/redis/redis_manager.h
libraries/database_system/database/backends/redis/redis_manager.cpp