Messaging System: TestUser Class Reference
TestUser Class Reference
Public Member Functions
TestUser ()=default
std::string table_name () const override
const entity_metadata & get_metadata () const override
bool save () override
bool load () override
bool update () override
bool remove () override
Public Member Functions inherited from database::orm::entity_base
virtual ~entity_base ()=default
Public Attributes
int64_t id = 0
std::string username
std::string email
bool is_active = true
Additional Inherited Members
Protected Member Functions inherited from database::orm::entity_base
entity_base ()=default
Detailed Description
Definition at line 96 of file unit_tests.cpp.
Constructor & Destructor Documentation
TestUser()
TestUser::TestUser () default
Member Function Documentation
get_metadata()
const entity_metadata & TestUser::get_metadata () const inline override virtual
Implements database::orm::entity_base.
Definition at line 111 of file unit_tests.cpp.
Referenced by TEST_F().
load()
bool TestUser::load () inline override virtual
Implements database::orm::entity_base.
Definition at line 121 of file unit_tests.cpp.
remove()
bool TestUser::remove () inline override virtual
Implements database::orm::entity_base.
Definition at line 131 of file unit_tests.cpp.
save()
bool TestUser::save () inline override virtual
Implements database::orm::entity_base.
Definition at line 116 of file unit_tests.cpp.
Referenced by TEST_F().
table_name()
std::string TestUser::table_name () const inline override virtual
Implements database::orm::entity_base.
Definition at line 107 of file unit_tests.cpp.
Referenced by TEST_F().
update()
bool TestUser::update () inline override virtual
Implements database::orm::entity_base.
Definition at line 126 of file unit_tests.cpp.
Member Data Documentation
email
std::string TestUser::email
Definition at line 101 of file unit_tests.cpp.
Referenced by TEST_F().
id
int64_t TestUser::id = 0
Definition at line 99 of file unit_tests.cpp.
is_active
bool TestUser::is_active = true
Definition at line 102 of file unit_tests.cpp.
Referenced by TEST_F().
username
std::string TestUser::username
Definition at line 100 of file unit_tests.cpp.
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/database_system/tests/unit_tests.cpp