Messaging System: libraries/thread_system/tests/benchmarks/thread_base_benchmarks/mpmc_performance_test.cpp File Reference
mpmc_performance_test.cpp File Reference
#include <benchmark/benchmark.h>
#include "job_queue.h"
#include "lockfree/queues/lockfree_job_queue.h"
#include "lockfree/queues/adaptive_job_queue.h"
#include "callback_job.h"
#include <thread>
#include <vector>
#include <atomic>
#include <random>
Functions
std::unique_ptr< job > create_simple_job (std::atomic< size_t > &counter)
template<typename QueueType >
static void BM_SPSC (benchmark::State &state)
template<typename QueueType >
static void BM_MPMC (benchmark::State &state)
template<typename QueueType >
static void BM_BatchOperations (benchmark::State &state)
template<typename QueueType >
static void BM_HighContention (benchmark::State &state)
Arg (SMALL_WORKLOAD) -> Arg(MEDIUM_WORKLOAD) ->Arg(LARGE_WORKLOAD)
Args ({2, 2, 5000}) -> Args({4, 4, 2500}) ->Args({8, 8, 1250})
Args ({10, 1000}) -> Args({100, 100}) ->Args({1000, 10})
Args ({4, 10000}) -> Args({8, 5000}) ->Args({16, 2500})
BENCHMARK_MAIN ()
Variables
constexpr size_t BATCH_SIZE = 100
constexpr size_t SMALL_WORKLOAD = 1000
constexpr size_t MEDIUM_WORKLOAD = 10000
constexpr size_t LARGE_WORKLOAD = 100000
Function Documentation
Arg()
Arg (SMALL_WORKLOAD) -> Arg(MEDIUM_WORKLOAD) ->Arg(LARGE_WORKLOAD)
Args() [1/3]
Args ({10, 1000}) -> Args({100, 100}) ->Args({1000, 10})
Args() [2/3]
Args ({2, 2, 5000}) -> Args({4, 4, 2500}) ->Args({8, 8, 1250})
Args() [3/3]
Args ({4, 10000}) -> Args({8, 5000}) ->Args({16, 2500})
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_BatchOperations()
template<typename QueueType > static void BM_BatchOperations (benchmark::State & state) static
Definition at line 150 of file mpmc_performance_test.cpp.
References create_simple_job(), and kcenon::thread::job::do_work().
BM_HighContention()
template<typename QueueType > static void BM_HighContention (benchmark::State & state) static
Definition at line 187 of file mpmc_performance_test.cpp.
References create_simple_job(), kcenon::thread::result< T >::has_value(), and kcenon::thread::result< T >::value().
BM_MPMC()
template<typename QueueType > static void BM_MPMC (benchmark::State & state) static
Definition at line 97 of file mpmc_performance_test.cpp.
References create_simple_job(), kcenon::thread::result< T >::has_value(), and kcenon::thread::result< T >::value().
BM_SPSC()
template<typename QueueType > static void BM_SPSC (benchmark::State & state) static
Definition at line 61 of file mpmc_performance_test.cpp.
References create_simple_job(), and kcenon::thread::result< T >::has_value().
create_simple_job()
std::unique_ptr< job > create_simple_job (std::atomic< size_t > & counter)
Definition at line 52 of file mpmc_performance_test.cpp.
Referenced by BM_BatchOperations(), BM_HighContention(), BM_MPMC(), and BM_SPSC().
Variable Documentation
BATCH_SIZE
constexpr size_t BATCH_SIZE = 100 constexpr
Definition at line 46 of file mpmc_performance_test.cpp.
LARGE_WORKLOAD
constexpr size_t LARGE_WORKLOAD = 100000 constexpr
Definition at line 49 of file mpmc_performance_test.cpp.
MEDIUM_WORKLOAD
constexpr size_t MEDIUM_WORKLOAD = 10000 constexpr
Definition at line 48 of file mpmc_performance_test.cpp.
SMALL_WORKLOAD
constexpr size_t SMALL_WORKLOAD = 1000 constexpr
Definition at line 47 of file mpmc_performance_test.cpp.