Messaging System: libraries/database_system/samples/async_operations_demo.cpp File Reference
async_operations_demo.cpp File Reference
#include <iostream>
#include <string>
#include <chrono>
#include <future>
#include <memory>
#include <vector>
#include <coroutine>
#include "database/database_manager.h"
#include "database/async/async_operations.h"
Classes
struct task
struct task::promise_type
Functions
void demonstrate_basic_async_operations ()
task async_database_operation (const std::string &operation_name)
void demonstrate_coroutine_operations ()
void demonstrate_async_connection_pool ()
void demonstrate_real_time_streams ()
void demonstrate_distributed_transactions ()
void demonstrate_saga_pattern ()
void demonstrate_async_batch_processing ()
int main ()
Function Documentation
async_database_operation()
task async_database_operation (const std::string & operation_name)
Definition at line 101 of file async_operations_demo.cpp.
Referenced by demonstrate_coroutine_operations().
demonstrate_async_batch_processing()
void demonstrate_async_batch_processing ()
Definition at line 384 of file async_operations_demo.cpp.
Referenced by main().
demonstrate_async_connection_pool()
void demonstrate_async_connection_pool ()
Definition at line 133 of file async_operations_demo.cpp.
Referenced by main().
demonstrate_basic_async_operations()
void demonstrate_basic_async_operations ()
Definition at line 22 of file async_operations_demo.cpp.
Referenced by main().
demonstrate_coroutine_operations()
void demonstrate_coroutine_operations ()
Definition at line 111 of file async_operations_demo.cpp.
References async_database_operation().
Referenced by main().
demonstrate_distributed_transactions()
void demonstrate_distributed_transactions ()
Definition at line 243 of file async_operations_demo.cpp.
Referenced by main().
demonstrate_real_time_streams()
void demonstrate_real_time_streams ()
Definition at line 189 of file async_operations_demo.cpp.
Referenced by main().
demonstrate_saga_pattern()
void demonstrate_saga_pattern ()
Definition at line 327 of file async_operations_demo.cpp.
Referenced by main().
main()
int main ()
Definition at line 425 of file async_operations_demo.cpp.
References demonstrate_async_batch_processing(), demonstrate_async_connection_pool(), demonstrate_basic_async_operations(), demonstrate_coroutine_operations(), demonstrate_distributed_transactions(), demonstrate_real_time_streams(), and demonstrate_saga_pattern().