Messaging System: kcenon::messaging::management::system_health_monitor Class Reference
kcenon::messaging::management::system_health_monitor Class Reference
#include <system_dashboard.h>
Classes
struct component_health_info
Public Member Functions
void update_component_health (const std::string &component, health_status status, const std::string &message="")
health_status get_overall_health () const
std::unordered_map< std::string, component_health_info > get_component_health () const
void evaluate_system_metrics (const metrics_aggregator &metrics)
Detailed Description
Definition at line 141 of file system_dashboard.h.
Member Function Documentation
evaluate_system_metrics()
void kcenon::messaging::management::system_health_monitor::evaluate_system_metrics (const metrics_aggregator & metrics) inline
Definition at line 207 of file system_dashboard.h.
References kcenon::messaging::management::critical, kcenon::messaging::management::metrics_aggregator::get_counter(), kcenon::messaging::management::metrics_aggregator::get_gauge(), kcenon::messaging::management::healthy, update_component_health(), and kcenon::messaging::management::warning.
get_component_health()
std::unordered_map< std::string, component_health_info > kcenon::messaging::management::system_health_monitor::get_component_health () const inline
Definition at line 187 of file system_dashboard.h.
get_overall_health()
health_status kcenon::messaging::management::system_health_monitor::get_overall_health () const inline
Definition at line 176 of file system_dashboard.h.
update_component_health()
void kcenon::messaging::management::system_health_monitor::update_component_health (const std::string & component, health_status status, const std::string & message = "") inline
Definition at line 157 of file system_dashboard.h.
References kcenon::messaging::management::critical, kcenon::messaging::management::healthy, and kcenon::messaging::management::warning.
Referenced by evaluate_system_metrics().
The documentation for this class was generated from the following file:
application_layer/include/kcenon/messaging/management/system_dashboard.h