Messaging System: libraries/logger_system/tests/unit/health_test/health_check_test.cpp File Reference
health_check_test.cpp File Reference
#include <gtest/gtest.h>
#include "../../sources/logger/health/health_check_system.h"
#include "../../sources/logger/writers/base_writer.h"
#include "../../sources/logger/core/log_collector.h"
#include <thread>
#include <chrono>
Classes
class mock_writer
class HealthCheckTest
class HealthCheckUtilsTest
Functions
TEST_F (HealthCheckTest, DefaultCriteria)
TEST_F (HealthCheckTest, WriterRegistration)
TEST_F (HealthCheckTest, WriterHealthTracking)
TEST_F (HealthCheckTest, WriterFailureDetection)
TEST_F (HealthCheckTest, WriterLatencyDetection)
TEST_F (HealthCheckTest, BufferHealthTracking)
TEST_F (HealthCheckTest, QueueHealthTracking)
TEST_F (HealthCheckTest, ComprehensiveHealthCheck)
TEST_F (HealthCheckTest, CustomHealthCheck)
TEST_F (HealthCheckTest, MonitoringStartStop)
TEST_F (HealthCheckTest, ConfigureChecks)
TEST_F (HealthCheckTest, ResetStats)
TEST_F (HealthCheckTest, ScopedRegistration)
TEST_F (HealthCheckUtilsTest, StatusToString)
TEST_F (HealthCheckUtilsTest, AggregateStatus)
TEST_F (HealthCheckUtilsTest, FormatAsJson)
TEST_F (HealthCheckUtilsTest, FormatWriterHealth)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 385 of file health_check_test.cpp.
TEST_F() [1/17]
TEST_F (HealthCheckTest , BufferHealthTracking)
Definition at line 149 of file health_check_test.cpp.
TEST_F() [2/17]
TEST_F (HealthCheckTest , ComprehensiveHealthCheck)
Definition at line 185 of file health_check_test.cpp.
TEST_F() [3/17]
TEST_F (HealthCheckTest , ConfigureChecks)
Definition at line 250 of file health_check_test.cpp.
TEST_F() [4/17]
TEST_F (HealthCheckTest , CustomHealthCheck)
Definition at line 204 of file health_check_test.cpp.
TEST_F() [5/17]
TEST_F (HealthCheckTest , DefaultCriteria)
Definition at line 70 of file health_check_test.cpp.
TEST_F() [6/17]
TEST_F (HealthCheckTest , MonitoringStartStop)
Definition at line 231 of file health_check_test.cpp.
TEST_F() [7/17]
TEST_F (HealthCheckTest , QueueHealthTracking)
Definition at line 165 of file health_check_test.cpp.
TEST_F() [8/17]
TEST_F (HealthCheckTest , ResetStats)
Definition at line 271 of file health_check_test.cpp.
TEST_F() [9/17]
TEST_F (HealthCheckTest , ScopedRegistration)
Definition at line 296 of file health_check_test.cpp.
TEST_F() [10/17]
TEST_F (HealthCheckTest , WriterFailureDetection)
Definition at line 116 of file health_check_test.cpp.
References kcenon::logger::result< T >::has_value(), logger_system::info, and kcenon::logger::result< T >::value().
TEST_F() [11/17]
TEST_F (HealthCheckTest , WriterHealthTracking)
Definition at line 97 of file health_check_test.cpp.
References kcenon::logger::result< T >::has_value(), logger_system::info, and kcenon::logger::result< T >::value().
TEST_F() [12/17]
TEST_F (HealthCheckTest , WriterLatencyDetection)
Definition at line 134 of file health_check_test.cpp.
References kcenon::logger::result< T >::has_value(), logger_system::info, and kcenon::logger::result< T >::value().
TEST_F() [13/17]
TEST_F (HealthCheckTest , WriterRegistration)
Definition at line 79 of file health_check_test.cpp.
TEST_F() [14/17]
TEST_F (HealthCheckUtilsTest , AggregateStatus)
Definition at line 322 of file health_check_test.cpp.
TEST_F() [15/17]
TEST_F (HealthCheckUtilsTest , FormatAsJson)
Definition at line 352 of file health_check_test.cpp.
TEST_F() [16/17]
TEST_F (HealthCheckUtilsTest , FormatWriterHealth)
Definition at line 367 of file health_check_test.cpp.
References logger_system::info.
TEST_F() [17/17]
TEST_F (HealthCheckUtilsTest , StatusToString)
Definition at line 315 of file health_check_test.cpp.