Messaging System: libraries/database_system/samples/performance_monitoring_demo.cpp File Reference
performance_monitoring_demo.cpp File Reference
#include <iostream>
#include <string>
#include <chrono>
#include <thread>
#include <memory>
#include <random>
#include "database/database_manager.h"
#include "database/monitoring/performance_monitor.h"
Functions
void demonstrate_basic_metrics ()
void demonstrate_query_metrics ()
void demonstrate_connection_pool_metrics ()
void demonstrate_real_time_monitoring ()
void demonstrate_performance_analysis ()
void demonstrate_metrics_export ()
void demonstrate_alerting_system ()
int main ()
Function Documentation
demonstrate_alerting_system()
void demonstrate_alerting_system ()
Definition at line 249 of file performance_monitoring_demo.cpp.
References database::monitoring::performance_monitor::instance().
Referenced by main().
demonstrate_basic_metrics()
void demonstrate_basic_metrics ()
Definition at line 21 of file performance_monitoring_demo.cpp.
References database::monitoring::performance_monitor::instance().
Referenced by main().
demonstrate_connection_pool_metrics()
void demonstrate_connection_pool_metrics ()
Definition at line 108 of file performance_monitoring_demo.cpp.
References database::monitoring::connection_metrics::active_connections, database::monitoring::connection_metrics::idle_connections, database::monitoring::performance_monitor::instance(), database::monitoring::performance_monitor::record_connection_metrics(), and database::monitoring::connection_metrics::total_connections.
Referenced by main().
demonstrate_metrics_export()
void demonstrate_metrics_export ()
Definition at line 217 of file performance_monitoring_demo.cpp.
References database::monitoring::performance_monitor::instance().
Referenced by main().
demonstrate_performance_analysis()
void demonstrate_performance_analysis ()
Definition at line 189 of file performance_monitoring_demo.cpp.
References database::monitoring::performance_monitor::instance().
Referenced by main().
demonstrate_query_metrics()
void demonstrate_query_metrics ()
Definition at line 52 of file performance_monitoring_demo.cpp.
References database::monitoring::query_metrics::execution_time, database::monitoring::performance_monitor::instance(), database::monitoring::query_metrics::rows_affected, and database::monitoring::query_metrics::success.
Referenced by main().
demonstrate_real_time_monitoring()
void demonstrate_real_time_monitoring ()
Definition at line 154 of file performance_monitoring_demo.cpp.
References database::monitoring::performance_monitor::instance(), and alert::message.
Referenced by main().
main()
int main ()
Definition at line 289 of file performance_monitoring_demo.cpp.
References demonstrate_alerting_system(), demonstrate_basic_metrics(), demonstrate_connection_pool_metrics(), demonstrate_metrics_export(), demonstrate_performance_analysis(), demonstrate_query_metrics(), and demonstrate_real_time_monitoring().