Messaging System: microservices_orchestrator Class Reference
microservices_orchestrator Class Reference
Public Member Functions
microservices_orchestrator ()
void setupMessageHandlers ()
void initializeServices ()
void defineService (const std::string &name, const std::string &version, const std::vector< std::string > &dependencies, int min_instances, int max_instances)
void deploy_service_instance (const std::string &service_name)
void handleServiceRegistration (const core::message &msg)
void handleServiceDiscovery (const core::message &msg)
void handleHealthCheck (const core::message &msg)
void handleServiceRequest (const core::message &msg)
void handleServiceScaling (const core::message &msg)
void handleServiceDeployment (const core::message &msg)
void scaleUp (const std::string &service_name, int count)
void scaleDown (const std::string &service_name, int count)
void autoScale (const std::string &service_name)
void performRollingUpdate (const std::string &service_name, const std::string &new_version)
void performBlueGreenDeployment (const std::string &service_name, const std::string &new_version)
void performCanaryDeployment (const std::string &service_name, const std::string &new_version)
bool forwardRequest (service_instance *instance, const core::message &msg)
void handleUnhealthyInstance (const service_instance &instance)
void notifyDependents (const std::string &service_name)
void sendServiceUnavailable (const std::string &service_name, const std::string &request_id)
void sendServiceNotFound (const std::string &service_name, const std::string &client_id)
void send_circuit_breaker_open (const std::string &service_name, const std::string &request_id)
void updateInstanceState (const std::string &instance_id, service_instance::state new_state)
std::string generateInstanceId (const std::string &service_name) const
void startHealthCheckMonitor ()
void startAutoScaler ()
void printServiceMap ()
void start ()
void stop ()
Detailed Description
Definition at line 213 of file microservices_orchestrator.cpp.
Constructor & Destructor Documentation
microservices_orchestrator()
microservices_orchestrator::microservices_orchestrator () inline
Definition at line 238 of file microservices_orchestrator.cpp.
References kcenon::messaging::config::config_builder::build(), kcenon::messaging::config::config_builder::enable_compression(), kcenon::messaging::config::config_builder::enable_external_monitoring(), initializeServices(), kcenon::messaging::config::config_builder::set_container_max_size(), kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), kcenon::messaging::config::config_builder::set_worker_threads(), and setupMessageHandlers().
Member Function Documentation
autoScale()
void microservices_orchestrator::autoScale (const std::string & service_name) inline
Definition at line 588 of file microservices_orchestrator.cpp.
References service_instance::HEALTHY, scaleDown(), and scaleUp().
Referenced by handleServiceScaling(), performCanaryDeployment(), and startAutoScaler().
defineService()
void microservices_orchestrator::defineService (const std::string & name, const std::string & version, const std::vector< std::string > & dependencies, int min_instances, int max_instances) inline
Definition at line 325 of file microservices_orchestrator.cpp.
References service_definition::dependencies, load_balancer::LEAST_CONNECTIONS, service_definition::max_instances, service_definition::min_instances, service_definition::service_name, and service_definition::version.
Referenced by initializeServices().
deploy_service_instance()
void microservices_orchestrator::deploy_service_instance (const std::string & service_name) inline
Definition at line 344 of file microservices_orchestrator.cpp.
References generateInstanceId(), service_instance::HEALTHY, service_instance::host, service_instance::instance_id, service_instance::last_health_check, service_instance::m_state, service_instance::port, service_instance::service_name, service_instance::STARTING, updateInstanceState(), and service_instance::version.
Referenced by handleUnhealthyInstance(), initializeServices(), performBlueGreenDeployment(), performCanaryDeployment(), and scaleUp().
forwardRequest()
bool microservices_orchestrator::forwardRequest (service_instance * instance, const core::message & msg) inline
Definition at line 691 of file microservices_orchestrator.cpp.
References kcenon::messaging::core::message_metadata::headers, service_instance::host, service_instance::instance_id, kcenon::messaging::core::message::metadata, kcenon::messaging::core::message::payload, service_instance::port, and kcenon::messaging::core::message_metadata::type.
Referenced by handleServiceRequest().
generateInstanceId()
std::string microservices_orchestrator::generateInstanceId (const std::string & service_name) const inline
Definition at line 782 of file microservices_orchestrator.cpp.
Referenced by deploy_service_instance().
handleHealthCheck()
void microservices_orchestrator::handleHealthCheck (const core::message & msg) inline
Definition at line 432 of file microservices_orchestrator.cpp.
References handleUnhealthyInstance(), kcenon::messaging::core::message_metadata::headers, service_instance::HEALTHY, kcenon::messaging::core::message::metadata, and service_instance::UNHEALTHY.
Referenced by setupMessageHandlers().
handleServiceDeployment()
void microservices_orchestrator::handleServiceDeployment (const core::message & msg) inline
Definition at line 527 of file microservices_orchestrator.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, performBlueGreenDeployment(), performCanaryDeployment(), and performRollingUpdate().
Referenced by setupMessageHandlers().
handleServiceDiscovery()
void microservices_orchestrator::handleServiceDiscovery (const core::message & msg) inline
Definition at line 400 of file microservices_orchestrator.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, sendServiceNotFound(), and sendServiceUnavailable().
Referenced by setupMessageHandlers().
handleServiceRegistration()
void microservices_orchestrator::handleServiceRegistration (const core::message & msg) inline
Definition at line 372 of file microservices_orchestrator.cpp.
References kcenon::messaging::core::message_metadata::headers, service_instance::HEALTHY, service_instance::host, service_instance::instance_id, service_instance::last_health_check, service_instance::m_state, kcenon::messaging::core::message::metadata, notifyDependents(), service_instance::port, and service_instance::service_name.
Referenced by setupMessageHandlers().
handleServiceRequest()
void microservices_orchestrator::handleServiceRequest (const core::message & msg) inline
Definition at line 472 of file microservices_orchestrator.cpp.
References forwardRequest(), kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, send_circuit_breaker_open(), and sendServiceUnavailable().
Referenced by setupMessageHandlers().
handleServiceScaling()
void microservices_orchestrator::handleServiceScaling (const core::message & msg) inline
Definition at line 512 of file microservices_orchestrator.cpp.
References autoScale(), kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, scaleDown(), and scaleUp().
Referenced by setupMessageHandlers().
handleUnhealthyInstance()
void microservices_orchestrator::handleUnhealthyInstance (const service_instance & instance) inline
Definition at line 705 of file microservices_orchestrator.cpp.
References deploy_service_instance(), service_instance::instance_id, and service_instance::service_name.
Referenced by handleHealthCheck(), and startHealthCheckMonitor().
initializeServices()
void microservices_orchestrator::initializeServices () inline
Definition at line 301 of file microservices_orchestrator.cpp.
References defineService(), and deploy_service_instance().
Referenced by microservices_orchestrator().
notifyDependents()
void microservices_orchestrator::notifyDependents (const std::string & service_name) inline
Definition at line 723 of file microservices_orchestrator.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, and kcenon::messaging::core::message_metadata::type.
Referenced by handleServiceRegistration().
performBlueGreenDeployment()
void microservices_orchestrator::performBlueGreenDeployment (const std::string & service_name, const std::string & new_version) inline
Definition at line 648 of file microservices_orchestrator.cpp.
References deploy_service_instance().
Referenced by handleServiceDeployment().
performCanaryDeployment()
void microservices_orchestrator::performCanaryDeployment (const std::string & service_name, const std::string & new_version) inline
Definition at line 672 of file microservices_orchestrator.cpp.
References autoScale(), and deploy_service_instance().
Referenced by handleServiceDeployment().
performRollingUpdate()
void microservices_orchestrator::performRollingUpdate (const std::string & service_name, const std::string & new_version) inline
Definition at line 620 of file microservices_orchestrator.cpp.
References service_instance::DRAINING, service_instance::HEALTHY, and service_instance::STARTING.
Referenced by handleServiceDeployment().
printServiceMap()
void microservices_orchestrator::printServiceMap () inline
Definition at line 821 of file microservices_orchestrator.cpp.
References service_instance::HEALTHY, and service_instance::UNHEALTHY.
Referenced by start().
scaleDown()
void microservices_orchestrator::scaleDown (const std::string & service_name, int count) inline
Definition at line 555 of file microservices_orchestrator.cpp.
References service_instance::DRAINING.
Referenced by autoScale(), and handleServiceScaling().
scaleUp()
void microservices_orchestrator::scaleUp (const std::string & service_name, int count) inline
Definition at line 541 of file microservices_orchestrator.cpp.
References deploy_service_instance().
Referenced by autoScale(), and handleServiceScaling().
send_circuit_breaker_open()
void microservices_orchestrator::send_circuit_breaker_open (const std::string & service_name, const std::string & request_id) inline
Definition at line 759 of file microservices_orchestrator.cpp.
Referenced by handleServiceRequest().
sendServiceNotFound()
void microservices_orchestrator::sendServiceNotFound (const std::string & service_name, const std::string & client_id) inline
Definition at line 749 of file microservices_orchestrator.cpp.
Referenced by handleServiceDiscovery().
sendServiceUnavailable()
void microservices_orchestrator::sendServiceUnavailable (const std::string & service_name, const std::string & request_id) inline
Definition at line 739 of file microservices_orchestrator.cpp.
Referenced by handleServiceDiscovery(), and handleServiceRequest().
setupMessageHandlers()
void microservices_orchestrator::setupMessageHandlers () inline
Definition at line 267 of file microservices_orchestrator.cpp.
References handleHealthCheck(), handleServiceDeployment(), handleServiceDiscovery(), handleServiceRegistration(), handleServiceRequest(), and handleServiceScaling().
Referenced by microservices_orchestrator().
start()
void microservices_orchestrator::start () inline
Definition at line 868 of file microservices_orchestrator.cpp.
References printServiceMap(), startAutoScaler(), startHealthCheckMonitor(), and stop().
Referenced by main().
startAutoScaler()
void microservices_orchestrator::startAutoScaler () inline
Definition at line 809 of file microservices_orchestrator.cpp.
References autoScale().
Referenced by start().
startHealthCheckMonitor()
void microservices_orchestrator::startHealthCheckMonitor () inline
Definition at line 787 of file microservices_orchestrator.cpp.
References handleUnhealthyInstance(), service_instance::HEALTHY, and service_instance::UNHEALTHY.
Referenced by start().
stop()
void microservices_orchestrator::stop () inline
Definition at line 917 of file microservices_orchestrator.cpp.
Referenced by start().
updateInstanceState()
void microservices_orchestrator::updateInstanceState (const std::string & instance_id, service_instance::state new_state) inline
Definition at line 769 of file microservices_orchestrator.cpp.
Referenced by deploy_service_instance().
The documentation for this class was generated from the following file:
application_layer/samples/microservices_orchestrator.cpp