Messaging System: libraries/logger_system/examples/basic_usage.cpp File Reference
basic_usage.cpp File Reference
#include <kcenon/logger/core/logger.h>
#include <kcenon/logger/writers/console_writer.h>
#include <thread>
#include <vector>
#include <iostream>
#include <chrono>
Typedefs
using log_level_type = logger_system::log_level
Functions
void basic_logging_example ()
void multithreaded_logging_example ()
void log_level_filtering_example ()
void sync_vs_async_example ()
int main ()
Typedef Documentation
log_level_type
using log_level_type = logger_system::log_level
Definition at line 40 of file basic_usage.cpp.
Function Documentation
basic_logging_example()
void basic_logging_example ()
Definition at line 51 of file basic_usage.cpp.
Referenced by main().
log_level_filtering_example()
void log_level_filtering_example ()
Definition at line 108 of file basic_usage.cpp.
Referenced by main().
main()
int main ()
Definition at line 166 of file basic_usage.cpp.
References basic_logging_example(), log_level_filtering_example(), multithreaded_logging_example(), and sync_vs_async_example().
multithreaded_logging_example()
void multithreaded_logging_example ()
Definition at line 79 of file basic_usage.cpp.
Referenced by main().
sync_vs_async_example()
void sync_vs_async_example ()
Definition at line 130 of file basic_usage.cpp.
References async_logger, and sync_logger.
Referenced by main().