Messaging System: libraries/database_system/tests/unit_tests.cpp File Reference
unit_tests.cpp File Reference
#include <gtest/gtest.h>
#include <memory>
#include <chrono>
#include <thread>
#include <future>
#include "database/database_manager.h"
#include "database/database_types.h"
#include "database/orm/entity.h"
#include "database/monitoring/performance_monitor.h"
#include "database/security/secure_connection.h"
#include "database/async/async_operations.h"
Classes
class DatabaseTest
class TestUser
class ORMTest
class PerformanceMonitorTest
class SecurityTest
class AsyncOperationsTest
class ConnectionPoolTest
class QueryBuilderTest
Functions
TEST_F (DatabaseTest, DatabaseManagerSingleton)
TEST_F (DatabaseTest, DatabaseTypeSettings)
TEST_F (DatabaseTest, BasicQueryOperations)
TEST_F (DatabaseTest, ConnectionHandling)
TEST_F (ORMTest, EntityDefinition)
TEST_F (ORMTest, EntityMetadata)
TEST_F (ORMTest, EntityManager)
TEST_F (PerformanceMonitorTest, BasicConfiguration)
TEST_F (PerformanceMonitorTest, QueryMetricsRecording)
TEST_F (PerformanceMonitorTest, ConnectionMetricsRecording)
TEST_F (PerformanceMonitorTest, MetricsRetrieval)
TEST_F (SecurityTest, SecureConnectionConfiguration)
TEST_F (SecurityTest, SecurityConceptDemonstration)
TEST_F (AsyncOperationsTest, AsyncExecutorCreation)
TEST_F (AsyncOperationsTest, MultipleAsyncOperations)
TEST_F (AsyncOperationsTest, AsyncConceptDemonstration)
TEST_F (ConnectionPoolTest, PoolConfiguration)
TEST_F (ConnectionPoolTest, PoolStatistics)
TEST_F (QueryBuilderTest, SQLQueryBuilder)
TEST_F (QueryBuilderTest, MongoDBQueryBuilder)
TEST_F (QueryBuilderTest, RedisQueryBuilder)
TEST_F (DatabaseTest, PhaseA4DatabaseTypes)
TEST_F (DatabaseTest, GeneralQueryExecution)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 457 of file unit_tests.cpp.
TEST_F() [1/23]
TEST_F (AsyncOperationsTest , AsyncConceptDemonstration)
Definition at line 338 of file unit_tests.cpp.
TEST_F() [2/23]
TEST_F (AsyncOperationsTest , AsyncExecutorCreation)
Definition at line 305 of file unit_tests.cpp.
TEST_F() [3/23]
TEST_F (AsyncOperationsTest , MultipleAsyncOperations)
Definition at line 321 of file unit_tests.cpp.
TEST_F() [4/23]
TEST_F (ConnectionPoolTest , PoolConfiguration)
Definition at line 362 of file unit_tests.cpp.
References database::connection_pool_config::acquire_timeout, database::connection_pool_config::connection_string, database::database_manager::handle(), database::connection_pool_config::max_connections, and database::connection_pool_config::min_connections.
TEST_F() [5/23]
TEST_F (ConnectionPoolTest , PoolStatistics)
Definition at line 375 of file unit_tests.cpp.
References database::database_manager::handle().
TEST_F() [6/23]
TEST_F (DatabaseTest , BasicQueryOperations)
Definition at line 66 of file unit_tests.cpp.
References database::database_manager::handle().
TEST_F() [7/23]
TEST_F (DatabaseTest , ConnectionHandling)
Definition at line 82 of file unit_tests.cpp.
References database::database_manager::handle().
TEST_F() [8/23]
TEST_F (DatabaseTest , DatabaseManagerSingleton)
Definition at line 40 of file unit_tests.cpp.
References database::database_manager::handle().
TEST_F() [9/23]
TEST_F (DatabaseTest , DatabaseTypeSettings)
Definition at line 48 of file unit_tests.cpp.
References database::database_manager::handle().
TEST_F() [10/23]
TEST_F (DatabaseTest , GeneralQueryExecution)
Definition at line 445 of file unit_tests.cpp.
References database::database_manager::handle().
TEST_F() [11/23]
TEST_F (DatabaseTest , PhaseA4DatabaseTypes)
Definition at line 427 of file unit_tests.cpp.
References database::database_manager::handle().
TEST_F() [12/23]
TEST_F (ORMTest , EntityDefinition)
Definition at line 149 of file unit_tests.cpp.
References TestUser::email, TestUser::is_active, and TestUser::username.
TEST_F() [13/23]
TEST_F (ORMTest , EntityManager)
Definition at line 167 of file unit_tests.cpp.
References TestUser::save(), and TestUser::table_name().
TEST_F() [14/23]
TEST_F (ORMTest , EntityMetadata)
Definition at line 159 of file unit_tests.cpp.
References TestUser::get_metadata().
TEST_F() [15/23]
TEST_F (PerformanceMonitorTest , BasicConfiguration)
Definition at line 194 of file unit_tests.cpp.
References database::monitoring::performance_monitor::instance().
TEST_F() [16/23]
TEST_F (PerformanceMonitorTest , ConnectionMetricsRecording)
Definition at line 223 of file unit_tests.cpp.
References database::monitoring::connection_metrics::active_connections, database::monitoring::connection_metrics::idle_connections, database::monitoring::performance_monitor::instance(), and database::monitoring::connection_metrics::total_connections.
TEST_F() [17/23]
TEST_F (PerformanceMonitorTest , MetricsRetrieval)
Definition at line 238 of file unit_tests.cpp.
References database::monitoring::performance_monitor::instance().
TEST_F() [18/23]
TEST_F (PerformanceMonitorTest , QueryMetricsRecording)
Definition at line 204 of file unit_tests.cpp.
References database::monitoring::query_metrics::db_type, database::monitoring::query_metrics::end_time, database::monitoring::query_metrics::execution_time, database::monitoring::performance_monitor::instance(), database::monitoring::query_metrics::query_hash, database::monitoring::query_metrics::rows_affected, database::monitoring::query_metrics::start_time, and database::monitoring::query_metrics::success.
TEST_F() [19/23]
TEST_F (QueryBuilderTest , MongoDBQueryBuilder)
Definition at line 406 of file unit_tests.cpp.
TEST_F() [20/23]
TEST_F (QueryBuilderTest , RedisQueryBuilder)
Definition at line 416 of file unit_tests.cpp.
TEST_F() [21/23]
TEST_F (QueryBuilderTest , SQLQueryBuilder)
Definition at line 394 of file unit_tests.cpp.
References database::database_manager::handle().
TEST_F() [22/23]
TEST_F (SecurityTest , SecureConnectionConfiguration)
Definition at line 264 of file unit_tests.cpp.
TEST_F() [23/23]
TEST_F (SecurityTest , SecurityConceptDemonstration)
Definition at line 281 of file unit_tests.cpp.