Messaging System: libraries/monitoring_system/tests/test_health_monitoring.cpp File Reference
test_health_monitoring.cpp File Reference
Unit tests for health monitoring functionality.
#include <gtest/gtest.h>
#include <thread>
#include <chrono>
#include <memory>
Classes
class test_health_check
class HealthMonitoringTest
Functions
TEST_F (HealthMonitoringTest, HealthCheckResultStaticFactories)
TEST_F (HealthMonitoringTest, FunctionalHealthCheck)
TEST_F (HealthMonitoringTest, CompositeHealthCheckAllRequired)
TEST_F (HealthMonitoringTest, CompositeHealthCheckAnyRequired)
TEST_F (HealthMonitoringTest, HealthDependencyGraphAddNode)
TEST_F (HealthMonitoringTest, HealthDependencyGraphAddDependency)
TEST_F (HealthMonitoringTest, HealthDependencyGraphCycleDetection)
TEST_F (HealthMonitoringTest, HealthDependencyGraphTopologicalSort)
TEST_F (HealthMonitoringTest, HealthDependencyGraphCheckWithDependencies)
TEST_F (HealthMonitoringTest, HealthDependencyGraphFailureImpact)
TEST_F (HealthMonitoringTest, HealthMonitorRegisterUnregister)
TEST_F (HealthMonitoringTest, HealthMonitorStartStop)
TEST_F (HealthMonitoringTest, HealthMonitorCheckSpecific)
TEST_F (HealthMonitoringTest, HealthMonitorCheckAll)
TEST_F (HealthMonitoringTest, HealthMonitorOverallStatus)
TEST_F (HealthMonitoringTest, HealthMonitorDependencies)
TEST_F (HealthMonitoringTest, HealthMonitorRecoveryHandler)
TEST_F (HealthMonitoringTest, HealthMonitorStats)
TEST_F (HealthMonitoringTest, HealthCheckBuilder)
TEST_F (HealthMonitoringTest, GlobalHealthMonitor)
TEST_F (HealthMonitoringTest, HealthMonitorReport)
TEST_F (HealthMonitoringTest, ConcurrentHealthChecks)
Detailed Description
Unit tests for health monitoring functionality.
Definition in file test_health_monitoring.cpp.
Function Documentation
TEST_F() [1/22]
TEST_F (HealthMonitoringTest , CompositeHealthCheckAllRequired)
Definition at line 100 of file test_health_monitoring.cpp.
TEST_F() [2/22]
TEST_F (HealthMonitoringTest , CompositeHealthCheckAnyRequired)
Definition at line 126 of file test_health_monitoring.cpp.
TEST_F() [3/22]
TEST_F (HealthMonitoringTest , ConcurrentHealthChecks)
Definition at line 555 of file test_health_monitoring.cpp.
TEST_F() [4/22]
TEST_F (HealthMonitoringTest , FunctionalHealthCheck)
Definition at line 81 of file test_health_monitoring.cpp.
References monitoring_system::functional_health_check::get_name(), monitoring_system::functional_health_check::get_type(), and monitoring_system::health_check_result::healthy().
TEST_F() [5/22]
TEST_F (HealthMonitoringTest , GlobalHealthMonitor)
Definition at line 517 of file test_health_monitoring.cpp.
References monitoring_system::result< T >::has_value().
TEST_F() [6/22]
TEST_F (HealthMonitoringTest , HealthCheckBuilder)
Definition at line 496 of file test_health_monitoring.cpp.
References monitoring_system::critical, and monitoring_system::health_check_result::healthy().
TEST_F() [7/22]
TEST_F (HealthMonitoringTest , HealthCheckResultStaticFactories)
Definition at line 61 of file test_health_monitoring.cpp.
References monitoring_system::degraded, monitoring_system::health_check_result::degraded(), monitoring_system::healthy, monitoring_system::health_check_result::healthy(), monitoring_system::unhealthy, and monitoring_system::health_check_result::unhealthy().
TEST_F() [8/22]
TEST_F (HealthMonitoringTest , HealthDependencyGraphAddDependency)
Definition at line 165 of file test_health_monitoring.cpp.
References monitoring_system::result< T >::has_value(), and monitoring_system::result< T >::value().
TEST_F() [9/22]
TEST_F (HealthMonitoringTest , HealthDependencyGraphAddNode)
Definition at line 150 of file test_health_monitoring.cpp.
References monitoring_system::error_info::code, monitoring_system::result< T >::get_error(), monitoring_system::result< T >::has_value(), and monitoring_system::result< T >::value().
TEST_F() [10/22]
TEST_F (HealthMonitoringTest , HealthDependencyGraphCheckWithDependencies)
Definition at line 246 of file test_health_monitoring.cpp.
TEST_F() [11/22]
TEST_F (HealthMonitoringTest , HealthDependencyGraphCycleDetection)
Definition at line 188 of file test_health_monitoring.cpp.
References monitoring_system::error_info::code, monitoring_system::result< T >::get_error(), and monitoring_system::result< T >::has_value().
TEST_F() [12/22]
TEST_F (HealthMonitoringTest , HealthDependencyGraphFailureImpact)
Definition at line 278 of file test_health_monitoring.cpp.
TEST_F() [13/22]
TEST_F (HealthMonitoringTest , HealthDependencyGraphTopologicalSort)
Definition at line 212 of file test_health_monitoring.cpp.
TEST_F() [14/22]
TEST_F (HealthMonitoringTest , HealthMonitorCheckAll)
Definition at line 374 of file test_health_monitoring.cpp.
TEST_F() [15/22]
TEST_F (HealthMonitoringTest , HealthMonitorCheckSpecific)
Definition at line 353 of file test_health_monitoring.cpp.
References monitoring_system::error_info::code, monitoring_system::result< T >::get_error(), monitoring_system::result< T >::has_value(), and monitoring_system::result< T >::value().
TEST_F() [16/22]
TEST_F (HealthMonitoringTest , HealthMonitorDependencies)
Definition at line 427 of file test_health_monitoring.cpp.
References monitoring_system::result< T >::has_value(), and monitoring_system::result< T >::value().
TEST_F() [17/22]
TEST_F (HealthMonitoringTest , HealthMonitorOverallStatus)
Definition at line 394 of file test_health_monitoring.cpp.
TEST_F() [18/22]
TEST_F (HealthMonitoringTest , HealthMonitorRecoveryHandler)
Definition at line 446 of file test_health_monitoring.cpp.
References monitoring_system::health_monitor_config::check_interval, and monitoring_system::health_monitor_config::enable_auto_recovery.
TEST_F() [19/22]
TEST_F (HealthMonitoringTest , HealthMonitorRegisterUnregister)
Definition at line 310 of file test_health_monitoring.cpp.
References monitoring_system::error_info::code, monitoring_system::result< T >::get_error(), monitoring_system::result< T >::has_value(), and monitoring_system::result< T >::value().
TEST_F() [20/22]
TEST_F (HealthMonitoringTest , HealthMonitorReport)
Definition at line 528 of file test_health_monitoring.cpp.
TEST_F() [21/22]
TEST_F (HealthMonitoringTest , HealthMonitorStartStop)
Definition at line 334 of file test_health_monitoring.cpp.
References monitoring_system::result< T >::has_value().
TEST_F() [22/22]
TEST_F (HealthMonitoringTest , HealthMonitorStats)
Definition at line 472 of file test_health_monitoring.cpp.