Messaging System: WorkloadSimulator Class Reference
WorkloadSimulator Class Reference
Static Public Member Functions
static void simulate_cpu_work (int complexity)
static void simulate_io_work (int duration_ms)
static void simulate_memory_work (size_t size_mb)
static void simulate_mixed_work (int cpu_complexity, int io_duration_ms)
Detailed Description
Definition at line 123 of file real_world_benchmark.cpp.
Member Function Documentation
simulate_cpu_work()
static void WorkloadSimulator::simulate_cpu_work (int complexity) inline static
Definition at line 126 of file real_world_benchmark.cpp.
Referenced by BM_BatchFileProcessing(), BM_DataAnalysisWorkload(), BM_ImageProcessingPipeline(), and simulate_mixed_work().
simulate_io_work()
static void WorkloadSimulator::simulate_io_work (int duration_ms) inline static
Definition at line 134 of file real_world_benchmark.cpp.
Referenced by BM_BatchFileProcessing(), BM_MicroserviceCommunication(), and simulate_mixed_work().
simulate_memory_work()
static void WorkloadSimulator::simulate_memory_work (size_t size_mb) inline static
Definition at line 139 of file real_world_benchmark.cpp.
Referenced by BM_DataAnalysisWorkload().
simulate_mixed_work()
static void WorkloadSimulator::simulate_mixed_work (int cpu_complexity, int io_duration_ms) inline static
Definition at line 148 of file real_world_benchmark.cpp.
References simulate_cpu_work(), and simulate_io_work().
Referenced by BM_WebServerSimulation().
The documentation for this class was generated from the following file:
libraries/thread_system/benchmarks/thread_pool_benchmarks/real_world_benchmark.cpp