Messaging System: libraries/monitoring_system/samples/crash_protection/main.cpp File Reference
main.cpp File Reference
Monitoring system crash protection demonstration.
#include <iostream>
#include <thread>
#include <chrono>
#include <random>
#include <vector>
#include <memory>
#include <atomic>
#include <fstream>
#include "interfaces/monitoring_crash_safety.h"
#include "monitoring/monitoring.h"
#include "storage/ring_buffer.h"
Classes
struct system_stats
Functions
void simulate_monitoring_crash ()
void simulate_ring_buffer_overflow ()
void simulate_alert_system_failure ()
void metrics_collection_task (int collector_id, std::shared_ptr< monitoring > monitor)
void thread_pool_monitoring_task (int monitor_id)
void risky_monitoring_task (int task_id)
void on_monitoring_component_crash (const std::string &component_name)
void on_ring_buffer_overflow (size_t lost_entries)
void on_alert_system_crash (const std::string &crash_info)
std::string save_monitoring_state ()
void restore_monitoring_state (const std::string &state)
std::string save_collector_state ()
void restore_collector_state (const std::string &state)
int main ()
Variables
std::atomic< bool > monitoring_active {true}
std::atomic< int > metrics_collected {0}
std::atomic< int > alerts_sent {0}
std::atomic< int > critical_snapshots {0}
Detailed Description
Monitoring system crash protection demonstration.
This example demonstrates comprehensive crash protection mechanisms for monitoring systems including metrics preservation, real-time backup, alert system protection, and automatic recovery of monitoring data.
Definition in file main.cpp.
Function Documentation
main()
int main ()
Definition at line 220 of file main.cpp.
References alerts_sent, monitoring_module::alert_system_crash_safety::configure_alert_safety(), monitoring_module::metrics_collection_crash_safety::configure_collector_safety(), monitoring_module::ring_buffer_crash_safety::configure_ring_buffer_safety(), critical_snapshots, monitoring_module::monitoring_crash_safety::instance(), metrics_collected, metrics_collection_task(), monitoring_active, on_alert_system_crash(), on_ring_buffer_overflow(), monitoring_module::alert_system_crash_safety::preserve_pending_alerts(), restore_collector_state(), restore_monitoring_state(), monitoring_module::alert_system_crash_safety::restore_preserved_alerts(), risky_monitoring_task(), save_collector_state(), save_monitoring_state(), monitoring_module::alert_system_crash_safety::set_crash_alert_handler(), monitoring_module::ring_buffer_crash_safety::set_overflow_handler(), and thread_pool_monitoring_task().
metrics_collection_task()
void metrics_collection_task (int collector_id, std::shared_ptr< monitoring > monitor)
Definition at line 57 of file main.cpp.
References monitoring_module::critical_metrics_snapshot::active_threads, monitoring_interface::system_metrics::active_threads, monitoring_module::critical_metrics_snapshot::cpu_usage_percent, monitoring_interface::system_metrics::cpu_usage_percent, monitoring_module::critical_metrics_snapshot::crash_context, critical_snapshots, monitoring_module::monitoring_crash_safety::instance(), monitoring_module::critical_metrics_snapshot::memory_usage_bytes, monitoring_interface::system_metrics::memory_usage_bytes, metrics_collected, monitoring_module::monitoring_crash_safety::preserve_critical_metrics(), and monitoring_module::critical_metrics_snapshot::timestamp.
Referenced by main().
on_alert_system_crash()
void on_alert_system_crash (const std::string & crash_info)
Definition at line 190 of file main.cpp.
Referenced by main().
on_monitoring_component_crash()
void on_monitoring_component_crash (const std::string & component_name)
Definition at line 174 of file main.cpp.
References monitoring_module::monitoring_crash_safety::force_save_all_states(), monitoring_module::monitoring_crash_safety::instance(), and monitoring_active.
on_ring_buffer_overflow()
void on_ring_buffer_overflow (size_t lost_entries)
Definition at line 182 of file main.cpp.
References monitoring_module::ring_buffer_crash_safety::create_emergency_snapshot().
Referenced by main().
restore_collector_state()
void restore_collector_state (const std::string & state)
Definition at line 216 of file main.cpp.
Referenced by main().
restore_monitoring_state()
void restore_monitoring_state (const std::string & state)
Definition at line 205 of file main.cpp.
Referenced by main().
risky_monitoring_task()
void risky_monitoring_task (int task_id)
Definition at line 132 of file main.cpp.
References monitoring_module::critical_metrics_snapshot::active_threads, monitoring_module::critical_metrics_snapshot::cpu_usage_percent, monitoring_module::critical_metrics_snapshot::crash_context, monitoring_module::monitoring_crash_safety::instance(), monitoring_module::critical_metrics_snapshot::memory_usage_bytes, metrics_collected, monitoring_module::monitoring_crash_safety::preserve_critical_metrics(), simulate_alert_system_failure(), simulate_monitoring_crash(), simulate_ring_buffer_overflow(), and monitoring_module::critical_metrics_snapshot::timestamp.
Referenced by main().
save_collector_state()
std::string save_collector_state ()
Definition at line 210 of file main.cpp.
Referenced by main().
save_monitoring_state()
std::string save_monitoring_state ()
Definition at line 198 of file main.cpp.
References alerts_sent, critical_snapshots, and metrics_collected.
Referenced by main().
simulate_alert_system_failure()
void simulate_alert_system_failure ()
Definition at line 51 of file main.cpp.
Referenced by risky_monitoring_task().
simulate_monitoring_crash()
void simulate_monitoring_crash ()
Definition at line 41 of file main.cpp.
Referenced by risky_monitoring_task().
simulate_ring_buffer_overflow()
void simulate_ring_buffer_overflow ()
Definition at line 46 of file main.cpp.
Referenced by risky_monitoring_task().
thread_pool_monitoring_task()
void thread_pool_monitoring_task (int monitor_id)
Definition at line 93 of file main.cpp.
References alerts_sent, monitoring_interface::thread_pool_metrics::average_latency_ns, monitoring_interface::thread_pool_metrics::jobs_completed, monitoring_interface::thread_pool_metrics::jobs_failed, monitoring_interface::thread_pool_metrics::jobs_pending, metrics_collected, and monitoring_interface::thread_pool_metrics::worker_threads.
Referenced by main().
Variable Documentation
alerts_sent
std::atomic<int> alerts_sent {0}
Definition at line 29 of file main.cpp.
Referenced by main(), save_monitoring_state(), and thread_pool_monitoring_task().
critical_snapshots
std::atomic<int> critical_snapshots {0}
Definition at line 30 of file main.cpp.
Referenced by main(), metrics_collection_task(), and save_monitoring_state().
metrics_collected
std::atomic<int> metrics_collected {0}
Definition at line 28 of file main.cpp.
Referenced by main(), metrics_collection_task(), risky_monitoring_task(), save_monitoring_state(), and thread_pool_monitoring_task().
monitoring_active
std::atomic<bool> monitoring_active {true}
Definition at line 27 of file main.cpp.
Referenced by main(), and on_monitoring_component_crash().