Messaging System: monitoring_system::online_statistics Class Reference
monitoring_system::online_statistics Class Reference
Online algorithm for computing statistics.
#include <stream_aggregator.h>
Public Member Functions
void add_value (double value)
Add a value to the statistics.
stream_statistics get_statistics () const
Get current statistics.
void reset ()
Reset statistics.
uint64_t count () const noexcept
Get sample count.
double mean () const noexcept
Get current mean.
double variance () const noexcept
Get current variance.
Detailed Description
Online algorithm for computing statistics.
Definition at line 133 of file stream_aggregator.h.
Member Function Documentation
add_value()
void monitoring_system::online_statistics::add_value (double value) inline
Add a value to the statistics.
Definition at line 148 of file stream_aggregator.h.
References monitoring_system::delta.
Referenced by monitoring_system::stream_aggregator::add_observation(), TEST_F(), and TEST_F().
count()
uint64_t monitoring_system::online_statistics::count () const inline noexcept
Get sample count.
Definition at line 215 of file stream_aggregator.h.
Referenced by monitoring_system::stream_aggregator::add_observation(), monitoring_system::stream_aggregator::count(), and TEST_F().
get_statistics()
stream_statistics monitoring_system::online_statistics::get_statistics () const inline
Get current statistics.
Definition at line 175 of file stream_aggregator.h.
References monitoring_system::stream_statistics::count, monitoring_system::stream_statistics::kurtosis, monitoring_system::stream_statistics::max_value, monitoring_system::stream_statistics::mean, monitoring_system::stream_statistics::min_value, monitoring_system::stream_statistics::skewness, monitoring_system::stream_statistics::std_deviation, monitoring_system::stream_statistics::sum, and monitoring_system::stream_statistics::variance.
Referenced by monitoring_system::stream_aggregator::get_statistics(), TEST_F(), and TEST_F().
mean()
double monitoring_system::online_statistics::mean () const inline noexcept
Get current mean.
Definition at line 220 of file stream_aggregator.h.
Referenced by monitoring_system::stream_aggregator::mean(), and TEST_F().
reset()
void monitoring_system::online_statistics::reset () inline
Reset statistics.
Definition at line 201 of file stream_aggregator.h.
Referenced by monitoring_system::stream_aggregator::reset().
variance()
double monitoring_system::online_statistics::variance () const inline noexcept
Get current variance.
Definition at line 225 of file stream_aggregator.h.
Referenced by TEST_F(), and monitoring_system::stream_aggregator::variance().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/stream_aggregator.h