Messaging System: kcenon::logger::console_writer Class Reference
kcenon::logger::console_writer Class Reference
Console writer that outputs logs to stdout/stderr.
#include <console_writer.h>
Public Member Functions
console_writer (bool use_stderr=false, bool auto_detect_color=true)
Constructor.
~console_writer () override
Destructor.
result_void write (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write log entry to console.
result_void flush () override
Flush console output.
std::string get_name () const override
Get writer name.
void set_use_stderr (bool use_stderr)
Set whether to use stderr for all output.
Public Member Functions inherited from kcenon::logger::base_writer
virtual ~base_writer ()=default
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
virtual bool is_healthy () const override
Check if the writer is healthy and operational.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
Additional Inherited Members
Protected Member Functions inherited from kcenon::logger::base_writer
std::string format_log_entry (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (logger_system::log_level level) const
Convert log level to string representation.
std::string level_to_color (logger_system::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
Console writer that outputs logs to stdout/stderr.
Features:
Color support for different log levels (if terminal supports it)
Thread-safe console output
Error levels go to stderr, others to stdout
Definition at line 48 of file console_writer.h.
Constructor & Destructor Documentation
console_writer()
kcenon::logger::console_writer::console_writer (bool use_stderr = false, bool auto_detect_color = true) explicit
Constructor.
Parameters
use_stderr If true, all output goes to stderr (default: false)
auto_detect_color Auto-detect terminal color support (default: true)
Definition at line 48 of file console_writer.cpp.
References kcenon::logger::base_writer::set_use_color().
~console_writer()
kcenon::logger::console_writer::~console_writer () override
Destructor.
Definition at line 55 of file console_writer.cpp.
References flush().
Member Function Documentation
flush()
result_void kcenon::logger::console_writer::flush () override virtual
Flush console output.
Implements kcenon::logger::base_writer.
Definition at line 91 of file console_writer.cpp.
References kcenon::logger::flush_timeout, and kcenon::logger::make_logger_error().
Referenced by ~console_writer().
get_name()
std::string kcenon::logger::console_writer::get_name () const inline override virtual
Get writer name.
Implements kcenon::logger::base_writer.
Definition at line 80 of file console_writer.h.
set_use_stderr()
void kcenon::logger::console_writer::set_use_stderr (bool use_stderr)
Set whether to use stderr for all output.
Parameters
use_stderr Enable/disable stderr usage
Definition at line 104 of file console_writer.cpp.
write()
result_void kcenon::logger::console_writer::write (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write log entry to console.
Implements kcenon::logger::base_writer.
Definition at line 59 of file console_writer.cpp.
References kcenon::logger::base_writer::format_log_entry(), kcenon::logger::base_writer::level_to_color(), kcenon::logger::make_logger_error(), kcenon::logger::processing_failed, and kcenon::logger::base_writer::use_color().
The documentation for this class was generated from the following files:
libraries/logger_system/include/kcenon/logger/writers/console_writer.h
libraries/logger_system/src/impl/writers/console_writer.cpp