Messaging System: monitoring_module::ring_buffer_crash_safety Class Reference
monitoring_module::ring_buffer_crash_safety Class Reference
Ring buffer crash safety extensions.
#include <monitoring_crash_safety.h>
Static Public Member Functions
static void configure_ring_buffer_safety (const std::string &buffer_name, bool persistent_backup=true, double backup_threshold=0.8)
Configure crash safety for ring buffer.
static void set_overflow_handler (const std::string &buffer_name, std::function< void(size_t lost_entries)> overflow_callback)
Set ring buffer overflow handler.
static void create_emergency_snapshot (const std::string &buffer_name, const std::vector< uint8_t > &data_snapshot)
Create emergency snapshot of ring buffer data.
Detailed Description
Ring buffer crash safety extensions.
Definition at line 255 of file monitoring_crash_safety.h.
Member Function Documentation
configure_ring_buffer_safety()
static void monitoring_module::ring_buffer_crash_safety::configure_ring_buffer_safety (const std::string & buffer_name, bool persistent_backup = true, double backup_threshold = 0.8) static
Configure crash safety for ring buffer.
Parameters
buffer_name Name of the ring buffer
persistent_backup Whether to create persistent backup
backup_threshold Backup when buffer reaches this percentage full
Referenced by main().
create_emergency_snapshot()
static void monitoring_module::ring_buffer_crash_safety::create_emergency_snapshot (const std::string & buffer_name, const std::vector< uint8_t > & data_snapshot) static
Create emergency snapshot of ring buffer data.
Parameters
buffer_name Name of the buffer
data_snapshot Buffer data to preserve
Referenced by on_ring_buffer_overflow().
set_overflow_handler()
static void monitoring_module::ring_buffer_crash_safety::set_overflow_handler (const std::string & buffer_name, std::function< void(size_t lost_entries)> overflow_callback) static
Set ring buffer overflow handler.
Parameters
buffer_name Name of the buffer
overflow_callback Function to handle overflow
Referenced by main().
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/interfaces/monitoring_crash_safety.h