Messaging System: libraries/thread_system/benchmarks/thread_base_benchmarks/simple_mpmc_benchmark.cpp File Reference
simple_mpmc_benchmark.cpp File Reference
Google Benchmark tests for MPMC queue implementations.
#include <benchmark/benchmark.h>
#include <atomic>
#include <vector>
#include <thread>
#include "job_queue.h"
#include "lockfree/queues/lockfree_job_queue.h"
#include "lockfree/queues/adaptive_job_queue.h"
#include "callback_job.h"
Functions
static void BM_MutexQueue_SPSC (benchmark::State &state)
Benchmark mutex-based queue with single producer/consumer.
BENCHMARK (BM_MutexQueue_SPSC) -> Arg(10000) ->Arg(100000)
static void BM_LockFreeQueue_SPSC (benchmark::State &state)
Benchmark lock-free queue with single producer/consumer.
BENCHMARK (BM_LockFreeQueue_SPSC) -> Arg(10000) ->Arg(100000)
static void BM_AdaptiveQueue_SPSC (benchmark::State &state)
Benchmark adaptive queue with single producer/consumer.
BENCHMARK (BM_AdaptiveQueue_SPSC) -> Arg(10000) ->Arg(100000)
template<typename QueueType >
static void BM_Queue_MPMC (benchmark::State &state)
Template function for MPMC benchmarks.
Args ({2, 2, 5000}) -> Args({4, 4, 2500}) ->Args({8, 8, 1250})
template<typename QueueType >
static void BM_Queue_Latency (benchmark::State &state)
Benchmark queue latency under contention.
Arg (1) -> Arg(2) ->Arg(4) ->Arg(8) ->UseManualTime()
template<typename QueueType >
static void BM_Queue_Batch (benchmark::State &state)
Benchmark batch operations.
Arg (10) -> Arg(100) ->Arg(1000)
BENCHMARK_MAIN ()
Detailed Description
Google Benchmark tests for MPMC queue implementations.
This file benchmarks different queue implementations:
Mutex-based queue (job_queue)
Lock-free MPMC queue (lockfree_job_queue)
Adaptive queue (adaptive_job_queue)
Tests measure throughput, latency, and scalability under various contention scenarios following Google Benchmark best practices.
Definition in file simple_mpmc_benchmark.cpp.
Function Documentation
Arg() [1/2]
Arg (1) -> Arg(2) ->Arg(4) ->Arg(8) ->UseManualTime()
Arg() [2/2]
Arg (10) -> Arg(100) ->Arg(1000)
Args()
Args ({2, 2, 5000}) -> Args({4, 4, 2500}) ->Args({8, 8, 1250})
BENCHMARK() [1/3]
BENCHMARK (BM_AdaptiveQueue_SPSC) -> Arg(10000) ->Arg(100000)
BENCHMARK() [2/3]
BENCHMARK (BM_LockFreeQueue_SPSC) -> Arg(10000) ->Arg(100000)
BENCHMARK() [3/3]
BENCHMARK (BM_MutexQueue_SPSC) -> Arg(10000) ->Arg(100000)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_AdaptiveQueue_SPSC()
static void BM_AdaptiveQueue_SPSC (benchmark::State & state) static
Benchmark adaptive queue with single producer/consumer.
Definition at line 125 of file simple_mpmc_benchmark.cpp.
References thread_module::adaptive_job_queue::enqueue().
BM_LockFreeQueue_SPSC()
static void BM_LockFreeQueue_SPSC (benchmark::State & state) static
Benchmark lock-free queue with single producer/consumer.
Definition at line 82 of file simple_mpmc_benchmark.cpp.
References thread_module::lockfree_job_queue::enqueue().
BM_MutexQueue_SPSC()
static void BM_MutexQueue_SPSC (benchmark::State & state) static
Benchmark mutex-based queue with single producer/consumer.
Measures the baseline performance with no contention.
Definition at line 39 of file simple_mpmc_benchmark.cpp.
References thread_module::job_queue::enqueue().
BM_Queue_Batch()
template<typename QueueType > static void BM_Queue_Batch (benchmark::State & state) static
Benchmark batch operations.
Measures performance when enqueuing/dequeuing multiple items at once.
Definition at line 328 of file simple_mpmc_benchmark.cpp.
References thread_module::job::do_work(), thread_module::result< T >::has_value(), and thread_module::result< T >::value().
BM_Queue_Latency()
template<typename QueueType > static void BM_Queue_Latency (benchmark::State & state) static
Benchmark queue latency under contention.
Measures the time for a single enqueue/dequeue operation when multiple threads are competing.
Definition at line 254 of file simple_mpmc_benchmark.cpp.
References thread_module::result< T >::has_value(), and thread_module::result< T >::value().
BM_Queue_MPMC()
template<typename QueueType > static void BM_Queue_MPMC (benchmark::State & state) static
Template function for MPMC benchmarks.
Tests queue performance with multiple producers and consumers.
Definition at line 171 of file simple_mpmc_benchmark.cpp.
References thread_module::result< T >::has_value(), and thread_module::result< T >::value().