Messaging System: monitoring_system::time_based_strategy Class Reference
monitoring_system::time_based_strategy Class Reference
Time-based buffering strategy.
#include <buffering_strategy.h>
Public Member Functions
time_based_strategy (const buffering_config &config)
result_void add_metric (buffered_metric &&metric) override
Add metric to buffer.
result< std::vector< buffered_metric > > flush () override
Flush buffer contents.
bool should_flush () const override
Check if flush is needed.
size_t size () const override
Get current buffer size.
const buffer_statistics & get_statistics () const override
Get buffer statistics.
void clear () override
Clear buffer.
const buffering_config & get_config () const override
Get configuration.
Public Member Functions inherited from monitoring_system::buffer_strategy_interface
virtual ~buffer_strategy_interface ()=default
Detailed Description
Time-based buffering strategy.
Definition at line 514 of file buffering_strategy.h.
Constructor & Destructor Documentation
time_based_strategy()
monitoring_system::time_based_strategy::time_based_strategy (const buffering_config & config) inline explicit
Definition at line 524 of file buffering_strategy.h.
References monitoring_system::buffering_config::max_buffer_size, and monitoring_system::buffering_config::strategy.
Member Function Documentation
add_metric()
result_void monitoring_system::time_based_strategy::add_metric (buffered_metric && metric) inline override virtual
Add metric to buffer.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 530 of file buffering_strategy.h.
References monitoring_system::buffer_statistics::forced_flushes, monitoring_system::buffering_config::max_buffer_size, and monitoring_system::buffer_statistics::total_items_buffered.
Referenced by TEST_F(), and TEST_F().
clear()
void monitoring_system::time_based_strategy::clear () inline override virtual
Clear buffer.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 597 of file buffering_strategy.h.
flush()
result< std::vector< buffered_metric > > monitoring_system::time_based_strategy::flush () inline override virtual
Flush buffer contents.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 548 of file buffering_strategy.h.
References monitoring_system::make_success(), monitoring_system::buffer_statistics::total_flushes, and monitoring_system::buffer_statistics::total_items_flushed.
Referenced by TEST_F().
get_config()
const buffering_config & monitoring_system::time_based_strategy::get_config () const inline override virtual
Get configuration.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 603 of file buffering_strategy.h.
get_statistics()
const buffer_statistics & monitoring_system::time_based_strategy::get_statistics () const inline override virtual
Get buffer statistics.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 593 of file buffering_strategy.h.
should_flush()
bool monitoring_system::time_based_strategy::should_flush () const inline override virtual
Check if flush is needed.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 572 of file buffering_strategy.h.
References monitoring_system::buffering_config::flush_interval, and monitoring_system::buffering_config::max_buffer_size.
Referenced by TEST_F(), and TEST_F().
size()
size_t monitoring_system::time_based_strategy::size () const inline override virtual
Get current buffer size.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 588 of file buffering_strategy.h.
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/buffering_strategy.h