Messaging System: logger_module::log_router Class Reference
logger_module::log_router Class Reference
Routes log messages to specific writers based on filters.
#include <log_router.h>
Public Member Functions
log_router ()=default
void add_route (std::unique_ptr< log_filter > filter, const std::vector< std::string > &writer_names, bool stop_propagation=false)
Add a routing rule.
std::vector< base_writer * > route (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp, const std::unordered_map< std::string, std::unique_ptr< base_writer > > &writers) const
Route a log message to appropriate writers.
void set_exclusive_routes (bool exclusive)
Set whether routes are exclusive (no default fallback)
void clear_routes ()
Clear all routes.
Detailed Description
Routes log messages to specific writers based on filters.
Definition at line 56 of file log_router.h.
Constructor & Destructor Documentation
log_router()
logger_module::log_router::log_router () default
Member Function Documentation
add_route()
void logger_module::log_router::add_route (std::unique_ptr< log_filter > filter, const std::vector< std::string > & writer_names, bool stop_propagation = false) inline
Add a routing rule.
Parameters
filter Filter to apply
writer_names Names of writers to route to
stop_propagation Stop processing other routes if this matches
Definition at line 66 of file log_router.h.
Referenced by logger_module::router_builder::route_to().
clear_routes()
void logger_module::log_router::clear_routes () inline
Clear all routes.
Definition at line 137 of file log_router.h.
route()
std::vector< base_writer * > logger_module::log_router::route (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp, const std::unordered_map< std::string, std::unique_ptr< base_writer > > & writers) const inline
Route a log message to appropriate writers.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
timestamp Timestamp
writers Map of available writers
Returns
Vector of writers that should process this log
Definition at line 83 of file log_router.h.
References route().
Referenced by route().
set_exclusive_routes()
void logger_module::log_router::set_exclusive_routes (bool exclusive) inline
Set whether routes are exclusive (no default fallback)
Definition at line 130 of file log_router.h.
The documentation for this class was generated from the following file:
libraries/logger_system/sources/logger/routing/log_router.h