Messaging System: kcenon::messaging::core::production_message_allocator Class Reference
kcenon::messaging::core::production_message_allocator Class Reference
#include <production_optimizations.h>
Classes
struct allocator_stats
Public Member Functions
production_message_allocator (size_t message_pool_size=1000, size_t payload_pool_size=1000)
std::unique_ptr< message > allocate_message ()
void deallocate_message (std::unique_ptr< message > msg)
std::unique_ptr< message_payload > allocate_payload ()
void deallocate_payload (std::unique_ptr< message_payload > payload)
allocator_stats get_stats () const
Detailed Description
Definition at line 99 of file production_optimizations.h.
Constructor & Destructor Documentation
production_message_allocator()
kcenon::messaging::core::production_message_allocator::production_message_allocator (size_t message_pool_size = 1000, size_t payload_pool_size = 1000) inline
Definition at line 105 of file production_optimizations.h.
Member Function Documentation
allocate_message()
std::unique_ptr< message > kcenon::messaging::core::production_message_allocator::allocate_message () inline
Definition at line 108 of file production_optimizations.h.
References kcenon::messaging::core::object_pool< T >::acquire().
allocate_payload()
std::unique_ptr< message_payload > kcenon::messaging::core::production_message_allocator::allocate_payload () inline
Definition at line 116 of file production_optimizations.h.
References kcenon::messaging::core::object_pool< T >::acquire().
deallocate_message()
void kcenon::messaging::core::production_message_allocator::deallocate_message (std::unique_ptr< message > msg) inline
Definition at line 112 of file production_optimizations.h.
References kcenon::messaging::core::object_pool< T >::release().
deallocate_payload()
void kcenon::messaging::core::production_message_allocator::deallocate_payload (std::unique_ptr< message_payload > payload) inline
Definition at line 120 of file production_optimizations.h.
References kcenon::messaging::core::object_pool< T >::release().
get_stats()
allocator_stats kcenon::messaging::core::production_message_allocator::get_stats () const inline
Definition at line 133 of file production_optimizations.h.
References kcenon::messaging::core::object_pool< T >::hit_ratio(), kcenon::messaging::core::object_pool< T >::size(), and kcenon::messaging::core::object_pool< T >::total_created().
The documentation for this class was generated from the following file:
application_layer/include/kcenon/messaging/core/production_optimizations.h