Messaging System: database::mongodb_manager Class Reference
database::mongodb_manager Class Reference
Manages MongoDB database operations.
#include <mongodb_manager.h>
Public Member Functions
mongodb_manager (void)
Default constructor.
virtual ~mongodb_manager (void)
Destructor.
database_types database_type (void) override
Returns the specific type of the database.
bool connect (const std::string &connect_string) override
Establishes a connection to a MongoDB database using the provided connection URI.
bool create_query (const std::string &query_string) override
Creates a query (e.g., creates collection or index) using the provided command string.
unsigned int insert_query (const std::string &query_string) override
Executes an INSERT operation on the connected MongoDB database.
unsigned int update_query (const std::string &query_string) override
Executes an UPDATE operation on the connected MongoDB database.
unsigned int delete_query (const std::string &query_string) override
Executes a DELETE operation on the connected MongoDB database.
database_result select_query (const std::string &query_string) override
Executes a FIND operation on the connected MongoDB database and returns the resulting documents.
bool execute_query (const std::string &query_string) override
Executes a general MongoDB command (DDL, DML, admin operations).
bool disconnect (void) override
Closes the connection to the MongoDB database.
bool insert_document (const std::string &collection_name, const std::string &document_json)
Inserts a document into the specified collection.
database_result find_documents (const std::string &collection_name, const std::string &query_json)
Finds documents in the specified collection matching the query.
unsigned int update_documents (const std::string &collection_name, const std::string &filter_json, const std::string &update_json)
Updates documents in the specified collection.
unsigned int delete_documents (const std::string &collection_name, const std::string &filter_json)
Deletes documents from the specified collection.
Public Member Functions inherited from database::database_base
database_base (void)
Default constructor.
virtual ~database_base (void)
Virtual destructor.
Detailed Description
Manages MongoDB database operations.
This class provides an implementation of the database_base interface for MongoDB databases. It defines methods for connecting, document operations, and disconnecting from a MongoDB database using the MongoDB C++ driver.
Definition at line 48 of file mongodb_manager.h.
Constructor & Destructor Documentation
mongodb_manager()
database::mongodb_manager::mongodb_manager (void)
Default constructor.
Definition at line 53 of file mongodb_manager.cpp.
~mongodb_manager()
database::mongodb_manager::~mongodb_manager (void) virtual
Destructor.
Definition at line 55 of file mongodb_manager.cpp.
References disconnect().
Member Function Documentation
connect()
bool database::mongodb_manager::connect (const std::string & connect_string) override virtual
Establishes a connection to a MongoDB database using the provided connection URI.
Parameters
connect_string A MongoDB connection URI string Format: "mongodb://username:password@host:port/database"
Returns
true if the connection is successfully established, false otherwise.
Implements database::database_base.
Definition at line 65 of file mongodb_manager.cpp.
create_query()
bool database::mongodb_manager::create_query (const std::string & query_string) override virtual
Creates a query (e.g., creates collection or index) using the provided command string.
Parameters
query_string The MongoDB command to create or execute.
Returns
true if the command is successfully executed, false otherwise.
Implements database::database_base.
Definition at line 107 of file mongodb_manager.cpp.
Referenced by execute_query().
database_type()
database_types database::mongodb_manager::database_type (void) override virtual
Returns the specific type of the database.
Returns
An enum value of type database_types indicating that this is a MongoDB database.
Implements database::database_base.
Definition at line 60 of file mongodb_manager.cpp.
References database::mongodb.
delete_documents()
unsigned int database::mongodb_manager::delete_documents (const std::string & collection_name, const std::string & filter_json)
Deletes documents from the specified collection.
Parameters
collection_name Name of the collection
filter_json JSON string representation of the filter
Returns
Number of documents deleted
Definition at line 351 of file mongodb_manager.cpp.
References delete_query().
delete_query()
unsigned int database::mongodb_manager::delete_query (const std::string & query_string) override virtual
Executes a DELETE operation on the connected MongoDB database.
For MongoDB, this translates to deleting documents.
Parameters
query_string Delete operation (format: "collection_name:filter_json")
Returns
The number of documents deleted, or 0 if failed.
Implements database::database_base.
Definition at line 192 of file mongodb_manager.cpp.
Referenced by delete_documents().
disconnect()
bool database::mongodb_manager::disconnect (void) override virtual
Closes the connection to the MongoDB database.
Returns
true if the disconnection is successful, false otherwise.
Implements database::database_base.
Definition at line 314 of file mongodb_manager.cpp.
Referenced by ~mongodb_manager().
execute_query()
bool database::mongodb_manager::execute_query (const std::string & query_string) override virtual
Executes a general MongoDB command (DDL, DML, admin operations).
Parameters
query_string The MongoDB command string to execute.
Returns
true if the command executed successfully, false otherwise.
Implements database::database_base.
Definition at line 282 of file mongodb_manager.cpp.
References create_query().
find_documents()
database_result database::mongodb_manager::find_documents (const std::string & collection_name, const std::string & query_json)
Finds documents in the specified collection matching the query.
Parameters
collection_name Name of the collection
query_json JSON string representation of the query filter
Returns
database_result containing matching documents
Definition at line 337 of file mongodb_manager.cpp.
References select_query().
insert_document()
bool database::mongodb_manager::insert_document (const std::string & collection_name, const std::string & document_json)
Inserts a document into the specified collection.
Parameters
collection_name Name of the collection
document_json JSON string representation of the document
Returns
true if insertion successful, false otherwise
Definition at line 331 of file mongodb_manager.cpp.
References insert_query().
insert_query()
unsigned int database::mongodb_manager::insert_query (const std::string & query_string) override virtual
Executes an INSERT operation on the connected MongoDB database.
For MongoDB, this translates to inserting a document.
Parameters
query_string JSON document to insert (format: "collection_name:document_json")
Returns
The number of documents inserted, or 0 if failed.
Implements database::database_base.
Definition at line 135 of file mongodb_manager.cpp.
Referenced by insert_document().
select_query()
database_result database::mongodb_manager::select_query (const std::string & query_string) override virtual
Executes a FIND operation on the connected MongoDB database and returns the resulting documents.
Parameters
query_string Find operation (format: "collection_name:filter_json")
Returns
A database_result containing documents as key-value pairs.
Implements database::database_base.
Definition at line 220 of file mongodb_manager.cpp.
Referenced by find_documents().
update_documents()
unsigned int database::mongodb_manager::update_documents (const std::string & collection_name, const std::string & filter_json, const std::string & update_json)
Updates documents in the specified collection.
Parameters
collection_name Name of the collection
filter_json JSON string representation of the filter
update_json JSON string representation of the update operation
Returns
Number of documents updated
Definition at line 343 of file mongodb_manager.cpp.
References update_query().
update_query()
unsigned int database::mongodb_manager::update_query (const std::string & query_string) override virtual
Executes an UPDATE operation on the connected MongoDB database.
For MongoDB, this translates to updating documents.
Parameters
query_string Update operation (format: "collection_name:filter_json:update_json")
Returns
The number of documents updated, or 0 if failed.
Implements database::database_base.
Definition at line 163 of file mongodb_manager.cpp.
Referenced by update_documents().
The documentation for this class was generated from the following files:
libraries/database_system/database/backends/mongodb/mongodb_manager.h
libraries/database_system/database/backends/mongodb/mongodb_manager.cpp