Messaging System: libraries/logger_system/tests/unit/monitoring_test/monitoring_test.cpp File Reference
monitoring_test.cpp File Reference
Unit tests for monitoring implementations.
#include <gtest/gtest.h>
#include "../../sources/logger/monitoring/basic_monitor.h"
#include "../../sources/logger/monitoring/monitoring_factory.h"
#include <thread>
#include <chrono>
Classes
class monitoring_test
Functions
TEST_F (monitoring_test, basic_monitor_initial_state)
TEST_F (monitoring_test, basic_monitor_enable_disable)
TEST_F (monitoring_test, basic_monitor_counter_increment)
TEST_F (monitoring_test, basic_monitor_gauge_update)
TEST_F (monitoring_test, basic_monitor_histogram_recording)
TEST_F (monitoring_test, basic_monitor_health_check_healthy)
TEST_F (monitoring_test, basic_monitor_health_check_with_errors)
TEST_F (monitoring_test, basic_monitor_health_check_degraded)
TEST_F (monitoring_test, basic_monitor_reset_metrics)
TEST_F (monitoring_test, basic_monitor_disabled_metrics)
TEST_F (monitoring_test, basic_monitor_core_metrics)
TEST (monitoring_factory_test, create_basic_monitor)
TEST (monitoring_factory_test, create_automatic_monitor)
TEST (monitoring_factory_test, create_best_available)
TEST (monitoring_factory_test, get_monitor_type_name)
TEST (monitoring_factory_test, get_available_type)
TEST (health_status_test, string_conversion)
TEST (metric_type_test, string_conversion)
TEST_F (monitoring_test, basic_monitor_thread_safety)
TEST_F (monitoring_test, basic_monitor_performance_metrics)
TEST_F (monitoring_test, basic_monitor_uptime)
Detailed Description
Unit tests for monitoring implementations.
Definition in file monitoring_test.cpp.
Function Documentation
TEST() [1/7]
TEST (health_status_test , string_conversion)
Definition at line 310 of file monitoring_test.cpp.
References kcenon::logger::health_status_to_string().
TEST() [2/7]
TEST (metric_type_test , string_conversion)
Definition at line 317 of file monitoring_test.cpp.
References kcenon::logger::metric_type_to_string().
TEST() [3/7]
TEST (monitoring_factory_test , create_automatic_monitor)
Definition at line 278 of file monitoring_test.cpp.
References kcenon::logger::monitoring::monitoring_factory::automatic.
TEST() [4/7]
TEST (monitoring_factory_test , create_basic_monitor)
Definition at line 269 of file monitoring_test.cpp.
References kcenon::logger::monitoring::monitoring_factory::basic.
TEST() [5/7]
TEST (monitoring_factory_test , create_best_available)
Definition at line 287 of file monitoring_test.cpp.
TEST() [6/7]
TEST (monitoring_factory_test , get_available_type)
Definition at line 301 of file monitoring_test.cpp.
References kcenon::logger::monitoring::monitoring_factory::basic.
TEST() [7/7]
TEST (monitoring_factory_test , get_monitor_type_name)
Definition at line 294 of file monitoring_test.cpp.
References kcenon::logger::monitoring::monitoring_factory::automatic, and kcenon::logger::monitoring::monitoring_factory::basic.
TEST_F() [1/14]
TEST_F (monitoring_test , basic_monitor_core_metrics)
Definition at line 235 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().
TEST_F() [2/14]
TEST_F (monitoring_test , basic_monitor_counter_increment)
Definition at line 57 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().
TEST_F() [3/14]
TEST_F (monitoring_test , basic_monitor_disabled_metrics)
Definition at line 225 of file monitoring_test.cpp.
References kcenon::logger::result< T >::error_code().
TEST_F() [4/14]
TEST_F (monitoring_test , basic_monitor_enable_disable)
Definition at line 42 of file monitoring_test.cpp.
TEST_F() [5/14]
TEST_F (monitoring_test , basic_monitor_gauge_update)
Definition at line 83 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().
TEST_F() [6/14]
TEST_F (monitoring_test , basic_monitor_health_check_degraded)
Definition at line 182 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().
TEST_F() [7/14]
TEST_F (monitoring_test , basic_monitor_health_check_healthy)
Definition at line 153 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().
TEST_F() [8/14]
TEST_F (monitoring_test , basic_monitor_health_check_with_errors)
Definition at line 164 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().
TEST_F() [9/14]
TEST_F (monitoring_test , basic_monitor_histogram_recording)
Definition at line 109 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().
TEST_F() [10/14]
TEST_F (monitoring_test , basic_monitor_initial_state)
Definition at line 37 of file monitoring_test.cpp.
TEST_F() [11/14]
TEST_F (monitoring_test , basic_monitor_performance_metrics)
Definition at line 371 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().
TEST_F() [12/14]
TEST_F (monitoring_test , basic_monitor_reset_metrics)
Definition at line 199 of file monitoring_test.cpp.
TEST_F() [13/14]
TEST_F (monitoring_test , basic_monitor_thread_safety)
Definition at line 325 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().
TEST_F() [14/14]
TEST_F (monitoring_test , basic_monitor_uptime)
Definition at line 414 of file monitoring_test.cpp.
References kcenon::logger::result< T >::value().