var annotated_dup =
[
    [ "container_module", "d1/d1a/namespacecontainer__module.html", [
      [ "simd", "dd/ddc/namespacecontainer__module_1_1simd.html", [
        [ "simd_compressor", "d0/de6/classcontainer__module_1_1simd_1_1simd__compressor.html", "d0/de6/classcontainer__module_1_1simd_1_1simd__compressor" ],
        [ "simd_processor", "db/dfe/classcontainer__module_1_1simd_1_1simd__processor.html", "db/dfe/classcontainer__module_1_1simd_1_1simd__processor" ],
        [ "simd_support", "d5/da4/classcontainer__module_1_1simd_1_1simd__support.html", "d5/da4/classcontainer__module_1_1simd_1_1simd__support" ],
        [ "simd_traits", "d5/db5/structcontainer__module_1_1simd_1_1simd__traits.html", "d5/db5/structcontainer__module_1_1simd_1_1simd__traits" ]
      ] ],
      [ "bool_value", "d7/d22/classcontainer__module_1_1bool__value.html", "d7/d22/classcontainer__module_1_1bool__value" ],
      [ "bytes_value", "df/df7/classcontainer__module_1_1bytes__value.html", "df/df7/classcontainer__module_1_1bytes__value" ],
      [ "container_value", "da/d1c/classcontainer__module_1_1container__value.html", "da/d1c/classcontainer__module_1_1container__value" ],
      [ "is_variant_type", "d9/d6f/structcontainer__module_1_1is__variant__type.html", null ],
      [ "is_variant_type< bool >", "da/d46/structcontainer__module_1_1is__variant__type_3_01bool_01_4.html", null ],
      [ "is_variant_type< double >", "da/de8/structcontainer__module_1_1is__variant__type_3_01double_01_4.html", null ],
      [ "is_variant_type< float >", "df/de0/structcontainer__module_1_1is__variant__type_3_01float_01_4.html", null ],
      [ "is_variant_type< int16_t >", "d4/dec/structcontainer__module_1_1is__variant__type_3_01int16__t_01_4.html", null ],
      [ "is_variant_type< int32_t >", "d4/d1c/structcontainer__module_1_1is__variant__type_3_01int32__t_01_4.html", null ],
      [ "is_variant_type< int64_t >", "d4/d8a/structcontainer__module_1_1is__variant__type_3_01int64__t_01_4.html", null ],
      [ "is_variant_type< std::monostate >", "d6/d73/structcontainer__module_1_1is__variant__type_3_01std_1_1monostate_01_4.html", null ],
      [ "is_variant_type< std::shared_ptr< thread_safe_container > >", "d9/dd6/structcontainer__module_1_1is__variant__type_3_01std_1_1shared__ptr_3_01thread__safe__container_01_4_01_4.html", null ],
      [ "is_variant_type< std::string >", "db/dc6/structcontainer__module_1_1is__variant__type_3_01std_1_1string_01_4.html", null ],
      [ "is_variant_type< std::vector< uint8_t > >", "de/d89/structcontainer__module_1_1is__variant__type_3_01std_1_1vector_3_01uint8__t_01_4_01_4.html", null ],
      [ "is_variant_type< uint16_t >", "d8/dce/structcontainer__module_1_1is__variant__type_3_01uint16__t_01_4.html", null ],
      [ "is_variant_type< uint32_t >", "d6/d4c/structcontainer__module_1_1is__variant__type_3_01uint32__t_01_4.html", null ],
      [ "is_variant_type< uint64_t >", "d7/dc4/structcontainer__module_1_1is__variant__type_3_01uint64__t_01_4.html", null ],
      [ "lockfree_reader", "d8/df9/classcontainer__module_1_1lockfree__reader.html", "d8/df9/classcontainer__module_1_1lockfree__reader" ],
      [ "numeric_value", "de/dc4/classcontainer__module_1_1numeric__value.html", "de/dc4/classcontainer__module_1_1numeric__value" ],
      [ "string_value", "d5/d22/classcontainer__module_1_1string__value.html", "d5/d22/classcontainer__module_1_1string__value" ],
      [ "thread_safe_container", "db/de5/classcontainer__module_1_1thread__safe__container.html", "db/de5/classcontainer__module_1_1thread__safe__container" ],
      [ "value", "d5/df9/classcontainer__module_1_1value.html", "d5/df9/classcontainer__module_1_1value" ],
      [ "value_container", "d9/dad/classcontainer__module_1_1value__container.html", "d9/dad/classcontainer__module_1_1value__container" ],
      [ "variant_value", "db/d1c/classcontainer__module_1_1variant__value.html", "db/d1c/classcontainer__module_1_1variant__value" ]
    ] ],
    [ "database", "da/df2/namespacedatabase.html", [
      [ "database_base", "d5/df0/classdatabase_1_1database__base.html", "d5/df0/classdatabase_1_1database__base" ],
      [ "database_manager", "df/d8d/classdatabase_1_1database__manager.html", "df/d8d/classdatabase_1_1database__manager" ],
      [ "postgres_manager", "d6/d7f/classdatabase_1_1postgres__manager.html", "d6/d7f/classdatabase_1_1postgres__manager" ]
    ] ],
    [ "fmt", null, [
      [ "formatter< test_priority >", "d0/d48/structfmt_1_1formatter_3_01test__priority_01_4.html", "d0/d48/structfmt_1_1formatter_3_01test__priority_01_4" ],
      [ "formatter< test_priority, wchar_t >", "d4/d08/structfmt_1_1formatter_3_01test__priority_00_01wchar__t_01_4.html", "d4/d08/structfmt_1_1formatter_3_01test__priority_00_01wchar__t_01_4" ],
      [ "formatter< thread_module::job >", "dd/d2a/structfmt_1_1formatter_3_01thread__module_1_1job_01_4.html", "dd/d2a/structfmt_1_1formatter_3_01thread__module_1_1job_01_4" ],
      [ "formatter< thread_module::job_queue >", "da/d9f/structfmt_1_1formatter_3_01thread__module_1_1job__queue_01_4.html", "da/d9f/structfmt_1_1formatter_3_01thread__module_1_1job__queue_01_4" ],
      [ "formatter< thread_module::thread_base >", "d2/d7f/structfmt_1_1formatter_3_01thread__module_1_1thread__base_01_4.html", "d2/d7f/structfmt_1_1formatter_3_01thread__module_1_1thread__base_01_4" ],
      [ "formatter< thread_module::thread_conditions >", "da/ddd/structfmt_1_1formatter_3_01thread__module_1_1thread__conditions_01_4.html", "da/ddd/structfmt_1_1formatter_3_01thread__module_1_1thread__conditions_01_4" ],
      [ "formatter< thread_pool_module::thread_pool >", "d3/d10/structfmt_1_1formatter_3_01thread__pool__module_1_1thread__pool_01_4.html", "d3/d10/structfmt_1_1formatter_3_01thread__pool__module_1_1thread__pool_01_4" ],
      [ "formatter< thread_pool_module::thread_worker >", "d3/da4/structfmt_1_1formatter_3_01thread__pool__module_1_1thread__worker_01_4.html", "d3/da4/structfmt_1_1formatter_3_01thread__pool__module_1_1thread__worker_01_4" ],
      [ "formatter< typed_thread_pool_module::job_types >", "da/d34/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1job__types_01_4.html", "da/d34/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1job__types_01_4" ],
      [ "formatter< typed_thread_pool_module::job_types, wchar_t >", "dd/de7/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1job__types_00_01wchar__t_01_4.html", "dd/de7/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1job__types_00_01wchar__t_01_4" ],
      [ "formatter< typed_thread_pool_module::typed_job_queue_t< job_type > >", "da/d41/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1typed__job__queue__t_3_01job__type_01_4_01_4.html", "da/d41/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1typed__job__queue__t_3_01job__type_01_4_01_4" ],
      [ "formatter< typed_thread_pool_module::typed_thread_pool_t< job_type > >", "d3/dc8/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1typed__thread__pool__t_3_01job__type_01_4_01_4.html", "d3/dc8/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1typed__thread__pool__t_3_01job__type_01_4_01_4" ],
      [ "formatter< typed_thread_pool_module::typed_thread_worker_t< job_type > >", "d3/dca/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1typed__thread__worker__t_3_01job__type_01_4_01_4.html", "d3/dca/structfmt_1_1formatter_3_01typed__thread__pool__module_1_1typed__thread__worker__t_3_01job__type_01_4_01_4" ]
    ] ],
    [ "kcenon", "d9/d03/namespacekcenon.html", [
      [ "messaging", "df/d4a/namespacekcenon_1_1messaging.html", [
        [ "cluster", "d0/d73/namespacekcenon_1_1messaging_1_1cluster.html", [
          [ "cluster_membership", "dc/def/classkcenon_1_1messaging_1_1cluster_1_1cluster__membership.html", "dc/def/classkcenon_1_1messaging_1_1cluster_1_1cluster__membership" ],
          [ "cluster_node", "d6/d9d/structkcenon_1_1messaging_1_1cluster_1_1cluster__node.html", "d6/d9d/structkcenon_1_1messaging_1_1cluster_1_1cluster__node" ],
          [ "consistent_hash_balancer", "d0/da1/classkcenon_1_1messaging_1_1cluster_1_1consistent__hash__balancer.html", "d0/da1/classkcenon_1_1messaging_1_1cluster_1_1consistent__hash__balancer" ],
          [ "distributed_broker", "d1/d28/classkcenon_1_1messaging_1_1cluster_1_1distributed__broker.html", "d1/d28/classkcenon_1_1messaging_1_1cluster_1_1distributed__broker" ],
          [ "distributed_broker_builder", "d7/d1b/classkcenon_1_1messaging_1_1cluster_1_1distributed__broker__builder.html", "d7/d1b/classkcenon_1_1messaging_1_1cluster_1_1distributed__broker__builder" ],
          [ "least_loaded_balancer", "d3/dab/classkcenon_1_1messaging_1_1cluster_1_1least__loaded__balancer.html", "d3/dab/classkcenon_1_1messaging_1_1cluster_1_1least__loaded__balancer" ],
          [ "load_balancer", "d1/df0/classkcenon_1_1messaging_1_1cluster_1_1load__balancer.html", "d1/df0/classkcenon_1_1messaging_1_1cluster_1_1load__balancer" ],
          [ "round_robin_balancer", "de/d17/classkcenon_1_1messaging_1_1cluster_1_1round__robin__balancer.html", "de/d17/classkcenon_1_1messaging_1_1cluster_1_1round__robin__balancer" ]
        ] ],
        [ "config", "d4/d18/namespacekcenon_1_1messaging_1_1config.html", [
          [ "config_builder", "d8/d82/classkcenon_1_1messaging_1_1config_1_1config__builder.html", "d8/d82/classkcenon_1_1messaging_1_1config_1_1config__builder" ],
          [ "messaging_config", "d3/d91/structkcenon_1_1messaging_1_1config_1_1messaging__config.html", "d3/d91/structkcenon_1_1messaging_1_1config_1_1messaging__config" ]
        ] ],
        [ "core", "db/d06/namespacekcenon_1_1messaging_1_1core.html", [
          [ "message", "dc/d1b/classkcenon_1_1messaging_1_1core_1_1message.html", "dc/d1b/classkcenon_1_1messaging_1_1core_1_1message" ],
          [ "message_bus", "de/d4b/classkcenon_1_1messaging_1_1core_1_1message__bus.html", "de/d4b/classkcenon_1_1messaging_1_1core_1_1message__bus" ],
          [ "message_bus_config", "d4/d84/structkcenon_1_1messaging_1_1core_1_1message__bus__config.html", "d4/d84/structkcenon_1_1messaging_1_1core_1_1message__bus__config" ],
          [ "message_dispatcher", "dd/d06/classkcenon_1_1messaging_1_1core_1_1message__dispatcher.html", "dd/d06/classkcenon_1_1messaging_1_1core_1_1message__dispatcher" ],
          [ "message_metadata", "d6/d94/structkcenon_1_1messaging_1_1core_1_1message__metadata.html", "d6/d94/structkcenon_1_1messaging_1_1core_1_1message__metadata" ],
          [ "message_payload", "d9/d87/structkcenon_1_1messaging_1_1core_1_1message__payload.html", "d9/d87/structkcenon_1_1messaging_1_1core_1_1message__payload" ],
          [ "message_queue", "d7/d9b/classkcenon_1_1messaging_1_1core_1_1message__queue.html", "d7/d9b/classkcenon_1_1messaging_1_1core_1_1message__queue" ],
          [ "message_router", "d8/d60/classkcenon_1_1messaging_1_1core_1_1message__router.html", "d8/d60/classkcenon_1_1messaging_1_1core_1_1message__router" ],
          [ "object_pool", "d5/d6f/classkcenon_1_1messaging_1_1core_1_1object__pool.html", "d5/d6f/classkcenon_1_1messaging_1_1core_1_1object__pool" ],
          [ "production_component_factory", "d8/d64/classkcenon_1_1messaging_1_1core_1_1production__component__factory.html", "d8/d64/classkcenon_1_1messaging_1_1core_1_1production__component__factory" ],
          [ "production_config_optimizer", "d0/df9/classkcenon_1_1messaging_1_1core_1_1production__config__optimizer.html", "d0/df9/classkcenon_1_1messaging_1_1core_1_1production__config__optimizer" ],
          [ "production_health_monitor", "d4/dc7/classkcenon_1_1messaging_1_1core_1_1production__health__monitor.html", "d4/dc7/classkcenon_1_1messaging_1_1core_1_1production__health__monitor" ],
          [ "production_message_allocator", "d1/d04/classkcenon_1_1messaging_1_1core_1_1production__message__allocator.html", "d1/d04/classkcenon_1_1messaging_1_1core_1_1production__message__allocator" ],
          [ "production_metrics", "d9/d02/structkcenon_1_1messaging_1_1core_1_1production__metrics.html", "d9/d02/structkcenon_1_1messaging_1_1core_1_1production__metrics" ]
        ] ],
        [ "integrations", "d9/dda/namespacekcenon_1_1messaging_1_1integrations.html", [
          [ "database_adapter", "d1/d2a/classkcenon_1_1messaging_1_1integrations_1_1database__adapter.html", "d1/d2a/classkcenon_1_1messaging_1_1integrations_1_1database__adapter" ],
          [ "external_connection_info", "d5/dc3/structkcenon_1_1messaging_1_1integrations_1_1external__connection__info.html", "d5/dc3/structkcenon_1_1messaging_1_1integrations_1_1external__connection__info" ],
          [ "external_system_adapter", "d0/d14/classkcenon_1_1messaging_1_1integrations_1_1external__system__adapter.html", "d0/d14/classkcenon_1_1messaging_1_1integrations_1_1external__system__adapter" ],
          [ "external_system_manager", "d8/d9c/classkcenon_1_1messaging_1_1integrations_1_1external__system__manager.html", "d8/d9c/classkcenon_1_1messaging_1_1integrations_1_1external__system__manager" ],
          [ "messaging_system_orchestrator", "d5/d8f/classkcenon_1_1messaging_1_1integrations_1_1messaging__system__orchestrator.html", "d5/d8f/classkcenon_1_1messaging_1_1integrations_1_1messaging__system__orchestrator" ],
          [ "service_container", "d5/d8f/classkcenon_1_1messaging_1_1integrations_1_1service__container.html", "d5/d8f/classkcenon_1_1messaging_1_1integrations_1_1service__container" ],
          [ "service_registration", "d0/d8f/structkcenon_1_1messaging_1_1integrations_1_1service__registration.html", "d0/d8f/structkcenon_1_1messaging_1_1integrations_1_1service__registration" ],
          [ "system_integrator", "d7/d69/classkcenon_1_1messaging_1_1integrations_1_1system__integrator.html", "d7/d69/classkcenon_1_1messaging_1_1integrations_1_1system__integrator" ],
          [ "thread_system_adapter", "da/d59/classkcenon_1_1messaging_1_1integrations_1_1thread__system__adapter.html", "da/d59/classkcenon_1_1messaging_1_1integrations_1_1thread__system__adapter" ]
        ] ],
        [ "management", "d5/d6d/namespacekcenon_1_1messaging_1_1management.html", [
          [ "dashboard_factory", "d9/daa/classkcenon_1_1messaging_1_1management_1_1dashboard__factory.html", "d9/daa/classkcenon_1_1messaging_1_1management_1_1dashboard__factory" ],
          [ "dashboard_manager", "d1/d50/classkcenon_1_1messaging_1_1management_1_1dashboard__manager.html", "d1/d50/classkcenon_1_1messaging_1_1management_1_1dashboard__manager" ],
          [ "dashboard_snapshot", "d1/d88/structkcenon_1_1messaging_1_1management_1_1dashboard__snapshot.html", "d1/d88/structkcenon_1_1messaging_1_1management_1_1dashboard__snapshot" ],
          [ "management_command_processor", "d7/d2f/classkcenon_1_1messaging_1_1management_1_1management__command__processor.html", "d7/d2f/classkcenon_1_1messaging_1_1management_1_1management__command__processor" ],
          [ "metrics_aggregator", "df/d0e/classkcenon_1_1messaging_1_1management_1_1metrics__aggregator.html", "df/d0e/classkcenon_1_1messaging_1_1management_1_1metrics__aggregator" ],
          [ "system_health_monitor", "d9/d0f/classkcenon_1_1messaging_1_1management_1_1system__health__monitor.html", "d9/d0f/classkcenon_1_1messaging_1_1management_1_1system__health__monitor" ],
          [ "system_management_commands", "dd/d2d/classkcenon_1_1messaging_1_1management_1_1system__management__commands.html", "dd/d2d/classkcenon_1_1messaging_1_1management_1_1system__management__commands" ]
        ] ],
        [ "persistence", "de/d62/namespacekcenon_1_1messaging_1_1persistence.html", [
          [ "file_message_storage", "d3/d07/classkcenon_1_1messaging_1_1persistence_1_1file__message__storage.html", "d3/d07/classkcenon_1_1messaging_1_1persistence_1_1file__message__storage" ],
          [ "message_recovery_system", "d1/d23/classkcenon_1_1messaging_1_1persistence_1_1message__recovery__system.html", "d1/d23/classkcenon_1_1messaging_1_1persistence_1_1message__recovery__system" ],
          [ "message_storage", "dd/d33/classkcenon_1_1messaging_1_1persistence_1_1message__storage.html", "dd/d33/classkcenon_1_1messaging_1_1persistence_1_1message__storage" ],
          [ "persistence_manager_factory", "d5/d20/classkcenon_1_1messaging_1_1persistence_1_1persistence__manager__factory.html", "d5/d20/classkcenon_1_1messaging_1_1persistence_1_1persistence__manager__factory" ],
          [ "persistent_message_queue", "df/d8c/classkcenon_1_1messaging_1_1persistence_1_1persistent__message__queue.html", "df/d8c/classkcenon_1_1messaging_1_1persistence_1_1persistent__message__queue" ]
        ] ],
        [ "routing", "d2/d97/namespacekcenon_1_1messaging_1_1routing.html", [
          [ "advanced_router", "de/d07/classkcenon_1_1messaging_1_1routing_1_1advanced__router.html", "de/d07/classkcenon_1_1messaging_1_1routing_1_1advanced__router" ],
          [ "composite_filter", "da/d4d/classkcenon_1_1messaging_1_1routing_1_1composite__filter.html", "da/d4d/classkcenon_1_1messaging_1_1routing_1_1composite__filter" ],
          [ "content_filter", "dd/d05/classkcenon_1_1messaging_1_1routing_1_1content__filter.html", "dd/d05/classkcenon_1_1messaging_1_1routing_1_1content__filter" ],
          [ "content_validator", "d0/d3d/classkcenon_1_1messaging_1_1routing_1_1content__validator.html", "d0/d3d/classkcenon_1_1messaging_1_1routing_1_1content__validator" ],
          [ "data_enricher", "da/d2e/classkcenon_1_1messaging_1_1routing_1_1data__enricher.html", "da/d2e/classkcenon_1_1messaging_1_1routing_1_1data__enricher" ],
          [ "function_transformer", "d7/d89/classkcenon_1_1messaging_1_1routing_1_1function__transformer.html", "d7/d89/classkcenon_1_1messaging_1_1routing_1_1function__transformer" ],
          [ "message_filter", "d4/d4d/classkcenon_1_1messaging_1_1routing_1_1message__filter.html", "d4/d4d/classkcenon_1_1messaging_1_1routing_1_1message__filter" ],
          [ "message_relay", "d4/d75/classkcenon_1_1messaging_1_1routing_1_1message__relay.html", "d4/d75/classkcenon_1_1messaging_1_1routing_1_1message__relay" ],
          [ "message_transformer", "dd/d0a/classkcenon_1_1messaging_1_1routing_1_1message__transformer.html", "dd/d0a/classkcenon_1_1messaging_1_1routing_1_1message__transformer" ],
          [ "pipeline_builder", "d2/ddb/classkcenon_1_1messaging_1_1routing_1_1pipeline__builder.html", "d2/ddb/classkcenon_1_1messaging_1_1routing_1_1pipeline__builder" ],
          [ "priority_adjuster", "d8/d1a/classkcenon_1_1messaging_1_1routing_1_1priority__adjuster.html", "d8/d1a/classkcenon_1_1messaging_1_1routing_1_1priority__adjuster" ],
          [ "priority_filter", "dc/df9/classkcenon_1_1messaging_1_1routing_1_1priority__filter.html", "dc/df9/classkcenon_1_1messaging_1_1routing_1_1priority__filter" ],
          [ "route_destination", "d1/dd7/structkcenon_1_1messaging_1_1routing_1_1route__destination.html", "d1/dd7/structkcenon_1_1messaging_1_1routing_1_1route__destination" ],
          [ "router_builder", "d0/d06/classkcenon_1_1messaging_1_1routing_1_1router__builder.html", "d0/d06/classkcenon_1_1messaging_1_1routing_1_1router__builder" ],
          [ "routing_rule", "df/df0/classkcenon_1_1messaging_1_1routing_1_1routing__rule.html", "df/df0/classkcenon_1_1messaging_1_1routing_1_1routing__rule" ],
          [ "topic_pattern_filter", "d6/d8f/classkcenon_1_1messaging_1_1routing_1_1topic__pattern__filter.html", "d6/d8f/classkcenon_1_1messaging_1_1routing_1_1topic__pattern__filter" ],
          [ "topic_rewriter", "d4/deb/classkcenon_1_1messaging_1_1routing_1_1topic__rewriter.html", "d4/deb/classkcenon_1_1messaging_1_1routing_1_1topic__rewriter" ],
          [ "transformation_context", "da/d3d/structkcenon_1_1messaging_1_1routing_1_1transformation__context.html", "da/d3d/structkcenon_1_1messaging_1_1routing_1_1transformation__context" ],
          [ "transformation_pipeline", "dc/d6f/classkcenon_1_1messaging_1_1routing_1_1transformation__pipeline.html", "dc/d6f/classkcenon_1_1messaging_1_1routing_1_1transformation__pipeline" ]
        ] ],
        [ "security", "d4/d80/namespacekcenon_1_1messaging_1_1security.html", [
          [ "auth_token", "d0/d48/structkcenon_1_1messaging_1_1security_1_1auth__token.html", "d0/d48/structkcenon_1_1messaging_1_1security_1_1auth__token" ],
          [ "authentication_manager", "d2/d9c/classkcenon_1_1messaging_1_1security_1_1authentication__manager.html", "d2/d9c/classkcenon_1_1messaging_1_1security_1_1authentication__manager" ],
          [ "message_access_controller", "da/d90/classkcenon_1_1messaging_1_1security_1_1message__access__controller.html", "da/d90/classkcenon_1_1messaging_1_1security_1_1message__access__controller" ],
          [ "message_encryptor", "d1/deb/classkcenon_1_1messaging_1_1security_1_1message__encryptor.html", "d1/deb/classkcenon_1_1messaging_1_1security_1_1message__encryptor" ],
          [ "secure_message", "d7/df4/structkcenon_1_1messaging_1_1security_1_1secure__message.html", "d7/df4/structkcenon_1_1messaging_1_1security_1_1secure__message" ],
          [ "security_manager", "df/d78/classkcenon_1_1messaging_1_1security_1_1security__manager.html", "df/d78/classkcenon_1_1messaging_1_1security_1_1security__manager" ],
          [ "security_policy_builder", "d7/d99/classkcenon_1_1messaging_1_1security_1_1security__policy__builder.html", "d7/d99/classkcenon_1_1messaging_1_1security_1_1security__policy__builder" ],
          [ "user_credentials", "d7/da3/structkcenon_1_1messaging_1_1security_1_1user__credentials.html", "d7/da3/structkcenon_1_1messaging_1_1security_1_1user__credentials" ],
          [ "xor_encryptor", "d5/dbc/classkcenon_1_1messaging_1_1security_1_1xor__encryptor.html", "d5/dbc/classkcenon_1_1messaging_1_1security_1_1xor__encryptor" ]
        ] ],
        [ "services", "d8/d37/namespacekcenon_1_1messaging_1_1services.html", [
          [ "container", "dd/df3/namespacekcenon_1_1messaging_1_1services_1_1container.html", [
            [ "container_config", "d0/dfd/structkcenon_1_1messaging_1_1services_1_1container_1_1container__config.html", "d0/dfd/structkcenon_1_1messaging_1_1services_1_1container_1_1container__config" ],
            [ "container_service", "db/daf/classkcenon_1_1messaging_1_1services_1_1container_1_1container__service.html", "db/daf/classkcenon_1_1messaging_1_1services_1_1container_1_1container__service" ],
            [ "container_service_adapter", "d2/d96/classkcenon_1_1messaging_1_1services_1_1container_1_1container__service__adapter.html", "d2/d96/classkcenon_1_1messaging_1_1services_1_1container_1_1container__service__adapter" ]
          ] ],
          [ "database", "d7/db1/namespacekcenon_1_1messaging_1_1services_1_1database.html", [
            [ "database_service", "d2/d07/classkcenon_1_1messaging_1_1services_1_1database_1_1database__service.html", "d2/d07/classkcenon_1_1messaging_1_1services_1_1database_1_1database__service" ]
          ] ],
          [ "discovery", "dd/d2b/namespacekcenon_1_1messaging_1_1services_1_1discovery.html", [
            [ "discovery_service", "dc/de7/classkcenon_1_1messaging_1_1services_1_1discovery_1_1discovery__service.html", "dc/de7/classkcenon_1_1messaging_1_1services_1_1discovery_1_1discovery__service" ]
          ] ],
          [ "gateway", "d1/da0/namespacekcenon_1_1messaging_1_1services_1_1gateway.html", [
            [ "gateway_service", "db/d91/classkcenon_1_1messaging_1_1services_1_1gateway_1_1gateway__service.html", "db/d91/classkcenon_1_1messaging_1_1services_1_1gateway_1_1gateway__service" ]
          ] ],
          [ "logging", "dc/d17/namespacekcenon_1_1messaging_1_1services_1_1logging.html", [
            [ "internal_logging_service", "d7/ddd/classkcenon_1_1messaging_1_1services_1_1logging_1_1internal__logging__service.html", "d7/ddd/classkcenon_1_1messaging_1_1services_1_1logging_1_1internal__logging__service" ],
            [ "logging_service", "db/d94/classkcenon_1_1messaging_1_1services_1_1logging_1_1logging__service.html", "db/d94/classkcenon_1_1messaging_1_1services_1_1logging_1_1logging__service" ],
            [ "logging_service_adapter", "df/d75/classkcenon_1_1messaging_1_1services_1_1logging_1_1logging__service__adapter.html", "df/d75/classkcenon_1_1messaging_1_1services_1_1logging_1_1logging__service__adapter" ]
          ] ],
          [ "monitoring", "dc/d02/namespacekcenon_1_1messaging_1_1services_1_1monitoring.html", [
            [ "internal_monitoring_service", "d6/db1/classkcenon_1_1messaging_1_1services_1_1monitoring_1_1internal__monitoring__service.html", "d6/db1/classkcenon_1_1messaging_1_1services_1_1monitoring_1_1internal__monitoring__service" ],
            [ "messaging_metrics", "d7/d9a/structkcenon_1_1messaging_1_1services_1_1monitoring_1_1messaging__metrics.html", "d7/d9a/structkcenon_1_1messaging_1_1services_1_1monitoring_1_1messaging__metrics" ],
            [ "monitoring_service", "db/d02/classkcenon_1_1messaging_1_1services_1_1monitoring_1_1monitoring__service.html", "db/d02/classkcenon_1_1messaging_1_1services_1_1monitoring_1_1monitoring__service" ],
            [ "monitoring_service_adapter", "dd/d47/classkcenon_1_1messaging_1_1services_1_1monitoring_1_1monitoring__service__adapter.html", "dd/d47/classkcenon_1_1messaging_1_1services_1_1monitoring_1_1monitoring__service__adapter" ]
          ] ],
          [ "network", "d2/d3f/namespacekcenon_1_1messaging_1_1services_1_1network.html", [
            [ "network_config", "df/d1b/structkcenon_1_1messaging_1_1services_1_1network_1_1network__config.html", "df/d1b/structkcenon_1_1messaging_1_1services_1_1network_1_1network__config" ],
            [ "network_service", "d2/db0/classkcenon_1_1messaging_1_1services_1_1network_1_1network__service.html", "d2/db0/classkcenon_1_1messaging_1_1services_1_1network_1_1network__service" ],
            [ "network_service_adapter", "d2/de5/classkcenon_1_1messaging_1_1services_1_1network_1_1network__service__adapter.html", "d2/de5/classkcenon_1_1messaging_1_1services_1_1network_1_1network__service__adapter" ]
          ] ],
          [ "service_adapter", "d5/d12/classkcenon_1_1messaging_1_1services_1_1service__adapter.html", "d5/d12/classkcenon_1_1messaging_1_1services_1_1service__adapter" ],
          [ "service_interface", "d4/df5/classkcenon_1_1messaging_1_1services_1_1service__interface.html", "d4/df5/classkcenon_1_1messaging_1_1services_1_1service__interface" ]
        ] ]
      ] ]
    ] ],
    [ "logger_module", "dc/d2b/namespacelogger__module.html", [
      [ "access_control_filter", "d0/dd6/classlogger__module_1_1access__control__filter.html", "d0/dd6/classlogger__module_1_1access__control__filter" ],
      [ "async_logger_crash_safety", "da/d71/classlogger__module_1_1async__logger__crash__safety.html", "da/d71/classlogger__module_1_1async__logger__crash__safety" ],
      [ "base_writer", "d0/d97/classlogger__module_1_1base__writer.html", "d0/d97/classlogger__module_1_1base__writer" ],
      [ "composite_filter", "d7/d30/classlogger__module_1_1composite__filter.html", "d7/d30/classlogger__module_1_1composite__filter" ],
      [ "console_writer", "d2/d43/classlogger__module_1_1console__writer.html", "d2/d43/classlogger__module_1_1console__writer" ],
      [ "emergency_log_entry", "d3/d25/structlogger__module_1_1emergency__log__entry.html", "d3/d25/structlogger__module_1_1emergency__log__entry" ],
      [ "encrypted_writer", "d3/d97/classlogger__module_1_1encrypted__writer.html", "d3/d97/classlogger__module_1_1encrypted__writer" ],
      [ "file_writer", "d0/d8d/classlogger__module_1_1file__writer.html", "d0/d8d/classlogger__module_1_1file__writer" ],
      [ "function_filter", "da/d34/classlogger__module_1_1function__filter.html", "da/d34/classlogger__module_1_1function__filter" ],
      [ "level_filter", "d8/dd3/classlogger__module_1_1level__filter.html", "d8/dd3/classlogger__module_1_1level__filter" ],
      [ "log_aggregator", "dc/d7c/classlogger__module_1_1log__aggregator.html", "dc/d7c/classlogger__module_1_1log__aggregator" ],
      [ "log_analyzer", "d1/d94/classlogger__module_1_1log__analyzer.html", "d1/d94/classlogger__module_1_1log__analyzer" ],
      [ "log_collector", "de/df6/classlogger__module_1_1log__collector.html", "de/df6/classlogger__module_1_1log__collector" ],
      [ "log_entry", "d0/d79/structlogger__module_1_1log__entry.html", "d0/d79/structlogger__module_1_1log__entry" ],
      [ "log_file_recovery", "d2/d37/classlogger__module_1_1log__file__recovery.html", "d2/d37/classlogger__module_1_1log__file__recovery" ],
      [ "log_filter", "d1/d9c/classlogger__module_1_1log__filter.html", "d1/d9c/classlogger__module_1_1log__filter" ],
      [ "log_route", "d1/d7f/structlogger__module_1_1log__route.html", "d1/d7f/structlogger__module_1_1log__route" ],
      [ "log_router", "d1/d04/classlogger__module_1_1log__router.html", "d1/d04/classlogger__module_1_1log__router" ],
      [ "log_sanitizer", "db/d54/classlogger__module_1_1log__sanitizer.html", "db/d54/classlogger__module_1_1log__sanitizer" ],
      [ "log_server", "df/d21/classlogger__module_1_1log__server.html", "df/d21/classlogger__module_1_1log__server" ],
      [ "logger", "da/d2e/classlogger__module_1_1logger.html", "da/d2e/classlogger__module_1_1logger" ],
      [ "logger_crash_safety", "d5/d70/classlogger__module_1_1logger__crash__safety.html", "d5/d70/classlogger__module_1_1logger__crash__safety" ],
      [ "logger_metrics_collector", "db/d9d/classlogger__module_1_1logger__metrics__collector.html", "db/d9d/classlogger__module_1_1logger__metrics__collector" ],
      [ "network_writer", "d2/daa/classlogger__module_1_1network__writer.html", "d2/daa/classlogger__module_1_1network__writer" ],
      [ "performance_metrics", "dc/d9f/structlogger__module_1_1performance__metrics.html", "dc/d9f/structlogger__module_1_1performance__metrics" ],
      [ "regex_filter", "d4/d40/classlogger__module_1_1regex__filter.html", "d4/d40/classlogger__module_1_1regex__filter" ],
      [ "rotating_file_writer", "d5/d2a/classlogger__module_1_1rotating__file__writer.html", "d5/d2a/classlogger__module_1_1rotating__file__writer" ],
      [ "router_builder", "d7/d5c/classlogger__module_1_1router__builder.html", "d7/d5c/classlogger__module_1_1router__builder" ],
      [ "sanitizing_filter", "d2/da8/classlogger__module_1_1sanitizing__filter.html", "d2/da8/classlogger__module_1_1sanitizing__filter" ],
      [ "scoped_logger_crash_protection", "d7/d29/classlogger__module_1_1scoped__logger__crash__protection.html", "d7/d29/classlogger__module_1_1scoped__logger__crash__protection" ],
      [ "standard_fields", "dc/da9/structlogger__module_1_1standard__fields.html", "dc/da9/structlogger__module_1_1standard__fields" ],
      [ "structured_logger", "d4/d01/classlogger__module_1_1structured__logger.html", "d4/d01/classlogger__module_1_1structured__logger" ],
      [ "writer_metrics", "d4/db6/structlogger__module_1_1writer__metrics.html", "d4/db6/structlogger__module_1_1writer__metrics" ]
    ] ],
    [ "monitoring_interface", "d3/d7a/namespacemonitoring__interface.html", [
      [ "metrics_snapshot", "dc/d59/structmonitoring__interface_1_1metrics__snapshot.html", "dc/d59/structmonitoring__interface_1_1metrics__snapshot" ],
      [ "monitoring_interface", "d6/d8e/classmonitoring__interface_1_1monitoring__interface.html", "d6/d8e/classmonitoring__interface_1_1monitoring__interface" ],
      [ "multi_process_metrics_snapshot", "d8/d51/structmonitoring__interface_1_1multi__process__metrics__snapshot.html", "d8/d51/structmonitoring__interface_1_1multi__process__metrics__snapshot" ],
      [ "multi_process_monitoring_interface", "dd/d4a/classmonitoring__interface_1_1multi__process__monitoring__interface.html", "dd/d4a/classmonitoring__interface_1_1multi__process__monitoring__interface" ],
      [ "null_monitoring", "dc/d6a/classmonitoring__interface_1_1null__monitoring.html", "dc/d6a/classmonitoring__interface_1_1null__monitoring" ],
      [ "process_identifier", "d5/da6/structmonitoring__interface_1_1process__identifier.html", "d5/da6/structmonitoring__interface_1_1process__identifier" ],
      [ "process_thread_pool_metrics", "d5/d7d/structmonitoring__interface_1_1process__thread__pool__metrics.html", "d5/d7d/structmonitoring__interface_1_1process__thread__pool__metrics" ],
      [ "scoped_timer", "d7/dfd/classmonitoring__interface_1_1scoped__timer.html", "d7/dfd/classmonitoring__interface_1_1scoped__timer" ],
      [ "system_metrics", "df/d06/structmonitoring__interface_1_1system__metrics.html", "df/d06/structmonitoring__interface_1_1system__metrics" ],
      [ "thread_pool_identifier", "da/d1f/structmonitoring__interface_1_1thread__pool__identifier.html", "da/d1f/structmonitoring__interface_1_1thread__pool__identifier" ],
      [ "thread_pool_metrics", "d6/d3b/structmonitoring__interface_1_1thread__pool__metrics.html", "d6/d3b/structmonitoring__interface_1_1thread__pool__metrics" ],
      [ "worker_metrics", "d6/da4/structmonitoring__interface_1_1worker__metrics.html", "d6/da4/structmonitoring__interface_1_1worker__metrics" ]
    ] ],
    [ "monitoring_module", "dc/da4/namespacemonitoring__module.html", [
      [ "alert_manager", "d3/d4d/classmonitoring__module_1_1alert__manager.html", "d3/d4d/classmonitoring__module_1_1alert__manager" ],
      [ "alert_system_crash_safety", "d6/d43/classmonitoring__module_1_1alert__system__crash__safety.html", "d6/d43/classmonitoring__module_1_1alert__system__crash__safety" ],
      [ "analysis_dashboard", "d5/d3d/classmonitoring__module_1_1analysis__dashboard.html", "d5/d3d/classmonitoring__module_1_1analysis__dashboard" ],
      [ "auto_scaler", "d6/dbb/classmonitoring__module_1_1auto__scaler.html", "d6/dbb/classmonitoring__module_1_1auto__scaler" ],
      [ "batch_metrics_processor", "db/d67/classmonitoring__module_1_1batch__metrics__processor.html", "db/d67/classmonitoring__module_1_1batch__metrics__processor" ],
      [ "compressed_metrics_storage", "db/d41/classmonitoring__module_1_1compressed__metrics__storage.html", "db/d41/classmonitoring__module_1_1compressed__metrics__storage" ],
      [ "critical_metrics_snapshot", "de/dca/structmonitoring__module_1_1critical__metrics__snapshot.html", "de/dca/structmonitoring__module_1_1critical__metrics__snapshot" ],
      [ "distributed_aggregator", "d6/dab/classmonitoring__module_1_1distributed__aggregator.html", "d6/dab/classmonitoring__module_1_1distributed__aggregator" ],
      [ "lock_free_metrics_queue", "d3/d42/classmonitoring__module_1_1lock__free__metrics__queue.html", "d3/d42/classmonitoring__module_1_1lock__free__metrics__queue" ],
      [ "metrics_collection_crash_safety", "d9/daa/classmonitoring__module_1_1metrics__collection__crash__safety.html", "d9/daa/classmonitoring__module_1_1metrics__collection__crash__safety" ],
      [ "metrics_collector", "d0/d98/classmonitoring__module_1_1metrics__collector.html", "d0/d98/classmonitoring__module_1_1metrics__collector" ],
      [ "monitoring", "d8/d4c/classmonitoring__module_1_1monitoring.html", "d8/d4c/classmonitoring__module_1_1monitoring" ],
      [ "monitoring_crash_safety", "dc/d3a/classmonitoring__module_1_1monitoring__crash__safety.html", "dc/d3a/classmonitoring__module_1_1monitoring__crash__safety" ],
      [ "multi_process_monitoring", "d3/d11/classmonitoring__module_1_1multi__process__monitoring.html", "d3/d11/classmonitoring__module_1_1multi__process__monitoring" ],
      [ "performance_optimizer", "d7/d01/classmonitoring__module_1_1performance__optimizer.html", "d7/d01/classmonitoring__module_1_1performance__optimizer" ],
      [ "ring_buffer", "d7/dc0/classmonitoring__module_1_1ring__buffer.html", "d7/dc0/classmonitoring__module_1_1ring__buffer" ],
      [ "ring_buffer_crash_safety", "d0/db1/classmonitoring__module_1_1ring__buffer__crash__safety.html", "d0/db1/classmonitoring__module_1_1ring__buffer__crash__safety" ],
      [ "scoped_monitoring_crash_protection", "dc/d06/classmonitoring__module_1_1scoped__monitoring__crash__protection.html", "dc/d06/classmonitoring__module_1_1scoped__monitoring__crash__protection" ],
      [ "thread_pool_analyzer", "da/d37/classmonitoring__module_1_1thread__pool__analyzer.html", "da/d37/classmonitoring__module_1_1thread__pool__analyzer" ],
      [ "tiered_storage", "d5/d7d/classmonitoring__module_1_1tiered__storage.html", "d5/d7d/classmonitoring__module_1_1tiered__storage" ],
      [ "trend_analyzer", "dc/d33/classmonitoring__module_1_1trend__analyzer.html", "dc/d33/classmonitoring__module_1_1trend__analyzer" ]
    ] ],
    [ "network_module", "d1/df3/namespacenetwork__module.html", [
      [ "messaging_client", "dc/d94/classnetwork__module_1_1messaging__client.html", "dc/d94/classnetwork__module_1_1messaging__client" ],
      [ "messaging_server", "de/d13/classnetwork__module_1_1messaging__server.html", "de/d13/classnetwork__module_1_1messaging__server" ],
      [ "messaging_session", "de/d65/classnetwork__module_1_1messaging__session.html", "de/d65/classnetwork__module_1_1messaging__session" ],
      [ "pipeline", "d2/dc7/structnetwork__module_1_1pipeline.html", "d2/dc7/structnetwork__module_1_1pipeline" ],
      [ "tcp_socket", "d3/d43/classnetwork__module_1_1tcp__socket.html", "d3/d43/classnetwork__module_1_1tcp__socket" ]
    ] ],
    [ "platform_test", "de/d60/namespaceplatform__test.html", [
      [ "AtomicOperationsTest", "df/db6/classplatform__test_1_1AtomicOperationsTest.html", "df/db6/classplatform__test_1_1AtomicOperationsTest" ],
      [ "CachePerformanceTest", "d4/d32/classplatform__test_1_1CachePerformanceTest.html", "d4/d32/classplatform__test_1_1CachePerformanceTest" ],
      [ "PlatformSpecificTest", "db/dd8/classplatform__test_1_1PlatformSpecificTest.html", "db/dd8/classplatform__test_1_1PlatformSpecificTest" ]
    ] ],
    [ "std", "d8/dcc/namespacestd.html", [
      [ "formatter< Point >", "d9/d50/structstd_1_1formatter_3_01Point_01_4.html", "d9/d50/structstd_1_1formatter_3_01Point_01_4" ],
      [ "formatter< TaskType >", "d1/d22/structstd_1_1formatter_3_01TaskType_01_4.html", "d1/d22/structstd_1_1formatter_3_01TaskType_01_4" ],
      [ "hash< monitoring_interface::process_identifier >", "d1/d29/structstd_1_1hash_3_01monitoring__interface_1_1process__identifier_01_4.html", "d1/d29/structstd_1_1hash_3_01monitoring__interface_1_1process__identifier_01_4" ],
      [ "hash< monitoring_interface::thread_pool_identifier >", "d0/dbc/structstd_1_1hash_3_01monitoring__interface_1_1thread__pool__identifier_01_4.html", "d0/dbc/structstd_1_1hash_3_01monitoring__interface_1_1thread__pool__identifier_01_4" ]
    ] ],
    [ "thread_module", "de/d48/namespacethread__module.html", [
      [ "detail", "de/de1/namespacethread__module_1_1detail.html", [
        [ "thread_impl", "df/d50/classthread__module_1_1detail_1_1thread__impl.html", "df/d50/classthread__module_1_1detail_1_1thread__impl" ]
      ] ],
      [ "jobs", "d2/dca/namespacethread__module_1_1jobs.html", [
        [ "job_interface", "d6/ddf/classthread__module_1_1jobs_1_1job__interface.html", "d6/ddf/classthread__module_1_1jobs_1_1job__interface" ]
      ] ],
      [ "lockfree", "de/d41/namespacethread__module_1_1lockfree.html", [
        [ "adaptive_config", "de/d2d/structthread__module_1_1lockfree_1_1adaptive__config.html", "de/d2d/structthread__module_1_1lockfree_1_1adaptive__config" ],
        [ "performance_stats", "d6/d6f/structthread__module_1_1lockfree_1_1performance__stats.html", "d6/d6f/structthread__module_1_1lockfree_1_1performance__stats" ]
      ] ],
      [ "sync", "d4/db0/namespacethread__module_1_1sync.html", [
        [ "atomic_flag_wrapper", "da/d62/classthread__module_1_1sync_1_1atomic__flag__wrapper.html", "da/d62/classthread__module_1_1sync_1_1atomic__flag__wrapper" ],
        [ "condition_variable_wrapper", "da/df8/classthread__module_1_1sync_1_1condition__variable__wrapper.html", "da/df8/classthread__module_1_1sync_1_1condition__variable__wrapper" ],
        [ "scoped_lock_guard", "dc/d7b/classthread__module_1_1sync_1_1scoped__lock__guard.html", "dc/d7b/classthread__module_1_1sync_1_1scoped__lock__guard" ],
        [ "shared_mutex_wrapper", "dc/dfb/classthread__module_1_1sync_1_1shared__mutex__wrapper.html", "dc/dfb/classthread__module_1_1sync_1_1shared__mutex__wrapper" ]
      ] ],
      [ "test", "dd/d4a/namespacethread__module_1_1test.html", [
        [ "ConcurrencyTest", "d2/da5/classthread__module_1_1test_1_1ConcurrencyTest.html", "d2/da5/classthread__module_1_1test_1_1ConcurrencyTest" ],
        [ "ErrorHandlingTest", "dd/d11/classthread__module_1_1test_1_1ErrorHandlingTest.html", "dd/d11/classthread__module_1_1test_1_1ErrorHandlingTest" ]
      ] ],
      [ "adaptive_job_queue", "d9/d67/classthread__module_1_1adaptive__job__queue.html", "d9/d67/classthread__module_1_1adaptive__job__queue" ],
      [ "callback_job", "dc/d7f/classthread__module_1_1callback__job.html", "dc/d7f/classthread__module_1_1callback__job" ],
      [ "cancellation_token", "df/d25/classthread__module_1_1cancellation__token.html", "df/d25/classthread__module_1_1cancellation__token" ],
      [ "crash_context", "d8/d68/structthread__module_1_1crash__context.html", "d8/d68/structthread__module_1_1crash__context" ],
      [ "crash_handler", "d6/d49/classthread__module_1_1crash__handler.html", "d6/d49/classthread__module_1_1crash__handler" ],
      [ "default_error_handler", "d1/d4a/classthread__module_1_1default__error__handler.html", "d1/d4a/classthread__module_1_1default__error__handler" ],
      [ "error", "dc/d6c/classthread__module_1_1error.html", "dc/d6c/classthread__module_1_1error" ],
      [ "error_handler", "dd/d11/classthread__module_1_1error__handler.html", "dd/d11/classthread__module_1_1error__handler" ],
      [ "hazard_pointer_manager", "d7/ded/classthread__module_1_1hazard__pointer__manager.html", "d7/ded/classthread__module_1_1hazard__pointer__manager" ],
      [ "job", "d8/d42/classthread__module_1_1job.html", "d8/d42/classthread__module_1_1job" ],
      [ "job_queue", "df/d6d/classthread__module_1_1job__queue.html", "df/d6d/classthread__module_1_1job__queue" ],
      [ "lockfree_job_queue", "d1/de8/classthread__module_1_1lockfree__job__queue.html", "d1/de8/classthread__module_1_1lockfree__job__queue" ],
      [ "logger_interface", "d1/dcb/classthread__module_1_1logger__interface.html", "d1/dcb/classthread__module_1_1logger__interface" ],
      [ "logger_registry", "d7/da8/classthread__module_1_1logger__registry.html", "d7/da8/classthread__module_1_1logger__registry" ],
      [ "node_pool", "d8/dad/classthread__module_1_1node__pool.html", "d8/dad/classthread__module_1_1node__pool" ],
      [ "result", "d2/d93/classthread__module_1_1result.html", "d2/d93/classthread__module_1_1result" ],
      [ "result< void >", "de/d5e/classthread__module_1_1result_3_01void_01_4.html", "de/d5e/classthread__module_1_1result_3_01void_01_4" ],
      [ "result_void", "dd/da2/classthread__module_1_1result__void.html", "dd/da2/classthread__module_1_1result__void" ],
      [ "scoped_crash_callback", "d5/dfd/classthread__module_1_1scoped__crash__callback.html", "d5/dfd/classthread__module_1_1scoped__crash__callback" ],
      [ "scoped_service", "db/ded/classthread__module_1_1scoped__service.html", "db/ded/classthread__module_1_1scoped__service" ],
      [ "service_container", "d8/d74/classthread__module_1_1service__container.html", "d8/d74/classthread__module_1_1service__container" ],
      [ "thread_base", "da/d94/classthread__module_1_1thread__base.html", "da/d94/classthread__module_1_1thread__base" ],
      [ "thread_context", "d5/d07/classthread__module_1_1thread__context.html", "d5/d07/classthread__module_1_1thread__context" ],
      [ "thread_context_builder", "dc/d2a/classthread__module_1_1thread__context__builder.html", "dc/d2a/classthread__module_1_1thread__context__builder" ],
      [ "thread_pool_crash_safety", "d4/d20/classthread__module_1_1thread__pool__crash__safety.html", "d4/d20/classthread__module_1_1thread__pool__crash__safety" ]
    ] ],
    [ "thread_pool_module", "d8/d98/namespacethread__pool__module.html", [
      [ "detail", "da/d38/namespacethread__pool__module_1_1detail.html", [
        [ "callable_eraser", "d3/dbe/classthread__pool__module_1_1detail_1_1callable__eraser.html", "d3/dbe/classthread__pool__module_1_1detail_1_1callable__eraser" ],
        [ "callable_return_type", "d5/d76/structthread__pool__module_1_1detail_1_1callable__return__type.html", "d5/d76/structthread__pool__module_1_1detail_1_1callable__return__type" ],
        [ "compile_string", "d6/dee/structthread__pool__module_1_1detail_1_1compile__string.html", "d6/dee/structthread__pool__module_1_1detail_1_1compile__string" ],
        [ "function_traits", "d4/d84/structthread__pool__module_1_1detail_1_1function__traits.html", null ],
        [ "function_traits< R(*)(Args...) noexcept >", "dc/d06/structthread__pool__module_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_01noexcept_01_4.html", "dc/d06/structthread__pool__module_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_01noexcept_01_4" ],
        [ "function_traits< R(*)(Args...)>", "de/dc4/structthread__pool__module_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_4.html", "de/dc4/structthread__pool__module_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_4" ],
        [ "function_traits< R(C::*)(Args...) const >", "de/d13/structthread__pool__module_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", "de/d13/structthread__pool__module_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4" ],
        [ "function_traits< R(C::*)(Args...)>", "da/db8/structthread__pool__module_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", "da/db8/structthread__pool__module_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4" ],
        [ "has_get_method", "df/d64/structthread__pool__module_1_1detail_1_1has__get__method.html", null ],
        [ "has_get_method< T, std::void_t< decltype(std::declval< T >().get())> >", "d9/d62/structthread__pool__module_1_1detail_1_1has__get__method_3_01T_00_01std_1_1void__t_3_01decltype_a0465c2793b601c1efa3be7652b795e9.html", null ],
        [ "is_duration", "d7/d0b/structthread__pool__module_1_1detail_1_1is__duration.html", null ],
        [ "is_duration< std::chrono::duration< Rep, Period > >", "d2/d92/structthread__pool__module_1_1detail_1_1is__duration_3_01std_1_1chrono_1_1duration_3_01Rep_00_01Period_01_4_01_4.html", null ],
        [ "is_future_like", "d4/d57/structthread__pool__module_1_1detail_1_1is__future__like.html", null ],
        [ "is_nothrow_callable", "d4/d3e/structthread__pool__module_1_1detail_1_1is__nothrow__callable.html", null ],
        [ "validate_thread_count", "d8/d4b/structthread__pool__module_1_1detail_1_1validate__thread__count.html", "d8/d4b/structthread__pool__module_1_1detail_1_1validate__thread__count" ]
      ] ],
      [ "pool_future", "df/d38/classthread__pool__module_1_1pool__future.html", "df/d38/classthread__pool__module_1_1pool__future" ],
      [ "pool_promise", "d4/d02/classthread__pool__module_1_1pool__promise.html", "d4/d02/classthread__pool__module_1_1pool__promise" ],
      [ "pool_promise< void >", "d8/d4a/classthread__pool__module_1_1pool__promise_3_01void_01_4.html", "d8/d4a/classthread__pool__module_1_1pool__promise_3_01void_01_4" ],
      [ "thread_pool", "d9/da1/classthread__pool__module_1_1thread__pool.html", "d9/da1/classthread__pool__module_1_1thread__pool" ],
      [ "thread_worker", "d7/d1b/classthread__pool__module_1_1thread__worker.html", "d7/d1b/classthread__pool__module_1_1thread__worker" ],
      [ "worker_policy", "d4/d53/structthread__pool__module_1_1worker__policy.html", "d4/d53/structthread__pool__module_1_1worker__policy" ]
    ] ],
    [ "typed_thread_pool_module", "d4/db9/namespacetyped__thread__pool__module.html", [
      [ "detail", "d9/d03/namespacetyped__thread__pool__module_1_1detail.html", [
        [ "conditional_feature", "da/da3/structtyped__thread__pool__module_1_1detail_1_1conditional__feature.html", "da/da3/structtyped__thread__pool__module_1_1detail_1_1conditional__feature" ],
        [ "constexpr_string", "de/dc3/structtyped__thread__pool__module_1_1detail_1_1constexpr__string.html", "de/dc3/structtyped__thread__pool__module_1_1detail_1_1constexpr__string" ],
        [ "function_traits", "d2/d44/structtyped__thread__pool__module_1_1detail_1_1function__traits.html", null ],
        [ "function_traits< R(*)(Args...)>", "db/d10/structtyped__thread__pool__module_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_4.html", "db/d10/structtyped__thread__pool__module_1_1detail_1_1function__traits_3_01R_07_5_08_07Args_8_8_8_08_4" ],
        [ "function_traits< R(C::*)(Args...) const >", "d8/dee/structtyped__thread__pool__module_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4.html", "d8/dee/structtyped__thread__pool__module_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_01const_01_4" ],
        [ "function_traits< R(C::*)(Args...)>", "de/d52/structtyped__thread__pool__module_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4.html", "de/d52/structtyped__thread__pool__module_1_1detail_1_1function__traits_3_01R_07C_1_1_5_08_07Args_8_8_8_08_4" ],
        [ "has_do_work_method", "dd/d19/structtyped__thread__pool__module_1_1detail_1_1has__do__work__method.html", null ],
        [ "has_do_work_method< T, std::void_t< decltype(std::declval< T >().do_work())> >", "db/df5/structtyped__thread__pool__module_1_1detail_1_1has__do__work__method_3_01T_00_01std_1_1void__t_326af756acd357eb452243a29392a2b29.html", null ],
        [ "has_priority_method", "d2/d0b/structtyped__thread__pool__module_1_1detail_1_1has__priority__method.html", null ],
        [ "has_priority_method< T, std::void_t< decltype(std::declval< T >().priority())> >", "de/d9b/structtyped__thread__pool__module_1_1detail_1_1has__priority__method_3_01T_00_01std_1_1void__t_3e6416fec089501094ca1aa6baa646e2f.html", null ],
        [ "is_compatible_job", "d2/dcf/structtyped__thread__pool__module_1_1detail_1_1is__compatible__job.html", null ],
        [ "is_compatible_job< Job, ExpectedJobType >", "dd/dbc/structtyped__thread__pool__module_1_1detail_1_1is__compatible__job_3_01Job_00_01ExpectedJobType_01_4.html", "dd/dbc/structtyped__thread__pool__module_1_1detail_1_1is__compatible__job_3_01Job_00_01ExpectedJobType_01_4" ],
        [ "is_valid_job_type", "d2/d81/structtyped__thread__pool__module_1_1detail_1_1is__valid__job__type.html", null ],
        [ "is_valid_job_type< T, std::void_t< std::enable_if_t< JobType< T > > > >", "de/d38/structtyped__thread__pool__module_1_1detail_1_1is__valid__job__type_3_01T_00_01std_1_1void__t_3_6c25439dd3b606b635c5ac1f9fed271e.html", null ],
        [ "job_eraser", "d1/d76/classtyped__thread__pool__module_1_1detail_1_1job__eraser.html", "d1/d76/classtyped__thread__pool__module_1_1detail_1_1job__eraser" ],
        [ "job_type_extractor", "d0/dfa/structtyped__thread__pool__module_1_1detail_1_1job__type__extractor.html", "d0/dfa/structtyped__thread__pool__module_1_1detail_1_1job__type__extractor" ],
        [ "job_type_extractor< T >", "d1/d67/structtyped__thread__pool__module_1_1detail_1_1job__type__extractor_3_01T_01_4.html", "d1/d67/structtyped__thread__pool__module_1_1detail_1_1job__type__extractor_3_01T_01_4" ],
        [ "job_type_list", "d0/dc2/structtyped__thread__pool__module_1_1detail_1_1job__type__list.html", "d0/dc2/structtyped__thread__pool__module_1_1detail_1_1job__type__list" ],
        [ "job_type_traits", "dc/d03/structtyped__thread__pool__module_1_1detail_1_1job__type__traits.html", "dc/d03/structtyped__thread__pool__module_1_1detail_1_1job__type__traits" ],
        [ "job_validator", "d2/d06/structtyped__thread__pool__module_1_1detail_1_1job__validator.html", "d2/d06/structtyped__thread__pool__module_1_1detail_1_1job__validator" ],
        [ "priority_comparator", "d7/d02/structtyped__thread__pool__module_1_1detail_1_1priority__comparator.html", "d7/d02/structtyped__thread__pool__module_1_1detail_1_1priority__comparator" ]
      ] ],
      [ "adaptive_typed_job_queue_t", "d2/d9e/classtyped__thread__pool__module_1_1adaptive__typed__job__queue__t.html", "d2/d9e/classtyped__thread__pool__module_1_1adaptive__typed__job__queue__t" ],
      [ "callback_typed_job_t", "d3/dea/classtyped__thread__pool__module_1_1callback__typed__job__t.html", "d3/dea/classtyped__thread__pool__module_1_1callback__typed__job__t" ],
      [ "typed_job_factory_interface", "dd/dab/classtyped__thread__pool__module_1_1typed__job__factory__interface.html", "dd/dab/classtyped__thread__pool__module_1_1typed__job__factory__interface" ],
      [ "typed_job_interface", "d0/d67/classtyped__thread__pool__module_1_1typed__job__interface.html", "d0/d67/classtyped__thread__pool__module_1_1typed__job__interface" ],
      [ "typed_job_queue_t", "db/de8/classtyped__thread__pool__module_1_1typed__job__queue__t.html", "db/de8/classtyped__thread__pool__module_1_1typed__job__queue__t" ],
      [ "typed_job_t", "d8/d4f/classtyped__thread__pool__module_1_1typed__job__t.html", "d8/d4f/classtyped__thread__pool__module_1_1typed__job__t" ],
      [ "typed_lockfree_job_queue_t", "d3/d35/classtyped__thread__pool__module_1_1typed__lockfree__job__queue__t.html", "d3/d35/classtyped__thread__pool__module_1_1typed__lockfree__job__queue__t" ],
      [ "typed_queue_statistics_t", "dd/dab/structtyped__thread__pool__module_1_1typed__queue__statistics__t.html", "dd/dab/structtyped__thread__pool__module_1_1typed__queue__statistics__t" ],
      [ "typed_thread_pool_builder", "dd/dd0/classtyped__thread__pool__module_1_1typed__thread__pool__builder.html", "dd/dd0/classtyped__thread__pool__module_1_1typed__thread__pool__builder" ],
      [ "typed_thread_pool_t", "dc/dd1/classtyped__thread__pool__module_1_1typed__thread__pool__t.html", "dc/dd1/classtyped__thread__pool__module_1_1typed__thread__pool__t" ],
      [ "typed_thread_worker_t", "d0/d0f/classtyped__thread__pool__module_1_1typed__thread__worker__t.html", "d0/d0f/classtyped__thread__pool__module_1_1typed__thread__worker__t" ]
    ] ],
    [ "utility_module", "dd/d2a/namespaceutility__module.html", [
      [ "convert_string", "d1/d53/classutility__module_1_1convert__string.html", "d1/d53/classutility__module_1_1convert__string" ],
      [ "enum_formatter", "d1/dec/classutility__module_1_1enum__formatter.html", "d1/dec/classutility__module_1_1enum__formatter" ],
      [ "formatter", "d1/daf/classutility__module_1_1formatter.html", "d1/daf/classutility__module_1_1formatter" ],
      [ "result_wrapper", "d6/d68/classutility__module_1_1result__wrapper.html", "d6/d68/classutility__module_1_1result__wrapper" ],
      [ "span", "d8/d4f/classutility__module_1_1span.html", "d8/d4f/classutility__module_1_1span" ]
    ] ],
    [ "aggregated_data", "da/da0/structaggregated__data.html", "da/da0/structaggregated__data" ],
    [ "alert", "dc/d19/structalert.html", "dc/d19/structalert" ],
    [ "analysis_visualizer", "d8/db7/classanalysis__visualizer.html", "d8/db7/classanalysis__visualizer" ],
    [ "BaseWriterTest", "d1/dc0/classBaseWriterTest.html", "d1/dc0/classBaseWriterTest" ],
    [ "BasicThreadPoolTest", "dd/d0d/classBasicThreadPoolTest.html", "dd/d0d/classBasicThreadPoolTest" ],
    [ "BenchmarkRunner", "dc/d7b/classBenchmarkRunner.html", "dc/d7b/classBenchmarkRunner" ],
    [ "cache_line_data", "da/d58/structcache__line__data.html", "da/d58/structcache__line__data" ],
    [ "chat_server", "d2/d4e/classchat__server.html", "d2/d4e/classchat__server" ],
    [ "circuit_breaker", "d0/ddb/classcircuit__breaker.html", "d0/ddb/classcircuit__breaker" ],
    [ "config_loader", "d4/dc8/classconfig__loader.html", "d4/dc8/classconfig__loader" ],
    [ "console_logger", "d4/d06/classconsole__logger.html", "d4/d06/classconsole__logger" ],
    [ "console_monitoring", "d7/dde/classconsole__monitoring.html", "d7/dde/classconsole__monitoring" ],
    [ "ConsoleWriterTest", "d7/ded/classConsoleWriterTest.html", "d7/ded/classConsoleWriterTest" ],
    [ "Container", "d0/d7b/classContainer.html", "d0/d7b/classContainer" ],
    [ "ContainerServiceTest", "da/d71/classContainerServiceTest.html", "da/d71/classContainerServiceTest" ],
    [ "ConvertStringTest", "d4/de6/classConvertStringTest.html", "d4/de6/classConvertStringTest" ],
    [ "critical_resource", "d3/d9c/classcritical__resource.html", "d3/d9c/classcritical__resource" ],
    [ "dashboard_renderer", "d7/d5d/classdashboard__renderer.html", "d7/d5d/classdashboard__renderer" ],
    [ "device_config", "d2/dd8/structdevice__config.html", "d2/dd8/structdevice__config" ],
    [ "device_telemetry", "d7/d16/structdevice__telemetry.html", "d7/d16/structdevice__telemetry" ],
    [ "distributed_worker", "d8/dfa/classdistributed__worker.html", "d8/dfa/classdistributed__worker" ],
    [ "event_pipeline", "dc/d11/classevent__pipeline.html", "dc/d11/classevent__pipeline" ],
    [ "health_monitor", "d9/dca/classhealth__monitor.html", "d9/dca/classhealth__monitor" ],
    [ "IntegrationTest", "d2/d6a/classIntegrationTest.html", "d2/d6a/classIntegrationTest" ],
    [ "iot_monitoring_system", "d9/d2e/classiot__monitoring__system.html", "d9/d2e/classiot__monitoring__system" ],
    [ "JobExecutionRecord", "da/d1e/structJobExecutionRecord.html", "da/d1e/structJobExecutionRecord" ],
    [ "load_balancer", "d9/d8b/classload__balancer.html", "d9/d8b/classload__balancer" ],
    [ "load_simulator", "df/d50/classload__simulator.html", "df/d50/classload__simulator" ],
    [ "lockfree_ring_buffer", "dc/db7/classlockfree__ring__buffer.html", "dc/db7/classlockfree__ring__buffer" ],
    [ "LockFreeStack", "d0/d8f/classLockFreeStack.html", "d0/d8f/classLockFreeStack" ],
    [ "LogCollectorTest", "de/d04/classLogCollectorTest.html", "de/d04/classLogCollectorTest" ],
    [ "LoggerIntegrationTest", "da/d80/classLoggerIntegrationTest.html", "da/d80/classLoggerIntegrationTest" ],
    [ "LoggerTest", "d2/daf/classLoggerTest.html", "d2/daf/classLoggerTest" ],
    [ "MemoryMonitor", "da/d6a/classMemoryMonitor.html", "da/d6a/classMemoryMonitor" ],
    [ "MessageBusTest", "d9/d84/classMessageBusTest.html", "d9/d84/classMessageBusTest" ],
    [ "MessagingIntegrationTest", "d3/df7/classMessagingIntegrationTest.html", "d3/df7/classMessagingIntegrationTest" ],
    [ "metrics_collector", "d7/db0/classmetrics__collector.html", "d7/db0/classmetrics__collector" ],
    [ "microservices_orchestrator", "d3/d02/classmicroservices__orchestrator.html", "d3/d02/classmicroservices__orchestrator" ],
    [ "mock_logger", "dd/d02/classmock__logger.html", "dd/d02/classmock__logger" ],
    [ "mock_monitoring", "d2/db4/classmock__monitoring.html", "d2/db4/classmock__monitoring" ],
    [ "MockCollectorWriter", "d3/d23/classMockCollectorWriter.html", "d3/d23/classMockCollectorWriter" ],
    [ "MockDependentService", "d2/dc0/classMockDependentService.html", "d2/dc0/classMockDependentService" ],
    [ "MockService", "d4/d00/classMockService.html", "d4/d00/classMockService" ],
    [ "MockWriter", "d0/df9/classMockWriter.html", "d0/df9/classMockWriter" ],
    [ "monitoring_interface", "db/d58/classmonitoring__interface.html", null ],
    [ "MonitoringIntegrationTest", "da/dd6/classMonitoringIntegrationTest.html", "da/dd6/classMonitoringIntegrationTest" ],
    [ "MonitoringTest", "d1/da1/classMonitoringTest.html", "d1/da1/classMonitoringTest" ],
    [ "MPMCQueueTest", "d4/d66/classMPMCQueueTest.html", "d4/d66/classMPMCQueueTest" ],
    [ "NetworkServiceTest", "d8/d56/classNetworkServiceTest.html", "d8/d56/classNetworkServiceTest" ],
    [ "null_writer", "d6/d8c/classnull__writer.html", "d6/d8c/classnull__writer" ],
    [ "performance_comparator", "df/da4/classperformance__comparator.html", "df/da4/classperformance__comparator" ],
    [ "PerformanceTest", "da/d80/classPerformanceTest.html", "da/d80/classPerformanceTest" ],
    [ "pipeline_stage", "df/d30/classpipeline__stage.html", "df/d30/classpipeline__stage" ],
    [ "Point", "d8/d43/structPoint.html", "d8/d43/structPoint" ],
    [ "priority_scheduling_benchmark", "da/dd2/classpriority__scheduling__benchmark.html", "da/dd2/classpriority__scheduling__benchmark" ],
    [ "process_simulator", "df/d10/classprocess__simulator.html", "df/d10/classprocess__simulator" ],
    [ "processed_event", "d0/d16/structprocessed__event.html", "d0/d16/structprocessed__event" ],
    [ "PyMessageHandler", "d0/d85/classPyMessageHandler.html", "d0/d85/classPyMessageHandler" ],
    [ "raw_event", "d2/da5/structraw__event.html", "d2/da5/structraw__event" ],
    [ "RequestType", "d6/d42/structRequestType.html", "d6/d42/structRequestType" ],
    [ "retry_handler", "d6/d71/classretry__handler.html", "d6/d71/classretry__handler" ],
    [ "RingBufferTest", "d5/d7b/classRingBufferTest.html", "d5/d7b/classRingBufferTest" ],
    [ "sample_monitoring", "d3/d20/classsample__monitoring.html", "d3/d20/classsample__monitoring" ],
    [ "service_definition", "db/d96/structservice__definition.html", "db/d96/structservice__definition" ],
    [ "service_instance", "d0/d45/structservice__instance.html", "d0/d45/structservice__instance" ],
    [ "ServiceContainerTest", "df/d3d/classServiceContainerTest.html", "df/d3d/classServiceContainerTest" ],
    [ "simple_test_job", "d7/d93/classsimple__test__job.html", "d7/d93/classsimple__test__job" ],
    [ "SimpleThreadPool", "d2/d1f/classSimpleThreadPool.html", "d2/d1f/classSimpleThreadPool" ],
    [ "simulated_thread_pool", "da/d7b/classsimulated__thread__pool.html", "da/d7b/classsimulated__thread__pool" ],
    [ "simulated_worker", "d2/d99/classsimulated__worker.html", "d2/d99/classsimulated__worker" ],
    [ "system_metrics_collector", "d3/d11/classsystem__metrics__collector.html", "d3/d11/classsystem__metrics__collector" ],
    [ "system_stats", "d0/df9/structsystem__stats.html", "d0/df9/structsystem__stats" ],
    [ "SystemIntegratorPerformanceTest", "d6/d06/classSystemIntegratorPerformanceTest.html", "d6/d06/classSystemIntegratorPerformanceTest" ],
    [ "SystemIntegratorTest", "d1/dc6/classSystemIntegratorTest.html", "d1/dc6/classSystemIntegratorTest" ],
    [ "task", "db/da2/structtask.html", "db/da2/structtask" ],
    [ "task_generator", "da/dc4/classtask__generator.html", "da/dc4/classtask__generator" ],
    [ "TestData", "d8/de1/structTestData.html", "d8/de1/structTestData" ],
    [ "TestLogger", "de/d3f/classTestLogger.html", "de/d3f/classTestLogger" ],
    [ "TestMonitoring", "d3/dce/classTestMonitoring.html", "d3/dce/classTestMonitoring" ],
    [ "TestNode", "d3/d4f/structTestNode.html", "d3/d4f/structTestNode" ],
    [ "ThreadBaseTest", "db/d90/classThreadBaseTest.html", "db/d90/classThreadBaseTest" ],
    [ "typed_queue_statistics", "d8/d18/structtyped__queue__statistics.html", null ],
    [ "TypedThreadPoolTest", "d2/d92/classTypedThreadPoolTest.html", "d2/d92/classTypedThreadPoolTest" ],
    [ "WakeIntervalTestWorker", "dc/de0/classWakeIntervalTestWorker.html", "dc/de0/classWakeIntervalTestWorker" ],
    [ "workload_generator", "df/d88/classworkload__generator.html", "df/d88/classworkload__generator" ],
    [ "workload_simulator", "d3/d63/classworkload__simulator.html", "d3/d63/classworkload__simulator" ],
    [ "WorkloadSimulator", "d1/d76/classWorkloadSimulator.html", "d1/d76/classWorkloadSimulator" ]
];