var dir_cca5f032534a7da49a25c5ecd33330bb =
[
    [ "adaptive_job_queue.h", "de/de2/modular__structure_2core_2include_2thread__system__core_2thread__base_2lockfree_2queues_2adaptive__job__queue_8h.html", "de/de2/modular__structure_2core_2include_2thread__system__core_2thread__base_2lockfree_2queues_2adaptive__job__queue_8h" ],
    [ "lockfree_job_queue.h", "d6/dea/modular__structure_2core_2include_2thread__system__core_2thread__base_2lockfree_2queues_2lockfree__job__queue_8h.html", "d6/dea/modular__structure_2core_2include_2thread__system__core_2thread__base_2lockfree_2queues_2lockfree__job__queue_8h" ]
];