var hierarchy =
[
    [ "thread_module::lockfree::adaptive_config", "structthread__module_1_1lockfree_1_1adaptive__config.html", null ],
    [ "thread_module::sync::atomic_flag_wrapper", "classthread__module_1_1sync_1_1atomic__flag__wrapper.html", null ],
    [ "thread_module::adaptive_job_queue::atomic_performance_metrics", "structthread__module_1_1adaptive__job__queue_1_1atomic__performance__metrics.html", null ],
    [ "thread_module::lockfree_job_queue::atomic_statistics", "structthread__module_1_1lockfree__job__queue_1_1atomic__statistics.html", null ],
    [ "std::bool_constant", null, [
      [ "thread_pool_module::detail::is_future_like< T >", "structthread__pool__module_1_1detail_1_1is__future__like.html", null ],
      [ "thread_pool_module::detail::is_nothrow_callable< F >", "structthread__pool__module_1_1detail_1_1is__nothrow__callable.html", null ]
    ] ],
    [ "thread_pool_module::detail::callable_eraser", "classthread__pool__module_1_1detail_1_1callable__eraser.html", null ],
    [ "thread_pool_module::detail::callable_return_type< F >", "structthread__pool__module_1_1detail_1_1callable__return__type.html", null ],
    [ "thread_module::crash_handler::callback_entry", "structthread__module_1_1crash__handler_1_1callback__entry.html", null ],
    [ "thread_module::cancellation_token", "classthread__module_1_1cancellation__token.html", null ],
    [ "thread_module::crash_handler::cleanup_entry", "structthread__module_1_1crash__handler_1_1cleanup__entry.html", null ],
    [ "thread_pool_module::detail::compile_string< N >", "structthread__pool__module_1_1detail_1_1compile__string.html", null ],
    [ "thread_module::sync::condition_variable_wrapper", "classthread__module_1_1sync_1_1condition__variable__wrapper.html", null ],
    [ "typed_thread_pool_module::detail::conditional_feature< Condition >", "structtyped__thread__pool__module_1_1detail_1_1conditional__feature.html", null ],
    [ "typed_thread_pool_module::detail::constexpr_string< N >", "structtyped__thread__pool__module_1_1detail_1_1constexpr__string.html", null ],
    [ "utility_module::convert_string", "classutility__module_1_1convert__string.html", null ],
    [ "thread_module::crash_context", "structthread__module_1_1crash__context.html", null ],
    [ "thread_module::crash_handler", "classthread__module_1_1crash__handler.html", null ],
    [ "thread_module::crash_handler::crash_stats", "structthread__module_1_1crash__handler_1_1crash__stats.html", null ],
    [ "database::database_base", "classdatabase_1_1database__base.html", [
      [ "database::postgres_manager", "classdatabase_1_1postgres__manager.html", null ]
    ] ],
    [ "database::database_manager", "classdatabase_1_1database__manager.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "container_module::thread_safe_container", "classcontainer__module_1_1thread__safe__container.html", null ],
      [ "container_module::value", "classcontainer__module_1_1value.html", [
        [ "container_module::bool_value", "classcontainer__module_1_1bool__value.html", null ],
        [ "container_module::bytes_value", "classcontainer__module_1_1bytes__value.html", null ],
        [ "container_module::container_value", "classcontainer__module_1_1container__value.html", null ],
        [ "container_module::numeric_value< T, TypeTag >", "classcontainer__module_1_1numeric__value.html", null ],
        [ "container_module::string_value", "classcontainer__module_1_1string__value.html", null ]
      ] ],
      [ "container_module::value_container", "classcontainer__module_1_1value__container.html", null ],
      [ "network_module::messaging_client", "classnetwork__module_1_1messaging__client.html", null ],
      [ "network_module::messaging_server", "classnetwork__module_1_1messaging__server.html", null ],
      [ "network_module::messaging_session", "classnetwork__module_1_1messaging__session.html", null ],
      [ "network_module::tcp_socket", "classnetwork__module_1_1tcp__socket.html", null ],
      [ "thread_module::job_queue", "classthread__module_1_1job__queue.html", [
        [ "typed_thread_pool_module::typed_job_queue_t< job_types >", "classtyped__thread__pool__module_1_1typed__job__queue__t.html", null ],
        [ "typed_thread_pool_module::typed_job_queue_t< job_type >", "classtyped__thread__pool__module_1_1typed__job__queue__t.html", null ],
        [ "typed_thread_pool_module::typed_lockfree_job_queue_t< job_types >", "classtyped__thread__pool__module_1_1typed__lockfree__job__queue__t.html", null ],
        [ "thread_module::adaptive_job_queue", "classthread__module_1_1adaptive__job__queue.html", null ],
        [ "thread_module::lockfree_job_queue", "classthread__module_1_1lockfree__job__queue.html", null ],
        [ "typed_thread_pool_module::typed_job_queue_t< job_type >", "classtyped__thread__pool__module_1_1typed__job__queue__t.html", [
          [ "typed_thread_pool_module::adaptive_typed_job_queue_t< job_type >", "classtyped__thread__pool__module_1_1adaptive__typed__job__queue__t.html", null ]
        ] ],
        [ "typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >", "classtyped__thread__pool__module_1_1typed__lockfree__job__queue__t.html", null ]
      ] ],
      [ "thread_pool_module::thread_pool", "classthread__pool__module_1_1thread__pool.html", null ],
      [ "typed_thread_pool_module::typed_thread_pool_t< job_type >", "classtyped__thread__pool__module_1_1typed__thread__pool__t.html", null ]
    ] ],
    [ "utility_module::enum_formatter< T, Converter >", "classutility__module_1_1enum__formatter.html", null ],
    [ "thread_module::error", "classthread__module_1_1error.html", null ],
    [ "thread_module::error_handler", "classthread__module_1_1error__handler.html", [
      [ "thread_module::default_error_handler", "classthread__module_1_1default__error__handler.html", null ]
    ] ],
    [ "std::false_type", null, [
      [ "container_module::is_variant_type< T >", "structcontainer__module_1_1is__variant__type.html", null ],
      [ "thread_pool_module::detail::has_get_method< T, typename >", "structthread__pool__module_1_1detail_1_1has__get__method.html", null ],
      [ "thread_pool_module::detail::is_duration< T >", "structthread__pool__module_1_1detail_1_1is__duration.html", null ],
      [ "typed_thread_pool_module::detail::has_do_work_method< T, typename >", "structtyped__thread__pool__module_1_1detail_1_1has__do__work__method.html", null ],
      [ "typed_thread_pool_module::detail::has_priority_method< T, typename >", "structtyped__thread__pool__module_1_1detail_1_1has__priority__method.html", null ],
      [ "typed_thread_pool_module::detail::is_compatible_job< Job, ExpectedJobType >", "structtyped__thread__pool__module_1_1detail_1_1is__compatible__job.html", null ],
      [ "typed_thread_pool_module::detail::is_valid_job_type< T, typename >", "structtyped__thread__pool__module_1_1detail_1_1is__valid__job__type.html", null ]
    ] ],
    [ "std::formatter", null, [
      [ "std::formatter< thread_module::thread_conditions >", "structstd_1_1formatter_3_01thread__module_1_1thread__conditions_01_4.html", null ],
      [ "std::formatter< thread_module::thread_conditions, wchar_t >", "structstd_1_1formatter_3_01thread__module_1_1thread__conditions_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< thread_pool_module::thread_pool >", "structstd_1_1formatter_3_01thread__pool__module_1_1thread__pool_01_4.html", null ],
      [ "std::formatter< thread_pool_module::thread_pool, wchar_t >", "structstd_1_1formatter_3_01thread__pool__module_1_1thread__pool_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< thread_pool_module::thread_worker >", "structstd_1_1formatter_3_01thread__pool__module_1_1thread__worker_01_4.html", null ],
      [ "std::formatter< thread_pool_module::thread_worker, wchar_t >", "structstd_1_1formatter_3_01thread__pool__module_1_1thread__worker_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< typed_thread_pool_module::job_types >", "structstd_1_1formatter_3_01typed__thread__pool__module_1_1job__types_01_4.html", null ],
      [ "std::formatter< typed_thread_pool_module::job_types, wchar_t >", "structstd_1_1formatter_3_01typed__thread__pool__module_1_1job__types_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< typed_thread_pool_module::typed_job_queue_t< job_type > >", "structstd_1_1formatter_3_01typed__thread__pool__module_1_1typed__job__queue__t_3_01job__type_01_4_01_4.html", null ],
      [ "std::formatter< typed_thread_pool_module::typed_job_queue_t< job_type >, wchar_t >", "structstd_1_1formatter_3_01typed__thread__pool__module_1_1typed__job__queue__t_3_01job__type_01_4_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< typed_thread_pool_module::typed_thread_pool_t< job_type > >", "structstd_1_1formatter_3_01typed__thread__pool__module_1_1typed__thread__pool__t_3_01job__type_01_4_01_4.html", null ],
      [ "std::formatter< typed_thread_pool_module::typed_thread_pool_t< job_type >, wchar_t >", "structstd_1_1formatter_3_01typed__thread__pool__module_1_1typed__thread__pool__t_3_01job__type_01_4_00_01wchar__t_01_4.html", null ],
      [ "std::formatter< typed_thread_pool_module::typed_thread_worker_t< job_type > >", "structstd_1_1formatter_3_01typed__thread__pool__module_1_1typed__thread__worker__t_3_01job__type_01_4_01_4.html", null ],
      [ "std::formatter< typed_thread_pool_module::typed_thread_worker_t< job_type >, wchar_t >", "structstd_1_1formatter_3_01typed__thread__pool__module_1_1typed__thread__worker__t_3_01job__type_01_4_00_01wchar__t_01_4.html", null ]
    ] ],
    [ "utility_module::formatter", "classutility__module_1_1formatter.html", null ],
    [ "thread_module::node_pool< T >::FreeNode", "structthread__module_1_1node__pool_1_1_free_node.html", null ],
    [ "thread_pool_module::detail::function_traits< F >", "structthread__pool__module_1_1detail_1_1function__traits.html", null ],
    [ "typed_thread_pool_module::detail::function_traits< F >", "structtyped__thread__pool__module_1_1detail_1_1function__traits.html", null ],
    [ "thread_pool_module::detail::function_traits< R(*)(Args...) noexcept >", "structthread__pool__module_1_1detail_1_1function__traits_3_01_r_07_5_08_07_args_8_8_8_08_01noexcept_01_4.html", null ],
    [ "thread_pool_module::detail::function_traits< R(*)(Args...)>", "structthread__pool__module_1_1detail_1_1function__traits_3_01_r_07_5_08_07_args_8_8_8_08_4.html", null ],
    [ "typed_thread_pool_module::detail::function_traits< R(*)(Args...)>", "structtyped__thread__pool__module_1_1detail_1_1function__traits_3_01_r_07_5_08_07_args_8_8_8_08_4.html", null ],
    [ "thread_pool_module::detail::function_traits< R(C::*)(Args...) const >", "structthread__pool__module_1_1detail_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_01const_01_4.html", null ],
    [ "typed_thread_pool_module::detail::function_traits< R(C::*)(Args...) const >", "structtyped__thread__pool__module_1_1detail_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_01const_01_4.html", null ],
    [ "thread_pool_module::detail::function_traits< R(C::*)(Args...)>", "structthread__pool__module_1_1detail_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4.html", null ],
    [ "typed_thread_pool_module::detail::function_traits< R(C::*)(Args...)>", "structtyped__thread__pool__module_1_1detail_1_1function__traits_3_01_r_07_c_1_1_5_08_07_args_8_8_8_08_4.html", null ],
    [ "thread_module::hazard_pointer_manager::hazard_pointer", "classthread__module_1_1hazard__pointer__manager_1_1hazard__pointer.html", null ],
    [ "thread_module::hazard_pointer_manager", "classthread__module_1_1hazard__pointer__manager.html", null ],
    [ "thread_module::hazard_pointer_manager::HazardRecord", "structthread__module_1_1hazard__pointer__manager_1_1_hazard_record.html", null ],
    [ "typed_thread_pool_module::detail::is_compatible_job< Job, ExpectedJobType >", "structtyped__thread__pool__module_1_1detail_1_1is__compatible__job_3_01_job_00_01_expected_job_type_01_4.html", null ],
    [ "thread_module::job", "classthread__module_1_1job.html", [
      [ "thread_module::callback_job", "classthread__module_1_1callback__job.html", null ],
      [ "typed_thread_pool_module::typed_job_t< job_type >", "classtyped__thread__pool__module_1_1typed__job__t.html", [
        [ "typed_thread_pool_module::callback_typed_job_t< job_type >", "classtyped__thread__pool__module_1_1callback__typed__job__t.html", null ]
      ] ]
    ] ],
    [ "typed_thread_pool_module::detail::job_eraser", "classtyped__thread__pool__module_1_1detail_1_1job__eraser.html", null ],
    [ "thread_module::jobs::job_interface", "classthread__module_1_1jobs_1_1job__interface.html", null ],
    [ "typed_thread_pool_module::detail::job_type_extractor< Job >", "structtyped__thread__pool__module_1_1detail_1_1job__type__extractor.html", null ],
    [ "typed_thread_pool_module::detail::job_type_extractor< T >", "structtyped__thread__pool__module_1_1detail_1_1job__type__extractor_3_01_t_01_4.html", null ],
    [ "typed_thread_pool_module::detail::job_type_list< Types >", "structtyped__thread__pool__module_1_1detail_1_1job__type__list.html", null ],
    [ "typed_thread_pool_module::detail::job_type_traits< T >", "structtyped__thread__pool__module_1_1detail_1_1job__type__traits.html", null ],
    [ "typed_thread_pool_module::detail::job_validator< Job, ExpectedType >", "structtyped__thread__pool__module_1_1detail_1_1job__validator.html", null ],
    [ "container_module::lockfree_reader", "classcontainer__module_1_1lockfree__reader.html", null ],
    [ "thread_module::logger_interface", "classthread__module_1_1logger__interface.html", null ],
    [ "thread_module::logger_registry", "classthread__module_1_1logger__registry.html", null ],
    [ "monitoring_interface::metrics_snapshot", "structmonitoring__interface_1_1metrics__snapshot.html", null ],
    [ "monitoring_interface", "classmonitoring__interface.html", null ],
    [ "monitoring_interface::monitoring_interface", "classmonitoring__interface_1_1monitoring__interface.html", [
      [ "monitoring_interface::null_monitoring", "classmonitoring__interface_1_1null__monitoring.html", null ]
    ] ],
    [ "thread_module::lockfree_job_queue::Node", "structthread__module_1_1lockfree__job__queue_1_1_node.html", null ],
    [ "thread_module::node_pool< T >", "classthread__module_1_1node__pool.html", null ],
    [ "thread_module::node_pool< thread_module::lockfree_job_queue::Node >", "classthread__module_1_1node__pool.html", null ],
    [ "thread_module::adaptive_job_queue::performance_metrics", "structthread__module_1_1adaptive__job__queue_1_1performance__metrics.html", null ],
    [ "typed_thread_pool_module::adaptive_typed_job_queue_t< job_type >::performance_metrics", "structtyped__thread__pool__module_1_1adaptive__typed__job__queue__t_1_1performance__metrics.html", null ],
    [ "thread_module::lockfree::performance_stats", "structthread__module_1_1lockfree_1_1performance__stats.html", null ],
    [ "network_module::pipeline", "structnetwork__module_1_1pipeline.html", null ],
    [ "thread_pool_module::pool_future< T >", "classthread__pool__module_1_1pool__future.html", null ],
    [ "thread_pool_module::pool_promise< T >", "classthread__pool__module_1_1pool__promise.html", null ],
    [ "thread_pool_module::pool_promise< void >", "classthread__pool__module_1_1pool__promise_3_01void_01_4.html", null ],
    [ "thread_module::node_pool< T >::PoolChunk", "structthread__module_1_1node__pool_1_1_pool_chunk.html", null ],
    [ "typed_thread_pool_module::detail::priority_comparator< T, Comparator >", "structtyped__thread__pool__module_1_1detail_1_1priority__comparator.html", null ],
    [ "thread_module::lockfree_job_queue::queue_statistics", "structthread__module_1_1lockfree__job__queue_1_1queue__statistics.html", [
      [ "typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_queue_statistics", "structtyped__thread__pool__module_1_1typed__lockfree__job__queue__t_1_1typed__queue__statistics.html", null ]
    ] ],
    [ "container_module::value_container::read_lock_guard", "classcontainer__module_1_1value__container_1_1read__lock__guard.html", null ],
    [ "thread_module::result< T >", "classthread__module_1_1result.html", null ],
    [ "thread_module::result< void >", "classthread__module_1_1result_3_01void_01_4.html", null ],
    [ "thread_module::result_void", "classthread__module_1_1result__void.html", null ],
    [ "utility_module::result_wrapper< T >", "classutility__module_1_1result__wrapper.html", null ],
    [ "thread_module::hazard_pointer_manager::RetiredNode", "structthread__module_1_1hazard__pointer__manager_1_1_retired_node.html", null ],
    [ "thread_module::scoped_crash_callback", "classthread__module_1_1scoped__crash__callback.html", null ],
    [ "thread_module::sync::scoped_lock_guard< Mutex >", "classthread__module_1_1sync_1_1scoped__lock__guard.html", null ],
    [ "thread_module::scoped_service< Interface >", "classthread__module_1_1scoped__service.html", null ],
    [ "monitoring_interface::scoped_timer", "classmonitoring__interface_1_1scoped__timer.html", null ],
    [ "thread_module::service_container", "classthread__module_1_1service__container.html", null ],
    [ "thread_module::service_container::service_entry", "structthread__module_1_1service__container_1_1service__entry.html", null ],
    [ "thread_module::sync::shared_mutex_wrapper", "classthread__module_1_1sync_1_1shared__mutex__wrapper.html", null ],
    [ "container_module::simd::simd_compressor", "classcontainer__module_1_1simd_1_1simd__compressor.html", null ],
    [ "container_module::simd::simd_processor", "classcontainer__module_1_1simd_1_1simd__processor.html", null ],
    [ "container_module::simd::simd_support", "classcontainer__module_1_1simd_1_1simd__support.html", null ],
    [ "container_module::simd::simd_traits< T >", "structcontainer__module_1_1simd_1_1simd__traits.html", null ],
    [ "container_module::thread_safe_container::Statistics", "structcontainer__module_1_1thread__safe__container_1_1_statistics.html", null ],
    [ "thread_module::hazard_pointer_manager::statistics", "structthread__module_1_1hazard__pointer__manager_1_1statistics.html", null ],
    [ "thread_module::node_pool< T >::statistics", "structthread__module_1_1node__pool_1_1statistics.html", null ],
    [ "monitoring_interface::system_metrics", "structmonitoring__interface_1_1system__metrics.html", null ],
    [ "thread_module::thread_base", "classthread__module_1_1thread__base.html", [
      [ "typed_thread_pool_module::typed_thread_worker_t< job_types >", "classtyped__thread__pool__module_1_1typed__thread__worker__t.html", null ],
      [ "thread_pool_module::thread_worker", "classthread__pool__module_1_1thread__worker.html", null ],
      [ "typed_thread_pool_module::typed_thread_worker_t< job_type >", "classtyped__thread__pool__module_1_1typed__thread__worker__t.html", null ]
    ] ],
    [ "thread_module::thread_context", "classthread__module_1_1thread__context.html", null ],
    [ "thread_module::thread_context_builder", "classthread__module_1_1thread__context__builder.html", null ],
    [ "thread_module::detail::thread_impl", "classthread__module_1_1detail_1_1thread__impl.html", null ],
    [ "thread_module::thread_pool_crash_safety", "classthread__module_1_1thread__pool__crash__safety.html", null ],
    [ "monitoring_interface::thread_pool_metrics", "structmonitoring__interface_1_1thread__pool__metrics.html", null ],
    [ "thread_module::cancellation_token::token_state", "structthread__module_1_1cancellation__token_1_1token__state.html", null ],
    [ "std::true_type", null, [
      [ "container_module::is_variant_type< bool >", "structcontainer__module_1_1is__variant__type_3_01bool_01_4.html", null ],
      [ "container_module::is_variant_type< double >", "structcontainer__module_1_1is__variant__type_3_01double_01_4.html", null ],
      [ "container_module::is_variant_type< float >", "structcontainer__module_1_1is__variant__type_3_01float_01_4.html", null ],
      [ "container_module::is_variant_type< int16_t >", "structcontainer__module_1_1is__variant__type_3_01int16__t_01_4.html", null ],
      [ "container_module::is_variant_type< int32_t >", "structcontainer__module_1_1is__variant__type_3_01int32__t_01_4.html", null ],
      [ "container_module::is_variant_type< int64_t >", "structcontainer__module_1_1is__variant__type_3_01int64__t_01_4.html", null ],
      [ "container_module::is_variant_type< std::monostate >", "structcontainer__module_1_1is__variant__type_3_01std_1_1monostate_01_4.html", null ],
      [ "container_module::is_variant_type< std::shared_ptr< thread_safe_container > >", "structcontainer__module_1_1is__variant__type_3_01std_1_1shared__ptr_3_01thread__safe__container_01_4_01_4.html", null ],
      [ "container_module::is_variant_type< std::string >", "structcontainer__module_1_1is__variant__type_3_01std_1_1string_01_4.html", null ],
      [ "container_module::is_variant_type< std::vector< uint8_t > >", "structcontainer__module_1_1is__variant__type_3_01std_1_1vector_3_01uint8__t_01_4_01_4.html", null ],
      [ "container_module::is_variant_type< uint16_t >", "structcontainer__module_1_1is__variant__type_3_01uint16__t_01_4.html", null ],
      [ "container_module::is_variant_type< uint32_t >", "structcontainer__module_1_1is__variant__type_3_01uint32__t_01_4.html", null ],
      [ "container_module::is_variant_type< uint64_t >", "structcontainer__module_1_1is__variant__type_3_01uint64__t_01_4.html", null ],
      [ "thread_pool_module::detail::has_get_method< T, std::void_t< decltype(std::declval< T >().get())> >", "structthread__pool__module_1_1detail_1_1has__get__method_3_01_t_00_01std_1_1void__t_3_01decltyped15719abeb75bab0e7f76d614dc15950.html", null ],
      [ "thread_pool_module::detail::is_duration< std::chrono::duration< Rep, Period > >", "structthread__pool__module_1_1detail_1_1is__duration_3_01std_1_1chrono_1_1duration_3_01_rep_00_01_period_01_4_01_4.html", null ],
      [ "typed_thread_pool_module::detail::has_do_work_method< T, std::void_t< decltype(std::declval< T >().do_work())> >", "structtyped__thread__pool__module_1_1detail_1_1has__do__work__method_3_01_t_00_01std_1_1void__t_8b61f0d08cbbac72013363436e4ca77b.html", null ],
      [ "typed_thread_pool_module::detail::has_priority_method< T, std::void_t< decltype(std::declval< T >().priority())> >", "structtyped__thread__pool__module_1_1detail_1_1has__priority__method_3_01_t_00_01std_1_1void__t_726f3ee9022a4700c38c2263f682386d.html", null ],
      [ "typed_thread_pool_module::detail::is_valid_job_type< T, std::void_t< std::enable_if_t< JobType< T > > > >", "structtyped__thread__pool__module_1_1detail_1_1is__valid__job__type_3_01_t_00_01std_1_1void__t_36fe37be9eab67e017b37496c9908e8c9.html", null ]
    ] ],
    [ "typed_thread_pool_module::typed_job_factory_interface< job_type >", "classtyped__thread__pool__module_1_1typed__job__factory__interface.html", null ],
    [ "typed_thread_pool_module::typed_job_interface< job_type >", "classtyped__thread__pool__module_1_1typed__job__interface.html", null ],
    [ "typed_queue_statistics", "structtyped__queue__statistics.html", null ],
    [ "typed_thread_pool_module::typed_queue_statistics_t< job_type >", "structtyped__thread__pool__module_1_1typed__queue__statistics__t.html", null ],
    [ "typed_thread_pool_module::typed_thread_pool_builder< job_type >", "classtyped__thread__pool__module_1_1typed__thread__pool__builder.html", null ],
    [ "thread_pool_module::detail::validate_thread_count< ThreadCount >", "structthread__pool__module_1_1detail_1_1validate__thread__count.html", null ],
    [ "container_module::variant_value", "classcontainer__module_1_1variant__value.html", null ],
    [ "thread_pool_module::detail::callable_eraser::vtable_t", "structthread__pool__module_1_1detail_1_1callable__eraser_1_1vtable__t.html", null ],
    [ "typed_thread_pool_module::detail::job_eraser::vtable_t", "structtyped__thread__pool__module_1_1detail_1_1job__eraser_1_1vtable__t.html", null ],
    [ "monitoring_interface::worker_metrics", "structmonitoring__interface_1_1worker__metrics.html", null ],
    [ "thread_pool_module::worker_policy", "structthread__pool__module_1_1worker__policy.html", null ],
    [ "container_module::value_container::write_lock_guard", "classcontainer__module_1_1value__container_1_1write__lock__guard.html", null ]
];