Messaging System: monitoring_module::tiered_storage Class Reference
monitoring_module::tiered_storage Class Reference
계층형 저장소
#include <optimized_storage.h>
Classes
struct memory_stats
메모리 사용량 조회
Public Member Functions
tiered_storage (std::size_t hot_capacity, std::size_t warm_capacity, std::size_t cold_capacity)
생성자
void store (const monitoring_interface::metrics_snapshot &snapshot)
메트릭 저장
std::optional< monitoring_interface::metrics_snapshot > retrieve (std::chrono::steady_clock::time_point time_point) const
시간 기반 조회
void perform_aging ()
데이터 에이징 수행
memory_stats get_memory_stats () const
Detailed Description
계층형 저장소
핫/웜/콜드 데이터 계층을 관리하는 저장소
Definition at line 228 of file optimized_storage.h.
Constructor & Destructor Documentation
tiered_storage()
monitoring_module::tiered_storage::tiered_storage (std::size_t hot_capacity, std::size_t warm_capacity, std::size_t cold_capacity)
생성자
Parameters
hot_capacity 핫 계층 용량
warm_capacity 웜 계층 용량
cold_capacity 콜드 계층 용량
Definition at line 128 of file optimized_storage.cpp.
Member Function Documentation
get_memory_stats()
tiered_storage::memory_stats monitoring_module::tiered_storage::get_memory_stats () const
Definition at line 196 of file optimized_storage.cpp.
References monitoring_module::tiered_storage::memory_stats::hot_tier_bytes, and monitoring_module::lock_free_metrics_queue< T >::size().
perform_aging()
void monitoring_module::tiered_storage::perform_aging ()
데이터 에이징 수행
오래된 데이터를 하위 계층으로 이동
Definition at line 170 of file optimized_storage.cpp.
References monitoring_module::lock_free_metrics_queue< T >::dequeue(), and monitoring_module::lock_free_metrics_queue< T >::size().
Referenced by store().
retrieve()
std::optional< monitoring_interface::metrics_snapshot > monitoring_module::tiered_storage::retrieve (std::chrono::steady_clock::time_point time_point) const
시간 기반 조회
Parameters
time_point 조회 시점
Returns
메트릭 스냅샷
Definition at line 149 of file optimized_storage.cpp.
store()
void monitoring_module::tiered_storage::store (const monitoring_interface::metrics_snapshot & snapshot)
메트릭 저장
Parameters
snapshot 메트릭 스냅샷
Definition at line 139 of file optimized_storage.cpp.
References monitoring_module::lock_free_metrics_queue< T >::enqueue(), and perform_aging().
The documentation for this class was generated from the following files:
libraries/monitoring_system/sources/monitoring/optimized_storage.h
libraries/monitoring_system/sources/monitoring/optimized_storage.cpp