Messaging System: application_layer/samples/basic_usage_example.cpp File Reference
basic_usage_example.cpp File Reference
#include <kcenon/messaging/integrations/system_integrator.h>
#include <kcenon/messaging/core/config.h>
#include <kcenon/logger/core/logger.h>
#include <kcenon/logger/writers/console_writer.h>
#include <kcenon/logger/writers/rotating_file_writer.h>
#include <iostream>
#include <thread>
#include <chrono>
#include <sstream>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 15 of file basic_usage_example.cpp.
References kcenon::messaging::config::config_builder::build(), kcenon::messaging::core::message_payload::data, kcenon::messaging::config::config_builder::enable_compression(), kcenon::messaging::core::message::payload, kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), kcenon::messaging::config::config_builder::set_worker_threads(), and kcenon::messaging::core::message_payload::topic.