Messaging System: monitoring_system::adaptive_monitor Class Reference
monitoring_system::adaptive_monitor Class Reference
Adaptive monitoring controller.
#include <adaptive_monitor.h>
Classes
struct monitor_impl
Public Member Functions
adaptive_monitor ()
~adaptive_monitor ()
adaptive_monitor (const adaptive_monitor &)=delete
adaptive_monitor & operator= (const adaptive_monitor &)=delete
adaptive_monitor (adaptive_monitor &&) noexcept
adaptive_monitor & operator= (adaptive_monitor &&) noexcept
monitoring_system::result< bool > register_collector (const std::string &name, std::shared_ptr< monitoring_system::metrics_collector > collector, const adaptive_config &config={})
Register a collector for adaptive monitoring.
monitoring_system::result< bool > unregister_collector (const std::string &name)
Unregister a collector.
monitoring_system::result< bool > start ()
Start adaptive monitoring.
monitoring_system::result< bool > stop ()
Stop adaptive monitoring.
bool is_running () const
Check if monitoring is active.
monitoring_system::result< adaptation_stats > get_collector_stats (const std::string &name) const
Get adaptation statistics for a collector.
std::unordered_map< std::string, adaptation_stats > get_all_stats () const
Get all collector statistics.
void set_global_strategy (adaptation_strategy strategy)
Set global adaptation strategy.
monitoring_system::result< bool > force_adaptation ()
Force adaptation cycle.
std::vector< std::string > get_active_collectors () const
Get recommended collectors based on load.
monitoring_system::result< bool > set_collector_priority (const std::string &name, int priority)
Set priority for a collector (higher priority = keep active longer)
Detailed Description
Adaptive monitoring controller.
Definition at line 317 of file adaptive_monitor.h.
Constructor & Destructor Documentation
adaptive_monitor() [1/3]
monitoring_system::adaptive_monitor::adaptive_monitor ()
Definition at line 89 of file adaptive_monitor.cpp.
~adaptive_monitor()
monitoring_system::adaptive_monitor::~adaptive_monitor () default
adaptive_monitor() [2/3]
monitoring_system::adaptive_monitor::adaptive_monitor (const adaptive_monitor &) delete
adaptive_monitor() [3/3]
monitoring_system::adaptive_monitor::adaptive_monitor (adaptive_monitor &&) default noexcept
Member Function Documentation
force_adaptation()
monitoring_system::result< bool > monitoring_system::adaptive_monitor::force_adaptation ()
Force adaptation cycle.
Definition at line 251 of file adaptive_monitor.cpp.
References monitoring_system::info, and monitoring_system::invalid_state.
get_active_collectors()
std::vector< std::string > monitoring_system::adaptive_monitor::get_active_collectors () const
Get recommended collectors based on load.
Definition at line 279 of file adaptive_monitor.cpp.
References monitoring_system::info.
get_all_stats()
std::unordered_map< std::string, adaptation_stats > monitoring_system::adaptive_monitor::get_all_stats () const
Get all collector statistics.
Definition at line 223 of file adaptive_monitor.cpp.
References monitoring_system::info.
get_collector_stats()
monitoring_system::result< adaptation_stats > monitoring_system::adaptive_monitor::get_collector_stats (const std::string & name) const
Get adaptation statistics for a collector.
Definition at line 200 of file adaptive_monitor.cpp.
References monitoring_system::invalid_state, and monitoring_system::not_found.
Referenced by TEST_F().
is_running()
bool monitoring_system::adaptive_monitor::is_running () const
Check if monitoring is active.
Definition at line 196 of file adaptive_monitor.cpp.
operator=() [1/2]
adaptive_monitor & monitoring_system::adaptive_monitor::operator= (adaptive_monitor &&) default noexcept
operator=() [2/2]
adaptive_monitor & monitoring_system::adaptive_monitor::operator= (const adaptive_monitor &) delete
register_collector()
monitoring_system::result< bool > monitoring_system::adaptive_monitor::register_collector (const std::string & name, std::shared_ptr< monitoring_system::metrics_collector > collector, const adaptive_config & config = {})
Register a collector for adaptive monitoring.
Definition at line 99 of file adaptive_monitor.cpp.
References monitoring_system::already_exists, monitoring_system::adaptive_monitor::monitor_impl::collector_info::collector, monitoring_system::info, and monitoring_system::invalid_argument.
set_collector_priority()
monitoring_system::result< bool > monitoring_system::adaptive_monitor::set_collector_priority (const std::string & name, int priority)
Set priority for a collector (higher priority = keep active longer)
Definition at line 324 of file adaptive_monitor.cpp.
References monitoring_system::not_found.
set_global_strategy()
void monitoring_system::adaptive_monitor::set_global_strategy (adaptation_strategy strategy)
Set global adaptation strategy.
Definition at line 237 of file adaptive_monitor.cpp.
References monitoring_system::info.
start()
monitoring_system::result< bool > monitoring_system::adaptive_monitor::start ()
Start adaptive monitoring.
Definition at line 148 of file adaptive_monitor.cpp.
References monitoring_system::adaptive_monitor::monitor_impl::adaptation_loop(), and monitoring_system::invalid_state.
stop()
monitoring_system::result< bool > monitoring_system::adaptive_monitor::stop ()
Stop adaptive monitoring.
Definition at line 179 of file adaptive_monitor.cpp.
References monitoring_system::invalid_state.
Referenced by AdaptiveMonitoringTest::SetUp(), and AdaptiveMonitoringTest::TearDown().
unregister_collector()
monitoring_system::result< bool > monitoring_system::adaptive_monitor::unregister_collector (const std::string & name)
Unregister a collector.
Definition at line 130 of file adaptive_monitor.cpp.
References monitoring_system::not_found.
Referenced by monitoring_system::adaptive_scope::operator=(), and monitoring_system::adaptive_scope::~adaptive_scope().
The documentation for this class was generated from the following files:
libraries/monitoring_system/src/impl/adaptive_monitor.h
libraries/monitoring_system/src/impl/adaptive_monitor.cpp