Messaging System: thread_module::error Class Reference
thread_module::error Class Reference
Represents an error in the thread system.
#include <error_handling.h>
Public Member Functions
error (error_code code, std::string message={})
Constructs an error with a code and optional message.
error_code code () const noexcept
Gets the error code.
const std::string & message () const noexcept
Gets the error message.
std::string to_string () const
Converts the error to a string representation.
operator std::string () const
Implicit conversion to string.
error (error_code code, std::string message={})
Constructs an error with a code and optional message.
error_code code () const noexcept
Gets the error code.
const std::string & message () const noexcept
Gets the error message.
std::string to_string () const
Converts the error to a string representation.
operator std::string () const
Implicit conversion to string.
error (error_code code, std::string message={})
Constructs an error with a code and optional message.
error_code code () const noexcept
Gets the error code.
const std::string & message () const noexcept
Gets the error message.
std::string to_string () const
Converts the error to a string representation.
operator std::string () const
Implicit conversion to string.
Detailed Description
Represents an error in the thread system.
This class encapsulates an error code and an optional message.
Definition at line 142 of file error_handling.h.
Constructor & Destructor Documentation
error() [1/3]
thread_module::error::error (error_code code, std::string message = {}) inline explicit
Constructs an error with a code and optional message.
Parameters
code The error code
message Optional detailed message about the error
Definition at line 149 of file error_handling.h.
error() [2/3]
thread_module::error::error (error_code code, std::string message = {}) inline explicit
Constructs an error with a code and optional message.
Parameters
code The error code
message Optional detailed message about the error
Definition at line 149 of file error_handling.h.
error() [3/3]
thread_module::error::error (error_code code, std::string message = {}) inline explicit
Constructs an error with a code and optional message.
Parameters
code The error code
message Optional detailed message about the error
Definition at line 149 of file error_handling.h.
Member Function Documentation
code() [1/3]
error_code thread_module::error::code () const inline noexcept
Gets the error code.
Returns
The error code
Definition at line 156 of file error_handling.h.
Referenced by thread_module::test::TEST_F(), TEST_F(), and TEST_F().
code() [2/3]
error_code thread_module::error::code () const inline noexcept
Gets the error code.
Returns
The error code
Definition at line 156 of file error_handling.h.
code() [3/3]
error_code thread_module::error::code () const inline noexcept
Gets the error code.
Returns
The error code
Definition at line 156 of file error_handling.h.
message() [1/3]
const std::string & thread_module::error::message () const inline noexcept
Gets the error message.
Returns
The error message
Definition at line 162 of file error_handling.h.
Referenced by basic_spsc_example(), basic_typed_queue_example(), batch_operations_example(), typed_thread_pool_module::typed_thread_pool_builder< job_type >::build(), create_priority_default(), different_strategies_example(), mpmc_typed_queue_example(), task_scheduling_example(), TEST_F(), and web_server_simulation().
message() [2/3]
const std::string & thread_module::error::message () const inline noexcept
Gets the error message.
Returns
The error message
Definition at line 162 of file error_handling.h.
message() [3/3]
const std::string & thread_module::error::message () const inline noexcept
Gets the error message.
Returns
The error message
Definition at line 162 of file error_handling.h.
operator std::string() [1/3]
thread_module::error::operator std::string () const inline
Implicit conversion to string.
Definition at line 178 of file error_handling.h.
References to_string().
operator std::string() [2/3]
thread_module::error::operator std::string () const inline
Implicit conversion to string.
Definition at line 178 of file error_handling.h.
References to_string().
operator std::string() [3/3]
thread_module::error::operator std::string () const inline
Implicit conversion to string.
Definition at line 178 of file error_handling.h.
References to_string().
to_string() [1/3]
std::string thread_module::error::to_string () const inline
Converts the error to a string representation.
Returns
A string describing the error
Definition at line 168 of file error_handling.h.
References thread_module::error_code_to_string().
Referenced by operator std::string(), thread_module::result< T >::value_or_throw(), thread_module::result< void >::value_or_throw(), and thread_module::result< T >::value_or_throw().
to_string() [2/3]
std::string thread_module::error::to_string () const inline
Converts the error to a string representation.
Returns
A string describing the error
Definition at line 168 of file error_handling.h.
References thread_module::error_code_to_string().
to_string() [3/3]
std::string thread_module::error::to_string () const inline
Converts the error to a string representation.
Returns
A string describing the error
Definition at line 168 of file error_handling.h.
References thread_module::error_code_to_string().
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/thread_base/sync/error_handling.h
libraries/thread_system/modular_structure/core/src/thread_base/sync/error_handling.h
libraries/thread_system/sources/thread_base/sync/error_handling.h