Messaging System: libraries/network_system/samples/messaging_system_integration/legacy_compatibility.cpp File Reference
legacy_compatibility.cpp File Reference
Example of using network_system with legacy messaging_system code.
#include <iostream>
#include <thread>
#include <chrono>
#include <string>
#include "network_system/compatibility.h"
Classes
class LegacyServer
Legacy server implementation.
class LegacyClient
Legacy client implementation.
Functions
void demonstrate_integration_features ()
Demonstrate integration features.
int main (int argc, char *argv[])
Main function demonstrating legacy compatibility.
Detailed Description
Example of using network_system with legacy messaging_system code.
This example demonstrates how existing messaging_system code can work with the new network_system without modification.
Author
kcenon
Date
2025-09-20
Definition in file legacy_compatibility.cpp.
Function Documentation
demonstrate_integration_features()
void demonstrate_integration_features ()
Demonstrate integration features.
Definition at line 138 of file legacy_compatibility.cpp.
References network_system::compat::has_container_support(), network_system::compat::has_thread_support(), network_system::integration::container_manager::instance(), and network_system::integration::thread_integration_manager::instance().
Referenced by main().
main()
int main (int argc, char * argv[])
Main function demonstrating legacy compatibility.
Definition at line 183 of file legacy_compatibility.cpp.
References demonstrate_integration_features(), network_system::compat::initialize(), and network_system::compat::shutdown().