Messaging System: monitoring_system::system_monitor Class Reference
monitoring_system::system_monitor Class Reference
System resource monitor.
#include <performance_monitor.h>
Classes
struct monitor_impl
Public Member Functions
system_monitor ()
~system_monitor ()
system_monitor (const system_monitor &)=delete
system_monitor & operator= (const system_monitor &)=delete
system_monitor (system_monitor &&) noexcept
system_monitor & operator= (system_monitor &&) noexcept
monitoring_system::result< system_metrics > get_current_metrics () const
Get current system metrics.
monitoring_system::result< bool > start_monitoring (std::chrono::milliseconds interval=std::chrono::milliseconds(1000))
Start monitoring system resources.
monitoring_system::result< bool > stop_monitoring ()
Stop monitoring.
bool is_monitoring () const
Check if monitoring is active.
std::vector< system_metrics > get_history (std::chrono::seconds duration=std::chrono::seconds(60)) const
Get historical metrics.
Detailed Description
System resource monitor.
Definition at line 234 of file performance_monitor.h.
Constructor & Destructor Documentation
system_monitor() [1/3]
monitoring_system::system_monitor::system_monitor ()
Definition at line 109 of file performance_monitor.cpp.
~system_monitor()
monitoring_system::system_monitor::~system_monitor () default
system_monitor() [2/3]
monitoring_system::system_monitor::system_monitor (const system_monitor &) delete
system_monitor() [3/3]
monitoring_system::system_monitor::system_monitor (system_monitor &&) default noexcept
Member Function Documentation
get_current_metrics()
result< system_metrics > monitoring_system::system_monitor::get_current_metrics () const
Get current system metrics.
Definition at line 116 of file performance_monitor.cpp.
References monitoring_system::system_metrics::available_memory_bytes, monitoring_system::system_metrics::cpu_usage_percent, monitoring_system::system_metrics::handle_count, monitoring_system::make_success(), monitoring_system::system_metrics::memory_usage_bytes, monitoring_system::system_metrics::memory_usage_percent, monitoring_system::system_metrics::thread_count, and monitoring_system::system_metrics::timestamp.
Referenced by monitoring_system::performance_monitor::collect(), main(), and TEST_F().
get_history()
std::vector< system_metrics > monitoring_system::system_monitor::get_history (std::chrono::seconds duration = std::chrono::seconds(60)) const
Get historical metrics.
Definition at line 159 of file performance_monitor.cpp.
Referenced by TEST_F().
is_monitoring()
bool monitoring_system::system_monitor::is_monitoring () const
Check if monitoring is active.
Definition at line 155 of file performance_monitor.cpp.
operator=() [1/2]
system_monitor & monitoring_system::system_monitor::operator= (const system_monitor &) delete
operator=() [2/2]
system_monitor & monitoring_system::system_monitor::operator= (system_monitor &&) default noexcept
start_monitoring()
result< bool > monitoring_system::system_monitor::start_monitoring (std::chrono::milliseconds interval = std::chrono::milliseconds(1000))
Start monitoring system resources.
Definition at line 131 of file performance_monitor.cpp.
References monitoring_system::make_success().
Referenced by monitoring_system::performance_monitor::initialize(), and TEST_F().
stop_monitoring()
result< bool > monitoring_system::system_monitor::stop_monitoring ()
Stop monitoring.
Definition at line 142 of file performance_monitor.cpp.
References monitoring_system::make_success().
Referenced by monitoring_system::performance_monitor::cleanup(), and TEST_F().
The documentation for this class was generated from the following files:
libraries/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h
libraries/monitoring_system/src/core/performance_monitor.cpp