Messaging System: libraries/database_system/samples/orm_framework_demo.cpp File Reference
orm_framework_demo.cpp File Reference
#include <iostream>
#include <string>
#include <chrono>
#include <memory>
#include "database/database_manager.h"
#include "database/orm/entity.h"
Classes
class User
class Product
Functions
void demonstrate_entity_definition ()
void demonstrate_schema_management ()
void demonstrate_type_safety ()
void demonstrate_entity_queries ()
void demonstrate_entity_lifecycle ()
int main ()
Function Documentation
demonstrate_entity_definition()
void demonstrate_entity_definition ()
Definition at line 109 of file orm_framework_demo.cpp.
References database::orm::entity_base::get_metadata(), and database::orm::entity_metadata::table_name().
Referenced by main().
demonstrate_entity_lifecycle()
void demonstrate_entity_lifecycle ()
Definition at line 235 of file orm_framework_demo.cpp.
Referenced by main().
demonstrate_entity_queries()
void demonstrate_entity_queries ()
Definition at line 203 of file orm_framework_demo.cpp.
Referenced by main().
demonstrate_schema_management()
void demonstrate_schema_management ()
Definition at line 138 of file orm_framework_demo.cpp.
References database::orm::entity_manager::get_metadata(), database::orm::entity_manager::instance(), database::orm::entity_manager::register_entity(), and database::orm::entity_base::table_name().
Referenced by main().
demonstrate_type_safety()
void demonstrate_type_safety ()
Definition at line 173 of file orm_framework_demo.cpp.
Referenced by main().
main()
int main ()
Definition at line 267 of file orm_framework_demo.cpp.
References demonstrate_entity_definition(), demonstrate_entity_lifecycle(), demonstrate_entity_queries(), demonstrate_schema_management(), and demonstrate_type_safety().