Messaging System: kcenon::thread::job Class Reference
kcenon::thread::job Class Reference
Represents a unit of work (task) to be executed, typically by a job queue.
#include <job.h>
Public Member Functions
job (const std::string &name="job")
Constructs a new job with an optional human-readable name.
job (const std::vector< uint8_t > &data, const std::string &name="data_job")
Constructs a new job with associated raw byte data and a name.
virtual ~job (void)
Virtual destructor for the job class to allow proper cleanup in derived classes.
auto get_name (void) const -> std::string
Retrieves the name of this job.
virtual auto do_work (void) -> result_void
The core task execution method to be overridden by derived classes.
virtual auto set_cancellation_token (const cancellation_token &token) -> void
Sets a cancellation token that can be used to cancel the job.
virtual auto get_cancellation_token () const -> cancellation_token
Gets the cancellation token associated with this job.
virtual auto set_job_queue (const std::shared_ptr< job_queue > &job_queue) -> void
Associates this job with a specific job_queue.
virtual auto get_job_queue (void) const -> std::shared_ptr< job_queue >
Retrieves the job_queue associated with this job, if any.
virtual auto to_string (void) const -> std::string
Provides a string representation of the job for logging or debugging.
Protected Attributes
std::string name_
The descriptive name of the job, used primarily for identification and logging.
std::vector< uint8_t > data_
An optional container of raw byte data that may be used by the job.
std::weak_ptr< job_queue > job_queue_
A weak reference to the job_queue that currently manages this job.
cancellation_token cancellation_token_
The cancellation token associated with this job.
Detailed Description
Represents a unit of work (task) to be executed, typically by a job queue.
The job class provides a base interface for scheduling and executing discrete tasks within a multi-threaded environment. Derived classes can override the do_work() method to implement custom logic for their specific tasks.
Thread-Safety
do_work() will generally be called from a worker thread. If your task accesses shared data or interacts with shared resources, you must ensure your implementation is thread-safe.
The job itself is meant to be used via std::shared_ptr, making it easier to manage lifetimes across multiple threads.
Error Handling
A job returns a result_void from do_work().
Returning result_void{} indicates success.
Returning an error indicates failure with a typed error code and message.
Error information can be used for logging, debugging, or to retry a job if desired.
Usage Example
// 1. Create a custom job that overrides do_work().
class my_job : public kcenon::thread::job
{
public:
    my_job() : job("my_custom_job") {}
    result_void do_work() override
    {
        // Execute custom logic:
        bool success = perform_operation();
        if (!success)
            return error{error_code::job_execution_failed, "Operation failed in my_custom_job"};
        return result_void{}; // success
    }
};
// 2. Submit the job to a queue.
auto q = std::make_shared<kcenon::thread::job_queue>();
auto job_ptr = std::make_shared<my_job>();
q->enqueue(job_ptr);
Definition at line 101 of file job.h.
Constructor & Destructor Documentation
job() [1/2]
kcenon::thread::job::job (const std::string & name = "job")
Constructs a new job with an optional human-readable name.
Constructs a basic job with name only.
Use this constructor when your derived job class does not need to store any initial data beyond what you might manually store in derived class members.
Parameters
name A descriptive name for the job (default is "job").
Example
// Creating a basic job with a custom name
auto my_simple_job = std::make_shared<kcenon::thread::job>("simple_job");
Implementation details:
Initializes job with descriptive name for identification
Creates empty data vector (no binary data associated)
Cancellation token is default-constructed (not cancelled)
Job queue is not associated initially (weak_ptr is empty)
Use Cases:
Simple computational jobs without input data
Lambda-based callback jobs
Jobs that generate data rather than process it
Parameters
name Descriptive name for debugging and logging
Definition at line 78 of file job.cpp.
job() [2/2]
kcenon::thread::job::job (const std::vector< uint8_t > & data, const std::string & name = "data_job")
Constructs a new job with associated raw byte data and a name.
Constructs a data-processing job with binary data.
This constructor is particularly useful if your job needs an inline payload or associated data that should be passed directly to do_work().
Parameters
data A vector of bytes serving as the job's payload.
name A descriptive name for the job (default is "data_job").
Example
// Creating a job that has binary data.
std::vector<uint8_t> my_data = {0xDE, 0xAD, 0xBE, 0xEF};
auto data_job = std::make_shared<kcenon::thread::job>(my_data, "data_handling_job");
Implementation details:
Stores binary data for processing during job execution
Data is copied into the job (caller retains ownership of original)
Suitable for file processing, network data handling, etc.
Memory efficient for moderate data sizes
Data Handling:
Data is stored as std::vector<uint8_t> for flexibility
Supports any binary data format (images, documents, network packets)
Data lifetime matches job lifetime (automatic cleanup)
Performance Considerations:
Data is copied during construction (consider move semantics for large data)
Memory usage scales with data size
Efficient for data sizes up to several MB
Parameters
data Binary data to be processed by this job
name Descriptive name for debugging and logging
Definition at line 102 of file job.cpp.
~job()
kcenon::thread::job::~job (void) virtual
Virtual destructor for the job class to allow proper cleanup in derived classes.
Destroys the job and cleans up resources.
Implementation details:
Virtual destructor ensures proper cleanup of derived classes
Automatically cleans up stored data and job queue reference
No manual cleanup required due to RAII design
Safe to destroy even if job is queued (weak_ptr prevents dangling references)
Definition at line 115 of file job.cpp.
Member Function Documentation
do_work()
auto kcenon::thread::job::do_work (void) -> result_void virtual
The core task execution method to be overridden by derived classes.
Default implementation of work execution (must be overridden).
Returns
A std::optional<std::string> indicating success or error:
std::nullopt on success, meaning no error occurred.
A non-empty string on failure, providing an error message or explanation.
Default Behavior
The base class implementation simply returns std::nullopt (i.e., no error). Override this method in a derived class to perform meaningful work.
Concurrency
Typically invoked by worker threads in a job_queue.
Ensure that any shared data or resources accessed here are protected with appropriate synchronization mechanisms (mutexes, locks, etc.) if needed.
The core task execution method to be overridden by derived classes.
Returns
A result_void indicating success or error:
A success result (constructed with result_void{}) if no error occurred.
An error result (constructed with error{error_code, message}) on failure.
Default Behavior
The base class implementation simply returns a success result. Override this method in a derived class to perform meaningful work.
Concurrency
Typically invoked by worker threads in a job_queue.
Ensure that any shared data or resources accessed here are protected with appropriate synchronization mechanisms (mutexes, locks, etc.) if needed.
This method should check the cancellation token if one is set and return an error with code operation_canceled if the token is cancelled.
Implementation details:
Base implementation always returns "not implemented" error
Forces derived classes to provide actual work implementation
Maintains compatibility with result_void error handling
Should never be called in production (indicates missing override)
Design Pattern:
Template method pattern: defines interface, requires implementation
Pure virtual in spirit (returns error instead of being pure virtual)
Enables compilation while encouraging proper inheritance
Derived Class Requirements:
Must override this method to provide actual work logic
Should return empty result_void{} on success
Should return error{...} on failure with descriptive message
Returns
Error indicating method needs to be implemented in derived class
Reimplemented in simple_test_job, simple_test_job, kcenon::thread::callback_job, and kcenon::thread::callback_typed_job_t< job_type >.
Definition at line 150 of file job.cpp.
References kcenon::thread::not_implemented.
Referenced by batch_operations_example(), BM_BatchOperations(), BM_Queue_Batch(), different_strategies_example(), kcenon::thread::callback_job::do_work(), mpmc_example(), mpmc_typed_queue_example(), performance_comparison_example(), strategy_comparison_example(), stress_test_example(), TEST_F(), TEST_F(), and TEST_F().
get_cancellation_token()
auto kcenon::thread::job::get_cancellation_token () const -> cancellation_token virtual
Gets the cancellation token associated with this job.
Gets the current cancellation token.
Returns
The cancellation token, or a default token if none was set.
Implementation details:
Returns copy of stored cancellation token
Thread-safe operation (cancellation_token is thread-safe)
Used by derived classes to check cancellation status
Returns default token if none was set (not cancelled)
Typical Usage in Derived Classes:
auto do_work() -> result_void {
    auto token = get_cancellation_token();
    for (int i = 0; i < large_number; ++i) {
        if (token.is_cancelled()) {
            return error{error_code::cancelled, "Job was cancelled"};
        }
        // Do work...
    }
    return {};
}
Returns
Current cancellation token
Definition at line 207 of file job.cpp.
References cancellation_token_.
get_job_queue()
auto kcenon::thread::job::get_job_queue (void) const -> std::shared_ptr<job_queue> virtual
Retrieves the job_queue associated with this job, if any.
Gets the associated job queue if it still exists.
Returns
A std::shared_ptr to the associated job_queue. Will be empty if no queue was set or if the queue has already been destroyed.
Usage Example
auto jq = get_job_queue();
if (jq)
{
    // Safe to use jq here
}
else
{
    // The queue is no longer valid
}
Implementation details:
Converts weak_ptr to shared_ptr (may return nullptr)
Thread-safe operation (weak_ptr::lock is atomic)
Returns nullptr if queue has been destroyed
Used for advanced job scheduling scenarios
Return Value Interpretation:
Valid shared_ptr: Queue is alive and accessible
nullptr: Queue has been destroyed or was never set
Safety Considerations:
Always check return value before use
Queue may be destroyed between check and use
Designed to fail gracefully if queue is unavailable
Returns
Shared pointer to job queue or nullptr if unavailable
Reimplemented in kcenon::thread::typed_job_t< job_type >, and kcenon::thread::typed_job_t< job_types >.
Definition at line 259 of file job.cpp.
get_name()
auto kcenon::thread::job::get_name (void) const -> std::string
Retrieves the name of this job.
Gets the descriptive name of this job.
Returns
A string containing the name assigned to this job.
The name can be useful for logging and diagnostic messages, especially when multiple jobs are running concurrently.
Implementation details:
Simple accessor for job identification
Thread-safe (string is immutable after construction)
Used for debugging, logging, and diagnostics
Returns
Job name as provided during construction
Definition at line 127 of file job.cpp.
set_cancellation_token()
auto kcenon::thread::job::set_cancellation_token (const cancellation_token & token) -> void virtual
Sets a cancellation token that can be used to cancel the job.
Sets the cancellation token for cooperative cancellation.
Parameters
token The cancellation token to associate with this job.
Implementation details:
Stores cancellation token for use during job execution
Enables cooperative cancellation (job checks token periodically)
Thread-safe assignment (cancellation_token is thread-safe)
Token can be checked during long-running operations
Cancellation Model:
Cooperative: job must check token voluntarily
Non-preemptive: job won't be forcibly stopped
Graceful: allows cleanup before termination
Usage Pattern:
Create cancellation_token
Set token on jobs before submission
Job checks token during execution
External code can signal cancellation
Parameters
token Cancellation token for cooperative cancellation
Definition at line 178 of file job.cpp.
set_job_queue()
auto kcenon::thread::job::set_job_queue (const std::shared_ptr< job_queue > & job_queue) -> void virtual
Associates this job with a specific job_queue.
Associates this job with a job queue for scheduling.
Once assigned, the job can be aware of the queue that manages it, enabling scenarios like re-enqueuing itself upon partial failure, or querying the queue for state (depending on the queue's interface).
Parameters
job_queue A shared pointer to the job_queue instance.
Implementation Detail
Stored internally as a std::weak_ptr. If the queue is destroyed, the pointer becomes invalid.
Implementation details:
Stores weak reference to prevent circular dependencies
Allows job to interact with its queue if needed
Automatic cleanup when queue is destroyed
Used for advanced job management scenarios
Weak Reference Benefits:
Prevents memory leaks from circular references
Queue can be destroyed without affecting jobs
Jobs can check if queue is still alive
No impact on queue lifetime management
Use Cases:
Jobs that need to submit additional jobs
Self-scheduling or recursive jobs
Jobs that need queue statistics
Advanced workflow management
Parameters
job_queue Shared pointer to the job queue
Reimplemented in kcenon::thread::typed_job_t< job_type >, and kcenon::thread::typed_job_t< job_types >.
Definition at line 234 of file job.cpp.
Referenced by kcenon::thread::typed_job_t< job_type >::set_job_queue().
to_string()
auto kcenon::thread::job::to_string (void) const -> std::string virtual
Provides a string representation of the job for logging or debugging.
Provides a string representation of this job.
By default, this returns the job's name. Derived classes can override to include extra diagnostic details (e.g., job status, data contents, etc.).
Returns
A string describing the job (e.g., name_).
Example
std::shared_ptr<my_job> job_ptr = std::make_shared<my_job>();
// ...
std::string desc = job_ptr->to_string(); // "my_custom_job", for instance
Implementation details:
Formats job name for display purposes
Used in debugging, logging, and diagnostics
Consistent format across all job types
Thread-safe operation (accesses immutable name)
Output Format:
"job: <name>" where <name> is the job's descriptive name
Simple, readable format for human consumption
Suitable for log files and debug output
Returns
Formatted string representation of the job
Definition at line 277 of file job.cpp.
References kcenon::thread::utils::formatter::format().
Referenced by main().
Member Data Documentation
cancellation_token_
cancellation_token kcenon::thread::job::cancellation_token_ protected
The cancellation token associated with this job.
This token can be used to cancel the job during execution. The job should periodically check this token and abort if it is cancelled.
Definition at line 284 of file job.h.
Referenced by get_cancellation_token().
data_
std::vector<uint8_t> kcenon::thread::job::data_ protected
An optional container of raw byte data that may be used by the job.
If the constructor without the data parameter is used, this vector will remain empty unless manually populated by derived classes or other means.
Definition at line 268 of file job.h.
job_queue_
std::weak_ptr<job_queue> kcenon::thread::job::job_queue_ protected
A weak reference to the job_queue that currently manages this job.
This reference can expire if the queue is destroyed, so always lock it into a std::shared_ptr before use to avoid invalid access.
Definition at line 276 of file job.h.
name_
std::string kcenon::thread::job::name_ protected
The descriptive name of the job, used primarily for identification and logging.
Definition at line 260 of file job.h.
The documentation for this class was generated from the following files:
libraries/thread_system/include/kcenon/thread/core/job.h
libraries/thread_system/src/core/job.cpp