Messaging System: libraries/monitoring_system/unittest/storage_test/ring_buffer_test.cpp File Reference
ring_buffer_test.cpp File Reference
#include <gtest/gtest.h>
#include <monitoring/storage/ring_buffer.h>
#include <vector>
#include <thread>
Classes
class RingBufferTest
Functions
TEST_F (RingBufferTest, ConstructorTest)
TEST_F (RingBufferTest, PushOperation)
TEST_F (RingBufferTest, OverflowBehavior)
TEST_F (RingBufferTest, ClearOperation)
TEST_F (RingBufferTest, GetRecentOperation)
TEST (RingBufferGenericTest, DifferentTypes)
TEST_F (RingBufferTest, MultithreadedAccess)
TEST_F (RingBufferTest, EdgeCases)
TEST (RingBufferLargeTest, LargeBuffer)
Function Documentation
TEST() [1/2]
TEST (RingBufferGenericTest , DifferentTypes)
Definition at line 124 of file ring_buffer_test.cpp.
References monitoring_module::ring_buffer< T >::get_recent(), monitoring_module::ring_buffer< T >::push(), and monitoring_module::ring_buffer< T >::size().
TEST() [2/2]
TEST (RingBufferLargeTest , LargeBuffer)
Definition at line 181 of file ring_buffer_test.cpp.
References monitoring_module::ring_buffer< T >::full(), monitoring_module::ring_buffer< T >::get_recent(), monitoring_module::ring_buffer< T >::push(), and monitoring_module::ring_buffer< T >::size().
TEST_F() [1/7]
TEST_F (RingBufferTest , ClearOperation)
Definition at line 85 of file ring_buffer_test.cpp.
TEST_F() [2/7]
TEST_F (RingBufferTest , ConstructorTest)
Definition at line 50 of file ring_buffer_test.cpp.
TEST_F() [3/7]
TEST_F (RingBufferTest , EdgeCases)
Definition at line 164 of file ring_buffer_test.cpp.
References monitoring_module::ring_buffer< T >::full(), monitoring_module::ring_buffer< T >::get_recent(), monitoring_module::ring_buffer< T >::push(), and monitoring_module::ring_buffer< T >::size().
TEST_F() [4/7]
TEST_F (RingBufferTest , GetRecentOperation)
Definition at line 101 of file ring_buffer_test.cpp.
TEST_F() [5/7]
TEST_F (RingBufferTest , MultithreadedAccess)
Definition at line 140 of file ring_buffer_test.cpp.
TEST_F() [6/7]
TEST_F (RingBufferTest , OverflowBehavior)
Definition at line 69 of file ring_buffer_test.cpp.
TEST_F() [7/7]
TEST_F (RingBufferTest , PushOperation)
Definition at line 58 of file ring_buffer_test.cpp.