Messaging System: libraries/monitoring_system/benchmarks/storage_benchmarks/ring_buffer_benchmark.cpp File Reference
ring_buffer_benchmark.cpp File Reference
#include <benchmark/benchmark.h>
#include <monitoring/storage/ring_buffer.h>
#include <thread>
#include <vector>
Functions
static void BM_RingBufferPush (benchmark::State &state)
BENCHMARK (BM_RingBufferPush) -> Range(64, 4096)
static void BM_RingBufferGetRecent (benchmark::State &state)
BENCHMARK (BM_RingBufferGetRecent) -> Range(1, 100)
static void BM_RingBufferMultithreaded (benchmark::State &state)
BENCHMARK (BM_RingBufferMultithreaded) -> Range(2, 16)
BENCHMARK_MAIN ()
Function Documentation
BENCHMARK() [1/3]
BENCHMARK (BM_RingBufferGetRecent) -> Range(1, 100)
BENCHMARK() [2/3]
BENCHMARK (BM_RingBufferMultithreaded) -> Range(2, 16)
BENCHMARK() [3/3]
BENCHMARK (BM_RingBufferPush) -> Range(64, 4096)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_RingBufferGetRecent()
static void BM_RingBufferGetRecent (benchmark::State & state) static
Definition at line 29 of file ring_buffer_benchmark.cpp.
References monitoring_module::ring_buffer< T >::get_recent(), and monitoring_module::ring_buffer< T >::push().
BM_RingBufferMultithreaded()
static void BM_RingBufferMultithreaded (benchmark::State & state) static
Definition at line 48 of file ring_buffer_benchmark.cpp.
References monitoring_module::ring_buffer< T >::push().
BM_RingBufferPush()
static void BM_RingBufferPush (benchmark::State & state) static
Definition at line 15 of file ring_buffer_benchmark.cpp.
References monitoring_module::ring_buffer< T >::push().