Messaging System: network_system::integration::thread_integration_manager Class Reference
network_system::integration::thread_integration_manager Class Reference
Manager for thread system integration.
#include <thread_integration.h>
Classes
class impl
struct metrics
Get thread pool metrics.
Public Member Functions
void set_thread_pool (std::shared_ptr< thread_pool_interface > pool)
Set the thread pool implementation.
std::shared_ptr< thread_pool_interface > get_thread_pool ()
Get the current thread pool.
std::future< void > submit_task (std::function< void()> task)
Submit a task to the thread pool.
std::future< void > submit_delayed_task (std::function< void()> task, std::chrono::milliseconds delay)
Submit a task with delay.
metrics get_metrics () const
Get current metrics.
Static Public Member Functions
static thread_integration_manager & instance ()
Get the singleton instance.
Detailed Description
Manager for thread system integration.
This class manages the integration between network_system and thread pool implementations.
Definition at line 121 of file thread_integration.h.
Member Function Documentation
get_metrics()
thread_integration_manager::metrics network_system::integration::thread_integration_manager::get_metrics () const
Get current metrics.
Returns
Current thread pool metrics
Definition at line 277 of file thread_integration.cpp.
Referenced by ModernServer::show_statistics().
get_thread_pool()
std::shared_ptr< thread_pool_interface > network_system::integration::thread_integration_manager::get_thread_pool ()
Get the current thread pool.
Returns
Current thread pool (creates basic pool if none set)
Definition at line 260 of file thread_integration.cpp.
Referenced by network_system::integration::messaging_bridge::get_thread_pool_interface().
instance()
thread_integration_manager & network_system::integration::thread_integration_manager::instance () static
Get the singleton instance.
Returns
Reference to the singleton instance
Definition at line 243 of file thread_integration.cpp.
References instance().
Referenced by benchmark_thread_pool(), demonstrate_integration_features(), network_system::integration::messaging_bridge::get_thread_pool_interface(), network_system::compat::initialize(), instance(), ModernServer::ModernServer(), ModernClient::send_async(), ModernServer::show_statistics(), network_system::compat::shutdown(), test_init_shutdown(), test_legacy_thread_integration(), test_thread_integration(), and test_thread_pool_integration().
set_thread_pool()
void network_system::integration::thread_integration_manager::set_thread_pool (std::shared_ptr< thread_pool_interface > pool)
Set the thread pool implementation.
Parameters
pool Thread pool to use
Definition at line 254 of file thread_integration.cpp.
submit_delayed_task()
std::future< void > network_system::integration::thread_integration_manager::submit_delayed_task (std::function< void()> task, std::chrono::milliseconds delay)
Submit a task with delay.
Parameters
task The task to execute
delay Delay before execution
Returns
Future for the task result
Definition at line 270 of file thread_integration.cpp.
submit_task()
std::future< void > network_system::integration::thread_integration_manager::submit_task (std::function< void()> task)
Submit a task to the thread pool.
Parameters
task The task to execute
Returns
Future for the task result
Definition at line 264 of file thread_integration.cpp.
The documentation for this class was generated from the following files:
libraries/network_system/include/network_system/integration/thread_integration.h
libraries/network_system/src/integration/thread_integration.cpp