Messaging System: StorageBackendsTest Class Reference
StorageBackendsTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
std::vector< metrics_snapshot > create_test_snapshots ()
Protected Attributes
std::vector< metrics_snapshot > test_snapshots_
std::filesystem::path test_dir_
Detailed Description
Definition at line 17 of file test_storage_backends.cpp.
Member Function Documentation
create_test_snapshots()
std::vector< metrics_snapshot > StorageBackendsTest::create_test_snapshots () inline protected
Definition at line 35 of file test_storage_backends.cpp.
References monitoring_system::metrics_snapshot::add_metric(), monitoring_system::metrics_snapshot::capture_time, and monitoring_system::metrics_snapshot::source_id.
Referenced by SetUp().
SetUp()
void StorageBackendsTest::SetUp () inline override protected
Definition at line 19 of file test_storage_backends.cpp.
References create_test_snapshots(), test_dir_, and test_snapshots_.
TearDown()
void StorageBackendsTest::TearDown () inline override protected
Definition at line 28 of file test_storage_backends.cpp.
References test_dir_.
Member Data Documentation
test_dir_
std::filesystem::path StorageBackendsTest::test_dir_ protected
Definition at line 69 of file test_storage_backends.cpp.
Referenced by SetUp(), and TearDown().
test_snapshots_
std::vector<metrics_snapshot> StorageBackendsTest::test_snapshots_ protected
Definition at line 68 of file test_storage_backends.cpp.
Referenced by SetUp().
The documentation for this class was generated from the following file:
libraries/monitoring_system/tests/test_storage_backends.cpp