Messaging System: libraries/thread_system/benchmarks/thread_pool_benchmarks/gbench_thread_pool.cpp File Reference
gbench_thread_pool.cpp File Reference
Google Benchmark tests for thread pool.
#include <benchmark/benchmark.h>
#include "../../sources/thread_pool/core/thread_pool.h"
#include "../../sources/thread_pool/workers/thread_worker.h"
#include "../../sources/thread_base/jobs/callback_job.h"
#include <atomic>
#include <memory>
#include <vector>
Functions
static std::shared_ptr< thread_pool > create_pool_with_workers (size_t worker_count)
static void BM_ThreadPoolCreation (benchmark::State &state)
BENCHMARK (BM_ThreadPoolCreation) -> Arg(1) ->Arg(2) ->Arg(4) ->Arg(8) ->Arg(16)
static void BM_EmptyJobSubmission (benchmark::State &state)
BENCHMARK (BM_EmptyJobSubmission) -> Arg(1) ->Arg(2) ->Arg(4) ->Arg(8)
static void BM_JobThroughput (benchmark::State &state)
BENCHMARK (BM_JobThroughput) -> Args({1, 0}) ->Args({2, 0}) ->Args({4, 0}) ->Args({8, 0}) ->Args({8, 1}) ->Args({8, 10}) ->Args({8, 100}) ->Args({8, 1000})
static void BM_BatchJobSubmission (benchmark::State &state)
BENCHMARK (BM_BatchJobSubmission) -> Args({4, 10}) ->Args({4, 100}) ->Args({4, 1000}) ->Args({8, 10}) ->Args({8, 100}) ->Args({8, 1000})
static void BM_ScalingEfficiency (benchmark::State &state)
BENCHMARK (BM_ScalingEfficiency) -> Arg(1) ->Arg(2) ->Arg(4) ->Arg(8) ->Arg(16)
BENCHMARK_MAIN ()
Detailed Description
Google Benchmark tests for thread pool.
Definition in file gbench_thread_pool.cpp.
Function Documentation
BENCHMARK() [1/5]
BENCHMARK (BM_BatchJobSubmission) -> Args({4, 10}) ->Args({4, 100}) ->Args({4, 1000}) ->Args({8, 10}) ->Args({8, 100}) ->Args({8, 1000})
BENCHMARK() [2/5]
BENCHMARK (BM_EmptyJobSubmission) -> Arg(1) ->Arg(2) ->Arg(4) ->Arg(8)
BENCHMARK() [3/5]
BENCHMARK (BM_JobThroughput) -> Args({1, 0}) ->Args({2, 0}) ->Args({4, 0}) ->Args({8, 0}) ->Args({8, 1}) ->Args({8, 10}) ->Args({8, 100}) ->Args({8, 1000})
BENCHMARK() [4/5]
BENCHMARK (BM_ScalingEfficiency) -> Arg(1) ->Arg(2) ->Arg(4) ->Arg(8) ->Arg(16)
BENCHMARK() [5/5]
BENCHMARK (BM_ThreadPoolCreation) -> Arg(1) ->Arg(2) ->Arg(4) ->Arg(8) ->Arg(16)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_BatchJobSubmission()
static void BM_BatchJobSubmission (benchmark::State & state) static
Definition at line 129 of file gbench_thread_pool.cpp.
References create_pool_with_workers().
BM_EmptyJobSubmission()
static void BM_EmptyJobSubmission (benchmark::State & state) static
Definition at line 75 of file gbench_thread_pool.cpp.
References create_pool_with_workers().
BM_JobThroughput()
static void BM_JobThroughput (benchmark::State & state) static
Definition at line 94 of file gbench_thread_pool.cpp.
References create_pool_with_workers(), and jobs_completed.
BM_ScalingEfficiency()
static void BM_ScalingEfficiency (benchmark::State & state) static
Definition at line 158 of file gbench_thread_pool.cpp.
References create_pool_with_workers(), and jobs_completed.
BM_ThreadPoolCreation()
static void BM_ThreadPoolCreation (benchmark::State & state) static
Definition at line 63 of file gbench_thread_pool.cpp.
References create_pool_with_workers().
create_pool_with_workers()
static std::shared_ptr< thread_pool > create_pool_with_workers (size_t worker_count) static
Definition at line 49 of file gbench_thread_pool.cpp.
Referenced by BM_BatchJobSubmission(), BM_EmptyJobSubmission(), BM_JobThroughput(), BM_ScalingEfficiency(), and BM_ThreadPoolCreation().