Messaging System: VersionCompatibilityTest Class Reference
VersionCompatibilityTest Class Reference
Classes
struct LogEntry
Protected Member Functions
void SetUp () override
void TearDown () override
void create_v1_log_file ()
void create_v2_log_file ()
LogEntry parse_v1_log_line (const std::string &line)
LogEntry parse_v2_log_line (const std::string &line)
Detailed Description
Definition at line 29 of file version_compatibility_test.cpp.
Member Function Documentation
create_v1_log_file()
void VersionCompatibilityTest::create_v1_log_file () inline protected
Definition at line 53 of file version_compatibility_test.cpp.
Referenced by SetUp().
create_v2_log_file()
void VersionCompatibilityTest::create_v2_log_file () inline protected
Definition at line 64 of file version_compatibility_test.cpp.
Referenced by SetUp().
parse_v1_log_line()
LogEntry VersionCompatibilityTest::parse_v1_log_line (const std::string & line) inline protected
Definition at line 84 of file version_compatibility_test.cpp.
References VersionCompatibilityTest::LogEntry::level, VersionCompatibilityTest::LogEntry::message, and VersionCompatibilityTest::LogEntry::timestamp.
parse_v2_log_line()
LogEntry VersionCompatibilityTest::parse_v2_log_line (const std::string & line) inline protected
Definition at line 98 of file version_compatibility_test.cpp.
References VersionCompatibilityTest::LogEntry::file, VersionCompatibilityTest::LogEntry::function, VersionCompatibilityTest::LogEntry::level, VersionCompatibilityTest::LogEntry::line, VersionCompatibilityTest::LogEntry::message, and VersionCompatibilityTest::LogEntry::timestamp.
SetUp()
void VersionCompatibilityTest::SetUp () inline override protected
Definition at line 31 of file version_compatibility_test.cpp.
References create_v1_log_file(), and create_v2_log_file().
TearDown()
void VersionCompatibilityTest::TearDown () inline override protected
Definition at line 46 of file version_compatibility_test.cpp.
The documentation for this class was generated from the following file:
libraries/logger_system/tests/compatibility/version_compatibility_test.cpp