Messaging System: monitoring_system::monitoring_aggregator Class Reference
monitoring_system::monitoring_aggregator Class Reference
Utility class to aggregate metrics from multiple monitorable components.
#include <monitorable_interface.h>
Public Member Functions
monitoring_aggregator (const std::string &id="aggregator")
Constructor.
void add_component (std::shared_ptr< monitorable_interface > component)
Add a component to monitor.
bool remove_component (const std::string &id)
Remove a component by ID.
result< monitoring_data > collect_all () const
Collect data from all components.
std::shared_ptr< monitorable_interface > get_component (const std::string &id) const
Get a specific component by ID.
std::vector< std::string > get_component_ids () const
Get all component IDs.
void clear ()
Clear all components.
std::size_t size () const
Get the number of registered components.
Detailed Description
Utility class to aggregate metrics from multiple monitorable components.
Definition at line 338 of file monitorable_interface.h.
Constructor & Destructor Documentation
monitoring_aggregator()
monitoring_system::monitoring_aggregator::monitoring_aggregator (const std::string & id = "aggregator") inline explicit
Constructor.
Parameters
id Identifier for this aggregator
Definition at line 348 of file monitorable_interface.h.
Member Function Documentation
add_component()
void monitoring_system::monitoring_aggregator::add_component (std::shared_ptr< monitorable_interface > component) inline
Add a component to monitor.
Parameters
component Component to add
Definition at line 355 of file monitorable_interface.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
clear()
void monitoring_system::monitoring_aggregator::clear () inline
Clear all components.
Definition at line 444 of file monitorable_interface.h.
Referenced by TEST_F().
collect_all()
result< monitoring_data > monitoring_system::monitoring_aggregator::collect_all () const inline
Collect data from all components.
Returns
Aggregated monitoring data
Definition at line 383 of file monitorable_interface.h.
References monitoring_system::monitoring_data::add_metric(), monitoring_system::monitoring_data::add_tag(), monitoring_system::result< T >::get_error(), monitoring_system::make_success(), monitoring_system::monitoring_data::merge(), monitoring_system::error_info::message, monitoring_system::monitoring_data::metric_count(), and monitoring_system::result< T >::value().
Referenced by TEST_F(), and TEST_F().
get_component()
std::shared_ptr< monitorable_interface > monitoring_system::monitoring_aggregator::get_component (const std::string & id) const inline
Get a specific component by ID.
Parameters
id Component ID
Returns
Shared pointer to component or nullptr
Definition at line 417 of file monitorable_interface.h.
Referenced by TEST_F().
get_component_ids()
std::vector< std::string > monitoring_system::monitoring_aggregator::get_component_ids () const inline
Get all component IDs.
Returns
Vector of component identifiers
Definition at line 430 of file monitorable_interface.h.
Referenced by TEST_F(), and TEST_F().
remove_component()
bool monitoring_system::monitoring_aggregator::remove_component (const std::string & id) inline
Remove a component by ID.
Parameters
id Component ID to remove
Returns
true if component was found and removed
Definition at line 366 of file monitorable_interface.h.
Referenced by TEST_F().
size()
std::size_t monitoring_system::monitoring_aggregator::size () const inline
Get the number of registered components.
Returns
Component count
Definition at line 452 of file monitorable_interface.h.
Referenced by TEST_F(), and TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/interfaces/monitorable_interface.h