Messaging System: metrics_collector Class Reference
metrics_collector Class Reference
Classes
struct metrics
Public Member Functions
metrics_collector (std::shared_ptr< logger_module::logger > logger)
~metrics_collector ()
void start (std::chrono::seconds report_interval=10s)
void stop ()
void increment_sent ()
void increment_received ()
void increment_errors ()
void increment_retries ()
void increment_successful_retries ()
void report ()
Detailed Description
Definition at line 41 of file production_ready_example.cpp.
Constructor & Destructor Documentation
metrics_collector()
metrics_collector::metrics_collector (std::shared_ptr< logger_module::logger > logger) inline explicit
Definition at line 61 of file production_ready_example.cpp.
~metrics_collector()
metrics_collector::~metrics_collector () inline
Definition at line 64 of file production_ready_example.cpp.
References stop().
Member Function Documentation
increment_errors()
void metrics_collector::increment_errors () inline
Definition at line 100 of file production_ready_example.cpp.
Referenced by retry_handler::execute_with_retry(), and main().
increment_received()
void metrics_collector::increment_received () inline
Definition at line 99 of file production_ready_example.cpp.
Referenced by main().
increment_retries()
void metrics_collector::increment_retries () inline
Definition at line 101 of file production_ready_example.cpp.
Referenced by retry_handler::execute_with_retry().
increment_sent()
void metrics_collector::increment_sent () inline
Definition at line 98 of file production_ready_example.cpp.
increment_successful_retries()
void metrics_collector::increment_successful_retries () inline
Definition at line 102 of file production_ready_example.cpp.
Referenced by retry_handler::execute_with_retry().
report()
void metrics_collector::report () inline
Definition at line 104 of file production_ready_example.cpp.
Referenced by start(), and stop().
start()
void metrics_collector::start (std::chrono::seconds report_interval = 10s) inline
Definition at line 68 of file production_ready_example.cpp.
References g_shutdown_cv, g_shutdown_mutex, and report().
Referenced by main().
stop()
void metrics_collector::stop () inline
Definition at line 85 of file production_ready_example.cpp.
References report().
Referenced by ~metrics_collector().
The documentation for this class was generated from the following file:
application_layer/samples/production_ready_example.cpp