Messaging System: monitoring_module::monitoring_crash_safety Class Reference
monitoring_module::monitoring_crash_safety Class Reference
Monitoring crash safety manager.
#include <monitoring_crash_safety.h>
Classes
struct monitoring_safety_stats
Get monitoring crash safety statistics.
Public Member Functions
void initialize (monitoring_crash_safety_level level=monitoring_crash_safety_level::standard, const std::string &backup_path="./monitoring_backup.dat", uint32_t backup_interval_ms=1000)
Initialize crash safety for monitoring system.
void register_monitoring_component (const std::string &component_name, std::function< std::string()> save_state_callback, std::function< void(const std::string &)> restore_state_callback)
Register a monitoring component for crash protection.
void unregister_monitoring_component (const std::string &component_name)
Unregister a monitoring component.
void preserve_critical_metrics (const critical_metrics_snapshot &snapshot)
Preserve critical metrics snapshot.
void set_backup_path (const std::string &path)
Set metrics backup file path.
void set_realtime_backup (bool enable, uint32_t interval_ms=1000)
Enable/disable real-time metrics backup.
void force_save_all_states ()
Force immediate save of all monitoring states.
void force_restore_all_states ()
Force immediate restore of all monitoring states.
bool is_handling_crash () const
Check if currently handling a monitoring crash.
void set_max_critical_snapshots (size_t max_snapshots)
Set maximum critical metrics to keep in memory.
monitoring_safety_stats get_stats () const
bool check_and_recover ()
Recovery check - detect and recover from previous crashes.
std::vector< critical_metrics_snapshot > get_preserved_metrics () const
Get last preserved critical metrics.
Static Public Member Functions
static monitoring_crash_safety & instance ()
Get the global monitoring crash safety instance.
Detailed Description
Monitoring crash safety manager.
Provides comprehensive crash safety for monitoring systems:
Real-time metrics backup
Critical data preservation
Monitoring state recovery
Performance data continuity
Alert system crash protection
Definition at line 58 of file monitoring_crash_safety.h.
Member Function Documentation
check_and_recover()
bool monitoring_module::monitoring_crash_safety::check_and_recover ()
Recovery check - detect and recover from previous crashes.
Returns
true if recovery actions were taken
force_restore_all_states()
void monitoring_module::monitoring_crash_safety::force_restore_all_states ()
Force immediate restore of all monitoring states.
force_save_all_states()
void monitoring_module::monitoring_crash_safety::force_save_all_states ()
Force immediate save of all monitoring states.
Referenced by on_monitoring_component_crash().
get_preserved_metrics()
std::vector< critical_metrics_snapshot > monitoring_module::monitoring_crash_safety::get_preserved_metrics () const
Get last preserved critical metrics.
Returns
Vector of preserved metrics snapshots
get_stats()
monitoring_safety_stats monitoring_module::monitoring_crash_safety::get_stats () const
initialize()
void monitoring_module::monitoring_crash_safety::initialize (monitoring_crash_safety_level level = monitoring_crash_safety_level::standard, const std::string & backup_path = "./monitoring_backup.dat", uint32_t backup_interval_ms = 1000)
Initialize crash safety for monitoring system.
Parameters
level Safety level to configure
backup_path Path for metrics backup
backup_interval_ms Backup creation interval
instance()
static monitoring_crash_safety & monitoring_module::monitoring_crash_safety::instance () static
Get the global monitoring crash safety instance.
Referenced by main(), metrics_collection_task(), on_monitoring_component_crash(), risky_monitoring_task(), monitoring_module::scoped_monitoring_crash_protection::scoped_monitoring_crash_protection(), and monitoring_module::scoped_monitoring_crash_protection::~scoped_monitoring_crash_protection().
is_handling_crash()
bool monitoring_module::monitoring_crash_safety::is_handling_crash () const
Check if currently handling a monitoring crash.
Returns
true if handling crash
preserve_critical_metrics()
void monitoring_module::monitoring_crash_safety::preserve_critical_metrics (const critical_metrics_snapshot & snapshot)
Preserve critical metrics snapshot.
Parameters
snapshot Metrics snapshot to preserve
Referenced by metrics_collection_task(), and risky_monitoring_task().
register_monitoring_component()
void monitoring_module::monitoring_crash_safety::register_monitoring_component (const std::string & component_name, std::function< std::string()> save_state_callback, std::function< void(const std::string &)> restore_state_callback)
Register a monitoring component for crash protection.
Parameters
component_name Unique name for the component
save_state_callback Function to save component state
restore_state_callback Function to restore component state
Referenced by monitoring_module::scoped_monitoring_crash_protection::scoped_monitoring_crash_protection().
set_backup_path()
void monitoring_module::monitoring_crash_safety::set_backup_path (const std::string & path)
Set metrics backup file path.
Parameters
path Path to backup file
set_max_critical_snapshots()
void monitoring_module::monitoring_crash_safety::set_max_critical_snapshots (size_t max_snapshots)
Set maximum critical metrics to keep in memory.
Parameters
max_snapshots Maximum number of snapshots
set_realtime_backup()
void monitoring_module::monitoring_crash_safety::set_realtime_backup (bool enable, uint32_t interval_ms = 1000)
Enable/disable real-time metrics backup.
Parameters
enable Whether to enable real-time backup
interval_ms Backup interval in milliseconds
unregister_monitoring_component()
void monitoring_module::monitoring_crash_safety::unregister_monitoring_component (const std::string & component_name)
Unregister a monitoring component.
Parameters
component_name Name of component to unregister
Referenced by monitoring_module::scoped_monitoring_crash_protection::~scoped_monitoring_crash_protection().
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/interfaces/monitoring_crash_safety.h