Messaging System: libraries/thread_system/samples/integration_example/integration_example.cpp File Reference
integration_example.cpp File Reference
Demonstrates integration of thread_system with external logger and monitoring.
#include <iostream>
#include <chrono>
#include <thread>
#include <vector>
#include "../../sources/interfaces/service_container.h"
#include "../../sources/interfaces/thread_context.h"
#include "../../sources/thread_pool/core/thread_pool.h"
#include "../../sources/thread_base/jobs/callback_job.h"
#include "mock_logger.h"
#include "mock_monitoring.h"
Functions
void thread_pool_with_logger_example ()
Example 1: Thread pool with external logger only.
void thread_pool_with_monitoring_example ()
Example 2: Thread pool with external monitoring only.
void complete_integration_example ()
Example 3: Complete integration with both logger and monitoring.
void dynamic_service_example ()
Example 4: Dynamic service registration.
int main ()
Detailed Description
Demonstrates integration of thread_system with external logger and monitoring.
This example shows how to:
Use thread_system with external logger implementation
Use thread_system with external monitoring implementation
Combine both for a complete system
Note: This example assumes logger_system and monitoring_system are installed or available in the build path.
Definition in file integration_example.cpp.
Function Documentation
complete_integration_example()
void complete_integration_example ()
Example 3: Complete integration with both logger and monitoring.
Definition at line 189 of file integration_example.cpp.
References thread_module::service_container::clear(), thread_module::service_container::global(), and thread_module::service_container::register_singleton().
Referenced by main().
dynamic_service_example()
void dynamic_service_example ()
Example 4: Dynamic service registration.
Definition at line 283 of file integration_example.cpp.
References thread_module::service_container::clear(), thread_module::service_container::global(), and thread_module::service_container::register_singleton().
Referenced by main().
main()
int main ()
Definition at line 337 of file integration_example.cpp.
References complete_integration_example(), dynamic_service_example(), thread_pool_with_logger_example(), and thread_pool_with_monitoring_example().
thread_pool_with_logger_example()
void thread_pool_with_logger_example ()
Example 1: Thread pool with external logger only.
Definition at line 74 of file integration_example.cpp.
References thread_module::service_container::clear(), thread_module::service_container::global(), and thread_module::service_container::register_singleton().
Referenced by main().
thread_pool_with_monitoring_example()
void thread_pool_with_monitoring_example ()
Example 2: Thread pool with external monitoring only.
Definition at line 126 of file integration_example.cpp.
References thread_module::service_container::clear(), thread_module::service_container::global(), and thread_module::service_container::register_singleton().
Referenced by main().