var searchData=
[
  ['websocket_20transport_0',['WebSocket Transport',['../da/db6/md_docs_2FEATURES.html#autotoc_md635',1,'']]],
  ['what_20about_20performance_1',['Q: What about performance?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md975',1,'']]],
  ['what_20c_20standard_20is_20required_2',['Q: What C++ standard is required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md910',1,'']]],
  ['what_20dependencies_20are_20required_3',['Q: What dependencies are required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md915',1,'']]],
  ['what_20is_20an_20adr_4',['What is an ADR?',['../index.html#autotoc_md53',1,'']]],
  ['what_20is_20messaging_5fsystem_5',['Q: What is messaging_system?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md909',1,'']]],
  ['what_20is_20the_20latency_6',['Q: What is the latency?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md924',1,'']]],
  ['what_20s_20included_7',['📦 What&apos;s Included',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2108',1,'']]],
  ['what_20throughput_20can_20i_20expect_8',['Q: What throughput can I expect?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md923',1,'']]],
  ['which_20platforms_20are_20supported_9',['Q: Which platforms are supported?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md911',1,'']]],
  ['wildcard_20patterns_10',['Wildcard Patterns',['../da/db6/md_docs_2FEATURES.html#autotoc_md645',1,'']]],
  ['wildcards_11',['Q: How do I use wildcards?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md920',1,'']]],
  ['windows_12',['Windows',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md996',1,'']]],
  ['windows_20ci_20performance_20optimization_13',['Windows CI Performance Optimization',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html',1,'']]],
  ['windows_5foptimization_2emd_14',['WINDOWS_OPTIMIZATION.md',['../d9/dea/WINDOWS__OPTIMIZATION_8md.html',1,'']]],
  ['wins_15',['Short-Term (Quick Wins)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md242',1,'']]],
  ['with_20base_20systems_16',['🌟 Integration with Base Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2131',1,'']]],
  ['with_20many_20topics_17',['Issue 5: Performance Degradation with Many Topics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1067',1,'']]],
  ['with_20network_5fsystem_18',['Using with network_system',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1100',1,'']]],
  ['with_20old_20includes_19',['Issue: Compilation errors with old includes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md966',1,'']]],
  ['with_20other_20systems_20',['with other systems',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md506',1,'Comparison with Other Systems'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md952',1,'Step 7: Integration with Other Systems']]],
  ['with_20perf_21',['Performance Profiling with perf',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1047',1,'']]],
  ['with_20retry_22',['Chain with Retry',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1885',1,'']]],
  ['with_20sample_20client_23',['3. Test with Sample Client',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1012',1,'']]],
  ['with_20small_20messages_24',['Issue 1: High CPU Usage with Small Messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1063',1,'']]],
  ['with_20strace_25',['System Tracing with strace',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1046',1,'']]],
  ['with_20subsystems_26',['Integration with Subsystems',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1092',1,'']]],
  ['with_20thread_5fsystem_27',['Using with thread_system',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1099',1,'']]],
  ['with_20transport_28',['Usage Example (Hybrid Mode with Transport)',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md315',1,'']]],
  ['won_20t_20start_29',['won t start',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1079',1,'Problem: Service Won&apos;t Start'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md844',1,'Service Won&apos;t Start']]],
  ['worker_20pool_30',['worker pool',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2059',1,'2.2 Worker Pool'],['../da/db6/md_docs_2FEATURES.html#autotoc_md606',1,'Worker Pool']]],
  ['worker_20pool_20configuration_31',['Worker Pool Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1692',1,'']]],
  ['worker_20scalability_32',['Worker Scalability',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md478',1,'']]],
  ['worker_20status_33',['worker status',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1996',1,'Check Worker Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1481',1,'Worker Status']]],
  ['worker_20system_34',['Phase 2: Worker System',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2057',1,'']]],
  ['worker_20system_20✅_35',['Sprint 3: Worker System ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2084',1,'']]],
  ['worker_20throughput_36',['Worker Throughput',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md477',1,'']]],
  ['worker_5fpool_37',['worker_pool',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1623',1,'4. worker_pool'],['../d9/db8/md_docs_2task_2ARCHITECTURE__KO.html#autotoc_md1654',1,'4. worker_pool'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1428',1,'worker_pool'],['../dd/db9/md_docs_2task_2API__REFERENCE__KO.html#autotoc_md1547',1,'worker_pool']]],
  ['workflow_38',['workflow',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2158',1,'Development Workflow'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md576',1,'Development Workflow'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md740',1,'Recommended Build Workflow'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md889',1,'Workflow']]],
  ['workflow_20patterns_39',['workflow patterns',['../d5/dd2/md_docs_2task_2PATTERNS.html',1,'Task Module Workflow Patterns'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1441',1,'Workflow Patterns']]],
  ['working_40',['Retry Not Working',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1989',1,'']]],
  ['workload_20type_41',['By Workload Type',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1718',1,'']]]
];
