var searchData=
[
  ['p_20not_20supported_20macos_0',['Issue 3: grep -P Not Supported (macOS)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md606',1,'']]],
  ['package_20managers_1',['Using Package Managers',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md644',1,'']]],
  ['parallel_20execution_20✅_2',['2. CTest Parallel Execution ✅',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md179',1,'']]],
  ['parallelization_20✅_3',['3. Build Parallelization ✅',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md180',1,'']]],
  ['parameters_4',['Linux Kernel Parameters',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md669',1,'']]],
  ['paths_5',['Update Include Paths',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md814',1,'']]],
  ['pattern_6',['pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md3',1,'1. Singleton Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md14',1,'10. Strategy Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md15',1,'11. Chain of Responsibility Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md16',1,'12. Command Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md17',1,'13. Template Method Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md19',1,'14. Producer-Consumer Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md20',1,'15. Thread Pool Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md22',1,'16. Microkernel Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md4',1,'2. Factory Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md5',1,'3. Builder Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md6',1,'4. Object Pool Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md8',1,'5. Adapter Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md9',1,'6. Decorator Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md10',1,'7. Proxy Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md11',1,'8. Composite Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md13',1,'9. Observer Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md121',1,'Event Streaming Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md65',1,'Event Streaming Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md122',1,'Message Pipeline Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md87',1,'Message Pipeline Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1264',1,'Pub/Sub Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md524',1,'Pub/Sub Pattern'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md819',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md28',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md119',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md45',1,'Request-Reply Pattern'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md820',1,'Request-Reply Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md120',1,'Request-Reply Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1265',1,'Request/Reply Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md525',1,'Request/Reply Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md553',1,'Result&lt;T&gt; Pattern']]],
  ['pattern_20matching_20performance_7',['Pattern Matching Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md402',1,'']]],
  ['pattern_20performance_8',['Pattern Performance',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md975',1,'']]],
  ['patterns_9',['patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md21',1,'Architectural Patterns'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md12',1,'Behavioral Patterns'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md18',1,'Concurrency Patterns'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md2',1,'Creational Patterns'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1127',1,'Include Patterns'],['../da/db6/md_docs_2FEATURES.html#autotoc_md523',1,'Messaging Patterns'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md143',1,'Scalability Patterns'],['../d2/d64/md_docs_2architecture.html#autotoc_md330',1,'Scalability Patterns'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md7',1,'Structural Patterns'],['../da/db6/md_docs_2FEATURES.html#autotoc_md541',1,'Wildcard Patterns']]],
  ['patterns_20and_20architectural_20decisions_10',['Design Patterns and Architectural Decisions',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html',1,'']]],
  ['patterns_20api_20reference_11',['Messaging Patterns API Reference',['../df/dde/md_docs_2advanced_2PATTERNS__API.html',1,'']]],
  ['patterns_20complete_12',['✅ Patterns (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1248',1,'']]],
  ['patterns_20optional_20but_20recommended_13',['Step 5: Migrate to Patterns (Optional but Recommended)',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md818',1,'']]],
  ['patterns_20tt_14',['Patterns (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1117',1,'']]],
  ['patterns_20tt_20include_20kcenon_20messaging_20patterns_20tt_15',['Patterns (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1117',1,'']]],
  ['patterns_5fapi_2emd_16',['PATTERNS_API.md',['../d1/dff/PATTERNS__API_8md.html',1,'']]],
  ['per_20component_20memory_20overhead_17',['Per-Component Memory Overhead',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md414',1,'']]],
  ['perf_18',['perf',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md917',1,'Performance Profiling with perf'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md755',1,'Using perf']]],
  ['performance_19',['performance',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1275',1,'📊 Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md995',1,'Component Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md411',1,'Concurrent Request Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md999',1,'Container System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1005',1,'Database System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md994',1,'Memory Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md395',1,'Message Builder Performance'],['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md974',1,'Message Bus Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1002',1,'Network System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md992',1,'Overall System Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md402',1,'Pattern Matching Performance'],['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md975',1,'Pattern Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md405',1,'Pub/Sub Performance'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md845',1,'Q: What about performance?'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1006',1,'Query Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md399',1,'Queue Contention Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md397',1,'Queue Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md409',1,'Request/Reply Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1000',1,'Serialization Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md996',1,'Thread System Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md401',1,'Topic Router Performance']]],
  ['performance_20baseline_20',['Performance Baseline',['../d9/df1/md_docs_2performance_2BASELINE.html',1,'']]],
  ['performance_20benchmarks_21',['Messaging System Performance Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html',1,'']]],
  ['performance_20comparison_22',['Performance Comparison',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md181',1,'']]],
  ['performance_20considerations_23',['Performance Considerations',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md129',1,'']]],
  ['performance_20degradation_24',['Issue: Build performance degradation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md840',1,'']]],
  ['performance_20degradation_20with_20many_20topics_25',['Issue 5: Performance Degradation with Many Topics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md937',1,'']]],
  ['performance_20features_26',['Key Performance Features',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md989',1,'']]],
  ['performance_20guide_27',['Performance Guide',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html',1,'']]],
  ['performance_20issues_28',['performance issues',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md716',1,'Performance Issues'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md775',1,'Performance Issues'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1024',1,'Troubleshooting Performance Issues']]],
  ['performance_20metrics_29',['performance metrics',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md391',1,'Core Performance Metrics'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md392',1,'Reference Performance Metrics']]],
  ['performance_20monitoring_30',['performance monitoring',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md434',1,'Continuous Performance Monitoring'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1017',1,'Performance Monitoring']]],
  ['performance_20monitoring_20dashboard_31',['2. Performance Monitoring Dashboard',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1029',1,'']]],
  ['performance_20optimization_32',['performance optimization',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md919',1,'Performance Optimization'],['../d2/d64/md_docs_2architecture.html#autotoc_md336',1,'Performance Optimization'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md149',1,'Performance Optimization'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html',1,'Windows CI Performance Optimization']]],
  ['performance_20overview_33',['Performance Overview',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md987',1,'']]],
  ['performance_20problems_34',['1. Common Performance Problems',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1025',1,'']]],
  ['performance_20profiling_35',['performance profiling',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1019',1,'2. Performance Profiling'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md754',1,'Performance Profiling']]],
  ['performance_20profiling_20with_20perf_36',['Performance Profiling with perf',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md917',1,'']]],
  ['performance_20questions_37',['performance questions',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md893',1,'Performance Questions'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md792',1,'Performance Questions']]],
  ['performance_20testing_38',['Performance Testing',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md748',1,'']]],
  ['performance_20tests_39',['Performance Tests',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1047',1,'']]],
  ['performance_20tuning_40',['Performance Tuning',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md667',1,'']]],
  ['performance_20tuning_20recommendations_41',['Performance Tuning Recommendations',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md426',1,'']]],
  ['performance_2emd_42',['PERFORMANCE.md',['../d8/d74/PERFORMANCE_8md.html',1,'']]],
  ['periodic_20task_20scheduler_43',['6.1 Periodic Task Scheduler',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1211',1,'']]],
  ['phase_201_3a_20task_20core_20기반_20확장_44',['Phase 1: Task Core (기반 확장)',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1191',1,'']]],
  ['phase_202_3a_20worker_20system_45',['Phase 2: Worker System',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1195',1,'']]],
  ['phase_203_3a_20task_20queue_20확장_46',['Phase 3: Task Queue (확장)',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1199',1,'']]],
  ['phase_204_3a_20result_20backend_47',['Phase 4: Result Backend',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1202',1,'']]],
  ['phase_205_3a_20task_20client_20producer_48',['Phase 5: Task Client (Producer)',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1207',1,'']]],
  ['phase_206_3a_20scheduler_49',['Phase 6: Scheduler',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1210',1,'']]],
  ['phase_207_3a_20monitoring_20management_50',['Phase 7: Monitoring &amp; Management',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1213',1,'']]],
  ['phase_208_3a_20integration_51',['Phase 8: Integration',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1216',1,'']]],
  ['pipeline_52',['pipeline',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1037',1,'CI/CD Pipeline'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md833',1,'Example 4: Message Pipeline'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1267',1,'Message Pipeline'],['../da/db6/md_docs_2FEATURES.html#autotoc_md527',1,'Message Pipeline'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md587',1,'Message Pipeline'],['../d2/d64/md_docs_2architecture.html#autotoc_md327',1,'Message Processing Pipeline'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md140',1,'Message Processing Pipeline']]],
  ['pipeline_20pattern_53',['pipeline pattern',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md87',1,'Message Pipeline Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md122',1,'Message Pipeline Pattern']]],
  ['pipeline_5fbuilder_20tt_54',['Class: &lt;tt&gt;pipeline_builder&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md102',1,'']]],
  ['pipeline_5fstage_20tt_55',['Struct: &lt;tt&gt;pipeline_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md91',1,'']]],
  ['pipeline_5fstages_20tt_56',['Namespace: &lt;tt&gt;pipeline_stages&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md111',1,'']]],
  ['pipelining_57',['Batching and Pipelining',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1016',1,'']]],
  ['plan_58',['plan',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md701',1,'Disaster Recovery Plan'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html',1,'Distributed Task Queue System - Improvement Plan']]],
  ['planned_20additions_59',['Planned Additions',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1142',1,'']]],
  ['planned_20enhancements_60',['planned enhancements',['../d2/d64/md_docs_2architecture.html#autotoc_md357',1,'Planned Enhancements'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md170',1,'Planned Enhancements']]],
  ['planned_20improvements_61',['Planned Improvements',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1074',1,'']]],
  ['planning_62',['planning',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1162',1,'Development &amp; Planning'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md199',1,'Priority 4 (Long-Term Planning)']]],
  ['platform_63',['Reference Platform',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md978',1,'']]],
  ['platform_20specific_20notes_64',['Platform-Specific Notes',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md622',1,'']]],
  ['platform_20specific_20setup_65',['2. Platform-Specific Setup',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md863',1,'']]],
  ['platform_20support_66',['🌐 Platform Support',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1291',1,'']]],
  ['platforms_20are_20supported_67',['Q: Which platforms are supported?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md781',1,'']]],
  ['pod_20autoscaler_68',['Horizontal Pod Autoscaler',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md665',1,'']]],
  ['points_69',['points',['../d2/d64/md_docs_2architecture.html#autotoc_md333',1,'Integration Points'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md146',1,'Integration Points']]],
  ['pool_70',['2.2 Worker Pool',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1197',1,'']]],
  ['pool_20configuration_71',['Thread Pool Configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md672',1,'']]],
  ['pool_20exhaustion_72',['Issue 3: Database Connection Pool Exhaustion',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md935',1,'']]],
  ['pool_20impact_73',['Connection Pool Impact',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1007',1,'']]],
  ['pool_20management_74',['Pool Management',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md267',1,'']]],
  ['pool_20pattern_75',['pool pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md20',1,'15. Thread Pool Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md6',1,'4. Object Pool Pattern']]],
  ['pool_20tuning_76',['Connection Pool Tuning',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md677',1,'']]],
  ['pooling_77',['Object Pooling',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1010',1,'']]],
  ['post_20deployment_78',['Post-Deployment',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1079',1,'']]],
  ['postgresql_20configuration_79',['PostgreSQL Configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md676',1,'']]],
  ['pr_2030_20success_80',['Target State (PR #30 - Success)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md176',1,'']]],
  ['pr_2031_20before_20fix_81',['Initial State (PR #31 - Before Fix)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md175',1,'']]],
  ['pr_20title_20format_82',['PR Title Format',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md510',1,'']]],
  ['practices_83',['practices',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1070',1,'Best Practices'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md118',1,'Best Practices'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md739',1,'Best Practices'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md768',1,'Security Best Practices']]],
  ['pre_20deployment_84',['Pre-Deployment',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1077',1,'']]],
  ['prebuilt_20dependency_20binaries_85',['3. Prebuilt Dependency Binaries',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md194',1,'']]],
  ['prerequisites_86',['prerequisites',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md857',1,'Prerequisites'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md430',1,'Prerequisites'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md500',1,'Prerequisites'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1258',1,'Prerequisites'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md722',1,'Prerequisites']]],
  ['principles_87',['principles',['../d2/d64/md_docs_2architecture.html#autotoc_md319',1,'Architectural Principles'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md132',1,'Architectural Principles'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1136',1,'Code Organization Principles']]],
  ['priority_88',['Implementation Priority',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md195',1,'']]],
  ['priority_201_20implemented_20✅_89',['Priority 1 (Implemented) ✅',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md196',1,'']]],
  ['priority_202_20recommended_20next_20sprint_90',['Priority 2 (Recommended - Next Sprint)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md197',1,'']]],
  ['priority_203_20future_20consideration_91',['Priority 3 (Future Consideration)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md198',1,'']]],
  ['priority_204_20long_20term_20planning_92',['Priority 4 (Long-Term Planning)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md199',1,'']]],
  ['priority_20levels_93',['Priority Levels',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md268',1,'']]],
  ['priority_20queue_20operations_94',['Priority Queue Operations',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md398',1,'']]],
  ['priority_20task_20queue_95',['3.1 Priority Task Queue',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1200',1,'']]],
  ['problem_20analysis_96',['Problem Analysis',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md174',1,'']]],
  ['problem_3a_20connection_20drops_97',['Problem: Connection Drops',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md951',1,'']]],
  ['problem_3a_20database_20bottleneck_98',['Problem: Database Bottleneck',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md953',1,'']]],
  ['problem_3a_20high_20memory_20usage_99',['Problem: High Memory Usage',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md952',1,'']]],
  ['problem_3a_20service_20won_20t_20start_100',['Problem: Service Won&apos;t Start',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md949',1,'']]],
  ['problem_3a_20slow_20message_20processing_101',['Problem: Slow Message Processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md950',1,'']]],
  ['problems_102',['problems',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1025',1,'1. Common Performance Problems'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md948',1,'Common Problems']]],
  ['procedures_103',['Recovery Procedures',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md699',1,'']]],
  ['process_104',['process',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md901',1,'Attach to Running Process'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md509',1,'Pull Request Process']]],
  ['process_20tt_105',['&lt;tt&gt;process&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md97',1,'']]],
  ['processing_106',['processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md936',1,'Issue 4: Deadlock in Message Processing'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md950',1,'Problem: Slow Message Processing']]],
  ['processing_20pipeline_107',['processing pipeline',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md140',1,'Message Processing Pipeline'],['../d2/d64/md_docs_2architecture.html#autotoc_md327',1,'Message Processing Pipeline']]],
  ['producer_108',['Phase 5: Task Client (Producer)',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1207',1,'']]],
  ['producer_20consumer_20pattern_109',['14. Producer-Consumer Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md19',1,'']]],
  ['production_20checklist_110',['Production Checklist',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1076',1,'']]],
  ['production_20deployment_111',['Production Deployment',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1054',1,'']]],
  ['production_20features_112',['Production Features',['../da/db6/md_docs_2FEATURES.html#autotoc_md561',1,'']]],
  ['production_20find_5fpackage_20mode_113',['For Production (find_package Mode)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md612',1,'']]],
  ['production_20quality_114',['Messaging System Production Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html',1,'']]],
  ['production_20requirements_115',['Production Requirements',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md634',1,'']]],
  ['production_5fquality_2emd_116',['PRODUCTION_QUALITY.md',['../db/d40/PRODUCTION__QUALITY_8md.html',1,'']]],
  ['production_5fquality_5fko_2emd_117',['PRODUCTION_QUALITY_KO.md',['../dc/d0d/PRODUCTION__QUALITY__KO_8md.html',1,'']]],
  ['profiling_118',['profiling',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1019',1,'2. Performance Profiling'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md754',1,'Performance Profiling'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md915',1,'Tracing and Profiling']]],
  ['profiling_20with_20perf_119',['Performance Profiling with perf',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md917',1,'']]],
  ['programmatic_120',['Programmatic',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md899',1,'']]],
  ['project_121',['2. Build the Project',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md724',1,'']]],
  ['project_20structure_122',['project structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'Messaging System Project Structure'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md732',1,'Project Structure'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md876',1,'Project Structure']]],
  ['project_5fstructure_2emd_123',['PROJECT_STRUCTURE.md',['../d8/d2e/PROJECT__STRUCTURE_8md.html',1,'']]],
  ['project_5fstructure_5fko_2emd_124',['PROJECT_STRUCTURE_KO.md',['../d0/d38/PROJECT__STRUCTURE__KO_8md.html',1,'']]],
  ['prometheus_20configuration_125',['Prometheus Configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md680',1,'']]],
  ['prometheus_20integration_126',['Prometheus Integration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md679',1,'']]],
  ['protocol_20overhead_127',['Protocol Overhead',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1004',1,'']]],
  ['proxy_20pattern_128',['7. Proxy Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md10',1,'']]],
  ['pub_20sub_129',['pub sub',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md418',1,'Latency Distribution (Pub/Sub)'],['../d5/ddb/md_docs_2BENCHMARKS__KO.html#autotoc_md455',1,'Pub/Sub'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md584',1,'Pub/Sub'],['../d4/d54/md_docs_2API__REFERENCE__KO.html#autotoc_md306',1,'Pub/Sub']]],
  ['pub_20sub_20migration_130',['Example 1: Simple Pub/Sub Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md830',1,'']]],
  ['pub_20sub_20pattern_131',['pub sub pattern',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1264',1,'Pub/Sub Pattern'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md819',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md28',1,'Pub/Sub Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md524',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md119',1,'Pub/Sub Pattern']]],
  ['pub_20sub_20performance_132',['Pub/Sub Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md405',1,'']]],
  ['publish_20subscribe_133',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md848',1,'']]],
  ['publish_20tt_134',['&lt;tt&gt;publish&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md33',1,'']]],
  ['publish_5fevent_20tt_135',['&lt;tt&gt;publish_event&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md71',1,'']]],
  ['publisher_20subscriber_20scaling_136',['Publisher/Subscriber Scaling',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md423',1,'']]],
  ['publisher_20tt_137',['Class: &lt;tt&gt;publisher&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md30',1,'']]],
  ['publishing_138',['Publishing',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md249',1,'']]],
  ['pull_20official_20image_139',['Pull Official Image',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md648',1,'']]],
  ['pull_20request_20process_140',['Pull Request Process',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md509',1,'']]]
];
