var searchData=
[
  ['packet_5fmode_0',['packet_mode',['../namespacenetwork__module.html#aee4e9adbf9f803ff81009170a8ae65b7a8d01e9bd18390ad98ebf15da69a53420',1,'network_module']]],
  ['parallel_5fserialize_1',['parallel_serialize',['../classcontainer__module_1_1simd_1_1simd__processor.html#a3715e29868c50888a5b467a29b1b6cb4',1,'container_module::simd::simd_processor']]],
  ['paranoid_2',['paranoid',['../namespacethread__module.html#a8e2e4ef65ebb4f41dfd38f28ae7a0899a9e7aa5c51cfe1d6922cd9a0c03387901',1,'thread_module']]],
  ['parent_3',['parent',['../classcontainer__module_1_1value.html#a99fb4d519e7e9a7cd47744e2bd75351f',1,'container_module::value']]],
  ['parent_5f_4',['parent_',['../classcontainer__module_1_1value.html#a9b1f6d403839bcec8ef5c15110f4480d',1,'container_module::value']]],
  ['parse_5',['parse',['../classutility__module_1_1enum__formatter.html#a86421b021ba81b03d2e0dc621ca8dfb1',1,'utility_module::enum_formatter']]],
  ['parsed_5fdata_5f_6',['parsed_data_',['../classcontainer__module_1_1value__container.html#a105a7df7f68e24b58f9be85dfd1496d9',1,'container_module::value_container']]],
  ['parsing_7',['parsing',['../classcontainer__module_1_1value__container.html#ac67f821c2e812722fd46526063911f4a',1,'container_module::value_container']]],
  ['patterns_20implementation_20strong_8',['🔄 &lt;strong&gt;Design Patterns Implementation&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md218',1,'']]],
  ['pending_9',['pending',['../namespacethread__module_1_1jobs.html#ab7e88d20a4feef6010627676c6cc6a93a7c6c2e5d48ab37a007cbf70d3ea25fa4',1,'thread_module::jobs']]],
  ['per_5ftype_5fdequeues_10',['per_type_dequeues',['../structtyped__thread__pool__module_1_1typed__queue__statistics__t.html#af4145c3b05032644e771ee2a4a1ba7da',1,'typed_thread_pool_module::typed_queue_statistics_t']]],
  ['per_5ftype_5fenqueues_11',['per_type_enqueues',['../structtyped__thread__pool__module_1_1typed__queue__statistics__t.html#a9c2330947027c4249fd000eb760ddafe',1,'typed_thread_pool_module::typed_queue_statistics_t']]],
  ['per_5ftype_5fstats_12',['per_type_stats',['../structtyped__thread__pool__module_1_1typed__lockfree__job__queue__t_1_1typed__queue__statistics.html#ad7108bfdbfaf93883a516226584ecabf',1,'typed_thread_pool_module::typed_lockfree_job_queue_t::typed_queue_statistics']]],
  ['performance_20adaptive_20logging_13',['High-Performance Adaptive Logging',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md254',1,'']]],
  ['performance_20benchmarks_20strong_14',['📊 &lt;strong&gt;Performance Benchmarks&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md212',1,'']]],
  ['performance_20characteristics_15',['performance characteristics',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md25',1,'📊 Performance Characteristics'],['..//home/runner/work/messaging_system/messaging_system/database/README.md#autotoc_md83',1,'Performance Characteristics'],['..//home/runner/work/messaging_system/messaging_system/container/README.md#autotoc_md56',1,'Performance Characteristics'],['..//home/runner/work/messaging_system/messaging_system/network/README.md#autotoc_md132',1,'Performance Characteristics'],['../index.html#performance',1,'Performance Characteristics']]],
  ['performance_20concurrency_20strong_16',['&lt;strong&gt;Performance &amp; Concurrency&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md257',1,'']]],
  ['performance_20considerations_17',['performance considerations',['../classtyped__thread__pool__module_1_1typed__thread__pool__t.html#autotoc_md177',1,'Performance Considerations'],['../classthread__pool__module_1_1thread__pool.html#autotoc_md169',1,'Performance Considerations']]],
  ['performance_20data_18',['Detailed Performance Data',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md215',1,'']]],
  ['performance_20example_19',['Adaptive High-Performance Example',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md249',1,'']]],
  ['performance_20excellence_20strong_20',['🚀 &lt;strong&gt;Performance Excellence&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md205',1,'']]],
  ['performance_20features_21',['Performance Features',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md27',1,'']]],
  ['performance_20metrics_20latest_20benchmarks_202025_2007_2009_22',['Core Performance Metrics (Latest Benchmarks - 2025-07-09)',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md213',1,'']]],
  ['performance_20monitoring_23',['Real-time Performance Monitoring',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md255',1,'']]],
  ['performance_20optimizations_24',['Performance Optimizations',['..//home/runner/work/messaging_system/messaging_system/container/README.md#autotoc_md46',1,'']]],
  ['performance_5fmetrics_25',['performance_metrics',['../structthread__module_1_1adaptive__job__queue_1_1performance__metrics.html',1,'thread_module::adaptive_job_queue::performance_metrics'],['../structtyped__thread__pool__module_1_1adaptive__typed__job__queue__t_1_1performance__metrics.html',1,'typed_thread_pool_module::adaptive_typed_job_queue_t&lt; job_type &gt;::performance_metrics']]],
  ['performance_5fstats_26',['performance_stats',['../structthread__module_1_1lockfree_1_1performance__stats.html',1,'thread_module::lockfree']]],
  ['pin_5fto_5fcpu_27',['pin_to_cpu',['../structthread__pool__module_1_1worker__policy.html#a263aa1c8396943d5a0701d884ded3ee3',1,'thread_pool_module::worker_policy']]],
  ['pipeline_28',['pipeline',['../structnetwork__module_1_1pipeline.html',1,'network_module']]],
  ['pipeline_20processing_29',['Advanced Pipeline Processing',['..//home/runner/work/messaging_system/messaging_system/network/README.md#autotoc_md123',1,'']]],
  ['pipeline_2ecpp_30',['pipeline.cpp',['../pipeline_8cpp.html',1,'']]],
  ['pipeline_2eh_31',['pipeline.h',['../pipeline_8h.html',1,'']]],
  ['pipeline_5f_32',['pipeline_',['../classnetwork__module_1_1messaging__session.html#a94d67c2dc85b2701dc13abfee58a2c1f',1,'network_module::messaging_session::pipeline_'],['../classnetwork__module_1_1messaging__client.html#a9e44de955ca094e87a5b31fdccf98852',1,'network_module::messaging_client::pipeline_']]],
  ['platform_20compatibility_20strong_33',['🌐 &lt;strong&gt;Cross-Platform Compatibility&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md208',1,'']]],
  ['pointers_5fper_5fthread_5f_34',['pointers_per_thread_',['../classthread__module_1_1hazard__pointer__manager.html#a0ec6262ddd348f4a8d6dd19cefa83fea',1,'thread_module::hazard_pointer_manager']]],
  ['pool_35',['Standard Thread Pool',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md233',1,'']]],
  ['pool_20files_36',['Thread Pool Files',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md223',1,'']]],
  ['pool_20files_20adaptive_20🆕_37',['Typed Thread Pool Files (Adaptive) 🆕',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md225',1,'']]],
  ['pool_20files_20mutex_20based_38',['Typed Thread Pool Files (Mutex-based)',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md224',1,'']]],
  ['pool_20fundamentals_20strong_39',['&lt;strong&gt;Thread Pool Fundamentals&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md258',1,'']]],
  ['pool_20high_20contention_40',['Adaptive Thread Pool (High Contention)',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md252',1,'']]],
  ['pool_20implementation_41',['Typed Thread Pool Implementation',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md238',1,'']]],
  ['pool_20low_20contention_42',['Standard Thread Pool (Low Contention)',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md251',1,'']]],
  ['pool_20management_43',['Connection Pool Management',['..//home/runner/work/messaging_system/messaging_system/database/README.md#autotoc_md76',1,'']]],
  ['pool_20system_20thread_5fpool_5fmodule_20a_44',['3. &lt;a href=&quot;https://github.com/kcenon/thread_system/tree/main/sources/thread_pool&quot; &gt;Thread Pool System (thread_pool_module)&lt;/a&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md232',1,'']]],
  ['pool_20system_20typed_5fthread_5fpool_5fmodule_20a_45',['5. &lt;a href=&quot;https://github.com/kcenon/thread_system/tree/main/sources/typed_thread_pool&quot; &gt;Typed Thread Pool System (typed_thread_pool_module)&lt;/a&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md237',1,'']]],
  ['pool_5fbuilder_2eh_46',['pool_builder.h',['../pool__builder_8h.html',1,'']]],
  ['pool_5ffuture_47',['pool_future',['../classthread__pool__module_1_1pool__future.html#af6de2ed770c8a01c7ba2eb864b612eab',1,'thread_pool_module::pool_future::pool_future()'],['../classthread__pool__module_1_1pool__future.html',1,'thread_pool_module::pool_future&lt; T &gt;']]],
  ['pool_5finstance_5fid_48',['pool_instance_id',['../structmonitoring__interface_1_1thread__pool__metrics.html#a7a59a41e22694c2a9b0dd051a7d62b73',1,'monitoring_interface::thread_pool_metrics']]],
  ['pool_5finstance_5fid_5f_49',['pool_instance_id_',['../classthread__pool__module_1_1thread__pool.html#ad43bd4318cfacc685ea5f3ca8b7ebff9',1,'thread_pool_module::thread_pool']]],
  ['pool_5fname_50',['pool_name',['../structmonitoring__interface_1_1thread__pool__metrics.html#a90b9b324a58a82ec57c16c02e40dd23a',1,'monitoring_interface::thread_pool_metrics']]],
  ['pool_5fpromise_51',['pool_promise',['../classthread__pool__module_1_1pool__promise.html#a816fb460d0ff23ffca2a3f860ece3d45',1,'thread_pool_module::pool_promise::pool_promise()'],['../classthread__pool__module_1_1pool__promise.html',1,'thread_pool_module::pool_promise&lt; T &gt;']]],
  ['pool_5fpromise_3c_20void_20_3e_52',['pool_promise&lt; void &gt;',['../classthread__pool__module_1_1pool__promise_3_01void_01_4.html',1,'thread_pool_module']]],
  ['pool_5ftraits_2eh_53',['pool_traits.h',['../pool__traits_8h.html',1,'']]],
  ['poolchunk_54',['poolchunk',['../structthread__module_1_1node__pool_1_1_pool_chunk.html#a5138c72307c76d76caa54f3463ce5eb3',1,'thread_module::node_pool::PoolChunk::PoolChunk()'],['../structthread__module_1_1node__pool_1_1_pool_chunk.html',1,'thread_module::node_pool&lt; T &gt;::PoolChunk']]],
  ['pop_5ffrom_5ffree_5flist_55',['pop_from_free_list',['../classthread__module_1_1node__pool.html#a7d6d09fada36729b9d837af09aef1359',1,'thread_module::node_pool']]],
  ['postgres_56',['postgres',['../namespacedatabase.html#ad983a92aeb2e850207432d806579489bae8a48653851e28c69d0506508fb27fc5',1,'database']]],
  ['postgres_5fmanager_57',['postgres_manager',['../classdatabase_1_1postgres__manager.html',1,'database::postgres_manager'],['../classdatabase_1_1postgres__manager.html#a2fb6a01c21ad878bfdb0c87815ecbf09',1,'database::postgres_manager::postgres_manager()']]],
  ['postgres_5fmanager_20class_58',['postgres_manager Class',['..//home/runner/work/messaging_system/messaging_system/database/README.md#autotoc_md81',1,'']]],
  ['postgres_5fmanager_2ecpp_59',['postgres_manager.cpp',['../postgres__manager_8cpp.html',1,'']]],
  ['postgres_5fmanager_2eh_60',['postgres_manager.h',['../postgres__manager_8h.html',1,'']]],
  ['postgresql_2014_20localhost_61',['Benchmarks (PostgreSQL 14, localhost)',['..//home/runner/work/messaging_system/messaging_system/database/README.md#autotoc_md84',1,'']]],
  ['power_5fefficient_62',['power_efficient',['../structthread__pool__module_1_1worker__policy.html#a6326704c791468e1cbed2d477907ceef',1,'thread_pool_module::worker_policy']]],
  ['practices_63',['Best Practices',['..//home/runner/work/messaging_system/messaging_system/container/README.md#autotoc_md55',1,'']]],
  ['preferred_5fcpu_64',['preferred_cpu',['../structthread__pool__module_1_1worker__policy.html#a498977c7ffe9b6ea17e9d6536f6e77e4',1,'thread_pool_module::worker_policy']]],
  ['prepare_5fdata_5fasync_65',['prepare_data_async',['../namespacenetwork__module.html#acca7c2a6f3f16ab29babe18b6b70433c',1,'network_module']]],
  ['prerequisites_66',['Prerequisites',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md261',1,'']]],
  ['prevention_67',['SQL Injection Prevention',['..//home/runner/work/messaging_system/messaging_system/database/README.md#autotoc_md88',1,'']]],
  ['previous_5fhandlers_5f_68',['previous_handlers_',['../classthread__module_1_1crash__handler.html#a8c01a295ee5b976b77c2e45e082b2e8d',1,'thread_module::crash_handler']]],
  ['principles_69',['Design Principles',['../classthread__pool__module_1_1thread__pool.html#autotoc_md167',1,'']]],
  ['priority_70',['priority',['../namespacethread__pool__module.html#add8b8e5f5fd0f12965fb6fdda6b22355ab988295c268025b49dfb3df26171ddc3',1,'thread_pool_module::priority'],['../structthread__module_1_1crash__handler_1_1callback__entry.html#a4f2c48653c9af3bff76d66c07bf2c0c3',1,'thread_module::crash_handler::callback_entry::priority'],['../classthread__module_1_1jobs_1_1job__interface.html#ab1ede8912e6405da3c8d6961d76287bd',1,'thread_module::jobs::job_interface::priority()'],['../classtyped__thread__pool__module_1_1typed__job__t.html#a88acbe2410c3ccef635b0e4d686a8914',1,'typed_thread_pool_module::typed_job_t::priority() const -&gt; job_type']]],
  ['priority_5f_71',['priority_',['../classtyped__thread__pool__module_1_1typed__job__t.html#a048fce659e535d0f0cd4e462ec5c62dd',1,'typed_thread_pool_module::typed_job_t']]],
  ['priority_5fcomparator_72',['priority_comparator',['../structtyped__thread__pool__module_1_1detail_1_1priority__comparator.html#ac79224f2591a6eca5fa481f7144ee6ec',1,'typed_thread_pool_module::detail::priority_comparator::priority_comparator()'],['../structtyped__thread__pool__module_1_1detail_1_1priority__comparator.html',1,'typed_thread_pool_module::detail::priority_comparator&lt; T, Comparator &gt;']]],
  ['priority_5fmutex_5f_73',['priority_mutex_',['../classtyped__thread__pool__module_1_1typed__lockfree__job__queue__t.html#aa19869034f4a26966f06ddad58981680',1,'typed_thread_pool_module::typed_lockfree_job_queue_t']]],
  ['priority_5forder_5f_74',['priority_order_',['../classtyped__thread__pool__module_1_1typed__lockfree__job__queue__t.html#a9c27a81bea8cf265f911925c51cb37ad',1,'typed_thread_pool_module::typed_lockfree_job_queue_t']]],
  ['processing_75',['Advanced Pipeline Processing',['..//home/runner/work/messaging_system/messaging_system/network/README.md#autotoc_md123',1,'']]],
  ['production_20grade_20reliability_20strong_76',['🛡️ &lt;strong&gt;Production-Grade Reliability&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md206',1,'']]],
  ['production_20monitoring_20diagnostics_20strong_77',['📊 &lt;strong&gt;Production Monitoring &amp; Diagnostics&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md244',1,'']]],
  ['productivity_20strong_78',['🔧 &lt;strong&gt;Developer Productivity&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md207',1,'']]],
  ['project_79',['project',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md12',1,'3. Build the Project'],['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md196',1,'Thread System Project']]],
  ['project_20a_80',['project a',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md231',1,'2. &lt;a href=&quot;https://github.com/kcenon/logger&quot; &gt;Logging System (Separate Project)&lt;/a&gt;'],['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md236',1,'4. &lt;a href=&quot;https://github.com/kcenon/monitoring&quot; &gt;Real-time Monitoring System (Separate Project)&lt;/a&gt;']]],
  ['project_20ecosystem_20inter_20dependencies_81',['🔗 Project Ecosystem &amp; Inter-Dependencies',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md198',1,'']]],
  ['project_20overview_82',['Project Overview',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md197',1,'']]],
  ['project_20purpose_20mission_83',['Project Purpose &amp; Mission',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md203',1,'']]],
  ['project_20structure_84',['Project Structure',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md219',1,'']]],
  ['promise_5f_85',['promise_',['../classthread__pool__module_1_1pool__promise.html#adb8ba4100cf069d773192ac21bc0811c',1,'thread_pool_module::pool_promise::promise_'],['../classthread__pool__module_1_1pool__promise_3_01void_01_4.html#af8c37d045afbf08c314e45e280b01f2b',1,'thread_pool_module::pool_promise&lt; void &gt;::promise_']]],
  ['protect_86',['protect',['../classthread__module_1_1hazard__pointer__manager_1_1hazard__pointer.html#a1b9cd40dd0159aaafdaee7c681dffef0',1,'thread_module::hazard_pointer_manager::hazard_pointer']]],
  ['protocol_87',['Message Protocol',['..//home/runner/work/messaging_system/messaging_system/network/README.md#autotoc_md116',1,'']]],
  ['ptr_88',['ptr',['../structthread__module_1_1hazard__pointer__manager_1_1_retired_node.html#ab22e578081a0f6c8d2af150c34584213',1,'thread_module::hazard_pointer_manager::RetiredNode']]],
  ['purpose_20mission_89',['Project Purpose &amp; Mission',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md203',1,'']]],
  ['purpose_20strong_90',['📖 &lt;strong&gt;Key Files and Their Purpose&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md221',1,'']]],
  ['push_5fto_5ffree_5flist_91',['push_to_free_list',['../classthread__module_1_1node__pool.html#a5114460242d5680d18f19bf16285d169',1,'thread_module::node_pool']]],
  ['python_20integration_92',['Python Integration',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md24',1,'']]]
];
