var searchData=
[
  ['p_20not_20supported_20macos_0',['Issue 3: grep -P Not Supported (macOS)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md193',1,'']]],
  ['package_20managers_1',['Using Package Managers',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md231',1,'']]],
  ['parallel_20execution_20✅_2',['2. CTest Parallel Execution ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md912',1,'']]],
  ['parallelization_20✅_3',['3. Build Parallelization ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md913',1,'']]],
  ['parameters_4',['Linux Kernel Parameters',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md256',1,'']]],
  ['paths_5',['Update Include Paths',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md496',1,'']]],
  ['pattern_6',['pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md310',1,'1. Singleton Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md321',1,'10. Strategy Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md322',1,'11. Chain of Responsibility Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md323',1,'12. Command Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md324',1,'13. Template Method Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md326',1,'14. Producer-Consumer Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md327',1,'15. Thread Pool Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md329',1,'16. Microkernel Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md311',1,'2. Factory Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md312',1,'3. Builder Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md313',1,'4. Object Pool Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md315',1,'5. Adapter Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md316',1,'6. Decorator Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md317',1,'7. Proxy Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md318',1,'8. Composite Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md320',1,'9. Observer Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md577',1,'Event Streaming Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md633',1,'Event Streaming Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md634',1,'Message Pipeline Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md599',1,'Message Pipeline Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md631',1,'Pub/Sub Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md399',1,'Pub/Sub Pattern'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md501',1,'Pub/Sub Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md540',1,'Pub/Sub Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md960',1,'Pub/Sub Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md632',1,'Request-Reply Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md557',1,'Request-Reply Pattern'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md502',1,'Request-Reply Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md400',1,'Request/Reply Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md961',1,'Request/Reply Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md428',1,'Result&lt;T&gt; Pattern']]],
  ['pattern_20matching_20performance_7',['Pattern Matching Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md148',1,'']]],
  ['patterns_8',['patterns',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md328',1,'Architectural Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md319',1,'Behavioral Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md325',1,'Concurrency Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md309',1,'Creational Patterns'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md764',1,'Include Patterns'],['../da/db6/md_docs_2FEATURES.html#autotoc_md398',1,'Messaging Patterns'],['../d2/d64/md_docs_2architecture.html#autotoc_md102',1,'Scalability Patterns'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md811',1,'Scalability Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md314',1,'Structural Patterns'],['../da/db6/md_docs_2FEATURES.html#autotoc_md416',1,'Wildcard Patterns']]],
  ['patterns_20and_20architectural_20decisions_9',['Design Patterns and Architectural Decisions',['../d5/dca/md_docs_2DESIGN__PATTERNS.html',1,'']]],
  ['patterns_20api_20reference_10',['Messaging Patterns API Reference',['../dc/d3e/md_docs_2PATTERNS__API.html',1,'']]],
  ['patterns_20complete_11',['✅ Patterns (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md945',1,'']]],
  ['patterns_20optional_20but_20recommended_12',['Step 5: Migrate to Patterns (Optional but Recommended)',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md500',1,'']]],
  ['patterns_20tt_13',['Patterns (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md754',1,'']]],
  ['patterns_20tt_20include_20kcenon_20messaging_20patterns_20tt_14',['Patterns (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md754',1,'']]],
  ['patterns_5fapi_2emd_15',['PATTERNS_API.md',['../d1/dff/PATTERNS__API_8md.html',1,'']]],
  ['per_20component_20memory_20overhead_16',['Per-Component Memory Overhead',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md160',1,'']]],
  ['perf_17',['perf',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md868',1,'Performance Profiling with perf'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md367',1,'Using perf']]],
  ['performance_18',['performance',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md970',1,'📊 Performance'],['../df/d94/md_docs_2performance.html#autotoc_md652',1,'Component Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md157',1,'Concurrent Request Performance'],['../df/d94/md_docs_2performance.html#autotoc_md656',1,'Container System Performance'],['../df/d94/md_docs_2performance.html#autotoc_md662',1,'Database System Performance'],['../df/d94/md_docs_2performance.html#autotoc_md651',1,'Memory Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md141',1,'Message Builder Performance'],['../df/d94/md_docs_2performance.html#autotoc_md659',1,'Network System Performance'],['../df/d94/md_docs_2performance.html#autotoc_md649',1,'Overall System Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md148',1,'Pattern Matching Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md151',1,'Pub/Sub Performance'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md527',1,'Q: What about performance?'],['../df/d94/md_docs_2performance.html#autotoc_md663',1,'Query Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md145',1,'Queue Contention Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md143',1,'Queue Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md155',1,'Request/Reply Performance'],['../df/d94/md_docs_2performance.html#autotoc_md657',1,'Serialization Performance'],['../df/d94/md_docs_2performance.html#autotoc_md653',1,'Thread System Performance'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md147',1,'Topic Router Performance']]],
  ['performance_20benchmarks_19',['Messaging System Performance Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html',1,'']]],
  ['performance_20comparison_20',['Performance Comparison',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md914',1,'']]],
  ['performance_20considerations_21',['Performance Considerations',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md641',1,'']]],
  ['performance_20degradation_22',['Issue: Build performance degradation',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md522',1,'']]],
  ['performance_20degradation_20with_20many_20topics_23',['Issue 5: Performance Degradation with Many Topics',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md888',1,'']]],
  ['performance_20features_24',['Key Performance Features',['../df/d94/md_docs_2performance.html#autotoc_md646',1,'']]],
  ['performance_20guide_25',['Performance Guide',['../df/d94/md_docs_2performance.html',1,'']]],
  ['performance_20issues_26',['performance issues',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md387',1,'Performance Issues'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md303',1,'Performance Issues'],['../df/d94/md_docs_2performance.html#autotoc_md681',1,'Troubleshooting Performance Issues']]],
  ['performance_20metrics_27',['performance metrics',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md137',1,'Core Performance Metrics'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md138',1,'Reference Performance Metrics']]],
  ['performance_20monitoring_28',['performance monitoring',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md180',1,'Continuous Performance Monitoring'],['../df/d94/md_docs_2performance.html#autotoc_md674',1,'Performance Monitoring']]],
  ['performance_20monitoring_20dashboard_29',['2. Performance Monitoring Dashboard',['../df/d94/md_docs_2performance.html#autotoc_md686',1,'']]],
  ['performance_20optimization_30',['performance optimization',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md817',1,'Performance Optimization'],['../d2/d64/md_docs_2architecture.html#autotoc_md108',1,'Performance Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md870',1,'Performance Optimization'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html',1,'Windows CI Performance Optimization']]],
  ['performance_20overview_31',['Performance Overview',['../df/d94/md_docs_2performance.html#autotoc_md644',1,'']]],
  ['performance_20problems_32',['1. Common Performance Problems',['../df/d94/md_docs_2performance.html#autotoc_md682',1,'']]],
  ['performance_20profiling_33',['performance profiling',['../df/d94/md_docs_2performance.html#autotoc_md676',1,'2. Performance Profiling'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md366',1,'Performance Profiling']]],
  ['performance_20profiling_20with_20perf_34',['Performance Profiling with perf',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md868',1,'']]],
  ['performance_20questions_35',['Performance Questions',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md844',1,'']]],
  ['performance_20testing_36',['Performance Testing',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md360',1,'']]],
  ['performance_20tests_37',['Performance Tests',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md704',1,'']]],
  ['performance_20tuning_38',['Performance Tuning',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md254',1,'']]],
  ['performance_20tuning_20recommendations_39',['Performance Tuning Recommendations',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md172',1,'']]],
  ['performance_2emd_40',['performance.md',['../de/d81/performance_8md.html',1,'']]],
  ['pipeline_41',['pipeline',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md694',1,'CI/CD Pipeline'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md515',1,'Example 4: Message Pipeline'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md963',1,'Message Pipeline'],['../da/db6/md_docs_2FEATURES.html#autotoc_md402',1,'Message Pipeline'],['../d2/d64/md_docs_2architecture.html#autotoc_md99',1,'Message Processing Pipeline'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md808',1,'Message Processing Pipeline']]],
  ['pipeline_20pattern_42',['pipeline pattern',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md634',1,'Message Pipeline Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md599',1,'Message Pipeline Pattern']]],
  ['pipeline_5fbuilder_20tt_43',['Class: &lt;tt&gt;pipeline_builder&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md614',1,'']]],
  ['pipeline_5fstage_20tt_44',['Struct: &lt;tt&gt;pipeline_stage&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md603',1,'']]],
  ['pipeline_5fstages_20tt_45',['Namespace: &lt;tt&gt;pipeline_stages&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md623',1,'']]],
  ['pipelining_46',['Batching and Pipelining',['../df/d94/md_docs_2performance.html#autotoc_md673',1,'']]],
  ['plan_47',['Disaster Recovery Plan',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md288',1,'']]],
  ['planned_20additions_48',['Planned Additions',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md779',1,'']]],
  ['planned_20enhancements_49',['planned enhancements',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md838',1,'Planned Enhancements'],['../d2/d64/md_docs_2architecture.html#autotoc_md129',1,'Planned Enhancements']]],
  ['planned_20improvements_50',['Planned Improvements',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md731',1,'']]],
  ['planning_51',['planning',['../index.html#autotoc_md785',1,'Development &amp; Planning'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md932',1,'Priority 4 (Long-Term Planning)']]],
  ['platform_20specific_20notes_52',['Platform-Specific Notes',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md209',1,'']]],
  ['platform_20specific_20setup_53',['2. Platform-Specific Setup',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md453',1,'']]],
  ['platform_20support_54',['🌐 Platform Support',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md986',1,'']]],
  ['pod_20autoscaler_55',['Horizontal Pod Autoscaler',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md252',1,'']]],
  ['points_56',['points',['../d2/d64/md_docs_2architecture.html#autotoc_md105',1,'Integration Points'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md814',1,'Integration Points']]],
  ['pool_20configuration_57',['Thread Pool Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md259',1,'']]],
  ['pool_20exhaustion_58',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md886',1,'']]],
  ['pool_20impact_59',['Connection Pool Impact',['../df/d94/md_docs_2performance.html#autotoc_md664',1,'']]],
  ['pool_20management_60',['Pool Management',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md62',1,'']]],
  ['pool_20pattern_61',['pool pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md327',1,'15. Thread Pool Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md313',1,'4. Object Pool Pattern']]],
  ['pool_20tuning_62',['Connection Pool Tuning',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md264',1,'']]],
  ['pooling_63',['Object Pooling',['../df/d94/md_docs_2performance.html#autotoc_md667',1,'']]],
  ['post_20deployment_64',['Post-Deployment',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md736',1,'']]],
  ['postgresql_20configuration_65',['PostgreSQL Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md263',1,'']]],
  ['pr_2030_20success_66',['Target State (PR #30 - Success)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md909',1,'']]],
  ['pr_2031_20before_20fix_67',['Initial State (PR #31 - Before Fix)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md908',1,'']]],
  ['practices_68',['practices',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md727',1,'Best Practices'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md351',1,'Best Practices'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md630',1,'Best Practices'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md380',1,'Security Best Practices']]],
  ['pre_20deployment_69',['Pre-Deployment',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md734',1,'']]],
  ['prebuilt_20dependency_20binaries_70',['3. Prebuilt Dependency Binaries',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md927',1,'']]],
  ['prerequisites_71',['prerequisites',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md176',1,'Prerequisites'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md955',1,'Prerequisites'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md334',1,'Prerequisites'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md447',1,'Prerequisites']]],
  ['principles_72',['principles',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md800',1,'Architectural Principles'],['../d2/d64/md_docs_2architecture.html#autotoc_md91',1,'Architectural Principles'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md773',1,'Code Organization Principles']]],
  ['priority_73',['Implementation Priority',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md928',1,'']]],
  ['priority_201_20implemented_20✅_74',['Priority 1 (Implemented) ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md929',1,'']]],
  ['priority_202_20recommended_20next_20sprint_75',['Priority 2 (Recommended - Next Sprint)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md930',1,'']]],
  ['priority_203_20future_20consideration_76',['Priority 3 (Future Consideration)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md931',1,'']]],
  ['priority_204_20long_20term_20planning_77',['Priority 4 (Long-Term Planning)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md932',1,'']]],
  ['priority_20levels_78',['Priority Levels',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md63',1,'']]],
  ['priority_20queue_20operations_79',['Priority Queue Operations',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md144',1,'']]],
  ['problem_20analysis_80',['Problem Analysis',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md907',1,'']]],
  ['problem_3a_20connection_20drops_81',['Problem: Connection Drops',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md902',1,'']]],
  ['problem_3a_20database_20bottleneck_82',['Problem: Database Bottleneck',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md904',1,'']]],
  ['problem_3a_20high_20memory_20usage_83',['Problem: High Memory Usage',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md903',1,'']]],
  ['problem_3a_20service_20won_20t_20start_84',['Problem: Service Won&apos;t Start',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md900',1,'']]],
  ['problem_3a_20slow_20message_20processing_85',['Problem: Slow Message Processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md901',1,'']]],
  ['problems_86',['problems',['../df/d94/md_docs_2performance.html#autotoc_md682',1,'1. Common Performance Problems'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md899',1,'Common Problems']]],
  ['procedures_87',['Recovery Procedures',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md286',1,'']]],
  ['process_88',['Attach to Running Process',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md852',1,'']]],
  ['process_20tt_89',['&lt;tt&gt;process&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md609',1,'']]],
  ['processing_90',['processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md887',1,'Issue 4: Deadlock in Message Processing'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md901',1,'Problem: Slow Message Processing']]],
  ['processing_20pipeline_91',['processing pipeline',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md808',1,'Message Processing Pipeline'],['../d2/d64/md_docs_2architecture.html#autotoc_md99',1,'Message Processing Pipeline']]],
  ['producer_20consumer_20pattern_92',['14. Producer-Consumer Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md326',1,'']]],
  ['production_20checklist_93',['Production Checklist',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md733',1,'']]],
  ['production_20deployment_94',['Production Deployment',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md711',1,'']]],
  ['production_20features_95',['Production Features',['../da/db6/md_docs_2FEATURES.html#autotoc_md436',1,'']]],
  ['production_20find_5fpackage_20mode_96',['For Production (find_package Mode)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md199',1,'']]],
  ['production_20quality_97',['Messaging System Production Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html',1,'']]],
  ['production_20requirements_98',['Production Requirements',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md221',1,'']]],
  ['production_5fquality_2emd_99',['PRODUCTION_QUALITY.md',['../db/d40/PRODUCTION__QUALITY_8md.html',1,'']]],
  ['profiling_100',['profiling',['../df/d94/md_docs_2performance.html#autotoc_md676',1,'2. Performance Profiling'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md366',1,'Performance Profiling'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md866',1,'Tracing and Profiling']]],
  ['profiling_20with_20perf_101',['Performance Profiling with perf',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md868',1,'']]],
  ['programmatic_102',['Programmatic',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md850',1,'']]],
  ['project_103',['2. Build the Project',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md336',1,'']]],
  ['project_20structure_104',['project structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'Messaging System Project Structure'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md466',1,'Project Structure'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md344',1,'Project Structure']]],
  ['project_5fstructure_2emd_105',['PROJECT_STRUCTURE.md',['../d8/d2e/PROJECT__STRUCTURE_8md.html',1,'']]],
  ['prometheus_20configuration_106',['Prometheus Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md267',1,'']]],
  ['prometheus_20integration_107',['Prometheus Integration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md266',1,'']]],
  ['protocol_20overhead_108',['Protocol Overhead',['../df/d94/md_docs_2performance.html#autotoc_md661',1,'']]],
  ['proxy_20pattern_109',['7. Proxy Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md317',1,'']]],
  ['pub_20sub_110',['Latency Distribution (Pub/Sub)',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md164',1,'']]],
  ['pub_20sub_20migration_111',['Example 1: Simple Pub/Sub Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md512',1,'']]],
  ['pub_20sub_20pattern_112',['pub sub pattern',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md501',1,'Pub/Sub Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md960',1,'Pub/Sub Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md399',1,'Pub/Sub Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md540',1,'Pub/Sub Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md631',1,'Pub/Sub Pattern']]],
  ['pub_20sub_20performance_113',['Pub/Sub Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md151',1,'']]],
  ['publish_20subscribe_114',['Q: Can I still use simple publish/subscribe?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md530',1,'']]],
  ['publish_20tt_115',['&lt;tt&gt;publish&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md545',1,'']]],
  ['publish_5fevent_20tt_116',['&lt;tt&gt;publish_event&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md583',1,'']]],
  ['publisher_20subscriber_20scaling_117',['Publisher/Subscriber Scaling',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md169',1,'']]],
  ['publisher_20tt_118',['Class: &lt;tt&gt;publisher&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md542',1,'']]],
  ['publishing_119',['Publishing',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md44',1,'']]],
  ['pull_20official_20image_120',['Pull Official Image',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md235',1,'']]]
];
