var searchData=
[
  ['v1_20x_20and_20v2_200_20together_0',['Q: Can I use v1.x and v2.0 together?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md966',1,'']]],
  ['v2_200_20together_1',['Q: Can I use v1.x and v2.0 together?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md966',1,'']]],
  ['valgrind_2',['valgrind',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md874',1,'Using Valgrind'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1027',1,'Using Valgrind']]],
  ['validation_3',['validation',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1212',1,'Input Validation'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md892',1,'Input Validation']]],
  ['value_5fcontainer_20tt_4',['Class: &lt;tt&gt;value_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md269',1,'']]],
  ['values_5',['values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md273',1,'Adding Values'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md274',1,'Retrieving Values'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md272',1,'Setting Values']]],
  ['variables_6',['variables',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md351',1,'Environment Variables'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md775',1,'Environment Variables'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1021',1,'Environment Variables']]],
  ['variant_20tt_7',['Class: &lt;tt&gt;variant&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md277',1,'']]],
  ['vault_8',['Using HashiCorp Vault',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md777',1,'']]],
  ['vcpkg_20cache_20efficiency_9',['2. Increase vcpkg Cache Efficiency',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md244',1,'']]],
  ['verify_20installation_10',['4. Verify Installation',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md993',1,'']]],
  ['verifying_20successful_20build_11',['Verifying Successful Build',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md739',1,'']]],
  ['version_12',['Version',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2095',1,'']]],
  ['version_20migration_13',['Version Migration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1762',1,'']]],
  ['vertical_20scaling_14',['vertical scaling',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md813',1,'Vertical Scaling'],['../d2/d64/md_docs_2architecture.html#autotoc_md394',1,'Vertical Scaling'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md204',1,'Vertical Scaling']]],
  ['via_20templates_15',['Alternative B: Compile-time Logger Selection via Templates',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md18',1,'']]],
  ['view_20task_20logs_16',['View Task Logs',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1990',1,'']]],
  ['virtual_20lifecycle_20hooks_17',['Virtual Lifecycle Hooks',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1398',1,'']]],
  ['virtual_20methods_18',['virtual methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1448',1,'Optional Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1447',1,'Pure Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1397',1,'Pure Virtual Methods']]],
  ['visual_20studio_19',['Visual Studio',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md853',1,'']]],
  ['visual_20studio_20code_20',['Visual Studio Code',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md851',1,'']]],
  ['vs_20재시도하지_20않을_20에러_21',['재시도 vs 재시도하지 않을 에러',['../dd/d35/md_docs_2task_2PATTERNS__KO.html#autotoc_md1904',1,'']]],
  ['vs_20logger_5fsystem_22',['vs logger_system',['../dd/da0/md_docs_2adr_2001-logging-architecture__KO.html',1,'ADR-001: 로깅 아키텍처 - ILogger 인터페이스 vs logger_system'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html',1,'ADR-001: Logging Architecture - ILogger Interface vs logger_system']]],
  ['vs_20mutex_20comparison_23',['Lock-free vs Mutex Comparison',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1149',1,'']]],
  ['vs_20no_20retry_20errors_24',['Retry vs. No Retry Errors',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1847',1,'']]],
  ['vtune_25',['Using Intel VTune',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md880',1,'']]]
];
