var searchData=
[
  ['macos_0',['macos',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md840',1,'Issue 3: grep -P Not Supported (macOS)'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md857',1,'macOS'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1099',1,'macOS'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md990',1,'Using Instruments (macOS)']]],
  ['macro_20based_20logging_1',['Alternative C: Macro-based Logging',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md19',1,'']]],
  ['management_2',['management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1518',1,'Checkpoint Management'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md222',1,'Configuration Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md427',1,'Configuration Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md297',1,'Connection Management'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2226',1,'Dependency Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md325',1,'Lifecycle Management'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md209',1,'Memory Management'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md907',1,'Memory Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md414',1,'Memory Management'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2179',1,'Phase 7: Monitoring &amp; Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md344',1,'Pool Management'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1325',1,'Resource Management'],['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md631',1,'Route Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md326',1,'Route Management'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1569',1,'Schedule Management'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md887',1,'Secrets Management'],['../da/db6/md_docs_2FEATURES.html#autotoc_md749',1,'Subscription Management'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1519',1,'Subtask Management'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1587',1,'Task Management']]],
  ['managers_3',['Using Package Managers',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md878',1,'']]],
  ['managing_20content_20routes_4',['Managing Content Routes',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md648',1,'']]],
  ['managing_20schedules_5',['Managing Schedules',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1971',1,'']]],
  ['many_20topics_6',['Issue 5: Performance Degradation with Many Topics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1171',1,'']]],
  ['mapping_20concepts_7',['Mapping Concepts',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1884',1,'']]],
  ['matching_8',['Topic Pattern Matching',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md639',1,'']]],
  ['matching_20performance_9',['Pattern Matching Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md479',1,'']]],
  ['matrix_10',['matrix',['../da/db6/md_docs_2FEATURES.html#autotoc_md773',1,'Feature Matrix'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2255',1,'Optional Dependency Matrix']]],
  ['meaningful_20route_20ids_11',['1. Use Meaningful Route IDs',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md658',1,'']]],
  ['measurements_12',['Latency Measurements',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1256',1,'']]],
  ['mechanism_13',['Retry Mechanism',['../da/db6/md_docs_2FEATURES.html#autotoc_md712',1,'']]],
  ['medium_20term_20architectural_14',['Medium-Term (Architectural)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md246',1,'']]],
  ['memory_15',['&quot;Out of memory&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1180',1,'']]],
  ['memory_20configuration_16',['2. Memory Configuration',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1285',1,'']]],
  ['memory_20debugging_17',['Memory Debugging',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1137',1,'']]],
  ['memory_20errors_18',['Memory Errors',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1179',1,'']]],
  ['memory_20leak_20in_20long_20running_20connections_19',['Issue 2: Memory Leak in Long-Running Connections',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1168',1,'']]],
  ['memory_20leaks_20',['Memory Leaks',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1290',1,'']]],
  ['memory_20management_21',['memory management',['../d2/d64/md_docs_2architecture.html#autotoc_md414',1,'Memory Management'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md907',1,'Memory Management'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md209',1,'Memory Management']]],
  ['memory_20optimization_22',['memory optimization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1272',1,'1. Memory Optimization'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1157',1,'Memory Optimization'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1819',1,'Memory Optimization']]],
  ['memory_20overhead_23',['Per-Component Memory Overhead',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md499',1,'']]],
  ['memory_20performance_24',['Memory Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1257',1,'']]],
  ['memory_20result_20backend_25',['4.2 In-Memory Result Backend',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2170',1,'']]],
  ['memory_20safety_26',['Memory Safety',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1304',1,'']]],
  ['memory_20scaling_27',['Memory Scaling',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md500',1,'']]],
  ['memory_20usage_28',['memory usage',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md949',1,'High Memory Usage'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2105',1,'High Memory Usage'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md498',1,'Memory Usage'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1186',1,'Problem: High Memory Usage']]],
  ['memory_20usage_20analysis_29',['Memory Usage Analysis',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1158',1,'']]],
  ['memory_20usage_20growing_30',['Memory Usage Growing',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2094',1,'']]],
  ['memory_5fresult_5fbackend_31',['memory_result_backend',['../dd/db9/md_docs_2task_2API__REFERENCE__KO.html#autotoc_md1680',1,'memory_result_backend'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1561',1,'memory_result_backend']]],
  ['message를_20상속_32',['1. Task는 Message를 상속',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2201',1,'']]],
  ['message_20api_33',['Message API',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1059',1,'']]],
  ['message_20based_20tasks_34',['1. Message-Based Tasks',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1743',1,'']]],
  ['message_20broker_35',['message broker',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html',1,'Message Broker'],['../da/db6/md_docs_2FEATURES.html#autotoc_md693',1,'Message Broker']]],
  ['message_20broker_20api_36',['Message Broker API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md317',1,'']]],
  ['message_20builder_37',['Message Builder',['../da/db6/md_docs_2FEATURES.html#autotoc_md744',1,'']]],
  ['message_20builder_20performance_38',['Message Builder Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md472',1,'']]],
  ['message_20bus_39',['message bus',['../da/db6/md_docs_2FEATURES.html#autotoc_md692',1,'Message Bus'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1022',1,'Q: How do I create a message bus?']]],
  ['message_20bus_20api_40',['message bus api',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1060',1,'Message Bus API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md302',1,'Message Bus API']]],
  ['message_20bus_20doesn_20t_20start_41',['Issue: Message bus doesn&apos;t start',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1072',1,'']]],
  ['message_20bus_20interface_42',['4. Message Bus Interface',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1042',1,'']]],
  ['message_20bus_20performance_43',['Message Bus Performance',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1237',1,'']]],
  ['message_20bus_20usage_44',['message bus usage',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1106',1,'1. Basic Message Bus Usage'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1051',1,'Step 4: Migrate Message Bus Usage']]],
  ['message_20creation_45',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1050',1,'']]],
  ['message_20creation_20benchmarks_46',['Message Creation Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md471',1,'']]],
  ['message_20flow_47',['Message Flow',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2221',1,'']]],
  ['message_20format_48',['Commit Message Format',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md994',1,'']]],
  ['message_20pipeline_49',['message pipeline',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1067',1,'Example 4: Message Pipeline'],['../da/db6/md_docs_2FEATURES.html#autotoc_md700',1,'Message Pipeline'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md794',1,'Message Pipeline'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2233',1,'Message Pipeline']]],
  ['message_20pipeline_20pattern_50',['message pipeline pattern',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md181',1,'Message Pipeline Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md146',1,'Message Pipeline Pattern']]],
  ['message_20processing_51',['message processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1170',1,'Issue 4: Deadlock in Message Processing'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1184',1,'Problem: Slow Message Processing']]],
  ['message_20processing_20pipeline_52',['message processing pipeline',['../d2/d64/md_docs_2architecture.html#autotoc_md404',1,'Message Processing Pipeline'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md199',1,'Message Processing Pipeline']]],
  ['message_20queue_53',['Message Queue',['../da/db6/md_docs_2FEATURES.html#autotoc_md751',1,'']]],
  ['message_20queue_20systems_54',['From Message Queue Systems',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1883',1,'']]],
  ['message_20routing_55',['message routing',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md327',1,'Message Routing'],['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md637',1,'Message Routing']]],
  ['message_20serialization_56',['Message Serialization',['../da/db6/md_docs_2FEATURES.html#autotoc_md745',1,'']]],
  ['message_20structure_57',['message structure',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1041',1,'3. Message Structure'],['../da/db6/md_docs_2FEATURES.html#autotoc_md743',1,'Message Structure']]],
  ['message_20types_58',['Message Types',['../da/db6/md_docs_2FEATURES.html#autotoc_md742',1,'']]],
  ['message_5fbroker_59',['After (message_broker)',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md666',1,'']]],
  ['message_5fbroker_20tt_60',['Class: &lt;tt&gt;message_broker&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md323',1,'']]],
  ['message_5fbroker_2emd_61',['MESSAGE_BROKER.md',['../db/df5/MESSAGE__BROKER_8md.html',1,'']]],
  ['message_5fbus_62',['message_bus',['../d4/d54/md_docs_2API__REFERENCE__KO.html#autotoc_md374',1,'']]],
  ['message_5fbus_20tt_63',['Class: &lt;tt&gt;message_bus&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md305',1,'']]],
  ['message_5fpipeline_20tt_64',['Class: &lt;tt&gt;message_pipeline&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md149',1,'']]],
  ['messagefiltercallable_65',['messagefiltercallable',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md815',1,'MessageFilterCallable'],['../da/db6/md_docs_2FEATURES.html#autotoc_md721',1,'MessageFilterCallable']]],
  ['messageprocessorcallable_66',['messageprocessorcallable',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md814',1,'MessageProcessorCallable'],['../da/db6/md_docs_2FEATURES.html#autotoc_md720',1,'MessageProcessorCallable']]],
  ['messages_67',['messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1172',1,'Error Messages'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1167',1,'Issue 1: High CPU Usage with Small Messages'],['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md675',1,'Replaying Messages']]],
  ['messages_20not_20being_20delivered_68',['Issue: Messages not being delivered',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1073',1,'']]],
  ['messages_20tasks_20that_20always_20fail_69',['Q: How do I handle poison messages (tasks that always fail)?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2116',1,'']]],
  ['messages_20to_20dlq_70',['Moving Messages to DLQ',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md673',1,'']]],
  ['messagetransformercallable_71',['messagetransformercallable',['../da/db6/md_docs_2FEATURES.html#autotoc_md722',1,'MessageTransformerCallable'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md816',1,'MessageTransformerCallable']]],
  ['messaging_72',['Core Messaging',['../da/db6/md_docs_2FEATURES.html#autotoc_md691',1,'']]],
  ['messaging_20backends_20tt_73',['messaging backends tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1417',1,'백엔드 (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1379',1,'Backends (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)']]],
  ['messaging_20core_20tt_74',['messaging core tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1415',1,'핵심 컴포넌트 (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1377',1,'Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)']]],
  ['messaging_20event_20bridge_20integration_75',['Messaging Event Bridge Integration',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1208',1,'']]],
  ['messaging_20interfaces_20tt_76',['messaging interfaces tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1416',1,'인터페이스 (&lt;tt&gt;include/kcenon/messaging/interfaces/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1378',1,'Interfaces (&lt;tt&gt;include/kcenon/messaging/interfaces/&lt;/tt&gt;)']]],
  ['messaging_20patterns_77',['Messaging Patterns',['../da/db6/md_docs_2FEATURES.html#autotoc_md696',1,'']]],
  ['messaging_20patterns_20api_20reference_78',['Messaging Patterns API Reference',['../df/dde/md_docs_2advanced_2PATTERNS__API.html',1,'']]],
  ['messaging_20patterns_20tt_79',['messaging patterns tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1418',1,'패턴 (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1380',1,'Patterns (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)']]],
  ['messaging_20system_80',['Contributing to Messaging System',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html',1,'']]],
  ['messaging_20system_20기능_81',['Messaging System 기능',['../d4/d0c/md_docs_2FEATURES__KO.html',1,'']]],
  ['messaging_20system_20문서_82',['Messaging System 문서',['../d8/d0a/md_docs_2README__KO.html',1,'']]],
  ['messaging_20system_20변경_20이력_83',['Messaging System 변경 이력',['../db/d9f/md_docs_2CHANGELOG__KO.html',1,'']]],
  ['messaging_20system_20성능_20벤치마크_84',['Messaging System 성능 벤치마크',['../d5/ddb/md_docs_2BENCHMARKS__KO.html',1,'']]],
  ['messaging_20system_20아키텍처_85',['Messaging System 아키텍처',['../de/de3/md_docs_2ARCHITECTURE__KO.html',1,'']]],
  ['messaging_20system_20프로덕션_20품질_86',['Messaging System 프로덕션 품질',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html',1,'']]],
  ['messaging_20system_20프로젝트_20구조_87',['Messaging System 프로젝트 구조',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html',1,'']]],
  ['messaging_20system_20api_20레퍼런스_88',['Messaging System API 레퍼런스',['../d4/d54/md_docs_2API__REFERENCE__KO.html',1,'']]],
  ['messaging_20system_20changelog_89',['Messaging System Changelog',['../da/dee/md_docs_2CHANGELOG.html',1,'']]],
  ['messaging_20system_20features_90',['Messaging System Features',['../da/db6/md_docs_2FEATURES.html',1,'']]],
  ['messaging_20system_20performance_20benchmarks_91',['Messaging System Performance Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html',1,'']]],
  ['messaging_20system_20production_20quality_92',['Messaging System Production Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html',1,'']]],
  ['messaging_20system_20project_20structure_93',['Messaging System Project Structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'']]],
  ['messaging_20task_20tt_94',['messaging task tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1419',1,'태스크 큐 (&lt;tt&gt;include/kcenon/messaging/task/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1381',1,'Task Queue (&lt;tt&gt;include/kcenon/messaging/task/&lt;/tt&gt;)']]],
  ['messaging_5fclient_20tt_95',['Class: &lt;tt&gt;messaging_client&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md287',1,'']]],
  ['messaging_5fserver_20tt_96',['Class: &lt;tt&gt;messaging_server&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md283',1,'']]],
  ['messaging_5fsystem에서의_20사용_20예시_97',['messaging_system에서의 사용 예시',['../dd/da0/md_docs_2adr_2001-logging-architecture__KO.html#autotoc_md48',1,'']]],
  ['messaging_5fsystem_98',['messaging_system',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1013',1,'Q: What is messaging_system?'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md22',1,'Usage Examples in messaging_system']]],
  ['method_99',['Build Method',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1504',1,'']]],
  ['method_20pattern_100',['13. Template Method Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md76',1,'']]],
  ['methods_101',['methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1563',1,'Additional Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1503',1,'Builder Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1491',1,'Configuration Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md271',1,'Core Methods'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2096',1,'Debugging Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1489',1,'Identification Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md308',1,'Lifecycle Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md163',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md99',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md108',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md114',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md285',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md119',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md289',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md129',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md140',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md152',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md357',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md91',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md279',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md349',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md335',1,'Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1559',1,'Optional Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1551',1,'Progress Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1558',1,'Pure Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1508',1,'Pure Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1495',1,'Retry Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1490',1,'State Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1578',1,'Static Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1550',1,'Status Methods']]],
  ['metrics_102',['metrics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1281',1,'1. Built-in Metrics'],['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1236',1,'Baseline Metrics'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1225',1,'Collected Metrics'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md468',1,'Core Performance Metrics'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1298',1,'Quality Metrics'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md469',1,'Reference Performance Metrics']]],
  ['metrics_20collection_103',['metrics collection',['../d2/d64/md_docs_2architecture.html#autotoc_md424',1,'Metrics Collection'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md219',1,'Metrics Collection']]],
  ['metrics_20exposed_104',['Metrics Exposed',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md915',1,'']]],
  ['metrics_20to_20track_105',['Key Metrics to Track',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md260',1,'']]],
  ['microkernel_20pattern_106',['16. Microkernel Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md81',1,'']]],
  ['migrate_20all_20code_20at_20once_107',['Q: Do I need to migrate all code at once?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1078',1,'']]],
  ['migrate_20message_20bus_20usage_108',['Step 4: Migrate Message Bus Usage',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1051',1,'']]],
  ['migrate_20message_20creation_109',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1050',1,'']]],
  ['migrate_20to_20patterns_20optional_20but_20recommended_110',['Step 5: Migrate to Patterns (Optional but Recommended)',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1052',1,'']]],
  ['migrating_20to_201_200_111',['Migrating to 1.0',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1874',1,'']]],
  ['migration_112',['migration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1882',1,'Benefits of Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1876',1,'Configuration Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1893',1,'During Migration'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1064',1,'Example 1: Simple Pub/Sub Migration'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1065',1,'Example 2: Request-Reply Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1894',1,'Post-Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1892',1,'Pre-Migration'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1045',1,'Step-by-Step Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1873',1,'Version Migration']]],
  ['migration_20checklist_113',['Migration Checklist',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1891',1,'']]],
  ['migration_20example_114',['Migration Example',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1885',1,'']]],
  ['migration_20from_20custom_20solutions_115',['Migration from Custom Solutions',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1878',1,'']]],
  ['migration_20from_20topic_5frouter_116',['Migration from topic_router',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md664',1,'']]],
  ['migration_20guide_117',['migration guide',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html',1,'Migration Guide'],['../d2/d8d/md_docs_2task_2MIGRATION.html',1,'Task Module Migration Guide']]],
  ['migration_20issues_118',['Common Migration Issues',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1897',1,'']]],
  ['migration_20testing_119',['Q: How do I handle migration testing?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1083',1,'']]],
  ['migration_20timeline_120',['Migration Timeline',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1035',1,'']]],
  ['migration_2emd_121',['MIGRATION.md',['../d2/de3/MIGRATION_8md.html',1,'']]],
  ['migration_5fguide_2emd_122',['MIGRATION_GUIDE.md',['../d7/d6a/MIGRATION__GUIDE_8md.html',1,'']]],
  ['migration_5fko_2emd_123',['MIGRATION_KO.md',['../d6/d07/MIGRATION__KO_8md.html',1,'']]],
  ['minimal_20build_20no_20external_20systems_124',['Alternative: Minimal Build (No External Systems)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md848',1,'']]],
  ['minimum_20requirements_125',['Minimum Requirements',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md866',1,'']]],
  ['missing_20queue_20configuration_126',['Missing Queue Configuration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1899',1,'']]],
  ['mode_127',['mode',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md845',1,'For Development (FetchContent Mode)'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md846',1,'For Production (find_package Mode)'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md314',1,'Usage Example (Local Mode)']]],
  ['mode_20with_20transport_128',['Usage Example (Hybrid Mode with Transport)',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md315',1,'']]],
  ['modularity_129',['Modularity',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1402',1,'']]],
  ['module_130',['After (Task Module)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1881',1,'']]],
  ['module_20api_20reference_131',['Task Module API Reference',['../df/d18/md_docs_2task_2API__REFERENCE.html',1,'']]],
  ['module_20architecture_132',['Task Module Architecture',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html',1,'']]],
  ['module_20configuration_20guide_133',['Task Module Configuration Guide',['../dc/d1e/md_docs_2task_2CONFIGURATION.html',1,'']]],
  ['module_20documentation_134',['Module Documentation',['../d2/d64/md_docs_2architecture.html#autotoc_md394',1,'']]],
  ['module_20migration_20guide_135',['Task Module Migration Guide',['../d2/d8d/md_docs_2task_2MIGRATION.html',1,'']]],
  ['module_20organization_136',['Module Organization',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md968',1,'']]],
  ['module_20performance_137',['Task Module Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md490',1,'']]],
  ['module_20quick_20start_20guide_138',['Task Module Quick Start Guide',['../d9/dff/md_docs_2task_2QUICK__START.html',1,'']]],
  ['module_20troubleshooting_20guide_139',['Task Module Troubleshooting Guide',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html',1,'']]],
  ['module_20workflow_20patterns_140',['Task Module Workflow Patterns',['../d5/dd2/md_docs_2task_2PATTERNS.html',1,'']]],
  ['modules_141',['modules',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md998',1,'Creating New Modules'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1457',1,'Data &amp; Communication Modules']]],
  ['monitor_142',['monitor',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2180',1,'7.1 Task Monitor'],['../da/db6/md_docs_2FEATURES.html#autotoc_md710',1,'Task Monitor']]],
  ['monitor_20events_143',['Monitor Events',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2098',1,'']]],
  ['monitor_20statistics_144',['4. Monitor Statistics',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md661',1,'']]],
  ['monitoring_145',['monitoring',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md519',1,'Continuous Performance Monitoring'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1227',1,'Health Monitoring'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1315',1,'Monitoring'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md259',1,'Monitoring'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md312',1,'Monitoring'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1280',1,'Performance Monitoring']]],
  ['monitoring_20and_20observability_146',['monitoring and observability',['../d2/d64/md_docs_2architecture.html#autotoc_md423',1,'Monitoring and Observability'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md218',1,'Monitoring and Observability']]],
  ['monitoring_20dashboard_147',['2. Performance Monitoring Dashboard',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1292',1,'']]],
  ['monitoring_20management_148',['Phase 7: Monitoring &amp; Management',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2179',1,'']]],
  ['monitoring_20progress_149',['monitoring progress',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1976',1,'Monitoring Progress'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md2065',1,'Monitoring Progress']]],
  ['monitoring_20setup_150',['Monitoring Setup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md912',1,'']]],
  ['monitoring_20system_20integration_151',['monitoring system integration',['../da/db6/md_docs_2FEATURES.html#autotoc_md765',1,'Monitoring System Integration'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1223',1,'Monitoring System Integration']]],
  ['monitoring_20system_20integration_20✅_152',['Sprint 6: Monitoring &amp; System Integration ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2191',1,'']]],
  ['more_20questions_153',['More Questions?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1030',1,'']]],
  ['moving_20messages_20to_20dlq_154',['Moving Messages to DLQ',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md673',1,'']]],
  ['mutex_20comparison_155',['Lock-free vs Mutex Comparison',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1260',1,'']]]
];
