var searchData=
[
  ['name_20conflicts_0',['Issue 1: Target Name Conflicts',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md133',1,'']]],
  ['namespace_20and_20configmap_1',['Namespace and ConfigMap',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md193',1,'']]],
  ['namespace_20changes_2',['1. Namespace Changes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md461',1,'']]],
  ['namespace_3a_20tt_20container_5fmodule_20tt_3',['Namespace: &lt;tt&gt;container_module&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md4',1,'']]],
  ['namespace_3a_20tt_20database_20tt_4',['Namespace: &lt;tt&gt;database&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md29',1,'']]],
  ['namespace_3a_20tt_20kcenon_3a_3amessaging_3a_3acore_20tt_5',['Namespace: &lt;tt&gt;kcenon::messaging::core&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md39',1,'']]],
  ['namespace_3a_20tt_20kcenon_3a_3amessaging_3a_3apatterns_20tt_6',['namespace: tt kcenon::messaging::patterns tt',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md574',1,'Namespace: &lt;tt&gt;kcenon::messaging::patterns&lt;/tt&gt;'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md515',1,'Namespace: &lt;tt&gt;kcenon::messaging::patterns&lt;/tt&gt;'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md532',1,'Namespace: &lt;tt&gt;kcenon::messaging::patterns&lt;/tt&gt;'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md552',1,'Namespace: &lt;tt&gt;kcenon::messaging::patterns&lt;/tt&gt;']]],
  ['namespace_3a_20tt_20kcenon_3a_3amessaging_3a_3aservices_20tt_7',['Namespace: &lt;tt&gt;kcenon::messaging::services&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md51',1,'']]],
  ['namespace_3a_20tt_20logger_20tt_8',['Namespace: &lt;tt&gt;logger&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md71',1,'']]],
  ['namespace_3a_20tt_20network_5fmodule_20tt_9',['Namespace: &lt;tt&gt;network_module&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md18',1,'']]],
  ['namespace_3a_20tt_20pipeline_5fstages_20tt_10',['Namespace: &lt;tt&gt;pipeline_stages&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md597',1,'']]],
  ['namespace_3a_20tt_20thread_5fsystem_20tt_11',['Namespace: &lt;tt&gt;thread_system&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md58',1,'']]],
  ['naming_20conventions_12',['Naming Conventions',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md293',1,'']]],
  ['navigation_13',['🚀 Quick Navigation',['../index.html#autotoc_md667',1,'']]],
  ['need_20to_20migrate_20all_20code_20at_20once_14',['Q: Do I need to migrate all code at once?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md500',1,'']]],
  ['network_15',['network',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md701',1,'Network'],['../d2/d64/md_docs_2architecture.html#autotoc_md111',1,'Network']]],
  ['network_20analysis_16',['Network Analysis',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md762',1,'']]],
  ['network_20bottlenecks_17',['Network Bottlenecks',['../df/d94/md_docs_2performance.html#autotoc_md659',1,'']]],
  ['network_20client_20server_18',['3. Network Client/Server',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md351',1,'']]],
  ['network_20configuration_19',['3. Network Configuration',['../df/d94/md_docs_2performance.html#autotoc_md654',1,'']]],
  ['network_20debugging_20',['Network Debugging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md739',1,'']]],
  ['network_20optimization_21',['network optimization',['../df/d94/md_docs_2performance.html#autotoc_md646',1,'3. Network Optimization'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md205',1,'Network Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md761',1,'Network Optimization']]],
  ['network_20security_22',['Network Security',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md234',1,'']]],
  ['network_20statistics_23',['Network Statistics',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md741',1,'']]],
  ['network_20system_24',['network system',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md685',1,'2. Network System'],['../d2/d64/md_docs_2architecture.html#autotoc_md95',1,'2. Network System']]],
  ['network_20system_20api_25',['Network System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md17',1,'']]],
  ['network_20system_20performance_26',['Network System Performance',['../df/d94/md_docs_2performance.html#autotoc_md633',1,'']]],
  ['network_5fmodule_20tt_27',['Namespace: &lt;tt&gt;network_module&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md18',1,'']]],
  ['network_5fsystem_20strong_20communication_20layer_28',['7. &lt;strong&gt;network_system&lt;/strong&gt; - Communication Layer',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md839',1,'']]],
  ['new_29',['Directory Structure (New)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md386',1,'']]],
  ['new_20modules_30',['Creating New Modules',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md320',1,'']]],
  ['new_20users_31',['new users',['../index.html#autotoc_md668',1,'For New Users'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md849',1,'Option B: Automatic FetchContent (Easiest for New Users)']]],
  ['next_20sprint_32',['Priority 2 (Recommended - Next Sprint)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md811',1,'']]],
  ['next_20steps_33',['Next Steps',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md360',1,'']]],
  ['no_20external_20systems_34',['Alternative: Minimal Build (No External Systems)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md145',1,'']]],
  ['non_20functional_20⚠️_201_205_20verified_20benchmarks_20implemented_20awaiting_20execution_35',['Non-Functional ⚠️ 1/5 Verified (Benchmarks implemented, awaiting execution)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md437',1,'']]],
  ['not_20being_20delivered_36',['Issue: Messages not being delivered',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md495',1,'']]],
  ['not_20found_37',['Issue 4: yaml-cpp Not Found',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md139',1,'']]],
  ['not_20found_20in_20external_20systems_38',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'']]],
  ['not_20implemented_39',['❌ Not Implemented',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md828',1,'']]],
  ['not_20supported_20macos_40',['Issue 3: grep -P Not Supported (macOS)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md137',1,'']]],
  ['notes_41',['Platform-Specific Notes',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md153',1,'']]]
];
