var searchData=
[
  ['p_20not_20supported_20macos_0',['Issue 3: grep -P Not Supported (macOS)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md137',1,'']]],
  ['package_20managers_1',['Using Package Managers',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md175',1,'']]],
  ['parallel_20execution_20✅_2',['2. CTest Parallel Execution ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md706',1,'']]],
  ['parallelization_20✅_3',['3. Build Parallelization ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md707',1,'']]],
  ['parameters_4',['Linux Kernel Parameters',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md200',1,'']]],
  ['paths_5',['Update Include Paths',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md383',1,'']]],
  ['pattern_6',['pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md254',1,'1. Singleton Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md265',1,'10. Strategy Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md266',1,'11. Chain of Responsibility Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md267',1,'12. Command Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md268',1,'13. Template Method Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md270',1,'14. Producer-Consumer Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md271',1,'15. Thread Pool Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md273',1,'16. Microkernel Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md255',1,'2. Factory Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md256',1,'3. Builder Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md257',1,'4. Object Pool Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md259',1,'5. Adapter Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md260',1,'6. Decorator Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md261',1,'7. Proxy Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md262',1,'8. Composite Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md264',1,'9. Observer Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md520',1,'Event Streaming Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md464',1,'Event Streaming Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md486',1,'Message Pipeline Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md521',1,'Message Pipeline Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md518',1,'Pub/Sub Pattern'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md388',1,'Pub/Sub Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md427',1,'Pub/Sub Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md754',1,'Pub/Sub Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md444',1,'Request-Reply Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md519',1,'Request-Reply Pattern'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md389',1,'Request-Reply Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md755',1,'Request/Reply Pattern']]],
  ['patterns_7',['patterns',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md272',1,'Architectural Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md263',1,'Behavioral Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md269',1,'Concurrency Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md253',1,'Creational Patterns'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md605',1,'Scalability Patterns'],['../d2/d64/md_docs_2architecture.html#autotoc_md102',1,'Scalability Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md258',1,'Structural Patterns']]],
  ['patterns_20and_20architectural_20decisions_8',['Design Patterns and Architectural Decisions',['../d5/dca/md_docs_2DESIGN__PATTERNS.html',1,'']]],
  ['patterns_20api_20reference_9',['Messaging Patterns API Reference',['../dc/d3e/md_docs_2PATTERNS__API.html',1,'']]],
  ['patterns_20complete_10',['✅ Patterns (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md739',1,'']]],
  ['patterns_20optional_20but_20recommended_11',['Step 5: Migrate to Patterns (Optional but Recommended)',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md387',1,'']]],
  ['patterns_5fapi_2emd_12',['PATTERNS_API.md',['../d1/dff/PATTERNS__API_8md.html',1,'']]],
  ['perf_13',['perf',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md662',1,'Performance Profiling with perf'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md311',1,'Using perf']]],
  ['performance_14',['performance',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md764',1,'📊 Performance'],['../df/d94/md_docs_2performance.html#autotoc_md539',1,'Component Performance'],['../df/d94/md_docs_2performance.html#autotoc_md543',1,'Container System Performance'],['../df/d94/md_docs_2performance.html#autotoc_md549',1,'Database System Performance'],['../df/d94/md_docs_2performance.html#autotoc_md538',1,'Memory Performance'],['../df/d94/md_docs_2performance.html#autotoc_md546',1,'Network System Performance'],['../df/d94/md_docs_2performance.html#autotoc_md536',1,'Overall System Performance'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md414',1,'Q: What about performance?'],['../df/d94/md_docs_2performance.html#autotoc_md550',1,'Query Performance'],['../df/d94/md_docs_2performance.html#autotoc_md544',1,'Serialization Performance'],['../df/d94/md_docs_2performance.html#autotoc_md540',1,'Thread System Performance']]],
  ['performance_20comparison_15',['Performance Comparison',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md708',1,'']]],
  ['performance_20considerations_16',['Performance Considerations',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md528',1,'']]],
  ['performance_20degradation_17',['Issue: Build performance degradation',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md409',1,'']]],
  ['performance_20degradation_20with_20many_20topics_18',['Issue 5: Performance Degradation with Many Topics',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md682',1,'']]],
  ['performance_20features_19',['Key Performance Features',['../df/d94/md_docs_2performance.html#autotoc_md533',1,'']]],
  ['performance_20guide_20',['Performance Guide',['../df/d94/md_docs_2performance.html',1,'']]],
  ['performance_20issues_21',['performance issues',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md247',1,'Performance Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md331',1,'Performance Issues'],['../df/d94/md_docs_2performance.html#autotoc_md568',1,'Troubleshooting Performance Issues']]],
  ['performance_20monitoring_22',['Performance Monitoring',['../df/d94/md_docs_2performance.html#autotoc_md561',1,'']]],
  ['performance_20monitoring_20dashboard_23',['2. Performance Monitoring Dashboard',['../df/d94/md_docs_2performance.html#autotoc_md573',1,'']]],
  ['performance_20optimization_24',['performance optimization',['../d2/d64/md_docs_2architecture.html#autotoc_md108',1,'Performance Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md664',1,'Performance Optimization'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md611',1,'Performance Optimization'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html',1,'Windows CI Performance Optimization']]],
  ['performance_20overview_25',['Performance Overview',['../df/d94/md_docs_2performance.html#autotoc_md531',1,'']]],
  ['performance_20problems_26',['1. Common Performance Problems',['../df/d94/md_docs_2performance.html#autotoc_md569',1,'']]],
  ['performance_20profiling_27',['performance profiling',['../df/d94/md_docs_2performance.html#autotoc_md563',1,'2. Performance Profiling'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md310',1,'Performance Profiling']]],
  ['performance_20profiling_20with_20perf_28',['Performance Profiling with perf',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md662',1,'']]],
  ['performance_20questions_29',['Performance Questions',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md638',1,'']]],
  ['performance_20testing_30',['Performance Testing',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md304',1,'']]],
  ['performance_20tuning_31',['Performance Tuning',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md198',1,'']]],
  ['performance_2emd_32',['performance.md',['../de/d81/performance_8md.html',1,'']]],
  ['pipeline_33',['pipeline',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md402',1,'Example 4: Message Pipeline'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md757',1,'Message Pipeline'],['../d2/d64/md_docs_2architecture.html#autotoc_md99',1,'Message Processing Pipeline'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md602',1,'Message Processing Pipeline']]],
  ['pipeline_20pattern_34',['pipeline pattern',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md521',1,'Message Pipeline Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md486',1,'Message Pipeline Pattern']]],
  ['pipeline_5fbuilder_20tt_35',['Class: &lt;tt&gt;pipeline_builder&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md501',1,'']]],
  ['pipeline_5fstage_20tt_36',['Struct: &lt;tt&gt;pipeline_stage&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md490',1,'']]],
  ['pipeline_5fstages_20tt_37',['Namespace: &lt;tt&gt;pipeline_stages&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md510',1,'']]],
  ['pipelining_38',['Batching and Pipelining',['../df/d94/md_docs_2performance.html#autotoc_md560',1,'']]],
  ['plan_39',['Disaster Recovery Plan',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md232',1,'']]],
  ['planned_20enhancements_40',['planned enhancements',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md632',1,'Planned Enhancements'],['../d2/d64/md_docs_2architecture.html#autotoc_md129',1,'Planned Enhancements']]],
  ['planning_41',['planning',['../index.html#autotoc_md579',1,'Development &amp; Planning'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md726',1,'Priority 4 (Long-Term Planning)']]],
  ['platform_20specific_20notes_42',['Platform-Specific Notes',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md153',1,'']]],
  ['platform_20specific_20setup_43',['2. Platform-Specific Setup',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md340',1,'']]],
  ['platform_20support_44',['🌐 Platform Support',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md780',1,'']]],
  ['pod_20autoscaler_45',['Horizontal Pod Autoscaler',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md196',1,'']]],
  ['points_46',['points',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md608',1,'Integration Points'],['../d2/d64/md_docs_2architecture.html#autotoc_md105',1,'Integration Points']]],
  ['pool_20configuration_47',['Thread Pool Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md203',1,'']]],
  ['pool_20exhaustion_48',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md680',1,'']]],
  ['pool_20impact_49',['Connection Pool Impact',['../df/d94/md_docs_2performance.html#autotoc_md551',1,'']]],
  ['pool_20management_50',['Pool Management',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md62',1,'']]],
  ['pool_20pattern_51',['pool pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md271',1,'15. Thread Pool Pattern'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md257',1,'4. Object Pool Pattern']]],
  ['pool_20tuning_52',['Connection Pool Tuning',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md208',1,'']]],
  ['pooling_53',['Object Pooling',['../df/d94/md_docs_2performance.html#autotoc_md554',1,'']]],
  ['postgresql_20configuration_54',['PostgreSQL Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md207',1,'']]],
  ['pr_2030_20success_55',['Target State (PR #30 - Success)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md703',1,'']]],
  ['pr_2031_20before_20fix_56',['Initial State (PR #31 - Before Fix)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md702',1,'']]],
  ['practices_57',['practices',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md295',1,'Best Practices'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md517',1,'Best Practices'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md324',1,'Security Best Practices']]],
  ['prebuilt_20dependency_20binaries_58',['3. Prebuilt Dependency Binaries',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md721',1,'']]],
  ['prerequisites_59',['prerequisites',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md334',1,'Prerequisites'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md278',1,'Prerequisites'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md749',1,'Prerequisites']]],
  ['principles_60',['principles',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md594',1,'Architectural Principles'],['../d2/d64/md_docs_2architecture.html#autotoc_md91',1,'Architectural Principles']]],
  ['priority_61',['Implementation Priority',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md722',1,'']]],
  ['priority_201_20implemented_20✅_62',['Priority 1 (Implemented) ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md723',1,'']]],
  ['priority_202_20recommended_20next_20sprint_63',['Priority 2 (Recommended - Next Sprint)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md724',1,'']]],
  ['priority_203_20future_20consideration_64',['Priority 3 (Future Consideration)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md725',1,'']]],
  ['priority_204_20long_20term_20planning_65',['Priority 4 (Long-Term Planning)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md726',1,'']]],
  ['priority_20levels_66',['Priority Levels',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md63',1,'']]],
  ['problem_20analysis_67',['Problem Analysis',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md701',1,'']]],
  ['problem_3a_20connection_20drops_68',['Problem: Connection Drops',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md696',1,'']]],
  ['problem_3a_20database_20bottleneck_69',['Problem: Database Bottleneck',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md698',1,'']]],
  ['problem_3a_20high_20memory_20usage_70',['Problem: High Memory Usage',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md697',1,'']]],
  ['problem_3a_20service_20won_20t_20start_71',['Problem: Service Won&apos;t Start',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md694',1,'']]],
  ['problem_3a_20slow_20message_20processing_72',['Problem: Slow Message Processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md695',1,'']]],
  ['problems_73',['problems',['../df/d94/md_docs_2performance.html#autotoc_md569',1,'1. Common Performance Problems'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md693',1,'Common Problems']]],
  ['procedures_74',['Recovery Procedures',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md230',1,'']]],
  ['process_75',['Attach to Running Process',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md646',1,'']]],
  ['process_20tt_76',['&lt;tt&gt;process&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md496',1,'']]],
  ['processing_77',['processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md681',1,'Issue 4: Deadlock in Message Processing'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md695',1,'Problem: Slow Message Processing']]],
  ['processing_20pipeline_78',['processing pipeline',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md602',1,'Message Processing Pipeline'],['../d2/d64/md_docs_2architecture.html#autotoc_md99',1,'Message Processing Pipeline']]],
  ['producer_20consumer_20pattern_79',['14. Producer-Consumer Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md270',1,'']]],
  ['production_20find_5fpackage_20mode_80',['For Production (find_package Mode)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md143',1,'']]],
  ['production_20requirements_81',['Production Requirements',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md165',1,'']]],
  ['profiling_82',['profiling',['../df/d94/md_docs_2performance.html#autotoc_md563',1,'2. Performance Profiling'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md310',1,'Performance Profiling'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md660',1,'Tracing and Profiling']]],
  ['profiling_20with_20perf_83',['Performance Profiling with perf',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md662',1,'']]],
  ['programmatic_84',['Programmatic',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md644',1,'']]],
  ['project_85',['2. Build the Project',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md280',1,'']]],
  ['project_20structure_86',['project structure',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md288',1,'Project Structure'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md353',1,'Project Structure']]],
  ['prometheus_20configuration_87',['Prometheus Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md211',1,'']]],
  ['prometheus_20integration_88',['Prometheus Integration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md210',1,'']]],
  ['protocol_20overhead_89',['Protocol Overhead',['../df/d94/md_docs_2performance.html#autotoc_md548',1,'']]],
  ['proxy_20pattern_90',['7. Proxy Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md261',1,'']]],
  ['pub_20sub_20migration_91',['Example 1: Simple Pub/Sub Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md399',1,'']]],
  ['pub_20sub_20pattern_92',['pub sub pattern',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md388',1,'Pub/Sub Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md754',1,'Pub/Sub Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md427',1,'Pub/Sub Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md518',1,'Pub/Sub Pattern']]],
  ['publish_20subscribe_93',['Q: Can I still use simple publish/subscribe?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md417',1,'']]],
  ['publish_20tt_94',['&lt;tt&gt;publish&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md432',1,'']]],
  ['publish_5fevent_20tt_95',['&lt;tt&gt;publish_event&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md470',1,'']]],
  ['publisher_20tt_96',['Class: &lt;tt&gt;publisher&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md429',1,'']]],
  ['publishing_97',['Publishing',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md44',1,'']]],
  ['pull_20official_20image_98',['Pull Official Image',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md179',1,'']]]
];
