var searchData=
[
  ['latency_0',['latency',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2007',1,'High Latency'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md928',1,'Q: What is the latency?'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md472',1,'Synchronous RPC Latency']]],
  ['latency_20analysis_1',['Latency Analysis',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md487',1,'']]],
  ['latency_20breakdown_2',['Latency Breakdown',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md489',1,'']]],
  ['latency_20configuration_3',['Low Latency Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1716',1,'']]],
  ['latency_20distribution_20pub_20sub_4',['Latency Distribution (Pub/Sub)',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md488',1,'']]],
  ['latency_20measurements_5',['Latency Measurements',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1156',1,'']]],
  ['layer_6',['Application Layer',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1358',1,'']]],
  ['layers_7',['layers',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md192',1,'System Layers'],['../d2/d64/md_docs_2architecture.html#autotoc_md382',1,'System Layers']]],
  ['layout_8',['layout',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md867',1,'Directory Layout'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1274',1,'Directory Layout']]],
  ['leak_20in_20long_20running_20connections_9',['Issue 2: Memory Leak in Long-Running Connections',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1068',1,'']]],
  ['leaks_10',['Memory Leaks',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1190',1,'']]],
  ['level_20timeouts_20✅_11',['1. Test-Level Timeouts ✅',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md237',1,'']]],
  ['levels_12',['levels',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md341',1,'Log Levels'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md330',1,'Priority Levels'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1707',1,'Priority Levels'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1861',1,'Priority Levels']]],
  ['library_13',['Q: How do I install the library?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md918',1,'']]],
  ['license_14',['📄 License',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2164',1,'']]],
  ['lifecycle_15',['lifecycle',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1426',1,'Lifecycle'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1436',1,'Lifecycle'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1470',1,'Lifecycle'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1493',1,'Lifecycle']]],
  ['lifecycle_20hooks_16',['Virtual Lifecycle Hooks',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1409',1,'']]],
  ['lifecycle_20methods_17',['Lifecycle Methods',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md308',1,'']]],
  ['lifetimes_18',['Service Lifetimes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md321',1,'']]],
  ['limit_20retry_20attempts_19',['Q: How do I limit retry attempts?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2015',1,'']]],
  ['limitations_20',['limitations',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1236',1,'Current Limitations'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md754',1,'Known Limitations'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1235',1,'Known Limitations']]],
  ['limiting_21',['limiting',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md905',1,'Rate Limiting'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md842',1,'Rate Limiting']]],
  ['linux_20fedora_20rhel_22',['Linux (Fedora/RHEL)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md759',1,'']]],
  ['linux_20kernel_20parameters_23',['Linux Kernel Parameters',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md803',1,'']]],
  ['linux_20ubuntu_20debian_24',['linux ubuntu debian',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md998',1,'Linux (Ubuntu/Debian)'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md758',1,'Linux (Ubuntu/Debian)']]],
  ['load_20balancer_20configuration_25',['Load Balancer Configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md822',1,'']]],
  ['local_20mode_26',['Usage Example (Local Mode)',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md314',1,'']]],
  ['lock_20free_20queues_27',['Q: How do I enable lock-free queues?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md981',1,'']]],
  ['lock_20free_20vs_20mutex_20comparison_28',['Lock-free vs Mutex Comparison',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1160',1,'']]],
  ['lock_5ffree_5fqueue_20tt_29',['Class: &lt;tt&gt;lock_free_queue&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md332',1,'']]],
  ['log_20aggregation_20elk_20stack_30',['Log Aggregation (ELK Stack)',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md819',1,'']]],
  ['log_20levels_31',['Log Levels',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md341',1,'']]],
  ['logger_20selection_20via_20templates_32',['Alternative B: Compile-time Logger Selection via Templates',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md18',1,'']]],
  ['logger_20system_20api_33',['Logger System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md337',1,'']]],
  ['logger_20system_20integration_34',['Logger System Integration',['../da/db6/md_docs_2FEATURES.html#autotoc_md665',1,'']]],
  ['logger_20tt_35',['Namespace: &lt;tt&gt;logger&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md338',1,'']]],
  ['logger_5fmanager_20tt_36',['Class: &lt;tt&gt;logger_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md339',1,'']]],
  ['logger_5fsystem_37',['logger_system',['../dd/da0/md_docs_2adr_2001-logging-architecture__KO.html',1,'ADR-001: 로깅 아키텍처 - ILogger 인터페이스 vs logger_system'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html',1,'ADR-001: Logging Architecture - ILogger Interface vs logger_system']]],
  ['logger_5fsystem_20직접_20의존성_38',['대안 A: logger_system 직접 의존성',['../dd/da0/md_docs_2adr_2001-logging-architecture__KO.html#autotoc_md43',1,'']]],
  ['logger_5fsystem_20dependency_39',['Alternative A: Direct logger_system Dependency',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md17',1,'']]],
  ['logging_40',['logging',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md19',1,'Alternative C: Macro-based Logging'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md844',1,'Audit Logging'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1030',1,'Enable Debug Logging'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1997',1,'Enable Logging'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1421',1,'Logging'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md221',1,'Logging'],['../d2/d64/md_docs_2architecture.html#autotoc_md411',1,'Logging'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md818',1,'Structured Logging']]],
  ['logging_20architecture_20ilogger_20interface_20vs_20logger_5fsystem_41',['ADR-001: Logging Architecture - ILogger Interface vs logger_system',['../de/dd2/md_docs_2adr_2001-logging-architecture.html',1,'']]],
  ['logging_20configuration_42',['logging configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md817',1,'Logging Configuration'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2138',1,'Logging Configuration']]],
  ['logic_43',['Custom Retry Logic',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1857',1,'']]],
  ['logs_44',['View Task Logs',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2001',1,'']]],
  ['long_20running_20connections_45',['Issue 2: Memory Leak in Long-Running Connections',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1068',1,'']]],
  ['long_20running_20tasks_20configuration_46',['Long-Running Tasks Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1718',1,'']]],
  ['long_20term_20infrastructure_47',['Long-Term (Infrastructure)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md250',1,'']]],
  ['long_20term_20planning_48',['Priority 4 (Long-Term Planning)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md258',1,'']]],
  ['low_20latency_20configuration_49',['Low Latency Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1716',1,'']]],
  ['low_20throughput_50',['Low Throughput',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2006',1,'']]]
];
