var searchData=
[
  ['dashboard_0',['dashboard',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1279',1,'2. Performance Monitoring Dashboard'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md903',1,'Grafana Dashboard']]],
  ['data_1',['data',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1968',1,'Checkpoint Data'],['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1234',1,'Historical Data']]],
  ['data_20communication_20modules_2',['Data &amp; Communication Modules',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1444',1,'']]],
  ['data_20encryption_3',['Data Encryption',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md932',1,'']]],
  ['data_20flow_4',['Data Flow',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1721',1,'']]],
  ['data_20flow_20architecture_5',['data flow architecture',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md198',1,'Data Flow Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md403',1,'Data Flow Architecture']]],
  ['data_20handling_6',['2. Container-Based Data Handling',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1094',1,'']]],
  ['database_20backup_7',['Database Backup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md919',1,'']]],
  ['database_20bottleneck_8',['Problem: Database Bottleneck',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1174',1,'']]],
  ['database_20connection_20failed_9',['&quot;Database connection failed&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1164',1,'']]],
  ['database_20connection_20pool_20exhaustion_10',['Issue 3: Database Connection Pool Exhaustion',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1156',1,'']]],
  ['database_20errors_11',['Database Errors',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1163',1,'']]],
  ['database_20scaling_12',['Database Scaling',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md913',1,'']]],
  ['database_20system_13',['database system',['../d2/d64/md_docs_2architecture.html#autotoc_md401',1,'3. Database System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md196',1,'3. Database System']]],
  ['database_20system_20api_14',['Database System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md292',1,'']]],
  ['database_20system_20performance_15',['Database System Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1255',1,'']]],
  ['database_20tt_16',['Namespace: &lt;tt&gt;database&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md293',1,'']]],
  ['database_20tuning_17',['Database Tuning',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md896',1,'']]],
  ['database_5fmanager_20tt_18',['Class: &lt;tt&gt;database_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md294',1,'']]],
  ['dead_20letter_20queue_19',['Dead Letter Queue',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md656',1,'']]],
  ['deadlock_20detected_20',['&quot;Deadlock detected&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1165',1,'']]],
  ['deadlock_20in_20message_20processing_21',['Issue 4: Deadlock in Message Processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1157',1,'']]],
  ['deadlocks_22',['Detect Deadlocks',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1134',1,'']]],
  ['debian_23',['debian',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md866',1,'APT Repository (Ubuntu/Debian)'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1085',1,'Linux (Ubuntu/Debian)'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md845',1,'Linux (Ubuntu/Debian)']]],
  ['debug_20core_20dumps_24',['Debug Core Dumps',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1123',1,'']]],
  ['debug_20logging_25',['Enable Debug Logging',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1117',1,'']]],
  ['debug_20techniques_26',['Debug Techniques',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1116',1,'']]],
  ['debugging_27',['debugging',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md970',1,'Debugging'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1124',1,'Memory Debugging'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1128',1,'Network Debugging'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1132',1,'Thread Debugging'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1121',1,'Using GDB for Debugging']]],
  ['debugging_20methods_28',['Debugging Methods',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2083',1,'']]],
  ['decision_29',['Decision',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md5',1,'']]],
  ['decision_20records_20adr_30',['decision records adr',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1447',1,'Architecture Decision Records (ADR)'],['../index.html',1,'Architecture Decision Records (ADR)']]],
  ['decisions_31',['decisions',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1729',1,'Design Decisions'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html',1,'Design Patterns and Architectural Decisions'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2187',1,'Key Design Decisions'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md23',1,'Related Decisions']]],
  ['decorator_20pattern_32',['6. Decorator Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md68',1,'']]],
  ['default_20configuration_33',['Default Configuration',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1941',1,'']]],
  ['degradation_34',['Issue: Build performance degradation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1061',1,'']]],
  ['degradation_20with_20many_20topics_35',['Issue 5: Performance Degradation with Many Topics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1158',1,'']]],
  ['delay_20calculation_36',['Retry Delay Calculation',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1942',1,'']]],
  ['delayed_20execution_37',['Delayed Execution',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1530',1,'']]],
  ['delayed_20queue_20settings_38',['Delayed Queue Settings',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1781',1,'']]],
  ['delayed_20task_20execution_39',['Delayed Task Execution',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1959',1,'']]],
  ['delivered_40',['Issue: Messages not being delivered',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1060',1,'']]],
  ['dependencies_41',['dependencies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md858',1,'Build Dependencies'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1390',1,'Dependencies'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1374',1,'Dependencies'],['../da/dee/md_docs_2CHANGELOG.html#autotoc_md564',1,'Dependencies'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1080',1,'Development Dependencies'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md952',1,'Development Dependencies'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1376',1,'Optional Dependencies'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1067',1,'Q: Are there any runtime dependencies?'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2099',1,'Q: How do I handle task dependencies?'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1375',1,'Required Dependencies'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md859',1,'Runtime Dependencies'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1081',1,'Runtime Dependencies'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md857',1,'Software Dependencies'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1033',1,'Step 1: Update Dependencies']]],
  ['dependencies_20are_20required_42',['Q: What dependencies are required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1006',1,'']]],
  ['dependency_43',['Alternative A: Direct logger_system Dependency',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md17',1,'']]],
  ['dependency_20binaries_44',['3. Prebuilt Dependency Binaries',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md253',1,'']]],
  ['dependency_20configuration_45',['4. CMake Dependency Configuration',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md11',1,'']]],
  ['dependency_20injection_46',['Dependency Injection',['../da/db6/md_docs_2FEATURES.html#autotoc_md742',1,'']]],
  ['dependency_20management_47',['Dependency Management',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2213',1,'']]],
  ['deployment_48',['deployment',['../d2/d64/md_docs_2architecture.html#autotoc_md431',1,'Container Deployment'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md226',1,'Container Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md884',1,'Deployment'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1328',1,'Deployment'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md986',1,'Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md887',1,'Docker Compose Deployment'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md987',1,'Docker Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md879',1,'High Availability Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md882',1,'Kubernetes Deployment'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md988',1,'Kubernetes Deployment'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1436',1,'Operations &amp; Deployment'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1329',1,'Post-Deployment'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1327',1,'Pre-Deployment'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1304',1,'Production Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md878',1,'Single Server Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md933',1,'Troubleshooting Deployment']]],
  ['deployment_20architecture_49',['deployment architecture',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md225',1,'Deployment Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md430',1,'Deployment Architecture']]],
  ['deployment_20guide_50',['Deployment Guide',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html',1,'']]],
  ['deployment_20scenarios_51',['Deployment Scenarios',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md877',1,'']]],
  ['deployment_5fguide_2emd_52',['DEPLOYMENT_GUIDE.md',['../dd/deb/DEPLOYMENT__GUIDE_8md.html',1,'']]],
  ['dequeue_20operations_53',['Dequeue Operations',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1515',1,'']]],
  ['design_20decisions_54',['design decisions',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1729',1,'Design Decisions'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2187',1,'Key Design Decisions']]],
  ['design_20goals_55',['Design Goals',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1238',1,'']]],
  ['design_20patterns_20and_20architectural_20decisions_56',['Design Patterns and Architectural Decisions',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html',1,'']]],
  ['design_5fpatterns_2emd_57',['DESIGN_PATTERNS.md',['../d7/d96/DESIGN__PATTERNS_8md.html',1,'']]],
  ['details_58',['Implementation Details',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md7',1,'']]],
  ['detect_20deadlocks_59',['Detect Deadlocks',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1134',1,'']]],
  ['detected_60',['&quot;Deadlock detected&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1165',1,'']]],
  ['detection_61',['detection',['../da/db6/md_docs_2FEATURES.html#autotoc_md718',1,'Auto-Detection'],['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1232',1,'Regression Detection']]],
  ['developer_20guide_62',['Developer Guide',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html',1,'']]],
  ['developer_5fguide_2emd_63',['DEVELOPER_GUIDE.md',['../d0/d0f/DEVELOPER__GUIDE_8md.html',1,'']]],
  ['developers_64',['For Developers',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1440',1,'']]],
  ['development_65',['development',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1107',1,'3. Development'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md594',1,'Building for Development']]],
  ['development_20dependencies_66',['development dependencies',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md952',1,'Development Dependencies'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1080',1,'Development Dependencies']]],
  ['development_20environment_67',['Development Environment',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1797',1,'']]],
  ['development_20fetchcontent_20mode_68',['For Development (FetchContent Mode)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md832',1,'']]],
  ['development_20planning_69',['Development &amp; Planning',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1437',1,'']]],
  ['development_20setup_70',['Development Setup',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md947',1,'']]],
  ['development_20workflow_71',['development workflow',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md596',1,'Development Workflow'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2249',1,'Development Workflow']]],
  ['di_20container_72',['di container',['../da/db6/md_docs_2FEATURES.html#autotoc_md743',1,'DI Container'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1187',1,'Service Resolution from DI Container']]],
  ['diagram_73',['Component Diagram',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md617',1,'']]],
  ['differences_74',['Key Differences',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md654',1,'']]],
  ['direct_20logger_5fsystem_20dependency_75',['Alternative A: Direct logger_system Dependency',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md17',1,'']]],
  ['directory_20layout_76',['directory layout',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1361',1,'Directory Layout'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md954',1,'Directory Layout']]],
  ['disabling_20routes_77',['Enabling/Disabling Routes',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md631',1,'']]],
  ['disaster_20recovery_20plan_78',['Disaster Recovery Plan',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md922',1,'']]],
  ['disk_20i_20o_20analysis_79',['Disk I/O Analysis',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1148',1,'']]],
  ['distributed_20architecture_80',['distributed architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md406',1,'Distributed Architecture'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md201',1,'Distributed Architecture']]],
  ['distributed_20task_20queue_20system_20improvement_20plan_81',['Distributed Task Queue System - Improvement Plan',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html',1,'']]],
  ['distributed_20tracing_82',['distributed tracing',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md220',1,'Distributed Tracing'],['../d2/d64/md_docs_2architecture.html#autotoc_md425',1,'Distributed Tracing']]],
  ['distribution_20pub_20sub_83',['Latency Distribution (Pub/Sub)',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md503',1,'']]],
  ['dlq_84',['dlq',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md660',1,'Moving Messages to DLQ'],['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md663',1,'Purging DLQ'],['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md661',1,'Querying DLQ']]],
  ['dlq_20configuration_85',['DLQ Configuration',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md657',1,'']]],
  ['dlq_20configuration_20options_86',['DLQ Configuration Options',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md658',1,'']]],
  ['dlq_20event_20callbacks_87',['DLQ Event Callbacks',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md665',1,'']]],
  ['dlq_20statistics_88',['DLQ Statistics',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md664',1,'']]],
  ['do_20i_20cancel_20a_20running_20task_89',['Q: How do I cancel a running task?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2097',1,'']]],
  ['do_20i_20create_20a_20message_20bus_90',['Q: How do I create a message bus?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1009',1,'']]],
  ['do_20i_20enable_20lock_20free_20queues_91',['Q: How do I enable lock-free queues?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1068',1,'']]],
  ['do_20i_20get_20task_20progress_20from_20outside_20the_20handler_92',['Q: How do I get task progress from outside the handler?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2098',1,'']]],
  ['do_20i_20gracefully_20shut_20down_20the_20system_93',['Q: How do I gracefully shut down the system?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2104',1,'']]],
  ['do_20i_20handle_20migration_20testing_94',['Q: How do I handle migration testing?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1070',1,'']]],
  ['do_20i_20handle_20poison_20messages_20tasks_20that_20always_20fail_95',['Q: How do I handle poison messages (tasks that always fail)?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2103',1,'']]],
  ['do_20i_20handle_20task_20dependencies_96',['Q: How do I handle task dependencies?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2099',1,'']]],
  ['do_20i_20install_20the_20library_97',['Q: How do I install the library?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1005',1,'']]],
  ['do_20i_20limit_20retry_20attempts_98',['Q: How do I limit retry attempts?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2102',1,'']]],
  ['do_20i_20need_20to_20migrate_20all_20code_20at_20once_99',['Q: Do I need to migrate all code at once?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1065',1,'']]],
  ['do_20i_20prioritize_20certain_20tasks_100',['Q: How do I prioritize certain tasks?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2101',1,'']]],
  ['do_20i_20process_20tasks_20in_20order_101',['Q: How do I process tasks in order?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2100',1,'']]],
  ['do_20i_20subscribe_20to_20topics_102',['Q: How do I subscribe to topics?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1010',1,'']]],
  ['do_20i_20use_20wildcards_103',['Q: How do I use wildcards?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1011',1,'']]],
  ['docker_20compose_20deployment_104',['Docker Compose Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md887',1,'']]],
  ['docker_20deployment_105',['Docker Deployment',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md987',1,'']]],
  ['docker_20installation_106',['Docker Installation',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md868',1,'']]],
  ['documentation_107',['documentation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2237',1,'📚 Documentation'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1442',1,'🧩 Component Documentation'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1315',1,'API Documentation'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md962',1,'Code Documentation'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2238',1,'Core Documentation'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1314',1,'Documentation'],['../d2/d64/md_docs_2architecture.html#autotoc_md394',1,'Module Documentation'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1587',1,'Related Documentation'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1218',1,'Related Documentation'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2106',1,'Related Documentation'],['../d2/d64/md_docs_2architecture.html#autotoc_md392',1,'Related Documentation'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1979',1,'Related Documentation'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1737',1,'Related Documentation'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1889',1,'Related Documentation'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1812',1,'Related Documentation'],['../index.html#autotoc_md58',1,'Related Documentation'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1435',1,'User Documentation']]],
  ['documentation_20✅_108',['Sprint 7: Testing &amp; Documentation ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2179',1,'']]],
  ['documentation_20complete_109',['✅ Documentation (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2204',1,'']]],
  ['documentation_20overview_110',['📚 Documentation Overview',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1434',1,'']]],
  ['documentation_20standards_111',['documentation standards',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1448',1,'📖 Documentation Standards'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md961',1,'Documentation Standards']]],
  ['documentation_20updates_112',['🔄 Documentation Updates',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1449',1,'']]],
  ['doesn_20t_20start_113',['Issue: Message bus doesn&apos;t start',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1059',1,'']]],
  ['down_20the_20system_114',['Q: How do I gracefully shut down the system?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2104',1,'']]],
  ['downloads_115',['3. Reduce FetchContent Downloads',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md245',1,'']]],
  ['driven_20architecture_116',['17. Event-Driven Architecture',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md82',1,'']]],
  ['drops_117',['Problem: Connection Drops',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1172',1,'']]],
  ['dump_118',['TCP Dump',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1129',1,'']]],
  ['dumps_119',['Debug Core Dumps',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1123',1,'']]],
  ['during_20migration_120',['During Migration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1880',1,'']]],
  ['dynamic_20configuration_121',['dynamic configuration',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md224',1,'Dynamic Configuration'],['../d2/d64/md_docs_2architecture.html#autotoc_md429',1,'Dynamic Configuration']]]
];
