var searchData=
[
  ['i_20enable_20lock_20free_20queues_0',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md529',1,'']]],
  ['i_20handle_20migration_20testing_1',['Q: How do I handle migration testing?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md531',1,'']]],
  ['i_20need_20to_20migrate_20all_20code_20at_20once_2',['Q: Do I need to migrate all code at once?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md526',1,'']]],
  ['i_20o_20analysis_3',['Disk I/O Analysis',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md878',1,'']]],
  ['i_20o_20optimization_4',['I/O Optimization',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md877',1,'']]],
  ['i_20still_20use_20simple_20publish_20subscribe_5',['Q: Can I still use simple publish/subscribe?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md530',1,'']]],
  ['i_20use_20v1_20x_20and_20v2_200_20together_6',['Q: Can I use v1.x and v2.0 together?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md525',1,'']]],
  ['ide_20configuration_7',['IDE Configuration',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md339',1,'']]],
  ['identify_20cpu_20bottlenecks_8',['Identify CPU Bottlenecks',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md872',1,'']]],
  ['image_9',['image',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md236',1,'Build Custom Image'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md235',1,'Pull Official Image']]],
  ['impact_10',['impact',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md153',1,'Backend Impact'],['../df/d94/md_docs_2performance.html#autotoc_md664',1,'Connection Pool Impact'],['../df/d94/md_docs_2performance.html#autotoc_md658',1,'SIMD Optimization Impact'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md149',1,'Subscription Count Impact']]],
  ['implement_20build_20caching_20service_11',['2. Implement Build Caching Service',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md926',1,'']]],
  ['implement_20test_20sharding_12',['2. Implement Test Sharding',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md922',1,'']]],
  ['implementation_13',['Internal Implementation',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md766',1,'']]],
  ['implementation_20priority_14',['Implementation Priority',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md928',1,'']]],
  ['implemented_20✅_15',['Priority 1 (Implemented) ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md929',1,'']]],
  ['implemented_20solutions_16',['Implemented Solutions',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md910',1,'']]],
  ['improvements_17',['Planned Improvements',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md731',1,'']]],
  ['in_20external_20systems_18',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md191',1,'']]],
  ['in_20long_20running_20connections_19',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md885',1,'']]],
  ['in_20message_20processing_20',['Issue 4: Deadlock in Message Processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md887',1,'']]],
  ['in_20metrics_21',['1. Built-in Metrics',['../df/d94/md_docs_2performance.html#autotoc_md675',1,'']]],
  ['include_20kcenon_20messaging_20backends_20tt_22',['Backends (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md753',1,'']]],
  ['include_20kcenon_20messaging_20core_20tt_23',['Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md751',1,'']]],
  ['include_20kcenon_20messaging_20interfaces_20tt_24',['Interfaces (&lt;tt&gt;include/kcenon/messaging/interfaces/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md752',1,'']]],
  ['include_20kcenon_20messaging_20patterns_20tt_25',['Patterns (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md754',1,'']]],
  ['include_20paths_26',['Update Include Paths',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md496',1,'']]],
  ['include_20patterns_27',['Include Patterns',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md764',1,'']]],
  ['included_28',['📦 What&apos;s Included',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md943',1,'']]],
  ['includes_29',['includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md518',1,'Issue: Compilation errors with old includes'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md497',1,'Step 2: Update Includes']]],
  ['increase_20vcpkg_20cache_20efficiency_30',['2. Increase vcpkg Cache Efficiency',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md918',1,'']]],
  ['industry_20standards_31',['Industry Standards',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md725',1,'']]],
  ['infrastructure_32',['infrastructure',['../index.html#autotoc_md791',1,'Core Infrastructure'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md924',1,'Long-Term (Infrastructure)']]],
  ['infrastructure_20complete_33',['✅ Infrastructure (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md946',1,'']]],
  ['ingress_34',['Service and Ingress',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md251',1,'']]],
  ['initial_20state_20pr_2031_20before_20fix_35',['Initial State (PR #31 - Before Fix)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md908',1,'']]],
  ['injection_36',['Dependency Injection',['../da/db6/md_docs_2FEATURES.html#autotoc_md423',1,'']]],
  ['input_20validation_37',['input validation',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md717',1,'Input Validation'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md381',1,'Input Validation']]],
  ['insights_38',['Optimization Insights',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md171',1,'']]],
  ['install_39',['3. Build and Install',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md230',1,'']]],
  ['installation_40',['installation',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md460',1,'4. Verify Installation'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md234',1,'Docker Installation'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md451',1,'Installation'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md226',1,'Installation'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md956',1,'Installation']]],
  ['instruments_20macos_41',['Using Instruments (macOS)',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md368',1,'']]],
  ['integration_42',['integration',['../da/db6/md_docs_2FEATURES.html#autotoc_md434',1,'Container System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md430',1,'Integration'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md836',1,'Kubernetes Integration'],['../d2/d64/md_docs_2architecture.html#autotoc_md127',1,'Kubernetes Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md432',1,'Logger System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md433',1,'Monitoring System Integration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md266',1,'Prometheus Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md431',1,'Thread System Integration']]],
  ['integration_20backend_43',['Integration Backend',['../da/db6/md_docs_2FEATURES.html#autotoc_md407',1,'']]],
  ['integration_20example_44',['Integration Example',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md968',1,'']]],
  ['integration_20guides_45',['Integration Guides',['../d2/d64/md_docs_2architecture.html#autotoc_md90',1,'']]],
  ['integration_20points_46',['integration points',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md814',1,'Integration Points'],['../d2/d64/md_docs_2architecture.html#autotoc_md105',1,'Integration Points']]],
  ['integration_20testing_47',['Integration Testing',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md359',1,'']]],
  ['integration_20tests_48',['integration tests',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md923',1,'3. Conditional Integration Tests'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md703',1,'Integration Tests']]],
  ['integration_20with_20base_20systems_49',['🌟 Integration with Base Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md965',1,'']]],
  ['integration_20with_20other_20systems_50',['Step 7: Integration with Other Systems',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md504',1,'']]],
  ['intel_20vtune_51',['Using Intel VTune',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md369',1,'']]],
  ['interface_52',['interface',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md490',1,'4. Message Bus Interface'],['../da/db6/md_docs_2FEATURES.html#autotoc_md405',1,'Backend Interface']]],
  ['interfaces_20tt_53',['Interfaces (&lt;tt&gt;include/kcenon/messaging/interfaces/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md752',1,'']]],
  ['interfaces_20tt_20include_20kcenon_20messaging_20interfaces_20tt_54',['Interfaces (&lt;tt&gt;include/kcenon/messaging/interfaces/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md752',1,'']]],
  ['internal_20communication_55',['internal communication',['../d2/d64/md_docs_2architecture.html#autotoc_md107',1,'Internal Communication'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md816',1,'Internal Communication']]],
  ['internal_20implementation_56',['Internal Implementation',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md766',1,'']]],
  ['is_5fready_20tt_57',['&lt;tt&gt;is_ready&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md548',1,'']]],
  ['is_5frunning_20tt_58',['&lt;tt&gt;is_running&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md596',1,'']]],
  ['issue_201_3a_20high_20cpu_20usage_20with_20small_20messages_59',['Issue 1: High CPU Usage with Small Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md884',1,'']]],
  ['issue_201_3a_20target_20name_20conflicts_60',['Issue 1: Target Name Conflicts',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md189',1,'']]],
  ['issue_202_3a_20gtest_20not_20found_20in_20external_20systems_61',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md191',1,'']]],
  ['issue_202_3a_20memory_20leak_20in_20long_20running_20connections_62',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md885',1,'']]],
  ['issue_203_3a_20database_20connection_20pool_20exhaustion_63',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md886',1,'']]],
  ['issue_203_3a_20grep_20p_20not_20supported_20macos_64',['Issue 3: grep -P Not Supported (macOS)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md193',1,'']]],
  ['issue_204_3a_20deadlock_20in_20message_20processing_65',['Issue 4: Deadlock in Message Processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md887',1,'']]],
  ['issue_204_3a_20yaml_20cpp_20not_20found_66',['Issue 4: yaml-cpp Not Found',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md195',1,'']]],
  ['issue_205_3a_20performance_20degradation_20with_20many_20topics_67',['Issue 5: Performance Degradation with Many Topics',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md888',1,'']]],
  ['issue_3a_20build_20performance_20degradation_68',['Issue: Build performance degradation',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md522',1,'']]],
  ['issue_3a_20compilation_20errors_20with_20old_20includes_69',['Issue: Compilation errors with old includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md518',1,'']]],
  ['issue_3a_20error_20code_20conflicts_70',['Issue: Error code conflicts',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md519',1,'']]],
  ['issue_3a_20message_20bus_20doesn_20t_20start_71',['Issue: Message bus doesn&apos;t start',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md520',1,'']]],
  ['issue_3a_20messages_20not_20being_20delivered_72',['Issue: Messages not being delivered',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md521',1,'']]],
  ['issues_73',['issues',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md385',1,'Build Issues'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md300',1,'Common Issues'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md883',1,'Known Issues'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md303',1,'Performance Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md387',1,'Performance Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md386',1,'Runtime Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md384',1,'Troubleshooting Common Issues'],['../df/d94/md_docs_2performance.html#autotoc_md681',1,'Troubleshooting Performance Issues']]],
  ['issues_20and_20solutions_74',['Common Build Issues and Solutions',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md188',1,'']]]
];
