var searchData=
[
  ['a_20advanced_20build_20guide_0',['A. Advanced Build Guide',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1032',1,'']]],
  ['a_20error_20code_20mapping_1',['A. Error Code Mapping',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md447',1,'']]],
  ['a_3a_20local_20development_20recommended_20for_20contributors_2',['Option A: Local Development (Recommended for Contributors)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md973',1,'']]],
  ['actions_20matrix_3',['GitHub Actions Matrix',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md512',1,'']]],
  ['adapter_20pattern_4',['5. Adapter Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md259',1,'']]],
  ['add_20messaging_5fsystem_20error_20codes_20to_20common_5fsystem_5',['1.1 Add messaging_system Error Codes to common_system',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md391',1,'']]],
  ['adding_20values_6',['Adding Values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md9',1,'']]],
  ['additional_20documentation_7',['Additional Documentation',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md771',1,'']]],
  ['address_20sanitizer_8',['Address Sanitizer',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md688',1,'']]],
  ['addresssanitizer_9',['addresssanitizer',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md895',1,'Using AddressSanitizer'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md308',1,'Using AddressSanitizer']]],
  ['administrators_10',['For System Administrators',['../index.html#autotoc_md794',1,'']]],
  ['advanced_20build_20guide_11',['A. Advanced Build Guide',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1032',1,'']]],
  ['advanced_20features_12',['2. Advanced Features',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md362',1,'']]],
  ['after_20iexecutor_20based_13',['After (IExecutor-based)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md556',1,'']]],
  ['after_20ilogger_14',['After (ILogger)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md562',1,'']]],
  ['after_20result_20based_15',['After (Result-based)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md553',1,'']]],
  ['after_20value_5fcontainer_16',['After (value_container)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md559',1,'']]],
  ['aggregation_20elk_20stack_17',['Log Aggregation (ELK Stack)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md216',1,'']]],
  ['allocation_18',['allocation',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md222',1,'Resource Allocation'],['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md532',1,'System Error Code Allocation']]],
  ['allocators_19',['Custom Allocators',['../df/d94/md_docs_2performance.html#autotoc_md478',1,'']]],
  ['already_20created_20in_20phase_200_20',['CMakePresets.json (Already created in Phase 0)',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md629',1,'']]],
  ['alternative_3a_20minimal_20build_20no_20external_20systems_21',['Alternative: Minimal Build (No External Systems)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md145',1,'']]],
  ['analysis_22',['analysis',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md371',1,'Current State Analysis'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md917',1,'Disk I/O Analysis'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md914',1,'Memory Usage Analysis'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md920',1,'Network Analysis'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md902',1,'Thread Analysis']]],
  ['and_20architectural_20decisions_23',['Design Patterns and Architectural Decisions',['../d5/dca/md_docs_2DESIGN__PATTERNS.html',1,'']]],
  ['and_20benchmarks_24',['C. Testing and Benchmarks',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1042',1,'']]],
  ['and_20broker_20week_203_25',['Phase 3: Message Queue and Broker (Week 3)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md396',1,'']]],
  ['and_20configmap_26',['Namespace and ConfigMap',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md193',1,'']]],
  ['and_20dependency_20refactoring_20design_20document_27',['Phase 1: Build System and Dependency Refactoring - Design Document',['../d5/d7c/md_docs_2phase1_2DESIGN.html',1,'']]],
  ['and_20deployment_20design_20document_28',['Phase 4: Validation and Deployment - Design Document',['../db/d5d/md_docs_2phase4_2DESIGN.html',1,'']]],
  ['and_20documentation_20weeks_209_2010_20⏳_20pending_29',['Phase 9-10: Testing and Documentation (Weeks 9-10) - ⏳ PENDING',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md433',1,'']]],
  ['and_20error_20codes_20week_201_30',['Phase 1: Foundation and Error Codes (Week 1)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md390',1,'']]],
  ['and_20external_20integration_20✅_31',['Phase 1: Build System and External Integration ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md750',1,'']]],
  ['and_20feature_20flags_32',['Task 1.2: Compiler Options and Feature Flags',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md627',1,'']]],
  ['and_20future_20work_33',['Known Limitations and Future Work',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md776',1,'']]],
  ['and_20ingress_34',['Service and Ingress',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md195',1,'']]],
  ['and_20install_35',['3. Build and Install',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md174',1,'']]],
  ['and_20linting_36',['B. Code Quality and Linting',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1036',1,'']]],
  ['and_20milestones_37',['Timeline and Milestones',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md424',1,'']]],
  ['and_20monitoring_20task_203_203_38',['3. Tracing and Monitoring (Task 3.3)',['../d7/de1/md_docs_2phase3_2DESIGN.html#autotoc_md674',1,'']]],
  ['and_20observability_39',['and observability',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md866',1,'Monitoring and Observability'],['../d2/d64/md_docs_2architecture.html#autotoc_md118',1,'Monitoring and Observability']]],
  ['and_20pipelining_40',['Batching and Pipelining',['../df/d94/md_docs_2performance.html#autotoc_md483',1,'']]],
  ['and_20preparation_20✅_41',['Phase 0: Foundation and Preparation ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md748',1,'']]],
  ['and_20profiling_42',['Tracing and Profiling',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md905',1,'']]],
  ['and_20pub_20sub_20week_205_43',['Phase 5: Topic Router and Pub/Sub (Week 5)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md403',1,'']]],
  ['and_20recovery_44',['Backup and Recovery',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md226',1,'']]],
  ['and_20risk_20assessment_45',['Migration Strategy and Risk Assessment',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html',1,'']]],
  ['and_20run_46',['2. Build and Run',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md358',1,'']]],
  ['and_20setup_47',['1. Clone and Setup',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md279',1,'']]],
  ['and_20solutions_48',['Common Build Issues and Solutions',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md132',1,'']]],
  ['ansible_20rollback_20playbook_49',['Ansible Rollback Playbook',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md601',1,'']]],
  ['api_50',['api',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md3',1,'Container System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md28',1,'Database System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md70',1,'Logger System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md38',1,'Message Bus API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md17',1,'Network System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md50',1,'Service Container API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md57',1,'Thread System API']]],
  ['api_20문서화_51',['**Task 4.2 – 마이그레이션 가이드 및 API 문서화**',['../d7/d01/md_docs_2REBUILD__PLAN.html#autotoc_md828',1,'']]],
  ['api_20changes_52',['3. Container API Changes',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md579',1,'']]],
  ['api_20reference_53',['API Reference',['../db/d91/md_docs_2API__REFERENCE.html',1,'']]],
  ['api_20transformation_54',['Container API Transformation',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md557',1,'']]],
  ['api_20wrapper_55',['Legacy API Wrapper',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md581',1,'']]],
  ['api_5freference_2emd_56',['API_REFERENCE.md',['../d2/dff/API__REFERENCE_8md.html',1,'']]],
  ['appendix_57',['appendix',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1031',1,'📋 Appendix'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md446',1,'Appendix']]],
  ['application_58',['application',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md281',1,'3. Your First Application'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md356',1,'First Application'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md977',1,'Step 3: Run Your Application']]],
  ['application_20health_59',['Application Health',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md249',1,'']]],
  ['application_20layer_60',['application layer',['../index.html#autotoc_md798',1,'Application Layer'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1014',1,'Application Layer']]],
  ['application_20security_61',['application security',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md237',1,'Application Security'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md865',1,'Application Security'],['../d2/d64/md_docs_2architecture.html#autotoc_md117',1,'Application Security']]],
  ['application_20state_20backup_62',['Application State Backup',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md228',1,'']]],
  ['application_20tracing_63',['Application Tracing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md908',1,'']]],
  ['application_20tuning_64',['Application Tuning',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md202',1,'']]],
  ['applications_65',['1. Explore Sample Applications',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md361',1,'']]],
  ['apt_20repository_20ubuntu_20debian_66',['APT Repository (Ubuntu/Debian)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md176',1,'']]],
  ['architectural_20decisions_67',['Design Patterns and Architectural Decisions',['../d5/dca/md_docs_2DESIGN__PATTERNS.html',1,'']]],
  ['architectural_20patterns_68',['architectural patterns',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md378',1,'3. Missing Architectural Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md272',1,'Architectural Patterns']]],
  ['architectural_20principles_69',['architectural principles',['../d2/d64/md_docs_2architecture.html#autotoc_md91',1,'Architectural Principles'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md839',1,'Architectural Principles']]],
  ['architecture_70',['architecture',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md966',1,'🏗️ System Architecture'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md274',1,'17. Event-Driven Architecture'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md190',1,'Architecture'],['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md682',1,'Architecture'],['../d7/de1/md_docs_2phase3_2DESIGN.html#autotoc_md670',1,'Architecture'],['../d2/d64/md_docs_2architecture.html',1,'Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md841',1,'Component Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md93',1,'Component Architecture'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md387',1,'Component Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md88',1,'Component-Specific Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md846',1,'Data Flow Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md98',1,'Data Flow Architecture'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md956',1,'Dependency Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md125',1,'Deployment Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md873',1,'Deployment Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md849',1,'Distributed Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md101',1,'Distributed Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html',1,'System Architecture'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md385',1,'Target Architecture'],['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md760',1,'Technical Architecture'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md588',1,'v2.0 (New Architecture)'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md661',1,'Week 3: DI Architecture']]],
  ['architecture_20diagram_71',['Architecture Diagram',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md623',1,'']]],
  ['architecture_2emd_72',['architecture.md',['../df/d97/architecture_8md.html',1,'']]],
  ['archive_20directory_20structure_73',['Archive Directory Structure',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md564',1,'']]],
  ['archive_20script_74',['Archive Script',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md565',1,'']]],
  ['archive_20strategy_75',['Archive Strategy',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md563',1,'']]],
  ['areas_76',['Contribution Areas',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1018',1,'']]],
  ['artifacts_20task_204_205_77',['6. Deployment Artifacts (Task 4.5)',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md694',1,'']]],
  ['as_20fetchcontent_78',['As FetchContent',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1004',1,'']]],
  ['as_20installed_20package_79',['As Installed Package',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1005',1,'']]],
  ['as_20subdirectory_80',['As Subdirectory',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1003',1,'']]],
  ['assessment_81',['assessment',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html',1,'Migration Strategy and Risk Assessment'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md441',1,'Risk Assessment']]],
  ['async_20execution_20transformation_82',['Async Execution Transformation',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md554',1,'']]],
  ['attach_20to_20running_20process_83',['Attach to Running Process',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md891',1,'']]],
  ['audit_20logging_84',['Audit Logging',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md241',1,'']]],
  ['authentication_85',['Authentication',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md238',1,'']]],
  ['auto_20scaling_20rules_86',['Auto-scaling Rules',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md220',1,'']]],
  ['automatic_20fetchcontent_20easiest_20for_20new_20users_87',['Option B: Automatic FetchContent (Easiest for New Users)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md974',1,'']]],
  ['autoscaler_88',['Horizontal Pod Autoscaler',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md196',1,'']]],
  ['availability_89',['availability',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md862',1,'High Availability'],['../d2/d64/md_docs_2architecture.html#autotoc_md114',1,'High Availability']]],
  ['availability_20deployment_90',['High Availability Deployment',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md189',1,'']]],
  ['available_20build_20presets_91',['Available Build Presets',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1033',1,'']]],
  ['available_20documentation_92',['Available Documentation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1011',1,'']]]
];
