var searchData=
[
  ['range_0',['2. Error Code Range',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md488',1,'']]],
  ['rate_20limiting_1',['rate limiting',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md383',1,'Rate Limiting'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md295',1,'Rate Limiting']]],
  ['read_20replicas_2',['Read Replicas',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md280',1,'']]],
  ['readme_2emd_3',['readme.md',['../da/ddd/README_8md.html',1,'(Global Namespace)'],['../d4/d84/docs_2README_8md.html',1,'(Global Namespace)']]],
  ['recommendations_4',['recommendations',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md915',1,'Additional Recommendations'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md172',1,'Performance Tuning Recommendations']]],
  ['recommended_5',['recommended',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md458',1,'Quick Build (Recommended)'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md500',1,'Step 5: Migrate to Patterns (Optional but Recommended)']]],
  ['recommended_20build_20workflow_6',['Recommended Build Workflow',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md197',1,'']]],
  ['recommended_20next_20sprint_7',['Priority 2 (Recommended - Next Sprint)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md930',1,'']]],
  ['recommended_20requirements_8',['Recommended Requirements',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md220',1,'']]],
  ['recovery_9',['recovery',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md282',1,'Backup and Recovery'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md822',1,'Error Recovery'],['../d2/d64/md_docs_2architecture.html#autotoc_md113',1,'Error Recovery'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md287',1,'Service Recovery']]],
  ['recovery_20plan_10',['Disaster Recovery Plan',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md288',1,'']]],
  ['recovery_20procedures_11',['Recovery Procedures',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md286',1,'']]],
  ['recovery_20strategies_12',['Error Recovery Strategies',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md81',1,'']]],
  ['reduce_20fetchcontent_20downloads_13',['3. Reduce FetchContent Downloads',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md919',1,'']]],
  ['reference_14',['reference',['../db/d91/md_docs_2API__REFERENCE.html',1,'API Reference'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md82',1,'Configuration Reference'],['../dc/d3e/md_docs_2PATTERNS__API.html',1,'Messaging Patterns API Reference']]],
  ['reference_20performance_20metrics_15',['Reference Performance Metrics',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md138',1,'']]],
  ['references_16',['References',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md937',1,'']]],
  ['refused_17',['&quot;Connection refused&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md891',1,'']]],
  ['register_5fhandler_20tt_18',['register_handler tt',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md573',1,'&lt;tt&gt;register_handler&lt;/tt&gt;'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md563',1,'&lt;tt&gt;register_handler&lt;/tt&gt;']]],
  ['related_20documentation_19',['Related Documentation',['../d2/d64/md_docs_2architecture.html#autotoc_md87',1,'']]],
  ['release_20build_20for_20tests_20',['1. Use Release Build for Tests',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md917',1,'']]],
  ['reliability_21',['Reliability',['../da/db6/md_docs_2FEATURES.html#autotoc_md437',1,'']]],
  ['reliability_20features_22',['Reliability Features',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md706',1,'']]],
  ['remove_5fstage_20tt_23',['&lt;tt&gt;remove_stage&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md607',1,'']]],
  ['replay_20tt_24',['&lt;tt&gt;replay&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md586',1,'']]],
  ['replicas_25',['Read Replicas',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md280',1,'']]],
  ['reply_20migration_26',['Example 2: Request-Reply Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md513',1,'']]],
  ['reply_20pattern_27',['reply pattern',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md557',1,'Request-Reply Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md632',1,'Request-Reply Pattern'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md502',1,'Request-Reply Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md961',1,'Request/Reply Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md400',1,'Request/Reply Pattern']]],
  ['reply_20performance_28',['Request/Reply Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md155',1,'']]],
  ['report_29',['Coverage Report',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md977',1,'']]],
  ['reporting_20bugs_30',['Reporting Bugs',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md740',1,'']]],
  ['repository_31',['repository',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md228',1,'1. Clone Repository'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md452',1,'1. Clone the Repository']]],
  ['repository_20rhel_20centos_32',['YUM Repository (RHEL/CentOS)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md233',1,'']]],
  ['repository_20ubuntu_20debian_33',['APT Repository (Ubuntu/Debian)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md232',1,'']]],
  ['request_20performance_34',['Concurrent Request Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md157',1,'']]],
  ['request_20reply_20migration_35',['Example 2: Request-Reply Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md513',1,'']]],
  ['request_20reply_20pattern_36',['request reply pattern',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md557',1,'Request-Reply Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md632',1,'Request-Reply Pattern'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md502',1,'Request-Reply Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md400',1,'Request/Reply Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md961',1,'Request/Reply Pattern']]],
  ['request_20reply_20performance_37',['Request/Reply Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md155',1,'']]],
  ['request_20response_38',['Request-Response',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md46',1,'']]],
  ['request_20response_20flow_39',['request response flow',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md809',1,'Request-Response Flow'],['../d2/d64/md_docs_2architecture.html#autotoc_md100',1,'Request-Response Flow']]],
  ['request_20tt_40',['request tt',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md562',1,'&lt;tt&gt;request&lt;/tt&gt;'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md568',1,'&lt;tt&gt;request&lt;/tt&gt;']]],
  ['request_5fclient_20tt_41',['Class: &lt;tt&gt;request_client&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md565',1,'']]],
  ['request_5freply_5fhandler_20tt_42',['Class: &lt;tt&gt;request_reply_handler&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md559',1,'']]],
  ['request_5fserver_20tt_43',['Class: &lt;tt&gt;request_server&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md570',1,'']]],
  ['required_20dependencies_44',['Required Dependencies',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md761',1,'']]],
  ['required_20systems_45',['Required Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md966',1,'']]],
  ['requirements_46',['requirements',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md218',1,'Hardware Requirements'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md219',1,'Minimum Requirements'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md221',1,'Production Requirements'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md220',1,'Recommended Requirements'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md713',1,'Resource Requirements'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md448',1,'System Requirements'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md217',1,'System Requirements']]],
  ['resource_20allocation_47',['Resource Allocation',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md278',1,'']]],
  ['resource_20management_48',['Resource Management',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md719',1,'']]],
  ['resource_20requirements_49',['Resource Requirements',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md713',1,'']]],
  ['resources_50',['resources',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md981',1,'Additional Resources'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md533',1,'Additional Resources']]],
  ['response_51',['Request-Response',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md46',1,'']]],
  ['response_20flow_52',['response flow',['../d2/d64/md_docs_2architecture.html#autotoc_md100',1,'Request-Response Flow'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md809',1,'Request-Response Flow']]],
  ['responsibility_20pattern_53',['11. Chain of Responsibility Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md322',1,'']]],
  ['result_20t_20pattern_54',['Result&lt;T&gt; Pattern',['../da/db6/md_docs_2FEATURES.html#autotoc_md428',1,'']]],
  ['results_55',['Benchmark Results',['../df/d94/md_docs_2performance.html#autotoc_md647',1,'']]],
  ['retrieving_20values_56',['Retrieving Values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md10',1,'']]],
  ['review_20checklist_57',['Code Review Checklist',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md373',1,'']]],
  ['reviews_58',['Code Reviews',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md699',1,'']]],
  ['rhel_59',['Linux (Fedora/RHEL)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md212',1,'']]],
  ['rhel_20centos_60',['YUM Repository (RHEL/CentOS)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md233',1,'']]],
  ['router_61',['5. Topic Router',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md491',1,'']]],
  ['router_20api_62',['Topic Router API',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md509',1,'']]],
  ['router_20performance_63',['Topic Router Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md147',1,'']]],
  ['routing_64',['Topic Routing',['../da/db6/md_docs_2FEATURES.html#autotoc_md415',1,'']]],
  ['rpc_20latency_65',['Synchronous RPC Latency',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md156',1,'']]],
  ['rules_66',['rules',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md276',1,'Auto-scaling Rules'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md291',1,'Firewall Rules']]],
  ['run_67',['2. Build and Run',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md471',1,'']]],
  ['runners_68',['1. Use Self-Hosted Runners',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md925',1,'']]],
  ['running_20benchmarks_69',['running benchmarks',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md972',1,'Running Benchmarks'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md175',1,'Running Benchmarks']]],
  ['running_20connections_70',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md885',1,'']]],
  ['running_20process_71',['Attach to Running Process',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md852',1,'']]],
  ['running_20tests_72',['Running Tests',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md976',1,'']]],
  ['runtime_20configuration_73',['Runtime Configuration',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md848',1,'']]],
  ['runtime_20dependencies_74',['runtime dependencies',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md528',1,'Q: Are there any runtime dependencies?'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md225',1,'Runtime Dependencies'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md450',1,'Runtime Dependencies']]],
  ['runtime_20issues_75',['Runtime Issues',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md386',1,'']]]
];
