var searchData=
[
  ['dashboard_0',['dashboard',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1035',1,'2. Performance Monitoring Dashboard'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md682',1,'Grafana Dashboard']]],
  ['data_1',['data',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1696',1,'Checkpoint Data'],['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md990',1,'Historical Data']]],
  ['data_20communication_20modules_2',['Data &amp; Communication Modules',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1175',1,'']]],
  ['data_20encryption_3',['Data Encryption',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md711',1,'']]],
  ['data_20flow_4',['Data Flow',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1449',1,'']]],
  ['data_20flow_20architecture_5',['data flow architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md326',1,'Data Flow Architecture'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md139',1,'Data Flow Architecture']]],
  ['data_20handling_6',['2. Container-Based Data Handling',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md873',1,'']]],
  ['database_20backup_7',['Database Backup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md698',1,'']]],
  ['database_20bottleneck_8',['Problem: Database Bottleneck',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md953',1,'']]],
  ['database_20connection_20failed_9',['&quot;Database connection failed&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md943',1,'']]],
  ['database_20connection_20pool_20exhaustion_10',['Issue 3: Database Connection Pool Exhaustion',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md935',1,'']]],
  ['database_20errors_11',['Database Errors',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md942',1,'']]],
  ['database_20scaling_12',['Database Scaling',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md692',1,'']]],
  ['database_20system_13',['database system',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md137',1,'3. Database System'],['../d2/d64/md_docs_2architecture.html#autotoc_md324',1,'3. Database System']]],
  ['database_20system_20api_14',['Database System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md233',1,'']]],
  ['database_20system_20performance_15',['Database System Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1011',1,'']]],
  ['database_20tt_16',['Namespace: &lt;tt&gt;database&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md234',1,'']]],
  ['database_20tuning_17',['Database Tuning',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md675',1,'']]],
  ['database_5fmanager_20tt_18',['Class: &lt;tt&gt;database_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md235',1,'']]],
  ['deadlock_20detected_19',['&quot;Deadlock detected&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md944',1,'']]],
  ['deadlock_20in_20message_20processing_20',['Issue 4: Deadlock in Message Processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md936',1,'']]],
  ['deadlocks_21',['Detect Deadlocks',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md913',1,'']]],
  ['debian_22',['debian',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md645',1,'APT Repository (Ubuntu/Debian)'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md864',1,'Linux (Ubuntu/Debian)'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md624',1,'Linux (Ubuntu/Debian)']]],
  ['debug_20core_20dumps_23',['Debug Core Dumps',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md902',1,'']]],
  ['debug_20logging_24',['Enable Debug Logging',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md896',1,'']]],
  ['debug_20techniques_25',['Debug Techniques',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md895',1,'']]],
  ['debugging_26',['debugging',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md749',1,'Debugging'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md903',1,'Memory Debugging'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md907',1,'Network Debugging'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md911',1,'Thread Debugging'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md900',1,'Using GDB for Debugging']]],
  ['debugging_20methods_27',['Debugging Methods',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1811',1,'']]],
  ['decisions_28',['decisions',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1457',1,'Design Decisions'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html',1,'Design Patterns and Architectural Decisions'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1915',1,'Key Design Decisions']]],
  ['decorator_20pattern_29',['6. Decorator Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md9',1,'']]],
  ['default_20configuration_30',['Default Configuration',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1669',1,'']]],
  ['degradation_31',['Issue: Build performance degradation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md840',1,'']]],
  ['degradation_20with_20many_20topics_32',['Issue 5: Performance Degradation with Many Topics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md937',1,'']]],
  ['delay_20calculation_33',['Retry Delay Calculation',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1670',1,'']]],
  ['delayed_20execution_34',['Delayed Execution',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1258',1,'']]],
  ['delayed_20queue_20settings_35',['Delayed Queue Settings',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1509',1,'']]],
  ['delayed_20task_20execution_36',['Delayed Task Execution',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1687',1,'']]],
  ['delivered_37',['Issue: Messages not being delivered',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md839',1,'']]],
  ['dependencies_38',['dependencies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md637',1,'Build Dependencies'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1129',1,'Dependencies'],['../da/dee/md_docs_2CHANGELOG.html#autotoc_md473',1,'Dependencies'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1145',1,'Dependencies'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md731',1,'Development Dependencies'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md859',1,'Development Dependencies'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1131',1,'Optional Dependencies'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md846',1,'Q: Are there any runtime dependencies?'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1827',1,'Q: How do I handle task dependencies?'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1130',1,'Required Dependencies'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md860',1,'Runtime Dependencies'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md638',1,'Runtime Dependencies'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md636',1,'Software Dependencies'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md812',1,'Step 1: Update Dependencies']]],
  ['dependencies_20are_20required_39',['Q: What dependencies are required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md785',1,'']]],
  ['dependency_20binaries_40',['3. Prebuilt Dependency Binaries',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md194',1,'']]],
  ['dependency_20injection_41',['Dependency Injection',['../da/db6/md_docs_2FEATURES.html#autotoc_md548',1,'']]],
  ['dependency_20management_42',['Dependency Management',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1941',1,'']]],
  ['deployment_43',['deployment',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md167',1,'Container Deployment'],['../d2/d64/md_docs_2architecture.html#autotoc_md354',1,'Container Deployment'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md765',1,'Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md663',1,'Deployment'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1084',1,'Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md666',1,'Docker Compose Deployment'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md766',1,'Docker Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md658',1,'High Availability Deployment'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md767',1,'Kubernetes Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md661',1,'Kubernetes Deployment'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1167',1,'Operations &amp; Deployment'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1085',1,'Post-Deployment'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1083',1,'Pre-Deployment'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1060',1,'Production Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md657',1,'Single Server Deployment'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md712',1,'Troubleshooting Deployment']]],
  ['deployment_20architecture_44',['deployment architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md353',1,'Deployment Architecture'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md166',1,'Deployment Architecture']]],
  ['deployment_20guide_45',['Deployment Guide',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html',1,'']]],
  ['deployment_20scenarios_46',['Deployment Scenarios',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md656',1,'']]],
  ['deployment_5fguide_2emd_47',['DEPLOYMENT_GUIDE.md',['../dd/deb/DEPLOYMENT__GUIDE_8md.html',1,'']]],
  ['dequeue_20operations_48',['Dequeue Operations',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1243',1,'']]],
  ['design_20decisions_49',['design decisions',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1457',1,'Design Decisions'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1915',1,'Key Design Decisions']]],
  ['design_20goals_50',['Design Goals',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md994',1,'']]],
  ['design_20patterns_20and_20architectural_20decisions_51',['Design Patterns and Architectural Decisions',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html',1,'']]],
  ['design_5fpatterns_2emd_52',['DESIGN_PATTERNS.md',['../d7/d96/DESIGN__PATTERNS_8md.html',1,'']]],
  ['detect_20deadlocks_53',['Detect Deadlocks',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md913',1,'']]],
  ['detected_54',['&quot;Deadlock detected&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md944',1,'']]],
  ['detection_55',['detection',['../da/db6/md_docs_2FEATURES.html#autotoc_md533',1,'Auto-Detection'],['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md988',1,'Regression Detection']]],
  ['developer_20guide_56',['Developer Guide',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html',1,'']]],
  ['developer_5fguide_2emd_57',['DEVELOPER_GUIDE.md',['../d0/d0f/DEVELOPER__GUIDE_8md.html',1,'']]],
  ['developers_58',['For Developers',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1171',1,'']]],
  ['development_59',['development',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md886',1,'3. Development'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md501',1,'Building for Development']]],
  ['development_20dependencies_60',['development dependencies',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md731',1,'Development Dependencies'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md859',1,'Development Dependencies']]],
  ['development_20environment_61',['Development Environment',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1525',1,'']]],
  ['development_20fetchcontent_20mode_62',['For Development (FetchContent Mode)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md611',1,'']]],
  ['development_20planning_63',['Development &amp; Planning',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1168',1,'']]],
  ['development_20setup_64',['Development Setup',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md726',1,'']]],
  ['development_20workflow_65',['development workflow',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1976',1,'Development Workflow'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md503',1,'Development Workflow']]],
  ['di_20container_66',['DI Container',['../da/db6/md_docs_2FEATURES.html#autotoc_md549',1,'']]],
  ['directory_20layout_67',['directory layout',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md733',1,'Directory Layout'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1117',1,'Directory Layout']]],
  ['disaster_20recovery_20plan_68',['Disaster Recovery Plan',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md701',1,'']]],
  ['disk_20i_20o_20analysis_69',['Disk I/O Analysis',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md927',1,'']]],
  ['distributed_20architecture_70',['distributed architecture',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md142',1,'Distributed Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md329',1,'Distributed Architecture']]],
  ['distributed_20task_20queue_20system_20improvement_20plan_71',['Distributed Task Queue System - Improvement Plan',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html',1,'']]],
  ['distributed_20tracing_72',['distributed tracing',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md161',1,'Distributed Tracing'],['../d2/d64/md_docs_2architecture.html#autotoc_md348',1,'Distributed Tracing']]],
  ['distribution_20pub_20sub_73',['Latency Distribution (Pub/Sub)',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md418',1,'']]],
  ['do_20i_20cancel_20a_20running_20task_74',['Q: How do I cancel a running task?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1825',1,'']]],
  ['do_20i_20create_20a_20message_20bus_75',['Q: How do I create a message bus?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md788',1,'']]],
  ['do_20i_20enable_20lock_20free_20queues_76',['Q: How do I enable lock-free queues?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md847',1,'']]],
  ['do_20i_20get_20task_20progress_20from_20outside_20the_20handler_77',['Q: How do I get task progress from outside the handler?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1826',1,'']]],
  ['do_20i_20gracefully_20shut_20down_20the_20system_78',['Q: How do I gracefully shut down the system?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1832',1,'']]],
  ['do_20i_20handle_20migration_20testing_79',['Q: How do I handle migration testing?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md849',1,'']]],
  ['do_20i_20handle_20poison_20messages_20tasks_20that_20always_20fail_80',['Q: How do I handle poison messages (tasks that always fail)?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1831',1,'']]],
  ['do_20i_20handle_20task_20dependencies_81',['Q: How do I handle task dependencies?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1827',1,'']]],
  ['do_20i_20install_20the_20library_82',['Q: How do I install the library?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md784',1,'']]],
  ['do_20i_20limit_20retry_20attempts_83',['Q: How do I limit retry attempts?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1830',1,'']]],
  ['do_20i_20need_20to_20migrate_20all_20code_20at_20once_84',['Q: Do I need to migrate all code at once?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md844',1,'']]],
  ['do_20i_20prioritize_20certain_20tasks_85',['Q: How do I prioritize certain tasks?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1829',1,'']]],
  ['do_20i_20process_20tasks_20in_20order_86',['Q: How do I process tasks in order?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1828',1,'']]],
  ['do_20i_20subscribe_20to_20topics_87',['Q: How do I subscribe to topics?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md789',1,'']]],
  ['do_20i_20use_20wildcards_88',['Q: How do I use wildcards?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md790',1,'']]],
  ['docker_20compose_20deployment_89',['Docker Compose Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md666',1,'']]],
  ['docker_20deployment_90',['Docker Deployment',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md766',1,'']]],
  ['docker_20installation_91',['Docker Installation',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md647',1,'']]],
  ['docs_92',['docs/',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1159',1,'']]],
  ['documentation_93',['documentation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1965',1,'📚 Documentation'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1173',1,'🧩 Component Documentation'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1071',1,'API Documentation'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md741',1,'Code Documentation'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1966',1,'Core Documentation'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1070',1,'Documentation'],['../d2/d64/md_docs_2architecture.html#autotoc_md317',1,'Module Documentation'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1315',1,'Related Documentation'],['../index.html#autotoc_md974',1,'Related Documentation'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1834',1,'Related Documentation'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1707',1,'Related Documentation'],['../d2/d64/md_docs_2architecture.html#autotoc_md315',1,'Related Documentation'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1617',1,'Related Documentation'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1540',1,'Related Documentation'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1465',1,'Related Documentation'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1907',1,'Sprint 7: Testing &amp; Documentation'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1166',1,'User Documentation']]],
  ['documentation_20complete_94',['✅ Documentation (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1932',1,'']]],
  ['documentation_20overview_95',['📚 Documentation Overview',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1165',1,'']]],
  ['documentation_20standards_96',['documentation standards',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1178',1,'📖 Documentation Standards'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md740',1,'Documentation Standards']]],
  ['documentation_20updates_97',['🔄 Documentation Updates',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1179',1,'']]],
  ['doesn_20t_20start_98',['Issue: Message bus doesn&apos;t start',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md838',1,'']]],
  ['down_20the_20system_99',['Q: How do I gracefully shut down the system?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1832',1,'']]],
  ['downloads_100',['3. Reduce FetchContent Downloads',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md186',1,'']]],
  ['driven_20architecture_101',['17. Event-Driven Architecture',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md23',1,'']]],
  ['drops_102',['Problem: Connection Drops',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md951',1,'']]],
  ['dump_103',['TCP Dump',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md908',1,'']]],
  ['dumps_104',['Debug Core Dumps',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md902',1,'']]],
  ['during_20migration_105',['During Migration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1608',1,'']]],
  ['dynamic_20configuration_106',['dynamic configuration',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md165',1,'Dynamic Configuration'],['../d2/d64/md_docs_2architecture.html#autotoc_md352',1,'Dynamic Configuration']]]
];
