var searchData=
[
  ['i_20enable_20lock_20free_20queues_0',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md416',1,'']]],
  ['i_20handle_20migration_20testing_1',['Q: How do I handle migration testing?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md418',1,'']]],
  ['i_20need_20to_20migrate_20all_20code_20at_20once_2',['Q: Do I need to migrate all code at once?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md413',1,'']]],
  ['i_20o_20analysis_3',['Disk I/O Analysis',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md672',1,'']]],
  ['i_20o_20optimization_4',['I/O Optimization',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md671',1,'']]],
  ['i_20still_20use_20simple_20publish_20subscribe_5',['Q: Can I still use simple publish/subscribe?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md417',1,'']]],
  ['i_20use_20v1_20x_20and_20v2_200_20together_6',['Q: Can I use v1.x and v2.0 together?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md412',1,'']]],
  ['ide_20configuration_7',['IDE Configuration',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md283',1,'']]],
  ['identify_20cpu_20bottlenecks_8',['Identify CPU Bottlenecks',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md666',1,'']]],
  ['image_9',['image',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md180',1,'Build Custom Image'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md179',1,'Pull Official Image']]],
  ['impact_10',['impact',['../df/d94/md_docs_2performance.html#autotoc_md551',1,'Connection Pool Impact'],['../df/d94/md_docs_2performance.html#autotoc_md545',1,'SIMD Optimization Impact']]],
  ['implement_20build_20caching_20service_11',['2. Implement Build Caching Service',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md720',1,'']]],
  ['implement_20test_20sharding_12',['2. Implement Test Sharding',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md716',1,'']]],
  ['implementation_20priority_13',['Implementation Priority',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md722',1,'']]],
  ['implemented_20✅_14',['Priority 1 (Implemented) ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md723',1,'']]],
  ['implemented_20solutions_15',['Implemented Solutions',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md704',1,'']]],
  ['in_20external_20systems_16',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'']]],
  ['in_20long_20running_20connections_17',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md679',1,'']]],
  ['in_20message_20processing_18',['Issue 4: Deadlock in Message Processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md681',1,'']]],
  ['in_20metrics_19',['1. Built-in Metrics',['../df/d94/md_docs_2performance.html#autotoc_md562',1,'']]],
  ['include_20paths_20',['Update Include Paths',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md383',1,'']]],
  ['included_21',['📦 What&apos;s Included',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md737',1,'']]],
  ['includes_22',['includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md405',1,'Issue: Compilation errors with old includes'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md384',1,'Step 2: Update Includes']]],
  ['increase_20vcpkg_20cache_20efficiency_23',['2. Increase vcpkg Cache Efficiency',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md712',1,'']]],
  ['infrastructure_24',['infrastructure',['../index.html#autotoc_md585',1,'Core Infrastructure'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md718',1,'Long-Term (Infrastructure)']]],
  ['infrastructure_20complete_25',['✅ Infrastructure (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md740',1,'']]],
  ['ingress_26',['Service and Ingress',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md195',1,'']]],
  ['initial_20state_20pr_2031_20before_20fix_27',['Initial State (PR #31 - Before Fix)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md702',1,'']]],
  ['input_20validation_28',['Input Validation',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md325',1,'']]],
  ['install_29',['3. Build and Install',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md174',1,'']]],
  ['installation_30',['installation',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md347',1,'4. Verify Installation'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md178',1,'Docker Installation'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md338',1,'Installation'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md170',1,'Installation'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md750',1,'Installation']]],
  ['instruments_20macos_31',['Using Instruments (macOS)',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md312',1,'']]],
  ['integration_32',['integration',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md630',1,'Kubernetes Integration'],['../d2/d64/md_docs_2architecture.html#autotoc_md127',1,'Kubernetes Integration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md210',1,'Prometheus Integration']]],
  ['integration_20example_33',['Integration Example',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md762',1,'']]],
  ['integration_20guides_34',['Integration Guides',['../d2/d64/md_docs_2architecture.html#autotoc_md90',1,'']]],
  ['integration_20points_35',['integration points',['../d2/d64/md_docs_2architecture.html#autotoc_md105',1,'Integration Points'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md608',1,'Integration Points']]],
  ['integration_20testing_36',['Integration Testing',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md303',1,'']]],
  ['integration_20tests_37',['3. Conditional Integration Tests',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md717',1,'']]],
  ['integration_20with_20base_20systems_38',['🌟 Integration with Base Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md759',1,'']]],
  ['integration_20with_20other_20systems_39',['Step 7: Integration with Other Systems',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md391',1,'']]],
  ['intel_20vtune_40',['Using Intel VTune',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md313',1,'']]],
  ['interface_41',['4. Message Bus Interface',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md377',1,'']]],
  ['internal_20communication_42',['internal communication',['../d2/d64/md_docs_2architecture.html#autotoc_md107',1,'Internal Communication'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md610',1,'Internal Communication']]],
  ['is_5fready_20tt_43',['&lt;tt&gt;is_ready&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md435',1,'']]],
  ['is_5frunning_20tt_44',['&lt;tt&gt;is_running&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md483',1,'']]],
  ['issue_201_3a_20high_20cpu_20usage_20with_20small_20messages_45',['Issue 1: High CPU Usage with Small Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md678',1,'']]],
  ['issue_201_3a_20target_20name_20conflicts_46',['Issue 1: Target Name Conflicts',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md133',1,'']]],
  ['issue_202_3a_20gtest_20not_20found_20in_20external_20systems_47',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'']]],
  ['issue_202_3a_20memory_20leak_20in_20long_20running_20connections_48',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md679',1,'']]],
  ['issue_203_3a_20database_20connection_20pool_20exhaustion_49',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md680',1,'']]],
  ['issue_203_3a_20grep_20p_20not_20supported_20macos_50',['Issue 3: grep -P Not Supported (macOS)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md137',1,'']]],
  ['issue_204_3a_20deadlock_20in_20message_20processing_51',['Issue 4: Deadlock in Message Processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md681',1,'']]],
  ['issue_204_3a_20yaml_20cpp_20not_20found_52',['Issue 4: yaml-cpp Not Found',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md139',1,'']]],
  ['issue_205_3a_20performance_20degradation_20with_20many_20topics_53',['Issue 5: Performance Degradation with Many Topics',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md682',1,'']]],
  ['issue_3a_20build_20performance_20degradation_54',['Issue: Build performance degradation',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md409',1,'']]],
  ['issue_3a_20compilation_20errors_20with_20old_20includes_55',['Issue: Compilation errors with old includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md405',1,'']]],
  ['issue_3a_20error_20code_20conflicts_56',['Issue: Error code conflicts',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md406',1,'']]],
  ['issue_3a_20message_20bus_20doesn_20t_20start_57',['Issue: Message bus doesn&apos;t start',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md407',1,'']]],
  ['issue_3a_20messages_20not_20being_20delivered_58',['Issue: Messages not being delivered',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md408',1,'']]],
  ['issues_59',['issues',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md329',1,'Build Issues'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md244',1,'Common Issues'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md677',1,'Known Issues'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md247',1,'Performance Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md331',1,'Performance Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md330',1,'Runtime Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md328',1,'Troubleshooting Common Issues'],['../df/d94/md_docs_2performance.html#autotoc_md568',1,'Troubleshooting Performance Issues']]],
  ['issues_20and_20solutions_60',['Common Build Issues and Solutions',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md132',1,'']]]
];
