var searchData=
[
  ['c_20standard_20is_20required_0',['Q: What C++ standard is required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md780',1,'']]],
  ['c_20style_20guide_1',['C++ Style Guide',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md736',1,'']]],
  ['cache_20efficiency_2',['2. Increase vcpkg Cache Efficiency',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md185',1,'']]],
  ['cache_20optimization_3',['Cache Optimization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1020',1,'']]],
  ['caching_20service_4',['2. Implement Build Caching Service',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md193',1,'']]],
  ['calculation_5',['Retry Delay Calculation',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1664',1,'']]],
  ['callback_20based_6',['Callback-Based',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1268',1,'']]],
  ['callback_20handler_7',['Callback Handler',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1658',1,'']]],
  ['callbacks_8',['Event Callbacks',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1287',1,'']]],
  ['can_20i_20expect_9',['Q: What throughput can I expect?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md793',1,'']]],
  ['can_20i_20still_20use_20simple_20publish_20subscribe_10',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md848',1,'']]],
  ['can_20i_20use_20v1_20x_20and_20v2_200_20together_11',['Q: Can I use v1.x and v2.0 together?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md843',1,'']]],
  ['cancel_20a_20running_20task_12',['Q: How do I cancel a running task?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1819',1,'']]],
  ['cancellation_13',['cancellation',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1235',1,'Cancellation'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1244',1,'Cancellation'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1261',1,'Result/Cancellation']]],
  ['cases_14',['cases',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1660',1,'Use Cases'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1653',1,'Use Cases'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1695',1,'Use Cases']]],
  ['cd_20인프라_15',['CI/CD 인프라',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html#autotoc_md1099',1,'']]],
  ['cd_20pipeline_16',['CI/CD Pipeline',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1043',1,'']]],
  ['centos_17',['YUM Repository (RHEL/CentOS)',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md646',1,'']]],
  ['certain_20tasks_18',['Q: How do I prioritize certain tasks?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1823',1,'']]],
  ['chain_19',['재시도가 있는 Chain',['../dd/d35/md_docs_2task_2PATTERNS__KO.html#autotoc_md1755',1,'']]],
  ['chain_20패턴_20',['Chain 패턴',['../dd/d35/md_docs_2task_2PATTERNS__KO.html#autotoc_md1705',1,'']]],
  ['chain_20of_20responsibility_20pattern_21',['11. Chain of Responsibility Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md15',1,'']]],
  ['chain_20pattern_22',['Chain Pattern',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1648',1,'']]],
  ['chain_20with_20retry_23',['Chain with Retry',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1698',1,'']]],
  ['changed_24',['changed',['../da/dee/md_docs_2CHANGELOG.html#autotoc_md468',1,'Changed'],['../da/dee/md_docs_2CHANGELOG.html#autotoc_md477',1,'Changed']]],
  ['changelog_25',['Messaging System Changelog',['../da/dee/md_docs_2CHANGELOG.html',1,'']]],
  ['changelog_2emd_26',['CHANGELOG.md',['../d3/d02/CHANGELOG_8md.html',1,'']]],
  ['changelog_5fko_2emd_27',['CHANGELOG_KO.md',['../d4/dfc/CHANGELOG__KO_8md.html',1,'']]],
  ['changes_28',['changes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md805',1,'1. Namespace Changes'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1584',1,'API Changes'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md824',1,'API Changes'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md804',1,'Breaking Changes']]],
  ['characteristics_29',['Scaling Characteristics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1004',1,'']]],
  ['chat_20server_20chat_5fserver_20cpp_30',['1. Chat Server (chat_server.cpp)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md880',1,'']]],
  ['chat_5fserver_20cpp_31',['1. Chat Server (chat_server.cpp)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md880',1,'']]],
  ['check_20queue_20status_32',['Check Queue Status',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1808',1,'']]],
  ['check_20worker_20status_33',['Check Worker Status',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1809',1,'']]],
  ['checklist_34',['checklist',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md761',1,'Code Review Checklist'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1600',1,'Migration Checklist'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1082',1,'Production Checklist'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1604',1,'Testing Checklist']]],
  ['checkpoint_20and_20recovery_35',['Checkpoint and Recovery',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1688',1,'']]],
  ['checkpoint_20data_36',['Checkpoint Data',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1690',1,'']]],
  ['checkpoint_20management_37',['Checkpoint Management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1233',1,'']]],
  ['checkpoints_38',['Saving Checkpoints',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1689',1,'']]],
  ['checks_39',['Health Checks',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md717',1,'']]],
  ['chord_40',['chord',['../dd/d35/md_docs_2task_2PATTERNS__KO.html#autotoc_md1756',1,'예약된 Chord'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1699',1,'Scheduled Chord']]],
  ['chord_20패턴_41',['Chord 패턴',['../dd/d35/md_docs_2task_2PATTERNS__KO.html#autotoc_md1712',1,'']]],
  ['chord_20pattern_42',['Chord Pattern',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1655',1,'']]],
  ['ci_20cd_20인프라_43',['CI/CD 인프라',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html#autotoc_md1099',1,'']]],
  ['ci_20cd_20pipeline_44',['CI/CD Pipeline',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1043',1,'']]],
  ['ci_20performance_20optimization_45',['Windows CI Performance Optimization',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html',1,'']]],
  ['class_3a_20tt_20database_5fmanager_20tt_46',['Class: &lt;tt&gt;database_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md235',1,'']]],
  ['class_3a_20tt_20event_5fbatch_5fprocessor_20tt_47',['Class: &lt;tt&gt;event_batch_processor&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md79',1,'']]],
  ['class_3a_20tt_20event_5fstream_20tt_48',['Class: &lt;tt&gt;event_stream&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md68',1,'']]],
  ['class_3a_20tt_20lock_5ffree_5fqueue_20tt_49',['Class: &lt;tt&gt;lock_free_queue&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md270',1,'']]],
  ['class_3a_20tt_20logger_5fmanager_20tt_50',['Class: &lt;tt&gt;logger_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md277',1,'']]],
  ['class_3a_20tt_20message_5fbus_20tt_51',['Class: &lt;tt&gt;message_bus&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md245',1,'']]],
  ['class_3a_20tt_20message_5fpipeline_20tt_52',['Class: &lt;tt&gt;message_pipeline&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md90',1,'']]],
  ['class_3a_20tt_20messaging_5fclient_20tt_53',['Class: &lt;tt&gt;messaging_client&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md228',1,'']]],
  ['class_3a_20tt_20messaging_5fserver_20tt_54',['Class: &lt;tt&gt;messaging_server&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md224',1,'']]],
  ['class_3a_20tt_20pipeline_5fbuilder_20tt_55',['Class: &lt;tt&gt;pipeline_builder&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md102',1,'']]],
  ['class_3a_20tt_20publisher_20tt_56',['Class: &lt;tt&gt;publisher&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md30',1,'']]],
  ['class_3a_20tt_20request_5fclient_20tt_57',['Class: &lt;tt&gt;request_client&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md53',1,'']]],
  ['class_3a_20tt_20request_5freply_5fhandler_20tt_58',['Class: &lt;tt&gt;request_reply_handler&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md47',1,'']]],
  ['class_3a_20tt_20request_5fserver_20tt_59',['Class: &lt;tt&gt;request_server&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md58',1,'']]],
  ['class_3a_20tt_20service_5fcontainer_20tt_60',['Class: &lt;tt&gt;service_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md257',1,'']]],
  ['class_3a_20tt_20subscriber_20tt_61',['Class: &lt;tt&gt;subscriber&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md38',1,'']]],
  ['class_3a_20tt_20thread_5fpool_20tt_62',['Class: &lt;tt&gt;thread_pool&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md264',1,'']]],
  ['class_3a_20tt_20value_5fcontainer_20tt_63',['Class: &lt;tt&gt;value_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md210',1,'']]],
  ['class_3a_20tt_20variant_20tt_64',['Class: &lt;tt&gt;variant&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md218',1,'']]],
  ['classes_65',['Classes',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1139',1,'']]],
  ['clear_5fbuffer_20tt_66',['&lt;tt&gt;clear_buffer&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md77',1,'']]],
  ['client_67',['client',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md882',1,'3. Test with Sample Client'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1883',1,'5.1 Task Client']]],
  ['client_20async_20result_20✅_68',['Sprint 4: Client &amp; Async Result ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1898',1,'']]],
  ['client_20producer_69',['Phase 5: Task Client (Producer)',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1882',1,'']]],
  ['client_20server_70',['3. Network Client/Server',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md874',1,'']]],
  ['clion_71',['CLion',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md729',1,'']]],
  ['clone_20and_20setup_72',['1. Clone and Setup',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md723',1,'']]],
  ['clone_20repository_73',['1. Clone Repository',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md641',1,'']]],
  ['clone_20the_20repository_74',['1. Clone the Repository',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md862',1,'']]],
  ['cmake_20configuration_75',['CMake Configuration',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md763',1,'']]],
  ['cmake_20integration_76',['CMake Integration',['../index.html#autotoc_md958',1,'']]],
  ['cmake_20structure_77',['CMake Structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1126',1,'']]],
  ['cmakelists_20txt_78',['Update CMakeLists.txt',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md813',1,'']]],
  ['code_79',['code',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1134',1,'Application Code'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md728',1,'Visual Studio Code']]],
  ['code_20at_20once_80',['Q: Do I need to migrate all code at once?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md844',1,'']]],
  ['code_20conflicts_81',['Issue: Error code conflicts',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md837',1,'']]],
  ['code_20documentation_82',['Code Documentation',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md741',1,'']]],
  ['code_20examples_83',['Code Examples',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md829',1,'']]],
  ['code_20of_20conduct_84',['Code of Conduct',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md497',1,'']]],
  ['code_20organization_20principles_85',['Code Organization Principles',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1142',1,'']]],
  ['code_20quality_86',['Code Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1045',1,'']]],
  ['code_20range_87',['2. Error Code Range',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md806',1,'']]],
  ['code_20review_20checklist_88',['Code Review Checklist',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md761',1,'']]],
  ['code_20reviews_89',['Code Reviews',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1048',1,'']]],
  ['codes_90',['codes',['../da/db6/md_docs_2FEATURES.html#autotoc_md552',1,'Error Codes'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md283',1,'Error Codes'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md284',1,'System Error Codes']]],
  ['coding_20standards_91',['coding standards',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md735',1,'Coding Standards'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md505',1,'Coding Standards']]],
  ['collection_92',['collection',['../d2/d64/md_docs_2architecture.html#autotoc_md347',1,'Metrics Collection'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md160',1,'Metrics Collection']]],
  ['combining_20patterns_93',['Combining Patterns',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1697',1,'']]],
  ['command_20pattern_94',['12. Command Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md16',1,'']]],
  ['commands_95',['Benchmark Commands',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md986',1,'']]],
  ['comment_20guidelines_96',['Comment Guidelines',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md742',1,'']]],
  ['commit_20message_20format_97',['Commit Message Format',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md760',1,'']]],
  ['common_20bottlenecks_98',['Common Bottlenecks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md427',1,'']]],
  ['common_20build_20issues_20and_20solutions_99',['Common Build Issues and Solutions',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md601',1,'']]],
  ['common_20issues_100',['common issues',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1798',1,'Common Issues'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md713',1,'Common Issues'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md772',1,'Troubleshooting Common Issues']]],
  ['common_20migration_20issues_101',['Common Migration Issues',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1606',1,'']]],
  ['common_20performance_20problems_102',['1. Common Performance Problems',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1031',1,'']]],
  ['common_20problems_103',['Common Problems',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md948',1,'']]],
  ['communication_104',['communication',['../d2/d64/md_docs_2architecture.html#autotoc_md335',1,'Internal Communication'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md148',1,'Internal Communication'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md770',1,'Secure Communication']]],
  ['communication_20modules_105',['Data &amp; Communication Modules',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1175',1,'']]],
  ['community_106',['4. Community',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md887',1,'']]],
  ['comparison_107',['comparison',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md437',1,'Feature Comparison'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1003',1,'Lock-free vs Mutex Comparison'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md181',1,'Performance Comparison']]],
  ['comparison_20with_20other_20systems_108',['Comparison with Other Systems',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md436',1,'']]],
  ['compatibility_109',['Compatibility',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md802',1,'']]],
  ['compilation_20errors_20with_20old_20includes_110',['Issue: Compilation errors with old includes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md836',1,'']]],
  ['complete_111',['complete',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1922',1,'✅ Core Components (Complete)'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1926',1,'✅ Documentation (Complete)'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1924',1,'✅ Infrastructure (Complete)'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1923',1,'✅ Patterns (Complete)'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1925',1,'✅ Testing &amp; Benchmarks (Complete)']]],
  ['complete_20example_112',['Complete Example',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1769',1,'']]],
  ['compliance_113',['compliance',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1075',1,'Compliance'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md709',1,'Compliance']]],
  ['component_20access_114',['Component Access',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1309',1,'']]],
  ['component_20architecture_115',['component architecture',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md134',1,'Component Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md321',1,'Component Architecture']]],
  ['component_20documentation_116',['🧩 Component Documentation',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1173',1,'']]],
  ['component_20memory_20overhead_117',['Per-Component Memory Overhead',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md414',1,'']]],
  ['component_20organization_118',['Component Organization',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1119',1,'']]],
  ['component_20performance_119',['Component Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1001',1,'']]],
  ['component_20specific_20architecture_120',['Component-Specific Architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md316',1,'']]],
  ['components_121',['components',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1438',1,'Core Components'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1907',1,'Reusing Existing Components']]],
  ['components_20complete_122',['✅ Core Components (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1922',1,'']]],
  ['components_20tt_20include_20kcenon_20messaging_20core_20tt_123',['Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1120',1,'']]],
  ['compose_20deployment_124',['Docker Compose Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md666',1,'']]],
  ['composite_20pattern_125',['8. Composite Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md11',1,'']]],
  ['concept_126',['concept',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1656',1,'Concept'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1649',1,'Concept']]],
  ['concepts_127',['Mapping Concepts',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1593',1,'']]],
  ['concerns_128',['Separation of Concerns',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1143',1,'']]],
  ['conclusion_129',['conclusion',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1091',1,'Conclusion'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md203',1,'Conclusion'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md439',1,'Conclusion']]],
  ['concurrency_130',['concurrency',['../d2/d64/md_docs_2architecture.html#autotoc_md338',1,'Concurrency'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md151',1,'Concurrency']]],
  ['concurrency_20patterns_131',['Concurrency Patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md18',1,'']]],
  ['concurrency_20settings_132',['Concurrency Settings',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1508',1,'']]],
  ['concurrent_20request_20performance_133',['Concurrent Request Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md411',1,'']]],
  ['conditional_20integration_20tests_134',['3. Conditional Integration Tests',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md190',1,'']]],
  ['conduct_135',['Code of Conduct',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md497',1,'']]],
  ['configmap_136',['Namespace and ConfigMap',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md662',1,'']]],
  ['configuration_137',['configuration',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1027',1,'1. Thread Configuration'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1028',1,'2. Memory Configuration'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1029',1,'3. Network Configuration'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md763',1,'CMake Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md650',1,'Configuration'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1239',1,'Configuration'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1248',1,'Configuration'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1306',1,'Configuration'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md278',1,'Configuration'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1061',1,'Configuration'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md237',1,'Configuration'],['../index.html#autotoc_md966',1,'Custom Configuration'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1663',1,'Default Configuration'],['../d2/d64/md_docs_2architecture.html#autotoc_md352',1,'Dynamic Configuration'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md165',1,'Dynamic Configuration'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md877',1,'Environment Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md660',1,'HAProxy Configuration'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1524',1,'High Throughput Configuration'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md727',1,'IDE Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md688',1,'Load Balancer Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md683',1,'Logging Configuration'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1947',1,'Logging Configuration'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1527',1,'Long-Running Tasks Configuration'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1525',1,'Low Latency Configuration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1608',1,'Missing Queue Configuration'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1502',1,'Persistence Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md676',1,'PostgreSQL Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md680',1,'Prometheus Configuration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md546',1,'Queue Configuration'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1526',1,'Resource-Constrained Configuration'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md897',1,'Runtime Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md705',1,'SSL/TLS Configuration'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md164',1,'Static Configuration'],['../d2/d64/md_docs_2architecture.html#autotoc_md351',1,'Static Configuration'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1512',1,'Task Configuration'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1499',1,'Task Queue Configuration'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1494',1,'Task System Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md672',1,'Thread Pool Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md670',1,'ulimit Configuration'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1505',1,'Worker Pool Configuration']]],
  ['configuration_20file_138',['Basic Configuration File',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md878',1,'']]],
  ['configuration_20file_20format_139',['System Configuration File Format',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md288',1,'']]],
  ['configuration_20file_20structure_140',['Configuration File Structure',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md651',1,'']]],
  ['configuration_20guide_141',['Task Module Configuration Guide',['../dc/d1e/md_docs_2task_2CONFIGURATION.html',1,'']]],
  ['configuration_20management_142',['configuration management',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md163',1,'Configuration Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md350',1,'Configuration Management']]],
  ['configuration_20methods_143',['Configuration Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1206',1,'']]],
  ['configuration_20migration_144',['Configuration Migration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1585',1,'']]],
  ['configuration_20options_145',['Configuration Options',['../index.html#autotoc_md971',1,'']]],
  ['configuration_20questions_146',['Configuration Questions',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md894',1,'']]],
  ['configuration_20recommendations_147',['Configuration Recommendations',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1530',1,'']]],
  ['configuration_20reference_148',['Configuration Reference',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md287',1,'']]],
  ['configuration_20structure_149',['Configuration Structure',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md247',1,'']]],
  ['configuration_2emd_150',['CONFIGURATION.md',['../db/daf/CONFIGURATION_8md.html',1,'']]],
  ['configuration_5fko_2emd_151',['CONFIGURATION_KO.md',['../d1/d79/CONFIGURATION__KO_8md.html',1,'']]],
  ['configure_20build_152',['2. Configure Build',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md642',1,'']]],
  ['configure_20the_20task_20system_153',['2. Create and Configure the Task System',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1764',1,'']]],
  ['conflicts_154',['conflicts',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md602',1,'Issue 1: Target Name Conflicts'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md837',1,'Issue: Error code conflicts']]],
  ['connection_20drops_155',['Problem: Connection Drops',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md951',1,'']]],
  ['connection_20errors_156',['Connection Errors',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md939',1,'']]],
  ['connection_20failed_157',['&quot;Database connection failed&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md943',1,'']]],
  ['connection_20management_158',['Connection Management',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md238',1,'']]],
  ['connection_20pool_20exhaustion_159',['Issue 3: Database Connection Pool Exhaustion',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md935',1,'']]],
  ['connection_20pool_20impact_160',['Connection Pool Impact',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1013',1,'']]],
  ['connection_20pool_20tuning_161',['Connection Pool Tuning',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md677',1,'']]],
  ['connection_20refused_162',['&quot;Connection refused&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md940',1,'']]],
  ['connection_20scaling_163',['Connection Scaling',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1009',1,'']]],
  ['connection_20timeout_164',['&quot;Connection timeout&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md941',1,'']]],
  ['connections_165',['Issue 2: Memory Leak in Long-Running Connections',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md934',1,'']]],
  ['connectivity_166',['Test Connectivity',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md910',1,'']]],
  ['consideration_167',['Priority 3 (Future Consideration)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md198',1,'']]],
  ['considerations_168',['considerations',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md169',1,'Future Considerations'],['../d2/d64/md_docs_2architecture.html#autotoc_md356',1,'Future Considerations'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md129',1,'Performance Considerations'],['../d2/d64/md_docs_2architecture.html#autotoc_md343',1,'Security Considerations'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md156',1,'Security Considerations']]],
  ['constants_169',['Event Type Constants',['../index.html#autotoc_md972',1,'']]],
  ['constrained_20configuration_170',['Resource-Constrained Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1526',1,'']]],
  ['constructor_171',['constructor',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1256',1,'Constructor'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1307',1,'Constructor'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1277',1,'Constructor'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1282',1,'Constructor'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1298',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md31',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md39',1,'Constructor'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1240',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md48',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md54',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md59',1,'Constructor'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1217',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md69',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md80',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md92',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md103',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md211',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md225',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md229',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md236',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md246',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md265',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md271',1,'Constructor']]],
  ['constructors_172',['Constructors',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1203',1,'']]],
  ['consumer_20pattern_173',['14. Producer-Consumer Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md19',1,'']]],
  ['contact_20support_174',['📬 Contact &amp; Support',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1974',1,'']]],
  ['container_175',['DI Container',['../da/db6/md_docs_2FEATURES.html#autotoc_md549',1,'']]],
  ['container_20api_176',['Service Container API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md255',1,'']]],
  ['container_20based_20data_20handling_177',['2. Container-Based Data Handling',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md873',1,'']]],
  ['container_20deployment_178',['container deployment',['../d2/d64/md_docs_2architecture.html#autotoc_md354',1,'Container Deployment'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md167',1,'Container Deployment']]],
  ['container_20system_179',['container system',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md135',1,'1. Container System'],['../d2/d64/md_docs_2architecture.html#autotoc_md322',1,'1. Container System']]],
  ['container_20system_20api_180',['Container System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md208',1,'']]],
  ['container_20system_20integration_181',['Container System Integration',['../da/db6/md_docs_2FEATURES.html#autotoc_md559',1,'']]],
  ['container_20system_20performance_182',['Container System Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1005',1,'']]],
  ['container_5fmodule_20tt_183',['Namespace: &lt;tt&gt;container_module&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md209',1,'']]],
  ['contention_20performance_184',['Queue Contention Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md399',1,'']]],
  ['contents_185',['contents',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md890',1,'Table of Contents'],['../da/db6/md_docs_2FEATURES.html#autotoc_md517',1,'Table of Contents'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md26',1,'Table of Contents'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md495',1,'Table of Contents'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1580',1,'Table of Contents'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md389',1,'Table of Contents'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md992',1,'Table of Contents'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md798',1,'Table of Contents'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md856',1,'Table of Contents'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1646',1,'Table of Contents'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1198',1,'Table of Contents'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1492',1,'Table of Contents'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md206',1,'Table of Contents'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1796',1,'Table of Contents']]],
  ['continuous_20performance_20monitoring_186',['Continuous Performance Monitoring',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md434',1,'']]],
  ['contribute_187',['How to Contribute',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1969',1,'']]],
  ['contributing_188',['🤝 Contributing',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1968',1,'']]],
  ['contributing_20guidelines_189',['Contributing Guidelines',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md758',1,'']]],
  ['contributing_20to_20messaging_20system_190',['Contributing to Messaging System',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_191',['CONTRIBUTING.md',['../d2/d52/CONTRIBUTING_8md.html',1,'']]],
  ['control_192',['Task Control',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1269',1,'']]],
  ['convenience_193',['convenience',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1310',1,'Handler Registration (Convenience)'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1312',1,'Scheduling (Convenience)'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1311',1,'Task Submission (Convenience)']]],
  ['conventions_194',['conventions',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md737',1,'Naming Conventions'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1137',1,'Naming Conventions']]],
  ['core_20기반_20확장_195',['Phase 1: Task Core (기반 확장)',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1866',1,'']]],
  ['core_20components_196',['Core Components',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1438',1,'']]],
  ['core_20components_20complete_197',['✅ Core Components (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1922',1,'']]],
  ['core_20components_20tt_20include_20kcenon_20messaging_20core_20tt_198',['Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1120',1,'']]],
  ['core_20documentation_199',['Core Documentation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1960',1,'']]],
  ['core_20dumps_200',['Debug Core Dumps',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md902',1,'']]],
  ['core_20infrastructure_201',['Core Infrastructure',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1174',1,'']]],
  ['core_20messaging_202',['Core Messaging',['../da/db6/md_docs_2FEATURES.html#autotoc_md519',1,'']]],
  ['core_20methods_203',['Core Methods',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md212',1,'']]],
  ['core_20performance_20metrics_204',['Core Performance Metrics',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md391',1,'']]],
  ['core_20task_20infrastructure_20✅_205',['Sprint 1: Core Task Infrastructure ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1895',1,'']]],
  ['core_20tt_206',['Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1120',1,'']]],
  ['count_20impact_207',['Subscription Count Impact',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md403',1,'']]],
  ['coverage_208',['coverage',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1042',1,'Test Coverage'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md746',1,'Test Coverage']]],
  ['coverage_20report_209',['Coverage Report',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1957',1,'']]],
  ['cpp_210',['1. Chat Server (chat_server.cpp)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md880',1,'']]],
  ['cpp_20not_20found_211',['Issue 4: yaml-cpp Not Found',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md608',1,'']]],
  ['cpu_20사용량_212',['높은 CPU 사용량',['../de/da3/md_docs_2task_2TROUBLESHOOTING__KO.html#autotoc_md1847',1,'']]],
  ['cpu_20bottlenecks_213',['Identify CPU Bottlenecks',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md921',1,'']]],
  ['cpu_20optimization_214',['cpu optimization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1018',1,'2. CPU Optimization'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md920',1,'CPU Optimization']]],
  ['cpu_20usage_215',['cpu usage',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1813',1,'High CPU Usage'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1032',1,'High CPU Usage']]],
  ['cpu_20usage_20with_20small_20messages_216',['Issue 1: High CPU Usage with Small Messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md933',1,'']]],
  ['create_20a_20message_20bus_217',['Q: How do I create a message bus?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md788',1,'']]],
  ['create_20and_20configure_20the_20task_20system_218',['2. Create and Configure the Task System',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1764',1,'']]],
  ['create_5fenrichment_5fstage_20tt_219',['&lt;tt&gt;create_enrichment_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md114',1,'']]],
  ['create_5flogging_5fstage_20tt_220',['&lt;tt&gt;create_logging_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md112',1,'']]],
  ['create_5fretry_5fstage_20tt_221',['&lt;tt&gt;create_retry_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md115',1,'']]],
  ['create_5fvalidation_5fstage_20tt_222',['&lt;tt&gt;create_validation_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md113',1,'']]],
  ['creating_20new_20modules_223',['Creating New Modules',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md764',1,'']]],
  ['creation_224',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md816',1,'']]],
  ['creation_20benchmarks_225',['Message Creation Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md394',1,'']]],
  ['creational_20patterns_226',['Creational Patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md2',1,'']]],
  ['cron_227',['cron',['../d7/d10/md_docs_2task_2MIGRATION__KO.html#autotoc_md1629',1,'이전 (시스템 Cron)'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1596',1,'Before (System Cron)']]],
  ['cron_20기반_20스케줄링_228',['Cron 기반 스케줄링',['../dd/d35/md_docs_2task_2PATTERNS__KO.html#autotoc_md1735',1,'']]],
  ['cron_20기반_20실행_229',['Cron 기반 실행',['../da/dee/md_docs_2task_2QUICK__START__KO.html#autotoc_md1791',1,'']]],
  ['cron_20작업에서_20마이그레이션_230',['Cron 작업에서 마이그레이션',['../d7/d10/md_docs_2task_2MIGRATION__KO.html#autotoc_md1628',1,'']]],
  ['cron_20표현식_20형식_231',['cron 표현식 형식',['../dd/d35/md_docs_2task_2PATTERNS__KO.html#autotoc_md1736',1,'Cron 표현식 형식'],['../dd/db9/md_docs_2task_2API__REFERENCE__KO.html#autotoc_md1409',1,'Cron 표현식 형식']]],
  ['cron_20based_20execution_232',['Cron-based Execution',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1773',1,'']]],
  ['cron_20based_20scheduling_233',['Cron-Based Scheduling',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1678',1,'']]],
  ['cron_20expression_20format_234',['cron expression format',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1679',1,'Cron Expression Format'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1290',1,'Cron Expression Format']]],
  ['cron_20jobs_235',['From Cron Jobs',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1595',1,'']]],
  ['cron_5fparser_236',['cron_parser',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1289',1,'cron_parser'],['../dd/db9/md_docs_2task_2API__REFERENCE__KO.html#autotoc_md1408',1,'cron_parser']]],
  ['ctest_20parallel_20execution_20✅_237',['2. CTest Parallel Execution ✅',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md179',1,'']]],
  ['current_20limitations_238',['Current Limitations',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1079',1,'']]],
  ['custom_20allocators_239',['Custom Allocators',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1017',1,'']]],
  ['custom_20build_20options_240',['Custom Build Options',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md869',1,'']]],
  ['custom_20configuration_241',['Custom Configuration',['../index.html#autotoc_md966',1,'']]],
  ['custom_20image_242',['Build Custom Image',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md649',1,'']]],
  ['custom_20result_20backend_243',['Custom Result Backend',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1454',1,'']]],
  ['custom_20retry_20logic_244',['Custom Retry Logic',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1666',1,'']]],
  ['custom_20solutions_245',['Migration from Custom Solutions',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1587',1,'']]],
  ['custom_20task_20handler_246',['Custom Task Handler',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1455',1,'']]],
  ['custom_20thread_20pool_247',['Before (Custom Thread Pool)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1589',1,'']]]
];
