var searchData=
[
  ['a_20advanced_20build_20guide_0',['A. Advanced Build Guide',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1195',1,'']]],
  ['a_20error_20code_20mapping_1',['A. Error Code Mapping',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md447',1,'']]],
  ['a_3a_20local_20development_20recommended_20for_20contributors_2',['Option A: Local Development (Recommended for Contributors)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1136',1,'']]],
  ['about_20performance_3',['Q: What about performance?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md500',1,'']]],
  ['actions_20matrix_4',['GitHub Actions Matrix',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md675',1,'']]],
  ['adapter_20pattern_5',['5. Adapter Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md259',1,'']]],
  ['add_20messaging_5fsystem_20error_20codes_20to_20common_5fsystem_6',['1.1 Add messaging_system Error Codes to common_system',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md391',1,'']]],
  ['add_5ffilter_20tt_7',['&lt;tt&gt;add_filter&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md592',1,'']]],
  ['add_5fstage_20tt_8',['add_stage tt',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md579',1,'&lt;tt&gt;add_stage&lt;/tt&gt;'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md591',1,'&lt;tt&gt;add_stage&lt;/tt&gt;']]],
  ['add_5ftransformer_20tt_9',['&lt;tt&gt;add_transformer&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md593',1,'']]],
  ['adding_20values_10',['Adding Values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md9',1,'']]],
  ['additional_20documentation_11',['Additional Documentation',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md934',1,'']]],
  ['additional_20resources_12',['Additional Resources',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md506',1,'']]],
  ['address_20sanitizer_13',['Address Sanitizer',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md851',1,'']]],
  ['addresssanitizer_14',['addresssanitizer',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md308',1,'Using AddressSanitizer'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1058',1,'Using AddressSanitizer']]],
  ['administrators_15',['For System Administrators',['../index.html#autotoc_md957',1,'']]],
  ['advanced_20build_20guide_16',['A. Advanced Build Guide',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1195',1,'']]],
  ['advanced_20features_17',['2. Advanced Features',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md362',1,'']]],
  ['after_20iexecutor_20based_18',['After (IExecutor-based)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md719',1,'']]],
  ['after_20ilogger_19',['After (ILogger)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md725',1,'']]],
  ['after_20result_20based_20',['After (Result-based)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md716',1,'']]],
  ['after_20value_5fcontainer_21',['After (value_container)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md722',1,'']]],
  ['aggregation_20elk_20stack_22',['Log Aggregation (ELK Stack)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md216',1,'']]],
  ['aliases_23',['Type Aliases',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md574',1,'']]],
  ['all_20code_20at_20once_24',['Q: Do I need to migrate all code at once?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md499',1,'']]],
  ['allocation_25',['allocation',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md222',1,'Resource Allocation'],['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md695',1,'System Error Code Allocation']]],
  ['allocators_26',['Custom Allocators',['../df/d94/md_docs_2performance.html#autotoc_md641',1,'']]],
  ['already_20created_20in_20phase_200_27',['CMakePresets.json (Already created in Phase 0)',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md792',1,'']]],
  ['alternative_3a_20minimal_20build_20no_20external_20systems_28',['Alternative: Minimal Build (No External Systems)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md145',1,'']]],
  ['analysis_29',['analysis',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md371',1,'Current State Analysis'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1080',1,'Disk I/O Analysis'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1077',1,'Memory Usage Analysis'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1083',1,'Network Analysis'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1065',1,'Thread Analysis']]],
  ['and_20architectural_20decisions_30',['Design Patterns and Architectural Decisions',['../d5/dca/md_docs_2DESIGN__PATTERNS.html',1,'']]],
  ['and_20benchmarks_31',['C. Testing and Benchmarks',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1205',1,'']]],
  ['and_20broker_20week_203_32',['Phase 3: Message Queue and Broker (Week 3)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md396',1,'']]],
  ['and_20configmap_33',['Namespace and ConfigMap',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md193',1,'']]],
  ['and_20dependency_20refactoring_20design_20document_34',['Phase 1: Build System and Dependency Refactoring - Design Document',['../d5/d7c/md_docs_2phase1_2DESIGN.html',1,'']]],
  ['and_20deployment_20design_20document_35',['Phase 4: Validation and Deployment - Design Document',['../db/d5d/md_docs_2phase4_2DESIGN.html',1,'']]],
  ['and_20documentation_20weeks_209_2010_20🔄_20in_20progress_36',['Phase 9-10: Testing and Documentation (Weeks 9-10) - 🔄 IN PROGRESS',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md433',1,'']]],
  ['and_20error_20codes_20week_201_37',['Phase 1: Foundation and Error Codes (Week 1)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md390',1,'']]],
  ['and_20external_20integration_20✅_38',['Phase 1: Build System and External Integration ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md913',1,'']]],
  ['and_20feature_20flags_39',['Task 1.2: Compiler Options and Feature Flags',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md790',1,'']]],
  ['and_20future_20work_40',['Known Limitations and Future Work',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md939',1,'']]],
  ['and_20ingress_41',['Service and Ingress',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md195',1,'']]],
  ['and_20install_42',['3. Build and Install',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md174',1,'']]],
  ['and_20linting_43',['B. Code Quality and Linting',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1199',1,'']]],
  ['and_20milestones_44',['Timeline and Milestones',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md424',1,'']]],
  ['and_20monitoring_20task_203_203_45',['3. Tracing and Monitoring (Task 3.3)',['../d7/de1/md_docs_2phase3_2DESIGN.html#autotoc_md837',1,'']]],
  ['and_20observability_46',['and observability',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1029',1,'Monitoring and Observability'],['../d2/d64/md_docs_2architecture.html#autotoc_md118',1,'Monitoring and Observability']]],
  ['and_20pipelining_47',['Batching and Pipelining',['../df/d94/md_docs_2performance.html#autotoc_md646',1,'']]],
  ['and_20preparation_20✅_48',['Phase 0: Foundation and Preparation ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md911',1,'']]],
  ['and_20profiling_49',['Tracing and Profiling',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1068',1,'']]],
  ['and_20pub_20sub_20week_205_50',['Phase 5: Topic Router and Pub/Sub (Week 5)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md403',1,'']]],
  ['and_20recovery_51',['Backup and Recovery',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md226',1,'']]],
  ['and_20risk_20assessment_52',['Migration Strategy and Risk Assessment',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html',1,'']]],
  ['and_20run_53',['2. Build and Run',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md358',1,'']]],
  ['and_20setup_54',['1. Clone and Setup',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md279',1,'']]],
  ['and_20solutions_55',['Common Build Issues and Solutions',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md132',1,'']]],
  ['and_20v2_200_20together_56',['Q: Can I use v1.x and v2.0 together?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md498',1,'']]],
  ['ansible_20rollback_20playbook_57',['Ansible Rollback Playbook',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md764',1,'']]],
  ['any_20runtime_20dependencies_58',['Q: Are there any runtime dependencies?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md501',1,'']]],
  ['api_59',['api',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md3',1,'Container System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md28',1,'Database System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md70',1,'Logger System API'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md480',1,'Message API'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md481',1,'Message Bus API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md38',1,'Message Bus API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md17',1,'Network System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md50',1,'Service Container API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md57',1,'Thread System API'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md482',1,'Topic Router API']]],
  ['api_20문서화_60',['**Task 4.2 – 마이그레이션 가이드 및 API 문서화**',['../d7/d01/md_docs_2REBUILD__PLAN.html#autotoc_md991',1,'']]],
  ['api_20changes_61',['api changes',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md742',1,'3. Container API Changes'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md479',1,'API Changes']]],
  ['api_20reference_62',['api reference',['../db/d91/md_docs_2API__REFERENCE.html',1,'API Reference'],['../dc/d3e/md_docs_2PATTERNS__API.html',1,'Messaging Patterns API Reference']]],
  ['api_20transformation_63',['Container API Transformation',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md720',1,'']]],
  ['api_20wrapper_64',['Legacy API Wrapper',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md744',1,'']]],
  ['api_5freference_2emd_65',['API_REFERENCE.md',['../d2/dff/API__REFERENCE_8md.html',1,'']]],
  ['appendix_66',['appendix',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1194',1,'📋 Appendix'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md446',1,'Appendix']]],
  ['application_67',['application',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md281',1,'3. Your First Application'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md356',1,'First Application'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1140',1,'Step 3: Run Your Application']]],
  ['application_20health_68',['Application Health',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md249',1,'']]],
  ['application_20layer_69',['application layer',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1177',1,'Application Layer'],['../index.html#autotoc_md961',1,'Application Layer']]],
  ['application_20security_70',['application security',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md237',1,'Application Security'],['../d2/d64/md_docs_2architecture.html#autotoc_md117',1,'Application Security'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1028',1,'Application Security']]],
  ['application_20state_20backup_71',['Application State Backup',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md228',1,'']]],
  ['application_20tracing_72',['Application Tracing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1071',1,'']]],
  ['application_20tuning_73',['Application Tuning',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md202',1,'']]],
  ['applications_74',['1. Explore Sample Applications',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md361',1,'']]],
  ['apt_20repository_20ubuntu_20debian_75',['APT Repository (Ubuntu/Debian)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md176',1,'']]],
  ['architectural_20decisions_76',['Design Patterns and Architectural Decisions',['../d5/dca/md_docs_2DESIGN__PATTERNS.html',1,'']]],
  ['architectural_20patterns_77',['architectural patterns',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md378',1,'3. Missing Architectural Patterns'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md272',1,'Architectural Patterns']]],
  ['architectural_20principles_78',['architectural principles',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1002',1,'Architectural Principles'],['../d2/d64/md_docs_2architecture.html#autotoc_md91',1,'Architectural Principles']]],
  ['architecture_79',['architecture',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1129',1,'🏗️ System Architecture'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md274',1,'17. Event-Driven Architecture'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md190',1,'Architecture'],['../d2/d64/md_docs_2architecture.html',1,'Architecture'],['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md845',1,'Architecture'],['../d7/de1/md_docs_2phase3_2DESIGN.html#autotoc_md833',1,'Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1004',1,'Component Architecture'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md387',1,'Component Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md93',1,'Component Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md88',1,'Component-Specific Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1009',1,'Data Flow Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md98',1,'Data Flow Architecture'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1119',1,'Dependency Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md125',1,'Deployment Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1036',1,'Deployment Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md101',1,'Distributed Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1012',1,'Distributed Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html',1,'System Architecture'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md385',1,'Target Architecture'],['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md923',1,'Technical Architecture'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md751',1,'v2.0 (New Architecture)'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md824',1,'Week 3: DI Architecture']]],
  ['architecture_20diagram_80',['Architecture Diagram',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md786',1,'']]],
  ['architecture_2emd_81',['architecture.md',['../df/d97/architecture_8md.html',1,'']]],
  ['archive_20directory_20structure_82',['Archive Directory Structure',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md727',1,'']]],
  ['archive_20script_83',['Archive Script',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md728',1,'']]],
  ['archive_20strategy_84',['Archive Strategy',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md726',1,'']]],
  ['are_20there_20any_20runtime_20dependencies_85',['Q: Are there any runtime dependencies?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md501',1,'']]],
  ['areas_86',['Contribution Areas',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1181',1,'']]],
  ['artifacts_20task_204_205_87',['6. Deployment Artifacts (Task 4.5)',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md857',1,'']]],
  ['as_20fetchcontent_88',['As FetchContent',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1167',1,'']]],
  ['as_20installed_20package_89',['As Installed Package',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1168',1,'']]],
  ['as_20subdirectory_90',['As Subdirectory',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1166',1,'']]],
  ['assessment_91',['assessment',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html',1,'Migration Strategy and Risk Assessment'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md441',1,'Risk Assessment']]],
  ['async_20execution_20transformation_92',['Async Execution Transformation',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md717',1,'']]],
  ['at_20once_93',['Q: Do I need to migrate all code at once?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md499',1,'']]],
  ['attach_20to_20running_20process_94',['Attach to Running Process',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1054',1,'']]],
  ['audit_20logging_95',['Audit Logging',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md241',1,'']]],
  ['authentication_96',['Authentication',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md238',1,'']]],
  ['auto_20scaling_20rules_97',['Auto-scaling Rules',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md220',1,'']]],
  ['automatic_20fetchcontent_20easiest_20for_20new_20users_98',['Option B: Automatic FetchContent (Easiest for New Users)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1137',1,'']]],
  ['autoscaler_99',['Horizontal Pod Autoscaler',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md196',1,'']]],
  ['availability_100',['availability',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1025',1,'High Availability'],['../d2/d64/md_docs_2architecture.html#autotoc_md114',1,'High Availability']]],
  ['availability_20deployment_101',['High Availability Deployment',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md189',1,'']]],
  ['available_20build_20presets_102',['Available Build Presets',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1196',1,'']]],
  ['available_20documentation_103',['Available Documentation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1174',1,'']]]
];
