var searchData=
[
  ['s_20included_0',['📦 What&apos;s Included',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1989',1,'']]],
  ['safety_1',['safety',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1106',1,'Memory Safety'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1514',1,'Thread Safety'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md186',1,'Thread Safety'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1126',1,'Thread Safety']]],
  ['sample_20applications_2',['1. Explore Sample Applications',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md943',1,'']]],
  ['sample_20client_3',['3. Test with Sample Client',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md941',1,'']]],
  ['saving_20checkpoints_4',['Saving Checkpoints',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1757',1,'']]],
  ['scalability_5',['scalability',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md480',1,'Scalability'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1122',1,'Scalability']]],
  ['scalability_20patterns_6',['scalability patterns',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md202',1,'Scalability Patterns'],['../d2/d64/md_docs_2architecture.html#autotoc_md389',1,'Scalability Patterns']]],
  ['scale_7',['By Scale',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1600',1,'']]],
  ['scaling_8',['scaling',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1068',1,'Connection Scaling'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md751',1,'Database Scaling'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md746',1,'Horizontal Scaling'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md203',1,'Horizontal Scaling'],['../d2/d64/md_docs_2architecture.html#autotoc_md390',1,'Horizontal Scaling'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md474',1,'Memory Scaling'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md482',1,'Publisher/Subscriber Scaling'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md481',1,'Thread Scaling'],['../d2/d64/md_docs_2architecture.html#autotoc_md391',1,'Vertical Scaling'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md749',1,'Vertical Scaling'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md204',1,'Vertical Scaling']]],
  ['scaling_20characteristics_9',['Scaling Characteristics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1063',1,'']]],
  ['scaling_20rules_10',['Auto-scaling Rules',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md748',1,'']]],
  ['scaling_20strategies_11',['Scaling Strategies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md745',1,'']]],
  ['scenarios_12',['Deployment Scenarios',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md715',1,'']]],
  ['schedule_20management_13',['Schedule Management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1346',1,'']]],
  ['schedule_20registration_14',['Schedule Registration',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1345',1,'']]],
  ['scheduled_20chord_15',['Scheduled Chord',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1767',1,'']]],
  ['scheduled_20tasks_16',['Scheduled Tasks',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1744',1,'']]],
  ['scheduler_17',['scheduler',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1954',1,'6.1 Periodic Task Scheduler'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1665',1,'After (Task Scheduler)'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1953',1,'Phase 6: Scheduler']]],
  ['scheduler_20✅_18',['Sprint 5: Scheduler ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1967',1,'']]],
  ['schedules_19',['Managing Schedules',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1748',1,'']]],
  ['scheduling_20',['Cron-Based Scheduling',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1746',1,'']]],
  ['scheduling_20convenience_21',['Scheduling (Convenience)',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1374',1,'']]],
  ['scheduling_20tasks_22',['Scheduling Tasks',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1839',1,'']]],
  ['secrets_23',['Using Kubernetes Secrets',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md714',1,'']]],
  ['secrets_20management_24',['Secrets Management',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md712',1,'']]],
  ['secure_20communication_25',['Secure Communication',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md829',1,'']]],
  ['security_26',['security',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md217',1,'Application Security'],['../d2/d64/md_docs_2architecture.html#autotoc_md404',1,'Application Security'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md765',1,'Application Security'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md762',1,'Network Security'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1124',1,'Security'],['../d2/d64/md_docs_2architecture.html#autotoc_md403',1,'Transport Security'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md216',1,'Transport Security']]],
  ['security_20best_20practices_27',['Security Best Practices',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md827',1,'']]],
  ['security_20considerations_28',['security considerations',['../d2/d64/md_docs_2architecture.html#autotoc_md402',1,'Security Considerations'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md215',1,'Security Considerations']]],
  ['security_20hardening_29',['Security Hardening',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md761',1,'']]],
  ['segmentation_20fault_30',['&quot;Segmentation fault&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1006',1,'']]],
  ['selection_20via_20templates_31',['Alternative B: Compile-time Logger Selection via Templates',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md18',1,'']]],
  ['self_20hosted_20runners_32',['1. Use Self-Hosted Runners',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md251',1,'']]],
  ['separation_20of_20concerns_33',['Separation of Concerns',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1202',1,'']]],
  ['serialization_34',['serialization',['../da/db6/md_docs_2FEATURES.html#autotoc_md597',1,'Message Serialization'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md275',1,'Serialization'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1273',1,'Serialization']]],
  ['serialization_20performance_35',['Serialization Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1065',1,'']]],
  ['server_36',['3. Network Client/Server',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md933',1,'']]],
  ['server_20chat_5fserver_20cpp_37',['1. Chat Server (chat_server.cpp)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md939',1,'']]],
  ['server_20deployment_38',['Single Server Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md716',1,'']]],
  ['service_39',['2. Implement Build Caching Service',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md252',1,'']]],
  ['service_20and_20ingress_40',['Service and Ingress',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md723',1,'']]],
  ['service_20container_20api_41',['Service Container API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md314',1,'']]],
  ['service_20lifetimes_42',['Service Lifetimes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md318',1,'']]],
  ['service_20recovery_43',['Service Recovery',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md759',1,'']]],
  ['service_20won_20t_20start_44',['service won t start',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1008',1,'Problem: Service Won&apos;t Start'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md773',1,'Service Won&apos;t Start']]],
  ['service_5fcontainer_20tt_45',['Class: &lt;tt&gt;service_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md316',1,'']]],
  ['set_5fdefault_5ftopic_20tt_46',['&lt;tt&gt;set_default_topic&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md94',1,'']]],
  ['setting_20priority_47',['Setting Priority',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1739',1,'']]],
  ['setting_20values_48',['Setting Values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md272',1,'']]],
  ['settings_49',['settings',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1576',1,'Concurrency Settings'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1571',1,'Delayed Queue Settings'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1586',1,'Environment-Specific Settings'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1578',1,'Prefetch Settings']]],
  ['setup_50',['setup',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md782',1,'1. Clone and Setup'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md922',1,'2. Platform-Specific Setup'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md785',1,'Development Setup'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md842',1,'Installation &amp; Setup'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md737',1,'Monitoring Setup'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1740',1,'Priority Queue Setup']]],
  ['sharding_51',['2. Implement Test Sharding',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md248',1,'']]],
  ['sharding_20strategy_52',['Sharding Strategy',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md753',1,'']]],
  ['short_53',['Timeout Too Short',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1677',1,'']]],
  ['short_20term_20quick_20wins_54',['Short-Term (Quick Wins)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md242',1,'']]],
  ['shut_20down_20the_20system_55',['Q: How do I gracefully shut down the system?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1894',1,'']]],
  ['simd_20optimization_20impact_56',['SIMD Optimization Impact',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1066',1,'']]],
  ['simd_20utilization_57',['SIMD Utilization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1078',1,'']]],
  ['simple_20pub_20sub_20migration_58',['Example 1: Simple Pub/Sub Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md889',1,'']]],
  ['simple_20publish_20subscribe_59',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md907',1,'']]],
  ['single_20server_20deployment_60',['Single Server Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md716',1,'']]],
  ['singleton_20pattern_61',['1. Singleton Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md62',1,'']]],
  ['slow_20message_20processing_62',['Problem: Slow Message Processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1009',1,'']]],
  ['small_20messages_63',['Issue 1: High CPU Usage with Small Messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md992',1,'']]],
  ['software_20dependencies_64',['Software Dependencies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md695',1,'']]],
  ['solutions_65',['solutions',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md660',1,'Common Build Issues and Solutions'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md236',1,'Implemented Solutions'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1655',1,'Migration from Custom Solutions']]],
  ['source_66',['From Source',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md699',1,'']]],
  ['spawning_67',['Subtask Spawning',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1760',1,'']]],
  ['spawning_20subtasks_68',['Spawning Subtasks',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1761',1,'']]],
  ['specific_20architecture_69',['Component-Specific Architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md375',1,'']]],
  ['specific_20notes_70',['Platform-Specific Notes',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md681',1,'']]],
  ['specific_20settings_71',['Environment-Specific Settings',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1586',1,'']]],
  ['specific_20setup_72',['2. Platform-Specific Setup',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md922',1,'']]],
  ['split_20test_20execution_73',['1. Split Test Execution',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md247',1,'']]],
  ['sprint_74',['Priority 2 (Recommended - Next Sprint)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md256',1,'']]],
  ['sprint_201_3a_20core_20task_20infrastructure_20✅_75',['Sprint 1: Core Task Infrastructure ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1963',1,'']]],
  ['sprint_202_3a_20queue_20result_20backend_20✅_76',['Sprint 2: Queue &amp; Result Backend ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1964',1,'']]],
  ['sprint_203_3a_20worker_20system_20✅_77',['Sprint 3: Worker System ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1965',1,'']]],
  ['sprint_204_3a_20client_20async_20result_20✅_78',['Sprint 4: Client &amp; Async Result ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1966',1,'']]],
  ['sprint_205_3a_20scheduler_20✅_79',['Sprint 5: Scheduler ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1967',1,'']]],
  ['sprint_206_3a_20monitoring_20system_20integration_80',['Sprint 6: Monitoring &amp; System Integration',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1968',1,'']]],
  ['sprint_207_3a_20testing_20documentation_81',['Sprint 7: Testing &amp; Documentation',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1969',1,'']]],
  ['src_82',['src/',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1217',1,'']]],
  ['ssl_20tls_20configuration_83',['SSL/TLS Configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md764',1,'']]],
  ['stack_84',['Log Aggregation (ELK Stack)',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md744',1,'']]],
  ['stage_5fcount_20tt_85',['&lt;tt&gt;stage_count&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md157',1,'']]],
  ['staging_20environment_86',['Staging Environment',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1588',1,'']]],
  ['standalone_20backend_87',['Standalone Backend',['../da/db6/md_docs_2FEATURES.html#autotoc_md590',1,'']]],
  ['standard_20is_20required_88',['Q: What C++ standard is required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md839',1,'']]],
  ['standards_89',['standards',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1238',1,'📖 Documentation Standards'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md564',1,'Coding Standards'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md794',1,'Coding Standards'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md799',1,'Documentation Standards'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1133',1,'Industry Standards']]],
  ['start_90',['start',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2000',1,'🚀 Quick Start'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md897',1,'Issue: Message bus doesn&apos;t start'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1008',1,'Problem: Service Won&apos;t Start'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md780',1,'Quick Start'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md930',1,'Quick Start'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md773',1,'Service Won&apos;t Start']]],
  ['start_20guide_91',['Task Module Quick Start Guide',['../d9/dff/md_docs_2task_2QUICK__START.html',1,'']]],
  ['start_20the_20system_92',['4. Start the System',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1834',1,'']]],
  ['start_20tt_20tt_20stop_20tt_93',['start tt tt stop tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md121',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md141',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md155',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;']]],
  ['started_94',['started',['../da/db6/md_docs_2FEATURES.html#autotoc_md627',1,'Getting Started'],['../d6/d63/md_docs_2guides_2QUICK__START.html',1,'Getting Started'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md558',1,'Getting Started']]],
  ['state_20backup_95',['Application State Backup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md756',1,'']]],
  ['state_20methods_96',['State Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1267',1,'']]],
  ['state_20pr_2030_20success_97',['Target State (PR #30 - Success)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md235',1,'']]],
  ['state_20pr_2031_20before_20fix_98',['Initial State (PR #31 - Before Fix)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md234',1,'']]],
  ['statement_99',['Problem Statement',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md4',1,'']]],
  ['static_20analysis_100',['Static Analysis',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1105',1,'']]],
  ['static_20configuration_101',['static configuration',['../d2/d64/md_docs_2architecture.html#autotoc_md410',1,'Static Configuration'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md223',1,'Static Configuration']]],
  ['static_20methods_102',['Static Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1355',1,'']]],
  ['statistics_103',['statistics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md968',1,'Network Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1361',1,'Queue Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1311',1,'Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1375',1,'Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1315',1,'Statistics']]],
  ['status_104',['status',['../index.html#autotoc_md55',1,'ADR Status'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1876',1,'Check Queue Status'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1877',1,'Check Worker Status'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md21',1,'Current Implementation Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1314',1,'Status'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md1',1,'Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1324',1,'Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1362',1,'Worker Status']]],
  ['status_20methods_105',['Status Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1327',1,'']]],
  ['step_201_3a_20update_20dependencies_106',['Step 1: Update Dependencies',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md871',1,'']]],
  ['step_202_3a_20update_20includes_107',['Step 2: Update Includes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md874',1,'']]],
  ['step_203_3a_20migrate_20message_20creation_108',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md875',1,'']]],
  ['step_204_3a_20migrate_20message_20bus_20usage_109',['Step 4: Migrate Message Bus Usage',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md876',1,'']]],
  ['step_205_3a_20migrate_20to_20patterns_20optional_20but_20recommended_110',['Step 5: Migrate to Patterns (Optional but Recommended)',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md877',1,'']]],
  ['step_206_3a_20update_20error_20handling_111',['Step 6: Update Error Handling',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md880',1,'']]],
  ['step_207_3a_20integration_20with_20other_20systems_112',['Step 7: Integration with Other Systems',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md881',1,'']]],
  ['step_20by_20step_20migration_113',['Step-by-Step Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md870',1,'']]],
  ['steps_114',['steps',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1844',1,'Next Steps'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md942',1,'Next Steps']]],
  ['still_20use_20simple_20publish_20subscribe_115',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md907',1,'']]],
  ['stop_20the_20system_116',['6. Stop the System',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1836',1,'']]],
  ['stop_20tt_117',['stop tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md121',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md155',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md141',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;']]],
  ['strace_118',['System Tracing with strace',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md975',1,'']]],
  ['strategies_119',['strategies',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md345',1,'Error Recovery Strategies'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1730',1,'Retry Strategies'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md745',1,'Scaling Strategies']]],
  ['strategy_120',['strategy',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md755',1,'Backup Strategy'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md753',1,'Sharding Strategy'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1109',1,'Testing Strategy']]],
  ['strategy_20pattern_121',['strategy pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md73',1,'10. Strategy Pattern'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1524',1,'5. Strategy Pattern']]],
  ['streaming_122',['streaming',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md645',1,'Event Streaming'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2009',1,'Event Streaming'],['../da/db6/md_docs_2FEATURES.html#autotoc_md585',1,'Event Streaming'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md891',1,'Example 3: Event Streaming']]],
  ['streaming_20pattern_123',['streaming pattern',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md124',1,'Event Streaming Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md180',1,'Event Streaming Pattern']]],
  ['struct_3a_20tt_20event_5fstream_5fconfig_20tt_124',['Struct: &lt;tt&gt;event_stream_config&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md126',1,'']]],
  ['struct_3a_20tt_20pipeline_5fstage_20tt_125',['Struct: &lt;tt&gt;pipeline_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md150',1,'']]],
  ['structural_20patterns_126',['Structural Patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md66',1,'']]],
  ['structure_127',['structure',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md866',1,'3. Message Structure'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1185',1,'CMake Structure'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md710',1,'Configuration File Structure'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md306',1,'Configuration Structure'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1971',1,'File Structure'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1206',1,'Future Structure'],['../da/db6/md_docs_2FEATURES.html#autotoc_md595',1,'Message Structure'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'Messaging System Project Structure'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md935',1,'Project Structure'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md791',1,'Project Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1563',1,'Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1574',1,'Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1581',1,'Structure'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1354',1,'Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1568',1,'Structure'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md804',1,'Test Structure']]],
  ['structured_20logging_128',['Structured Logging',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md743',1,'']]],
  ['structures_129',['structures',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1343',1,'Structures'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1359',1,'Structures'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1291',1,'Structures'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1334',1,'Structures']]],
  ['studio_130',['Visual Studio',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md789',1,'']]],
  ['studio_20code_131',['Visual Studio Code',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md787',1,'']]],
  ['style_20guide_132',['C++ Style Guide',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md795',1,'']]],
  ['sub_133',['sub',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md477',1,'Latency Distribution (Pub/Sub)'],['../d4/d54/md_docs_2API__REFERENCE__KO.html#autotoc_md365',1,'Pub/Sub'],['../d5/ddb/md_docs_2BENCHMARKS__KO.html#autotoc_md514',1,'Pub/Sub'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md643',1,'Pub/Sub']]],
  ['sub_20migration_134',['Example 1: Simple Pub/Sub Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md889',1,'']]],
  ['sub_20pattern_135',['sub pattern',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2007',1,'Pub/Sub Pattern'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md878',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md87',1,'Pub/Sub Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md583',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md178',1,'Pub/Sub Pattern']]],
  ['sub_20performance_136',['Pub/Sub Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md464',1,'']]],
  ['subdirectory_137',['Subdirectory',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1019',1,'']]],
  ['submission_138',['Job Submission',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md325',1,'']]],
  ['submission_20convenience_139',['Task Submission (Convenience)',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1373',1,'']]],
  ['submission_20flow_140',['Task Submission Flow',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1512',1,'']]],
  ['submit_20a_20task_141',['5. Submit a Task',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1835',1,'']]],
  ['submitting_20to_20priority_20queues_142',['Submitting to Priority Queues',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1741',1,'']]],
  ['subscribe_143',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md907',1,'']]],
  ['subscribe_20to_20topics_144',['Q: How do I subscribe to topics?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md848',1,'']]],
  ['subscribe_20tt_145',['subscribe tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md100',1,'&lt;tt&gt;subscribe&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md131',1,'&lt;tt&gt;subscribe&lt;/tt&gt;']]],
  ['subscriber_20scaling_146',['Publisher/Subscriber Scaling',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md482',1,'']]],
  ['subscriber_20tt_147',['Class: &lt;tt&gt;subscriber&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md97',1,'']]],
  ['subscription_148',['Subscription',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md309',1,'']]],
  ['subscription_20count_20impact_149',['Subscription Count Impact',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md462',1,'']]],
  ['subscription_20management_150',['Subscription Management',['../da/db6/md_docs_2FEATURES.html#autotoc_md601',1,'']]],
  ['subscriptions_151',['Event Subscriptions',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1365',1,'']]],
  ['subsystems_152',['Integration with Subsystems',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1021',1,'']]],
  ['subtask_20management_153',['Subtask Management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1296',1,'']]],
  ['subtask_20spawning_154',['Subtask Spawning',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1760',1,'']]],
  ['subtasks_155',['subtasks',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1761',1,'Spawning Subtasks'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1762',1,'Tracking Subtasks']]],
  ['success_156',['Target State (PR #30 - Success)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md235',1,'']]],
  ['successful_20build_157',['Verifying Successful Build',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md675',1,'']]],
  ['suites_158',['Test Suites',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2023',1,'']]],
  ['summary_159',['summary',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md446',1,'Executive Summary'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1932',1,'Executive Summary'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md232',1,'Executive Summary'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md686',1,'Quick Fix Summary'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md83',1,'Summary']]],
  ['support_160',['support',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2034',1,'🌐 Platform Support'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2042',1,'📬 Contact &amp; Support'],['../da/db6/md_docs_2FEATURES.html#autotoc_md588',1,'Backend Support'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md694',1,'Operating System Support'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1146',1,'Support'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md912',1,'Support'],['../da/db6/md_docs_2FEATURES.html#autotoc_md623',1,'Testing Support'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md299',1,'Transaction Support']]],
  ['supported_161',['Q: Which platforms are supported?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md840',1,'']]],
  ['supported_20macos_162',['Issue 3: grep -P Not Supported (macOS)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md665',1,'']]],
  ['supported_20syntax_163',['Supported Syntax',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1353',1,'']]],
  ['supported_20types_164',['Supported Types',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md278',1,'']]],
  ['synchronous_20rpc_20latency_165',['Synchronous RPC Latency',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md469',1,'']]],
  ['syntax_166',['Supported Syntax',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1353',1,'']]],
  ['system_167',['system',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md194',1,'1. Container System'],['../d2/d64/md_docs_2architecture.html#autotoc_md381',1,'1. Container System'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1832',1,'2. Create and Configure the Task System'],['../d2/d64/md_docs_2architecture.html#autotoc_md382',1,'2. Network System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md195',1,'2. Network System'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md926',1,'3. Build the System'],['../d2/d64/md_docs_2architecture.html#autotoc_md383',1,'3. Database System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md196',1,'3. Database System'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1834',1,'4. Start the System'],['../d2/d64/md_docs_2architecture.html#autotoc_md384',1,'4. Thread System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md197',1,'4. Thread System'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1836',1,'6. Stop the System'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1184',1,'Build System'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md821',1,'Build System'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html',1,'Contributing to Messaging System'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1938',1,'Phase 2: Worker System'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1894',1,'Q: How do I gracefully shut down the system?'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1236',1,'Task Queue System']]],
  ['system_20✅_168',['Sprint 3: Worker System ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1965',1,'']]],
  ['system_20기능_169',['Messaging System 기능',['../d4/d0c/md_docs_2FEATURES__KO.html',1,'']]],
  ['system_20문서_170',['Messaging System 문서',['../d8/d0a/md_docs_2README__KO.html',1,'']]],
  ['system_20변경_20이력_171',['Messaging System 변경 이력',['../db/d9f/md_docs_2CHANGELOG__KO.html',1,'']]],
  ['system_20성능_20벤치마크_172',['Messaging System 성능 벤치마크',['../d5/ddb/md_docs_2BENCHMARKS__KO.html',1,'']]],
  ['system_20아키텍처_173',['Messaging System 아키텍처',['../de/de3/md_docs_2ARCHITECTURE__KO.html',1,'']]],
  ['system_20프로덕션_20품질_174',['Messaging System 프로덕션 품질',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html',1,'']]],
  ['system_20프로젝트_20구조_175',['Messaging System 프로젝트 구조',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html',1,'']]],
  ['system_20administrators_176',['For System Administrators',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1231',1,'']]],
  ['system_20api_177',['system api',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md267',1,'Container System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md292',1,'Database System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md334',1,'Logger System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md281',1,'Network System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md321',1,'Thread System API']]],
  ['system_20api_20레퍼런스_178',['Messaging System API 레퍼런스',['../d4/d54/md_docs_2API__REFERENCE__KO.html',1,'']]],
  ['system_20architecture_179',['system architecture',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html',1,'System Architecture'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1499',1,'System Architecture']]],
  ['system_20changelog_180',['Messaging System Changelog',['../da/dee/md_docs_2CHANGELOG.html',1,'']]],
  ['system_20configuration_181',['Task System Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1562',1,'']]],
  ['system_20configuration_20file_20format_182',['System Configuration File Format',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md347',1,'']]],
  ['system_20cron_183',['Before (System Cron)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1664',1,'']]],
  ['system_20error_20codes_184',['System Error Codes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md343',1,'']]],
  ['system_20features_185',['Messaging System Features',['../da/db6/md_docs_2FEATURES.html',1,'']]],
  ['system_20health_186',['System Health',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md778',1,'']]],
  ['system_20improvement_20plan_187',['Distributed Task Queue System - Improvement Plan',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html',1,'']]],
  ['system_20integration_188',['system integration',['../da/db6/md_docs_2FEATURES.html#autotoc_md618',1,'Container System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md616',1,'Logger System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md617',1,'Monitoring System Integration'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1968',1,'Sprint 6: Monitoring &amp; System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md615',1,'Thread System Integration']]],
  ['system_20layers_189',['system layers',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md192',1,'System Layers'],['../d2/d64/md_docs_2architecture.html#autotoc_md379',1,'System Layers']]],
  ['system_20overview_190',['System Overview',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1997',1,'']]],
  ['system_20performance_191',['system performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1064',1,'Container System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1070',1,'Database System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1067',1,'Network System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1057',1,'Overall System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1061',1,'Thread System Performance']]],
  ['system_20performance_20benchmarks_192',['Messaging System Performance Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html',1,'']]],
  ['system_20production_20quality_193',['Messaging System Production Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html',1,'']]],
  ['system_20project_20structure_194',['Messaging System Project Structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'']]],
  ['system_20requirements_195',['system requirements',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md689',1,'System Requirements'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md917',1,'System Requirements']]],
  ['system_20support_196',['Operating System Support',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md694',1,'']]],
  ['system_20tracing_20with_20strace_197',['System Tracing with strace',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md975',1,'']]],
  ['system_20tuning_198',['System Tuning',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md727',1,'']]],
  ['system_5farchitecture_2emd_199',['SYSTEM_ARCHITECTURE.md',['../db/d93/SYSTEM__ARCHITECTURE_8md.html',1,'']]],
  ['systems_200',['systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2012',1,'🌟 Integration with Base Systems'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md673',1,'Alternative: Minimal Build (No External Systems)'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md495',1,'Comparison with Other Systems'],['../d2/d64/md_docs_2architecture.html#autotoc_md393',1,'External Systems'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md206',1,'External Systems'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1660',1,'From Message Queue Systems'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md663',1,'Issue 2: GTest Not Found in External Systems'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2014',1,'Optional Systems'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2013',1,'Required Systems'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md881',1,'Step 7: Integration with Other Systems']]]
];
