var searchData=
[
  ['d_20development_20guidelines_0',['D. Development Guidelines',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1253',1,'']]],
  ['d_20references_1',['D. References',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md783',1,'']]],
  ['dashboard_2',['dashboard',['../df/d94/md_docs_2performance.html#autotoc_md992',1,'2. Performance Monitoring Dashboard'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md545',1,'Grafana Dashboard']]],
  ['data_3',['5. &lt;strong&gt;container_system&lt;/strong&gt; - Type-Safe Data',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1169',1,'']]],
  ['data_20communication_20modules_4',['Data &amp; Communication Modules',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1005',1,'']]],
  ['data_20encryption_5',['Data Encryption',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md574',1,'']]],
  ['data_20flow_20architecture_6',['data flow architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md98',1,'Data Flow Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1020',1,'Data Flow Architecture']]],
  ['data_20handling_7',['2. Container-Based Data Handling',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md682',1,'']]],
  ['data_20loss_20during_20migration_8',['Risk 2: Data Loss During Migration',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md238',1,'']]],
  ['database_20backup_9',['Database Backup',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md561',1,'']]],
  ['database_20bottleneck_10',['Problem: Database Bottleneck',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1117',1,'']]],
  ['database_20connection_20failed_11',['&quot;Database connection failed&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1107',1,'']]],
  ['database_20connection_20pool_20exhaustion_12',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1099',1,'']]],
  ['database_20contracts_13',['Database Contracts',['../da/dab/md_docs_2archived_2phase0_2INTERFACE__MAPPING.html#autotoc_md163',1,'']]],
  ['database_20errors_14',['Database Errors',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1106',1,'']]],
  ['database_20migration_20rollback_15',['Database Migration Rollback',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md228',1,'']]],
  ['database_20scaling_16',['Database Scaling',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md555',1,'']]],
  ['database_20system_17',['database system',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1018',1,'3. Database System'],['../d2/d64/md_docs_2architecture.html#autotoc_md96',1,'3. Database System']]],
  ['database_20system_20api_18',['Database System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md28',1,'']]],
  ['database_20system_20performance_19',['Database System Performance',['../df/d94/md_docs_2performance.html#autotoc_md968',1,'']]],
  ['database_20tt_20',['Namespace: &lt;tt&gt;database&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md29',1,'']]],
  ['database_20tuning_21',['Database Tuning',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md538',1,'']]],
  ['database_5fmanager_20tt_22',['Class: &lt;tt&gt;database_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md30',1,'']]],
  ['database_5fsystem_20strong_20persistence_23',['6. &lt;strong&gt;database_system&lt;/strong&gt; - Persistence',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1170',1,'']]],
  ['deadlock_20detected_24',['&quot;Deadlock detected&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1108',1,'']]],
  ['deadlock_20in_20message_20processing_25',['Issue 4: Deadlock in Message Processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1100',1,'']]],
  ['deadlocks_26',['Detect Deadlocks',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1077',1,'']]],
  ['debian_27',['debian',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md508',1,'APT Repository (Ubuntu/Debian)'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md487',1,'Linux (Ubuntu/Debian)'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md673',1,'Linux (Ubuntu/Debian)']]],
  ['debug_20core_20dumps_28',['Debug Core Dumps',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1066',1,'']]],
  ['debug_20logging_29',['Enable Debug Logging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1060',1,'']]],
  ['debug_20techniques_30',['Debug Techniques',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1059',1,'']]],
  ['debugging_31',['debugging',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md637',1,'Debugging'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1067',1,'Memory Debugging'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1071',1,'Network Debugging'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1075',1,'Thread Debugging'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1064',1,'Using GDB for Debugging']]],
  ['decisions_32',['Design Patterns and Architectural Decisions',['../d5/dca/md_docs_2DESIGN__PATTERNS.html',1,'']]],
  ['decorator_20pattern_33',['6. Decorator Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md592',1,'']]],
  ['definitions_34',['definitions',['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html#autotoc_md280',1,'2. Error Code Definitions'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md711',1,'4. Lack of Interface Definitions']]],
  ['degradation_35',['Issue: Build performance degradation',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md828',1,'']]],
  ['degradation_20with_20many_20topics_36',['Issue 5: Performance Degradation with Many Topics',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1101',1,'']]],
  ['deliverables_37',['Documentation Deliverables',['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md402',1,'']]],
  ['delivered_38',['Issue: Messages not being delivered',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md827',1,'']]],
  ['dependencies_39',['dependencies',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md211',1,'2. External System Dependencies'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md500',1,'Build Dependencies'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md782',1,'C. Dependencies'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md668',1,'Development Dependencies'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md619',1,'Development Dependencies'],['../da/dab/md_docs_2archived_2phase0_2INTERFACE__MAPPING.html#autotoc_md168',1,'External Dependencies'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md834',1,'Q: Are there any runtime dependencies?'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md501',1,'Runtime Dependencies'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md669',1,'Runtime Dependencies'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md499',1,'Software Dependencies'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md800',1,'Step 1: Update Dependencies'],['../d6/d40/md_docs_2archived_2phase4_2TEST__SUMMARY.html#autotoc_md370',1,'Test Dependencies']]],
  ['dependencies_20to_20remove_40',['Legacy Dependencies to Remove',['../da/dab/md_docs_2archived_2phase0_2INTERFACE__MAPPING.html#autotoc_md166',1,'']]],
  ['dependency_20architecture_41',['Dependency Architecture',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1163',1,'']]],
  ['dependency_20binaries_42',['3. Prebuilt Dependency Binaries',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1140',1,'']]],
  ['dependency_20integration_20strategy_43',['Dependency Integration Strategy',['../de/df8/md_docs_2archived_2phase0_2BUILD__CONFIGURATION.html#autotoc_md133',1,'']]],
  ['dependency_20refactoring_20design_20document_44',['Phase 1: Build System and Dependency Refactoring - Design Document',['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html',1,'']]],
  ['dependency_20validation_20script_45',['Dependency Validation Script',['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html#autotoc_md259',1,'']]],
  ['dependency_20version_20conflicts_46',['Risk 4: Dependency Version Conflicts',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md241',1,'']]],
  ['deployment_47',['deployment',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md224',1,'Blue-Green Deployment'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1048',1,'Container Deployment'],['../d2/d64/md_docs_2architecture.html#autotoc_md126',1,'Container Deployment'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md653',1,'Deployment'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md526',1,'Deployment'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md529',1,'Docker Compose Deployment'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md654',1,'Docker Deployment'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md521',1,'High Availability Deployment'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md524',1,'Kubernetes Deployment'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md655',1,'Kubernetes Deployment'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md997',1,'Operations &amp; Deployment'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md520',1,'Single Server Deployment'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md575',1,'Troubleshooting Deployment']]],
  ['deployment_20architecture_48',['deployment architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md125',1,'Deployment Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1047',1,'Deployment Architecture']]],
  ['deployment_20artifacts_20task_204_205_49',['6. Deployment Artifacts (Task 4.5)',['../dd/db6/md_docs_2archived_2phase4_2DESIGN.html#autotoc_md327',1,'']]],
  ['deployment_20design_20document_50',['Phase 4: Validation and Deployment - Design Document',['../dd/db6/md_docs_2archived_2phase4_2DESIGN.html',1,'']]],
  ['deployment_20guide_51',['Deployment Guide',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html',1,'']]],
  ['deployment_20scenarios_52',['Deployment Scenarios',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md519',1,'']]],
  ['deployment_5fguide_2emd_53',['DEPLOYMENT_GUIDE.md',['../dd/deb/DEPLOYMENT__GUIDE_8md.html',1,'']]],
  ['design_54',['design',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md213',1,'Compatibility Layer Design'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1174',1,'High-Level Design']]],
  ['design_20document_55',['design document',['../de/df8/md_docs_2archived_2phase0_2BUILD__CONFIGURATION.html',1,'Build Configuration Design Document'],['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html',1,'Phase 1: Build System and Dependency Refactoring - Design Document'],['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html',1,'Phase 2: Messaging Core Redesign - Design Document'],['../df/d85/md_docs_2archived_2phase3_2DESIGN.html',1,'Phase 3: Infrastructure Integration - Design Document'],['../dd/db6/md_docs_2archived_2phase4_2DESIGN.html',1,'Phase 4: Validation and Deployment - Design Document']]],
  ['design_20goals_56',['Design Goals',['../df/d94/md_docs_2performance.html#autotoc_md951',1,'']]],
  ['design_20patterns_57',['Key Design Patterns',['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md396',1,'']]],
  ['design_20patterns_20and_20architectural_20decisions_58',['Design Patterns and Architectural Decisions',['../d5/dca/md_docs_2DESIGN__PATTERNS.html',1,'']]],
  ['design_2emd_59',['design.md',['../d2/db4/phase2_2DESIGN_8md.html',1,'(Global Namespace)'],['../d3/d62/phase3_2DESIGN_8md.html',1,'(Global Namespace)'],['../d1/ddf/phase4_2DESIGN_8md.html',1,'(Global Namespace)'],['../d8/d86/phase1_2DESIGN_8md.html',1,'(Global Namespace)']]],
  ['design_5fpatterns_2emd_60',['DESIGN_PATTERNS.md',['../d7/d96/DESIGN__PATTERNS_8md.html',1,'']]],
  ['designs_61',['designs',['../df/d85/md_docs_2archived_2phase3_2DESIGN.html#autotoc_md304',1,'Component Designs'],['../dd/db6/md_docs_2archived_2phase4_2DESIGN.html#autotoc_md316',1,'Component Designs']]],
  ['detailed_20replacement_20mapping_62',['Detailed Replacement Mapping',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md183',1,'']]],
  ['detect_20deadlocks_63',['Detect Deadlocks',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1077',1,'']]],
  ['detected_64',['detected',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1108',1,'&quot;Deadlock detected&quot;'],['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md227',1,'Rollback (If Issues Detected)']]],
  ['detection_20utility_65',['1.3 Integration Detection Utility',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md725',1,'']]],
  ['developer_20guide_66',['Developer Guide',['../db/dac/md_docs_2DEVELOPER__GUIDE.html',1,'']]],
  ['developer_5fguide_2emd_67',['DEVELOPER_GUIDE.md',['../d0/d0f/DEVELOPER__GUIDE_8md.html',1,'']]],
  ['developers_68',['For Developers',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1001',1,'']]],
  ['development_69',['development',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md695',1,'3. Development'],['../de/df8/md_docs_2archived_2phase0_2BUILD__CONFIGURATION.html#autotoc_md153',1,'FetchContent Mode (Development)']]],
  ['development_20dependencies_70',['development dependencies',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md619',1,'Development Dependencies'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md668',1,'Development Dependencies']]],
  ['development_20environment_71',['Option 1: FetchContent (Development Environment)',['../de/df8/md_docs_2archived_2phase0_2BUILD__CONFIGURATION.html#autotoc_md134',1,'']]],
  ['development_20fetchcontent_20mode_72',['For Development (FetchContent Mode)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md474',1,'']]],
  ['development_20guidelines_73',['D. Development Guidelines',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1253',1,'']]],
  ['development_20planning_74',['Development &amp; Planning',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md998',1,'']]],
  ['development_20recommended_75',['Local Development (Recommended)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1198',1,'']]],
  ['development_20recommended_20for_20contributors_76',['Option A: Local Development (Recommended for Contributors)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1180',1,'']]],
  ['development_20setup_77',['Development Setup',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md614',1,'']]],
  ['development_20workflow_78',['Development Workflow',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1226',1,'']]],
  ['di_79',['3. Message Bus with DI',['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html#autotoc_md281',1,'']]],
  ['di_20architecture_80',['Week 3: DI Architecture',['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html#autotoc_md294',1,'']]],
  ['di_20container_20interface_81',['7.1 DI Container Interface',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md740',1,'']]],
  ['di_20container_20week_207_82',['Phase 7: DI Container (Week 7)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md739',1,'']]],
  ['di_20container_20week_207_20✅_20completed_83',['Phase 7: DI Container (Week 7) - ✅ COMPLETED',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md763',1,'']]],
  ['diagram_84',['Architecture Diagram',['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html#autotoc_md256',1,'']]],
  ['direct_20console_20output_85',['5. Direct Console Output',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md181',1,'']]],
  ['direct_20output_86',['Before (Direct output)',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md194',1,'']]],
  ['directories_20phase0_204_87',['Phase Directories (phase0-4)',['../index.html#autotoc_md426',1,'']]],
  ['directory_20layout_88',['Directory Layout',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md621',1,'']]],
  ['directory_20structure_89',['directory structure',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md197',1,'Archive Directory Structure'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md704',1,'Existing Directory Structure']]],
  ['directory_20structure_20inconsistency_90',['2. Directory Structure Inconsistency',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md709',1,'']]],
  ['directory_20structure_20new_91',['Directory Structure (New)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md718',1,'']]],
  ['disaster_20recovery_20plan_92',['Disaster Recovery Plan',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md564',1,'']]],
  ['disk_20i_20o_20analysis_93',['Disk I/O Analysis',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1091',1,'']]],
  ['distributed_20architecture_94',['distributed architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md101',1,'Distributed Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1023',1,'Distributed Architecture']]],
  ['distributed_20task_20queue_20with_20persistence_95',['Example 1: Distributed Task Queue with Persistence',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1187',1,'']]],
  ['distributed_20tracing_96',['distributed tracing',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1042',1,'Distributed Tracing'],['../d2/d64/md_docs_2architecture.html#autotoc_md120',1,'Distributed Tracing']]],
  ['do_20i_20enable_20lock_20free_20queues_97',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md835',1,'']]],
  ['do_20i_20handle_20migration_20testing_98',['Q: How do I handle migration testing?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md837',1,'']]],
  ['do_20i_20need_20to_20migrate_20all_20code_20at_20once_99',['Q: Do I need to migrate all code at once?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md832',1,'']]],
  ['docker_20compose_20deployment_100',['Docker Compose Deployment',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md529',1,'']]],
  ['docker_20deployment_101',['Docker Deployment',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md654',1,'']]],
  ['docker_20installation_102',['Docker Installation',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md510',1,'']]],
  ['docs_103',['Phase-Specific Docs',['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md403',1,'']]],
  ['document_104',['document',['../de/df8/md_docs_2archived_2phase0_2BUILD__CONFIGURATION.html',1,'Build Configuration Design Document'],['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html',1,'Phase 1: Build System and Dependency Refactoring - Design Document'],['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html',1,'Phase 2: Messaging Core Redesign - Design Document'],['../df/d85/md_docs_2archived_2phase3_2DESIGN.html',1,'Phase 3: Infrastructure Integration - Design Document'],['../dd/db6/md_docs_2archived_2phase4_2DESIGN.html',1,'Phase 4: Validation and Deployment - Design Document'],['../da/dab/md_docs_2archived_2phase0_2INTERFACE__MAPPING.html',1,'System Interface Mapping Document']]],
  ['documentation_105',['documentation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1217',1,'📚 Documentation'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1003',1,'🧩 Component Documentation'],['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md404',1,'Additional Documentation'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1218',1,'Available Documentation'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md629',1,'Code Documentation'],['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md405',1,'Code Documentation'],['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html#autotoc_md272',1,'Documentation'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1220',1,'External System Documentation'],['../d2/d64/md_docs_2architecture.html#autotoc_md89',1,'Module Documentation'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1219',1,'Phase Documentation'],['../d2/d64/md_docs_2architecture.html#autotoc_md87',1,'Related Documentation'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md996',1,'User Documentation']]],
  ['documentation_20deliverables_106',['Documentation Deliverables',['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md402',1,'']]],
  ['documentation_20of_20option_20impact_107',['Documentation of Option Impact',['../de/df8/md_docs_2archived_2phase0_2BUILD__CONFIGURATION.html#autotoc_md146',1,'']]],
  ['documentation_20overview_108',['📚 Documentation Overview',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md995',1,'']]],
  ['documentation_20standards_109',['documentation standards',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1007',1,'📖 Documentation Standards'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md628',1,'Documentation Standards']]],
  ['documentation_20updates_110',['🔄 Documentation Updates',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1008',1,'']]],
  ['documentation_20weeks_209_2010_20✅_20completed_111',['Phase 9-10: Testing and Documentation (Weeks 9-10) - ✅ COMPLETED',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md765',1,'']]],
  ['documents_112',['documents',['../index.html#autotoc_md423',1,'Archived Documents'],['../index.html',1,'Archived Planning Documents'],['../index.html#autotoc_md427',1,'Current Planning Documents']]],
  ['doesn_20t_20start_113',['Issue: Message bus doesn&apos;t start',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md826',1,'']]],
  ['downloads_114',['3. Reduce FetchContent Downloads',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1132',1,'']]],
  ['driven_20architecture_115',['17. Event-Driven Architecture',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md606',1,'']]],
  ['driven_20initialization_20tt_20test_5fconfig_5fdriven_5finitialization_20tt_116',['6. Config-Driven Initialization (&lt;tt&gt;test_config_driven_initialization&lt;/tt&gt;)',['../d6/d40/md_docs_2archived_2phase4_2TEST__SUMMARY.html#autotoc_md355',1,'']]],
  ['driven_20microservice_20with_20tracing_117',['Example 3: Event-Driven Microservice with Tracing',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1189',1,'']]],
  ['drops_118',['Problem: Connection Drops',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1115',1,'']]],
  ['dsl_119',['1. Message Container DSL',['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html#autotoc_md279',1,'']]],
  ['dsl_20정립_20strong_120',['&lt;strong&gt;Task 2.1 – 메시지 컨테이너 DSL 정립&lt;/strong&gt;',['../dd/df9/md_docs_2archived_2REBUILD__PLAN.html#autotoc_md443',1,'']]],
  ['dump_121',['TCP Dump',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1072',1,'']]],
  ['dumps_122',['Debug Core Dumps',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1066',1,'']]],
  ['during_20migration_123',['during migration',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md245',1,'During Migration'],['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md238',1,'Risk 2: Data Loss During Migration']]],
  ['dynamic_20configuration_124',['dynamic configuration',['../d2/d64/md_docs_2architecture.html#autotoc_md124',1,'Dynamic Configuration'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1046',1,'Dynamic Configuration']]]
];
