var searchData=
[
  ['kcenon_20logger_20logging_20system_20separate_20project_20a_0',['2. &lt;a href=&quot;https://github.com/kcenon/logger&quot; &gt;Logging System (Separate Project)&lt;/a&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md231',1,'']]],
  ['kcenon_20monitoring_20real_20time_20monitoring_20system_20separate_20project_20a_1',['4. &lt;a href=&quot;https://github.com/kcenon/monitoring&quot; &gt;Real-time Monitoring System (Separate Project)&lt;/a&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md236',1,'']]],
  ['kcenon_20thread_5fsystem_20tree_20main_20sources_20thread_5fbase_20thread_20base_20thread_5fmodule_20a_2',['1. &lt;a href=&quot;https://github.com/kcenon/thread_system/tree/main/sources/thread_base&quot; &gt;Thread Base (thread_module)&lt;/a&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md230',1,'']]],
  ['kcenon_20thread_5fsystem_20tree_20main_20sources_20thread_5fpool_20thread_20pool_20system_20thread_5fpool_5fmodule_20a_3',['3. &lt;a href=&quot;https://github.com/kcenon/thread_system/tree/main/sources/thread_pool&quot; &gt;Thread Pool System (thread_pool_module)&lt;/a&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md232',1,'']]],
  ['kcenon_20thread_5fsystem_20tree_20main_20sources_20typed_5fthread_5fpool_20typed_20thread_20pool_20system_20typed_5fthread_5fpool_5fmodule_20a_4',['5. &lt;a href=&quot;https://github.com/kcenon/thread_system/tree/main/sources/typed_thread_pool&quot; &gt;Typed Thread Pool System (typed_thread_pool_module)&lt;/a&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md237',1,'']]],
  ['key_20components_5',['Key Components',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md229',1,'']]],
  ['key_20features_6',['key features',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1',1,'🚀 Key Features'],['../index.html#features',1,'Key Features'],['../classnetwork__module_1_1messaging__client.html#autotoc_md99',1,'Key Features'],['../classnetwork__module_1_1tcp__socket.html#autotoc_md108',1,'Key Features'],['../classthread__module_1_1thread__base.html#autotoc_md148',1,'Key Features'],['../classtyped__thread__pool__module_1_1typed__thread__pool__t.html#autotoc_md174',1,'Key Features']]],
  ['key_20files_20and_20their_20purpose_20strong_7',['📖 &lt;strong&gt;Key Files and Their Purpose&lt;/strong&gt;',['..//home/runner/work/messaging_system/messaging_system/thread_system/README.md#autotoc_md221',1,'']]],
  ['key_20responsibilities_8',['Key Responsibilities',['../classnetwork__module_1_1messaging__server.html#autotoc_md101',1,'']]],
  ['keys_9',['keys',['../classcontainer__module_1_1thread__safe__container.html#a449760a101db94287dcf9b6cdbc41b0a',1,'container_module::thread_safe_container']]]
];
