var searchData=
[
  ['websocket_20transport_0',['WebSocket Transport',['../da/db6/md_docs_2FEATURES.html#autotoc_md734',1,'']]],
  ['what_20about_20performance_1',['Q: What about performance?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1077',1,'']]],
  ['what_20c_20standard_20is_20required_2',['Q: What C++ standard is required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1012',1,'']]],
  ['what_20dependencies_20are_20required_3',['Q: What dependencies are required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1017',1,'']]],
  ['what_20is_20an_20adr_4',['What is an ADR?',['../index.html#autotoc_md53',1,'']]],
  ['what_20is_20messaging_5fsystem_5',['Q: What is messaging_system?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1011',1,'']]],
  ['what_20is_20the_20latency_6',['Q: What is the latency?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1026',1,'']]],
  ['what_20s_20included_7',['📦 What&apos;s Included',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2210',1,'']]],
  ['what_20throughput_20can_20i_20expect_8',['Q: What throughput can I expect?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1025',1,'']]],
  ['which_20platforms_20are_20supported_9',['Q: Which platforms are supported?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1013',1,'']]],
  ['wildcard_20patterns_10',['Wildcard Patterns',['../da/db6/md_docs_2FEATURES.html#autotoc_md746',1,'']]],
  ['wildcards_11',['wildcards',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1022',1,'Q: How do I use wildcards?'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md330',1,'Topic Pattern Wildcards']]],
  ['windows_12',['Windows',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1098',1,'']]],
  ['windows_20ci_20performance_20optimization_13',['Windows CI Performance Optimization',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html',1,'']]],
  ['windows_5foptimization_2emd_14',['WINDOWS_OPTIMIZATION.md',['../d9/dea/WINDOWS__OPTIMIZATION_8md.html',1,'']]],
  ['wins_15',['Short-Term (Quick Wins)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md242',1,'']]],
  ['with_20base_20systems_16',['🌟 Integration with Base Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2233',1,'']]],
  ['with_20custom_20configuration_17',['With Custom Configuration',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md623',1,'']]],
  ['with_20many_20topics_18',['Issue 5: Performance Degradation with Many Topics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1169',1,'']]],
  ['with_20network_5fsystem_19',['Using with network_system',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1202',1,'']]],
  ['with_20old_20includes_20',['Issue: Compilation errors with old includes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1068',1,'']]],
  ['with_20other_20systems_21',['with other systems',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md521',1,'Comparison with Other Systems'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1054',1,'Step 7: Integration with Other Systems']]],
  ['with_20perf_22',['Performance Profiling with perf',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1149',1,'']]],
  ['with_20retry_23',['Chain with Retry',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1987',1,'']]],
  ['with_20sample_20client_24',['3. Test with Sample Client',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1114',1,'']]],
  ['with_20small_20messages_25',['Issue 1: High CPU Usage with Small Messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1165',1,'']]],
  ['with_20strace_26',['System Tracing with strace',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1148',1,'']]],
  ['with_20subsystems_27',['Integration with Subsystems',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1194',1,'']]],
  ['with_20thread_5fsystem_28',['Using with thread_system',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1201',1,'']]],
  ['with_20transport_29',['Usage Example (Hybrid Mode with Transport)',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md315',1,'']]],
  ['won_20t_20start_30',['won t start',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1181',1,'Problem: Service Won&apos;t Start'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md946',1,'Service Won&apos;t Start']]],
  ['worker_20pool_31',['worker pool',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2161',1,'2.2 Worker Pool'],['../da/db6/md_docs_2FEATURES.html#autotoc_md704',1,'Worker Pool']]],
  ['worker_20pool_20configuration_32',['Worker Pool Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1794',1,'']]],
  ['worker_20scalability_33',['Worker Scalability',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md493',1,'']]],
  ['worker_20status_34',['worker status',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2098',1,'Check Worker Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1583',1,'Worker Status']]],
  ['worker_20system_35',['Phase 2: Worker System',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2159',1,'']]],
  ['worker_20system_20✅_36',['Sprint 3: Worker System ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2186',1,'']]],
  ['worker_20throughput_37',['Worker Throughput',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md492',1,'']]],
  ['worker_5fpool_38',['worker_pool',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1725',1,'4. worker_pool'],['../d9/db8/md_docs_2task_2ARCHITECTURE__KO.html#autotoc_md1756',1,'4. worker_pool'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1530',1,'worker_pool'],['../dd/db9/md_docs_2task_2API__REFERENCE__KO.html#autotoc_md1649',1,'worker_pool']]],
  ['workflow_39',['workflow',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2262',1,'Development Workflow'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md596',1,'Development Workflow'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md842',1,'Recommended Build Workflow'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md991',1,'Workflow']]],
  ['workflow_20patterns_40',['workflow patterns',['../d5/dd2/md_docs_2task_2PATTERNS.html',1,'Task Module Workflow Patterns'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1543',1,'Workflow Patterns']]],
  ['working_41',['Retry Not Working',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2091',1,'']]],
  ['workload_20type_42',['By Workload Type',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1820',1,'']]],
  ['works_43',['How Routing Works',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md636',1,'']]]
];
