var searchData=
[
  ['✅_0',['✅',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md237',1,'1. Test-Level Timeouts ✅'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md238',1,'2. CTest Parallel Execution ✅'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md239',1,'3. Build Parallelization ✅'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md255',1,'Priority 1 (Implemented) ✅'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2191',1,'Sprint 1: Core Task Infrastructure ✅'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2192',1,'Sprint 2: Queue &amp; Result Backend ✅'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2193',1,'Sprint 3: Worker System ✅'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2194',1,'Sprint 4: Client &amp; Async Result ✅'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2195',1,'Sprint 5: Scheduler ✅'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2196',1,'Sprint 6: Monitoring &amp; System Integration ✅'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2197',1,'Sprint 7: Testing &amp; Documentation ✅']]],
  ['✅_20core_20components_20complete_1',['✅ Core Components (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2218',1,'']]],
  ['✅_20documentation_20complete_2',['✅ Documentation (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2222',1,'']]],
  ['✅_20infrastructure_20complete_3',['✅ Infrastructure (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2220',1,'']]],
  ['✅_20patterns_20complete_4',['✅ Patterns (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2219',1,'']]],
  ['✅_20testing_20benchmarks_20complete_5',['✅ Testing &amp; Benchmarks (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2221',1,'']]]
];
