var searchData=
[
  ['b_3a_20템플릿을_20통한_20컴파일_20타임_20로거_20선택_0',['대안 B: 템플릿을 통한 컴파일 타임 로거 선택',['../dd/da0/md_docs_2adr_2001-logging-architecture__KO.html#autotoc_md44',1,'']]],
  ['b_3a_20compile_20time_20logger_20selection_20via_20templates_1',['Alternative B: Compile-time Logger Selection via Templates',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md18',1,'']]],
  ['backend_2',['backend',['../d9/db8/md_docs_2task_2ARCHITECTURE__KO.html#autotoc_md1548',1,'커스텀 Result Backend'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1947',1,'4.2 In-Memory Result Backend'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1517',1,'Custom Result Backend'],['../da/db6/md_docs_2FEATURES.html#autotoc_md591',1,'Integration Backend'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1945',1,'Phase 4: Result Backend'],['../da/db6/md_docs_2FEATURES.html#autotoc_md590',1,'Standalone Backend']]],
  ['backend_20✅_3',['Sprint 2: Queue &amp; Result Backend ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1964',1,'']]],
  ['backend_20분리_4',['2. Result Backend 분리',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1979',1,'']]],
  ['backend_20선택적_5',['4.3 Redis Result Backend (선택적)',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1948',1,'']]],
  ['backend_20impact_6',['Backend Impact',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md466',1,'']]],
  ['backend_20interface_7',['backend interface',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1946',1,'4.1 Result Backend Interface'],['../da/db6/md_docs_2FEATURES.html#autotoc_md589',1,'Backend Interface']]],
  ['backend_20support_8',['Backend Support',['../da/db6/md_docs_2FEATURES.html#autotoc_md588',1,'']]],
  ['backends_20tt_9',['Backends (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1181',1,'']]],
  ['backends_20tt_20include_20kcenon_20messaging_20backends_20tt_10',['Backends (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1181',1,'']]],
  ['background_11',['Background',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md3',1,'']]],
  ['backup_12',['backup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md756',1,'Application State Backup'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md757',1,'Database Backup']]],
  ['backup_20and_20recovery_13',['Backup and Recovery',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md754',1,'']]],
  ['backup_20strategy_14',['Backup Strategy',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md755',1,'']]],
  ['balancer_20configuration_15',['Load Balancer Configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md747',1,'']]],
  ['base_20systems_16',['🌟 Integration with Base Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2012',1,'']]],
  ['based_17',['Callback-Based',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1330',1,'']]],
  ['based_20data_20handling_18',['2. Container-Based Data Handling',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md932',1,'']]],
  ['based_20execution_19',['Cron-based Execution',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1841',1,'']]],
  ['based_20logging_20',['Alternative C: Macro-based Logging',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md19',1,'']]],
  ['based_20scheduling_21',['Cron-Based Scheduling',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1746',1,'']]],
  ['based_20tasks_22',['1. Message-Based Tasks',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1520',1,'']]],
  ['baseline_23',['Performance Baseline',['../d9/df1/md_docs_2performance_2BASELINE.html',1,'']]],
  ['baseline_20metrics_24',['Baseline Metrics',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1038',1,'']]],
  ['baseline_2emd_25',['BASELINE.md',['../dc/d78/BASELINE_8md.html',1,'']]],
  ['basic_20configuration_20file_26',['Basic Configuration File',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md937',1,'']]],
  ['basic_20example_27',['Basic Example',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2004',1,'']]],
  ['basic_20message_20bus_20usage_28',['1. Basic Message Bus Usage',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md931',1,'']]],
  ['basic_20usage_29',['basic usage',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md934',1,'Basic Usage'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1830',1,'Basic Usage'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1029',1,'Basic Usage']]],
  ['batch_20operations_30',['Batch Operations',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1321',1,'']]],
  ['batching_20and_20pipelining_31',['Batching and Pipelining',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1081',1,'']]],
  ['before_20custom_20thread_20pool_32',['Before (Custom Thread Pool)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1657',1,'']]],
  ['before_20fix_33',['Initial State (PR #31 - Before Fix)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md234',1,'']]],
  ['before_20system_20cron_34',['Before (System Cron)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1664',1,'']]],
  ['behavioral_20patterns_35',['Behavioral Patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md71',1,'']]],
  ['being_20delivered_36',['Issue: Messages not being delivered',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md898',1,'']]],
  ['being_20processed_37',['Tasks Not Being Processed',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1867',1,'']]],
  ['benchmark_20commands_38',['Benchmark Commands',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1045',1,'']]],
  ['benchmark_20output_20format_39',['Benchmark Output Format',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md491',1,'']]],
  ['benchmark_20results_40',['Benchmark Results',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1055',1,'']]],
  ['benchmarks_41',['benchmarks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md490',1,'Available Benchmarks'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2019',1,'Benchmarks'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md453',1,'Message Creation Benchmarks'],['../de/d93/md_docs_2BENCHMARKS.html',1,'Messaging System Performance Benchmarks'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2020',1,'Running Benchmarks'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md488',1,'Running Benchmarks']]],
  ['benchmarks_20complete_42',['✅ Testing &amp; Benchmarks (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1993',1,'']]],
  ['benchmarks_2emd_43',['BENCHMARKS.md',['../de/d04/BENCHMARKS_8md.html',1,'']]],
  ['benchmarks_5fko_2emd_44',['BENCHMARKS_KO.md',['../d3/d9a/BENCHMARKS__KO_8md.html',1,'']]],
  ['benefits_45',['Benefits',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1666',1,'']]],
  ['benefits_20of_20migration_46',['Benefits of Migration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1659',1,'']]],
  ['best_20practices_47',['best practices',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1742',1,'Best Practices'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md798',1,'Best Practices'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md177',1,'Best Practices'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1135',1,'Best Practices'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md827',1,'Security Best Practices']]],
  ['binaries_48',['3. Prebuilt Dependency Binaries',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md253',1,'']]],
  ['blocking_20result_20retrieval_49',['Blocking Result Retrieval',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1329',1,'']]],
  ['bottleneck_50',['Problem: Database Bottleneck',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1012',1,'']]],
  ['bottlenecks_51',['bottlenecks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md486',1,'Common Bottlenecks'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md980',1,'Identify CPU Bottlenecks'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1093',1,'Network Bottlenecks']]],
  ['breakdown_52',['Latency Breakdown',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md478',1,'']]],
  ['breaking_20changes_53',['Breaking Changes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md863',1,'']]],
  ['bridge_20integration_54',['Task Event Bridge Integration',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1027',1,'']]],
  ['broker_55',['Message Broker',['../da/db6/md_docs_2FEATURES.html#autotoc_md580',1,'']]],
  ['bugs_56',['Reporting Bugs',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1148',1,'']]],
  ['build_57',['build',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md701',1,'2. Configure Build'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md675',1,'Verifying Successful Build']]],
  ['build_20and_20install_58',['3. Build and Install',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md702',1,'']]],
  ['build_20and_20run_59',['2. Build and Run',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md940',1,'']]],
  ['build_20caching_20service_60',['2. Implement Build Caching Service',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md252',1,'']]],
  ['build_20custom_20image_61',['Build Custom Image',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md708',1,'']]],
  ['build_20dependencies_62',['Build Dependencies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md696',1,'']]],
  ['build_20for_20tests_63',['1. Use Release Build for Tests',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md243',1,'']]],
  ['build_20issues_64',['Build Issues',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md832',1,'']]],
  ['build_20issues_20and_20solutions_65',['Common Build Issues and Solutions',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md660',1,'']]],
  ['build_20method_66',['Build Method',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1281',1,'']]],
  ['build_20no_20external_20systems_67',['Alternative: Minimal Build (No External Systems)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md673',1,'']]],
  ['build_20options_68',['build options',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2031',1,'🔧 Build Options'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md928',1,'Custom Build Options']]],
  ['build_20parallelization_20✅_69',['3. Build Parallelization ✅',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md239',1,'']]],
  ['build_20performance_20degradation_70',['Issue: Build performance degradation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md899',1,'']]],
  ['build_20recommended_71',['Quick Build (Recommended)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md927',1,'']]],
  ['build_20system_72',['build system',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md821',1,'Build System'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1184',1,'Build System']]],
  ['build_20targets_73',['Build Targets',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1186',1,'']]],
  ['build_20the_20project_74',['2. Build the Project',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md783',1,'']]],
  ['build_20the_20system_75',['3. Build the System',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md926',1,'']]],
  ['build_20troubleshooting_20guide_76',['Build Troubleshooting Guide',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html',1,'']]],
  ['build_20tt_77',['&lt;tt&gt;build&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md168',1,'']]],
  ['build_20workflow_78',['Recommended Build Workflow',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md669',1,'']]],
  ['build_5ftroubleshooting_2emd_79',['BUILD_TROUBLESHOOTING.md',['../d5/dd8/BUILD__TROUBLESHOOTING_8md.html',1,'']]],
  ['builder_80',['builder',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md1936',1,'1.2 Task Builder'],['../da/db6/md_docs_2FEATURES.html#autotoc_md596',1,'Message Builder'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1583',1,'Using Task Builder'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1733',1,'Using Task Builder'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1838',1,'Using the Task Builder']]],
  ['builder_20methods_81',['Builder Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1280',1,'']]],
  ['builder_20pattern_82',['builder pattern',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1522',1,'3. Builder Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md64',1,'3. Builder Pattern']]],
  ['builder_20performance_83',['Message Builder Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md454',1,'']]],
  ['building_20for_20development_84',['Building for Development',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md560',1,'']]],
  ['builds_85',['Example Builds',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2032',1,'']]],
  ['built_20in_20metrics_86',['1. Built-in Metrics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1083',1,'']]],
  ['bus_87',['bus',['../da/db6/md_docs_2FEATURES.html#autotoc_md579',1,'Message Bus'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md847',1,'Q: How do I create a message bus?']]],
  ['bus_20api_88',['bus api',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md885',1,'Message Bus API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md302',1,'Message Bus API']]],
  ['bus_20doesn_20t_20start_89',['Issue: Message bus doesn&apos;t start',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md897',1,'']]],
  ['bus_20interface_90',['4. Message Bus Interface',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md867',1,'']]],
  ['bus_20performance_91',['Message Bus Performance',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1039',1,'']]],
  ['bus_20usage_92',['bus usage',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md931',1,'1. Basic Message Bus Usage'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md876',1,'Step 4: Migrate Message Bus Usage']]],
  ['but_20recommended_93',['Step 5: Migrate to Patterns (Optional but Recommended)',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md877',1,'']]],
  ['by_20scale_94',['By Scale',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1600',1,'']]],
  ['by_20step_20migration_95',['Step-by-Step Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md870',1,'']]],
  ['by_20workload_20type_96',['By Workload Type',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1599',1,'']]]
];
