var searchData=
[
  ['name_20conflicts_0',['Issue 1: Target Name Conflicts',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md133',1,'']]],
  ['namespace_20and_20configmap_1',['Namespace and ConfigMap',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md193',1,'']]],
  ['namespace_3a_20tt_20container_5fmodule_20tt_2',['Namespace: &lt;tt&gt;container_module&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md4',1,'']]],
  ['namespace_3a_20tt_20database_20tt_3',['Namespace: &lt;tt&gt;database&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md29',1,'']]],
  ['namespace_3a_20tt_20kcenon_3a_3amessaging_3a_3acore_20tt_4',['Namespace: &lt;tt&gt;kcenon::messaging::core&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md39',1,'']]],
  ['namespace_3a_20tt_20kcenon_3a_3amessaging_3a_3aservices_20tt_5',['Namespace: &lt;tt&gt;kcenon::messaging::services&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md51',1,'']]],
  ['namespace_3a_20tt_20logger_20tt_6',['Namespace: &lt;tt&gt;logger&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md71',1,'']]],
  ['namespace_3a_20tt_20network_5fmodule_20tt_7',['Namespace: &lt;tt&gt;network_module&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md18',1,'']]],
  ['namespace_3a_20tt_20thread_5fsystem_20tt_8',['Namespace: &lt;tt&gt;thread_system&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md58',1,'']]],
  ['naming_20conventions_9',['Naming Conventions',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md293',1,'']]],
  ['navigation_10',['🚀 Quick Navigation',['../index.html#autotoc_md791',1,'']]],
  ['network_11',['network',['../d2/d64/md_docs_2architecture.html#autotoc_md111',1,'Network'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md859',1,'Network']]],
  ['network_20analysis_12',['Network Analysis',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md920',1,'']]],
  ['network_20bottlenecks_13',['Network Bottlenecks',['../df/d94/md_docs_2performance.html#autotoc_md495',1,'']]],
  ['network_20bridge_20task_203_201_14',['1. Network Bridge (Task 3.1)',['../d7/de1/md_docs_2phase3_2DESIGN.html#autotoc_md672',1,'']]],
  ['network_20client_20server_15',['3. Network Client/Server',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md351',1,'']]],
  ['network_20configuration_16',['3. Network Configuration',['../df/d94/md_docs_2performance.html#autotoc_md490',1,'']]],
  ['network_20debugging_17',['Network Debugging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md897',1,'']]],
  ['network_20optimization_18',['network optimization',['../df/d94/md_docs_2performance.html#autotoc_md482',1,'3. Network Optimization'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md205',1,'Network Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md919',1,'Network Optimization']]],
  ['network_20security_19',['Network Security',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md234',1,'']]],
  ['network_20statistics_20',['Network Statistics',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md899',1,'']]],
  ['network_20system_21',['network system',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md545',1,'2. Internal Network System'],['../d2/d64/md_docs_2architecture.html#autotoc_md95',1,'2. Network System'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md843',1,'2. Network System']]],
  ['network_20system_20api_22',['Network System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md17',1,'']]],
  ['network_20system_20performance_23',['Network System Performance',['../df/d94/md_docs_2performance.html#autotoc_md469',1,'']]],
  ['network_5fmodule_20tt_24',['Namespace: &lt;tt&gt;network_module&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md18',1,'']]],
  ['network_5fsystem_20strong_20communication_20layer_25',['7. &lt;strong&gt;network_system&lt;/strong&gt; - Communication Layer',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md964',1,'']]],
  ['new_26',['Directory Structure (New)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md386',1,'']]],
  ['new_20architecture_27',['v2.0 (New Architecture)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md588',1,'']]],
  ['new_20modules_28',['Creating New Modules',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md320',1,'']]],
  ['new_20users_29',['new users',['../index.html#autotoc_md792',1,'For New Users'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md974',1,'Option B: Automatic FetchContent (Easiest for New Users)']]],
  ['next_20phase_30',['Next Phase',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md642',1,'']]],
  ['next_20steps_31',['next steps',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md540',1,'Next Steps'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md360',1,'Next Steps']]],
  ['no_20external_20systems_32',['Alternative: Minimal Build (No External Systems)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md145',1,'']]],
  ['non_20functional_33',['Non-Functional',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md437',1,'']]],
  ['not_20found_34',['Issue 4: yaml-cpp Not Found',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md139',1,'']]],
  ['not_20found_20in_20external_20systems_35',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'']]],
  ['not_20implemented_36',['❌ Not Implemented',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md953',1,'']]],
  ['not_20supported_20macos_37',['Issue 3: grep -P Not Supported (macOS)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md137',1,'']]],
  ['notes_38',['Platform-Specific Notes',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md153',1,'']]],
  ['notification_20timeline_39',['Notification Timeline',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md616',1,'']]]
];
