var searchData=
[
  ['c_20dependencies_0',['C. Dependencies',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md449',1,'']]],
  ['c_20style_20guide_1',['C++ Style Guide',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md292',1,'']]],
  ['c_20testing_20and_20benchmarks_2',['C. Testing and Benchmarks',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1205',1,'']]],
  ['c_3a_20system_20installed_20packages_20production_3',['Option C: System-Installed Packages (Production)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1138',1,'']]],
  ['cache_20optimization_4',['Cache Optimization',['../df/d94/md_docs_2performance.html#autotoc_md644',1,'']]],
  ['can_20i_20still_20use_20simple_20publish_20subscribe_5',['Q: Can I still use simple publish/subscribe?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md503',1,'']]],
  ['can_20i_20use_20v1_20x_20and_20v2_200_20together_6',['Q: Can I use v1.x and v2.0 together?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md498',1,'']]],
  ['capabilities_7',['Current Capabilities',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md373',1,'']]],
  ['centos_8',['YUM Repository (RHEL/CentOS)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md177',1,'']]],
  ['chain_20of_20responsibility_20pattern_9',['11. Chain of Responsibility Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md266',1,'']]],
  ['chaining_10',['Pattern 3: Monadic Chaining',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md816',1,'']]],
  ['changes_11',['changes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md460',1,'1. Namespace Changes'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md742',1,'3. Container API Changes'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md479',1,'API Changes'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md459',1,'Breaking Changes'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md739',1,'Breaking Changes'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md769',1,'Risk 3: Client Breaking Changes']]],
  ['characteristics_12',['characteristics',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1147',1,'📊 Performance Characteristics'],['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md928',1,'Performance Characteristics'],['../df/d94/md_docs_2performance.html#autotoc_md628',1,'Scaling Characteristics']]],
  ['chat_20server_20chat_5fserver_20cpp_13',['1. Chat Server (chat_server.cpp)',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md357',1,'']]],
  ['chat_20server_20with_20monitoring_14',['Example 2: Real-Time Chat Server with Monitoring',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1144',1,'']]],
  ['chat_5fserver_20cpp_15',['1. Chat Server (chat_server.cpp)',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md357',1,'']]],
  ['checklist_16',['checklist',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md317',1,'Code Review Checklist'],['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md684',1,'Completion Checklist'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md783',1,'Completion Checklist'],['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md701',1,'Migration Checklist'],['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md734',1,'Phase 1.4 Execution Checklist'],['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md733',1,'Removal Checklist'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md773',1,'Risk Mitigation Checklist'],['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md794',1,'Validation Checklist']]],
  ['checks_17',['Health Checks',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md248',1,'']]],
  ['choose_20your_20build_20strategy_18',['Step 1: Choose Your Build Strategy',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1135',1,'']]],
  ['ci_20profile_20configurations_19',['CI Profile Configurations',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md674',1,'']]],
  ['clang_20tidy_20',['clang-tidy',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md854',1,'']]],
  ['class_3a_20tt_20database_5fmanager_20tt_21',['Class: &lt;tt&gt;database_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md30',1,'']]],
  ['class_3a_20tt_20event_5fbatch_5fprocessor_20tt_22',['Class: &lt;tt&gt;event_batch_processor&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md564',1,'']]],
  ['class_3a_20tt_20event_5fstream_20tt_23',['Class: &lt;tt&gt;event_stream&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md553',1,'']]],
  ['class_3a_20tt_20lock_5ffree_5fqueue_20tt_24',['Class: &lt;tt&gt;lock_free_queue&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md65',1,'']]],
  ['class_3a_20tt_20logger_5fmanager_20tt_25',['Class: &lt;tt&gt;logger_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md72',1,'']]],
  ['class_3a_20tt_20message_5fbus_20tt_26',['Class: &lt;tt&gt;message_bus&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md40',1,'']]],
  ['class_3a_20tt_20message_5fpipeline_20tt_27',['Class: &lt;tt&gt;message_pipeline&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md575',1,'']]],
  ['class_3a_20tt_20messaging_5fclient_20tt_28',['Class: &lt;tt&gt;messaging_client&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md23',1,'']]],
  ['class_3a_20tt_20messaging_5fserver_20tt_29',['Class: &lt;tt&gt;messaging_server&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md19',1,'']]],
  ['class_3a_20tt_20pipeline_5fbuilder_20tt_30',['Class: &lt;tt&gt;pipeline_builder&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md587',1,'']]],
  ['class_3a_20tt_20publisher_20tt_31',['Class: &lt;tt&gt;publisher&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md515',1,'']]],
  ['class_3a_20tt_20request_5fclient_20tt_32',['Class: &lt;tt&gt;request_client&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md538',1,'']]],
  ['class_3a_20tt_20request_5freply_5fhandler_20tt_33',['Class: &lt;tt&gt;request_reply_handler&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md532',1,'']]],
  ['class_3a_20tt_20request_5fserver_20tt_34',['Class: &lt;tt&gt;request_server&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md543',1,'']]],
  ['class_3a_20tt_20service_5fcontainer_20tt_35',['Class: &lt;tt&gt;service_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md52',1,'']]],
  ['class_3a_20tt_20subscriber_20tt_36',['Class: &lt;tt&gt;subscriber&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md523',1,'']]],
  ['class_3a_20tt_20thread_5fpool_20tt_37',['Class: &lt;tt&gt;thread_pool&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md59',1,'']]],
  ['class_3a_20tt_20value_5fcontainer_20tt_38',['Class: &lt;tt&gt;value_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md5',1,'']]],
  ['class_3a_20tt_20variant_20tt_39',['Class: &lt;tt&gt;variant&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md13',1,'']]],
  ['cleanup_40',['CMakeLists.txt Cleanup',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md729',1,'']]],
  ['clear_5fbuffer_20tt_41',['&lt;tt&gt;clear_buffer&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md562',1,'']]],
  ['client_42',['3. Test with Sample Client',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md359',1,'']]],
  ['client_20breaking_20changes_43',['Risk 3: Client Breaking Changes',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md769',1,'']]],
  ['client_20server_44',['3. Network Client/Server',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md351',1,'']]],
  ['clion_45',['CLion',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md285',1,'']]],
  ['clone_20and_20setup_46',['1. Clone and Setup',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md279',1,'']]],
  ['clone_20repository_47',['1. Clone Repository',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md172',1,'']]],
  ['clone_20the_20repository_48',['1. Clone the Repository',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md339',1,'']]],
  ['cmake_20configuration_49',['CMake Configuration',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md319',1,'']]],
  ['cmake_20configuration_20for_20guards_50',['CMake Configuration for Guards',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md732',1,'']]],
  ['cmake_20configuration_20options_51',['Unified CMake Configuration Options',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md666',1,'']]],
  ['cmake_20integration_52',['📦 CMake Integration',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1165',1,'']]],
  ['cmake_20presets_53',['CMake Presets',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md672',1,'']]],
  ['cmakelists_20txt_54',['Update CMakeLists.txt',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md468',1,'']]],
  ['cmakelists_20txt_20cleanup_55',['CMakeLists.txt Cleanup',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md729',1,'']]],
  ['cmakelists_20txt_20structure_56',['Updated CMakeLists.txt Structure',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md788',1,'']]],
  ['cmakepresets_20json_57',['CMakePresets.json',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md673',1,'']]],
  ['cmakepresets_20json_20already_20created_20in_20phase_200_58',['CMakePresets.json (Already created in Phase 0)',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md792',1,'']]],
  ['code_59',['Visual Studio Code',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md284',1,'']]],
  ['code_20allocation_60',['System Error Code Allocation',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md695',1,'']]],
  ['code_20at_20once_61',['Q: Do I need to migrate all code at once?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md499',1,'']]],
  ['code_20conflicts_62',['Issue: Error code conflicts',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md492',1,'']]],
  ['code_20definitions_63',['2. Error Code Definitions',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md810',1,'']]],
  ['code_20documentation_64',['code documentation',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md935',1,'Code Documentation'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md297',1,'Code Documentation']]],
  ['code_20examples_65',['Code Examples',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md484',1,'']]],
  ['code_20integration_66',['VS Code Integration',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1212',1,'']]],
  ['code_20inventory_67',['Legacy Code Inventory',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md706',1,'']]],
  ['code_20mapping_68',['A. Error Code Mapping',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md447',1,'']]],
  ['code_20quality_20and_20linting_69',['B. Code Quality and Linting',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1199',1,'']]],
  ['code_20range_70',['2. Error Code Range',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md461',1,'']]],
  ['code_20range_20conflict_71',['1. Error Code Range Conflict',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md376',1,'']]],
  ['code_20ranges_72',['Error Code Ranges',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md694',1,'']]],
  ['code_20removal_73',['Task 1.4: Legacy Code Removal',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md796',1,'']]],
  ['code_20removal_20plan_74',['Legacy Code Removal Plan',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html',1,'']]],
  ['code_20review_20checklist_75',['Code Review Checklist',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md317',1,'']]],
  ['code_20style_76',['code style',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1210',1,'Code Style'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1183',1,'Code Style']]],
  ['codes_77',['codes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md78',1,'Error Codes'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md79',1,'System Error Codes']]],
  ['codes_20to_20common_5fsystem_78',['1.1 Add messaging_system Error Codes to common_system',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md391',1,'']]],
  ['codes_20week_201_79',['Phase 1: Foundation and Error Codes (Week 1)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md390',1,'']]],
  ['coding_20standards_80',['Coding Standards',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md291',1,'']]],
  ['coexistence_20period_81',['Coexistence Period',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md417',1,'']]],
  ['collection_82',['collection',['../d2/d64/md_docs_2architecture.html#autotoc_md119',1,'Metrics Collection'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1030',1,'Metrics Collection']]],
  ['command_20pattern_83',['12. Command Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md267',1,'']]],
  ['comment_20guidelines_84',['Comment Guidelines',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md298',1,'']]],
  ['commit_20history_85',['Commit History',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md937',1,'']]],
  ['commit_20hooks_20optional_86',['Pre-commit Hooks (Optional)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1204',1,'']]],
  ['commit_20message_20format_87',['commit message format',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md316',1,'Commit Message Format'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1211',1,'Commit Message Format']]],
  ['common_20build_20issues_20and_20solutions_88',['Common Build Issues and Solutions',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md132',1,'']]],
  ['common_20issues_89',['common issues',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md244',1,'Common Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md328',1,'Troubleshooting Common Issues']]],
  ['common_20performance_20problems_90',['1. Common Performance Problems',['../df/d94/md_docs_2performance.html#autotoc_md655',1,'']]],
  ['common_20problems_91',['Common Problems',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1101',1,'']]],
  ['common_20system_20interfaces_92',['Common System Interfaces',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md687',1,'']]],
  ['common_5fsystem_93',['1.1 Add messaging_system Error Codes to common_system',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md391',1,'']]],
  ['common_5fsystem_20즉시_20통합_20최우선_94',['**Task 0.0 – common_system 즉시 통합 (최우선)**',['../d7/d01/md_docs_2REBUILD__PLAN.html#autotoc_md969',1,'']]],
  ['common_5fsystem_20strong_20the_20foundation_95',['1. &lt;strong&gt;common_system&lt;/strong&gt; - The Foundation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1121',1,'']]],
  ['communication_96',['communication',['../d2/d64/md_docs_2architecture.html#autotoc_md107',1,'Internal Communication'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1018',1,'Internal Communication'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md326',1,'Secure Communication']]],
  ['communication_20layer_97',['7. &lt;strong&gt;network_system&lt;/strong&gt; - Communication Layer',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1127',1,'']]],
  ['communication_20modules_98',['Data &amp; Communication Modules',['../index.html#autotoc_md960',1,'']]],
  ['communication_20plan_99',['Communication Plan',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md777',1,'']]],
  ['community_100',['4. Community',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md364',1,'']]],
  ['comparison_101',['Lock-free vs Mutex Comparison',['../df/d94/md_docs_2performance.html#autotoc_md627',1,'']]],
  ['compatibility_102',['compatibility',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md414',1,'Backward Compatibility'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md457',1,'Compatibility']]],
  ['compatibility_20layer_20design_103',['Compatibility Layer Design',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md743',1,'']]],
  ['compilation_20errors_20with_20old_20includes_104',['Issue: Compilation errors with old includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md491',1,'']]],
  ['compiler_20options_105',['Compiler Options',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md669',1,'']]],
  ['compiler_20options_20and_20feature_20flags_106',['Task 1.2: Compiler Options and Feature Flags',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md790',1,'']]],
  ['complete_20pub_20sub_20flow_20tt_20test_5fcomplete_5fpubsub_5fflow_20tt_107',['1. Complete Pub/Sub Flow (&lt;tt&gt;test_complete_pubsub_flow&lt;/tt&gt;)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md880',1,'']]],
  ['completed_108',['completed',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md425',1,'Phase 1: Foundation (Week 1) - ✅ COMPLETED'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md426',1,'Phase 2: Core Message Types (Week 2) - ✅ COMPLETED'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md427',1,'Phase 3: Message Queue (Week 3) - ✅ COMPLETED'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md428',1,'Phase 4: Backend Pattern (Week 4) - ✅ COMPLETED'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md429',1,'Phase 5: Topic Router (Week 5) - ✅ COMPLETED'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md430',1,'Phase 6: Message Bus (Week 6) - ✅ COMPLETED'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md431',1,'Phase 7: DI Container (Week 7) - ✅ COMPLETED'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md432',1,'Phase 8: Messaging Patterns (Week 8) - ✅ COMPLETED']]],
  ['completion_20checklist_109',['completion checklist',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md783',1,'Completion Checklist'],['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md684',1,'Completion Checklist']]],
  ['completion_20criteria_110',['Phase 0 Completion Criteria',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md702',1,'']]],
  ['completion_20summary_111',['Messaging System v2.0 - Project Completion Summary',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html',1,'']]],
  ['complex_20routing_20tt_20test_5fcomplex_5frouting_5fscenario_20tt_112',['2. Complex Routing (&lt;tt&gt;test_complex_routing_scenario&lt;/tt&gt;)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md881',1,'']]],
  ['compliance_113',['Compliance',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md240',1,'']]],
  ['component_20architecture_114',['component architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md93',1,'Component Architecture'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md387',1,'Component Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1004',1,'Component Architecture']]],
  ['component_20designs_115',['component designs',['../d7/de1/md_docs_2phase3_2DESIGN.html#autotoc_md834',1,'Component Designs'],['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md846',1,'Component Designs']]],
  ['component_20documentation_116',['🧩 Component Documentation',['../index.html#autotoc_md958',1,'']]],
  ['component_20performance_117',['Component Performance',['../df/d94/md_docs_2performance.html#autotoc_md625',1,'']]],
  ['component_20specific_20architecture_118',['Component-Specific Architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md88',1,'']]],
  ['components_119',['components',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md924',1,'Core Components'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md808',1,'Core Components']]],
  ['components_20tested_120',['Components Tested',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md893',1,'']]],
  ['compose_20deployment_121',['Docker Compose Deployment',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md197',1,'']]],
  ['composite_20pattern_122',['8. Composite Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md262',1,'']]],
  ['comprehensive_20test_20suite_20✅_123',['Phase 4: Comprehensive Test Suite ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md919',1,'']]],
  ['conclusion_124',['conclusion',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md949',1,'Conclusion'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md906',1,'Conclusion']]],
  ['concurrency_125',['concurrency',['../d2/d64/md_docs_2architecture.html#autotoc_md110',1,'Concurrency'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1021',1,'Concurrency']]],
  ['concurrency_20engine_126',['2. &lt;strong&gt;thread_system&lt;/strong&gt; - Concurrency Engine',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1122',1,'']]],
  ['concurrency_20patterns_127',['Concurrency Patterns',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md269',1,'']]],
  ['conditional_20features_20requires_20external_20systems_128',['⚠️ Conditional Features (Requires External Systems)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1115',1,'']]],
  ['config_20driven_20initialization_20tt_20test_5fconfig_5fdriven_5finitialization_20tt_129',['6. Config-Driven Initialization (&lt;tt&gt;test_config_driven_initialization&lt;/tt&gt;)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md885',1,'']]],
  ['configloader_20tests_20test_5fconfig_5floader_20cpp_130',['5. ConfigLoader Tests (test_config_loader.cpp)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md876',1,'']]],
  ['configmap_131',['Namespace and ConfigMap',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md193',1,'']]],
  ['configuration_132',['configuration',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1170',1,'🔧 Configuration'],['../df/d94/md_docs_2performance.html#autotoc_md651',1,'1. Thread Configuration'],['../df/d94/md_docs_2performance.html#autotoc_md652',1,'2. Memory Configuration'],['../df/d94/md_docs_2performance.html#autotoc_md653',1,'3. Network Configuration'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md319',1,'CMake Configuration'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md73',1,'Configuration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md181',1,'Configuration'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md32',1,'Configuration'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1035',1,'Dynamic Configuration'],['../d2/d64/md_docs_2architecture.html#autotoc_md124',1,'Dynamic Configuration'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md354',1,'Environment Configuration'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md745',1,'Feature Flag Configuration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md191',1,'HAProxy Configuration'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md283',1,'IDE Configuration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md219',1,'Load Balancer Configuration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md214',1,'Logging Configuration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md207',1,'PostgreSQL Configuration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md211',1,'Prometheus Configuration'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1050',1,'Runtime Configuration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md236',1,'SSL/TLS Configuration'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1034',1,'Static Configuration'],['../d2/d64/md_docs_2architecture.html#autotoc_md123',1,'Static Configuration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md203',1,'Thread Pool Configuration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md201',1,'ulimit Configuration']]],
  ['configuration_20design_20document_133',['Build Configuration Design Document',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html',1,'']]],
  ['configuration_20file_134',['Basic Configuration File',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md355',1,'']]],
  ['configuration_20file_20format_135',['System Configuration File Format',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md83',1,'']]],
  ['configuration_20file_20structure_136',['Configuration File Structure',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md182',1,'']]],
  ['configuration_20for_20guards_137',['CMake Configuration for Guards',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md732',1,'']]],
  ['configuration_20management_138',['configuration management',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1033',1,'Configuration Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md122',1,'Configuration Management']]],
  ['configuration_20options_139',['Unified CMake Configuration Options',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md666',1,'']]],
  ['configuration_20questions_140',['Configuration Questions',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1047',1,'']]],
  ['configuration_20reference_141',['Configuration Reference',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md82',1,'']]],
  ['configuration_20rollback_142',['Configuration Rollback',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md762',1,'']]],
  ['configuration_20structure_143',['Configuration Structure',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md42',1,'']]],
  ['configuration_20system_20task_203_204_144',['4. Configuration System (Task 3.4)',['../d7/de1/md_docs_2phase3_2DESIGN.html#autotoc_md838',1,'']]],
  ['configuration_20validation_145',['Task 1.3: Configuration Validation',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md793',1,'']]],
  ['configuration_20versioning_146',['Configuration Versioning',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md763',1,'']]],
  ['configuration_20with_20yaml_147',['Runtime Configuration with YAML',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1171',1,'']]],
  ['configurations_148',['CI Profile Configurations',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md674',1,'']]],
  ['configure_20build_149',['2. Configure Build',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md173',1,'']]],
  ['conflict_150',['1. Error Code Range Conflict',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md376',1,'']]],
  ['conflicts_151',['conflicts',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md133',1,'Issue 1: Target Name Conflicts'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md492',1,'Issue: Error code conflicts'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md771',1,'Risk 4: Dependency Version Conflicts']]],
  ['connection_20drops_152',['Problem: Connection Drops',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1104',1,'']]],
  ['connection_20errors_153',['Connection Errors',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1092',1,'']]],
  ['connection_20failed_154',['&quot;Database connection failed&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1096',1,'']]],
  ['connection_20management_155',['Connection Management',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md33',1,'']]],
  ['connection_20pool_20exhaustion_156',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1088',1,'']]],
  ['connection_20pool_20impact_157',['Connection Pool Impact',['../df/d94/md_docs_2performance.html#autotoc_md637',1,'']]],
  ['connection_20pool_20tuning_158',['Connection Pool Tuning',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md208',1,'']]],
  ['connection_20refused_159',['&quot;Connection refused&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1093',1,'']]],
  ['connection_20scaling_160',['Connection Scaling',['../df/d94/md_docs_2performance.html#autotoc_md633',1,'']]],
  ['connection_20timeout_161',['&quot;Connection timeout&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1094',1,'']]],
  ['connections_162',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1087',1,'']]],
  ['connectivity_163',['Test Connectivity',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1063',1,'']]],
  ['considerations_164',['considerations',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1039',1,'Future Considerations'],['../d2/d64/md_docs_2architecture.html#autotoc_md128',1,'Future Considerations'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md614',1,'Performance Considerations'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1026',1,'Security Considerations'],['../d2/d64/md_docs_2architecture.html#autotoc_md115',1,'Security Considerations']]],
  ['console_20output_165',['5. Direct Console Output',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md711',1,'']]],
  ['constructor_166',['constructor',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md60',1,'Constructor'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md565',1,'Constructor'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md577',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md31',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md6',1,'Constructor'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md544',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md41',1,'Constructor'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md554',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md66',1,'Constructor'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md539',1,'Constructor'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md533',1,'Constructor'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md588',1,'Constructor'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md524',1,'Constructor'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md516',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md24',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md20',1,'Constructor']]],
  ['consumer_20pattern_167',['14. Producer-Consumer Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md270',1,'']]],
  ['contact_20support_168',['📬 Contact &amp; Support',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1191',1,'']]],
  ['container_169',['container',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md721',1,'Before (Internal container)'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md818',1,'Message Container'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md822',1,'Week 1: Message Container']]],
  ['container_20api_170',['Service Container API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md50',1,'']]],
  ['container_20api_20changes_171',['3. Container API Changes',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md742',1,'']]],
  ['container_20api_20transformation_172',['Container API Transformation',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md720',1,'']]],
  ['container_20based_20data_20handling_173',['2. Container-Based Data Handling',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md350',1,'']]],
  ['container_20deployment_174',['container deployment',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1037',1,'Container Deployment'],['../d2/d64/md_docs_2architecture.html#autotoc_md126',1,'Container Deployment']]],
  ['container_20dsl_175',['1. Message Container DSL',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md809',1,'']]],
  ['container_20interface_176',['7.1 DI Container Interface',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md408',1,'']]],
  ['container_20system_177',['container system',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1005',1,'1. Container System'],['../d2/d64/md_docs_2architecture.html#autotoc_md94',1,'1. Container System'],['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md707',1,'1. Internal Container System']]],
  ['container_20system_20api_178',['Container System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md3',1,'']]],
  ['container_20system_20performance_179',['Container System Performance',['../df/d94/md_docs_2performance.html#autotoc_md629',1,'']]],
  ['container_20week_207_180',['Phase 7: DI Container (Week 7)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md407',1,'']]],
  ['container_20week_207_20✅_20completed_181',['Phase 7: DI Container (Week 7) - ✅ COMPLETED',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md431',1,'']]],
  ['container_5fmodule_20tt_182',['Namespace: &lt;tt&gt;container_module&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md4',1,'']]],
  ['container_5fsystem_20strong_20type_20safe_20data_183',['5. &lt;strong&gt;container_system&lt;/strong&gt; - Type-Safe Data',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1125',1,'']]],
  ['contents_184',['contents',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md511',1,'Table of Contents'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md1',1,'Table of Contents'],['../df/d94/md_docs_2performance.html#autotoc_md616',1,'Table of Contents'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1043',1,'Table of Contents'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md333',1,'Table of Contents'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md369',1,'Table of Contents'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md453',1,'Table of Contents']]],
  ['contracts_185',['contracts',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md693',1,'Database Contracts'],['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md690',1,'Execution Contracts'],['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md691',1,'Logging Contracts'],['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md692',1,'Monitoring Contracts']]],
  ['contribute_186',['How to Contribute',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1180',1,'']]],
  ['contributes_187',['🧩 How Each System Contributes',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1120',1,'']]],
  ['contributing_188',['🤝 Contributing',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1179',1,'']]],
  ['contributing_20guidelines_189',['Contributing Guidelines',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md314',1,'']]],
  ['contribution_20areas_190',['Contribution Areas',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1181',1,'']]],
  ['contributors_191',['Option A: Local Development (Recommended for Contributors)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1136',1,'']]],
  ['conventions_192',['Naming Conventions',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md293',1,'']]],
  ['conversion_193',['Pattern 1: Simple Function Conversion',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md814',1,'']]],
  ['coordination_20tt_20test_5fmulti_5fsubscriber_5fcoordination_20tt_194',['3. Multi-Subscriber Coordination (&lt;tt&gt;test_multi_subscriber_coordination&lt;/tt&gt;)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md882',1,'']]],
  ['core_20components_195',['core components',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md808',1,'Core Components'],['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md924',1,'Core Components']]],
  ['core_20dumps_196',['Debug Core Dumps',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1055',1,'']]],
  ['core_20features_20fully_20implemented_197',['✅ Core Features (Fully Implemented)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1113',1,'']]],
  ['core_20implementation_20✅_198',['Phase 2: Messaging Core Implementation ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md915',1,'']]],
  ['core_20infrastructure_199',['Core Infrastructure',['../index.html#autotoc_md959',1,'']]],
  ['core_20interfaces_200',['1.2 Create Core Interfaces',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md392',1,'']]],
  ['core_20message_20types_20week_202_201',['Phase 2: Core Message Types (Week 2)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md394',1,'']]],
  ['core_20message_20types_20week_202_20✅_20completed_202',['Phase 2: Core Message Types (Week 2) - ✅ COMPLETED',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md426',1,'']]],
  ['core_20methods_203',['Core Methods',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md7',1,'']]],
  ['core_20redesign_20design_20document_204',['Phase 2: Messaging Core Redesign - Design Document',['../d6/df5/md_docs_2phase2_2DESIGN.html',1,'']]],
  ['coverage_205',['coverage',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md894',1,'Feature Coverage'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1206',1,'Test Coverage'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1163',1,'Test Coverage'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md302',1,'Test Coverage'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md892',1,'Test Coverage']]],
  ['cpp_206',['cpp',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md357',1,'1. Chat Server (chat_server.cpp)'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md868',1,'1. MessagingContainer Tests (test_messaging_container.cpp)'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md870',1,'2. TopicRouter Tests (test_topic_router.cpp)'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md872',1,'3. MessageBus Tests (test_message_bus.cpp)'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md874',1,'4. TraceContext Tests (test_trace_context.cpp)'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md876',1,'5. ConfigLoader Tests (test_config_loader.cpp)'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md879',1,'End-to-End Integration (test_end_to_end.cpp)']]],
  ['cpp_20not_20found_207',['Issue 4: yaml-cpp Not Found',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md139',1,'']]],
  ['cppcheck_208',['cppcheck',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md855',1,'cppcheck'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1201',1,'Running Cppcheck']]],
  ['cpu_20bottlenecks_209',['Identify CPU Bottlenecks',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1074',1,'']]],
  ['cpu_20optimization_210',['cpu optimization',['../df/d94/md_docs_2performance.html#autotoc_md642',1,'2. CPU Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1073',1,'CPU Optimization']]],
  ['cpu_20usage_211',['High CPU Usage',['../df/d94/md_docs_2performance.html#autotoc_md656',1,'']]],
  ['cpu_20usage_20with_20small_20messages_212',['Issue 1: High CPU Usage with Small Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1086',1,'']]],
  ['create_20core_20interfaces_213',['1.2 Create Core Interfaces',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md392',1,'']]],
  ['create_5fenrichment_5fstage_20tt_214',['&lt;tt&gt;create_enrichment_stage&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md599',1,'']]],
  ['create_5flogging_5fstage_20tt_215',['&lt;tt&gt;create_logging_stage&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md597',1,'']]],
  ['create_5fretry_5fstage_20tt_216',['&lt;tt&gt;create_retry_stage&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md600',1,'']]],
  ['create_5fvalidation_5fstage_20tt_217',['&lt;tt&gt;create_validation_stage&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md598',1,'']]],
  ['created_20in_20phase_200_218',['CMakePresets.json (Already created in Phase 0)',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md792',1,'']]],
  ['creating_20new_20modules_219',['Creating New Modules',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md320',1,'']]],
  ['creation_220',['Step 3: Migrate Message Creation',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md471',1,'']]],
  ['creational_20patterns_221',['Creational Patterns',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md253',1,'']]],
  ['criteria_222',['criteria',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md782',1,'Business Criteria'],['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md702',1,'Phase 0 Completion Criteria'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md435',1,'Success Criteria'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md780',1,'Success Criteria'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md830',1,'Success Criteria'],['../d7/de1/md_docs_2phase3_2DESIGN.html#autotoc_md842',1,'Success Criteria'],['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md861',1,'Success Criteria'],['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md798',1,'Success Criteria'],['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md736',1,'Success Criteria'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md781',1,'Technical Criteria']]],
  ['current_223',['v1.9 (Current)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md748',1,'']]],
  ['current_20capabilities_224',['Current Capabilities',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md373',1,'']]],
  ['current_20limitations_225',['Current Limitations',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md940',1,'']]],
  ['current_20state_20analysis_226',['Current State Analysis',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md371',1,'']]],
  ['custom_20allocators_227',['Custom Allocators',['../df/d94/md_docs_2performance.html#autotoc_md641',1,'']]],
  ['custom_20build_20options_228',['Custom Build Options',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md346',1,'']]],
  ['custom_20image_229',['Build Custom Image',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md180',1,'']]],
  ['cutover_230',['Cutover',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md756',1,'']]]
];
