var searchData=
[
  ['c_20standard_20is_20required_0',['Q: What C++ standard is required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md776',1,'']]],
  ['c_20style_20guide_1',['C++ Style Guide',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md732',1,'']]],
  ['cache_20efficiency_2',['2. Increase vcpkg Cache Efficiency',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md185',1,'']]],
  ['cache_20optimization_3',['Cache Optimization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1010',1,'']]],
  ['caching_20service_4',['2. Implement Build Caching Service',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md193',1,'']]],
  ['can_20i_20expect_5',['Q: What throughput can I expect?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md789',1,'']]],
  ['can_20i_20still_20use_20simple_20publish_20subscribe_6',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md844',1,'']]],
  ['can_20i_20use_20v1_20x_20and_20v2_200_20together_7',['Q: Can I use v1.x and v2.0 together?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md839',1,'']]],
  ['cd_20인프라_8',['CI/CD 인프라',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html#autotoc_md1089',1,'']]],
  ['cd_20pipeline_9',['CI/CD Pipeline',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1033',1,'']]],
  ['centos_10',['YUM Repository (RHEL/CentOS)',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md642',1,'']]],
  ['chain_20of_20responsibility_20pattern_11',['11. Chain of Responsibility Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md15',1,'']]],
  ['changed_12',['changed',['../da/dee/md_docs_2CHANGELOG.html#autotoc_md475',1,'Changed'],['../da/dee/md_docs_2CHANGELOG.html#autotoc_md466',1,'Changed']]],
  ['changelog_13',['Messaging System Changelog',['../da/dee/md_docs_2CHANGELOG.html',1,'']]],
  ['changelog_2emd_14',['CHANGELOG.md',['../d3/d02/CHANGELOG_8md.html',1,'']]],
  ['changelog_5fko_2emd_15',['CHANGELOG_KO.md',['../d4/dfc/CHANGELOG__KO_8md.html',1,'']]],
  ['changes_16',['changes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md801',1,'1. Namespace Changes'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md820',1,'API Changes'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md800',1,'Breaking Changes']]],
  ['characteristics_17',['Scaling Characteristics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md994',1,'']]],
  ['chat_20server_20chat_5fserver_20cpp_18',['1. Chat Server (chat_server.cpp)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md876',1,'']]],
  ['chat_5fserver_20cpp_19',['1. Chat Server (chat_server.cpp)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md876',1,'']]],
  ['checklist_20',['checklist',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md757',1,'Code Review Checklist'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1072',1,'Production Checklist']]],
  ['checks_21',['Health Checks',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md713',1,'']]],
  ['ci_20cd_20인프라_22',['CI/CD 인프라',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html#autotoc_md1089',1,'']]],
  ['ci_20cd_20pipeline_23',['CI/CD Pipeline',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1033',1,'']]],
  ['ci_20performance_20optimization_24',['Windows CI Performance Optimization',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html',1,'']]],
  ['class_3a_20tt_20database_5fmanager_20tt_25',['Class: &lt;tt&gt;database_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md235',1,'']]],
  ['class_3a_20tt_20event_5fbatch_5fprocessor_20tt_26',['Class: &lt;tt&gt;event_batch_processor&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md79',1,'']]],
  ['class_3a_20tt_20event_5fstream_20tt_27',['Class: &lt;tt&gt;event_stream&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md68',1,'']]],
  ['class_3a_20tt_20lock_5ffree_5fqueue_20tt_28',['Class: &lt;tt&gt;lock_free_queue&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md270',1,'']]],
  ['class_3a_20tt_20logger_5fmanager_20tt_29',['Class: &lt;tt&gt;logger_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md277',1,'']]],
  ['class_3a_20tt_20message_5fbus_20tt_30',['Class: &lt;tt&gt;message_bus&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md245',1,'']]],
  ['class_3a_20tt_20message_5fpipeline_20tt_31',['Class: &lt;tt&gt;message_pipeline&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md90',1,'']]],
  ['class_3a_20tt_20messaging_5fclient_20tt_32',['Class: &lt;tt&gt;messaging_client&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md228',1,'']]],
  ['class_3a_20tt_20messaging_5fserver_20tt_33',['Class: &lt;tt&gt;messaging_server&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md224',1,'']]],
  ['class_3a_20tt_20pipeline_5fbuilder_20tt_34',['Class: &lt;tt&gt;pipeline_builder&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md102',1,'']]],
  ['class_3a_20tt_20publisher_20tt_35',['Class: &lt;tt&gt;publisher&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md30',1,'']]],
  ['class_3a_20tt_20request_5fclient_20tt_36',['Class: &lt;tt&gt;request_client&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md53',1,'']]],
  ['class_3a_20tt_20request_5freply_5fhandler_20tt_37',['Class: &lt;tt&gt;request_reply_handler&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md47',1,'']]],
  ['class_3a_20tt_20request_5fserver_20tt_38',['Class: &lt;tt&gt;request_server&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md58',1,'']]],
  ['class_3a_20tt_20service_5fcontainer_20tt_39',['Class: &lt;tt&gt;service_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md257',1,'']]],
  ['class_3a_20tt_20subscriber_20tt_40',['Class: &lt;tt&gt;subscriber&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md38',1,'']]],
  ['class_3a_20tt_20thread_5fpool_20tt_41',['Class: &lt;tt&gt;thread_pool&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md264',1,'']]],
  ['class_3a_20tt_20value_5fcontainer_20tt_42',['Class: &lt;tt&gt;value_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md210',1,'']]],
  ['class_3a_20tt_20variant_20tt_43',['Class: &lt;tt&gt;variant&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md218',1,'']]],
  ['classes_44',['Classes',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1129',1,'']]],
  ['clear_5fbuffer_20tt_45',['&lt;tt&gt;clear_buffer&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md77',1,'']]],
  ['client_46',['3. Test with Sample Client',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md878',1,'']]],
  ['client_20server_47',['3. Network Client/Server',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md870',1,'']]],
  ['clion_48',['CLion',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md725',1,'']]],
  ['clone_20and_20setup_49',['1. Clone and Setup',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md719',1,'']]],
  ['clone_20repository_50',['1. Clone Repository',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md637',1,'']]],
  ['clone_20the_20repository_51',['1. Clone the Repository',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md858',1,'']]],
  ['cmake_20configuration_52',['CMake Configuration',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md759',1,'']]],
  ['cmake_20integration_53',['CMake Integration',['../index.html#autotoc_md954',1,'']]],
  ['cmake_20structure_54',['CMake Structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1116',1,'']]],
  ['cmakelists_20txt_55',['Update CMakeLists.txt',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md809',1,'']]],
  ['code_56',['code',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1124',1,'Application Code'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md724',1,'Visual Studio Code']]],
  ['code_20at_20once_57',['Q: Do I need to migrate all code at once?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md840',1,'']]],
  ['code_20conflicts_58',['Issue: Error code conflicts',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md833',1,'']]],
  ['code_20documentation_59',['Code Documentation',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md737',1,'']]],
  ['code_20examples_60',['Code Examples',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md825',1,'']]],
  ['code_20of_20conduct_61',['Code of Conduct',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md493',1,'']]],
  ['code_20organization_20principles_62',['Code Organization Principles',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1132',1,'']]],
  ['code_20quality_63',['Code Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1035',1,'']]],
  ['code_20range_64',['2. Error Code Range',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md802',1,'']]],
  ['code_20review_20checklist_65',['Code Review Checklist',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md757',1,'']]],
  ['code_20reviews_66',['Code Reviews',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1038',1,'']]],
  ['codes_67',['codes',['../da/db6/md_docs_2FEATURES.html#autotoc_md548',1,'Error Codes'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md283',1,'Error Codes'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md284',1,'System Error Codes']]],
  ['coding_20standards_68',['coding standards',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md501',1,'Coding Standards'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md731',1,'Coding Standards']]],
  ['collection_69',['collection',['../d2/d64/md_docs_2architecture.html#autotoc_md347',1,'Metrics Collection'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md160',1,'Metrics Collection']]],
  ['command_20pattern_70',['12. Command Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md16',1,'']]],
  ['commands_71',['Benchmark Commands',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md976',1,'']]],
  ['comment_20guidelines_72',['Comment Guidelines',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md738',1,'']]],
  ['commit_20message_20format_73',['Commit Message Format',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md756',1,'']]],
  ['common_20bottlenecks_74',['Common Bottlenecks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md427',1,'']]],
  ['common_20build_20issues_20and_20solutions_75',['Common Build Issues and Solutions',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md597',1,'']]],
  ['common_20issues_76',['common issues',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md709',1,'Common Issues'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md768',1,'Troubleshooting Common Issues']]],
  ['common_20performance_20problems_77',['1. Common Performance Problems',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1021',1,'']]],
  ['common_20problems_78',['Common Problems',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md944',1,'']]],
  ['communication_79',['communication',['../d2/d64/md_docs_2architecture.html#autotoc_md335',1,'Internal Communication'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md148',1,'Internal Communication'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md766',1,'Secure Communication']]],
  ['communication_20modules_80',['Data &amp; Communication Modules',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1165',1,'']]],
  ['community_81',['4. Community',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md883',1,'']]],
  ['comparison_82',['comparison',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md437',1,'Feature Comparison'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md993',1,'Lock-free vs Mutex Comparison'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md181',1,'Performance Comparison']]],
  ['comparison_20with_20other_20systems_83',['Comparison with Other Systems',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md436',1,'']]],
  ['compatibility_84',['Compatibility',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md798',1,'']]],
  ['compilation_20errors_20with_20old_20includes_85',['Issue: Compilation errors with old includes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md832',1,'']]],
  ['complete_86',['complete',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1190',1,'✅ Core Components (Complete)'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1194',1,'✅ Documentation (Complete)'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1192',1,'✅ Infrastructure (Complete)'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1191',1,'✅ Patterns (Complete)'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1193',1,'✅ Testing &amp; Benchmarks (Complete)']]],
  ['compliance_87',['compliance',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md705',1,'Compliance'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1065',1,'Compliance']]],
  ['component_20architecture_88',['component architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md321',1,'Component Architecture'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md134',1,'Component Architecture']]],
  ['component_20documentation_89',['🧩 Component Documentation',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1163',1,'']]],
  ['component_20memory_20overhead_90',['Per-Component Memory Overhead',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md414',1,'']]],
  ['component_20organization_91',['Component Organization',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1109',1,'']]],
  ['component_20performance_92',['Component Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md991',1,'']]],
  ['component_20specific_20architecture_93',['Component-Specific Architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md316',1,'']]],
  ['components_20complete_94',['✅ Core Components (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1190',1,'']]],
  ['components_20tt_20include_20kcenon_20messaging_20core_20tt_95',['Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1110',1,'']]],
  ['compose_20deployment_96',['Docker Compose Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md662',1,'']]],
  ['composite_20pattern_97',['8. Composite Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md11',1,'']]],
  ['concerns_98',['Separation of Concerns',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1133',1,'']]],
  ['conclusion_99',['conclusion',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1081',1,'Conclusion'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md439',1,'Conclusion'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md203',1,'Conclusion']]],
  ['concurrency_100',['concurrency',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md151',1,'Concurrency'],['../d2/d64/md_docs_2architecture.html#autotoc_md338',1,'Concurrency']]],
  ['concurrency_20patterns_101',['Concurrency Patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md18',1,'']]],
  ['concurrent_20request_20performance_102',['Concurrent Request Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md411',1,'']]],
  ['conditional_20integration_20tests_103',['3. Conditional Integration Tests',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md190',1,'']]],
  ['conduct_104',['Code of Conduct',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md493',1,'']]],
  ['configmap_105',['Namespace and ConfigMap',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md658',1,'']]],
  ['configuration_106',['configuration',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1017',1,'1. Thread Configuration'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1018',1,'2. Memory Configuration'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1019',1,'3. Network Configuration'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md759',1,'CMake Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md646',1,'Configuration'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1051',1,'Configuration'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md278',1,'Configuration'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md237',1,'Configuration'],['../index.html#autotoc_md962',1,'Custom Configuration'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md165',1,'Dynamic Configuration'],['../d2/d64/md_docs_2architecture.html#autotoc_md352',1,'Dynamic Configuration'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md873',1,'Environment Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md656',1,'HAProxy Configuration'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md723',1,'IDE Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md684',1,'Load Balancer Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md679',1,'Logging Configuration'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1215',1,'Logging Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md672',1,'PostgreSQL Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md676',1,'Prometheus Configuration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md542',1,'Queue Configuration'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md893',1,'Runtime Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md701',1,'SSL/TLS Configuration'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md164',1,'Static Configuration'],['../d2/d64/md_docs_2architecture.html#autotoc_md351',1,'Static Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md668',1,'Thread Pool Configuration'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md666',1,'ulimit Configuration']]],
  ['configuration_20file_107',['Basic Configuration File',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md874',1,'']]],
  ['configuration_20file_20format_108',['System Configuration File Format',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md288',1,'']]],
  ['configuration_20file_20structure_109',['Configuration File Structure',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md647',1,'']]],
  ['configuration_20management_110',['configuration management',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md163',1,'Configuration Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md350',1,'Configuration Management']]],
  ['configuration_20questions_111',['Configuration Questions',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md890',1,'']]],
  ['configuration_20reference_112',['Configuration Reference',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md287',1,'']]],
  ['configuration_20structure_113',['Configuration Structure',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md247',1,'']]],
  ['configure_20build_114',['2. Configure Build',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md638',1,'']]],
  ['conflicts_115',['conflicts',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md598',1,'Issue 1: Target Name Conflicts'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md833',1,'Issue: Error code conflicts']]],
  ['connection_20drops_116',['Problem: Connection Drops',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md947',1,'']]],
  ['connection_20errors_117',['Connection Errors',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md935',1,'']]],
  ['connection_20failed_118',['&quot;Database connection failed&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md939',1,'']]],
  ['connection_20management_119',['Connection Management',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md238',1,'']]],
  ['connection_20pool_20exhaustion_120',['Issue 3: Database Connection Pool Exhaustion',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md931',1,'']]],
  ['connection_20pool_20impact_121',['Connection Pool Impact',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1003',1,'']]],
  ['connection_20pool_20tuning_122',['Connection Pool Tuning',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md673',1,'']]],
  ['connection_20refused_123',['&quot;Connection refused&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md936',1,'']]],
  ['connection_20scaling_124',['Connection Scaling',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md999',1,'']]],
  ['connection_20timeout_125',['&quot;Connection timeout&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md937',1,'']]],
  ['connections_126',['Issue 2: Memory Leak in Long-Running Connections',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md930',1,'']]],
  ['connectivity_127',['Test Connectivity',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md906',1,'']]],
  ['consideration_128',['Priority 3 (Future Consideration)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md198',1,'']]],
  ['considerations_129',['considerations',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md169',1,'Future Considerations'],['../d2/d64/md_docs_2architecture.html#autotoc_md356',1,'Future Considerations'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md129',1,'Performance Considerations'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md156',1,'Security Considerations'],['../d2/d64/md_docs_2architecture.html#autotoc_md343',1,'Security Considerations']]],
  ['constructor_130',['constructor',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md103',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md211',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md31',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md39',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md59',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md54',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md69',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md225',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md229',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md236',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md246',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md48',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md265',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md92',1,'Constructor'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md271',1,'Constructor'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md80',1,'Constructor']]],
  ['consumer_20pattern_131',['14. Producer-Consumer Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md19',1,'']]],
  ['contact_20support_132',['📬 Contact &amp; Support',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1242',1,'']]],
  ['container_133',['DI Container',['../da/db6/md_docs_2FEATURES.html#autotoc_md545',1,'']]],
  ['container_20api_134',['Service Container API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md255',1,'']]],
  ['container_20based_20data_20handling_135',['2. Container-Based Data Handling',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md869',1,'']]],
  ['container_20deployment_136',['container deployment',['../d2/d64/md_docs_2architecture.html#autotoc_md354',1,'Container Deployment'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md167',1,'Container Deployment']]],
  ['container_20system_137',['container system',['../d2/d64/md_docs_2architecture.html#autotoc_md322',1,'1. Container System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md135',1,'1. Container System']]],
  ['container_20system_20api_138',['Container System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md208',1,'']]],
  ['container_20system_20integration_139',['Container System Integration',['../da/db6/md_docs_2FEATURES.html#autotoc_md555',1,'']]],
  ['container_20system_20performance_140',['Container System Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md995',1,'']]],
  ['container_5fmodule_20tt_141',['Namespace: &lt;tt&gt;container_module&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md209',1,'']]],
  ['contention_20performance_142',['Queue Contention Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md399',1,'']]],
  ['contents_143',['contents',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md206',1,'Table of Contents'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md794',1,'Table of Contents'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md982',1,'Table of Contents'],['../da/db6/md_docs_2FEATURES.html#autotoc_md513',1,'Table of Contents'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md491',1,'Table of Contents'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md389',1,'Table of Contents'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md852',1,'Table of Contents'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md26',1,'Table of Contents'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md886',1,'Table of Contents']]],
  ['continuous_20performance_20monitoring_144',['Continuous Performance Monitoring',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md434',1,'']]],
  ['contribute_145',['How to Contribute',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1237',1,'']]],
  ['contributing_146',['🤝 Contributing',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1236',1,'']]],
  ['contributing_20guidelines_147',['Contributing Guidelines',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md754',1,'']]],
  ['contributing_20to_20messaging_20system_148',['Contributing to Messaging System',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html',1,'']]],
  ['contributing_2emd_149',['CONTRIBUTING.md',['../d2/d52/CONTRIBUTING_8md.html',1,'']]],
  ['conventions_150',['conventions',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1127',1,'Naming Conventions'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md733',1,'Naming Conventions']]],
  ['core_20components_20complete_151',['✅ Core Components (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1190',1,'']]],
  ['core_20components_20tt_20include_20kcenon_20messaging_20core_20tt_152',['Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1110',1,'']]],
  ['core_20documentation_153',['Core Documentation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1228',1,'']]],
  ['core_20dumps_154',['Debug Core Dumps',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md898',1,'']]],
  ['core_20infrastructure_155',['Core Infrastructure',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1164',1,'']]],
  ['core_20messaging_156',['Core Messaging',['../da/db6/md_docs_2FEATURES.html#autotoc_md515',1,'']]],
  ['core_20methods_157',['Core Methods',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md212',1,'']]],
  ['core_20performance_20metrics_158',['Core Performance Metrics',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md391',1,'']]],
  ['core_20tt_159',['Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1110',1,'']]],
  ['count_20impact_160',['Subscription Count Impact',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md403',1,'']]],
  ['coverage_161',['coverage',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md742',1,'Test Coverage'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1032',1,'Test Coverage']]],
  ['coverage_20report_162',['Coverage Report',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1225',1,'']]],
  ['cpp_163',['1. Chat Server (chat_server.cpp)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md876',1,'']]],
  ['cpp_20not_20found_164',['Issue 4: yaml-cpp Not Found',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md604',1,'']]],
  ['cpu_20bottlenecks_165',['Identify CPU Bottlenecks',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md917',1,'']]],
  ['cpu_20optimization_166',['cpu optimization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1008',1,'2. CPU Optimization'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md916',1,'CPU Optimization']]],
  ['cpu_20usage_167',['High CPU Usage',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1022',1,'']]],
  ['cpu_20usage_20with_20small_20messages_168',['Issue 1: High CPU Usage with Small Messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md929',1,'']]],
  ['create_20a_20message_20bus_169',['Q: How do I create a message bus?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md784',1,'']]],
  ['create_5fenrichment_5fstage_20tt_170',['&lt;tt&gt;create_enrichment_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md114',1,'']]],
  ['create_5flogging_5fstage_20tt_171',['&lt;tt&gt;create_logging_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md112',1,'']]],
  ['create_5fretry_5fstage_20tt_172',['&lt;tt&gt;create_retry_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md115',1,'']]],
  ['create_5fvalidation_5fstage_20tt_173',['&lt;tt&gt;create_validation_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md113',1,'']]],
  ['creating_20new_20modules_174',['Creating New Modules',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md760',1,'']]],
  ['creation_175',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md812',1,'']]],
  ['creation_20benchmarks_176',['Message Creation Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md394',1,'']]],
  ['creational_20patterns_177',['Creational Patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md2',1,'']]],
  ['ctest_20parallel_20execution_20✅_178',['2. CTest Parallel Execution ✅',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md179',1,'']]],
  ['current_20limitations_179',['Current Limitations',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1069',1,'']]],
  ['custom_20allocators_180',['Custom Allocators',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1007',1,'']]],
  ['custom_20build_20options_181',['Custom Build Options',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md865',1,'']]],
  ['custom_20configuration_182',['Custom Configuration',['../index.html#autotoc_md962',1,'']]],
  ['custom_20image_183',['Build Custom Image',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md645',1,'']]]
];
