var searchData=
[
  ['range_0',['2. Error Code Range',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md462',1,'']]],
  ['range_20conflict_1',['1. Error Code Range Conflict',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md376',1,'']]],
  ['ranges_2',['Error Code Ranges',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md695',1,'']]],
  ['rate_20limiting_3',['rate limiting',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md239',1,'Rate Limiting'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md327',1,'Rate Limiting']]],
  ['read_20replicas_4',['Read Replicas',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md224',1,'']]],
  ['readme_2emd_5',['readme.md',['../da/ddd/README_8md.html',1,'(Global Namespace)'],['../d4/d84/docs_2README_8md.html',1,'(Global Namespace)']]],
  ['real_20time_20chat_20server_20with_20monitoring_6',['Example 2: Real-Time Chat Server with Monitoring',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1178',1,'']]],
  ['real_20world_20examples_7',['🔥 Real-World Examples',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1176',1,'']]],
  ['rebuild_5fplan_2emd_8',['REBUILD_PLAN.md',['../db/d5d/REBUILD__PLAN_8md.html',1,'']]],
  ['recommendations_9',['Additional Recommendations',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1118',1,'']]],
  ['recommended_10',['recommended',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1188',1,'Local Development (Recommended)'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md345',1,'Quick Build (Recommended)'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md474',1,'Step 5: Migrate to Patterns (Optional but Recommended)']]],
  ['recommended_20build_20workflow_11',['Recommended Build Workflow',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md141',1,'']]],
  ['recommended_20for_20contributors_12',['Option A: Local Development (Recommended for Contributors)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1170',1,'']]],
  ['recommended_20next_20sprint_13',['Priority 2 (Recommended - Next Sprint)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1133',1,'']]],
  ['recommended_20requirements_14',['Recommended Requirements',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md164',1,'']]],
  ['recovery_15',['recovery',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md226',1,'Backup and Recovery'],['../d2/d64/md_docs_2architecture.html#autotoc_md113',1,'Error Recovery'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1025',1,'Error Recovery'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md231',1,'Service Recovery']]],
  ['recovery_20plan_16',['Disaster Recovery Plan',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md232',1,'']]],
  ['recovery_20procedures_17',['Recovery Procedures',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md230',1,'']]],
  ['recovery_20strategies_18',['Error Recovery Strategies',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md81',1,'']]],
  ['redesign_20design_20document_19',['Phase 2: Messaging Core Redesign - Design Document',['../d6/df5/md_docs_2phase2_2DESIGN.html',1,'']]],
  ['reduce_20fetchcontent_20downloads_20',['3. Reduce FetchContent Downloads',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1122',1,'']]],
  ['refactoring_20design_20document_21',['Phase 1: Build System and Dependency Refactoring - Design Document',['../d5/d7c/md_docs_2phase1_2DESIGN.html',1,'']]],
  ['reference_22',['reference',['../db/d91/md_docs_2API__REFERENCE.html',1,'API Reference'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md82',1,'Configuration Reference'],['../dc/d3e/md_docs_2PATTERNS__API.html',1,'Messaging Patterns API Reference']]],
  ['references_23',['references',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md451',1,'D. References'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1140',1,'References']]],
  ['refused_24',['&quot;Connection refused&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1094',1,'']]],
  ['register_25',['Risk Register',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md766',1,'']]],
  ['register_5fhandler_20tt_26',['register_handler tt',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md547',1,'&lt;tt&gt;register_handler&lt;/tt&gt;'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md537',1,'&lt;tt&gt;register_handler&lt;/tt&gt;']]],
  ['regression_27',['Risk 1: Performance Regression',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md768',1,'']]],
  ['related_20documentation_28',['Related Documentation',['../d2/d64/md_docs_2architecture.html#autotoc_md87',1,'']]],
  ['release_29',['v1.10 (Transition Release)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md750',1,'']]],
  ['release_20build_20for_20tests_30',['1. Use Release Build for Tests',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1120',1,'']]],
  ['release_20timeline_31',['Release Timeline',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md748',1,'']]],
  ['relocation_20map_32',['B. File Relocation Map',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md449',1,'']]],
  ['removal_33',['Task 1.4: Legacy Code Removal',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md797',1,'']]],
  ['removal_20checklist_34',['Removal Checklist',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md734',1,'']]],
  ['removal_20plan_35',['Legacy Code Removal Plan',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html',1,'']]],
  ['removal_20verification_36',['Post-Removal Verification',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md736',1,'']]],
  ['remove_37',['Legacy Dependencies to Remove',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md697',1,'']]],
  ['remove_5fstage_20tt_38',['&lt;tt&gt;remove_stage&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md581',1,'']]],
  ['replacement_20mapping_39',['Detailed Replacement Mapping',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md714',1,'']]],
  ['replay_20tt_40',['&lt;tt&gt;replay&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md560',1,'']]],
  ['replicas_41',['Read Replicas',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md224',1,'']]],
  ['reply_20migration_42',['Example 2: Request-Reply Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md487',1,'']]],
  ['reply_20pattern_43',['reply pattern',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md411',1,'8.2 Request-Reply Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md606',1,'Request-Reply Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md531',1,'Request-Reply Pattern'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md476',1,'Request-Reply Pattern']]],
  ['repository_44',['repository',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md172',1,'1. Clone Repository'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md339',1,'1. Clone the Repository']]],
  ['repository_20rhel_20centos_45',['YUM Repository (RHEL/CentOS)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md177',1,'']]],
  ['repository_20ubuntu_20debian_46',['APT Repository (Ubuntu/Debian)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md176',1,'']]],
  ['request_20reply_20migration_47',['Example 2: Request-Reply Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md487',1,'']]],
  ['request_20reply_20pattern_48',['request reply pattern',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md411',1,'8.2 Request-Reply Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md531',1,'Request-Reply Pattern'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md476',1,'Request-Reply Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md606',1,'Request-Reply Pattern']]],
  ['request_20response_49',['Request-Response',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md46',1,'']]],
  ['request_20response_20flow_50',['request response flow',['../d2/d64/md_docs_2architecture.html#autotoc_md100',1,'Request-Response Flow'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1012',1,'Request-Response Flow']]],
  ['request_20tt_51',['request tt',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md542',1,'&lt;tt&gt;request&lt;/tt&gt;'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md536',1,'&lt;tt&gt;request&lt;/tt&gt;']]],
  ['request_5fclient_20tt_52',['Class: &lt;tt&gt;request_client&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md539',1,'']]],
  ['request_5freply_5fhandler_20tt_53',['Class: &lt;tt&gt;request_reply_handler&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md533',1,'']]],
  ['request_5fserver_20tt_54',['Class: &lt;tt&gt;request_server&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md544',1,'']]],
  ['required_55',['Required',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md902',1,'']]],
  ['requirements_56',['requirements',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md162',1,'Hardware Requirements'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md163',1,'Minimum Requirements'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md165',1,'Production Requirements'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md164',1,'Recommended Requirements'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md161',1,'System Requirements'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md335',1,'System Requirements']]],
  ['requires_20external_20systems_57',['⚠️ Conditional Features (Requires External Systems)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1149',1,'']]],
  ['resource_20allocation_58',['Resource Allocation',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md222',1,'']]],
  ['resource_20usage_59',['Resource Usage',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md931',1,'']]],
  ['resources_60',['Additional Resources',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md507',1,'']]],
  ['response_61',['Request-Response',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md46',1,'']]],
  ['response_20flow_62',['response flow',['../d2/d64/md_docs_2architecture.html#autotoc_md100',1,'Request-Response Flow'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1012',1,'Request-Response Flow']]],
  ['responsibility_20matrix_63',['Responsibility Matrix',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md713',1,'']]],
  ['responsibility_20pattern_64',['11. Chain of Responsibility Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md266',1,'']]],
  ['result_20기반_20플로우_20제로화_20strong_65',['&lt;strong&gt;Task 2.2 – Result 기반 플로우 제로화&lt;/strong&gt;',['../d7/d01/md_docs_2REBUILD__PLAN.html#autotoc_md982',1,'']]],
  ['result_20based_66',['After (Result-based)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md717',1,'']]],
  ['result_20t_20migration_67',['Week 2: Result&lt;T&gt; Migration',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md824',1,'']]],
  ['result_20t_20migration_20patterns_68',['Result&lt;T&gt; Migration Patterns',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md814',1,'']]],
  ['results_69',['Benchmark Results',['../df/d94/md_docs_2performance.html#autotoc_md621',1,'']]],
  ['retrieving_20values_70',['Retrieving Values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md10',1,'']]],
  ['return_5fif_5ferror_71',['Pattern 2: Error Propagation with RETURN_IF_ERROR',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md816',1,'']]],
  ['review_20checklist_72',['Code Review Checklist',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md317',1,'']]],
  ['review_20task_204_204_73',['4. Security Review (Task 4.4)',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md851',1,'']]],
  ['rhel_74',['Linux (Fedora/RHEL)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md156',1,'']]],
  ['rhel_20centos_75',['YUM Repository (RHEL/CentOS)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md177',1,'']]],
  ['risk_76',['risk',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md443',1,'High Risk'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md445',1,'Low Risk'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md444',1,'Medium Risk']]],
  ['risk_201_3a_20performance_20regression_77',['Risk 1: Performance Regression',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md768',1,'']]],
  ['risk_202_3a_20data_20loss_20during_20migration_78',['Risk 2: Data Loss During Migration',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md769',1,'']]],
  ['risk_203_3a_20client_20breaking_20changes_79',['Risk 3: Client Breaking Changes',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md770',1,'']]],
  ['risk_204_3a_20dependency_20version_20conflicts_80',['Risk 4: Dependency Version Conflicts',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md772',1,'']]],
  ['risk_205_3a_20build_20system_20issues_81',['Risk 5: Build System Issues',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md773',1,'']]],
  ['risk_20assessment_82',['risk assessment',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html',1,'Migration Strategy and Risk Assessment'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md442',1,'Risk Assessment']]],
  ['risk_20items_83',['risk items',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md767',1,'High Risk Items'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md771',1,'Medium Risk Items']]],
  ['risk_20mitigation_20checklist_84',['Risk Mitigation Checklist',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md774',1,'']]],
  ['risk_20register_85',['Risk Register',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md766',1,'']]],
  ['rollback_86',['rollback',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md763',1,'Configuration Rollback'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md759',1,'Database Migration Rollback']]],
  ['rollback_20if_20issues_20detected_87',['Rollback (If Issues Detected)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md758',1,'']]],
  ['rollback_20plan_88',['rollback plan',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md805',1,'Rollback Plan'],['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md864',1,'Rollback Plan']]],
  ['rollback_20playbook_89',['Ansible Rollback Playbook',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md765',1,'']]],
  ['rollback_20script_90',['Rollback Script',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md761',1,'']]],
  ['rollback_20strategy_91',['Rollback Strategy',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md754',1,'']]],
  ['router_92',['router',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md813',1,'4. Topic Router'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md465',1,'5. Topic Router'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md821',1,'Topic Router'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md826',1,'Week 4: Topic Router']]],
  ['router_20and_20pub_20sub_20week_205_93',['Phase 5: Topic Router and Pub/Sub (Week 5)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md403',1,'']]],
  ['router_20api_94',['Topic Router API',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md483',1,'']]],
  ['router_20implementation_95',['5.1 Topic Router Implementation',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md404',1,'']]],
  ['router_20week_205_20✅_20completed_96',['Phase 5: Topic Router (Week 5) - ✅ COMPLETED',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md429',1,'']]],
  ['routing_20tt_20test_5fcomplex_5frouting_5fscenario_20tt_97',['2. Complex Routing (&lt;tt&gt;test_complex_routing_scenario&lt;/tt&gt;)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md882',1,'']]],
  ['rules_98',['rules',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md220',1,'Auto-scaling Rules'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md235',1,'Firewall Rules']]],
  ['run_99',['2. Build and Run',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md358',1,'']]],
  ['run_20tests_100',['run tests',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1195',1,'Run Tests'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md890',1,'Run Tests']]],
  ['run_20your_20application_101',['Step 3: Run Your Application',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1174',1,'']]],
  ['runners_102',['1. Use Self-Hosted Runners',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1128',1,'']]],
  ['running_20connections_103',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1088',1,'']]],
  ['running_20cppcheck_104',['Running Cppcheck',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1235',1,'']]],
  ['running_20process_105',['Attach to Running Process',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1055',1,'']]],
  ['running_20specific_20tests_106',['Running Specific Tests',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1241',1,'']]],
  ['runtime_20configuration_107',['Runtime Configuration',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1051',1,'']]],
  ['runtime_20configuration_20with_20yaml_108',['Runtime Configuration with YAML',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1205',1,'']]],
  ['runtime_20dependencies_109',['runtime dependencies',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md502',1,'Q: Are there any runtime dependencies?'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md169',1,'Runtime Dependencies'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md337',1,'Runtime Dependencies']]],
  ['runtime_20issues_110',['Runtime Issues',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md330',1,'']]]
];
