var searchData=
[
  ['macos_0',['macos',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md724',1,'Issue 3: grep -P Not Supported (macOS)'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md983',1,'macOS'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md741',1,'macOS'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md874',1,'Using Instruments (macOS)']]],
  ['macro_20based_20logging_1',['Alternative C: Macro-based Logging',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md19',1,'']]],
  ['management_2',['management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1402',1,'Checkpoint Management'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md222',1,'Configuration Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md409',1,'Configuration Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md297',1,'Connection Management'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2110',1,'Dependency Management'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md791',1,'Memory Management'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md209',1,'Memory Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md396',1,'Memory Management'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2063',1,'Phase 7: Monitoring &amp; Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md326',1,'Pool Management'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1209',1,'Resource Management'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1453',1,'Schedule Management'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md771',1,'Secrets Management'],['../da/db6/md_docs_2FEATURES.html#autotoc_md634',1,'Subscription Management'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1403',1,'Subtask Management'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1471',1,'Task Management']]],
  ['managers_3',['Using Package Managers',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md762',1,'']]],
  ['managing_20schedules_4',['Managing Schedules',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1855',1,'']]],
  ['many_20topics_5',['Issue 5: Performance Degradation with Many Topics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1055',1,'']]],
  ['mapping_20concepts_6',['Mapping Concepts',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1768',1,'']]],
  ['matching_20performance_7',['Pattern Matching Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md461',1,'']]],
  ['matrix_8',['Feature Matrix',['../da/db6/md_docs_2FEATURES.html#autotoc_md658',1,'']]],
  ['measurements_9',['Latency Measurements',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1140',1,'']]],
  ['mechanism_10',['Retry Mechanism',['../da/db6/md_docs_2FEATURES.html#autotoc_md607',1,'']]],
  ['medium_20term_20architectural_11',['Medium-Term (Architectural)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md246',1,'']]],
  ['memory_12',['&quot;Out of memory&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1064',1,'']]],
  ['memory_20configuration_13',['2. Memory Configuration',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1169',1,'']]],
  ['memory_20debugging_14',['Memory Debugging',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1021',1,'']]],
  ['memory_20errors_15',['Memory Errors',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1063',1,'']]],
  ['memory_20leak_20in_20long_20running_20connections_16',['Issue 2: Memory Leak in Long-Running Connections',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1052',1,'']]],
  ['memory_20leaks_17',['Memory Leaks',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1174',1,'']]],
  ['memory_20management_18',['memory management',['../d2/d64/md_docs_2architecture.html#autotoc_md396',1,'Memory Management'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md209',1,'Memory Management'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md791',1,'Memory Management']]],
  ['memory_20optimization_19',['memory optimization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1156',1,'1. Memory Optimization'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1041',1,'Memory Optimization'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1703',1,'Memory Optimization']]],
  ['memory_20overhead_20',['Per-Component Memory Overhead',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md481',1,'']]],
  ['memory_20performance_21',['Memory Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1141',1,'']]],
  ['memory_20result_20backend_22',['4.2 In-Memory Result Backend',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2054',1,'']]],
  ['memory_20safety_23',['Memory Safety',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1188',1,'']]],
  ['memory_20scaling_24',['Memory Scaling',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md482',1,'']]],
  ['memory_20usage_25',['memory usage',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md833',1,'High Memory Usage'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1989',1,'High Memory Usage'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md480',1,'Memory Usage'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1070',1,'Problem: High Memory Usage']]],
  ['memory_20usage_20analysis_26',['Memory Usage Analysis',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1042',1,'']]],
  ['memory_20usage_20growing_27',['Memory Usage Growing',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1978',1,'']]],
  ['memory_5fresult_5fbackend_28',['memory_result_backend',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1445',1,'memory_result_backend'],['../dd/db9/md_docs_2task_2API__REFERENCE__KO.html#autotoc_md1564',1,'memory_result_backend']]],
  ['message를_20상속_29',['1. Task는 Message를 상속',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2085',1,'']]],
  ['message_20api_30',['Message API',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md943',1,'']]],
  ['message_20based_20tasks_31',['1. Message-Based Tasks',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1627',1,'']]],
  ['message_20broker_32',['Message Broker',['../da/db6/md_docs_2FEATURES.html#autotoc_md589',1,'']]],
  ['message_20builder_33',['Message Builder',['../da/db6/md_docs_2FEATURES.html#autotoc_md629',1,'']]],
  ['message_20builder_20performance_34',['Message Builder Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md454',1,'']]],
  ['message_20bus_35',['message bus',['../da/db6/md_docs_2FEATURES.html#autotoc_md588',1,'Message Bus'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md906',1,'Q: How do I create a message bus?']]],
  ['message_20bus_20api_36',['message bus api',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md944',1,'Message Bus API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md302',1,'Message Bus API']]],
  ['message_20bus_20doesn_20t_20start_37',['Issue: Message bus doesn&apos;t start',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md956',1,'']]],
  ['message_20bus_20interface_38',['4. Message Bus Interface',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md926',1,'']]],
  ['message_20bus_20performance_39',['Message Bus Performance',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1121',1,'']]],
  ['message_20bus_20usage_40',['message bus usage',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md990',1,'1. Basic Message Bus Usage'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md935',1,'Step 4: Migrate Message Bus Usage']]],
  ['message_20creation_41',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md934',1,'']]],
  ['message_20creation_20benchmarks_42',['Message Creation Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md453',1,'']]],
  ['message_20flow_43',['Message Flow',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2105',1,'']]],
  ['message_20format_44',['Commit Message Format',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md878',1,'']]],
  ['message_20pipeline_45',['message pipeline',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md951',1,'Example 4: Message Pipeline'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md678',1,'Message Pipeline'],['../da/db6/md_docs_2FEATURES.html#autotoc_md595',1,'Message Pipeline'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2117',1,'Message Pipeline']]],
  ['message_20pipeline_20pattern_46',['message pipeline pattern',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md146',1,'Message Pipeline Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md181',1,'Message Pipeline Pattern']]],
  ['message_20processing_47',['message processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1054',1,'Issue 4: Deadlock in Message Processing'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1068',1,'Problem: Slow Message Processing']]],
  ['message_20processing_20pipeline_48',['message processing pipeline',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md199',1,'Message Processing Pipeline'],['../d2/d64/md_docs_2architecture.html#autotoc_md386',1,'Message Processing Pipeline']]],
  ['message_20queue_49',['Message Queue',['../da/db6/md_docs_2FEATURES.html#autotoc_md636',1,'']]],
  ['message_20queue_20systems_50',['From Message Queue Systems',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1767',1,'']]],
  ['message_20serialization_51',['Message Serialization',['../da/db6/md_docs_2FEATURES.html#autotoc_md630',1,'']]],
  ['message_20structure_52',['message structure',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md925',1,'3. Message Structure'],['../da/db6/md_docs_2FEATURES.html#autotoc_md628',1,'Message Structure']]],
  ['message_20types_53',['Message Types',['../da/db6/md_docs_2FEATURES.html#autotoc_md627',1,'']]],
  ['message_5fbus_54',['message_bus',['../d4/d54/md_docs_2API__REFERENCE__KO.html#autotoc_md356',1,'']]],
  ['message_5fbus_20tt_55',['Class: &lt;tt&gt;message_bus&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md304',1,'']]],
  ['message_5fpipeline_20tt_56',['Class: &lt;tt&gt;message_pipeline&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md149',1,'']]],
  ['messagefiltercallable_57',['messagefiltercallable',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md699',1,'MessageFilterCallable'],['../da/db6/md_docs_2FEATURES.html#autotoc_md616',1,'MessageFilterCallable']]],
  ['messageprocessorcallable_58',['messageprocessorcallable',['../da/db6/md_docs_2FEATURES.html#autotoc_md615',1,'MessageProcessorCallable'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md698',1,'MessageProcessorCallable']]],
  ['messages_59',['messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1056',1,'Error Messages'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1051',1,'Issue 1: High CPU Usage with Small Messages']]],
  ['messages_20not_20being_20delivered_60',['Issue: Messages not being delivered',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md957',1,'']]],
  ['messages_20tasks_20that_20always_20fail_61',['Q: How do I handle poison messages (tasks that always fail)?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2000',1,'']]],
  ['messagetransformercallable_62',['messagetransformercallable',['../da/db6/md_docs_2FEATURES.html#autotoc_md617',1,'MessageTransformerCallable'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md700',1,'MessageTransformerCallable']]],
  ['messaging_63',['Core Messaging',['../da/db6/md_docs_2FEATURES.html#autotoc_md587',1,'']]],
  ['messaging_20backends_20tt_64',['messaging backends tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1301',1,'백엔드 (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1263',1,'Backends (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)']]],
  ['messaging_20core_20tt_65',['messaging core tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1299',1,'핵심 컴포넌트 (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1261',1,'Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)']]],
  ['messaging_20event_20bridge_20integration_66',['Messaging Event Bridge Integration',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1092',1,'']]],
  ['messaging_20interfaces_20tt_67',['messaging interfaces tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1300',1,'인터페이스 (&lt;tt&gt;include/kcenon/messaging/interfaces/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1262',1,'Interfaces (&lt;tt&gt;include/kcenon/messaging/interfaces/&lt;/tt&gt;)']]],
  ['messaging_20patterns_68',['Messaging Patterns',['../da/db6/md_docs_2FEATURES.html#autotoc_md591',1,'']]],
  ['messaging_20patterns_20api_20reference_69',['Messaging Patterns API Reference',['../df/dde/md_docs_2advanced_2PATTERNS__API.html',1,'']]],
  ['messaging_20patterns_20tt_70',['messaging patterns tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1302',1,'패턴 (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1264',1,'Patterns (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)']]],
  ['messaging_20system_71',['Contributing to Messaging System',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html',1,'']]],
  ['messaging_20system_20기능_72',['Messaging System 기능',['../d4/d0c/md_docs_2FEATURES__KO.html',1,'']]],
  ['messaging_20system_20문서_73',['Messaging System 문서',['../d8/d0a/md_docs_2README__KO.html',1,'']]],
  ['messaging_20system_20변경_20이력_74',['Messaging System 변경 이력',['../db/d9f/md_docs_2CHANGELOG__KO.html',1,'']]],
  ['messaging_20system_20성능_20벤치마크_75',['Messaging System 성능 벤치마크',['../d5/ddb/md_docs_2BENCHMARKS__KO.html',1,'']]],
  ['messaging_20system_20아키텍처_76',['Messaging System 아키텍처',['../de/de3/md_docs_2ARCHITECTURE__KO.html',1,'']]],
  ['messaging_20system_20프로덕션_20품질_77',['Messaging System 프로덕션 품질',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html',1,'']]],
  ['messaging_20system_20프로젝트_20구조_78',['Messaging System 프로젝트 구조',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html',1,'']]],
  ['messaging_20system_20api_20레퍼런스_79',['Messaging System API 레퍼런스',['../d4/d54/md_docs_2API__REFERENCE__KO.html',1,'']]],
  ['messaging_20system_20changelog_80',['Messaging System Changelog',['../da/dee/md_docs_2CHANGELOG.html',1,'']]],
  ['messaging_20system_20features_81',['Messaging System Features',['../da/db6/md_docs_2FEATURES.html',1,'']]],
  ['messaging_20system_20performance_20benchmarks_82',['Messaging System Performance Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html',1,'']]],
  ['messaging_20system_20production_20quality_83',['Messaging System Production Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html',1,'']]],
  ['messaging_20system_20project_20structure_84',['Messaging System Project Structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'']]],
  ['messaging_20task_20tt_85',['messaging task tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1303',1,'태스크 큐 (&lt;tt&gt;include/kcenon/messaging/task/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1265',1,'Task Queue (&lt;tt&gt;include/kcenon/messaging/task/&lt;/tt&gt;)']]],
  ['messaging_5fclient_20tt_86',['Class: &lt;tt&gt;messaging_client&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md287',1,'']]],
  ['messaging_5fserver_20tt_87',['Class: &lt;tt&gt;messaging_server&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md283',1,'']]],
  ['messaging_5fsystem에서의_20사용_20예시_88',['messaging_system에서의 사용 예시',['../dd/da0/md_docs_2adr_2001-logging-architecture__KO.html#autotoc_md48',1,'']]],
  ['messaging_5fsystem_89',['messaging_system',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md897',1,'Q: What is messaging_system?'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md22',1,'Usage Examples in messaging_system']]],
  ['method_90',['Build Method',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1388',1,'']]],
  ['method_20pattern_91',['13. Template Method Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md76',1,'']]],
  ['methods_92',['methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1447',1,'Additional Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1387',1,'Builder Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1375',1,'Configuration Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md271',1,'Core Methods'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1980',1,'Debugging Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1373',1,'Identification Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md307',1,'Lifecycle Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md108',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md339',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md331',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md317',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md289',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md91',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md99',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md152',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md114',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md119',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md285',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md129',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md140',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md163',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md279',1,'Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1443',1,'Optional Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1435',1,'Progress Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1442',1,'Pure Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1392',1,'Pure Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1379',1,'Retry Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1374',1,'State Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1462',1,'Static Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1434',1,'Status Methods']]],
  ['metrics_93',['metrics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1165',1,'1. Built-in Metrics'],['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1120',1,'Baseline Metrics'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1109',1,'Collected Metrics'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md450',1,'Core Performance Metrics'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1182',1,'Quality Metrics'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md451',1,'Reference Performance Metrics']]],
  ['metrics_20collection_94',['metrics collection',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md219',1,'Metrics Collection'],['../d2/d64/md_docs_2architecture.html#autotoc_md406',1,'Metrics Collection']]],
  ['metrics_20exposed_95',['Metrics Exposed',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md799',1,'']]],
  ['metrics_20to_20track_96',['Key Metrics to Track',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md260',1,'']]],
  ['microkernel_20pattern_97',['16. Microkernel Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md81',1,'']]],
  ['migrate_20all_20code_20at_20once_98',['Q: Do I need to migrate all code at once?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md962',1,'']]],
  ['migrate_20message_20bus_20usage_99',['Step 4: Migrate Message Bus Usage',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md935',1,'']]],
  ['migrate_20message_20creation_100',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md934',1,'']]],
  ['migrate_20to_20patterns_20optional_20but_20recommended_101',['Step 5: Migrate to Patterns (Optional but Recommended)',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md936',1,'']]],
  ['migrating_20to_201_200_102',['Migrating to 1.0',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1758',1,'']]],
  ['migration_103',['migration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1766',1,'Benefits of Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1760',1,'Configuration Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1777',1,'During Migration'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md948',1,'Example 1: Simple Pub/Sub Migration'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md949',1,'Example 2: Request-Reply Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1778',1,'Post-Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1776',1,'Pre-Migration'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md929',1,'Step-by-Step Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1757',1,'Version Migration']]],
  ['migration_20checklist_104',['Migration Checklist',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1775',1,'']]],
  ['migration_20example_105',['Migration Example',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1769',1,'']]],
  ['migration_20from_20custom_20solutions_106',['Migration from Custom Solutions',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1762',1,'']]],
  ['migration_20guide_107',['migration guide',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html',1,'Migration Guide'],['../d2/d8d/md_docs_2task_2MIGRATION.html',1,'Task Module Migration Guide']]],
  ['migration_20issues_108',['Common Migration Issues',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1781',1,'']]],
  ['migration_20testing_109',['Q: How do I handle migration testing?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md967',1,'']]],
  ['migration_20timeline_110',['Migration Timeline',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md919',1,'']]],
  ['migration_2emd_111',['MIGRATION.md',['../d2/de3/MIGRATION_8md.html',1,'']]],
  ['migration_5fguide_2emd_112',['MIGRATION_GUIDE.md',['../d7/d6a/MIGRATION__GUIDE_8md.html',1,'']]],
  ['migration_5fko_2emd_113',['MIGRATION_KO.md',['../d6/d07/MIGRATION__KO_8md.html',1,'']]],
  ['minimal_20build_20no_20external_20systems_114',['Alternative: Minimal Build (No External Systems)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md732',1,'']]],
  ['minimum_20requirements_115',['Minimum Requirements',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md750',1,'']]],
  ['missing_20queue_20configuration_116',['Missing Queue Configuration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1783',1,'']]],
  ['mode_117',['mode',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md729',1,'For Development (FetchContent Mode)'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md730',1,'For Production (find_package Mode)']]],
  ['modularity_118',['Modularity',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1286',1,'']]],
  ['module_119',['After (Task Module)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1765',1,'']]],
  ['module_20api_20reference_120',['Task Module API Reference',['../df/d18/md_docs_2task_2API__REFERENCE.html',1,'']]],
  ['module_20architecture_121',['Task Module Architecture',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html',1,'']]],
  ['module_20configuration_20guide_122',['Task Module Configuration Guide',['../dc/d1e/md_docs_2task_2CONFIGURATION.html',1,'']]],
  ['module_20documentation_123',['Module Documentation',['../d2/d64/md_docs_2architecture.html#autotoc_md376',1,'']]],
  ['module_20migration_20guide_124',['Task Module Migration Guide',['../d2/d8d/md_docs_2task_2MIGRATION.html',1,'']]],
  ['module_20organization_125',['Module Organization',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md852',1,'']]],
  ['module_20performance_126',['Task Module Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md472',1,'']]],
  ['module_20quick_20start_20guide_127',['Task Module Quick Start Guide',['../d9/dff/md_docs_2task_2QUICK__START.html',1,'']]],
  ['module_20troubleshooting_20guide_128',['Task Module Troubleshooting Guide',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html',1,'']]],
  ['module_20workflow_20patterns_129',['Task Module Workflow Patterns',['../d5/dd2/md_docs_2task_2PATTERNS.html',1,'']]],
  ['modules_130',['modules',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md882',1,'Creating New Modules'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1341',1,'Data &amp; Communication Modules']]],
  ['monitor_131',['monitor',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2064',1,'7.1 Task Monitor'],['../da/db6/md_docs_2FEATURES.html#autotoc_md605',1,'Task Monitor']]],
  ['monitor_20events_132',['Monitor Events',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1982',1,'']]],
  ['monitoring_133',['monitoring',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md501',1,'Continuous Performance Monitoring'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1111',1,'Health Monitoring'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1199',1,'Monitoring'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md259',1,'Monitoring'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md311',1,'Monitoring'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1164',1,'Performance Monitoring']]],
  ['monitoring_20and_20observability_134',['monitoring and observability',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md218',1,'Monitoring and Observability'],['../d2/d64/md_docs_2architecture.html#autotoc_md405',1,'Monitoring and Observability']]],
  ['monitoring_20dashboard_135',['2. Performance Monitoring Dashboard',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1176',1,'']]],
  ['monitoring_20management_136',['Phase 7: Monitoring &amp; Management',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2063',1,'']]],
  ['monitoring_20progress_137',['monitoring progress',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1949',1,'Monitoring Progress'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1860',1,'Monitoring Progress']]],
  ['monitoring_20setup_138',['Monitoring Setup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md796',1,'']]],
  ['monitoring_20system_20integration_139',['monitoring system integration',['../da/db6/md_docs_2FEATURES.html#autotoc_md650',1,'Monitoring System Integration'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1107',1,'Monitoring System Integration']]],
  ['monitoring_20system_20integration_20✅_140',['Sprint 6: Monitoring &amp; System Integration ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2075',1,'']]],
  ['more_20questions_141',['More Questions?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md914',1,'']]],
  ['mutex_20comparison_142',['Lock-free vs Mutex Comparison',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1144',1,'']]]
];
