var searchData=
[
  ['factory_20pattern_0',['2. Factory Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md255',1,'']]],
  ['failed_1',['&quot;Database connection failed&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1097',1,'']]],
  ['faq_2',['faq',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md498',1,'FAQ'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1045',1,'FAQ']]],
  ['fault_3',['&quot;Segmentation fault&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1101',1,'']]],
  ['fault_20tolerance_4',['fault tolerance',['../d2/d64/md_docs_2architecture.html#autotoc_md112',1,'Fault Tolerance'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1024',1,'Fault Tolerance']]],
  ['feature_20coverage_5',['Feature Coverage',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md895',1,'']]],
  ['feature_20flag_20configuration_6',['Feature Flag Configuration',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md746',1,'']]],
  ['feature_20flags_7',['feature flags',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md668',1,'Feature Flags'],['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md791',1,'Task 1.2: Compiler Options and Feature Flags']]],
  ['features_8',['features',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md362',1,'2. Advanced Features'],['../df/d94/md_docs_2performance.html#autotoc_md620',1,'Key Performance Features']]],
  ['features_20fully_20implemented_9',['✅ Core Features (Fully Implemented)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1147',1,'']]],
  ['features_20headers_20only_20planned_10',['🚧 Integration Features (Headers Only - Planned)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1148',1,'']]],
  ['features_20requires_20external_20systems_11',['⚠️ Conditional Features (Requires External Systems)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1149',1,'']]],
  ['fedora_20rhel_12',['Linux (Fedora/RHEL)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md156',1,'']]],
  ['feedback_13',['💬 Feedback',['../index.html#autotoc_md965',1,'']]],
  ['fetchcontent_14',['As FetchContent',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1201',1,'']]],
  ['fetchcontent_20development_20environment_15',['Option 1: FetchContent (Development Environment)',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md665',1,'']]],
  ['fetchcontent_20downloads_16',['3. Reduce FetchContent Downloads',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1122',1,'']]],
  ['fetchcontent_20easiest_20for_20new_20users_17',['Option B: Automatic FetchContent (Easiest for New Users)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1171',1,'']]],
  ['fetchcontent_20mode_18',['fetchcontent mode',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1189',1,'FetchContent Mode'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md142',1,'For Development (FetchContent Mode)']]],
  ['fetchcontent_20mode_20development_19',['FetchContent Mode (Development)',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md684',1,'']]],
  ['file_20',['Basic Configuration File',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md355',1,'']]],
  ['file_20format_21',['System Configuration File Format',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md83',1,'']]],
  ['file_20organization_22',['File Organization',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md294',1,'']]],
  ['file_20relocation_20map_23',['B. File Relocation Map',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md449',1,'']]],
  ['file_20structure_24',['Configuration File Structure',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md182',1,'']]],
  ['final_20transition_25',['v1.11 (Final Transition)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md751',1,'']]],
  ['find_5fpackage_20mode_26',['find_package mode',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md143',1,'For Production (find_package Mode)'],['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md683',1,'System-Wide Installation (find_package mode)']]],
  ['find_5fpackage_20production_20environment_27',['Option 2: find_package (Production Environment)',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md666',1,'']]],
  ['firewall_20rules_28',['Firewall Rules',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md235',1,'']]],
  ['first_20application_29',['first application',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md281',1,'3. Your First Application'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md356',1,'First Application']]],
  ['first_20program_2060_20seconds_30',['Step 2: Your First Program (60 seconds)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1173',1,'']]],
  ['fix_31',['Initial State (PR #31 - Before Fix)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1111',1,'']]],
  ['fix_20summary_32',['Quick Fix Summary',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md158',1,'']]],
  ['flag_20configuration_33',['Feature Flag Configuration',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md746',1,'']]],
  ['flag_20propagation_20strategy_34',['Flag Propagation Strategy',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md792',1,'']]],
  ['flags_35',['flags',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md668',1,'Feature Flags'],['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md791',1,'Task 1.2: Compiler Options and Feature Flags']]],
  ['flow_36',['flow',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1165',1,'Message Flow'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1012',1,'Request-Response Flow'],['../d2/d64/md_docs_2architecture.html#autotoc_md100',1,'Request-Response Flow']]],
  ['flow_20architecture_37',['flow architecture',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1010',1,'Data Flow Architecture'],['../d2/d64/md_docs_2architecture.html#autotoc_md98',1,'Data Flow Architecture']]],
  ['flow_20tt_20test_5fcomplete_5fpubsub_5fflow_20tt_38',['1. Complete Pub/Sub Flow (&lt;tt&gt;test_complete_pubsub_flow&lt;/tt&gt;)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md881',1,'']]],
  ['flush_20tt_39',['&lt;tt&gt;flush&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md569',1,'']]],
  ['for_20contributors_40',['Option A: Local Development (Recommended for Contributors)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1170',1,'']]],
  ['for_20debugging_41',['Using GDB for Debugging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1054',1,'']]],
  ['for_20developers_42',['For Developers',['../index.html#autotoc_md957',1,'']]],
  ['for_20development_20fetchcontent_20mode_43',['For Development (FetchContent Mode)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md142',1,'']]],
  ['for_20guards_44',['CMake Configuration for Guards',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md733',1,'']]],
  ['for_20new_20users_45',['for new users',['../index.html#autotoc_md956',1,'For New Users'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1171',1,'Option B: Automatic FetchContent (Easiest for New Users)']]],
  ['for_20production_20find_5fpackage_20mode_46',['For Production (find_package Mode)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md143',1,'']]],
  ['for_20system_20administrators_47',['For System Administrators',['../index.html#autotoc_md958',1,'']]],
  ['for_20tests_48',['1. Use Release Build for Tests',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1120',1,'']]],
  ['format_49',['format',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1245',1,'Commit Message Format'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md316',1,'Commit Message Format'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md83',1,'System Configuration File Format']]],
  ['forward_20migration_20script_50',['Forward Migration Script',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md760',1,'']]],
  ['found_51',['Issue 4: yaml-cpp Not Found',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md139',1,'']]],
  ['found_20in_20external_20systems_52',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'']]],
  ['foundation_53',['1. &lt;strong&gt;common_system&lt;/strong&gt; - The Foundation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1155',1,'']]],
  ['foundation_20and_20error_20codes_20week_201_54',['Phase 1: Foundation and Error Codes (Week 1)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md390',1,'']]],
  ['foundation_20and_20preparation_20✅_55',['Phase 0: Foundation and Preparation ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md912',1,'']]],
  ['foundation_20week_201_20✅_20completed_56',['Phase 1: Foundation (Week 1) - ✅ COMPLETED',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md425',1,'']]],
  ['framework_57',['Test Framework',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1194',1,'']]],
  ['framework_20task_204_201_58',['1. Unit Test Framework (Task 4.1)',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md848',1,'']]],
  ['free_20queues_59',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md503',1,'']]],
  ['free_20vs_20mutex_20comparison_60',['Lock-free vs Mutex Comparison',['../df/d94/md_docs_2performance.html#autotoc_md628',1,'']]],
  ['from_20integration_20tests_61',['Benchmarks (from integration tests)',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md930',1,'']]],
  ['from_20source_62',['from source',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1185',1,'🛠️ Building from Source'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md171',1,'From Source']]],
  ['from_20tt_20tt_20to_20tt_63',['&lt;tt&gt;from&lt;/tt&gt; / &lt;tt&gt;to&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md591',1,'']]],
  ['fully_20implemented_64',['✅ Core Features (Fully Implemented)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1147',1,'']]],
  ['function_20conversion_65',['Pattern 1: Simple Function Conversion',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md815',1,'']]],
  ['functional_20⚠️_201_205_20verified_20benchmarks_20implemented_20awaiting_20execution_66',['Non-Functional ⚠️ 1/5 Verified (Benchmarks implemented, awaiting execution)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md437',1,'']]],
  ['functional_20✅_205_205_20completed_67',['Functional ✅ 5/5 Completed',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md436',1,'']]],
  ['functionality_68',['Functionality',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md801',1,'']]],
  ['future_20consideration_69',['Priority 3 (Future Consideration)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1134',1,'']]],
  ['future_20considerations_70',['future considerations',['../d2/d64/md_docs_2architecture.html#autotoc_md128',1,'Future Considerations'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1040',1,'Future Considerations']]],
  ['future_20enhancements_71',['future enhancements',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md905',1,'Future Enhancements'],['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md942',1,'Future Enhancements']]],
  ['future_20work_72',['Known Limitations and Future Work',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md940',1,'']]]
];
