var searchData=
[
  ['ubuntu_20debian_0',['ubuntu debian',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md176',1,'APT Repository (Ubuntu/Debian)'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md341',1,'Linux (Ubuntu/Debian)'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md155',1,'Linux (Ubuntu/Debian)']]],
  ['ulimit_20configuration_1',['ulimit Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md201',1,'']]],
  ['unit_20testing_2',['Unit Testing',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md300',1,'']]],
  ['unit_20tests_3',['Unit Tests',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md420',1,'']]],
  ['unsubscribe_20tt_4',['&lt;tt&gt;unsubscribe&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md559',1,'']]],
  ['unsubscribe_5fall_20tt_5',['&lt;tt&gt;unsubscribe_all&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md528',1,'']]],
  ['update_20cmakelists_20txt_6',['Update CMakeLists.txt',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md469',1,'']]],
  ['update_20dependencies_7',['Step 1: Update Dependencies',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md468',1,'']]],
  ['update_20error_20handling_8',['Step 6: Update Error Handling',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md477',1,'']]],
  ['update_20include_20paths_9',['Update Include Paths',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md470',1,'']]],
  ['update_20includes_10',['Step 2: Update Includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md471',1,'']]],
  ['updates_11',['🔄 Documentation Updates',['../index.html#autotoc_md676',1,'']]],
  ['usage_12',['usage',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md349',1,'1. Basic Message Bus Usage'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md352',1,'Basic Usage'],['../df/d94/md_docs_2performance.html#autotoc_md657',1,'High CPU Usage'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md246',1,'High Memory Usage'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md784',1,'Problem: High Memory Usage'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md473',1,'Step 4: Migrate Message Bus Usage']]],
  ['usage_20analysis_13',['Memory Usage Analysis',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md756',1,'']]],
  ['usage_20example_14',['usage example',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md602',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md22',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md564',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md523',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md596',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md529',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md538',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md543',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md587',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md571',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md549',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md12',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md26',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md36',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md48',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md55',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md76',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md68',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md64',1,'Usage Example']]],
  ['usage_20with_20small_20messages_15',['Issue 1: High CPU Usage with Small Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md765',1,'']]],
  ['use_20release_20build_20for_20tests_16',['1. Use Release Build for Tests',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md798',1,'']]],
  ['use_20self_20hosted_20runners_17',['1. Use Self-Hosted Runners',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md806',1,'']]],
  ['use_20simple_20publish_20subscribe_18',['Q: Can I still use simple publish/subscribe?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md504',1,'']]],
  ['use_20v1_20x_20and_20v2_200_20together_19',['Q: Can I use v1.x and v2.0 together?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md499',1,'']]],
  ['user_20documentation_20',['User Documentation',['../index.html#autotoc_md664',1,'']]],
  ['users_21',['users',['../index.html#autotoc_md668',1,'For New Users'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md849',1,'Option B: Automatic FetchContent (Easiest for New Users)']]],
  ['using_20addresssanitizer_22',['using addresssanitizer',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md737',1,'Using AddressSanitizer'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md308',1,'Using AddressSanitizer']]],
  ['using_20gdb_23',['Using GDB',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md306',1,'']]],
  ['using_20gdb_20for_20debugging_24',['Using GDB for Debugging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md732',1,'']]],
  ['using_20hashicorp_20vault_25',['Using HashiCorp Vault',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md185',1,'']]],
  ['using_20heaptrack_26',['Using HeapTrack',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md738',1,'']]],
  ['using_20instruments_20macos_27',['Using Instruments (macOS)',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md312',1,'']]],
  ['using_20intel_20vtune_28',['Using Intel VTune',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md313',1,'']]],
  ['using_20kubernetes_20secrets_29',['Using Kubernetes Secrets',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md186',1,'']]],
  ['using_20package_20managers_30',['Using Package Managers',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md175',1,'']]],
  ['using_20perf_31',['Using perf',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md311',1,'']]],
  ['using_20threadsanitizer_32',['Using ThreadSanitizer',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md309',1,'']]],
  ['using_20valgrind_33',['using valgrind',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md307',1,'Using Valgrind'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md736',1,'Using Valgrind']]],
  ['utility_34',['1.3 Integration Detection Utility',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md393',1,'']]],
  ['utilization_35',['SIMD Utilization',['../df/d94/md_docs_2performance.html#autotoc_md644',1,'']]]
];
