var searchData=
[
  ['each_20system_20contributes_0',['🧩 How Each System Contributes',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1154',1,'']]],
  ['easiest_20for_20new_20users_1',['Option B: Automatic FetchContent (Easiest for New Users)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1171',1,'']]],
  ['ecosystem_20integration_2',['🌟 Ecosystem Integration',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1152',1,'']]],
  ['efficiency_3',['2. Increase vcpkg Cache Efficiency',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1121',1,'']]],
  ['elk_20stack_4',['Log Aggregation (ELK Stack)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md216',1,'']]],
  ['enable_20debug_20logging_5',['Enable Debug Logging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1050',1,'']]],
  ['enable_20lock_20free_20queues_6',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md503',1,'']]],
  ['encryption_7',['Data Encryption',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md242',1,'']]],
  ['end_20to_20end_20integration_20test_5fend_5fto_5fend_20cpp_8',['End-to-End Integration (test_end_to_end.cpp)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md880',1,'']]],
  ['engine_9',['2. &lt;strong&gt;thread_system&lt;/strong&gt; - Concurrency Engine',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1156',1,'']]],
  ['enhancements_10',['enhancements',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md905',1,'Future Enhancements'],['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md942',1,'Future Enhancements'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1041',1,'Planned Enhancements'],['../d2/d64/md_docs_2architecture.html#autotoc_md129',1,'Planned Enhancements']]],
  ['environment_11',['environment',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md665',1,'Option 1: FetchContent (Development Environment)'],['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md666',1,'Option 2: find_package (Production Environment)'],['../df/d94/md_docs_2performance.html#autotoc_md622',1,'Test Environment']]],
  ['environment_20configuration_12',['Environment Configuration',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md354',1,'']]],
  ['environment_20variables_13',['environment variables',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md84',1,'Environment Variables'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1052',1,'Environment Variables'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md183',1,'Environment Variables']]],
  ['error_20code_20allocation_14',['System Error Code Allocation',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md696',1,'']]],
  ['error_20code_20conflicts_15',['Issue: Error code conflicts',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md493',1,'']]],
  ['error_20code_20definitions_16',['2. Error Code Definitions',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md811',1,'']]],
  ['error_20code_20mapping_17',['A. Error Code Mapping',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md448',1,'']]],
  ['error_20code_20range_18',['2. Error Code Range',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md462',1,'']]],
  ['error_20code_20range_20conflict_19',['1. Error Code Range Conflict',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md376',1,'']]],
  ['error_20code_20ranges_20',['Error Code Ranges',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md695',1,'']]],
  ['error_20codes_21',['error codes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md78',1,'Error Codes'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md79',1,'System Error Codes']]],
  ['error_20codes_20to_20common_5fsystem_22',['1.1 Add messaging_system Error Codes to common_system',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md391',1,'']]],
  ['error_20codes_20week_201_23',['Phase 1: Foundation and Error Codes (Week 1)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md390',1,'']]],
  ['error_20handling_24',['error handling',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md711',1,'4. Exception-Based Error Handling'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md611',1,'Error Handling'],['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md689',1,'Error Handling'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md80',1,'Error Handling'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md477',1,'Step 6: Update Error Handling']]],
  ['error_20handling_20paradigm_20shift_25',['1. Error Handling Paradigm Shift',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md741',1,'']]],
  ['error_20handling_20transformation_26',['Error Handling Transformation',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md715',1,'']]],
  ['error_20messages_27',['Error Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1092',1,'']]],
  ['error_20propagation_20with_20return_5fif_5ferror_28',['Pattern 2: Error Propagation with RETURN_IF_ERROR',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md816',1,'']]],
  ['error_20recovery_29',['error recovery',['../d2/d64/md_docs_2architecture.html#autotoc_md113',1,'Error Recovery'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1025',1,'Error Recovery']]],
  ['error_20recovery_20strategies_30',['Error Recovery Strategies',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md81',1,'']]],
  ['errors_31',['errors',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1093',1,'Connection Errors'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1096',1,'Database Errors'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1099',1,'Memory Errors']]],
  ['errors_20with_20old_20includes_32',['Issue: Compilation errors with old includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md492',1,'']]],
  ['estimates_33',['Expected Performance (Estimates)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1182',1,'']]],
  ['evaluation_34',['evaluation',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1042',1,'Technology Evaluation'],['../d2/d64/md_docs_2architecture.html#autotoc_md130',1,'Technology Evaluation']]],
  ['event_20driven_20architecture_35',['17. Event-Driven Architecture',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md274',1,'']]],
  ['event_20driven_20microservice_20with_20tracing_36',['Example 3: Event-Driven Microservice with Tracing',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1179',1,'']]],
  ['event_20streaming_37',['Example 3: Event Streaming',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md488',1,'']]],
  ['event_20streaming_20pattern_38',['event streaming pattern',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md551',1,'Event Streaming Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md607',1,'Event Streaming Pattern']]],
  ['event_20system_39',['Event System',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md690',1,'']]],
  ['event_5fbatch_5fprocessor_20tt_40',['Class: &lt;tt&gt;event_batch_processor&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md565',1,'']]],
  ['event_5fcount_20tt_41',['&lt;tt&gt;event_count&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md562',1,'']]],
  ['event_5fstream_20tt_42',['Class: &lt;tt&gt;event_stream&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md554',1,'']]],
  ['event_5fstream_5fconfig_20tt_43',['Struct: &lt;tt&gt;event_stream_config&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md553',1,'']]],
  ['example_44',['example',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md22',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md596',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md12',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md26',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md76',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md68',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md64',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md523',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md529',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md55',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md48',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md538',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md543',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md36',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md549',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md564',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md602',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md571',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md587',1,'Usage Example']]],
  ['example_201_3a_20distributed_20task_20queue_20with_20persistence_45',['Example 1: Distributed Task Queue with Persistence',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1177',1,'']]],
  ['example_201_3a_20simple_20pub_20sub_20migration_46',['Example 1: Simple Pub/Sub Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md486',1,'']]],
  ['example_202_3a_20real_20time_20chat_20server_20with_20monitoring_47',['Example 2: Real-Time Chat Server with Monitoring',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1178',1,'']]],
  ['example_202_3a_20request_20reply_20migration_48',['Example 2: Request-Reply Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md487',1,'']]],
  ['example_203_3a_20event_20driven_20microservice_20with_20tracing_49',['Example 3: Event-Driven Microservice with Tracing',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1179',1,'']]],
  ['example_203_3a_20event_20streaming_50',['Example 3: Event Streaming',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md488',1,'']]],
  ['example_204_3a_20message_20pipeline_51',['Example 4: Message Pipeline',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md489',1,'']]],
  ['examples_52',['examples',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1176',1,'🔥 Real-World Examples'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md485',1,'Code Examples']]],
  ['exception_20based_53',['Before (Exception-based)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md716',1,'']]],
  ['exception_20based_20error_20handling_54',['4. Exception-Based Error Handling',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md711',1,'']]],
  ['exception_20mapper_20utility_55',['Exception Mapper Utility',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md700',1,'']]],
  ['execution_56',['execution',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1124',1,'1. Split Test Execution'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md762',1,'Execution'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md437',1,'Non-Functional ⚠️ 1/5 Verified (Benchmarks implemented, awaiting execution)'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md34',1,'Query Execution'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md888',1,'Test Execution']]],
  ['execution_20✅_57',['2. CTest Parallel Execution ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1115',1,'']]],
  ['execution_20checklist_58',['Phase 1.4 Execution Checklist',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md735',1,'']]],
  ['execution_20contracts_59',['Execution Contracts',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md691',1,'']]],
  ['execution_20steps_60',['Execution Steps',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md798',1,'']]],
  ['execution_20transformation_61',['Async Execution Transformation',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md718',1,'']]],
  ['executive_20summary_62',['executive summary',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1109',1,'Executive Summary'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md368',1,'Executive Summary']]],
  ['exhaustion_63',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1089',1,'']]],
  ['existing_20directory_20structure_64',['Existing Directory Structure',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md372',1,'']]],
  ['expected_20performance_20estimates_65',['Expected Performance (Estimates)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1182',1,'']]],
  ['explore_20sample_20applications_66',['1. Explore Sample Applications',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md361',1,'']]],
  ['exposed_67',['Metrics Exposed',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md212',1,'']]],
  ['external_20dependencies_68',['External Dependencies',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md699',1,'']]],
  ['external_20integration_20✅_69',['Phase 1: Build System and External Integration ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md914',1,'']]],
  ['external_20module_20integration_70',['Task 1.1: External Module Integration',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md788',1,'']]],
  ['external_20system_20dependencies_71',['2. External System Dependencies',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md742',1,'']]],
  ['external_20system_20documentation_72',['External System Documentation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1210',1,'']]],
  ['external_20system_20integration_73',['External System Integration',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md926',1,'']]],
  ['external_20systems_74',['external systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1149',1,'⚠️ Conditional Features (Requires External Systems)'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md145',1,'Alternative: Minimal Build (No External Systems)'],['../d2/d64/md_docs_2architecture.html#autotoc_md106',1,'External Systems'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1018',1,'External Systems'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'Issue 2: GTest Not Found in External Systems'],['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md671',1,'Propagating Options to External Systems']]]
];
