var searchData=
[
  ['lack_20of_20interface_20definitions_0',['4. Lack of Interface Definitions',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md379',1,'']]],
  ['latency_20measurements_1',['Latency Measurements',['../df/d94/md_docs_2performance.html#autotoc_md623',1,'']]],
  ['layer_2',['layer',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1127',1,'7. &lt;strong&gt;network_system&lt;/strong&gt; - Communication Layer'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1177',1,'Application Layer'],['../index.html#autotoc_md961',1,'Application Layer']]],
  ['layer_20design_3',['Compatibility Layer Design',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md743',1,'']]],
  ['layers_4',['layers',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1003',1,'System Layers'],['../d2/d64/md_docs_2architecture.html#autotoc_md92',1,'System Layers']]],
  ['layout_5',['Directory Layout',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md289',1,'']]],
  ['leak_20in_20long_20running_20connections_6',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1087',1,'']]],
  ['leaks_7',['Memory Leaks',['../df/d94/md_docs_2performance.html#autotoc_md657',1,'']]],
  ['learned_8',['Lessons Learned',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md947',1,'']]],
  ['legacy_20api_20wrapper_9',['Legacy API Wrapper',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md744',1,'']]],
  ['legacy_20code_20inventory_10',['Legacy Code Inventory',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md706',1,'']]],
  ['legacy_20code_20removal_11',['Task 1.4: Legacy Code Removal',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md796',1,'']]],
  ['legacy_20code_20removal_20plan_12',['Legacy Code Removal Plan',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html',1,'']]],
  ['legacy_20dependencies_20to_20remove_13',['Legacy Dependencies to Remove',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md696',1,'']]],
  ['legacy_20guard_20header_14',['Legacy Guard Header',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md731',1,'']]],
  ['legacy_20include_20guard_15',['Legacy Include Guard',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md415',1,'']]],
  ['legacy_5fremoval_5fplan_2emd_16',['LEGACY_REMOVAL_PLAN.md',['../d7/d1d/LEGACY__REMOVAL__PLAN_8md.html',1,'']]],
  ['lessons_20learned_17',['Lessons Learned',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md947',1,'']]],
  ['level_20design_18',['High-Level Design',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1130',1,'']]],
  ['levels_19',['levels',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md74',1,'Log Levels'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md63',1,'Priority Levels']]],
  ['license_20',['📄 License',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1189',1,'']]],
  ['lifecycle_20methods_21',['Lifecycle Methods',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md43',1,'']]],
  ['lifecycle_20tt_20test_5fsubscribe_5funsubscribe_5flifecycle_20tt_22',['5. Subscription Lifecycle (&lt;tt&gt;test_subscribe_unsubscribe_lifecycle&lt;/tt&gt;)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md884',1,'']]],
  ['lifetimes_23',['Service Lifetimes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md54',1,'']]],
  ['limitations_24',['limitations',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md940',1,'Current Limitations'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md151',1,'Known Limitations'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md898',1,'Known Limitations']]],
  ['limitations_20and_20future_20work_25',['Known Limitations and Future Work',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md939',1,'']]],
  ['limiting_26',['limiting',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md239',1,'Rate Limiting'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md327',1,'Rate Limiting']]],
  ['linting_27',['linting',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1199',1,'B. Code Quality and Linting'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1202',1,'Markdown Linting']]],
  ['linting_20tools_28',['Linting Tools',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1200',1,'']]],
  ['linux_20fedora_20rhel_29',['Linux (Fedora/RHEL)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md156',1,'']]],
  ['linux_20kernel_20parameters_30',['Linux Kernel Parameters',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md200',1,'']]],
  ['linux_20ubuntu_20debian_31',['linux ubuntu debian',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md155',1,'Linux (Ubuntu/Debian)'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md341',1,'Linux (Ubuntu/Debian)']]],
  ['load_20balancer_20configuration_32',['Load Balancer Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md219',1,'']]],
  ['local_20development_20recommended_33',['Local Development (Recommended)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1154',1,'']]],
  ['local_20development_20recommended_20for_20contributors_34',['Option A: Local Development (Recommended for Contributors)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1136',1,'']]],
  ['lock_20free_20queues_35',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md502',1,'']]],
  ['lock_20free_20vs_20mutex_20comparison_36',['Lock-free vs Mutex Comparison',['../df/d94/md_docs_2performance.html#autotoc_md627',1,'']]],
  ['lock_5ffree_5fqueue_20tt_37',['Class: &lt;tt&gt;lock_free_queue&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md65',1,'']]],
  ['log_20aggregation_20elk_20stack_38',['Log Aggregation (ELK Stack)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md216',1,'']]],
  ['log_20levels_39',['Log Levels',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md74',1,'']]],
  ['logger_20system_20api_40',['Logger System API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md70',1,'']]],
  ['logger_20tt_41',['Namespace: &lt;tt&gt;logger&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md71',1,'']]],
  ['logger_5fmanager_20tt_42',['Class: &lt;tt&gt;logger_manager&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md72',1,'']]],
  ['logger_5fsystem_20strong_20observability_43',['3. &lt;strong&gt;logger_system&lt;/strong&gt; - Observability',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1123',1,'']]],
  ['logging_44',['logging',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md241',1,'Audit Logging'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1049',1,'Enable Debug Logging'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1032',1,'Logging'],['../d2/d64/md_docs_2architecture.html#autotoc_md121',1,'Logging'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md215',1,'Structured Logging']]],
  ['logging_20configuration_45',['Logging Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md214',1,'']]],
  ['logging_20contracts_46',['Logging Contracts',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md691',1,'']]],
  ['logging_20transformation_47',['Logging Transformation',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md723',1,'']]],
  ['long_20running_20connections_48',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1087',1,'']]],
  ['loss_20during_20migration_49',['Risk 2: Data Loss During Migration',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md768',1,'']]],
  ['low_20risk_50',['Low Risk',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md444',1,'']]]
];
