var searchData=
[
  ['range_0',['2. Error Code Range',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md800',1,'']]],
  ['rate_20limiting_1',['rate limiting',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md765',1,'Rate Limiting'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md702',1,'Rate Limiting']]],
  ['read_20replicas_2',['Read Replicas',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md687',1,'']]],
  ['readme_2emd_3',['readme.md',['../d4/d84/docs_2README_8md.html',1,'(Global Namespace)'],['../da/ddd/README_8md.html',1,'(Global Namespace)'],['../df/d50/docs_2integration_2README_8md.html',1,'(Global Namespace)']]],
  ['readme_5fko_2emd_4',['README_KO.md',['../dd/d72/README__KO_8md.html',1,'']]],
  ['recommendations_5',['recommendations',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md182',1,'Additional Recommendations'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md426',1,'Performance Tuning Recommendations']]],
  ['recommended_6',['recommended',['../index.html#autotoc_md953',1,'FetchContent (Recommended)'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md862',1,'Quick Build (Recommended)'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md812',1,'Step 5: Migrate to Patterns (Optional but Recommended)']]],
  ['recommended_20build_20workflow_7',['Recommended Build Workflow',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md604',1,'']]],
  ['recommended_20next_20sprint_8',['Priority 2 (Recommended - Next Sprint)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md197',1,'']]],
  ['recommended_20requirements_9',['Recommended Requirements',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md627',1,'']]],
  ['recovery_10',['recovery',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md689',1,'Backup and Recovery'],['../d2/d64/md_docs_2architecture.html#autotoc_md341',1,'Error Recovery'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md154',1,'Error Recovery'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md694',1,'Service Recovery']]],
  ['recovery_20plan_11',['Disaster Recovery Plan',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md695',1,'']]],
  ['recovery_20procedures_12',['Recovery Procedures',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md693',1,'']]],
  ['recovery_20strategies_13',['Error Recovery Strategies',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md286',1,'']]],
  ['reduce_20fetchcontent_20downloads_14',['3. Reduce FetchContent Downloads',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md186',1,'']]],
  ['reference_15',['reference',['../db/d91/md_docs_2API__REFERENCE.html',1,'API Reference'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md287',1,'Configuration Reference'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html',1,'Messaging Patterns API Reference']]],
  ['reference_20performance_20metrics_16',['Reference Performance Metrics',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md392',1,'']]],
  ['reference_20platform_17',['Reference Platform',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md972',1,'']]],
  ['references_18',['References',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md204',1,'']]],
  ['refused_19',['&quot;Connection refused&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md934',1,'']]],
  ['register_5fhandler_20tt_20',['register_handler tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md61',1,'&lt;tt&gt;register_handler&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md51',1,'&lt;tt&gt;register_handler&lt;/tt&gt;']]],
  ['regression_20detection_21',['Regression Detection',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md976',1,'']]],
  ['related_20documentation_22',['related documentation',['../index.html#autotoc_md962',1,'Related Documentation'],['../d2/d64/md_docs_2architecture.html#autotoc_md315',1,'Related Documentation']]],
  ['release_20build_20for_20tests_23',['1. Use Release Build for Tests',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md184',1,'']]],
  ['reliability_24',['Reliability',['../da/db6/md_docs_2FEATURES.html#autotoc_md556',1,'']]],
  ['reliability_20features_25',['Reliability Features',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1043',1,'']]],
  ['remove_5fstage_20tt_26',['&lt;tt&gt;remove_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md95',1,'']]],
  ['replay_20tt_27',['&lt;tt&gt;replay&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md74',1,'']]],
  ['replicas_28',['Read Replicas',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md687',1,'']]],
  ['reply_29',['reply',['../d4/d54/md_docs_2API__REFERENCE__KO.html#autotoc_md307',1,'Request/Reply'],['../d5/ddb/md_docs_2BENCHMARKS__KO.html#autotoc_md456',1,'Request/Reply'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md579',1,'Request/Reply']]],
  ['reply_20흐름_30',['Request/Reply 흐름',['../de/de3/md_docs_2ARCHITECTURE__KO.html#autotoc_md376',1,'']]],
  ['reply_20migration_31',['Example 2: Request-Reply Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md825',1,'']]],
  ['reply_20pattern_32',['reply pattern',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md814',1,'Request-Reply Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md120',1,'Request-Reply Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md45',1,'Request-Reply Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1206',1,'Request/Reply Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md519',1,'Request/Reply Pattern']]],
  ['reply_20performance_33',['Request/Reply Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md409',1,'']]],
  ['report_34',['Coverage Report',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1222',1,'']]],
  ['reporting_20bugs_35',['Reporting Bugs',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1077',1,'']]],
  ['repository_36',['repository',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md635',1,'1. Clone Repository'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md856',1,'1. Clone the Repository']]],
  ['repository_20rhel_20centos_37',['YUM Repository (RHEL/CentOS)',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md640',1,'']]],
  ['repository_20ubuntu_20debian_38',['APT Repository (Ubuntu/Debian)',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md639',1,'']]],
  ['request_20performance_39',['Concurrent Request Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md411',1,'']]],
  ['request_20process_40',['Pull Request Process',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md503',1,'']]],
  ['request_20reply_41',['request reply',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md579',1,'Request/Reply'],['../d5/ddb/md_docs_2BENCHMARKS__KO.html#autotoc_md456',1,'Request/Reply'],['../d4/d54/md_docs_2API__REFERENCE__KO.html#autotoc_md307',1,'Request/Reply']]],
  ['request_20reply_20흐름_42',['Request/Reply 흐름',['../de/de3/md_docs_2ARCHITECTURE__KO.html#autotoc_md376',1,'']]],
  ['request_20reply_20migration_43',['Example 2: Request-Reply Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md825',1,'']]],
  ['request_20reply_20pattern_44',['request reply pattern',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md120',1,'Request-Reply Pattern'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md814',1,'Request-Reply Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md45',1,'Request-Reply Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1206',1,'Request/Reply Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md519',1,'Request/Reply Pattern']]],
  ['request_20reply_20performance_45',['Request/Reply Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md409',1,'']]],
  ['request_20response_46',['Request-Response',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md251',1,'']]],
  ['request_20response_20flow_47',['request response flow',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md141',1,'Request-Response Flow'],['../d2/d64/md_docs_2architecture.html#autotoc_md328',1,'Request-Response Flow']]],
  ['request_20tt_48',['request tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md50',1,'&lt;tt&gt;request&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md56',1,'&lt;tt&gt;request&lt;/tt&gt;']]],
  ['request_5fclient_20tt_49',['Class: &lt;tt&gt;request_client&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md53',1,'']]],
  ['request_5freply_5fhandler_20tt_50',['Class: &lt;tt&gt;request_reply_handler&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md47',1,'']]],
  ['request_5fserver_20tt_51',['Class: &lt;tt&gt;request_server&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md58',1,'']]],
  ['required_52',['required',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md774',1,'Q: What C++ standard is required?'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md779',1,'Q: What dependencies are required?']]],
  ['required_20dependencies_53',['Required Dependencies',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1118',1,'']]],
  ['required_20systems_54',['Required Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1211',1,'']]],
  ['requirements_55',['requirements',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md625',1,'Hardware Requirements'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md626',1,'Minimum Requirements'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md628',1,'Production Requirements'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md627',1,'Recommended Requirements'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1050',1,'Resource Requirements'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md852',1,'System Requirements'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md624',1,'System Requirements'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md501',1,'Testing Requirements']]],
  ['resource_20allocation_56',['Resource Allocation',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md685',1,'']]],
  ['resource_20management_57',['Resource Management',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1056',1,'']]],
  ['resource_20requirements_58',['Resource Requirements',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1050',1,'']]],
  ['resources_59',['resources',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1226',1,'Additional Resources'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md845',1,'Additional Resources']]],
  ['response_60',['Request-Response',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md251',1,'']]],
  ['response_20flow_61',['response flow',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md141',1,'Request-Response Flow'],['../d2/d64/md_docs_2architecture.html#autotoc_md328',1,'Request-Response Flow']]],
  ['responsibility_20pattern_62',['11. Chain of Responsibility Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md15',1,'']]],
  ['result_20t_20pattern_63',['Result&lt;T&gt; Pattern',['../da/db6/md_docs_2FEATURES.html#autotoc_md547',1,'']]],
  ['results_64',['Benchmark Results',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md984',1,'']]],
  ['retrieving_20values_65',['Retrieving Values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md215',1,'']]],
  ['review_20checklist_66',['Code Review Checklist',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md755',1,'']]],
  ['reviews_67',['Code Reviews',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1036',1,'']]],
  ['rhel_68',['Linux (Fedora/RHEL)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md619',1,'']]],
  ['rhel_20centos_69',['YUM Repository (RHEL/CentOS)',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md640',1,'']]],
  ['router_70',['5. Topic Router',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md803',1,'']]],
  ['router_20api_71',['Topic Router API',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md821',1,'']]],
  ['router_20performance_72',['Topic Router Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md401',1,'']]],
  ['routing_73',['Topic Routing',['../da/db6/md_docs_2FEATURES.html#autotoc_md534',1,'']]],
  ['rpc_20latency_74',['Synchronous RPC Latency',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md410',1,'']]],
  ['rules_75',['rules',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md683',1,'Auto-scaling Rules'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md698',1,'Firewall Rules']]],
  ['run_76',['2. Build and Run',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md875',1,'']]],
  ['runners_77',['1. Use Self-Hosted Runners',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md192',1,'']]],
  ['running_20benchmarks_78',['running benchmarks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md429',1,'Running Benchmarks'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1217',1,'Running Benchmarks']]],
  ['running_20connections_79',['Issue 2: Memory Leak in Long-Running Connections',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md928',1,'']]],
  ['running_20process_80',['Attach to Running Process',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md895',1,'']]],
  ['running_20tests_81',['Running Tests',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1221',1,'']]],
  ['runtime_20configuration_82',['Runtime Configuration',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md891',1,'']]],
  ['runtime_20dependencies_83',['runtime dependencies',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md840',1,'Q: Are there any runtime dependencies?'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md632',1,'Runtime Dependencies'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md854',1,'Runtime Dependencies']]],
  ['runtime_20issues_84',['Runtime Issues',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md768',1,'']]]
];
