var searchData=
[
  ['b_3a_20템플릿을_20통한_20컴파일_20타임_20로거_20선택_0',['대안 B: 템플릿을 통한 컴파일 타임 로거 선택',['../dd/da0/md_docs_2adr_2001-logging-architecture__KO.html#autotoc_md44',1,'']]],
  ['b_3a_20compile_20time_20logger_20selection_20via_20templates_1',['Alternative B: Compile-time Logger Selection via Templates',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md18',1,'']]],
  ['backend_2',['backend',['../d9/db8/md_docs_2task_2ARCHITECTURE__KO.html#autotoc_md1671',1,'커스텀 Result Backend'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2070',1,'4.2 In-Memory Result Backend'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1640',1,'Custom Result Backend'],['../da/db6/md_docs_2FEATURES.html#autotoc_md631',1,'Integration Backend'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2068',1,'Phase 4: Result Backend'],['../da/db6/md_docs_2FEATURES.html#autotoc_md610',1,'Result Backend'],['../da/db6/md_docs_2FEATURES.html#autotoc_md630',1,'Standalone Backend']]],
  ['backend_20✅_3',['Sprint 2: Queue &amp; Result Backend ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2087',1,'']]],
  ['backend_20분리_4',['2. Result Backend 분리',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2102',1,'']]],
  ['backend_20선택적_5',['4.3 Redis Result Backend (선택적)',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2071',1,'']]],
  ['backend_20impact_6',['Backend Impact',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md469',1,'']]],
  ['backend_20interface_7',['backend interface',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2069',1,'4.1 Result Backend Interface'],['../da/db6/md_docs_2FEATURES.html#autotoc_md628',1,'Backend Interface']]],
  ['backend_20performance_8',['Result Backend Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md479',1,'']]],
  ['backend_20support_9',['Backend Support',['../da/db6/md_docs_2FEATURES.html#autotoc_md627',1,'']]],
  ['backends_20tt_10',['backends tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1317',1,'백엔드 (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1279',1,'Backends (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)']]],
  ['backends_20tt_20include_20kcenon_20messaging_20backends_20tt_11',['Backends (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1279',1,'']]],
  ['background_12',['Background',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md3',1,'']]],
  ['backup_13',['backup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md831',1,'Application State Backup'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md832',1,'Database Backup']]],
  ['backup_20and_20recovery_14',['Backup and Recovery',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md829',1,'']]],
  ['backup_20strategy_15',['Backup Strategy',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md830',1,'']]],
  ['balancer_20configuration_16',['Load Balancer Configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md822',1,'']]],
  ['base_20systems_17',['🌟 Integration with Base Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2135',1,'']]],
  ['based_18',['Callback-Based',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1453',1,'']]],
  ['based_20data_20handling_19',['2. Container-Based Data Handling',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1007',1,'']]],
  ['based_20execution_20',['Cron-based Execution',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1964',1,'']]],
  ['based_20logging_21',['Alternative C: Macro-based Logging',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md19',1,'']]],
  ['based_20scheduling_22',['Cron-Based Scheduling',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1869',1,'']]],
  ['based_20tasks_23',['1. Message-Based Tasks',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1643',1,'']]],
  ['baseline_24',['Performance Baseline',['../d9/df1/md_docs_2performance_2BASELINE.html',1,'']]],
  ['baseline_20metrics_25',['Baseline Metrics',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1136',1,'']]],
  ['baseline_2emd_26',['BASELINE.md',['../dc/d78/BASELINE_8md.html',1,'']]],
  ['basic_20configuration_20file_27',['Basic Configuration File',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1012',1,'']]],
  ['basic_20example_28',['Basic Example',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2127',1,'']]],
  ['basic_20integration_29',['Basic Integration',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1098',1,'']]],
  ['basic_20message_20bus_20usage_30',['1. Basic Message Bus Usage',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1006',1,'']]],
  ['basic_20usage_31',['basic usage',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1119',1,'Basic Usage'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1009',1,'Basic Usage'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1110',1,'Basic Usage'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1126',1,'Basic Usage'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1953',1,'Basic Usage']]],
  ['batch_20operations_32',['Batch Operations',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1444',1,'']]],
  ['batching_20and_20pipelining_33',['Batching and Pipelining',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1179',1,'']]],
  ['before_20custom_20thread_20pool_34',['Before (Custom Thread Pool)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1780',1,'']]],
  ['before_20fix_35',['Initial State (PR #31 - Before Fix)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md234',1,'']]],
  ['before_20system_20cron_36',['Before (System Cron)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1787',1,'']]],
  ['behavior_37',['Shutdown Behavior',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1101',1,'']]],
  ['behavioral_20patterns_38',['Behavioral Patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md71',1,'']]],
  ['being_20delivered_39',['Issue: Messages not being delivered',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md973',1,'']]],
  ['being_20processed_40',['Tasks Not Being Processed',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1990',1,'']]],
  ['benchmark_20commands_41',['Benchmark Commands',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1143',1,'']]],
  ['benchmark_20output_20format_42',['Benchmark Output Format',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md502',1,'']]],
  ['benchmark_20results_43',['Benchmark Results',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1153',1,'']]],
  ['benchmarks_44',['benchmarks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md501',1,'Available Benchmarks'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2142',1,'Benchmarks'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md456',1,'Message Creation Benchmarks'],['../de/d93/md_docs_2BENCHMARKS.html',1,'Messaging System Performance Benchmarks'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2143',1,'Running Benchmarks'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md499',1,'Running Benchmarks']]],
  ['benchmarks_20complete_45',['✅ Testing &amp; Benchmarks (Complete)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2116',1,'']]],
  ['benchmarks_2emd_46',['BENCHMARKS.md',['../de/d04/BENCHMARKS_8md.html',1,'']]],
  ['benchmarks_5fko_2emd_47',['BENCHMARKS_KO.md',['../d3/d9a/BENCHMARKS__KO_8md.html',1,'']]],
  ['benefits_48',['benefits',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1789',1,'Benefits'],['../da/db6/md_docs_2FEATURES.html#autotoc_md625',1,'Benefits']]],
  ['benefits_20of_20migration_49',['Benefits of Migration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1782',1,'']]],
  ['best_20practices_50',['best practices',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md177',1,'Best Practices'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1233',1,'Best Practices'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md873',1,'Best Practices'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1865',1,'Best Practices'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md902',1,'Security Best Practices']]],
  ['binaries_51',['3. Prebuilt Dependency Binaries',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md253',1,'']]],
  ['blocking_20result_20retrieval_52',['Blocking Result Retrieval',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1452',1,'']]],
  ['bottleneck_53',['Problem: Database Bottleneck',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1087',1,'']]],
  ['bottlenecks_54',['bottlenecks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md497',1,'Common Bottlenecks'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1055',1,'Identify CPU Bottlenecks'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1191',1,'Network Bottlenecks']]],
  ['breakdown_55',['Latency Breakdown',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md489',1,'']]],
  ['breaking_20changes_56',['Breaking Changes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md938',1,'']]],
  ['bridge_20integration_57',['bridge integration',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1108',1,'Messaging Event Bridge Integration'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1117',1,'Task Event Bridge Integration']]],
  ['broker_58',['Message Broker',['../da/db6/md_docs_2FEATURES.html#autotoc_md595',1,'']]],
  ['bugs_59',['Reporting Bugs',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1246',1,'']]],
  ['build_60',['build',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md776',1,'2. Configure Build'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md750',1,'Verifying Successful Build']]],
  ['build_20and_20install_61',['3. Build and Install',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md777',1,'']]],
  ['build_20and_20run_62',['2. Build and Run',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1015',1,'']]],
  ['build_20caching_20service_63',['2. Implement Build Caching Service',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md252',1,'']]],
  ['build_20configuration_64',['Build Configuration',['../da/db6/md_docs_2FEATURES.html#autotoc_md639',1,'']]],
  ['build_20custom_20image_65',['Build Custom Image',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md783',1,'']]],
  ['build_20dependencies_66',['Build Dependencies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md771',1,'']]],
  ['build_20for_20tests_67',['1. Use Release Build for Tests',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md243',1,'']]],
  ['build_20issues_68',['Build Issues',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md907',1,'']]],
  ['build_20issues_20and_20solutions_69',['Common Build Issues and Solutions',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md735',1,'']]],
  ['build_20method_70',['Build Method',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1404',1,'']]],
  ['build_20no_20external_20systems_71',['Alternative: Minimal Build (No External Systems)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md748',1,'']]],
  ['build_20options_72',['build options',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2154',1,'🔧 Build Options'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1003',1,'Custom Build Options']]],
  ['build_20parallelization_20✅_73',['3. Build Parallelization ✅',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md239',1,'']]],
  ['build_20performance_20degradation_74',['Issue: Build performance degradation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md974',1,'']]],
  ['build_20recommended_75',['Quick Build (Recommended)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1002',1,'']]],
  ['build_20system_76',['build system',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1283',1,'Build System'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md896',1,'Build System']]],
  ['build_20targets_77',['Build Targets',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1285',1,'']]],
  ['build_20the_20project_78',['2. Build the Project',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md858',1,'']]],
  ['build_20the_20system_79',['3. Build the System',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1001',1,'']]],
  ['build_20troubleshooting_20guide_80',['Build Troubleshooting Guide',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html',1,'']]],
  ['build_20tt_81',['&lt;tt&gt;build&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md168',1,'']]],
  ['build_20workflow_82',['Recommended Build Workflow',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md744',1,'']]],
  ['build_5ftroubleshooting_2emd_83',['BUILD_TROUBLESHOOTING.md',['../d5/dd8/BUILD__TROUBLESHOOTING_8md.html',1,'']]],
  ['builder_84',['builder',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2059',1,'1.2 Task Builder'],['../da/db6/md_docs_2FEATURES.html#autotoc_md645',1,'Message Builder'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1706',1,'Using Task Builder'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1856',1,'Using Task Builder'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1961',1,'Using the Task Builder']]],
  ['builder_20api_85',['Fluent Builder API',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1099',1,'']]],
  ['builder_20methods_86',['Builder Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1403',1,'']]],
  ['builder_20pattern_87',['builder pattern',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1645',1,'3. Builder Pattern'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md64',1,'3. Builder Pattern']]],
  ['builder_20performance_88',['Message Builder Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md457',1,'']]],
  ['building_20for_20development_89',['Building for Development',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md575',1,'']]],
  ['builds_90',['Example Builds',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2156',1,'']]],
  ['built_20in_20metrics_91',['1. Built-in Metrics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1181',1,'']]],
  ['bus_92',['bus',['../da/db6/md_docs_2FEATURES.html#autotoc_md594',1,'Message Bus'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md922',1,'Q: How do I create a message bus?']]],
  ['bus_20api_93',['bus api',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md960',1,'Message Bus API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md302',1,'Message Bus API']]],
  ['bus_20doesn_20t_20start_94',['Issue: Message bus doesn&apos;t start',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md972',1,'']]],
  ['bus_20interface_95',['4. Message Bus Interface',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md942',1,'']]],
  ['bus_20performance_96',['Message Bus Performance',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1137',1,'']]],
  ['bus_20usage_97',['bus usage',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1006',1,'1. Basic Message Bus Usage'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md951',1,'Step 4: Migrate Message Bus Usage']]],
  ['but_20recommended_98',['Step 5: Migrate to Patterns (Optional but Recommended)',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md952',1,'']]],
  ['by_20scale_99',['By Scale',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1723',1,'']]],
  ['by_20step_20migration_100',['Step-by-Step Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md945',1,'']]],
  ['by_20workload_20type_101',['By Workload Type',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1722',1,'']]]
];
