var searchData=
[
  ['i_20enable_20lock_20free_20queues_0',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md503',1,'']]],
  ['i_20handle_20migration_20testing_1',['Q: How do I handle migration testing?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md505',1,'']]],
  ['i_20need_20to_20migrate_20all_20code_20at_20once_2',['Q: Do I need to migrate all code at once?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md500',1,'']]],
  ['i_20o_20analysis_3',['Disk I/O Analysis',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1081',1,'']]],
  ['i_20o_20optimization_4',['I/O Optimization',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1080',1,'']]],
  ['i_20still_20use_20simple_20publish_20subscribe_5',['Q: Can I still use simple publish/subscribe?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md504',1,'']]],
  ['i_20use_20v1_20x_20and_20v2_200_20together_6',['Q: Can I use v1.x and v2.0 together?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md499',1,'']]],
  ['ide_20configuration_7',['IDE Configuration',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md283',1,'']]],
  ['identified_20issues_8',['Identified Issues',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md375',1,'']]],
  ['identify_20cpu_20bottlenecks_9',['Identify CPU Bottlenecks',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1075',1,'']]],
  ['iexecutor_20주입식_20아키텍처_20구현_20strong_10',['&lt;strong&gt;Task 2.3 – IExecutor 주입식 아키텍처 구현&lt;/strong&gt;',['../d7/d01/md_docs_2REBUILD__PLAN.html#autotoc_md983',1,'']]],
  ['iexecutor_20based_11',['After (IExecutor-based)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md720',1,'']]],
  ['if_20issues_20detected_12',['Rollback (If Issues Detected)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md758',1,'']]],
  ['ilogger_13',['After (ILogger)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md726',1,'']]],
  ['image_14',['image',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md180',1,'Build Custom Image'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md179',1,'Pull Official Image']]],
  ['impact_15',['impact',['../df/d94/md_docs_2performance.html#autotoc_md638',1,'Connection Pool Impact'],['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md677',1,'Documentation of Option Impact'],['../df/d94/md_docs_2performance.html#autotoc_md632',1,'SIMD Optimization Impact']]],
  ['implementation_16',['implementation',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md398',1,'3.2 Message Queue Implementation'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md404',1,'5.1 Topic Router Implementation'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md406',1,'6.1 Message Bus Implementation'],['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md731',1,'Build Guard Implementation']]],
  ['implementation_20✅_17',['Phase 2: Messaging Core Implementation ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md916',1,'']]],
  ['implementation_20plan_18',['implementation plan',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md389',1,'Implementation Plan'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md822',1,'Implementation Plan']]],
  ['implementation_20status_19',['📋 Implementation Status',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1113',1,'']]],
  ['implementation_20timeline_20',['implementation timeline',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md863',1,'Implementation Timeline'],['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md804',1,'Implementation Timeline']]],
  ['implementation_20week_208_21',['Phase 8: Patterns Implementation (Week 8)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md409',1,'']]],
  ['implementations_22',['Internal Implementations',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md698',1,'']]],
  ['implemented_23',['implemented',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1114',1,'✅ Core Features (Fully Implemented)'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1117',1,'❌ Not Implemented']]],
  ['implemented_20awaiting_20execution_24',['Non-Functional ⚠️ 1/5 Verified (Benchmarks implemented, awaiting execution)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md437',1,'']]],
  ['improvement_20objectives_25',['Improvement Objectives',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md381',1,'']]],
  ['improvement_20plan_26',['Messaging System Improvement Plan',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html',1,'']]],
  ['improvement_5fplan_2emd_27',['IMPROVEMENT_PLAN.md',['../d5/d89/IMPROVEMENT__PLAN_8md.html',1,'']]],
  ['improvements_20✅_28',['Build System Improvements ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md922',1,'']]],
  ['in_20external_20systems_29',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'']]],
  ['in_20long_20running_20connections_30',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1088',1,'']]],
  ['in_20message_20processing_31',['Issue 4: Deadlock in Message Processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1090',1,'']]],
  ['in_20metrics_32',['1. Built-in Metrics',['../df/d94/md_docs_2performance.html#autotoc_md649',1,'']]],
  ['in_20phase_200_33',['CMakePresets.json (Already created in Phase 0)',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md793',1,'']]],
  ['include_20guard_34',['Legacy Include Guard',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md415',1,'']]],
  ['include_20paths_35',['Update Include Paths',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md470',1,'']]],
  ['includes_36',['includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md492',1,'Issue: Compilation errors with old includes'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md471',1,'Step 2: Update Includes']]],
  ['inconsistency_37',['2. Directory Structure Inconsistency',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md377',1,'']]],
  ['infrastructure_38',['Core Infrastructure',['../index.html#autotoc_md960',1,'']]],
  ['infrastructure_20integration_20✅_39',['Phase 3: Infrastructure Integration ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md918',1,'']]],
  ['infrastructure_20integration_20design_20document_40',['Phase 3: Infrastructure Integration - Design Document',['../d7/de1/md_docs_2phase3_2DESIGN.html',1,'']]],
  ['ingress_41',['Service and Ingress',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md195',1,'']]],
  ['initialization_20tt_20test_5fconfig_5fdriven_5finitialization_20tt_42',['6. Config-Driven Initialization (&lt;tt&gt;test_config_driven_initialization&lt;/tt&gt;)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md886',1,'']]],
  ['input_20validation_43',['Input Validation',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md325',1,'']]],
  ['install_44',['3. Build and Install',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md174',1,'']]],
  ['installation_45',['installation',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md347',1,'4. Verify Installation'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md178',1,'Docker Installation'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md338',1,'Installation'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md170',1,'Installation']]],
  ['installation_20find_5fpackage_20mode_46',['System-Wide Installation (find_package mode)',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md683',1,'']]],
  ['installation_20guide_47',['Installation Guide',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md682',1,'']]],
  ['installed_20package_48',['As Installed Package',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1169',1,'']]],
  ['installed_20packages_20production_49',['Option C: System-Installed Packages (Production)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1139',1,'']]],
  ['instruments_20macos_50',['Using Instruments (macOS)',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md312',1,'']]],
  ['integration_51',['integration',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1119',1,'🌟 Ecosystem Integration'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1166',1,'📦 CMake Integration'],['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md926',1,'External System Integration'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1039',1,'Kubernetes Integration'],['../d2/d64/md_docs_2architecture.html#autotoc_md127',1,'Kubernetes Integration'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md210',1,'Prometheus Integration'],['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md788',1,'Task 1.1: External Module Integration'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1213',1,'VS Code Integration']]],
  ['integration_20✅_52',['integration ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md914',1,'Phase 1: Build System and External Integration ✅'],['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md918',1,'Phase 3: Infrastructure Integration ✅']]],
  ['integration_20✅_205_205_20completed_53',['Integration ✅ 5/5 Completed',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md439',1,'']]],
  ['integration_20backend_54',['4.3 Integration Backend',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md402',1,'']]],
  ['integration_20design_20document_55',['Phase 3: Infrastructure Integration - Design Document',['../d7/de1/md_docs_2phase3_2DESIGN.html',1,'']]],
  ['integration_20detection_20utility_56',['1.3 Integration Detection Utility',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md393',1,'']]],
  ['integration_20features_20headers_20only_20planned_57',['🚧 Integration Features (Headers Only - Planned)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1115',1,'']]],
  ['integration_20guides_58',['Integration Guides',['../d2/d64/md_docs_2architecture.html#autotoc_md90',1,'']]],
  ['integration_20points_59',['integration points',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1017',1,'Integration Points'],['../d7/de1/md_docs_2phase3_2DESIGN.html#autotoc_md840',1,'Integration Points'],['../d2/d64/md_docs_2architecture.html#autotoc_md105',1,'Integration Points']]],
  ['integration_20strategy_60',['Dependency Integration Strategy',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md664',1,'']]],
  ['integration_20test_5fend_5fto_5fend_20cpp_61',['End-to-End Integration (test_end_to_end.cpp)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md880',1,'']]],
  ['integration_20testing_62',['Integration Testing',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md303',1,'']]],
  ['integration_20tests_63',['integration tests',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md930',1,'Benchmarks (from integration tests)'],['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md879',1,'Integration Tests'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md421',1,'Integration Tests'],['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md829',1,'Integration Tests']]],
  ['integration_20tests_20task_204_201_64',['2. Integration Tests (Task 4.1)',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md849',1,'']]],
  ['integration_20with_20other_20systems_65',['Step 7: Integration with Other Systems',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md478',1,'']]],
  ['intel_20vtune_66',['Using Intel VTune',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md313',1,'']]],
  ['interface_67',['interface',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md397',1,'3.1 Queue Interface'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md464',1,'4. Message Bus Interface'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md400',1,'4.1 Backend Interface'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md408',1,'7.1 DI Container Interface']]],
  ['interface_20definitions_68',['4. Lack of Interface Definitions',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md379',1,'']]],
  ['interface_20mapping_20document_69',['System Interface Mapping Document',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html',1,'']]],
  ['interface_5fmapping_2emd_70',['INTERFACE_MAPPING.md',['../dc/d4f/INTERFACE__MAPPING_8md.html',1,'']]],
  ['interfaces_71',['interfaces',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md392',1,'1.2 Create Core Interfaces'],['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md688',1,'Common System Interfaces']]],
  ['internal_20communication_72',['internal communication',['../d2/d64/md_docs_2architecture.html#autotoc_md107',1,'Internal Communication'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1019',1,'Internal Communication']]],
  ['internal_20container_73',['Before (Internal container)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md722',1,'']]],
  ['internal_20container_20system_74',['1. Internal Container System',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md708',1,'']]],
  ['internal_20implementations_75',['Internal Implementations',['../df/dad/md_docs_2phase0_2INTERFACE__MAPPING.html#autotoc_md698',1,'']]],
  ['internal_20network_20system_76',['2. Internal Network System',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md709',1,'']]],
  ['internal_20thread_20pool_77',['Before (Internal thread pool)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md719',1,'']]],
  ['internal_20thread_20system_78',['3. Internal Thread System',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md710',1,'']]],
  ['inventory_79',['Legacy Code Inventory',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md707',1,'']]],
  ['is_5fready_20tt_80',['&lt;tt&gt;is_ready&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md522',1,'']]],
  ['is_5frunning_20tt_81',['&lt;tt&gt;is_running&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md570',1,'']]],
  ['issue_201_3a_20high_20cpu_20usage_20with_20small_20messages_82',['Issue 1: High CPU Usage with Small Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1087',1,'']]],
  ['issue_201_3a_20target_20name_20conflicts_83',['Issue 1: Target Name Conflicts',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md133',1,'']]],
  ['issue_202_3a_20gtest_20not_20found_20in_20external_20systems_84',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'']]],
  ['issue_202_3a_20memory_20leak_20in_20long_20running_20connections_85',['Issue 2: Memory Leak in Long-Running Connections',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1088',1,'']]],
  ['issue_203_3a_20database_20connection_20pool_20exhaustion_86',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1089',1,'']]],
  ['issue_203_3a_20grep_20p_20not_20supported_20macos_87',['Issue 3: grep -P Not Supported (macOS)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md137',1,'']]],
  ['issue_204_3a_20deadlock_20in_20message_20processing_88',['Issue 4: Deadlock in Message Processing',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1090',1,'']]],
  ['issue_204_3a_20yaml_20cpp_20not_20found_89',['Issue 4: yaml-cpp Not Found',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md139',1,'']]],
  ['issue_205_3a_20performance_20degradation_20with_20many_20topics_90',['Issue 5: Performance Degradation with Many Topics',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1091',1,'']]],
  ['issue_3a_20build_20performance_20degradation_91',['Issue: Build performance degradation',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md496',1,'']]],
  ['issue_3a_20compilation_20errors_20with_20old_20includes_92',['Issue: Compilation errors with old includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md492',1,'']]],
  ['issue_3a_20error_20code_20conflicts_93',['Issue: Error code conflicts',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md493',1,'']]],
  ['issue_3a_20message_20bus_20doesn_20t_20start_94',['Issue: Message bus doesn&apos;t start',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md494',1,'']]],
  ['issue_3a_20messages_20not_20being_20delivered_95',['Issue: Messages not being delivered',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md495',1,'']]],
  ['issues_96',['issues',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md329',1,'Build Issues'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md244',1,'Common Issues'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md375',1,'Identified Issues'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1086',1,'Known Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md331',1,'Performance Issues'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md247',1,'Performance Issues'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md773',1,'Risk 5: Build System Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md330',1,'Runtime Issues'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1199',1,'Troubleshooting Build Issues'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md328',1,'Troubleshooting Common Issues'],['../df/d94/md_docs_2performance.html#autotoc_md655',1,'Troubleshooting Performance Issues']]],
  ['issues_20and_20solutions_97',['Common Build Issues and Solutions',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md132',1,'']]],
  ['issues_20detected_98',['Rollback (If Issues Detected)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md758',1,'']]],
  ['items_99',['items',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md767',1,'High Risk Items'],['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md771',1,'Medium Risk Items']]]
];
