var searchData=
[
  ['what_20about_20performance_0',['Q: What about performance?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md964',1,'']]],
  ['what_20c_20standard_20is_20required_1',['Q: What C++ standard is required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md899',1,'']]],
  ['what_20dependencies_20are_20required_2',['Q: What dependencies are required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md904',1,'']]],
  ['what_20is_20an_20adr_3',['What is an ADR?',['../index.html#autotoc_md53',1,'']]],
  ['what_20is_20messaging_5fsystem_4',['Q: What is messaging_system?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md898',1,'']]],
  ['what_20is_20the_20latency_5',['Q: What is the latency?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md913',1,'']]],
  ['what_20s_20included_6',['📦 What&apos;s Included',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2097',1,'']]],
  ['what_20throughput_20can_20i_20expect_7',['Q: What throughput can I expect?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md912',1,'']]],
  ['which_20platforms_20are_20supported_8',['Q: Which platforms are supported?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md900',1,'']]],
  ['wildcard_20patterns_9',['Wildcard Patterns',['../da/db6/md_docs_2FEATURES.html#autotoc_md634',1,'']]],
  ['wildcards_10',['Q: How do I use wildcards?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md909',1,'']]],
  ['windows_11',['Windows',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md985',1,'']]],
  ['windows_20ci_20performance_20optimization_12',['Windows CI Performance Optimization',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html',1,'']]],
  ['windows_5foptimization_2emd_13',['WINDOWS_OPTIMIZATION.md',['../d9/dea/WINDOWS__OPTIMIZATION_8md.html',1,'']]],
  ['wins_14',['Short-Term (Quick Wins)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md242',1,'']]],
  ['with_20base_20systems_15',['🌟 Integration with Base Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2120',1,'']]],
  ['with_20many_20topics_16',['Issue 5: Performance Degradation with Many Topics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1056',1,'']]],
  ['with_20network_5fsystem_17',['Using with network_system',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1089',1,'']]],
  ['with_20old_20includes_18',['Issue: Compilation errors with old includes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md955',1,'']]],
  ['with_20other_20systems_19',['with other systems',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md503',1,'Comparison with Other Systems'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md941',1,'Step 7: Integration with Other Systems']]],
  ['with_20perf_20',['Performance Profiling with perf',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1036',1,'']]],
  ['with_20retry_21',['Chain with Retry',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1874',1,'']]],
  ['with_20sample_20client_22',['3. Test with Sample Client',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1001',1,'']]],
  ['with_20small_20messages_23',['Issue 1: High CPU Usage with Small Messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1052',1,'']]],
  ['with_20strace_24',['System Tracing with strace',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1035',1,'']]],
  ['with_20subsystems_25',['Integration with Subsystems',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1081',1,'']]],
  ['with_20thread_5fsystem_26',['Using with thread_system',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1088',1,'']]],
  ['won_20t_20start_27',['won t start',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1068',1,'Problem: Service Won&apos;t Start'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md833',1,'Service Won&apos;t Start']]],
  ['worker_20pool_28',['worker pool',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2048',1,'2.2 Worker Pool'],['../da/db6/md_docs_2FEATURES.html#autotoc_md602',1,'Worker Pool']]],
  ['worker_20pool_20configuration_29',['Worker Pool Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1681',1,'']]],
  ['worker_20scalability_30',['Worker Scalability',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md475',1,'']]],
  ['worker_20status_31',['worker status',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1985',1,'Check Worker Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1470',1,'Worker Status']]],
  ['worker_20system_32',['Phase 2: Worker System',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2046',1,'']]],
  ['worker_20system_20✅_33',['Sprint 3: Worker System ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2073',1,'']]],
  ['worker_20throughput_34',['Worker Throughput',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md474',1,'']]],
  ['worker_5fpool_35',['worker_pool',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1612',1,'4. worker_pool'],['../d9/db8/md_docs_2task_2ARCHITECTURE__KO.html#autotoc_md1643',1,'4. worker_pool'],['../dd/db9/md_docs_2task_2API__REFERENCE__KO.html#autotoc_md1536',1,'worker_pool'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1417',1,'worker_pool']]],
  ['workflow_36',['workflow',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md572',1,'Development Workflow'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2146',1,'Development Workflow'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md729',1,'Recommended Build Workflow'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md878',1,'Workflow']]],
  ['workflow_20patterns_37',['workflow patterns',['../d5/dd2/md_docs_2task_2PATTERNS.html',1,'Task Module Workflow Patterns'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1430',1,'Workflow Patterns']]],
  ['working_38',['Retry Not Working',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1978',1,'']]],
  ['workload_20type_39',['By Workload Type',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1707',1,'']]]
];
