var searchData=
[
  ['v1_2010_20transition_20release_0',['v1.10 (Transition Release)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md749',1,'']]],
  ['v1_2011_20final_20transition_1',['v1.11 (Final Transition)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md750',1,'']]],
  ['v1_209_20current_2',['v1.9 (Current)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md748',1,'']]],
  ['v1_20x_20and_20v2_200_20together_3',['Q: Can I use v1.x and v2.0 together?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md498',1,'']]],
  ['v2_200_20new_20architecture_4',['v2.0 (New Architecture)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md751',1,'']]],
  ['v2_200_20project_20completion_20summary_5',['Messaging System v2.0 - Project Completion Summary',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html',1,'']]],
  ['v2_200_20together_6',['Q: Can I use v1.x and v2.0 together?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md498',1,'']]],
  ['valgrind_7',['valgrind',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1057',1,'Using Valgrind'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md307',1,'Using Valgrind']]],
  ['validation_8',['validation',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md325',1,'Input Validation'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1203',1,'Shell Script Validation'],['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md793',1,'Task 1.3: Configuration Validation']]],
  ['validation_20and_20deployment_20design_20document_9',['Phase 4: Validation and Deployment - Design Document',['../db/d5d/md_docs_2phase4_2DESIGN.html',1,'']]],
  ['validation_20checklist_10',['Validation Checklist',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md794',1,'']]],
  ['validation_20phases_11',['Validation Phases',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md859',1,'']]],
  ['validation_20script_12',['Dependency Validation Script',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md789',1,'']]],
  ['validation_20task_204_202_13',['5. Performance Validation (Task 4.2)',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md856',1,'']]],
  ['value_5fcontainer_14',['After (value_container)',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md722',1,'']]],
  ['value_5fcontainer_20tt_15',['Class: &lt;tt&gt;value_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md5',1,'']]],
  ['values_16',['values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md9',1,'Adding Values'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md10',1,'Retrieving Values'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md8',1,'Setting Values']]],
  ['variables_17',['variables',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1051',1,'Environment Variables'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md84',1,'Environment Variables'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md183',1,'Environment Variables']]],
  ['variant_20tt_18',['Class: &lt;tt&gt;variant&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md13',1,'']]],
  ['vault_19',['Using HashiCorp Vault',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md185',1,'']]],
  ['verification_20',['verification',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md795',1,'Post-build Verification'],['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md735',1,'Post-Removal Verification']]],
  ['verify_20installation_21',['4. Verify Installation',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md347',1,'']]],
  ['verifying_20successful_20build_22',['Verifying Successful Build',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md147',1,'']]],
  ['version_20conflicts_23',['Risk 4: Dependency Version Conflicts',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md771',1,'']]],
  ['versioning_24',['Configuration Versioning',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md763',1,'']]],
  ['vertical_20scaling_25',['vertical scaling',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1015',1,'Vertical Scaling'],['../d2/d64/md_docs_2architecture.html#autotoc_md104',1,'Vertical Scaling'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md221',1,'Vertical Scaling']]],
  ['visual_20studio_26',['Visual Studio',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md286',1,'']]],
  ['visual_20studio_20code_27',['Visual Studio Code',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md284',1,'']]],
  ['vs_20code_20integration_28',['VS Code Integration',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1212',1,'']]],
  ['vs_20mutex_20comparison_29',['Lock-free vs Mutex Comparison',['../df/d94/md_docs_2performance.html#autotoc_md627',1,'']]],
  ['vtune_30',['Using Intel VTune',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md313',1,'']]]
];
