var searchData=
[
  ['b_20code_20quality_20and_20linting_0',['B. Code Quality and Linting',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1243',1,'']]],
  ['b_20file_20relocation_20map_1',['B. File Relocation Map',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md781',1,'']]],
  ['b_3a_20automatic_20fetchcontent_20easiest_20for_20new_20users_2',['Option B: Automatic FetchContent (Easiest for New Users)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1181',1,'']]],
  ['backend_3',['backend',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md733',1,'4.2 Standalone Backend'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md734',1,'4.3 Integration Backend']]],
  ['backend_20interface_4',['4.1 Backend Interface',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md732',1,'']]],
  ['backend_20pattern_20week_204_5',['Phase 4: Backend Pattern (Week 4)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md731',1,'']]],
  ['backend_20pattern_20week_204_20✅_20completed_6',['Phase 4: Backend Pattern (Week 4) - ✅ COMPLETED',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md760',1,'']]],
  ['backup_7',['backup',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md560',1,'Application State Backup'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md561',1,'Database Backup']]],
  ['backup_20and_20recovery_8',['Backup and Recovery',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md558',1,'']]],
  ['backup_20strategy_9',['Backup Strategy',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md559',1,'']]],
  ['backward_20compatibility_10',['Backward Compatibility',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md746',1,'']]],
  ['balancer_20configuration_11',['Load Balancer Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md551',1,'']]],
  ['based_12',['based',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md189',1,'After (IExecutor-based)'],['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md186',1,'After (Result-based)'],['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md185',1,'Before (Exception-based)']]],
  ['based_20data_20handling_13',['2. Container-Based Data Handling',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md682',1,'']]],
  ['based_20error_20handling_14',['4. Exception-Based Error Handling',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md180',1,'']]],
  ['basic_20configuration_20file_15',['Basic Configuration File',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md687',1,'']]],
  ['basic_20message_20bus_20usage_16',['1. Basic Message Bus Usage',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md681',1,'']]],
  ['basic_20usage_17',['Basic Usage',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md684',1,'']]],
  ['batching_20and_20pipelining_18',['Batching and Pipelining',['../df/d94/md_docs_2performance.html#autotoc_md979',1,'']]],
  ['before_20direct_20output_19',['Before (Direct output)',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md194',1,'']]],
  ['before_20exception_20based_20',['Before (Exception-based)',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md185',1,'']]],
  ['before_20fix_21',['Initial State (PR #31 - Before Fix)',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1121',1,'']]],
  ['before_20internal_20container_22',['Before (Internal container)',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md191',1,'']]],
  ['before_20internal_20thread_20pool_23',['Before (Internal thread pool)',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md188',1,'']]],
  ['behavior_20sanitizer_24',['Undefined Behavior Sanitizer',['../dd/db6/md_docs_2archived_2phase4_2DESIGN.html#autotoc_md323',1,'']]],
  ['behavioral_20patterns_25',['Behavioral Patterns',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md595',1,'']]],
  ['being_20delivered_26',['Issue: Messages not being delivered',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md827',1,'']]],
  ['benchmark_20results_27',['Benchmark Results',['../df/d94/md_docs_2performance.html#autotoc_md953',1,'']]],
  ['benchmarking_28',['Benchmarking',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1193',1,'']]],
  ['benchmarks_29',['benchmarks',['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html#autotoc_md299',1,'Benchmarks'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1249',1,'C. Testing and Benchmarks'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1252',1,'Performance Benchmarks'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md754',1,'Performance Benchmarks'],['../d6/d40/md_docs_2archived_2phase4_2TEST__SUMMARY.html#autotoc_md366',1,'Performance Benchmarks']]],
  ['benchmarks_20from_20integration_20tests_30',['Benchmarks (from integration tests)',['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md399',1,'']]],
  ['benchmarks_20implemented_20awaiting_20execution_31',['Non-Functional ⚠️ 1/5 Verified (Benchmarks implemented, awaiting execution)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md769',1,'']]],
  ['benchmarks_20task_204_202_32',['3. Benchmarks (Task 4.2)',['../dd/db6/md_docs_2archived_2phase4_2DESIGN.html#autotoc_md319',1,'']]],
  ['best_20practices_33',['best practices',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md936',1,'Best Practices'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md627',1,'Best Practices'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md656',1,'Security Best Practices']]],
  ['binaries_34',['3. Prebuilt Dependency Binaries',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1140',1,'']]],
  ['blockquote_35',['&lt;/blockquote&gt;',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1185',1,'']]],
  ['blue_20green_20deployment_36',['Blue-Green Deployment',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md224',1,'']]],
  ['bottleneck_37',['Problem: Database Bottleneck',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1117',1,'']]],
  ['bottlenecks_38',['bottlenecks',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1085',1,'Identify CPU Bottlenecks'],['../df/d94/md_docs_2performance.html#autotoc_md991',1,'Network Bottlenecks']]],
  ['breaking_20changes_39',['breaking changes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md792',1,'Breaking Changes'],['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md209',1,'Breaking Changes'],['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md239',1,'Risk 3: Client Breaking Changes']]],
  ['bridge_20task_203_201_40',['1. Network Bridge (Task 3.1)',['../df/d85/md_docs_2archived_2phase3_2DESIGN.html#autotoc_md305',1,'']]],
  ['broker_20week_203_41',['Phase 3: Message Queue and Broker (Week 3)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md728',1,'']]],
  ['build_42',['build',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md505',1,'2. Configure Build'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md479',1,'Verifying Successful Build']]],
  ['build_20and_20install_43',['3. Build and Install',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md506',1,'']]],
  ['build_20and_20run_44',['2. Build and Run',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md690',1,'']]],
  ['build_20caching_20service_45',['2. Implement Build Caching Service',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1139',1,'']]],
  ['build_20configuration_20design_20document_46',['Build Configuration Design Document',['../de/df8/md_docs_2archived_2phase0_2BUILD__CONFIGURATION.html',1,'']]],
  ['build_20custom_20image_47',['Build Custom Image',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md512',1,'']]],
  ['build_20dependencies_48',['Build Dependencies',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md500',1,'']]],
  ['build_20for_20tests_49',['1. Use Release Build for Tests',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1130',1,'']]],
  ['build_20guard_20implementation_50',['Build Guard Implementation',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md200',1,'']]],
  ['build_20guide_51',['A. Advanced Build Guide',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1239',1,'']]],
  ['build_20issues_52',['build issues',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md661',1,'Build Issues'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1242',1,'Troubleshooting Build Issues']]],
  ['build_20issues_20and_20solutions_53',['Common Build Issues and Solutions',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md464',1,'']]],
  ['build_20modes_54',['Build Modes',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1197',1,'']]],
  ['build_20no_20external_20systems_55',['Alternative: Minimal Build (No External Systems)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md477',1,'']]],
  ['build_20options_56',['build options',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1201',1,'Build Options'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md678',1,'Custom Build Options']]],
  ['build_20parallelization_20✅_57',['3. Build Parallelization ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1126',1,'']]],
  ['build_20performance_20degradation_58',['Issue: Build performance degradation',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md828',1,'']]],
  ['build_20presets_59',['Available Build Presets',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1240',1,'']]],
  ['build_20profiles_60',['Build Profiles',['../de/df8/md_docs_2archived_2phase0_2BUILD__CONFIGURATION.html#autotoc_md138',1,'']]],
  ['build_20recommended_61',['Quick Build (Recommended)',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md677',1,'']]],
  ['build_20script_20options_62',['Build Script Options',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1241',1,'']]],
  ['build_20strategy_63',['Step 1: Choose Your Build Strategy',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1179',1,'']]],
  ['build_20success_64',['Build Success',['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html#autotoc_md269',1,'']]],
  ['build_20system_65',['Build System',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md650',1,'']]],
  ['build_20system_20and_20dependency_20refactoring_20design_20document_66',['Phase 1: Build System and Dependency Refactoring - Design Document',['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html',1,'']]],
  ['build_20system_20and_20external_20integration_20✅_67',['Phase 1: Build System and External Integration ✅',['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md383',1,'']]],
  ['build_20system_20improvements_20✅_68',['Build System Improvements ✅',['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md391',1,'']]],
  ['build_20system_20issues_69',['Risk 5: Build System Issues',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md242',1,'']]],
  ['build_20the_20project_70',['2. Build the Project',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md612',1,'']]],
  ['build_20the_20system_71',['3. Build the System',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md676',1,'']]],
  ['build_20troubleshooting_20guide_72',['Build Troubleshooting Guide',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html',1,'']]],
  ['build_20tt_73',['&lt;tt&gt;build&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md927',1,'']]],
  ['build_20verification_74',['Post-build Verification',['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html#autotoc_md265',1,'']]],
  ['build_20with_20tests_75',['Build with Tests',['../d6/d40/md_docs_2archived_2phase4_2TEST__SUMMARY.html#autotoc_md358',1,'']]],
  ['build_20workflow_76',['Recommended Build Workflow',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md473',1,'']]],
  ['build_5fconfiguration_2emd_77',['BUILD_CONFIGURATION.md',['../de/df9/BUILD__CONFIGURATION_8md.html',1,'']]],
  ['build_5ftroubleshooting_2emd_78',['BUILD_TROUBLESHOOTING.md',['../d5/dd8/BUILD__TROUBLESHOOTING_8md.html',1,'']]],
  ['builder_20pattern_79',['3. Builder Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md588',1,'']]],
  ['building_20from_20source_80',['🛠️ Building from Source',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1195',1,'']]],
  ['built_20in_20metrics_81',['1. Built-in Metrics',['../df/d94/md_docs_2performance.html#autotoc_md981',1,'']]],
  ['bus_82',['Message Bus',['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html#autotoc_md289',1,'']]],
  ['bus_20api_83',['bus api',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md814',1,'Message Bus API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md38',1,'Message Bus API']]],
  ['bus_20doesn_20t_20start_84',['Issue: Message bus doesn&apos;t start',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md826',1,'']]],
  ['bus_20implementation_85',['6.1 Message Bus Implementation',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md738',1,'']]],
  ['bus_20interface_86',['4. Message Bus Interface',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md796',1,'']]],
  ['bus_20usage_87',['bus usage',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md681',1,'1. Basic Message Bus Usage'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md805',1,'Step 4: Migrate Message Bus Usage']]],
  ['bus_20week_206_88',['Phase 6: Message Bus (Week 6)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md737',1,'']]],
  ['bus_20week_206_20✅_20completed_89',['Phase 6: Message Bus (Week 6) - ✅ COMPLETED',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md762',1,'']]],
  ['bus_20with_20di_90',['3. Message Bus with DI',['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html#autotoc_md281',1,'']]],
  ['business_20criteria_91',['Business Criteria',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md252',1,'']]],
  ['but_20recommended_92',['Step 5: Migrate to Patterns (Optional but Recommended)',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md806',1,'']]],
  ['by_20step_20migration_93',['Step-by-Step Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md799',1,'']]]
];
