var searchData=
[
  ['efficiency_0',['2. Increase vcpkg Cache Efficiency',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md918',1,'']]],
  ['elk_20stack_1',['Log Aggregation (ELK Stack)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md272',1,'']]],
  ['enable_20debug_20logging_2',['Enable Debug Logging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md847',1,'']]],
  ['enable_20lock_20free_20queues_3',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md529',1,'']]],
  ['encryption_4',['Data Encryption',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md298',1,'']]],
  ['end_20to_20end_20throughput_5',['End-to-End Throughput',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md152',1,'']]],
  ['enhancements_6',['enhancements',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md838',1,'Planned Enhancements'],['../d2/d64/md_docs_2architecture.html#autotoc_md129',1,'Planned Enhancements']]],
  ['environment_7',['Test Environment',['../df/d94/md_docs_2performance.html#autotoc_md648',1,'']]],
  ['environment_20configuration_8',['Environment Configuration',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md467',1,'']]],
  ['environment_20variables_9',['environment variables',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md239',1,'Environment Variables'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md849',1,'Environment Variables'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md84',1,'Environment Variables']]],
  ['error_20code_20conflicts_10',['Issue: Error code conflicts',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md519',1,'']]],
  ['error_20code_20range_11',['2. Error Code Range',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md488',1,'']]],
  ['error_20codes_12',['error codes',['../da/db6/md_docs_2FEATURES.html#autotoc_md427',1,'Error Codes'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md78',1,'Error Codes'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md79',1,'System Error Codes']]],
  ['error_20handling_13',['error handling',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md80',1,'Error Handling'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md637',1,'Error Handling'],['../da/db6/md_docs_2FEATURES.html#autotoc_md426',1,'Error Handling'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md707',1,'Error Handling'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md503',1,'Step 6: Update Error Handling']]],
  ['error_20messages_14',['Error Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md889',1,'']]],
  ['error_20recovery_15',['error recovery',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md822',1,'Error Recovery'],['../d2/d64/md_docs_2architecture.html#autotoc_md113',1,'Error Recovery']]],
  ['error_20recovery_20strategies_16',['Error Recovery Strategies',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md81',1,'']]],
  ['errors_17',['errors',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md890',1,'Connection Errors'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md893',1,'Database Errors'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md896',1,'Memory Errors']]],
  ['errors_20with_20old_20includes_18',['Issue: Compilation errors with old includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md518',1,'']]],
  ['evaluation_19',['evaluation',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md839',1,'Technology Evaluation'],['../d2/d64/md_docs_2architecture.html#autotoc_md130',1,'Technology Evaluation']]],
  ['event_20driven_20architecture_20',['17. Event-Driven Architecture',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md330',1,'']]],
  ['event_20streaming_21',['event streaming',['../da/db6/md_docs_2FEATURES.html#autotoc_md401',1,'Event Streaming'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md962',1,'Event Streaming'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md514',1,'Example 3: Event Streaming']]],
  ['event_20streaming_20pattern_22',['event streaming pattern',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md633',1,'Event Streaming Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md577',1,'Event Streaming Pattern']]],
  ['event_5fbatch_5fprocessor_20tt_23',['Class: &lt;tt&gt;event_batch_processor&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md591',1,'']]],
  ['event_5fcount_20tt_24',['&lt;tt&gt;event_count&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md588',1,'']]],
  ['event_5fstream_20tt_25',['Class: &lt;tt&gt;event_stream&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md580',1,'']]],
  ['event_5fstream_5fconfig_20tt_26',['Struct: &lt;tt&gt;event_stream_config&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md579',1,'']]],
  ['example_27',['example',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md957',1,'Basic Example'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md968',1,'Integration Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md613',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md597',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md622',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md590',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md628',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md22',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md575',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md76',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md68',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md64',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md55',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md48',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md36',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md26',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md12',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md549',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md555',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md564',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md569',1,'Usage Example']]],
  ['example_201_3a_20simple_20pub_20sub_20migration_28',['Example 1: Simple Pub/Sub Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md512',1,'']]],
  ['example_202_3a_20request_20reply_20migration_29',['Example 2: Request-Reply Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md513',1,'']]],
  ['example_203_3a_20event_20streaming_30',['Example 3: Event Streaming',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md514',1,'']]],
  ['example_204_3a_20message_20pipeline_31',['Example 4: Message Pipeline',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md515',1,'']]],
  ['example_20builds_32',['Example Builds',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md984',1,'']]],
  ['examples_33',['examples',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md959',1,'📖 Usage Examples'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md511',1,'Code Examples']]],
  ['execution_34',['execution',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md921',1,'1. Split Test Execution'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md34',1,'Query Execution']]],
  ['execution_20✅_35',['2. CTest Parallel Execution ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md912',1,'']]],
  ['executive_20summary_36',['executive summary',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md133',1,'Executive Summary'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md906',1,'Executive Summary']]],
  ['exhaustion_37',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md886',1,'']]],
  ['explore_20sample_20applications_38',['1. Explore Sample Applications',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md474',1,'']]],
  ['exposed_39',['Metrics Exposed',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md268',1,'']]],
  ['external_20systems_40',['external systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md201',1,'Alternative: Minimal Build (No External Systems)'],['../d2/d64/md_docs_2architecture.html#autotoc_md106',1,'External Systems'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md815',1,'External Systems'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md191',1,'Issue 2: GTest Not Found in External Systems']]]
];
