var searchData=
[
  ['each_20system_20contributes_0',['🧩 How Each System Contributes',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md832',1,'']]],
  ['easiest_20for_20new_20users_1',['Option B: Automatic FetchContent (Easiest for New Users)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md849',1,'']]],
  ['ecosystem_20integration_2',['🌟 Ecosystem Integration',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md830',1,'']]],
  ['efficiency_3',['2. Increase vcpkg Cache Efficiency',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md799',1,'']]],
  ['elk_20stack_4',['Log Aggregation (ELK Stack)',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md216',1,'']]],
  ['enable_20debug_20logging_5',['Enable Debug Logging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md728',1,'']]],
  ['enable_20lock_20free_20queues_6',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md503',1,'']]],
  ['encryption_7',['Data Encryption',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md242',1,'']]],
  ['engine_8',['2. &lt;strong&gt;thread_system&lt;/strong&gt; - Concurrency Engine',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md834',1,'']]],
  ['enhancements_9',['enhancements',['../d2/d64/md_docs_2architecture.html#autotoc_md129',1,'Planned Enhancements'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md719',1,'Planned Enhancements']]],
  ['environment_10',['Test Environment',['../df/d94/md_docs_2performance.html#autotoc_md622',1,'']]],
  ['environment_20configuration_11',['Environment Configuration',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md354',1,'']]],
  ['environment_20variables_12',['environment variables',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md84',1,'Environment Variables'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md183',1,'Environment Variables'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md730',1,'Environment Variables']]],
  ['error_20code_20conflicts_13',['Issue: Error code conflicts',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md493',1,'']]],
  ['error_20code_20mapping_14',['A. Error Code Mapping',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md448',1,'']]],
  ['error_20code_20range_15',['2. Error Code Range',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md462',1,'']]],
  ['error_20code_20range_20conflict_16',['1. Error Code Range Conflict',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md376',1,'']]],
  ['error_20codes_17',['error codes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md78',1,'Error Codes'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md79',1,'System Error Codes']]],
  ['error_20codes_20to_20common_5fsystem_18',['1.1 Add messaging_system Error Codes to common_system',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md391',1,'']]],
  ['error_20codes_20week_201_19',['Phase 1: Foundation and Error Codes (Week 1)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md390',1,'']]],
  ['error_20handling_20',['error handling',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md80',1,'Error Handling'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md611',1,'Error Handling'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md477',1,'Step 6: Update Error Handling']]],
  ['error_20messages_21',['Error Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md770',1,'']]],
  ['error_20recovery_22',['error recovery',['../d2/d64/md_docs_2architecture.html#autotoc_md113',1,'Error Recovery'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md703',1,'Error Recovery']]],
  ['error_20recovery_20strategies_23',['Error Recovery Strategies',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md81',1,'']]],
  ['errors_24',['errors',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md771',1,'Connection Errors'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md774',1,'Database Errors'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md777',1,'Memory Errors']]],
  ['errors_20with_20old_20includes_25',['Issue: Compilation errors with old includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md492',1,'']]],
  ['estimates_26',['Expected Performance (Estimates)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md860',1,'']]],
  ['evaluation_27',['evaluation',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md720',1,'Technology Evaluation'],['../d2/d64/md_docs_2architecture.html#autotoc_md130',1,'Technology Evaluation']]],
  ['event_20driven_20architecture_28',['17. Event-Driven Architecture',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md274',1,'']]],
  ['event_20driven_20microservice_20with_20tracing_29',['Example 3: Event-Driven Microservice with Tracing',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md857',1,'']]],
  ['event_20streaming_30',['Example 3: Event Streaming',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md488',1,'']]],
  ['event_20streaming_20pattern_31',['event streaming pattern',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md607',1,'Event Streaming Pattern'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md551',1,'Event Streaming Pattern']]],
  ['event_5fbatch_5fprocessor_20tt_32',['Class: &lt;tt&gt;event_batch_processor&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md565',1,'']]],
  ['event_5fcount_20tt_33',['&lt;tt&gt;event_count&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md562',1,'']]],
  ['event_5fstream_20tt_34',['Class: &lt;tt&gt;event_stream&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md554',1,'']]],
  ['event_5fstream_5fconfig_20tt_35',['Struct: &lt;tt&gt;event_stream_config&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md553',1,'']]],
  ['example_36',['example',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md596',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md587',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md602',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md22',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md571',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md564',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md543',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md538',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md529',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md523',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md36',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md48',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md55',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md64',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md549',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md68',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md76',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md26',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md12',1,'Usage Example']]],
  ['example_201_3a_20distributed_20task_20queue_20with_20persistence_37',['Example 1: Distributed Task Queue with Persistence',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md855',1,'']]],
  ['example_201_3a_20simple_20pub_20sub_20migration_38',['Example 1: Simple Pub/Sub Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md486',1,'']]],
  ['example_202_3a_20real_20time_20chat_20server_20with_20monitoring_39',['Example 2: Real-Time Chat Server with Monitoring',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md856',1,'']]],
  ['example_202_3a_20request_20reply_20migration_40',['Example 2: Request-Reply Migration',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md487',1,'']]],
  ['example_203_3a_20event_20driven_20microservice_20with_20tracing_41',['Example 3: Event-Driven Microservice with Tracing',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md857',1,'']]],
  ['example_203_3a_20event_20streaming_42',['Example 3: Event Streaming',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md488',1,'']]],
  ['example_204_3a_20message_20pipeline_43',['Example 4: Message Pipeline',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md489',1,'']]],
  ['examples_44',['examples',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md854',1,'🔥 Real-World Examples'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md485',1,'Code Examples']]],
  ['execution_45',['execution',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md802',1,'1. Split Test Execution'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md437',1,'Non-Functional ⚠️ 1/5 Verified (Benchmarks implemented, awaiting execution)'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md34',1,'Query Execution']]],
  ['execution_20✅_46',['2. CTest Parallel Execution ✅',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md793',1,'']]],
  ['executive_20summary_47',['executive summary',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md368',1,'Executive Summary'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md787',1,'Executive Summary']]],
  ['exhaustion_48',['Issue 3: Database Connection Pool Exhaustion',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md767',1,'']]],
  ['existing_20directory_20structure_49',['Existing Directory Structure',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md372',1,'']]],
  ['expected_20performance_20estimates_50',['Expected Performance (Estimates)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md860',1,'']]],
  ['explore_20sample_20applications_51',['1. Explore Sample Applications',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md361',1,'']]],
  ['exposed_52',['Metrics Exposed',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md212',1,'']]],
  ['external_20system_20documentation_53',['External System Documentation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md888',1,'']]],
  ['external_20systems_54',['external systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md827',1,'⚠️ Conditional Features (Requires External Systems)'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md145',1,'Alternative: Minimal Build (No External Systems)'],['../d2/d64/md_docs_2architecture.html#autotoc_md106',1,'External Systems'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md696',1,'External Systems'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'Issue 2: GTest Not Found in External Systems']]]
];
