var searchData=
[
  ['factory_20pattern_0',['2. Factory Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md255',1,'']]],
  ['failed_1',['&quot;Database connection failed&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md933',1,'']]],
  ['faq_2',['FAQ',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md881',1,'']]],
  ['fault_3',['&quot;Segmentation fault&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md937',1,'']]],
  ['fault_20tolerance_4',['fault tolerance',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md860',1,'Fault Tolerance'],['../d2/d64/md_docs_2architecture.html#autotoc_md112',1,'Fault Tolerance']]],
  ['feature_20coverage_5',['Feature Coverage',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md731',1,'']]],
  ['feature_20flag_20configuration_6',['Feature Flag Configuration',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md582',1,'']]],
  ['feature_20flags_7',['feature flags',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md504',1,'Feature Flags'],['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md627',1,'Task 1.2: Compiler Options and Feature Flags']]],
  ['features_8',['features',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md362',1,'2. Advanced Features'],['../df/d94/md_docs_2performance.html#autotoc_md456',1,'Key Performance Features']]],
  ['features_20fully_20implemented_9',['✅ Core Features (Fully Implemented)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md950',1,'']]],
  ['features_20headers_20only_20planned_10',['🚧 Integration Features (Headers Only - Planned)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md951',1,'']]],
  ['features_20requires_20external_20systems_11',['⚠️ Conditional Features (Requires External Systems)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md952',1,'']]],
  ['fedora_20rhel_12',['Linux (Fedora/RHEL)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md156',1,'']]],
  ['feedback_13',['💬 Feedback',['../index.html#autotoc_md801',1,'']]],
  ['fetchcontent_14',['As FetchContent',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1004',1,'']]],
  ['fetchcontent_20development_20environment_15',['Option 1: FetchContent (Development Environment)',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md501',1,'']]],
  ['fetchcontent_20easiest_20for_20new_20users_16',['Option B: Automatic FetchContent (Easiest for New Users)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md974',1,'']]],
  ['fetchcontent_20mode_17',['fetchcontent mode',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md992',1,'FetchContent Mode'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md142',1,'For Development (FetchContent Mode)']]],
  ['fetchcontent_20mode_20development_18',['FetchContent Mode (Development)',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md520',1,'']]],
  ['file_19',['Basic Configuration File',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md355',1,'']]],
  ['file_20format_20',['System Configuration File Format',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md83',1,'']]],
  ['file_20organization_21',['File Organization',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md294',1,'']]],
  ['file_20relocation_20map_22',['B. File Relocation Map',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md448',1,'']]],
  ['file_20structure_23',['Configuration File Structure',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md182',1,'']]],
  ['final_20transition_24',['v1.11 (Final Transition)',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md587',1,'']]],
  ['find_5fpackage_20mode_25',['find_package mode',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md143',1,'For Production (find_package Mode)'],['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md519',1,'System-Wide Installation (find_package mode)']]],
  ['find_5fpackage_20production_20environment_26',['Option 2: find_package (Production Environment)',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md502',1,'']]],
  ['firewall_20rules_27',['Firewall Rules',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md235',1,'']]],
  ['first_20application_28',['first application',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md281',1,'3. Your First Application'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md356',1,'First Application']]],
  ['first_20program_2060_20seconds_29',['Step 2: Your First Program (60 seconds)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md976',1,'']]],
  ['fix_20summary_30',['Quick Fix Summary',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md158',1,'']]],
  ['flag_20configuration_31',['Feature Flag Configuration',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md582',1,'']]],
  ['flag_20propagation_20strategy_32',['Flag Propagation Strategy',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md628',1,'']]],
  ['flags_33',['flags',['../d1/d57/md_docs_2phase0_2BUILD__CONFIGURATION.html#autotoc_md504',1,'Feature Flags'],['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md627',1,'Task 1.2: Compiler Options and Feature Flags']]],
  ['flow_34',['flow',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md968',1,'Message Flow'],['../d2/d64/md_docs_2architecture.html#autotoc_md100',1,'Request-Response Flow'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md848',1,'Request-Response Flow']]],
  ['flow_20architecture_35',['flow architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md98',1,'Data Flow Architecture'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md846',1,'Data Flow Architecture']]],
  ['flow_20tt_20test_5fcomplete_5fpubsub_5fflow_20tt_36',['1. Complete Pub/Sub Flow (&lt;tt&gt;test_complete_pubsub_flow&lt;/tt&gt;)',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md717',1,'']]],
  ['for_20contributors_37',['Option A: Local Development (Recommended for Contributors)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md973',1,'']]],
  ['for_20debugging_38',['Using GDB for Debugging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md890',1,'']]],
  ['for_20developers_39',['For Developers',['../index.html#autotoc_md793',1,'']]],
  ['for_20development_20fetchcontent_20mode_40',['For Development (FetchContent Mode)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md142',1,'']]],
  ['for_20guards_41',['CMake Configuration for Guards',['../dd/d64/md_docs_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md569',1,'']]],
  ['for_20new_20users_42',['for new users',['../index.html#autotoc_md792',1,'For New Users'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md974',1,'Option B: Automatic FetchContent (Easiest for New Users)']]],
  ['for_20production_20find_5fpackage_20mode_43',['For Production (find_package Mode)',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md143',1,'']]],
  ['for_20system_20administrators_44',['For System Administrators',['../index.html#autotoc_md794',1,'']]],
  ['format_45',['format',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1048',1,'Commit Message Format'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md316',1,'Commit Message Format'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md83',1,'System Configuration File Format']]],
  ['forward_20migration_20script_46',['Forward Migration Script',['../d3/d70/md_docs_2phase0_2MIGRATION__STRATEGY.html#autotoc_md596',1,'']]],
  ['found_47',['Issue 4: yaml-cpp Not Found',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md139',1,'']]],
  ['found_20in_20external_20systems_48',['Issue 2: GTest Not Found in External Systems',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md135',1,'']]],
  ['foundation_49',['1. &lt;strong&gt;common_system&lt;/strong&gt; - The Foundation',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md958',1,'']]],
  ['foundation_20and_20error_20codes_20week_201_50',['Phase 1: Foundation and Error Codes (Week 1)',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md390',1,'']]],
  ['foundation_20and_20preparation_20✅_51',['Phase 0: Foundation and Preparation ✅',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md748',1,'']]],
  ['foundation_20week_201_20✅_20completed_52',['Phase 1: Foundation (Week 1) - ✅ COMPLETED',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md425',1,'']]],
  ['framework_53',['Test Framework',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md997',1,'']]],
  ['framework_20task_204_201_54',['1. Unit Test Framework (Task 4.1)',['../db/d5d/md_docs_2phase4_2DESIGN.html#autotoc_md684',1,'']]],
  ['free_20vs_20mutex_20comparison_55',['Lock-free vs Mutex Comparison',['../df/d94/md_docs_2performance.html#autotoc_md464',1,'']]],
  ['from_20integration_20tests_56',['Benchmarks (from integration tests)',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md766',1,'']]],
  ['from_20source_57',['from source',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md988',1,'🛠️ Building from Source'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md171',1,'From Source']]],
  ['fully_20implemented_58',['✅ Core Features (Fully Implemented)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md950',1,'']]],
  ['function_20conversion_59',['Pattern 1: Simple Function Conversion',['../d6/df5/md_docs_2phase2_2DESIGN.html#autotoc_md651',1,'']]],
  ['functional_60',['functional',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md436',1,'Functional'],['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md437',1,'Non-Functional']]],
  ['functionality_61',['Functionality',['../d5/d7c/md_docs_2phase1_2DESIGN.html#autotoc_md637',1,'']]],
  ['future_20considerations_62',['future considerations',['../d2/d64/md_docs_2architecture.html#autotoc_md128',1,'Future Considerations'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md876',1,'Future Considerations']]],
  ['future_20enhancements_63',['future enhancements',['../df/d5e/md_docs_2phase4_2TEST__SUMMARY.html#autotoc_md741',1,'Future Enhancements'],['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md778',1,'Future Enhancements']]],
  ['future_20work_64',['Known Limitations and Future Work',['../da/da3/md_docs_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md776',1,'']]]
];
