var searchData=
[
  ['s_20included_0',['📦 What&apos;s Included',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2072',1,'']]],
  ['safety_1',['safety',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1164',1,'Memory Safety'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1597',1,'Thread Safety'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1184',1,'Thread Safety'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md186',1,'Thread Safety']]],
  ['sample_20applications_2',['1. Explore Sample Applications',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1001',1,'']]],
  ['sample_20client_3',['3. Test with Sample Client',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md999',1,'']]],
  ['saving_20checkpoints_4',['Saving Checkpoints',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1840',1,'']]],
  ['scalability_5',['scalability',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md488',1,'Scalability'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1180',1,'Scalability'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md475',1,'Worker Scalability']]],
  ['scalability_20patterns_6',['scalability patterns',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md202',1,'Scalability Patterns'],['../d2/d64/md_docs_2architecture.html#autotoc_md389',1,'Scalability Patterns']]],
  ['scale_7',['By Scale',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1683',1,'']]],
  ['scaling_8',['scaling',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1126',1,'Connection Scaling'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md809',1,'Database Scaling'],['../d2/d64/md_docs_2architecture.html#autotoc_md390',1,'Horizontal Scaling'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md203',1,'Horizontal Scaling'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md804',1,'Horizontal Scaling'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md482',1,'Memory Scaling'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md490',1,'Publisher/Subscriber Scaling'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md489',1,'Thread Scaling'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md204',1,'Vertical Scaling'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md807',1,'Vertical Scaling'],['../d2/d64/md_docs_2architecture.html#autotoc_md391',1,'Vertical Scaling']]],
  ['scaling_20characteristics_9',['Scaling Characteristics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1121',1,'']]],
  ['scaling_20rules_10',['Auto-scaling Rules',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md806',1,'']]],
  ['scaling_20strategies_11',['Scaling Strategies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md803',1,'']]],
  ['scenarios_12',['Deployment Scenarios',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md773',1,'']]],
  ['schedule_20management_13',['Schedule Management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1429',1,'']]],
  ['schedule_20registration_14',['Schedule Registration',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1428',1,'']]],
  ['scheduled_20chord_15',['Scheduled Chord',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1850',1,'']]],
  ['scheduled_20tasks_16',['Scheduled Tasks',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1827',1,'']]],
  ['scheduleeventcallable_17',['scheduleeventcallable',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md696',1,'ScheduleEventCallable'],['../da/db6/md_docs_2FEATURES.html#autotoc_md613',1,'ScheduleEventCallable']]],
  ['scheduler_18',['scheduler',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2037',1,'6.1 Periodic Task Scheduler'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1748',1,'After (Task Scheduler)'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2036',1,'Phase 6: Scheduler'],['../da/db6/md_docs_2FEATURES.html#autotoc_md601',1,'Task Scheduler']]],
  ['scheduler_20✅_19',['Sprint 5: Scheduler ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2050',1,'']]],
  ['scheduler_20performance_20',['Scheduler Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md477',1,'']]],
  ['schedules_21',['Managing Schedules',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1831',1,'']]],
  ['scheduling_22',['Cron-Based Scheduling',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1829',1,'']]],
  ['scheduling_20convenience_23',['Scheduling (Convenience)',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1457',1,'']]],
  ['scheduling_20tasks_24',['Scheduling Tasks',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1922',1,'']]],
  ['secrets_25',['Using Kubernetes Secrets',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md772',1,'']]],
  ['secrets_20management_26',['Secrets Management',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md770',1,'']]],
  ['secure_20communication_27',['Secure Communication',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md887',1,'']]],
  ['security_28',['security',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md823',1,'Application Security'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md217',1,'Application Security'],['../d2/d64/md_docs_2architecture.html#autotoc_md404',1,'Application Security'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md820',1,'Network Security'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1182',1,'Security'],['../d2/d64/md_docs_2architecture.html#autotoc_md403',1,'Transport Security'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md216',1,'Transport Security']]],
  ['security_20best_20practices_29',['Security Best Practices',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md885',1,'']]],
  ['security_20considerations_30',['security considerations',['../d2/d64/md_docs_2architecture.html#autotoc_md402',1,'Security Considerations'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md215',1,'Security Considerations']]],
  ['security_20hardening_31',['Security Hardening',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md819',1,'']]],
  ['segmentation_20fault_32',['&quot;Segmentation fault&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1064',1,'']]],
  ['selection_20via_20templates_33',['Alternative B: Compile-time Logger Selection via Templates',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md18',1,'']]],
  ['self_20hosted_20runners_34',['1. Use Self-Hosted Runners',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md251',1,'']]],
  ['separation_20of_20concerns_35',['Separation of Concerns',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1261',1,'']]],
  ['serialization_36',['serialization',['../da/db6/md_docs_2FEATURES.html#autotoc_md629',1,'Message Serialization'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1356',1,'Serialization'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md275',1,'Serialization']]],
  ['serialization_20performance_37',['Serialization Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1123',1,'']]],
  ['server_38',['3. Network Client/Server',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md991',1,'']]],
  ['server_20chat_5fserver_20cpp_39',['1. Chat Server (chat_server.cpp)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md997',1,'']]],
  ['server_20deployment_40',['Single Server Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md774',1,'']]],
  ['service_41',['2. Implement Build Caching Service',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md252',1,'']]],
  ['service_20and_20ingress_42',['Service and Ingress',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md781',1,'']]],
  ['service_20container_20api_43',['Service Container API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md314',1,'']]],
  ['service_20lifetimes_44',['Service Lifetimes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md318',1,'']]],
  ['service_20recovery_45',['Service Recovery',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md817',1,'']]],
  ['service_20won_20t_20start_46',['service won t start',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1066',1,'Problem: Service Won&apos;t Start'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md831',1,'Service Won&apos;t Start']]],
  ['service_5fcontainer_20tt_47',['Class: &lt;tt&gt;service_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md316',1,'']]],
  ['set_5fdefault_5ftopic_20tt_48',['&lt;tt&gt;set_default_topic&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md94',1,'']]],
  ['setting_20priority_49',['Setting Priority',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1822',1,'']]],
  ['setting_20values_50',['Setting Values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md272',1,'']]],
  ['settings_51',['settings',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1659',1,'Concurrency Settings'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1654',1,'Delayed Queue Settings'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1669',1,'Environment-Specific Settings'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1661',1,'Prefetch Settings']]],
  ['setup_52',['setup',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md840',1,'1. Clone and Setup'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md980',1,'2. Platform-Specific Setup'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md843',1,'Development Setup'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md900',1,'Installation &amp; Setup'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md795',1,'Monitoring Setup'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1823',1,'Priority Queue Setup']]],
  ['sharding_53',['2. Implement Test Sharding',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md248',1,'']]],
  ['sharding_20strategy_54',['Sharding Strategy',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md811',1,'']]],
  ['short_55',['Timeout Too Short',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1760',1,'']]],
  ['short_20term_20quick_20wins_56',['Short-Term (Quick Wins)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md242',1,'']]],
  ['shut_20down_20the_20system_57',['Q: How do I gracefully shut down the system?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1977',1,'']]],
  ['simd_20optimization_20impact_58',['SIMD Optimization Impact',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1124',1,'']]],
  ['simd_20utilization_59',['SIMD Utilization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1136',1,'']]],
  ['simple_20pub_20sub_20migration_60',['Example 1: Simple Pub/Sub Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md947',1,'']]],
  ['simple_20publish_20subscribe_61',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md965',1,'']]],
  ['single_20server_20deployment_62',['Single Server Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md774',1,'']]],
  ['singleton_20pattern_63',['1. Singleton Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md62',1,'']]],
  ['slow_20message_20processing_64',['Problem: Slow Message Processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1067',1,'']]],
  ['small_20messages_65',['Issue 1: High CPU Usage with Small Messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1050',1,'']]],
  ['software_20dependencies_66',['Software Dependencies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md753',1,'']]],
  ['solutions_67',['solutions',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md718',1,'Common Build Issues and Solutions'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md236',1,'Implemented Solutions'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1738',1,'Migration from Custom Solutions']]],
  ['source_68',['From Source',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md757',1,'']]],
  ['spawning_69',['Subtask Spawning',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1843',1,'']]],
  ['spawning_20subtasks_70',['Spawning Subtasks',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1844',1,'']]],
  ['specific_20architecture_71',['Component-Specific Architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md375',1,'']]],
  ['specific_20notes_72',['Platform-Specific Notes',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md739',1,'']]],
  ['specific_20settings_73',['Environment-Specific Settings',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1669',1,'']]],
  ['specific_20setup_74',['2. Platform-Specific Setup',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md980',1,'']]],
  ['split_20test_20execution_75',['1. Split Test Execution',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md247',1,'']]],
  ['sprint_76',['Priority 2 (Recommended - Next Sprint)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md256',1,'']]],
  ['sprint_201_3a_20core_20task_20infrastructure_20✅_77',['Sprint 1: Core Task Infrastructure ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2046',1,'']]],
  ['sprint_202_3a_20queue_20result_20backend_20✅_78',['Sprint 2: Queue &amp; Result Backend ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2047',1,'']]],
  ['sprint_203_3a_20worker_20system_20✅_79',['Sprint 3: Worker System ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2048',1,'']]],
  ['sprint_204_3a_20client_20async_20result_20✅_80',['Sprint 4: Client &amp; Async Result ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2049',1,'']]],
  ['sprint_205_3a_20scheduler_20✅_81',['Sprint 5: Scheduler ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2050',1,'']]],
  ['sprint_206_3a_20monitoring_20system_20integration_20✅_82',['Sprint 6: Monitoring &amp; System Integration ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2051',1,'']]],
  ['sprint_207_3a_20testing_20documentation_20✅_83',['Sprint 7: Testing &amp; Documentation ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2052',1,'']]],
  ['ssl_20tls_20configuration_84',['SSL/TLS Configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md822',1,'']]],
  ['stack_85',['Log Aggregation (ELK Stack)',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md802',1,'']]],
  ['stage_5fcount_20tt_86',['&lt;tt&gt;stage_count&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md157',1,'']]],
  ['staging_20environment_87',['Staging Environment',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1671',1,'']]],
  ['standalone_20backend_88',['Standalone Backend',['../da/db6/md_docs_2FEATURES.html#autotoc_md622',1,'']]],
  ['standard_20is_20required_89',['Q: What C++ standard is required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md897',1,'']]],
  ['standards_90',['standards',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1321',1,'📖 Documentation Standards'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md852',1,'Coding Standards'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md572',1,'Coding Standards'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md857',1,'Documentation Standards'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1191',1,'Industry Standards']]],
  ['start_91',['start',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2083',1,'🚀 Quick Start'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md955',1,'Issue: Message bus doesn&apos;t start'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1066',1,'Problem: Service Won&apos;t Start'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md838',1,'Quick Start'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md988',1,'Quick Start'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md831',1,'Service Won&apos;t Start']]],
  ['start_20guide_92',['Task Module Quick Start Guide',['../d9/dff/md_docs_2task_2QUICK__START.html',1,'']]],
  ['start_20the_20system_93',['4. Start the System',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1917',1,'']]],
  ['start_20tt_20tt_20stop_20tt_94',['start tt tt stop tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md121',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md141',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md155',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;']]],
  ['started_95',['started',['../da/db6/md_docs_2FEATURES.html#autotoc_md659',1,'Getting Started'],['../d6/d63/md_docs_2guides_2QUICK__START.html',1,'Getting Started'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md566',1,'Getting Started']]],
  ['state_20backup_96',['Application State Backup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md814',1,'']]],
  ['state_20methods_97',['State Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1350',1,'']]],
  ['state_20pr_2030_20success_98',['Target State (PR #30 - Success)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md235',1,'']]],
  ['state_20pr_2031_20before_20fix_99',['Initial State (PR #31 - Before Fix)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md234',1,'']]],
  ['statement_100',['Problem Statement',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md4',1,'']]],
  ['static_20analysis_101',['Static Analysis',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1163',1,'']]],
  ['static_20configuration_102',['static configuration',['../d2/d64/md_docs_2architecture.html#autotoc_md410',1,'Static Configuration'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md223',1,'Static Configuration']]],
  ['static_20methods_103',['Static Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1438',1,'']]],
  ['statistics_104',['statistics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1026',1,'Network Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1444',1,'Queue Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1458',1,'Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1394',1,'Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1398',1,'Statistics']]],
  ['status_105',['status',['../index.html#autotoc_md55',1,'ADR Status'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1959',1,'Check Queue Status'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1960',1,'Check Worker Status'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md21',1,'Current Implementation Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1407',1,'Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1397',1,'Status'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md1',1,'Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1445',1,'Worker Status']]],
  ['status_20methods_106',['Status Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1410',1,'']]],
  ['step_201_3a_20update_20dependencies_107',['Step 1: Update Dependencies',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md929',1,'']]],
  ['step_202_3a_20update_20includes_108',['Step 2: Update Includes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md932',1,'']]],
  ['step_203_3a_20migrate_20message_20creation_109',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md933',1,'']]],
  ['step_204_3a_20migrate_20message_20bus_20usage_110',['Step 4: Migrate Message Bus Usage',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md934',1,'']]],
  ['step_205_3a_20migrate_20to_20patterns_20optional_20but_20recommended_111',['Step 5: Migrate to Patterns (Optional but Recommended)',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md935',1,'']]],
  ['step_206_3a_20update_20error_20handling_112',['Step 6: Update Error Handling',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md938',1,'']]],
  ['step_207_3a_20integration_20with_20other_20systems_113',['Step 7: Integration with Other Systems',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md939',1,'']]],
  ['step_20by_20step_20migration_114',['Step-by-Step Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md928',1,'']]],
  ['steps_115',['steps',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1000',1,'Next Steps'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1927',1,'Next Steps']]],
  ['still_20use_20simple_20publish_20subscribe_116',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md965',1,'']]],
  ['stop_20the_20system_117',['6. Stop the System',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1919',1,'']]],
  ['stop_20tt_118',['stop tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md155',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md141',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md121',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;']]],
  ['strace_119',['System Tracing with strace',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1033',1,'']]],
  ['strategies_120',['strategies',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md345',1,'Error Recovery Strategies'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1813',1,'Retry Strategies'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md803',1,'Scaling Strategies']]],
  ['strategy_121',['strategy',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md813',1,'Backup Strategy'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md811',1,'Sharding Strategy'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1167',1,'Testing Strategy']]],
  ['strategy_20pattern_122',['strategy pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md73',1,'10. Strategy Pattern'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1607',1,'5. Strategy Pattern']]],
  ['streaming_123',['streaming',['../da/db6/md_docs_2FEATURES.html#autotoc_md593',1,'Event Streaming'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md676',1,'Event Streaming'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2092',1,'Event Streaming'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md949',1,'Example 3: Event Streaming']]],
  ['streaming_20pattern_124',['streaming pattern',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md124',1,'Event Streaming Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md180',1,'Event Streaming Pattern']]],
  ['struct_3a_20tt_20event_5fstream_5fconfig_20tt_125',['Struct: &lt;tt&gt;event_stream_config&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md126',1,'']]],
  ['struct_3a_20tt_20pipeline_5fstage_20tt_126',['Struct: &lt;tt&gt;pipeline_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md150',1,'']]],
  ['structural_20patterns_127',['Structural Patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md66',1,'']]],
  ['structure_128',['structure',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md924',1,'3. Message Structure'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1244',1,'CMake Structure'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md768',1,'Configuration File Structure'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md306',1,'Configuration Structure'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2054',1,'File Structure'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1265',1,'Future Structure'],['../da/db6/md_docs_2FEATURES.html#autotoc_md627',1,'Message Structure'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'Messaging System Project Structure'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md849',1,'Project Structure'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md993',1,'Project Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1646',1,'Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1651',1,'Structure'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1437',1,'Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1657',1,'Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1664',1,'Structure'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md862',1,'Test Structure']]],
  ['structured_20logging_129',['Structured Logging',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md801',1,'']]],
  ['structures_130',['structures',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1442',1,'Structures'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1417',1,'Structures'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1374',1,'Structures'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1426',1,'Structures']]],
  ['studio_131',['Visual Studio',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md847',1,'']]],
  ['studio_20code_132',['Visual Studio Code',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md845',1,'']]],
  ['style_20guide_133',['C++ Style Guide',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md853',1,'']]],
  ['sub_134',['sub',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md485',1,'Latency Distribution (Pub/Sub)'],['../d4/d54/md_docs_2API__REFERENCE__KO.html#autotoc_md365',1,'Pub/Sub'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md674',1,'Pub/Sub'],['../d5/ddb/md_docs_2BENCHMARKS__KO.html#autotoc_md522',1,'Pub/Sub']]],
  ['sub_20migration_135',['Example 1: Simple Pub/Sub Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md947',1,'']]],
  ['sub_20pattern_136',['sub pattern',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2090',1,'Pub/Sub Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md591',1,'Pub/Sub Pattern'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md936',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md178',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md87',1,'Pub/Sub Pattern']]],
  ['sub_20performance_137',['Pub/Sub Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md464',1,'']]],
  ['subdirectory_138',['Subdirectory',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1077',1,'']]],
  ['submission_139',['Job Submission',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md325',1,'']]],
  ['submission_20convenience_140',['Task Submission (Convenience)',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1456',1,'']]],
  ['submission_20flow_141',['Task Submission Flow',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1595',1,'']]],
  ['submit_20a_20task_142',['5. Submit a Task',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1918',1,'']]],
  ['submitting_20to_20priority_20queues_143',['Submitting to Priority Queues',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1824',1,'']]],
  ['subscribe_144',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md965',1,'']]],
  ['subscribe_20to_20topics_145',['Q: How do I subscribe to topics?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md906',1,'']]],
  ['subscribe_20tt_146',['subscribe tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md131',1,'&lt;tt&gt;subscribe&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md100',1,'&lt;tt&gt;subscribe&lt;/tt&gt;']]],
  ['subscriber_20scaling_147',['Publisher/Subscriber Scaling',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md490',1,'']]],
  ['subscriber_20tt_148',['Class: &lt;tt&gt;subscriber&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md97',1,'']]],
  ['subscription_149',['Subscription',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md309',1,'']]],
  ['subscription_20count_20impact_150',['Subscription Count Impact',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md462',1,'']]],
  ['subscription_20management_151',['Subscription Management',['../da/db6/md_docs_2FEATURES.html#autotoc_md633',1,'']]],
  ['subscriptioncallable_152',['subscriptioncallable',['../da/db6/md_docs_2FEATURES.html#autotoc_md617',1,'SubscriptionCallable'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md700',1,'SubscriptionCallable']]],
  ['subscriptions_153',['Event Subscriptions',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1448',1,'']]],
  ['subsystems_154',['Integration with Subsystems',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1079',1,'']]],
  ['subtask_20management_155',['Subtask Management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1379',1,'']]],
  ['subtask_20spawning_156',['Subtask Spawning',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1843',1,'']]],
  ['subtasks_157',['subtasks',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1844',1,'Spawning Subtasks'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1845',1,'Tracking Subtasks']]],
  ['success_158',['Target State (PR #30 - Success)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md235',1,'']]],
  ['successful_20build_159',['Verifying Successful Build',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md733',1,'']]],
  ['suites_160',['Test Suites',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2106',1,'']]],
  ['summary_161',['summary',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md446',1,'Executive Summary'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md232',1,'Executive Summary'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2015',1,'Executive Summary'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md478',1,'Performance Targets Summary'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md744',1,'Quick Fix Summary'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md83',1,'Summary']]],
  ['support_162',['support',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2117',1,'🌐 Platform Support'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2125',1,'📬 Contact &amp; Support'],['../da/db6/md_docs_2FEATURES.html#autotoc_md620',1,'Backend Support'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md752',1,'Operating System Support'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1204',1,'Support'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md970',1,'Support'],['../da/db6/md_docs_2FEATURES.html#autotoc_md655',1,'Testing Support'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md299',1,'Transaction Support']]],
  ['supported_163',['Q: Which platforms are supported?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md898',1,'']]],
  ['supported_20macos_164',['Issue 3: grep -P Not Supported (macOS)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md723',1,'']]],
  ['supported_20syntax_165',['Supported Syntax',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1436',1,'']]],
  ['supported_20types_166',['Supported Types',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md278',1,'']]],
  ['synchronous_20rpc_20latency_167',['Synchronous RPC Latency',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md469',1,'']]],
  ['syntax_168',['Supported Syntax',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1436',1,'']]],
  ['system_169',['system',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md194',1,'1. Container System'],['../d2/d64/md_docs_2architecture.html#autotoc_md381',1,'1. Container System'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1915',1,'2. Create and Configure the Task System'],['../d2/d64/md_docs_2architecture.html#autotoc_md382',1,'2. Network System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md195',1,'2. Network System'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md984',1,'3. Build the System'],['../d2/d64/md_docs_2architecture.html#autotoc_md383',1,'3. Database System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md196',1,'3. Database System'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1917',1,'4. Start the System'],['../d2/d64/md_docs_2architecture.html#autotoc_md384',1,'4. Thread System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md197',1,'4. Thread System'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1919',1,'6. Stop the System'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1243',1,'Build System'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md879',1,'Build System'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html',1,'Contributing to Messaging System'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2021',1,'Phase 2: Worker System'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1977',1,'Q: How do I gracefully shut down the system?'],['../da/db6/md_docs_2FEATURES.html#autotoc_md596',1,'Task Queue System'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1319',1,'Task Queue System']]],
  ['system_20✅_170',['Sprint 3: Worker System ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2048',1,'']]],
  ['system_20기능_171',['Messaging System 기능',['../d4/d0c/md_docs_2FEATURES__KO.html',1,'']]],
  ['system_20문서_172',['Messaging System 문서',['../d8/d0a/md_docs_2README__KO.html',1,'']]],
  ['system_20변경_20이력_173',['Messaging System 변경 이력',['../db/d9f/md_docs_2CHANGELOG__KO.html',1,'']]],
  ['system_20성능_20벤치마크_174',['Messaging System 성능 벤치마크',['../d5/ddb/md_docs_2BENCHMARKS__KO.html',1,'']]],
  ['system_20아키텍처_175',['Messaging System 아키텍처',['../de/de3/md_docs_2ARCHITECTURE__KO.html',1,'']]],
  ['system_20프로덕션_20품질_176',['Messaging System 프로덕션 품질',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html',1,'']]],
  ['system_20프로젝트_20구조_177',['Messaging System 프로젝트 구조',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html',1,'']]],
  ['system_20administrators_178',['For System Administrators',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1314',1,'']]],
  ['system_20api_179',['system api',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md267',1,'Container System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md292',1,'Database System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md334',1,'Logger System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md281',1,'Network System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md321',1,'Thread System API']]],
  ['system_20api_20레퍼런스_180',['Messaging System API 레퍼런스',['../d4/d54/md_docs_2API__REFERENCE__KO.html',1,'']]],
  ['system_20architecture_181',['system architecture',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html',1,'System Architecture'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1582',1,'System Architecture']]],
  ['system_20changelog_182',['Messaging System Changelog',['../da/dee/md_docs_2CHANGELOG.html',1,'']]],
  ['system_20configuration_183',['Task System Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1645',1,'']]],
  ['system_20configuration_20file_20format_184',['System Configuration File Format',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md347',1,'']]],
  ['system_20cron_185',['Before (System Cron)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1747',1,'']]],
  ['system_20error_20codes_186',['System Error Codes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md343',1,'']]],
  ['system_20facade_187',['Task System Facade',['../da/db6/md_docs_2FEATURES.html#autotoc_md598',1,'']]],
  ['system_20features_188',['Messaging System Features',['../da/db6/md_docs_2FEATURES.html',1,'']]],
  ['system_20health_189',['System Health',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md836',1,'']]],
  ['system_20improvement_20plan_190',['Distributed Task Queue System - Improvement Plan',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html',1,'']]],
  ['system_20integration_191',['system integration',['../da/db6/md_docs_2FEATURES.html#autotoc_md650',1,'Container System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md648',1,'Logger System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md649',1,'Monitoring System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md647',1,'Thread System Integration']]],
  ['system_20integration_20✅_192',['Sprint 6: Monitoring &amp; System Integration ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2051',1,'']]],
  ['system_20layers_193',['system layers',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md192',1,'System Layers'],['../d2/d64/md_docs_2architecture.html#autotoc_md379',1,'System Layers']]],
  ['system_20overview_194',['System Overview',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2080',1,'']]],
  ['system_20performance_195',['system performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1122',1,'Container System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1128',1,'Database System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1125',1,'Network System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1115',1,'Overall System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1119',1,'Thread System Performance']]],
  ['system_20performance_20benchmarks_196',['Messaging System Performance Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html',1,'']]],
  ['system_20production_20quality_197',['Messaging System Production Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html',1,'']]],
  ['system_20project_20structure_198',['Messaging System Project Structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'']]],
  ['system_20requirements_199',['system requirements',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md975',1,'System Requirements'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md747',1,'System Requirements']]],
  ['system_20support_200',['Operating System Support',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md752',1,'']]],
  ['system_20tracing_20with_20strace_201',['System Tracing with strace',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1033',1,'']]],
  ['system_20tuning_202',['System Tuning',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md785',1,'']]],
  ['system_5farchitecture_2emd_203',['SYSTEM_ARCHITECTURE.md',['../db/d93/SYSTEM__ARCHITECTURE_8md.html',1,'']]],
  ['systems_204',['systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2095',1,'🌟 Integration with Base Systems'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md731',1,'Alternative: Minimal Build (No External Systems)'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md503',1,'Comparison with Other Systems'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md206',1,'External Systems'],['../d2/d64/md_docs_2architecture.html#autotoc_md393',1,'External Systems'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1743',1,'From Message Queue Systems'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md721',1,'Issue 2: GTest Not Found in External Systems'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2097',1,'Optional Systems'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2096',1,'Required Systems'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md939',1,'Step 7: Integration with Other Systems']]]
];
