var searchData=
[
  ['ubuntu_20debian_0',['ubuntu debian',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md508',1,'APT Repository (Ubuntu/Debian)'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md673',1,'Linux (Ubuntu/Debian)'],['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md487',1,'Linux (Ubuntu/Debian)']]],
  ['ulimit_20configuration_1',['ulimit Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md533',1,'']]],
  ['undefined_20behavior_20sanitizer_2',['Undefined Behavior Sanitizer',['../dd/db6/md_docs_2archived_2phase4_2DESIGN.html#autotoc_md323',1,'']]],
  ['unified_20cmake_20configuration_20options_3',['Unified CMake Configuration Options',['../de/df8/md_docs_2archived_2phase0_2BUILD__CONFIGURATION.html#autotoc_md136',1,'']]],
  ['unit_20test_20framework_20task_204_201_4',['1. Unit Test Framework (Task 4.1)',['../dd/db6/md_docs_2archived_2phase4_2DESIGN.html#autotoc_md317',1,'']]],
  ['unit_20testing_5',['Unit Testing',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md632',1,'']]],
  ['unit_20tests_6',['unit tests',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md752',1,'Unit Tests'],['../df/d0f/md_docs_2archived_2phase2_2DESIGN.html#autotoc_md297',1,'Unit Tests'],['../d6/d40/md_docs_2archived_2phase4_2TEST__SUMMARY.html#autotoc_md337',1,'Unit Tests']]],
  ['unsubscribe_20tt_7',['&lt;tt&gt;unsubscribe&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md891',1,'']]],
  ['unsubscribe_5fall_20tt_8',['&lt;tt&gt;unsubscribe_all&lt;/tt&gt;',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md860',1,'']]],
  ['update_20cmakelists_20txt_9',['Update CMakeLists.txt',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md801',1,'']]],
  ['update_20dependencies_10',['Step 1: Update Dependencies',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md800',1,'']]],
  ['update_20error_20handling_11',['Step 6: Update Error Handling',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md809',1,'']]],
  ['update_20include_20paths_12',['Update Include Paths',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md802',1,'']]],
  ['update_20includes_13',['Step 2: Update Includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md803',1,'']]],
  ['updated_20cmakelists_20txt_20structure_14',['Updated CMakeLists.txt Structure',['../d1/da1/md_docs_2archived_2phase1_2DESIGN.html#autotoc_md258',1,'']]],
  ['updates_15',['🔄 Documentation Updates',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1008',1,'']]],
  ['usage_16',['usage',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md681',1,'1. Basic Message Bus Usage'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md684',1,'Basic Usage'],['../df/d94/md_docs_2performance.html#autotoc_md989',1,'High CPU Usage'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md578',1,'High Memory Usage'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1116',1,'Problem: High Memory Usage'],['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md400',1,'Resource Usage'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md805',1,'Step 4: Migrate Message Bus Usage']]],
  ['usage_20analysis_17',['Memory Usage Analysis',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1088',1,'']]],
  ['usage_20example_18',['usage example',['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md855',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md861',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md870',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md875',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md881',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md896',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md903',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md919',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md934',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md22',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md26',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md36',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md48',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md55',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md64',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md68',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md76',1,'Usage Example'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md12',1,'Usage Example'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md928',1,'Usage Example']]],
  ['usage_20pattern_19',['Usage Pattern',['../da/dab/md_docs_2archived_2phase0_2INTERFACE__MAPPING.html#autotoc_md170',1,'']]],
  ['usage_20with_20small_20messages_20',['Issue 1: High CPU Usage with Small Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1097',1,'']]],
  ['use_20release_20build_20for_20tests_21',['1. Use Release Build for Tests',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1130',1,'']]],
  ['use_20self_20hosted_20runners_22',['1. Use Self-Hosted Runners',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1138',1,'']]],
  ['use_20simple_20publish_20subscribe_23',['Q: Can I still use simple publish/subscribe?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md836',1,'']]],
  ['use_20v1_20x_20and_20v2_200_20together_24',['Q: Can I use v1.x and v2.0 together?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md831',1,'']]],
  ['user_20documentation_25',['User Documentation',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md996',1,'']]],
  ['users_26',['users',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1000',1,'For New Users'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1181',1,'Option B: Automatic FetchContent (Easiest for New Users)']]],
  ['using_20addresssanitizer_27',['using addresssanitizer',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md640',1,'Using AddressSanitizer'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1069',1,'Using AddressSanitizer']]],
  ['using_20gdb_28',['Using GDB',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md638',1,'']]],
  ['using_20gdb_20for_20debugging_29',['Using GDB for Debugging',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1064',1,'']]],
  ['using_20hashicorp_20vault_30',['Using HashiCorp Vault',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md517',1,'']]],
  ['using_20heaptrack_31',['Using HeapTrack',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1070',1,'']]],
  ['using_20instruments_20macos_32',['Using Instruments (macOS)',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md644',1,'']]],
  ['using_20intel_20vtune_33',['Using Intel VTune',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md645',1,'']]],
  ['using_20kubernetes_20secrets_34',['Using Kubernetes Secrets',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md518',1,'']]],
  ['using_20package_20managers_35',['Using Package Managers',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md507',1,'']]],
  ['using_20perf_36',['Using perf',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md643',1,'']]],
  ['using_20threadsanitizer_37',['Using ThreadSanitizer',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md641',1,'']]],
  ['using_20valgrind_38',['using valgrind',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1068',1,'Using Valgrind'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md639',1,'Using Valgrind']]],
  ['utility_39',['utility',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md725',1,'1.3 Integration Detection Utility'],['../da/dab/md_docs_2archived_2phase0_2INTERFACE__MAPPING.html#autotoc_md169',1,'Exception Mapper Utility']]],
  ['utilization_40',['SIMD Utilization',['../df/d94/md_docs_2performance.html#autotoc_md976',1,'']]]
];
