var searchData=
[
  ['o_20analysis_0',['Disk I/O Analysis',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md672',1,'']]],
  ['o_20optimization_1',['I/O Optimization',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md671',1,'']]],
  ['object_20pool_20pattern_2',['4. Object Pool Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md257',1,'']]],
  ['object_20pooling_3',['Object Pooling',['../df/d94/md_docs_2performance.html#autotoc_md554',1,'']]],
  ['observability_4',['observability',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md621',1,'Monitoring and Observability'],['../d2/d64/md_docs_2architecture.html#autotoc_md118',1,'Monitoring and Observability']]],
  ['observer_20pattern_5',['9. Observer Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md264',1,'']]],
  ['of_20contents_6',['of contents',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md1',1,'Table of Contents'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md635',1,'Table of Contents'],['../df/d94/md_docs_2performance.html#autotoc_md530',1,'Table of Contents'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md425',1,'Table of Contents'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md367',1,'Table of Contents'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md333',1,'Table of Contents']]],
  ['of_20memory_7',['&quot;Out of memory&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md691',1,'']]],
  ['of_20responsibility_20pattern_8',['11. Chain of Responsibility Pattern',['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md266',1,'']]],
  ['official_20image_9',['Pull Official Image',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md179',1,'']]],
  ['old_20includes_10',['Issue: Compilation errors with old includes',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md405',1,'']]],
  ['once_11',['Q: Do I need to migrate all code at once?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md413',1,'']]],
  ['operating_20system_20support_12',['Operating System Support',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md166',1,'']]],
  ['operations_20deployment_13',['Operations &amp; Deployment',['../index.html#autotoc_md578',1,'']]],
  ['optimization_14',['optimization',['../df/d94/md_docs_2performance.html#autotoc_md553',1,'1. Memory Optimization'],['../df/d94/md_docs_2performance.html#autotoc_md556',1,'2. CPU Optimization'],['../df/d94/md_docs_2performance.html#autotoc_md559',1,'3. Network Optimization'],['../df/d94/md_docs_2performance.html#autotoc_md558',1,'Cache Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md665',1,'CPU Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md671',1,'I/O Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md668',1,'Memory Optimization'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md205',1,'Network Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md674',1,'Network Optimization'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md664',1,'Performance Optimization'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md611',1,'Performance Optimization'],['../d2/d64/md_docs_2architecture.html#autotoc_md108',1,'Performance Optimization'],['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html',1,'Windows CI Performance Optimization']]],
  ['optimization_20impact_15',['SIMD Optimization Impact',['../df/d94/md_docs_2performance.html#autotoc_md545',1,'']]],
  ['optimization_20techniques_16',['optimization techniques',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md673',1,'Optimization Techniques'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md667',1,'Optimization Techniques'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md670',1,'Optimization Techniques'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md676',1,'Optimization Techniques'],['../df/d94/md_docs_2performance.html#autotoc_md552',1,'Optimization Techniques']]],
  ['optional_20but_20recommended_17',['Step 5: Migrate to Patterns (Optional but Recommended)',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md387',1,'']]],
  ['optional_20systems_18',['Optional Systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md761',1,'']]],
  ['options_19',['options',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md777',1,'🔧 Build Options'],['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md346',1,'Custom Build Options']]],
  ['organization_20',['organization',['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md294',1,'File Organization'],['../db/dac/md_docs_2DEVELOPER__GUIDE.html#autotoc_md290',1,'Module Organization']]],
  ['other_20systems_21',['Step 7: Integration with Other Systems',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md391',1,'']]],
  ['out_20of_20memory_22',['&quot;Out of memory&quot;',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md691',1,'']]],
  ['overall_20system_20performance_23',['Overall System Performance',['../df/d94/md_docs_2performance.html#autotoc_md536',1,'']]],
  ['overhead_24',['Protocol Overhead',['../df/d94/md_docs_2performance.html#autotoc_md548',1,'']]],
  ['overview_25',['overview',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md734',1,'✨ Overview'],['../index.html#autotoc_md576',1,'📚 Documentation Overview'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md369',1,'Overview'],['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md593',1,'Overview'],['../d5/dca/md_docs_2DESIGN__PATTERNS.html#autotoc_md252',1,'Overview'],['../d2/d64/md_docs_2architecture.html#autotoc_md86',1,'Overview'],['../df/d94/md_docs_2performance.html#autotoc_md531',1,'Performance Overview'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md745',1,'System Overview']]]
];
