var searchData=
[
  ['handle_20migration_20testing_0',['Q: How do I handle migration testing?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md837',1,'']]],
  ['handling_1',['handling',['../d2/d41/md_docs_2GETTING__STARTED.html#autotoc_md682',1,'2. Container-Based Data Handling'],['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md180',1,'4. Exception-Based Error Handling'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md80',1,'Error Handling'],['../dc/d3e/md_docs_2PATTERNS__API.html#autotoc_md943',1,'Error Handling'],['../da/dab/md_docs_2archived_2phase0_2INTERFACE__MAPPING.html#autotoc_md158',1,'Error Handling'],['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md809',1,'Step 6: Update Error Handling']]],
  ['handling_20paradigm_20shift_2',['1. Error Handling Paradigm Shift',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md210',1,'']]],
  ['handling_20transformation_3',['Error Handling Transformation',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md184',1,'']]],
  ['haproxy_20configuration_4',['HAProxy Configuration',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md523',1,'']]],
  ['hardening_5',['Security Hardening',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md565',1,'']]],
  ['hardware_20requirements_6',['Hardware Requirements',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md494',1,'']]],
  ['hashicorp_20vault_7',['Using HashiCorp Vault',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md517',1,'']]],
  ['header_8',['Legacy Guard Header',['../de/d28/md_docs_2archived_2phase0_2LEGACY__REMOVAL__PLAN.html#autotoc_md201',1,'']]],
  ['headers_20only_20planned_9',['🚧 Integration Features (Headers Only - Planned)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1158',1,'']]],
  ['health_10',['health',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md581',1,'Application Health'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md582',1,'System Health']]],
  ['health_20checks_11',['Health Checks',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md580',1,'']]],
  ['heaptrack_12',['Using HeapTrack',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1070',1,'']]],
  ['help_13',['Getting Help',['../d7/d68/md_docs_2BUILD__TROUBLESHOOTING.html#autotoc_md481',1,'']]],
  ['high_20availability_14',['high availability',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1036',1,'High Availability'],['../d2/d64/md_docs_2architecture.html#autotoc_md114',1,'High Availability']]],
  ['high_20availability_20deployment_15',['High Availability Deployment',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md521',1,'']]],
  ['high_20cpu_20usage_16',['High CPU Usage',['../df/d94/md_docs_2performance.html#autotoc_md989',1,'']]],
  ['high_20cpu_20usage_20with_20small_20messages_17',['Issue 1: High CPU Usage with Small Messages',['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1097',1,'']]],
  ['high_20level_20design_18',['High-Level Design',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1174',1,'']]],
  ['high_20memory_20usage_19',['high memory usage',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md578',1,'High Memory Usage'],['../d4/d2f/md_docs_2TROUBLESHOOTING.html#autotoc_md1116',1,'Problem: High Memory Usage']]],
  ['high_20risk_20',['High Risk',['../d0/d01/md_docs_2IMPROVEMENT__PLAN.html#autotoc_md775',1,'']]],
  ['high_20risk_20items_21',['High Risk Items',['../d7/d23/md_docs_2archived_2phase0_2MIGRATION__STRATEGY.html#autotoc_md236',1,'']]],
  ['high_20throughput_20tt_20test_5fhigh_5fthroughput_5fscenario_20tt_22',['4. High Throughput (&lt;tt&gt;test_high_throughput_scenario&lt;/tt&gt;)',['../d6/d40/md_docs_2archived_2phase4_2TEST__SUMMARY.html#autotoc_md353',1,'']]],
  ['highlights_23',['🎯 Key Highlights',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1154',1,'']]],
  ['history_24',['Commit History',['../d6/d74/md_docs_2archived_2PROJECT__COMPLETION__SUMMARY.html#autotoc_md407',1,'']]],
  ['hooks_20optional_25',['Pre-commit Hooks (Optional)',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1248',1,'']]],
  ['horizontal_20pod_20autoscaler_26',['Horizontal Pod Autoscaler',['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md528',1,'']]],
  ['horizontal_20scaling_27',['horizontal scaling',['../da/db4/md_docs_2SYSTEM__ARCHITECTURE.html#autotoc_md1025',1,'Horizontal Scaling'],['../df/d23/md_docs_2DEPLOYMENT__GUIDE.html#autotoc_md550',1,'Horizontal Scaling'],['../d2/d64/md_docs_2architecture.html#autotoc_md103',1,'Horizontal Scaling']]],
  ['hosted_20runners_28',['1. Use Self-Hosted Runners',['../d8/d29/md_docs_2WINDOWS__OPTIMIZATION.html#autotoc_md1138',1,'']]],
  ['how_20do_20i_20enable_20lock_20free_20queues_29',['Q: How do I enable lock-free queues?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md835',1,'']]],
  ['how_20do_20i_20handle_20migration_20testing_30',['Q: How do I handle migration testing?',['../db/d3a/md_docs_2MIGRATION__GUIDE.html#autotoc_md837',1,'']]],
  ['how_20each_20system_20contributes_31',['🧩 How Each System Contributes',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1164',1,'']]],
  ['how_20to_20contribute_32',['How to Contribute',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md1224',1,'']]]
];
