var searchData=
[
  ['macos_0',['macos',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md827',1,'Issue 3: grep -P Not Supported (macOS)'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md844',1,'macOS'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1086',1,'macOS'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md977',1,'Using Instruments (macOS)']]],
  ['macro_20based_20logging_1',['Alternative C: Macro-based Logging',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md19',1,'']]],
  ['management_2',['management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1505',1,'Checkpoint Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md427',1,'Configuration Management'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md222',1,'Configuration Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md297',1,'Connection Management'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2213',1,'Dependency Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md325',1,'Lifecycle Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md414',1,'Memory Management'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md894',1,'Memory Management'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md209',1,'Memory Management'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2166',1,'Phase 7: Monitoring &amp; Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md344',1,'Pool Management'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1312',1,'Resource Management'],['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md628',1,'Route Management'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md326',1,'Route Management'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1556',1,'Schedule Management'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md874',1,'Secrets Management'],['../da/db6/md_docs_2FEATURES.html#autotoc_md736',1,'Subscription Management'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1506',1,'Subtask Management'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1574',1,'Task Management']]],
  ['managers_3',['Using Package Managers',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md865',1,'']]],
  ['managing_20schedules_4',['Managing Schedules',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1958',1,'']]],
  ['many_20topics_5',['Issue 5: Performance Degradation with Many Topics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1158',1,'']]],
  ['mapping_20concepts_6',['Mapping Concepts',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1871',1,'']]],
  ['matching_7',['Topic Pattern Matching',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md636',1,'']]],
  ['matching_20performance_8',['Pattern Matching Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md479',1,'']]],
  ['matrix_9',['Feature Matrix',['../da/db6/md_docs_2FEATURES.html#autotoc_md760',1,'']]],
  ['meaningful_20route_20ids_10',['1. Use Meaningful Route IDs',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md645',1,'']]],
  ['measurements_11',['Latency Measurements',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1243',1,'']]],
  ['mechanism_12',['Retry Mechanism',['../da/db6/md_docs_2FEATURES.html#autotoc_md699',1,'']]],
  ['medium_20term_20architectural_13',['Medium-Term (Architectural)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md246',1,'']]],
  ['memory_14',['&quot;Out of memory&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1167',1,'']]],
  ['memory_20configuration_15',['2. Memory Configuration',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1272',1,'']]],
  ['memory_20debugging_16',['Memory Debugging',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1124',1,'']]],
  ['memory_20errors_17',['Memory Errors',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1166',1,'']]],
  ['memory_20leak_20in_20long_20running_20connections_18',['Issue 2: Memory Leak in Long-Running Connections',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1155',1,'']]],
  ['memory_20leaks_19',['Memory Leaks',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1277',1,'']]],
  ['memory_20management_20',['memory management',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md894',1,'Memory Management'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md209',1,'Memory Management'],['../d2/d64/md_docs_2architecture.html#autotoc_md414',1,'Memory Management']]],
  ['memory_20optimization_21',['memory optimization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1259',1,'1. Memory Optimization'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1806',1,'Memory Optimization'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1144',1,'Memory Optimization']]],
  ['memory_20overhead_22',['Per-Component Memory Overhead',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md499',1,'']]],
  ['memory_20performance_23',['Memory Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1244',1,'']]],
  ['memory_20result_20backend_24',['4.2 In-Memory Result Backend',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2157',1,'']]],
  ['memory_20safety_25',['Memory Safety',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1291',1,'']]],
  ['memory_20scaling_26',['Memory Scaling',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md500',1,'']]],
  ['memory_20usage_27',['memory usage',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2092',1,'High Memory Usage'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md936',1,'High Memory Usage'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md498',1,'Memory Usage'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1173',1,'Problem: High Memory Usage']]],
  ['memory_20usage_20analysis_28',['Memory Usage Analysis',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1145',1,'']]],
  ['memory_20usage_20growing_29',['Memory Usage Growing',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2081',1,'']]],
  ['memory_5fresult_5fbackend_30',['memory_result_backend',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1548',1,'memory_result_backend'],['../dd/db9/md_docs_2task_2API__REFERENCE__KO.html#autotoc_md1667',1,'memory_result_backend']]],
  ['message를_20상속_31',['1. Task는 Message를 상속',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2188',1,'']]],
  ['message_20api_32',['Message API',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1046',1,'']]],
  ['message_20based_20tasks_33',['1. Message-Based Tasks',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1730',1,'']]],
  ['message_20broker_34',['message broker',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html',1,'Message Broker'],['../da/db6/md_docs_2FEATURES.html#autotoc_md681',1,'Message Broker']]],
  ['message_20broker_20api_35',['Message Broker API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md317',1,'']]],
  ['message_20builder_36',['Message Builder',['../da/db6/md_docs_2FEATURES.html#autotoc_md731',1,'']]],
  ['message_20builder_20performance_37',['Message Builder Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md472',1,'']]],
  ['message_20bus_38',['message bus',['../da/db6/md_docs_2FEATURES.html#autotoc_md680',1,'Message Bus'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1009',1,'Q: How do I create a message bus?']]],
  ['message_20bus_20api_39',['message bus api',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md302',1,'Message Bus API'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1047',1,'Message Bus API']]],
  ['message_20bus_20doesn_20t_20start_40',['Issue: Message bus doesn&apos;t start',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1059',1,'']]],
  ['message_20bus_20interface_41',['4. Message Bus Interface',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1029',1,'']]],
  ['message_20bus_20performance_42',['Message Bus Performance',['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1224',1,'']]],
  ['message_20bus_20usage_43',['message bus usage',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1093',1,'1. Basic Message Bus Usage'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1038',1,'Step 4: Migrate Message Bus Usage']]],
  ['message_20creation_44',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1037',1,'']]],
  ['message_20creation_20benchmarks_45',['Message Creation Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md471',1,'']]],
  ['message_20flow_46',['Message Flow',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2208',1,'']]],
  ['message_20format_47',['Commit Message Format',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md981',1,'']]],
  ['message_20pipeline_48',['message pipeline',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1054',1,'Example 4: Message Pipeline'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md781',1,'Message Pipeline'],['../da/db6/md_docs_2FEATURES.html#autotoc_md687',1,'Message Pipeline'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2220',1,'Message Pipeline']]],
  ['message_20pipeline_20pattern_49',['message pipeline pattern',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md146',1,'Message Pipeline Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md181',1,'Message Pipeline Pattern']]],
  ['message_20processing_50',['message processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1157',1,'Issue 4: Deadlock in Message Processing'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1171',1,'Problem: Slow Message Processing']]],
  ['message_20processing_20pipeline_51',['message processing pipeline',['../d2/d64/md_docs_2architecture.html#autotoc_md404',1,'Message Processing Pipeline'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md199',1,'Message Processing Pipeline']]],
  ['message_20queue_52',['Message Queue',['../da/db6/md_docs_2FEATURES.html#autotoc_md738',1,'']]],
  ['message_20queue_20systems_53',['From Message Queue Systems',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1870',1,'']]],
  ['message_20routing_54',['message routing',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md634',1,'Message Routing'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md327',1,'Message Routing']]],
  ['message_20serialization_55',['Message Serialization',['../da/db6/md_docs_2FEATURES.html#autotoc_md732',1,'']]],
  ['message_20structure_56',['message structure',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1028',1,'3. Message Structure'],['../da/db6/md_docs_2FEATURES.html#autotoc_md730',1,'Message Structure']]],
  ['message_20types_57',['Message Types',['../da/db6/md_docs_2FEATURES.html#autotoc_md729',1,'']]],
  ['message_5fbroker_58',['After (message_broker)',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md653',1,'']]],
  ['message_5fbroker_20tt_59',['Class: &lt;tt&gt;message_broker&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md323',1,'']]],
  ['message_5fbroker_2emd_60',['MESSAGE_BROKER.md',['../db/df5/MESSAGE__BROKER_8md.html',1,'']]],
  ['message_5fbus_61',['message_bus',['../d4/d54/md_docs_2API__REFERENCE__KO.html#autotoc_md374',1,'']]],
  ['message_5fbus_20tt_62',['Class: &lt;tt&gt;message_bus&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md305',1,'']]],
  ['message_5fpipeline_20tt_63',['Class: &lt;tt&gt;message_pipeline&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md149',1,'']]],
  ['messagefiltercallable_64',['messagefiltercallable',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md802',1,'MessageFilterCallable'],['../da/db6/md_docs_2FEATURES.html#autotoc_md708',1,'MessageFilterCallable']]],
  ['messageprocessorcallable_65',['messageprocessorcallable',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md801',1,'MessageProcessorCallable'],['../da/db6/md_docs_2FEATURES.html#autotoc_md707',1,'MessageProcessorCallable']]],
  ['messages_66',['messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1159',1,'Error Messages'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1154',1,'Issue 1: High CPU Usage with Small Messages'],['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md662',1,'Replaying Messages']]],
  ['messages_20not_20being_20delivered_67',['Issue: Messages not being delivered',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1060',1,'']]],
  ['messages_20tasks_20that_20always_20fail_68',['Q: How do I handle poison messages (tasks that always fail)?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2103',1,'']]],
  ['messages_20to_20dlq_69',['Moving Messages to DLQ',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md660',1,'']]],
  ['messagetransformercallable_70',['messagetransformercallable',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md803',1,'MessageTransformerCallable'],['../da/db6/md_docs_2FEATURES.html#autotoc_md709',1,'MessageTransformerCallable']]],
  ['messaging_71',['Core Messaging',['../da/db6/md_docs_2FEATURES.html#autotoc_md679',1,'']]],
  ['messaging_20backends_20tt_72',['messaging backends tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1404',1,'백엔드 (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1366',1,'Backends (&lt;tt&gt;include/kcenon/messaging/backends/&lt;/tt&gt;)']]],
  ['messaging_20core_20tt_73',['messaging core tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1402',1,'핵심 컴포넌트 (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1364',1,'Core Components (&lt;tt&gt;include/kcenon/messaging/core/&lt;/tt&gt;)']]],
  ['messaging_20event_20bridge_20integration_74',['Messaging Event Bridge Integration',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1195',1,'']]],
  ['messaging_20interfaces_20tt_75',['messaging interfaces tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1403',1,'인터페이스 (&lt;tt&gt;include/kcenon/messaging/interfaces/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1365',1,'Interfaces (&lt;tt&gt;include/kcenon/messaging/interfaces/&lt;/tt&gt;)']]],
  ['messaging_20patterns_76',['Messaging Patterns',['../da/db6/md_docs_2FEATURES.html#autotoc_md683',1,'']]],
  ['messaging_20patterns_20api_20reference_77',['Messaging Patterns API Reference',['../df/dde/md_docs_2advanced_2PATTERNS__API.html',1,'']]],
  ['messaging_20patterns_20tt_78',['messaging patterns tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1405',1,'패턴 (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1367',1,'Patterns (&lt;tt&gt;include/kcenon/messaging/patterns/&lt;/tt&gt;)']]],
  ['messaging_20system_79',['Contributing to Messaging System',['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html',1,'']]],
  ['messaging_20system_20기능_80',['Messaging System 기능',['../d4/d0c/md_docs_2FEATURES__KO.html',1,'']]],
  ['messaging_20system_20문서_81',['Messaging System 문서',['../d8/d0a/md_docs_2README__KO.html',1,'']]],
  ['messaging_20system_20변경_20이력_82',['Messaging System 변경 이력',['../db/d9f/md_docs_2CHANGELOG__KO.html',1,'']]],
  ['messaging_20system_20성능_20벤치마크_83',['Messaging System 성능 벤치마크',['../d5/ddb/md_docs_2BENCHMARKS__KO.html',1,'']]],
  ['messaging_20system_20아키텍처_84',['Messaging System 아키텍처',['../de/de3/md_docs_2ARCHITECTURE__KO.html',1,'']]],
  ['messaging_20system_20프로덕션_20품질_85',['Messaging System 프로덕션 품질',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html',1,'']]],
  ['messaging_20system_20프로젝트_20구조_86',['Messaging System 프로젝트 구조',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html',1,'']]],
  ['messaging_20system_20api_20레퍼런스_87',['Messaging System API 레퍼런스',['../d4/d54/md_docs_2API__REFERENCE__KO.html',1,'']]],
  ['messaging_20system_20changelog_88',['Messaging System Changelog',['../da/dee/md_docs_2CHANGELOG.html',1,'']]],
  ['messaging_20system_20features_89',['Messaging System Features',['../da/db6/md_docs_2FEATURES.html',1,'']]],
  ['messaging_20system_20performance_20benchmarks_90',['Messaging System Performance Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html',1,'']]],
  ['messaging_20system_20production_20quality_91',['Messaging System Production Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html',1,'']]],
  ['messaging_20system_20project_20structure_92',['Messaging System Project Structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'']]],
  ['messaging_20task_20tt_93',['messaging task tt',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html#autotoc_md1406',1,'태스크 큐 (&lt;tt&gt;include/kcenon/messaging/task/&lt;/tt&gt;)'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1368',1,'Task Queue (&lt;tt&gt;include/kcenon/messaging/task/&lt;/tt&gt;)']]],
  ['messaging_5fclient_20tt_94',['Class: &lt;tt&gt;messaging_client&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md287',1,'']]],
  ['messaging_5fserver_20tt_95',['Class: &lt;tt&gt;messaging_server&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md283',1,'']]],
  ['messaging_5fsystem에서의_20사용_20예시_96',['messaging_system에서의 사용 예시',['../dd/da0/md_docs_2adr_2001-logging-architecture__KO.html#autotoc_md48',1,'']]],
  ['messaging_5fsystem_97',['messaging_system',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1000',1,'Q: What is messaging_system?'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md22',1,'Usage Examples in messaging_system']]],
  ['method_98',['Build Method',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1491',1,'']]],
  ['method_20pattern_99',['13. Template Method Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md76',1,'']]],
  ['methods_100',['methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1550',1,'Additional Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1490',1,'Builder Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1478',1,'Configuration Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md271',1,'Core Methods'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2083',1,'Debugging Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1476',1,'Identification Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md308',1,'Lifecycle Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md108',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md99',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md91',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md114',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md163',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md129',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md289',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md285',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md279',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md335',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md349',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md152',1,'Methods'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md357',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md119',1,'Methods'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md140',1,'Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1546',1,'Optional Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1538',1,'Progress Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1495',1,'Pure Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1545',1,'Pure Virtual Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1482',1,'Retry Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1477',1,'State Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1565',1,'Static Methods'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1537',1,'Status Methods']]],
  ['metrics_101',['metrics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1268',1,'1. Built-in Metrics'],['../d9/df1/md_docs_2performance_2BASELINE.html#autotoc_md1223',1,'Baseline Metrics'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1212',1,'Collected Metrics'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md468',1,'Core Performance Metrics'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1285',1,'Quality Metrics'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md469',1,'Reference Performance Metrics']]],
  ['metrics_20collection_102',['metrics collection',['../d2/d64/md_docs_2architecture.html#autotoc_md424',1,'Metrics Collection'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md219',1,'Metrics Collection']]],
  ['metrics_20exposed_103',['Metrics Exposed',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md902',1,'']]],
  ['metrics_20to_20track_104',['Key Metrics to Track',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md260',1,'']]],
  ['microkernel_20pattern_105',['16. Microkernel Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md81',1,'']]],
  ['migrate_20all_20code_20at_20once_106',['Q: Do I need to migrate all code at once?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1065',1,'']]],
  ['migrate_20message_20bus_20usage_107',['Step 4: Migrate Message Bus Usage',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1038',1,'']]],
  ['migrate_20message_20creation_108',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1037',1,'']]],
  ['migrate_20to_20patterns_20optional_20but_20recommended_109',['Step 5: Migrate to Patterns (Optional but Recommended)',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1039',1,'']]],
  ['migrating_20to_201_200_110',['Migrating to 1.0',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1861',1,'']]],
  ['migration_111',['migration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1869',1,'Benefits of Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1863',1,'Configuration Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1880',1,'During Migration'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1051',1,'Example 1: Simple Pub/Sub Migration'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1052',1,'Example 2: Request-Reply Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1881',1,'Post-Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1879',1,'Pre-Migration'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1032',1,'Step-by-Step Migration'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1860',1,'Version Migration']]],
  ['migration_20checklist_112',['Migration Checklist',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1878',1,'']]],
  ['migration_20example_113',['Migration Example',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1872',1,'']]],
  ['migration_20from_20custom_20solutions_114',['Migration from Custom Solutions',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1865',1,'']]],
  ['migration_20from_20topic_5frouter_115',['Migration from topic_router',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md651',1,'']]],
  ['migration_20guide_116',['migration guide',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html',1,'Migration Guide'],['../d2/d8d/md_docs_2task_2MIGRATION.html',1,'Task Module Migration Guide']]],
  ['migration_20issues_117',['Common Migration Issues',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1884',1,'']]],
  ['migration_20testing_118',['Q: How do I handle migration testing?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1070',1,'']]],
  ['migration_20timeline_119',['Migration Timeline',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md1022',1,'']]],
  ['migration_2emd_120',['MIGRATION.md',['../d2/de3/MIGRATION_8md.html',1,'']]],
  ['migration_5fguide_2emd_121',['MIGRATION_GUIDE.md',['../d7/d6a/MIGRATION__GUIDE_8md.html',1,'']]],
  ['migration_5fko_2emd_122',['MIGRATION_KO.md',['../d6/d07/MIGRATION__KO_8md.html',1,'']]],
  ['minimal_20build_20no_20external_20systems_123',['Alternative: Minimal Build (No External Systems)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md835',1,'']]],
  ['minimum_20requirements_124',['Minimum Requirements',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md853',1,'']]],
  ['missing_20queue_20configuration_125',['Missing Queue Configuration',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1886',1,'']]],
  ['mode_126',['mode',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md832',1,'For Development (FetchContent Mode)'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md833',1,'For Production (find_package Mode)'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md314',1,'Usage Example (Local Mode)']]],
  ['mode_20with_20transport_127',['Usage Example (Hybrid Mode with Transport)',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md315',1,'']]],
  ['modularity_128',['Modularity',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1389',1,'']]],
  ['module_129',['After (Task Module)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1868',1,'']]],
  ['module_20api_20reference_130',['Task Module API Reference',['../df/d18/md_docs_2task_2API__REFERENCE.html',1,'']]],
  ['module_20architecture_131',['Task Module Architecture',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html',1,'']]],
  ['module_20configuration_20guide_132',['Task Module Configuration Guide',['../dc/d1e/md_docs_2task_2CONFIGURATION.html',1,'']]],
  ['module_20documentation_133',['Module Documentation',['../d2/d64/md_docs_2architecture.html#autotoc_md394',1,'']]],
  ['module_20migration_20guide_134',['Task Module Migration Guide',['../d2/d8d/md_docs_2task_2MIGRATION.html',1,'']]],
  ['module_20organization_135',['Module Organization',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md955',1,'']]],
  ['module_20performance_136',['Task Module Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md490',1,'']]],
  ['module_20quick_20start_20guide_137',['Task Module Quick Start Guide',['../d9/dff/md_docs_2task_2QUICK__START.html',1,'']]],
  ['module_20troubleshooting_20guide_138',['Task Module Troubleshooting Guide',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html',1,'']]],
  ['module_20workflow_20patterns_139',['Task Module Workflow Patterns',['../d5/dd2/md_docs_2task_2PATTERNS.html',1,'']]],
  ['modules_140',['modules',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md985',1,'Creating New Modules'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1444',1,'Data &amp; Communication Modules']]],
  ['monitor_141',['monitor',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2167',1,'7.1 Task Monitor'],['../da/db6/md_docs_2FEATURES.html#autotoc_md697',1,'Task Monitor']]],
  ['monitor_20events_142',['Monitor Events',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md2085',1,'']]],
  ['monitor_20statistics_143',['4. Monitor Statistics',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md648',1,'']]],
  ['monitoring_144',['monitoring',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md519',1,'Continuous Performance Monitoring'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1214',1,'Health Monitoring'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1302',1,'Monitoring'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md312',1,'Monitoring'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md259',1,'Monitoring'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1267',1,'Performance Monitoring']]],
  ['monitoring_20and_20observability_145',['monitoring and observability',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md218',1,'Monitoring and Observability'],['../d2/d64/md_docs_2architecture.html#autotoc_md423',1,'Monitoring and Observability']]],
  ['monitoring_20dashboard_146',['2. Performance Monitoring Dashboard',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1279',1,'']]],
  ['monitoring_20management_147',['Phase 7: Monitoring &amp; Management',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2166',1,'']]],
  ['monitoring_20progress_148',['monitoring progress',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md2052',1,'Monitoring Progress'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1963',1,'Monitoring Progress']]],
  ['monitoring_20setup_149',['Monitoring Setup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md899',1,'']]],
  ['monitoring_20system_20integration_150',['monitoring system integration',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1210',1,'Monitoring System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md752',1,'Monitoring System Integration']]],
  ['monitoring_20system_20integration_20✅_151',['Sprint 6: Monitoring &amp; System Integration ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2178',1,'']]],
  ['more_20questions_152',['More Questions?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md1017',1,'']]],
  ['moving_20messages_20to_20dlq_153',['Moving Messages to DLQ',['../d8/dc1/md_docs_2core_2MESSAGE__BROKER.html#autotoc_md660',1,'']]],
  ['mutex_20comparison_154',['Lock-free vs Mutex Comparison',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1247',1,'']]]
];
