var searchData=
[
  ['s_20included_0',['📦 What&apos;s Included',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2086',1,'']]],
  ['safety_1',['safety',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1178',1,'Memory Safety'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md186',1,'Thread Safety'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1611',1,'Thread Safety'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1198',1,'Thread Safety']]],
  ['sample_20applications_2',['1. Explore Sample Applications',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1001',1,'']]],
  ['sample_20client_3',['3. Test with Sample Client',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md999',1,'']]],
  ['saving_20checkpoints_4',['Saving Checkpoints',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1854',1,'']]],
  ['scalability_5',['scalability',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1194',1,'Scalability'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md488',1,'Scalability'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md475',1,'Worker Scalability']]],
  ['scalability_20patterns_6',['scalability patterns',['../d2/d64/md_docs_2architecture.html#autotoc_md389',1,'Scalability Patterns'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md202',1,'Scalability Patterns']]],
  ['scale_7',['By Scale',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1697',1,'']]],
  ['scaling_8',['scaling',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1140',1,'Connection Scaling'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md809',1,'Database Scaling'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md804',1,'Horizontal Scaling'],['../d2/d64/md_docs_2architecture.html#autotoc_md390',1,'Horizontal Scaling'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md203',1,'Horizontal Scaling'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md482',1,'Memory Scaling'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md490',1,'Publisher/Subscriber Scaling'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md489',1,'Thread Scaling'],['../d2/d64/md_docs_2architecture.html#autotoc_md391',1,'Vertical Scaling'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md807',1,'Vertical Scaling'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md204',1,'Vertical Scaling']]],
  ['scaling_20characteristics_9',['Scaling Characteristics',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1135',1,'']]],
  ['scaling_20rules_10',['Auto-scaling Rules',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md806',1,'']]],
  ['scaling_20strategies_11',['Scaling Strategies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md803',1,'']]],
  ['scenarios_12',['Deployment Scenarios',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md773',1,'']]],
  ['schedule_20management_13',['Schedule Management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1443',1,'']]],
  ['schedule_20registration_14',['Schedule Registration',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1442',1,'']]],
  ['scheduled_20chord_15',['Scheduled Chord',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1864',1,'']]],
  ['scheduled_20tasks_16',['Scheduled Tasks',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1841',1,'']]],
  ['scheduleeventcallable_17',['scheduleeventcallable',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md696',1,'ScheduleEventCallable'],['../da/db6/md_docs_2FEATURES.html#autotoc_md613',1,'ScheduleEventCallable']]],
  ['scheduler_18',['scheduler',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2051',1,'6.1 Periodic Task Scheduler'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1762',1,'After (Task Scheduler)'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2050',1,'Phase 6: Scheduler'],['../da/db6/md_docs_2FEATURES.html#autotoc_md601',1,'Task Scheduler']]],
  ['scheduler_20✅_19',['Sprint 5: Scheduler ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2064',1,'']]],
  ['scheduler_20performance_20',['Scheduler Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md477',1,'']]],
  ['schedules_21',['Managing Schedules',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1845',1,'']]],
  ['scheduling_22',['Cron-Based Scheduling',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1843',1,'']]],
  ['scheduling_20convenience_23',['Scheduling (Convenience)',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1471',1,'']]],
  ['scheduling_20tasks_24',['Scheduling Tasks',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1936',1,'']]],
  ['secrets_25',['Using Kubernetes Secrets',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md772',1,'']]],
  ['secrets_20management_26',['Secrets Management',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md770',1,'']]],
  ['secure_20communication_27',['Secure Communication',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md887',1,'']]],
  ['security_28',['security',['../d2/d64/md_docs_2architecture.html#autotoc_md404',1,'Application Security'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md823',1,'Application Security'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md217',1,'Application Security'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md820',1,'Network Security'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1196',1,'Security'],['../d2/d64/md_docs_2architecture.html#autotoc_md403',1,'Transport Security'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md216',1,'Transport Security']]],
  ['security_20best_20practices_29',['Security Best Practices',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md885',1,'']]],
  ['security_20considerations_30',['security considerations',['../d2/d64/md_docs_2architecture.html#autotoc_md402',1,'Security Considerations'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md215',1,'Security Considerations']]],
  ['security_20hardening_31',['Security Hardening',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md819',1,'']]],
  ['segmentation_20fault_32',['&quot;Segmentation fault&quot;',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1064',1,'']]],
  ['selection_20via_20templates_33',['Alternative B: Compile-time Logger Selection via Templates',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md18',1,'']]],
  ['self_20hosted_20runners_34',['1. Use Self-Hosted Runners',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md251',1,'']]],
  ['separation_20of_20concerns_35',['Separation of Concerns',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1275',1,'']]],
  ['serialization_36',['serialization',['../da/db6/md_docs_2FEATURES.html#autotoc_md629',1,'Message Serialization'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1370',1,'Serialization'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md275',1,'Serialization']]],
  ['serialization_20performance_37',['Serialization Performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1137',1,'']]],
  ['server_38',['3. Network Client/Server',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md991',1,'']]],
  ['server_20chat_5fserver_20cpp_39',['1. Chat Server (chat_server.cpp)',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md997',1,'']]],
  ['server_20deployment_40',['Single Server Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md774',1,'']]],
  ['service_41',['2. Implement Build Caching Service',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md252',1,'']]],
  ['service_20and_20ingress_42',['Service and Ingress',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md781',1,'']]],
  ['service_20container_20api_43',['Service Container API',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md314',1,'']]],
  ['service_20lifetimes_44',['Service Lifetimes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md318',1,'']]],
  ['service_20recovery_45',['Service Recovery',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md817',1,'']]],
  ['service_20resolution_20from_20di_20container_46',['Service Resolution from DI Container',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1083',1,'']]],
  ['service_20won_20t_20start_47',['service won t start',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1066',1,'Problem: Service Won&apos;t Start'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md831',1,'Service Won&apos;t Start']]],
  ['service_5fcontainer_20tt_48',['Class: &lt;tt&gt;service_container&lt;/tt&gt;',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md316',1,'']]],
  ['set_5fdefault_5ftopic_20tt_49',['&lt;tt&gt;set_default_topic&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md94',1,'']]],
  ['setting_20priority_50',['Setting Priority',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1836',1,'']]],
  ['setting_20values_51',['Setting Values',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md272',1,'']]],
  ['settings_52',['settings',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1673',1,'Concurrency Settings'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1668',1,'Delayed Queue Settings'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1683',1,'Environment-Specific Settings'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1675',1,'Prefetch Settings']]],
  ['setup_53',['setup',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md840',1,'1. Clone and Setup'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md980',1,'2. Platform-Specific Setup'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md843',1,'Development Setup'],['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md900',1,'Installation &amp; Setup'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md795',1,'Monitoring Setup'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1837',1,'Priority Queue Setup']]],
  ['sharding_54',['2. Implement Test Sharding',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md248',1,'']]],
  ['sharding_20strategy_55',['Sharding Strategy',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md811',1,'']]],
  ['short_56',['Timeout Too Short',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1774',1,'']]],
  ['short_20term_20quick_20wins_57',['Short-Term (Quick Wins)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md242',1,'']]],
  ['shut_20down_20the_20system_58',['Q: How do I gracefully shut down the system?',['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1991',1,'']]],
  ['shutdown_20behavior_59',['Shutdown Behavior',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1084',1,'']]],
  ['simd_20optimization_20impact_60',['SIMD Optimization Impact',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1138',1,'']]],
  ['simd_20utilization_61',['SIMD Utilization',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1150',1,'']]],
  ['simple_20pub_20sub_20migration_62',['Example 1: Simple Pub/Sub Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md947',1,'']]],
  ['simple_20publish_20subscribe_63',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md965',1,'']]],
  ['single_20server_20deployment_64',['Single Server Deployment',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md774',1,'']]],
  ['singleton_20pattern_65',['1. Singleton Pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md62',1,'']]],
  ['slow_20message_20processing_66',['Problem: Slow Message Processing',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1067',1,'']]],
  ['small_20messages_67',['Issue 1: High CPU Usage with Small Messages',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1050',1,'']]],
  ['software_20dependencies_68',['Software Dependencies',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md753',1,'']]],
  ['solutions_69',['solutions',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md718',1,'Common Build Issues and Solutions'],['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md236',1,'Implemented Solutions'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1752',1,'Migration from Custom Solutions']]],
  ['source_70',['From Source',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md757',1,'']]],
  ['spawning_71',['Subtask Spawning',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1857',1,'']]],
  ['spawning_20subtasks_72',['Spawning Subtasks',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1858',1,'']]],
  ['specific_20architecture_73',['Component-Specific Architecture',['../d2/d64/md_docs_2architecture.html#autotoc_md375',1,'']]],
  ['specific_20notes_74',['Platform-Specific Notes',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md739',1,'']]],
  ['specific_20settings_75',['Environment-Specific Settings',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1683',1,'']]],
  ['specific_20setup_76',['2. Platform-Specific Setup',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md980',1,'']]],
  ['split_20test_20execution_77',['1. Split Test Execution',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md247',1,'']]],
  ['sprint_78',['Priority 2 (Recommended - Next Sprint)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md256',1,'']]],
  ['sprint_201_3a_20core_20task_20infrastructure_20✅_79',['Sprint 1: Core Task Infrastructure ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2060',1,'']]],
  ['sprint_202_3a_20queue_20result_20backend_20✅_80',['Sprint 2: Queue &amp; Result Backend ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2061',1,'']]],
  ['sprint_203_3a_20worker_20system_20✅_81',['Sprint 3: Worker System ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2062',1,'']]],
  ['sprint_204_3a_20client_20async_20result_20✅_82',['Sprint 4: Client &amp; Async Result ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2063',1,'']]],
  ['sprint_205_3a_20scheduler_20✅_83',['Sprint 5: Scheduler ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2064',1,'']]],
  ['sprint_206_3a_20monitoring_20system_20integration_20✅_84',['Sprint 6: Monitoring &amp; System Integration ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2065',1,'']]],
  ['sprint_207_3a_20testing_20documentation_20✅_85',['Sprint 7: Testing &amp; Documentation ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2066',1,'']]],
  ['ssl_20tls_20configuration_86',['SSL/TLS Configuration',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md822',1,'']]],
  ['stack_87',['Log Aggregation (ELK Stack)',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md802',1,'']]],
  ['stage_5fcount_20tt_88',['&lt;tt&gt;stage_count&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md157',1,'']]],
  ['staging_20environment_89',['Staging Environment',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1685',1,'']]],
  ['standalone_20backend_90',['Standalone Backend',['../da/db6/md_docs_2FEATURES.html#autotoc_md622',1,'']]],
  ['standard_20is_20required_91',['Q: What C++ standard is required?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md897',1,'']]],
  ['standards_92',['standards',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1335',1,'📖 Documentation Standards'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md852',1,'Coding Standards'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md572',1,'Coding Standards'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md857',1,'Documentation Standards'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1205',1,'Industry Standards']]],
  ['start_93',['start',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2097',1,'🚀 Quick Start'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md955',1,'Issue: Message bus doesn&apos;t start'],['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1066',1,'Problem: Service Won&apos;t Start'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md838',1,'Quick Start'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md988',1,'Quick Start'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md831',1,'Service Won&apos;t Start']]],
  ['start_20guide_94',['Task Module Quick Start Guide',['../d9/dff/md_docs_2task_2QUICK__START.html',1,'']]],
  ['start_20the_20system_95',['4. Start the System',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1931',1,'']]],
  ['start_20tt_20tt_20stop_20tt_96',['start tt tt stop tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md141',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md121',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md155',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;']]],
  ['started_97',['started',['../da/db6/md_docs_2FEATURES.html#autotoc_md659',1,'Getting Started'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html#autotoc_md566',1,'Getting Started'],['../d6/d63/md_docs_2guides_2QUICK__START.html',1,'Getting Started']]],
  ['state_20backup_98',['Application State Backup',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md814',1,'']]],
  ['state_20methods_99',['State Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1364',1,'']]],
  ['state_20pr_2030_20success_100',['Target State (PR #30 - Success)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md235',1,'']]],
  ['state_20pr_2031_20before_20fix_101',['Initial State (PR #31 - Before Fix)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md234',1,'']]],
  ['statement_102',['Problem Statement',['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md4',1,'']]],
  ['static_20analysis_103',['Static Analysis',['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1177',1,'']]],
  ['static_20configuration_104',['static configuration',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md223',1,'Static Configuration'],['../d2/d64/md_docs_2architecture.html#autotoc_md410',1,'Static Configuration']]],
  ['static_20methods_105',['Static Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1452',1,'']]],
  ['statistics_106',['statistics',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1026',1,'Network Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1458',1,'Queue Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1408',1,'Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1472',1,'Statistics'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1412',1,'Statistics']]],
  ['status_107',['status',['../index.html#autotoc_md55',1,'ADR Status'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1973',1,'Check Queue Status'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1974',1,'Check Worker Status'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md21',1,'Current Implementation Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1411',1,'Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1421',1,'Status'],['../de/dd2/md_docs_2adr_2001-logging-architecture.html#autotoc_md1',1,'Status'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1459',1,'Worker Status']]],
  ['status_20methods_108',['Status Methods',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1424',1,'']]],
  ['step_201_3a_20update_20dependencies_109',['Step 1: Update Dependencies',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md929',1,'']]],
  ['step_202_3a_20update_20includes_110',['Step 2: Update Includes',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md932',1,'']]],
  ['step_203_3a_20migrate_20message_20creation_111',['Step 3: Migrate Message Creation',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md933',1,'']]],
  ['step_204_3a_20migrate_20message_20bus_20usage_112',['Step 4: Migrate Message Bus Usage',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md934',1,'']]],
  ['step_205_3a_20migrate_20to_20patterns_20optional_20but_20recommended_113',['Step 5: Migrate to Patterns (Optional but Recommended)',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md935',1,'']]],
  ['step_206_3a_20update_20error_20handling_114',['Step 6: Update Error Handling',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md938',1,'']]],
  ['step_207_3a_20integration_20with_20other_20systems_115',['Step 7: Integration with Other Systems',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md939',1,'']]],
  ['step_20by_20step_20migration_116',['Step-by-Step Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md928',1,'']]],
  ['steps_117',['steps',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1941',1,'Next Steps'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md1000',1,'Next Steps']]],
  ['still_20use_20simple_20publish_20subscribe_118',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md965',1,'']]],
  ['stop_20the_20system_119',['6. Stop the System',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1933',1,'']]],
  ['stop_20tt_120',['stop tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md141',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md155',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md121',1,'&lt;tt&gt;start&lt;/tt&gt; / &lt;tt&gt;stop&lt;/tt&gt;']]],
  ['strace_121',['System Tracing with strace',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1033',1,'']]],
  ['strategies_122',['strategies',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md345',1,'Error Recovery Strategies'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1827',1,'Retry Strategies'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md803',1,'Scaling Strategies']]],
  ['strategy_123',['strategy',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md813',1,'Backup Strategy'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md811',1,'Sharding Strategy'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1181',1,'Testing Strategy']]],
  ['strategy_20pattern_124',['strategy pattern',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md73',1,'10. Strategy Pattern'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1621',1,'5. Strategy Pattern']]],
  ['streaming_125',['streaming',['../da/db6/md_docs_2FEATURES.html#autotoc_md593',1,'Event Streaming'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md676',1,'Event Streaming'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2106',1,'Event Streaming'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md949',1,'Example 3: Event Streaming']]],
  ['streaming_20pattern_126',['streaming pattern',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md180',1,'Event Streaming Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md124',1,'Event Streaming Pattern']]],
  ['struct_3a_20tt_20event_5fstream_5fconfig_20tt_127',['Struct: &lt;tt&gt;event_stream_config&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md126',1,'']]],
  ['struct_3a_20tt_20pipeline_5fstage_20tt_128',['Struct: &lt;tt&gt;pipeline_stage&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md150',1,'']]],
  ['structural_20patterns_129',['Structural Patterns',['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md66',1,'']]],
  ['structure_130',['structure',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md924',1,'3. Message Structure'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1258',1,'CMake Structure'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md768',1,'Configuration File Structure'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md306',1,'Configuration Structure'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2068',1,'File Structure'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1279',1,'Future Structure'],['../da/db6/md_docs_2FEATURES.html#autotoc_md627',1,'Message Structure'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'Messaging System Project Structure'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md849',1,'Project Structure'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md993',1,'Project Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1671',1,'Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1665',1,'Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1660',1,'Structure'],['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1678',1,'Structure'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1451',1,'Structure'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md862',1,'Test Structure']]],
  ['structured_20logging_131',['Structured Logging',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md801',1,'']]],
  ['structures_132',['structures',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1431',1,'Structures'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1456',1,'Structures'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1440',1,'Structures'],['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1388',1,'Structures']]],
  ['studio_133',['Visual Studio',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md847',1,'']]],
  ['studio_20code_134',['Visual Studio Code',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md845',1,'']]],
  ['style_20guide_135',['C++ Style Guide',['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md853',1,'']]],
  ['sub_136',['sub',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md485',1,'Latency Distribution (Pub/Sub)'],['../d4/d54/md_docs_2API__REFERENCE__KO.html#autotoc_md365',1,'Pub/Sub'],['../d5/ddb/md_docs_2BENCHMARKS__KO.html#autotoc_md522',1,'Pub/Sub'],['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md674',1,'Pub/Sub']]],
  ['sub_20migration_137',['Example 1: Simple Pub/Sub Migration',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md947',1,'']]],
  ['sub_20pattern_138',['sub pattern',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md936',1,'Pub/Sub Pattern'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2104',1,'Pub/Sub Pattern'],['../da/db6/md_docs_2FEATURES.html#autotoc_md591',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md87',1,'Pub/Sub Pattern'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md178',1,'Pub/Sub Pattern']]],
  ['sub_20performance_139',['Pub/Sub Performance',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md464',1,'']]],
  ['subdirectory_140',['Subdirectory',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1077',1,'']]],
  ['submission_141',['Job Submission',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md325',1,'']]],
  ['submission_20convenience_142',['Task Submission (Convenience)',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1470',1,'']]],
  ['submission_20flow_143',['Task Submission Flow',['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1609',1,'']]],
  ['submit_20a_20task_144',['5. Submit a Task',['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1932',1,'']]],
  ['submitting_20to_20priority_20queues_145',['Submitting to Priority Queues',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1838',1,'']]],
  ['subscribe_146',['Q: Can I still use simple publish/subscribe?',['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md965',1,'']]],
  ['subscribe_20to_20topics_147',['Q: How do I subscribe to topics?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md906',1,'']]],
  ['subscribe_20tt_148',['subscribe tt',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md100',1,'&lt;tt&gt;subscribe&lt;/tt&gt;'],['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md131',1,'&lt;tt&gt;subscribe&lt;/tt&gt;']]],
  ['subscriber_20scaling_149',['Publisher/Subscriber Scaling',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md490',1,'']]],
  ['subscriber_20tt_150',['Class: &lt;tt&gt;subscriber&lt;/tt&gt;',['../df/dde/md_docs_2advanced_2PATTERNS__API.html#autotoc_md97',1,'']]],
  ['subscription_151',['Subscription',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md309',1,'']]],
  ['subscription_20count_20impact_152',['Subscription Count Impact',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md462',1,'']]],
  ['subscription_20management_153',['Subscription Management',['../da/db6/md_docs_2FEATURES.html#autotoc_md633',1,'']]],
  ['subscriptioncallable_154',['subscriptioncallable',['../d4/d0c/md_docs_2FEATURES__KO.html#autotoc_md700',1,'SubscriptionCallable'],['../da/db6/md_docs_2FEATURES.html#autotoc_md617',1,'SubscriptionCallable']]],
  ['subscriptions_155',['Event Subscriptions',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1462',1,'']]],
  ['subsystems_156',['Integration with Subsystems',['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1079',1,'']]],
  ['subtask_20management_157',['Subtask Management',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1393',1,'']]],
  ['subtask_20spawning_158',['Subtask Spawning',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1857',1,'']]],
  ['subtasks_159',['subtasks',['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1858',1,'Spawning Subtasks'],['../d5/dd2/md_docs_2task_2PATTERNS.html#autotoc_md1859',1,'Tracking Subtasks']]],
  ['success_160',['Target State (PR #30 - Success)',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md235',1,'']]],
  ['successful_20build_161',['Verifying Successful Build',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md733',1,'']]],
  ['suites_162',['Test Suites',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2120',1,'']]],
  ['summary_163',['summary',['../d1/dc9/md_docs_2advanced_2WINDOWS__OPTIMIZATION.html#autotoc_md232',1,'Executive Summary'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md446',1,'Executive Summary'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2029',1,'Executive Summary'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md478',1,'Performance Targets Summary'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md744',1,'Quick Fix Summary'],['../d6/d58/md_docs_2advanced_2DESIGN__PATTERNS.html#autotoc_md83',1,'Summary']]],
  ['support_164',['support',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2131',1,'🌐 Platform Support'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2139',1,'📬 Contact &amp; Support'],['../da/db6/md_docs_2FEATURES.html#autotoc_md620',1,'Backend Support'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md752',1,'Operating System Support'],['../dd/def/md_docs_2PRODUCTION__QUALITY.html#autotoc_md1218',1,'Support'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md970',1,'Support'],['../da/db6/md_docs_2FEATURES.html#autotoc_md655',1,'Testing Support'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md299',1,'Transaction Support']]],
  ['supported_165',['Q: Which platforms are supported?',['../d4/da1/md_docs_2guides_2FAQ.html#autotoc_md898',1,'']]],
  ['supported_20macos_166',['Issue 3: grep -P Not Supported (macOS)',['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md723',1,'']]],
  ['supported_20syntax_167',['Supported Syntax',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1450',1,'']]],
  ['supported_20types_168',['Supported Types',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md278',1,'']]],
  ['synchronous_20rpc_20latency_169',['Synchronous RPC Latency',['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md469',1,'']]],
  ['syntax_170',['Supported Syntax',['../df/d18/md_docs_2task_2API__REFERENCE.html#autotoc_md1450',1,'']]],
  ['system_171',['system',['../d2/d64/md_docs_2architecture.html#autotoc_md381',1,'1. Container System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md194',1,'1. Container System'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1929',1,'2. Create and Configure the Task System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md195',1,'2. Network System'],['../d2/d64/md_docs_2architecture.html#autotoc_md382',1,'2. Network System'],['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md984',1,'3. Build the System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md196',1,'3. Database System'],['../d2/d64/md_docs_2architecture.html#autotoc_md383',1,'3. Database System'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1931',1,'4. Start the System'],['../d2/d64/md_docs_2architecture.html#autotoc_md384',1,'4. Thread System'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md197',1,'4. Thread System'],['../d9/dff/md_docs_2task_2QUICK__START.html#autotoc_md1933',1,'6. Stop the System'],['../da/d7c/md_docs_2guides_2DEVELOPER__GUIDE.html#autotoc_md879',1,'Build System'],['../d4/d22/md_docs_2PROJECT__STRUCTURE.html#autotoc_md1257',1,'Build System'],['../d7/d4b/md_docs_2contributing_2CONTRIBUTING.html',1,'Contributing to Messaging System'],['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2035',1,'Phase 2: Worker System'],['../dd/df5/md_docs_2task_2TROUBLESHOOTING.html#autotoc_md1991',1,'Q: How do I gracefully shut down the system?'],['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1333',1,'Task Queue System'],['../da/db6/md_docs_2FEATURES.html#autotoc_md596',1,'Task Queue System']]],
  ['system_20✅_172',['Sprint 3: Worker System ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2062',1,'']]],
  ['system_20기능_173',['Messaging System 기능',['../d4/d0c/md_docs_2FEATURES__KO.html',1,'']]],
  ['system_20문서_174',['Messaging System 문서',['../d8/d0a/md_docs_2README__KO.html',1,'']]],
  ['system_20변경_20이력_175',['Messaging System 변경 이력',['../db/d9f/md_docs_2CHANGELOG__KO.html',1,'']]],
  ['system_20성능_20벤치마크_176',['Messaging System 성능 벤치마크',['../d5/ddb/md_docs_2BENCHMARKS__KO.html',1,'']]],
  ['system_20아키텍처_177',['Messaging System 아키텍처',['../de/de3/md_docs_2ARCHITECTURE__KO.html',1,'']]],
  ['system_20프로덕션_20품질_178',['Messaging System 프로덕션 품질',['../d2/d74/md_docs_2PRODUCTION__QUALITY__KO.html',1,'']]],
  ['system_20프로젝트_20구조_179',['Messaging System 프로젝트 구조',['../d5/d19/md_docs_2PROJECT__STRUCTURE__KO.html',1,'']]],
  ['system_20administrators_180',['For System Administrators',['..//home/runner/work/messaging_system/messaging_system/docs/README.md#autotoc_md1328',1,'']]],
  ['system_20api_181',['system api',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md267',1,'Container System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md292',1,'Database System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md334',1,'Logger System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md281',1,'Network System API'],['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md321',1,'Thread System API']]],
  ['system_20api_20레퍼런스_182',['Messaging System API 레퍼런스',['../d4/d54/md_docs_2API__REFERENCE__KO.html',1,'']]],
  ['system_20architecture_183',['system architecture',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html',1,'System Architecture'],['../d1/d5e/md_docs_2task_2ARCHITECTURE.html#autotoc_md1596',1,'System Architecture']]],
  ['system_20changelog_184',['Messaging System Changelog',['../da/dee/md_docs_2CHANGELOG.html',1,'']]],
  ['system_20configuration_185',['Task System Configuration',['../dc/d1e/md_docs_2task_2CONFIGURATION.html#autotoc_md1659',1,'']]],
  ['system_20configuration_20file_20format_186',['System Configuration File Format',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md347',1,'']]],
  ['system_20cron_187',['Before (System Cron)',['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1761',1,'']]],
  ['system_20error_20codes_188',['System Error Codes',['../db/d91/md_docs_2API__REFERENCE.html#autotoc_md343',1,'']]],
  ['system_20facade_189',['Task System Facade',['../da/db6/md_docs_2FEATURES.html#autotoc_md598',1,'']]],
  ['system_20features_190',['Messaging System Features',['../da/db6/md_docs_2FEATURES.html',1,'']]],
  ['system_20health_191',['System Health',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md836',1,'']]],
  ['system_20improvement_20plan_192',['Distributed Task Queue System - Improvement Plan',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html',1,'']]],
  ['system_20integration_193',['system integration',['../da/db6/md_docs_2FEATURES.html#autotoc_md650',1,'Container System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md648',1,'Logger System Integration'],['..//home/runner/work/messaging_system/messaging_system/docs/integration/README.md#autotoc_md1097',1,'Monitoring System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md649',1,'Monitoring System Integration'],['../da/db6/md_docs_2FEATURES.html#autotoc_md647',1,'Thread System Integration']]],
  ['system_20integration_20✅_194',['Sprint 6: Monitoring &amp; System Integration ✅',['../d1/db3/md_docs_2TASK__QUEUE__IMPROVEMENT__PLAN.html#autotoc_md2065',1,'']]],
  ['system_20layers_195',['system layers',['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md192',1,'System Layers'],['../d2/d64/md_docs_2architecture.html#autotoc_md379',1,'System Layers']]],
  ['system_20overview_196',['System Overview',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2094',1,'']]],
  ['system_20performance_197',['system performance',['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1136',1,'Container System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1142',1,'Database System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1139',1,'Network System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1129',1,'Overall System Performance'],['../d9/dd2/md_docs_2performance_2PERFORMANCE.html#autotoc_md1133',1,'Thread System Performance']]],
  ['system_20performance_20benchmarks_198',['Messaging System Performance Benchmarks',['../de/d93/md_docs_2BENCHMARKS.html',1,'']]],
  ['system_20production_20quality_199',['Messaging System Production Quality',['../dd/def/md_docs_2PRODUCTION__QUALITY.html',1,'']]],
  ['system_20project_20structure_200',['Messaging System Project Structure',['../d4/d22/md_docs_2PROJECT__STRUCTURE.html',1,'']]],
  ['system_20requirements_201',['system requirements',['../d6/d63/md_docs_2guides_2QUICK__START.html#autotoc_md975',1,'System Requirements'],['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md747',1,'System Requirements']]],
  ['system_20support_202',['Operating System Support',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md752',1,'']]],
  ['system_20tracing_20with_20strace_203',['System Tracing with strace',['../d6/dab/md_docs_2guides_2TROUBLESHOOTING.html#autotoc_md1033',1,'']]],
  ['system_20tuning_204',['System Tuning',['../d9/d77/md_docs_2guides_2DEPLOYMENT__GUIDE.html#autotoc_md785',1,'']]],
  ['system_5farchitecture_2emd_205',['SYSTEM_ARCHITECTURE.md',['../db/d93/SYSTEM__ARCHITECTURE_8md.html',1,'']]],
  ['systems_206',['systems',['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2109',1,'🌟 Integration with Base Systems'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md731',1,'Alternative: Minimal Build (No External Systems)'],['../de/d93/md_docs_2BENCHMARKS.html#autotoc_md503',1,'Comparison with Other Systems'],['../df/dbc/md_docs_2advanced_2SYSTEM__ARCHITECTURE.html#autotoc_md206',1,'External Systems'],['../d2/d64/md_docs_2architecture.html#autotoc_md393',1,'External Systems'],['../d2/d8d/md_docs_2task_2MIGRATION.html#autotoc_md1757',1,'From Message Queue Systems'],['../d6/d3f/md_docs_2guides_2BUILD__TROUBLESHOOTING.html#autotoc_md721',1,'Issue 2: GTest Not Found in External Systems'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2111',1,'Optional Systems'],['..//home/runner/work/messaging_system/messaging_system/README.md#autotoc_md2110',1,'Required Systems'],['../dc/d15/md_docs_2guides_2MIGRATION__GUIDE.html#autotoc_md939',1,'Step 7: Integration with Other Systems']]]
];
