var searchData=
[
  ['patterns_2emd_0',['patterns.md',['../da/df3/patterns_8md.html',1,'']]],
  ['performance_2emd_1',['performance.md',['../d3/d16/docs_2performance_8md.html',1,'(Global Namespace)'],['../d3/da1/libraries_2container__system_2performance_8md.html',1,'(Global Namespace)'],['../de/d89/libraries_2thread__system_2docs_2performance_8md.html',1,'(Global Namespace)'],['../d8/d74/PERFORMANCE_8md.html',1,'(Global Namespace)']]],
  ['performance_5fbenchmark_2ecpp_2',['performance_benchmark.cpp',['../df/db0/performance__benchmark_8cpp.html',1,'']]],
  ['performance_5fbenchmarks_2emd_3',['PERFORMANCE_BENCHMARKS.md',['../d7/d9d/PERFORMANCE__BENCHMARKS_8md.html',1,'']]],
  ['performance_5fmonitor_2ecpp_4',['performance_monitor.cpp',['../de/dbd/database__system_2database_2monitoring_2performance__monitor_8cpp.html',1,'(Global Namespace)'],['../d9/d77/monitoring__system_2src_2core_2performance__monitor_8cpp.html',1,'(Global Namespace)']]],
  ['performance_5fmonitor_2eh_5',['performance_monitor.h',['../de/df8/monitoring__system_2include_2monitoring_2performance_2performance__monitor_8h.html',1,'(Global Namespace)'],['../d8/d28/monitoring__system_2include_2kcenon_2monitoring_2core_2performance__monitor_8h.html',1,'(Global Namespace)'],['../d4/db5/database__system_2database_2monitoring_2performance__monitor_8h.html',1,'(Global Namespace)']]],
  ['performance_5fmonitoring_5fdemo_2ecpp_6',['performance_monitoring_demo.cpp',['../d1/ded/performance__monitoring__demo_8cpp.html',1,'']]],
  ['performance_5ftest_2ecpp_7',['performance_test.cpp',['../d0/de9/performance__test_8cpp.html',1,'']]],
  ['performance_5ftests_2ecpp_8',['performance_tests.cpp',['../d8/d14/performance__tests_8cpp.html',1,'']]],
  ['performance_5ftuning_2emd_9',['PERFORMANCE_TUNING.md',['../de/d9a/PERFORMANCE__TUNING_8md.html',1,'']]],
  ['phase3_2emd_10',['PHASE3.md',['../dd/d62/PHASE3_8md.html',1,'']]],
  ['pipeline_2ecpp_11',['pipeline.cpp',['../d1/de9/src_2internal_2pipeline_8cpp.html',1,'(Global Namespace)'],['../da/d6c/internal_2pipeline_8cpp.html',1,'(Global Namespace)']]],
  ['pipeline_2eh_12',['pipeline.h',['../d0/d53/src_2internal_2pipeline_8h.html',1,'(Global Namespace)'],['../d4/dbd/internal_2pipeline_8h.html',1,'(Global Namespace)'],['../df/dae/include_2network__system_2internal_2pipeline_8h.html',1,'(Global Namespace)']]],
  ['platform_5fspecific_5ftest_2ecpp_13',['platform_specific_test.cpp',['../d8/da2/unittest_2platform__test_2platform__specific__test_8cpp.html',1,'(Global Namespace)'],['../d9/d10/tests_2unit_2platform__test_2platform__specific__test_8cpp.html',1,'(Global Namespace)']]],
  ['plugin_5fcollector_5fexample_2ecpp_14',['plugin_collector_example.cpp',['../dc/d7a/plugin__collector__example_8cpp.html',1,'']]],
  ['plugin_5fmetric_5fcollector_2eh_15',['plugin_metric_collector.h',['../d6/da5/plugin__metric__collector_8h.html',1,'']]],
  ['pool_5fbuilder_2eh_16',['pool_builder.h',['../d1/df2/pool__builder_8h.html',1,'']]],
  ['pool_5ftraits_2eh_17',['pool_traits.h',['../da/d62/pool__traits_8h.html',1,'']]],
  ['postgres_5fadvanced_2ecpp_18',['postgres_advanced.cpp',['../d4/d17/postgres__advanced_8cpp.html',1,'']]],
  ['postgres_5fmanager_2ecpp_19',['postgres_manager.cpp',['../da/d57/postgres__manager_8cpp.html',1,'']]],
  ['postgres_5fmanager_2eh_20',['postgres_manager.h',['../d6/d94/postgres__manager_8h.html',1,'']]],
  ['production_5foptimizations_2eh_21',['production_optimizations.h',['../d9/d34/production__optimizations_8h.html',1,'']]],
  ['production_5fready_5fexample_2ecpp_22',['production_ready_example.cpp',['../d9/dd9/production__ready__example_8cpp.html',1,'']]]
];
