Messaging System: libraries/logger_system/samples/metrics_demo.cpp File Reference
metrics_demo.cpp File Reference
#include <logger/logger.h>
#include <logger/writers/console_writer.h>
#include <logger/structured/structured_logger.h>
#include <thread>
#include <iostream>
#include <random>
Functions
void generate_logs (logger *log, int thread_id, int count)
void print_metrics (const performance_metrics &metrics)
void test_structured_logging ()
int main ()
Function Documentation
generate_logs()
void generate_logs (logger * log, int thread_id, int count)
Definition at line 17 of file metrics_demo.cpp.
References logger_module::logger::log().
Referenced by main().
main()
int main ()
Definition at line 97 of file metrics_demo.cpp.
References logger_module::logger::add_writer(), logger_module::logger::enable_metrics_collection(), generate_logs(), logger_module::logger::get_current_metrics(), print_metrics(), logger_module::logger::start(), logger_module::logger::stop(), and test_structured_logging().
print_metrics()
void print_metrics (const performance_metrics & metrics)
Definition at line 36 of file metrics_demo.cpp.
References logger_module::writer_metrics::bytes_written, logger_module::performance_metrics::get_avg_enqueue_time_ns(), logger_module::writer_metrics::get_avg_write_time_us(), logger_module::performance_metrics::get_bytes_per_second(), logger_module::performance_metrics::get_drop_rate_percent(), logger_module::performance_metrics::get_messages_per_second(), logger_module::performance_metrics::get_queue_utilization_percent(), logger_module::performance_metrics::messages_dropped, logger_module::performance_metrics::messages_enqueued, logger_module::performance_metrics::messages_processed, logger_module::writer_metrics::messages_written, logger_module::writer_metrics::write_failures, and logger_module::performance_metrics::writer_stats.
Referenced by main().
test_structured_logging()
void test_structured_logging ()
Definition at line 57 of file metrics_demo.cpp.
Referenced by main().