Messaging System: logger_module::log_file_recovery Class Reference
logger_module::log_file_recovery Class Reference
Log file corruption detector and recovery.
#include <logger_crash_safety.h>
Static Public Member Functions
static bool is_corrupted (const std::string &file_path)
Check if log file is corrupted.
static bool recover_file (const std::string &file_path, const std::string &recovery_path)
Attempt to recover corrupted log file.
static bool create_backup_with_checksum (const std::string &source_path, const std::string &backup_path)
Create backup of log file with integrity check.
static bool verify_integrity (const std::string &file_path, const std::string &checksum_path)
Verify log file integrity using checksum.
Detailed Description
Log file corruption detector and recovery.
Definition at line 241 of file logger_crash_safety.h.
Member Function Documentation
create_backup_with_checksum()
static bool logger_module::log_file_recovery::create_backup_with_checksum (const std::string & source_path, const std::string & backup_path) static
Create backup of log file with integrity check.
Parameters
source_path Source log file
backup_path Backup file path
Returns
true if backup successful
Referenced by main().
is_corrupted()
static bool logger_module::log_file_recovery::is_corrupted (const std::string & file_path) static
Check if log file is corrupted.
Parameters
file_path Path to log file
Returns
true if corruption detected
Referenced by main().
recover_file()
static bool logger_module::log_file_recovery::recover_file (const std::string & file_path, const std::string & recovery_path) static
Attempt to recover corrupted log file.
Parameters
file_path Path to corrupted log file
recovery_path Path for recovered file
Returns
true if recovery successful
Referenced by main().
verify_integrity()
static bool logger_module::log_file_recovery::verify_integrity (const std::string & file_path, const std::string & checksum_path) static
Verify log file integrity using checksum.
Parameters
file_path Path to log file
checksum_path Path to checksum file
Returns
true if integrity verified
Referenced by main().
The documentation for this class was generated from the following file:
libraries/logger_system/sources/interfaces/logger_crash_safety.h