Messaging System: kcenon::thread Namespace Reference
kcenon::thread Namespace Reference
Core threading foundation of the thread system library.
Namespaces
namespace adapters
namespace config
namespace core
namespace detail
namespace impl
namespace interfaces
namespace job_detail
namespace jobs
namespace sync
namespace test
namespace utils
Classes
class adaptive_typed_job_queue_t
Adaptive priority queue that switches between mutex-based and lock-free implementations.
class callback_job
A specialized job class that encapsulates user-defined callbacks.
class callback_typed_job_t
A template for creating priority-based jobs that execute a user-defined callback.
class cancellation_token
Provides a mechanism for cooperative cancellation of operations.
struct config_changed_event
Configuration changed event.
class configuration_manager
Configuration manager for unified system configuration.
struct crash_context
Crash context information.
class crash_handler
Thread-safe crash handler for the entire thread system.
class default_error_handler
Default error handler implementation.
class error
Represents an error in the thread system.
class error_handler
Error handler interface.
class event_base
Event base class for type safety.
class event_bus
Event Bus for publish-subscribe pattern.
class executor_interface
Executor interface for submitting work and coordinating shutdown.
class job
Represents a unit of work (task) to be executed, typically by a job queue.
class job_queue
A thread-safe job queue for managing and dispatching work items.
class logger_interface
Logger interface for thread system.
class logger_registry
Global logger registry.
class monitorable_interface
Interface for components exposing metrics.
struct performance_alert_event
Performance alert event.
class pool_future
A future that can be scheduled on a thread pool.
class pool_promise
A promise that can schedule work on a thread pool.
class pool_promise< void >
Specialization for void type.
class result
A template class representing either a value or an error.
class result< void >
Specialization of result for void.
class result_void
Wrapper for void result.
class scheduler_interface
Scheduler interface for queuing and retrieving jobs.
class scoped_crash_callback
RAII helper for automatic crash callback registration.
class scoped_service
RAII helper for scoped service registration.
class service_container
Modern service container for dependency injection.
class service_registry
Lightweight service registry for dependency lookup.
struct system_shutdown_event
System shutdown event.
struct system_startup_event
System startup event.
class thread_base
A foundational class for implementing custom worker threads.
class thread_context
Context object that provides access to optional services.
class thread_context_builder
Builder for thread_context with fluent interface.
class thread_pool
A thread pool for concurrent execution of jobs using multiple worker threads.
class thread_pool_crash_safety
Thread pool crash safety extensions.
class thread_worker
A specialized worker thread that processes jobs from a job_queue.
class typed_job_factory_interface
Factory interface for creating typed jobs.
class typed_job_interface
Base interface for all typed jobs.
class typed_job_queue_t
A template-based queue that manages jobs with distinct priority levels.
class typed_job_t
Represents a job that carries a specific priority level.
class typed_lockfree_job_queue_t
High-performance lock-free priority-based job queue.
struct typed_queue_statistics_t
class typed_thread_pool_builder
Builder class for constructing typed thread pools.
class typed_thread_pool_t
A thread pool that schedules and executes jobs based on their priority levels.
class typed_thread_worker_t
A template-based worker thread class that processes jobs from a priority job queue.
struct validation_result
Configuration validation result.
struct worker_policy
Worker behavior policy configuration.
Typedefs
template<typename T >
using result_t = result< T >
using config_value = std::variant< bool, int, double, std::string, std::vector< std::string >, std::unordered_map< std::string, std::any > >
Configuration value type.
using crash_callback = std::function< void(const crash_context &)>
Callback function type for crash handling.
using callback_typed_job = callback_typed_job_t< job_types >
Type alias for a callback_typed_job_t that uses job_types as its priority type.
using typed_job = typed_job_t< job_types >
A convenient alias for typed_job_t using the job_types type.
template<detail::JobType job_type>
using typed_job_ptr = std::shared_ptr< typed_job_interface< job_type > >
Shared pointer type for typed job interfaces.
template<detail::JobType job_type>
using typed_job_weak_ptr = std::weak_ptr< typed_job_interface< job_type > >
Weak pointer type for typed job interfaces.
using typed_job_queue = typed_job_queue_t< job_types >
Alias for a typed_job_queue using default job types.
using typed_queue_statistics = typed_queue_statistics_t< job_types >
using typed_lockfree_job_queue = typed_lockfree_job_queue_t< job_types >
using typed_thread_pool = typed_thread_pool_t< job_types >
Alias for a typed_thread_pool with the default job_types type.
using typed_thread_worker = typed_thread_worker_t< job_types >
Convenience typedef for a worker configured with default job_types.
Enumerations
enum class error_code {
success = 0 , unknown_error , operation_canceled , operation_timeout ,
not_implemented , invalid_argument , thread_already_running = 100 , thread_not_running ,
thread_start_failure , thread_join_failure , queue_full = 200 , queue_empty ,
queue_stopped , job_creation_failed = 300 , job_execution_failed , job_invalid ,
resource_allocation_failed = 400 , resource_limit_reached , mutex_error = 500 , deadlock_detected ,
condition_variable_error , io_error = 600 , file_not_found , success = 0 ,
unknown_error , operation_canceled , operation_timeout , not_implemented ,
invalid_argument , thread_already_running = 100 , thread_not_running , thread_start_failure ,
thread_join_failure , queue_full = 200 , queue_empty , queue_stopped ,
job_creation_failed = 300 , job_execution_failed , job_invalid , resource_allocation_failed = 400 ,
resource_limit_reached , mutex_error = 500 , deadlock_detected , condition_variable_error ,
io_error = 600 , file_not_found
}
Strongly typed error codes for thread system operations.
enum class error_code {
success = 0 , unknown_error , operation_canceled , operation_timeout ,
not_implemented , invalid_argument , thread_already_running = 100 , thread_not_running ,
thread_start_failure , thread_join_failure , queue_full = 200 , queue_empty ,
queue_stopped , job_creation_failed = 300 , job_execution_failed , job_invalid ,
resource_allocation_failed = 400 , resource_limit_reached , mutex_error = 500 , deadlock_detected ,
condition_variable_error , io_error = 600 , file_not_found , success = 0 ,
unknown_error , operation_canceled , operation_timeout , not_implemented ,
invalid_argument , thread_already_running = 100 , thread_not_running , thread_start_failure ,
thread_join_failure , queue_full = 200 , queue_empty , queue_stopped ,
job_creation_failed = 300 , job_execution_failed , job_invalid , resource_allocation_failed = 400 ,
resource_limit_reached , mutex_error = 500 , deadlock_detected , condition_variable_error ,
io_error = 600 , file_not_found
}
enum class thread_conditions : uint8_t {
Created , Waiting , Working , Stopping ,
Stopped
}
Enumeration of various states in a thread's lifecycle.
enum class worker_state {
created , starting , active , idle ,
stopping , stopped
}
Enumeration of worker states.
enum class scheduling_policy { fifo , lifo , priority , work_stealing }
Enumeration of scheduling policies.
enum class crash_safety_level { minimal , standard , paranoid }
Crash safety levels for different scenarios.
enum class log_level {
critical = 0 , error = 1 , warning = 2 , info = 3 ,
debug = 4 , trace = 5
}
Log level enumeration.
enum class job_types : uint8_t { RealTime , Batch , Background }
Defines different types of jobs for a typed thread pool.
Functions
std::string error_code_to_string (error_code code)
Converts an error_code to a string representation.
template<typename T >
result< T > optional_error_to_result (const std::optional< std::string > &error, T &&value)
result< void > optional_error_to_result (const std::optional< std::string > &error)
std::optional< std::string > result_to_optional_error (const result< void > &res)
template<typename T >
std::pair< std::optional< T >, std::optional< std::string > > result_to_pair (const result< T > &res)
template<typename T >
pool_future< std::decay_t< T > > make_ready_future (T &&value)
Create a future that is already ready with a value.
pool_future< void > make_ready_future ()
Create a future that is already ready with void.
template<typename T >
pool_future< T > make_exceptional_future (std::exception_ptr exception)
Create a future that is already ready with an exception.
template<typename... Futures>
void wait_for_all (Futures &... futures)
Wait for all futures to complete.
template<typename... Futures>
size_t wait_for_any (Futures &... futures)
Wait for any future to complete.
constexpr std::string_view to_string (thread_conditions condition)
Converts a thread_conditions value to its corresponding string representation.
auto all_types (void) -> std::vector< thread_conditions >
Retrieves a vector containing all possible thread_conditions values.
constexpr const char * to_string (worker_state state)
Convert worker state to string representation.
constexpr const char * to_string (scheduling_policy policy)
Convert scheduling policy to string representation.
template auto create_typed_job_queue< job_types > (adaptive_typed_job_queue_t< job_types >::queue_strategy, size_t) -> std::shared_ptr< typed_job_queue_t< job_types > >
Explicit instantiation of typed job queue factory function.
template<typename job_type = job_types>
auto create_typed_job_queue (typename adaptive_typed_job_queue_t< job_type >::queue_strategy strategy=adaptive_typed_job_queue_t< job_type >::queue_strategy::AUTO_DETECT, size_t max_threads=128) -> std::shared_ptr< typed_job_queue_t< job_type > >
Factory function to create appropriate typed job queue.
constexpr std::string_view to_string (job_types job_type)
Converts a job_types value to its corresponding string representation.
template<detail::JobType job_type = job_types>
typed_thread_pool_builder< job_type > create_pool_builder ()
Convenience function to create a builder.
Detailed Description
Core threading foundation of the thread system library.
Type-based thread pool implementation for job scheduling with types.
Thread pool implementation for managing worker threads.
The thread_module namespace provides fundamental threading primitives including the base thread class, jobs, job queues, and synchronization utilities. It serves as the foundation for all thread-related functionality in the library.
Key components include:
thread_base: The fundamental worker thread class
job: The base unit of work that can be scheduled and executed
job_queue: A thread-safe queue for storing and retrieving jobs
cancellation_token: Mechanism for cancelling ongoing operations
This namespace implements low-level threading concepts while higher-level functionality like thread pools are implemented in separate namespaces that build upon these primitives.
The thread_pool_module namespace provides a standard thread pool implementation for processing jobs concurrently using a team of worker threads.
Key components include:
thread_pool: The primary thread pool class managing multiple workers and a shared job queue
thread_worker: A specialized worker thread that processes jobs from a shared queue
task: A template-based convenience wrapper for creating and submitting callable jobs
The thread pool pattern improves performance by:
Reusing threads rather than creating new ones for each task
Reducing thread creation overhead
Limiting the total number of threads to control resource usage
Providing a simple interface for async task execution
See also
kcenon::thread for a more advanced implementation with job prioritization
The kcenon::thread namespace extends the basic thread pool concept with priority-based scheduling of jobs. It allows jobs to be processed according to their importance or urgency rather than just their order of submission.
Key components include:
typed_thread_pool_t: A templated thread pool class supporting prioritized job scheduling
typed_thread_worker_t: A worker thread that retrieves jobs based on priority
typed_job_t: A job with an associated priority level
typed_job_queue_t: A thread-safe job queue that orders jobs by priority
job_types: Default enumeration of priority levels
This implementation allows for:
Custom priority types through template parameters
RealTimeer priority jobs being processed ahead of lower priority ones
Dynamic adjustment of types based on application needs
See also
thread_pool_module for the basic non-prioritized implementation
Typedef Documentation
callback_typed_job
kcenon::thread::callback_typed_job
Type alias for a callback_typed_job_t that uses job_types as its priority type.
Definition at line 118 of file callback_typed_job.h.
config_value
using kcenon::thread::config_value = typedef std::variant< bool, int, double, std::string, std::vector<std::string>, std::unordered_map<std::string, std::any> >
Configuration value type.
Definition at line 21 of file configuration_manager.h.
crash_callback
using kcenon::thread::crash_callback = typedef std::function<void(const crash_context&)>
Callback function type for crash handling.
Definition at line 44 of file crash_handler.h.
result_t
template<typename T > using kcenon::thread::result_t = typedef result<T>
Definition at line 555 of file error_handling.h.
typed_job
kcenon::thread::typed_job
A convenient alias for typed_job_t using the job_types type.
Definition at line 134 of file typed_job.h.
typed_job_ptr
template<detail::JobType job_type> using kcenon::thread::typed_job_ptr = typedef std::shared_ptr<typed_job_interface<job_type> >
Shared pointer type for typed job interfaces.
Definition at line 128 of file typed_job_interface.h.
typed_job_queue
using kcenon::thread::typed_job_queue = typedef typed_job_queue_t<job_types>
Alias for a typed_job_queue using default job types.
Definition at line 277 of file typed_job_queue.h.
typed_job_weak_ptr
template<detail::JobType job_type> using kcenon::thread::typed_job_weak_ptr = typedef std::weak_ptr<typed_job_interface<job_type> >
Weak pointer type for typed job interfaces.
Definition at line 134 of file typed_job_interface.h.
typed_lockfree_job_queue
using kcenon::thread::typed_lockfree_job_queue = typedef typed_lockfree_job_queue_t<job_types>
Definition at line 298 of file typed_lockfree_job_queue.h.
typed_queue_statistics
using kcenon::thread::typed_queue_statistics = typedef typed_queue_statistics_t<job_types>
Definition at line 87 of file typed_lockfree_job_queue.h.
typed_thread_pool
using kcenon::thread::typed_thread_pool = typedef typed_thread_pool_t<job_types>
Alias for a typed_thread_pool with the default job_types type.
Definition at line 351 of file typed_thread_pool.h.
typed_thread_worker
using kcenon::thread::typed_thread_worker = typedef typed_thread_worker_t<job_types>
Convenience typedef for a worker configured with default job_types.
Definition at line 239 of file typed_thread_worker.h.
Enumeration Type Documentation
crash_safety_level
enum class kcenon::thread::crash_safety_level strong
Crash safety levels for different scenarios.
Enumerator
minimal
standard
paranoid
Definition at line 23 of file crash_handler.h.
error_code [1/2]
enum class kcenon::thread::error_code strong
Strongly typed error codes for thread system operations.
Enumerator
success
unknown_error
operation_canceled
operation_timeout
not_implemented
invalid_argument
thread_already_running
thread_not_running
thread_start_failure
thread_join_failure
queue_full
queue_empty
queue_stopped
job_creation_failed
job_execution_failed
job_invalid
resource_allocation_failed
resource_limit_reached
mutex_error
deadlock_detected
condition_variable_error
io_error
file_not_found
success
unknown_error
operation_canceled
operation_timeout
not_implemented
invalid_argument
thread_already_running
thread_not_running
thread_start_failure
thread_join_failure
queue_full
queue_empty
queue_stopped
job_creation_failed
job_execution_failed
job_invalid
resource_allocation_failed
resource_limit_reached
mutex_error
deadlock_detected
condition_variable_error
io_error
file_not_found
Definition at line 56 of file error_handling.h.
error_code [2/2]
enum class kcenon::thread::error_code strong
Enumerator
success
unknown_error
operation_canceled
operation_timeout
not_implemented
invalid_argument
thread_already_running
thread_not_running
thread_start_failure
thread_join_failure
queue_full
queue_empty
queue_stopped
job_creation_failed
job_execution_failed
job_invalid
resource_allocation_failed
resource_limit_reached
mutex_error
deadlock_detected
condition_variable_error
io_error
file_not_found
success
unknown_error
operation_canceled
operation_timeout
not_implemented
invalid_argument
thread_already_running
thread_not_running
thread_start_failure
thread_join_failure
queue_full
queue_empty
queue_stopped
job_creation_failed
job_execution_failed
job_invalid
resource_allocation_failed
resource_limit_reached
mutex_error
deadlock_detected
condition_variable_error
io_error
file_not_found
Definition at line 56 of file error_handling.h.
job_types
enum class kcenon::thread::job_types : uint8_t strong
Defines different types of jobs for a typed thread pool.
Each job in a typed thread pool can be assigned one of these types (RealTime, Batch, Background) to determine which specialized worker threads will process them. This enum uses uint8_t as its underlying type to minimize storage overhead.
Enumerator
RealTime
Real-time job requiring immediate response.
Batch
Batch processing job for throughput optimization.
Background
Background job for low-type maintenance tasks.
Definition at line 55 of file job_types.h.
log_level
enum class kcenon::thread::log_level strong
Log level enumeration.
Enumerator
critical
error
warning
info
debug
trace
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 37 of file logger_interface.h.
scheduling_policy
enum class kcenon::thread::scheduling_policy strong
Enumeration of scheduling policies.
Enumerator
fifo
First-in, first-out scheduling.
lifo
Last-in, first-out scheduling.
priority
Priority-based scheduling.
work_stealing
Work-stealing scheduling.
Definition at line 64 of file worker_policy.h.
thread_conditions
enum class kcenon::thread::thread_conditions : uint8_t strong
Enumeration of various states in a thread's lifecycle.
Represents distinct conditions that a thread may occupy during its execution lifecycle. This enum class is backed by uint8_t for compact storage.
Value Description
Created The thread object is constructed but not yet started.
Waiting The thread is started and idle, waiting for work.
Working The thread is actively processing work.
Stopping The thread is in the process of stopping its work.
Stopped The thread has fully stopped.
Enumerator
Created
Thread created but not started.
Waiting
Thread waiting for work or tasks.
Working
Thread currently processing a task.
Stopping
Thread in the process of stopping.
Stopped
Thread fully stopped.
Definition at line 63 of file thread_conditions.h.
worker_state
enum class kcenon::thread::worker_state strong
Enumeration of worker states.
Enumerator
created
Worker created but not started.
starting
Worker is starting up.
active
Worker is actively processing jobs.
idle
Worker is idle, waiting for work.
stopping
Worker is shutting down.
stopped
Worker has stopped.
Definition at line 52 of file worker_policy.h.
Function Documentation
all_types()
auto kcenon::thread::all_types (void) -> std::vector<thread_conditions> inline
Retrieves a vector containing all possible thread_conditions values.
Returns a vector containing all possible job_types values.
Returns
A std::vector of all enumerators in thread_conditions, in ascending order.
This can be useful for iteration, logging, or building UI elements that list thread states. For example:
for (auto cond : all_types()) {
    std::cout << to_string(cond) << std::endl;
}
Returns
A std::vector<job_types> with [RealTime, Batch, Background].
This function is useful when iterating over all defined types (e.g. for logging, UI selection, or testing).
Example
for (auto type : all_types()) {
    std::cout << to_string(type) << std::endl;
}
// Output:
// REALTIME
// BATCH
// BACKGROUND
Definition at line 131 of file thread_conditions.h.
References Created, Stopped, Stopping, Waiting, and Working.
create_pool_builder()
template<detail::JobType job_type = job_types> typed_thread_pool_builder< job_type > kcenon::thread::create_pool_builder ()
Convenience function to create a builder.
Returns
A new thread pool builder instance
Definition at line 196 of file pool_builder.h.
create_typed_job_queue()
template<typename job_type = job_types> auto kcenon::thread::create_typed_job_queue (typename adaptive_typed_job_queue_t< job_type >::queue_strategy strategy = adaptive_typed_job_queue_t< job_type >::queue_strategy::AUTO_DETECT, size_t max_threads = 128) -> std::shared_ptr< typed_job_queue_t< job_type > >
Factory function to create appropriate typed job queue.
Parameters
strategy Queue selection strategy
max_threads Maximum number of threads (for lockfree queue)
Returns
Shared pointer to created queue
create_typed_job_queue< job_types >()
template auto kcenon::thread::create_typed_job_queue< job_types > (adaptive_typed_job_queue_t< job_types >::queue_strategy , size_t) -> std::shared_ptr< typed_job_queue_t< job_types > >
Explicit instantiation of typed job queue factory function.
This instantiation provides the factory function for creating typed job queues with specified strategies and configurations. The factory handles queue strategy selection and initialization.
Parameters instantiated:
queue_strategy: Strategy selection (lock-free, mutex, adaptive)
size_t: Maximum queue capacity or thread count
Returns
Shared pointer to initialized typed job queue
error_code_to_string()
std::string kcenon::thread::error_code_to_string (error_code code) inline
Converts an error_code to a string representation.
Parameters
code The error code to convert
Returns
A human-readable string describing the error
Definition at line 100 of file error_handling.h.
References condition_variable_error, deadlock_detected, file_not_found, invalid_argument, io_error, job_creation_failed, job_execution_failed, job_invalid, mutex_error, not_implemented, operation_canceled, operation_timeout, queue_empty, queue_full, queue_stopped, resource_allocation_failed, resource_limit_reached, success, thread_already_running, thread_join_failure, thread_not_running, thread_start_failure, and unknown_error.
Referenced by kcenon::thread::test::TEST_F(), and kcenon::thread::error::to_string().
make_exceptional_future()
template<typename T > pool_future< T > kcenon::thread::make_exceptional_future (std::exception_ptr exception)
Create a future that is already ready with an exception.
Definition at line 230 of file future_extensions.h.
References kcenon::thread::pool_promise< T >::get_future(), and kcenon::thread::pool_promise< T >::set_exception().
make_ready_future() [1/2]
pool_future< void > kcenon::thread::make_ready_future () inline
Create a future that is already ready with void.
Definition at line 219 of file future_extensions.h.
References kcenon::thread::pool_promise< T >::get_future(), and kcenon::thread::pool_promise< T >::set_value().
make_ready_future() [2/2]
template<typename T > pool_future< std::decay_t< T > > kcenon::thread::make_ready_future (T && value)
Create a future that is already ready with a value.
Definition at line 209 of file future_extensions.h.
References kcenon::thread::pool_promise< T >::get_future(), and kcenon::thread::pool_promise< T >::set_value().
optional_error_to_result() [1/2]
result< void > kcenon::thread::optional_error_to_result (const std::optional< std::string > & error) inline
Definition at line 567 of file error_handling.h.
References unknown_error.
optional_error_to_result() [2/2]
template<typename T > result< T > kcenon::thread::optional_error_to_result (const std::optional< std::string > & error, T && value)
Definition at line 559 of file error_handling.h.
References unknown_error.
result_to_optional_error()
std::optional< std::string > kcenon::thread::result_to_optional_error (const result< void > & res) inline
Definition at line 575 of file error_handling.h.
result_to_pair()
template<typename T > std::pair< std::optional< T >, std::optional< std::string > > kcenon::thread::result_to_pair (const result< T > & res)
Definition at line 583 of file error_handling.h.
to_string() [1/4]
constexpr std::string_view kcenon::thread::to_string (job_types job_type) constexpr
Converts a job_types value to its corresponding string representation.
Parameters
job_type The job_types value to convert.
Returns
A std::string_view containing one of "REALTIME", "BATCH", "BACKGROUND", or "UNKNOWN" if job_type is out of expected range.
Example
auto p = job_types::RealTime;
std::string_view sv = to_string(p); // "REALTIME"
Definition at line 104 of file job_types.h.
References kcenon::thread::job_detail::job_type_count, and kcenon::thread::job_detail::job_type_strings.
to_string() [2/4]
constexpr const char * kcenon::thread::to_string (scheduling_policy policy) constexpr
Convert scheduling policy to string representation.
Definition at line 167 of file worker_policy.h.
References fifo, lifo, priority, and work_stealing.
to_string() [3/4]
constexpr std::string_view kcenon::thread::to_string (thread_conditions condition) constexpr
Converts a thread_conditions value to its corresponding string representation.
Parameters
condition The thread_conditions value to convert.
Returns
A std::string_view representing the condition name. If the value is out of range, returns "UNKNOWN".
Example:
auto state = thread_conditions::Working;
auto name = to_string(state); // "working"
Definition at line 111 of file thread_conditions.h.
References kcenon::thread::job_detail::thread_conditions_count, and kcenon::thread::job_detail::thread_conditions_strings.
Referenced by fmt::formatter< kcenon::thread::thread_conditions >::format().
to_string() [4/4]
constexpr const char * kcenon::thread::to_string (worker_state state) constexpr
Convert worker state to string representation.
Definition at line 152 of file worker_policy.h.
References active, created, idle, starting, stopped, and stopping.
wait_for_all()
template<typename... Futures> void kcenon::thread::wait_for_all (Futures &... futures)
Wait for all futures to complete.
Definition at line 241 of file future_extensions.h.
wait_for_any()
template<typename... Futures> size_t kcenon::thread::wait_for_any (Futures &... futures)
Wait for any future to complete.
Definition at line 249 of file future_extensions.h.