Messaging System: libraries/thread_system/unittest/thread_base_test/simple_mpmc_test.cpp File Reference
simple_mpmc_test.cpp File Reference
#include "gtest/gtest.h"
#include "lockfree/queues/lockfree_job_queue.h"
#include "jobs/callback_job.h"
#include <thread>
Functions
TEST (SimpleMPMCTest, CreateDestroy)
TEST (SimpleMPMCTest, SingleEnqueue)
TEST (SimpleMPMCTest, SingleEnqueueDequeue)
TEST (SimpleMPMCTest, MultipleQueues)
TEST (SimpleMPMCTest, ThreadAccess)
Function Documentation
TEST() [1/5]
TEST (SimpleMPMCTest , CreateDestroy)
Definition at line 43 of file simple_mpmc_test.cpp.
TEST() [2/5]
TEST (SimpleMPMCTest , MultipleQueues)
Definition at line 78 of file simple_mpmc_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), and thread_module::lockfree_job_queue::enqueue().
TEST() [3/5]
TEST (SimpleMPMCTest , SingleEnqueue)
Definition at line 49 of file simple_mpmc_test.cpp.
References thread_module::lockfree_job_queue::enqueue().
TEST() [4/5]
TEST (SimpleMPMCTest , SingleEnqueueDequeue)
Definition at line 62 of file simple_mpmc_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), and thread_module::lockfree_job_queue::enqueue().
TEST() [5/5]
TEST (SimpleMPMCTest , ThreadAccess)
Definition at line 96 of file simple_mpmc_test.cpp.
References thread_module::lockfree_job_queue::enqueue().