Messaging System: monitoring_system::jaeger_exporter Class Reference
monitoring_system::jaeger_exporter Class Reference
Jaeger trace exporter implementation.
#include <trace_exporters.h>
Public Member Functions
jaeger_exporter (const trace_export_config &config)
jaeger_span_data convert_span (const trace_span &span) const
Convert internal span to Jaeger format.
result_void export_spans (const std::vector< trace_span > &spans) override
Export a batch of spans.
result_void flush () override
Flush any pending spans.
result_void shutdown () override
Shutdown the exporter.
std::unordered_map< std::string, std::size_t > get_stats () const override
Get exporter statistics.
Public Member Functions inherited from monitoring_system::trace_exporter_interface
virtual ~trace_exporter_interface ()=default
Detailed Description
Jaeger trace exporter implementation.
Definition at line 183 of file trace_exporters.h.
Constructor & Destructor Documentation
jaeger_exporter()
monitoring_system::jaeger_exporter::jaeger_exporter (const trace_export_config & config) inline explicit
Definition at line 191 of file trace_exporters.h.
Member Function Documentation
convert_span()
jaeger_span_data monitoring_system::jaeger_exporter::convert_span (const trace_span & span) const inline
Convert internal span to Jaeger format.
Definition at line 197 of file trace_exporters.h.
References monitoring_system::jaeger_span_data::duration, monitoring_system::jaeger_span_data::operation_name, monitoring_system::jaeger_span_data::parent_span_id, monitoring_system::jaeger_span_data::process_tags, monitoring_system::trace_export_config::service_name, monitoring_system::jaeger_span_data::service_name, monitoring_system::jaeger_span_data::span_id, monitoring_system::jaeger_span_data::start_time, monitoring_system::jaeger_span_data::tags, and monitoring_system::jaeger_span_data::trace_id.
Referenced by export_spans(), and TEST_F().
export_spans()
result_void monitoring_system::jaeger_exporter::export_spans (const std::vector< trace_span > & spans) inline override virtual
Export a batch of spans.
Implements monitoring_system::trace_exporter_interface.
Definition at line 223 of file trace_exporters.h.
References convert_span(), monitoring_system::trace_export_config::format, monitoring_system::invalid_configuration, monitoring_system::jaeger_grpc, monitoring_system::jaeger_thrift, and monitoring_system::operation_failed.
Referenced by TEST_F(), TEST_F(), and TEST_F().
flush()
result_void monitoring_system::jaeger_exporter::flush () inline override virtual
Flush any pending spans.
Implements monitoring_system::trace_exporter_interface.
Definition at line 259 of file trace_exporters.h.
Referenced by shutdown(), and TEST_F().
get_stats()
std::unordered_map< std::string, std::size_t > monitoring_system::jaeger_exporter::get_stats () const inline override virtual
Get exporter statistics.
Implements monitoring_system::trace_exporter_interface.
Definition at line 268 of file trace_exporters.h.
Referenced by TEST_F(), and TEST_F().
shutdown()
result_void monitoring_system::jaeger_exporter::shutdown () inline override virtual
Shutdown the exporter.
Implements monitoring_system::trace_exporter_interface.
Definition at line 264 of file trace_exporters.h.
References flush().
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/exporters/trace_exporters.h