Messaging System: monitoring_system::adaptive_strategy Class Reference
monitoring_system::adaptive_strategy Class Reference
Adaptive buffering strategy based on system load.
#include <buffering_strategy.h>
Public Member Functions
adaptive_strategy (const buffering_config &config)
result_void add_metric (buffered_metric &&metric) override
Add metric to buffer.
result< std::vector< buffered_metric > > flush () override
Flush buffer contents.
bool should_flush () const override
Check if flush is needed.
size_t size () const override
Get current buffer size.
const buffer_statistics & get_statistics () const override
Get buffer statistics.
void clear () override
Clear buffer.
const buffering_config & get_config () const override
Get configuration.
Public Member Functions inherited from monitoring_system::buffer_strategy_interface
virtual ~buffer_strategy_interface ()=default
Detailed Description
Adaptive buffering strategy based on system load.
Definition at line 730 of file buffering_strategy.h.
Constructor & Destructor Documentation
adaptive_strategy()
monitoring_system::adaptive_strategy::adaptive_strategy (const buffering_config & config) inline explicit
Definition at line 776 of file buffering_strategy.h.
References monitoring_system::buffering_config::max_buffer_size, and monitoring_system::buffering_config::strategy.
Member Function Documentation
add_metric()
result_void monitoring_system::adaptive_strategy::add_metric (buffered_metric && metric) inline override virtual
Add metric to buffer.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 782 of file buffering_strategy.h.
References monitoring_system::buffering_config::adaptive_check_interval, monitoring_system::buffer_statistics::forced_flushes, monitoring_system::buffer_statistics::items_dropped_overflow, monitoring_system::buffering_config::load_factor_threshold, monitoring_system::buffering_config::max_buffer_size, and monitoring_system::buffer_statistics::total_items_buffered.
Referenced by TEST_F().
clear()
void monitoring_system::adaptive_strategy::clear () inline override virtual
Clear buffer.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 858 of file buffering_strategy.h.
flush()
result< std::vector< buffered_metric > > monitoring_system::adaptive_strategy::flush () inline override virtual
Flush buffer contents.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 814 of file buffering_strategy.h.
References monitoring_system::make_success(), monitoring_system::buffer_statistics::total_flushes, and monitoring_system::buffer_statistics::total_items_flushed.
get_config()
const buffering_config & monitoring_system::adaptive_strategy::get_config () const inline override virtual
Get configuration.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 863 of file buffering_strategy.h.
get_statistics()
const buffer_statistics & monitoring_system::adaptive_strategy::get_statistics () const inline override virtual
Get buffer statistics.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 854 of file buffering_strategy.h.
should_flush()
bool monitoring_system::adaptive_strategy::should_flush () const inline override virtual
Check if flush is needed.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 837 of file buffering_strategy.h.
References monitoring_system::buffering_config::flush_threshold_size, and monitoring_system::buffering_config::load_factor_threshold.
Referenced by TEST_F().
size()
size_t monitoring_system::adaptive_strategy::size () const inline override virtual
Get current buffer size.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 849 of file buffering_strategy.h.
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/buffering_strategy.h