Messaging System: MemoryMonitor Class Reference
MemoryMonitor Class Reference
Memory usage monitor.
Classes
struct MemoryStats
Public Member Functions
MemoryMonitor ()
~MemoryMonitor ()
size_t get_peak_memory () const
size_t get_current_memory () const
Static Public Member Functions
static MemoryStats get_current_memory ()
static MemoryStats get_current_memory ()
Detailed Description
Memory usage monitor.
Definition at line 94 of file stress_test.cpp.
Constructor & Destructor Documentation
MemoryMonitor()
MemoryMonitor::MemoryMonitor () inline
Definition at line 96 of file stress_test.cpp.
~MemoryMonitor()
MemoryMonitor::~MemoryMonitor () inline
Definition at line 100 of file stress_test.cpp.
Member Function Documentation
get_current_memory() [1/3]
static MemoryStats MemoryMonitor::get_current_memory () inline static
Definition at line 105 of file memory_benchmark.cpp.
References kcenon::thread::info, MemoryMonitor::MemoryStats::peak_size, MemoryMonitor::MemoryStats::resident_size, and MemoryMonitor::MemoryStats::virtual_size.
get_current_memory() [2/3]
static MemoryStats MemoryMonitor::get_current_memory () inline static
Definition at line 105 of file memory_benchmark.cpp.
References kcenon::thread::info.
get_current_memory() [3/3]
size_t MemoryMonitor::get_current_memory () const inline
Definition at line 108 of file stress_test.cpp.
Referenced by BM_BaseMemory(), BM_JobQueueMemory(), BM_MemoryAllocationPattern(), BM_ThreadPoolMemory(), BM_TypedThreadPoolMemory(), and run_stress_test().
get_peak_memory()
size_t MemoryMonitor::get_peak_memory () const inline
Definition at line 107 of file stress_test.cpp.
Referenced by run_stress_test().
The documentation for this class was generated from the following files:
libraries/network_system/tests/stress/stress_test.cpp
libraries/thread_system/benchmarks/thread_pool_benchmarks/memory_benchmark.cpp
libraries/thread_system/tests/benchmarks/thread_pool_benchmarks/memory_benchmark.cpp