Messaging System: libraries/logger_system/samples/distributed_logging_demo.cpp File Reference
distributed_logging_demo.cpp File Reference
#include <logger/logger.h>
#include <logger/writers/console_writer.h>
#include <logger/writers/network_writer.h>
#include <logger/server/log_server.h>
#include <logger/analysis/log_analyzer.h>
#include <iostream>
#include <thread>
#include <chrono>
#include <random>
#include <atomic>
Functions
void simulate_client (int client_id, const std::string &server_host, uint16_t server_port)
int main ()
Function Documentation
main()
int main ()
Definition at line 67 of file distributed_logging_demo.cpp.
References logger_module::log_server::network_log_entry::parsed_fields, logger_module::log_server::network_log_entry::raw_data, logger_module::log_server::network_log_entry::received_time, simulate_client(), and logger_module::log_server::network_log_entry::source_address.
simulate_client()
void simulate_client (int client_id, const std::string & server_host, uint16_t server_port)
Definition at line 23 of file distributed_logging_demo.cpp.
References logger_module::logger::add_writer(), logger_module::logger::flush(), logger_module::logger::log(), logger_module::logger::start(), and logger_module::logger::stop().
Referenced by main().