Messaging System: libraries/network_system/tests/benchmark_tests.cpp File Reference
benchmark_tests.cpp File Reference
#include <benchmark/benchmark.h>
#include <memory>
#include <thread>
#include <vector>
#include <atomic>
#include <chrono>
#include <random>
#include <sstream>
#include "../network.h"
#include <container.h>
Classes
class NetworkBenchmarkFixture
Functions
static unsigned short FindAvailablePort (unsigned short start=6000)
BENCHMARK_DEFINE_F (NetworkBenchmarkFixture, BM_ClientConnection)(benchmark
BENCHMARK_REGISTER_F (NetworkBenchmarkFixture, BM_ClientConnection)
static void BM_MessageCreation (benchmark::State &state)
RangeMultiplier (10) -> Range(1, 1000)
BENCHMARK_DEFINE_F (NetworkBenchmarkFixture, BM_MessageSending)(benchmark
BENCHMARK_DEFINE_F (NetworkBenchmarkFixture, BM_RoundTripLatency)(benchmark
UseManualTime ()
static void BM_ConcurrentConnections (benchmark::State &state)
BENCHMARK_DEFINE_F (NetworkBenchmarkFixture, BM_MessageThroughput)(benchmark
static void BM_MessageSerialization (benchmark::State &state)
static void BM_MessageDeserialization (benchmark::State &state)
static void BM_ClientAllocation (benchmark::State &state)
BENCHMARK (BM_ClientAllocation)
static void BM_MultiThreadedStress (benchmark::State &state)
static void BM_CompressionEfficiency (benchmark::State &state)
int main (int argc, char **argv)
Variables
static std::shared_ptr< messaging_server > g_benchmark_server
static unsigned short g_server_port = 0
Function Documentation
BENCHMARK()
BENCHMARK (BM_ClientAllocation)
BENCHMARK_DEFINE_F() [1/4]
BENCHMARK_DEFINE_F (NetworkBenchmarkFixture , BM_ClientConnection)
Definition at line 98 of file benchmark_tests.cpp.
References g_server_port.
BENCHMARK_DEFINE_F() [2/4]
BENCHMARK_DEFINE_F (NetworkBenchmarkFixture , BM_MessageSending)
Definition at line 143 of file benchmark_tests.cpp.
References g_server_port.
BENCHMARK_DEFINE_F() [3/4]
BENCHMARK_DEFINE_F (NetworkBenchmarkFixture , BM_MessageThroughput)
Definition at line 299 of file benchmark_tests.cpp.
References g_server_port.
BENCHMARK_DEFINE_F() [4/4]
BENCHMARK_DEFINE_F (NetworkBenchmarkFixture , BM_RoundTripLatency)
Definition at line 192 of file benchmark_tests.cpp.
References g_server_port.
BENCHMARK_REGISTER_F()
BENCHMARK_REGISTER_F (NetworkBenchmarkFixture , BM_ClientConnection)
BM_ClientAllocation()
static void BM_ClientAllocation (benchmark::State & state) static
Definition at line 418 of file benchmark_tests.cpp.
BM_CompressionEfficiency()
static void BM_CompressionEfficiency (benchmark::State & state) static
Definition at line 495 of file benchmark_tests.cpp.
References g_server_port.
BM_ConcurrentConnections()
static void BM_ConcurrentConnections (benchmark::State & state) static
Definition at line 258 of file benchmark_tests.cpp.
References g_server_port.
BM_MessageCreation()
static void BM_MessageCreation (benchmark::State & state) static
Definition at line 120 of file benchmark_tests.cpp.
BM_MessageDeserialization()
static void BM_MessageDeserialization (benchmark::State & state) static
Definition at line 389 of file benchmark_tests.cpp.
References container_module::value_container::deserialize().
BM_MessageSerialization()
static void BM_MessageSerialization (benchmark::State & state) static
Definition at line 356 of file benchmark_tests.cpp.
BM_MultiThreadedStress()
static void BM_MultiThreadedStress (benchmark::State & state) static
Definition at line 434 of file benchmark_tests.cpp.
References g_server_port.
FindAvailablePort()
static unsigned short FindAvailablePort (unsigned short start = 6000) static
Definition at line 55 of file benchmark_tests.cpp.
Referenced by main(), NetworkBenchmarkFixture::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
main()
int main (int argc, char ** argv)
Definition at line 545 of file benchmark_tests.cpp.
References FindAvailablePort(), g_benchmark_server, and g_server_port.
RangeMultiplier()
RangeMultiplier (10) -> Range(1, 1000)
UseManualTime()
UseManualTime ()
Variable Documentation
g_benchmark_server
std::shared_ptr<messaging_server> g_benchmark_server static
Definition at line 51 of file benchmark_tests.cpp.
Referenced by main(), and NetworkBenchmarkFixture::SetUp().
g_server_port
unsigned short g_server_port = 0 static
Definition at line 52 of file benchmark_tests.cpp.
Referenced by BENCHMARK_DEFINE_F(), BENCHMARK_DEFINE_F(), BENCHMARK_DEFINE_F(), BENCHMARK_DEFINE_F(), BM_CompressionEfficiency(), BM_ConcurrentConnections(), BM_MultiThreadedStress(), main(), and NetworkBenchmarkFixture::SetUp().