Messaging System: database::security::audit_logger Class Reference
database::security::audit_logger Class Reference
Security audit logging system.
#include <secure_connection.h>
Public Member Functions
void log_database_access (const std::string &user_id, const std::string &session_id, const std::string &operation, const std::string &table, const std::string &query_hash, bool success, const std::string &error_message="")
void log_authentication_event (const std::string &user_id, const std::string &client_ip, bool success, const std::string &method)
void log_authorization_failure (const std::string &user_id, const std::string &operation, const std::string &table, const std::string &reason)
std::vector< audit_log_entry > get_audit_logs (std::chrono::hours window) const
std::vector< audit_log_entry > get_user_audit_logs (const std::string &user_id, std::chrono::hours window) const
std::string generate_security_report (std::chrono::hours window) const
std::vector< std::string > detect_suspicious_activity (std::chrono::hours window) const
void set_log_retention_period (std::chrono::hours retention)
void cleanup_old_logs ()
bool export_logs_to_file (const std::string &filename) const
Static Public Member Functions
static audit_logger & instance ()
Detailed Description
Security audit logging system.
Definition at line 268 of file secure_connection.h.
Member Function Documentation
cleanup_old_logs()
void database::security::audit_logger::cleanup_old_logs ()
detect_suspicious_activity()
std::vector< std::string > database::security::audit_logger::detect_suspicious_activity (std::chrono::hours window) const
export_logs_to_file()
bool database::security::audit_logger::export_logs_to_file (const std::string & filename) const
generate_security_report()
std::string database::security::audit_logger::generate_security_report (std::chrono::hours window) const
get_audit_logs()
std::vector< audit_log_entry > database::security::audit_logger::get_audit_logs (std::chrono::hours window) const
get_user_audit_logs()
std::vector< audit_log_entry > database::security::audit_logger::get_user_audit_logs (const std::string & user_id, std::chrono::hours window) const
instance()
static audit_logger & database::security::audit_logger::instance () static
Referenced by demonstrate_audit_logging(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
log_authentication_event()
void database::security::audit_logger::log_authentication_event (const std::string & user_id, const std::string & client_ip, bool success, const std::string & method)
log_authorization_failure()
void database::security::audit_logger::log_authorization_failure (const std::string & user_id, const std::string & operation, const std::string & table, const std::string & reason)
log_database_access()
void database::security::audit_logger::log_database_access (const std::string & user_id, const std::string & session_id, const std::string & operation, const std::string & table, const std::string & query_hash, bool success, const std::string & error_message = "")
set_log_retention_period()
void database::security::audit_logger::set_log_retention_period (std::chrono::hours retention)
The documentation for this class was generated from the following file:
libraries/database_system/database/security/secure_connection.h