Messaging System: logger_module::encrypted_writer Class Reference
logger_module::encrypted_writer Class Reference
Writer that encrypts log data before passing to another writer.
#include <encrypted_writer.h>
Public Types
enum class encryption_type { aes_256_cbc , aes_256_gcm , chacha20_poly1305 }
Encryption algorithm type.
Public Member Functions
encrypted_writer (std::unique_ptr< base_writer > wrapped_writer, const std::vector< uint8_t > &key, encryption_type type=encryption_type::aes_256_gcm)
Constructor.
~encrypted_writer () override
Destructor.
bool write (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write encrypted log entry.
void flush () override
Flush wrapped writer.
std::string get_name () const override
Get writer name.
Public Member Functions inherited from logger_module::base_writer
virtual ~base_writer ()=default
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get color setting.
Static Public Member Functions
static std::vector< uint8_t > generate_key (size_t size=32)
Generate random encryption key.
static bool save_key (const std::vector< uint8_t > &key, const std::string &filename)
Save key to file (securely)
static std::vector< uint8_t > load_key (const std::string &filename)
Load key from file.
Additional Inherited Members
Protected Member Functions inherited from logger_module::base_writer
std::string format_log_entry (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
Format a log entry to string.
std::string level_to_string (thread_module::log_level level) const
Convert log level to string.
std::string level_to_color (thread_module::log_level level) const
Get ANSI color code for log level.
Detailed Description
Writer that encrypts log data before passing to another writer.
Definition at line 21 of file encrypted_writer.h.
Member Enumeration Documentation
encryption_type
enum class logger_module::encrypted_writer::encryption_type strong
Encryption algorithm type.
Enumerator
aes_256_cbc
aes_256_gcm
chacha20_poly1305
Definition at line 26 of file encrypted_writer.h.
Constructor & Destructor Documentation
encrypted_writer()
logger_module::encrypted_writer::encrypted_writer (std::unique_ptr< base_writer > wrapped_writer, const std::vector< uint8_t > & key, encryption_type type = encryption_type::aes_256_gcm)
Constructor.
Parameters
wrapped_writer The writer to wrap with encryption
key Encryption key (must be 32 bytes for AES-256)
type Encryption algorithm to use
Definition at line 17 of file encrypted_writer.cpp.
References generate_key().
~encrypted_writer()
logger_module::encrypted_writer::~encrypted_writer () override default
Destructor.
Member Function Documentation
flush()
void logger_module::encrypted_writer::flush () override virtual
Flush wrapped writer.
Implements logger_module::base_writer.
Definition at line 62 of file encrypted_writer.cpp.
generate_key()
std::vector< uint8_t > logger_module::encrypted_writer::generate_key (size_t size = 32) static
Generate random encryption key.
Parameters
size Key size in bytes (32 for AES-256)
Returns
Random key
Definition at line 66 of file encrypted_writer.cpp.
Referenced by encrypted_writer(), test_combined_security(), test_encryption(), and TEST_F().
get_name()
std::string logger_module::encrypted_writer::get_name () const inline override virtual
Get writer name.
Implements logger_module::base_writer.
Definition at line 65 of file encrypted_writer.h.
load_key()
std::vector< uint8_t > logger_module::encrypted_writer::load_key (const std::string & filename) static
Load key from file.
Parameters
filename File path
Returns
The loaded key (empty if failed)
Definition at line 97 of file encrypted_writer.cpp.
Referenced by TEST_F().
save_key()
bool logger_module::encrypted_writer::save_key (const std::vector< uint8_t > & key, const std::string & filename) static
Save key to file (securely)
Parameters
key The key to save
filename File path
Returns
true if saved successfully
Definition at line 79 of file encrypted_writer.cpp.
Referenced by test_encryption(), and TEST_F().
write()
bool logger_module::encrypted_writer::write (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write encrypted log entry.
Implements logger_module::base_writer.
Definition at line 35 of file encrypted_writer.cpp.
References logger_module::base_writer::format_log_entry().
The documentation for this class was generated from the following files:
libraries/logger_system/sources/logger/writers/encrypted_writer.h
libraries/logger_system/sources/logger/writers/encrypted_writer.cpp