Messaging System: libraries/thread_system/benchmarks/thread_pool_benchmarks/comparison_benchmark.cpp File Reference
comparison_benchmark.cpp File Reference
Comparative benchmarks against standard library and common patterns.
#include <benchmark/benchmark.h>
#include <chrono>
#include <vector>
#include <thread>
#include <future>
#include <queue>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <functional>
#include <numeric>
#include <algorithm>
#include <iomanip>
#include "../../sources/thread_pool/core/thread_pool.h"
#include "../../sources/thread_pool/workers/thread_worker.h"
#include "../../sources/typed_thread_pool/pool/typed_thread_pool.h"
#include "../../sources/typed_thread_pool/jobs/callback_typed_job.h"
#include "../../sources/utilities/core/formatter.h"
Classes
class SimpleThreadPool
struct std::formatter< TaskType >
Enumerations
enum class TaskType : int { CPU = 1 , IO = 10 }
Functions
auto create_default (const uint16_t &worker_counts) -> std::tuple< std::shared_ptr< thread_pool_module::thread_pool >, std::optional< std::string > >
template<typename Type >
auto create_priority_default (const uint16_t &worker_counts, const std::vector< Type > &types) -> std::tuple< std::shared_ptr< typed_thread_pool_module::typed_thread_pool_t< Type > >, std::optional< std::string > >
static void BM_SimpleTaskExecution_Sequential (benchmark::State &state)
Benchmark sequential task execution baseline.
Arg (100000) -> Unit(benchmark::kMillisecond)
static void BM_SimpleTaskExecution_ThreadSystem (benchmark::State &state)
Benchmark Thread System simple task execution.
static void BM_SimpleTaskExecution_StdAsync (benchmark::State &state)
Benchmark std::async simple task execution.
static void BM_SimpleTaskExecution_SimplePool (benchmark::State &state)
Benchmark simple thread pool task execution.
static void BM_ParallelComputation_Sequential (benchmark::State &state)
Benchmark sequential parallel computation baseline.
Arg (10000000) -> Unit(benchmark::kMillisecond)
static void BM_ParallelComputation_ThreadSystem (benchmark::State &state)
Benchmark Thread System parallel computation.
static void BM_ParallelComputation_StdAsync (benchmark::State &state)
Benchmark std::async parallel computation.
static void BM_IOBound_ThreadSystem_ManyWorkers (benchmark::State &state)
Benchmark Thread System I/O bound workload with many workers.
Args ({1000, 10}) -> Unit(benchmark::kMillisecond)
static void BM_IOBound_ThreadSystem_NormalWorkers (benchmark::State &state)
Benchmark Thread System I/O bound workload with normal workers.
static void BM_IOBound_StdAsync (benchmark::State &state)
Benchmark std::async I/O bound workload.
static void BM_MixedWorkload_ThreadSystem (benchmark::State &state)
Benchmark Thread System mixed CPU/IO workload.
Arg (1000) -> Unit(benchmark::kMillisecond)
static void BM_MixedWorkload_TypedThreadSystem (benchmark::State &state)
Benchmark Typed Thread System mixed workload with priority.
static void BM_MixedWorkload_StdAsync (benchmark::State &state)
Benchmark std::async mixed workload.
static void BM_TaskCreation_ThreadSystem (benchmark::State &state)
Benchmark Thread System task creation overhead.
static void BM_TaskCreation_StdAsync (benchmark::State &state)
Benchmark std::async task creation overhead.
static void BM_TaskCreation_RawLambda (benchmark::State &state)
Benchmark raw lambda creation overhead.
static void BM_MemoryUsage_Comparison (benchmark::State &state)
Benchmark memory usage comparison.
BENCHMARK_MAIN ()
Variables
static std::map< std::string, double > g_baseline_times
Detailed Description
Comparative benchmarks against standard library and common patterns.
Compares Thread System performance with:
std::async
Raw std::thread
OpenMP (if available)
Custom thread pool implementations
Definition in file comparison_benchmark.cpp.
Enumeration Type Documentation
TaskType
enum class TaskType : int strong
Enumerator
CPU
IO
Definition at line 655 of file comparison_benchmark.cpp.
Function Documentation
Arg() [1/3]
Arg (1000) -> Unit(benchmark::kMillisecond)
Arg() [2/3]
Arg (100000) -> Unit(benchmark::kMillisecond)
Arg() [3/3]
Arg (10000000) -> Unit(benchmark::kMillisecond)
Args()
Args ({1000, 10}) -> Unit(benchmark::kMillisecond)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_IOBound_StdAsync()
static void BM_IOBound_StdAsync (benchmark::State & state) static
Benchmark std::async I/O bound workload.
Definition at line 585 of file comparison_benchmark.cpp.
BM_IOBound_ThreadSystem_ManyWorkers()
static void BM_IOBound_ThreadSystem_ManyWorkers (benchmark::State & state) static
Benchmark Thread System I/O bound workload with many workers.
Definition at line 512 of file comparison_benchmark.cpp.
References create_default().
BM_IOBound_ThreadSystem_NormalWorkers()
static void BM_IOBound_ThreadSystem_NormalWorkers (benchmark::State & state) static
Benchmark Thread System I/O bound workload with normal workers.
Definition at line 549 of file comparison_benchmark.cpp.
References create_default().
BM_MemoryUsage_Comparison()
static void BM_MemoryUsage_Comparison (benchmark::State & state) static
Benchmark memory usage comparison.
This benchmark estimates memory usage for different approaches. Since we can't directly measure memory in Google Benchmark, we calculate theoretical memory usage based on object sizes.
Definition at line 840 of file comparison_benchmark.cpp.
BM_MixedWorkload_StdAsync()
static void BM_MixedWorkload_StdAsync (benchmark::State & state) static
Benchmark std::async mixed workload.
Definition at line 713 of file comparison_benchmark.cpp.
BM_MixedWorkload_ThreadSystem()
static void BM_MixedWorkload_ThreadSystem (benchmark::State & state) static
Benchmark Thread System mixed CPU/IO workload.
Definition at line 613 of file comparison_benchmark.cpp.
References create_default().
BM_MixedWorkload_TypedThreadSystem()
static void BM_MixedWorkload_TypedThreadSystem (benchmark::State & state) static
Benchmark Typed Thread System mixed workload with priority.
Definition at line 668 of file comparison_benchmark.cpp.
References CPU, and IO.
BM_ParallelComputation_Sequential()
static void BM_ParallelComputation_Sequential (benchmark::State & state) static
Benchmark sequential parallel computation baseline.
Definition at line 337 of file comparison_benchmark.cpp.
References g_baseline_times.
BM_ParallelComputation_StdAsync()
static void BM_ParallelComputation_StdAsync (benchmark::State & state) static
Benchmark std::async parallel computation.
Definition at line 429 of file comparison_benchmark.cpp.
References g_baseline_times.
BM_ParallelComputation_ThreadSystem()
static void BM_ParallelComputation_ThreadSystem (benchmark::State & state) static
Benchmark Thread System parallel computation.
Definition at line 364 of file comparison_benchmark.cpp.
References create_default(), and g_baseline_times.
BM_SimpleTaskExecution_Sequential()
static void BM_SimpleTaskExecution_Sequential (benchmark::State & state) static
Benchmark sequential task execution baseline.
Definition at line 182 of file comparison_benchmark.cpp.
References g_baseline_times.
BM_SimpleTaskExecution_SimplePool()
static void BM_SimpleTaskExecution_SimplePool (benchmark::State & state) static
Benchmark simple thread pool task execution.
Definition at line 274 of file comparison_benchmark.cpp.
References g_baseline_times, and SimpleThreadPool::submit().
BM_SimpleTaskExecution_StdAsync()
static void BM_SimpleTaskExecution_StdAsync (benchmark::State & state) static
Benchmark std::async simple task execution.
Definition at line 241 of file comparison_benchmark.cpp.
References g_baseline_times.
BM_SimpleTaskExecution_ThreadSystem()
static void BM_SimpleTaskExecution_ThreadSystem (benchmark::State & state) static
Benchmark Thread System simple task execution.
Definition at line 205 of file comparison_benchmark.cpp.
References create_default(), and g_baseline_times.
BM_TaskCreation_RawLambda()
static void BM_TaskCreation_RawLambda (benchmark::State & state) static
Benchmark raw lambda creation overhead.
Definition at line 810 of file comparison_benchmark.cpp.
BM_TaskCreation_StdAsync()
static void BM_TaskCreation_StdAsync (benchmark::State & state) static
Benchmark std::async task creation overhead.
Definition at line 784 of file comparison_benchmark.cpp.
BM_TaskCreation_ThreadSystem()
static void BM_TaskCreation_ThreadSystem (benchmark::State & state) static
Benchmark Thread System task creation overhead.
Definition at line 751 of file comparison_benchmark.cpp.
References create_default().
create_default()
auto create_default (const uint16_t & worker_counts) -> std::tuple<std::shared_ptr<thread_pool_module::thread_pool>, std::optional<std::string>>
Definition at line 68 of file comparison_benchmark.cpp.
References utility_module::formatter::format().
Referenced by BM_IOBound_ThreadSystem_ManyWorkers(), BM_IOBound_ThreadSystem_NormalWorkers(), BM_MixedWorkload_ThreadSystem(), BM_ParallelComputation_ThreadSystem(), BM_SimpleTaskExecution_ThreadSystem(), and BM_TaskCreation_ThreadSystem().
create_priority_default()
template<typename Type > auto create_priority_default (const uint16_t & worker_counts, const std::vector< Type > & types) -> std::tuple<std::shared_ptr<typed_thread_pool_module::typed_thread_pool_t<Type>>, std::optional<std::string>>
Definition at line 96 of file comparison_benchmark.cpp.
References thread_module::result< T >::get_error(), and thread_module::error::message().
Variable Documentation
g_baseline_times
std::map<std::string, double> g_baseline_times static
Definition at line 177 of file comparison_benchmark.cpp.
Referenced by BM_ParallelComputation_Sequential(), BM_ParallelComputation_StdAsync(), BM_ParallelComputation_ThreadSystem(), BM_SimpleTaskExecution_Sequential(), BM_SimpleTaskExecution_SimplePool(), BM_SimpleTaskExecution_StdAsync(), and BM_SimpleTaskExecution_ThreadSystem().