Messaging System: libraries/monitoring_system/samples/optimization_demo.cpp File Reference
optimization_demo.cpp File Reference
#include <monitoring/multi_process_monitoring.h>
#include <monitoring/performance_optimizer.h>
#include <monitoring/analysis_dashboard.h>
#include <thread>
#include <iostream>
#include <iomanip>
#include <chrono>
#include <random>
#include <csignal>
#include <atomic>
Classes
class load_simulator
class performance_comparator
Functions
void signal_handler (int signal)
void visualize_scaling_decision (const auto_scaler::scaling_decision &decision)
int main ()
Variables
std::atomic< bool > running {true}
Function Documentation
main()
int main ()
Definition at line 189 of file optimization_demo.cpp.
References monitoring_interface::system_metrics::active_threads, performance_comparator::add_optimized_sample(), performance_comparator::add_unoptimized_sample(), load_simulator::advance(), monitoring_module::performance_optimizer::optimization_config::batch_size, monitoring_interface::metrics_snapshot::capture_time, monitoring_module::performance_optimizer::optimization_config::compression_threshold, monitoring_module::auto_scaler::scaling_policy::cooldown, monitoring_module::auto_scaler::scaling_policy::cpu_threshold_down, monitoring_module::auto_scaler::scaling_policy::cpu_threshold_up, monitoring_interface::system_metrics::cpu_usage_percent, monitoring_module::performance_optimizer::optimization_config::enable_adaptive_sampling, monitoring_module::performance_optimizer::optimization_config::enable_batching, monitoring_module::performance_optimizer::optimization_config::enable_compression, monitoring_module::distributed_aggregator::aggregation_config::enable_parallel_aggregation, monitoring_module::performance_optimizer::optimization_config::enable_tiered_storage, load_simulator::get_cpu_load(), load_simulator::get_memory_usage(), load_simulator::gradual, monitoring_interface::system_metrics::memory_usage_bytes, monitoring_interface::process_identifier::pid, performance_comparator::print_comparison(), running, signal_handler(), monitoring_interface::metrics_snapshot::system, visualize_scaling_decision(), and monitoring_module::distributed_aggregator::aggregation_config::worker_threads.
signal_handler()
void signal_handler (int signal)
Definition at line 24 of file optimization_demo.cpp.
References running.
Referenced by main().
visualize_scaling_decision()
void visualize_scaling_decision (const auto_scaler::scaling_decision & decision)
Definition at line 148 of file optimization_demo.cpp.
References monitoring_module::auto_scaler::scaling_decision::confidence, monitoring_module::auto_scaler::scaling_decision::reason, monitoring_module::auto_scaler::scaling_decision::recommended_action, and monitoring_module::auto_scaler::scaling_decision::recommended_resources.
Referenced by main().
Variable Documentation
running
std::atomic<bool> running {true}
Definition at line 22 of file optimization_demo.cpp.
Referenced by main(), and signal_handler().