Messaging System: kcenon::thread::cancellation_token Class Reference
kcenon::thread::cancellation_token Class Reference
Provides a mechanism for cooperative cancellation of operations.
#include <cancellation_token.h>
Public Member Functions
cancellation_token ()
cancellation_token (const cancellation_token &)=default
cancellation_token & operator= (const cancellation_token &)=default
cancellation_token (cancellation_token &&)=default
cancellation_token & operator= (cancellation_token &&)=default
void cancel ()
Cancels the operation.
bool is_cancelled () const
Checks if the token has been canceled.
void throw_if_cancelled () const
Throws an exception if the token has been canceled.
void register_callback (std::function< void()> callback)
Registers a callback to be invoked when the token is canceled.
cancellation_token ()
cancellation_token (const cancellation_token &)=default
cancellation_token & operator= (const cancellation_token &)=default
cancellation_token (cancellation_token &&)=default
cancellation_token & operator= (cancellation_token &&)=default
void cancel ()
Cancels the operation.
bool is_cancelled () const
Checks if the token has been canceled.
void throw_if_cancelled () const
Throws an exception if the token has been canceled.
void register_callback (std::function< void()> callback)
Registers a callback to be invoked when the token is canceled.
Static Public Member Functions
static cancellation_token create ()
Creates a new cancellation token.
static cancellation_token create_linked (std::initializer_list< cancellation_token > tokens)
Creates a linked token that is canceled when any of the parent tokens are canceled.
static cancellation_token create ()
Creates a new cancellation token.
static cancellation_token create_linked (std::initializer_list< cancellation_token > tokens)
Creates a linked token that is canceled when any of the parent tokens are canceled.
Detailed Description
Provides a mechanism for cooperative cancellation of operations.
Cancellation tokens allow long-running operations to be gracefully canceled. They are particularly useful for worker threads that need to be notified when their work should be aborted.
Definition at line 55 of file cancellation_token.h.
Constructor & Destructor Documentation
cancellation_token() [1/6]
kcenon::thread::cancellation_token::cancellation_token () inline
Definition at line 72 of file cancellation_token.h.
Referenced by create().
cancellation_token() [2/6]
kcenon::thread::cancellation_token::cancellation_token (const cancellation_token &) default
cancellation_token() [3/6]
kcenon::thread::cancellation_token::cancellation_token (cancellation_token &&) default
cancellation_token() [4/6]
kcenon::thread::cancellation_token::cancellation_token () inline
Definition at line 72 of file cancellation_token.h.
cancellation_token() [5/6]
kcenon::thread::cancellation_token::cancellation_token (const cancellation_token &) default
cancellation_token() [6/6]
kcenon::thread::cancellation_token::cancellation_token (cancellation_token &&) default
Member Function Documentation
cancel() [1/2]
void kcenon::thread::cancellation_token::cancel () inline
Cancels the operation.
Sets the token to the canceled state and invokes all registered callbacks.
Note
This method is thread-safe and guarantees callbacks are invoked exactly once.
Definition at line 132 of file cancellation_token.h.
cancel() [2/2]
void kcenon::thread::cancellation_token::cancel () inline
Cancels the operation.
Sets the token to the canceled state and invokes all registered callbacks.
Note
This method is thread-safe and guarantees callbacks are invoked exactly once.
Definition at line 132 of file cancellation_token.h.
create() [1/2]
static cancellation_token kcenon::thread::cancellation_token::create () inline static
Creates a new cancellation token.
Returns
A new cancellation token
Definition at line 84 of file cancellation_token.h.
References cancellation_token().
Referenced by BM_CancellationTokenOperations(), and create_linked().
create() [2/2]
static cancellation_token kcenon::thread::cancellation_token::create () inline static
Creates a new cancellation token.
Returns
A new cancellation token
Definition at line 84 of file cancellation_token.h.
References cancellation_token().
create_linked() [1/2]
static cancellation_token kcenon::thread::cancellation_token::create_linked (std::initializer_list< cancellation_token > tokens) inline static
Creates a linked token that is canceled when any of the parent tokens are canceled.
Parameters
tokens The parent tokens
Returns
A new token linked to the parents
Note
Uses weak_ptr to avoid circular references and memory leaks
Definition at line 95 of file cancellation_token.h.
References create().
create_linked() [2/2]
static cancellation_token kcenon::thread::cancellation_token::create_linked (std::initializer_list< cancellation_token > tokens) inline static
Creates a linked token that is canceled when any of the parent tokens are canceled.
Parameters
tokens The parent tokens
Returns
A new token linked to the parents
Note
Uses weak_ptr to avoid circular references and memory leaks
Definition at line 95 of file cancellation_token.h.
References create().
is_cancelled() [1/2]
bool kcenon::thread::cancellation_token::is_cancelled () const inline
Checks if the token has been canceled.
Returns
true if the token has been canceled, false otherwise
Definition at line 155 of file cancellation_token.h.
Referenced by throw_if_cancelled().
is_cancelled() [2/2]
bool kcenon::thread::cancellation_token::is_cancelled () const inline
Checks if the token has been canceled.
Returns
true if the token has been canceled, false otherwise
Definition at line 155 of file cancellation_token.h.
operator=() [1/4]
cancellation_token & kcenon::thread::cancellation_token::operator= (cancellation_token &&) default
operator=() [2/4]
cancellation_token & kcenon::thread::cancellation_token::operator= (cancellation_token &&) default
operator=() [3/4]
cancellation_token & kcenon::thread::cancellation_token::operator= (const cancellation_token &) default
operator=() [4/4]
cancellation_token & kcenon::thread::cancellation_token::operator= (const cancellation_token &) default
register_callback() [1/2]
void kcenon::thread::cancellation_token::register_callback (std::function< void()> callback) inline
Registers a callback to be invoked when the token is canceled.
Parameters
callback The function to call when the token is canceled
If the token is already canceled, the callback is invoked immediately.
Note
This method is thread-safe and guarantees the callback is called exactly once.
Definition at line 177 of file cancellation_token.h.
register_callback() [2/2]
void kcenon::thread::cancellation_token::register_callback (std::function< void()> callback) inline
Registers a callback to be invoked when the token is canceled.
Parameters
callback The function to call when the token is canceled
If the token is already canceled, the callback is invoked immediately.
Note
This method is thread-safe and guarantees the callback is called exactly once.
Definition at line 177 of file cancellation_token.h.
throw_if_cancelled() [1/2]
void kcenon::thread::cancellation_token::throw_if_cancelled () const inline
Throws an exception if the token has been canceled.
Exceptions
std::runtime_error if the token has been canceled
Definition at line 163 of file cancellation_token.h.
References is_cancelled().
throw_if_cancelled() [2/2]
void kcenon::thread::cancellation_token::throw_if_cancelled () const inline
Throws an exception if the token has been canceled.
Exceptions
std::runtime_error if the token has been canceled
Definition at line 163 of file cancellation_token.h.
References is_cancelled().
The documentation for this class was generated from the following files:
libraries/thread_system/core/sync/include/cancellation_token.h
libraries/thread_system/include/kcenon/thread/core/cancellation_token.h