Messaging System: monitoring_system::thread_context Class Reference
monitoring_system::thread_context Class Reference
Thread-local context management.
#include <thread_context.h>
Static Public Member Functions
static thread_context_data & create (const std::string &request_id="")
static thread_context_data * current ()
static bool has_context ()
static void clear ()
static std::string generate_request_id ()
static std::string generate_correlation_id ()
static bool copy_from (const thread_context_data &source)
Detailed Description
Thread-local context management.
Definition at line 68 of file thread_context.h.
Member Function Documentation
clear()
void monitoring_system::thread_context::clear () static
Definition at line 33 of file thread_context.cpp.
Referenced by ThreadContextTest::SetUp(), ThreadContextTest::TearDown(), TEST_F(), and TEST_F().
copy_from()
bool monitoring_system::thread_context::copy_from (const thread_context_data & source) static
Definition at line 37 of file thread_context.cpp.
Referenced by TEST_F().
create()
thread_context_data & monitoring_system::thread_context::create (const std::string & request_id = "") static
Definition at line 16 of file thread_context.cpp.
References generate_request_id().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
current()
thread_context_data * monitoring_system::thread_context::current () static
Definition at line 25 of file thread_context.cpp.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
generate_correlation_id()
std::string monitoring_system::thread_context::generate_correlation_id () static
Definition at line 67 of file thread_context.cpp.
References generate_request_id().
Referenced by TEST_F().
generate_request_id()
std::string monitoring_system::thread_context::generate_request_id () static
Definition at line 57 of file thread_context.cpp.
Referenced by create(), generate_correlation_id(), and TEST_F().
has_context()
bool monitoring_system::thread_context::has_context () static
Definition at line 29 of file thread_context.cpp.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
The documentation for this class was generated from the following files:
libraries/monitoring_system/include/kcenon/monitoring/context/thread_context.h
libraries/monitoring_system/src/context/thread_context.cpp