Messaging System: database::security Namespace Reference
database::security Namespace Reference
Classes
class access_control
Role-based access control (RBAC) system.
struct audit_log_entry
Audit log entry for security events.
class audit_logger
Security audit logging system.
class connection_security
Handles secure database connections.
class credential_manager
Manages encrypted credential storage and retrieval.
class encryption_manager
Data encryption and key management.
class query_security
SQL injection prevention and query security.
struct security_credentials
Secure credential storage.
class security_monitor
Real-time security monitoring and alerting.
Enumerations
enum class encryption_type { none , tls , ssl , aes256 }
Types of encryption supported.
enum class authentication_method {
password , certificate , kerberos , oauth2 ,
jwt
}
Authentication methods supported.
Functions
access_control::permission operator| (access_control::permission a, access_control::permission b)
bool has_permission (access_control::permission permissions, access_control::permission check)
Enumeration Type Documentation
authentication_method
enum class database::security::authentication_method strong
Authentication methods supported.
Enumerator
password
certificate
kerberos
oauth2
jwt
Definition at line 62 of file secure_connection.h.
encryption_type
enum class database::security::encryption_type strong
Types of encryption supported.
Enumerator
none
tls
ssl
aes256
Definition at line 51 of file secure_connection.h.
Function Documentation
has_permission()
bool database::security::has_permission (access_control::permission permissions, access_control::permission check) inline
Definition at line 400 of file secure_connection.h.
Referenced by BM_IntegratedSystemPerformance(), BM_SecurityConfigurationOverhead(), TEST_F(), and TEST_F().
operator|()
access_control::permission database::security::operator| (access_control::permission a, access_control::permission b) inline
Definition at line 396 of file secure_connection.h.