Messaging System: fmt::formatter< typed_thread_pool_module::job_types > Struct Reference
fmt::formatter< typed_thread_pool_module::job_types > Struct Reference
Specialization of fmt::formatter for job_types using narrow strings.
#include <job_types.h>
Public Member Functions
template<typename FormatContext >
auto format (const typed_thread_pool_module::job_types &job_type, FormatContext &ctx) const
Formats a job_types value as a narrow string using {fmt}.
template<typename FormatContext >
auto format (const typed_thread_pool_module::job_types &job_type, FormatContext &ctx) const
Formats a job_types value as a narrow string using {fmt}.
template<typename FormatContext >
auto format (const typed_thread_pool_module::job_types &job_type, FormatContext &ctx) const
Formats a job_types value as a narrow string using {fmt}.
Detailed Description
Specialization of fmt::formatter for job_types using narrow strings.
Allows code such as:
std::string s = fmt::format("Type is {}", job_types::RealTime); // "Type is REALTIME"
Definition at line 209 of file job_types.h.
Member Function Documentation
format() [1/3]
template<typename FormatContext > auto fmt::formatter< typed_thread_pool_module::job_types >::format (const typed_thread_pool_module::job_types & job_type, FormatContext & ctx) const inline
Formats a job_types value as a narrow string using {fmt}.
Template Parameters
FormatContext The type of the format context.
Parameters
job_type The job_types enum value to format.
ctx The format context for the output.
Returns
An iterator to the end of the formatted output.
Definition at line 220 of file job_types.h.
References thread_module::to_string().
format() [2/3]
template<typename FormatContext > auto fmt::formatter< typed_thread_pool_module::job_types >::format (const typed_thread_pool_module::job_types & job_type, FormatContext & ctx) const inline
Formats a job_types value as a narrow string using {fmt}.
Template Parameters
FormatContext The type of the format context.
Parameters
job_type The job_types enum value to format.
ctx The format context for the output.
Returns
An iterator to the end of the formatted output.
Definition at line 220 of file job_types.h.
References thread_module::to_string().
format() [3/3]
template<typename FormatContext > auto fmt::formatter< typed_thread_pool_module::job_types >::format (const typed_thread_pool_module::job_types & job_type, FormatContext & ctx) const inline
Formats a job_types value as a narrow string using {fmt}.
Template Parameters
FormatContext The type of the format context.
Parameters
job_type The job_types enum value to format.
ctx The format context for the output.
Returns
An iterator to the end of the formatted output.
Definition at line 220 of file job_types.h.
References thread_module::to_string().
The documentation for this struct was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/typed_thread_pool/core/job_types.h
libraries/thread_system/modular_structure/core/src/typed_thread_pool/core/job_types.h
libraries/thread_system/sources/typed_thread_pool/core/job_types.h