Messaging System: monitoring_system::monitoring_data Struct Reference
monitoring_system::monitoring_data Struct Reference
Container for monitoring metrics from a component.
#include <monitorable_interface.h>
Public Types
using metric_map = std::unordered_map< std::string, double >
using tag_map = std::unordered_map< std::string, std::string >
Public Member Functions
monitoring_data ()
Default constructor.
monitoring_data (const std::string &name)
Constructor with component name.
void add_metric (const std::string &key, double value)
Add a numeric metric.
void add_tag (const std::string &key, const std::string &value)
Add a tag (string metadata)
std::optional< double > get_metric (const std::string &key) const
Get a metric value.
std::optional< std::string > get_tag (const std::string &key) const
Get a tag value.
const metric_map & get_metrics () const
Get all metrics.
const tag_map & get_tags () const
Get all tags.
std::chrono::system_clock::time_point get_timestamp () const
Get the timestamp.
const std::string & get_component_name () const
Get the component name.
void set_component_name (const std::string &name)
Set the component name.
void clear ()
Clear all metrics and tags.
bool empty () const
Check if data is empty.
std::size_t metric_count () const
Get the number of metrics.
std::size_t tag_count () const
Get the number of tags.
void merge (const monitoring_data &other, const std::string &prefix="")
Merge another monitoring_data into this one.
Detailed Description
Container for monitoring metrics from a component.
This structure holds key-value pairs of metrics that a component exposes for monitoring purposes.
Definition at line 38 of file monitorable_interface.h.
Member Typedef Documentation
metric_map
using monitoring_system::monitoring_data::metric_map = std::unordered_map<std::string, double>
Definition at line 39 of file monitorable_interface.h.
tag_map
using monitoring_system::monitoring_data::tag_map = std::unordered_map<std::string, std::string>
Definition at line 40 of file monitorable_interface.h.
Constructor & Destructor Documentation
monitoring_data() [1/2]
monitoring_system::monitoring_data::monitoring_data () inline
Default constructor.
Definition at line 52 of file monitorable_interface.h.
monitoring_data() [2/2]
monitoring_system::monitoring_data::monitoring_data (const std::string & name) inline explicit
Constructor with component name.
Parameters
name Name of the component being monitored
Definition at line 59 of file monitorable_interface.h.
Member Function Documentation
add_metric()
void monitoring_system::monitoring_data::add_metric (const std::string & key, double value) inline
Add a numeric metric.
Parameters
key Metric name
value Metric value
Definition at line 68 of file monitorable_interface.h.
Referenced by monitoring_system::monitoring_aggregator::collect_all(), MetricExportersTest::create_test_monitoring_data(), test_monitorable_component::get_monitoring_data(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and monitoring_system::monitorable_component::update_metric().
add_tag()
void monitoring_system::monitoring_data::add_tag (const std::string & key, const std::string & value) inline
Add a tag (string metadata)
Parameters
key Tag name
value Tag value
Definition at line 77 of file monitorable_interface.h.
Referenced by monitoring_system::monitoring_aggregator::collect_all(), MetricExportersTest::create_test_monitoring_data(), test_monitorable_component::get_monitoring_data(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and monitoring_system::monitorable_component::update_tag().
clear()
void monitoring_system::monitoring_data::clear () inline
Clear all metrics and tags.
Definition at line 150 of file monitorable_interface.h.
Referenced by monitoring_system::monitorable_component::reset_monitoring(), and TEST_F().
empty()
bool monitoring_system::monitoring_data::empty () const inline
Check if data is empty.
Returns
true if no metrics or tags are present
Definition at line 159 of file monitorable_interface.h.
Referenced by TEST_F(), and TEST_F().
get_component_name()
const std::string & monitoring_system::monitoring_data::get_component_name () const inline
Get the component name.
Returns
Name of the monitored component
Definition at line 135 of file monitorable_interface.h.
Referenced by monitoring_system::prometheus_exporter::convert_monitoring_data(), monitoring_system::statsd_exporter::convert_monitoring_data(), and TEST_F().
get_metric()
std::optional< double > monitoring_system::monitoring_data::get_metric (const std::string & key) const inline
Get a metric value.
Parameters
key Metric name
Returns
Optional containing the value if found
Definition at line 86 of file monitorable_interface.h.
Referenced by TEST_F(), TEST_F(), and TEST_F().
get_metrics()
const metric_map & monitoring_system::monitoring_data::get_metrics () const inline
Get all metrics.
Returns
Map of all metrics
Definition at line 111 of file monitorable_interface.h.
Referenced by monitoring_system::opentelemetry_metrics_adapter::convert_monitoring_data(), monitoring_system::prometheus_exporter::convert_monitoring_data(), and monitoring_system::statsd_exporter::convert_monitoring_data().
get_tag()
std::optional< std::string > monitoring_system::monitoring_data::get_tag (const std::string & key) const inline
Get a tag value.
Parameters
key Tag name
Returns
Optional containing the value if found
Definition at line 99 of file monitorable_interface.h.
Referenced by TEST_F(), TEST_F(), and TEST_F().
get_tags()
const tag_map & monitoring_system::monitoring_data::get_tags () const inline
Get all tags.
Returns
Map of all tags
Definition at line 119 of file monitorable_interface.h.
Referenced by monitoring_system::opentelemetry_metrics_adapter::convert_monitoring_data(), monitoring_system::prometheus_exporter::convert_monitoring_data(), and monitoring_system::statsd_exporter::convert_monitoring_data().
get_timestamp()
std::chrono::system_clock::time_point monitoring_system::monitoring_data::get_timestamp () const inline
Get the timestamp.
Returns
Time when the data was collected
Definition at line 127 of file monitorable_interface.h.
Referenced by monitoring_system::opentelemetry_metrics_adapter::convert_monitoring_data(), monitoring_system::prometheus_exporter::convert_monitoring_data(), and TEST_F().
merge()
void monitoring_system::monitoring_data::merge (const monitoring_data & other, const std::string & prefix = "") inline
Merge another monitoring_data into this one.
Parameters
other Data to merge
prefix Optional prefix for merged metrics
Definition at line 184 of file monitorable_interface.h.
Referenced by monitoring_system::monitoring_aggregator::collect_all(), and TEST_F().
metric_count()
std::size_t monitoring_system::monitoring_data::metric_count () const inline
Get the number of metrics.
Returns
Count of metrics
Definition at line 167 of file monitorable_interface.h.
Referenced by monitoring_system::monitoring_aggregator::collect_all(), TEST_F(), TEST_F(), and TEST_F().
set_component_name()
void monitoring_system::monitoring_data::set_component_name (const std::string & name) inline
Set the component name.
Parameters
name Component name
Definition at line 143 of file monitorable_interface.h.
Referenced by monitoring_system::monitorable_component::reset_monitoring().
tag_count()
std::size_t monitoring_system::monitoring_data::tag_count () const inline
Get the number of tags.
Returns
Count of tags
Definition at line 175 of file monitorable_interface.h.
Referenced by TEST_F(), TEST_F(), and TEST_F().
The documentation for this struct was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/interfaces/monitorable_interface.h