Messaging System: kcenon::thread::result< T > Class Template Reference
kcenon::thread::result< T > Class Template Reference
A template class representing either a value or an error.
#include <error_handling.h>
Public Types
using value_type = T
using error_type = error
using value_type = T
using error_type = error
Public Member Functions
result (T value)
Constructs a result with a value.
result (error err)
Constructs a result with an error.
operator bool () const noexcept
Checks if the result contains a value.
bool has_value () const noexcept
Checks if the result contains a value.
T & value () &
Gets the value.
const T & value () const &
Gets the value.
T && value () &&
Gets the value.
error & get_error () &
Gets the error.
const error & get_error () const &
Gets the error.
error && get_error () &&
Gets the error.
template<typename U >
T value_or (U &&default_value) const &
Gets the value or a default.
template<typename U >
T value_or (U &&default_value) &&
Gets the value or a default.
T value_or_throw () const &
Gets the value or throws an exception.
T value_or_throw () &&
Gets the value or throws an exception.
template<typename Fn >
auto map (Fn &&fn) const -> result< std::invoke_result_t< Fn, const T & > >
Maps the result to another type using a function.
template<typename Fn >
auto and_then (Fn &&fn) const -> std::invoke_result_t< Fn, const T & >
Maps the result to another type using a function that returns a result.
result (T value)
Constructs a result with a value.
result (error err)
Constructs a result with an error.
operator bool () const noexcept
Checks if the result contains a value.
bool has_value () const noexcept
Checks if the result contains a value.
T & value () &
Gets the value.
const T & value () const &
Gets the value.
T && value () &&
Gets the value.
error & get_error () &
Gets the error.
const error & get_error () const &
Gets the error.
error && get_error () &&
Gets the error.
template<typename U >
T value_or (U &&default_value) const &
Gets the value or a default.
template<typename U >
T value_or (U &&default_value) &&
Gets the value or a default.
T value_or_throw () const &
Gets the value or throws an exception.
T value_or_throw () &&
Gets the value or throws an exception.
template<typename Fn >
auto map (Fn &&fn) const -> result< std::invoke_result_t< Fn, const T & > >
Maps the result to another type using a function.
template<typename Fn >
auto and_then (Fn &&fn) const -> std::invoke_result_t< Fn, const T & >
Maps the result to another type using a function that returns a result.
Detailed Description
template<typename T>
class kcenon::thread::result< T >
A template class representing either a value or an error.
This class is similar to std::expected from C++23, but can be used with C++20. It holds either a value of type T or an error.
Definition at line 238 of file error_handling.h.
Member Typedef Documentation
error_type [1/2]
template<typename T > using kcenon::thread::result< T >::error_type = error
Definition at line 241 of file error_handling.h.
error_type [2/2]
template<typename T > using kcenon::thread::result< T >::error_type = error
Definition at line 241 of file error_handling.h.
value_type [1/2]
template<typename T > using kcenon::thread::result< T >::value_type = T
Definition at line 240 of file error_handling.h.
value_type [2/2]
template<typename T > using kcenon::thread::result< T >::value_type = T
Definition at line 240 of file error_handling.h.
Constructor & Destructor Documentation
result() [1/4]
template<typename T > kcenon::thread::result< T >::result (T value) inline
Constructs a result with a value.
Parameters
value The value to store
Definition at line 247 of file error_handling.h.
result() [2/4]
template<typename T > kcenon::thread::result< T >::result (error err) inline
Constructs a result with an error.
Parameters
err The error to store
Definition at line 253 of file error_handling.h.
result() [3/4]
template<typename T > kcenon::thread::result< T >::result (T value) inline
Constructs a result with a value.
Parameters
value The value to store
Definition at line 247 of file error_handling.h.
result() [4/4]
template<typename T > kcenon::thread::result< T >::result (error err) inline
Constructs a result with an error.
Parameters
err The error to store
Definition at line 253 of file error_handling.h.
Member Function Documentation
and_then() [1/2]
template<typename T > template<typename Fn > auto kcenon::thread::result< T >::and_then (Fn && fn) const -> std::invoke_result_t<Fn, const T&> inline
Maps the result to another type using a function that returns a result.
Parameters
fn The function to apply to the value
Returns
A new result with the mapped value or the original error
Definition at line 414 of file error_handling.h.
Referenced by kcenon::thread::test::TEST_F(), kcenon::thread::test::TEST_F(), and kcenon::thread::test::TEST_F().
and_then() [2/2]
template<typename T > template<typename Fn > auto kcenon::thread::result< T >::and_then (Fn && fn) const -> std::invoke_result_t<Fn, const T&> inline
Maps the result to another type using a function that returns a result.
Parameters
fn The function to apply to the value
Returns
A new result with the mapped value or the original error
Definition at line 414 of file error_handling.h.
get_error() [1/6]
template<typename T > error & kcenon::thread::result< T >::get_error () & inline
Gets the error.
Returns
A reference to the contained error
Exceptions
std::runtime_error if the result contains a value
Definition at line 312 of file error_handling.h.
Referenced by basic_spsc_example(), basic_typed_queue_example(), batch_operations_example(), kcenon::thread::typed_thread_pool_builder< job_type >::build(), create_priority_default(), different_strategies_example(), main(), mpmc_typed_queue_example(), store_job(), task_scheduling_example(), kcenon::thread::test::TEST_F(), TEST_F(), TEST_F(), TEST_F(), and web_server_simulation().
get_error() [2/6]
template<typename T > error & kcenon::thread::result< T >::get_error () & inline
Gets the error.
Returns
A reference to the contained error
Exceptions
std::runtime_error if the result contains a value
Definition at line 312 of file error_handling.h.
get_error() [3/6]
template<typename T > error && kcenon::thread::result< T >::get_error () && inline
Gets the error.
Returns
An rvalue reference to the contained error
Exceptions
std::runtime_error if the result contains a value
Definition at line 336 of file error_handling.h.
get_error() [4/6]
template<typename T > error && kcenon::thread::result< T >::get_error () && inline
Gets the error.
Returns
An rvalue reference to the contained error
Exceptions
std::runtime_error if the result contains a value
Definition at line 336 of file error_handling.h.
get_error() [5/6]
template<typename T > const error & kcenon::thread::result< T >::get_error () const & inline
Gets the error.
Returns
A const reference to the contained error
Exceptions
std::runtime_error if the result contains a value
Definition at line 324 of file error_handling.h.
get_error() [6/6]
template<typename T > const error & kcenon::thread::result< T >::get_error () const & inline
Gets the error.
Returns
A const reference to the contained error
Exceptions
std::runtime_error if the result contains a value
Definition at line 324 of file error_handling.h.
has_value() [1/2]
template<typename T > bool kcenon::thread::result< T >::has_value () const inline noexcept
Checks if the result contains a value.
Returns
true if the result contains a value, false if it contains an error
Definition at line 267 of file error_handling.h.
Referenced by adaptive_behavior_example(), basic_spsc_example(), BM_HighContention(), BM_MaximumThreads(), BM_MPMC(), BM_Queue_Batch(), BM_Queue_Latency(), BM_Queue_MPMC(), BM_SPSC(), BM_TypedJobQueue_EnqueueDequeue(), BM_TypedJobQueue_HighContention(), BM_TypedJobQueue_MemoryUsage(), BM_TypedLockfreeJobQueue_EnqueueDequeue(), BM_TypedLockfreeJobQueue_HighContention(), BM_TypedLockfreeJobQueue_MemoryUsage(), BM_TypedLockfreeJobQueue_PriorityDequeue(), mpmc_example(), performance_example(), run_producer_consumer_test(), strategy_comparison_example(), kcenon::thread::test::TEST_F(), kcenon::thread::test::TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and test_producer_consumer().
has_value() [2/2]
template<typename T > bool kcenon::thread::result< T >::has_value () const inline noexcept
Checks if the result contains a value.
Returns
true if the result contains a value, false if it contains an error
Definition at line 267 of file error_handling.h.
map() [1/2]
template<typename T > template<typename Fn > auto kcenon::thread::result< T >::map (Fn && fn) const -> result<std::invoke_result_t<Fn, const T&>> inline
Maps the result to another type using a function.
Parameters
fn The function to apply to the value
Returns
A new result with the mapped value or the original error
Definition at line 399 of file error_handling.h.
map() [2/2]
template<typename T > template<typename Fn > auto kcenon::thread::result< T >::map (Fn && fn) const -> result<std::invoke_result_t<Fn, const T&>> inline
Maps the result to another type using a function.
Parameters
fn The function to apply to the value
Returns
A new result with the mapped value or the original error
Definition at line 399 of file error_handling.h.
operator bool() [1/2]
template<typename T > kcenon::thread::result< T >::operator bool () const inline explicit noexcept
Checks if the result contains a value.
Returns
true if the result contains a value, false if it contains an error
Definition at line 259 of file error_handling.h.
operator bool() [2/2]
template<typename T > kcenon::thread::result< T >::operator bool () const inline explicit noexcept
Checks if the result contains a value.
Returns
true if the result contains a value, false if it contains an error
Definition at line 259 of file error_handling.h.
value() [1/6]
template<typename T > T & kcenon::thread::result< T >::value () & inline
Gets the value.
Returns
A reference to the contained value
Exceptions
std::runtime_error if the result contains an error
Definition at line 276 of file error_handling.h.
Referenced by adaptive_behavior_example(), BM_HighContention(), BM_MaximumThreads(), BM_MPMC(), BM_Queue_Batch(), BM_Queue_Latency(), BM_Queue_MPMC(), BM_TypedJobQueue_EnqueueDequeue(), BM_TypedJobQueue_HighContention(), BM_TypedJobQueue_MemoryUsage(), BM_TypedLockfreeJobQueue_EnqueueDequeue(), BM_TypedLockfreeJobQueue_HighContention(), BM_TypedLockfreeJobQueue_MemoryUsage(), BM_TypedLockfreeJobQueue_PriorityDequeue(), kcenon::thread::callback_job::callback_job(), kcenon::thread::callback_job::callback_job(), mpmc_example(), run_producer_consumer_test(), strategy_comparison_example(), kcenon::thread::test::TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and test_producer_consumer().
value() [2/6]
template<typename T > T & kcenon::thread::result< T >::value () & inline
Gets the value.
Returns
A reference to the contained value
Exceptions
std::runtime_error if the result contains an error
Definition at line 276 of file error_handling.h.
value() [3/6]
template<typename T > T && kcenon::thread::result< T >::value () && inline
Gets the value.
Returns
An rvalue reference to the contained value
Exceptions
std::runtime_error if the result contains an error
Definition at line 300 of file error_handling.h.
value() [4/6]
template<typename T > T && kcenon::thread::result< T >::value () && inline
Gets the value.
Returns
An rvalue reference to the contained value
Exceptions
std::runtime_error if the result contains an error
Definition at line 300 of file error_handling.h.
value() [5/6]
template<typename T > const T & kcenon::thread::result< T >::value () const & inline
Gets the value.
Returns
A const reference to the contained value
Exceptions
std::runtime_error if the result contains an error
Definition at line 288 of file error_handling.h.
value() [6/6]
template<typename T > const T & kcenon::thread::result< T >::value () const & inline
Gets the value.
Returns
A const reference to the contained value
Exceptions
std::runtime_error if the result contains an error
Definition at line 288 of file error_handling.h.
value_or() [1/4]
template<typename T > template<typename U > T kcenon::thread::result< T >::value_or (U && default_value) && inline
Gets the value or a default.
Parameters
default_value The value to return if the result contains an error
Returns
The contained value or the default
Definition at line 362 of file error_handling.h.
value_or() [2/4]
template<typename T > template<typename U > T kcenon::thread::result< T >::value_or (U && default_value) && inline
Gets the value or a default.
Parameters
default_value The value to return if the result contains an error
Returns
The contained value or the default
Definition at line 362 of file error_handling.h.
value_or() [3/4]
template<typename T > template<typename U > T kcenon::thread::result< T >::value_or (U && default_value) const & inline
Gets the value or a default.
Parameters
default_value The value to return if the result contains an error
Returns
The contained value or the default
Definition at line 349 of file error_handling.h.
value_or() [4/4]
template<typename T > template<typename U > T kcenon::thread::result< T >::value_or (U && default_value) const & inline
Gets the value or a default.
Parameters
default_value The value to return if the result contains an error
Returns
The contained value or the default
Definition at line 349 of file error_handling.h.
value_or_throw() [1/4]
template<typename T > T kcenon::thread::result< T >::value_or_throw () && inline
Gets the value or throws an exception.
Returns
The contained value
Exceptions
std::runtime_error with the error message if the result contains an error
Definition at line 386 of file error_handling.h.
References kcenon::thread::error::to_string().
value_or_throw() [2/4]
template<typename T > T kcenon::thread::result< T >::value_or_throw () && inline
Gets the value or throws an exception.
Returns
The contained value
Exceptions
std::runtime_error with the error message if the result contains an error
Definition at line 386 of file error_handling.h.
References kcenon::thread::error::to_string().
value_or_throw() [3/4]
template<typename T > T kcenon::thread::result< T >::value_or_throw () const & inline
Gets the value or throws an exception.
Returns
The contained value
Exceptions
std::runtime_error with the error message if the result contains an error
Definition at line 374 of file error_handling.h.
References kcenon::thread::error::to_string().
value_or_throw() [4/4]
template<typename T > T kcenon::thread::result< T >::value_or_throw () const & inline
Gets the value or throws an exception.
Returns
The contained value
Exceptions
std::runtime_error with the error message if the result contains an error
Definition at line 374 of file error_handling.h.
References kcenon::thread::error::to_string().
The documentation for this class was generated from the following files:
libraries/thread_system/core/sync/include/error_handling.h
libraries/thread_system/include/kcenon/thread/core/error_handling.h