Messaging System: analysis_visualizer Class Reference
analysis_visualizer Class Reference
Static Public Member Functions
static void print_header ()
static void print_pool_summary (const thread_pool_analyzer::pool_performance_summary &summary)
static void print_comparison (const thread_pool_analyzer::pool_comparison_result &result)
static void print_bottleneck (const std::string &pool_name, const std::optional< std::string > &bottleneck)
static void print_pool_type (const std::string &pool_name, const std::string &type)
static void print_health_score (const std::string &pool_name, double score)
static void print_suggestions (const std::string &pool_name, const std::vector< std::string > &suggestions)
Detailed Description
Definition at line 121 of file thread_pool_analysis_example.cpp.
Member Function Documentation
print_bottleneck()
static void analysis_visualizer::print_bottleneck (const std::string & pool_name, const std::optional< std::string > & bottleneck) inline static
Definition at line 172 of file thread_pool_analysis_example.cpp.
References colors::red, and colors::reset.
Referenced by main().
print_comparison()
static void analysis_visualizer::print_comparison (const thread_pool_analyzer::pool_comparison_result & result) inline static
Definition at line 157 of file thread_pool_analysis_example.cpp.
References colors::bold, monitoring_module::thread_pool_analyzer::pool_comparison_result::efficiency_difference, colors::green, colors::magenta, monitoring_module::thread_pool_analyzer::pool_comparison_result::performance_winner, monitoring_module::thread_pool_analyzer::pool_comparison_result::pool1, monitoring_module::thread_pool_analyzer::pool_comparison_result::pool2, monitoring_interface::thread_pool_identifier::pool_name, monitoring_module::thread_pool_analyzer::pool_comparison_result::recommendation, colors::reset, monitoring_module::thread_pool_analyzer::pool_comparison_result::throughput_ratio, and colors::yellow.
Referenced by main().
print_header()
static void analysis_visualizer::print_header () inline static
Definition at line 123 of file thread_pool_analysis_example.cpp.
References colors::bold, colors::cyan, and colors::reset.
Referenced by main().
print_health_score()
static void analysis_visualizer::print_health_score (const std::string & pool_name, double score) inline static
Definition at line 189 of file thread_pool_analysis_example.cpp.
References colors::green, colors::red, colors::reset, and colors::yellow.
Referenced by main().
print_pool_summary()
static void analysis_visualizer::print_pool_summary (const thread_pool_analyzer::pool_performance_summary & summary) inline static
Definition at line 129 of file thread_pool_analysis_example.cpp.
References colors::bold, colors::green, monitoring_module::thread_pool_analyzer::pool_performance_summary::load_balance_score, monitoring_module::thread_pool_analyzer::pool_performance_summary::pool_id, monitoring_interface::thread_pool_identifier::pool_instance_id, monitoring_interface::thread_pool_identifier::pool_name, monitoring_interface::thread_pool_identifier::process_id, monitoring_interface::process_identifier::process_name, monitoring_module::thread_pool_analyzer::pool_performance_summary::queue_saturation, colors::red, colors::reset, monitoring_module::thread_pool_analyzer::pool_performance_summary::throughput_per_worker, monitoring_module::thread_pool_analyzer::pool_performance_summary::worker_efficiency, and colors::yellow.
Referenced by main().
print_pool_type()
static void analysis_visualizer::print_pool_type (const std::string & pool_name, const std::string & type) inline static
Definition at line 180 of file thread_pool_analysis_example.cpp.
References colors::blue, colors::cyan, colors::red, colors::reset, and colors::yellow.
Referenced by main().
print_suggestions()
static void analysis_visualizer::print_suggestions (const std::string & pool_name, const std::vector< std::string > & suggestions) inline static
Definition at line 199 of file thread_pool_analysis_example.cpp.
References colors::bold, and colors::reset.
Referenced by main().
The documentation for this class was generated from the following file:
libraries/monitoring_system/samples/thread_pool_analysis_example.cpp