Messaging System: kcenon::logger::encrypted_writer Class Reference
kcenon::logger::encrypted_writer Class Reference
Writer that encrypts log data before passing to another writer.
#include <encrypted_writer.h>
Public Types
enum class encryption_type { none , aes_256_cbc , aes_256_gcm , chacha20_poly1305 }
Encryption algorithm type.
Public Member Functions
encrypted_writer (std::unique_ptr< base_writer > wrapped_writer, const std::vector< uint8_t > &key, encryption_type type=encryption_type::aes_256_gcm)
Constructor.
~encrypted_writer () override
Destructor.
result_void write (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write encrypted log entry.
result_void flush () override
Flush wrapped writer.
std::string get_name () const override
Get writer name.
Public Member Functions inherited from kcenon::logger::base_writer
virtual ~base_writer ()=default
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
virtual bool is_healthy () const override
Check if the writer is healthy and operational.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
Static Public Member Functions
static std::vector< uint8_t > generate_key (size_t size=32)
Generate random encryption key.
static bool save_key (const std::vector< uint8_t > &key, const std::string &filename)
Save key to file (securely)
static std::vector< uint8_t > load_key (const std::string &filename)
Load key from file.
Additional Inherited Members
Protected Member Functions inherited from kcenon::logger::base_writer
std::string format_log_entry (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (logger_system::log_level level) const
Convert log level to string representation.
std::string level_to_color (logger_system::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
Writer that encrypts log data before passing to another writer.
Definition at line 21 of file encrypted_writer.h.
Member Enumeration Documentation
encryption_type
enum class kcenon::logger::encrypted_writer::encryption_type strong
Encryption algorithm type.
Enumerator
none
aes_256_cbc
aes_256_gcm
chacha20_poly1305
Definition at line 26 of file encrypted_writer.h.
Constructor & Destructor Documentation
encrypted_writer()
kcenon::logger::encrypted_writer::encrypted_writer (std::unique_ptr< base_writer > wrapped_writer, const std::vector< uint8_t > & key, encryption_type type = encryption_type::aes_256_gcm)
Constructor.
Parameters
wrapped_writer The writer to wrap with encryption
key Encryption key (must be 32 bytes for AES-256)
type Encryption algorithm to use
Definition at line 17 of file encrypted_writer.cpp.
References generate_key().
~encrypted_writer()
kcenon::logger::encrypted_writer::~encrypted_writer () override default
Destructor.
Member Function Documentation
flush()
result_void kcenon::logger::encrypted_writer::flush () override virtual
Flush wrapped writer.
Implements kcenon::logger::base_writer.
Definition at line 67 of file encrypted_writer.cpp.
generate_key()
std::vector< uint8_t > kcenon::logger::encrypted_writer::generate_key (size_t size = 32) static
Generate random encryption key.
Parameters
size Key size in bytes (32 for AES-256)
Returns
Random key
Definition at line 71 of file encrypted_writer.cpp.
Referenced by encrypted_writer(), and TEST_F().
get_name()
std::string kcenon::logger::encrypted_writer::get_name () const inline override virtual
Get writer name.
Implements kcenon::logger::base_writer.
Definition at line 66 of file encrypted_writer.h.
load_key()
std::vector< uint8_t > kcenon::logger::encrypted_writer::load_key (const std::string & filename) static
Load key from file.
Parameters
filename File path
Returns
The loaded key (empty if failed)
Definition at line 102 of file encrypted_writer.cpp.
Referenced by TEST_F().
save_key()
bool kcenon::logger::encrypted_writer::save_key (const std::vector< uint8_t > & key, const std::string & filename) static
Save key to file (securely)
Parameters
key The key to save
filename File path
Returns
true if saved successfully
Definition at line 84 of file encrypted_writer.cpp.
Referenced by TEST_F().
write()
result_void kcenon::logger::encrypted_writer::write (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write encrypted log entry.
Implements kcenon::logger::base_writer.
Definition at line 35 of file encrypted_writer.cpp.
References kcenon::logger::encryption_failed, kcenon::logger::base_writer::format_log_entry(), and kcenon::logger::make_logger_error().
The documentation for this class was generated from the following files:
libraries/logger_system/include/kcenon/logger/writers/encrypted_writer.h
libraries/logger_system/src/impl/writers/encrypted_writer.cpp