Messaging System: libraries/thread_system/cmake/test_std_format.cpp File Reference
test_std_format.cpp File Reference
#include <format>
#include <string>
#include <string_view>
#include <vector>
Classes
struct Point
struct std::formatter< Point >
Functions
std::string test_basic ()
std::string test_numeric ()
std::string test_float ()
std::string test_alignment ()
std::string test_custom ()
template<typename... Args>
std::string test_compile_time (std::format_string< Args... > fmt, Args &&... args)
int main ()
Function Documentation
main()
int main ()
Definition at line 83 of file test_std_format.cpp.
References test_alignment(), test_basic(), test_compile_time(), test_custom(), test_float(), and test_numeric().
test_alignment()
std::string test_alignment ()
Definition at line 54 of file test_std_format.cpp.
Referenced by main().
test_basic()
std::string test_basic ()
Definition at line 39 of file test_std_format.cpp.
Referenced by main().
test_compile_time()
template<typename... Args> std::string test_compile_time (std::format_string< Args... > fmt, Args &&... args)
Definition at line 79 of file test_std_format.cpp.
Referenced by main().
test_custom()
std::string test_custom ()
Definition at line 72 of file test_std_format.cpp.
Referenced by main().
test_float()
std::string test_float ()
Definition at line 49 of file test_std_format.cpp.
Referenced by main().
test_numeric()
std::string test_numeric ()
Definition at line 44 of file test_std_format.cpp.
Referenced by main().