Messaging System: kcenon::logger::async::high_performance_async_writer Class Reference
kcenon::logger::async::high_performance_async_writer Class Reference
High-performance asynchronous writer.
#include <high_performance_async_writer.h>
Classes
struct config
Configuration for the high-performance async writer.
struct performance_stats
Performance statistics.
Public Member Functions
high_performance_async_writer (std::unique_ptr< base_writer > wrapped_writer, const config &cfg=config{})
Constructor.
~high_performance_async_writer () override
Destructor.
bool start ()
Start the async writer.
void stop (bool flush_remaining=true)
Stop the async writer.
result_void write (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write a log message asynchronously.
result_void flush () override
Flush all pending messages.
bool is_healthy () const override
Check if the writer is healthy.
std::string get_name () const override
Get the name of this writer.
void set_use_color (bool use_color) override
Set whether to use color output.
const performance_stats & get_stats () const
Get performance statistics.
void reset_stats ()
Reset performance statistics.
double get_queue_utilization () const
Get current queue utilization.
const batch_processor::processing_stats * get_batch_stats () const
Get batch processor statistics if enabled.
Public Member Functions inherited from kcenon::logger::base_writer
virtual ~base_writer ()=default
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
bool use_color () const
Get current color output setting.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
Additional Inherited Members
Protected Member Functions inherited from kcenon::logger::base_writer
std::string format_log_entry (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (logger_system::log_level level) const
Convert log level to string representation.
std::string level_to_color (logger_system::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
High-performance asynchronous writer.
This writer combines lock-free queuing, memory pooling, and batch processing to achieve maximum throughput while maintaining low latency.
Definition at line 38 of file high_performance_async_writer.h.
Constructor & Destructor Documentation
high_performance_async_writer()
kcenon::logger::async::high_performance_async_writer::high_performance_async_writer (std::unique_ptr< base_writer > wrapped_writer, const config & cfg = config{}) explicit
Constructor.
Parameters
wrapped_writer The underlying writer to wrap
cfg Configuration
Definition at line 13 of file high_performance_async_writer.cpp.
References kcenon::logger::async::high_performance_async_writer::config::batch_config, kcenon::logger::async::high_performance_async_writer::config::enable_batch_processing, kcenon::logger::async::high_performance_async_writer::config::enable_memory_pooling, kcenon::logger::async::make_batch_processor(), and kcenon::logger::async::high_performance_async_writer::config::pool_config.
~high_performance_async_writer()
kcenon::logger::async::high_performance_async_writer::~high_performance_async_writer () override
Destructor.
Definition at line 37 of file high_performance_async_writer.cpp.
References stop().
Member Function Documentation
flush()
result_void kcenon::logger::async::high_performance_async_writer::flush () override virtual
Flush all pending messages.
Returns
result_void indicating success or error
Implements kcenon::logger::base_writer.
Definition at line 102 of file high_performance_async_writer.cpp.
get_batch_stats()
const batch_processor::processing_stats * kcenon::logger::async::high_performance_async_writer::get_batch_stats () const
Get batch processor statistics if enabled.
Returns
Pointer to batch processor stats, or nullptr if not enabled
Definition at line 143 of file high_performance_async_writer.cpp.
get_name()
std::string kcenon::logger::async::high_performance_async_writer::get_name () const override virtual
Get the name of this writer.
Returns
Writer name
Implements kcenon::logger::base_writer.
Definition at line 123 of file high_performance_async_writer.cpp.
get_queue_utilization()
double kcenon::logger::async::high_performance_async_writer::get_queue_utilization () const
Get current queue utilization.
Returns
Queue utilization as percentage (0.0 to 1.0)
Definition at line 134 of file high_performance_async_writer.cpp.
References kcenon::logger::async::high_performance_async_writer::config::queue_size.
get_stats()
const performance_stats & kcenon::logger::async::high_performance_async_writer::get_stats () const inline
Get performance statistics.
Returns
Reference to performance statistics
Definition at line 176 of file high_performance_async_writer.h.
is_healthy()
bool kcenon::logger::async::high_performance_async_writer::is_healthy () const override virtual
Check if the writer is healthy.
Returns
true if healthy, false otherwise
Reimplemented from kcenon::logger::base_writer.
Definition at line 111 of file high_performance_async_writer.cpp.
reset_stats()
void kcenon::logger::async::high_performance_async_writer::reset_stats () inline
Reset performance statistics.
Definition at line 181 of file high_performance_async_writer.h.
References kcenon::logger::async::high_performance_async_writer::performance_stats::reset().
set_use_color()
void kcenon::logger::async::high_performance_async_writer::set_use_color (bool use_color) override virtual
Set whether to use color output.
Parameters
use_color Enable/disable color output
Reimplemented from kcenon::logger::base_writer.
Definition at line 128 of file high_performance_async_writer.cpp.
References kcenon::logger::base_writer::use_color().
start()
bool kcenon::logger::async::high_performance_async_writer::start ()
Start the async writer.
Returns
true if started successfully
Definition at line 41 of file high_performance_async_writer.cpp.
stop()
void kcenon::logger::async::high_performance_async_writer::stop (bool flush_remaining = true)
Stop the async writer.
Parameters
flush_remaining Whether to flush remaining messages
Definition at line 54 of file high_performance_async_writer.cpp.
Referenced by ~high_performance_async_writer().
write()
result_void kcenon::logger::async::high_performance_async_writer::write (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write a log message asynchronously.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
timestamp Timestamp
Returns
result_void indicating success or error
Implements kcenon::logger::base_writer.
Definition at line 66 of file high_performance_async_writer.cpp.
References kcenon::logger::async::high_performance_async_writer::performance_stats::dropped_writes, and kcenon::logger::async::high_performance_async_writer::performance_stats::total_writes.
The documentation for this class was generated from the following files:
libraries/logger_system/src/impl/async/high_performance_async_writer.h
libraries/logger_system/src/impl/async/high_performance_async_writer.cpp