Messaging System: libraries/thread_system/benchmarks/thread_pool_benchmarks/real_world_benchmark.cpp File Reference
real_world_benchmark.cpp File Reference
Real-world scenario benchmarks for Thread System.
#include <benchmark/benchmark.h>
#include <chrono>
#include <vector>
#include <random>
#include <fstream>
#include <sstream>
#include <cmath>
#include <algorithm>
#include <numeric>
#include <atomic>
#include <future>
#include <map>
#include <thread>
#include "../../sources/thread_pool/core/thread_pool.h"
#include "../../sources/thread_pool/workers/thread_worker.h"
#include "../../sources/typed_thread_pool/pool/typed_thread_pool.h"
#include "../../sources/typed_thread_pool/scheduling/typed_thread_worker.h"
#include "../../sources/typed_thread_pool/jobs/callback_typed_job.h"
#include "../../sources/utilities/core/formatter.h"
Classes
class WorkloadSimulator
struct RequestType
Functions
auto create_default (const uint16_t &worker_counts) -> std::tuple< std::shared_ptr< thread_pool_module::thread_pool >, std::optional< std::string > >
template<typename Type >
auto create_priority_default (const uint16_t &worker_counts) -> std::tuple< std::shared_ptr< typed_thread_pool_module::typed_thread_pool_t< Type > >, std::optional< std::string > >
static void BM_WebServerSimulation (benchmark::State &state)
Benchmark web server request handling simulation.
Args ({8, 10000}) -> Args({16, 10000}) ->Args({32, 10000}) ->Args({64, 10000}) ->Unit(benchmark::kMillisecond)
static void BM_ImageProcessingPipeline (benchmark::State &state)
Benchmark image processing pipeline simulation.
Arg (100) -> Arg(500) ->Arg(1000) ->Arg(5000) ->Unit(benchmark::kMillisecond)
static void BM_DataAnalysisWorkload (benchmark::State &state)
Benchmark data analysis workload (MapReduce simulation)
Args ({2, 100}) -> Args({4, 100}) ->Args({8, 100}) ->Args({16, 100}) ->Unit(benchmark::kMillisecond)
static void BM_GameEngineSimulation (benchmark::State &state)
Benchmark game engine update loop simulation.
Args ({60, 300}) -> Args({30, 150}) ->Args({120, 600}) ->Unit(benchmark::kMillisecond) ->UseRealTime()
static void BM_MicroserviceCommunication (benchmark::State &state)
Benchmark microservice communication pattern.
static void BM_BatchFileProcessing (benchmark::State &state)
Benchmark batch file processing simulation.
Args ({10, 10000}) -> Args({50, 10000}) ->Args({100, 10000}) ->Args({500, 10000}) ->Unit(benchmark::kMillisecond)
BENCHMARK_MAIN ()
Variables
static const std::vector< RequestType > g_request_types
Detailed Description
Real-world scenario benchmarks for Thread System.
Tests that simulate actual usage patterns:
Web server request handling
Image processing pipeline
Data analysis workloads
Mixed I/O and CPU tasks
Definition in file real_world_benchmark.cpp.
Function Documentation
Arg()
Arg (100) -> Arg(500) ->Arg(1000) ->Arg(5000) ->Unit(benchmark::kMillisecond)
Args() [1/4]
Args ({10, 10000}) -> Args({50, 10000}) ->Args({100, 10000}) ->Args({500, 10000}) ->Unit(benchmark::kMillisecond)
Args() [2/4]
Args ({2, 100}) -> Args({4, 100}) ->Args({8, 100}) ->Args({16, 100}) ->Unit(benchmark::kMillisecond)
Args() [3/4]
Args ({60, 300}) -> Args({30, 150}) ->Args({120, 600}) ->Unit(benchmark::kMillisecond) ->UseRealTime()
Args() [4/4]
Args ({8, 10000}) -> Args({16, 10000}) ->Args({32, 10000}) ->Args({64, 10000}) ->Unit(benchmark::kMillisecond)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_BatchFileProcessing()
static void BM_BatchFileProcessing (benchmark::State & state) static
Benchmark batch file processing simulation.
Definition at line 568 of file real_world_benchmark.cpp.
References create_default(), WorkloadSimulator::simulate_cpu_work(), and WorkloadSimulator::simulate_io_work().
BM_DataAnalysisWorkload()
static void BM_DataAnalysisWorkload (benchmark::State & state) static
Benchmark data analysis workload (MapReduce simulation)
Definition at line 299 of file real_world_benchmark.cpp.
References create_default(), WorkloadSimulator::simulate_cpu_work(), and WorkloadSimulator::simulate_memory_work().
BM_GameEngineSimulation()
static void BM_GameEngineSimulation (benchmark::State & state) static
Benchmark game engine update loop simulation.
Definition at line 375 of file real_world_benchmark.cpp.
References thread_pool_module::priority.
BM_ImageProcessingPipeline()
static void BM_ImageProcessingPipeline (benchmark::State & state) static
Benchmark image processing pipeline simulation.
Definition at line 240 of file real_world_benchmark.cpp.
References create_default(), and WorkloadSimulator::simulate_cpu_work().
BM_MicroserviceCommunication()
static void BM_MicroserviceCommunication (benchmark::State & state) static
Benchmark microservice communication pattern.
Definition at line 475 of file real_world_benchmark.cpp.
References create_default(), and WorkloadSimulator::simulate_io_work().
BM_WebServerSimulation()
static void BM_WebServerSimulation (benchmark::State & state) static
Benchmark web server request handling simulation.
Definition at line 171 of file real_world_benchmark.cpp.
References create_default(), g_request_types, and WorkloadSimulator::simulate_mixed_work().
create_default()
auto create_default (const uint16_t & worker_counts) -> std::tuple<std::shared_ptr<thread_pool_module::thread_pool>, std::optional<std::string>>
Definition at line 65 of file real_world_benchmark.cpp.
References utility_module::formatter::format().
Referenced by BM_BatchFileProcessing(), BM_DataAnalysisWorkload(), BM_ImageProcessingPipeline(), BM_MicroserviceCommunication(), and BM_WebServerSimulation().
create_priority_default()
template<typename Type > auto create_priority_default (const uint16_t & worker_counts) -> std::tuple<std::shared_ptr<typed_thread_pool_module::typed_thread_pool_t<Type>>, std::optional<std::string>>
Definition at line 93 of file real_world_benchmark.cpp.
References utility_module::formatter::format().
Variable Documentation
g_request_types
const std::vector<RequestType> g_request_types static
Initial value:
= {
    {"Static file", 1, 1, 0.5},
    {"API query", 5, 10, 0.3},
    {"Database write", 10, 50, 0.15},
    {"Complex computation", 50, 5, 0.05}
}
Definition at line 162 of file real_world_benchmark.cpp.
Referenced by BM_WebServerSimulation().