Messaging System: monitoring_module::analysis_dashboard Class Reference
monitoring_module::analysis_dashboard Class Reference
종합 분석 대시보드
#include <analysis_dashboard.h>
Classes
struct correlation_matrix
메트릭간 상관관계 매트릭스
struct dashboard_config
대시보드 설정
struct performance_forecast
성능 예측 리포트
struct system_health_report
시스템 건강도 종합 리포트
Public Member Functions
analysis_dashboard (std::shared_ptr< multi_process_monitoring > monitor, const dashboard_config &config)
생성자
system_health_report generate_health_report ()
시스템 건강도 종합 분석
performance_forecast generate_forecast (std::chrono::seconds duration)
성능 예측 분석
correlation_matrix analyze_correlations ()
메트릭간 상관관계 분석
std::vector< trend_analyzer::anomaly_result > detect_real_time_anomalies ()
실시간 이상 징후 탐지
std::unordered_map< monitoring_interface::thread_pool_identifier, std::string > analyze_bottlenecks ()
병목 현상 종합 분석
std::vector< std::pair< int, std::string > > generate_optimization_suggestions ()
최적화 제안 생성
std::unordered_map< std::string, std::optional< std::chrono::steady_clock::time_point > > analyze_capacity_planning ()
용량 계획 분석
std::string render_text_dashboard ()
대시보드 텍스트 렌더링
std::string export_json ()
JSON 형식으로 대시보드 데이터 내보내기
alert_manager & get_alert_manager ()
알림 관리자 접근
std::vector< trend_analyzer::trend_point > collect_metric_history (const std::string &metric_name, std::chrono::seconds duration)
메트릭 히스토리 수집
Detailed Description
종합 분석 대시보드
모든 고급 분석 기능을 통합하여 시각화하는 대시보드
Definition at line 26 of file analysis_dashboard.h.
Constructor & Destructor Documentation
analysis_dashboard()
monitoring_module::analysis_dashboard::analysis_dashboard (std::shared_ptr< multi_process_monitoring > monitor, const dashboard_config & config) explicit
생성자
Parameters
monitor 모니터링 시스템
config 대시보드 설정
Definition at line 14 of file analysis_dashboard.cpp.
References monitoring_module::analysis_dashboard::dashboard_config::enable_alerts.
Member Function Documentation
analyze_bottlenecks()
std::unordered_map< monitoring_interface::thread_pool_identifier, std::string > monitoring_module::analysis_dashboard::analyze_bottlenecks ()
병목 현상 종합 분석
Returns
프로세스/풀별 병목 현상 맵
Definition at line 262 of file analysis_dashboard.cpp.
References monitoring_module::thread_pool_analyzer::detect_bottleneck().
Referenced by render_text_dashboard().
analyze_capacity_planning()
std::unordered_map< std::string, std::optional< std::chrono::steady_clock::time_point > > monitoring_module::analysis_dashboard::analyze_capacity_planning ()
용량 계획 분석
Returns
리소스별 용량 예측
Definition at line 314 of file analysis_dashboard.cpp.
References monitoring_module::trend_analyzer::predict_capacity_exhaustion().
analyze_correlations()
analysis_dashboard::correlation_matrix monitoring_module::analysis_dashboard::analyze_correlations ()
메트릭간 상관관계 분석
Returns
상관관계 매트릭스
Definition at line 201 of file analysis_dashboard.cpp.
References monitoring_module::trend_analyzer::calculate_correlation(), monitoring_module::analysis_dashboard::correlation_matrix::correlations, monitoring_module::analysis_dashboard::dashboard_config::enable_correlations, monitoring_module::analysis_dashboard::correlation_matrix::metric_names, and monitoring_module::analysis_dashboard::correlation_matrix::strong_correlations.
collect_metric_history()
std::vector< trend_analyzer::trend_point > monitoring_module::analysis_dashboard::collect_metric_history (const std::string & metric_name, std::chrono::seconds duration)
메트릭 히스토리 수집
Parameters
metric_name 메트릭 이름
duration 수집 기간
Returns
시계열 데이터
Definition at line 458 of file analysis_dashboard.cpp.
References monitoring_module::trend_analyzer::trend_point::timestamp, and monitoring_module::trend_analyzer::trend_point::value.
detect_real_time_anomalies()
std::vector< trend_analyzer::anomaly_result > monitoring_module::analysis_dashboard::detect_real_time_anomalies ()
실시간 이상 징후 탐지
Returns
탐지된 이상 징후들
Definition at line 246 of file analysis_dashboard.cpp.
References monitoring_module::analysis_dashboard::dashboard_config::anomaly_threshold, and monitoring_module::trend_analyzer::detect_anomalies().
Referenced by render_text_dashboard().
export_json()
std::string monitoring_module::analysis_dashboard::export_json ()
JSON 형식으로 대시보드 데이터 내보내기
Returns
JSON 문자열
Definition at line 420 of file analysis_dashboard.cpp.
References monitoring_module::alert_manager::critical, monitoring_module::alert_manager::emergency, generate_health_report(), monitoring_module::alert_manager::get_alert_statistics(), monitoring_module::alert_manager::info, and monitoring_module::alert_manager::warning.
generate_forecast()
analysis_dashboard::performance_forecast monitoring_module::analysis_dashboard::generate_forecast (std::chrono::seconds duration)
성능 예측 분석
Parameters
duration 예측 기간
Returns
예측 리포트
Definition at line 146 of file analysis_dashboard.cpp.
References monitoring_module::analysis_dashboard::performance_forecast::capacity_warning_time, monitoring_module::analysis_dashboard::performance_forecast::cpu_predictions, monitoring_module::analysis_dashboard::dashboard_config::enable_predictions, monitoring_module::analysis_dashboard::performance_forecast::memory_predictions, monitoring_module::trend_analyzer::predict_capacity_exhaustion(), monitoring_module::trend_analyzer::predict_linear(), monitoring_module::analysis_dashboard::performance_forecast::risk_factors, and monitoring_module::analysis_dashboard::performance_forecast::throughput_predictions.
Referenced by render_text_dashboard().
generate_health_report()
analysis_dashboard::system_health_report monitoring_module::analysis_dashboard::generate_health_report ()
시스템 건강도 종합 분석
Returns
건강도 리포트
Definition at line 72 of file analysis_dashboard.cpp.
References monitoring_module::thread_pool_analyzer::detect_bottleneck(), monitoring_module::analysis_dashboard::system_health_report::health_status, monitoring_module::analysis_dashboard::system_health_report::issues, monitoring_module::analysis_dashboard::system_health_report::overall_health_score, monitoring_module::analysis_dashboard::system_health_report::recommendations, monitoring_module::analysis_dashboard::system_health_report::report_time, monitoring_module::thread_pool_analyzer::suggest_optimizations(), and monitoring_module::analysis_dashboard::system_health_report::warnings.
Referenced by export_json(), and render_text_dashboard().
generate_optimization_suggestions()
std::vector< std::pair< int, std::string > > monitoring_module::analysis_dashboard::generate_optimization_suggestions ()
최적화 제안 생성
Returns
우선순위별 최적화 제안
Definition at line 278 of file analysis_dashboard.cpp.
References monitoring_module::thread_pool_analyzer::calculate_health_score(), and monitoring_module::thread_pool_analyzer::suggest_optimizations().
Referenced by render_text_dashboard().
get_alert_manager()
alert_manager & monitoring_module::analysis_dashboard::get_alert_manager () inline
알림 관리자 접근
Returns
알림 관리자 참조
Definition at line 146 of file analysis_dashboard.h.
render_text_dashboard()
std::string monitoring_module::analysis_dashboard::render_text_dashboard ()
대시보드 텍스트 렌더링
Returns
포맷된 대시보드 문자열
Definition at line 340 of file analysis_dashboard.cpp.
References analyze_bottlenecks(), detect_real_time_anomalies(), monitoring_module::analysis_dashboard::dashboard_config::enable_predictions, generate_forecast(), generate_health_report(), generate_optimization_suggestions(), monitoring_module::alert_manager::get_recent_alerts(), and alert::message.
The documentation for this class was generated from the following files:
libraries/monitoring_system/sources/monitoring/analysis_dashboard.h
libraries/monitoring_system/sources/monitoring/analysis_dashboard.cpp