Messaging System: thread_pool_module::thread_pool Class Reference
thread_pool_module::thread_pool Class Reference
A thread pool for concurrent execution of jobs using multiple worker threads.
#include <thread_pool.h>
Public Member Functions
thread_pool (const std::string &thread_title="thread_pool", const thread_context &context=thread_context())
Constructs a new thread_pool instance.
virtual ~thread_pool (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< thread_pool >
Retrieves a std::shared_ptr to this thread_pool instance.
auto start (void) -> std::optional< std::string >
Starts the thread pool and all associated workers.
auto get_job_queue (void) -> std::shared_ptr< job_queue >
Returns the shared job_queue used by this thread pool.
auto enqueue (std::unique_ptr< job > &&job) -> std::optional< std::string >
Enqueues a new job into the shared job_queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> std::optional< std::string >
Enqueues a batch of jobs into the shared job_queue.
auto enqueue (std::unique_ptr< thread_worker > &&worker) -> std::optional< std::string >
Adds a thread_worker to the thread pool for specialized or additional processing.
auto enqueue_batch (std::vector< std::unique_ptr< thread_worker > > &&workers) -> std::optional< std::string >
Adds a batch of thread_worker objects to the thread pool.
auto stop (const bool &immediately_stop=false) -> void
Stops the thread pool and all worker threads.
auto to_string (void) const -> std::string
Provides a string representation of this thread_pool.
std::uint32_t get_pool_instance_id () const
Get the pool instance id.
void report_metrics ()
Collect and report current thread pool metrics.
std::size_t get_idle_worker_count () const
Get the number of idle workers.
auto get_context (void) const -> const thread_context &
Gets the thread context for this pool.
thread_pool (const std::string &thread_title="thread_pool", const thread_context &context=thread_context())
Constructs a new thread_pool instance.
virtual ~thread_pool (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< thread_pool >
Retrieves a std::shared_ptr to this thread_pool instance.
auto start (void) -> std::optional< std::string >
Starts the thread pool and all associated workers.
auto get_job_queue (void) -> std::shared_ptr< job_queue >
Returns the shared job_queue used by this thread pool.
auto enqueue (std::unique_ptr< job > &&job) -> std::optional< std::string >
Enqueues a new job into the shared job_queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> std::optional< std::string >
Enqueues a batch of jobs into the shared job_queue.
auto enqueue (std::unique_ptr< thread_worker > &&worker) -> std::optional< std::string >
Adds a thread_worker to the thread pool for specialized or additional processing.
auto enqueue_batch (std::vector< std::unique_ptr< thread_worker > > &&workers) -> std::optional< std::string >
Adds a batch of thread_worker objects to the thread pool.
auto stop (const bool &immediately_stop=false) -> void
Stops the thread pool and all worker threads.
auto to_string (void) const -> std::string
Provides a string representation of this thread_pool.
std::uint32_t get_pool_instance_id () const
Get the pool instance id.
void report_metrics ()
Collect and report current thread pool metrics.
std::size_t get_idle_worker_count () const
Get the number of idle workers.
auto get_context (void) const -> const thread_context &
Gets the thread context for this pool.
thread_pool (const std::string &thread_title="thread_pool", const thread_context &context=thread_context())
Constructs a new thread_pool instance.
virtual ~thread_pool (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< thread_pool >
Retrieves a std::shared_ptr to this thread_pool instance.
auto start (void) -> std::optional< std::string >
Starts the thread pool and all associated workers.
auto get_job_queue (void) -> std::shared_ptr< job_queue >
Returns the shared job_queue used by this thread pool.
auto enqueue (std::unique_ptr< job > &&job) -> std::optional< std::string >
Enqueues a new job into the shared job_queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> std::optional< std::string >
Enqueues a batch of jobs into the shared job_queue.
auto enqueue (std::unique_ptr< thread_worker > &&worker) -> std::optional< std::string >
Adds a thread_worker to the thread pool for specialized or additional processing.
auto enqueue_batch (std::vector< std::unique_ptr< thread_worker > > &&workers) -> std::optional< std::string >
Adds a batch of thread_worker objects to the thread pool.
auto stop (const bool &immediately_stop=false) -> void
Stops the thread pool and all worker threads.
auto to_string (void) const -> std::string
Provides a string representation of this thread_pool.
std::uint32_t get_pool_instance_id () const
Get the pool instance id.
void report_metrics ()
Collect and report current thread pool metrics.
std::size_t get_idle_worker_count () const
Get the number of idle workers.
auto get_context (void) const -> const thread_context &
Gets the thread context for this pool.
Detailed Description
A thread pool for concurrent execution of jobs using multiple worker threads.
The thread_pool class manages a group of worker threads that process jobs from a shared job_queue. This implementation provides:
Efficient reuse of threads to reduce thread creation/destruction overhead
Controlled concurrency through a fixed or dynamic thread count
A simple interface for submitting jobs of various types
Graceful handling of thread startup, execution, and shutdown
The thread pool is designed for scenarios where many short-lived tasks need to be executed asynchronously without creating a new thread for each task.
Design Principles
Worker Thread Model: Each worker runs in its own thread, processing jobs from the shared queue.
Shared Job Queue: A single, thread-safe queue holds all pending jobs.
Job-Based Work Units: Jobs encapsulate work to be executed.
Non-Blocking Submission: Adding jobs to the pool never blocks the caller thread.
Cooperative Shutdown: Workers can complete current jobs before stopping.
Thread Safety
All public methods of this class are thread-safe and can be called from any thread. The underlying job_queue is also thread-safe, allowing multiple workers to dequeue jobs concurrently.
Performance Considerations
The number of worker threads should typically be close to the number of available CPU cores for CPU-bound tasks.
For I/O-bound tasks, more threads may be beneficial to maximize throughput while some threads are blocked on I/O.
Very large thread pools (significantly more threads than cores) may degrade performance due to context switching overhead.
See also
thread_worker The worker thread class used by the pool
job_queue The shared queue for storing pending jobs
typed_thread_pool_module::typed_thread_pool For a priority-based version
The thread_pool class manages a group of worker threads that process jobs from a shared job_queue. This implementation provides:
Efficient reuse of threads to reduce thread creation/destruction overhead
Controlled concurrency through a fixed or dynamic thread count
A simple interface for submitting jobs of various types
Graceful handling of thread startup, execution, and shutdown
The thread pool is designed for scenarios where many short-lived tasks need to be executed asynchronously without creating a new thread for each task.
Design Principles
Worker Thread Model: Each worker runs in its own thread, processing jobs from the shared queue.
Shared Job Queue: A single, thread-safe queue holds all pending jobs.
Job-Based Work Units: Jobs encapsulate work to be executed.
Non-Blocking Submission: Adding jobs to the pool never blocks the caller thread.
Cooperative Shutdown: Workers can complete current jobs before stopping.
Thread Safety
All public methods of this class are thread-safe and can be called from any thread. The underlying job_queue is also thread-safe, allowing multiple workers to dequeue jobs concurrently.
Performance Considerations
The number of worker threads should typically be close to the number of available CPU cores for CPU-bound tasks.
For I/O-bound tasks, more threads may be beneficial to maximize throughput while some threads are blocked on I/O.
Very large thread pools (significantly more threads than cores) may degrade performance due to context switching overhead.
See also
thread_worker The worker thread class used by the pool
job_queue The shared queue for storing pending jobs
typed_thread_pool_module::typed_thread_pool For a priority-based version
The thread_pool class manages a group of worker threads that process jobs from a shared job_queue. This implementation provides:
Efficient reuse of threads to reduce thread creation/destruction overhead
Controlled concurrency through a fixed or dynamic thread count
A simple interface for submitting jobs of various types
Graceful handling of thread startup, execution, and shutdown
The thread pool is designed for scenarios where many short-lived tasks need to be executed asynchronously without creating a new thread for each task.
Design Principles
Worker Thread Model: Each worker runs in its own thread, processing jobs from the shared queue.
Shared Job Queue: A single, thread-safe queue holds all pending jobs.
Job-Based Work Units: Jobs encapsulate work to be executed.
Non-Blocking Submission: Adding jobs to the pool never blocks the caller thread.
Cooperative Shutdown: Workers can complete current jobs before stopping.
Thread Safety
All public methods of this class are thread-safe and can be called from any thread. The underlying job_queue is also thread-safe, allowing multiple workers to dequeue jobs concurrently.
Performance Considerations
The number of worker threads should typically be close to the number of available CPU cores for CPU-bound tasks.
For I/O-bound tasks, more threads may be beneficial to maximize throughput while some threads are blocked on I/O.
Very large thread pools (significantly more threads than cores) may degrade performance due to context switching overhead.
See also
thread_worker The worker thread class used by the pool
job_queue The shared queue for storing pending jobs
typed_thread_pool_module::typed_thread_pool For a priority-based version
Definition at line 116 of file thread_pool.h.
Constructor & Destructor Documentation
thread_pool() [1/3]
thread_pool_module::thread_pool::thread_pool (const std::string & thread_title = "thread_pool", const thread_context & context = thread_context())
Constructs a new thread_pool instance.
Constructs a thread pool with adaptive job queue.
Parameters
thread_title An optional title or identifier for the thread pool (defaults to "thread_pool").
context Optional thread context for logging and monitoring (defaults to empty context).
This title can be used for logging or debugging purposes. The context provides access to logging and monitoring services.
Implementation details:
Initializes with provided thread title for identification
Creates adaptive job queue that automatically optimizes based on contention
Pool starts in stopped state (start_pool_ = false)
No workers are initially assigned (workers_ is empty)
Stores thread context for logging and monitoring
Adaptive Queue Strategy:
ADAPTIVE mode automatically switches between mutex and lock-free implementations
Provides optimal performance across different contention levels
Eliminates need for manual queue strategy selection
Parameters
thread_title Descriptive name for this thread pool instance
context Thread context providing logging and monitoring services
Definition at line 72 of file thread_pool.cpp.
References thread_module::thread_context::monitoring(), monitoring_interface::thread_pool_metrics::pool_instance_id, monitoring_interface::thread_pool_metrics::pool_name, monitoring_interface::thread_pool_metrics::timestamp, thread_module::thread_context::update_thread_pool_metrics(), and monitoring_interface::thread_pool_metrics::worker_threads.
~thread_pool() [1/3]
thread_pool_module::thread_pool::~thread_pool (void) virtual
Virtual destructor.
Destroys the thread pool, ensuring all workers are stopped.
Cleans up resources used by the thread pool.
If the pool is still running, this typically calls stop() internally to ensure all worker threads are properly shut down.
Implementation details:
Automatically calls stop() to ensure clean shutdown
Workers will complete current jobs before terminating
Prevents resource leaks from running threads
Definition at line 99 of file thread_pool.cpp.
References stop().
thread_pool() [2/3]
thread_pool_module::thread_pool::thread_pool (const std::string & thread_title = "thread_pool", const thread_context & context = thread_context())
Constructs a new thread_pool instance.
Parameters
thread_title An optional title or identifier for the thread pool (defaults to "thread_pool").
context Optional thread context for logging and monitoring (defaults to empty context).
This title can be used for logging or debugging purposes. The context provides access to logging and monitoring services.
~thread_pool() [2/3]
virtual thread_pool_module::thread_pool::~thread_pool (void) virtual
Virtual destructor.
Cleans up resources used by the thread pool.
If the pool is still running, this typically calls stop() internally to ensure all worker threads are properly shut down.
thread_pool() [3/3]
thread_pool_module::thread_pool::thread_pool (const std::string & thread_title = "thread_pool", const thread_context & context = thread_context())
Constructs a new thread_pool instance.
Parameters
thread_title An optional title or identifier for the thread pool (defaults to "thread_pool").
context Optional thread context for logging and monitoring (defaults to empty context).
This title can be used for logging or debugging purposes. The context provides access to logging and monitoring services.
~thread_pool() [3/3]
virtual thread_pool_module::thread_pool::~thread_pool (void) virtual
Virtual destructor.
Cleans up resources used by the thread pool.
If the pool is still running, this typically calls stop() internally to ensure all worker threads are properly shut down.
Member Function Documentation
enqueue() [1/6]
auto thread_pool_module::thread_pool::enqueue (std::unique_ptr< job > && job) -> std::optional<std::string>
Enqueues a new job into the shared job_queue.
Adds a single job to the thread pool for processing.
Parameters
job A std::unique_ptr<job> representing the work to be done.
Returns
std::optional<std::string> containing an error message if the enqueue operation fails, or std::nullopt on success.
Example:
auto pool = std::make_shared<thread_pool_module::thread_pool>();
pool->start();
auto my_job = std::make_unique<callback_job>(
       // some callback...
);
if (auto err = pool->enqueue(std::move(my_job))) {
    // handle error
}
Implementation details:
Validates job pointer before submission
Validates queue availability
Delegates to adaptive job queue for optimal scheduling
Job will be processed by next available worker thread
Queue Behavior:
Adaptive queue automatically selects best strategy (mutex/lock-free)
Jobs are processed in FIFO order within the selected strategy
Workers are notified when jobs become available
Thread Safety:
Safe to call from multiple threads simultaneously
Adaptive queue handles contention efficiently
Parameters
job Unique pointer to job (ownership transferred)
Returns
std::nullopt on success, error message on failure
Definition at line 198 of file thread_pool.cpp.
enqueue() [2/6]
auto thread_pool_module::thread_pool::enqueue (std::unique_ptr< job > && job) -> std::optional< std::string >
Enqueues a new job into the shared job_queue.
Parameters
job A std::unique_ptr<job> representing the work to be done.
Returns
std::optional<std::string> containing an error message if the enqueue operation fails, or std::nullopt on success.
Example:
auto pool = std::make_shared<thread_pool_module::thread_pool>();
pool->start();
auto my_job = std::make_unique<callback_job>(
       // some callback...
);
if (auto err = pool->enqueue(std::move(my_job))) {
    // handle error
}
enqueue() [3/6]
auto thread_pool_module::thread_pool::enqueue (std::unique_ptr< job > && job) -> std::optional< std::string >
Enqueues a new job into the shared job_queue.
Parameters
job A std::unique_ptr<job> representing the work to be done.
Returns
std::optional<std::string> containing an error message if the enqueue operation fails, or std::nullopt on success.
Example:
auto pool = std::make_shared<thread_pool_module::thread_pool>();
pool->start();
auto my_job = std::make_unique<callback_job>(
       // some callback...
);
if (auto err = pool->enqueue(std::move(my_job))) {
    // handle error
}
enqueue() [4/6]
auto thread_pool_module::thread_pool::enqueue (std::unique_ptr< thread_worker > && worker) -> std::optional<std::string>
Adds a thread_worker to the thread pool for specialized or additional processing.
Parameters
worker A std::unique_ptr<thread_worker> object.
Returns
std::optional<std::string> containing an error message if the operation fails, or std::nullopt on success.
Each worker is stored in workers_. When start() is called, these workers begin running and can process jobs from the job_queue.
Definition at line 243 of file thread_pool.cpp.
enqueue() [5/6]
auto thread_pool_module::thread_pool::enqueue (std::unique_ptr< thread_worker > && worker) -> std::optional< std::string >
Adds a thread_worker to the thread pool for specialized or additional processing.
Parameters
worker A std::unique_ptr<thread_worker> object.
Returns
std::optional<std::string> containing an error message if the operation fails, or std::nullopt on success.
Each worker is stored in workers_. When start() is called, these workers begin running and can process jobs from the job_queue.
enqueue() [6/6]
auto thread_pool_module::thread_pool::enqueue (std::unique_ptr< thread_worker > && worker) -> std::optional< std::string >
Adds a thread_worker to the thread pool for specialized or additional processing.
Parameters
worker A std::unique_ptr<thread_worker> object.
Returns
std::optional<std::string> containing an error message if the operation fails, or std::nullopt on success.
Each worker is stored in workers_. When start() is called, these workers begin running and can process jobs from the job_queue.
enqueue_batch() [1/6]
auto thread_pool_module::thread_pool::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> std::optional<std::string>
Enqueues a batch of jobs into the shared job_queue.
Parameters
jobs A vector of std::unique_ptr<job> objects to be added.
Returns
std::optional<std::string> containing an error message if the enqueue operation fails, or std::nullopt on success.
Example:
auto pool = std::make_shared<thread_pool_module::thread_pool>();
pool->start();
std::vector<std::unique_ptr<job>> jobs;
jobs.push_back(std::make_unique<callback_job>(
    // some callback...
));
jobs.push_back(std::make_unique<callback_job>(
    // another callback...
));
if (auto err = pool->enqueue_batch(std::move(jobs))) {
    // handle error
}
Definition at line 221 of file thread_pool.cpp.
Referenced by store_job().
enqueue_batch() [2/6]
auto thread_pool_module::thread_pool::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> std::optional< std::string >
Enqueues a batch of jobs into the shared job_queue.
Parameters
jobs A vector of std::unique_ptr<job> objects to be added.
Returns
std::optional<std::string> containing an error message if the enqueue operation fails, or std::nullopt on success.
Example:
auto pool = std::make_shared<thread_pool_module::thread_pool>();
pool->start();
std::vector<std::unique_ptr<job>> jobs;
jobs.push_back(std::make_unique<callback_job>(
    // some callback...
));
jobs.push_back(std::make_unique<callback_job>(
    // another callback...
));
if (auto err = pool->enqueue_batch(std::move(jobs))) {
    // handle error
}
enqueue_batch() [3/6]
auto thread_pool_module::thread_pool::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> std::optional< std::string >
Enqueues a batch of jobs into the shared job_queue.
Parameters
jobs A vector of std::unique_ptr<job> objects to be added.
Returns
std::optional<std::string> containing an error message if the enqueue operation fails, or std::nullopt on success.
Example:
auto pool = std::make_shared<thread_pool_module::thread_pool>();
pool->start();
std::vector<std::unique_ptr<job>> jobs;
jobs.push_back(std::make_unique<callback_job>(
    // some callback...
));
jobs.push_back(std::make_unique<callback_job>(
    // another callback...
));
if (auto err = pool->enqueue_batch(std::move(jobs))) {
    // handle error
}
enqueue_batch() [4/6]
auto thread_pool_module::thread_pool::enqueue_batch (std::vector< std::unique_ptr< thread_worker > > && workers) -> std::optional<std::string>
Adds a batch of thread_worker objects to the thread pool.
Parameters
workers A vector of std::unique_ptr<thread_worker> objects.
Returns
std::optional<std::string> containing an error message if the operation fails, or std::nullopt on success.
Each worker is stored in workers_. When start() is called, these workers begin running and can process jobs from the job_queue.
Definition at line 273 of file thread_pool.cpp.
enqueue_batch() [5/6]
auto thread_pool_module::thread_pool::enqueue_batch (std::vector< std::unique_ptr< thread_worker > > && workers) -> std::optional< std::string >
Adds a batch of thread_worker objects to the thread pool.
Parameters
workers A vector of std::unique_ptr<thread_worker> objects.
Returns
std::optional<std::string> containing an error message if the operation fails, or std::nullopt on success.
Each worker is stored in workers_. When start() is called, these workers begin running and can process jobs from the job_queue.
enqueue_batch() [6/6]
auto thread_pool_module::thread_pool::enqueue_batch (std::vector< std::unique_ptr< thread_worker > > && workers) -> std::optional< std::string >
Adds a batch of thread_worker objects to the thread pool.
Parameters
workers A vector of std::unique_ptr<thread_worker> objects.
Returns
std::optional<std::string> containing an error message if the operation fails, or std::nullopt on success.
Each worker is stored in workers_. When start() is called, these workers begin running and can process jobs from the job_queue.
get_context() [1/3]
auto thread_pool_module::thread_pool::get_context (void) const -> const thread_context&
Gets the thread context for this pool.
Returns
The thread context providing access to logging and monitoring services.
Definition at line 355 of file thread_pool.cpp.
get_context() [2/3]
auto thread_pool_module::thread_pool::get_context (void) const -> const thread_context &
Gets the thread context for this pool.
Returns
The thread context providing access to logging and monitoring services.
get_context() [3/3]
auto thread_pool_module::thread_pool::get_context (void) const -> const thread_context &
Gets the thread context for this pool.
Returns
The thread context providing access to logging and monitoring services.
get_idle_worker_count() [1/3]
std::size_t thread_pool_module::thread_pool::get_idle_worker_count () const
Get the number of idle workers.
Returns
Number of workers currently not processing jobs.
Definition at line 389 of file thread_pool.cpp.
Referenced by report_metrics().
get_idle_worker_count() [2/3]
std::size_t thread_pool_module::thread_pool::get_idle_worker_count () const
Get the number of idle workers.
Returns
Number of workers currently not processing jobs.
get_idle_worker_count() [3/3]
std::size_t thread_pool_module::thread_pool::get_idle_worker_count () const
Get the number of idle workers.
Returns
Number of workers currently not processing jobs.
get_job_queue() [1/3]
auto thread_pool_module::thread_pool::get_job_queue (void) -> std::shared_ptr<job_queue>
Returns the shared job_queue used by this thread pool.
Returns the shared job queue used by all workers.
Returns
A std::shared_ptr<job_queue> that stores the queued jobs.
The returned queue is shared among all worker threads in the pool, which can concurrently dequeue and process jobs.
Implementation details:
Provides access to the adaptive job queue for external job submission
Queue is shared among all workers for load balancing
Adaptive queue automatically optimizes based on contention patterns
Returns
Shared pointer to the job queue
Definition at line 175 of file thread_pool.cpp.
get_job_queue() [2/3]
auto thread_pool_module::thread_pool::get_job_queue (void) -> std::shared_ptr< job_queue >
Returns the shared job_queue used by this thread pool.
Returns
A std::shared_ptr<job_queue> that stores the queued jobs.
The returned queue is shared among all worker threads in the pool, which can concurrently dequeue and process jobs.
get_job_queue() [3/3]
auto thread_pool_module::thread_pool::get_job_queue (void) -> std::shared_ptr< job_queue >
Returns the shared job_queue used by this thread pool.
Returns
A std::shared_ptr<job_queue> that stores the queued jobs.
The returned queue is shared among all worker threads in the pool, which can concurrently dequeue and process jobs.
get_pool_instance_id() [1/3]
std::uint32_t thread_pool_module::thread_pool::get_pool_instance_id () const
Get the pool instance id.
Returns
Returns the unique instance id for this pool.
Definition at line 360 of file thread_pool.cpp.
get_pool_instance_id() [2/3]
std::uint32_t thread_pool_module::thread_pool::get_pool_instance_id () const
Get the pool instance id.
Returns
Returns the unique instance id for this pool.
get_pool_instance_id() [3/3]
std::uint32_t thread_pool_module::thread_pool::get_pool_instance_id () const
Get the pool instance id.
Returns
Returns the unique instance id for this pool.
get_ptr() [1/3]
auto thread_pool_module::thread_pool::get_ptr (void) -> std::shared_ptr<thread_pool>
Retrieves a std::shared_ptr to this thread_pool instance.
Returns a shared pointer to this thread pool instance.
Returns
A shared pointer to the current thread_pool object.
By inheriting from std::enable_shared_from_this, you can call get_ptr() within member functions to avoid storing a separate shared pointer.
Implementation details:
Uses std::enable_shared_from_this for safe shared_ptr creation
Required for passing pool reference to workers or other components
Ensures proper lifetime management in multi-threaded environment
Returns
Shared pointer to this thread_pool
Definition at line 111 of file thread_pool.cpp.
get_ptr() [2/3]
auto thread_pool_module::thread_pool::get_ptr (void) -> std::shared_ptr< thread_pool >
Retrieves a std::shared_ptr to this thread_pool instance.
Returns
A shared pointer to the current thread_pool object.
By inheriting from std::enable_shared_from_this, you can call get_ptr() within member functions to avoid storing a separate shared pointer.
get_ptr() [3/3]
auto thread_pool_module::thread_pool::get_ptr (void) -> std::shared_ptr< thread_pool >
Retrieves a std::shared_ptr to this thread_pool instance.
Returns
A shared pointer to the current thread_pool object.
By inheriting from std::enable_shared_from_this, you can call get_ptr() within member functions to avoid storing a separate shared pointer.
report_metrics() [1/3]
void thread_pool_module::thread_pool::report_metrics ()
Collect and report current thread pool metrics.
This method gathers current metrics from the pool and reports them through the monitoring interface if available.
Definition at line 365 of file thread_pool.cpp.
References get_idle_worker_count(), monitoring_interface::thread_pool_metrics::idle_threads, monitoring_interface::thread_pool_metrics::jobs_pending, thread_module::thread_context::monitoring(), monitoring_interface::thread_pool_metrics::pool_instance_id, monitoring_interface::thread_pool_metrics::pool_name, monitoring_interface::thread_pool_metrics::timestamp, thread_module::thread_context::update_thread_pool_metrics(), and monitoring_interface::thread_pool_metrics::worker_threads.
report_metrics() [2/3]
void thread_pool_module::thread_pool::report_metrics ()
Collect and report current thread pool metrics.
This method gathers current metrics from the pool and reports them through the monitoring interface if available.
report_metrics() [3/3]
void thread_pool_module::thread_pool::report_metrics ()
Collect and report current thread pool metrics.
This method gathers current metrics from the pool and reports them through the monitoring interface if available.
start() [1/3]
auto thread_pool_module::thread_pool::start (void) -> std::optional<std::string>
Starts the thread pool and all associated workers.
Starts all worker threads in the pool.
Returns
std::optional<std::string> containing an error message if the start operation fails, or std::nullopt on success.
If the pool is already running, a subsequent call to start() may return an error. On success, each thread_worker in workers_ is started, enabling them to process jobs from the job_queue_.
Implementation details:
Validates that workers have been added to the pool
Starts each worker thread individually
If any worker fails to start, stops all workers and returns error
Sets start_pool_ flag to true on successful startup
Workers begin processing jobs from the shared queue immediately
Startup Sequence:
Check that workers exist
Start each worker sequentially
On failure: stop all workers and return error message
On success: mark pool as started
Error Handling:
All-or-nothing startup (if one fails, all stop)
Provides detailed error message from failed worker
Ensures consistent pool state (either all running or all stopped)
Returns
std::nullopt on success, error message on failure
Definition at line 139 of file thread_pool.cpp.
Referenced by main().
start() [2/3]
auto thread_pool_module::thread_pool::start (void) -> std::optional< std::string >
Starts the thread pool and all associated workers.
Returns
std::optional<std::string> containing an error message if the start operation fails, or std::nullopt on success.
If the pool is already running, a subsequent call to start() may return an error. On success, each thread_worker in workers_ is started, enabling them to process jobs from the job_queue_.
start() [3/3]
auto thread_pool_module::thread_pool::start (void) -> std::optional< std::string >
Starts the thread pool and all associated workers.
Returns
std::optional<std::string> containing an error message if the start operation fails, or std::nullopt on success.
If the pool is already running, a subsequent call to start() may return an error. On success, each thread_worker in workers_ is started, enabling them to process jobs from the job_queue_.
stop() [1/3]
auto thread_pool_module::thread_pool::stop (const bool & immediately_stop = false) -> void
Stops the thread pool and all worker threads.
Parameters
immediately_stop If true, any ongoing jobs may be interrupted; if false (default), each worker attempts to finish its current job before stopping.
Once stopped, the pool's start_pool_ flag is set to false, and no further job processing occurs. Behavior of re-starting a stopped pool depends on the implementation and may require re-initialization.
Definition at line 307 of file thread_pool.cpp.
References utility_module::formatter::format().
Referenced by main(), and ~thread_pool().
stop() [2/3]
auto thread_pool_module::thread_pool::stop (const bool & immediately_stop = false) -> void
Stops the thread pool and all worker threads.
Parameters
immediately_stop If true, any ongoing jobs may be interrupted; if false (default), each worker attempts to finish its current job before stopping.
Once stopped, the pool's start_pool_ flag is set to false, and no further job processing occurs. Behavior of re-starting a stopped pool depends on the implementation and may require re-initialization.
stop() [3/3]
auto thread_pool_module::thread_pool::stop (const bool & immediately_stop = false) -> void
Stops the thread pool and all worker threads.
Parameters
immediately_stop If true, any ongoing jobs may be interrupted; if false (default), each worker attempts to finish its current job before stopping.
Once stopped, the pool's start_pool_ flag is set to false, and no further job processing occurs. Behavior of re-starting a stopped pool depends on the implementation and may require re-initialization.
to_string() [1/3]
auto thread_pool_module::thread_pool::to_string (void) const -> std::string
Provides a string representation of this thread_pool.
Returns
A string describing the pool, including its title and other optional details.
Derived classes may override this to include more diagnostic or state-related info.
Definition at line 338 of file thread_pool.cpp.
References utility_module::formatter::format_to().
Referenced by fmt::formatter< thread_pool_module::thread_pool >::format(), and main().
to_string() [2/3]
auto thread_pool_module::thread_pool::to_string (void) const -> std::string
Provides a string representation of this thread_pool.
Returns
A string describing the pool, including its title and other optional details.
Derived classes may override this to include more diagnostic or state-related info.
to_string() [3/3]
auto thread_pool_module::thread_pool::to_string (void) const -> std::string
Provides a string representation of this thread_pool.
Returns
A string describing the pool, including its title and other optional details.
Derived classes may override this to include more diagnostic or state-related info.
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/thread_pool/core/thread_pool.h
libraries/thread_system/modular_structure/core/src/thread_pool/core/thread_pool.h
libraries/thread_system/sources/thread_pool/core/thread_pool.h
libraries/thread_system/modular_structure/core/src/thread_pool/core/thread_pool.cpp
libraries/thread_system/sources/thread_pool/core/thread_pool.cpp