Messaging System: logger_module::log_sanitizer Class Reference
logger_module::log_sanitizer Class Reference
Sanitizes sensitive information from log messages.
#include <log_sanitizer.h>
Classes
struct sanitization_rule
Rule for sanitizing specific patterns.
Public Member Functions
log_sanitizer ()
Constructor.
void add_default_rules ()
Add default sanitization rules.
void add_rule (const sanitization_rule &rule)
Add custom sanitization rule.
void remove_rule (const std::string &name)
Remove a sanitization rule.
std::string sanitize (const std::string &message) const
Sanitize a message.
void set_rule_enabled (const std::string &name, bool enabled)
Enable/disable specific rules.
Static Public Member Functions
static bool was_sanitized (const std::string &original, const std::string &sanitized)
Check if sanitization changed the message.
static std::string mask_credit_card (const std::smatch &match)
static std::string mask_ssn (const std::smatch &match)
static std::string mask_email (const std::smatch &match)
static std::string mask_ip_address (const std::smatch &match)
static std::string mask_api_key (const std::smatch &match)
static std::string mask_password (const std::smatch &match)
Detailed Description
Sanitizes sensitive information from log messages.
Definition at line 21 of file log_sanitizer.h.
Constructor & Destructor Documentation
log_sanitizer()
logger_module::log_sanitizer::log_sanitizer ()
Constructor.
Definition at line 15 of file log_sanitizer.cpp.
References add_default_rules().
Member Function Documentation
add_default_rules()
void logger_module::log_sanitizer::add_default_rules ()
Add default sanitization rules.
Definition at line 19 of file log_sanitizer.cpp.
References add_rule(), mask_api_key(), mask_credit_card(), mask_email(), mask_ip_address(), mask_password(), and mask_ssn().
Referenced by log_sanitizer().
add_rule()
void logger_module::log_sanitizer::add_rule (const sanitization_rule & rule)
Add custom sanitization rule.
Parameters
rule The sanitization rule
Definition at line 65 of file log_sanitizer.cpp.
References logger_module::log_sanitizer::sanitization_rule::name.
Referenced by add_default_rules().
mask_api_key()
std::string logger_module::log_sanitizer::mask_api_key (const std::smatch & match) static
Definition at line 203 of file log_sanitizer.cpp.
Referenced by add_default_rules().
mask_credit_card()
std::string logger_module::log_sanitizer::mask_credit_card (const std::smatch & match) static
Definition at line 136 of file log_sanitizer.cpp.
Referenced by add_default_rules().
mask_email()
std::string logger_module::log_sanitizer::mask_email (const std::smatch & match) static
Definition at line 170 of file log_sanitizer.cpp.
Referenced by add_default_rules().
mask_ip_address()
std::string logger_module::log_sanitizer::mask_ip_address (const std::smatch & match) static
Definition at line 190 of file log_sanitizer.cpp.
Referenced by add_default_rules().
mask_password()
std::string logger_module::log_sanitizer::mask_password (const std::smatch & match) static
Definition at line 223 of file log_sanitizer.cpp.
Referenced by add_default_rules().
mask_ssn()
std::string logger_module::log_sanitizer::mask_ssn (const std::smatch & match) static
Definition at line 161 of file log_sanitizer.cpp.
Referenced by add_default_rules().
remove_rule()
void logger_module::log_sanitizer::remove_rule (const std::string & name)
Remove a sanitization rule.
Parameters
name Rule name
Definition at line 71 of file log_sanitizer.cpp.
sanitize()
std::string logger_module::log_sanitizer::sanitize (const std::string & message) const
Sanitize a message.
Parameters
message The message to sanitize
Returns
Sanitized message
Definition at line 83 of file log_sanitizer.cpp.
set_rule_enabled()
void logger_module::log_sanitizer::set_rule_enabled (const std::string & name, bool enabled)
Enable/disable specific rules.
Parameters
name Rule name
enabled Whether to enable the rule
Definition at line 126 of file log_sanitizer.cpp.
was_sanitized()
bool logger_module::log_sanitizer::was_sanitized (const std::string & original, const std::string & sanitized) static
Check if sanitization changed the message.
Parameters
original Original message
sanitized Sanitized message
Returns
true if message was modified
Definition at line 131 of file log_sanitizer.cpp.
The documentation for this class was generated from the following files:
libraries/logger_system/sources/logger/security/log_sanitizer.h
libraries/logger_system/sources/logger/security/log_sanitizer.cpp