Messaging System: libraries/thread_system/tests/benchmarks/thread_base_benchmarks/quick_mpmc_test_google.cpp File Reference
quick_mpmc_test_google.cpp File Reference
#include <benchmark/benchmark.h>
#include <thread>
#include <vector>
#include <atomic>
#include "job_queue.h"
#include "lockfree/queues/lockfree_job_queue.h"
#include "callback_job.h"
Functions
template<typename QueueType >
static void run_producer_consumer_test (QueueType &queue, size_t num_producers, size_t num_consumers, size_t ops_per_thread)
static void BM_MutexQueue (benchmark::State &state)
Benchmark mutex-based queue.
static void BM_LockFreeQueue (benchmark::State &state)
Benchmark lock-free queue.
Args ({1, 1, 10000}) -> Unit(benchmark::kMillisecond)
Args ({2, 2, 5000}) -> Unit(benchmark::kMillisecond)
Args ({4, 4, 2500}) -> Unit(benchmark::kMillisecond)
Args ({8, 8, 1250}) -> Unit(benchmark::kMillisecond)
Args ({16, 1, 625}) -> Unit(benchmark::kMillisecond)
Args ({1, 16, 10000}) -> Unit(benchmark::kMillisecond)
BENCHMARK_MAIN ()
Function Documentation
Args() [1/6]
Args ({1, 1, 10000}) -> Unit(benchmark::kMillisecond)
Args() [2/6]
Args ({1, 16, 10000}) -> Unit(benchmark::kMillisecond)
Args() [3/6]
Args ({16, 1, 625}) -> Unit(benchmark::kMillisecond)
Args() [4/6]
Args ({2, 2, 5000}) -> Unit(benchmark::kMillisecond)
Args() [5/6]
Args ({4, 4, 2500}) -> Unit(benchmark::kMillisecond)
Args() [6/6]
Args ({8, 8, 1250}) -> Unit(benchmark::kMillisecond)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_LockFreeQueue()
static void BM_LockFreeQueue (benchmark::State & state) static
Benchmark lock-free queue.
Definition at line 101 of file quick_mpmc_test_google.cpp.
References run_producer_consumer_test().
BM_MutexQueue()
static void BM_MutexQueue (benchmark::State & state) static
Benchmark mutex-based queue.
Definition at line 82 of file quick_mpmc_test_google.cpp.
References run_producer_consumer_test().
run_producer_consumer_test()
template<typename QueueType > static void run_producer_consumer_test (QueueType & queue, size_t num_producers, size_t num_consumers, size_t ops_per_thread) static
Definition at line 23 of file quick_mpmc_test_google.cpp.
References kcenon::thread::result< T >::has_value(), and kcenon::thread::result< T >::value().
Referenced by BM_LockFreeQueue(), and BM_MutexQueue().