Messaging System: MessagingIntegrationTest Class Reference
MessagingIntegrationTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void SetUp () override
void TearDown () override
Protected Attributes
messaging_config config_
std::unique_ptr< system_integrator > integrator_
Detailed Description
Definition at line 13 of file test_messaging_integration.cpp.
Member Function Documentation
SetUp() [1/2]
void MessagingIntegrationTest::SetUp () inline override protected
Definition at line 15 of file test_messaging_integration.cpp.
References kcenon::messaging::config::config_builder::build(), config_, kcenon::messaging::config::config_builder::enable_compression(), integrator_, kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), and kcenon::messaging::config::config_builder::set_worker_threads().
SetUp() [2/2]
void MessagingIntegrationTest::SetUp () inline override protected
Definition at line 23 of file test_messaging_integration.cpp.
TearDown() [1/2]
void MessagingIntegrationTest::TearDown () inline override protected
Definition at line 28 of file test_messaging_integration.cpp.
References integrator_.
TearDown() [2/2]
void MessagingIntegrationTest::TearDown () inline override protected
Definition at line 27 of file test_messaging_integration.cpp.
Member Data Documentation
config_
messaging_config MessagingIntegrationTest::config_ protected
Definition at line 34 of file test_messaging_integration.cpp.
Referenced by SetUp().
integrator_
std::unique_ptr<system_integrator> MessagingIntegrationTest::integrator_ protected
Definition at line 35 of file test_messaging_integration.cpp.
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following files:
application_layer/tests/integration/test_messaging_integration.cpp
libraries/container_system/tests/test_messaging_integration.cpp