Messaging System: kcenon::thread::event_bus::subscription Class Reference
kcenon::thread::event_bus::subscription Class Reference
Subscription handle for managing subscriptions.
#include <event_bus.h>
Public Member Functions
subscription ()=default
subscription (event_bus *bus, std::type_index type, std::size_t id)
void unsubscribe ()
Unsubscribe from events.
bool is_active () const
Check if subscription is active.
subscription (subscription &&other) noexcept
subscription & operator= (subscription &&other) noexcept
subscription (const subscription &)=delete
subscription & operator= (const subscription &)=delete
~subscription ()
Detailed Description
Subscription handle for managing subscriptions.
Definition at line 54 of file event_bus.h.
Constructor & Destructor Documentation
subscription() [1/4]
kcenon::thread::event_bus::subscription::subscription () default
subscription() [2/4]
kcenon::thread::event_bus::subscription::subscription (event_bus * bus, std::type_index type, std::size_t id) inline
Definition at line 57 of file event_bus.h.
subscription() [3/4]
kcenon::thread::event_bus::subscription::subscription (subscription && other) inline noexcept
Definition at line 78 of file event_bus.h.
subscription() [4/4]
kcenon::thread::event_bus::subscription::subscription (const subscription &) delete
~subscription()
kcenon::thread::event_bus::subscription::~subscription () inline
Definition at line 98 of file event_bus.h.
References unsubscribe().
Member Function Documentation
is_active()
bool kcenon::thread::event_bus::subscription::is_active () const inline
Check if subscription is active.
Definition at line 73 of file event_bus.h.
operator=() [1/2]
subscription & kcenon::thread::event_bus::subscription::operator= (const subscription &) delete
operator=() [2/2]
subscription & kcenon::thread::event_bus::subscription::operator= (subscription && other) inline noexcept
Definition at line 83 of file event_bus.h.
References unsubscribe().
unsubscribe()
void kcenon::thread::event_bus::subscription::unsubscribe () inline
Unsubscribe from events.
Definition at line 63 of file event_bus.h.
Referenced by operator=(), and ~subscription().
The documentation for this class was generated from the following file:
libraries/thread_system/include/kcenon/thread/core/event_bus.h