Messaging System: monitoring_system::distributed_tracer Class Reference
monitoring_system::distributed_tracer Class Reference
Distributed tracer for managing spans and traces.
#include <distributed_tracer.h>
Classes
struct tracer_impl
Private implementation of distributed tracer.
Public Member Functions
std::shared_ptr< trace_span > start_span (const std::string &name)
result< std::shared_ptr< trace_span > > start_span (const std::string &name, const std::string &service)
result< trace_context > extract_context_from_carrier (const std::map< std::string, std::string > &headers)
result< std::shared_ptr< trace_span > > start_span_from_context (const trace_context &context, const std::string &name)
result< std::shared_ptr< trace_span > > start_child_span (std::shared_ptr< trace_span > parent, const std::string &name)
void finish_span (std::shared_ptr< trace_span > span)
void inject_context_into_carrier (const trace_context &context, std::map< std::string, std::string > &headers)
trace_context get_context_from_span (std::shared_ptr< trace_span > span)
result< std::vector< std::shared_ptr< trace_span > > > get_trace (const std::string &trace_id)
std::shared_ptr< trace_span > get_current_span ()
distributed_tracer ()
~distributed_tracer ()
distributed_tracer (const distributed_tracer &)=delete
distributed_tracer & operator= (const distributed_tracer &)=delete
distributed_tracer (distributed_tracer &&) noexcept
distributed_tracer & operator= (distributed_tracer &&) noexcept
monitoring_system::result< std::shared_ptr< trace_span > > start_span (const std::string &operation_name, const std::string &service_name="monitoring_system")
Start a new root span.
monitoring_system::result< std::shared_ptr< trace_span > > start_child_span (const trace_span &parent, const std::string &operation_name)
Start a child span.
monitoring_system::result< std::shared_ptr< trace_span > > start_span_from_context (const trace_context &context, const std::string &operation_name)
Start a span from trace context (for incoming requests)
monitoring_system::result< bool > finish_span (std::shared_ptr< trace_span > span)
Finish a span.
std::shared_ptr< trace_span > get_current_span () const
Get current active span for this thread.
void set_current_span (std::shared_ptr< trace_span > span)
Set current active span for this thread.
trace_context extract_context (const trace_span &span) const
Extract trace context for propagation.
template<typename Carrier >
void inject_context (const trace_context &context, Carrier &carrier)
Inject trace context into carrier (e.g., HTTP headers)
template<typename Carrier >
monitoring_system::result< trace_context > extract_context_from_carrier (const Carrier &carrier)
Extract trace context from carrier.
monitoring_system::result< std::vector< trace_span > > get_trace (const std::string &trace_id) const
Get all spans for a trace.
monitoring_system::result< bool > export_spans (std::vector< trace_span > spans)
Export spans to external system.
Static Public Member Functions
static distributed_tracer & instance ()
Detailed Description
Distributed tracer for managing spans and traces.
Definition at line 105 of file distributed_tracer.h.
Constructor & Destructor Documentation
distributed_tracer() [1/3]
monitoring_system::distributed_tracer::distributed_tracer ()
Definition at line 71 of file distributed_tracer.cpp.
~distributed_tracer()
monitoring_system::distributed_tracer::~distributed_tracer () default
distributed_tracer() [2/3]
monitoring_system::distributed_tracer::distributed_tracer (const distributed_tracer &) delete
distributed_tracer() [3/3]
monitoring_system::distributed_tracer::distributed_tracer (distributed_tracer &&) default noexcept
Member Function Documentation
export_spans()
monitoring_system::result< bool > monitoring_system::distributed_tracer::export_spans (std::vector< trace_span > spans)
Export spans to external system.
Definition at line 205 of file distributed_tracer.cpp.
References monitoring_system::error_info::code, monitoring_system::result< T >::get_error(), and monitoring_system::invalid_state.
extract_context()
trace_context monitoring_system::distributed_tracer::extract_context (const trace_span & span) const
Extract trace context for propagation.
Definition at line 185 of file distributed_tracer.cpp.
References monitoring_system::trace_context::baggage, monitoring_system::trace_context::span_id, monitoring_system::trace_context::trace_flags, and monitoring_system::trace_context::trace_id.
extract_context_from_carrier() [1/2]
template<typename Carrier > monitoring_system::result< trace_context > monitoring_system::distributed_tracer::extract_context_from_carrier (const Carrier & carrier) inline
Extract trace context from carrier.
Definition at line 253 of file distributed_tracer.h.
References monitoring_system::trace_context::from_w3c_traceparent(), and monitoring_system::not_found.
extract_context_from_carrier() [2/2]
result< trace_context > monitoring_system::distributed_tracer::extract_context_from_carrier (const std::map< std::string, std::string > & headers) inline
Definition at line 125 of file distributed_tracer.h.
References monitoring_system::trace_context::span_id, and monitoring_system::trace_context::trace_id.
Referenced by WebService::handle_request(), and main().
finish_span() [1/2]
monitoring_system::result< bool > monitoring_system::distributed_tracer::finish_span (std::shared_ptr< trace_span > span) inline
Definition at line 156 of file distributed_tracer.h.
Referenced by analyze_traces(), WebService::handle_request(), and main().
finish_span() [2/2]
monitoring_system::result< bool > monitoring_system::distributed_tracer::finish_span (std::shared_ptr< trace_span > span)
Finish a span.
get_context_from_span()
trace_context monitoring_system::distributed_tracer::get_context_from_span (std::shared_ptr< trace_span > span) inline
Definition at line 169 of file distributed_tracer.h.
Referenced by main().
get_current_span() [1/2]
std::shared_ptr< trace_span > monitoring_system::distributed_tracer::get_current_span () inline
Definition at line 185 of file distributed_tracer.h.
Referenced by TEST_F().
get_current_span() [2/2]
std::shared_ptr< trace_span > monitoring_system::distributed_tracer::get_current_span () const
Get current active span for this thread.
Definition at line 177 of file distributed_tracer.cpp.
get_trace() [1/2]
result< std::vector< std::shared_ptr< trace_span > > > monitoring_system::distributed_tracer::get_trace (const std::string & trace_id) inline
Definition at line 177 of file distributed_tracer.h.
Referenced by analyze_traces().
get_trace() [2/2]
monitoring_system::result< std::vector< trace_span > > monitoring_system::distributed_tracer::get_trace (const std::string & trace_id) const
Get all spans for a trace.
Definition at line 194 of file distributed_tracer.cpp.
References monitoring_system::not_found.
inject_context()
template<typename Carrier > void monitoring_system::distributed_tracer::inject_context (const trace_context & context, Carrier & carrier) inline
Inject trace context into carrier (e.g., HTTP headers)
Definition at line 238 of file distributed_tracer.h.
References monitoring_system::trace_context::to_w3c_traceparent().
inject_context_into_carrier()
void monitoring_system::distributed_tracer::inject_context_into_carrier (const trace_context & context, std::map< std::string, std::string > & headers) inline
Definition at line 163 of file distributed_tracer.h.
References monitoring_system::trace_context::span_id, and monitoring_system::trace_context::trace_id.
Referenced by main().
instance()
static distributed_tracer & monitoring_system::distributed_tracer::instance () inline static
Definition at line 107 of file distributed_tracer.h.
Referenced by monitoring_system::global_tracer().
operator=() [1/2]
distributed_tracer & monitoring_system::distributed_tracer::operator= (const distributed_tracer &) delete
operator=() [2/2]
distributed_tracer & monitoring_system::distributed_tracer::operator= (distributed_tracer &&) default noexcept
set_current_span()
void monitoring_system::distributed_tracer::set_current_span (std::shared_ptr< trace_span > span)
Set current active span for this thread.
Definition at line 181 of file distributed_tracer.cpp.
start_child_span() [1/2]
monitoring_system::result< std::shared_ptr< trace_span > > monitoring_system::distributed_tracer::start_child_span (const trace_span & parent, const std::string & operation_name)
Start a child span.
Definition at line 110 of file distributed_tracer.cpp.
References monitoring_system::trace_span::baggage, monitoring_system::trace_span::service_name, monitoring_system::trace_span::span_id, and monitoring_system::trace_span::trace_id.
start_child_span() [2/2]
result< std::shared_ptr< trace_span > > monitoring_system::distributed_tracer::start_child_span (std::shared_ptr< trace_span > parent, const std::string & name) inline
Definition at line 148 of file distributed_tracer.h.
Referenced by analyze_traces(), and main().
start_span() [1/3]
std::shared_ptr< trace_span > monitoring_system::distributed_tracer::start_span (const std::string & name) inline
Definition at line 113 of file distributed_tracer.h.
Referenced by analyze_traces(), WebService::handle_request(), and main().
start_span() [2/3]
monitoring_system::result< std::shared_ptr< trace_span > > monitoring_system::distributed_tracer::start_span (const std::string & name, const std::string & service) inline
Definition at line 118 of file distributed_tracer.h.
References monitoring_system::service.
start_span() [3/3]
monitoring_system::result< std::shared_ptr< trace_span > > monitoring_system::distributed_tracer::start_span (const std::string & operation_name, const std::string & service_name = "monitoring_system")
Start a new root span.
start_span_from_context() [1/2]
monitoring_system::result< std::shared_ptr< trace_span > > monitoring_system::distributed_tracer::start_span_from_context (const trace_context & context, const std::string & name) inline
Definition at line 140 of file distributed_tracer.h.
References monitoring_system::trace_context::span_id, and monitoring_system::trace_context::trace_id.
Referenced by WebService::handle_request(), and main().
start_span_from_context() [2/2]
monitoring_system::result< std::shared_ptr< trace_span > > monitoring_system::distributed_tracer::start_span_from_context (const trace_context & context, const std::string & operation_name)
Start a span from trace context (for incoming requests)
The documentation for this class was generated from the following files:
libraries/monitoring_system/include/monitoring/tracing/distributed_tracer.h
libraries/monitoring_system/src/impl/tracing/distributed_tracer.h
libraries/monitoring_system/src/impl/tracing/distributed_tracer.cpp