Messaging System: monitoring_system::performance_metrics Struct Reference
monitoring_system::performance_metrics Struct Reference
Performance metrics for a specific operation.
#include <performance_monitor.h>
Public Member Functions
void update_statistics (const std::vector< std::chrono::nanoseconds > &durations)
Update statistics with new duration samples.
Static Public Member Functions
static std::chrono::nanoseconds calculate_percentile (const std::vector< std::chrono::nanoseconds > &sorted_durations, double percentile)
Calculate percentile from sorted durations.
Public Attributes
std::string operation_name
std::chrono::nanoseconds min_duration {std::chrono::nanoseconds::max()}
std::chrono::nanoseconds max_duration {std::chrono::nanoseconds::zero()}
std::chrono::nanoseconds total_duration {std::chrono::nanoseconds::zero()}
std::chrono::nanoseconds mean_duration {std::chrono::nanoseconds::zero()}
std::chrono::nanoseconds median_duration {std::chrono::nanoseconds::zero()}
std::chrono::nanoseconds p95_duration {std::chrono::nanoseconds::zero()}
std::chrono::nanoseconds p99_duration {std::chrono::nanoseconds::zero()}
std::uint64_t call_count {0}
std::uint64_t error_count {0}
double throughput {0.0}
Detailed Description
Performance metrics for a specific operation.
Definition at line 35 of file performance_monitor.h.
Member Function Documentation
calculate_percentile()
static std::chrono::nanoseconds monitoring_system::performance_metrics::calculate_percentile (const std::vector< std::chrono::nanoseconds > & sorted_durations, double percentile) inline static
Calculate percentile from sorted durations.
Definition at line 51 of file performance_monitor.h.
References monitoring_system::percentile.
Referenced by update_statistics().
update_statistics()
void monitoring_system::performance_metrics::update_statistics (const std::vector< std::chrono::nanoseconds > & durations) inline
Update statistics with new duration samples.
Definition at line 68 of file performance_monitor.h.
References calculate_percentile(), max_duration, mean_duration, median_duration, min_duration, p95_duration, p99_duration, and total_duration.
Member Data Documentation
call_count
std::uint64_t monitoring_system::performance_metrics::call_count {0}
Definition at line 44 of file performance_monitor.h.
Referenced by monitoring_system::performance_profiler::get_metrics().
error_count
std::uint64_t monitoring_system::performance_metrics::error_count {0}
Definition at line 45 of file performance_monitor.h.
Referenced by monitoring_system::performance_profiler::get_metrics().
max_duration
std::chrono::nanoseconds monitoring_system::performance_metrics::max_duration {std::chrono::nanoseconds::zero()}
Definition at line 38 of file performance_monitor.h.
Referenced by monitoring_system::performance_profiler::get_metrics(), and update_statistics().
mean_duration
std::chrono::nanoseconds monitoring_system::performance_metrics::mean_duration {std::chrono::nanoseconds::zero()}
Definition at line 40 of file performance_monitor.h.
Referenced by monitoring_system::performance_profiler::get_metrics(), and update_statistics().
median_duration
std::chrono::nanoseconds monitoring_system::performance_metrics::median_duration {std::chrono::nanoseconds::zero()}
Definition at line 41 of file performance_monitor.h.
Referenced by update_statistics().
min_duration
std::chrono::nanoseconds monitoring_system::performance_metrics::min_duration {std::chrono::nanoseconds::max()}
Definition at line 37 of file performance_monitor.h.
Referenced by monitoring_system::performance_profiler::get_metrics(), and update_statistics().
operation_name
std::string monitoring_system::performance_metrics::operation_name
Definition at line 36 of file performance_monitor.h.
Referenced by monitoring_system::performance_profiler::get_metrics().
p95_duration
std::chrono::nanoseconds monitoring_system::performance_metrics::p95_duration {std::chrono::nanoseconds::zero()}
Definition at line 42 of file performance_monitor.h.
Referenced by update_statistics().
p99_duration
std::chrono::nanoseconds monitoring_system::performance_metrics::p99_duration {std::chrono::nanoseconds::zero()}
Definition at line 43 of file performance_monitor.h.
Referenced by update_statistics().
throughput
double monitoring_system::performance_metrics::throughput {0.0}
Definition at line 46 of file performance_monitor.h.
total_duration
std::chrono::nanoseconds monitoring_system::performance_metrics::total_duration {std::chrono::nanoseconds::zero()}
Definition at line 39 of file performance_monitor.h.
Referenced by update_statistics().
The documentation for this struct was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h