Messaging System: thread_module::service_container Class Reference
thread_module::service_container Class Reference
Modern service container for dependency injection.
#include <service_container.h>
Public Types
enum class lifetime { singleton , transient , singleton , transient }
Service lifetime scope.
enum class lifetime { singleton , transient , singleton , transient }
Service lifetime scope.
Public Member Functions
template<typename Interface , typename Implementation >
void register_singleton (std::shared_ptr< Implementation > instance)
Register a service with singleton lifetime.
template<typename Interface >
void register_factory (std::function< std::shared_ptr< Interface >()> factory, lifetime lt=lifetime::transient)
Register a service with factory function.
template<typename Interface , typename Implementation , typename... Args>
void register_transient ()
Register a transient service.
template<typename Interface >
std::shared_ptr< Interface > resolve ()
Resolve a service.
template<typename Interface >
bool is_registered () const
Check if a service is registered.
void clear ()
Clear all registered services.
template<typename Interface , typename Implementation >
void register_singleton (std::shared_ptr< Implementation > instance)
Register a service with singleton lifetime.
template<typename Interface >
void register_factory (std::function< std::shared_ptr< Interface >()> factory, lifetime lt=lifetime::transient)
Register a service with factory function.
template<typename Interface , typename Implementation , typename... Args>
void register_transient ()
Register a transient service.
template<typename Interface >
std::shared_ptr< Interface > resolve ()
Resolve a service.
template<typename Interface >
bool is_registered () const
Check if a service is registered.
void clear ()
Clear all registered services.
Static Public Member Functions
static service_container & global ()
Get the global service container instance.
static service_container & global ()
Get the global service container instance.
Detailed Description
Modern service container for dependency injection.
This container supports:
Registration of interfaces with concrete implementations
Factory functions for lazy instantiation
Singleton and transient lifetime management
Thread-safe operations
Definition at line 52 of file service_container.h.
Member Enumeration Documentation
lifetime [1/2]
enum class thread_module::service_container::lifetime strong
Service lifetime scope.
Enumerator
singleton
transient
singleton
transient
Definition at line 57 of file service_container.h.
lifetime [2/2]
enum class thread_module::service_container::lifetime strong
Service lifetime scope.
Enumerator
singleton
transient
singleton
transient
Definition at line 57 of file service_container.h.
Member Function Documentation
clear() [1/2]
void thread_module::service_container::clear () inline
Clear all registered services.
Definition at line 161 of file service_container.h.
Referenced by complete_integration_example(), demonstrate_minimal_usage(), dynamic_service_example(), main(), thread_pool_with_logger_example(), and thread_pool_with_monitoring_example().
clear() [2/2]
void thread_module::service_container::clear () inline
Clear all registered services.
Definition at line 161 of file service_container.h.
global() [1/2]
static service_container & thread_module::service_container::global () inline static
Get the global service container instance.
Returns
Reference to the global container
Definition at line 170 of file service_container.h.
Referenced by complete_integration_example(), demonstrate_composition(), demonstrate_minimal_usage(), dynamic_service_example(), thread_module::thread_context_builder::from_global_container(), main(), thread_module::scoped_service< Interface >::scoped_service(), thread_pool_with_logger_example(), and thread_pool_with_monitoring_example().
global() [2/2]
static service_container & thread_module::service_container::global () inline static
Get the global service container instance.
Returns
Reference to the global container
Definition at line 170 of file service_container.h.
is_registered() [1/2]
template<typename Interface > bool thread_module::service_container::is_registered () const inline
Check if a service is registered.
Template Parameters
Interface The interface type to check
Returns
true if the service is registered
Definition at line 153 of file service_container.h.
is_registered() [2/2]
template<typename Interface > bool thread_module::service_container::is_registered () const inline
Check if a service is registered.
Template Parameters
Interface The interface type to check
Returns
true if the service is registered
Definition at line 153 of file service_container.h.
register_factory() [1/2]
template<typename Interface > void thread_module::service_container::register_factory (std::function< std::shared_ptr< Interface >()> factory, lifetime lt = lifetime::transient) inline
Register a service with factory function.
Template Parameters
Interface The interface type
Parameters
factory Factory function that creates the service
lt Service lifetime (default: transient)
Definition at line 85 of file service_container.h.
register_factory() [2/2]
template<typename Interface > void thread_module::service_container::register_factory (std::function< std::shared_ptr< Interface >()> factory, lifetime lt = lifetime::transient) inline
Register a service with factory function.
Template Parameters
Interface The interface type
Parameters
factory Factory function that creates the service
lt Service lifetime (default: transient)
Definition at line 85 of file service_container.h.
register_singleton() [1/2]
template<typename Interface , typename Implementation > void thread_module::service_container::register_singleton (std::shared_ptr< Implementation > instance) inline
Register a service with singleton lifetime.
Template Parameters
Interface The interface type
Implementation The concrete implementation type
Parameters
instance Shared pointer to the implementation
Definition at line 69 of file service_container.h.
References singleton.
Referenced by complete_integration_example(), dynamic_service_example(), thread_module::scoped_service< Interface >::scoped_service(), thread_pool_with_logger_example(), and thread_pool_with_monitoring_example().
register_singleton() [2/2]
template<typename Interface , typename Implementation > void thread_module::service_container::register_singleton (std::shared_ptr< Implementation > instance) inline
Register a service with singleton lifetime.
Template Parameters
Interface The interface type
Implementation The concrete implementation type
Parameters
instance Shared pointer to the implementation
Definition at line 69 of file service_container.h.
References singleton.
register_transient() [1/2]
template<typename Interface , typename Implementation , typename... Args> void thread_module::service_container::register_transient () inline
Register a transient service.
Template Parameters
Interface The interface type
Implementation The concrete implementation type
Args Constructor argument types
Definition at line 102 of file service_container.h.
References transient.
register_transient() [2/2]
template<typename Interface , typename Implementation , typename... Args> void thread_module::service_container::register_transient () inline
Register a transient service.
Template Parameters
Interface The interface type
Implementation The concrete implementation type
Args Constructor argument types
Definition at line 102 of file service_container.h.
References transient.
resolve() [1/2]
template<typename Interface > std::shared_ptr< Interface > thread_module::service_container::resolve () inline
Resolve a service.
Template Parameters
Interface The interface type to resolve
Returns
Shared pointer to the service, or nullptr if not found
Definition at line 117 of file service_container.h.
References singleton.
Referenced by thread_module::thread_context_builder::from_global_container().
resolve() [2/2]
template<typename Interface > std::shared_ptr< Interface > thread_module::service_container::resolve () inline
Resolve a service.
Template Parameters
Interface The interface type to resolve
Returns
Shared pointer to the service, or nullptr if not found
Definition at line 117 of file service_container.h.
References singleton.
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/interfaces/service_container.h
libraries/thread_system/sources/interfaces/service_container.h