Messaging System: iot_monitoring_system Class Reference
iot_monitoring_system Class Reference
Public Member Functions
iot_monitoring_system ()
void setupMessageHandlers ()
void initializeDevices ()
void registerDevice (const std::string &device_id, device_type type, const std::string &location, double min_threshold, double max_threshold)
void handleDeviceTelemetry (const core::message &msg)
void checkThresholds (const device_config &config, const device_telemetry &telemetry)
void createAlert (const std::string &device_id, alert::severity severity, const std::string &message, double threshold, double actual)
void publishAlert (const alert &alert_obj)
void handleDeviceRegistration (const core::message &msg)
void handleDeviceCommand (const core::message &msg)
void handleSystemQuery (const core::message &msg)
void handleAlertAcknowledgment (const core::message &msg)
void storeTelemetry (const device_telemetry &telemetry)
void processAnalytics (const device_telemetry &telemetry)
void sendSystemStatus ()
void sendDeviceList ()
void sendLatestTelemetry ()
void startDeviceSimulation ()
void startAlertProcessor ()
void processAlert (const alert &alert_obj)
std::string generateAlertId () const
std::string getUnitForType (device_type type) const
std::string getSeverityString (alert::severity severity) const
int getUptime () const
void start ()
void stop ()
void startDashboard ()
void printDashboard ()
Detailed Description
Definition at line 82 of file iot_monitoring.cpp.
Constructor & Destructor Documentation
iot_monitoring_system()
iot_monitoring_system::iot_monitoring_system () inline
Definition at line 113 of file iot_monitoring.cpp.
References kcenon::messaging::config::config_builder::build(), kcenon::messaging::config::config_builder::enable_compression(), kcenon::messaging::config::config_builder::enable_external_monitoring(), initializeDevices(), kcenon::messaging::config::config_builder::set_container_max_size(), kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), kcenon::messaging::config::config_builder::set_worker_threads(), and setupMessageHandlers().
Member Function Documentation
checkThresholds()
void iot_monitoring_system::checkThresholds (const device_config & config, const device_telemetry & telemetry) inline
Definition at line 265 of file iot_monitoring.cpp.
References createAlert(), alert::CRITICAL, device_config::device_id, alert::INFO, device_config::location, device_config::max_threshold, device_config::min_threshold, MOTION_DETECTOR, device_config::type, device_telemetry::value, and alert::WARNING.
Referenced by handleDeviceTelemetry().
createAlert()
void iot_monitoring_system::createAlert (const std::string & device_id, alert::severity severity, const std::string & message, double threshold, double actual) inline
Definition at line 310 of file iot_monitoring.cpp.
References alert::actual_value, alert::alert_id, alert::device_id, generateAlertId(), getSeverityString(), alert::message, publishAlert(), alert::sev, alert::threshold_value, and alert::triggered_at.
Referenced by checkThresholds(), and processAnalytics().
generateAlertId()
std::string iot_monitoring_system::generateAlertId () const inline
Definition at line 587 of file iot_monitoring.cpp.
Referenced by createAlert().
getSeverityString()
std::string iot_monitoring_system::getSeverityString (alert::severity severity) const inline
Definition at line 603 of file iot_monitoring.cpp.
References alert::CRITICAL, alert::EMERGENCY, alert::INFO, and alert::WARNING.
Referenced by createAlert().
getUnitForType()
std::string iot_monitoring_system::getUnitForType (device_type type) const inline
Definition at line 592 of file iot_monitoring.cpp.
References ENERGY_METER, HUMIDITY_SENSOR, PRESSURE_SENSOR, SMART_LIGHT, and TEMPERATURE_SENSOR.
Referenced by handleDeviceTelemetry().
getUptime()
int iot_monitoring_system::getUptime () const inline
Definition at line 613 of file iot_monitoring.cpp.
Referenced by printDashboard(), and sendSystemStatus().
handleAlertAcknowledgment()
void iot_monitoring_system::handleAlertAcknowledgment (const core::message & msg) inline
Definition at line 409 of file iot_monitoring.cpp.
References kcenon::messaging::core::message_metadata::headers, and kcenon::messaging::core::message::metadata.
Referenced by setupMessageHandlers().
handleDeviceCommand()
void iot_monitoring_system::handleDeviceCommand (const core::message & msg) inline
Definition at line 380 of file iot_monitoring.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, and kcenon::messaging::core::message::set_priority().
Referenced by setupMessageHandlers().
handleDeviceRegistration()
void iot_monitoring_system::handleDeviceRegistration (const core::message & msg) inline
Definition at line 368 of file iot_monitoring.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, and registerDevice().
Referenced by setupMessageHandlers().
handleDeviceTelemetry()
void iot_monitoring_system::handleDeviceTelemetry (const core::message & msg) inline
Definition at line 220 of file iot_monitoring.cpp.
References checkThresholds(), device_telemetry::device_id, getUnitForType(), kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, processAnalytics(), storeTelemetry(), device_telemetry::timestamp, device_telemetry::type, device_telemetry::unit, and device_telemetry::value.
Referenced by setupMessageHandlers().
handleSystemQuery()
void iot_monitoring_system::handleSystemQuery (const core::message & msg) inline
Definition at line 397 of file iot_monitoring.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, sendDeviceList(), sendLatestTelemetry(), and sendSystemStatus().
Referenced by setupMessageHandlers().
initializeDevices()
void iot_monitoring_system::initializeDevices () inline
Definition at line 171 of file iot_monitoring.cpp.
References CAMERA, ENERGY_METER, HUMIDITY_SENSOR, MOTION_DETECTOR, registerDevice(), SMART_LIGHT, SMART_LOCK, and TEMPERATURE_SENSOR.
Referenced by iot_monitoring_system().
printDashboard()
void iot_monitoring_system::printDashboard () inline
Definition at line 668 of file iot_monitoring.cpp.
References getUptime().
Referenced by startDashboard().
processAlert()
void iot_monitoring_system::processAlert (const alert & alert_obj) inline
Definition at line 575 of file iot_monitoring.cpp.
Referenced by startAlertProcessor().
processAnalytics()
void iot_monitoring_system::processAnalytics (const device_telemetry & telemetry) inline
Definition at line 428 of file iot_monitoring.cpp.
References createAlert(), device_telemetry::device_id, device_telemetry::value, and alert::WARNING.
Referenced by handleDeviceTelemetry().
publishAlert()
void iot_monitoring_system::publishAlert (const alert & alert_obj) inline
Definition at line 341 of file iot_monitoring.cpp.
References alert::alert_id, alert::CRITICAL, alert::device_id, alert::EMERGENCY, kcenon::messaging::core::message_metadata::headers, alert::message, kcenon::messaging::core::message::metadata, kcenon::messaging::core::message::payload, kcenon::messaging::core::message_payload::set(), kcenon::messaging::core::message::set_priority(), alert::sev, kcenon::messaging::core::message_payload::topic, kcenon::messaging::core::message_metadata::type, and alert::WARNING.
Referenced by createAlert().
registerDevice()
void iot_monitoring_system::registerDevice (const std::string & device_id, device_type type, const std::string & location, double min_threshold, double max_threshold) inline
Definition at line 195 of file iot_monitoring.cpp.
References device_config::device_id, device_config::enabled, device_config::location, device_config::max_threshold, device_config::min_threshold, device_config::reporting_interval, and device_config::type.
Referenced by handleDeviceRegistration(), and initializeDevices().
sendDeviceList()
void iot_monitoring_system::sendDeviceList () inline
Definition at line 473 of file iot_monitoring.cpp.
References kcenon::messaging::core::message::payload, and kcenon::messaging::core::message_payload::set().
Referenced by handleSystemQuery().
sendLatestTelemetry()
void iot_monitoring_system::sendLatestTelemetry () inline
Definition at line 488 of file iot_monitoring.cpp.
References kcenon::messaging::core::message::payload, and kcenon::messaging::core::message_payload::set().
Referenced by handleSystemQuery().
sendSystemStatus()
void iot_monitoring_system::sendSystemStatus () inline
Definition at line 463 of file iot_monitoring.cpp.
References getUptime(), kcenon::messaging::core::message_metadata::headers, and kcenon::messaging::core::message::metadata.
Referenced by handleSystemQuery().
setupMessageHandlers()
void iot_monitoring_system::setupMessageHandlers () inline
Definition at line 142 of file iot_monitoring.cpp.
References handleAlertAcknowledgment(), handleDeviceCommand(), handleDeviceRegistration(), handleDeviceTelemetry(), and handleSystemQuery().
Referenced by iot_monitoring_system().
start()
void iot_monitoring_system::start () inline
Definition at line 622 of file iot_monitoring.cpp.
References startAlertProcessor(), startDashboard(), startDeviceSimulation(), and stop().
Referenced by main().
startAlertProcessor()
void iot_monitoring_system::startAlertProcessor () inline
Definition at line 552 of file iot_monitoring.cpp.
References processAlert().
Referenced by start().
startDashboard()
void iot_monitoring_system::startDashboard () inline
Definition at line 658 of file iot_monitoring.cpp.
References printDashboard().
Referenced by start().
startDeviceSimulation()
void iot_monitoring_system::startDeviceSimulation () inline
Definition at line 505 of file iot_monitoring.cpp.
References ENERGY_METER, kcenon::messaging::core::message_metadata::headers, HUMIDITY_SENSOR, kcenon::messaging::core::message::metadata, MOTION_DETECTOR, SMART_LIGHT, and TEMPERATURE_SENSOR.
Referenced by start().
stop()
void iot_monitoring_system::stop () inline
Definition at line 641 of file iot_monitoring.cpp.
Referenced by start().
storeTelemetry()
void iot_monitoring_system::storeTelemetry (const device_telemetry & telemetry) inline
Definition at line 420 of file iot_monitoring.cpp.
Referenced by handleDeviceTelemetry().
The documentation for this class was generated from the following file:
application_layer/samples/iot_monitoring.cpp