Messaging System: monitoring_module::batch_metrics_processor Class Reference
monitoring_module::batch_metrics_processor Class Reference
배치 메트릭 프로세서
#include <optimized_storage.h>
Classes
struct stats
통계 조회
Public Types
using batch_callback = std::function< void(const std::vector< monitoring_interface::metrics_snapshot > &)>
Public Member Functions
batch_metrics_processor (std::size_t batch_size, std::chrono::milliseconds flush_interval, batch_callback callback)
생성자
~batch_metrics_processor ()
void add (const monitoring_interface::metrics_snapshot &snapshot)
메트릭 추가
void flush ()
강제 플러시
void start ()
처리 시작
void stop ()
처리 중지
const stats & get_stats () const
Detailed Description
배치 메트릭 프로세서
메트릭을 배치로 처리하여 효율성 향상
Definition at line 293 of file optimized_storage.h.
Member Typedef Documentation
batch_callback
using monitoring_module::batch_metrics_processor::batch_callback = std::function<void(const std::vector<monitoring_interface::metrics_snapshot>&)>
Definition at line 295 of file optimized_storage.h.
Constructor & Destructor Documentation
batch_metrics_processor()
monitoring_module::batch_metrics_processor::batch_metrics_processor (std::size_t batch_size, std::chrono::milliseconds flush_interval, batch_callback callback)
생성자
Parameters
batch_size 배치 크기
flush_interval 플러시 간격
callback 배치 처리 콜백
Definition at line 214 of file optimized_storage.cpp.
~batch_metrics_processor()
monitoring_module::batch_metrics_processor::~batch_metrics_processor ()
Definition at line 224 of file optimized_storage.cpp.
References stop().
Member Function Documentation
add()
void monitoring_module::batch_metrics_processor::add (const monitoring_interface::metrics_snapshot & snapshot)
메트릭 추가
Parameters
snapshot 메트릭 스냅샷
Definition at line 228 of file optimized_storage.cpp.
flush()
void monitoring_module::batch_metrics_processor::flush ()
강제 플러시
Definition at line 238 of file optimized_storage.cpp.
References monitoring_module::batch_metrics_processor::stats::flush_count.
Referenced by stop().
get_stats()
const stats & monitoring_module::batch_metrics_processor::get_stats () const inline
Definition at line 340 of file optimized_storage.h.
start()
void monitoring_module::batch_metrics_processor::start ()
처리 시작
Definition at line 246 of file optimized_storage.cpp.
stop()
void monitoring_module::batch_metrics_processor::stop ()
처리 중지
Definition at line 255 of file optimized_storage.cpp.
References flush().
Referenced by ~batch_metrics_processor().
The documentation for this class was generated from the following files:
libraries/monitoring_system/sources/monitoring/optimized_storage.h
libraries/monitoring_system/sources/monitoring/optimized_storage.cpp