Messaging System: libraries/logger_system/tests/unit/integration_test/integration_test.cpp File Reference
integration_test.cpp File Reference
Integration tests for logger system.
#include <gtest/gtest.h>
#include "../../sources/logger/logger.h"
#include "../../sources/logger/config/logger_builder.h"
#include "../../sources/logger/config/configuration_templates.h"
#include "../../sources/logger/writers/console_writer.h"
#include "../../sources/logger/writers/file_writer.h"
#include "../../sources/logger/writers/async_writer.h"
#include "../../sources/logger/writers/batch_writer.h"
#include "../../sources/logger/monitoring/basic_monitor.h"
#include "../../sources/logger/di/lightweight_container.h"
#include "../mocks/mock_writer.hpp"
#include "../mocks/mock_monitor.hpp"
#include "../mocks/mock_di_container.hpp"
#include <filesystem>
#include <fstream>
#include <thread>
Classes
class integration_test
Typedefs
using log_level = thread_module::log_level
Functions
TEST_F (integration_test, complete_pipeline_integration)
Test complete logging pipeline with real components.
TEST_F (integration_test, DISABLED_di_container_integration)
Test DI container integration.
TEST_F (integration_test, configuration_templates_integration)
Test configuration templates.
TEST_F (integration_test, batch_writer_integration)
Test batch writer integration.
TEST_F (integration_test, monitoring_health_integration)
Test monitoring and health check integration.
TEST_F (integration_test, multi_writer_synchronization)
Test multi-writer synchronization.
TEST_F (integration_test, error_recovery_fallback)
Test error recovery and fallback mechanisms.
TEST_F (integration_test, performance_tuning_strategies)
Test performance tuning strategies.
TEST_F (integration_test, environment_based_configuration)
Test environment-based configuration.
Detailed Description
Integration tests for logger system.
Date
2025-09-09
BSD 3-Clause License Copyright (c) 2025, kcenon All rights reserved.
Definition in file integration_test.cpp.
Typedef Documentation
log_level
using log_level = thread_module::log_level
Definition at line 32 of file integration_test.cpp.
Function Documentation
TEST_F() [1/9]
TEST_F (integration_test , batch_writer_integration)
Test batch writer integration.
Verifies that batch writing works correctly with the logger.
Definition at line 185 of file integration_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), and kcenon::logger::result< T >::value().
TEST_F() [2/9]
TEST_F (integration_test , complete_pipeline_integration)
Test complete logging pipeline with real components.
Verifies that all components work together correctly in a realistic scenario.
Definition at line 56 of file integration_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), kcenon::logger::result< T >::value(), kcenon::logger::logger_builder::with_buffer_size(), kcenon::logger::logger_builder::with_default_pattern(), and kcenon::logger::logger_builder::with_monitoring().
TEST_F() [3/9]
TEST_F (integration_test , configuration_templates_integration)
Test configuration templates.
Verifies that pre-defined configuration templates work correctly.
Definition at line 142 of file integration_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::apply_template(), and kcenon::logger::logger_builder::build().
TEST_F() [4/9]
TEST_F (integration_test , DISABLED_di_container_integration)
Test DI container integration.
NOTE: DI container integration is not fully implemented in logger_builder yet. This test is disabled until the implementation is complete.
Definition at line 120 of file integration_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), and kcenon::logger::result< T >::value().
TEST_F() [5/9]
TEST_F (integration_test , environment_based_configuration)
Test environment-based configuration.
Verifies that environment detection and configuration works correctly.
Definition at line 406 of file integration_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger_builder::detect_environment(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), and kcenon::logger::result< T >::value().
TEST_F() [6/9]
TEST_F (integration_test , error_recovery_fallback)
Test error recovery and fallback mechanisms.
Verifies that the logger can recover from errors and use fallback mechanisms.
Definition at line 324 of file integration_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), logger_system::error, kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), kcenon::logger::result< T >::value(), and kcenon::logger::logger_builder::with_error_handler().
TEST_F() [7/9]
TEST_F (integration_test , monitoring_health_integration)
Test monitoring and health check integration.
Verifies that monitoring and health checks work correctly together.
Definition at line 225 of file integration_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), kcenon::logger::result< T >::value(), kcenon::logger::logger_builder::with_health_check_interval(), and kcenon::logger::logger_builder::with_monitoring().
TEST_F() [8/9]
TEST_F (integration_test , multi_writer_synchronization)
Test multi-writer synchronization.
Verifies that multiple writers work correctly together without conflicts.
Definition at line 281 of file integration_test.cpp.
References kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), and kcenon::logger::result< T >::value().
TEST_F() [9/9]
TEST_F (integration_test , performance_tuning_strategies)
Test performance tuning strategies.
Verifies that different performance strategies work as expected.
Definition at line 369 of file integration_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::apply_performance_strategy(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), and kcenon::logger::result< T >::value().