Messaging System: libraries/network_system/tests/integration/test_e2e.cpp File Reference
test_e2e.cpp File Reference
End-to-end tests for network_system.
#include <iostream>
#include <vector>
#include <thread>
#include <chrono>
#include <atomic>
#include <memory>
#include <random>
#include <cassert>
#include "network_system/network_system.h"
Classes
struct TestResults
Functions
bool test_basic_connectivity (TestResults &results)
Test 1: Basic connectivity test.
bool test_multi_client (TestResults &results)
Test 2: Multi-client concurrent connections.
bool test_large_messages (TestResults &results)
Test 3: Large message handling.
bool test_connection_resilience (TestResults &results)
Test 4: Connection resilience.
bool test_rapid_connections (TestResults &results)
Test 5: Rapid connect/disconnect cycles.
bool test_thread_pool_integration (TestResults &results)
Test 6: Thread pool integration.
bool test_container_integration (TestResults &results)
Test 7: Container serialization integration.
int main (int argc, char *argv[])
Main test runner.
Variables
constexpr uint16_t TEST_PORT = 9191
constexpr size_t NUM_CLIENTS = 10
constexpr size_t MESSAGES_PER_CLIENT = 100
constexpr size_t MAX_MESSAGE_SIZE = 8192
Detailed Description
End-to-end tests for network_system.
Comprehensive integration tests covering real-world scenarios including multi-client connections, error handling, and recovery.
Author
kcenon
Date
2025-09-20
Definition in file test_e2e.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Main test runner.
Definition at line 428 of file test_e2e.cpp.
References network_system::compat::initialize(), TestResults::is_successful(), TestResults::print(), network_system::compat::shutdown(), test_basic_connectivity(), test_connection_resilience(), test_container_integration(), test_large_messages(), test_multi_client(), test_rapid_connections(), and test_thread_pool_integration().
test_basic_connectivity()
bool test_basic_connectivity (TestResults & results)
Test 1: Basic connectivity test.
Definition at line 60 of file test_e2e.cpp.
References TestResults::errors, TestResults::failed, TestResults::messages_sent, TestResults::passed, and TEST_PORT.
Referenced by main().
test_connection_resilience()
bool test_connection_resilience (TestResults & results)
Test 4: Connection resilience.
Definition at line 224 of file test_e2e.cpp.
References TestResults::errors, TestResults::failed, TestResults::messages_sent, TestResults::passed, and TEST_PORT.
Referenced by main().
test_container_integration()
bool test_container_integration (TestResults & results)
Test 7: Container serialization integration.
Definition at line 380 of file test_e2e.cpp.
References TestResults::errors, TestResults::failed, network_system::integration::container_manager::instance(), TestResults::messages_received, TestResults::messages_sent, and TestResults::passed.
test_large_messages()
bool test_large_messages (TestResults & results)
Test 3: Large message handling.
Definition at line 178 of file test_e2e.cpp.
References TestResults::errors, TestResults::failed, TestResults::messages_sent, TestResults::passed, and TEST_PORT.
Referenced by main().
test_multi_client()
bool test_multi_client (TestResults & results)
Test 2: Multi-client concurrent connections.
Definition at line 103 of file test_e2e.cpp.
References TestResults::errors, TestResults::failed, MESSAGES_PER_CLIENT, TestResults::messages_sent, NUM_CLIENTS, TestResults::passed, and TEST_PORT.
Referenced by main().
test_rapid_connections()
bool test_rapid_connections (TestResults & results)
Test 5: Rapid connect/disconnect cycles.
Definition at line 289 of file test_e2e.cpp.
References TestResults::errors, TestResults::failed, TestResults::messages_sent, TestResults::passed, and TEST_PORT.
Referenced by main().
test_thread_pool_integration()
bool test_thread_pool_integration (TestResults & results)
Test 6: Thread pool integration.
Definition at line 335 of file test_e2e.cpp.
References TestResults::errors, TestResults::failed, network_system::integration::thread_integration_manager::instance(), and TestResults::passed.
Referenced by main().
Variable Documentation
MAX_MESSAGE_SIZE
constexpr size_t MAX_MESSAGE_SIZE = 8192 constexpr
Definition at line 31 of file test_e2e.cpp.
MESSAGES_PER_CLIENT
constexpr size_t MESSAGES_PER_CLIENT = 100 constexpr
Definition at line 30 of file test_e2e.cpp.
Referenced by test_multi_client().
NUM_CLIENTS
constexpr size_t NUM_CLIENTS = 10 constexpr
Definition at line 29 of file test_e2e.cpp.
Referenced by test_multi_client().
TEST_PORT
constexpr uint16_t TEST_PORT = 9191 constexpr
Definition at line 28 of file test_e2e.cpp.
Referenced by test_basic_connectivity(), test_connection_resilience(), test_large_messages(), test_multi_client(), and test_rapid_connections().