Messaging System: StressPerformanceTest Class Reference
StressPerformanceTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
size_t GetCurrentMemoryUsage ()
Protected Attributes
std::filesystem::path test_dir_
size_t initial_memory_
Detailed Description
Definition at line 52 of file test_stress_performance.cpp.
Member Function Documentation
GetCurrentMemoryUsage()
size_t StressPerformanceTest::GetCurrentMemoryUsage () inline protected
Definition at line 78 of file test_stress_performance.cpp.
Referenced by SetUp(), and TearDown().
SetUp()
void StressPerformanceTest::SetUp () inline override protected
Definition at line 54 of file test_stress_performance.cpp.
References GetCurrentMemoryUsage(), initial_memory_, and test_dir_.
TearDown()
void StressPerformanceTest::TearDown () inline override protected
Definition at line 60 of file test_stress_performance.cpp.
References GetCurrentMemoryUsage(), initial_memory_, and test_dir_.
Member Data Documentation
initial_memory_
size_t StressPerformanceTest::initial_memory_ protected
Definition at line 86 of file test_stress_performance.cpp.
Referenced by SetUp(), and TearDown().
test_dir_
std::filesystem::path StressPerformanceTest::test_dir_ protected
Definition at line 85 of file test_stress_performance.cpp.
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
libraries/monitoring_system/tests/test_stress_performance.cpp