Messaging System: fmt::formatter< thread_module::thread_conditions > Struct Reference
fmt::formatter< thread_module::thread_conditions > Struct Reference
Specialization of fmt::formatter for thread_module::thread_conditions.
#include <thread_conditions.h>
Public Member Functions
template<typename FormatContext >
auto format (const thread_module::thread_conditions &thread_condition, FormatContext &ctx) const
Formats a thread_conditions value as a string.
template<typename FormatContext >
auto format (const thread_module::thread_conditions &thread_condition, FormatContext &ctx) const
Formats a thread_conditions value as a string.
template<typename FormatContext >
auto format (const thread_module::thread_conditions &thread_condition, FormatContext &ctx) const
Formats a thread_conditions value as a string.
Detailed Description
Specialization of fmt::formatter for thread_module::thread_conditions.
Allows thread_conditions enum values to be formatted as strings using the {fmt} library.
Example
auto cond = thread_module::thread_conditions::Working;
std::string output = fmt::format("Thread state is {}", cond); // "Thread state is working"
Allows thread_conditions enum values to be formatted as strings using the {fmt} library.
Example
auto cond = thread_module::thread_conditions::Working;
std::string output = fmt::format("Thread state is {}", cond); // "Thread state is working"
Allows thread_conditions enum values to be formatted as strings using the {fmt} library.
Example
auto cond = thread_module::thread_conditions::Working;
std::string output = fmt::format("Thread state is {}", cond); // "Thread state is working"
Definition at line 212 of file thread_conditions.h.
Member Function Documentation
format() [1/3]
template<typename FormatContext > auto fmt::formatter< thread_module::thread_conditions >::format (const thread_module::thread_conditions & thread_condition, FormatContext & ctx) const inline
Formats a thread_conditions value as a string.
Template Parameters
FormatContext The type of the format context.
Parameters
thread_condition The thread_conditions enum value to format.
ctx The format context for the output.
Returns
An iterator to the end of the formatted output.
Definition at line 222 of file thread_conditions.h.
References thread_module::to_string().
format() [2/3]
template<typename FormatContext > auto fmt::formatter< thread_module::thread_conditions >::format (const thread_module::thread_conditions & thread_condition, FormatContext & ctx) const inline
Formats a thread_conditions value as a string.
Template Parameters
FormatContext The type of the format context.
Parameters
thread_condition The thread_conditions enum value to format.
ctx The format context for the output.
Returns
An iterator to the end of the formatted output.
Definition at line 222 of file thread_conditions.h.
References thread_module::to_string().
format() [3/3]
template<typename FormatContext > auto fmt::formatter< thread_module::thread_conditions >::format (const thread_module::thread_conditions & thread_condition, FormatContext & ctx) const inline
Formats a thread_conditions value as a string.
Template Parameters
FormatContext The type of the format context.
Parameters
thread_condition The thread_conditions enum value to format.
ctx The format context for the output.
Returns
An iterator to the end of the formatted output.
Definition at line 222 of file thread_conditions.h.
References thread_module::to_string().
The documentation for this struct was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/thread_base/core/thread_conditions.h
libraries/thread_system/modular_structure/core/src/thread_base/core/thread_conditions.h
libraries/thread_system/sources/thread_base/core/thread_conditions.h