Messaging System: monitoring_system::aggregation_processor Class Reference
monitoring_system::aggregation_processor Class Reference
High-level processor for metric aggregation.
#include <aggregation_processor.h>
Public Member Functions
aggregation_processor (std::shared_ptr< metric_storage > storage=nullptr)
Constructor.
~aggregation_processor ()
Destructor.
aggregation_processor (const aggregation_processor &)=delete
aggregation_processor & operator= (const aggregation_processor &)=delete
aggregation_processor (aggregation_processor &&)=delete
aggregation_processor & operator= (aggregation_processor &&)=delete
result_void add_aggregation_rule (const aggregation_rule &rule)
Add aggregation rule.
result_void remove_aggregation_rule (const std::string &source_metric)
Remove aggregation rule.
result_void process_observation (const std::string &metric_name, double value, std::chrono::system_clock::time_point timestamp=std::chrono::system_clock::now())
Process metric observation.
result< stream_statistics > get_current_statistics (const std::string &metric_name) const
Get current statistics for a metric.
result< metric_aggregation_result > force_aggregation (const std::string &metric_name)
Force aggregation for a specific metric.
std::vector< metric_aggregation_result > force_all_aggregations ()
Force aggregation for all metrics.
result_void start_background_processing (std::chrono::milliseconds interval=std::chrono::milliseconds(10000))
Start background processing.
void stop_background_processing ()
Stop background processing.
void set_aggregation_callback (std::function< void(const metric_aggregation_result &)> callback)
Set aggregation callback.
void set_storage (std::shared_ptr< metric_storage > storage)
Set metric storage.
std::vector< std::string > get_configured_metrics () const
Get list of configured metrics.
result< aggregation_rule > get_aggregation_rule (const std::string &metric_name) const
Get aggregation rule for a metric.
void clear_all_rules ()
Clear all aggregation rules.
std::unordered_map< std::string, uint64_t > get_processing_statistics () const
Get processing statistics.
Detailed Description
High-level processor for metric aggregation.
Definition at line 94 of file aggregation_processor.h.
Constructor & Destructor Documentation
aggregation_processor() [1/3]
monitoring_system::aggregation_processor::aggregation_processor (std::shared_ptr< metric_storage > storage = nullptr) inline explicit
Constructor.
Definition at line 272 of file aggregation_processor.h.
~aggregation_processor()
monitoring_system::aggregation_processor::~aggregation_processor () inline
Destructor.
Definition at line 278 of file aggregation_processor.h.
References stop_background_processing().
aggregation_processor() [2/3]
monitoring_system::aggregation_processor::aggregation_processor (const aggregation_processor &) delete
aggregation_processor() [3/3]
monitoring_system::aggregation_processor::aggregation_processor (aggregation_processor &&) delete
Member Function Documentation
add_aggregation_rule()
result_void monitoring_system::aggregation_processor::add_aggregation_rule (const aggregation_rule & rule) inline
Add aggregation rule.
Definition at line 291 of file aggregation_processor.h.
References monitoring_system::invalid_configuration, monitoring_system::aggregation_rule::source_metric, and monitoring_system::aggregation_rule::validate().
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
clear_all_rules()
void monitoring_system::aggregation_processor::clear_all_rules () inline
Clear all aggregation rules.
Definition at line 465 of file aggregation_processor.h.
force_aggregation()
result< metric_aggregation_result > monitoring_system::aggregation_processor::force_aggregation (const std::string & metric_name) inline
Force aggregation for a specific metric.
Definition at line 361 of file aggregation_processor.h.
Referenced by TEST_F().
force_all_aggregations()
std::vector< metric_aggregation_result > monitoring_system::aggregation_processor::force_all_aggregations () inline
Force aggregation for all metrics.
Definition at line 368 of file aggregation_processor.h.
References monitoring_system::result< T >::value().
get_aggregation_rule()
result< aggregation_rule > monitoring_system::aggregation_processor::get_aggregation_rule (const std::string & metric_name) const inline
Get aggregation rule for a metric.
Definition at line 450 of file aggregation_processor.h.
References monitoring_system::collector_not_found, and monitoring_system::make_success().
get_configured_metrics()
std::vector< std::string > monitoring_system::aggregation_processor::get_configured_metrics () const inline
Get list of configured metrics.
Definition at line 436 of file aggregation_processor.h.
Referenced by TEST_F().
get_current_statistics()
result< stream_statistics > monitoring_system::aggregation_processor::get_current_statistics (const std::string & metric_name) const inline
Get current statistics for a metric.
Definition at line 346 of file aggregation_processor.h.
References monitoring_system::collector_not_found, and monitoring_system::make_success().
Referenced by TEST_F().
get_processing_statistics()
std::unordered_map< std::string, uint64_t > monitoring_system::aggregation_processor::get_processing_statistics () const inline
Get processing statistics.
Definition at line 473 of file aggregation_processor.h.
References monitoring_system::stream_statistics::count.
operator=() [1/2]
aggregation_processor & monitoring_system::aggregation_processor::operator= (aggregation_processor &&) delete
operator=() [2/2]
aggregation_processor & monitoring_system::aggregation_processor::operator= (const aggregation_processor &) delete
process_observation()
result_void monitoring_system::aggregation_processor::process_observation (const std::string & metric_name, double value, std::chrono::system_clock::time_point timestamp = std::chrono::system_clock::now()) inline
Process metric observation.
Definition at line 328 of file aggregation_processor.h.
References monitoring_system::collector_not_found.
Referenced by TEST_F(), TEST_F(), and TEST_F().
remove_aggregation_rule()
result_void monitoring_system::aggregation_processor::remove_aggregation_rule (const std::string & source_metric) inline
Remove aggregation rule.
Definition at line 312 of file aggregation_processor.h.
References monitoring_system::collector_not_found.
set_aggregation_callback()
void monitoring_system::aggregation_processor::set_aggregation_callback (std::function< void(const metric_aggregation_result &)> callback) inline
Set aggregation callback.
Definition at line 422 of file aggregation_processor.h.
set_storage()
void monitoring_system::aggregation_processor::set_storage (std::shared_ptr< metric_storage > storage) inline
Set metric storage.
Definition at line 429 of file aggregation_processor.h.
start_background_processing()
result_void monitoring_system::aggregation_processor::start_background_processing (std::chrono::milliseconds interval = std::chrono::milliseconds(10000)) inline
Start background processing.
Definition at line 392 of file aggregation_processor.h.
References monitoring_system::invalid_configuration.
stop_background_processing()
void monitoring_system::aggregation_processor::stop_background_processing () inline
Stop background processing.
Definition at line 408 of file aggregation_processor.h.
Referenced by ~aggregation_processor().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/aggregation_processor.h