Messaging System: monitoring_system::otel_resource Struct Reference
monitoring_system::otel_resource Struct Reference
OpenTelemetry resource representation.
#include <opentelemetry_adapter.h>
Public Member Functions
void add_attribute (const std::string &key, const std::string &value)
result< std::string > get_attribute (const std::string &key) const
Public Attributes
otel_resource_type type {otel_resource_type::service}
std::vector< otel_attribute > attributes
Detailed Description
OpenTelemetry resource representation.
Definition at line 91 of file opentelemetry_adapter.h.
Member Function Documentation
add_attribute()
void monitoring_system::otel_resource::add_attribute (const std::string & key, const std::string & value) inline
Definition at line 95 of file opentelemetry_adapter.h.
References attributes.
Referenced by monitoring_system::create_service_resource().
get_attribute()
result< std::string > monitoring_system::otel_resource::get_attribute (const std::string & key) const inline
Definition at line 99 of file opentelemetry_adapter.h.
References attributes, monitoring_system::make_success(), and monitoring_system::not_found.
Referenced by monitoring_system::opentelemetry_metrics_adapter::convert_metrics().
Member Data Documentation
attributes
std::vector<otel_attribute> monitoring_system::otel_resource::attributes
Definition at line 93 of file opentelemetry_adapter.h.
Referenced by add_attribute(), and get_attribute().
type
otel_resource_type monitoring_system::otel_resource::type {otel_resource_type::service}
Definition at line 92 of file opentelemetry_adapter.h.
Referenced by monitoring_system::create_service_resource().
The documentation for this struct was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/exporters/opentelemetry_adapter.h