Messaging System: libraries/monitoring_system/tests/test_optimization.cpp File Reference
test_optimization.cpp File Reference
#include <gtest/gtest.h>
#include <monitoring/optimization/lockfree_queue.h>
#include <monitoring/optimization/memory_pool.h>
#include <monitoring/optimization/simd_aggregator.h>
#include <chrono>
#include <thread>
#include <vector>
#include <random>
#include <functional>
Classes
class OptimizationTest
Test suite for Phase 3 P4: Lock-free data structures integration.
Functions
TEST_F (OptimizationTest, LockfreeQueueBasicOperations)
TEST_F (OptimizationTest, LockfreeQueueConcurrentAccess)
TEST_F (OptimizationTest, MemoryPoolBasicOperations)
TEST_F (OptimizationTest, MemoryPoolObjectAllocation)
TEST_F (OptimizationTest, MemoryPoolConcurrentAccess)
TEST_F (OptimizationTest, SIMDAggregatorBasicOperations)
TEST_F (OptimizationTest, SIMDAggregatorLargeDataset)
TEST_F (OptimizationTest, SIMDAggregatorPerformanceComparison)
TEST_F (OptimizationTest, ConfigurationValidation)
TEST_F (OptimizationTest, FactoryFunctions)
TEST_F (OptimizationTest, DefaultConfigurations)
TEST_F (OptimizationTest, IntegrationTest)
Function Documentation
TEST_F() [1/12]
TEST_F (OptimizationTest , ConfigurationValidation)
Definition at line 365 of file test_optimization.cpp.
TEST_F() [2/12]
TEST_F (OptimizationTest , DefaultConfigurations)
Definition at line 421 of file test_optimization.cpp.
TEST_F() [3/12]
TEST_F (OptimizationTest , FactoryFunctions)
Definition at line 399 of file test_optimization.cpp.
TEST_F() [4/12]
TEST_F (OptimizationTest , IntegrationTest)
Definition at line 448 of file test_optimization.cpp.
References monitoring_system::summary, and monitoring_system::result< T >::value().
TEST_F() [5/12]
TEST_F (OptimizationTest , LockfreeQueueBasicOperations)
Definition at line 46 of file test_optimization.cpp.
References monitoring_system::result< T >::value().
TEST_F() [6/12]
TEST_F (OptimizationTest , LockfreeQueueConcurrentAccess)
Definition at line 76 of file test_optimization.cpp.
TEST_F() [7/12]
TEST_F (OptimizationTest , MemoryPoolBasicOperations)
Definition at line 138 of file test_optimization.cpp.
References monitoring_system::result< T >::value().
TEST_F() [8/12]
TEST_F (OptimizationTest , MemoryPoolConcurrentAccess)
Definition at line 207 of file test_optimization.cpp.
References monitoring_system::result< T >::value().
TEST_F() [9/12]
TEST_F (OptimizationTest , MemoryPoolObjectAllocation)
Definition at line 173 of file test_optimization.cpp.
References monitoring_system::result< T >::value().
TEST_F() [10/12]
TEST_F (OptimizationTest , SIMDAggregatorBasicOperations)
Definition at line 255 of file test_optimization.cpp.
TEST_F() [11/12]
TEST_F (OptimizationTest , SIMDAggregatorLargeDataset)
Definition at line 286 of file test_optimization.cpp.
References monitoring_system::summary.
TEST_F() [12/12]
TEST_F (OptimizationTest , SIMDAggregatorPerformanceComparison)
Definition at line 316 of file test_optimization.cpp.