Messaging System: kcenon::messaging::persistence::persistence_manager_factory Class Reference
kcenon::messaging::persistence::persistence_manager_factory Class Reference
#include <message_persistence.h>
Static Public Member Functions
static std::unique_ptr< message_storage > create_file_storage (const std::string &storage_path)
static std::unique_ptr< message_recovery_system > create_recovery_system (std::unique_ptr< message_storage > storage)
static std::unique_ptr< persistent_message_queue > create_persistent_queue (std::unique_ptr< message_storage > storage)
static std::unique_ptr< message_recovery_system > create_file_recovery_system (const std::string &storage_path)
static std::unique_ptr< persistent_message_queue > create_file_persistent_queue (const std::string &storage_path)
Detailed Description
Definition at line 426 of file message_persistence.h.
Member Function Documentation
create_file_persistent_queue()
static std::unique_ptr< persistent_message_queue > kcenon::messaging::persistence::persistence_manager_factory::create_file_persistent_queue (const std::string & storage_path) inline static
Definition at line 449 of file message_persistence.h.
References create_file_storage(), and create_persistent_queue().
create_file_recovery_system()
static std::unique_ptr< message_recovery_system > kcenon::messaging::persistence::persistence_manager_factory::create_file_recovery_system (const std::string & storage_path) inline static
Definition at line 443 of file message_persistence.h.
References create_file_storage(), and create_recovery_system().
create_file_storage()
static std::unique_ptr< message_storage > kcenon::messaging::persistence::persistence_manager_factory::create_file_storage (const std::string & storage_path) inline static
Definition at line 428 of file message_persistence.h.
Referenced by create_file_persistent_queue(), and create_file_recovery_system().
create_persistent_queue()
static std::unique_ptr< persistent_message_queue > kcenon::messaging::persistence::persistence_manager_factory::create_persistent_queue (std::unique_ptr< message_storage > storage) inline static
Definition at line 438 of file message_persistence.h.
Referenced by create_file_persistent_queue().
create_recovery_system()
static std::unique_ptr< message_recovery_system > kcenon::messaging::persistence::persistence_manager_factory::create_recovery_system (std::unique_ptr< message_storage > storage) inline static
Definition at line 433 of file message_persistence.h.
Referenced by create_file_recovery_system().
The documentation for this class was generated from the following file:
application_layer/include/kcenon/messaging/persistence/message_persistence.h