Messaging System: kcenon::logger Namespace Reference
kcenon::logger Namespace Reference
Namespaces
namespace adapters
namespace analysis
namespace async
namespace core
namespace di
namespace filters
namespace formatters
namespace impl
namespace interfaces
namespace memory
namespace metrics
namespace monitoring
namespace routing
namespace server
namespace structured
namespace utils
namespace writers
Classes
class async_writer
Asynchronous wrapper for log writers.
class base_formatter
Base implementation for log formatters.
class base_writer
Abstract base class for all log output writers.
class basic_monitor
Basic monitoring implementation.
class batch_writer
Batch writer that accumulates log entries and writes them in batches.
class compact_formatter
Compact formatter for minimal output.
class composite_filter
Combine multiple filters with AND/OR logic.
class console_writer
Console writer that outputs logs to stdout/stderr.
class di_container_factory
Factory for creating DI containers.
class di_container_interface
Abstract interface for dependency injection container.
class encrypted_writer
Writer that encrypts log data before passing to another writer.
class file_writer
Basic file writer for logging to files.
class function_filter
Filter logs by custom function.
class health_check_result
Health check result.
class json_formatter
JSON formatter for structured logging.
class level_filter
Filter logs by minimum level.
class lightweight_container
Simple dependency injection container.
class lightweight_di_container
Lightweight implementation of DI container.
class log_collector
Asynchronous log collector for high-performance logging.
struct log_entry
Represents a single log entry with all associated metadata.
class log_filter
Base class for log filtering.
interface log_filter_interface
Interface for log filters.
interface log_formatter_interface
Interface for log formatters.
interface log_sink_interface
Interface for log sinks.
interface log_writer_interface
Interface for log writers.
class logger
Main logger implementation that implements thread_system's logger_interface.
class logger_builder
Builder pattern for logger construction with validation.
struct logger_config
Configuration structure for logger with validation.
struct metric_value
Single metric value with metadata.
class monitoring_data
Collection of metrics.
class monitoring_factory
Factory for creating monitoring implementations.
class monitoring_interface
Abstract monitoring interface.
class network_writer
Sends logs over network (TCP/UDP)
class plain_formatter
Simple plain text formatter.
class regex_filter
Filter logs by regex pattern.
class result
class result_void
class rotating_file_writer
File writer with rotation support based on size or time.
class small_string
Small String Optimization (SSO) implementation.
struct source_location
Source code location information for debugging.
class thread_system_monitor_adapter
Fallback when thread_system is not available.
Typedefs
using error_code = logger_error_code
using log_level = logger_system::log_level
using logger_metrics = metrics::logger_performance_stats
using performance_metrics = metrics::logger_performance_stats
using monitoring_metrics = monitoring::monitoring_data
using monitoring_interface = monitoring::monitoring_interface
using di_container_interface = di::di_container_interface
using di_container_factory = di::di_container_factory
using monitoring_factory = monitoring::monitoring_factory
using small_string_64 = small_string< 64 >
using small_string_128 = small_string< 128 >
using small_string_256 = small_string< 256 >
using small_string_512 = small_string< 512 >
Enumerations
enum class logger_error_code {
success = 0 , unknown_error = 1 , not_implemented = 2 , invalid_argument = 3 ,
writer_not_found = 1000 , writer_initialization_failed = 1001 , writer_already_exists = 1002 , writer_not_healthy = 1003 ,
file_open_failed = 1100 , file_write_failed = 1101 , file_rotation_failed = 1102 , file_permission_denied = 1103 ,
network_connection_failed = 1200 , network_send_failed = 1201 , network_timeout = 1202 , buffer_overflow = 1300 ,
queue_full = 1301 , queue_stopped = 1302 , invalid_configuration = 1400 , configuration_missing = 1401 ,
configuration_conflict = 1402 , metrics_collection_failed = 1500 , metrics_not_available = 1501 , flush_timeout = 1600 ,
processing_failed = 1601 , filter_error = 1602 , formatter_error = 1603 , encryption_failed = 1700 ,
decryption_failed = 1701 , authentication_failed = 1702 , sanitization_failed = 1703 , di_not_available = 1800 ,
component_not_found = 1801 , registration_failed = 1802 , creation_failed = 1803 , operation_failed = 1804 ,
writer_not_available = 1900 , writer_configuration_error = 1901 , writer_operation_failed = 1902
}
Error codes specific to the logger system.
enum class metric_type {
gauge , counter , histogram , counter ,
gauge , histogram , summary
}
enum class health_status { healthy , degraded , unhealthy , unknown }
Health status levels.
enum class metric_type {
gauge , counter , histogram , counter ,
gauge , histogram , summary
}
Metric types for categorization.
Functions
std::string logger_error_to_string (logger_error_code code)
Convert logger_error_code to string representation.
result_void make_logger_error (logger_error_code code, const std::string &message="")
template<typename T >
result< T > make_logger_error (logger_error_code code, const std::string &message="")
std::unique_ptr< batch_writer > make_batch_writer (std::unique_ptr< base_writer > writer, size_t batch_size=100, std::chrono::milliseconds flush_interval=std::chrono::milliseconds{1000})
Factory function to create a batch writer.
logger_system::log_level convert_log_level (logger_system::log_level level)
lightweight_container & get_container ()
Get the global lightweight container instance.
std::string health_status_to_string (health_status status)
Convert health status to string.
std::string metric_type_to_string (metric_type type)
Convert metric type to string.
Typedef Documentation
di_container_factory
using kcenon::logger::di_container_factory = typedef di::di_container_factory
Definition at line 126 of file logger.h.
di_container_interface
using kcenon::logger::di_container_interface = typedef di::di_container_interface
Definition at line 125 of file logger.h.
error_code
using kcenon::logger::error_code = typedef logger_error_code
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 278 of file error_codes.h.
log_level
using kcenon::logger::log_level = typedef logger_system::log_level
Definition at line 117 of file logger.h.
logger_metrics
using kcenon::logger::logger_metrics = typedef metrics::logger_performance_stats
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 121 of file logger.h.
monitoring_factory
using kcenon::logger::monitoring_factory = typedef monitoring::monitoring_factory
Definition at line 127 of file logger.h.
monitoring_interface
using kcenon::logger::monitoring_interface = typedef monitoring::monitoring_interface
Definition at line 124 of file logger.h.
monitoring_metrics
using kcenon::logger::monitoring_metrics = typedef monitoring::monitoring_data
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 123 of file logger.h.
performance_metrics
using kcenon::logger::performance_metrics = typedef metrics::logger_performance_stats
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 122 of file logger.h.
small_string_128
using kcenon::logger::small_string_128 = typedef small_string<128>
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/interfaces/log_entry.h.
Definition at line 441 of file small_string.h.
small_string_256
using kcenon::logger::small_string_256 = typedef small_string<256>
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/interfaces/log_entry.h.
Definition at line 442 of file small_string.h.
small_string_512
using kcenon::logger::small_string_512 = typedef small_string<512>
Definition at line 443 of file small_string.h.
small_string_64
using kcenon::logger::small_string_64 = typedef small_string<64>
Definition at line 440 of file small_string.h.
Enumeration Type Documentation
health_status
enum class kcenon::logger::health_status strong
Health status levels.
Enumerator
healthy
Everything is working normally.
degraded
Some issues but still operational.
unhealthy
Major issues, may not be operational.
unknown
Status cannot be determined.
Definition at line 30 of file monitoring_interface.h.
logger_error_code
enum class kcenon::logger::logger_error_code strong
Error codes specific to the logger system.
These error codes extend the thread_module error codes with logger-specific error conditions.
Enumerator
success
unknown_error
not_implemented
invalid_argument
writer_not_found
writer_initialization_failed
writer_already_exists
writer_not_healthy
file_open_failed
file_write_failed
file_rotation_failed
file_permission_denied
network_connection_failed
network_send_failed
network_timeout
buffer_overflow
queue_full
queue_stopped
invalid_configuration
configuration_missing
configuration_conflict
metrics_collection_failed
metrics_not_available
flush_timeout
processing_failed
filter_error
formatter_error
encryption_failed
decryption_failed
authentication_failed
sanitization_failed
di_not_available
component_not_found
registration_failed
creation_failed
operation_failed
writer_not_available
writer_configuration_error
writer_operation_failed
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 52 of file error_codes.h.
metric_type [1/2]
enum class kcenon::logger::metric_type strong
Enumerator
gauge
counter
histogram
counter
Monotonically increasing value.
gauge
Value that can go up or down.
histogram
Distribution of values.
summary
Statistical summary.
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 130 of file logger.h.
metric_type [2/2]
enum class kcenon::logger::metric_type strong
Metric types for categorization.
Enumerator
gauge
counter
histogram
counter
Monotonically increasing value.
gauge
Value that can go up or down.
histogram
Distribution of values.
summary
Statistical summary.
Definition at line 40 of file monitoring_interface.h.
Function Documentation
convert_log_level()
logger_system::log_level kcenon::logger::convert_log_level (logger_system::log_level level)
Definition at line 57 of file logger.cpp.
Referenced by kcenon::logger::log_collector::enqueue(), kcenon::logger::logger::log(), and kcenon::logger::logger::log().
get_container()
lightweight_container & kcenon::logger::get_container () inline
Get the global lightweight container instance.
Returns
Reference to the global container
Definition at line 111 of file lightweight_container.h.
health_status_to_string()
std::string kcenon::logger::health_status_to_string (health_status status) inline
Convert health status to string.
Parameters
status The health status
Returns
String representation
Definition at line 287 of file monitoring_interface.h.
References degraded, healthy, unhealthy, and unknown.
Referenced by TEST().
logger_error_to_string()
std::string kcenon::logger::logger_error_to_string (logger_error_code code) inline
Convert logger_error_code to string representation.
Parameters
code The error code to convert
Returns
Human-readable error description
Definition at line 120 of file error_codes.h.
References authentication_failed, buffer_overflow, component_not_found, configuration_conflict, configuration_missing, creation_failed, decryption_failed, di_not_available, encryption_failed, file_open_failed, file_permission_denied, file_rotation_failed, file_write_failed, filter_error, flush_timeout, formatter_error, invalid_argument, invalid_configuration, metrics_collection_failed, metrics_not_available, network_connection_failed, network_send_failed, network_timeout, not_implemented, operation_failed, processing_failed, queue_full, queue_stopped, registration_failed, sanitization_failed, success, unknown_error, writer_already_exists, writer_initialization_failed, writer_not_found, and writer_not_healthy.
Referenced by make_logger_error().
make_batch_writer()
std::unique_ptr< batch_writer > kcenon::logger::make_batch_writer (std::unique_ptr< base_writer > writer, size_t batch_size = 100, std::chrono::milliseconds flush_interval = std::chrono::milliseconds{1000})
Factory function to create a batch writer.
Parameters
writer The underlying writer to wrap
batch_size Maximum batch size
flush_interval Auto-flush interval in milliseconds
Returns
Unique pointer to the batch writer
Definition at line 186 of file batch_writer.cpp.
References kcenon::logger::batch_writer::config::flush_interval, and kcenon::logger::batch_writer::config::max_batch_size.
make_logger_error() [1/2]
result_void kcenon::logger::make_logger_error (logger_error_code code, const std::string & message = "") inline
Definition at line 267 of file error_codes.h.
References logger_error_to_string().
Referenced by kcenon::logger::console_writer::flush(), kcenon::logger::file_writer::flush(), kcenon::logger::network_writer::flush(), logger_system::testing::mock_writer::flush(), kcenon::logger::file_writer::open(), logger_system::testing::mock_monitor::record_event(), logger_system::testing::mock_di_container::register_factory(), kcenon::logger::lightweight_di_container< T >::register_factory(), logger_system::testing::mock_di_container::register_instance(), logger_system::testing::mock_di_container::register_singleton(), kcenon::logger::lightweight_di_container< T >::register_singleton(), kcenon::logger::logger_config::validate(), logger_system::testing::mock_writer::write(), kcenon::logger::async_writer::write(), kcenon::logger::batch_writer::write(), kcenon::logger::console_writer::write(), kcenon::logger::encrypted_writer::write(), kcenon::logger::file_writer::write(), and logger_system::testing::mock_writer::write().
make_logger_error() [2/2]
template<typename T > result< T > kcenon::logger::make_logger_error (logger_error_code code, const std::string & message = "") inline
Definition at line 273 of file error_codes.h.
References logger_error_to_string().
metric_type_to_string()
std::string kcenon::logger::metric_type_to_string (metric_type type) inline
Convert metric type to string.
Parameters
type The metric type
Returns
String representation
Definition at line 307 of file monitoring_interface.h.
References counter, gauge, histogram, and summary.
Referenced by TEST().