Messaging System: kcenon::logger::logger Class Reference
kcenon::logger::logger Class Reference
Main logger implementation that implements thread_system's logger_interface.
#include <logger.h>
Classes
class impl
Public Member Functions
logger (bool async=true, std::size_t buffer_size=8192)
Constructor with optional configuration.
~logger () override
Destructor - ensures all logs are flushed.
void log (logger_system::log_level level, const std::string &message) override
Log a simple message.
void log (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function) override
Log a message with source location information.
bool is_enabled (logger_system::log_level level) const override
Check if logging is enabled for the specified level.
void flush () override
Flush all pending log messages.
result_void add_writer (std::unique_ptr< base_writer > writer)
result_void clear_writers ()
Remove all writers.
void set_min_level (logger_system::log_level level)
logger_system::log_level get_min_level () const
Get the minimum log level.
result_void start ()
result_void stop ()
Stop the logger.
bool is_running () const
Check if logger is running.
result_void enable_metrics_collection (bool enable=true)
Enable or disable metrics collection.
bool is_metrics_collection_enabled () const
Check if metrics collection is enabled.
result< metrics::logger_performance_stats > get_current_metrics () const
Get current performance metrics.
result< std::unique_ptr< metrics::logger_performance_stats > > get_metrics_history (std::chrono::seconds duration) const
Get metrics history for a specific duration.
result_void reset_metrics ()
Reset performance metrics.
logger_metrics_collector * get_metrics_collector ()
Get metrics collector for direct access.
void add_writer (const std::string &name, std::unique_ptr< base_writer > writer)
Add a writer with a specific name.
bool remove_writer (const std::string &name)
Remove a writer by name.
base_writer * get_writer (const std::string &name)
Get a writer by name.
void set_filter (std::unique_ptr< log_filter > filter)
Set global filter.
log_router & get_router ()
Get the log router for configuration.
void set_di_container (di::di_container_interface *container)
Set a DI container for writer resolution.
bool has_di_container () const
Check if DI container is available.
result_void add_writer_from_di (const std::string &name)
Add a writer from DI container.
result_void register_writer_factory (const std::string &name, std::function< std::shared_ptr< base_writer >()> factory)
Register a writer factory in the internal DI container.
di::di_container_factory::container_type get_di_strategy () const
Get the DI strategy being used.
result_void enable_di (di::di_container_factory::container_type type=di::di_container_factory::container_type::automatic)
Enable internal DI container.
void set_monitor (std::unique_ptr< monitoring::monitoring_interface > monitor)
Set a custom monitoring implementation.
result_void enable_monitoring (monitoring::monitoring_factory::monitor_type type=monitoring::monitoring_factory::monitor_type::automatic)
Enable monitoring with specified backend.
result_void disable_monitoring ()
Disable monitoring.
bool is_monitoring_enabled () const
Check if monitoring is enabled.
result< monitoring::monitoring_data > collect_metrics () const
Collect current metrics.
result< health_status > check_health () const
Perform health check.
result_void reset_monitoring_metrics ()
Reset monitoring metrics.
std::string get_monitoring_backend () const
Get the monitoring backend name.
void record_metric (const std::string &name, double value, metric_type type=metric_type::gauge)
Record a custom metric.
Public Member Functions inherited from logger_system::logger_interface
virtual ~logger_interface ()=default
Detailed Description
Main logger implementation that implements thread_system's logger_interface.
The logger class provides a high-performance, thread-safe logging system with:
Asynchronous logging with configurable batching for optimal throughput
Multiple writer support for outputting to different destinations simultaneously
Real-time metrics collection and performance monitoring
Dependency injection support for flexible writer management
Configurable filtering and routing of log messages
Integration with monitoring backends for production observability
The logger uses the PIMPL idiom to hide implementation details and maintain ABI stability.
Warning
When using asynchronous mode, ensure proper shutdown by calling stop() and flush() before destroying the logger to prevent loss of buffered messages.
Since
1.0.0
Examples
Basic.
Definition at line 165 of file logger.h.
Constructor & Destructor Documentation
logger()
kcenon::logger::logger::logger (bool async = true, std::size_t buffer_size = 8192) explicit
Constructor with optional configuration.
Parameters
async Enable asynchronous logging (default: true)
buffer_size Size of the log buffer in bytes (default: 8192)
Creates a logger instance with the specified configuration. In async mode, a background thread is created to process log messages, providing better performance for high-throughput applications.
Note
The buffer_size parameter affects memory usage and batching efficiency. Larger buffers can improve throughput but increase memory consumption.
Since
1.0.0
Definition at line 84 of file logger.cpp.
~logger()
kcenon::logger::logger::~logger () override
Destructor - ensures all logs are flushed.
Properly shuts down the logger, ensuring all buffered messages are written to their destinations before destruction. Automatically calls stop() and flush() if the logger is still running.
Warning
Destruction may block until all pending messages are processed.
Since
1.0.0
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 89 of file logger.cpp.
References stop().
Member Function Documentation
add_writer() [1/2]
void kcenon::logger::logger::add_writer (const std::string & name, std::unique_ptr< base_writer > writer)
Add a writer with a specific name.
Parameters
name Name for the writer
writer Unique pointer to the writer
add_writer() [2/2]
result_void kcenon::logger::logger::add_writer (std::unique_ptr< base_writer > writer)
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h, and Basic.
Definition at line 115 of file logger.cpp.
Referenced by demonstrate_audit_trail(), demonstrate_encryption(), main(), migration_pitfalls_example(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
add_writer_from_di()
result_void kcenon::logger::logger::add_writer_from_di (const std::string & name)
Add a writer from DI container.
Parameters
name Name of the writer registered in DI container
Returns
result_void indicating success or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
check_health()
result< health_status > kcenon::logger::logger::check_health () const
Perform health check.
Returns
Result containing health check result or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
clear_writers()
result_void kcenon::logger::logger::clear_writers ()
Remove all writers.
Returns
result_void Success or error code
Removes all currently registered writers from the logger. After this call, log messages will not be output anywhere until new writers are added.
Warning
This operation cannot be undone. Removed writers are destroyed.
Since
1.0.0
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
collect_metrics()
result< monitoring::monitoring_data > kcenon::logger::logger::collect_metrics () const
Collect current metrics.
Returns
Result containing monitoring data or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
disable_monitoring()
result_void kcenon::logger::logger::disable_monitoring ()
Disable monitoring.
Returns
result_void indicating success or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
enable_di()
result_void kcenon::logger::logger::enable_di (di::di_container_factory::container_type type = di::di_container_factory::container_type::automatic)
Enable internal DI container.
Parameters
type Type of DI container to use
Returns
result_void indicating success or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
enable_metrics_collection()
result_void kcenon::logger::logger::enable_metrics_collection (bool enable = true)
Enable or disable metrics collection.
Parameters
enable true to enable metrics collection
Returns
result_void indicating success or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Referenced by demonstrate_security_metrics(), TEST_F(), and TEST_F().
enable_monitoring()
result_void kcenon::logger::logger::enable_monitoring (monitoring::monitoring_factory::monitor_type type = monitoring::monitoring_factory::monitor_type::automatic)
Enable monitoring with specified backend.
Parameters
type Type of monitoring backend to use
Returns
result_void indicating success or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
flush()
void kcenon::logger::logger::flush () override virtual
Flush all pending log messages.
Forces immediate writing of all buffered messages to their destinations. This is a blocking operation that waits until all messages are processed.
Note
In synchronous mode, this is a no-op as messages are written immediately.
Warning
May cause performance degradation if called frequently in async mode.
Since
1.0.0
Implements logger_system::logger_interface.
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h, and Basic.
Definition at line 183 of file logger.cpp.
Referenced by main(), stop(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
get_current_metrics()
result< metrics::logger_performance_stats > kcenon::logger::logger::get_current_metrics () const
Get current performance metrics.
Returns
Result containing metrics or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Referenced by demonstrate_security_metrics(), TEST_F(), and TEST_F().
get_di_strategy()
di::di_container_factory::container_type kcenon::logger::logger::get_di_strategy () const
Get the DI strategy being used.
Returns
Current DI strategy
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
get_metrics_collector()
logger_metrics_collector * kcenon::logger::logger::get_metrics_collector ()
Get metrics collector for direct access.
Returns
Pointer to metrics collector (may be null if not enabled)
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
get_metrics_history()
result< std::unique_ptr< metrics::logger_performance_stats > > kcenon::logger::logger::get_metrics_history (std::chrono::seconds duration) const
Get metrics history for a specific duration.
Parameters
duration How far back to retrieve metrics
Returns
Result containing metrics snapshot or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
get_min_level()
logger_system::log_level kcenon::logger::logger::get_min_level () const
Get the minimum log level.
Returns
Current minimum log level
Returns the current threshold level for message logging.
Since
1.0.0
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 136 of file logger.cpp.
get_monitoring_backend()
std::string kcenon::logger::logger::get_monitoring_backend () const
Get the monitoring backend name.
Returns
Name of the current monitoring backend
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
get_router()
log_router & kcenon::logger::logger::get_router ()
Get the log router for configuration.
Returns
Reference to the log router
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Referenced by demonstrate_audit_trail(), and TEST_F().
get_writer()
base_writer * kcenon::logger::logger::get_writer (const std::string & name)
Get a writer by name.
Parameters
name Name of the writer
Returns
Pointer to writer or nullptr if not found
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
has_di_container()
bool kcenon::logger::logger::has_di_container () const
Check if DI container is available.
Returns
true if DI container is set
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
is_enabled()
bool kcenon::logger::logger::is_enabled (logger_system::log_level level) const override virtual
Check if logging is enabled for the specified level.
Parameters
level Log level to check
Returns
true if logging is enabled for this level
Implements logger_system::logger_interface.
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 178 of file logger.cpp.
is_metrics_collection_enabled()
bool kcenon::logger::logger::is_metrics_collection_enabled () const
Check if metrics collection is enabled.
Returns
true if metrics collection is enabled
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
is_monitoring_enabled()
bool kcenon::logger::logger::is_monitoring_enabled () const
Check if monitoring is enabled.
Returns
true if monitoring is enabled
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
is_running()
bool kcenon::logger::logger::is_running () const
Check if logger is running.
Returns
true if the logger is currently running, false otherwise
In async mode, returns true if the background processing thread is active. In sync mode, always returns true.
Since
1.0.0
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 111 of file logger.cpp.
log() [1/2]
void kcenon::logger::logger::log (logger_system::log_level level, const std::string & message) override virtual
Log a simple message.
Parameters
level Severity level of the message
message The message to log
Logs a message without source location information. The message is queued for asynchronous processing if async mode is enabled.
Note
Messages below the minimum log level are discarded for performance.
Since
1.0.0
Implements logger_system::logger_interface.
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h, and Basic.
Definition at line 144 of file logger.cpp.
References kcenon::logger::convert_log_level().
Referenced by api_comparison_example(), demonstrate_audit_trail(), demonstrate_encryption(), demonstrate_security_logging(), demonstrate_security_metrics(), generate_logs(), main(), migration_pitfalls_example(), modern_v2_code_example(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
log() [2/2]
void kcenon::logger::logger::log (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function) override virtual
Log a message with source location information.
Parameters
level Log level
message Log message
file Source file name
line Source line number
function Function name
Implements logger_system::logger_interface.
Definition at line 161 of file logger.cpp.
References kcenon::logger::convert_log_level().
record_metric()
void kcenon::logger::logger::record_metric (const std::string & name, double value, metric_type type = metric_type::gauge)
Record a custom metric.
Parameters
name Metric name
value Metric value
type Metric type
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
register_writer_factory()
result_void kcenon::logger::logger::register_writer_factory (const std::string & name, std::function< std::shared_ptr< base_writer >()> factory)
Register a writer factory in the internal DI container.
Parameters
name Name to register the writer factory under
factory Factory function to create the writer
Returns
result_void indicating success or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
remove_writer()
bool kcenon::logger::logger::remove_writer (const std::string & name)
Remove a writer by name.
Parameters
name Name of the writer to remove
Returns
true if writer was found and removed
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Referenced by TEST_F().
reset_metrics()
result_void kcenon::logger::logger::reset_metrics ()
Reset performance metrics.
Returns
result_void indicating success or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
reset_monitoring_metrics()
result_void kcenon::logger::logger::reset_monitoring_metrics ()
Reset monitoring metrics.
Returns
result_void indicating success or error
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
set_di_container()
void kcenon::logger::logger::set_di_container (di::di_container_interface * container)
Set a DI container for writer resolution.
Parameters
container Pointer to DI container (not owned)
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
set_filter()
void kcenon::logger::logger::set_filter (std::unique_ptr< log_filter > filter)
Set global filter.
Parameters
filter Filter to apply to all logs
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Referenced by demonstrate_security_logging(), and TEST_F().
set_min_level()
void kcenon::logger::logger::set_min_level (logger_system::log_level level)
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 125 of file logger.cpp.
Referenced by main().
set_monitor()
void kcenon::logger::logger::set_monitor (std::unique_ptr< monitoring::monitoring_interface > monitor)
Set a custom monitoring implementation.
Parameters
monitor Unique pointer to monitoring implementation
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
start()
result_void kcenon::logger::logger::start ()
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h, and Basic.
Definition at line 95 of file logger.cpp.
Referenced by BM_ConfigurationTemplates(), BM_FilterImpact(), BM_LoggerWithBatchConfig(), BM_MessageSize(), BM_MultipleWriters(), BM_MultithreadedBatchSimulation(), BM_QueueBehavior(), BM_StructuredLogging(), main(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
stop()
result_void kcenon::logger::logger::stop ()
Stop the logger.
Returns
result_void Success or error code
Stops the background processing thread and flushes all pending messages. This is a blocking operation that waits for all queued messages to be processed.
Note
After stopping, the logger can be restarted with start().
Warning
Stopping the logger may take time if there are many pending messages.
Since
1.0.0
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h, and Basic.
Definition at line 103 of file logger.cpp.
References flush().
Referenced by main(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and ~logger().
The documentation for this class was generated from the following files:
libraries/logger_system/include/kcenon/logger/core/logger.h
libraries/logger_system/src/core/logger.cpp