Messaging System: libraries/thread_system/benchmarks/typed_thread_pool_benchmarks/queue_comparison_benchmark.cpp File Reference
queue_comparison_benchmark.cpp File Reference
#include <benchmark/benchmark.h>
#include "typed_thread_pool/scheduling/typed_lockfree_job_queue.h"
#include "typed_thread_pool/scheduling/typed_job_queue.h"
#include "typed_thread_pool/jobs/callback_typed_job.h"
#include "thread_base/lockfree/queues/lockfree_job_queue.h"
#include "thread_base/jobs/job_queue.h"
Classes
class simple_test_job
Functions
static void BM_TypedJobQueue_Enqueue (benchmark::State &state)
static void BM_TypedLockfreeJobQueue_Enqueue (benchmark::State &state)
static void BM_TypedJobQueue_EnqueueDequeue (benchmark::State &state)
static void BM_TypedLockfreeJobQueue_EnqueueDequeue (benchmark::State &state)
static void BM_TypedJobQueue_BatchEnqueue (benchmark::State &state)
static void BM_TypedLockfreeJobQueue_BatchEnqueue (benchmark::State &state)
static void BM_TypedJobQueue_HighContention (benchmark::State &state)
static void BM_TypedLockfreeJobQueue_HighContention (benchmark::State &state)
static void BM_TypedLockfreeJobQueue_PriorityDequeue (benchmark::State &state)
static void BM_TypedJobQueue_MemoryUsage (benchmark::State &state)
static void BM_TypedLockfreeJobQueue_MemoryUsage (benchmark::State &state)
BENCHMARK (BM_TypedJobQueue_Enqueue) -> Unit(benchmark::kNanosecond)
BENCHMARK (BM_TypedLockfreeJobQueue_Enqueue) -> Unit(benchmark::kNanosecond)
BENCHMARK (BM_TypedJobQueue_EnqueueDequeue) -> Unit(benchmark::kNanosecond)
BENCHMARK (BM_TypedLockfreeJobQueue_EnqueueDequeue) -> Unit(benchmark::kNanosecond)
BENCHMARK (BM_TypedJobQueue_BatchEnqueue) -> Range(8, 1024) ->Unit(benchmark::kMicrosecond)
BENCHMARK (BM_TypedLockfreeJobQueue_BatchEnqueue) -> Range(8, 1024) ->Unit(benchmark::kMicrosecond)
BENCHMARK (BM_TypedJobQueue_HighContention) -> Range(1, 16) ->Unit(benchmark::kMicrosecond)
BENCHMARK (BM_TypedLockfreeJobQueue_HighContention) -> Range(1, 16) ->Unit(benchmark::kMicrosecond)
BENCHMARK (BM_TypedLockfreeJobQueue_PriorityDequeue) -> Unit(benchmark::kNanosecond)
BENCHMARK (BM_TypedJobQueue_MemoryUsage) -> Range(100, 10000) ->Unit(benchmark::kMicrosecond)
BENCHMARK (BM_TypedLockfreeJobQueue_MemoryUsage) -> Range(100, 10000) ->Unit(benchmark::kMicrosecond)
Function Documentation
BENCHMARK() [1/11]
BENCHMARK (BM_TypedJobQueue_BatchEnqueue) -> Range(8, 1024) ->Unit(benchmark::kMicrosecond)
BENCHMARK() [2/11]
BENCHMARK (BM_TypedJobQueue_Enqueue) -> Unit(benchmark::kNanosecond)
BENCHMARK() [3/11]
BENCHMARK (BM_TypedJobQueue_EnqueueDequeue) -> Unit(benchmark::kNanosecond)
BENCHMARK() [4/11]
BENCHMARK (BM_TypedJobQueue_HighContention) -> Range(1, 16) ->Unit(benchmark::kMicrosecond)
BENCHMARK() [5/11]
BENCHMARK (BM_TypedJobQueue_MemoryUsage) -> Range(100, 10000) ->Unit(benchmark::kMicrosecond)
BENCHMARK() [6/11]
BENCHMARK (BM_TypedLockfreeJobQueue_BatchEnqueue) -> Range(8, 1024) ->Unit(benchmark::kMicrosecond)
BENCHMARK() [7/11]
BENCHMARK (BM_TypedLockfreeJobQueue_Enqueue) -> Unit(benchmark::kNanosecond)
BENCHMARK() [8/11]
BENCHMARK (BM_TypedLockfreeJobQueue_EnqueueDequeue) -> Unit(benchmark::kNanosecond)
BENCHMARK() [9/11]
BENCHMARK (BM_TypedLockfreeJobQueue_HighContention) -> Range(1, 16) ->Unit(benchmark::kMicrosecond)
BENCHMARK() [10/11]
BENCHMARK (BM_TypedLockfreeJobQueue_MemoryUsage) -> Range(100, 10000) ->Unit(benchmark::kMicrosecond)
BENCHMARK() [11/11]
BENCHMARK (BM_TypedLockfreeJobQueue_PriorityDequeue) -> Unit(benchmark::kNanosecond)
BM_TypedJobQueue_BatchEnqueue()
static void BM_TypedJobQueue_BatchEnqueue (benchmark::State & state) static
Definition at line 136 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch().
BM_TypedJobQueue_Enqueue()
static void BM_TypedJobQueue_Enqueue (benchmark::State & state) static
Definition at line 57 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue().
BM_TypedJobQueue_EnqueueDequeue()
static void BM_TypedJobQueue_EnqueueDequeue (benchmark::State & state) static
Definition at line 81 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue(), typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue(), thread_module::result< T >::has_value(), and thread_module::result< T >::value().
BM_TypedJobQueue_HighContention()
static void BM_TypedJobQueue_HighContention (benchmark::State & state) static
Definition at line 177 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue(), typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue(), thread_module::result< T >::has_value(), thread_count, and thread_module::result< T >::value().
BM_TypedJobQueue_MemoryUsage()
static void BM_TypedJobQueue_MemoryUsage (benchmark::State & state) static
Definition at line 284 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue(), typed_thread_pool_module::typed_job_queue_t< job_type >::empty(), typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue(), thread_module::result< T >::has_value(), thread_module::job_queue::size(), and thread_module::result< T >::value().
BM_TypedLockfreeJobQueue_BatchEnqueue()
static void BM_TypedLockfreeJobQueue_BatchEnqueue (benchmark::State & state) static
Definition at line 156 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue_batch().
BM_TypedLockfreeJobQueue_Enqueue()
static void BM_TypedLockfreeJobQueue_Enqueue (benchmark::State & state) static
Definition at line 69 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue().
BM_TypedLockfreeJobQueue_EnqueueDequeue()
static void BM_TypedLockfreeJobQueue_EnqueueDequeue (benchmark::State & state) static
Definition at line 108 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue(), typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue(), thread_module::result< T >::has_value(), and thread_module::result< T >::value().
BM_TypedLockfreeJobQueue_HighContention()
static void BM_TypedLockfreeJobQueue_HighContention (benchmark::State & state) static
Definition at line 215 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue(), typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue(), thread_module::result< T >::has_value(), thread_count, and thread_module::result< T >::value().
BM_TypedLockfreeJobQueue_MemoryUsage()
static void BM_TypedLockfreeJobQueue_MemoryUsage (benchmark::State & state) static
Definition at line 312 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue(), typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::empty(), typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue(), thread_module::result< T >::has_value(), typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::size(), and thread_module::result< T >::value().
BM_TypedLockfreeJobQueue_PriorityDequeue()
static void BM_TypedLockfreeJobQueue_PriorityDequeue (benchmark::State & state) static
Definition at line 254 of file queue_comparison_benchmark.cpp.
References typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue(), typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue(), thread_module::result< T >::has_value(), and thread_module::result< T >::value().