Messaging System: libraries/thread_system/tests/unit/interfaces_test/interfaces_test.cpp File Reference
interfaces_test.cpp File Reference
#include <gtest/gtest.h>
#include "executor_interface.h"
#include "scheduler_interface.h"
#include "monitorable_interface.h"
#include "thread_pool.h"
#include "job_queue.h"
#include "callback_job.h"
#include "service_registry.h"
Functions
TEST (interfaces_test, scheduler_interface_job_queue)
TEST (interfaces_test, executor_interface_thread_pool)
TEST (interfaces_test, monitorable_interface_mock)
TEST (interfaces_test, service_registry_basic)
Function Documentation
TEST() [1/4]
TEST (interfaces_test , executor_interface_thread_pool)
Definition at line 38 of file interfaces_test.cpp.
References kcenon::thread::executor_interface::execute(), and kcenon::thread::executor_interface::shutdown().
TEST() [2/4]
TEST (interfaces_test , monitorable_interface_mock)
Definition at line 81 of file interfaces_test.cpp.
TEST() [3/4]
TEST (interfaces_test , scheduler_interface_job_queue)
Definition at line 20 of file interfaces_test.cpp.
References kcenon::thread::job_queue::get_next_job(), and kcenon::thread::job_queue::schedule().
TEST() [4/4]
TEST (interfaces_test , service_registry_basic)
Definition at line 90 of file interfaces_test.cpp.