Messaging System: TestLogger Class Reference
TestLogger Class Reference
Public Member Functions
TestLogger ()=default
void log (log_level level, const std::string &message) override
Log a message with specified level.
void log_with_caller (log_level level, const std::string &message, const std::string &caller_function, const std::string &caller_file, int caller_line) override
std::optional< std::string > get_identifier () const override
std::string to_string () const override
size_t log_count () const
bool has_log_with_level (log_level level) const
bool has_log_containing (const std::string &text) const
Public Member Functions inherited from thread_module::logger_interface
virtual ~logger_interface ()=default
virtual void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function)=0
Log a message with source location information.
virtual bool is_enabled (log_level level) const =0
Check if logging is enabled for the specified level.
virtual void flush ()=0
Flush any buffered log messages.
virtual ~logger_interface ()=default
virtual void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function)=0
Log a message with source location information.
virtual bool is_enabled (log_level level) const =0
Check if logging is enabled for the specified level.
virtual void flush ()=0
Flush any buffered log messages.
virtual ~logger_interface ()=default
virtual void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function)=0
Log a message with source location information.
virtual bool is_enabled (log_level level) const =0
Check if logging is enabled for the specified level.
virtual void flush ()=0
Flush any buffered log messages.
Detailed Description
Definition at line 14 of file test_logger_integration.cpp.
Constructor & Destructor Documentation
TestLogger()
TestLogger::TestLogger () default
Member Function Documentation
get_identifier()
std::optional< std::string > TestLogger::get_identifier () const inline override
Definition at line 35 of file test_logger_integration.cpp.
has_log_containing()
bool TestLogger::has_log_containing (const std::string & text) const inline
Definition at line 55 of file test_logger_integration.cpp.
References log().
has_log_with_level()
bool TestLogger::has_log_with_level (log_level level) const inline
Definition at line 49 of file test_logger_integration.cpp.
References log().
log()
void TestLogger::log (log_level level, const std::string & message) inline override virtual
Log a message with specified level.
Parameters
level Log level
message Log message
Implements thread_module::logger_interface.
Definition at line 18 of file test_logger_integration.cpp.
Referenced by has_log_containing(), and has_log_with_level().
log_count()
size_t TestLogger::log_count () const inline
Definition at line 44 of file test_logger_integration.cpp.
log_with_caller()
void TestLogger::log_with_caller (log_level level, const std::string & message, const std::string & caller_function, const std::string & caller_file, int caller_line) inline override
Definition at line 23 of file test_logger_integration.cpp.
to_string()
std::string TestLogger::to_string () const inline override
Definition at line 39 of file test_logger_integration.cpp.
The documentation for this class was generated from the following file:
libraries/thread_system/modular_structure/integration_tests/test_logger_integration.cpp