Messaging System: monitoring_system Namespace Reference
monitoring_system Namespace Reference
Namespaces
namespace adapters
namespace alerting
Classes
struct adaptation_stats
Adaptation statistics.
class adaptive_collector
Adaptive collector wrapper.
struct adaptive_config
Adaptive configuration parameters.
class adaptive_monitor
Adaptive monitoring controller.
class adaptive_scope
Adaptive monitoring scope.
class adaptive_strategy
Adaptive buffering strategy based on system load.
class aggregation_processor
High-level processor for metric aggregation.
struct aggregation_result
Result of time series aggregation.
struct aggregation_rule
Rule for metric aggregation.
class buffer_manager
High-level buffer management system.
struct buffer_manager_config
Configuration for buffer manager.
struct buffer_manager_statistics
Statistics for buffer manager.
struct buffer_statistics
Statistics for buffer performance.
class buffer_strategy_interface
Abstract interface for buffering strategies.
struct buffered_metric
Metric with buffering metadata.
struct buffering_config
Configuration for buffering strategy.
class circuit_breaker
Basic circuit breaker implementation - stub.
struct circuit_breaker_config
Circuit breaker configuration.
struct circuit_breaker_metrics
Circuit breaker metrics.
class collection_config
Configuration for metric collection.
struct compact_metric_value
Memory-efficient metric value storage.
class component_lifecycle_event
Event for component lifecycle changes.
class configuration_change_event
Event fired when configuration changes.
struct context_metadata
Context metadata for thread-specific information.
class distributed_tracer
Distributed tracer for managing spans and traces.
class error_boundary
Basic error boundary implementation - stub.
struct error_boundary_config
Error boundary configuration.
struct error_boundary_metrics
Error boundary metrics.
struct error_info
Extended error information with context.
class event_base
Base class for all events in the system.
class event_bus
Thread-safe event bus implementation.
struct event_bus_config
Configuration for event bus.
class event_envelope
Container for events with metadata.
class event_handler
Type-safe event handler wrapper.
class event_handler_wrapper
Wrapper for event handlers with metadata.
struct expression_node
Query expression AST node.
class fault_tolerance_manager
Basic fault tolerance manager - stub implementation.
class file_storage_backend
File storage backend - stub implementation.
class fixed_size_strategy
Fixed size buffering strategy.
class functional_health_check
Functional health check implementation.
class health_check_event
Event for health check results.
struct health_check_result
Health check result.
class health_monitor
Basic health monitor interface - stub implementation.
struct health_monitor_config
Health monitor configuration.
struct histogram_bucket
Bucket for histogram metrics.
struct histogram_data
Histogram data with buckets.
class immediate_strategy
Immediate processing strategy (no buffering)
class interface_aggregated_collector
Interface for collectors that aggregate metrics from multiple sources.
class interface_event_bus
Pure virtual interface for event bus implementation.
class interface_event_publisher
Interface for components that publish events.
class interface_event_subscriber
Interface for components that subscribe to events.
class interface_metric_collector
Pure virtual interface for metric collectors.
class interface_metric_source
Interface for components that provide metrics.
class interface_monitoring_observer
Pure virtual interface for monitoring event observers.
class interface_observable
Interface for components that can be observed.
class jaeger_exporter
Jaeger trace exporter implementation.
struct jaeger_span_data
Jaeger-specific span representation.
class kv_storage_backend
Basic key-value storage interface - stub.
class log_anomaly_detector
Log anomaly detector Detects anomalies in logging patterns and volumes.
struct log_pattern_analysis
Log pattern analysis results.
class log_storage_optimizer
Log storage optimizer Optimizes log storage and retention policies.
class logger_system_collector
Logger system metrics collector plugin Collects metrics from logging systems and analyzes log patterns.
class logging_metric_event
Event containing logging system metrics.
struct logging_stats
Logging system statistics.
class memory_storage_backend
In-memory storage backend - basic implementation.
struct metric
Basic metric structure for interface compatibility.
struct metric_aggregation_result
Result of metric aggregation.
struct metric_batch
Batch of metrics for efficient processing.
class metric_collection_event
Event containing collected metrics batch.
class metric_collector_plugin
Plugin interface for metric collectors All metric collector plugins must implement this interface.
class metric_event
Event fired when a metric is collected.
struct metric_export_config
Configuration for metric exporters.
class metric_exporter_factory
Factory for creating metric exporters.
class metric_exporter_interface
Abstract interface for metric exporters.
class metric_filter
Filter configuration for metric collection.
struct metric_metadata
Compact metadata for metrics.
class metric_query_engine
High-level metric query engine.
struct metric_stats
Statistics about metric collection.
class metric_storage
Memory-efficient metric storage using ring buffers.
struct metric_storage_config
Configuration for metric storage system.
struct metric_storage_stats
Statistics for metric storage performance.
struct metric_value
Represents a single metric value with metadata.
class metrics_analyzer
Abstract interface for metrics analysis.
class metrics_collector
Abstract base class for metric collectors.
struct metrics_snapshot
Complete snapshot of metrics at a point in time.
class monitorable_component
Base class providing default monitorable implementation.
class monitorable_interface
Interface for components that can be monitored.
class monitoring_aggregator
Utility class to aggregate metrics from multiple monitorable components.
struct monitoring_config
Configuration for the monitoring system.
struct monitoring_data
Container for monitoring metrics from a component.
class monitoring_interface
Abstract interface for monitoring operations.
class moving_window_aggregator
Sliding window aggregator for time-based statistics.
class online_statistics
Online algorithm for computing statistics.
class opentelemetry_compatibility_layer
Main OpenTelemetry compatibility layer.
class opentelemetry_exporter_config
Configuration for OpenTelemetry exporters.
class opentelemetry_metrics_adapter
Adapter for converting monitoring system metrics to OpenTelemetry format.
class opentelemetry_tracer_adapter
Adapter for converting monitoring system traces to OpenTelemetry format.
struct otel_attribute
OpenTelemetry attribute representation.
struct otel_metric_data
OpenTelemetry metric data representation.
struct otel_resource
OpenTelemetry resource representation.
struct otel_span_context
OpenTelemetry span context.
struct otel_span_data
OpenTelemetry span data representation.
class otlp_exporter
OpenTelemetry Protocol (OTLP) trace exporter implementation.
class otlp_metrics_exporter
OpenTelemetry Protocol (OTLP) metrics exporter implementation.
class performance_alert_event
Event for performance-related alerts.
class performance_benchmark
Performance benchmark utility.
struct performance_metrics
Performance metrics for a specific operation.
class performance_monitor
Performance monitor combining profiling and system monitoring.
class performance_profiler
Performance profiler for code sections.
struct plugin_collector_config
Configuration for plugin metric collector.
class plugin_factory
Factory for creating standard collector plugins.
class plugin_loader
Plugin loading and management interface.
class plugin_metric_collector
Main plugin-based metric collector implementation Manages multiple collector plugins and provides unified metric collection.
class priority_based_strategy
Priority-based buffering strategy.
class prometheus_exporter
Prometheus metric exporter implementation.
struct prometheus_metric_data
Prometheus-specific metric representation.
class quantile_estimator
P algorithm for quantile estimation.
class query_context
Query context for variable resolution.
class query_executor
Query executor.
struct query_hints
Query optimization hints.
class query_optimizer
Query plan optimizer.
class query_parser
Query parser for SQL-like syntax.
class resource_threshold_monitor
Resource threshold monitor Monitors system resources against configured thresholds.
class result
Result type for operations that may fail.
class result_void
Specialization for operations with no return value.
struct retry_config
Retry configuration.
class retry_policy
Basic retry policy implementation - stub.
class ring_buffer
Lock-free ring buffer with atomic operations.
struct ring_buffer_config
Configuration for ring buffer behavior.
struct ring_buffer_stats
Statistics for ring buffer performance monitoring.
class scoped_span
Scoped span for RAII-style span management.
class scoped_timer
Scoped performance timer.
class service_container_interface
class service_locator
class span_builder
Span builder for creating new spans.
class state_change_event
Event fired when system state changes.
class statsd_exporter
StatsD metric exporter implementation.
struct statsd_metric_data
StatsD-specific metric representation.
class storage_backend
Abstract interface for metrics storage.
struct storage_config
Storage configuration.
class stream_aggregator
Main class for statistical stream aggregation.
struct stream_aggregator_config
Configuration for stream aggregation.
struct stream_statistics
Comprehensive streaming statistics.
class subscription_token
Token for managing event subscriptions.
struct summary_data
Summary statistics for metrics.
class system_event
Generic system event for monitoring components.
class system_info_collector
Platform-specific system resource collector implementation.
struct system_metrics
System resource metrics.
class system_monitor
System resource monitor.
class system_resource_collector
System resource collector plugin implementation.
class system_resource_event
Event containing system resource metrics.
struct system_resources
System resource information structure.
class thread_context
Thread-local context management.
struct thread_context_data
Enhanced thread context for comprehensive tracking.
class thread_context_manager
Thread-local context storage (legacy compatibility)
class thread_pool_auto_scaler
Thread pool auto-scaler Automatically adjusts thread pool size based on load.
class thread_pool_health_monitor
Thread pool health monitor Monitors thread pool health and detects anomalies.
class thread_pool_metric_event
Event containing thread pool metrics.
struct thread_pool_stats
Thread pool statistics.
class thread_system_collector
Thread system metrics collector plugin Collects metrics from thread pools and thread management systems.
class time_based_strategy
Time-based buffering strategy.
struct time_point_data
Single data point in time series.
class time_series
Thread-safe time series data storage.
struct time_series_config
Configuration for time series storage.
struct time_series_query
Query parameters for time series data.
struct trace_context
Trace context for propagation across service boundaries.
struct trace_export_config
Configuration for trace exporters.
class trace_exporter_factory
Factory for creating trace exporters.
class trace_exporter_interface
Abstract interface for trace exporters.
struct trace_span
Trace span representing a unit of work in distributed tracing.
class zipkin_exporter
Zipkin trace exporter implementation.
struct zipkin_span_data
Zipkin-specific span representation.
Typedefs
using metric_value = std::variant< double, int64_t, std::string >
Type alias for metric value.
Enumerations
enum class log_level {
trace , debug , info , warning ,
error , critical , fatal
}
Log level enumeration.
enum class monitoring_error_code : std::uint32_t {
success = 0 , collector_not_found = 1000 , collection_failed = 1001 , collector_initialization_failed = 1002 ,
collector_already_exists = 1003 , collector_disabled = 1004 , invalid_collector_config = 1005 , monitoring_disabled = 1006 ,
storage_full = 2000 , storage_corrupted = 2001 , compression_failed = 2002 , storage_not_initialized = 2003 ,
storage_write_failed = 2004 , storage_read_failed = 2005 , storage_empty = 2006 , invalid_configuration = 3000 ,
invalid_interval = 3001 , invalid_capacity = 3002 , configuration_not_found = 3003 , configuration_parse_error = 3004 ,
system_resource_unavailable = 4000 , permission_denied = 4001 , out_of_memory = 4002 , memory_allocation_failed = 4003 ,
operation_timeout = 4004 , operation_cancelled = 4005 , thread_system_not_available = 5000 , logger_system_not_available = 5001 ,
incompatible_version = 5002 , adapter_initialization_failed = 5003 , metric_not_found = 6000 , invalid_metric_type = 6001 ,
metric_overflow = 6002 , aggregation_failed = 6003 , processing_failed = 6004 , health_check_failed = 7000 ,
health_check_timeout = 7001 , health_check_not_registered = 7002 , circuit_breaker_open = 8000 , circuit_breaker_half_open = 8001 ,
retry_attempts_exhausted = 8002 , operation_failed = 8003 , network_error = 8004 , service_unavailable = 8005 ,
service_degraded = 8006 , error_boundary_triggered = 8007 , fallback_failed = 8008 , recovery_failed = 8009 ,
invalid_argument = 8100 , invalid_state = 8101 , not_found = 8102 , already_exists = 8103 ,
resource_exhausted = 8104 , already_started = 8105 , dependency_missing = 8106 , quota_exceeded = 8200 ,
rate_limit_exceeded = 8201 , cpu_throttled = 8202 , memory_quota_exceeded = 8203 , bandwidth_exceeded = 8204 ,
resource_unavailable = 8205 , transaction_failed = 8300 , transaction_timeout = 8301 , transaction_aborted = 8302 ,
validation_failed = 8303 , data_corrupted = 8304 , state_inconsistent = 8305 , deadlock_detected = 8306 ,
rollback_failed = 8307 , unknown_error = 9999 , collector_not_found = 1000
}
Comprehensive error codes for monitoring system operations.
enum class metric_export_format {
prometheus_text , prometheus_protobuf , statsd_plain , statsd_datadog ,
otlp_grpc , otlp_http_json , otlp_http_protobuf
}
Supported metric export formats.
enum class metric_type {
counter , gauge , histogram , summary ,
timer , counter = 0 , gauge , histogram ,
summary , timer , set , counter = 0 ,
gauge , histogram , summary , timer ,
set
}
Metric types supported by exporters.
enum class otel_resource_type {
service , service_instance , host , container ,
process , runtime , telemetry_sdk , custom
}
OpenTelemetry resource types.
enum class otel_span_kind {
unspecified = 0 , internal = 1 , server = 2 , client = 3 ,
producer = 4 , consumer = 5
}
OpenTelemetry span kinds.
enum class otel_status_code { unset = 0 , ok = 1 , error = 2 }
OpenTelemetry status codes.
enum class trace_export_format {
jaeger_thrift , jaeger_grpc , zipkin_json , zipkin_protobuf ,
otlp_grpc , otlp_http_json , otlp_http_protobuf
}
Supported trace export formats.
enum class event_priority { low , normal , high , critical }
enum class health_status {
healthy , degraded , unhealthy , unknown ,
healthy , degraded , unhealthy , unknown
}
System health status levels.
enum class metric_type : uint8_t {
counter , gauge , histogram , summary ,
timer , counter = 0 , gauge , histogram ,
summary , timer , set , counter = 0 ,
gauge , histogram , summary , timer ,
set
}
enum class health_status {
healthy , degraded , unhealthy , unknown ,
healthy , degraded , unhealthy , unknown
}
Basic health status enumeration.
enum class health_check_type { liveness , readiness , startup }
Health check types.
enum class circuit_state { closed , open , half_open }
Circuit breaker states.
enum class degradation_level {
none = 0 , low = 1 , medium = 2 , high = 3 ,
critical = 4
}
Degradation levels.
enum class retry_strategy { fixed_delay , exponential_backoff , linear_backoff }
Retry strategies.
enum class storage_backend_type {
memory , file_json , file_binary , database ,
time_series
}
Storage backend types.
enum class compression_algorithm { none , gzip , lz4 , zstd }
Compression algorithms.
enum class adaptation_strategy { conservative , balanced , aggressive }
Adaptation strategy for monitoring behavior.
enum class load_level {
idle , low , moderate , high ,
critical
}
System load levels.
enum class expression_type {
literal , identifier , binary_op , unary_op ,
function_call , aggregation
}
Query expression types.
enum class binary_operator {
add , subtract , multiply , divide ,
modulo , power , equal , not_equal ,
less_than , less_equal , greater_than , greater_equal ,
logical_and , logical_or
}
Binary operators.
enum class unary_operator { negate , logical_not , absolute }
Unary operators.
enum class aggregation_function {
sum , avg , min , max ,
count , stddev , variance , percentile ,
rate , delta , derivative , integral
}
Aggregation functions.
enum class buffering_strategy_type : uint8_t {
immediate , fixed_size , time_based , adaptive ,
priority_based , compression_based
}
Types of buffering strategies.
enum class buffer_overflow_policy : uint8_t {
drop_oldest , drop_newest , drop_lowest_priority , compress ,
flush_immediately , block_until_space
}
Policies for handling buffer overflow.
enum class buffer_flush_trigger : uint8_t {
size_threshold , time_interval , priority_threshold , memory_pressure ,
manual , adaptive
}
Triggers for buffer flushing.
enum class metric_type : uint8_t {
counter , gauge , histogram , summary ,
timer , counter = 0 , gauge , histogram ,
summary , timer , set , counter = 0 ,
gauge , histogram , summary , timer ,
set
}
enum class monitoring_error_code {
success = 0 , collector_not_found = 1000 , collection_failed = 1001 , collector_initialization_failed = 1002 ,
collector_already_exists = 1003 , collector_disabled = 1004 , invalid_collector_config = 1005 , monitoring_disabled = 1006 ,
storage_full = 2000 , storage_corrupted = 2001 , compression_failed = 2002 , storage_not_initialized = 2003 ,
storage_write_failed = 2004 , storage_read_failed = 2005 , storage_empty = 2006 , invalid_configuration = 3000 ,
invalid_interval = 3001 , invalid_capacity = 3002 , configuration_not_found = 3003 , configuration_parse_error = 3004 ,
system_resource_unavailable = 4000 , permission_denied = 4001 , out_of_memory = 4002 , memory_allocation_failed = 4003 ,
operation_timeout = 4004 , operation_cancelled = 4005 , thread_system_not_available = 5000 , logger_system_not_available = 5001 ,
incompatible_version = 5002 , adapter_initialization_failed = 5003 , metric_not_found = 6000 , invalid_metric_type = 6001 ,
metric_overflow = 6002 , aggregation_failed = 6003 , processing_failed = 6004 , health_check_failed = 7000 ,
health_check_timeout = 7001 , health_check_not_registered = 7002 , circuit_breaker_open = 8000 , circuit_breaker_half_open = 8001 ,
retry_attempts_exhausted = 8002 , operation_failed = 8003 , network_error = 8004 , service_unavailable = 8005 ,
service_degraded = 8006 , error_boundary_triggered = 8007 , fallback_failed = 8008 , recovery_failed = 8009 ,
invalid_argument = 8100 , invalid_state = 8101 , not_found = 8102 , already_exists = 8103 ,
resource_exhausted = 8104 , already_started = 8105 , dependency_missing = 8106 , quota_exceeded = 8200 ,
rate_limit_exceeded = 8201 , cpu_throttled = 8202 , memory_quota_exceeded = 8203 , bandwidth_exceeded = 8204 ,
resource_unavailable = 8205 , transaction_failed = 8300 , transaction_timeout = 8301 , transaction_aborted = 8302 ,
validation_failed = 8303 , data_corrupted = 8304 , state_inconsistent = 8305 , deadlock_detected = 8306 ,
rollback_failed = 8307 , unknown_error = 9999 , collector_not_found = 1000
}
enum class service_lifetime { transient , singleton , scoped }
Functions
std::string error_code_to_string (monitoring_error_code code)
Convert error code to string representation.
std::string get_error_details (monitoring_error_code code)
Get detailed error message.
performance_monitor & global_performance_monitor ()
Global performance monitor instance.
template<typename T >
result< std::decay_t< T > > make_success (T &&value)
Create a successful result.
template<typename T >
result< T > make_error (monitoring_error_code code, const std::string &message="")
Create an error result.
template<typename T >
result< T > make_error_with_context (monitoring_error_code code, const std::string &message, const std::string &context)
Create an error result with context.
std::unique_ptr< prometheus_exporter > create_prometheus_exporter (std::uint16_t port=9090, const std::string &job_name="monitoring_system")
Helper function to create a Prometheus exporter.
std::unique_ptr< statsd_exporter > create_statsd_exporter (const std::string &host="localhost", std::uint16_t port=8125, bool datadog_format=false)
Helper function to create a StatsD exporter.
std::unique_ptr< otlp_metrics_exporter > create_otlp_metrics_exporter (const std::string &endpoint, const otel_resource &resource, metric_export_format format=metric_export_format::otlp_grpc)
Helper function to create an OTLP metrics exporter.
otel_resource create_service_resource (const std::string &service_name, const std::string &service_version="1.0.0", const std::string &service_namespace="")
Create OpenTelemetry resource with service information.
std::unique_ptr< opentelemetry_compatibility_layer > create_opentelemetry_compatibility_layer (const otel_resource &resource)
Create OpenTelemetry compatibility layer.
std::unique_ptr< opentelemetry_compatibility_layer > create_opentelemetry_compatibility_layer (const std::string &service_name, const std::string &service_version="1.0.0")
Create OpenTelemetry compatibility layer with service resource.
std::unique_ptr< jaeger_exporter > create_jaeger_exporter (const std::string &endpoint, trace_export_format format=trace_export_format::jaeger_grpc)
Helper function to create a Jaeger exporter.
std::unique_ptr< zipkin_exporter > create_zipkin_exporter (const std::string &endpoint, trace_export_format format=trace_export_format::zipkin_json)
Helper function to create a Zipkin exporter.
std::unique_ptr< otlp_exporter > create_otlp_exporter (const std::string &endpoint, const otel_resource &resource, trace_export_format format=trace_export_format::otlp_grpc)
Helper function to create an OTLP exporter.
constexpr const char * metric_type_to_string (metric_type type) noexcept
Convert metric type to string.
uint32_t hash_metric_name (const std::string &name) noexcept
Hash function for metric names.
metric_metadata create_metric_metadata (const std::string &name, metric_type type, size_t tag_count=0)
Create metric metadata from name and type.
std::unique_ptr< time_series > make_time_series (const std::string &name)
Helper function to create a time series with default configuration.
std::unique_ptr< time_series > make_time_series (const std::string &name, const time_series_config &config)
Helper function to create a time series with custom configuration.
distributed_tracer & global_tracer ()
Global tracer instance.
adaptive_monitor & global_adaptive_monitor ()
Global adaptive monitor instance.
std::unique_ptr< aggregation_processor > make_aggregation_processor (std::shared_ptr< metric_storage > storage=nullptr)
Helper function to create aggregation processor.
std::vector< aggregation_rule > create_standard_aggregation_rules ()
Create standard aggregation rules for common metrics.
std::unique_ptr< buffer_manager > make_buffer_manager (std::shared_ptr< metric_storage > storage=nullptr)
Helper function to create buffer manager with default configuration.
std::unique_ptr< buffer_manager > make_buffer_manager (const buffer_manager_config &config, std::shared_ptr< metric_storage > storage=nullptr)
Helper function to create buffer manager with custom configuration.
std::unique_ptr< buffer_strategy_interface > create_buffering_strategy (const buffering_config &config)
Factory function to create buffering strategy.
std::vector< buffering_config > create_default_buffering_configs ()
Create default buffering configurations for common scenarios.
std::unique_ptr< metric_storage > make_metric_storage ()
Helper function to create metric storage with default configuration.
std::unique_ptr< metric_storage > make_metric_storage (const metric_storage_config &config)
Helper function to create metric storage with custom configuration.
template<typename T >
std::unique_ptr< ring_buffer< T > > make_ring_buffer (size_t capacity=8192)
Helper function to create a ring buffer with default configuration.
template<typename T >
std::unique_ptr< ring_buffer< T > > make_ring_buffer (const ring_buffer_config &config)
Helper function to create a ring buffer with custom configuration.
std::unique_ptr< stream_aggregator > make_stream_aggregator ()
Helper function to create stream aggregator with default configuration.
std::unique_ptr< stream_aggregator > make_stream_aggregator (const stream_aggregator_config &config)
Helper function to create stream aggregator with custom configuration.
double pearson_correlation (const std::vector< double > &x, const std::vector< double > &y)
Calculate Pearson correlation coefficient between two series.
template<typename T >
result< T > make_success (T &&value)
std::unique_ptr< service_container_interface > create_lightweight_container ()
std::unique_ptr< service_container_interface > create_thread_system_adapter ()
Typedef Documentation
metric_value
using monitoring_system::metric_value = typedef std::variant<double, int64_t, std::string>
Type alias for metric value.
Definition at line 21 of file metric_types_adapter.h.
Enumeration Type Documentation
adaptation_strategy
enum class monitoring_system::adaptation_strategy strong
Adaptation strategy for monitoring behavior.
Enumerator
conservative
balanced
aggressive
Definition at line 36 of file adaptive_monitor.h.
aggregation_function
enum class monitoring_system::aggregation_function strong
Aggregation functions.
Enumerator
sum
avg
min
max
count
stddev
variance
percentile
rate
delta
derivative
integral
Definition at line 70 of file metric_query_engine.h.
binary_operator
enum class monitoring_system::binary_operator strong
Binary operators.
Enumerator
add
subtract
multiply
divide
modulo
power
equal
not_equal
less_than
less_equal
greater_than
greater_equal
logical_and
logical_or
Definition at line 41 of file metric_query_engine.h.
buffer_flush_trigger
enum class monitoring_system::buffer_flush_trigger : uint8_t strong
Triggers for buffer flushing.
Enumerator
size_threshold
time_interval
priority_threshold
memory_pressure
manual
adaptive
Definition at line 64 of file buffering_strategy.h.
buffer_overflow_policy
enum class monitoring_system::buffer_overflow_policy : uint8_t strong
Policies for handling buffer overflow.
Enumerator
drop_oldest
drop_newest
drop_lowest_priority
compress
flush_immediately
block_until_space
Definition at line 51 of file buffering_strategy.h.
buffering_strategy_type
enum class monitoring_system::buffering_strategy_type : uint8_t strong
Types of buffering strategies.
Enumerator
immediate
fixed_size
time_based
adaptive
priority_based
compression_based
Definition at line 38 of file buffering_strategy.h.
circuit_state
enum class monitoring_system::circuit_state strong
Circuit breaker states.
Enumerator
closed
open
half_open
Definition at line 13 of file circuit_breaker.h.
compression_algorithm
enum class monitoring_system::compression_algorithm strong
Compression algorithms.
Enumerator
none
gzip
lz4
zstd
Definition at line 26 of file storage_backends.h.
degradation_level
enum class monitoring_system::degradation_level strong
Degradation levels.
Enumerator
none
low
medium
high
critical
Definition at line 15 of file error_boundary.h.
event_priority
enum class monitoring_system::event_priority strong
Enumerator
low
normal
high
critical
Definition at line 75 of file event_bus_interface.h.
expression_type
enum class monitoring_system::expression_type strong
Query expression types.
Enumerator
literal
identifier
binary_op
unary_op
function_call
aggregation
Definition at line 29 of file metric_query_engine.h.
health_check_type
enum class monitoring_system::health_check_type strong
Health check types.
Enumerator
liveness
readiness
startup
Definition at line 70 of file health_monitor.h.
health_status [1/2]
enum class monitoring_system::health_status strong
System health status levels.
Enumerator
healthy
degraded
unhealthy
unknown
healthy
degraded
unhealthy
unknown
Definition at line 95 of file monitoring_interface.h.
health_status [2/2]
enum class monitoring_system::health_status strong
Basic health status enumeration.
Enumerator
healthy
degraded
unhealthy
unknown
healthy
degraded
unhealthy
unknown
Definition at line 15 of file health_monitor.h.
load_level
enum class monitoring_system::load_level strong
System load levels.
Enumerator
idle
low
moderate
high
critical
Definition at line 45 of file adaptive_monitor.h.
log_level
enum class monitoring_system::log_level strong
Log level enumeration.
Enumerator
trace
debug
info
warning
error
critical
fatal
Definition at line 28 of file logger_system_collector.h.
metric_export_format
enum class monitoring_system::metric_export_format strong
Supported metric export formats.
Enumerator
prometheus_text
Prometheus text exposition format.
prometheus_protobuf
Prometheus protocol buffers format.
statsd_plain
StatsD plain UDP format.
statsd_datadog
StatsD DataDog extension format.
otlp_grpc
OTLP gRPC metrics protocol.
otlp_http_json
OTLP HTTP JSON metrics protocol.
otlp_http_protobuf
OTLP HTTP Protocol Buffers metrics.
Definition at line 49 of file metric_exporters.h.
metric_type [1/3]
enum class monitoring_system::metric_type strong
Metric types supported by exporters.
Types of metrics supported by the system.
Enumerator
counter
Monotonically increasing counter.
gauge
Instantaneous value that can go up and down.
histogram
Distribution of values with buckets.
summary
Pre-calculated quantiles and count/sum.
timer
StatsD-specific timer metric.
counter
gauge
histogram
summary
timer
set
counter
gauge
histogram
summary
timer
set
Definition at line 63 of file metric_exporters.h.
metric_type [2/3]
enum class monitoring_system::metric_type : uint8_t strong
Enumerator
counter
Monotonically increasing counter.
gauge
Instantaneous value that can go up and down.
histogram
Distribution of values with buckets.
summary
Pre-calculated quantiles and count/sum.
timer
StatsD-specific timer metric.
counter
gauge
histogram
summary
timer
set
counter
gauge
histogram
summary
timer
set
Definition at line 32 of file metric_types.h.
metric_type [3/3]
enum class monitoring_system::metric_type : uint8_t strong
Enumerator
counter
Monotonically increasing counter.
gauge
Instantaneous value that can go up and down.
histogram
Distribution of values with buckets.
summary
Pre-calculated quantiles and count/sum.
timer
StatsD-specific timer metric.
counter
gauge
histogram
summary
timer
set
counter
gauge
histogram
summary
timer
set
Definition at line 32 of file metric_types.h.
monitoring_error_code [1/2]
enum class monitoring_system::monitoring_error_code : std::uint32_t strong
Comprehensive error codes for monitoring system operations.
Enumerator
success
collector_not_found
collection_failed
collector_initialization_failed
collector_already_exists
collector_disabled
invalid_collector_config
monitoring_disabled
storage_full
storage_corrupted
compression_failed
storage_not_initialized
storage_write_failed
storage_read_failed
storage_empty
invalid_configuration
invalid_interval
invalid_capacity
configuration_not_found
configuration_parse_error
system_resource_unavailable
permission_denied
out_of_memory
memory_allocation_failed
operation_timeout
operation_cancelled
thread_system_not_available
logger_system_not_available
incompatible_version
adapter_initialization_failed
metric_not_found
invalid_metric_type
metric_overflow
aggregation_failed
processing_failed
health_check_failed
health_check_timeout
health_check_not_registered
circuit_breaker_open
circuit_breaker_half_open
retry_attempts_exhausted
operation_failed
network_error
service_unavailable
service_degraded
error_boundary_triggered
fallback_failed
recovery_failed
invalid_argument
invalid_state
not_found
already_exists
resource_exhausted
already_started
dependency_missing
quota_exceeded
rate_limit_exceeded
cpu_throttled
memory_quota_exceeded
bandwidth_exceeded
resource_unavailable
transaction_failed
transaction_timeout
transaction_aborted
validation_failed
data_corrupted
state_inconsistent
deadlock_detected
rollback_failed
unknown_error
collector_not_found
Definition at line 27 of file error_codes.h.
monitoring_error_code [2/2]
enum class monitoring_system::monitoring_error_code strong
Enumerator
success
collector_not_found
collection_failed
collector_initialization_failed
collector_already_exists
collector_disabled
invalid_collector_config
monitoring_disabled
storage_full
storage_corrupted
compression_failed
storage_not_initialized
storage_write_failed
storage_read_failed
storage_empty
invalid_configuration
invalid_interval
invalid_capacity
configuration_not_found
configuration_parse_error
system_resource_unavailable
permission_denied
out_of_memory
memory_allocation_failed
operation_timeout
operation_cancelled
thread_system_not_available
logger_system_not_available
incompatible_version
adapter_initialization_failed
metric_not_found
invalid_metric_type
metric_overflow
aggregation_failed
processing_failed
health_check_failed
health_check_timeout
health_check_not_registered
circuit_breaker_open
circuit_breaker_half_open
retry_attempts_exhausted
operation_failed
network_error
service_unavailable
service_degraded
error_boundary_triggered
fallback_failed
recovery_failed
invalid_argument
invalid_state
not_found
already_exists
resource_exhausted
already_started
dependency_missing
quota_exceeded
rate_limit_exceeded
cpu_throttled
memory_quota_exceeded
bandwidth_exceeded
resource_unavailable
transaction_failed
transaction_timeout
transaction_aborted
validation_failed
data_corrupted
state_inconsistent
deadlock_detected
rollback_failed
unknown_error
collector_not_found
Definition at line 30 of file test_di_container.cpp.
otel_resource_type
enum class monitoring_system::otel_resource_type strong
OpenTelemetry resource types.
Enumerator
service
service_instance
host
container
process
runtime
telemetry_sdk
custom
Definition at line 37 of file opentelemetry_adapter.h.
otel_span_kind
enum class monitoring_system::otel_span_kind strong
OpenTelemetry span kinds.
Enumerator
unspecified
internal
server
client
producer
consumer
Definition at line 52 of file opentelemetry_adapter.h.
otel_status_code
enum class monitoring_system::otel_status_code strong
OpenTelemetry status codes.
Enumerator
unset
ok
error
Definition at line 65 of file opentelemetry_adapter.h.
retry_strategy
enum class monitoring_system::retry_strategy strong
Retry strategies.
Enumerator
fixed_delay
exponential_backoff
linear_backoff
Definition at line 12 of file retry_policy.h.
service_lifetime
enum class monitoring_system::service_lifetime strong
Enumerator
transient
singleton
scoped
Definition at line 65 of file test_di_container.cpp.
storage_backend_type
enum class monitoring_system::storage_backend_type strong
Storage backend types.
Enumerator
memory
file_json
file_binary
database
time_series
Definition at line 15 of file storage_backends.h.
trace_export_format
enum class monitoring_system::trace_export_format strong
Supported trace export formats.
Enumerator
jaeger_thrift
Jaeger Thrift protocol.
jaeger_grpc
Jaeger gRPC protocol.
zipkin_json
Zipkin JSON v2 format.
zipkin_protobuf
Zipkin Protocol Buffers format.
otlp_grpc
OTLP gRPC protocol.
otlp_http_json
OTLP HTTP JSON protocol.
otlp_http_protobuf
OTLP HTTP Protocol Buffers.
Definition at line 43 of file trace_exporters.h.
unary_operator
enum class monitoring_system::unary_operator strong
Unary operators.
Enumerator
negate
logical_not
absolute
Definition at line 61 of file metric_query_engine.h.
Function Documentation
create_buffering_strategy()
std::unique_ptr< buffer_strategy_interface > monitoring_system::create_buffering_strategy (const buffering_config & config) inline
Factory function to create buffering strategy.
Definition at line 871 of file buffering_strategy.h.
References create_buffering_strategy(), monitoring_system::buffering_config::strategy, and monitoring_system::buffering_config::validate().
Referenced by monitoring_system::buffer_manager::add_metric(), monitoring_system::buffer_manager::configure_metric_buffer(), create_buffering_strategy(), TEST_F(), and TEST_F().
create_default_buffering_configs()
std::vector< buffering_config > monitoring_system::create_default_buffering_configs () inline
Create default buffering configurations for common scenarios.
Definition at line 904 of file buffering_strategy.h.
References adaptive, create_default_buffering_configs(), monitoring_system::buffering_config::enable_background_flushing, monitoring_system::buffering_config::flush_interval, monitoring_system::buffering_config::flush_priority_threshold, monitoring_system::buffering_config::flush_threshold_size, monitoring_system::buffering_config::max_buffer_size, monitoring_system::buffering_config::overflow_policy, and monitoring_system::buffering_config::strategy.
Referenced by create_default_buffering_configs(), and TEST_F().
create_jaeger_exporter()
std::unique_ptr< jaeger_exporter > monitoring_system::create_jaeger_exporter (const std::string & endpoint, trace_export_format format = trace_export_format::jaeger_grpc) inline
Helper function to create a Jaeger exporter.
Definition at line 560 of file trace_exporters.h.
References monitoring_system::trace_export_config::endpoint, and monitoring_system::trace_export_config::format.
Referenced by TEST_F().
create_lightweight_container()
std::unique_ptr< service_container_interface > monitoring_system::create_lightweight_container () inline
Definition at line 208 of file test_di_container.cpp.
Referenced by DIContainerTest::SetUp(), and TEST_F().
create_metric_metadata()
metric_metadata monitoring_system::create_metric_metadata (const std::string & name, metric_type type, size_t tag_count = 0) inline
Create metric metadata from name and type.
Definition at line 350 of file metric_types.h.
References hash_metric_name().
Referenced by monitoring_system::metric_storage::store_metric(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
create_opentelemetry_compatibility_layer() [1/2]
std::unique_ptr< opentelemetry_compatibility_layer > monitoring_system::create_opentelemetry_compatibility_layer (const otel_resource & resource) inline
Create OpenTelemetry compatibility layer.
Definition at line 555 of file opentelemetry_adapter.h.
Referenced by create_opentelemetry_compatibility_layer(), OpenTelemetryAdapterTest::SetUp(), TEST_F(), TEST_F(), and TEST_F().
create_opentelemetry_compatibility_layer() [2/2]
std::unique_ptr< opentelemetry_compatibility_layer > monitoring_system::create_opentelemetry_compatibility_layer (const std::string & service_name, const std::string & service_version = "1.0.0") inline
Create OpenTelemetry compatibility layer with service resource.
Definition at line 563 of file opentelemetry_adapter.h.
References create_opentelemetry_compatibility_layer(), and create_service_resource().
create_otlp_exporter()
std::unique_ptr< otlp_exporter > monitoring_system::create_otlp_exporter (const std::string & endpoint, const otel_resource & resource, trace_export_format format = trace_export_format::otlp_grpc) inline
Helper function to create an OTLP exporter.
Definition at line 586 of file trace_exporters.h.
References monitoring_system::trace_export_config::endpoint, and monitoring_system::trace_export_config::format.
Referenced by TEST_F().
create_otlp_metrics_exporter()
std::unique_ptr< otlp_metrics_exporter > monitoring_system::create_otlp_metrics_exporter (const std::string & endpoint, const otel_resource & resource, metric_export_format format = metric_export_format::otlp_grpc) inline
Helper function to create an OTLP metrics exporter.
Definition at line 877 of file metric_exporters.h.
References monitoring_system::metric_export_config::endpoint, and monitoring_system::metric_export_config::format.
Referenced by TEST_F().
create_prometheus_exporter()
std::unique_ptr< prometheus_exporter > monitoring_system::create_prometheus_exporter (std::uint16_t port = 9090, const std::string & job_name = "monitoring_system") inline
Helper function to create a Prometheus exporter.
Definition at line 848 of file metric_exporters.h.
References monitoring_system::metric_export_config::format, monitoring_system::metric_export_config::job_name, monitoring_system::metric_export_config::port, and prometheus_text.
Referenced by TEST_F().
create_service_resource()
otel_resource monitoring_system::create_service_resource (const std::string & service_name, const std::string & service_version = "1.0.0", const std::string & service_namespace = "") inline
Create OpenTelemetry resource with service information.
Definition at line 534 of file opentelemetry_adapter.h.
References monitoring_system::otel_resource::add_attribute(), service, and monitoring_system::otel_resource::type.
Referenced by create_opentelemetry_compatibility_layer(), MetricExportersTest::SetUp(), OpenTelemetryAdapterTest::SetUp(), TraceExportersTest::SetUp(), and TEST_F().
create_standard_aggregation_rules()
std::vector< aggregation_rule > monitoring_system::create_standard_aggregation_rules () inline
Create standard aggregation rules for common metrics.
Definition at line 497 of file aggregation_processor.h.
References monitoring_system::aggregation_rule::compute_rate, monitoring_system::aggregation_rule::detect_outliers, monitoring_system::aggregation_rule::percentiles, monitoring_system::aggregation_rule::source_metric, and monitoring_system::aggregation_rule::target_metric_prefix.
Referenced by TEST_F().
create_statsd_exporter()
std::unique_ptr< statsd_exporter > monitoring_system::create_statsd_exporter (const std::string & host = "localhost", std::uint16_t port = 8125, bool datadog_format = false) inline
Helper function to create a StatsD exporter.
Definition at line 862 of file metric_exporters.h.
References monitoring_system::metric_export_config::endpoint, monitoring_system::metric_export_config::format, host, monitoring_system::metric_export_config::port, statsd_datadog, and statsd_plain.
Referenced by TEST_F().
create_thread_system_adapter()
std::unique_ptr< service_container_interface > monitoring_system::create_thread_system_adapter () inline
Definition at line 235 of file test_di_container.cpp.
Referenced by TEST_F().
create_zipkin_exporter()
std::unique_ptr< zipkin_exporter > monitoring_system::create_zipkin_exporter (const std::string & endpoint, trace_export_format format = trace_export_format::zipkin_json) inline
Helper function to create a Zipkin exporter.
Definition at line 573 of file trace_exporters.h.
References monitoring_system::trace_export_config::endpoint, and monitoring_system::trace_export_config::format.
Referenced by TEST_F().
error_code_to_string()
std::string monitoring_system::error_code_to_string (monitoring_error_code code) inline
Convert error code to string representation.
Parameters
code The error code to convert
Returns
String representation of the error code
Definition at line 130 of file error_codes.h.
References adapter_initialization_failed, aggregation_failed, already_exists, already_started, bandwidth_exceeded, circuit_breaker_half_open, circuit_breaker_open, collection_failed, collector_already_exists, collector_disabled, collector_initialization_failed, collector_not_found, compression_failed, configuration_not_found, configuration_parse_error, cpu_throttled, data_corrupted, deadlock_detected, dependency_missing, error_boundary_triggered, fallback_failed, health_check_failed, health_check_not_registered, health_check_timeout, incompatible_version, invalid_argument, invalid_capacity, invalid_collector_config, invalid_configuration, invalid_interval, invalid_metric_type, invalid_state, logger_system_not_available, memory_allocation_failed, memory_quota_exceeded, metric_not_found, metric_overflow, monitoring_disabled, network_error, not_found, operation_cancelled, operation_failed, operation_timeout, out_of_memory, permission_denied, quota_exceeded, rate_limit_exceeded, recovery_failed, resource_exhausted, resource_unavailable, retry_attempts_exhausted, rollback_failed, service_degraded, service_unavailable, state_inconsistent, storage_corrupted, storage_empty, storage_full, storage_not_initialized, storage_read_failed, storage_write_failed, success, system_resource_unavailable, thread_system_not_available, transaction_aborted, transaction_failed, transaction_timeout, unknown_error, and validation_failed.
Referenced by get_error_details(), TEST_F(), and monitoring_system::error_info::to_string().
get_error_details()
std::string monitoring_system::get_error_details (monitoring_error_code code) inline
Get detailed error message.
Parameters
code The error code
Returns
Detailed error message with suggestions
Definition at line 303 of file error_codes.h.
References bandwidth_exceeded, circuit_breaker_open, collector_not_found, cpu_throttled, data_corrupted, deadlock_detected, error_boundary_triggered, error_code_to_string(), fallback_failed, invalid_configuration, memory_quota_exceeded, operation_failed, quota_exceeded, rate_limit_exceeded, resource_unavailable, retry_attempts_exhausted, rollback_failed, service_degraded, state_inconsistent, storage_full, thread_system_not_available, transaction_aborted, transaction_failed, transaction_timeout, and validation_failed.
global_adaptive_monitor()
adaptive_monitor & monitoring_system::global_adaptive_monitor ()
Global adaptive monitor instance.
Definition at line 344 of file adaptive_monitor.cpp.
Referenced by TEST_F(), and TEST_F().
global_performance_monitor()
performance_monitor & monitoring_system::global_performance_monitor ()
Global performance monitor instance.
Definition at line 231 of file performance_monitor.cpp.
Referenced by TEST_F().
global_tracer()
distributed_tracer & monitoring_system::global_tracer () inline
Global tracer instance.
Definition at line 192 of file distributed_tracer.h.
References monitoring_system::distributed_tracer::instance().
Referenced by TEST_F().
hash_metric_name()
uint32_t monitoring_system::hash_metric_name (const std::string & name) inline noexcept
Hash function for metric names.
Definition at line 337 of file metric_types.h.
Referenced by create_metric_metadata(), monitoring_system::metric_storage::get_latest_value(), and monitoring_system::metric_storage::query_metric().
make_aggregation_processor()
std::unique_ptr< aggregation_processor > monitoring_system::make_aggregation_processor (std::shared_ptr< metric_storage > storage = nullptr) inline
Helper function to create aggregation processor.
Definition at line 489 of file aggregation_processor.h.
make_buffer_manager() [1/2]
std::unique_ptr< buffer_manager > monitoring_system::make_buffer_manager (const buffer_manager_config & config, std::shared_ptr< metric_storage > storage = nullptr) inline
Helper function to create buffer manager with custom configuration.
Definition at line 555 of file buffer_manager.h.
make_buffer_manager() [2/2]
std::unique_ptr< buffer_manager > monitoring_system::make_buffer_manager (std::shared_ptr< metric_storage > storage = nullptr) inline
Helper function to create buffer manager with default configuration.
Definition at line 547 of file buffer_manager.h.
make_error()
template<typename T > result< T > monitoring_system::make_error (monitoring_error_code code, const std::string & message = "")
Create an error result.
Template Parameters
T The expected value type
Parameters
code The error code
message Optional error message
Returns
result<T> containing the error
Definition at line 248 of file result_types.h.
make_error_with_context()
template<typename T > result< T > monitoring_system::make_error_with_context (monitoring_error_code code, const std::string & message, const std::string & context)
Create an error result with context.
Template Parameters
T The expected value type
Parameters
code The error code
message Error message
context Additional context
Returns
result<T> containing the error with context
Definition at line 262 of file result_types.h.
References error.
make_metric_storage() [1/2]
std::unique_ptr< metric_storage > monitoring_system::make_metric_storage () inline
Helper function to create metric storage with default configuration.
Definition at line 492 of file metric_storage.h.
make_metric_storage() [2/2]
std::unique_ptr< metric_storage > monitoring_system::make_metric_storage (const metric_storage_config & config) inline
Helper function to create metric storage with custom configuration.
Definition at line 499 of file metric_storage.h.
make_ring_buffer() [1/2]
template<typename T > std::unique_ptr< ring_buffer< T > > monitoring_system::make_ring_buffer (const ring_buffer_config & config)
Helper function to create a ring buffer with custom configuration.
Definition at line 382 of file ring_buffer.h.
make_ring_buffer() [2/2]
template<typename T > std::unique_ptr< ring_buffer< T > > monitoring_system::make_ring_buffer (size_t capacity = 8192)
Helper function to create a ring buffer with default configuration.
Definition at line 372 of file ring_buffer.h.
References monitoring_system::ring_buffer_config::capacity.
make_stream_aggregator() [1/2]
std::unique_ptr< stream_aggregator > monitoring_system::make_stream_aggregator () inline
Helper function to create stream aggregator with default configuration.
Definition at line 661 of file stream_aggregator.h.
make_stream_aggregator() [2/2]
std::unique_ptr< stream_aggregator > monitoring_system::make_stream_aggregator (const stream_aggregator_config & config) inline
Helper function to create stream aggregator with custom configuration.
Definition at line 668 of file stream_aggregator.h.
make_success() [1/2]
template<typename T > result< std::decay_t< T > > monitoring_system::make_success (T && value)
Create a successful result.
Template Parameters
T The value type
Parameters
value The success value
Returns
result<T> containing the value
Definition at line 236 of file result_types.h.
Referenced by ErrorBoundariesTest::always_succeeding_operation(), FaultToleranceTest::always_succeeding_operation(), monitoring_system::performance_monitor::check_thresholds(), monitoring_system::service_container_interface::clear(), monitoring_system::performance_profiler::clear_samples(), monitoring_system::performance_monitor::collect(), monitoring_system::monitoring_aggregator::collect_all(), monitoring_system::opentelemetry_metrics_adapter::convert_metrics(), monitoring_system::opentelemetry_metrics_adapter::convert_monitoring_data(), monitoring_system::opentelemetry_tracer_adapter::convert_span(), monitoring_system::opentelemetry_tracer_adapter::convert_spans(), monitoring_system::opentelemetry_tracer_adapter::create_context(), ErrorBoundariesTest::failing_operation(), FaultToleranceTest::failing_operation(), monitoring_system::kv_storage_backend::flush(), monitoring_system::file_storage_backend::flush(), monitoring_system::immediate_strategy::flush(), monitoring_system::fixed_size_strategy::flush(), monitoring_system::time_based_strategy::flush(), monitoring_system::priority_based_strategy::flush(), monitoring_system::adaptive_strategy::flush(), monitoring_system::aggregation_processor::get_aggregation_rule(), monitoring_system::otel_resource::get_attribute(), monitoring_system::buffer_manager::get_buffer_size(), monitoring_system::buffer_manager::get_buffer_statistics(), monitoring_system::system_monitor::get_current_metrics(), monitoring_system::aggregation_processor::get_current_statistics(), monitoring_system::time_series::get_latest_value(), test_monitorable_component::get_monitoring_data(), monitoring_system::stream_aggregator::get_percentile(), monitoring_system::time_series::query(), monitoring_system::service_container_interface::register_factory(), monitoring_system::service_container_interface::register_factory(), monitoring_system::service_container_interface::register_singleton(), monitoring_system::service_container_interface::resolve(), monitoring_system::service_container_interface::resolve(), FaultToleranceTest::slow_operation(), monitoring_system::system_monitor::start_monitoring(), monitoring_system::system_monitor::stop_monitoring(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and ResourceManagementTest::test_operation().
make_success() [2/2]
template<typename T > result< T > monitoring_system::make_success (T && value)
Definition at line 38 of file test_di_container.cpp.
make_time_series() [1/2]
std::unique_ptr< time_series > monitoring_system::make_time_series (const std::string & name) inline
Helper function to create a time series with default configuration.
Definition at line 474 of file time_series.h.
make_time_series() [2/2]
std::unique_ptr< time_series > monitoring_system::make_time_series (const std::string & name, const time_series_config & config) inline
Helper function to create a time series with custom configuration.
Definition at line 481 of file time_series.h.
metric_type_to_string()
constexpr const char * monitoring_system::metric_type_to_string (metric_type type) constexpr noexcept
Convert metric type to string.
Definition at line 44 of file metric_types.h.
References counter, gauge, histogram, set, summary, and timer.
pearson_correlation()
double monitoring_system::pearson_correlation (const std::vector< double > & x, const std::vector< double > & y) inline
Calculate Pearson correlation coefficient between two series.
Definition at line 675 of file stream_aggregator.h.
Referenced by TEST_F().