Messaging System: monitoring_module::scoped_monitoring_crash_protection Class Reference
monitoring_module::scoped_monitoring_crash_protection Class Reference
RAII helper for automatic monitoring component registration.
#include <monitoring_crash_safety.h>
Public Member Functions
scoped_monitoring_crash_protection (const std::string &name, std::function< std::string()> save_callback, std::function< void(const std::string &)> restore_callback)
~scoped_monitoring_crash_protection ()
scoped_monitoring_crash_protection (const scoped_monitoring_crash_protection &)=delete
scoped_monitoring_crash_protection & operator= (const scoped_monitoring_crash_protection &)=delete
scoped_monitoring_crash_protection (scoped_monitoring_crash_protection &&)=default
scoped_monitoring_crash_protection & operator= (scoped_monitoring_crash_protection &&)=default
Detailed Description
RAII helper for automatic monitoring component registration.
Definition at line 229 of file monitoring_crash_safety.h.
Constructor & Destructor Documentation
scoped_monitoring_crash_protection() [1/3]
monitoring_module::scoped_monitoring_crash_protection::scoped_monitoring_crash_protection (const std::string & name, std::function< std::string()> save_callback, std::function< void(const std::string &)> restore_callback) inline
Definition at line 231 of file monitoring_crash_safety.h.
References monitoring_module::monitoring_crash_safety::instance(), and monitoring_module::monitoring_crash_safety::register_monitoring_component().
~scoped_monitoring_crash_protection()
monitoring_module::scoped_monitoring_crash_protection::~scoped_monitoring_crash_protection () inline
Definition at line 238 of file monitoring_crash_safety.h.
References monitoring_module::monitoring_crash_safety::instance(), and monitoring_module::monitoring_crash_safety::unregister_monitoring_component().
scoped_monitoring_crash_protection() [2/3]
monitoring_module::scoped_monitoring_crash_protection::scoped_monitoring_crash_protection (const scoped_monitoring_crash_protection &) delete
scoped_monitoring_crash_protection() [3/3]
monitoring_module::scoped_monitoring_crash_protection::scoped_monitoring_crash_protection (scoped_monitoring_crash_protection &&) default
Member Function Documentation
operator=() [1/2]
scoped_monitoring_crash_protection & monitoring_module::scoped_monitoring_crash_protection::operator= (const scoped_monitoring_crash_protection &) delete
operator=() [2/2]
scoped_monitoring_crash_protection & monitoring_module::scoped_monitoring_crash_protection::operator= (scoped_monitoring_crash_protection &&) default
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/interfaces/monitoring_crash_safety.h