Messaging System: monitoring_system::performance_monitor Class Reference
monitoring_system::performance_monitor Class Reference
Performance monitor combining profiling and system monitoring.
#include <performance_monitor.h>
Public Member Functions
performance_monitor (const std::string &name="performance_monitor")
std::string get_name () const override
Get collector name.
bool is_enabled () const override
Check if collector is enabled.
result_void set_enabled (bool enable) override
Enable or disable the collector.
result_void initialize () override
Initialize the collector.
result_void cleanup () override
Cleanup collector resources.
monitoring_system::result< metrics_snapshot > collect () override
Collect metrics.
scoped_timer time_operation (const std::string &operation_name)
Create a scoped timer for an operation.
performance_profiler & get_profiler ()
Get performance profiler.
const performance_profiler & get_profiler () const
system_monitor & get_system_monitor ()
Get system monitor.
const system_monitor & get_system_monitor () const
void set_cpu_threshold (double threshold)
Set performance thresholds.
void set_memory_threshold (double threshold)
void set_latency_threshold (std::chrono::milliseconds threshold)
monitoring_system::result< bool > check_thresholds () const
Check if any thresholds are exceeded.
Public Member Functions inherited from monitoring_system::metrics_collector
virtual ~metrics_collector ()=default
Detailed Description
Performance monitor combining profiling and system monitoring.
Definition at line 284 of file performance_monitor.h.
Constructor & Destructor Documentation
performance_monitor()
monitoring_system::performance_monitor::performance_monitor (const std::string & name = "performance_monitor") inline explicit
Definition at line 299 of file performance_monitor.h.
Member Function Documentation
check_thresholds()
result< bool > monitoring_system::performance_monitor::check_thresholds () const
Check if any thresholds are exceeded.
Definition at line 186 of file performance_monitor.cpp.
References monitoring_system::make_success().
cleanup()
result_void monitoring_system::performance_monitor::cleanup () inline override virtual
Cleanup collector resources.
Returns
Result indicating success or cleanup error
Implements monitoring_system::metrics_collector.
Definition at line 320 of file performance_monitor.h.
References monitoring_system::error_info::code, monitoring_system::result< T >::get_error(), monitoring_system::error_info::message, and monitoring_system::system_monitor::stop_monitoring().
Referenced by main(), and PerformanceMonitoringTest::TearDown().
collect()
result< metrics_snapshot > monitoring_system::performance_monitor::collect () override virtual
Collect metrics.
Returns
Result containing collected metrics or error
Implements monitoring_system::metrics_collector.
Definition at line 166 of file performance_monitor.cpp.
References monitoring_system::metrics_snapshot::add_metric(), monitoring_system::metrics_snapshot::capture_time, monitoring_system::system_monitor::get_current_metrics(), monitoring_system::make_success(), and monitoring_system::metrics_snapshot::source_id.
Referenced by main().
get_name()
std::string monitoring_system::performance_monitor::get_name () const inline override virtual
Get collector name.
Returns
Collector identifier
Implements monitoring_system::metrics_collector.
Definition at line 303 of file performance_monitor.h.
get_profiler() [1/2]
performance_profiler & monitoring_system::performance_monitor::get_profiler () inline
Get performance profiler.
Definition at line 340 of file performance_monitor.h.
get_profiler() [2/2]
const performance_profiler & monitoring_system::performance_monitor::get_profiler () const inline
Definition at line 341 of file performance_monitor.h.
get_system_monitor() [1/2]
system_monitor & monitoring_system::performance_monitor::get_system_monitor () inline
Get system monitor.
Definition at line 346 of file performance_monitor.h.
Referenced by main().
get_system_monitor() [2/2]
const system_monitor & monitoring_system::performance_monitor::get_system_monitor () const inline
Definition at line 347 of file performance_monitor.h.
initialize()
result_void monitoring_system::performance_monitor::initialize () inline override virtual
Initialize the collector.
Returns
Result indicating success or initialization error
Implements monitoring_system::metrics_collector.
Definition at line 312 of file performance_monitor.h.
References monitoring_system::error_info::code, monitoring_system::result< T >::get_error(), monitoring_system::error_info::message, and monitoring_system::system_monitor::start_monitoring().
Referenced by main().
is_enabled()
bool monitoring_system::performance_monitor::is_enabled () const inline override virtual
Check if collector is enabled.
Returns
true if collector is active
Implements monitoring_system::metrics_collector.
Definition at line 304 of file performance_monitor.h.
set_cpu_threshold()
void monitoring_system::performance_monitor::set_cpu_threshold (double threshold) inline
Set performance thresholds.
Definition at line 352 of file performance_monitor.h.
set_enabled()
result_void monitoring_system::performance_monitor::set_enabled (bool enable) inline override virtual
Enable or disable the collector.
Parameters
enable true to enable, false to disable
Returns
Result indicating success or error
Implements monitoring_system::metrics_collector.
Definition at line 306 of file performance_monitor.h.
References monitoring_system::performance_profiler::set_enabled().
Referenced by PerformanceMonitoringTest::SetUp().
set_latency_threshold()
void monitoring_system::performance_monitor::set_latency_threshold (std::chrono::milliseconds threshold) inline
Definition at line 360 of file performance_monitor.h.
set_memory_threshold()
void monitoring_system::performance_monitor::set_memory_threshold (double threshold) inline
Definition at line 356 of file performance_monitor.h.
time_operation()
scoped_timer monitoring_system::performance_monitor::time_operation (const std::string & operation_name) inline
Create a scoped timer for an operation.
Definition at line 333 of file performance_monitor.h.
Referenced by main().
The documentation for this class was generated from the following files:
libraries/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h
libraries/monitoring_system/src/core/performance_monitor.cpp