Messaging System: kcenon::thread::thread_context Class Reference
kcenon::thread::thread_context Class Reference
Context object that provides access to optional services.
#include <thread_context.h>
Public Member Functions
thread_context ()
Default constructor - resolves services from global container.
thread_context (std::shared_ptr< logger_interface > logger, std::shared_ptr< monitoring_interface::monitoring_interface > monitoring=nullptr)
Constructor with explicit service injection.
std::shared_ptr< logger_interface > logger () const
Get the logger service.
std::shared_ptr< monitoring_interface::monitoring_interface > monitoring () const
Get the monitoring service.
void log (log_level level, const std::string &message) const
Log a message if logger is available.
void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function) const
Log a message with source information if logger is available.
void update_system_metrics (const monitoring_interface::system_metrics &metrics) const
Update system metrics if monitoring is available.
void update_thread_pool_metrics (const monitoring_interface::thread_pool_metrics &metrics) const
Update thread pool metrics if monitoring is available.
void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const monitoring_interface::thread_pool_metrics &metrics) const
Update thread pool metrics with pool identifier.
void update_worker_metrics (std::size_t worker_id, const monitoring_interface::worker_metrics &metrics) const
Update worker metrics if monitoring is available.
thread_context create_child () const
Create a child context with the same services.
auto get_context_name () const -> std::string
Get context name.
auto set_context_name (const std::string &name) -> bool
Set context name.
auto has_logger () const -> bool
Check if logger is available.
auto has_monitoring () const -> bool
Check if monitoring is available.
Detailed Description
Context object that provides access to optional services.
This class uses composition to provide thread system components with optional access to logger and monitoring services.
Definition at line 49 of file thread_context.h.
Constructor & Destructor Documentation
thread_context() [1/2]
kcenon::thread::thread_context::thread_context () inline
Default constructor - resolves services from global container.
Definition at line 54 of file thread_context.h.
Referenced by create_child().
thread_context() [2/2]
kcenon::thread::thread_context::thread_context (std::shared_ptr< logger_interface > logger, std::shared_ptr< monitoring_interface::monitoring_interface > monitoring = nullptr) inline explicit
Constructor with explicit service injection.
Parameters
logger Optional logger service
monitoring Optional monitoring service
Definition at line 64 of file thread_context.h.
Member Function Documentation
create_child()
thread_context kcenon::thread::thread_context::create_child () const inline
Create a child context with the same services.
Returns
New context with shared services
Definition at line 163 of file thread_context.h.
References thread_context().
get_context_name()
auto kcenon::thread::thread_context::get_context_name () const -> std::string inline
Get context name.
Returns
Context name
Definition at line 171 of file thread_context.h.
has_logger()
auto kcenon::thread::thread_context::has_logger () const -> bool inline
Check if logger is available.
Returns
True if logger is set
Definition at line 189 of file thread_context.h.
has_monitoring()
auto kcenon::thread::thread_context::has_monitoring () const -> bool inline
Check if monitoring is available.
Returns
True if monitoring is set
Definition at line 197 of file thread_context.h.
log() [1/2]
void kcenon::thread::thread_context::log (log_level level, const std::string & message) const inline
Log a message if logger is available.
Parameters
level Log level
message Log message
Definition at line 92 of file thread_context.h.
log() [2/2]
void kcenon::thread::thread_context::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) const inline
Log a message with source information if logger is available.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
Definition at line 106 of file thread_context.h.
logger()
std::shared_ptr< logger_interface > kcenon::thread::thread_context::logger () const inline
Get the logger service.
Returns
Logger service or nullptr if not available
Definition at line 75 of file thread_context.h.
monitoring()
std::shared_ptr< monitoring_interface::monitoring_interface > kcenon::thread::thread_context::monitoring () const inline
Get the monitoring service.
Returns
Monitoring service or nullptr if not available
Definition at line 83 of file thread_context.h.
Referenced by kcenon::thread::thread_pool::report_metrics(), and kcenon::thread::thread_pool::thread_pool().
set_context_name()
auto kcenon::thread::thread_context::set_context_name (const std::string & name) -> bool inline
Set context name.
Parameters
name New context name
Returns
True if successful
Definition at line 180 of file thread_context.h.
update_system_metrics()
void kcenon::thread::thread_context::update_system_metrics (const monitoring_interface::system_metrics & metrics) const inline
Update system metrics if monitoring is available.
Parameters
metrics System metrics to record
Definition at line 117 of file thread_context.h.
update_thread_pool_metrics() [1/2]
void kcenon::thread::thread_context::update_thread_pool_metrics (const monitoring_interface::thread_pool_metrics & metrics) const inline
Update thread pool metrics if monitoring is available.
Parameters
metrics Thread pool metrics to record
Definition at line 127 of file thread_context.h.
Referenced by kcenon::thread::thread_pool::report_metrics(), and kcenon::thread::thread_pool::thread_pool().
update_thread_pool_metrics() [2/2]
void kcenon::thread::thread_context::update_thread_pool_metrics (const std::string & pool_name, std::uint32_t pool_instance_id, const monitoring_interface::thread_pool_metrics & metrics) const inline
Update thread pool metrics with pool identifier.
Parameters
pool_name Name of the thread pool
pool_instance_id Instance ID for multiple pools
metrics Thread pool metrics to record
Definition at line 139 of file thread_context.h.
update_worker_metrics()
void kcenon::thread::thread_context::update_worker_metrics (std::size_t worker_id, const monitoring_interface::worker_metrics & metrics) const inline
Update worker metrics if monitoring is available.
Parameters
worker_id Worker identifier
metrics Worker metrics to record
Definition at line 152 of file thread_context.h.
The documentation for this class was generated from the following file:
libraries/thread_system/include/kcenon/thread/interfaces/thread_context.h