Messaging System: thread_module::thread_context Class Reference
thread_module::thread_context Class Reference
Context object that provides access to optional services.
#include <thread_context.h>
Public Member Functions
thread_context ()
Default constructor - resolves services from global container.
thread_context (std::shared_ptr< logger_interface > logger, std::shared_ptr< monitoring_interface::monitoring_interface > monitoring=nullptr)
Constructor with explicit service injection.
std::shared_ptr< logger_interface > logger () const
Get the logger service.
std::shared_ptr< monitoring_interface::monitoring_interface > monitoring () const
Get the monitoring service.
void log (log_level level, const std::string &message) const
Log a message if logger is available.
void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function) const
Log a message with source information if logger is available.
void update_system_metrics (const monitoring_interface::system_metrics &metrics) const
Update system metrics if monitoring is available.
void update_thread_pool_metrics (const monitoring_interface::thread_pool_metrics &metrics) const
Update thread pool metrics if monitoring is available.
void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const monitoring_interface::thread_pool_metrics &metrics) const
Update thread pool metrics with pool identifier.
void update_worker_metrics (std::size_t worker_id, const monitoring_interface::worker_metrics &metrics) const
Update worker metrics if monitoring is available.
thread_context create_child () const
Create a child context with the same services.
thread_context ()
Default constructor - resolves services from global container.
thread_context (std::shared_ptr< logger_interface > logger, std::shared_ptr< monitoring_interface::monitoring_interface > monitoring=nullptr)
Constructor with explicit service injection.
std::shared_ptr< logger_interface > logger () const
Get the logger service.
std::shared_ptr< monitoring_interface::monitoring_interface > monitoring () const
Get the monitoring service.
void log (log_level level, const std::string &message) const
Log a message if logger is available.
void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function) const
Log a message with source information if logger is available.
void update_system_metrics (const monitoring_interface::system_metrics &metrics) const
Update system metrics if monitoring is available.
void update_thread_pool_metrics (const monitoring_interface::thread_pool_metrics &metrics) const
Update thread pool metrics if monitoring is available.
void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const monitoring_interface::thread_pool_metrics &metrics) const
Update thread pool metrics with pool identifier.
void update_worker_metrics (std::size_t worker_id, const monitoring_interface::worker_metrics &metrics) const
Update worker metrics if monitoring is available.
thread_context create_child () const
Create a child context with the same services.
Detailed Description
Context object that provides access to optional services.
This class uses composition to provide thread system components with optional access to logger and monitoring services.
Definition at line 49 of file thread_context.h.
Constructor & Destructor Documentation
thread_context() [1/4]
thread_module::thread_context::thread_context () inline
Default constructor - resolves services from global container.
Definition at line 54 of file thread_context.h.
Referenced by create_child().
thread_context() [2/4]
thread_module::thread_context::thread_context (std::shared_ptr< logger_interface > logger, std::shared_ptr< monitoring_interface::monitoring_interface > monitoring = nullptr) inline explicit
Constructor with explicit service injection.
Parameters
logger Optional logger service
monitoring Optional monitoring service
Definition at line 64 of file thread_context.h.
thread_context() [3/4]
thread_module::thread_context::thread_context () inline
Default constructor - resolves services from global container.
Definition at line 54 of file thread_context.h.
thread_context() [4/4]
thread_module::thread_context::thread_context (std::shared_ptr< logger_interface > logger, std::shared_ptr< monitoring_interface::monitoring_interface > monitoring = nullptr) inline explicit
Constructor with explicit service injection.
Parameters
logger Optional logger service
monitoring Optional monitoring service
Definition at line 64 of file thread_context.h.
Member Function Documentation
create_child() [1/2]
thread_context thread_module::thread_context::create_child () const inline
Create a child context with the same services.
Returns
New context with shared services
Definition at line 163 of file thread_context.h.
References thread_context().
create_child() [2/2]
thread_context thread_module::thread_context::create_child () const inline
Create a child context with the same services.
Returns
New context with shared services
Definition at line 163 of file thread_context.h.
References thread_context().
log() [1/4]
void thread_module::thread_context::log (log_level level, const std::string & message) const inline
Log a message if logger is available.
Parameters
level Log level
message Log message
Definition at line 92 of file thread_context.h.
log() [2/4]
void thread_module::thread_context::log (log_level level, const std::string & message) const inline
Log a message if logger is available.
Parameters
level Log level
message Log message
Definition at line 92 of file thread_context.h.
log() [3/4]
void thread_module::thread_context::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) const inline
Log a message with source information if logger is available.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
Definition at line 106 of file thread_context.h.
log() [4/4]
void thread_module::thread_context::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) const inline
Log a message with source information if logger is available.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
Definition at line 106 of file thread_context.h.
logger() [1/2]
std::shared_ptr< logger_interface > thread_module::thread_context::logger () const inline
Get the logger service.
Returns
Logger service or nullptr if not available
Definition at line 75 of file thread_context.h.
logger() [2/2]
std::shared_ptr< logger_interface > thread_module::thread_context::logger () const inline
Get the logger service.
Returns
Logger service or nullptr if not available
Definition at line 75 of file thread_context.h.
monitoring() [1/2]
std::shared_ptr< monitoring_interface::monitoring_interface > thread_module::thread_context::monitoring () const inline
Get the monitoring service.
Returns
Monitoring service or nullptr if not available
Definition at line 83 of file thread_context.h.
Referenced by thread_pool_module::thread_pool::report_metrics(), and thread_pool_module::thread_pool::thread_pool().
monitoring() [2/2]
std::shared_ptr< monitoring_interface::monitoring_interface > thread_module::thread_context::monitoring () const inline
Get the monitoring service.
Returns
Monitoring service or nullptr if not available
Definition at line 83 of file thread_context.h.
update_system_metrics() [1/2]
void thread_module::thread_context::update_system_metrics (const monitoring_interface::system_metrics & metrics) const inline
Update system metrics if monitoring is available.
Parameters
metrics System metrics to record
Definition at line 117 of file thread_context.h.
update_system_metrics() [2/2]
void thread_module::thread_context::update_system_metrics (const monitoring_interface::system_metrics & metrics) const inline
Update system metrics if monitoring is available.
Parameters
metrics System metrics to record
Definition at line 117 of file thread_context.h.
update_thread_pool_metrics() [1/4]
void thread_module::thread_context::update_thread_pool_metrics (const monitoring_interface::thread_pool_metrics & metrics) const inline
Update thread pool metrics if monitoring is available.
Parameters
metrics Thread pool metrics to record
Definition at line 127 of file thread_context.h.
Referenced by thread_pool_module::thread_pool::report_metrics(), and thread_pool_module::thread_pool::thread_pool().
update_thread_pool_metrics() [2/4]
void thread_module::thread_context::update_thread_pool_metrics (const monitoring_interface::thread_pool_metrics & metrics) const inline
Update thread pool metrics if monitoring is available.
Parameters
metrics Thread pool metrics to record
Definition at line 127 of file thread_context.h.
update_thread_pool_metrics() [3/4]
void thread_module::thread_context::update_thread_pool_metrics (const std::string & pool_name, std::uint32_t pool_instance_id, const monitoring_interface::thread_pool_metrics & metrics) const inline
Update thread pool metrics with pool identifier.
Parameters
pool_name Name of the thread pool
pool_instance_id Instance ID for multiple pools
metrics Thread pool metrics to record
Definition at line 139 of file thread_context.h.
update_thread_pool_metrics() [4/4]
void thread_module::thread_context::update_thread_pool_metrics (const std::string & pool_name, std::uint32_t pool_instance_id, const monitoring_interface::thread_pool_metrics & metrics) const inline
Update thread pool metrics with pool identifier.
Parameters
pool_name Name of the thread pool
pool_instance_id Instance ID for multiple pools
metrics Thread pool metrics to record
Definition at line 139 of file thread_context.h.
update_worker_metrics() [1/2]
void thread_module::thread_context::update_worker_metrics (std::size_t worker_id, const monitoring_interface::worker_metrics & metrics) const inline
Update worker metrics if monitoring is available.
Parameters
worker_id Worker identifier
metrics Worker metrics to record
Definition at line 152 of file thread_context.h.
update_worker_metrics() [2/2]
void thread_module::thread_context::update_worker_metrics (std::size_t worker_id, const monitoring_interface::worker_metrics & metrics) const inline
Update worker metrics if monitoring is available.
Parameters
worker_id Worker identifier
metrics Worker metrics to record
Definition at line 152 of file thread_context.h.
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/interfaces/thread_context.h
libraries/thread_system/sources/interfaces/thread_context.h