Messaging System: libraries/monitoring_system/tests/test_metric_exporters.cpp File Reference
test_metric_exporters.cpp File Reference
#include <gtest/gtest.h>
#include <kcenon/monitoring/exporters/metric_exporters.h>
#include <kcenon/monitoring/interfaces/monitorable_interface.h>
#include <kcenon/monitoring/interfaces/monitoring_interface.h>
#include <kcenon/monitoring/exporters/opentelemetry_adapter.h>
#include <thread>
#include <chrono>
Classes
class MetricExportersTest
Functions
TEST_F (MetricExportersTest, MetricExportConfigValidation)
TEST_F (MetricExportersTest, PrometheusMetricConversion)
TEST_F (MetricExportersTest, PrometheusTextFormat)
TEST_F (MetricExportersTest, PrometheusExporterBasicFunctionality)
TEST_F (MetricExportersTest, StatsDMetricConversion)
TEST_F (MetricExportersTest, StatsDTextFormat)
TEST_F (MetricExportersTest, StatsDExporterBasicFunctionality)
TEST_F (MetricExportersTest, OtlpMetricsExporterBasicFunctionality)
TEST_F (MetricExportersTest, MetricExporterFactory)
TEST_F (MetricExportersTest, SupportedFormatsQuery)
TEST_F (MetricExportersTest, HelperFunctions)
TEST_F (MetricExportersTest, EmptyMetricsHandling)
TEST_F (MetricExportersTest, LargeMetricBatch)
TEST_F (MetricExportersTest, MetricNameSanitization)
TEST_F (MetricExportersTest, MetricTypeInference)
Function Documentation
TEST_F() [1/15]
TEST_F (MetricExportersTest , EmptyMetricsHandling)
Definition at line 414 of file test_metric_exporters.cpp.
References monitoring_system::metric_export_config::endpoint, monitoring_system::prometheus_exporter::export_metrics(), monitoring_system::prometheus_exporter::export_snapshot(), monitoring_system::metric_export_config::format, and monitoring_system::prometheus_exporter::get_stats().
TEST_F() [2/15]
TEST_F (MetricExportersTest , HelperFunctions)
Definition at line 399 of file test_metric_exporters.cpp.
References monitoring_system::create_otlp_metrics_exporter(), monitoring_system::create_prometheus_exporter(), and monitoring_system::create_statsd_exporter().
TEST_F() [3/15]
TEST_F (MetricExportersTest , LargeMetricBatch)
Definition at line 435 of file test_metric_exporters.cpp.
References monitoring_system::monitoring_data::add_metric(), monitoring_system::monitoring_data::add_tag(), monitoring_system::metric_export_config::endpoint, monitoring_system::statsd_exporter::export_metrics(), monitoring_system::metric_export_config::format, monitoring_system::statsd_exporter::get_stats(), and monitoring_system::metric_export_config::max_batch_size.
TEST_F() [4/15]
TEST_F (MetricExportersTest , MetricExportConfigValidation)
Definition at line 71 of file test_metric_exporters.cpp.
References monitoring_system::metric_export_config::endpoint, monitoring_system::metric_export_config::format, monitoring_system::invalid_interval, monitoring_system::metric_export_config::max_batch_size, monitoring_system::metric_export_config::max_queue_size, monitoring_system::metric_export_config::port, monitoring_system::metric_export_config::push_interval, and monitoring_system::metric_export_config::validate().
TEST_F() [5/15]
TEST_F (MetricExportersTest , MetricExporterFactory)
Definition at line 340 of file test_metric_exporters.cpp.
References monitoring_system::metric_exporter_factory::create_exporter(), monitoring_system::metric_export_config::endpoint, monitoring_system::metric_export_config::format, and monitoring_system::metric_export_config::port.
TEST_F() [6/15]
TEST_F (MetricExportersTest , MetricNameSanitization)
Definition at line 459 of file test_metric_exporters.cpp.
References monitoring_system::monitoring_data::add_metric(), monitoring_system::prometheus_exporter::convert_monitoring_data(), monitoring_system::metric_export_config::endpoint, monitoring_system::metric_export_config::format, and monitoring_system::metric::name.
TEST_F() [7/15]
TEST_F (MetricExportersTest , MetricTypeInference)
Definition at line 488 of file test_metric_exporters.cpp.
References monitoring_system::monitoring_data::add_metric(), monitoring_system::statsd_exporter::convert_monitoring_data(), monitoring_system::metric_export_config::endpoint, monitoring_system::metric_export_config::format, and monitoring_system::metric_export_config::port.
TEST_F() [8/15]
TEST_F (MetricExportersTest , OtlpMetricsExporterBasicFunctionality)
Definition at line 311 of file test_metric_exporters.cpp.
References monitoring_system::metric_export_config::endpoint, monitoring_system::otlp_metrics_exporter::export_metrics(), monitoring_system::otlp_metrics_exporter::export_snapshot(), monitoring_system::otlp_metrics_exporter::flush(), monitoring_system::metric_export_config::format, monitoring_system::otlp_metrics_exporter::get_stats(), and monitoring_system::otlp_metrics_exporter::shutdown().
TEST_F() [9/15]
TEST_F (MetricExportersTest , PrometheusExporterBasicFunctionality)
Definition at line 181 of file test_metric_exporters.cpp.
References monitoring_system::metric_export_config::endpoint, monitoring_system::prometheus_exporter::export_metrics(), monitoring_system::prometheus_exporter::export_snapshot(), monitoring_system::prometheus_exporter::flush(), monitoring_system::metric_export_config::format, monitoring_system::prometheus_exporter::get_metrics_text(), monitoring_system::prometheus_exporter::get_stats(), and monitoring_system::prometheus_exporter::shutdown().
TEST_F() [10/15]
TEST_F (MetricExportersTest , PrometheusMetricConversion)
Definition at line 120 of file test_metric_exporters.cpp.
References monitoring_system::prometheus_exporter::convert_monitoring_data(), monitoring_system::prometheus_exporter::convert_snapshot(), monitoring_system::metric_export_config::endpoint, monitoring_system::metric_export_config::format, monitoring_system::metric_export_config::instance_id, and monitoring_system::metric_export_config::labels.
TEST_F() [11/15]
TEST_F (MetricExportersTest , PrometheusTextFormat)
Definition at line 160 of file test_metric_exporters.cpp.
References monitoring_system::metric::name, monitoring_system::prometheus_text, monitoring_system::metric::timestamp, monitoring_system::metric::type, and monitoring_system::metric::value.
TEST_F() [12/15]
TEST_F (MetricExportersTest , StatsDExporterBasicFunctionality)
Definition at line 280 of file test_metric_exporters.cpp.
References monitoring_system::metric_export_config::endpoint, monitoring_system::statsd_exporter::export_metrics(), monitoring_system::statsd_exporter::export_snapshot(), monitoring_system::statsd_exporter::flush(), monitoring_system::metric_export_config::format, monitoring_system::statsd_exporter::get_stats(), monitoring_system::metric_export_config::port, and monitoring_system::statsd_exporter::shutdown().
TEST_F() [13/15]
TEST_F (MetricExportersTest , StatsDMetricConversion)
Definition at line 217 of file test_metric_exporters.cpp.
References monitoring_system::statsd_exporter::convert_monitoring_data(), monitoring_system::statsd_exporter::convert_snapshot(), monitoring_system::metric_export_config::endpoint, monitoring_system::metric_export_config::format, monitoring_system::metric_export_config::instance_id, monitoring_system::metric_export_config::labels, and monitoring_system::metric_export_config::port.
TEST_F() [14/15]
TEST_F (MetricExportersTest , StatsDTextFormat)
Definition at line 250 of file test_metric_exporters.cpp.
References monitoring_system::statsd_metric_data::name, monitoring_system::statsd_metric_data::sample_rate, monitoring_system::statsd_metric_data::tags, monitoring_system::statsd_metric_data::to_statsd_format(), monitoring_system::statsd_metric_data::type, and monitoring_system::statsd_metric_data::value.
TEST_F() [15/15]
TEST_F (MetricExportersTest , SupportedFormatsQuery)
Definition at line 375 of file test_metric_exporters.cpp.
References monitoring_system::metric_exporter_factory::get_supported_formats().