Messaging System: logger_system::testing::mock_writer Class Reference
logger_system::testing::mock_writer Class Reference
Mock writer for unit testing.
#include <mock_writer.hpp>
Classes
struct write_record
Public Member Functions
mock_writer ()=default
~mock_writer () override=default
result_void write (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
result_void write (const log_entry &entry)
Write a log entry using the new interface.
result_void flush () override
Flush any buffered data.
result_void open ()
result_void close ()
bool is_thread_safe () const
std::string get_name () const override
Get the name of this writer.
void set_should_fail (bool fail, logger_error_code error=logger_error_code::file_write_failed)
void set_write_delay (std::chrono::milliseconds delay)
void reset ()
size_t get_write_count () const
size_t get_flush_count () const
std::vector< write_record > get_written_entries () const
bool has_entry_with_message (const std::string &message) const
write_record get_last_entry () const
Public Member Functions inherited from kcenon::logger::base_writer
virtual ~base_writer ()=default
virtual result_void write (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)=0
Write a log entry (legacy API for backward compatibility)
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
virtual bool is_healthy () const override
Check if the writer is healthy and operational.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
Additional Inherited Members
Protected Member Functions inherited from kcenon::logger::base_writer
std::string format_log_entry (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (logger_system::log_level level) const
Convert log level to string representation.
std::string level_to_color (logger_system::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
Mock writer for unit testing.
Provides controllable behavior for testing various scenarios including success, failure, delays, and tracking write operations.
Definition at line 32 of file mock_writer.hpp.
Constructor & Destructor Documentation
mock_writer()
logger_system::testing::mock_writer::mock_writer () default
~mock_writer()
logger_system::testing::mock_writer::~mock_writer () override default
Member Function Documentation
close()
result_void logger_system::testing::mock_writer::close () inline
Definition at line 136 of file mock_writer.hpp.
flush()
result_void logger_system::testing::mock_writer::flush () inline override virtual
Flush any buffered data.
Returns
result_void indicating success or failure
Implements kcenon::logger::base_writer.
Definition at line 122 of file mock_writer.hpp.
References kcenon::logger::make_logger_error().
get_flush_count()
size_t logger_system::testing::mock_writer::get_flush_count () const inline
Definition at line 174 of file mock_writer.hpp.
get_last_entry()
write_record logger_system::testing::mock_writer::get_last_entry () const inline
Definition at line 191 of file mock_writer.hpp.
get_name()
std::string logger_system::testing::mock_writer::get_name () const inline override virtual
Get the name of this writer.
Returns
Writer name for identification
Implements kcenon::logger::base_writer.
Definition at line 145 of file mock_writer.hpp.
get_write_count()
size_t logger_system::testing::mock_writer::get_write_count () const inline
Definition at line 170 of file mock_writer.hpp.
get_written_entries()
std::vector< write_record > logger_system::testing::mock_writer::get_written_entries () const inline
Definition at line 178 of file mock_writer.hpp.
has_entry_with_message()
bool logger_system::testing::mock_writer::has_entry_with_message (const std::string & message) const inline
Definition at line 183 of file mock_writer.hpp.
is_thread_safe()
bool logger_system::testing::mock_writer::is_thread_safe () const inline
Definition at line 141 of file mock_writer.hpp.
open()
result_void logger_system::testing::mock_writer::open () inline
Definition at line 131 of file mock_writer.hpp.
reset()
void logger_system::testing::mock_writer::reset () inline
Definition at line 159 of file mock_writer.hpp.
set_should_fail()
void logger_system::testing::mock_writer::set_should_fail (bool fail, logger_error_code error = logger_error_code::file_write_failed) inline
Definition at line 150 of file mock_writer.hpp.
References logger_system::error.
set_write_delay()
void logger_system::testing::mock_writer::set_write_delay (std::chrono::milliseconds delay) inline
Definition at line 155 of file mock_writer.hpp.
write() [1/2]
result_void logger_system::testing::mock_writer::write (const log_entry & entry) inline virtual
Write a log entry using the new interface.
Parameters
entry The log entry to write
Returns
result_void Success or error code
This method provides compatibility with the modern log_entry structure. The default implementation converts the entry to the legacy API format for backward compatibility. Derived classes can override this for optimized handling.
Note
This method extracts source location information if present in the entry.
Since
1.0.0
Reimplemented from kcenon::logger::base_writer.
Definition at line 95 of file mock_writer.hpp.
References kcenon::logger::log_entry::level, kcenon::logger::log_entry::location, kcenon::logger::make_logger_error(), kcenon::logger::log_entry::message, kcenon::logger::log_entry::timestamp, and kcenon::logger::small_string< SSO_SIZE >::to_string().
write() [2/2]
result_void logger_system::testing::mock_writer::write (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) inline override
Definition at line 64 of file mock_writer.hpp.
References kcenon::logger::make_logger_error().
The documentation for this class was generated from the following file:
libraries/logger_system/tests/unit/mocks/mock_writer.hpp