Messaging System: database::orm::entity_manager Class Reference
database::orm::entity_manager Class Reference
Manages entity metadata and provides factory methods.
#include <entity.h>
Public Member Functions
template<Entity EntityType>
void register_entity ()
template<Entity EntityType>
const entity_metadata & get_metadata ()
template<Entity EntityType>
query_builder< EntityType > query (std::shared_ptr< database_base > db)
bool create_tables (std::shared_ptr< database_base > db)
bool drop_tables (std::shared_ptr< database_base > db)
bool sync_schema (std::shared_ptr< database_base > db)
Static Public Member Functions
static entity_manager & instance ()
Detailed Description
Manages entity metadata and provides factory methods.
Definition at line 257 of file entity.h.
Member Function Documentation
create_tables()
bool database::orm::entity_manager::create_tables (std::shared_ptr< database_base > db)
Definition at line 189 of file entity.cpp.
Referenced by sync_schema().
drop_tables()
bool database::orm::entity_manager::drop_tables (std::shared_ptr< database_base > db)
Definition at line 219 of file entity.cpp.
Referenced by sync_schema().
get_metadata()
template<Entity EntityType> const entity_metadata & database::orm::entity_manager::get_metadata ()
Referenced by demonstrate_schema_management().
instance()
entity_manager & database::orm::entity_manager::instance () static
Definition at line 183 of file entity.cpp.
References instance().
Referenced by demonstrate_schema_management(), instance(), and TEST_F().
query()
template<Entity EntityType> query_builder< EntityType > database::orm::entity_manager::query (std::shared_ptr< database_base > db)
register_entity()
template<Entity EntityType> void database::orm::entity_manager::register_entity ()
Referenced by demonstrate_schema_management().
sync_schema()
bool database::orm::entity_manager::sync_schema (std::shared_ptr< database_base > db)
Definition at line 241 of file entity.cpp.
References create_tables(), and drop_tables().
The documentation for this class was generated from the following files:
libraries/database_system/database/orm/entity.h
libraries/database_system/database/orm/entity.cpp