Messaging System: monitoring_system::otlp_metrics_exporter Class Reference
monitoring_system::otlp_metrics_exporter Class Reference
OpenTelemetry Protocol (OTLP) metrics exporter implementation.
#include <metric_exporters.h>
Public Member Functions
otlp_metrics_exporter (const metric_export_config &config, const otel_resource &resource)
result_void export_metrics (const std::vector< monitoring_data > &metrics) override
Export a batch of metrics.
result_void export_snapshot (const metrics_snapshot &snapshot) override
Export a single metrics snapshot.
result_void flush () override
Flush any pending metrics.
result_void shutdown () override
Shutdown the exporter.
std::unordered_map< std::string, std::size_t > get_stats () const override
Get exporter statistics.
Public Member Functions inherited from monitoring_system::metric_exporter_interface
virtual ~metric_exporter_interface ()=default
virtual result_void start ()
Start the exporter (for pull-based systems)
virtual result_void stop ()
Stop the exporter.
Detailed Description
OpenTelemetry Protocol (OTLP) metrics exporter implementation.
Definition at line 701 of file metric_exporters.h.
Constructor & Destructor Documentation
otlp_metrics_exporter()
monitoring_system::otlp_metrics_exporter::otlp_metrics_exporter (const metric_export_config & config, const otel_resource & resource) inline explicit
Definition at line 709 of file metric_exporters.h.
Member Function Documentation
export_metrics()
result_void monitoring_system::otlp_metrics_exporter::export_metrics (const std::vector< monitoring_data > & metrics) inline override virtual
Export a batch of metrics.
Implements monitoring_system::metric_exporter_interface.
Definition at line 712 of file metric_exporters.h.
References monitoring_system::operation_failed, and monitoring_system::processing_failed.
Referenced by TEST_F().
export_snapshot()
result_void monitoring_system::otlp_metrics_exporter::export_snapshot (const metrics_snapshot & snapshot) inline override virtual
Export a single metrics snapshot.
Implements monitoring_system::metric_exporter_interface.
Definition at line 743 of file metric_exporters.h.
References monitoring_system::operation_failed, and monitoring_system::processing_failed.
Referenced by TEST_F().
flush()
result_void monitoring_system::otlp_metrics_exporter::flush () inline override virtual
Flush any pending metrics.
Implements monitoring_system::metric_exporter_interface.
Definition at line 772 of file metric_exporters.h.
Referenced by shutdown(), and TEST_F().
get_stats()
std::unordered_map< std::string, std::size_t > monitoring_system::otlp_metrics_exporter::get_stats () const inline override virtual
Get exporter statistics.
Implements monitoring_system::metric_exporter_interface.
Definition at line 781 of file metric_exporters.h.
Referenced by TEST_F().
shutdown()
result_void monitoring_system::otlp_metrics_exporter::shutdown () inline override virtual
Shutdown the exporter.
Implements monitoring_system::metric_exporter_interface.
Definition at line 777 of file metric_exporters.h.
References flush().
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/exporters/metric_exporters.h