Messaging System: monitoring_system::metrics_snapshot Struct Reference
monitoring_system::metrics_snapshot Struct Reference
Complete snapshot of metrics at a point in time.
#include <monitoring_interface.h>
Public Member Functions
metrics_snapshot ()
void add_metric (const std::string &name, double value)
Add a metric to the snapshot.
std::optional< double > get_metric (const std::string &name) const
Get a specific metric value.
Public Attributes
std::vector< metric_value > metrics
std::chrono::system_clock::time_point capture_time
std::string source_id
Detailed Description
Complete snapshot of metrics at a point in time.
Definition at line 59 of file monitoring_interface.h.
Constructor & Destructor Documentation
metrics_snapshot()
monitoring_system::metrics_snapshot::metrics_snapshot () inline
Definition at line 64 of file monitoring_interface.h.
Member Function Documentation
add_metric()
void monitoring_system::metrics_snapshot::add_metric (const std::string & name, double value) inline
Add a metric to the snapshot.
Parameters
name Metric name
value Metric value
Definition at line 72 of file monitoring_interface.h.
References metrics.
Referenced by monitoring_system::performance_monitor::collect(), mock_collector::collect(), MetricExportersTest::create_test_snapshot(), StorageBackendsTest::create_test_snapshots(), main(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
get_metric()
std::optional< double > monitoring_system::metrics_snapshot::get_metric (const std::string & name) const inline
Get a specific metric value.
Parameters
name Metric name
Returns
Optional metric value
Definition at line 81 of file monitoring_interface.h.
References metrics.
Referenced by main(), and TEST_F().
Member Data Documentation
capture_time
std::chrono::system_clock::time_point monitoring_system::metrics_snapshot::capture_time
Definition at line 61 of file monitoring_interface.h.
Referenced by monitoring_system::performance_monitor::collect(), mock_collector::collect(), MetricExportersTest::create_test_snapshot(), and StorageBackendsTest::create_test_snapshots().
metrics
std::vector<metric_value> monitoring_system::metrics_snapshot::metrics
Definition at line 60 of file monitoring_interface.h.
Referenced by add_metric(), monitoring_system::opentelemetry_metrics_adapter::convert_metrics(), monitoring_system::prometheus_exporter::convert_snapshot(), monitoring_system::statsd_exporter::convert_snapshot(), MetricExportersTest::create_test_snapshot(), get_metric(), main(), and TEST_F().
source_id
std::string monitoring_system::metrics_snapshot::source_id
Definition at line 62 of file monitoring_interface.h.
Referenced by monitoring_system::performance_monitor::collect(), mock_collector::collect(), monitoring_system::prometheus_exporter::convert_snapshot(), monitoring_system::statsd_exporter::convert_snapshot(), MetricExportersTest::create_test_snapshot(), StorageBackendsTest::create_test_snapshots(), TEST_F(), and TEST_F().
The documentation for this struct was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/interfaces/monitoring_interface.h