Messaging System: thread_module::adaptive_job_queue Class Reference
thread_module::adaptive_job_queue Class Reference
Adaptive queue that switches between mutex-based and lock-free implementations.
#include <adaptive_job_queue.h>
Classes
struct atomic_performance_metrics
Internal atomic performance metrics.
struct performance_metrics
Performance metrics structure (non-atomic for returning)
Public Types
enum class queue_strategy {
AUTO_DETECT , FORCE_LEGACY , FORCE_LOCKFREE , ADAPTIVE ,
AUTO_DETECT , FORCE_LEGACY , FORCE_LOCKFREE , ADAPTIVE ,
AUTO_DETECT , FORCE_LEGACY , FORCE_LOCKFREE , ADAPTIVE
}
Queue implementation strategy.
enum class queue_strategy {
AUTO_DETECT , FORCE_LEGACY , FORCE_LOCKFREE , ADAPTIVE ,
AUTO_DETECT , FORCE_LEGACY , FORCE_LOCKFREE , ADAPTIVE ,
AUTO_DETECT , FORCE_LEGACY , FORCE_LOCKFREE , ADAPTIVE
}
Queue implementation strategy.
enum class queue_strategy {
AUTO_DETECT , FORCE_LEGACY , FORCE_LOCKFREE , ADAPTIVE ,
AUTO_DETECT , FORCE_LEGACY , FORCE_LOCKFREE , ADAPTIVE ,
AUTO_DETECT , FORCE_LEGACY , FORCE_LOCKFREE , ADAPTIVE
}
Queue implementation strategy.
Public Member Functions
adaptive_job_queue (queue_strategy initial_strategy=queue_strategy::AUTO_DETECT)
Constructor.
virtual ~adaptive_job_queue ()
Destructor.
auto enqueue (std::unique_ptr< job > &&value) -> result_void override
Enqueues a new job into the queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void override
Enqueues a batch of jobs into the queue.
auto dequeue () -> result< std::unique_ptr< job > > override
Dequeues a job from the queue in FIFO order.
auto dequeue_batch () -> std::deque< std::unique_ptr< job > > override
Dequeues all remaining jobs from the queue without processing them.
auto clear () -> void override
Removes all jobs currently in the queue without processing them.
auto empty () const -> bool
auto size () const -> std::size_t
auto to_string () const -> std::string override
Returns a string representation of this job_queue.
auto evaluate_and_switch () -> void
Force evaluation and potential switch of queue implementation.
auto get_current_type () const -> std::string
Get current queue type.
auto get_metrics () const -> performance_metrics
Get performance metrics.
adaptive_job_queue (queue_strategy initial_strategy=queue_strategy::AUTO_DETECT)
Constructor.
virtual ~adaptive_job_queue ()
Destructor.
auto enqueue (std::unique_ptr< job > &&value) -> result_void override
Enqueues a new job into the queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void override
Enqueues a batch of jobs into the queue.
auto dequeue () -> result< std::unique_ptr< job > > override
Dequeues a job from the queue in FIFO order.
auto dequeue_batch () -> std::deque< std::unique_ptr< job > > override
Dequeues all remaining jobs from the queue without processing them.
auto clear () -> void override
Removes all jobs currently in the queue without processing them.
auto empty () const -> bool
auto size () const -> std::size_t
auto to_string () const -> std::string override
Returns a string representation of this job_queue.
auto evaluate_and_switch () -> void
Force evaluation and potential switch of queue implementation.
auto get_current_type () const -> std::string
Get current queue type.
auto get_metrics () const -> performance_metrics
Get performance metrics.
adaptive_job_queue (queue_strategy initial_strategy=queue_strategy::AUTO_DETECT)
Constructor.
virtual ~adaptive_job_queue ()
Destructor.
auto enqueue (std::unique_ptr< job > &&value) -> result_void override
Enqueues a new job into the queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void override
Enqueues a batch of jobs into the queue.
auto dequeue () -> result< std::unique_ptr< job > > override
Dequeues a job from the queue in FIFO order.
auto dequeue_batch () -> std::deque< std::unique_ptr< job > > override
Dequeues all remaining jobs from the queue without processing them.
auto clear () -> void override
Removes all jobs currently in the queue without processing them.
auto empty () const -> bool
auto size () const -> std::size_t
auto to_string () const -> std::string override
Returns a string representation of this job_queue.
auto evaluate_and_switch () -> void
Force evaluation and potential switch of queue implementation.
auto get_current_type () const -> std::string
Get current queue type.
auto get_metrics () const -> performance_metrics
Get performance metrics.
Public Member Functions inherited from thread_module::job_queue
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
Additional Inherited Members
Protected Attributes inherited from thread_module::job_queue
std::atomic_bool notify_
If true, threads waiting for new jobs are notified when a new job is enqueued.
std::atomic_bool stop_
Indicates whether the queue has been signaled to stop.
std::mutex mutex_
Mutex to protect access to the underlying queue_ container and related state.
std::condition_variable condition_
Condition variable used to signal worker threads.
Detailed Description
Adaptive queue that switches between mutex-based and lock-free implementations.
This queue monitors performance metrics and automatically switches between a traditional mutex-based queue and a lock-free MPMC queue based on contention levels and performance characteristics.
Definition at line 51 of file adaptive_job_queue.h.
Member Enumeration Documentation
queue_strategy [1/3]
enum class thread_module::adaptive_job_queue::queue_strategy strong
Queue implementation strategy.
Enumerator
AUTO_DETECT
Automatically detect best strategy.
FORCE_LEGACY
Always use mutex-based queue.
FORCE_LOCKFREE
Always use lock-free queue.
ADAPTIVE
Switch based on runtime metrics.
AUTO_DETECT
Automatically detect best strategy.
FORCE_LEGACY
Always use mutex-based queue.
FORCE_LOCKFREE
Always use lock-free queue.
ADAPTIVE
Switch based on runtime metrics.
AUTO_DETECT
Automatically detect best strategy.
FORCE_LEGACY
Always use mutex-based queue.
FORCE_LOCKFREE
Always use lock-free queue.
ADAPTIVE
Switch based on runtime metrics.
Definition at line 57 of file adaptive_job_queue.h.
queue_strategy [2/3]
enum class thread_module::adaptive_job_queue::queue_strategy strong
Queue implementation strategy.
Enumerator
AUTO_DETECT
Automatically detect best strategy.
FORCE_LEGACY
Always use mutex-based queue.
FORCE_LOCKFREE
Always use lock-free queue.
ADAPTIVE
Switch based on runtime metrics.
AUTO_DETECT
Automatically detect best strategy.
FORCE_LEGACY
Always use mutex-based queue.
FORCE_LOCKFREE
Always use lock-free queue.
ADAPTIVE
Switch based on runtime metrics.
AUTO_DETECT
Automatically detect best strategy.
FORCE_LEGACY
Always use mutex-based queue.
FORCE_LOCKFREE
Always use lock-free queue.
ADAPTIVE
Switch based on runtime metrics.
Definition at line 57 of file adaptive_job_queue.h.
queue_strategy [3/3]
enum class thread_module::adaptive_job_queue::queue_strategy strong
Queue implementation strategy.
Enumerator
AUTO_DETECT
Automatically detect best strategy.
FORCE_LEGACY
Always use mutex-based queue.
FORCE_LOCKFREE
Always use lock-free queue.
ADAPTIVE
Switch based on runtime metrics.
AUTO_DETECT
Automatically detect best strategy.
FORCE_LEGACY
Always use mutex-based queue.
FORCE_LOCKFREE
Always use lock-free queue.
ADAPTIVE
Switch based on runtime metrics.
AUTO_DETECT
Automatically detect best strategy.
FORCE_LEGACY
Always use mutex-based queue.
FORCE_LOCKFREE
Always use lock-free queue.
ADAPTIVE
Switch based on runtime metrics.
Definition at line 57 of file adaptive_job_queue.h.
Constructor & Destructor Documentation
adaptive_job_queue() [1/3]
thread_module::adaptive_job_queue::adaptive_job_queue (queue_strategy initial_strategy = queue_strategy::AUTO_DETECT) explicit
Constructor.
Constructs an adaptive job queue with specified initial strategy.
Parameters
initial_strategy Initial queue strategy
Implementation details:
Creates both mutex-based and lock-free queue implementations
Initializes performance monitoring system
Sets up strategy switching logic if ADAPTIVE mode is selected
Resets performance metrics to baseline
Strategy Initialization:
MUTEX_ONLY: Uses only the legacy mutex-based queue
LOCKFREE_ONLY: Uses only the lock-free MPMC queue
ADAPTIVE: Intelligently switches between both based on performance
Performance Monitoring:
Started automatically for ADAPTIVE mode
Collects latency and contention metrics
Triggers strategy switches based on performance thresholds
Memory Usage:
Both queue implementations are always created (enables fast switching)
Memory overhead: ~2KB for dual queue setup
Metrics collection: ~1KB for performance data
Parameters
initial_strategy Starting queue strategy (MUTEX_ONLY, LOCKFREE_ONLY, or ADAPTIVE)
Definition at line 93 of file adaptive_job_queue.cpp.
References ADAPTIVE, and thread_module::adaptive_job_queue::atomic_performance_metrics::reset().
~adaptive_job_queue() [1/3]
thread_module::adaptive_job_queue::~adaptive_job_queue () virtual
Destructor.
Definition at line 111 of file adaptive_job_queue.cpp.
adaptive_job_queue() [2/3]
thread_module::adaptive_job_queue::adaptive_job_queue (queue_strategy initial_strategy = queue_strategy::AUTO_DETECT) explicit
Constructor.
Parameters
initial_strategy Initial queue strategy
~adaptive_job_queue() [2/3]
virtual thread_module::adaptive_job_queue::~adaptive_job_queue () virtual
Destructor.
adaptive_job_queue() [3/3]
thread_module::adaptive_job_queue::adaptive_job_queue (queue_strategy initial_strategy = queue_strategy::AUTO_DETECT) explicit
Constructor.
Parameters
initial_strategy Initial queue strategy
~adaptive_job_queue() [3/3]
virtual thread_module::adaptive_job_queue::~adaptive_job_queue () virtual
Destructor.
Member Function Documentation
clear() [1/3]
auto thread_module::adaptive_job_queue::clear (void) -> void override virtual
Removes all jobs currently in the queue without processing them.
Removes all jobs from the queue without returning them.
This operation is thread-safe and can be used to discard pending jobs, typically during shutdown or error recovery. It does not affect the stop_ or notify_ flags.
Implementation details:
Discards all jobs immediately (destructors called automatically)
Uses deque::clear() for efficient bulk removal
Notifies all waiting threads since queue is now empty
More efficient than dequeue_batch() when jobs don't need to be processed
Use Cases:
Emergency shutdown (discard pending work)
Queue reset/reinitialization
Error recovery scenarios
Note
Jobs are destroyed immediately, so any cleanup logic in job destructors will run
Reimplemented from thread_module::job_queue.
Definition at line 197 of file adaptive_job_queue.cpp.
clear() [2/3]
auto thread_module::adaptive_job_queue::clear (void) -> void override virtual
Removes all jobs currently in the queue without processing them.
Removes all jobs from the queue without returning them.
This operation is thread-safe and can be used to discard pending jobs, typically during shutdown or error recovery. It does not affect the stop_ or notify_ flags.
Implementation details:
Discards all jobs immediately (destructors called automatically)
Uses deque::clear() for efficient bulk removal
Notifies all waiting threads since queue is now empty
More efficient than dequeue_batch() when jobs don't need to be processed
Use Cases:
Emergency shutdown (discard pending work)
Queue reset/reinitialization
Error recovery scenarios
Note
Jobs are destroyed immediately, so any cleanup logic in job destructors will run
Reimplemented from thread_module::job_queue.
clear() [3/3]
auto thread_module::adaptive_job_queue::clear (void) -> void override virtual
Removes all jobs currently in the queue without processing them.
Removes all jobs from the queue without returning them.
This operation is thread-safe and can be used to discard pending jobs, typically during shutdown or error recovery. It does not affect the stop_ or notify_ flags.
Implementation details:
Discards all jobs immediately (destructors called automatically)
Uses deque::clear() for efficient bulk removal
Notifies all waiting threads since queue is now empty
More efficient than dequeue_batch() when jobs don't need to be processed
Use Cases:
Emergency shutdown (discard pending work)
Queue reset/reinitialization
Error recovery scenarios
Note
Jobs are destroyed immediately, so any cleanup logic in job destructors will run
Reimplemented from thread_module::job_queue.
dequeue() [1/3]
auto thread_module::adaptive_job_queue::dequeue (void) -> result<std::unique_ptr<job>> override virtual
Dequeues a job from the queue in FIFO order.
Removes and returns the first job from the queue (blocking operation).
Returns
A result<std::unique_ptr<job>> containing either a valid job or an error object.
If the queue is empty, the caller may block depending on the internal concurrency model (unless stop_ is set, in which case it may return immediately).
Implementation details:
Uses unique_lock (required by condition_variable)
Blocks until a job is available OR queue is stopped
Returns error if queue is empty after waking up (indicates stop condition)
Efficiently moves job out of queue (zero-copy transfer)
Automatically unlocks mutex when function exits
Blocking Behavior:
Waits indefinitely until job available or stop requested
Uses condition variable for efficient waiting (no busy polling)
Multiple threads can wait concurrently (fair wake-up via notify_one)
Stop Coordination:
Wakes up when stop_.load() becomes true
Returns error instead of blocking indefinitely during shutdown
Thread Safety:
Safe for concurrent access with other dequeue/enqueue operations
Uses proper synchronization primitives
Returns
Unique pointer to job on success, error if queue empty/stopped
Reimplemented from thread_module::job_queue.
Definition at line 157 of file adaptive_job_queue.cpp.
References thread_module::queue_empty.
Referenced by adaptive_behavior_example(), strategy_comparison_example(), TEST_F(), TEST_F(), and web_server_simulation().
dequeue() [2/3]
auto thread_module::adaptive_job_queue::dequeue (void) -> result<std::unique_ptr<job>> override virtual
Dequeues a job from the queue in FIFO order.
Removes and returns the first job from the queue (blocking operation).
Returns
A result<std::unique_ptr<job>> containing either a valid job or an error object.
If the queue is empty, the caller may block depending on the internal concurrency model (unless stop_ is set, in which case it may return immediately).
Implementation details:
Uses unique_lock (required by condition_variable)
Blocks until a job is available OR queue is stopped
Returns error if queue is empty after waking up (indicates stop condition)
Efficiently moves job out of queue (zero-copy transfer)
Automatically unlocks mutex when function exits
Blocking Behavior:
Waits indefinitely until job available or stop requested
Uses condition variable for efficient waiting (no busy polling)
Multiple threads can wait concurrently (fair wake-up via notify_one)
Stop Coordination:
Wakes up when stop_.load() becomes true
Returns error instead of blocking indefinitely during shutdown
Thread Safety:
Safe for concurrent access with other dequeue/enqueue operations
Uses proper synchronization primitives
Returns
Unique pointer to job on success, error if queue empty/stopped
Reimplemented from thread_module::job_queue.
dequeue() [3/3]
auto thread_module::adaptive_job_queue::dequeue (void) -> result<std::unique_ptr<job>> override virtual
Dequeues a job from the queue in FIFO order.
Removes and returns the first job from the queue (blocking operation).
Returns
A result<std::unique_ptr<job>> containing either a valid job or an error object.
If the queue is empty, the caller may block depending on the internal concurrency model (unless stop_ is set, in which case it may return immediately).
Implementation details:
Uses unique_lock (required by condition_variable)
Blocks until a job is available OR queue is stopped
Returns error if queue is empty after waking up (indicates stop condition)
Efficiently moves job out of queue (zero-copy transfer)
Automatically unlocks mutex when function exits
Blocking Behavior:
Waits indefinitely until job available or stop requested
Uses condition variable for efficient waiting (no busy polling)
Multiple threads can wait concurrently (fair wake-up via notify_one)
Stop Coordination:
Wakes up when stop_.load() becomes true
Returns error instead of blocking indefinitely during shutdown
Thread Safety:
Safe for concurrent access with other dequeue/enqueue operations
Uses proper synchronization primitives
Returns
Unique pointer to job on success, error if queue empty/stopped
Reimplemented from thread_module::job_queue.
dequeue_batch() [1/3]
auto thread_module::adaptive_job_queue::dequeue_batch (void) -> std::deque<std::unique_ptr<job>> override virtual
Dequeues all remaining jobs from the queue without processing them.
Removes and returns ALL jobs from the queue (non-blocking operation).
Returns
A std::deque of unique_ptr<job> containing all jobs that were in the queue at the time of the call.
Similar to clear(), but returns the dequeued jobs to the caller for potential inspection or manual processing.
Implementation details:
Non-blocking: returns immediately regardless of queue state
Uses efficient swap operation to transfer entire queue contents
Notifies all waiting threads since queue is now empty
Returns empty deque if queue was already empty
Leaves queue in empty state after operation
Performance Characteristics:
O(1) complexity due to swap operation (very efficient)
No copying of job objects (moves ownership)
Single lock acquisition for entire batch
Use Cases:
Shutdown scenarios (drain all pending work)
Batch processing of accumulated jobs
Queue migration between workers
Thread Safety:
Uses scoped_lock for automatic cleanup
notify_all() ensures no threads remain blocked on empty queue
Returns
Deque containing all jobs that were in the queue
Reimplemented from thread_module::job_queue.
Definition at line 185 of file adaptive_job_queue.cpp.
Referenced by different_strategies_example().
dequeue_batch() [2/3]
auto thread_module::adaptive_job_queue::dequeue_batch (void) -> std::deque<std::unique_ptr<job>> override virtual
Dequeues all remaining jobs from the queue without processing them.
Removes and returns ALL jobs from the queue (non-blocking operation).
Returns
A std::deque of unique_ptr<job> containing all jobs that were in the queue at the time of the call.
Similar to clear(), but returns the dequeued jobs to the caller for potential inspection or manual processing.
Implementation details:
Non-blocking: returns immediately regardless of queue state
Uses efficient swap operation to transfer entire queue contents
Notifies all waiting threads since queue is now empty
Returns empty deque if queue was already empty
Leaves queue in empty state after operation
Performance Characteristics:
O(1) complexity due to swap operation (very efficient)
No copying of job objects (moves ownership)
Single lock acquisition for entire batch
Use Cases:
Shutdown scenarios (drain all pending work)
Batch processing of accumulated jobs
Queue migration between workers
Thread Safety:
Uses scoped_lock for automatic cleanup
notify_all() ensures no threads remain blocked on empty queue
Returns
Deque containing all jobs that were in the queue
Reimplemented from thread_module::job_queue.
dequeue_batch() [3/3]
auto thread_module::adaptive_job_queue::dequeue_batch (void) -> std::deque<std::unique_ptr<job>> override virtual
Dequeues all remaining jobs from the queue without processing them.
Removes and returns ALL jobs from the queue (non-blocking operation).
Returns
A std::deque of unique_ptr<job> containing all jobs that were in the queue at the time of the call.
Similar to clear(), but returns the dequeued jobs to the caller for potential inspection or manual processing.
Implementation details:
Non-blocking: returns immediately regardless of queue state
Uses efficient swap operation to transfer entire queue contents
Notifies all waiting threads since queue is now empty
Returns empty deque if queue was already empty
Leaves queue in empty state after operation
Performance Characteristics:
O(1) complexity due to swap operation (very efficient)
No copying of job objects (moves ownership)
Single lock acquisition for entire batch
Use Cases:
Shutdown scenarios (drain all pending work)
Batch processing of accumulated jobs
Queue migration between workers
Thread Safety:
Uses scoped_lock for automatic cleanup
notify_all() ensures no threads remain blocked on empty queue
Returns
Deque containing all jobs that were in the queue
Reimplemented from thread_module::job_queue.
empty() [1/3]
auto thread_module::adaptive_job_queue::empty (void) const -> bool
Definition at line 202 of file adaptive_job_queue.cpp.
Referenced by TEST_F().
empty() [2/3]
auto thread_module::adaptive_job_queue::empty () const -> bool
empty() [3/3]
auto thread_module::adaptive_job_queue::empty () const -> bool
enqueue() [1/3]
auto thread_module::adaptive_job_queue::enqueue (std::unique_ptr< job > && value) -> result_void override virtual
Enqueues a new job into the queue.
Adds a single job to the back of the queue.
Parameters
value A unique pointer to the job being added.
Returns
A result_void indicating success or an error message.
This method is thread-safe. If notify_ is set to true, a waiting thread (if any) will be notified upon successful enqueue.
Implementation details:
First checks if queue is stopped to fail fast
Validates that the job pointer is not null
Uses scoped_lock for automatic mutex management
Moves the job into the queue (zero-copy transfer)
Optionally notifies one waiting thread if notifications enabled
Thread Safety:
Uses mutex to protect queue modification
Safe to call concurrently from multiple threads
notify_one() wakes exactly one waiting thread (fair scheduling)
Error Conditions:
Returns error if queue is stopped
Returns error if job is null
Parameters
value Unique pointer to job (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented from thread_module::job_queue.
Definition at line 116 of file adaptive_job_queue.cpp.
Referenced by adaptive_behavior_example(), BM_AdaptiveQueue_SPSC(), performance_monitoring_example(), strategy_comparison_example(), TEST_F(), TEST_F(), and web_server_simulation().
enqueue() [2/3]
auto thread_module::adaptive_job_queue::enqueue (std::unique_ptr< job > && value) -> result_void override virtual
Enqueues a new job into the queue.
Adds a single job to the back of the queue.
Parameters
value A unique pointer to the job being added.
Returns
A result_void indicating success or an error message.
This method is thread-safe. If notify_ is set to true, a waiting thread (if any) will be notified upon successful enqueue.
Implementation details:
First checks if queue is stopped to fail fast
Validates that the job pointer is not null
Uses scoped_lock for automatic mutex management
Moves the job into the queue (zero-copy transfer)
Optionally notifies one waiting thread if notifications enabled
Thread Safety:
Uses mutex to protect queue modification
Safe to call concurrently from multiple threads
notify_one() wakes exactly one waiting thread (fair scheduling)
Error Conditions:
Returns error if queue is stopped
Returns error if job is null
Parameters
value Unique pointer to job (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented from thread_module::job_queue.
enqueue() [3/3]
auto thread_module::adaptive_job_queue::enqueue (std::unique_ptr< job > && value) -> result_void override virtual
Enqueues a new job into the queue.
Adds a single job to the back of the queue.
Parameters
value A unique pointer to the job being added.
Returns
A result_void indicating success or an error message.
This method is thread-safe. If notify_ is set to true, a waiting thread (if any) will be notified upon successful enqueue.
Implementation details:
First checks if queue is stopped to fail fast
Validates that the job pointer is not null
Uses scoped_lock for automatic mutex management
Moves the job into the queue (zero-copy transfer)
Optionally notifies one waiting thread if notifications enabled
Thread Safety:
Uses mutex to protect queue modification
Safe to call concurrently from multiple threads
notify_one() wakes exactly one waiting thread (fair scheduling)
Error Conditions:
Returns error if queue is stopped
Returns error if job is null
Parameters
value Unique pointer to job (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented from thread_module::job_queue.
enqueue_batch() [1/3]
auto thread_module::adaptive_job_queue::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void override virtual
Enqueues a batch of jobs into the queue.
Adds multiple jobs to the queue in a single operation.
Parameters
jobs A vector of unique pointers to the jobs being added.
Returns
A result_void indicating success or an error message.
Implementation details:
Validates queue state and input before any modifications
Pre-validates all jobs to ensure atomicity (all or nothing)
Uses single lock acquisition for entire batch (better performance)
Moves all jobs efficiently without copying
Only notifies once after all jobs are added (avoids notification spam)
Performance Benefits:
Single mutex acquisition vs multiple for individual enqueues
Single notification vs notification per job
Reduced contention for high-throughput scenarios
Atomicity:
Either all jobs are added or none are (on validation failure)
No partial batches in case of null job detection
Parameters
jobs Vector of unique pointers to jobs (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented from thread_module::job_queue.
Definition at line 145 of file adaptive_job_queue.cpp.
Referenced by different_strategies_example().
enqueue_batch() [2/3]
auto thread_module::adaptive_job_queue::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void override virtual
Enqueues a batch of jobs into the queue.
Adds multiple jobs to the queue in a single operation.
Parameters
jobs A vector of unique pointers to the jobs being added.
Returns
A result_void indicating success or an error message.
Implementation details:
Validates queue state and input before any modifications
Pre-validates all jobs to ensure atomicity (all or nothing)
Uses single lock acquisition for entire batch (better performance)
Moves all jobs efficiently without copying
Only notifies once after all jobs are added (avoids notification spam)
Performance Benefits:
Single mutex acquisition vs multiple for individual enqueues
Single notification vs notification per job
Reduced contention for high-throughput scenarios
Atomicity:
Either all jobs are added or none are (on validation failure)
No partial batches in case of null job detection
Parameters
jobs Vector of unique pointers to jobs (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented from thread_module::job_queue.
enqueue_batch() [3/3]
auto thread_module::adaptive_job_queue::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void override virtual
Enqueues a batch of jobs into the queue.
Adds multiple jobs to the queue in a single operation.
Parameters
jobs A vector of unique pointers to the jobs being added.
Returns
A result_void indicating success or an error message.
Implementation details:
Validates queue state and input before any modifications
Pre-validates all jobs to ensure atomicity (all or nothing)
Uses single lock acquisition for entire batch (better performance)
Moves all jobs efficiently without copying
Only notifies once after all jobs are added (avoids notification spam)
Performance Benefits:
Single mutex acquisition vs multiple for individual enqueues
Single notification vs notification per job
Reduced contention for high-throughput scenarios
Atomicity:
Either all jobs are added or none are (on validation failure)
No partial batches in case of null job detection
Parameters
jobs Vector of unique pointers to jobs (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented from thread_module::job_queue.
evaluate_and_switch() [1/3]
auto thread_module::adaptive_job_queue::evaluate_and_switch () -> void
Force evaluation and potential switch of queue implementation.
Definition at line 225 of file adaptive_job_queue.cpp.
evaluate_and_switch() [2/3]
auto thread_module::adaptive_job_queue::evaluate_and_switch () -> void
Force evaluation and potential switch of queue implementation.
evaluate_and_switch() [3/3]
auto thread_module::adaptive_job_queue::evaluate_and_switch () -> void
Force evaluation and potential switch of queue implementation.
get_current_type() [1/3]
auto thread_module::adaptive_job_queue::get_current_type () const -> std::string
Get current queue type.
Returns
Current queue implementation type
Definition at line 254 of file adaptive_job_queue.cpp.
Referenced by adaptive_behavior_example(), different_strategies_example(), TEST_F(), and to_string().
get_current_type() [2/3]
auto thread_module::adaptive_job_queue::get_current_type () const -> std::string
Get current queue type.
Returns
Current queue implementation type
get_current_type() [3/3]
auto thread_module::adaptive_job_queue::get_current_type () const -> std::string
Get current queue type.
Returns
Current queue implementation type
get_metrics() [1/3]
auto thread_module::adaptive_job_queue::get_metrics () const -> performance_metrics
Get performance metrics.
Returns
Current performance metrics
Definition at line 268 of file adaptive_job_queue.cpp.
References thread_module::adaptive_job_queue::performance_metrics::contention_count, thread_module::adaptive_job_queue::atomic_performance_metrics::contention_count, thread_module::adaptive_job_queue::performance_metrics::last_evaluation, thread_module::adaptive_job_queue::atomic_performance_metrics::last_evaluation, thread_module::adaptive_job_queue::performance_metrics::operation_count, thread_module::adaptive_job_queue::atomic_performance_metrics::operation_count, thread_module::adaptive_job_queue::performance_metrics::switch_count, thread_module::adaptive_job_queue::atomic_performance_metrics::switch_count, thread_module::adaptive_job_queue::performance_metrics::total_latency_ns, and thread_module::adaptive_job_queue::atomic_performance_metrics::total_latency_ns.
Referenced by to_string().
get_metrics() [2/3]
auto thread_module::adaptive_job_queue::get_metrics () const -> performance_metrics
Get performance metrics.
Returns
Current performance metrics
get_metrics() [3/3]
auto thread_module::adaptive_job_queue::get_metrics () const -> performance_metrics
Get performance metrics.
Returns
Current performance metrics
size() [1/3]
auto thread_module::adaptive_job_queue::size (void) const -> std::size_t
Definition at line 207 of file adaptive_job_queue.cpp.
Referenced by to_string().
size() [2/3]
auto thread_module::adaptive_job_queue::size () const -> std::size_t
size() [3/3]
auto thread_module::adaptive_job_queue::size () const -> std::size_t
to_string() [1/3]
auto thread_module::adaptive_job_queue::to_string (void) const -> std::string override virtual
Returns a string representation of this job_queue.
Provides a string representation of the queue's current state.
Returns
A std::string describing the state of the queue (e.g., size, flags).
Primarily used for logging and debugging. Derived classes may override this to include additional diagnostic information.
Implementation details:
Uses size() method to get current job count
Formats output using the formatter utility
Useful for logging and debugging purposes
Returns
Formatted string showing current job count
Reimplemented from thread_module::job_queue.
Definition at line 212 of file adaptive_job_queue.cpp.
References utility_module::formatter::format(), get_current_type(), get_metrics(), and size().
to_string() [2/3]
auto thread_module::adaptive_job_queue::to_string (void) const -> std::string override virtual
Returns a string representation of this job_queue.
Provides a string representation of the queue's current state.
Returns
A std::string describing the state of the queue (e.g., size, flags).
Primarily used for logging and debugging. Derived classes may override this to include additional diagnostic information.
Implementation details:
Uses size() method to get current job count
Formats output using the formatter utility
Useful for logging and debugging purposes
Returns
Formatted string showing current job count
Reimplemented from thread_module::job_queue.
to_string() [3/3]
auto thread_module::adaptive_job_queue::to_string (void) const -> std::string override virtual
Returns a string representation of this job_queue.
Provides a string representation of the queue's current state.
Returns
A std::string describing the state of the queue (e.g., size, flags).
Primarily used for logging and debugging. Derived classes may override this to include additional diagnostic information.
Implementation details:
Uses size() method to get current job count
Formats output using the formatter utility
Useful for logging and debugging purposes
Returns
Formatted string showing current job count
Reimplemented from thread_module::job_queue.
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/thread_base/lockfree/queues/adaptive_job_queue.h
libraries/thread_system/modular_structure/core/src/thread_base/lockfree/queues/adaptive_job_queue.h
libraries/thread_system/sources/thread_base/lockfree/queues/adaptive_job_queue.h
libraries/thread_system/modular_structure/core/src/thread_base/lockfree/queues/adaptive_job_queue.cpp
libraries/thread_system/sources/thread_base/lockfree/queues/adaptive_job_queue.cpp