Messaging System: monitoring::monitoring_system Class Reference
monitoring::monitoring_system Class Reference
#include <monitoring_system.h>
Public Member Functions
monitoring_system ()
~monitoring_system ()
bool initialize ()
void shutdown ()
bool is_running () const
void record_metric (const std::string &name, double value, const std::unordered_map< std::string, std::string > &labels={})
std::shared_ptr< counter > create_counter (const std::string &name, const std::string &description="", const std::unordered_map< std::string, std::string > &labels={})
std::shared_ptr< gauge > create_gauge (const std::string &name, const std::string &description="", const std::unordered_map< std::string, std::string > &labels={})
std::shared_ptr< timer > create_timer (const std::string &name, const std::string &description="", const std::unordered_map< std::string, std::string > &labels={})
std::shared_ptr< metric > get_metric (const std::string &name) const
std::vector< std::shared_ptr< metric > > get_all_metrics () const
void register_exporter (export_callback callback)
void set_export_interval (std::chrono::seconds interval)
void export_metrics ()
Detailed Description
Definition at line 18 of file monitoring_system.h.
Constructor & Destructor Documentation
monitoring_system()
monitoring::monitoring_system::monitoring_system () inline
Definition at line 36 of file monitoring_system.h.
~monitoring_system()
monitoring::monitoring_system::~monitoring_system () inline
Definition at line 39 of file monitoring_system.h.
References shutdown().
Member Function Documentation
create_counter()
std::shared_ptr< counter > monitoring::monitoring_system::create_counter (const std::string & name, const std::string & description = "", const std::unordered_map< std::string, std::string > & labels = {}) inline
Definition at line 98 of file monitoring_system.h.
create_gauge()
std::shared_ptr< gauge > monitoring::monitoring_system::create_gauge (const std::string & name, const std::string & description = "", const std::unordered_map< std::string, std::string > & labels = {}) inline
Definition at line 110 of file monitoring_system.h.
create_timer()
std::shared_ptr< timer > monitoring::monitoring_system::create_timer (const std::string & name, const std::string & description = "", const std::unordered_map< std::string, std::string > & labels = {}) inline
Definition at line 122 of file monitoring_system.h.
export_metrics()
void monitoring::monitoring_system::export_metrics () inline
Definition at line 154 of file monitoring_system.h.
References get_all_metrics().
get_all_metrics()
std::vector< std::shared_ptr< metric > > monitoring::monitoring_system::get_all_metrics () const inline
Definition at line 139 of file monitoring_system.h.
Referenced by export_metrics().
get_metric()
std::shared_ptr< metric > monitoring::monitoring_system::get_metric (const std::string & name) const inline
Definition at line 134 of file monitoring_system.h.
initialize()
bool monitoring::monitoring_system::initialize () inline
Definition at line 44 of file monitoring_system.h.
is_running()
bool monitoring::monitoring_system::is_running () const inline
Definition at line 64 of file monitoring_system.h.
record_metric()
void monitoring::monitoring_system::record_metric (const std::string & name, double value, const std::unordered_map< std::string, std::string > & labels = {}) inline
Definition at line 69 of file monitoring_system.h.
register_exporter()
void monitoring::monitoring_system::register_exporter (export_callback callback) inline
Definition at line 144 of file monitoring_system.h.
set_export_interval()
void monitoring::monitoring_system::set_export_interval (std::chrono::seconds interval) inline
Definition at line 149 of file monitoring_system.h.
shutdown()
void monitoring::monitoring_system::shutdown () inline
Definition at line 54 of file monitoring_system.h.
Referenced by ~monitoring_system().
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/monitoring/monitoring_system.h