Messaging System: thread_module::thread_context_builder Class Reference
thread_module::thread_context_builder Class Reference
Builder for thread_context with fluent interface.
#include <thread_context.h>
Public Member Functions
thread_context_builder & with_logger (std::shared_ptr< logger_interface > logger)
thread_context_builder & with_monitoring (std::shared_ptr< monitoring_interface::monitoring_interface > monitoring)
thread_context_builder & from_global_container ()
thread_context build () const
thread_context_builder & with_logger (std::shared_ptr< logger_interface > logger)
thread_context_builder & with_monitoring (std::shared_ptr< monitoring_interface::monitoring_interface > monitoring)
thread_context_builder & from_global_container ()
thread_context build () const
Detailed Description
Builder for thread_context with fluent interface.
Definition at line 175 of file thread_context.h.
Member Function Documentation
build() [1/2]
thread_context thread_module::thread_context_builder::build () const inline
Definition at line 194 of file thread_context.h.
Referenced by demonstrate_typed_pool_composition().
build() [2/2]
thread_context thread_module::thread_context_builder::build () const inline
Definition at line 194 of file thread_context.h.
from_global_container() [1/2]
thread_context_builder & thread_module::thread_context_builder::from_global_container () inline
Definition at line 188 of file thread_context.h.
References thread_module::service_container::global(), and thread_module::service_container::resolve().
Referenced by demonstrate_typed_pool_composition().
from_global_container() [2/2]
thread_context_builder & thread_module::thread_context_builder::from_global_container () inline
Definition at line 188 of file thread_context.h.
References thread_module::service_container::global(), and thread_module::service_container::resolve().
with_logger() [1/2]
thread_context_builder & thread_module::thread_context_builder::with_logger (std::shared_ptr< logger_interface > logger) inline
Definition at line 177 of file thread_context.h.
with_logger() [2/2]
thread_context_builder & thread_module::thread_context_builder::with_logger (std::shared_ptr< logger_interface > logger) inline
Definition at line 177 of file thread_context.h.
with_monitoring() [1/2]
thread_context_builder & thread_module::thread_context_builder::with_monitoring (std::shared_ptr< monitoring_interface::monitoring_interface > monitoring) inline
Definition at line 182 of file thread_context.h.
with_monitoring() [2/2]
thread_context_builder & thread_module::thread_context_builder::with_monitoring (std::shared_ptr< monitoring_interface::monitoring_interface > monitoring) inline
Definition at line 182 of file thread_context.h.
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/interfaces/thread_context.h
libraries/thread_system/sources/interfaces/thread_context.h