Messaging System: monitoring_system::buffer_manager Class Reference
monitoring_system::buffer_manager Class Reference
High-level buffer management system.
#include <buffer_manager.h>
Public Member Functions
buffer_manager (const buffer_manager_config &config={}, std::shared_ptr< metric_storage > storage=nullptr)
Constructor.
~buffer_manager ()
Destructor.
buffer_manager (const buffer_manager &)=delete
buffer_manager & operator= (const buffer_manager &)=delete
buffer_manager (buffer_manager &&)=delete
buffer_manager & operator= (buffer_manager &&)=delete
result_void add_metric (const std::string &metric_name, compact_metric_value &&metric, uint8_t priority=128)
Add metric to buffer.
result_void configure_metric_buffer (const std::string &metric_name, const buffering_config &config)
Configure buffer strategy for a specific metric.
result_void force_flush (const std::string &metric_name)
Force flush a specific metric buffer.
result_void force_flush_all ()
Force flush all buffers.
result< buffer_statistics > get_buffer_statistics (const std::string &metric_name) const
Get buffer statistics for a specific metric.
result< size_t > get_buffer_size (const std::string &metric_name) const
Get buffer size for a specific metric.
std::vector< std::string > get_buffered_metrics () const
Get list of all metric names with buffers.
result_void start_background_processing ()
Start background processing.
void stop_background_processing ()
Stop background processing.
void set_flush_callback (std::function< void(const std::string &, const std::vector< buffered_metric > &)> callback)
Set flush callback.
void set_storage (std::shared_ptr< metric_storage > storage)
Set metric storage.
const buffer_manager_statistics & get_statistics () const
Get manager statistics.
const buffer_manager_config & get_config () const
Get configuration.
void clear_all_buffers ()
Clear all buffers.
result_void remove_buffer (const std::string &metric_name)
Remove buffer for a specific metric.
size_t get_total_memory_usage () const
Get total memory usage of all buffers.
Detailed Description
High-level buffer management system.
Definition at line 103 of file buffer_manager.h.
Constructor & Destructor Documentation
buffer_manager() [1/3]
monitoring_system::buffer_manager::buffer_manager (const buffer_manager_config & config = {}, std::shared_ptr< metric_storage > storage = nullptr) inline explicit
Constructor.
Definition at line 254 of file buffer_manager.h.
~buffer_manager()
monitoring_system::buffer_manager::~buffer_manager () inline
Destructor.
Definition at line 268 of file buffer_manager.h.
References stop_background_processing().
buffer_manager() [2/3]
monitoring_system::buffer_manager::buffer_manager (const buffer_manager &) delete
buffer_manager() [3/3]
monitoring_system::buffer_manager::buffer_manager (buffer_manager &&) delete
Member Function Documentation
add_metric()
result_void monitoring_system::buffer_manager::add_metric (const std::string & metric_name, compact_metric_value && metric, uint8_t priority = 128) inline
Add metric to buffer.
Definition at line 281 of file buffer_manager.h.
References monitoring_system::create_buffering_strategy(), monitoring_system::buffer_manager_config::default_buffering_config, and monitoring_system::buffer_manager_statistics::total_buffers.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
clear_all_buffers()
void monitoring_system::buffer_manager::clear_all_buffers () inline
Clear all buffers.
Definition at line 492 of file buffer_manager.h.
configure_metric_buffer()
result_void monitoring_system::buffer_manager::configure_metric_buffer (const std::string & metric_name, const buffering_config & config) inline
Configure buffer strategy for a specific metric.
Definition at line 310 of file buffer_manager.h.
References monitoring_system::metric_batch::add_metric(), monitoring_system::create_buffering_strategy(), monitoring_system::buffered_metric::metric, monitoring_system::buffer_manager_statistics::total_buffers, and monitoring_system::buffering_config::validate().
Referenced by TEST_F(), and TEST_F().
force_flush()
result_void monitoring_system::buffer_manager::force_flush (const std::string & metric_name) inline
Force flush a specific metric buffer.
Definition at line 350 of file buffer_manager.h.
Referenced by TEST_F().
force_flush_all()
result_void monitoring_system::buffer_manager::force_flush_all () inline
Force flush all buffers.
Definition at line 357 of file buffer_manager.h.
References monitoring_system::buffer_manager_statistics::failed_flushes.
Referenced by stop_background_processing(), and TEST_F().
get_buffer_size()
result< size_t > monitoring_system::buffer_manager::get_buffer_size (const std::string & metric_name) const inline
Get buffer size for a specific metric.
Definition at line 396 of file buffer_manager.h.
References monitoring_system::collector_not_found, and monitoring_system::make_success().
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
get_buffer_statistics()
result< buffer_statistics > monitoring_system::buffer_manager::get_buffer_statistics (const std::string & metric_name) const inline
Get buffer statistics for a specific metric.
Definition at line 381 of file buffer_manager.h.
References monitoring_system::collector_not_found, and monitoring_system::make_success().
Referenced by TEST_F().
get_buffered_metrics()
std::vector< std::string > monitoring_system::buffer_manager::get_buffered_metrics () const inline
Get list of all metric names with buffers.
Definition at line 411 of file buffer_manager.h.
Referenced by TEST_F(), and TEST_F().
get_config()
const buffer_manager_config & monitoring_system::buffer_manager::get_config () const inline
Get configuration.
Definition at line 485 of file buffer_manager.h.
get_statistics()
const buffer_manager_statistics & monitoring_system::buffer_manager::get_statistics () const inline
Get manager statistics.
Definition at line 478 of file buffer_manager.h.
get_total_memory_usage()
size_t monitoring_system::buffer_manager::get_total_memory_usage () const inline
Get total memory usage of all buffers.
Definition at line 531 of file buffer_manager.h.
operator=() [1/2]
buffer_manager & monitoring_system::buffer_manager::operator= (buffer_manager &&) delete
operator=() [2/2]
buffer_manager & monitoring_system::buffer_manager::operator= (const buffer_manager &) delete
remove_buffer()
result_void monitoring_system::buffer_manager::remove_buffer (const std::string & metric_name) inline
Remove buffer for a specific metric.
Definition at line 503 of file buffer_manager.h.
References monitoring_system::metric_batch::add_metric(), monitoring_system::collector_not_found, monitoring_system::buffered_metric::metric, and monitoring_system::buffer_manager_statistics::total_buffers.
set_flush_callback()
void monitoring_system::buffer_manager::set_flush_callback (std::function< void(const std::string &, const std::vector< buffered_metric > &)> callback) inline
Set flush callback.
Definition at line 464 of file buffer_manager.h.
set_storage()
void monitoring_system::buffer_manager::set_storage (std::shared_ptr< metric_storage > storage) inline
Set metric storage.
Definition at line 471 of file buffer_manager.h.
start_background_processing()
result_void monitoring_system::buffer_manager::start_background_processing () inline
Start background processing.
Definition at line 427 of file buffer_manager.h.
References monitoring_system::buffer_manager_config::enable_automatic_flushing, and monitoring_system::invalid_configuration.
Referenced by TEST_F().
stop_background_processing()
void monitoring_system::buffer_manager::stop_background_processing () inline
Stop background processing.
Definition at line 447 of file buffer_manager.h.
References force_flush_all().
Referenced by TEST_F(), and ~buffer_manager().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/buffer_manager.h