Messaging System: database::mongodb_query_builder Class Reference
database::mongodb_query_builder Class Reference
Builder for MongoDB queries.
#include <query_builder.h>
Public Member Functions
mongodb_query_builder ()
~mongodb_query_builder ()=default
mongodb_query_builder & collection (const std::string &name)
mongodb_query_builder & find (const std::map< std::string, database_value > &filter={})
mongodb_query_builder & find_one (const std::map< std::string, database_value > &filter={})
mongodb_query_builder & project (const std::vector< std::string > &fields)
mongodb_query_builder & exclude (const std::vector< std::string > &fields)
mongodb_query_builder & sort (const std::map< std::string, int > &sort_spec)
mongodb_query_builder & sort (const std::string &field, int direction=1)
mongodb_query_builder & limit (size_t count)
mongodb_query_builder & skip (size_t count)
mongodb_query_builder & insert_one (const std::map< std::string, database_value > &document)
mongodb_query_builder & insert_many (const std::vector< std::map< std::string, database_value > > &documents)
mongodb_query_builder & update_one (const std::map< std::string, database_value > &filter, const std::map< std::string, database_value > &update)
mongodb_query_builder & update_many (const std::map< std::string, database_value > &filter, const std::map< std::string, database_value > &update)
mongodb_query_builder & delete_one (const std::map< std::string, database_value > &filter)
mongodb_query_builder & delete_many (const std::map< std::string, database_value > &filter)
mongodb_query_builder & match (const std::map< std::string, database_value > &conditions)
mongodb_query_builder & group (const std::map< std::string, database_value > &group_spec)
mongodb_query_builder & unwind (const std::string &field)
std::string build () const
std::string build_json () const
void reset ()
Detailed Description
Builder for MongoDB queries.
Definition at line 184 of file query_builder.h.
Constructor & Destructor Documentation
mongodb_query_builder()
database::mongodb_query_builder::mongodb_query_builder ()
Definition at line 552 of file query_builder.cpp.
~mongodb_query_builder()
database::mongodb_query_builder::~mongodb_query_builder () default
References find().
Member Function Documentation
build()
std::string database::mongodb_query_builder::build () const
Definition at line 701 of file query_builder.cpp.
Referenced by build_json().
build_json()
std::string database::mongodb_query_builder::build_json () const
Definition at line 773 of file query_builder.cpp.
References build().
collection()
mongodb_query_builder & database::mongodb_query_builder::collection (const std::string & name)
Definition at line 559 of file query_builder.cpp.
delete_many()
mongodb_query_builder & database::mongodb_query_builder::delete_many (const std::map< std::string, database_value > & filter)
Definition at line 661 of file query_builder.cpp.
delete_one()
mongodb_query_builder & database::mongodb_query_builder::delete_one (const std::map< std::string, database_value > & filter)
Definition at line 653 of file query_builder.cpp.
exclude()
mongodb_query_builder & database::mongodb_query_builder::exclude (const std::vector< std::string > & fields)
Definition at line 589 of file query_builder.cpp.
find()
mongodb_query_builder & database::mongodb_query_builder::find (const std::map< std::string, database_value > & filter = {})
Definition at line 565 of file query_builder.cpp.
Referenced by ~mongodb_query_builder().
find_one()
mongodb_query_builder & database::mongodb_query_builder::find_one (const std::map< std::string, database_value > & filter = {})
Definition at line 572 of file query_builder.cpp.
group()
mongodb_query_builder & database::mongodb_query_builder::group (const std::map< std::string, database_value > & group_spec)
Definition at line 677 of file query_builder.cpp.
insert_many()
mongodb_query_builder & database::mongodb_query_builder::insert_many (const std::vector< std::map< std::string, database_value > > & documents)
Definition at line 628 of file query_builder.cpp.
insert_one()
mongodb_query_builder & database::mongodb_query_builder::insert_one (const std::map< std::string, database_value > & document)
Definition at line 621 of file query_builder.cpp.
limit()
mongodb_query_builder & database::mongodb_query_builder::limit (size_t count)
Definition at line 609 of file query_builder.cpp.
match()
mongodb_query_builder & database::mongodb_query_builder::match (const std::map< std::string, database_value > & conditions)
Definition at line 668 of file query_builder.cpp.
project()
mongodb_query_builder & database::mongodb_query_builder::project (const std::vector< std::string > & fields)
Definition at line 580 of file query_builder.cpp.
reset()
void database::mongodb_query_builder::reset ()
Definition at line 778 of file query_builder.cpp.
skip()
mongodb_query_builder & database::mongodb_query_builder::skip (size_t count)
Definition at line 615 of file query_builder.cpp.
sort() [1/2]
mongodb_query_builder & database::mongodb_query_builder::sort (const std::map< std::string, int > & sort_spec)
Definition at line 597 of file query_builder.cpp.
sort() [2/2]
mongodb_query_builder & database::mongodb_query_builder::sort (const std::string & field, int direction = 1)
Definition at line 603 of file query_builder.cpp.
unwind()
mongodb_query_builder & database::mongodb_query_builder::unwind (const std::string & field)
Definition at line 689 of file query_builder.cpp.
update_many()
mongodb_query_builder & database::mongodb_query_builder::update_many (const std::map< std::string, database_value > & filter, const std::map< std::string, database_value > & update)
Definition at line 644 of file query_builder.cpp.
update_one()
mongodb_query_builder & database::mongodb_query_builder::update_one (const std::map< std::string, database_value > & filter, const std::map< std::string, database_value > & update)
Definition at line 635 of file query_builder.cpp.
The documentation for this class was generated from the following files:
libraries/database_system/database/query_builder.h
libraries/database_system/database/query_builder.cpp