Messaging System: libraries/logger_system/tests/unit/stress_test/stress_test.cpp File Reference
stress_test.cpp File Reference
Stress tests for logger system.
#include <gtest/gtest.h>
#include "../../sources/logger/logger.h"
#include "../../sources/logger/config/logger_builder.h"
#include "../../sources/logger/writers/console_writer.h"
#include "../../sources/logger/writers/file_writer.h"
#include "../../sources/logger/writers/async_writer.h"
#include "../mocks/mock_writer.hpp"
#include <thread>
#include <vector>
#include <atomic>
#include <chrono>
#include <random>
#include <sstream>
#include <filesystem>
Classes
class stress_test
Typedefs
using log_level = thread_module::log_level
Functions
TEST_F (stress_test, concurrent_logging_stress)
Test high-volume concurrent logging.
TEST_F (stress_test, memory_stability_stress)
Test memory usage under sustained load.
TEST_F (stress_test, buffer_overflow_stress)
Test overflow handling under extreme load.
TEST_F (stress_test, writer_switching_stress)
Test rapid writer switching.
TEST_F (stress_test, random_load_pattern_stress)
Test logger behavior under random load patterns.
TEST_F (stress_test, writer_failure_recovery_stress)
Test logger recovery from writer failures.
TEST_F (stress_test, async_writer_performance_stress)
Test async writer performance under load.
Detailed Description
Stress tests for logger system.
Date
2025-09-09
BSD 3-Clause License Copyright (c) 2025, kcenon All rights reserved.
Definition in file stress_test.cpp.
Typedef Documentation
log_level
using log_level = thread_module::log_level
Definition at line 30 of file stress_test.cpp.
Function Documentation
TEST_F() [1/7]
TEST_F (stress_test , async_writer_performance_stress)
Test async writer performance under load.
Verifies that async writers maintain performance under heavy load.
Definition at line 335 of file stress_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger::flush(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), and kcenon::logger::result< T >::value().
TEST_F() [2/7]
TEST_F (stress_test , buffer_overflow_stress)
Test overflow handling under extreme load.
Verifies that the logger properly handles buffer overflow scenarios.
Definition at line 148 of file stress_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), kcenon::logger::result< T >::value(), kcenon::logger::logger_builder::with_buffer_size(), and kcenon::logger::logger_builder::with_overflow_policy().
TEST_F() [3/7]
TEST_F (stress_test , concurrent_logging_stress)
Test high-volume concurrent logging.
Verifies that the logger can handle multiple threads logging simultaneously without crashes or data corruption.
Definition at line 54 of file stress_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), kcenon::logger::result< T >::value(), and kcenon::logger::logger_builder::with_default_pattern().
TEST_F() [4/7]
TEST_F (stress_test , memory_stability_stress)
Test memory usage under sustained load.
Verifies that memory usage remains stable during extended logging sessions.
Definition at line 110 of file stress_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), kcenon::logger::result< T >::value(), and kcenon::logger::logger_builder::with_buffer_size().
TEST_F() [5/7]
TEST_F (stress_test , random_load_pattern_stress)
Test logger behavior under random load patterns.
Simulates realistic usage with varying message rates and sizes.
Definition at line 239 of file stress_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), kcenon::logger::result< T >::value(), and kcenon::logger::logger_builder::with_buffer_size().
TEST_F() [6/7]
TEST_F (stress_test , writer_failure_recovery_stress)
Test logger recovery from writer failures.
Verifies that the logger continues operating when writers fail.
Definition at line 293 of file stress_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), and kcenon::logger::result< T >::value().
TEST_F() [7/7]
TEST_F (stress_test , writer_switching_stress)
Test rapid writer switching.
Verifies that the logger can handle frequent writer additions and removals.
Definition at line 195 of file stress_test.cpp.
References kcenon::logger::logger::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::result< T >::has_value(), kcenon::logger::logger::log(), kcenon::logger::logger::remove_writer(), kcenon::logger::result< T >::value(), and kcenon::logger::logger_builder::with_default_pattern().