Messaging System: kcenon::logger::batch_writer Class Reference
kcenon::logger::batch_writer Class Reference
Batch writer that accumulates log entries and writes them in batches.
#include <batch_writer.h>
Classes
struct batch_stats
Get batch statistics.
struct config
Configuration for batch writer.
Public Member Functions
batch_writer (std::unique_ptr< base_writer > underlying_writer, const config &cfg=config{})
Construct a batch writer.
~batch_writer () override
Destructor - ensures all pending entries are flushed.
result_void write (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write a log entry to the batch.
result_void flush () override
Flush the batch to the underlying writer.
std::string get_name () const override
Get writer name.
bool is_healthy () const override
Check if writer is healthy.
size_t get_current_batch_size () const
Get current batch size.
const batch_stats & get_stats () const
Get batch statistics.
void reset_stats ()
Reset batch statistics.
Public Member Functions inherited from kcenon::logger::base_writer
virtual ~base_writer ()=default
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
Additional Inherited Members
Protected Member Functions inherited from kcenon::logger::base_writer
std::string format_log_entry (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (logger_system::log_level level) const
Convert log level to string representation.
std::string level_to_color (logger_system::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
Batch writer that accumulates log entries and writes them in batches.
This writer wraps another writer and accumulates log entries up to a configurable batch size or timeout, then writes them all at once. This reduces the number of I/O operations and improves performance.
Features:
Configurable batch size
Automatic flush on timeout
Thread-safe batch accumulation
Preserves original timestamps
Definition at line 58 of file batch_writer.h.
Constructor & Destructor Documentation
batch_writer()
kcenon::logger::batch_writer::batch_writer (std::unique_ptr< base_writer > underlying_writer, const config & cfg = config{}) explicit
Construct a batch writer.
Parameters
underlying_writer The actual writer to batch writes for
cfg Batch configuration
Definition at line 38 of file batch_writer.cpp.
References kcenon::logger::batch_writer::config::max_batch_size.
~batch_writer()
kcenon::logger::batch_writer::~batch_writer () override
Destructor - ensures all pending entries are flushed.
Definition at line 52 of file batch_writer.cpp.
References flush().
Member Function Documentation
flush()
result_void kcenon::logger::batch_writer::flush () override virtual
Flush the batch to the underlying writer.
Returns
result_void indicating success or error
Implements kcenon::logger::base_writer.
Definition at line 96 of file batch_writer.cpp.
References kcenon::logger::batch_writer::batch_stats::manual_flushes.
Referenced by write(), and ~batch_writer().
get_current_batch_size()
size_t kcenon::logger::batch_writer::get_current_batch_size () const
Get current batch size.
Returns
Number of entries currently in the batch
Definition at line 159 of file batch_writer.cpp.
get_name()
std::string kcenon::logger::batch_writer::get_name () const override virtual
Get writer name.
Returns
Name of the batch writer
Implements kcenon::logger::base_writer.
Definition at line 151 of file batch_writer.cpp.
get_stats()
const batch_stats & kcenon::logger::batch_writer::get_stats () const inline
Get batch statistics.
Returns
Current batch statistics
Definition at line 149 of file batch_writer.h.
is_healthy()
bool kcenon::logger::batch_writer::is_healthy () const override virtual
Check if writer is healthy.
Returns
true if both batch writer and underlying writer are healthy
Reimplemented from kcenon::logger::base_writer.
Definition at line 155 of file batch_writer.cpp.
reset_stats()
void kcenon::logger::batch_writer::reset_stats ()
Reset batch statistics.
Definition at line 164 of file batch_writer.cpp.
References kcenon::logger::batch_writer::batch_stats::dropped_entries, kcenon::logger::batch_writer::batch_stats::flush_on_size, kcenon::logger::batch_writer::batch_stats::flush_on_timeout, kcenon::logger::batch_writer::batch_stats::manual_flushes, kcenon::logger::batch_writer::batch_stats::total_batches, and kcenon::logger::batch_writer::batch_stats::total_entries.
write()
result_void kcenon::logger::batch_writer::write (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write a log entry to the batch.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
timestamp Time of log entry
Returns
result_void indicating success or error
Implements kcenon::logger::base_writer.
Definition at line 61 of file batch_writer.cpp.
References flush(), kcenon::logger::batch_writer::batch_stats::flush_on_size, kcenon::logger::make_logger_error(), kcenon::logger::queue_stopped, and kcenon::logger::batch_writer::batch_stats::total_entries.
The documentation for this class was generated from the following files:
libraries/logger_system/include/kcenon/logger/writers/batch_writer.h
libraries/logger_system/src/impl/writers/batch_writer.cpp