Messaging System: kcenon::messaging::core::message_bus Class Reference
kcenon::messaging::core::message_bus Class Reference
#include <message_bus.h>
Classes
struct statistics
struct statistics_snapshot
Public Member Functions
message_bus (const message_bus_config &config={})
~message_bus ()
message_bus (const message_bus &)=delete
message_bus & operator= (const message_bus &)=delete
message_bus (message_bus &&)=delete
message_bus & operator= (message_bus &&)=delete
bool initialize ()
void shutdown ()
bool is_running () const
bool publish (const message &msg)
bool publish (const std::string &topic, const message_payload &payload, const std::string &sender="")
void subscribe (const std::string &topic, message_handler handler)
void unsubscribe (const std::string &topic, const message_handler &handler)
void unsubscribe_all (const std::string &topic)
std::future< message > request (const message &request_msg)
void respond (const message &original_msg, const message &response_msg)
std::vector< std::string > get_topics () const
size_t get_subscriber_count (const std::string &topic) const
statistics_snapshot get_statistics () const
void reset_statistics ()
Detailed Description
Definition at line 32 of file message_bus.h.
Constructor & Destructor Documentation
message_bus() [1/3]
kcenon::messaging::core::message_bus::message_bus (const message_bus_config & config = {}) explicit
Definition at line 162 of file message_bus.cpp.
~message_bus()
kcenon::messaging::core::message_bus::~message_bus ()
Definition at line 170 of file message_bus.cpp.
References shutdown().
message_bus() [2/3]
kcenon::messaging::core::message_bus::message_bus (const message_bus &) delete
message_bus() [3/3]
kcenon::messaging::core::message_bus::message_bus (message_bus &&) delete
Member Function Documentation
get_statistics()
statistics_snapshot kcenon::messaging::core::message_bus::get_statistics () const inline
Definition at line 84 of file message_bus.h.
References kcenon::messaging::core::message_bus::statistics::active_subscriptions, kcenon::messaging::core::message_bus::statistics::messages_failed, kcenon::messaging::core::message_bus::statistics::messages_processed, kcenon::messaging::core::message_bus::statistics::messages_published, and kcenon::messaging::core::message_bus::statistics::pending_requests.
get_subscriber_count()
size_t kcenon::messaging::core::message_bus::get_subscriber_count (const std::string & topic) const
Definition at line 269 of file message_bus.cpp.
get_topics()
std::vector< std::string > kcenon::messaging::core::message_bus::get_topics () const
Definition at line 265 of file message_bus.cpp.
initialize()
bool kcenon::messaging::core::message_bus::initialize ()
Definition at line 174 of file message_bus.cpp.
References shutdown(), and kcenon::messaging::core::message_bus_config::worker_threads.
is_running()
bool kcenon::messaging::core::message_bus::is_running () const inline
Definition at line 46 of file message_bus.h.
Referenced by TEST_F().
operator=() [1/2]
message_bus & kcenon::messaging::core::message_bus::operator= (const message_bus &) delete
operator=() [2/2]
message_bus & kcenon::messaging::core::message_bus::operator= (message_bus &&) delete
publish() [1/2]
bool kcenon::messaging::core::message_bus::publish (const message & msg)
Definition at line 214 of file message_bus.cpp.
References kcenon::messaging::core::message_bus::statistics::messages_published.
Referenced by publish(), request(), and respond().
publish() [2/2]
bool kcenon::messaging::core::message_bus::publish (const std::string & topic, const message_payload & payload, const std::string & sender = "")
Definition at line 229 of file message_bus.cpp.
References kcenon::messaging::core::message::payload, and publish().
request()
std::future< message > kcenon::messaging::core::message_bus::request (const message & request_msg)
Definition at line 247 of file message_bus.cpp.
References kcenon::messaging::core::message_bus::statistics::pending_requests, and publish().
reset_statistics()
void kcenon::messaging::core::message_bus::reset_statistics ()
Definition at line 273 of file message_bus.cpp.
References kcenon::messaging::core::message_bus::statistics::messages_failed, kcenon::messaging::core::message_bus::statistics::messages_processed, and kcenon::messaging::core::message_bus::statistics::messages_published.
respond()
void kcenon::messaging::core::message_bus::respond (const message & original_msg, const message & response_msg)
Definition at line 260 of file message_bus.cpp.
References publish().
shutdown()
void kcenon::messaging::core::message_bus::shutdown ()
Definition at line 194 of file message_bus.cpp.
Referenced by initialize(), and ~message_bus().
subscribe()
void kcenon::messaging::core::message_bus::subscribe (const std::string & topic, message_handler handler)
Definition at line 236 of file message_bus.cpp.
References kcenon::messaging::core::message_bus::statistics::active_subscriptions.
Referenced by kcenon::messaging::services::logging::logging_service_adapter::register_with_bus(), kcenon::messaging::services::monitoring::monitoring_service_adapter::register_with_bus(), kcenon::messaging::services::container::container_service_adapter::register_with_bus(), and kcenon::messaging::services::network::network_service_adapter::register_with_bus().
unsubscribe()
void kcenon::messaging::core::message_bus::unsubscribe (const std::string & topic, const message_handler & handler)
unsubscribe_all()
void kcenon::messaging::core::message_bus::unsubscribe_all (const std::string & topic)
Definition at line 241 of file message_bus.cpp.
References kcenon::messaging::core::message_bus::statistics::active_subscriptions.
The documentation for this class was generated from the following files:
application_layer/include/kcenon/messaging/core/message_bus.h
application_layer/src/kcenon/messaging/core/message_bus.cpp