Messaging System: kcenon::logger::base_writer Class Reference
kcenon::logger::base_writer Class Reference abstract
Abstract base class for all log output writers.
#include <base_writer.h>
Public Member Functions
virtual ~base_writer ()=default
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
virtual result_void write (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)=0
Write a log entry (legacy API for backward compatibility)
virtual result_void flush () override=0
Flush any buffered data.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
virtual std::string get_name () const override=0
Get the name of this writer.
virtual bool is_healthy () const override
Check if the writer is healthy and operational.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
Protected Member Functions
std::string format_log_entry (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (logger_system::log_level level) const
Convert log level to string representation.
std::string level_to_color (logger_system::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
Abstract base class for all log output writers.
Writers are responsible for outputting log messages to various destinations. This class provides a compatibility layer between the old API and the new interface-based approach, implementing log_writer_interface while providing backward compatibility for existing code.
Key responsibilities:
Format log messages for output
Handle destination-specific output logic
Manage buffering and flushing
Provide health status information
Note
All derived classes must implement the pure virtual methods.
Warning
Writers used in async mode must be thread-safe.
Since
1.0.0
Definition at line 123 of file base_writer.h.
Constructor & Destructor Documentation
~base_writer()
virtual kcenon::logger::base_writer::~base_writer () virtual default
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
Member Function Documentation
flush()
virtual result_void kcenon::logger::base_writer::flush () override pure virtual
Flush any buffered data.
Returns
result_void indicating success or failure
Implements kcenon::logger::log_writer_interface.
Implemented in kcenon::logger::async_writer, kcenon::logger::batch_writer, kcenon::logger::console_writer, kcenon::logger::encrypted_writer, kcenon::logger::file_writer, kcenon::logger::network_writer, kcenon::logger::async::high_performance_async_writer, benchmark_writer, null_writer, null_writer, null_writer, null_writer, null_writer, null_writer, null_writer, null_writer, MockCollectorWriter, mock_writer, mock_writer, logger_system::testing::mock_writer, and MockWriter.
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
format_log_entry()
std::string kcenon::logger::base_writer::format_log_entry (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) protected
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
Definition at line 131 of file console_writer.cpp.
References level_to_string().
Referenced by kcenon::logger::console_writer::write(), kcenon::logger::encrypted_writer::write(), kcenon::logger::file_writer::write(), and MockWriter::write().
get_name()
virtual std::string kcenon::logger::base_writer::get_name () const override pure virtual
Get the name of this writer.
Returns
Writer name for identification
Implements kcenon::logger::log_writer_interface.
Implemented in kcenon::logger::async_writer, kcenon::logger::batch_writer, kcenon::logger::console_writer, kcenon::logger::encrypted_writer, kcenon::logger::file_writer, kcenon::logger::network_writer, kcenon::logger::rotating_file_writer, kcenon::logger::async::high_performance_async_writer, benchmark_writer, null_writer, MockCollectorWriter, mock_writer, mock_writer, logger_system::testing::mock_writer, and MockWriter.
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
is_healthy()
virtual bool kcenon::logger::base_writer::is_healthy () const inline override virtual
Check if the writer is healthy and operational.
Returns
true if the writer is functioning correctly, false otherwise
Used for health monitoring and automatic failover. A writer might be unhealthy if its destination is unavailable (e.g., disk full, network disconnected).
Note
Default implementation always returns true. Override for writers that can detect failure conditions.
Since
1.0.0
Implements kcenon::logger::log_writer_interface.
Reimplemented in kcenon::logger::async_writer, kcenon::logger::batch_writer, kcenon::logger::async::high_performance_async_writer, and mock_writer.
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
Definition at line 249 of file base_writer.h.
level_to_color()
std::string kcenon::logger::base_writer::level_to_color (logger_system::log_level level) const protected
Get ANSI color code for the specified log level.
Parameters
level Log level to get color for
Returns
ANSI escape sequence for color, or empty string if color is disabled
Returns appropriate ANSI color codes for terminal output:
trace -> Gray/Dim
debug -> Cyan
info -> Green
warning -> Yellow
error -> Red
Note
Returns empty string if use_color() is false.
Warning
Only use for terminals that support ANSI escape codes.
Since
1.0.0
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
Definition at line 171 of file console_writer.cpp.
References use_color().
Referenced by kcenon::logger::console_writer::write().
level_to_string()
std::string kcenon::logger::base_writer::level_to_string (logger_system::log_level level) const protected
Convert log level to string representation.
Parameters
level Log level to convert
Returns
String representation of the level
Maps log levels to human-readable strings:
trace -> "TRACE"
debug -> "DEBUG"
info -> "INFO"
warning -> "WARNING"
error -> "ERROR"
Since
1.0.0
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
Definition at line 158 of file console_writer.cpp.
Referenced by format_log_entry().
set_use_color()
virtual void kcenon::logger::base_writer::set_use_color (bool use_color) inline virtual
Set whether to use color output (if supported)
Parameters
use_color true to enable color output, false to disable
Enables or disables ANSI color codes in formatted output. Only affects writers that output to terminals supporting color.
Note
Has no effect on writers that don't support color (e.g., file writers).
Since
1.0.0
Reimplemented in kcenon::logger::async_writer, and kcenon::logger::async::high_performance_async_writer.
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
Definition at line 209 of file base_writer.h.
References use_color().
Referenced by kcenon::logger::console_writer::console_writer().
use_color()
bool kcenon::logger::base_writer::use_color () const inline
Get current color output setting.
Returns
true if color output is enabled, false otherwise
Since
1.0.0
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
Definition at line 219 of file base_writer.h.
Referenced by level_to_color(), set_use_color(), kcenon::logger::async_writer::set_use_color(), kcenon::logger::async::high_performance_async_writer::set_use_color(), and kcenon::logger::console_writer::write().
write() [1/2]
virtual result_void kcenon::logger::base_writer::write (const log_entry & entry) inline override virtual
Write a log entry using the new interface.
Parameters
entry The log entry to write
Returns
result_void Success or error code
This method provides compatibility with the modern log_entry structure. The default implementation converts the entry to the legacy API format for backward compatibility. Derived classes can override this for optimized handling.
Note
This method extracts source location information if present in the entry.
Since
1.0.0
Implements kcenon::logger::log_writer_interface.
Reimplemented in logger_system::testing::mock_writer.
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/writers/base_writer.h.
Definition at line 140 of file base_writer.h.
References kcenon::logger::log_entry::level, kcenon::logger::log_entry::location, kcenon::logger::log_entry::message, kcenon::logger::log_entry::timestamp, kcenon::logger::small_string< SSO_SIZE >::to_string(), and write().
Referenced by write().
write() [2/2]
virtual result_void kcenon::logger::base_writer::write (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) pure virtual
Write a log entry (legacy API for backward compatibility)
Parameters
level Log severity level
message Log message text
file Source file path (empty if not available)
line Source line number (0 if not available)
function Function name (empty if not available)
timestamp Time when the log entry was created
Returns
result_void Success or error code
This is the main method that derived classes must implement. It receives all log information and is responsible for outputting it to the writer's specific destination.
Note
Implementations should handle empty file/function strings gracefully.
Warning
This method may be called from multiple threads in async mode. Implementations must be thread-safe.
Since
1.0.0
Implemented in kcenon::logger::async_writer, kcenon::logger::batch_writer, kcenon::logger::console_writer, kcenon::logger::encrypted_writer, kcenon::logger::file_writer, kcenon::logger::network_writer, kcenon::logger::rotating_file_writer, and kcenon::logger::async::high_performance_async_writer.
The documentation for this class was generated from the following files:
libraries/logger_system/include/kcenon/logger/writers/base_writer.h
libraries/logger_system/src/impl/writers/console_writer.cpp