Messaging System: database::orm::entity_metadata Class Reference
database::orm::entity_metadata Class Reference
Metadata for entire entities including table mapping and relationships.
#include <entity.h>
Public Member Functions
entity_metadata (const std::string &table_name)
void add_field (const field_metadata &field)
const std::vector< field_metadata > & fields () const
const std::string & table_name () const
const field_metadata * get_primary_key () const
std::vector< const field_metadata * > get_indexes () const
std::vector< const field_metadata * > get_foreign_keys () const
std::string create_table_sql () const
std::string create_indexes_sql () const
Detailed Description
Metadata for entire entities including table mapping and relationships.
Definition at line 137 of file entity.h.
Constructor & Destructor Documentation
entity_metadata()
database::orm::entity_metadata::entity_metadata (const std::string & table_name)
Definition at line 99 of file entity.cpp.
Member Function Documentation
add_field()
void database::orm::entity_metadata::add_field (const field_metadata & field)
Definition at line 104 of file entity.cpp.
create_indexes_sql()
std::string database::orm::entity_metadata::create_indexes_sql () const
Definition at line 163 of file entity.cpp.
References get_indexes(), and database::orm::index.
create_table_sql()
std::string database::orm::entity_metadata::create_table_sql () const
Definition at line 140 of file entity.cpp.
References get_foreign_keys().
fields()
const std::vector< field_metadata > & database::orm::entity_metadata::fields () const inline
Definition at line 143 of file entity.h.
get_foreign_keys()
std::vector< const field_metadata * > database::orm::entity_metadata::get_foreign_keys () const
Definition at line 129 of file entity.cpp.
Referenced by create_table_sql().
get_indexes()
std::vector< const field_metadata * > database::orm::entity_metadata::get_indexes () const
Definition at line 118 of file entity.cpp.
Referenced by create_indexes_sql().
get_primary_key()
const field_metadata * database::orm::entity_metadata::get_primary_key () const
Definition at line 109 of file entity.cpp.
table_name()
const std::string & database::orm::entity_metadata::table_name () const inline
Definition at line 144 of file entity.h.
Referenced by demonstrate_entity_definition().
The documentation for this class was generated from the following files:
libraries/database_system/database/orm/entity.h
libraries/database_system/database/orm/entity.cpp