Messaging System: libraries/thread_system/unittest/thread_base_test/thread_base_test.cpp File Reference
thread_base_test.cpp File Reference
#include <gtest/gtest.h>
#include <kcenon/thread/core/job_queue.h>
#include <kcenon/thread/core/callback_job.h>
#include <kcenon/thread/core/thread_base.h>
#include <thread>
#include <chrono>
#include <atomic>
Classes
class ThreadBaseTest
Functions
TEST_F (ThreadBaseTest, JobQueueBasicOperations)
TEST_F (ThreadBaseTest, JobQueueDequeue)
TEST_F (ThreadBaseTest, JobQueueMultipleJobs)
TEST_F (ThreadBaseTest, CallbackJobExecution)
TEST_F (ThreadBaseTest, CallbackJobWithError)
TEST_F (ThreadBaseTest, JobQueueStopWaiting)
TEST_F (ThreadBaseTest, ClearQueue)
TEST_F (ThreadBaseTest, ThreadBaseBasicOperations)
Function Documentation
TEST_F() [1/8]
TEST_F (ThreadBaseTest , CallbackJobExecution)
Definition at line 148 of file thread_base_test.cpp.
TEST_F() [2/8]
TEST_F (ThreadBaseTest , CallbackJobWithError)
Definition at line 171 of file thread_base_test.cpp.
References kcenon::thread::result< T >::get_error(), and kcenon::thread::error::message().
TEST_F() [3/8]
TEST_F (ThreadBaseTest , ClearQueue)
Definition at line 194 of file thread_base_test.cpp.
TEST_F() [4/8]
TEST_F (ThreadBaseTest , JobQueueBasicOperations)
Definition at line 62 of file thread_base_test.cpp.
TEST_F() [5/8]
TEST_F (ThreadBaseTest , JobQueueDequeue)
Definition at line 81 of file thread_base_test.cpp.
TEST_F() [6/8]
TEST_F (ThreadBaseTest , JobQueueMultipleJobs)
Definition at line 110 of file thread_base_test.cpp.
References kcenon::thread::job::do_work().
TEST_F() [7/8]
TEST_F (ThreadBaseTest , JobQueueStopWaiting)
Definition at line 186 of file thread_base_test.cpp.
TEST_F() [8/8]
TEST_F (ThreadBaseTest , ThreadBaseBasicOperations)
Definition at line 219 of file thread_base_test.cpp.
References kcenon::thread::thread_base::do_work(), and kcenon::thread::thread_base::should_continue_work().