Messaging System: kcenon::thread::test Namespace Reference
kcenon::thread::test Namespace Reference
Classes
class ConcurrencyTest
class ErrorHandlingTest
Functions
TEST_F (ConcurrencyTest, ThreadBaseRapidStartStop)
TEST_F (ConcurrencyTest, JobQueueExtremeConcurrency)
TEST_F (ConcurrencyTest, LockfreeQueueBoundaryConditions)
TEST_F (ConcurrencyTest, JobExecutionRaceConditions)
TEST_F (ConcurrencyTest, MemoryOrderingTest)
TEST_F (ConcurrencyTest, BarrierSynchronization)
TEST_F (ConcurrencyTest, LatchCoordination)
TEST_F (ConcurrencyTest, ABAScenario)
TEST_F (ConcurrencyTest, SpuriousWakeupHandling)
TEST_F (ErrorHandlingTest, ErrorCodeToString)
TEST_F (ErrorHandlingTest, ResultVoidSuccess)
TEST_F (ErrorHandlingTest, ResultVoidError)
TEST_F (ErrorHandlingTest, ResultWithValue)
TEST_F (ErrorHandlingTest, ResultValueOr)
TEST_F (ErrorHandlingTest, ResultAndThenBasic)
TEST_F (ErrorHandlingTest, ResultAndThen)
TEST_F (ErrorHandlingTest, ResultValueOrThrow)
TEST_F (ErrorHandlingTest, JobQueueErrorStates)
TEST_F (ErrorHandlingTest, JobExecutionErrors)
TEST_F (ErrorHandlingTest, ThreadBaseStartStop)
TEST_F (ErrorHandlingTest, ConcurrentErrorHandling)
TEST_F (ErrorHandlingTest, ErrorChaining)
TEST_F (ErrorHandlingTest, ResourceAllocationErrors)
TEST_F (ConcurrencyTest, JobQueueBoundaryConditions)
Function Documentation
TEST_F() [1/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , ABAScenario)
Definition at line 386 of file concurrency_test.cpp.
TEST_F() [2/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , BarrierSynchronization)
Definition at line 324 of file concurrency_test.cpp.
TEST_F() [3/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , JobExecutionRaceConditions)
Definition at line 224 of file concurrency_test.cpp.
References kcenon::thread::result< T >::has_value(), and kcenon::thread::result< T >::value().
TEST_F() [4/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , JobQueueBoundaryConditions)
Definition at line 180 of file concurrency_test.cpp.
TEST_F() [5/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , JobQueueExtremeConcurrency)
Definition at line 116 of file concurrency_test.cpp.
TEST_F() [6/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , LatchCoordination)
Definition at line 355 of file concurrency_test.cpp.
TEST_F() [7/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , LockfreeQueueBoundaryConditions)
Definition at line 181 of file concurrency_test.cpp.
TEST_F() [8/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , MemoryOrderingTest)
Definition at line 285 of file concurrency_test.cpp.
TEST_F() [9/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , SpuriousWakeupHandling)
Definition at line 455 of file concurrency_test.cpp.
TEST_F() [10/24]
kcenon::thread::test::TEST_F (ConcurrencyTest , ThreadBaseRapidStartStop)
Definition at line 61 of file concurrency_test.cpp.
TEST_F() [11/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ConcurrentErrorHandling)
Definition at line 236 of file error_handling_test.cpp.
References kcenon::thread::result< T >::has_value(), and kcenon::thread::unknown_error.
TEST_F() [12/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ErrorChaining)
Definition at line 270 of file error_handling_test.cpp.
References kcenon::thread::result< T >::and_then(), and kcenon::thread::invalid_argument.
TEST_F() [13/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ErrorCodeToString)
Definition at line 55 of file error_handling_test.cpp.
References kcenon::thread::error_code_to_string(), kcenon::thread::io_error, kcenon::thread::job_creation_failed, kcenon::thread::mutex_error, kcenon::thread::queue_full, kcenon::thread::resource_allocation_failed, kcenon::thread::success, kcenon::thread::thread_already_running, and kcenon::thread::unknown_error.
TEST_F() [14/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , JobExecutionErrors)
Definition at line 176 of file error_handling_test.cpp.
References kcenon::thread::error::code(), kcenon::thread::result< T >::get_error(), and kcenon::thread::job_execution_failed.
TEST_F() [15/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , JobQueueErrorStates)
Definition at line 161 of file error_handling_test.cpp.
TEST_F() [16/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ResourceAllocationErrors)
Definition at line 302 of file error_handling_test.cpp.
References kcenon::thread::resource_allocation_failed.
TEST_F() [17/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ResultAndThen)
Definition at line 132 of file error_handling_test.cpp.
References kcenon::thread::result< T >::and_then(), and kcenon::thread::invalid_argument.
TEST_F() [18/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ResultAndThenBasic)
Definition at line 112 of file error_handling_test.cpp.
References kcenon::thread::result< T >::and_then(), and kcenon::thread::unknown_error.
TEST_F() [19/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ResultValueOr)
Definition at line 104 of file error_handling_test.cpp.
References kcenon::thread::unknown_error.
TEST_F() [20/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ResultValueOrThrow)
Definition at line 146 of file error_handling_test.cpp.
References kcenon::thread::unknown_error.
TEST_F() [21/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ResultVoidError)
Definition at line 78 of file error_handling_test.cpp.
References kcenon::thread::unknown_error.
TEST_F() [22/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ResultVoidSuccess)
Definition at line 71 of file error_handling_test.cpp.
References kcenon::thread::result_void::has_error().
TEST_F() [23/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ResultWithValue)
Definition at line 88 of file error_handling_test.cpp.
References kcenon::thread::invalid_argument.
TEST_F() [24/24]
kcenon::thread::test::TEST_F (ErrorHandlingTest , ThreadBaseStartStop)
Definition at line 198 of file error_handling_test.cpp.