Messaging System: libraries/database_system/samples/security_framework_demo.cpp File Reference
security_framework_demo.cpp File Reference
#include <iostream>
#include <string>
#include <chrono>
#include <memory>
#include <vector>
#include "database/database_manager.h"
#include "database/security/secure_connection.h"
Functions
void demonstrate_secure_connections ()
void demonstrate_credential_management ()
void demonstrate_rbac_system ()
void demonstrate_audit_logging ()
void demonstrate_threat_detection ()
bool detect_sql_injection (const std::string &query)
void demonstrate_session_management ()
int main ()
Function Documentation
demonstrate_audit_logging()
void demonstrate_audit_logging ()
Definition at line 191 of file security_framework_demo.cpp.
References database::security::audit_logger::instance().
Referenced by main().
demonstrate_credential_management()
void demonstrate_credential_management ()
Definition at line 58 of file security_framework_demo.cpp.
References database::security::password.
Referenced by main().
demonstrate_rbac_system()
void demonstrate_rbac_system ()
Definition at line 110 of file security_framework_demo.cpp.
Referenced by main().
demonstrate_secure_connections()
void demonstrate_secure_connections ()
Definition at line 20 of file security_framework_demo.cpp.
Referenced by main().
demonstrate_session_management()
void demonstrate_session_management ()
Definition at line 363 of file security_framework_demo.cpp.
Referenced by main().
demonstrate_threat_detection()
void demonstrate_threat_detection ()
Definition at line 280 of file security_framework_demo.cpp.
References detect_sql_injection().
Referenced by main().
detect_sql_injection()
bool detect_sql_injection (const std::string & query)
Definition at line 336 of file security_framework_demo.cpp.
Referenced by demonstrate_threat_detection().
main()
int main ()
Definition at line 396 of file security_framework_demo.cpp.
References demonstrate_audit_logging(), demonstrate_credential_management(), demonstrate_rbac_system(), demonstrate_secure_connections(), demonstrate_session_management(), and demonstrate_threat_detection().