Messaging System: libraries/thread_system/unittest/thread_base_test/mpmc_queue_test.cpp File Reference
mpmc_queue_test.cpp File Reference
#include "gtest/gtest.h"
#include "lockfree/queues/lockfree_job_queue.h"
#include "lockfree/queues/adaptive_job_queue.h"
#include "jobs/callback_job.h"
#include <thread>
#include <vector>
#include <atomic>
#include <random>
#include <chrono>
#include <algorithm>
Classes
class MPMCQueueTest
Functions
TEST_F (MPMCQueueTest, BasicEnqueueDequeue)
TEST_F (MPMCQueueTest, EmptyQueueDequeue)
TEST_F (MPMCQueueTest, NullJobEnqueue)
TEST_F (MPMCQueueTest, BatchOperations)
TEST_F (MPMCQueueTest, ConcurrentEnqueue)
TEST_F (MPMCQueueTest, ConcurrentDequeue)
TEST_F (MPMCQueueTest, ProducerConsumerStress)
TEST_F (MPMCQueueTest, AdaptiveQueueBasicOperation)
TEST_F (MPMCQueueTest, AdaptiveQueueStrategySwitch)
TEST_F (MPMCQueueTest, PerformanceComparison)
TEST_F (MPMCQueueTest, SimpleMPMCPerformance)
TEST_F (MPMCQueueTest, MultipleProducerConsumer)
TEST_F (MPMCQueueTest, SingleThreadedSafety)
Function Documentation
TEST_F() [1/13]
TEST_F (MPMCQueueTest , AdaptiveQueueBasicOperation)
Definition at line 423 of file mpmc_queue_test.cpp.
References thread_module::adaptive_job_queue::dequeue(), thread_module::adaptive_job_queue::empty(), and thread_module::adaptive_job_queue::enqueue().
TEST_F() [2/13]
TEST_F (MPMCQueueTest , AdaptiveQueueStrategySwitch)
Definition at line 439 of file mpmc_queue_test.cpp.
References thread_module::adaptive_job_queue::dequeue(), thread_module::adaptive_job_queue::enqueue(), and thread_module::adaptive_job_queue::get_current_type().
TEST_F() [3/13]
TEST_F (MPMCQueueTest , BasicEnqueueDequeue)
Definition at line 76 of file mpmc_queue_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), thread_module::lockfree_job_queue::empty(), thread_module::lockfree_job_queue::enqueue(), and thread_module::lockfree_job_queue::size().
TEST_F() [4/13]
TEST_F (MPMCQueueTest , BatchOperations)
Definition at line 128 of file mpmc_queue_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), thread_module::lockfree_job_queue::dequeue_batch(), thread_module::job::do_work(), thread_module::lockfree_job_queue::empty(), thread_module::lockfree_job_queue::enqueue(), thread_module::lockfree_job_queue::enqueue_batch(), and thread_module::lockfree_job_queue::size().
TEST_F() [5/13]
TEST_F (MPMCQueueTest , ConcurrentDequeue)
Definition at line 235 of file mpmc_queue_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), thread_module::lockfree_job_queue::empty(), thread_module::lockfree_job_queue::enqueue(), thread_module::result< T >::has_value(), thread_module::lockfree_job_queue::size(), and thread_module::result< T >::value().
TEST_F() [6/13]
TEST_F (MPMCQueueTest , ConcurrentEnqueue)
Definition at line 185 of file mpmc_queue_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), thread_module::lockfree_job_queue::empty(), thread_module::lockfree_job_queue::enqueue(), thread_module::result< T >::has_value(), thread_module::lockfree_job_queue::size(), and thread_module::result< T >::value().
TEST_F() [7/13]
TEST_F (MPMCQueueTest , EmptyQueueDequeue)
Definition at line 107 of file mpmc_queue_test.cpp.
References thread_module::error::code(), thread_module::lockfree_job_queue::dequeue(), thread_module::result< T >::get_error(), and thread_module::result< T >::has_value().
TEST_F() [8/13]
TEST_F (MPMCQueueTest , MultipleProducerConsumer)
Definition at line 591 of file mpmc_queue_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), thread_module::lockfree_job_queue::enqueue(), thread_module::result< T >::has_value(), and thread_module::result< T >::value().
TEST_F() [9/13]
TEST_F (MPMCQueueTest , NullJobEnqueue)
Definition at line 117 of file mpmc_queue_test.cpp.
References thread_module::error::code(), thread_module::lockfree_job_queue::enqueue(), and thread_module::result< T >::get_error().
TEST_F() [10/13]
TEST_F (MPMCQueueTest , PerformanceComparison)
Definition at line 462 of file mpmc_queue_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), thread_module::job_queue::dequeue(), thread_module::job_queue::enqueue(), thread_module::lockfree_job_queue::enqueue(), and thread_module::lockfree_job_queue::get_statistics().
TEST_F() [11/13]
TEST_F (MPMCQueueTest , ProducerConsumerStress)
Definition at line 284 of file mpmc_queue_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), thread_module::lockfree_job_queue::empty(), thread_module::lockfree_job_queue::enqueue(), thread_module::lockfree_job_queue::get_statistics(), thread_module::result< T >::has_value(), and thread_module::result< T >::value().
TEST_F() [12/13]
TEST_F (MPMCQueueTest , SimpleMPMCPerformance)
Definition at line 521 of file mpmc_queue_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), thread_module::lockfree_job_queue::enqueue(), thread_module::result< T >::has_value(), and thread_module::result< T >::value().
TEST_F() [13/13]
TEST_F (MPMCQueueTest , SingleThreadedSafety)
Definition at line 679 of file mpmc_queue_test.cpp.
References thread_module::lockfree_job_queue::dequeue(), thread_module::lockfree_job_queue::empty(), thread_module::lockfree_job_queue::enqueue(), thread_module::result< T >::has_value(), thread_module::lockfree_job_queue::size(), and thread_module::result< T >::value().