Messaging System: monitoring_system::prometheus_exporter Class Reference
monitoring_system::prometheus_exporter Class Reference
Prometheus metric exporter implementation.
#include <metric_exporters.h>
Public Member Functions
prometheus_exporter (const metric_export_config &config)
std::vector< prometheus_metric_data > convert_monitoring_data (const monitoring_data &data) const
Convert monitoring_data to Prometheus format.
std::vector< prometheus_metric_data > convert_snapshot (const metrics_snapshot &snapshot) const
Convert metrics_snapshot to Prometheus format.
result_void export_metrics (const std::vector< monitoring_data > &metrics) override
Export a batch of metrics.
result_void export_snapshot (const metrics_snapshot &snapshot) override
Export a single metrics snapshot.
std::string get_metrics_text () const
Get current metrics in Prometheus format (for HTTP endpoint)
result_void flush () override
Flush any pending metrics.
result_void shutdown () override
Shutdown the exporter.
std::unordered_map< std::string, std::size_t > get_stats () const override
Get exporter statistics.
Public Member Functions inherited from monitoring_system::metric_exporter_interface
virtual ~metric_exporter_interface ()=default
virtual result_void start ()
Start the exporter (for pull-based systems)
virtual result_void stop ()
Stop the exporter.
Detailed Description
Prometheus metric exporter implementation.
Definition at line 285 of file metric_exporters.h.
Constructor & Destructor Documentation
prometheus_exporter()
monitoring_system::prometheus_exporter::prometheus_exporter (const metric_export_config & config) inline explicit
Definition at line 295 of file metric_exporters.h.
Member Function Documentation
convert_monitoring_data()
std::vector< prometheus_metric_data > monitoring_system::prometheus_exporter::convert_monitoring_data (const monitoring_data & data) const inline
Convert monitoring_data to Prometheus format.
Definition at line 301 of file metric_exporters.h.
References monitoring_system::monitoring_data::get_component_name(), monitoring_system::monitoring_data::get_metrics(), monitoring_system::monitoring_data::get_tags(), monitoring_system::monitoring_data::get_timestamp(), monitoring_system::metric_export_config::instance_id, monitoring_system::metric_export_config::labels, monitoring_system::metric::name, monitoring_system::metric::timestamp, monitoring_system::metric::type, and monitoring_system::metric::value.
Referenced by export_metrics(), TEST_F(), and TEST_F().
convert_snapshot()
std::vector< prometheus_metric_data > monitoring_system::prometheus_exporter::convert_snapshot (const metrics_snapshot & snapshot) const inline
Convert metrics_snapshot to Prometheus format.
Definition at line 338 of file metric_exporters.h.
References monitoring_system::metric_export_config::instance_id, monitoring_system::metric_export_config::labels, monitoring_system::metrics_snapshot::metrics, monitoring_system::metric::name, monitoring_system::metrics_snapshot::source_id, monitoring_system::metric::timestamp, monitoring_system::metric::type, monitoring_system::metric::value, and monitoring_system::metric_value::value.
Referenced by export_snapshot(), and TEST_F().
export_metrics()
result_void monitoring_system::prometheus_exporter::export_metrics (const std::vector< monitoring_data > & metrics) inline override virtual
Export a batch of metrics.
Implements monitoring_system::metric_exporter_interface.
Definition at line 374 of file metric_exporters.h.
References convert_monitoring_data(), and monitoring_system::operation_failed.
Referenced by TEST_F(), and TEST_F().
export_snapshot()
result_void monitoring_system::prometheus_exporter::export_snapshot (const metrics_snapshot & snapshot) inline override virtual
Export a single metrics snapshot.
Implements monitoring_system::metric_exporter_interface.
Definition at line 395 of file metric_exporters.h.
References convert_snapshot(), and monitoring_system::operation_failed.
Referenced by TEST_F(), and TEST_F().
flush()
result_void monitoring_system::prometheus_exporter::flush () inline override virtual
Flush any pending metrics.
Implements monitoring_system::metric_exporter_interface.
Definition at line 429 of file metric_exporters.h.
Referenced by shutdown(), and TEST_F().
get_metrics_text()
std::string monitoring_system::prometheus_exporter::get_metrics_text () const inline
Get current metrics in Prometheus format (for HTTP endpoint)
Definition at line 415 of file metric_exporters.h.
Referenced by TEST_F().
get_stats()
std::unordered_map< std::string, std::size_t > monitoring_system::prometheus_exporter::get_stats () const inline override virtual
Get exporter statistics.
Implements monitoring_system::metric_exporter_interface.
Definition at line 438 of file metric_exporters.h.
Referenced by TEST_F(), and TEST_F().
shutdown()
result_void monitoring_system::prometheus_exporter::shutdown () inline override virtual
Shutdown the exporter.
Implements monitoring_system::metric_exporter_interface.
Definition at line 434 of file metric_exporters.h.
References flush().
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/exporters/metric_exporters.h