Messaging System: database::orm::entity_base Class Reference
database::orm::entity_base Class Reference abstract
Base class for all ORM entities.
#include <entity.h>
Public Member Functions
virtual ~entity_base ()=default
virtual std::string table_name () const =0
virtual const entity_metadata & get_metadata () const =0
virtual bool save ()=0
virtual bool load ()=0
virtual bool update ()=0
virtual bool remove ()=0
Protected Member Functions
entity_base ()=default
Detailed Description
Base class for all ORM entities.
Definition at line 162 of file entity.h.
Constructor & Destructor Documentation
~entity_base()
virtual database::orm::entity_base::~entity_base () virtual default
entity_base()
database::orm::entity_base::entity_base () protected default
Member Function Documentation
get_metadata()
virtual const entity_metadata & database::orm::entity_base::get_metadata () const pure virtual
Implemented in TestUser.
Referenced by demonstrate_entity_definition(), and TEST_F().
load()
virtual bool database::orm::entity_base::load () pure virtual
Implemented in TestUser.
remove()
virtual bool database::orm::entity_base::remove () pure virtual
Implemented in TestUser.
save()
virtual bool database::orm::entity_base::save () pure virtual
Implemented in TestUser.
table_name()
virtual std::string database::orm::entity_base::table_name () const pure virtual
Implemented in TestUser.
Referenced by demonstrate_schema_management().
update()
virtual bool database::orm::entity_base::update () pure virtual
Implemented in TestUser.
The documentation for this class was generated from the following file:
libraries/database_system/database/orm/entity.h