Messaging System: kcenon::logger::monitoring::monitoring_factory Class Reference
kcenon::logger::monitoring::monitoring_factory Class Reference
Factory class for creating monitoring instances.
#include <monitoring_factory.h>
Public Types
enum class monitor_type { automatic , basic , advanced }
Monitor type enumeration.
Static Public Member Functions
static std::shared_ptr< monitoring_interface > create_default ()
Create a default monitoring instance.
template<typename ConfigType >
static std::shared_ptr< monitoring_interface > create_with_config (const ConfigType &config)
Create a monitoring instance with specific configuration.
static monitoring_interface & get_global_monitoring ()
Get the global monitoring instance.
static std::shared_ptr< monitoring_interface > create_with_thresholds (double error_rate_threshold=0.1, double queue_utilization_threshold=0.9)
Create a monitoring instance with specific health thresholds.
Detailed Description
Factory class for creating monitoring instances.
Definition at line 16 of file monitoring_factory.h.
Member Enumeration Documentation
monitor_type
enum class kcenon::logger::monitoring::monitoring_factory::monitor_type strong
Monitor type enumeration.
Enumerator
automatic
basic
advanced
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger.h.
Definition at line 21 of file monitoring_factory.h.
Member Function Documentation
create_default()
static std::shared_ptr< monitoring_interface > kcenon::logger::monitoring::monitoring_factory::create_default () inline static
Create a default monitoring instance.
Returns
Shared pointer to monitoring interface
Definition at line 30 of file monitoring_factory.h.
Referenced by create_with_config(), and create_with_thresholds().
create_with_config()
template<typename ConfigType > static std::shared_ptr< monitoring_interface > kcenon::logger::monitoring::monitoring_factory::create_with_config (const ConfigType & config) inline static
Create a monitoring instance with specific configuration.
Parameters
config Configuration parameters for monitoring
Returns
Shared pointer to monitoring interface
Definition at line 40 of file monitoring_factory.h.
References create_default().
create_with_thresholds()
static std::shared_ptr< monitoring_interface > kcenon::logger::monitoring::monitoring_factory::create_with_thresholds (double error_rate_threshold = 0.1, double queue_utilization_threshold = 0.9) inline static
Create a monitoring instance with specific health thresholds.
Parameters
error_rate_threshold Error rate threshold for warning status
queue_utilization_threshold Queue utilization threshold for critical status
Returns
Shared pointer to monitoring interface
Definition at line 60 of file monitoring_factory.h.
References create_default().
get_global_monitoring()
static monitoring_interface & kcenon::logger::monitoring::monitoring_factory::get_global_monitoring () inline static
Get the global monitoring instance.
Returns
Reference to the global monitoring instance
Definition at line 49 of file monitoring_factory.h.
The documentation for this class was generated from the following file:
libraries/logger_system/include/kcenon/logger/core/monitoring/monitoring_factory.h