Messaging System: libraries/database_system/tests/integration_tests.cpp File Reference
integration_tests.cpp File Reference
#include <gtest/gtest.h>
#include <memory>
#include <chrono>
#include <thread>
#include <future>
#include <vector>
#include "database/database_manager.h"
#include "database/database_types.h"
#include "database/orm/entity.h"
#include "database/monitoring/performance_monitor.h"
#include "database/security/secure_connection.h"
#include "database/async/async_operations.h"
Classes
class IntegrationTestUser
class IntegrationTestBase
class ORMSecurityIntegrationTest
class PerformanceAsyncIntegrationTest
class SecurityMonitoringIntegrationTest
class FullSystemIntegrationTest
class ErrorHandlingIntegrationTest
class ConcurrentOperationsIntegrationTest
Functions
TEST_F (ORMSecurityIntegrationTest, SecureEntityOperations)
TEST_F (PerformanceAsyncIntegrationTest, MonitoredAsyncOperations)
TEST_F (SecurityMonitoringIntegrationTest, MonitoredSecurityEvents)
TEST_F (FullSystemIntegrationTest, CompleteWorkflow)
TEST_F (ErrorHandlingIntegrationTest, FailureRecoveryWorkflow)
TEST_F (ConcurrentOperationsIntegrationTest, ConcurrentSecureOperations)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 561 of file integration_tests.cpp.
TEST_F() [1/6]
TEST_F (ConcurrentOperationsIntegrationTest , ConcurrentSecureOperations)
Definition at line 474 of file integration_tests.cpp.
References database::monitoring::query_metrics::execution_time, database::security::has_permission(), database::monitoring::performance_monitor::instance(), database::security::audit_logger::instance(), database::monitoring::query_metrics::rows_affected, and database::monitoring::query_metrics::success.
TEST_F() [2/6]
TEST_F (ErrorHandlingIntegrationTest , FailureRecoveryWorkflow)
Definition at line 410 of file integration_tests.cpp.
References database::monitoring::query_metrics::execution_time, database::monitoring::performance_monitor::instance(), database::security::audit_logger::instance(), database::monitoring::query_metrics::rows_affected, and database::monitoring::query_metrics::success.
TEST_F() [3/6]
TEST_F (FullSystemIntegrationTest , CompleteWorkflow)
Definition at line 323 of file integration_tests.cpp.
References database::monitoring::query_metrics::execution_time, database::monitoring::performance_monitor::instance(), database::orm::entity_manager::instance(), database::security::audit_logger::instance(), database::monitoring::query_metrics::rows_affected, and database::monitoring::query_metrics::success.
TEST_F() [4/6]
TEST_F (ORMSecurityIntegrationTest , SecureEntityOperations)
Definition at line 149 of file integration_tests.cpp.
References database::orm::entity_base::get_metadata(), and database::security::audit_logger::instance().
TEST_F() [5/6]
TEST_F (PerformanceAsyncIntegrationTest , MonitoredAsyncOperations)
Definition at line 194 of file integration_tests.cpp.
References database::monitoring::query_metrics::execution_time, database::monitoring::performance_monitor::instance(), database::monitoring::query_metrics::rows_affected, and database::monitoring::query_metrics::success.
TEST_F() [6/6]
TEST_F (SecurityMonitoringIntegrationTest , MonitoredSecurityEvents)
Definition at line 249 of file integration_tests.cpp.
References database::monitoring::query_metrics::execution_time, database::security::has_permission(), database::monitoring::performance_monitor::instance(), database::security::audit_logger::instance(), database::monitoring::query_metrics::rows_affected, and database::monitoring::query_metrics::success.