Messaging System: thread_module::scoped_crash_callback Class Reference
thread_module::scoped_crash_callback Class Reference
RAII helper for automatic crash callback registration.
#include <crash_handler.h>
Public Member Functions
scoped_crash_callback (const std::string &name, crash_callback callback, int priority=100)
~scoped_crash_callback ()
scoped_crash_callback (const scoped_crash_callback &)=delete
scoped_crash_callback & operator= (const scoped_crash_callback &)=delete
scoped_crash_callback (scoped_crash_callback &&)=default
scoped_crash_callback & operator= (scoped_crash_callback &&)=default
scoped_crash_callback (const std::string &name, crash_callback callback, int priority=100)
~scoped_crash_callback ()
scoped_crash_callback (const scoped_crash_callback &)=delete
scoped_crash_callback & operator= (const scoped_crash_callback &)=delete
scoped_crash_callback (scoped_crash_callback &&)=default
scoped_crash_callback & operator= (scoped_crash_callback &&)=default
Detailed Description
RAII helper for automatic crash callback registration.
Definition at line 194 of file crash_handler.h.
Constructor & Destructor Documentation
scoped_crash_callback() [1/6]
thread_module::scoped_crash_callback::scoped_crash_callback (const std::string & name, crash_callback callback, int priority = 100) inline
Definition at line 196 of file crash_handler.h.
~scoped_crash_callback() [1/2]
thread_module::scoped_crash_callback::~scoped_crash_callback () inline
Definition at line 199 of file crash_handler.h.
References thread_module::crash_handler::instance(), and thread_module::crash_handler::unregister_crash_callback().
scoped_crash_callback() [2/6]
thread_module::scoped_crash_callback::scoped_crash_callback (const scoped_crash_callback &) delete
scoped_crash_callback() [3/6]
thread_module::scoped_crash_callback::scoped_crash_callback (scoped_crash_callback &&) default
scoped_crash_callback() [4/6]
thread_module::scoped_crash_callback::scoped_crash_callback (const std::string & name, crash_callback callback, int priority = 100) inline
Definition at line 196 of file crash_handler.h.
~scoped_crash_callback() [2/2]
thread_module::scoped_crash_callback::~scoped_crash_callback () inline
Definition at line 199 of file crash_handler.h.
References thread_module::crash_handler::instance(), and thread_module::crash_handler::unregister_crash_callback().
scoped_crash_callback() [5/6]
thread_module::scoped_crash_callback::scoped_crash_callback (const scoped_crash_callback &) delete
scoped_crash_callback() [6/6]
thread_module::scoped_crash_callback::scoped_crash_callback (scoped_crash_callback &&) default
Member Function Documentation
operator=() [1/4]
scoped_crash_callback & thread_module::scoped_crash_callback::operator= (const scoped_crash_callback &) delete
operator=() [2/4]
scoped_crash_callback & thread_module::scoped_crash_callback::operator= (const scoped_crash_callback &) delete
operator=() [3/4]
scoped_crash_callback & thread_module::scoped_crash_callback::operator= (scoped_crash_callback &&) default
operator=() [4/4]
scoped_crash_callback & thread_module::scoped_crash_callback::operator= (scoped_crash_callback &&) default
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/interfaces/crash_handler.h
libraries/thread_system/sources/interfaces/crash_handler.h