Messaging System: monitoring_module::multi_process_monitoring::multi_process_impl Class Reference
monitoring_module::multi_process_monitoring::multi_process_impl Class Reference
다중 프로세스 모니터링 구현 세부사항
Public Member Functions
multi_process_impl (std::size_t history_size, std::uint32_t collection_interval_ms, std::size_t max_processes, std::size_t max_pools_per_process)
~multi_process_impl ()
void register_process (const process_identifier &process_id)
void unregister_process (const process_identifier &process_id)
void register_thread_pool (const thread_pool_identifier &pool_id)
void unregister_thread_pool (const thread_pool_identifier &pool_id)
void update_process_system_metrics (const process_identifier &process_id, const system_metrics &metrics)
void update_thread_pool_metrics (const thread_pool_identifier &pool_id, const process_thread_pool_metrics &metrics)
void update_process_worker_metrics (const process_identifier &process_id, std::size_t worker_id, const worker_metrics &metrics)
multi_process_metrics_snapshot get_multi_process_snapshot () const
metrics_snapshot get_process_snapshot (const process_identifier &process_id) const
std::unordered_map< std::string, double > compare_process_performance (const std::vector< process_identifier > &process_ids) const
bool is_active () const
void start ()
void stop ()
void set_default_process (const process_identifier &process_id)
void set_default_thread_pool (const thread_pool_identifier &pool_id)
void update_system_metrics (const system_metrics &metrics)
void update_thread_pool_metrics (const thread_pool_metrics &metrics)
void update_worker_metrics (std::size_t worker_id, const worker_metrics &metrics)
metrics_snapshot get_current_snapshot () const
std::vector< process_identifier > get_registered_processes () const
std::vector< thread_pool_identifier > get_process_thread_pools (const process_identifier &process_id) const
Detailed Description
다중 프로세스 모니터링 구현 세부사항
Definition at line 27 of file multi_process_monitoring.cpp.
Constructor & Destructor Documentation
multi_process_impl()
monitoring_module::multi_process_monitoring::multi_process_impl::multi_process_impl (std::size_t history_size, std::uint32_t collection_interval_ms, std::size_t max_processes, std::size_t max_pools_per_process) inline
Definition at line 29 of file multi_process_monitoring.cpp.
~multi_process_impl()
monitoring_module::multi_process_monitoring::multi_process_impl::~multi_process_impl () inline
Definition at line 41 of file multi_process_monitoring.cpp.
References stop().
Member Function Documentation
compare_process_performance()
std::unordered_map< std::string, double > monitoring_module::multi_process_monitoring::multi_process_impl::compare_process_performance (const std::vector< process_identifier > & process_ids) const inline
Definition at line 219 of file multi_process_monitoring.cpp.
get_current_snapshot()
metrics_snapshot monitoring_module::multi_process_monitoring::multi_process_impl::get_current_snapshot () const inline
Definition at line 303 of file multi_process_monitoring.cpp.
References monitoring_interface::metrics_snapshot::capture_time, get_multi_process_snapshot(), get_process_snapshot(), monitoring_interface::process_identifier::pid, monitoring_interface::metrics_snapshot::system, monitoring_interface::metrics_snapshot::thread_pool, and monitoring_interface::thread_pool_metrics::worker_threads.
get_multi_process_snapshot()
multi_process_metrics_snapshot monitoring_module::multi_process_monitoring::multi_process_impl::get_multi_process_snapshot () const inline
Definition at line 141 of file multi_process_monitoring.cpp.
References monitoring_interface::multi_process_metrics_snapshot::capture_time, monitoring_interface::multi_process_metrics_snapshot::global_system, monitoring_interface::multi_process_metrics_snapshot::process_system_metrics, monitoring_interface::multi_process_metrics_snapshot::process_worker_metrics, and monitoring_interface::multi_process_metrics_snapshot::thread_pool_metrics_map.
Referenced by get_current_snapshot().
get_process_snapshot()
metrics_snapshot monitoring_module::multi_process_monitoring::multi_process_impl::get_process_snapshot (const process_identifier & process_id) const inline
Definition at line 175 of file multi_process_monitoring.cpp.
References monitoring_interface::metrics_snapshot::capture_time, monitoring_interface::worker_metrics::jobs_processed, monitoring_interface::metrics_snapshot::system, monitoring_interface::metrics_snapshot::thread_pool, monitoring_interface::metrics_snapshot::worker, and monitoring_interface::thread_pool_metrics::worker_threads.
Referenced by get_current_snapshot().
get_process_thread_pools()
std::vector< thread_pool_identifier > monitoring_module::multi_process_monitoring::multi_process_impl::get_process_thread_pools (const process_identifier & process_id) const inline
Definition at line 341 of file multi_process_monitoring.cpp.
get_registered_processes()
std::vector< process_identifier > monitoring_module::multi_process_monitoring::multi_process_impl::get_registered_processes () const inline
Definition at line 329 of file multi_process_monitoring.cpp.
is_active()
bool monitoring_module::multi_process_monitoring::multi_process_impl::is_active () const inline
Definition at line 248 of file multi_process_monitoring.cpp.
register_process()
void monitoring_module::multi_process_monitoring::multi_process_impl::register_process (const process_identifier & process_id) inline
Definition at line 46 of file multi_process_monitoring.cpp.
register_thread_pool()
void monitoring_module::multi_process_monitoring::multi_process_impl::register_thread_pool (const thread_pool_identifier & pool_id) inline
Definition at line 74 of file multi_process_monitoring.cpp.
References monitoring_interface::thread_pool_identifier::process_id.
set_default_process()
void monitoring_module::multi_process_monitoring::multi_process_impl::set_default_process (const process_identifier & process_id) inline
Definition at line 271 of file multi_process_monitoring.cpp.
set_default_thread_pool()
void monitoring_module::multi_process_monitoring::multi_process_impl::set_default_thread_pool (const thread_pool_identifier & pool_id) inline
Definition at line 276 of file multi_process_monitoring.cpp.
start()
void monitoring_module::multi_process_monitoring::multi_process_impl::start () inline
Definition at line 252 of file multi_process_monitoring.cpp.
stop()
void monitoring_module::multi_process_monitoring::multi_process_impl::stop () inline
Definition at line 263 of file multi_process_monitoring.cpp.
Referenced by ~multi_process_impl().
unregister_process()
void monitoring_module::multi_process_monitoring::multi_process_impl::unregister_process (const process_identifier & process_id) inline
Definition at line 60 of file multi_process_monitoring.cpp.
unregister_thread_pool()
void monitoring_module::multi_process_monitoring::multi_process_impl::unregister_thread_pool (const thread_pool_identifier & pool_id) inline
Definition at line 92 of file multi_process_monitoring.cpp.
References monitoring_interface::thread_pool_identifier::process_id.
update_process_system_metrics()
void monitoring_module::multi_process_monitoring::multi_process_impl::update_process_system_metrics (const process_identifier & process_id, const system_metrics & metrics) inline
Definition at line 105 of file multi_process_monitoring.cpp.
Referenced by update_system_metrics().
update_process_worker_metrics()
void monitoring_module::multi_process_monitoring::multi_process_impl::update_process_worker_metrics (const process_identifier & process_id, std::size_t worker_id, const worker_metrics & metrics) inline
Definition at line 128 of file multi_process_monitoring.cpp.
Referenced by update_worker_metrics().
update_system_metrics()
void monitoring_module::multi_process_monitoring::multi_process_impl::update_system_metrics (const system_metrics & metrics) inline
Definition at line 282 of file multi_process_monitoring.cpp.
References monitoring_interface::process_identifier::pid, and update_process_system_metrics().
update_thread_pool_metrics() [1/2]
void monitoring_module::multi_process_monitoring::multi_process_impl::update_thread_pool_metrics (const thread_pool_identifier & pool_id, const process_thread_pool_metrics & metrics) inline
Definition at line 117 of file multi_process_monitoring.cpp.
References monitoring_interface::thread_pool_identifier::process_id.
Referenced by update_thread_pool_metrics().
update_thread_pool_metrics() [2/2]
void monitoring_module::multi_process_monitoring::multi_process_impl::update_thread_pool_metrics (const thread_pool_metrics & metrics) inline
Definition at line 288 of file multi_process_monitoring.cpp.
References monitoring_interface::process_identifier::pid, monitoring_interface::process_thread_pool_metrics::pool_id, monitoring_interface::thread_pool_identifier::process_id, and update_thread_pool_metrics().
update_worker_metrics()
void monitoring_module::multi_process_monitoring::multi_process_impl::update_worker_metrics (std::size_t worker_id, const worker_metrics & metrics) inline
Definition at line 297 of file multi_process_monitoring.cpp.
References monitoring_interface::process_identifier::pid, and update_process_worker_metrics().
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/monitoring/multi_process_monitoring.cpp