Messaging System: CrashSafetyTest Class Reference
CrashSafetyTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void cleanup_test_files ()
Protected Attributes
std::string test_log_path_
Detailed Description
Definition at line 17 of file crash_safety_test.cpp.
Member Function Documentation
cleanup_test_files()
void CrashSafetyTest::cleanup_test_files () inline protected
Definition at line 28 of file crash_safety_test.cpp.
References test_log_path_.
Referenced by SetUp(), and TearDown().
SetUp()
void CrashSafetyTest::SetUp () inline override protected
Definition at line 19 of file crash_safety_test.cpp.
References cleanup_test_files(), and test_log_path_.
TearDown()
void CrashSafetyTest::TearDown () inline override protected
Definition at line 24 of file crash_safety_test.cpp.
References cleanup_test_files().
Member Data Documentation
test_log_path_
std::string CrashSafetyTest::test_log_path_ protected
Definition at line 40 of file crash_safety_test.cpp.
Referenced by cleanup_test_files(), and SetUp().
The documentation for this class was generated from the following file:
libraries/logger_system/tests/unit/safety_test/crash_safety_test.cpp