Messaging System: container_module::variant_value Class Reference
container_module::variant_value Class Reference
Type-safe value wrapper with thread safety.
#include <variant_value.h>
Public Member Functions
variant_value ()
Default constructor - creates a null value.
variant_value (std::string_view name)
Construct with name and null value.
template<typename T >
variant_value (std::string_view name, T &&value)
Construct with name and value.
variant_value (const variant_value &other)
Copy constructor.
variant_value (variant_value &&other) noexcept
Move constructor.
variant_value & operator= (const variant_value &other)
Copy assignment.
variant_value & operator= (variant_value &&other) noexcept
Move assignment.
std::string_view name () const
Get the name of this value.
void set_name (std::string_view name)
Set the name of this value.
size_t type_index () const
Get the current type index (corresponds to value_types enum)
bool is_null () const
Check if this is a null value.
template<typename T >
std::optional< T > get () const
Type-safe getter with optional return.
template<typename T >
void set (T &&value)
Type-safe setter.
template<typename Visitor >
auto visit (Visitor &&vis) const
Apply a visitor to the contained value.
template<typename Visitor >
auto visit_mut (Visitor &&vis)
Apply a visitor to the contained value (mutable version)
std::string to_string () const
Convert to string representation.
std::string to_json () const
Convert to JSON representation.
std::vector< uint8_t > serialize () const
Serialize to binary format.
size_t read_count () const
Get read count (for statistics/debugging)
size_t write_count () const
Get write count (for statistics/debugging)
bool operator== (const variant_value &other) const
Comparison operators.
bool operator!= (const variant_value &other) const
bool operator< (const variant_value &other) const
Static Public Member Functions
static std::optional< variant_value > deserialize (const std::vector< uint8_t > &data)
Deserialize from binary format.
Detailed Description
Type-safe value wrapper with thread safety.
This class provides a modern, type-safe alternative to the polymorphic value class. It uses std::variant for type safety and includes thread synchronization primitives.
Definition at line 83 of file variant_value.h.
Constructor & Destructor Documentation
variant_value() [1/5]
container_module::variant_value::variant_value () inline
Default constructor - creates a null value.
Definition at line 89 of file variant_value.h.
variant_value() [2/5]
container_module::variant_value::variant_value (std::string_view name) inline explicit
Construct with name and null value.
Definition at line 94 of file variant_value.h.
variant_value() [3/5]
template<typename T > container_module::variant_value::variant_value (std::string_view name, T && value) inline
Construct with name and value.
Definition at line 101 of file variant_value.h.
variant_value() [4/5]
container_module::variant_value::variant_value (const variant_value & other)
Copy constructor.
Definition at line 44 of file variant_value.cpp.
variant_value() [5/5]
container_module::variant_value::variant_value (variant_value && other) noexcept
Move constructor.
Definition at line 51 of file variant_value.cpp.
Member Function Documentation
deserialize()
std::optional< variant_value > container_module::variant_value::deserialize (const std::vector< uint8_t > & data) static
Deserialize from binary format.
Definition at line 246 of file variant_value.cpp.
References container_module::value::data(), name(), and set().
Referenced by container_module::thread_safe_container::deserialize().
get()
template<typename T > std::optional< T > container_module::variant_value::get () const inline
Type-safe getter with optional return.
Template Parameters
T The type to retrieve
Returns
std::optional containing the value if type matches, empty otherwise
Definition at line 162 of file variant_value.h.
is_null()
bool container_module::variant_value::is_null () const inline
Check if this is a null value.
Definition at line 151 of file variant_value.h.
name()
std::string_view container_module::variant_value::name () const inline
Get the name of this value.
Definition at line 127 of file variant_value.h.
Referenced by deserialize(), set_name(), and to_json().
operator!=()
bool container_module::variant_value::operator!= (const variant_value & other) const
Definition at line 347 of file variant_value.cpp.
operator<()
bool container_module::variant_value::operator< (const variant_value & other) const
Definition at line 352 of file variant_value.cpp.
operator=() [1/2]
variant_value & container_module::variant_value::operator= (const variant_value & other)
Copy assignment.
Definition at line 62 of file variant_value.cpp.
operator=() [2/2]
variant_value & container_module::variant_value::operator= (variant_value && other) noexcept
Move assignment.
Definition at line 74 of file variant_value.cpp.
operator==()
bool container_module::variant_value::operator== (const variant_value & other) const
Comparison operators.
Definition at line 340 of file variant_value.cpp.
read_count()
size_t container_module::variant_value::read_count () const inline
Get read count (for statistics/debugging)
Definition at line 228 of file variant_value.h.
serialize()
std::vector< uint8_t > container_module::variant_value::serialize () const
Serialize to binary format.
Definition at line 183 of file variant_value.cpp.
References container_module::value::serialize(), container_module::value::size(), type_index(), and visit().
set()
template<typename T > void container_module::variant_value::set (T && value) inline
Type-safe setter.
Template Parameters
T The type to set
Parameters
value The value to store
Definition at line 176 of file variant_value.h.
Referenced by deserialize().
set_name()
void container_module::variant_value::set_name (std::string_view name) inline
Set the name of this value.
Definition at line 135 of file variant_value.h.
References name().
to_json()
std::string container_module::variant_value::to_json () const
Convert to JSON representation.
Definition at line 118 of file variant_value.cpp.
References kcenon::thread::utils::formatter::format_to(), name(), container_module::value::to_json(), type_index(), and visit().
to_string()
std::string container_module::variant_value::to_string () const
Convert to string representation.
Definition at line 86 of file variant_value.cpp.
References container_module::value::to_json(), and visit().
type_index()
size_t container_module::variant_value::type_index () const inline
Get the current type index (corresponds to value_types enum)
Definition at line 143 of file variant_value.h.
Referenced by serialize(), and to_json().
visit()
template<typename Visitor > auto container_module::variant_value::visit (Visitor && vis) const inline
Apply a visitor to the contained value.
Template Parameters
Visitor Callable object that can handle all variant types
Parameters
vis The visitor to apply
Returns
The result of the visitor
Definition at line 189 of file variant_value.h.
Referenced by serialize(), to_json(), and to_string().
visit_mut()
template<typename Visitor > auto container_module::variant_value::visit_mut (Visitor && vis) inline
Apply a visitor to the contained value (mutable version)
Definition at line 199 of file variant_value.h.
write_count()
size_t container_module::variant_value::write_count () const inline
Get write count (for statistics/debugging)
Definition at line 235 of file variant_value.h.
The documentation for this class was generated from the following files:
libraries/container_system/internal/variant_value.h
libraries/container_system/internal/variant_value.cpp