Messaging System: network_system::integration::thread_integration_manager::impl Class Reference
network_system::integration::thread_integration_manager::impl Class Reference
Public Member Functions
impl ()=default
void set_thread_pool (std::shared_ptr< thread_pool_interface > pool)
std::shared_ptr< thread_pool_interface > get_thread_pool ()
std::future< void > submit_task (std::function< void()> task)
std::future< void > submit_delayed_task (std::function< void()> task, std::chrono::milliseconds delay)
thread_integration_manager::metrics get_metrics () const
Detailed Description
Definition at line 193 of file thread_integration.cpp.
Constructor & Destructor Documentation
impl()
network_system::integration::thread_integration_manager::impl::impl () default
Member Function Documentation
get_metrics()
thread_integration_manager::metrics network_system::integration::thread_integration_manager::impl::get_metrics () const inline
Definition at line 221 of file thread_integration.cpp.
References network_system::integration::thread_integration_manager::metrics::completed_tasks, network_system::integration::thread_integration_manager::metrics::is_running, network_system::integration::thread_integration_manager::metrics::pending_tasks, and network_system::integration::thread_integration_manager::metrics::worker_threads.
get_thread_pool()
std::shared_ptr< thread_pool_interface > network_system::integration::thread_integration_manager::impl::get_thread_pool () inline
Definition at line 202 of file thread_integration.cpp.
Referenced by submit_delayed_task(), and submit_task().
set_thread_pool()
void network_system::integration::thread_integration_manager::impl::set_thread_pool (std::shared_ptr< thread_pool_interface > pool) inline
Definition at line 197 of file thread_integration.cpp.
submit_delayed_task()
std::future< void > network_system::integration::thread_integration_manager::impl::submit_delayed_task (std::function< void()> task, std::chrono::milliseconds delay) inline
Definition at line 214 of file thread_integration.cpp.
References get_thread_pool().
submit_task()
std::future< void > network_system::integration::thread_integration_manager::impl::submit_task (std::function< void()> task) inline
Definition at line 210 of file thread_integration.cpp.
References get_thread_pool().
The documentation for this class was generated from the following file:
libraries/network_system/src/integration/thread_integration.cpp