Messaging System: container_module::value Class Reference
container_module::value Class Reference
The base class for all values stored in the container system.
#include <value.h>
Public Member Functions
value ()
value (std::shared_ptr< value > object)
value (const std::string &name, std::vector< std::shared_ptr< value > > units={})
value (const std::string &name, const value_types &type, const std::string &data)
value (const std::string &name, const unsigned char *data, const size_t &size, const value_types &type=value_types::null_value)
value (value &&other) noexcept
value & operator= (value &&other) noexcept
virtual ~value ()
std::shared_ptr< value > get_ptr ()
void set_parent (std::shared_ptr< value > parent)
void set_data (const unsigned char *data, const size_t &size, const value_types &type)
Set raw data with a known type.
void set_data (const std::string &name, const value_types &type, const std::string &data)
Set this value from a string form, specifying a type.
std::string name () const
value_types type () const
std::string data () const
size_t size () const
std::shared_ptr< value > parent ()
size_t child_count () const
std::vector< std::shared_ptr< value > > children (const bool &only_container=false)
std::vector< std::shared_ptr< value > > value_array (std::string_view key)
const std::vector< uint8_t > to_bytes () const
bool is_null () const
bool is_bytes () const
bool is_boolean () const
bool is_numeric () const
bool is_string () const
bool is_container () const
const std::string to_xml ()
const std::string to_json ()
const std::string serialize ()
template<typename T >
T safe_convert (const char *type_name, T default_value) const
Template method for safe type conversion with null checking.
virtual bool to_boolean () const
Virtual numeric/string conversion methods.
virtual short to_short () const
virtual unsigned short to_ushort () const
virtual int to_int () const
virtual unsigned int to_uint () const
virtual long to_long () const
virtual unsigned long to_ulong () const
virtual long long to_llong () const
virtual unsigned long long to_ullong () const
virtual float to_float () const
virtual double to_double () const
virtual std::string to_string (const bool &original=true) const
virtual std::shared_ptr< value > add (const value &item, bool update_count=true)
Virtual methods for adding/removing child values.
virtual std::shared_ptr< value > add (std::shared_ptr< value > item, bool update_count=true)
virtual void add (const std::vector< value > &items, bool update_count=true)
virtual void add (const std::vector< std::shared_ptr< value > > &items, bool update_count=true)
virtual void remove (std::string_view name, bool update_count=true)
virtual void remove (std::shared_ptr< value > item, bool update_count=true)
virtual void remove_all ()
std::shared_ptr< value > operator[] (std::string_view key)
An index operator to get the first matching child by name (if any).
Protected Member Functions
template<typename T >
void set_data (T data)
std::string convert_specific_string (const std::vector< uint8_t > &data) const
std::vector< uint8_t > convert_specific_string (std::string data) const
void set_byte_string (const std::string &data)
void set_string (const std::string &data)
void set_boolean (const std::string &data)
void set_short (const std::string &data)
void set_ushort (const std::string &data)
void set_int (const std::string &data)
void set_uint (const std::string &data)
void set_long (const std::string &data)
void set_ulong (const std::string &data)
void set_llong (const std::string &data)
void set_ullong (const std::string &data)
void set_float (const std::string &data)
void set_double (const std::string &data)
Protected Attributes
size_t size_
value_types type_
std::string name_
std::vector< uint8_t > data_
std::weak_ptr< value > parent_
std::vector< std::shared_ptr< value > > units_
std::map< value_types, std::function< void(const std::string &)> > data_type_map_
Friends
std::shared_ptr< value > operator<< (std::shared_ptr< value > container, std::shared_ptr< value > other)
std::ostream & operator<< (std::ostream &out, std::shared_ptr< value > other)
std::string & operator<< (std::string &out, std::shared_ptr< value > other)
Detailed Description
The base class for all values stored in the container system.
Definition at line 51 of file value.h.
Constructor & Destructor Documentation
value() [1/6]
container_module::value::value ()
Definition at line 44 of file value.cpp.
References container_module::bool_value, container_module::bytes_value, container_module::container_value, data_type_map_, container_module::double_value, container_module::float_value, container_module::int_value, container_module::llong_value, container_module::long_value, set_boolean(), set_byte_string(), set_double(), set_float(), set_int(), set_llong(), set_long(), set_short(), set_string(), set_uint(), set_ullong(), set_ulong(), set_ushort(), container_module::short_value, container_module::string_value, container_module::uint_value, container_module::ullong_value, container_module::ulong_value, and container_module::ushort_value.
value() [2/6]
container_module::value::value (std::shared_ptr< value > object)
Definition at line 90 of file value.cpp.
References data_, name(), name_, parent_, size_, type_, and units_.
value() [3/6]
container_module::value::value (const std::string & name, std::vector< std::shared_ptr< value > > units = {})
Definition at line 103 of file value.cpp.
References container_module::container_value, name(), name_, set_data(), and units_.
value() [4/6]
container_module::value::value (const std::string & name, const value_types & type, const std::string & data)
Definition at line 114 of file value.cpp.
References name(), set_data(), and type().
value() [5/6]
container_module::value::value (const std::string & name, const unsigned char * data, const size_t & size, const value_types & type = value_types::null_value)
Definition at line 122 of file value.cpp.
References name(), name_, set_data(), and type().
value() [6/6]
container_module::value::value (value && other) noexcept
Definition at line 132 of file value.cpp.
References container_module::null_value.
~value()
container_module::value::~value () virtual
Definition at line 165 of file value.cpp.
Member Function Documentation
add() [1/4]
virtual void container_module::value::add (const std::vector< std::shared_ptr< value > > & items, bool update_count = true) inline virtual
Reimplemented in container_module::container_value.
Definition at line 206 of file value.h.
add() [2/4]
virtual void container_module::value::add (const std::vector< value > & items, bool update_count = true) inline virtual
Reimplemented in container_module::container_value.
Definition at line 201 of file value.h.
add() [3/4]
virtual std::shared_ptr< value > container_module::value::add (const value & item, bool update_count = true) inline virtual
Virtual methods for adding/removing child values.
By default, these throw logic_error.
Reimplemented in container_module::container_value.
Definition at line 191 of file value.h.
add() [4/4]
virtual std::shared_ptr< value > container_module::value::add (std::shared_ptr< value > item, bool update_count = true) inline virtual
Reimplemented in container_module::container_value.
Definition at line 196 of file value.h.
child_count()
size_t container_module::value::child_count () const
Definition at line 220 of file value.cpp.
References units_.
children()
std::vector< std::shared_ptr< value > > container_module::value::children (const bool & only_container = false)
Definition at line 222 of file value.cpp.
References units_.
convert_specific_string() [1/2]
std::string container_module::value::convert_specific_string (const std::vector< uint8_t > & data) const protected
Definition at line 388 of file value.cpp.
Referenced by container_module::string_value::string_value(), and container_module::string_value::to_string().
convert_specific_string() [2/2]
std::vector< uint8_t > container_module::value::convert_specific_string (std::string data) const protected
Definition at line 404 of file value.cpp.
data()
std::string container_module::value::data () const
Definition at line 207 of file value.cpp.
References container_module::string_value, to_string(), and type_.
Referenced by container_module::variant_value::deserialize(), and set_data().
get_ptr()
std::shared_ptr< value > container_module::value::get_ptr ()
Definition at line 167 of file value.cpp.
is_boolean()
bool container_module::value::is_boolean () const
Definition at line 260 of file value.cpp.
References container_module::bool_value, and type_.
is_bytes()
bool container_module::value::is_bytes () const
Definition at line 258 of file value.cpp.
References container_module::bytes_value, and type_.
is_container()
bool container_module::value::is_container () const
Definition at line 290 of file value.cpp.
References container_module::container_value, and type_.
is_null()
bool container_module::value::is_null () const
Definition at line 256 of file value.cpp.
References container_module::null_value, and type_.
is_numeric()
bool container_module::value::is_numeric () const
Definition at line 265 of file value.cpp.
References container_module::double_value, container_module::float_value, container_module::int_value, container_module::llong_value, container_module::long_value, container_module::short_value, type_, container_module::uint_value, container_module::ullong_value, container_module::ulong_value, and container_module::ushort_value.
is_string()
bool container_module::value::is_string () const
Definition at line 285 of file value.cpp.
References container_module::string_value, and type_.
name()
std::string container_module::value::name () const
Definition at line 203 of file value.cpp.
References name_.
Referenced by container_module::container_value::add(), container_module::bool_value::bool_value(), container_module::bool_value::bool_value(), container_module::bytes_value::bytes_value(), container_module::bytes_value::bytes_value(), container_module::container_value::container_value(), container_module::container_value::container_value(), demonstrate_value_access(), container_module::string_value::string_value(), value(), value(), value(), and value().
operator=()
value & container_module::value::operator= (value && other) noexcept
Definition at line 146 of file value.cpp.
References container_module::null_value, and size_.
operator[]()
std::shared_ptr< value > container_module::value::operator[] (std::string_view key)
An index operator to get the first matching child by name (if any).
Definition at line 357 of file value.cpp.
parent()
std::shared_ptr< value > container_module::value::parent ()
Definition at line 218 of file value.cpp.
References parent_.
Referenced by set_parent().
remove() [1/2]
virtual void container_module::value::remove (std::shared_ptr< value > item, bool update_count = true) inline virtual
Reimplemented in container_module::container_value.
Definition at line 215 of file value.h.
remove() [2/2]
virtual void container_module::value::remove (std::string_view name, bool update_count = true) inline virtual
Reimplemented in container_module::container_value.
Definition at line 211 of file value.h.
remove_all()
virtual void container_module::value::remove_all () inline virtual
Reimplemented in container_module::container_value.
Definition at line 220 of file value.h.
safe_convert()
template<typename T > T container_module::value::safe_convert (const char * type_name, T default_value) const inline
Template method for safe type conversion with null checking.
Template Parameters
T The target type for conversion
Parameters
type_name Human-readable name of the target type for error messages
default_value Default value to return for base class implementation
Returns
Converted value or default_value if conversion is not supported
Exceptions
std::logic_error if trying to convert from null_value
Definition at line 126 of file value.h.
References container_module::null_value, and type_.
serialize()
const std::string container_module::value::serialize ()
Definition at line 344 of file value.cpp.
References container_module::convert_value_type(), kcenon::thread::utils::formatter::format_to(), name_, to_string(), type_, and units_.
Referenced by container_module::thread_safe_container::serialize(), and container_module::variant_value::serialize().
set_boolean()
void container_module::value::set_boolean (const std::string & data) protected
Definition at line 448 of file value.cpp.
References container_module::bool_value, set_data(), and type_.
Referenced by value().
set_byte_string()
void container_module::value::set_byte_string (const std::string & data) protected
Definition at line 418 of file value.cpp.
References container_module::bytes_value, data_, size_, and type_.
Referenced by value().
set_data() [1/3]
void container_module::value::set_data (const std::string & name, const value_types & type, const std::string & data)
Set this value from a string form, specifying a type.
Parameters
name Value name.
type The enum type.
data The string to parse and store.
Definition at line 187 of file value.cpp.
References data_, data_type_map_, name_, size_, and type_.
set_data() [2/3]
void container_module::value::set_data (const unsigned char * data, const size_t & size, const value_types & type)
Set raw data with a known type.
Parameters
data Raw pointer.
size Byte size.
type The value_types enum to apply.
Definition at line 171 of file value.cpp.
References data_, size_, and type_.
Referenced by container_module::container_value::add(), container_module::container_value::add(), container_module::container_value::add(), container_module::bool_value::bool_value(), container_module::bool_value::bool_value(), container_module::bool_value::bool_value(), container_module::container_value::container_value(), container_module::container_value::container_value(), container_module::container_value::container_value(), container_module::container_value::remove(), container_module::container_value::remove(), container_module::container_value::remove_all(), set_boolean(), set_double(), set_float(), set_int(), set_llong(), set_long(), set_short(), set_uint(), set_ullong(), set_ulong(), set_ushort(), value(), value(), and value().
set_data() [3/3]
template<typename T > void container_module::value::set_data (T data) inline protected
Definition at line 240 of file value.h.
References data(), data_, and size_.
set_double()
void container_module::value::set_double (const std::string & data) protected
Definition at line 540 of file value.cpp.
References container_module::double_value, set_data(), and type_.
Referenced by value().
set_float()
void container_module::value::set_float (const std::string & data) protected
Definition at line 533 of file value.cpp.
References container_module::float_value, set_data(), and type_.
Referenced by value().
set_int()
void container_module::value::set_int (const std::string & data) protected
Definition at line 479 of file value.cpp.
References container_module::int_value, set_data(), and type_.
Referenced by value().
set_llong()
void container_module::value::set_llong (const std::string & data) protected
Definition at line 518 of file value.cpp.
References container_module::llong_value, set_data(), and type_.
Referenced by value().
set_long()
void container_module::value::set_long (const std::string & data) protected
Definition at line 503 of file value.cpp.
References container_module::long_value, set_data(), and type_.
Referenced by value().
set_parent()
void container_module::value::set_parent (std::shared_ptr< value > parent)
Definition at line 169 of file value.cpp.
References parent(), and parent_.
set_short()
void container_module::value::set_short (const std::string & data) protected
Definition at line 455 of file value.cpp.
References set_data(), container_module::short_value, and type_.
Referenced by value().
set_string()
void container_module::value::set_string (const std::string & data) protected
Definition at line 433 of file value.cpp.
References data_, size_, container_module::string_value, and type_.
Referenced by value().
set_uint()
void container_module::value::set_uint (const std::string & data) protected
Definition at line 491 of file value.cpp.
References set_data(), type_, and container_module::uint_value.
Referenced by value().
set_ullong()
void container_module::value::set_ullong (const std::string & data) protected
Definition at line 525 of file value.cpp.
References set_data(), type_, and container_module::ullong_value.
Referenced by value().
set_ulong()
void container_module::value::set_ulong (const std::string & data) protected
Definition at line 510 of file value.cpp.
References set_data(), type_, and container_module::ulong_value.
Referenced by value().
set_ushort()
void container_module::value::set_ushort (const std::string & data) protected
Definition at line 467 of file value.cpp.
References set_data(), type_, and container_module::ushort_value.
Referenced by value().
size()
size_t container_module::value::size () const
Definition at line 216 of file value.cpp.
References data_.
Referenced by container_module::bytes_value::bytes_value(), container_module::bytes_value::bytes_value(), and container_module::variant_value::serialize().
to_boolean()
virtual bool container_module::value::to_boolean (void) const inline virtual
Virtual numeric/string conversion methods.
Reimplemented in container_module::bool_value, and container_module::numeric_value< T, TypeTag >.
Definition at line 136 of file value.h.
Referenced by container_module::container_value::add().
to_bytes()
const std::vector< uint8_t > container_module::value::to_bytes () const
Definition at line 254 of file value.cpp.
References data_.
to_double()
virtual double container_module::value::to_double (void) const inline virtual
Reimplemented in container_module::numeric_value< T, TypeTag >.
Definition at line 176 of file value.h.
to_float()
virtual float container_module::value::to_float (void) const inline virtual
Reimplemented in container_module::numeric_value< T, TypeTag >.
Definition at line 172 of file value.h.
to_int()
virtual int container_module::value::to_int (void) const inline virtual
Reimplemented in container_module::numeric_value< T, TypeTag >.
Definition at line 148 of file value.h.
to_json()
const std::string container_module::value::to_json ()
Definition at line 313 of file value.cpp.
References container_module::bytes_value, kcenon::thread::utils::formatter::format_to(), name_, container_module::string_value, to_string(), type_, and units_.
Referenced by container_module::thread_safe_container::to_json(), container_module::variant_value::to_json(), and container_module::variant_value::to_string().
to_llong()
virtual long long container_module::value::to_llong (void) const inline virtual
Reimplemented in container_module::numeric_value< T, TypeTag >.
Definition at line 164 of file value.h.
to_long()
virtual long container_module::value::to_long (void) const inline virtual
Reimplemented in container_module::container_value, and container_module::numeric_value< T, TypeTag >.
Definition at line 156 of file value.h.
to_short()
virtual short container_module::value::to_short (void) const inline virtual
Reimplemented in container_module::numeric_value< T, TypeTag >.
Definition at line 140 of file value.h.
Referenced by container_module::container_value::add().
to_string()
virtual std::string container_module::value::to_string (const bool & original = true) const inline virtual
Reimplemented in container_module::bool_value, container_module::bytes_value, container_module::container_value, container_module::numeric_value< T, TypeTag >, and container_module::string_value.
Definition at line 180 of file value.h.
References container_module::null_value, and type_.
Referenced by data(), demonstrate_value_access(), serialize(), to_json(), and to_xml().
to_uint()
virtual unsigned int container_module::value::to_uint (void) const inline virtual
Reimplemented in container_module::numeric_value< T, TypeTag >.
Definition at line 152 of file value.h.
to_ullong()
virtual unsigned long long container_module::value::to_ullong (void) const inline virtual
Reimplemented in container_module::numeric_value< T, TypeTag >.
Definition at line 168 of file value.h.
to_ulong()
virtual unsigned long container_module::value::to_ulong (void) const inline virtual
Reimplemented in container_module::numeric_value< T, TypeTag >.
Definition at line 160 of file value.h.
to_ushort()
virtual unsigned short container_module::value::to_ushort (void) const inline virtual
Reimplemented in container_module::numeric_value< T, TypeTag >.
Definition at line 144 of file value.h.
to_xml()
const std::string container_module::value::to_xml ()
Definition at line 295 of file value.cpp.
References kcenon::thread::utils::formatter::format_to(), name_, to_string(), and units_.
type()
value_types container_module::value::type () const
Definition at line 205 of file value.cpp.
References type_.
Referenced by container_module::container_value::add(), demonstrate_value_access(), value(), and value().
value_array()
std::vector< std::shared_ptr< value > > container_module::value::value_array (std::string_view key)
Definition at line 240 of file value.cpp.
References units_.
Friends And Related Symbol Documentation
operator<< [1/3]
std::ostream & operator<< (std::ostream & out, std::shared_ptr< value > other) friend
Definition at line 376 of file value.cpp.
operator<< [2/3]
std::shared_ptr< value > operator<< (std::shared_ptr< value > container, std::shared_ptr< value > other) friend
Definition at line 357 of file value.cpp.
operator<< [3/3]
std::string & operator<< (std::string & out, std::shared_ptr< value > other) friend
Definition at line 382 of file value.cpp.
Member Data Documentation
data_
std::vector<uint8_t> container_module::value::data_ protected
Definition at line 269 of file value.h.
Referenced by container_module::bytes_value::bytes_value(), container_module::bytes_value::bytes_value(), set_byte_string(), set_data(), set_data(), set_data(), set_string(), size(), container_module::string_value::string_value(), container_module::bool_value::to_boolean(), to_bytes(), container_module::container_value::to_long(), container_module::bytes_value::to_string(), container_module::string_value::to_string(), and value().
data_type_map_
std::map<value_types, std::function<void(const std::string&)> > container_module::value::data_type_map_ protected
Definition at line 274 of file value.h.
Referenced by set_data(), and value().
name_
std::string container_module::value::name_ protected
Definition at line 268 of file value.h.
Referenced by container_module::bool_value::bool_value(), container_module::bool_value::bool_value(), container_module::bytes_value::bytes_value(), container_module::bytes_value::bytes_value(), container_module::container_value::container_value(), container_module::container_value::container_value(), name(), serialize(), set_data(), container_module::string_value::string_value(), to_json(), to_xml(), value(), value(), and value().
parent_
std::weak_ptr<value> container_module::value::parent_ protected
Definition at line 270 of file value.h.
Referenced by parent(), set_parent(), and value().
size_
size_t container_module::value::size_ protected
Definition at line 266 of file value.h.
Referenced by container_module::bytes_value::bytes_value(), container_module::bytes_value::bytes_value(), container_module::bytes_value::bytes_value(), operator=(), set_byte_string(), set_data(), set_data(), set_data(), set_string(), container_module::string_value::string_value(), container_module::string_value::string_value(), and value().
type_
value_types container_module::value::type_ protected
Definition at line 267 of file value.h.
Referenced by container_module::bool_value::bool_value(), container_module::bool_value::bool_value(), container_module::bool_value::bool_value(), container_module::bytes_value::bytes_value(), container_module::container_value::container_value(), data(), is_boolean(), is_bytes(), is_container(), is_null(), is_numeric(), is_string(), safe_convert(), serialize(), set_boolean(), set_byte_string(), set_data(), set_data(), set_double(), set_float(), set_int(), set_llong(), set_long(), set_short(), set_string(), set_uint(), set_ullong(), set_ulong(), set_ushort(), container_module::string_value::string_value(), to_json(), to_string(), type(), and value().
units_
std::vector<std::shared_ptr<value> > container_module::value::units_ protected
Definition at line 271 of file value.h.
Referenced by container_module::container_value::add(), container_module::container_value::add(), container_module::container_value::add(), child_count(), children(), container_module::container_value::container_value(), container_module::container_value::remove(), container_module::container_value::remove(), container_module::container_value::remove_all(), serialize(), to_json(), to_xml(), value(), value(), value_array(), and container_module::container_value::~container_value().
The documentation for this class was generated from the following files:
libraries/container_system/core/value.h
libraries/container_system/core/value.cpp