Messaging System: libraries/logger_system/tests/unit/config_test/strategy_test.cpp File Reference
strategy_test.cpp File Reference
#include <gtest/gtest.h>
#include "../../sources/logger/config/config_strategy_interface.h"
#include "../../sources/logger/config/logger_builder.h"
#include "../../sources/logger/writers/console_writer.h"
#include <chrono>
#include <cstdlib>
Classes
class ConfigStrategyTest
Functions
TEST_F (ConfigStrategyTest, TemplateStrategy_HighPerformance)
TEST_F (ConfigStrategyTest, TemplateStrategy_LowLatency)
TEST_F (ConfigStrategyTest, TemplateStrategy_Debug)
TEST_F (ConfigStrategyTest, TemplateStrategy_Production)
TEST_F (ConfigStrategyTest, EnvironmentStrategy_Development)
TEST_F (ConfigStrategyTest, EnvironmentStrategy_Testing)
TEST_F (ConfigStrategyTest, EnvironmentStrategy_Staging)
TEST_F (ConfigStrategyTest, PerformanceTuning_Conservative)
TEST_F (ConfigStrategyTest, PerformanceTuning_Balanced)
TEST_F (ConfigStrategyTest, PerformanceTuning_Aggressive)
TEST_F (ConfigStrategyTest, PerformanceTuning_RequiresAsync)
TEST_F (ConfigStrategyTest, CompositeStrategy_Multiple)
TEST_F (ConfigStrategyTest, Factory_CreateTemplate)
TEST_F (ConfigStrategyTest, Factory_CreateEnvironment)
TEST_F (ConfigStrategyTest, Factory_CreateTuning)
TEST_F (ConfigStrategyTest, Factory_FromEnvironment)
TEST_F (ConfigStrategyTest, Builder_UseTemplate)
TEST_F (ConfigStrategyTest, Builder_ApplyStrategy)
TEST_F (ConfigStrategyTest, Builder_ForEnvironment)
TEST_F (ConfigStrategyTest, Builder_WithPerformanceTuning)
TEST_F (ConfigStrategyTest, Builder_AutoConfigure)
TEST_F (ConfigStrategyTest, Builder_ClearStrategies)
TEST_F (ConfigStrategyTest, Builder_ChainedStrategies)
TEST_F (ConfigStrategyTest, Builder_BackwardCompatibility)
TEST_F (ConfigStrategyTest, Strategy_InvalidConfiguration)
Function Documentation
TEST_F() [1/25]
TEST_F (ConfigStrategyTest , Builder_ApplyStrategy)
Definition at line 311 of file strategy_test.cpp.
References kcenon::logger::logger_builder::apply_strategy(), and kcenon::logger::logger_builder::build().
TEST_F() [2/25]
TEST_F (ConfigStrategyTest , Builder_AutoConfigure)
Definition at line 340 of file strategy_test.cpp.
References kcenon::logger::logger_builder::auto_configure(), and kcenon::logger::logger_builder::build().
TEST_F() [3/25]
TEST_F (ConfigStrategyTest , Builder_BackwardCompatibility)
Definition at line 374 of file strategy_test.cpp.
References kcenon::logger::logger_builder::build(), and kcenon::logger::logger_builder::use_template().
TEST_F() [4/25]
TEST_F (ConfigStrategyTest , Builder_ChainedStrategies)
Definition at line 360 of file strategy_test.cpp.
References kcenon::logger::logger_builder::build(), kcenon::logger::logger_builder::for_environment(), kcenon::logger::logger_builder::use_template(), and kcenon::logger::logger_builder::with_performance_tuning().
TEST_F() [5/25]
TEST_F (ConfigStrategyTest , Builder_ClearStrategies)
Definition at line 350 of file strategy_test.cpp.
References kcenon::logger::logger_builder::build(), kcenon::logger::logger_builder::clear_strategies(), kcenon::logger::logger_builder::for_environment(), and kcenon::logger::logger_builder::use_template().
TEST_F() [6/25]
TEST_F (ConfigStrategyTest , Builder_ForEnvironment)
Definition at line 323 of file strategy_test.cpp.
References kcenon::logger::logger_builder::build(), and kcenon::logger::logger_builder::for_environment().
TEST_F() [7/25]
TEST_F (ConfigStrategyTest , Builder_UseTemplate)
Definition at line 301 of file strategy_test.cpp.
References kcenon::logger::logger_builder::get_config(), kcenon::logger::logger_builder::use_template(), and kcenon::logger::logger_builder::validate().
TEST_F() [8/25]
TEST_F (ConfigStrategyTest , Builder_WithPerformanceTuning)
Definition at line 331 of file strategy_test.cpp.
References kcenon::logger::logger_builder::build(), kcenon::logger::logger_builder::with_async(), and kcenon::logger::logger_builder::with_performance_tuning().
TEST_F() [9/25]
TEST_F (ConfigStrategyTest , CompositeStrategy_Multiple)
Definition at line 224 of file strategy_test.cpp.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::buffer_size, and kcenon::logger::logger_config::min_level.
TEST_F() [10/25]
TEST_F (ConfigStrategyTest , EnvironmentStrategy_Development)
Definition at line 99 of file strategy_test.cpp.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::enable_color_output, kcenon::logger::logger_config::enable_metrics, and kcenon::logger::logger_config::min_level.
TEST_F() [11/25]
TEST_F (ConfigStrategyTest , EnvironmentStrategy_Staging)
Definition at line 134 of file strategy_test.cpp.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::enable_crash_handler, kcenon::logger::logger_config::enable_metrics, kcenon::logger::logger_config::enable_structured_logging, and kcenon::logger::logger_config::min_level.
TEST_F() [12/25]
TEST_F (ConfigStrategyTest , EnvironmentStrategy_Testing)
Definition at line 117 of file strategy_test.cpp.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::enable_crash_handler, kcenon::logger::logger_config::enable_metrics, and kcenon::logger::logger_config::min_level.
TEST_F() [13/25]
TEST_F (ConfigStrategyTest , Factory_CreateEnvironment)
Definition at line 256 of file strategy_test.cpp.
TEST_F() [14/25]
TEST_F (ConfigStrategyTest , Factory_CreateTemplate)
Definition at line 247 of file strategy_test.cpp.
TEST_F() [15/25]
TEST_F (ConfigStrategyTest , Factory_CreateTuning)
Definition at line 267 of file strategy_test.cpp.
TEST_F() [16/25]
TEST_F (ConfigStrategyTest , Factory_FromEnvironment)
Definition at line 278 of file strategy_test.cpp.
References logger_system::debug.
TEST_F() [17/25]
TEST_F (ConfigStrategyTest , PerformanceTuning_Aggressive)
Definition at line 190 of file strategy_test.cpp.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::buffer_size, kcenon::logger::logger_config::enable_compression, kcenon::logger::logger_config::max_queue_size, kcenon::logger::logger_config::use_lock_free, and kcenon::logger::logger_config::writer_thread_count.
TEST_F() [18/25]
TEST_F (ConfigStrategyTest , PerformanceTuning_Balanced)
Definition at line 172 of file strategy_test.cpp.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::buffer_size, kcenon::logger::logger_config::max_queue_size, and kcenon::logger::logger_config::writer_thread_count.
TEST_F() [19/25]
TEST_F (ConfigStrategyTest , PerformanceTuning_Conservative)
Definition at line 154 of file strategy_test.cpp.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::buffer_size, kcenon::logger::logger_config::max_queue_size, and kcenon::logger::logger_config::writer_thread_count.
TEST_F() [20/25]
TEST_F (ConfigStrategyTest , PerformanceTuning_RequiresAsync)
Definition at line 210 of file strategy_test.cpp.
References kcenon::logger::logger_config::async.
TEST_F() [21/25]
TEST_F (ConfigStrategyTest , Strategy_InvalidConfiguration)
Definition at line 384 of file strategy_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger_builder::get_config(), kcenon::logger::logger_builder::with_async(), and kcenon::logger::logger_builder::with_performance_tuning().
TEST_F() [22/25]
TEST_F (ConfigStrategyTest , TemplateStrategy_Debug)
Definition at line 66 of file strategy_test.cpp.
References kcenon::logger::logger_config::async, and kcenon::logger::logger_config::min_level.
TEST_F() [23/25]
TEST_F (ConfigStrategyTest , TemplateStrategy_HighPerformance)
Definition at line 34 of file strategy_test.cpp.
References kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::buffer_size, and kcenon::logger::logger_config::use_lock_free.
TEST_F() [24/25]
TEST_F (ConfigStrategyTest , TemplateStrategy_LowLatency)
Definition at line 51 of file strategy_test.cpp.
References kcenon::logger::logger_config::batch_size, and kcenon::logger::logger_config::flush_interval.
TEST_F() [25/25]
TEST_F (ConfigStrategyTest , TemplateStrategy_Production)
Definition at line 81 of file strategy_test.cpp.
References kcenon::logger::logger_config::enable_color_output, kcenon::logger::logger_config::enable_crash_handler, and kcenon::logger::logger_config::enable_metrics.