Messaging System: network_system::compat Namespace Reference
network_system::compat Namespace Reference
Compatibility utilities namespace.
Functions
constexpr bool has_container_support ()
Check if container integration is available.
constexpr bool has_thread_support ()
Check if thread integration is available.
void initialize ()
Initialize network system with default settings.
void shutdown ()
Shutdown network system cleanly.
Detailed Description
Compatibility utilities namespace.
Function Documentation
has_container_support()
constexpr bool network_system::compat::has_container_support () inline constexpr
Check if container integration is available.
Returns
true if container system is integrated
Definition at line 113 of file compatibility.h.
References HAS_CONTAINER_INTEGRATION.
Referenced by demonstrate_integration_features(), test_compatibility_api(), and test_feature_detection().
has_thread_support()
constexpr bool network_system::compat::has_thread_support () inline constexpr
Check if thread integration is available.
Returns
true if thread system is integrated
Definition at line 121 of file compatibility.h.
References HAS_THREAD_INTEGRATION.
Referenced by demonstrate_integration_features(), test_compatibility_api(), and test_feature_detection().
initialize()
void network_system::compat::initialize () inline
Initialize network system with default settings.
Definition at line 128 of file compatibility.h.
References network_system::integration::container_manager::instance(), and network_system::integration::thread_integration_manager::instance().
Referenced by main(), main(), and test_init_shutdown().
shutdown()
void network_system::compat::shutdown () inline
Shutdown network system cleanly.
Definition at line 149 of file compatibility.h.
References network_system::integration::thread_integration_manager::instance().
Referenced by main(), main(), and test_init_shutdown().