Messaging System: monitoring_system::thread_context_manager Class Reference
monitoring_system::thread_context_manager Class Reference
Thread-local context storage (legacy compatibility)
#include <thread_context.h>
Static Public Member Functions
static void set_context (const thread_context_data &context)
static std::optional< thread_context_data > get_context ()
static void clear_context ()
static std::string generate_request_id ()
static std::string generate_correlation_id ()
Detailed Description
Thread-local context storage (legacy compatibility)
Definition at line 96 of file thread_context.h.
Member Function Documentation
clear_context()
void monitoring_system::thread_context_manager::clear_context () static
Definition at line 53 of file thread_context.cpp.
generate_correlation_id()
std::string monitoring_system::thread_context_manager::generate_correlation_id () static
Definition at line 82 of file thread_context.cpp.
Referenced by monitoring_system::span_builder::build(), and monitoring_system::distributed_tracer::tracer_impl::generate_trace_id().
generate_request_id()
std::string monitoring_system::thread_context_manager::generate_request_id () static
Definition at line 71 of file thread_context.cpp.
Referenced by monitoring_system::span_builder::build(), and monitoring_system::distributed_tracer::tracer_impl::generate_span_id().
get_context()
std::optional< thread_context_data > monitoring_system::thread_context_manager::get_context () static
Definition at line 49 of file thread_context.cpp.
set_context()
void monitoring_system::thread_context_manager::set_context (const thread_context_data & context) static
Definition at line 45 of file thread_context.cpp.
The documentation for this class was generated from the following files:
libraries/monitoring_system/include/kcenon/monitoring/context/thread_context.h
libraries/monitoring_system/src/context/thread_context.cpp