Messaging System: kcenon::logger::di::di_container_interface Class Reference
kcenon::logger::di::di_container_interface Class Reference abstract
Interface for dependency injection container.
#include <di_container_interface.h>
Public Member Functions
virtual ~di_container_interface ()=default
virtual void register_service (std::type_index type, std::shared_ptr< void > service)=0
Register a service with the container using type erasure.
virtual std::shared_ptr< void > get_service (std::type_index type)=0
Get a service from the container using type erasure.
virtual bool has_service (std::type_index type) const =0
Check if a service is registered using type erasure.
virtual void clear ()=0
Clear all registered services.
virtual void register_factory (const std::string &name, std::function< std::shared_ptr< void >()> factory)=0
Register a factory function for creating services.
virtual std::shared_ptr< void > get_service (const std::string &name)=0
Get a service by name using factory.
template<typename T >
void register_service (std::shared_ptr< T > service)
Template wrappers for type-safe access.
template<typename T >
std::shared_ptr< T > get_service ()
template<typename T >
bool has_service () const
Detailed Description
Interface for dependency injection container.
Definition at line 19 of file di_container_interface.h.
Constructor & Destructor Documentation
~di_container_interface()
virtual kcenon::logger::di::di_container_interface::~di_container_interface () virtual default
Member Function Documentation
clear()
virtual void kcenon::logger::di::di_container_interface::clear () pure virtual
Clear all registered services.
Implemented in kcenon::logger::di::basic_di_container.
get_service() [1/3]
template<typename T > std::shared_ptr< T > kcenon::logger::di::di_container_interface::get_service () inline
Definition at line 62 of file di_container_interface.h.
References get_service().
Referenced by get_service().
get_service() [2/3]
virtual std::shared_ptr< void > kcenon::logger::di::di_container_interface::get_service (const std::string & name) pure virtual
Get a service by name using factory.
Implemented in kcenon::logger::di::basic_di_container.
get_service() [3/3]
virtual std::shared_ptr< void > kcenon::logger::di::di_container_interface::get_service (std::type_index type) pure virtual
Get a service from the container using type erasure.
Implemented in kcenon::logger::di::basic_di_container.
has_service() [1/2]
template<typename T > bool kcenon::logger::di::di_container_interface::has_service () const inline
Definition at line 68 of file di_container_interface.h.
References has_service().
Referenced by has_service().
has_service() [2/2]
virtual bool kcenon::logger::di::di_container_interface::has_service (std::type_index type) const pure virtual
Check if a service is registered using type erasure.
Implemented in kcenon::logger::di::basic_di_container.
register_factory()
virtual void kcenon::logger::di::di_container_interface::register_factory (const std::string & name, std::function< std::shared_ptr< void >()> factory) pure virtual
Register a factory function for creating services.
Implemented in kcenon::logger::di::basic_di_container.
register_service() [1/2]
template<typename T > void kcenon::logger::di::di_container_interface::register_service (std::shared_ptr< T > service) inline
Template wrappers for type-safe access.
Definition at line 57 of file di_container_interface.h.
References register_service().
register_service() [2/2]
virtual void kcenon::logger::di::di_container_interface::register_service (std::type_index type, std::shared_ptr< void > service) pure virtual
Register a service with the container using type erasure.
Implemented in kcenon::logger::di::basic_di_container.
Referenced by register_service().
The documentation for this class was generated from the following file:
libraries/logger_system/include/kcenon/logger/core/di/di_container_interface.h