Messaging System: typed_thread_pool_module::typed_job_queue_t< job_type > Class Template Reference
typed_thread_pool_module::typed_job_queue_t< job_type > Class Template Reference
A template-based queue that manages jobs with distinct priority levels.
#include <typed_job_queue.h>
Public Member Functions
typed_job_queue_t ()
Constructs an empty priority job queue.
~typed_job_queue_t () override
Destroys the priority job queue and all remaining jobs within it.
auto enqueue (std::unique_ptr< job > &&value) -> result_void override
Enqueues a non-priority (base) job into the queue.
auto enqueue_batch_ref (std::vector< std::unique_ptr< job > > &jobs) -> result_void
Enqueues a batch of jobs into the queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void override
Enqueues a batch of jobs into the queue.
auto enqueue (std::unique_ptr< typed_job_t< job_type > > &&value) -> result_void
Enqueues a priority job into the appropriate priority queue.
template<typename DerivedJob >
requires std::is_base_of_v<typed_job_t<job_type>, DerivedJob>
auto enqueue (std::unique_ptr< DerivedJob > &&value) -> result_void
Enqueues a derived typed job (like callback_typed_job) into the appropriate priority queue.
auto enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > &&jobs) -> result_void
Enqueues a batch of priority jobs into the appropriate priority queues.
auto dequeue () -> result< std::unique_ptr< job > > override
Dequeues the next available job (of any type or priority).
auto dequeue (const std::vector< job_type > &types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types.
auto dequeue (utility_module::span< const job_type > types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types using span.
auto clear () -> void override
Removes all jobs from all priority queues.
auto empty (const std::vector< job_type > &types) const -> bool
Checks if there are no jobs in any of the specified priority queues.
auto empty (utility_module::span< const job_type > types) const -> bool
Checks if there are no jobs in any of the specified priority queues using span.
auto to_string () const -> std::string override
Returns a string representation of the entire priority job queue.
auto stop () -> void
Stops accepting new jobs and marks the queue as stopped.
typed_job_queue_t ()
Constructs an empty priority job queue.
~typed_job_queue_t () override
Destroys the priority job queue and all remaining jobs within it.
auto enqueue (std::unique_ptr< job > &&value) -> result_void override
Enqueues a non-priority (base) job into the queue.
auto enqueue_batch_ref (std::vector< std::unique_ptr< job > > &jobs) -> result_void
Enqueues a batch of jobs into the queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void override
Enqueues a batch of jobs into the queue.
auto enqueue (std::unique_ptr< typed_job_t< job_type > > &&value) -> result_void
Enqueues a priority job into the appropriate priority queue.
template<typename DerivedJob >
requires std::is_base_of_v<typed_job_t<job_type>, DerivedJob>
auto enqueue (std::unique_ptr< DerivedJob > &&value) -> result_void
Enqueues a derived typed job (like callback_typed_job) into the appropriate priority queue.
auto enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > &&jobs) -> result_void
Enqueues a batch of priority jobs into the appropriate priority queues.
auto dequeue () -> result< std::unique_ptr< job > > override
Dequeues the next available job (of any type or priority).
auto dequeue (const std::vector< job_type > &types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types.
auto dequeue (utility_module::span< const job_type > types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types using span.
auto clear () -> void override
Removes all jobs from all priority queues.
auto empty (const std::vector< job_type > &types) const -> bool
Checks if there are no jobs in any of the specified priority queues.
auto empty (utility_module::span< const job_type > types) const -> bool
Checks if there are no jobs in any of the specified priority queues using span.
auto to_string () const -> std::string override
Returns a string representation of the entire priority job queue.
auto stop () -> void
Stops accepting new jobs and marks the queue as stopped.
typed_job_queue_t ()
Constructs an empty priority job queue.
~typed_job_queue_t () override
Destroys the priority job queue and all remaining jobs within it.
auto enqueue (std::unique_ptr< job > &&value) -> result_void override
Enqueues a non-priority (base) job into the queue.
auto enqueue_batch_ref (std::vector< std::unique_ptr< job > > &jobs) -> result_void
Enqueues a batch of jobs into the queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void override
Enqueues a batch of jobs into the queue.
auto enqueue (std::unique_ptr< typed_job_t< job_type > > &&value) -> result_void
Enqueues a priority job into the appropriate priority queue.
template<typename DerivedJob >
requires std::is_base_of_v<typed_job_t<job_type>, DerivedJob>
auto enqueue (std::unique_ptr< DerivedJob > &&value) -> result_void
Enqueues a derived typed job (like callback_typed_job) into the appropriate priority queue.
auto enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > &&jobs) -> result_void
Enqueues a batch of priority jobs into the appropriate priority queues.
auto dequeue () -> result< std::unique_ptr< job > > override
Dequeues the next available job (of any type or priority).
auto dequeue (const std::vector< job_type > &types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types.
auto dequeue (utility_module::span< const job_type > types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types using span.
auto clear () -> void override
Removes all jobs from all priority queues.
auto empty (const std::vector< job_type > &types) const -> bool
Checks if there are no jobs in any of the specified priority queues.
auto empty (utility_module::span< const job_type > types) const -> bool
Checks if there are no jobs in any of the specified priority queues using span.
auto to_string () const -> std::string override
Returns a string representation of the entire priority job queue.
auto stop () -> void
Stops accepting new jobs and marks the queue as stopped.
Public Member Functions inherited from thread_module::job_queue
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
virtual auto dequeue_batch (void) -> std::deque< std::unique_ptr< job > >
Dequeues all remaining jobs from the queue without processing them.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
virtual auto dequeue_batch (void) -> std::deque< std::unique_ptr< job > >
Dequeues all remaining jobs from the queue without processing them.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
virtual auto dequeue_batch (void) -> std::deque< std::unique_ptr< job > >
Dequeues all remaining jobs from the queue without processing them.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
Protected Member Functions
auto empty_check_without_lock (const std::vector< job_type > &types) const -> bool
Checks if the specified priority queues are empty without acquiring any locks.
auto empty_check_without_lock (utility_module::span< const job_type > types) const -> bool
Checks if the specified priority queues are empty without acquiring any locks using span.
auto try_dequeue_from_priority (const job_type &priority) -> std::optional< std::unique_ptr< typed_job_t< job_type > > >
Attempts to dequeue a single job from the queue for a given priority.
auto empty_check_without_lock (const std::vector< job_type > &types) const -> bool
Checks if the specified priority queues are empty without acquiring any locks.
auto empty_check_without_lock (utility_module::span< const job_type > types) const -> bool
Checks if the specified priority queues are empty without acquiring any locks using span.
auto try_dequeue_from_priority (const job_type &priority) -> std::optional< std::unique_ptr< typed_job_t< job_type > > >
Attempts to dequeue a single job from the queue for a given priority.
auto empty_check_without_lock (const std::vector< job_type > &types) const -> bool
Checks if the specified priority queues are empty without acquiring any locks.
auto empty_check_without_lock (utility_module::span< const job_type > types) const -> bool
Checks if the specified priority queues are empty without acquiring any locks using span.
auto try_dequeue_from_priority (const job_type &priority) -> std::optional< std::unique_ptr< typed_job_t< job_type > > >
Attempts to dequeue a single job from the queue for a given priority.
Additional Inherited Members
Protected Attributes inherited from thread_module::job_queue
std::atomic_bool notify_
If true, threads waiting for new jobs are notified when a new job is enqueued.
std::atomic_bool stop_
Indicates whether the queue has been signaled to stop.
std::mutex mutex_
Mutex to protect access to the underlying queue_ container and related state.
std::condition_variable condition_
Condition variable used to signal worker threads.
Detailed Description
template<typename job_type = job_types>
class typed_thread_pool_module::typed_job_queue_t< job_type >
A template-based queue that manages jobs with distinct priority levels.
This class inherits from job_queue and provides functionality to enqueue and dequeue priority-based jobs. Internally, it maintains multiple queues (one per priority level) and tracks their sizes.
Template Parameters
job_type The type used to represent job priority levels. Defaults to job_types.
Definition at line 63 of file typed_job_queue.h.
Constructor & Destructor Documentation
typed_job_queue_t() [1/3]
template<typename job_type = job_types> typed_thread_pool_module::typed_job_queue_t< job_type >::typed_job_queue_t ()
Constructs an empty priority job queue.
~typed_job_queue_t() [1/3]
template<typename job_type = job_types> typed_thread_pool_module::typed_job_queue_t< job_type >::~typed_job_queue_t () override
Destroys the priority job queue and all remaining jobs within it.
typed_job_queue_t() [2/3]
template<typename job_type = job_types> typed_thread_pool_module::typed_job_queue_t< job_type >::typed_job_queue_t ()
Constructs an empty priority job queue.
~typed_job_queue_t() [2/3]
template<typename job_type = job_types> typed_thread_pool_module::typed_job_queue_t< job_type >::~typed_job_queue_t () override
Destroys the priority job queue and all remaining jobs within it.
typed_job_queue_t() [3/3]
template<typename job_type = job_types> typed_thread_pool_module::typed_job_queue_t< job_type >::typed_job_queue_t ()
Constructs an empty priority job queue.
~typed_job_queue_t() [3/3]
template<typename job_type = job_types> typed_thread_pool_module::typed_job_queue_t< job_type >::~typed_job_queue_t () override
Destroys the priority job queue and all remaining jobs within it.
Member Function Documentation
clear() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::clear () -> void override virtual
Removes all jobs from all priority queues.
After this call, the queue will be empty for every priority level.
Reimplemented from thread_module::job_queue.
clear() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::clear () -> void override virtual
Removes all jobs from all priority queues.
After this call, the queue will be empty for every priority level.
Reimplemented from thread_module::job_queue.
clear() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::clear () -> void override virtual
Removes all jobs from all priority queues.
After this call, the queue will be empty for every priority level.
Reimplemented from thread_module::job_queue.
dequeue() [1/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue () -> result< std::unique_ptr< job > > override virtual
Dequeues the next available job (of any type or priority).
This method attempts to dequeue from the front of any internal priority queue that may contain a job, typically checking in an unspecified priority order.
Returns
A result<std::unique_ptr<job>> containing either the dequeued job or an error.
Reimplemented from thread_module::job_queue.
Referenced by basic_typed_queue_example(), BM_TypedJobQueue_EnqueueDequeue(), BM_TypedJobQueue_HighContention(), BM_TypedJobQueue_MemoryUsage(), mpmc_typed_queue_example(), performance_comparison_example(), stress_test_example(), and task_scheduling_example().
dequeue() [2/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue () -> result< std::unique_ptr< job > > override virtual
Dequeues the next available job (of any type or priority).
This method attempts to dequeue from the front of any internal priority queue that may contain a job, typically checking in an unspecified priority order.
Returns
A result<std::unique_ptr<job>> containing either the dequeued job or an error.
Reimplemented from thread_module::job_queue.
dequeue() [3/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue () -> result< std::unique_ptr< job > > override virtual
Dequeues the next available job (of any type or priority).
This method attempts to dequeue from the front of any internal priority queue that may contain a job, typically checking in an unspecified priority order.
Returns
A result<std::unique_ptr<job>> containing either the dequeued job or an error.
Reimplemented from thread_module::job_queue.
dequeue() [4/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue (const std::vector< job_type > & types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types.
This method checks the queues corresponding to the given priority levels in an implementation-defined sequence and removes the first job found.
Parameters
types A list of priority levels from which to attempt a dequeue.
Returns
A result<std::unique_ptr<typed_job_t<job_type>>> containing either the dequeued job or an error.
dequeue() [5/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue (const std::vector< job_type > & types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types.
This method checks the queues corresponding to the given priority levels in an implementation-defined sequence and removes the first job found.
Parameters
types A list of priority levels from which to attempt a dequeue.
Returns
A result<std::unique_ptr<typed_job_t<job_type>>> containing either the dequeued job or an error.
dequeue() [6/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue (const std::vector< job_type > & types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types.
This method checks the queues corresponding to the given priority levels in an implementation-defined sequence and removes the first job found.
Parameters
types A list of priority levels from which to attempt a dequeue.
Returns
A result<std::unique_ptr<typed_job_t<job_type>>> containing either the dequeued job or an error.
dequeue() [7/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue (utility_module::span< const job_type > types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types using span.
This method checks the queues corresponding to the given priority levels in an implementation-defined sequence and removes the first job found. This overload accepts a span to avoid copying the types collection.
Parameters
types A span of priority levels from which to attempt a dequeue.
Returns
A result<std::unique_ptr<typed_job_t<job_type>>> containing either the dequeued job or an error.
dequeue() [8/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue (utility_module::span< const job_type > types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types using span.
This method checks the queues corresponding to the given priority levels in an implementation-defined sequence and removes the first job found. This overload accepts a span to avoid copying the types collection.
Parameters
types A span of priority levels from which to attempt a dequeue.
Returns
A result<std::unique_ptr<typed_job_t<job_type>>> containing either the dequeued job or an error.
dequeue() [9/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::dequeue (utility_module::span< const job_type > types) -> result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job with one of the specified types using span.
This method checks the queues corresponding to the given priority levels in an implementation-defined sequence and removes the first job found. This overload accepts a span to avoid copying the types collection.
Parameters
types A span of priority levels from which to attempt a dequeue.
Returns
A result<std::unique_ptr<typed_job_t<job_type>>> containing either the dequeued job or an error.
empty() [1/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty (const std::vector< job_type > & types) const -> bool
Checks if there are no jobs in any of the specified priority queues.
Parameters
types A list of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
Referenced by BM_TypedJobQueue_MemoryUsage().
empty() [2/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty (const std::vector< job_type > & types) const -> bool
Checks if there are no jobs in any of the specified priority queues.
Parameters
types A list of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty() [3/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty (const std::vector< job_type > & types) const -> bool
Checks if there are no jobs in any of the specified priority queues.
Parameters
types A list of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty() [4/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty (utility_module::span< const job_type > types) const -> bool
Checks if there are no jobs in any of the specified priority queues using span.
Parameters
types A span of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty() [5/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty (utility_module::span< const job_type > types) const -> bool
Checks if there are no jobs in any of the specified priority queues using span.
Parameters
types A span of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty() [6/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty (utility_module::span< const job_type > types) const -> bool
Checks if there are no jobs in any of the specified priority queues using span.
Parameters
types A span of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty_check_without_lock() [1/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty_check_without_lock (const std::vector< job_type > & types) const -> bool protected
Checks if the specified priority queues are empty without acquiring any locks.
This function is intended for internal use, where external locking is expected to be handled by the caller.
Parameters
types A list of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty_check_without_lock() [2/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty_check_without_lock (const std::vector< job_type > & types) const -> bool protected
Checks if the specified priority queues are empty without acquiring any locks.
This function is intended for internal use, where external locking is expected to be handled by the caller.
Parameters
types A list of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty_check_without_lock() [3/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty_check_without_lock (const std::vector< job_type > & types) const -> bool protected
Checks if the specified priority queues are empty without acquiring any locks.
This function is intended for internal use, where external locking is expected to be handled by the caller.
Parameters
types A list of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty_check_without_lock() [4/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty_check_without_lock (utility_module::span< const job_type > types) const -> bool protected
Checks if the specified priority queues are empty without acquiring any locks using span.
This function is intended for internal use, where external locking is expected to be handled by the caller.
Parameters
types A span of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty_check_without_lock() [5/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty_check_without_lock (utility_module::span< const job_type > types) const -> bool protected
Checks if the specified priority queues are empty without acquiring any locks using span.
This function is intended for internal use, where external locking is expected to be handled by the caller.
Parameters
types A span of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
empty_check_without_lock() [6/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::empty_check_without_lock (utility_module::span< const job_type > types) const -> bool protected
Checks if the specified priority queues are empty without acquiring any locks using span.
This function is intended for internal use, where external locking is expected to be handled by the caller.
Parameters
types A span of priority levels to check.
Returns
true if all specified priority queues are empty, otherwise false.
enqueue() [1/9]
template<typename job_type = job_types> template<typename DerivedJob > requires std::is_base_of_v<typed_job_t<job_type>, DerivedJob> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue (std::unique_ptr< DerivedJob > && value) -> result_void inline
Enqueues a derived typed job (like callback_typed_job) into the appropriate priority queue.
Template Parameters
DerivedJob A type that derives from typed_job_t<job_type>
Parameters
value A unique pointer to the derived job to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
Definition at line 124 of file typed_job_queue.h.
References typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue().
enqueue() [2/9]
template<typename job_type = job_types> template<typename DerivedJob > requires std::is_base_of_v<typed_job_t<job_type>, DerivedJob> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue (std::unique_ptr< DerivedJob > && value) -> result_void inline
Enqueues a derived typed job (like callback_typed_job) into the appropriate priority queue.
Template Parameters
DerivedJob A type that derives from typed_job_t<job_type>
Parameters
value A unique pointer to the derived job to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
Definition at line 124 of file typed_job_queue.h.
References typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue().
enqueue() [3/9]
template<typename job_type = job_types> template<typename DerivedJob > requires std::is_base_of_v<typed_job_t<job_type>, DerivedJob> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue (std::unique_ptr< DerivedJob > && value) -> result_void inline
Enqueues a derived typed job (like callback_typed_job) into the appropriate priority queue.
Template Parameters
DerivedJob A type that derives from typed_job_t<job_type>
Parameters
value A unique pointer to the derived job to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
Definition at line 124 of file typed_job_queue.h.
References typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue().
enqueue() [4/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue (std::unique_ptr< job > && value) -> result_void override virtual
Enqueues a non-priority (base) job into the queue.
This function accepts a std::unique_ptr<job> which does not carry specific priority information. Typically, these jobs may be handled in a default or low-priority manner, depending on the implementation.
Parameters
value A unique pointer to the base job to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
Reimplemented from thread_module::job_queue.
Referenced by basic_typed_queue_example(), BM_TypedJobQueue_Enqueue(), BM_TypedJobQueue_EnqueueDequeue(), BM_TypedJobQueue_HighContention(), BM_TypedJobQueue_MemoryUsage(), typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue(), mpmc_typed_queue_example(), performance_comparison_example(), stress_test_example(), and task_scheduling_example().
enqueue() [5/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue (std::unique_ptr< job > && value) -> result_void override virtual
Enqueues a non-priority (base) job into the queue.
This function accepts a std::unique_ptr<job> which does not carry specific priority information. Typically, these jobs may be handled in a default or low-priority manner, depending on the implementation.
Parameters
value A unique pointer to the base job to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
Reimplemented from thread_module::job_queue.
enqueue() [6/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue (std::unique_ptr< job > && value) -> result_void override virtual
Enqueues a non-priority (base) job into the queue.
This function accepts a std::unique_ptr<job> which does not carry specific priority information. Typically, these jobs may be handled in a default or low-priority manner, depending on the implementation.
Parameters
value A unique pointer to the base job to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
Reimplemented from thread_module::job_queue.
enqueue() [7/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue (std::unique_ptr< typed_job_t< job_type > > && value) -> result_void
Enqueues a priority job into the appropriate priority queue.
Parameters
value A unique pointer to the priority job to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
enqueue() [8/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue (std::unique_ptr< typed_job_t< job_type > > && value) -> result_void
Enqueues a priority job into the appropriate priority queue.
Parameters
value A unique pointer to the priority job to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
enqueue() [9/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue (std::unique_ptr< typed_job_t< job_type > > && value) -> result_void
Enqueues a priority job into the appropriate priority queue.
Parameters
value A unique pointer to the priority job to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
enqueue_batch() [1/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void override virtual
Enqueues a batch of jobs into the queue.
Adds multiple jobs to the queue in a single operation.
Parameters
jobs A vector of unique pointers to the jobs being added.
Returns
A result_void indicating success or an error message.
Implementation details:
Validates queue state and input before any modifications
Pre-validates all jobs to ensure atomicity (all or nothing)
Uses single lock acquisition for entire batch (better performance)
Moves all jobs efficiently without copying
Only notifies once after all jobs are added (avoids notification spam)
Performance Benefits:
Single mutex acquisition vs multiple for individual enqueues
Single notification vs notification per job
Reduced contention for high-throughput scenarios
Atomicity:
Either all jobs are added or none are (on validation failure)
No partial batches in case of null job detection
Parameters
jobs Vector of unique pointers to jobs (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented from thread_module::job_queue.
Referenced by BM_TypedJobQueue_BatchEnqueue().
enqueue_batch() [2/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void override virtual
Enqueues a batch of jobs into the queue.
Adds multiple jobs to the queue in a single operation.
Parameters
jobs A vector of unique pointers to the jobs being added.
Returns
A result_void indicating success or an error message.
Implementation details:
Validates queue state and input before any modifications
Pre-validates all jobs to ensure atomicity (all or nothing)
Uses single lock acquisition for entire batch (better performance)
Moves all jobs efficiently without copying
Only notifies once after all jobs are added (avoids notification spam)
Performance Benefits:
Single mutex acquisition vs multiple for individual enqueues
Single notification vs notification per job
Reduced contention for high-throughput scenarios
Atomicity:
Either all jobs are added or none are (on validation failure)
No partial batches in case of null job detection
Parameters
jobs Vector of unique pointers to jobs (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented from thread_module::job_queue.
enqueue_batch() [3/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void override virtual
Enqueues a batch of jobs into the queue.
Adds multiple jobs to the queue in a single operation.
Parameters
jobs A vector of unique pointers to the jobs being added.
Returns
A result_void indicating success or an error message.
Implementation details:
Validates queue state and input before any modifications
Pre-validates all jobs to ensure atomicity (all or nothing)
Uses single lock acquisition for entire batch (better performance)
Moves all jobs efficiently without copying
Only notifies once after all jobs are added (avoids notification spam)
Performance Benefits:
Single mutex acquisition vs multiple for individual enqueues
Single notification vs notification per job
Reduced contention for high-throughput scenarios
Atomicity:
Either all jobs are added or none are (on validation failure)
No partial batches in case of null job detection
Parameters
jobs Vector of unique pointers to jobs (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented from thread_module::job_queue.
enqueue_batch() [4/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > && jobs) -> result_void
Enqueues a batch of priority jobs into the appropriate priority queues.
This function accepts a vector of unique pointers to priority jobs and enqueues them in an unspecified order. The method returns an error if any job fails to enqueue.
Parameters
jobs A vector of unique pointers to priority jobs to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
enqueue_batch() [5/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > && jobs) -> result_void
Enqueues a batch of priority jobs into the appropriate priority queues.
This function accepts a vector of unique pointers to priority jobs and enqueues them in an unspecified order. The method returns an error if any job fails to enqueue.
Parameters
jobs A vector of unique pointers to priority jobs to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
enqueue_batch() [6/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > && jobs) -> result_void
Enqueues a batch of priority jobs into the appropriate priority queues.
This function accepts a vector of unique pointers to priority jobs and enqueues them in an unspecified order. The method returns an error if any job fails to enqueue.
Parameters
jobs A vector of unique pointers to priority jobs to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
enqueue_batch_ref() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch_ref (std::vector< std::unique_ptr< job > > & jobs) -> result_void
Enqueues a batch of jobs into the queue.
This function accepts a vector of unique pointers to jobs and enqueues them in an unspecified order. The method returns an error if any job fails to enqueue.
Parameters
jobs A vector of unique pointers to jobs to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
enqueue_batch_ref() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch_ref (std::vector< std::unique_ptr< job > > & jobs) -> result_void
Enqueues a batch of jobs into the queue.
This function accepts a vector of unique pointers to jobs and enqueues them in an unspecified order. The method returns an error if any job fails to enqueue.
Parameters
jobs A vector of unique pointers to jobs to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
enqueue_batch_ref() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::enqueue_batch_ref (std::vector< std::unique_ptr< job > > & jobs) -> result_void
Enqueues a batch of jobs into the queue.
This function accepts a vector of unique pointers to jobs and enqueues them in an unspecified order. The method returns an error if any job fails to enqueue.
Parameters
jobs A vector of unique pointers to jobs to enqueue.
Returns
result_void containing an error if the operation fails, or a success value.
stop() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::stop () -> void
Stops accepting new jobs and marks the queue as stopped.
After this method is called, any attempt to enqueue a new job will result in an error until the queue is reset or recreated.
stop() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::stop () -> void
Stops accepting new jobs and marks the queue as stopped.
After this method is called, any attempt to enqueue a new job will result in an error until the queue is reset or recreated.
stop() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::stop () -> void
Stops accepting new jobs and marks the queue as stopped.
After this method is called, any attempt to enqueue a new job will result in an error until the queue is reset or recreated.
to_string() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::to_string () const -> std::string override virtual
Returns a string representation of the entire priority job queue.
The format of the returned string may vary, but typically includes information about the number of jobs and their types.
Returns
A string describing the current state of the queue.
Reimplemented from thread_module::job_queue.
Referenced by fmt::formatter< typed_thread_pool_module::typed_job_queue_t< job_type > >::format(), and typed_thread_pool_module::typed_job_queue_t< job_type >::try_dequeue_from_priority().
to_string() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::to_string () const -> std::string override virtual
Returns a string representation of the entire priority job queue.
The format of the returned string may vary, but typically includes information about the number of jobs and their types.
Returns
A string describing the current state of the queue.
Reimplemented from thread_module::job_queue.
to_string() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::to_string () const -> std::string override virtual
Returns a string representation of the entire priority job queue.
The format of the returned string may vary, but typically includes information about the number of jobs and their types.
Returns
A string describing the current state of the queue.
Reimplemented from thread_module::job_queue.
try_dequeue_from_priority() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::try_dequeue_from_priority (const job_type & priority) -> std::optional< std::unique_ptr< typed_job_t< job_type > > > protected
Attempts to dequeue a single job from the queue for a given priority.
This function is intended for internal use to remove a job from one specific priority level. If no jobs exist at that priority, returns std::nullopt.
Parameters
priority The priority level from which to dequeue.
Returns
std::optional<std::unique_ptr<typed_job_t<job_type>>>
The dequeued priority job, or std::nullopt if the queue for that priority is empty.
try_dequeue_from_priority() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::try_dequeue_from_priority (const job_type & priority) -> std::optional< std::unique_ptr< typed_job_t< job_type > > > protected
Attempts to dequeue a single job from the queue for a given priority.
This function is intended for internal use to remove a job from one specific priority level. If no jobs exist at that priority, returns std::nullopt.
Parameters
priority The priority level from which to dequeue.
Returns
std::optional<std::unique_ptr<typed_job_t<job_type>>>
The dequeued priority job, or std::nullopt if the queue for that priority is empty.
References typed_thread_pool_module::typed_job_queue_t< job_type >::to_string().
try_dequeue_from_priority() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_job_queue_t< job_type >::try_dequeue_from_priority (const job_type & priority) -> std::optional< std::unique_ptr< typed_job_t< job_type > > > protected
Attempts to dequeue a single job from the queue for a given priority.
This function is intended for internal use to remove a job from one specific priority level. If no jobs exist at that priority, returns std::nullopt.
Parameters
priority The priority level from which to dequeue.
Returns
std::optional<std::unique_ptr<typed_job_t<job_type>>>
The dequeued priority job, or std::nullopt if the queue for that priority is empty.
References typed_thread_pool_module::typed_job_queue_t< job_type >::to_string().
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/typed_thread_pool/detail/forward_declarations.h
libraries/thread_system/modular_structure/core/include/thread_system_core/typed_thread_pool/scheduling/typed_job_queue.h
libraries/thread_system/modular_structure/core/src/typed_thread_pool/scheduling/typed_job_queue.h
libraries/thread_system/sources/typed_thread_pool/scheduling/typed_job_queue.h