Messaging System: monitoring_system::scoped_timer Class Reference
monitoring_system::scoped_timer Class Reference
Scoped performance timer.
#include <performance_monitor.h>
Public Member Functions
scoped_timer (performance_profiler *profiler, const std::string &operation_name)
~scoped_timer ()
void mark_failed ()
Mark the operation as failed.
void complete ()
Manually complete the timing.
std::chrono::nanoseconds elapsed () const
Get elapsed time without completing.
Detailed Description
Scoped performance timer.
Definition at line 177 of file performance_monitor.h.
Constructor & Destructor Documentation
scoped_timer()
monitoring_system::scoped_timer::scoped_timer (performance_profiler * profiler, const std::string & operation_name) inline
Definition at line 186 of file performance_monitor.h.
~scoped_timer()
monitoring_system::scoped_timer::~scoped_timer () inline
Definition at line 191 of file performance_monitor.h.
References complete().
Member Function Documentation
complete()
void monitoring_system::scoped_timer::complete () inline
Manually complete the timing.
Definition at line 205 of file performance_monitor.h.
References monitoring_system::performance_profiler::record_sample().
Referenced by ~scoped_timer().
elapsed()
std::chrono::nanoseconds monitoring_system::scoped_timer::elapsed () const inline
Get elapsed time without completing.
Definition at line 223 of file performance_monitor.h.
mark_failed()
void monitoring_system::scoped_timer::mark_failed () inline
Mark the operation as failed.
Definition at line 200 of file performance_monitor.h.
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h