Messaging System: kcenon::logger::async_writer Class Reference
kcenon::logger::async_writer Class Reference
Asynchronous wrapper for log writers.
#include <async_writer.h>
Public Member Functions
async_writer (std::unique_ptr< base_writer > wrapped_writer, std::size_t queue_size=10000)
Constructor.
~async_writer () override
Destructor.
void start ()
Start the async writer thread.
void stop ()
Stop the async writer thread.
result_void write (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write a log message asynchronously.
result_void flush () override
Flush all pending messages.
bool is_healthy () const override
Check if the writer is healthy.
std::string get_name () const override
Get the name of this writer.
void set_use_color (bool use_color) override
Set whether to use color output.
Public Member Functions inherited from kcenon::logger::base_writer
virtual ~base_writer ()=default
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
bool use_color () const
Get current color output setting.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
Additional Inherited Members
Protected Member Functions inherited from kcenon::logger::base_writer
std::string format_log_entry (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (logger_system::log_level level) const
Convert log level to string representation.
std::string level_to_color (logger_system::log_level level) const
Get ANSI color code for the specified log level.
Detailed Description
Asynchronous wrapper for log writers.
This class wraps any base_writer implementation and provides asynchronous writing capabilities using a background thread.
Definition at line 35 of file async_writer.h.
Constructor & Destructor Documentation
async_writer()
kcenon::logger::async_writer::async_writer (std::unique_ptr< base_writer > wrapped_writer, std::size_t queue_size = 10000) inline explicit
Constructor.
Parameters
wrapped_writer The writer to wrap with async functionality
queue_size Maximum queue size for pending messages
Definition at line 42 of file async_writer.h.
~async_writer()
kcenon::logger::async_writer::~async_writer () inline override
Destructor.
Definition at line 55 of file async_writer.h.
References stop().
Member Function Documentation
flush()
result_void kcenon::logger::async_writer::flush () inline override virtual
Flush all pending messages.
Returns
result_void indicating success or error
Implements kcenon::logger::base_writer.
Definition at line 137 of file async_writer.h.
get_name()
std::string kcenon::logger::async_writer::get_name () const inline override virtual
Get the name of this writer.
Returns
Writer name
Implements kcenon::logger::base_writer.
Definition at line 164 of file async_writer.h.
is_healthy()
bool kcenon::logger::async_writer::is_healthy () const inline override virtual
Check if the writer is healthy.
Returns
true if healthy, false otherwise
Reimplemented from kcenon::logger::base_writer.
Definition at line 156 of file async_writer.h.
set_use_color()
void kcenon::logger::async_writer::set_use_color (bool use_color) inline override virtual
Set whether to use color output.
Parameters
use_color Enable/disable color output
Reimplemented from kcenon::logger::base_writer.
Definition at line 172 of file async_writer.h.
References kcenon::logger::base_writer::use_color().
start()
void kcenon::logger::async_writer::start () inline
Start the async writer thread.
Definition at line 62 of file async_writer.h.
stop()
void kcenon::logger::async_writer::stop () inline
Stop the async writer thread.
Definition at line 75 of file async_writer.h.
Referenced by ~async_writer().
write()
result_void kcenon::logger::async_writer::write (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) inline override virtual
Write a log message asynchronously.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
timestamp Timestamp
Returns
result_void indicating success or error
Implements kcenon::logger::base_writer.
Definition at line 105 of file async_writer.h.
References kcenon::logger::make_logger_error(), and kcenon::logger::queue_full.
The documentation for this class was generated from the following file:
libraries/logger_system/include/kcenon/logger/writers/async_writer.h