Messaging System: logger_module::console_writer Class Reference
logger_module::console_writer Class Reference
Console writer that outputs logs to stdout/stderr.
#include <console_writer.h>
Public Member Functions
console_writer (bool use_stderr=false, bool auto_detect_color=true)
Constructor.
~console_writer () override
Destructor.
bool write (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write log entry to console.
void flush () override
Flush console output.
std::string get_name () const override
Get writer name.
void set_use_stderr (bool use_stderr)
Set whether to use stderr for all output.
Public Member Functions inherited from logger_module::base_writer
virtual ~base_writer ()=default
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get color setting.
Additional Inherited Members
Protected Member Functions inherited from logger_module::base_writer
std::string format_log_entry (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
Format a log entry to string.
std::string level_to_string (thread_module::log_level level) const
Convert log level to string.
std::string level_to_color (thread_module::log_level level) const
Get ANSI color code for log level.
Detailed Description
Console writer that outputs logs to stdout/stderr.
Features:
Color support for different log levels (if terminal supports it)
Thread-safe console output
Error levels go to stderr, others to stdout
Definition at line 48 of file console_writer.h.
Constructor & Destructor Documentation
console_writer()
logger_module::console_writer::console_writer (bool use_stderr = false, bool auto_detect_color = true) explicit
Constructor.
Parameters
use_stderr If true, all output goes to stderr (default: false)
auto_detect_color Auto-detect terminal color support (default: true)
Definition at line 47 of file console_writer.cpp.
References logger_module::base_writer::set_use_color().
~console_writer()
logger_module::console_writer::~console_writer () override
Destructor.
Definition at line 54 of file console_writer.cpp.
References flush().
Member Function Documentation
flush()
void logger_module::console_writer::flush () override virtual
Flush console output.
Implements logger_module::base_writer.
Definition at line 85 of file console_writer.cpp.
Referenced by ~console_writer().
get_name()
std::string logger_module::console_writer::get_name () const inline override virtual
Get writer name.
Implements logger_module::base_writer.
Definition at line 80 of file console_writer.h.
set_use_stderr()
void logger_module::console_writer::set_use_stderr (bool use_stderr)
Set whether to use stderr for all output.
Parameters
use_stderr Enable/disable stderr usage
Definition at line 91 of file console_writer.cpp.
write()
bool logger_module::console_writer::write (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write log entry to console.
Implements logger_module::base_writer.
Definition at line 58 of file console_writer.cpp.
References thread_module::error, logger_module::base_writer::format_log_entry(), logger_module::base_writer::level_to_color(), and logger_module::base_writer::use_color().
The documentation for this class was generated from the following files:
libraries/logger_system/sources/logger/writers/console_writer.h
libraries/logger_system/sources/logger/writers/console_writer.cpp