Messaging System: kcenon::thread::crash_handler Class Reference
kcenon::thread::crash_handler Class Reference
Thread-safe crash handler for the entire thread system.
#include <crash_handler.h>
Classes
struct crash_stats
Get crash statistics.
Public Member Functions
void initialize (crash_safety_level level=crash_safety_level::standard, bool enable_core_dumps=false)
Initialize crash handling with specified safety level.
size_t register_crash_callback (const std::string &name, crash_callback callback, int priority=100)
Register a callback to be called during crash handling.
void unregister_crash_callback (size_t registration_id)
Unregister a crash callback.
void register_cleanup (const std::string &name, std::function< void()> cleanup, uint32_t timeout_ms=1000)
Register a resource cleanup function.
void set_crash_log_directory (const std::string &directory)
Set custom crash log directory.
void set_stack_trace_enabled (bool enable)
Enable/disable automatic stack trace generation.
void trigger_crash_handling (const crash_context &context)
Manually trigger crash handling (for testing)
bool is_handling_crash () const
Check if crash handler is currently active.
crash_stats get_stats () const
Static Public Member Functions
static crash_handler & instance ()
Get the global crash handler instance.
Detailed Description
Thread-safe crash handler for the entire thread system.
Provides comprehensive crash safety mechanisms including:
Signal handling (SIGSEGV, SIGABRT, SIGFPE, etc.)
Stack trace generation
Graceful shutdown coordination
Resource cleanup callbacks
Cross-platform crash reporting
Definition at line 56 of file crash_handler.h.
Member Function Documentation
get_stats()
crash_stats kcenon::thread::crash_handler::get_stats () const
References kcenon::thread::priority.
Referenced by main().
initialize()
void kcenon::thread::crash_handler::initialize (crash_safety_level level = crash_safety_level::standard, bool enable_core_dumps = false)
Initialize crash handling with specified safety level.
Parameters
level Safety level to configure
enable_core_dumps Whether to enable core dump generation
Referenced by main().
instance()
static crash_handler & kcenon::thread::crash_handler::instance () static
Get the global crash handler instance.
Returns
Reference to the singleton crash handler
Referenced by main(), and kcenon::thread::scoped_crash_callback::~scoped_crash_callback().
is_handling_crash()
bool kcenon::thread::crash_handler::is_handling_crash () const
Check if crash handler is currently active.
Returns
true if currently handling a crash
register_cleanup()
void kcenon::thread::crash_handler::register_cleanup (const std::string & name, std::function< void()> cleanup, uint32_t timeout_ms = 1000)
Register a resource cleanup function.
Parameters
name Unique name for cleanup
cleanup Function to call for cleanup
timeout_ms Maximum time to wait for cleanup
Referenced by main().
register_crash_callback()
size_t kcenon::thread::crash_handler::register_crash_callback (const std::string & name, crash_callback callback, int priority = 100)
Register a callback to be called during crash handling.
Parameters
name Unique name for the callback
callback Function to call during crash
priority Priority order (lower numbers called first)
Returns
Registration ID for later removal
Referenced by main().
set_crash_log_directory()
void kcenon::thread::crash_handler::set_crash_log_directory (const std::string & directory)
Set custom crash log directory.
Parameters
directory Path to directory for crash logs
Referenced by main().
set_stack_trace_enabled()
void kcenon::thread::crash_handler::set_stack_trace_enabled (bool enable)
Enable/disable automatic stack trace generation.
Parameters
enable Whether to generate stack traces
trigger_crash_handling()
void kcenon::thread::crash_handler::trigger_crash_handling (const crash_context & context)
Manually trigger crash handling (for testing)
Parameters
context Custom crash context
Referenced by main().
unregister_crash_callback()
void kcenon::thread::crash_handler::unregister_crash_callback (size_t registration_id)
Unregister a crash callback.
Parameters
registration_id ID returned from register_crash_callback
Referenced by main(), and kcenon::thread::scoped_crash_callback::~scoped_crash_callback().
The documentation for this class was generated from the following file:
libraries/thread_system/include/kcenon/thread/interfaces/crash_handler.h