Messaging System: application_layer/samples/production_ready_example.cpp File Reference
production_ready_example.cpp File Reference
Production-ready messaging system with signal handling, config, metrics, and error recovery.
#include <kcenon/messaging/integrations/system_integrator.h>
#include <kcenon/messaging/core/config.h>
#include <kcenon/logger/core/logger.h>
#include <kcenon/logger/writers/console_writer.h>
#include <kcenon/logger/writers/rotating_file_writer.h>
#include <iostream>
#include <thread>
#include <chrono>
#include <sstream>
#include <fstream>
#include <csignal>
#include <atomic>
#include <map>
#include <mutex>
#include <condition_variable>
#include <random>
Classes
class metrics_collector
struct metrics_collector::metrics
class config_loader
struct config_loader::app_config
class retry_handler
class health_monitor
Functions
void signal_handler (int signal)
void setup_signal_handlers ()
int main (int argc, char *argv[])
Variables
std::atomic< bool > g_shutdown_requested {false}
std::condition_variable g_shutdown_cv
std::mutex g_shutdown_mutex
Detailed Description
Production-ready messaging system with signal handling, config, metrics, and error recovery.
This example demonstrates production-ready features including:
Signal handling for graceful shutdown (SIGINT, SIGTERM)
Configuration file loading
Error recovery and retry mechanisms
Metric collection and reporting
Health check monitoring
Definition in file production_ready_example.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 376 of file production_ready_example.cpp.
References kcenon::messaging::config::config_builder::build(), kcenon::messaging::core::message_payload::data, kcenon::messaging::config::config_builder::enable_compression(), retry_handler::execute_with_retry(), g_shutdown_cv, g_shutdown_mutex, g_shutdown_requested, metrics_collector::increment_errors(), metrics_collector::increment_received(), config_loader::load_from_file(), kcenon::messaging::core::message::payload, config_loader::save_default_config(), kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), kcenon::messaging::config::config_builder::set_worker_threads(), setup_signal_handlers(), health_monitor::start(), metrics_collector::start(), and kcenon::messaging::core::message_payload::topic.
setup_signal_handlers()
void setup_signal_handlers ()
Definition at line 297 of file production_ready_example.cpp.
References signal_handler().
Referenced by main().
signal_handler()
void signal_handler (int signal)
Definition at line 289 of file production_ready_example.cpp.
References g_shutdown_cv, and g_shutdown_requested.
Referenced by setup_signal_handlers().
Variable Documentation
g_shutdown_cv
std::condition_variable g_shutdown_cv
Definition at line 37 of file production_ready_example.cpp.
Referenced by main(), signal_handler(), health_monitor::start(), and metrics_collector::start().
g_shutdown_mutex
std::mutex g_shutdown_mutex
Definition at line 38 of file production_ready_example.cpp.
Referenced by main(), health_monitor::start(), and metrics_collector::start().
g_shutdown_requested
std::atomic<bool> g_shutdown_requested {false}
Definition at line 36 of file production_ready_example.cpp.
Referenced by main(), and signal_handler().