Messaging System: monitoring_system::service_container_interface Class Reference
monitoring_system::service_container_interface Class Reference
Public Member Functions
virtual ~service_container_interface ()=default
template<typename TInterface >
result< bool > register_factory (std::function< std::shared_ptr< TInterface >()> factory, service_lifetime lifetime)
template<typename TInterface >
result< bool > register_factory (const std::string &name, std::function< std::shared_ptr< TInterface >()> factory, service_lifetime lifetime)
template<typename TInterface >
result< bool > register_singleton (std::shared_ptr< TInterface > instance)
template<typename TInterface >
bool is_registered () const
template<typename TInterface >
bool is_registered (const std::string &name) const
template<typename TInterface >
result< std::shared_ptr< TInterface > > resolve () const
template<typename TInterface >
result< std::shared_ptr< TInterface > > resolve (const std::string &name) const
virtual result< bool > clear ()
virtual std::unique_ptr< service_container_interface > create_scope ()
Detailed Description
Definition at line 72 of file test_di_container.cpp.
Constructor & Destructor Documentation
~service_container_interface()
virtual monitoring_system::service_container_interface::~service_container_interface () virtual default
Member Function Documentation
clear()
virtual result< bool > monitoring_system::service_container_interface::clear () inline virtual
Definition at line 195 of file test_di_container.cpp.
References monitoring_system::make_success().
create_scope()
virtual std::unique_ptr< service_container_interface > monitoring_system::service_container_interface::create_scope () inline virtual
Definition at line 202 of file test_di_container.cpp.
is_registered() [1/2]
template<typename TInterface > bool monitoring_system::service_container_interface::is_registered () const inline
Definition at line 125 of file test_di_container.cpp.
is_registered() [2/2]
template<typename TInterface > bool monitoring_system::service_container_interface::is_registered (const std::string & name) const inline
Definition at line 131 of file test_di_container.cpp.
register_factory() [1/2]
template<typename TInterface > result< bool > monitoring_system::service_container_interface::register_factory (const std::string & name, std::function< std::shared_ptr< TInterface >()> factory, service_lifetime lifetime) inline
Definition at line 103 of file test_di_container.cpp.
References monitoring_system::make_success().
register_factory() [2/2]
template<typename TInterface > result< bool > monitoring_system::service_container_interface::register_factory (std::function< std::shared_ptr< TInterface >()> factory, service_lifetime lifetime) inline
Definition at line 90 of file test_di_container.cpp.
References monitoring_system::make_success().
register_singleton()
template<typename TInterface > result< bool > monitoring_system::service_container_interface::register_singleton (std::shared_ptr< TInterface > instance) inline
Definition at line 117 of file test_di_container.cpp.
References monitoring_system::make_success(), and monitoring_system::singleton.
resolve() [1/2]
template<typename TInterface > result< std::shared_ptr< TInterface > > monitoring_system::service_container_interface::resolve () const inline
Definition at line 137 of file test_di_container.cpp.
References monitoring_system::make_success(), and monitoring_system::singleton.
resolve() [2/2]
template<typename TInterface > result< std::shared_ptr< TInterface > > monitoring_system::service_container_interface::resolve (const std::string & name) const inline
Definition at line 166 of file test_di_container.cpp.
References monitoring_system::make_success(), and monitoring_system::singleton.
The documentation for this class was generated from the following file:
libraries/monitoring_system/tests/test_di_container.cpp