Messaging System: libraries/monitoring_system/samples/basic_monitoring.cpp File Reference
basic_monitoring.cpp File Reference
#include <monitoring/monitoring.h>
#include <iostream>
#include <thread>
#include <chrono>
#include <random>
#include <iomanip>
Classes
class system_metrics_collector
Functions
void print_metrics (const metrics_snapshot &snapshot)
void basic_monitoring_example ()
void manual_metrics_example ()
void historical_data_example ()
void performance_monitoring_example ()
int main ()
Function Documentation
basic_monitoring_example()
void basic_monitoring_example ()
Definition at line 102 of file basic_monitoring.cpp.
References print_metrics().
Referenced by main().
historical_data_example()
void historical_data_example ()
Definition at line 156 of file basic_monitoring.cpp.
Referenced by main().
main()
int main ()
Definition at line 223 of file basic_monitoring.cpp.
References basic_monitoring_example(), historical_data_example(), manual_metrics_example(), and performance_monitoring_example().
manual_metrics_example()
void manual_metrics_example ()
Definition at line 127 of file basic_monitoring.cpp.
References monitoring_interface::system_metrics::active_threads, monitoring_interface::system_metrics::cpu_usage_percent, monitoring_interface::thread_pool_metrics::idle_threads, monitoring_interface::thread_pool_metrics::jobs_completed, monitoring_interface::thread_pool_metrics::jobs_pending, monitoring_interface::worker_metrics::jobs_processed, monitoring_interface::system_metrics::memory_usage_bytes, print_metrics(), monitoring_interface::worker_metrics::total_processing_time_ns, and monitoring_interface::thread_pool_metrics::worker_threads.
Referenced by main().
performance_monitoring_example()
void performance_monitoring_example ()
Definition at line 185 of file basic_monitoring.cpp.
References monitoring_interface::worker_metrics::jobs_processed, print_metrics(), and monitoring_interface::worker_metrics::total_processing_time_ns.
Referenced by main().
print_metrics()
void print_metrics (const metrics_snapshot & snapshot)
Definition at line 72 of file basic_monitoring.cpp.
References monitoring_interface::system_metrics::active_threads, monitoring_interface::system_metrics::cpu_usage_percent, monitoring_interface::thread_pool_metrics::idle_threads, monitoring_interface::thread_pool_metrics::jobs_completed, monitoring_interface::thread_pool_metrics::jobs_pending, monitoring_interface::worker_metrics::jobs_processed, monitoring_interface::system_metrics::memory_usage_bytes, monitoring_interface::metrics_snapshot::system, monitoring_interface::metrics_snapshot::thread_pool, monitoring_interface::worker_metrics::total_processing_time_ns, monitoring_interface::metrics_snapshot::worker, and monitoring_interface::thread_pool_metrics::worker_threads.
Referenced by basic_monitoring_example(), manual_metrics_example(), and performance_monitoring_example().