Messaging System: monitoring_system::moving_window_aggregator< T > Class Template Reference
monitoring_system::moving_window_aggregator< T > Class Template Reference
Sliding window aggregator for time-based statistics.
#include <stream_aggregator.h>
Public Member Functions
moving_window_aggregator (std::chrono::milliseconds duration, size_t max_size)
Constructor.
void add_value (const T &value, std::chrono::system_clock::time_point timestamp=std::chrono::system_clock::now())
Add value to window.
std::vector< T > get_values () const
Get values in window.
size_t size () const
Get window size.
void clear ()
Clear window.
double get_rate_per_second () const
Get rate per second.
Detailed Description
template<typename T>
class monitoring_system::moving_window_aggregator< T >
Sliding window aggregator for time-based statistics.
Definition at line 366 of file stream_aggregator.h.
Constructor & Destructor Documentation
moving_window_aggregator()
template<typename T > monitoring_system::moving_window_aggregator< T >::moving_window_aggregator (std::chrono::milliseconds duration, size_t max_size) inline
Constructor.
Definition at line 401 of file stream_aggregator.h.
Member Function Documentation
add_value()
template<typename T > void monitoring_system::moving_window_aggregator< T >::add_value (const T & value, std::chrono::system_clock::time_point timestamp = std::chrono::system_clock::now()) inline
Add value to window.
Definition at line 407 of file stream_aggregator.h.
Referenced by monitoring_system::stream_aggregator::add_observation(), TEST_F(), and TEST_F().
clear()
template<typename T > void monitoring_system::moving_window_aggregator< T >::clear () inline
Clear window.
Definition at line 441 of file stream_aggregator.h.
Referenced by monitoring_system::stream_aggregator::reset().
get_rate_per_second()
template<typename T > double monitoring_system::moving_window_aggregator< T >::get_rate_per_second () const inline
Get rate per second.
Definition at line 449 of file stream_aggregator.h.
get_values()
template<typename T > std::vector< T > monitoring_system::moving_window_aggregator< T >::get_values () const inline
Get values in window.
Definition at line 418 of file stream_aggregator.h.
Referenced by TEST_F(), and TEST_F().
size()
template<typename T > size_t monitoring_system::moving_window_aggregator< T >::size () const inline
Get window size.
Definition at line 433 of file stream_aggregator.h.
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/stream_aggregator.h