Messaging System: kcenon::thread::job_queue Class Reference
kcenon::thread::job_queue Class Reference
A thread-safe job queue for managing and dispatching work items.
#include <job_queue.h>
Public Member Functions
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto schedule (std::unique_ptr< job > &&value) -> result_void override
scheduler_interface implementation: schedule a job
auto get_next_job () -> result< std::unique_ptr< job > > override
scheduler_interface implementation: get next job
virtual auto enqueue (std::unique_ptr< job > &&value) -> result_void
Enqueues a new job into the queue.
virtual auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void
Enqueues a batch of jobs into the queue.
virtual auto dequeue (void) -> result< std::unique_ptr< job > >
Dequeues a job from the queue in FIFO order (blocking operation).
virtual auto try_dequeue (void) -> result< std::unique_ptr< job > >
Attempts to dequeue a job from the queue without blocking.
virtual auto dequeue_batch (void) -> std::deque< std::unique_ptr< job > >
Dequeues all remaining jobs from the queue without processing them.
virtual auto clear (void) -> void
Removes all jobs currently in the queue without processing them.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
virtual auto to_string (void) const -> std::string
Returns a string representation of this job_queue.
Public Member Functions inherited from kcenon::thread::scheduler_interface
virtual ~scheduler_interface ()=default
Protected Attributes
std::atomic_bool notify_
If true, threads waiting for new jobs are notified when a new job is enqueued.
std::atomic_bool stop_
Indicates whether the queue has been signaled to stop.
std::mutex mutex_
Mutex to protect access to the underlying queue_ container and related state.
std::condition_variable condition_
Condition variable used to signal worker threads.
Detailed Description
A thread-safe job queue for managing and dispatching work items.
The job_queue class provides a synchronized queue for storing and retrieving job objects (or derived classes). Multiple threads can safely enqueue and dequeue jobs, ensuring proper synchronization and preventing data races.
This class inherits from std::enable_shared_from_this, which allows it to create std::shared_ptr instances referring to itself via get_ptr(). This is often useful when passing a job_queue pointer to jobs themselves or other components that need a safe, shared reference to the queue.
Typical Usage
Create a job_queue instance, typically via std::make_shared.
Enqueue job objects (or derived types) using enqueue().
One or more worker threads repeatedly call dequeue() to retrieve jobs and process them.
Call stop_waiting_dequeue() and possibly clear() to shut down the queue gracefully when all jobs are done or when the system is stopping.
Definition at line 76 of file job_queue.h.
Constructor & Destructor Documentation
job_queue()
kcenon::thread::job_queue::job_queue ()
Constructs a new, empty job_queue.
Constructs a new job_queue with default settings.
Initializes internal synchronization primitives and sets all flags to their default states (e.g., notify_ = false, stop_ = false).
Implementation details:
notify_ starts as true (enables condition variable notifications)
stop_ starts as false (queue is active)
mutex_ and condition_ are default constructed
queue_ is an empty deque ready for job storage
The queue is immediately ready for use after construction.
Definition at line 57 of file job_queue.cpp.
~job_queue()
kcenon::thread::job_queue::~job_queue (void) virtual
Virtual destructor.
Destroys the job_queue.
Cleans up resources used by the job_queue.
Implementation details:
Any remaining jobs in the queue are automatically destroyed
No explicit cleanup needed due to RAII design
Any threads waiting on dequeue() will be unblocked by the stop mechanism
Definition at line 67 of file job_queue.cpp.
Member Function Documentation
clear()
auto kcenon::thread::job_queue::clear (void) -> void virtual
Removes all jobs currently in the queue without processing them.
Removes all jobs from the queue without returning them.
This operation is thread-safe and can be used to discard pending jobs, typically during shutdown or error recovery. It does not affect the stop_ or notify_ flags.
Implementation details:
Discards all jobs immediately (destructors called automatically)
Uses deque::clear() for efficient bulk removal
Notifies all waiting threads since queue is now empty
More efficient than dequeue_batch() when jobs don't need to be processed
Use Cases:
Emergency shutdown (discard pending work)
Queue reset/reinitialization
Error recovery scenarios
Note
Jobs are destroyed immediately, so any cleanup logic in job destructors will run
Reimplemented in kcenon::thread::adaptive_typed_job_queue_t< job_type >, kcenon::thread::typed_job_queue_t< job_type >, kcenon::thread::typed_job_queue_t< job_type >, and kcenon::thread::typed_job_queue_t< job_types >.
Definition at line 370 of file job_queue.cpp.
dequeue()
auto kcenon::thread::job_queue::dequeue (void) -> result<std::unique_ptr<job>> virtual
Dequeues a job from the queue in FIFO order (blocking operation).
Removes and returns the first job from the queue (blocking operation).
Returns
A result<std::unique_ptr<job>> containing either a valid job or an error object.
If the queue is empty, the caller will block until a job becomes available or the queue is stopped. Use try_dequeue() for non-blocking operation.
Implementation details:
Uses unique_lock (required by condition_variable)
Blocks until a job is available OR queue is stopped
Returns error if queue is empty after waking up (indicates stop condition)
Efficiently moves job out of queue (zero-copy transfer)
Automatically unlocks mutex when function exits
Blocking Behavior:
Waits indefinitely until job available or stop requested
Uses condition variable for efficient waiting (no busy polling)
Multiple threads can wait concurrently (fair wake-up via notify_one)
Stop Coordination:
Wakes up when stop_.load() becomes true
Returns error instead of blocking indefinitely during shutdown
Thread Safety:
Safe for concurrent access with other dequeue/enqueue operations
Uses proper synchronization primitives
Returns
Unique pointer to job on success, error if queue empty/stopped
Reimplemented in kcenon::thread::typed_job_queue_t< job_type >, kcenon::thread::typed_job_queue_t< job_type >, kcenon::thread::typed_job_queue_t< job_types >, and kcenon::thread::adaptive_typed_job_queue_t< job_type >.
Definition at line 245 of file job_queue.cpp.
References kcenon::thread::queue_empty.
Referenced by get_next_job(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
dequeue_batch()
auto kcenon::thread::job_queue::dequeue_batch (void) -> std::deque<std::unique_ptr<job>> virtual
Dequeues all remaining jobs from the queue without processing them.
Removes and returns ALL jobs from the queue (non-blocking operation).
Returns
A std::deque of unique_ptr<job> containing all jobs that were in the queue at the time of the call.
Similar to clear(), but returns the dequeued jobs to the caller for potential inspection or manual processing.
Implementation details:
Non-blocking: returns immediately regardless of queue state
Uses efficient swap operation to transfer entire queue contents
Notifies all waiting threads since queue is now empty
Returns empty deque if queue was already empty
Leaves queue in empty state after operation
Performance Characteristics:
O(1) complexity due to swap operation (very efficient)
No copying of job objects (moves ownership)
Single lock acquisition for entire batch
Use Cases:
Shutdown scenarios (drain all pending work)
Batch processing of accumulated jobs
Queue migration between workers
Thread Safety:
Uses scoped_lock for automatic cleanup
notify_all() ensures no threads remain blocked on empty queue
Returns
Deque containing all jobs that were in the queue
Reimplemented in kcenon::thread::adaptive_typed_job_queue_t< job_type >.
Definition at line 337 of file job_queue.cpp.
Referenced by TEST_F().
empty()
auto kcenon::thread::job_queue::empty (void) const -> bool
Checks if the queue is currently empty.
Checks if the queue contains any jobs.
Returns
true if the queue has no pending jobs, false otherwise.
Note
This method is thread-safe.
Implementation details:
Thread-safe read operation using mutex
Snapshot in time (may change immediately after call)
Useful for non-blocking queue state checks
Note
Result may be stale by the time caller uses it in multi-threaded environment
Returns
true if queue has no jobs, false if jobs are present
Definition at line 394 of file job_queue.cpp.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
enqueue()
auto kcenon::thread::job_queue::enqueue (std::unique_ptr< job > && value) -> result_void virtual
Enqueues a new job into the queue.
Adds a single job to the back of the queue.
Parameters
value A unique pointer to the job being added.
Returns
A result_void indicating success or an error message.
This method is thread-safe. If notify_ is set to true, a waiting thread (if any) will be notified upon successful enqueue.
Implementation details:
First checks if queue is stopped to fail fast
Validates that the job pointer is not null
Uses scoped_lock for automatic mutex management
Moves the job into the queue (zero-copy transfer)
Optionally notifies one waiting thread if notifications enabled
Thread Safety:
Uses mutex to protect queue modification
Safe to call concurrently from multiple threads
notify_one() wakes exactly one waiting thread (fair scheduling)
Error Conditions:
Returns error if queue is stopped
Returns error if job is null
Parameters
value Unique pointer to job (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented in kcenon::thread::typed_job_queue_t< job_type >, kcenon::thread::typed_job_queue_t< job_type >, and kcenon::thread::typed_job_queue_t< job_types >.
Definition at line 128 of file job_queue.cpp.
References kcenon::thread::invalid_argument, and kcenon::thread::queue_stopped.
Referenced by BM_MutexQueue_SPSC(), schedule(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
enqueue_batch()
auto kcenon::thread::job_queue::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void virtual
Enqueues a batch of jobs into the queue.
Adds multiple jobs to the queue in a single operation.
Parameters
jobs A vector of unique pointers to the jobs being added.
Returns
A result_void indicating success or an error message.
Implementation details:
Validates queue state and input before any modifications
Pre-validates all jobs to ensure atomicity (all or nothing)
Uses single lock acquisition for entire batch (better performance)
Moves all jobs efficiently without copying
Only notifies once after all jobs are added (avoids notification spam)
Performance Benefits:
Single mutex acquisition vs multiple for individual enqueues
Single notification vs notification per job
Reduced contention for high-throughput scenarios
Atomicity:
Either all jobs are added or none are (on validation failure)
No partial batches in case of null job detection
Parameters
jobs Vector of unique pointers to jobs (moved into queue)
Returns
Empty result on success, error on failure
Reimplemented in kcenon::thread::typed_job_queue_t< job_type >, kcenon::thread::typed_job_queue_t< job_type >, and kcenon::thread::typed_job_queue_t< job_types >.
Definition at line 179 of file job_queue.cpp.
References kcenon::thread::invalid_argument, and kcenon::thread::queue_stopped.
Referenced by TEST(), TEST(), and TEST_F().
get_next_job()
auto kcenon::thread::job_queue::get_next_job () -> result<std::unique_ptr<job>> inline override virtual
scheduler_interface implementation: get next job
Implements kcenon::thread::scheduler_interface.
Definition at line 128 of file job_queue.h.
References dequeue().
Referenced by TEST().
get_ptr()
auto kcenon::thread::job_queue::get_ptr (void) -> std::shared_ptr<job_queue>
Obtains a std::shared_ptr that points to this queue instance.
Returns a shared pointer to this job_queue instance.
Returns
A shared pointer to the current job_queue object.
Because job_queue inherits from std::enable_shared_from_this, calling get_ptr() allows retrieving a shared_ptr<job_queue> from within member functions of job_queue.
Implementation details:
Uses std::enable_shared_from_this to safely create shared_ptr
Required for passing the queue to multiple threads safely
Ensures proper lifetime management of the queue object
Returns
Shared pointer to this job_queue
Definition at line 79 of file job_queue.cpp.
is_stopped()
auto kcenon::thread::job_queue::is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
Checks if the queue has been stopped.
Returns
true if the queue is stopped, false otherwise.
When stopped, worker threads are typically notified to cease waiting for new jobs. New jobs may still be enqueued, but it is up to the system design how they are handled in a stopped state.
Implementation details:
Uses atomic load for thread-safe access
When stopped, dequeue operations will fail instead of blocking
Used to coordinate shutdown between producer and consumer threads
Returns
true if queue is stopped, false if active
Definition at line 91 of file job_queue.cpp.
References stop_.
schedule()
auto kcenon::thread::job_queue::schedule (std::unique_ptr< job > && value) -> result_void inline override virtual
scheduler_interface implementation: schedule a job
Implements kcenon::thread::scheduler_interface.
Definition at line 123 of file job_queue.h.
References enqueue().
Referenced by TEST().
set_notify()
auto kcenon::thread::job_queue::set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
Controls whether enqueue operations notify waiting threads.
Parameters
notify If true, signals that enqueue should notify waiting threads. If false, jobs can still be enqueued, but waiting threads won't be automatically notified.
Implementation details:
Uses atomic store for thread-safe modification
When false, enqueue won't wake up threads waiting in dequeue()
Useful for batch operations to avoid excessive notifications
Default is true (notifications enabled)
Parameters
notify true to enable notifications, false to disable
Definition at line 104 of file job_queue.cpp.
size()
auto kcenon::thread::job_queue::size (void) const -> std::size_t
Returns the current number of jobs in the queue.
Returns
The number of pending jobs.
Note
This method is thread-safe.
Implementation details:
Thread-safe read operation using mutex
Snapshot in time (may change immediately after call)
O(1) operation for std::deque
Note
Result may be stale by the time caller uses it in multi-threaded environment
Returns
Number of jobs currently in the queue
Definition at line 444 of file job_queue.cpp.
Referenced by BM_TypedJobQueue_MemoryUsage(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
stop_waiting_dequeue()
auto kcenon::thread::job_queue::stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
Signals the queue to stop accepting jobs and wake waiting threads.
Sets the stop_ flag to true and notifies any threads that might be blocked in dequeue(). This allows worker threads to exit gracefully rather than remain blocked indefinitely.
Implementation details:
Sets atomic stop flag to prevent new enqueue operations
Wakes all threads waiting in dequeue() operations
Those threads will then return with error instead of blocking
Used for coordinated shutdown of producer-consumer systems
Shutdown Sequence:
Set stop flag (prevents new jobs)
Notify all waiting consumers
Waiting dequeue() calls return with error
Threads can then complete their shutdown process
Thread Safety:
Safe to call from any thread
Idempotent operation (safe to call multiple times)
Definition at line 420 of file job_queue.cpp.
Referenced by TEST().
to_string()
auto kcenon::thread::job_queue::to_string (void) const -> std::string virtual
Returns a string representation of this job_queue.
Provides a string representation of the queue's current state.
Returns
A std::string describing the state of the queue (e.g., size, flags).
Primarily used for logging and debugging. Derived classes may override this to include additional diagnostic information.
Implementation details:
Uses size() method to get current job count
Formats output using the formatter utility
Useful for logging and debugging purposes
Returns
Formatted string showing current job count
Reimplemented in kcenon::thread::adaptive_typed_job_queue_t< job_type >, kcenon::thread::typed_job_queue_t< job_type >, kcenon::thread::typed_job_queue_t< job_type >, and kcenon::thread::typed_job_queue_t< job_types >.
Definition at line 460 of file job_queue.cpp.
References kcenon::thread::utils::formatter::format().
try_dequeue()
auto kcenon::thread::job_queue::try_dequeue (void) -> result<std::unique_ptr<job>> virtual
Attempts to dequeue a job from the queue without blocking.
Attempts to dequeue a job without blocking (non-blocking operation).
Returns
A result<std::unique_ptr<job>> containing either a valid job or an error object.
If the queue is empty, this method returns immediately with an error instead of blocking. This is useful for polling-based consumers.
Implementation details:
Never blocks, returns immediately regardless of queue state
Returns error if queue is empty (vs blocking in dequeue())
Uses scoped_lock for quick queue access and release
Ideal for polling-based consumers or timeout-based operations
Performance Benefits:
No condition variable overhead
No thread blocking/unblocking costs
Suitable for high-frequency polling scenarios
Use Cases:
Non-blocking consumer threads
Timeout-based dequeue operations
Testing scenarios where blocking is undesirable
Returns
Unique pointer to job on success, error if queue empty/stopped
Definition at line 287 of file job_queue.cpp.
References kcenon::thread::queue_empty, and kcenon::thread::queue_stopped.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
condition_
std::condition_variable kcenon::thread::job_queue::condition_ protected
Condition variable used to signal worker threads.
Used in combination with mutex_ to block or notify threads waiting for new jobs.
Definition at line 250 of file job_queue.h.
mutex_
std::mutex kcenon::thread::job_queue::mutex_ mutable protected
Mutex to protect access to the underlying queue_ container and related state.
Any operation that modifies or reads the queue should lock this mutex to ensure thread safety.
Definition at line 242 of file job_queue.h.
notify_
std::atomic_bool kcenon::thread::job_queue::notify_ protected
If true, threads waiting for new jobs are notified when a new job is enqueued.
If false, enqueuing does not automatically trigger a notification.
Definition at line 226 of file job_queue.h.
stop_
std::atomic_bool kcenon::thread::job_queue::stop_ protected
Indicates whether the queue has been signaled to stop.
Setting stop_ to true typically causes waiting threads to unblock and exit their waiting loop.
Definition at line 234 of file job_queue.h.
Referenced by is_stopped().
The documentation for this class was generated from the following files:
libraries/thread_system/include/kcenon/thread/core/job_queue.h
libraries/thread_system/src/core/job_queue.cpp