Messaging System: libraries/monitoring_system/tests/test_integration_e2e.cpp File Reference
test_integration_e2e.cpp File Reference
End-to-end integration tests for the monitoring system.
#include <gtest/gtest.h>
#include <thread>
#include <chrono>
#include <vector>
#include <atomic>
#include <random>
#include <fstream>
#include <filesystem>
#include <monitoring/core/result_types.h>
#include <monitoring/interfaces/monitoring_interface.h>
#include <monitoring/tracing/distributed_tracer.h>
#include <monitoring/performance/performance_monitor.h>
#include <monitoring/adaptive/adaptive_monitor.h>
#include <monitoring/health/health_monitor.h>
#include <monitoring/reliability/circuit_breaker.h>
#include <monitoring/reliability/retry_policy.h>
#include <monitoring/reliability/fault_tolerance_manager.h>
#include <monitoring/export/opentelemetry_adapter.h>
#include <monitoring/export/trace_exporters.h>
#include <monitoring/storage/storage_backends.h>
Classes
class IntegrationE2ETest
Functions
TEST_F (IntegrationE2ETest, StorageBackendIntegration)
Test 1: Storage Backend Integration Multiple backends → Concurrent operations → Data consistency.
TEST_F (IntegrationE2ETest, DistributedTracingE2E)
Test 2: Distributed Tracing End-to-End Span creation → Context propagation → Export.
TEST_F (IntegrationE2ETest, HealthMonitoringWithRecovery)
Test 3: Health Monitoring with Fault Recovery Health checks → Failure detection → Recovery → Verification.
TEST_F (IntegrationE2ETest, PerformanceAdaptiveOptimization)
Test 4: Performance Monitoring with Adaptive Optimization Monitoring → Load detection → Adaptation → Verification.
TEST_F (IntegrationE2ETest, CircuitBreakerAndRetry)
Test 5: Circuit Breaker and Retry Mechanism Failure injection → Circuit breaking → Recovery.
TEST_F (IntegrationE2ETest, ExportPipelineIntegration)
Test 6: Export Pipeline Integration Trace and storage export verification.
TEST_F (IntegrationE2ETest, FullSystemLoadTest)
Test 7: Full System Load Test High volume → All components → Performance verification.
TEST_F (IntegrationE2ETest, CrossComponentIntegration)
Test 8: Cross-Component Integration Multiple components working together.
int main (int argc, char **argv)
Detailed Description
End-to-end integration tests for the monitoring system.
Tests complete workflows and interactions between all major components
Definition in file test_integration_e2e.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 545 of file test_integration_e2e.cpp.
TEST_F() [1/8]
TEST_F (IntegrationE2ETest , CircuitBreakerAndRetry)
Test 5: Circuit Breaker and Retry Mechanism Failure injection → Circuit breaking → Recovery.
Definition at line 293 of file test_integration_e2e.cpp.
TEST_F() [2/8]
TEST_F (IntegrationE2ETest , CrossComponentIntegration)
Test 8: Cross-Component Integration Multiple components working together.
Definition at line 491 of file test_integration_e2e.cpp.
References monitoring_system::metrics_snapshot::add_metric(), and monitoring_system::storage_config::type.
TEST_F() [3/8]
TEST_F (IntegrationE2ETest , DistributedTracingE2E)
Test 2: Distributed Tracing End-to-End Span creation → Context propagation → Export.
Definition at line 133 of file test_integration_e2e.cpp.
References monitoring_system::create_opentelemetry_compatibility_layer().
TEST_F() [4/8]
TEST_F (IntegrationE2ETest , ExportPipelineIntegration)
Test 6: Export Pipeline Integration Trace and storage export verification.
Definition at line 364 of file test_integration_e2e.cpp.
References monitoring_system::monitoring_data::add_metric(), and monitoring_system::create_opentelemetry_compatibility_layer().
TEST_F() [5/8]
TEST_F (IntegrationE2ETest , FullSystemLoadTest)
Test 7: Full System Load Test High volume → All components → Performance verification.
Definition at line 419 of file test_integration_e2e.cpp.
TEST_F() [6/8]
TEST_F (IntegrationE2ETest , HealthMonitoringWithRecovery)
Test 3: Health Monitoring with Fault Recovery Health checks → Failure detection → Recovery → Verification.
Definition at line 179 of file test_integration_e2e.cpp.
References monitoring_system::health_check_result::healthy(), and monitoring_system::health_check_result::unhealthy().
TEST_F() [7/8]
TEST_F (IntegrationE2ETest , PerformanceAdaptiveOptimization)
Test 4: Performance Monitoring with Adaptive Optimization Monitoring → Load detection → Adaptation → Verification.
Definition at line 239 of file test_integration_e2e.cpp.
References monitoring_system::adaptive_config::strategy.
TEST_F() [8/8]
TEST_F (IntegrationE2ETest , StorageBackendIntegration)
Test 1: Storage Backend Integration Multiple backends → Concurrent operations → Data consistency.
Definition at line 61 of file test_integration_e2e.cpp.
References monitoring_system::metrics_snapshot::add_metric(), monitoring_system::storage_config::path, and monitoring_system::storage_config::type.