Messaging System: container_module::value_container Class Reference
container_module::value_container Class Reference
A high-level container for messages, including source/target IDs, message type, and a list of values (similar to a root node).
#include <container.h>
Public Member Functions
value_container ()
Default constructor: sets up a "data_container" type with version "1.0.0.0".
value_container (const std::string &data_string, bool parse_only_header=true)
Construct from a serialized data string.
value_container (const std::vector< uint8_t > &data_array, bool parse_only_header=true)
Construct from a raw byte array.
value_container (const value_container &data_container, bool parse_only_header=true)
Copy constructor from another value_container.
value_container (std::shared_ptr< value_container > data_container, bool parse_only_header=true)
Copy from an existing pointer.
value_container (const std::string &message_type, std::vector< std::shared_ptr< value > > units)
Construct with message type and a set of child units.
value_container (const std::string &target_id, const std::string &target_sub_id, const std::string &message_type, std::vector< std::shared_ptr< value > > units)
Construct with target info and message type, plus child units.
value_container (const std::string &source_id, const std::string &source_sub_id, const std::string &target_id, const std::string &target_sub_id, const std::string &message_type, std::vector< std::shared_ptr< value > > units)
Construct with full header info and child units.
value_container (value_container &&other) noexcept
Move constructor.
value_container & operator= (value_container &&other) noexcept
Move assignment operator.
virtual ~value_container ()
std::shared_ptr< value_container > get_ptr ()
void set_source (std::string_view source_id, std::string_view source_sub_id)
void set_target (std::string_view target_id, std::string_view target_sub_id="")
void set_message_type (std::string_view message_type)
void set_units (const std::vector< std::shared_ptr< value > > &target_values, bool update_immediately=false)
Add or merge multiple child values into this container (the top-level).
void swap_header (void)
Swap source/target IDs in this header.
void clear_value (void)
Clear all stored child values.
std::shared_ptr< value_container > copy (bool containing_values=true)
Create a copy of this container.
std::string source_id (void) const
std::string source_sub_id (void) const
std::string target_id (void) const
std::string target_sub_id (void) const
std::string message_type (void) const
std::shared_ptr< value > add (const value &target_value, bool update_immediately=false)
std::shared_ptr< value > add (std::shared_ptr< value > target_value, bool update_immediately=false)
void remove (std::string_view target_name, bool update_immediately=false)
void remove (std::shared_ptr< value > target_value, bool update_immediately=false)
std::vector< std::shared_ptr< value > > value_array (std::string_view target_name)
Return all child values that match the given name.
std::shared_ptr< value > get_value (std::string_view target_name, unsigned int index=0)
Return the first child value matching the given name, or a new null_value if not found.
void initialize (void)
Reinitialize the entire container to defaults.
std::string serialize (void) const
Serialize this container (header + data).
std::vector< uint8_t > serialize_array (void) const
Serialize to a raw byte array.
bool deserialize (const std::string &data_string, bool parse_only_header=true)
Deserialize from string.
bool deserialize (const std::vector< uint8_t > &data_array, bool parse_only_header=true)
Deserialize from a raw byte array.
const std::string to_xml (void)
Generate an XML representation of this container (header + values).
const std::string to_json (void)
Generate a JSON representation of this container (header + values).
std::string datas (void) const
Returns only the data portion's serialized string, if fully parsed.
void load_packet (const std::string &file_path)
Load from a file path (reads entire file content, then calls deserialize).
void save_packet (const std::string &file_path)
Save to a file path (serialize to bytes, then write to file).
std::vector< std::shared_ptr< value > > operator[] (std::string_view key)
Friends
value_container operator<< (value_container target_container, value &other)
value_container operator<< (value_container target_container, std::shared_ptr< value > other)
std::shared_ptr< value_container > operator<< (std::shared_ptr< value_container > target_container, value &other)
std::shared_ptr< value_container > operator<< (std::shared_ptr< value_container > target_container, std::shared_ptr< value > other)
std::ostream & operator<< (std::ostream &out, value_container &other)
std::ostream & operator<< (std::ostream &out, std::shared_ptr< value_container > other)
std::string & operator<< (std::string &out, value_container &other)
std::string & operator<< (std::string &out, std::shared_ptr< value_container > other)
Detailed Description
A high-level container for messages, including source/target IDs, message type, and a list of values (similar to a root node).
Definition at line 51 of file container.h.
Constructor & Destructor Documentation
value_container() [1/9]
container_module::value_container::value_container ()
Default constructor: sets up a "data_container" type with version "1.0.0.0".
Definition at line 62 of file container.cpp.
References container_module::bool_value, container_module::bytes_value, container_module::container_value, container_module::double_value, container_module::float_value, container_module::int_value, container_module::llong_value, container_module::long_value, container_module::short_value, container_module::string_value, container_module::uint_value, container_module::ullong_value, container_module::ulong_value, and container_module::ushort_value.
value_container() [2/9]
container_module::value_container::value_container (const std::string & data_string, bool parse_only_header = true)
Construct from a serialized data string.
If parse_only_header==true, only parse the header part, delaying value parsing.
Definition at line 189 of file container.cpp.
References deserialize().
value_container() [3/9]
container_module::value_container::value_container (const std::vector< uint8_t > & data_array, bool parse_only_header = true)
Construct from a raw byte array.
If parse_only_header==true, only parse the header part, delaying value parsing.
Definition at line 196 of file container.cpp.
References deserialize().
value_container() [4/9]
container_module::value_container::value_container (const value_container & data_container, bool parse_only_header = true)
Copy constructor from another value_container.
If parse_only_header==true, only parse the header portion of source.
Definition at line 203 of file container.cpp.
References deserialize(), and serialize().
value_container() [5/9]
container_module::value_container::value_container (std::shared_ptr< value_container > data_container, bool parse_only_header = true)
Copy from an existing pointer.
If parse_only_header==true, only parse header.
Definition at line 210 of file container.cpp.
References deserialize().
value_container() [6/9]
container_module::value_container::value_container (const std::string & message_type, std::vector< std::shared_ptr< value > > units)
Construct with message type and a set of child units.
Definition at line 220 of file container.cpp.
References set_message_type().
value_container() [7/9]
container_module::value_container::value_container (const std::string & target_id, const std::string & target_sub_id, const std::string & message_type, std::vector< std::shared_ptr< value > > units)
Construct with target info and message type, plus child units.
Definition at line 234 of file container.cpp.
References set_message_type(), and set_target().
value_container() [8/9]
container_module::value_container::value_container (const std::string & source_id, const std::string & source_sub_id, const std::string & target_id, const std::string & target_sub_id, const std::string & message_type, std::vector< std::shared_ptr< value > > units)
Construct with full header info and child units.
Definition at line 251 of file container.cpp.
References set_message_type(), set_source(), and set_target().
value_container() [9/9]
container_module::value_container::value_container (value_container && other) noexcept
Move constructor.
Definition at line 271 of file container.cpp.
~value_container()
container_module::value_container::~value_container () virtual
Definition at line 312 of file container.cpp.
Member Function Documentation
add() [1/2]
std::shared_ptr< value > container_module::value_container::add (const value & target_value, bool update_immediately = false)
Definition at line 419 of file container.cpp.
References add(), and get_ptr().
Referenced by add(), and BM_NestedContainer_Serialize().
add() [2/2]
std::shared_ptr< value > container_module::value_container::add (std::shared_ptr< value > target_value, bool update_immediately = false)
Definition at line 428 of file container.cpp.
References datas().
clear_value()
void container_module::value_container::clear_value (void)
Clear all stored child values.
Definition at line 371 of file container.cpp.
Referenced by initialize().
copy()
std::shared_ptr< value_container > container_module::value_container::copy (bool containing_values = true)
Create a copy of this container.
If containing_values == false, the returned container only has the header, no child values.
Definition at line 379 of file container.cpp.
References serialize().
datas()
std::string container_module::value_container::datas (void) const
Returns only the data portion's serialized string, if fully parsed.
Definition at line 724 of file container.cpp.
References kcenon::thread::utils::formatter::format_to().
Referenced by add(), remove(), remove(), serialize(), and set_units().
deserialize() [1/2]
bool container_module::value_container::deserialize (const std::string & data_string, bool parse_only_header = true)
Deserialize from string.
If parse_only_header is true, child values are not fully parsed yet.
Definition at line 594 of file container.cpp.
References initialize(), container_module::MESSAGE_TYPE, container_module::MESSAGE_VERSION, container_module::SOURCE_ID, container_module::SOURCE_SUB_ID, container_module::TARGET_ID, and container_module::TARGET_SUB_ID.
Referenced by BM_MessageDeserialization(), deserialize(), value_container(), value_container(), value_container(), and value_container().
deserialize() [2/2]
bool container_module::value_container::deserialize (const std::vector< uint8_t > & data_array, bool parse_only_header = true)
Deserialize from a raw byte array.
If parse_only_header is true, child values are not fully parsed.
Definition at line 632 of file container.cpp.
References deserialize().
get_ptr()
std::shared_ptr< value_container > container_module::value_container::get_ptr ()
Definition at line 314 of file container.cpp.
Referenced by add().
get_value()
std::shared_ptr< value > container_module::value_container::get_value (std::string_view target_name, unsigned int index = 0)
Return the first child value matching the given name, or a new null_value if not found.
Definition at line 523 of file container.cpp.
References value_array().
initialize()
void container_module::value_container::initialize (void)
Reinitialize the entire container to defaults.
Definition at line 540 of file container.cpp.
References clear_value().
Referenced by deserialize().
load_packet()
void container_module::value_container::load_packet (const std::string & file_path)
Load from a file path (reads entire file content, then calls deserialize).
Definition at line 742 of file container.cpp.
message_type()
std::string container_module::value_container::message_type (void) const
Definition at line 413 of file container.cpp.
operator=()
value_container & container_module::value_container::operator= (value_container && other) noexcept
Move assignment operator.
Definition at line 289 of file container.cpp.
operator[]()
std::vector< std::shared_ptr< value > > container_module::value_container::operator[] (std::string_view key)
Definition at line 758 of file container.cpp.
References value_array().
remove() [1/2]
void container_module::value_container::remove (std::shared_ptr< value > target_value, bool update_immediately = false)
Definition at line 482 of file container.cpp.
References datas().
remove() [2/2]
void container_module::value_container::remove (std::string_view target_name, bool update_immediately = false)
Definition at line 453 of file container.cpp.
References datas().
save_packet()
void container_module::value_container::save_packet (const std::string & file_path)
Save to a file path (serialize to bytes, then write to file).
Definition at line 750 of file container.cpp.
serialize()
std::string container_module::value_container::serialize (void) const
Serialize this container (header + data).
Returns
The string form.
Definition at line 552 of file container.cpp.
References datas(), kcenon::thread::utils::formatter::format_to(), container_module::MESSAGE_TYPE, container_module::MESSAGE_VERSION, container_module::SOURCE_ID, container_module::SOURCE_SUB_ID, container_module::TARGET_ID, and container_module::TARGET_SUB_ID.
Referenced by copy(), serialize_array(), and value_container().
serialize_array()
std::vector< uint8_t > container_module::value_container::serialize_array (void) const
Serialize to a raw byte array.
Definition at line 584 of file container.cpp.
References serialize().
set_message_type()
void container_module::value_container::set_message_type (std::string_view message_type)
Definition at line 335 of file container.cpp.
Referenced by value_container(), value_container(), and value_container().
set_source()
void container_module::value_container::set_source (std::string_view source_id, std::string_view source_sub_id)
Definition at line 319 of file container.cpp.
Referenced by value_container().
set_target()
void container_module::value_container::set_target (std::string_view target_id, std::string_view target_sub_id = "")
Definition at line 327 of file container.cpp.
Referenced by value_container(), and value_container().
set_units()
void container_module::value_container::set_units (const std::vector< std::shared_ptr< value > > & target_values, bool update_immediately = false)
Add or merge multiple child values into this container (the top-level).
Definition at line 341 of file container.cpp.
References datas().
source_id()
std::string container_module::value_container::source_id (void) const
Definition at line 391 of file container.cpp.
source_sub_id()
std::string container_module::value_container::source_sub_id (void) const
Definition at line 396 of file container.cpp.
swap_header()
void container_module::value_container::swap_header (void)
Swap source/target IDs in this header.
Definition at line 365 of file container.cpp.
target_id()
std::string container_module::value_container::target_id (void) const
Definition at line 402 of file container.cpp.
target_sub_id()
std::string container_module::value_container::target_sub_id (void) const
Definition at line 407 of file container.cpp.
to_json()
const std::string container_module::value_container::to_json (void)
Generate a JSON representation of this container (header + values).
Definition at line 681 of file container.cpp.
References kcenon::thread::utils::formatter::format_to().
to_xml()
const std::string container_module::value_container::to_xml (void)
Generate an XML representation of this container (header + values).
Definition at line 643 of file container.cpp.
References kcenon::thread::utils::formatter::format_to().
value_array()
std::vector< std::shared_ptr< value > > container_module::value_container::value_array (std::string_view target_name)
Return all child values that match the given name.
Definition at line 503 of file container.cpp.
Referenced by get_value(), and operator[]().
Friends And Related Symbol Documentation
operator<< [1/8]
std::ostream & operator<< (std::ostream & out, std::shared_ptr< value_container > other) friend
Definition at line 796 of file container.cpp.
operator<< [2/8]
std::ostream & operator<< (std::ostream & out, value_container & other) friend
Definition at line 790 of file container.cpp.
operator<< [3/8]
std::shared_ptr< value_container > operator<< (std::shared_ptr< value_container > target_container, std::shared_ptr< value > other) friend
Definition at line 770 of file container.cpp.
operator<< [4/8]
std::shared_ptr< value_container > operator<< (std::shared_ptr< value_container > target_container, value & other) friend
Definition at line 770 of file container.cpp.
operator<< [5/8]
std::string & operator<< (std::string & out, std::shared_ptr< value_container > other) friend
Definition at line 810 of file container.cpp.
operator<< [6/8]
std::string & operator<< (std::string & out, value_container & other) friend
Definition at line 804 of file container.cpp.
operator<< [7/8]
value_container operator<< (value_container target_container, std::shared_ptr< value > other) friend
Definition at line 770 of file container.cpp.
operator<< [8/8]
value_container operator<< (value_container target_container, value & other) friend
Definition at line 764 of file container.cpp.
The documentation for this class was generated from the following files:
libraries/container_system/core/container.h
libraries/container_system/core/container.cpp