Messaging System: monitoring_system::performance_profiler Class Reference
monitoring_system::performance_profiler Class Reference
Performance profiler for code sections.
#include <performance_monitor.h>
Public Member Functions
monitoring_system::result< bool > record_sample (const std::string &operation_name, std::chrono::nanoseconds duration, bool success=true)
Record a performance sample.
monitoring_system::result< performance_metrics > get_metrics (const std::string &operation_name) const
Get performance metrics for an operation.
std::vector< performance_metrics > get_all_metrics () const
Get all performance metrics.
monitoring_system::result< bool > clear_samples (const std::string &operation_name)
Clear samples for an operation.
void clear_all_samples ()
Clear all samples.
void set_enabled (bool enabled)
Enable or disable profiling.
bool is_enabled () const
Check if profiling is enabled.
void set_max_samples (std::size_t max_samples)
Set maximum samples per operation.
Detailed Description
Performance profiler for code sections.
Definition at line 110 of file performance_monitor.h.
Member Function Documentation
clear_all_samples()
void monitoring_system::performance_profiler::clear_all_samples ()
Clear all samples.
Definition at line 219 of file performance_monitor.cpp.
Referenced by PerformanceMonitoringTest::SetUp().
clear_samples()
result< bool > monitoring_system::performance_profiler::clear_samples (const std::string & operation_name)
Clear samples for an operation.
Definition at line 205 of file performance_monitor.cpp.
References monitoring_system::make_success().
get_all_metrics()
std::vector< performance_metrics > monitoring_system::performance_profiler::get_all_metrics () const
Get all performance metrics.
Definition at line 191 of file performance_monitor.cpp.
References get_metrics().
get_metrics()
monitoring_system::result< monitoring_system::performance_metrics > monitoring_system::performance_profiler::get_metrics (const std::string & operation_name) const
Get performance metrics for an operation.
Definition at line 49 of file performance_monitor.cpp.
References monitoring_system::performance_metrics::call_count, monitoring_system::performance_metrics::error_count, monitoring_system::performance_metrics::max_duration, monitoring_system::performance_metrics::mean_duration, monitoring_system::performance_metrics::min_duration, monitoring_system::not_found, and monitoring_system::performance_metrics::operation_name.
Referenced by get_all_metrics(), and monitoring_system::performance_benchmark::run().
is_enabled()
bool monitoring_system::performance_profiler::is_enabled () const inline
Check if profiling is enabled.
Definition at line 164 of file performance_monitor.h.
record_sample()
result< bool > monitoring_system::performance_profiler::record_sample (const std::string & operation_name, std::chrono::nanoseconds duration, bool success = true)
Record a performance sample.
Definition at line 11 of file performance_monitor.cpp.
References monitoring_system::success.
Referenced by monitoring_system::scoped_timer::complete(), and monitoring_system::performance_benchmark::run().
set_enabled()
void monitoring_system::performance_profiler::set_enabled (bool enabled) inline
Enable or disable profiling.
Definition at line 159 of file performance_monitor.h.
Referenced by monitoring_system::performance_monitor::set_enabled().
set_max_samples()
void monitoring_system::performance_profiler::set_max_samples (std::size_t max_samples) inline
Set maximum samples per operation.
Definition at line 169 of file performance_monitor.h.
The documentation for this class was generated from the following files:
libraries/monitoring_system/include/kcenon/monitoring/core/performance_monitor.h
libraries/monitoring_system/src/core/performance_monitor.cpp