Messaging System: monitoring_system::fixed_size_strategy Class Reference
monitoring_system::fixed_size_strategy Class Reference
Fixed size buffering strategy.
#include <buffering_strategy.h>
Public Member Functions
fixed_size_strategy (const buffering_config &config)
result_void add_metric (buffered_metric &&metric) override
Add metric to buffer.
result< std::vector< buffered_metric > > flush () override
Flush buffer contents.
bool should_flush () const override
Check if flush is needed.
size_t size () const override
Get current buffer size.
const buffer_statistics & get_statistics () const override
Get buffer statistics.
void clear () override
Clear buffer.
const buffering_config & get_config () const override
Get configuration.
Public Member Functions inherited from monitoring_system::buffer_strategy_interface
virtual ~buffer_strategy_interface ()=default
Detailed Description
Fixed size buffering strategy.
Definition at line 348 of file buffering_strategy.h.
Constructor & Destructor Documentation
fixed_size_strategy()
monitoring_system::fixed_size_strategy::fixed_size_strategy (const buffering_config & config) inline explicit
Definition at line 422 of file buffering_strategy.h.
References monitoring_system::fixed_size.
Member Function Documentation
add_metric()
result_void monitoring_system::fixed_size_strategy::add_metric (buffered_metric && metric) inline override virtual
Add metric to buffer.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 428 of file buffering_strategy.h.
References monitoring_system::drop_newest.
Referenced by TEST_F(), and TEST_F().
clear()
void monitoring_system::fixed_size_strategy::clear () inline override virtual
Clear buffer.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 500 of file buffering_strategy.h.
flush()
result< std::vector< buffered_metric > > monitoring_system::fixed_size_strategy::flush () inline override virtual
Flush buffer contents.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 453 of file buffering_strategy.h.
References monitoring_system::make_success().
Referenced by TEST_F().
get_config()
const buffering_config & monitoring_system::fixed_size_strategy::get_config () const inline override virtual
Get configuration.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 505 of file buffering_strategy.h.
get_statistics()
const buffer_statistics & monitoring_system::fixed_size_strategy::get_statistics () const inline override virtual
Get buffer statistics.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 496 of file buffering_strategy.h.
Referenced by TEST_F(), and TEST_F().
should_flush()
bool monitoring_system::fixed_size_strategy::should_flush () const inline override virtual
Check if flush is needed.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 476 of file buffering_strategy.h.
References monitoring_system::manual, and monitoring_system::size_threshold.
Referenced by TEST_F().
size()
size_t monitoring_system::fixed_size_strategy::size () const inline override virtual
Get current buffer size.
Implements monitoring_system::buffer_strategy_interface.
Definition at line 491 of file buffering_strategy.h.
Referenced by TEST_F(), and TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/buffering_strategy.h