Messaging System: libraries/thread_system/unittest/thread_base_test/job_queue_error_test.cpp File Reference
job_queue_error_test.cpp File Reference
#include <gtest/gtest.h>
#include <kcenon/thread/core/job_queue.h>
#include <kcenon/thread/core/callback_job.h>
#include <kcenon/thread/core/error_handling.h>
Functions
TEST (job_queue_error, enqueue_null)
TEST (job_queue_error, enqueue_batch_empty)
TEST (job_queue_error, enqueue_batch_contains_null)
TEST (job_queue_error, dequeue_after_stop)
Function Documentation
TEST() [1/4]
TEST (job_queue_error , dequeue_after_stop)
Definition at line 41 of file job_queue_error_test.cpp.
References kcenon::thread::job_queue::dequeue(), and kcenon::thread::job_queue::stop_waiting_dequeue().
TEST() [2/4]
TEST (job_queue_error , enqueue_batch_contains_null)
Definition at line 31 of file job_queue_error_test.cpp.
References kcenon::thread::job_queue::enqueue_batch().
TEST() [3/4]
TEST (job_queue_error , enqueue_batch_empty)
Definition at line 22 of file job_queue_error_test.cpp.
References kcenon::thread::job_queue::enqueue_batch().
TEST() [4/4]
TEST (job_queue_error , enqueue_null)
Definition at line 13 of file job_queue_error_test.cpp.
References kcenon::thread::job_queue::enqueue().