Messaging System: application_layer/python_bindings/messaging_python.cpp File Reference
messaging_python.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/chrono.h>
#include <pybind11/functional.h>
#include <kcenon/messaging/integrations/system_integrator.h>
#include <kcenon/messaging/core/message_types.h>
#include <kcenon/messaging/core/config.h>
Classes
class PyMessageHandler
Functions
core::message_payload dict_to_payload (const std::string &topic, const py::dict &data)
py::dict payload_to_dict (const core::message_payload &payload)
PYBIND11_MODULE (messaging_cpp, m)
Function Documentation
dict_to_payload()
core::message_payload dict_to_payload (const std::string & topic, const py::dict & data)
Definition at line 14 of file messaging_python.cpp.
References kcenon::messaging::core::message_payload::data, and kcenon::messaging::core::message_payload::topic.
Referenced by PYBIND11_MODULE().
payload_to_dict()
py::dict payload_to_dict (const core::message_payload & payload)
Definition at line 41 of file messaging_python.cpp.
References kcenon::messaging::core::message_payload::binary_data, kcenon::messaging::core::message_payload::data, and kcenon::messaging::core::message_payload::topic.
Referenced by PyMessageHandler::operator()(), and PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (messaging_cpp , m)
Definition at line 94 of file messaging_python.cpp.
References kcenon::messaging::integrations::system_integrator::system_health::active_services, kcenon::messaging::integrations::system_integrator::system_health::all_services_healthy, kcenon::messaging::config::config_builder::build(), kcenon::messaging::integrations::system_integrator::check_system_health(), kcenon::messaging::integrations::system_integrator::create_default(), kcenon::messaging::integrations::system_integrator::create_for_environment(), dict_to_payload(), kcenon::messaging::config::config_builder::enable_compression(), kcenon::messaging::config::config_builder::enable_external_logger(), kcenon::messaging::config::config_builder::enable_external_monitoring(), kcenon::messaging::config::config_builder::enable_priority_queue(), kcenon::messaging::config::messaging_config::environment, kcenon::messaging::integrations::system_integrator::initialize(), kcenon::messaging::integrations::system_integrator::is_running(), kcenon::messaging::integrations::system_integrator::system_health::last_check, kcenon::messaging::integrations::system_integrator::system_health::message_bus_healthy, payload_to_dict(), kcenon::messaging::integrations::system_integrator::publish(), kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), kcenon::messaging::config::config_builder::set_system_name(), kcenon::messaging::config::config_builder::set_worker_threads(), kcenon::messaging::integrations::system_integrator::shutdown(), kcenon::messaging::integrations::system_integrator::subscribe(), kcenon::messaging::config::messaging_config::system_name, kcenon::messaging::integrations::system_integrator::system_health::total_messages_processed, and kcenon::messaging::config::messaging_config::version.