Messaging System: performance_comparator Class Reference
performance_comparator Class Reference
Public Member Functions
void add_unoptimized_sample (std::chrono::nanoseconds processing_time, std::size_t memory_usage)
void add_optimized_sample (std::chrono::nanoseconds processing_time, std::size_t memory_usage, const performance_optimizer::optimization_stats &stats)
void print_comparison ()
Detailed Description
Definition at line 78 of file optimization_demo.cpp.
Member Function Documentation
add_optimized_sample()
void performance_comparator::add_optimized_sample (std::chrono::nanoseconds processing_time, std::size_t memory_usage, const performance_optimizer::optimization_stats & stats) inline
Definition at line 86 of file optimization_demo.cpp.
Referenced by main().
add_unoptimized_sample()
void performance_comparator::add_unoptimized_sample (std::chrono::nanoseconds processing_time, std::size_t memory_usage) inline
Definition at line 80 of file optimization_demo.cpp.
Referenced by main().
print_comparison()
void performance_comparator::print_comparison () inline
Definition at line 94 of file optimization_demo.cpp.
References monitoring_module::performance_optimizer::optimization_stats::batches_processed, monitoring_module::performance_optimizer::optimization_stats::compression_ratio, monitoring_module::performance_optimizer::optimization_stats::memory_saved_bytes, and monitoring_module::performance_optimizer::optimization_stats::samples_skipped.
Referenced by main().
The documentation for this class was generated from the following file:
libraries/monitoring_system/samples/optimization_demo.cpp