Messaging System: monitoring_system::health_monitor_config Struct Reference
monitoring_system::health_monitor_config Struct Reference
Health monitor configuration.
#include <health_monitor.h>
Public Attributes
std::chrono::seconds check_interval {std::chrono::seconds(5)}
std::chrono::seconds cache_duration {std::chrono::seconds(1)}
bool enable_auto_recovery {true}
size_t max_consecutive_failures {3}
std::chrono::seconds recovery_timeout {std::chrono::seconds(30)}
Detailed Description
Health monitor configuration.
Definition at line 59 of file health_monitor.h.
Member Data Documentation
cache_duration
std::chrono::seconds monitoring_system::health_monitor_config::cache_duration {std::chrono::seconds(1)}
Definition at line 61 of file health_monitor.h.
Referenced by demonstrate_health_monitoring().
check_interval
std::chrono::seconds monitoring_system::health_monitor_config::check_interval {std::chrono::seconds(5)}
Definition at line 60 of file health_monitor.h.
Referenced by demonstrate_health_monitoring(), and TEST_F().
enable_auto_recovery
bool monitoring_system::health_monitor_config::enable_auto_recovery {true}
Definition at line 62 of file health_monitor.h.
Referenced by TEST_F().
max_consecutive_failures
size_t monitoring_system::health_monitor_config::max_consecutive_failures {3}
Definition at line 63 of file health_monitor.h.
recovery_timeout
std::chrono::seconds monitoring_system::health_monitor_config::recovery_timeout {std::chrono::seconds(30)}
Definition at line 64 of file health_monitor.h.
The documentation for this struct was generated from the following file:
libraries/monitoring_system/include/monitoring/health/health_monitor.h