Messaging System: libraries/monitoring_system/samples/advanced_analysis_example.cpp File Reference
advanced_analysis_example.cpp File Reference
#include <monitoring/multi_process_monitoring.h>
#include <monitoring/analysis_dashboard.h>
#include <thread>
#include <iostream>
#include <iomanip>
#include <chrono>
#include <random>
#include <csignal>
#include <atomic>
#include <unistd.h>
Classes
class workload_simulator
class dashboard_renderer
Functions
void signal_handler (int signal)
int main ()
Variables
std::atomic< bool > running {true}
Function Documentation
main()
int main ()
Definition at line 315 of file advanced_analysis_example.cpp.
References monitoring_module::analysis_dashboard::dashboard_config::anomaly_threshold, monitoring_module::analysis_dashboard::dashboard_config::enable_alerts, monitoring_module::analysis_dashboard::dashboard_config::enable_correlations, monitoring_module::analysis_dashboard::dashboard_config::enable_predictions, monitoring_module::analysis_dashboard::dashboard_config::prediction_horizon, dashboard_renderer::render_alerts_section(), dashboard_renderer::render_correlation_section(), dashboard_renderer::render_forecast_section(), dashboard_renderer::render_header(), dashboard_renderer::render_health_section(), dashboard_renderer::render_optimization_section(), running, signal_handler(), workload_simulator::simulate_tick(), and monitoring_module::analysis_dashboard::dashboard_config::trend_window_size.
signal_handler()
void signal_handler (int signal)
Definition at line 24 of file advanced_analysis_example.cpp.
References running.
Referenced by main().
Variable Documentation
running
std::atomic<bool> running {true}
Definition at line 22 of file advanced_analysis_example.cpp.
Referenced by adaptive_behavior_example(), BM_ProducerConsumerContention(), BM_SustainedThroughput(), main(), performance_monitoring_example(), and signal_handler().