Messaging System: kcenon::messaging::integrations::service_container Class Reference
kcenon::messaging::integrations::service_container Class Reference
#include <service_container.h>
Public Member Functions
service_container ()=default
~service_container ()=default
service_container (const service_container &)=delete
service_container & operator= (const service_container &)=delete
template<typename T >
void register_service (const std::string &name, service_factory< T > factory, bool singleton=true)
template<typename T >
void register_singleton (const std::string &name, std::shared_ptr< T > instance)
template<typename T >
std::shared_ptr< T > resolve (const std::string &name)
template<typename T >
std::shared_ptr< T > resolve ()
bool is_registered (const std::string &name) const
template<typename T >
bool is_registered () const
std::vector< std::string > get_registered_services () const
void clear ()
Detailed Description
Definition at line 44 of file service_container.h.
Constructor & Destructor Documentation
service_container() [1/2]
kcenon::messaging::integrations::service_container::service_container () default
~service_container()
kcenon::messaging::integrations::service_container::~service_container () default
service_container() [2/2]
kcenon::messaging::integrations::service_container::service_container (const service_container &) delete
Member Function Documentation
clear()
void kcenon::messaging::integrations::service_container::clear () inline
Definition at line 137 of file service_container.h.
Referenced by kcenon::messaging::integrations::messaging_system_orchestrator::shutdown().
get_registered_services()
std::vector< std::string > kcenon::messaging::integrations::service_container::get_registered_services () const inline
Definition at line 127 of file service_container.h.
is_registered() [1/2]
template<typename T > bool kcenon::messaging::integrations::service_container::is_registered () const inline
Definition at line 120 of file service_container.h.
is_registered() [2/2]
bool kcenon::messaging::integrations::service_container::is_registered (const std::string & name) const inline
Definition at line 114 of file service_container.h.
operator=()
service_container & kcenon::messaging::integrations::service_container::operator= (const service_container &) delete
register_service()
template<typename T > void kcenon::messaging::integrations::service_container::register_service (const std::string & name, service_factory< T > factory, bool singleton = true) inline
Definition at line 55 of file service_container.h.
Referenced by kcenon::messaging::integrations::messaging_system_orchestrator::register_messaging_services().
register_singleton()
template<typename T > void kcenon::messaging::integrations::service_container::register_singleton (const std::string & name, std::shared_ptr< T > instance) inline
Definition at line 64 of file service_container.h.
References kcenon::messaging::integrations::service_registration::instance.
Referenced by kcenon::messaging::integrations::messaging_system_orchestrator::register_core_services().
resolve() [1/2]
template<typename T > std::shared_ptr< T > kcenon::messaging::integrations::service_container::resolve () inline
Definition at line 104 of file service_container.h.
resolve() [2/2]
template<typename T > std::shared_ptr< T > kcenon::messaging::integrations::service_container::resolve (const std::string & name) inline
Definition at line 77 of file service_container.h.
Referenced by kcenon::messaging::integrations::system_integrator::get_service(), kcenon::messaging::integrations::system_integrator::get_service(), and kcenon::messaging::integrations::messaging_system_orchestrator::register_messaging_services().
The documentation for this class was generated from the following file:
application_layer/include/kcenon/messaging/integrations/service_container.h