Messaging System: kcenon::messaging::integrations::messaging_system_orchestrator Class Reference
kcenon::messaging::integrations::messaging_system_orchestrator Class Reference
#include <service_container.h>
Public Member Functions
messaging_system_orchestrator (const config::messaging_config &config)
~messaging_system_orchestrator ()
bool initialize ()
void shutdown ()
service_container & get_container ()
const service_container & get_container () const
core::message_bus * get_message_bus () const
const config::messaging_config & get_config () const
class external_system_manager & get_external_systems ()
bool is_running () const
void register_core_services ()
void register_messaging_services ()
void register_service_adapter (const std::string &name, std::shared_ptr< services::service_adapter > adapter)
std::vector< std::string > get_registered_adapters () const
Detailed Description
Definition at line 150 of file service_container.h.
Constructor & Destructor Documentation
messaging_system_orchestrator()
kcenon::messaging::integrations::messaging_system_orchestrator::messaging_system_orchestrator (const config::messaging_config & config) explicit
Definition at line 9 of file system_integrator.cpp.
References kcenon::messaging::config::messaging_config::message_bus.
~messaging_system_orchestrator()
kcenon::messaging::integrations::messaging_system_orchestrator::~messaging_system_orchestrator ()
Definition at line 19 of file system_integrator.cpp.
References shutdown().
Member Function Documentation
get_config()
const config::messaging_config & kcenon::messaging::integrations::messaging_system_orchestrator::get_config () const inline
Definition at line 167 of file service_container.h.
Referenced by kcenon::messaging::integrations::system_integrator::get_config().
get_container() [1/2]
service_container & kcenon::messaging::integrations::messaging_system_orchestrator::get_container () inline
Definition at line 160 of file service_container.h.
Referenced by kcenon::messaging::integrations::system_integrator::get_container(), kcenon::messaging::integrations::system_integrator::get_service(), and kcenon::messaging::integrations::system_integrator::get_service().
get_container() [2/2]
const service_container & kcenon::messaging::integrations::messaging_system_orchestrator::get_container () const inline
Definition at line 161 of file service_container.h.
get_external_systems()
class external_system_manager & kcenon::messaging::integrations::messaging_system_orchestrator::get_external_systems () inline
Definition at line 170 of file service_container.h.
Referenced by kcenon::messaging::integrations::system_integrator::get_external_systems().
get_message_bus()
core::message_bus * kcenon::messaging::integrations::messaging_system_orchestrator::get_message_bus () const inline
Definition at line 164 of file service_container.h.
Referenced by kcenon::messaging::integrations::system_integrator::get_message_bus().
get_registered_adapters()
std::vector< std::string > kcenon::messaging::integrations::messaging_system_orchestrator::get_registered_adapters () const
Definition at line 136 of file system_integrator.cpp.
Referenced by kcenon::messaging::integrations::system_integrator::check_system_health().
initialize()
bool kcenon::messaging::integrations::messaging_system_orchestrator::initialize ()
Definition at line 23 of file system_integrator.cpp.
References register_core_services(), and register_messaging_services().
Referenced by kcenon::messaging::integrations::system_integrator::initialize().
is_running()
bool kcenon::messaging::integrations::messaging_system_orchestrator::is_running () const inline
Definition at line 173 of file service_container.h.
Referenced by kcenon::messaging::integrations::system_integrator::is_running().
register_core_services()
void kcenon::messaging::integrations::messaging_system_orchestrator::register_core_services ()
Definition at line 77 of file system_integrator.cpp.
References kcenon::messaging::integrations::service_container::register_singleton().
Referenced by initialize().
register_messaging_services()
void kcenon::messaging::integrations::messaging_system_orchestrator::register_messaging_services ()
Definition at line 87 of file system_integrator.cpp.
References kcenon::messaging::config::messaging_config::container, kcenon::messaging::config::messaging_config::network, kcenon::messaging::integrations::service_container::register_service(), and kcenon::messaging::integrations::service_container::resolve().
Referenced by initialize().
register_service_adapter()
void kcenon::messaging::integrations::messaging_system_orchestrator::register_service_adapter (const std::string & name, std::shared_ptr< services::service_adapter > adapter)
Definition at line 123 of file system_integrator.cpp.
shutdown()
void kcenon::messaging::integrations::messaging_system_orchestrator::shutdown ()
Definition at line 56 of file system_integrator.cpp.
References kcenon::messaging::integrations::service_container::clear().
Referenced by kcenon::messaging::integrations::system_integrator::shutdown(), and ~messaging_system_orchestrator().
The documentation for this class was generated from the following files:
application_layer/include/kcenon/messaging/integrations/service_container.h
application_layer/src/kcenon/messaging/integrations/system_integrator.cpp