Messaging System: logger_module::file_writer Class Reference
logger_module::file_writer Class Reference
Basic file writer for logging to files.
#include <file_writer.h>
Public Member Functions
file_writer (const std::string &filename, bool append=true, size_t buffer_size=8192)
Constructor.
~file_writer () override
Destructor.
bool write (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write log entry to file.
void flush () override
Flush file buffer.
std::string get_name () const override
Get writer name.
bool is_open () const
Check if file is open.
size_t get_file_size () const
Get current file size.
bool reopen ()
Reopen the file.
Public Member Functions inherited from logger_module::base_writer
virtual ~base_writer ()=default
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get color setting.
Protected Member Functions
void close ()
Close the current file.
bool open ()
Open the file.
Protected Member Functions inherited from logger_module::base_writer
std::string format_log_entry (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
Format a log entry to string.
std::string level_to_string (thread_module::log_level level) const
Convert log level to string.
std::string level_to_color (thread_module::log_level level) const
Get ANSI color code for log level.
Protected Attributes
std::string filename_
bool append_mode_
size_t buffer_size_
std::ofstream file_stream_
std::unique_ptr< char[]> buffer_
std::mutex write_mutex_
std::atomic< size_t > bytes_written_ {0}
Detailed Description
Basic file writer for logging to files.
Definition at line 21 of file file_writer.h.
Constructor & Destructor Documentation
file_writer()
logger_module::file_writer::file_writer (const std::string & filename, bool append = true, size_t buffer_size = 8192) explicit
Constructor.
Parameters
filename Path to the log file
append Whether to append to existing file (default: true)
buffer_size Output buffer size in bytes (default: 8192)
Definition at line 14 of file file_writer.cpp.
References open().
~file_writer()
logger_module::file_writer::~file_writer () override
Destructor.
Definition at line 22 of file file_writer.cpp.
References close().
Member Function Documentation
close()
void logger_module::file_writer::close () protected
Close the current file.
Definition at line 63 of file file_writer.cpp.
References file_stream_.
Referenced by logger_module::rotating_file_writer::perform_rotation(), reopen(), and ~file_writer().
flush()
void logger_module::file_writer::flush () override virtual
Flush file buffer.
Implements logger_module::base_writer.
Definition at line 50 of file file_writer.cpp.
References file_stream_, and write_mutex_.
get_file_size()
size_t logger_module::file_writer::get_file_size () const inline
Get current file size.
Definition at line 66 of file file_writer.h.
References bytes_written_.
Referenced by logger_module::rotating_file_writer::should_rotate().
get_name()
std::string logger_module::file_writer::get_name () const inline override virtual
Get writer name.
Implements logger_module::base_writer.
Reimplemented in logger_module::rotating_file_writer.
Definition at line 56 of file file_writer.h.
is_open()
bool logger_module::file_writer::is_open () const inline
Check if file is open.
Definition at line 61 of file file_writer.h.
References file_stream_.
open()
bool logger_module::file_writer::open () protected
Open the file.
Definition at line 70 of file file_writer.cpp.
References append_mode_, buffer_, buffer_size_, bytes_written_, file_stream_, and filename_.
Referenced by file_writer(), logger_module::rotating_file_writer::perform_rotation(), and reopen().
reopen()
bool logger_module::file_writer::reopen ()
Reopen the file.
Definition at line 57 of file file_writer.cpp.
References close(), open(), and write_mutex_.
write()
bool logger_module::file_writer::write (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write log entry to file.
Implements logger_module::base_writer.
Reimplemented in logger_module::rotating_file_writer.
Definition at line 26 of file file_writer.cpp.
References bytes_written_, file_stream_, logger_module::base_writer::format_log_entry(), and write_mutex_.
Referenced by logger_module::rotating_file_writer::write().
Member Data Documentation
append_mode_
bool logger_module::file_writer::append_mode_ protected
Definition at line 86 of file file_writer.h.
Referenced by open().
buffer_
std::unique_ptr<char[]> logger_module::file_writer::buffer_ protected
Definition at line 90 of file file_writer.h.
Referenced by open().
buffer_size_
size_t logger_module::file_writer::buffer_size_ protected
Definition at line 87 of file file_writer.h.
Referenced by open().
bytes_written_
std::atomic<size_t> logger_module::file_writer::bytes_written_ {0} protected
Definition at line 93 of file file_writer.h.
Referenced by get_file_size(), open(), and write().
file_stream_
std::ofstream logger_module::file_writer::file_stream_ protected
Definition at line 89 of file file_writer.h.
Referenced by close(), flush(), is_open(), open(), and write().
filename_
std::string logger_module::file_writer::filename_ protected
Definition at line 85 of file file_writer.h.
Referenced by logger_module::rotating_file_writer::generate_rotated_filename(), logger_module::rotating_file_writer::get_backup_files(), open(), and logger_module::rotating_file_writer::perform_rotation().
write_mutex_
std::mutex logger_module::file_writer::write_mutex_ mutable protected
Definition at line 91 of file file_writer.h.
Referenced by flush(), reopen(), logger_module::rotating_file_writer::rotate(), and write().
The documentation for this class was generated from the following files:
libraries/logger_system/sources/logger/writers/file_writer.h
libraries/logger_system/sources/logger/writers/file_writer.cpp