Messaging System: libraries/container_system/examples/basic_container_example.cpp File Reference
basic_container_example.cpp File Reference
#include <iostream>
#include <memory>
#include <vector>
#include <chrono>
#include <iomanip>
#include "container.h"
#include "values/bytes_value.h"
#include "values/container_value.h"
Functions
void demonstrate_basic_usage ()
Basic Container System Example.
void demonstrate_value_types ()
void demonstrate_nested_containers ()
void demonstrate_serialization ()
void demonstrate_value_access ()
void demonstrate_error_handling ()
void demonstrate_performance_basics ()
int main ()
Function Documentation
demonstrate_basic_usage()
void demonstrate_basic_usage ()
Basic Container System Example.
This example demonstrates fundamental usage of the container system:
Creating containers
Adding different types of values
Serialization and deserialization
Basic error handling
Definition at line 23 of file basic_container_example.cpp.
Referenced by main().
demonstrate_error_handling()
void demonstrate_error_handling ()
Definition at line 245 of file basic_container_example.cpp.
Referenced by main().
demonstrate_nested_containers()
void demonstrate_nested_containers ()
Definition at line 98 of file basic_container_example.cpp.
Referenced by main().
demonstrate_performance_basics()
void demonstrate_performance_basics ()
Definition at line 286 of file basic_container_example.cpp.
Referenced by main().
demonstrate_serialization()
void demonstrate_serialization ()
Definition at line 138 of file basic_container_example.cpp.
Referenced by main().
demonstrate_value_access()
void demonstrate_value_access ()
Definition at line 193 of file basic_container_example.cpp.
References container_module::value::name(), container_module::value::to_string(), and container_module::value::type().
Referenced by main().
demonstrate_value_types()
void demonstrate_value_types ()
Definition at line 40 of file basic_container_example.cpp.
Referenced by main().
main()
int main ()
Definition at line 350 of file basic_container_example.cpp.
References demonstrate_basic_usage(), demonstrate_error_handling(), demonstrate_nested_containers(), demonstrate_performance_basics(), demonstrate_serialization(), demonstrate_value_access(), and demonstrate_value_types().