name: Build-Windows-MSYS2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_windows_msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    timeout-minutes: 60
    env:
      BUILD_TYPE: Debug
    
    steps:
      - name: Clean workspace
        shell: pwsh
        run: |
          if (Test-Path .git) {
            Remove-Item -Recurse -Force .git
          }
          if (Test-Path .github) {
            Remove-Item -Recurse -Force .github
          }
      
      - name: Configure git
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          git config --global core.longpaths true
      
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: kcenon/thread_system
          persist-credentials: true
          clean: true
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-make
            git

      - name: Cache vcpkg
        uses: actions/cache@v3
        id: vcpkg-cache
        with:
          path: |
            ${{ github.workspace }}/vcpkg
            !${{ github.workspace }}/vcpkg/buildtrees
            !${{ github.workspace }}/vcpkg/packages
            !${{ github.workspace }}/vcpkg/downloads
          key: ${{ runner.os }}-msys2-vcpkg-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-msys2-vcpkg-

      - name: Cache vcpkg installed
        uses: actions/cache@v3
        id: vcpkg-installed
        with:
          path: ${{ github.workspace }}/vcpkg_installed
          key: ${{ runner.os }}-msys2-vcpkg-installed-${{ hashFiles('vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-msys2-vcpkg-installed-

      - name: Set up vcpkg
        run: |
          if [ ! -d "vcpkg" ]; then
            echo "Cloning vcpkg repository..."
            git clone https://github.com/Microsoft/vcpkg.git
          else
            echo "Updating existing vcpkg repository..."
            cd vcpkg
            git pull
            cd ..
          fi
          
          echo "Bootstrapping vcpkg..."
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies with vcpkg
        if: steps.vcpkg-installed.outputs.cache-hit != 'true'
        run: |
          echo "Installing dependencies..."
          ./vcpkg/vcpkg install --x-manifest-root=. --x-install-root="${GITHUB_WORKSPACE}/vcpkg_installed" --triplet x64-mingw-dynamic

      - name: Cache CMake build
        uses: actions/cache@v3
        id: cmake-cache
        with:
          path: |
            ${{ github.workspace }}/build
          key: ${{ runner.os }}-cmake-msys2-${{ hashFiles('CMakeLists.txt', 'vcpkg.json') }}-${{ env.BUILD_TYPE }}
          restore-keys: |
            ${{ runner.os }}-cmake-msys2-

      - name: Prepare build directory
        run: |
          rm -rf build
          mkdir -p build

      - name: Build application
        env:
          CC: gcc
          CXX: g++
        run: |
          export PATH="/mingw64/bin:$PATH"
          cd build
          cmake .. \
            -G "Ninja" \
            -DBUILD_TESTS=ON \
            -DCMAKE_INSTALL_PREFIX="../target" \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DCMAKE_TOOLCHAIN_FILE="$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DVCPKG_TARGET_TRIPLET=x64-mingw-dynamic \
            -DCMAKE_C_COMPILER=/mingw64/bin/gcc.exe \
            -DCMAKE_CXX_COMPILER=/mingw64/bin/g++.exe \
            -DCMAKE_AR=/mingw64/bin/ar.exe

          cmake --build . --config $BUILD_TYPE --parallel $(nproc)

      - name: Cache built libraries
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.os }}-built-libs-msys2-${{ hashFiles('CMakeLists.txt', 'vcpkg.json') }}-${{ env.BUILD_TYPE }}
          restore-keys: |
            ${{ runner.os }}-built-libs-msys2-
