Messaging System: monitoring_system::time_series Class Reference
monitoring_system::time_series Class Reference
Thread-safe time series data storage.
#include <time_series.h>
Public Member Functions
time_series (const std::string &name, const time_series_config &config={})
Constructor.
result_void add_point (double value, std::chrono::system_clock::time_point timestamp=std::chrono::system_clock::now())
Add a data point.
result_void add_points (const std::vector< time_point_data > &points)
Add multiple data points.
result< aggregation_result > query (const time_series_query &query) const
Query data for a time range.
size_t size () const
Get current number of data points.
bool empty () const
Check if series is empty.
const std::string & name () const noexcept
Get series name.
const time_series_config & get_config () const noexcept
Get configuration.
void clear ()
Clear all data.
result< double > get_latest_value () const
Get latest value.
size_t memory_footprint () const
Get memory footprint in bytes.
time_series (const std::string &name, const time_series_config &config={})
Constructor.
result_void add_point (double value, std::chrono::system_clock::time_point timestamp=std::chrono::system_clock::now())
Add a data point.
result_void add_points (const std::vector< time_point_data > &points)
Add multiple data points.
result< aggregation_result > query (const time_series_query &query) const
Query data for a time range.
size_t size () const
Get current number of data points.
bool empty () const
Check if series is empty.
const std::string & name () const noexcept
Get series name.
const time_series_config & get_config () const noexcept
Get configuration.
void clear ()
Clear all data.
result< double > get_latest_value () const
Get latest value.
size_t memory_footprint () const
Get memory footprint in bytes.
Detailed Description
Thread-safe time series data storage.
Definition at line 206 of file time_series.h.
Constructor & Destructor Documentation
time_series() [1/2]
monitoring_system::time_series::time_series (const std::string & name, const time_series_config & config = {}) inline explicit
Constructor.
Definition at line 279 of file time_series.h.
time_series() [2/2]
monitoring_system::time_series::time_series (const std::string & name, const time_series_config & config = {}) inline explicit
Constructor.
Definition at line 279 of file time_series.h.
Member Function Documentation
add_point() [1/2]
result_void monitoring_system::time_series::add_point (double value, std::chrono::system_clock::time_point timestamp = std::chrono::system_clock::now()) inline
Add a data point.
Definition at line 295 of file time_series.h.
Referenced by TEST_F(), and TEST_F().
add_point() [2/2]
result_void monitoring_system::time_series::add_point (double value, std::chrono::system_clock::time_point timestamp = std::chrono::system_clock::now()) inline
Add a data point.
Definition at line 295 of file time_series.h.
add_points() [1/2]
result_void monitoring_system::time_series::add_points (const std::vector< time_point_data > & points) inline
Add multiple data points.
Definition at line 321 of file time_series.h.
add_points() [2/2]
result_void monitoring_system::time_series::add_points (const std::vector< time_point_data > & points) inline
Add multiple data points.
Definition at line 321 of file time_series.h.
clear() [1/2]
void monitoring_system::time_series::clear () inline
Clear all data.
Definition at line 441 of file time_series.h.
clear() [2/2]
void monitoring_system::time_series::clear () inline
Clear all data.
Definition at line 441 of file time_series.h.
empty() [1/2]
bool monitoring_system::time_series::empty () const inline
Check if series is empty.
Definition at line 419 of file time_series.h.
Referenced by TEST_F().
empty() [2/2]
bool monitoring_system::time_series::empty () const inline
Check if series is empty.
Definition at line 419 of file time_series.h.
get_config() [1/2]
const time_series_config & monitoring_system::time_series::get_config () const inline noexcept
Get configuration.
Definition at line 434 of file time_series.h.
get_config() [2/2]
const time_series_config & monitoring_system::time_series::get_config () const inline noexcept
Get configuration.
Definition at line 434 of file time_series.h.
get_latest_value() [1/2]
result< double > monitoring_system::time_series::get_latest_value () const inline
Get latest value.
Definition at line 449 of file time_series.h.
References monitoring_system::collection_failed, and monitoring_system::make_success().
Referenced by TEST_F().
get_latest_value() [2/2]
result< double > monitoring_system::time_series::get_latest_value () const inline
Get latest value.
Definition at line 449 of file time_series.h.
References monitoring_system::collection_failed, and monitoring_system::make_success().
memory_footprint() [1/2]
size_t monitoring_system::time_series::memory_footprint () const inline
Get memory footprint in bytes.
Definition at line 463 of file time_series.h.
memory_footprint() [2/2]
size_t monitoring_system::time_series::memory_footprint () const inline
Get memory footprint in bytes.
Definition at line 463 of file time_series.h.
name() [1/2]
const std::string & monitoring_system::time_series::name () const inline noexcept
Get series name.
Definition at line 427 of file time_series.h.
Referenced by TEST_F().
name() [2/2]
const std::string & monitoring_system::time_series::name () const inline noexcept
Get series name.
Definition at line 427 of file time_series.h.
query() [1/2]
result< aggregation_result > monitoring_system::time_series::query (const time_series_query & query) const inline
Query data for a time range.
Definition at line 344 of file time_series.h.
References monitoring_system::invalid_argument, monitoring_system::make_success(), monitoring_system::time_point_data::merge(), query(), and monitoring_system::time_point_data::timestamp.
Referenced by query(), and TEST_F().
query() [2/2]
result< aggregation_result > monitoring_system::time_series::query (const time_series_query & query) const inline
Query data for a time range.
Definition at line 344 of file time_series.h.
References monitoring_system::invalid_argument, monitoring_system::make_success(), and query().
size() [1/2]
size_t monitoring_system::time_series::size () const inline
Get current number of data points.
Definition at line 411 of file time_series.h.
Referenced by TEST_F().
size() [2/2]
size_t monitoring_system::time_series::size () const inline
Get current number of data points.
Definition at line 411 of file time_series.h.
The documentation for this class was generated from the following files:
libraries/monitoring_system/include/kcenon/monitoring/utils/time_series.h
libraries/monitoring_system/src/utils/time_series.h