Messaging System: thread_pool_module::detail Namespace Reference
thread_pool_module::detail Namespace Reference
Classes
class callable_eraser
Type eraser for heterogeneous callable storage.
struct callable_return_type
Type trait to extract return type from callable.
struct compile_string
Compile-time string for template error messages.
struct function_traits
Type trait for function signature analysis.
struct function_traits< R(*)(Args...) noexcept >
struct function_traits< R(*)(Args...)>
struct function_traits< R(C::*)(Args...) const >
struct function_traits< R(C::*)(Args...)>
struct has_get_method
SFINAE helper to detect if a type has a specific member.
struct has_get_method< T, std::void_t< decltype(std::declval< T >().get())> >
struct is_duration
Type trait to detect if a type is a duration.
struct is_duration< std::chrono::duration< Rep, Period > >
struct is_future_like
SFINAE helper to detect future-like types.
struct is_nothrow_callable
Type trait to check if a callable is noexcept.
struct validate_thread_count
Compile-time validation for thread pool configuration.
Concepts
concept Callable
Concept to validate callable types for thread pool jobs.
concept VoidCallable
Concept for callable types that return void.
concept ReturningCallable
Concept for callable types that return a result.
concept CallableWith
Concept for callables with specific argument types.
concept Duration
Concept for duration types.
concept FutureLike
Concept for future-like types.
concept PoolJob
Concept for valid thread pool job types.
Typedefs
template<typename F >
using callable_return_type_t = typename callable_return_type< F >::type
template<typename F >
using function_return_t = typename function_traits< F >::return_type
Helper to get function traits.
template<typename F >
using function_args_t = typename function_traits< F >::argument_types
Functions
template<typename T >
constexpr auto forward_if_callable (T &&t) -> std::enable_if_t< Callable< T >, T && >
Template helper for perfect forwarding with type constraints.
template<typename T >
constexpr auto get_type_name ()
Template for generating descriptive error messages.
Variables
template<typename T >
constexpr bool is_duration_v = is_duration<T>::value
template<typename F >
constexpr bool is_nothrow_callable_v = is_nothrow_callable<F>::value
template<typename T >
constexpr bool has_get_method_v = has_get_method<T>::value
template<typename T >
constexpr bool is_future_like_v = is_future_like<T>::value
template<typename F >
constexpr size_t function_arity_v = function_traits<F>::arity
Typedef Documentation
callable_return_type_t
template<typename F > using thread_pool_module::detail::callable_return_type_t = typedef typename callable_return_type<F>::type
Definition at line 100 of file pool_traits.h.
function_args_t
template<typename F > using thread_pool_module::detail::function_args_t = typedef typename function_traits<F>::argument_types
Definition at line 197 of file pool_traits.h.
function_return_t
template<typename F > using thread_pool_module::detail::function_return_t = typedef typename function_traits<F>::return_type
Helper to get function traits.
Definition at line 194 of file pool_traits.h.
Function Documentation
forward_if_callable()
template<typename T > constexpr auto thread_pool_module::detail::forward_if_callable (T && t) -> std::enable_if_t<Callable<T>, T&&> constexpr
Template helper for perfect forwarding with type constraints.
Definition at line 216 of file pool_traits.h.
References forward_if_callable().
Referenced by forward_if_callable().
get_type_name()
template<typename T > constexpr auto thread_pool_module::detail::get_type_name () constexpr
Template for generating descriptive error messages.
Definition at line 275 of file pool_traits.h.
References get_type_name().
Referenced by get_type_name().
Variable Documentation
function_arity_v
template<typename F > constexpr size_t thread_pool_module::detail::function_arity_v = function_traits<F>::arity constexpr
Definition at line 200 of file pool_traits.h.
has_get_method_v
template<typename T > constexpr bool thread_pool_module::detail::has_get_method_v = has_get_method<T>::value constexpr
Definition at line 122 of file pool_traits.h.
is_duration_v
template<typename T > constexpr bool thread_pool_module::detail::is_duration_v = is_duration<T>::value constexpr
Definition at line 83 of file pool_traits.h.
is_future_like_v
template<typename T > constexpr bool thread_pool_module::detail::is_future_like_v = is_future_like<T>::value constexpr
Definition at line 134 of file pool_traits.h.
is_nothrow_callable_v
template<typename F > constexpr bool thread_pool_module::detail::is_nothrow_callable_v = is_nothrow_callable<F>::value constexpr
Definition at line 109 of file pool_traits.h.