Messaging System: kcenon::logger::logger_builder Class Reference
kcenon::logger::logger_builder Class Reference
Builder pattern for logger construction with validation.
#include <logger_builder.h>
Public Member Functions
logger_builder ()
logger_builder & with_config (const logger_config &config)
logger_builder & with_async (bool async=true)
logger_builder & with_buffer_size (std::size_t size)
Set buffer size.
logger_builder & with_min_level (kcenon::thread::log_level level)
logger_builder & with_batch_size (std::size_t size)
Set batch size for processing.
logger_builder & with_batch_writing (bool enable=true)
Enable batch writing for writers.
logger_builder & with_flush_interval (std::chrono::milliseconds interval)
Set flush interval.
logger_builder & with_lock_free (bool enable=true)
Enable lock-free queue.
logger_builder & with_metrics (bool enable=true)
Enable metrics collection.
logger_builder & with_crash_handler (bool enable=true)
Enable crash handler.
logger_builder & with_structured_logging (bool enable=true)
Enable structured logging.
logger_builder & with_overflow_policy (logger_config::overflow_policy policy)
Set queue overflow policy.
logger_builder & with_max_queue_size (std::size_t size)
Set max queue size.
logger_builder & with_file_output (const std::string &directory, const std::string &prefix="app", std::size_t max_size=100 *1024 *1024, std::size_t max_count=5)
Configure file output.
logger_builder & with_network_output (const std::string &host, uint16_t port, std::chrono::milliseconds timeout=std::chrono::milliseconds(5000))
Configure network output.
logger_builder & add_writer (const std::string &name, std::unique_ptr< base_writer > writer)
Add a writer to the logger.
logger_builder & add_filter (std::unique_ptr< log_filter > filter)
Add a filter to the logger.
logger_builder & with_formatter (std::unique_ptr< log_formatter_interface > formatter)
Set formatter for the logger.
logger_builder & use_template (const std::string &name)
logger_builder & apply_strategy (std::unique_ptr< config_strategy_interface > strategy)
Apply a configuration strategy.
logger_builder & for_environment (const std::string &env)
Apply environment-based configuration.
logger_builder & with_performance_tuning (const std::string &level="balanced")
Apply performance tuning strategy.
logger_builder & auto_configure ()
Auto-detect and apply environment configuration.
logger_builder & apply_template (kcenon::logger::configuration_template template_type)
Apply a configuration template.
logger_builder & apply_performance_strategy (kcenon::logger::performance_strategy strategy)
Apply a performance strategy.
logger_builder & detect_environment ()
Detect environment from environment variables.
logger_builder & with_monitoring (std::shared_ptr< monitoring_interface > monitor)
Set monitoring interface.
logger_builder & with_health_check_interval (std::chrono::milliseconds interval)
Set health check interval.
template<typename T >
logger_builder & with_di_container (std::shared_ptr< di_container_interface< T > > container)
Set DI container.
logger_builder & with_writer_from_di (const std::string &name)
Add writer from DI container.
logger_builder & with_error_handler (std::function< void(const logger_error_code &)> handler)
Set error handler.
logger_builder & with_default_pattern ()
Use default pattern for logging.
logger_builder & clear_strategies ()
Clear all applied strategies.
result< std::unique_ptr< logger > > build ()
const logger_config & get_config () const
Get the current configuration (for inspection)
result_void validate () const
Validate current configuration without building.
Detailed Description
Builder pattern for logger construction with validation.
The logger_builder class provides a fluent interface for constructing logger instances with complex configurations. It ensures configuration validity, applies optimization strategies, and handles the complexity of logger initialization.
Key features:
Fluent interface for intuitive configuration
Automatic validation of configuration parameters
Support for configuration templates and strategies
Environment-based auto-configuration
Integration with dependency injection containers
Performance tuning presets
Note
All builder methods return a reference to the builder for method chaining.
Warning
The build() method consumes writers and filters. After calling build(), the builder should not be reused without adding new writers.
Since
1.0.0
Definition at line 107 of file logger_builder.h.
Constructor & Destructor Documentation
logger_builder()
kcenon::logger::logger_builder::logger_builder () inline
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 109 of file logger_builder.h.
Member Function Documentation
add_filter()
logger_builder & kcenon::logger::logger_builder::add_filter (std::unique_ptr< log_filter > filter) inline
Add a filter to the logger.
Parameters
filter Filter instance
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 353 of file logger_builder.h.
Referenced by TEST_F().
add_writer()
logger_builder & kcenon::logger::logger_builder::add_writer (const std::string & name, std::unique_ptr< base_writer > writer) inline
Add a writer to the logger.
Parameters
name Writer name
writer Writer instance
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 343 of file logger_builder.h.
Referenced by api_comparison_example(), BM_ConfigurationTemplates(), BM_FilterImpact(), BM_LoggerWithBatchConfig(), BM_MessageSize(), BM_MultipleWriters(), BM_MultithreadedBatchSimulation(), BM_QueueBehavior(), BM_StructuredLogging(), GradualMigrationExample::GradualMigrationExample(), migration_pitfalls_example(), modern_v2_code_example(), performance_comparison(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
apply_performance_strategy()
logger_builder & kcenon::logger::logger_builder::apply_performance_strategy (kcenon::logger::performance_strategy strategy) inline
Apply a performance strategy.
Parameters
strategy Performance strategy to apply
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 501 of file logger_builder.h.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::block, kcenon::logger::logger_config::buffer_size, kcenon::logger::logger_config::drop_newest, kcenon::logger::logger_config::drop_oldest, kcenon::logger::logger_config::enable_batch_writing, kcenon::logger::logger_config::flush_interval, kcenon::logger::logger_config::grow, kcenon::logger::logger_config::min_level, and kcenon::logger::logger_config::queue_overflow_policy.
Referenced by TEST_F().
apply_strategy()
logger_builder & kcenon::logger::logger_builder::apply_strategy (std::unique_ptr< config_strategy_interface > strategy) inline
Apply a configuration strategy.
Parameters
strategy Strategy to apply
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 420 of file logger_builder.h.
Referenced by auto_configure(), for_environment(), TEST_F(), use_template(), and with_performance_tuning().
apply_template()
logger_builder & kcenon::logger::logger_builder::apply_template (kcenon::logger::configuration_template template_type) inline
Apply a configuration template.
Parameters
template_type Template to apply
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 470 of file logger_builder.h.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::block, kcenon::logger::logger_config::buffer_size, kcenon::logger::logger_config::drop_newest, kcenon::logger::logger_config::drop_oldest, kcenon::logger::logger_config::enable_batch_writing, kcenon::logger::logger_config::flush_interval, kcenon::logger::logger_config::grow, kcenon::logger::logger_config::min_level, and kcenon::logger::logger_config::queue_overflow_policy.
Referenced by detect_environment(), and TEST_F().
auto_configure()
logger_builder & kcenon::logger::logger_builder::auto_configure () inline
Auto-detect and apply environment configuration.
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 457 of file logger_builder.h.
References apply_strategy().
Referenced by TEST_F().
build()
result< std::unique_ptr< logger > > kcenon::logger::logger_builder::build () inline
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 662 of file logger_builder.h.
References kcenon::logger::composite_filter::AND, kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::buffer_size, kcenon::logger::logger_config::enable_batch_writing, kcenon::logger::logger_config::enable_color_output, kcenon::logger::logger_config::enable_metrics, kcenon::logger::result< T >::error_code(), kcenon::logger::result< T >::error_message(), kcenon::logger::logger_config::flush_interval, kcenon::logger::batch_writer::config::flush_interval, kcenon::logger::invalid_configuration, kcenon::logger::batch_writer::config::max_batch_size, kcenon::logger::logger_config::max_writers, kcenon::logger::logger_config::min_level, and kcenon::logger::logger_config::validate().
Referenced by api_comparison_example(), BM_ConfigurationTemplates(), BM_FilterImpact(), BM_LoggerWithBatchConfig(), BM_MessageSize(), BM_MultipleWriters(), BM_MultithreadedBatchSimulation(), BM_QueueBehavior(), BM_StructuredLogging(), GradualMigrationExample::GradualMigrationExample(), migration_pitfalls_example(), modern_v2_code_example(), performance_comparison(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
clear_strategies()
logger_builder & kcenon::logger::logger_builder::clear_strategies () inline
Clear all applied strategies.
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 625 of file logger_builder.h.
Referenced by TEST_F().
detect_environment()
logger_builder & kcenon::logger::logger_builder::detect_environment () inline
Detect environment from environment variables.
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 531 of file logger_builder.h.
References apply_template(), and kcenon::logger::logger_config::min_level.
Referenced by TEST_F().
for_environment()
logger_builder & kcenon::logger::logger_builder::for_environment (const std::string & env) inline
Apply environment-based configuration.
Parameters
env Environment name ("development", "testing", "staging", "production")
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 432 of file logger_builder.h.
References apply_strategy().
Referenced by TEST_F(), TEST_F(), and TEST_F().
get_config()
const logger_config & kcenon::logger::logger_builder::get_config () const inline
Get the current configuration (for inspection)
Returns
Current configuration
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 773 of file logger_builder.h.
Referenced by TEST_F(), and TEST_F().
use_template()
logger_builder & kcenon::logger::logger_builder::use_template (const std::string & name) inline
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 394 of file logger_builder.h.
References apply_strategy(), kcenon::logger::logger_config::debug_config(), kcenon::logger::logger_config::default_config(), kcenon::logger::logger_config::high_performance(), kcenon::logger::logger_config::low_latency(), and kcenon::logger::logger_config::production().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
validate()
result_void kcenon::logger::logger_builder::validate () const inline
Validate current configuration without building.
Returns
Validation result
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 781 of file logger_builder.h.
References kcenon::logger::logger_config::validate().
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
with_async()
logger_builder & kcenon::logger::logger_builder::with_async (bool async = true) inline
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 157 of file logger_builder.h.
References kcenon::logger::logger_config::async, and kcenon::logger::logger_config::batch_size.
Referenced by api_comparison_example(), BM_FilterImpact(), BM_LoggerWithBatchConfig(), BM_MessageSize(), BM_MultipleWriters(), BM_MultithreadedBatchSimulation(), BM_QueueBehavior(), BM_StructuredLogging(), performance_comparison(), TEST_F(), TEST_F(), and TEST_F().
with_batch_size()
logger_builder & kcenon::logger::logger_builder::with_batch_size (std::size_t size) inline
Set batch size for processing.
Parameters
size Batch size
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 217 of file logger_builder.h.
References kcenon::logger::logger_config::batch_size.
Referenced by BM_LoggerWithBatchConfig(), BM_MessageSize(), BM_MultipleWriters(), BM_MultithreadedBatchSimulation(), and performance_comparison().
with_batch_writing()
logger_builder & kcenon::logger::logger_builder::with_batch_writing (bool enable = true) inline
Enable batch writing for writers.
Parameters
enable Enable/disable batch writing
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 227 of file logger_builder.h.
References kcenon::logger::logger_config::enable_batch_writing.
Referenced by BM_MessageSize(), BM_MultipleWriters(), and performance_comparison().
with_buffer_size()
logger_builder & kcenon::logger::logger_builder::with_buffer_size (std::size_t size) inline
Set buffer size.
Parameters
size Buffer size in bytes
Returns
Reference to builder for chaining
Configures the internal buffer size for log message queuing. Larger buffers can improve throughput but increase memory usage.
Note
Recommended sizes:
Small applications: 4096-8192 bytes
Medium applications: 16384-32768 bytes
High-throughput applications: 65536+ bytes
Warning
Very large buffers may cause memory pressure in constrained environments.
Since
1.0.0
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 183 of file logger_builder.h.
References kcenon::logger::logger_config::buffer_size.
Referenced by api_comparison_example(), BM_MessageSize(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
with_config()
logger_builder & kcenon::logger::logger_builder::with_config (const logger_config & config) inline
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 130 of file logger_builder.h.
Referenced by BM_ConfigurationTemplates().
with_crash_handler()
logger_builder & kcenon::logger::logger_builder::with_crash_handler (bool enable = true) inline
Enable crash handler.
Parameters
enable Enable/disable crash handler
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 267 of file logger_builder.h.
References kcenon::logger::logger_config::enable_crash_handler.
Referenced by TEST_F().
with_default_pattern()
logger_builder & kcenon::logger::logger_builder::with_default_pattern () inline
Use default pattern for logging.
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 614 of file logger_builder.h.
References kcenon::logger::logger_config::enable_source_location, and kcenon::logger::logger_config::enable_timestamp.
Referenced by TEST_F(), TEST_F(), and TEST_F().
with_di_container()
template<typename T > logger_builder & kcenon::logger::logger_builder::with_di_container (std::shared_ptr< di_container_interface< T > > container) inline
Set DI container.
Parameters
container DI container implementation
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 584 of file logger_builder.h.
with_error_handler()
logger_builder & kcenon::logger::logger_builder::with_error_handler (std::function< void(const logger_error_code &)> handler) inline
Set error handler.
Parameters
handler Error handler function
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 605 of file logger_builder.h.
Referenced by TEST_F().
with_file_output()
logger_builder & kcenon::logger::logger_builder::with_file_output (const std::string & directory, const std::string & prefix = "app", std::size_t max_size = 100 * 1024 * 1024, std::size_t max_count = 5) inline
Configure file output.
Parameters
directory Log directory
prefix File prefix
max_size Maximum file size
max_count Maximum file count for rotation
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 310 of file logger_builder.h.
References kcenon::logger::logger_config::log_directory, kcenon::logger::logger_config::log_file_prefix, kcenon::logger::logger_config::max_file_count, and kcenon::logger::logger_config::max_file_size.
Referenced by modern_v2_code_example().
with_flush_interval()
logger_builder & kcenon::logger::logger_builder::with_flush_interval (std::chrono::milliseconds interval) inline
Set flush interval.
Parameters
interval Flush interval
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 237 of file logger_builder.h.
References kcenon::logger::logger_config::flush_interval.
with_formatter()
logger_builder & kcenon::logger::logger_builder::with_formatter (std::unique_ptr< log_formatter_interface > formatter) inline
Set formatter for the logger.
Parameters
formatter Formatter instance
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 363 of file logger_builder.h.
with_health_check_interval()
logger_builder & kcenon::logger::logger_builder::with_health_check_interval (std::chrono::milliseconds interval) inline
Set health check interval.
Parameters
interval Health check interval
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 573 of file logger_builder.h.
Referenced by TEST_F().
with_lock_free()
logger_builder & kcenon::logger::logger_builder::with_lock_free (bool enable = true) inline
Enable lock-free queue.
Parameters
enable Enable/disable lock-free mode
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 247 of file logger_builder.h.
References kcenon::logger::logger_config::use_lock_free.
with_max_queue_size()
logger_builder & kcenon::logger::logger_builder::with_max_queue_size (std::size_t size) inline
Set max queue size.
Parameters
size Maximum queue size
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 297 of file logger_builder.h.
References kcenon::logger::logger_config::max_queue_size.
Referenced by BM_QueueBehavior(), and performance_comparison().
with_metrics()
logger_builder & kcenon::logger::logger_builder::with_metrics (bool enable = true) inline
Enable metrics collection.
Parameters
enable Enable/disable metrics
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 257 of file logger_builder.h.
References kcenon::logger::logger_config::enable_metrics.
Referenced by TEST_F(), and TEST_F().
with_min_level()
logger_builder & kcenon::logger::logger_builder::with_min_level (kcenon::thread::log_level level) inline
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 207 of file logger_builder.h.
References kcenon::logger::logger_config::min_level.
Referenced by api_comparison_example(), BM_FilterImpact(), migration_pitfalls_example(), modern_v2_code_example(), TEST_F(), and TEST_F().
with_monitoring()
logger_builder & kcenon::logger::logger_builder::with_monitoring (std::shared_ptr< monitoring_interface > monitor) inline
Set monitoring interface.
Parameters
monitor Monitoring interface implementation
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 562 of file logger_builder.h.
References kcenon::logger::logger_config::enable_metrics.
Referenced by TEST_F(), and TEST_F().
with_network_output()
logger_builder & kcenon::logger::logger_builder::with_network_output (const std::string & host, uint16_t port, std::chrono::milliseconds timeout = std::chrono::milliseconds(5000)) inline
Configure network output.
Parameters
host Remote host
port Remote port
timeout Connection timeout
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 328 of file logger_builder.h.
References kcenon::logger::logger_config::network_timeout, kcenon::logger::logger_config::remote_host, and kcenon::logger::logger_config::remote_port.
with_overflow_policy()
logger_builder & kcenon::logger::logger_builder::with_overflow_policy (logger_config::overflow_policy policy) inline
Set queue overflow policy.
Parameters
policy Overflow policy to use
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 287 of file logger_builder.h.
References kcenon::logger::logger_config::queue_overflow_policy.
Referenced by BM_QueueBehavior(), and TEST_F().
with_performance_tuning()
logger_builder & kcenon::logger::logger_builder::with_performance_tuning (const std::string & level = "balanced") inline
Apply performance tuning strategy.
Parameters
level Tuning level ("conservative", "balanced", "aggressive")
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 445 of file logger_builder.h.
References apply_strategy().
Referenced by TEST_F(), TEST_F(), and TEST_F().
with_structured_logging()
logger_builder & kcenon::logger::logger_builder::with_structured_logging (bool enable = true) inline
Enable structured logging.
Parameters
enable Enable/disable structured logging
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 277 of file logger_builder.h.
References kcenon::logger::logger_config::enable_structured_logging.
Referenced by BM_StructuredLogging().
with_writer_from_di()
logger_builder & kcenon::logger::logger_builder::with_writer_from_di (const std::string & name) inline
Add writer from DI container.
Parameters
name Writer name to resolve from DI
Returns
Reference to builder for chaining
Examples
/home/runner/work/messaging_system/messaging_system/libraries/logger_system/include/kcenon/logger/core/logger_builder.h.
Definition at line 595 of file logger_builder.h.
The documentation for this class was generated from the following file:
libraries/logger_system/include/kcenon/logger/core/logger_builder.h