Messaging System: monitoring_system::alerting::DeduplicationConfigBuilder Class Reference
monitoring_system::alerting::DeduplicationConfigBuilder Class Reference
#include <alert_deduplication.h>
Public Member Functions
DeduplicationConfigBuilder ()=default
DeduplicationConfigBuilder & with_strategy (DeduplicationStrategy strategy)
DeduplicationConfigBuilder & with_window (std::chrono::seconds window)
DeduplicationConfigBuilder & with_similarity_threshold (double threshold)
DeduplicationConfigBuilder & with_max_entries (size_t max_entries)
void apply_to (AlertDeduplication &dedup) const
Detailed Description
Definition at line 291 of file alert_deduplication.h.
Constructor & Destructor Documentation
DeduplicationConfigBuilder()
monitoring_system::alerting::DeduplicationConfigBuilder::DeduplicationConfigBuilder () default
Member Function Documentation
apply_to()
void monitoring_system::alerting::DeduplicationConfigBuilder::apply_to (AlertDeduplication & dedup) const inline
Definition at line 315 of file alert_deduplication.h.
References monitoring_system::alerting::AlertDeduplication::set_deduplication_strategy(), monitoring_system::alerting::AlertDeduplication::set_deduplication_window(), monitoring_system::alerting::AlertDeduplication::set_max_entries(), and monitoring_system::alerting::AlertDeduplication::set_similarity_threshold().
with_max_entries()
DeduplicationConfigBuilder & monitoring_system::alerting::DeduplicationConfigBuilder::with_max_entries (size_t max_entries) inline
Definition at line 310 of file alert_deduplication.h.
with_similarity_threshold()
DeduplicationConfigBuilder & monitoring_system::alerting::DeduplicationConfigBuilder::with_similarity_threshold (double threshold) inline
Definition at line 305 of file alert_deduplication.h.
with_strategy()
DeduplicationConfigBuilder & monitoring_system::alerting::DeduplicationConfigBuilder::with_strategy (DeduplicationStrategy strategy) inline
Definition at line 295 of file alert_deduplication.h.
with_window()
DeduplicationConfigBuilder & monitoring_system::alerting::DeduplicationConfigBuilder::with_window (std::chrono::seconds window) inline
Definition at line 300 of file alert_deduplication.h.
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/impl/alerting/alert_deduplication.h