Messaging System: libraries/thread_system/examples/typed_thread_pool_sample_2/test_type.h File Reference
test_type.h File Reference
#include "utilities/core/formatter.h"
#include "utilities/conversion/convert_string.h"
#include <string>
#include <array>
#include <cstdint>
#include <string_view>
Classes
struct fmt::formatter< test_priority >
Specialization of fmt::formatter for test_priority.
struct fmt::formatter< test_priority, wchar_t >
Specialization of fmt::formatter for wide-character test_priority.
Namespaces
namespace test_detail
Enumerations
enum class test_priority : uint8_t { Top = 0 , Middle , Bottom }
Enumeration of test priority levels.
Functions
constexpr std::string_view to_string (test_priority priority)
Converts a test_priority value to its string representation.
auto all_types (void) -> std::vector< test_priority >
Converts a string to a job_types value.
Variables
constexpr std::array test_detail::test_priority_strings = { "Top", "Middle", "Bottom" }
Array of string representations for each test priority level.
constexpr size_t test_detail::test_priority_count = test_priority_strings.size()
Total number of test types available in test_priority_strings.
Enumeration Type Documentation
test_priority
enum class test_priority : uint8_t strong
Enumeration of test priority levels.
Defines priority levels for test cases. This enum class is based on uint8_t to optimize storage, with three priority levels: Top, Middle, and Bottom.
Enumerator
Top
Top priority.
Middle
Middle priority.
Bottom
Bottom priority.
Definition at line 50 of file test_type.h.
Function Documentation
all_types()
auto all_types (void) -> std::vector<test_priority> inline
Converts a string to a job_types value.
Returns
std::vector<test_priority>
Definition at line 90 of file test_type.h.
References Bottom, Middle, and Top.
to_string()
constexpr std::string_view to_string (test_priority priority) constexpr
Converts a test_priority value to its string representation.
Parameters
priority The test_priority value to convert.
Returns
std::string_view String representation of the test priority.
Definition at line 79 of file test_type.h.
References test_detail::test_priority_count, and test_detail::test_priority_strings.
Referenced by fmt::formatter< test_priority >::format(), fmt::formatter< test_priority, wchar_t >::format(), TEST_F(), monitoring_system::result< T >::value(), and monitoring_system::result< T >::value().