Messaging System: kcenon::logger::rotating_file_writer Class Reference
kcenon::logger::rotating_file_writer Class Reference
File writer with rotation support based on size or time.
#include <rotating_file_writer.h>
Public Types
enum class rotation_type { size , daily , hourly , size_and_time }
Type of rotation strategy.
Public Member Functions
rotating_file_writer (const std::string &filename, size_t max_size, size_t max_files=10)
Constructor for size-based rotation.
rotating_file_writer (const std::string &filename, rotation_type type, size_t max_files=10)
Constructor for time-based rotation.
rotating_file_writer (const std::string &filename, rotation_type type, size_t max_size, size_t max_files=10)
Constructor for combined rotation.
~rotating_file_writer () override=default
Destructor.
result_void write (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write with rotation check.
std::string get_name () const override
Get writer name.
void rotate ()
Force rotation.
Public Member Functions inherited from kcenon::logger::file_writer
file_writer (const std::string &filename, bool append=true, size_t buffer_size=8192)
Constructor.
~file_writer () override
Destructor.
result_void flush () override
Flush file buffer.
bool is_open () const
Check if file is open.
size_t get_file_size () const
Get current file size.
result_void reopen ()
Reopen the file.
Public Member Functions inherited from kcenon::logger::base_writer
virtual ~base_writer ()=default
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
virtual bool is_healthy () const override
Check if the writer is healthy and operational.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
Protected Member Functions
bool should_rotate () const
Check if rotation is needed.
void perform_rotation ()
Perform rotation.
std::string generate_rotated_filename (int index=-1) const
Generate rotated filename.
void cleanup_old_files ()
Clean up old files.
std::vector< std::string > get_backup_files () const
Get list of existing backup files.
bool should_rotate_by_time () const
Check if time-based rotation is needed.
Protected Member Functions inherited from kcenon::logger::file_writer
void close ()
Close the current file.
result_void open ()
Open the file.
Protected Member Functions inherited from kcenon::logger::base_writer
std::string format_log_entry (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (logger_system::log_level level) const
Convert log level to string representation.
std::string level_to_color (logger_system::log_level level) const
Get ANSI color code for the specified log level.
Additional Inherited Members
Protected Attributes inherited from kcenon::logger::file_writer
std::string filename_
bool append_mode_
size_t buffer_size_
std::ofstream file_stream_
std::unique_ptr< char[]> buffer_
std::mutex write_mutex_
std::atomic< size_t > bytes_written_ {0}
Detailed Description
File writer with rotation support based on size or time.
Definition at line 21 of file rotating_file_writer.h.
Member Enumeration Documentation
rotation_type
enum class kcenon::logger::rotating_file_writer::rotation_type strong
Type of rotation strategy.
Enumerator
size
daily
hourly
size_and_time
Definition at line 27 of file rotating_file_writer.h.
Constructor & Destructor Documentation
rotating_file_writer() [1/3]
kcenon::logger::rotating_file_writer::rotating_file_writer (const std::string & filename, size_t max_size, size_t max_files = 10)
Constructor for size-based rotation.
Parameters
filename Base filename (will be appended with number/date)
max_size Maximum file size in bytes before rotation
max_files Maximum number of backup files to keep
Definition at line 17 of file rotating_file_writer.cpp.
rotating_file_writer() [2/3]
kcenon::logger::rotating_file_writer::rotating_file_writer (const std::string & filename, rotation_type type, size_t max_files = 10)
Constructor for time-based rotation.
Parameters
filename Base filename (will be appended with date/time)
type Rotation type (daily or hourly)
max_files Maximum number of backup files to keep
Definition at line 36 of file rotating_file_writer.cpp.
rotating_file_writer() [3/3]
kcenon::logger::rotating_file_writer::rotating_file_writer (const std::string & filename, rotation_type type, size_t max_size, size_t max_files = 10)
Constructor for combined rotation.
Parameters
filename Base filename
type Must be size_and_time
max_size Maximum file size
max_files Maximum number of backup files
Definition at line 55 of file rotating_file_writer.cpp.
References size_and_time.
~rotating_file_writer()
kcenon::logger::rotating_file_writer::~rotating_file_writer () override default
Destructor.
Member Function Documentation
cleanup_old_files()
void kcenon::logger::rotating_file_writer::cleanup_old_files () protected
Clean up old files.
Definition at line 187 of file rotating_file_writer.cpp.
References get_backup_files().
Referenced by perform_rotation().
generate_rotated_filename()
std::string kcenon::logger::rotating_file_writer::generate_rotated_filename (int index = -1) const protected
Generate rotated filename.
Definition at line 142 of file rotating_file_writer.cpp.
References daily, kcenon::logger::file_writer::filename_, hourly, size, and size_and_time.
Referenced by perform_rotation().
get_backup_files()
std::vector< std::string > kcenon::logger::rotating_file_writer::get_backup_files () const protected
Get list of existing backup files.
Definition at line 210 of file rotating_file_writer.cpp.
References kcenon::logger::file_writer::filename_.
Referenced by cleanup_old_files().
get_name()
std::string kcenon::logger::rotating_file_writer::get_name () const inline override virtual
Get writer name.
Reimplemented from kcenon::logger::file_writer.
Definition at line 84 of file rotating_file_writer.h.
perform_rotation()
void kcenon::logger::rotating_file_writer::perform_rotation () protected
Perform rotation.
Definition at line 115 of file rotating_file_writer.cpp.
References cleanup_old_files(), kcenon::logger::file_writer::close(), kcenon::logger::file_writer::filename_, generate_rotated_filename(), and kcenon::logger::file_writer::open().
Referenced by rotate().
rotate()
void kcenon::logger::rotating_file_writer::rotate ()
Force rotation.
Definition at line 93 of file rotating_file_writer.cpp.
References perform_rotation(), and kcenon::logger::file_writer::write_mutex_.
Referenced by write().
should_rotate()
bool kcenon::logger::rotating_file_writer::should_rotate () const protected
Check if rotation is needed.
Definition at line 98 of file rotating_file_writer.cpp.
References daily, kcenon::logger::file_writer::get_file_size(), hourly, should_rotate_by_time(), size, and size_and_time.
Referenced by write().
should_rotate_by_time()
bool kcenon::logger::rotating_file_writer::should_rotate_by_time () const protected
Check if time-based rotation is needed.
Definition at line 238 of file rotating_file_writer.cpp.
References daily, hourly, and size_and_time.
Referenced by should_rotate().
write()
result_void kcenon::logger::rotating_file_writer::write (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write with rotation check.
Reimplemented from kcenon::logger::file_writer.
Definition at line 79 of file rotating_file_writer.cpp.
References rotate(), should_rotate(), and kcenon::logger::file_writer::write().
The documentation for this class was generated from the following files:
libraries/logger_system/include/kcenon/logger/writers/rotating_file_writer.h
libraries/logger_system/src/impl/writers/rotating_file_writer.cpp