Messaging System: event_pipeline Class Reference
event_pipeline Class Reference
Public Member Functions
event_pipeline ()
void setupPipeline ()
void setupMessageHandlers ()
raw_event validateEvent (const raw_event &event)
processed_event enrichEvent (const raw_event &event)
processed_event transformEvent (const processed_event &event)
aggregated_data aggregateEvent (const processed_event &event)
void handleRawEvent (const core::message &msg)
void handlePipelineControl (const core::message &msg)
void handleDataQuery (const core::message &msg)
void sendToDeadLetterQueue (const raw_event &event, const std::string &reason)
void retryDeadLetterEvents ()
void startProcessingThreads ()
void publishAggregatedData (const aggregated_data &data)
void startEventGenerator ()
void startMetricsCollector ()
void pausePipeline ()
void resumePipeline ()
void flushPipeline ()
void printPipelineStats ()
void sendAggregatedData ()
void sendProcessedEvents ()
void sendPipelineMetrics ()
void start ()
void stop ()
Detailed Description
Definition at line 120 of file event_pipeline.cpp.
Constructor & Destructor Documentation
event_pipeline()
event_pipeline::event_pipeline () inline
Definition at line 155 of file event_pipeline.cpp.
References kcenon::messaging::config::config_builder::build(), kcenon::messaging::config::config_builder::enable_compression(), kcenon::messaging::config::config_builder::enable_external_monitoring(), kcenon::messaging::config::config_builder::set_container_max_size(), kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), kcenon::messaging::config::config_builder::set_worker_threads(), setupMessageHandlers(), and setupPipeline().
Member Function Documentation
aggregateEvent()
aggregated_data event_pipeline::aggregateEvent (const processed_event & event) inline
Definition at line 355 of file event_pipeline.cpp.
References aggregated_data::avg_score, aggregated_data::event_count, aggregated_data::metric_sums, aggregated_data::tag_frequency, aggregated_data::window_end, aggregated_data::window_id, and aggregated_data::window_start.
Referenced by setupPipeline().
enrichEvent()
processed_event event_pipeline::enrichEvent (const raw_event & event) inline
Definition at line 281 of file event_pipeline.cpp.
References processed_event::category, processed_event::id, processed_event::metrics, processed_event::score, raw_event::source, processed_event::tags, raw_event::timestamp, raw_event::type, and processed_event::valid.
Referenced by setupPipeline().
flushPipeline()
void event_pipeline::flushPipeline () inline
Definition at line 625 of file event_pipeline.cpp.
Referenced by handlePipelineControl(), and stop().
handleDataQuery()
void event_pipeline::handleDataQuery (const core::message & msg) inline
Definition at line 445 of file event_pipeline.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, sendAggregatedData(), sendPipelineMetrics(), and sendProcessedEvents().
Referenced by setupMessageHandlers().
handlePipelineControl()
void event_pipeline::handlePipelineControl (const core::message & msg) inline
Definition at line 431 of file event_pipeline.cpp.
References flushPipeline(), kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, pausePipeline(), printPipelineStats(), and resumePipeline().
Referenced by setupMessageHandlers().
handleRawEvent()
void event_pipeline::handleRawEvent (const core::message & msg) inline
Definition at line 405 of file event_pipeline.cpp.
References kcenon::messaging::core::message_payload::get(), kcenon::messaging::core::message_metadata::headers, raw_event::id, kcenon::messaging::core::message::metadata, and kcenon::messaging::core::message::payload.
Referenced by setupMessageHandlers().
pausePipeline()
void event_pipeline::pausePipeline () inline
Definition at line 615 of file event_pipeline.cpp.
Referenced by handlePipelineControl().
printPipelineStats()
void event_pipeline::printPipelineStats () inline
Definition at line 636 of file event_pipeline.cpp.
Referenced by handlePipelineControl(), start(), and stop().
publishAggregatedData()
void event_pipeline::publishAggregatedData (const aggregated_data & data) inline
Definition at line 541 of file event_pipeline.cpp.
References aggregated_data::avg_score, aggregated_data::event_count, kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, aggregated_data::tag_frequency, and aggregated_data::window_id.
Referenced by sendAggregatedData(), and startProcessingThreads().
resumePipeline()
void event_pipeline::resumePipeline () inline
Definition at line 620 of file event_pipeline.cpp.
Referenced by handlePipelineControl().
retryDeadLetterEvents()
void event_pipeline::retryDeadLetterEvents () inline
Definition at line 468 of file event_pipeline.cpp.
Referenced by setupMessageHandlers().
sendAggregatedData()
void event_pipeline::sendAggregatedData () inline
Definition at line 665 of file event_pipeline.cpp.
References publishAggregatedData().
Referenced by handleDataQuery().
sendPipelineMetrics()
void event_pipeline::sendPipelineMetrics () inline
Definition at line 683 of file event_pipeline.cpp.
References kcenon::messaging::core::message_metadata::headers, and kcenon::messaging::core::message::metadata.
Referenced by handleDataQuery().
sendProcessedEvents()
void event_pipeline::sendProcessedEvents () inline
Definition at line 675 of file event_pipeline.cpp.
Referenced by handleDataQuery().
sendToDeadLetterQueue()
void event_pipeline::sendToDeadLetterQueue (const raw_event & event, const std::string & reason) inline
Definition at line 457 of file event_pipeline.cpp.
References raw_event::id.
Referenced by setupPipeline().
setupMessageHandlers()
void event_pipeline::setupMessageHandlers () inline
Definition at line 228 of file event_pipeline.cpp.
References handleDataQuery(), handlePipelineControl(), handleRawEvent(), and retryDeadLetterEvents().
Referenced by event_pipeline().
setupPipeline()
void event_pipeline::setupPipeline () inline
Definition at line 183 of file event_pipeline.cpp.
References aggregateEvent(), enrichEvent(), sendToDeadLetterQueue(), transformEvent(), and validateEvent().
Referenced by event_pipeline().
start()
void event_pipeline::start () inline
Definition at line 693 of file event_pipeline.cpp.
References printPipelineStats(), startEventGenerator(), startMetricsCollector(), startProcessingThreads(), and stop().
Referenced by main().
startEventGenerator()
void event_pipeline::startEventGenerator () inline
Definition at line 560 of file event_pipeline.cpp.
Referenced by start().
startMetricsCollector()
void event_pipeline::startMetricsCollector () inline
Definition at line 589 of file event_pipeline.cpp.
References kcenon::messaging::core::message_metadata::headers, and kcenon::messaging::core::message::metadata.
Referenced by start().
startProcessingThreads()
void event_pipeline::startProcessingThreads () inline
Definition at line 487 of file event_pipeline.cpp.
References publishAggregatedData().
Referenced by start().
stop()
void event_pipeline::stop () inline
Definition at line 719 of file event_pipeline.cpp.
References flushPipeline(), and printPipelineStats().
Referenced by start().
transformEvent()
processed_event event_pipeline::transformEvent (const processed_event & event) inline
Definition at line 329 of file event_pipeline.cpp.
References processed_event::category, processed_event::metrics, processed_event::score, and processed_event::tags.
Referenced by setupPipeline().
validateEvent()
raw_event event_pipeline::validateEvent (const raw_event & event) inline
Definition at line 252 of file event_pipeline.cpp.
References raw_event::id, raw_event::source, raw_event::timestamp, and raw_event::type.
Referenced by setupPipeline().
The documentation for this class was generated from the following file:
application_layer/samples/event_pipeline.cpp