Messaging System: libraries/thread_system/unittest/thread_base_test/mpmc_queue_test.cpp File Reference
mpmc_queue_test.cpp File Reference
#include "gtest/gtest.h"
#include <kcenon/thread/core/job_queue.h>
#include <kcenon/thread/core/callback_job.h>
#include <thread>
#include <vector>
#include <atomic>
#include <random>
#include <chrono>
#include <algorithm>
Classes
class MPMCQueueTest
Functions
TEST_F (MPMCQueueTest, BasicEnqueueDequeue)
TEST_F (MPMCQueueTest, EmptyQueueDequeue)
TEST_F (MPMCQueueTest, NullJobEnqueue)
TEST_F (MPMCQueueTest, BatchOperations)
TEST_F (MPMCQueueTest, ConcurrentEnqueue)
TEST_F (MPMCQueueTest, ConcurrentDequeue)
TEST_F (MPMCQueueTest, ProducerConsumerStress)
TEST_F (MPMCQueueTest, AdaptiveQueueBasicOperation)
TEST_F (MPMCQueueTest, AdaptiveQueueStrategySwitch)
TEST_F (MPMCQueueTest, PerformanceComparison)
TEST_F (MPMCQueueTest, SimpleMPMCPerformance)
TEST_F (MPMCQueueTest, MultipleProducerConsumer)
TEST_F (MPMCQueueTest, SingleThreadedSafety)
Function Documentation
TEST_F() [1/13]
TEST_F (MPMCQueueTest , AdaptiveQueueBasicOperation)
Definition at line 427 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::dequeue(), kcenon::thread::job_queue::empty(), and kcenon::thread::job_queue::enqueue().
TEST_F() [2/13]
TEST_F (MPMCQueueTest , AdaptiveQueueStrategySwitch)
Definition at line 443 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::empty(), kcenon::thread::job_queue::enqueue(), and kcenon::thread::job_queue::try_dequeue().
TEST_F() [3/13]
TEST_F (MPMCQueueTest , BasicEnqueueDequeue)
Definition at line 77 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::dequeue(), kcenon::thread::job_queue::empty(), kcenon::thread::job_queue::enqueue(), and kcenon::thread::job_queue::size().
TEST_F() [4/13]
TEST_F (MPMCQueueTest , BatchOperations)
Definition at line 129 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::dequeue(), kcenon::thread::job_queue::dequeue_batch(), kcenon::thread::job::do_work(), kcenon::thread::job_queue::empty(), kcenon::thread::job_queue::enqueue(), kcenon::thread::job_queue::enqueue_batch(), and kcenon::thread::job_queue::size().
TEST_F() [5/13]
TEST_F (MPMCQueueTest , ConcurrentDequeue)
Definition at line 236 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::enqueue(), kcenon::thread::result< T >::has_value(), kcenon::thread::job_queue::size(), kcenon::thread::job_queue::try_dequeue(), and kcenon::thread::result< T >::value().
TEST_F() [6/13]
TEST_F (MPMCQueueTest , ConcurrentEnqueue)
Definition at line 186 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::dequeue(), kcenon::thread::job_queue::empty(), kcenon::thread::job_queue::enqueue(), kcenon::thread::result< T >::has_value(), kcenon::thread::job_queue::size(), and kcenon::thread::result< T >::value().
TEST_F() [7/13]
TEST_F (MPMCQueueTest , EmptyQueueDequeue)
Definition at line 108 of file mpmc_queue_test.cpp.
References kcenon::thread::error::code(), kcenon::thread::result< T >::get_error(), kcenon::thread::result< T >::has_value(), and kcenon::thread::job_queue::try_dequeue().
TEST_F() [8/13]
TEST_F (MPMCQueueTest , MultipleProducerConsumer)
Definition at line 596 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::enqueue(), kcenon::thread::result< T >::has_value(), kcenon::thread::job_queue::try_dequeue(), and kcenon::thread::result< T >::value().
TEST_F() [9/13]
TEST_F (MPMCQueueTest , NullJobEnqueue)
Definition at line 118 of file mpmc_queue_test.cpp.
References kcenon::thread::error::code(), kcenon::thread::job_queue::enqueue(), and kcenon::thread::result< T >::get_error().
TEST_F() [10/13]
TEST_F (MPMCQueueTest , PerformanceComparison)
Definition at line 467 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::dequeue(), and kcenon::thread::job_queue::enqueue().
TEST_F() [11/13]
TEST_F (MPMCQueueTest , ProducerConsumerStress)
Definition at line 291 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::dequeue(), kcenon::thread::job_queue::empty(), kcenon::thread::job_queue::enqueue(), kcenon::thread::result< T >::has_value(), and kcenon::thread::result< T >::value().
TEST_F() [12/13]
TEST_F (MPMCQueueTest , SimpleMPMCPerformance)
Definition at line 526 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::enqueue(), kcenon::thread::result< T >::has_value(), kcenon::thread::job_queue::try_dequeue(), and kcenon::thread::result< T >::value().
TEST_F() [13/13]
TEST_F (MPMCQueueTest , SingleThreadedSafety)
Definition at line 684 of file mpmc_queue_test.cpp.
References kcenon::thread::job_queue::dequeue(), kcenon::thread::job_queue::empty(), kcenon::thread::job_queue::enqueue(), kcenon::thread::result< T >::has_value(), kcenon::thread::job_queue::size(), and kcenon::thread::result< T >::value().