Messaging System: logger_system::testing::mock_di_container Class Reference
logger_system::testing::mock_di_container Class Reference
Mock DI container for unit testing.
#include <mock_di_container.hpp>
Public Member Functions
mock_di_container ()=default
~mock_di_container () override=default
result< std::shared_ptr< base_writer > > resolve (const std::string &name) override
Resolve a component by name.
result_void register_factory (const std::string &name, std::function< std::shared_ptr< base_writer >()> factory)
Register a factory function for creating components.
result_void register_singleton (const std::string &name, std::shared_ptr< base_writer > instance) override
Register a singleton instance.
bool is_registered (const std::string &name) const override
Check if a component is registered.
result_void clear () override
Clear all registrations.
size_t size () const override
Get the number of registered components.
result_void register_instance (const std::string &name, std::shared_ptr< base_writer > instance)
void set_should_fail (bool fail, logger_error_code error=logger_error_code::component_not_found)
void set_use_singletons (bool use)
void reset ()
size_t get_resolution_count (const std::string &name) const
std::vector< std::string > get_registered_names () const
bool has_component (const std::string &name) const
Public Member Functions inherited from kcenon::logger::di_container_interface< base_writer >
virtual ~di_container_interface ()=default
Virtual destructor.
Detailed Description
Mock DI container for unit testing.
Provides controllable dependency injection behavior for testing DI integration and component resolution scenarios.
Definition at line 30 of file mock_di_container.hpp.
Constructor & Destructor Documentation
mock_di_container()
logger_system::testing::mock_di_container::mock_di_container () default
~mock_di_container()
logger_system::testing::mock_di_container::~mock_di_container () override default
Member Function Documentation
clear()
result_void logger_system::testing::mock_di_container::clear () inline override virtual
Clear all registrations.
Returns
Result indicating success or error
Implements kcenon::logger::di_container_interface< base_writer >.
Definition at line 109 of file mock_di_container.hpp.
get_registered_names()
std::vector< std::string > logger_system::testing::mock_di_container::get_registered_names () const inline
Definition at line 159 of file mock_di_container.hpp.
get_resolution_count()
size_t logger_system::testing::mock_di_container::get_resolution_count (const std::string & name) const inline
Definition at line 153 of file mock_di_container.hpp.
has_component()
bool logger_system::testing::mock_di_container::has_component (const std::string & name) const inline
Definition at line 168 of file mock_di_container.hpp.
is_registered()
bool logger_system::testing::mock_di_container::is_registered (const std::string & name) const inline override virtual
Check if a component is registered.
Parameters
name The name to check
Returns
true if registered, false otherwise
Implements kcenon::logger::di_container_interface< base_writer >.
Definition at line 103 of file mock_di_container.hpp.
register_factory()
result_void logger_system::testing::mock_di_container::register_factory (const std::string & name, std::function< std::shared_ptr< base_writer >()> factory) inline virtual
Register a factory function for creating components.
Parameters
name The name to register the factory under
factory Function that creates instances of T
Returns
Result indicating success or error
Implements kcenon::logger::di_container_interface< base_writer >.
Definition at line 80 of file mock_di_container.hpp.
References kcenon::logger::make_logger_error().
register_instance()
result_void logger_system::testing::mock_di_container::register_instance (const std::string & name, std::shared_ptr< base_writer > instance) inline
Definition at line 122 of file mock_di_container.hpp.
References kcenon::logger::make_logger_error().
register_singleton()
result_void logger_system::testing::mock_di_container::register_singleton (const std::string & name, std::shared_ptr< base_writer > instance) inline override virtual
Register a singleton instance.
Parameters
name The name to register the instance under
instance The singleton instance to register
Returns
Result indicating success or error
Implements kcenon::logger::di_container_interface< base_writer >.
Definition at line 92 of file mock_di_container.hpp.
References kcenon::logger::make_logger_error().
reset()
void logger_system::testing::mock_di_container::reset () inline
Definition at line 143 of file mock_di_container.hpp.
resolve()
result< std::shared_ptr< base_writer > > logger_system::testing::mock_di_container::resolve (const std::string & name) inline override virtual
Resolve a component by name.
Parameters
name The registered name of the component
Returns
Result containing the resolved component or error
Implements kcenon::logger::di_container_interface< base_writer >.
Definition at line 47 of file mock_di_container.hpp.
References logger_system::component_not_found.
set_should_fail()
void logger_system::testing::mock_di_container::set_should_fail (bool fail, logger_error_code error = logger_error_code::component_not_found) inline
Definition at line 134 of file mock_di_container.hpp.
References logger_system::error.
set_use_singletons()
void logger_system::testing::mock_di_container::set_use_singletons (bool use) inline
Definition at line 139 of file mock_di_container.hpp.
size()
size_t logger_system::testing::mock_di_container::size () const inline override virtual
Get the number of registered components.
Returns
Number of registered components
Implements kcenon::logger::di_container_interface< base_writer >.
Definition at line 116 of file mock_di_container.hpp.
The documentation for this class was generated from the following file:
libraries/logger_system/tests/unit/mocks/mock_di_container.hpp