Messaging System: libraries/thread_system/tests/benchmarks/typed_thread_pool_benchmarks/typed_scheduling_benchmark_google.cpp File Reference
typed_scheduling_benchmark_google.cpp File Reference
Priority-based thread pool scheduling benchmark using Google Benchmark.
#include <benchmark/benchmark.h>
#include <vector>
#include <thread>
#include <atomic>
#include <random>
#include <queue>
#include <map>
#include <algorithm>
#include <mutex>
#include <chrono>
#include <future>
#include "../../sources/typed_thread_pool/pool/typed_thread_pool.h"
#include "../../sources/utilities/core/formatter.h"
Classes
struct JobExecutionRecord
Functions
static void submit_test_job (std::shared_ptr< typed_thread_pool > pool, size_t job_id, job_types priority, milliseconds work_duration)
static std::shared_ptr< typed_thread_pool > setup_priority_pool (size_t num_workers=4)
static void BM_BasicPriorityOrdering (benchmark::State &state)
Benchmark basic priority ordering.
Arg (25) -> Arg(50) ->Arg(100) ->Unit(benchmark::kMillisecond)
static void BM_PriorityFairness (benchmark::State &state)
Benchmark priority fairness under mixed load.
Arg (500) -> Arg(1000) ->Unit(benchmark::kMillisecond)
static void BM_PriorityInversion (benchmark::State &state)
Benchmark priority inversion scenarios.
Args ({50, 10}) -> Args({100, 20}) ->Unit(benchmark::kMillisecond)
static void BM_StarvationResistance (benchmark::State &state)
Benchmark starvation resistance.
Args ({500, 50}) -> Unit(benchmark::kMillisecond) ->UseRealTime()
static void BM_MixedPriorityWorkload (benchmark::State &state)
Benchmark mixed priority workload performance.
Arg (5000) -> UseManualTime() ->Unit(benchmark::kSecond)
BENCHMARK_MAIN ()
Variables
static std::vector< JobExecutionRecord > g_execution_records
static std::mutex g_records_mutex
Detailed Description
Priority-based thread pool scheduling benchmark using Google Benchmark.
Tests priority scheduling effectiveness, fairness, and performance under various load conditions and priority distributions.
Definition in file typed_scheduling_benchmark_google.cpp.
Function Documentation
Arg() [1/3]
Arg (25) -> Arg(50) ->Arg(100) ->Unit(benchmark::kMillisecond)
Arg() [2/3]
Arg (500) -> Arg(1000) ->Unit(benchmark::kMillisecond)
Arg() [3/3]
Arg (5000) -> UseManualTime() ->Unit(benchmark::kSecond)
Args() [1/2]
Args ({50, 10}) -> Args({100, 20}) ->Unit(benchmark::kMillisecond)
Args() [2/2]
Args ({500, 50}) -> Unit(benchmark::kMillisecond) ->UseRealTime()
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_BasicPriorityOrdering()
static void BM_BasicPriorityOrdering (benchmark::State & state) static
Benchmark basic priority ordering.
Definition at line 129 of file typed_scheduling_benchmark_google.cpp.
References g_execution_records, g_records_mutex, kcenon::thread::priority, setup_priority_pool(), and submit_test_job().
BM_MixedPriorityWorkload()
static void BM_MixedPriorityWorkload (benchmark::State & state) static
Benchmark mixed priority workload performance.
Definition at line 425 of file typed_scheduling_benchmark_google.cpp.
References g_execution_records, g_records_mutex, kcenon::thread::priority, setup_priority_pool(), and submit_test_job().
BM_PriorityFairness()
static void BM_PriorityFairness (benchmark::State & state) static
Benchmark priority fairness under mixed load.
Definition at line 199 of file typed_scheduling_benchmark_google.cpp.
References g_execution_records, g_records_mutex, kcenon::thread::priority, setup_priority_pool(), and submit_test_job().
BM_PriorityInversion()
static void BM_PriorityInversion (benchmark::State & state) static
Benchmark priority inversion scenarios.
Definition at line 275 of file typed_scheduling_benchmark_google.cpp.
References g_execution_records, g_records_mutex, setup_priority_pool(), and submit_test_job().
BM_StarvationResistance()
static void BM_StarvationResistance (benchmark::State & state) static
Benchmark starvation resistance.
Definition at line 348 of file typed_scheduling_benchmark_google.cpp.
References g_execution_records, g_records_mutex, setup_priority_pool(), and submit_test_job().
setup_priority_pool()
static std::shared_ptr< typed_thread_pool > setup_priority_pool (size_t num_workers = 4) static
Definition at line 99 of file typed_scheduling_benchmark_google.cpp.
Referenced by BM_BasicPriorityOrdering(), BM_MixedPriorityWorkload(), BM_PriorityFairness(), BM_PriorityInversion(), and BM_StarvationResistance().
submit_test_job()
static void submit_test_job (std::shared_ptr< typed_thread_pool > pool, size_t job_id, job_types priority, milliseconds work_duration) static
Definition at line 56 of file typed_scheduling_benchmark_google.cpp.
References JobExecutionRecord::complete_time, g_execution_records, g_records_mutex, JobExecutionRecord::job_id, JobExecutionRecord::priority, kcenon::thread::priority, JobExecutionRecord::start_time, and JobExecutionRecord::submit_time.
Referenced by BM_BasicPriorityOrdering(), BM_MixedPriorityWorkload(), BM_PriorityFairness(), BM_PriorityInversion(), and BM_StarvationResistance().
Variable Documentation
g_execution_records
std::vector<JobExecutionRecord> g_execution_records static
Definition at line 52 of file typed_scheduling_benchmark_google.cpp.
Referenced by BM_BasicPriorityOrdering(), BM_MixedPriorityWorkload(), BM_PriorityFairness(), BM_PriorityInversion(), BM_StarvationResistance(), and submit_test_job().
g_records_mutex
std::mutex g_records_mutex static
Definition at line 53 of file typed_scheduling_benchmark_google.cpp.
Referenced by BM_BasicPriorityOrdering(), BM_MixedPriorityWorkload(), BM_PriorityFairness(), BM_PriorityInversion(), BM_StarvationResistance(), and submit_test_job().