Messaging System: logger_module::router_builder Class Reference
logger_module::router_builder Class Reference
Fluent builder for creating routing rules.
#include <log_router.h>
Public Member Functions
router_builder (log_router &router)
router_builder & when_level (thread_module::log_level min_level)
router_builder & when_matches (const std::string &pattern)
router_builder & when_not_matches (const std::string &pattern)
router_builder & when (std::unique_ptr< log_filter > filter)
router_builder & route_to (const std::vector< std::string > &writer_names, bool stop_propagation=false)
router_builder & route_to (const std::string &writer_name, bool stop_propagation=false)
Detailed Description
Fluent builder for creating routing rules.
Definition at line 150 of file log_router.h.
Constructor & Destructor Documentation
router_builder()
logger_module::router_builder::router_builder (log_router & router) inline explicit
Definition at line 152 of file log_router.h.
Member Function Documentation
route_to() [1/2]
router_builder & logger_module::router_builder::route_to (const std::string & writer_name, bool stop_propagation = false) inline
Definition at line 188 of file log_router.h.
References route_to().
route_to() [2/2]
router_builder & logger_module::router_builder::route_to (const std::vector< std::string > & writer_names, bool stop_propagation = false) inline
Definition at line 179 of file log_router.h.
References logger_module::log_router::add_route().
Referenced by main(), route_to(), and TEST_F().
when()
router_builder & logger_module::router_builder::when (std::unique_ptr< log_filter > filter) inline
Definition at line 173 of file log_router.h.
when_level()
router_builder & logger_module::router_builder::when_level (thread_module::log_level min_level) inline
Definition at line 155 of file log_router.h.
Referenced by main(), and TEST_F().
when_matches()
router_builder & logger_module::router_builder::when_matches (const std::string & pattern) inline
Definition at line 161 of file log_router.h.
Referenced by main().
when_not_matches()
router_builder & logger_module::router_builder::when_not_matches (const std::string & pattern) inline
Definition at line 167 of file log_router.h.
The documentation for this class was generated from the following file:
libraries/logger_system/sources/logger/routing/log_router.h