Messaging System: network_system::integration::container_manager::impl Class Reference
network_system::integration::container_manager::impl Class Reference
Public Member Functions
impl ()=default
void register_container (const std::string &name, std::shared_ptr< container_interface > container)
std::shared_ptr< container_interface > get_container (const std::string &name) const
void set_default_container (std::shared_ptr< container_interface > container)
std::shared_ptr< container_interface > get_default_container ()
std::vector< uint8_t > serialize (const std::any &data)
std::any deserialize (const std::vector< uint8_t > &bytes)
std::vector< std::string > list_containers () const
Detailed Description
Definition at line 171 of file container_integration.cpp.
Constructor & Destructor Documentation
impl()
network_system::integration::container_manager::impl::impl () default
Member Function Documentation
deserialize()
std::any network_system::integration::container_manager::impl::deserialize (const std::vector< uint8_t > & bytes) inline
Definition at line 213 of file container_integration.cpp.
References get_default_container().
get_container()
std::shared_ptr< container_interface > network_system::integration::container_manager::impl::get_container (const std::string & name) const inline
Definition at line 183 of file container_integration.cpp.
get_default_container()
std::shared_ptr< container_interface > network_system::integration::container_manager::impl::get_default_container () inline
Definition at line 201 of file container_integration.cpp.
Referenced by deserialize(), and serialize().
list_containers()
std::vector< std::string > network_system::integration::container_manager::impl::list_containers () const inline
Definition at line 217 of file container_integration.cpp.
register_container()
void network_system::integration::container_manager::impl::register_container (const std::string & name, std::shared_ptr< container_interface > container) inline
Definition at line 175 of file container_integration.cpp.
serialize()
std::vector< uint8_t > network_system::integration::container_manager::impl::serialize (const std::any & data) inline
Definition at line 209 of file container_integration.cpp.
References get_default_container().
set_default_container()
void network_system::integration::container_manager::impl::set_default_container (std::shared_ptr< container_interface > container) inline
Definition at line 194 of file container_integration.cpp.
The documentation for this class was generated from the following file:
libraries/network_system/src/integration/container_integration.cpp