Messaging System: monitoring_system::otlp_exporter Class Reference
monitoring_system::otlp_exporter Class Reference
OpenTelemetry Protocol (OTLP) trace exporter implementation.
#include <trace_exporters.h>
Public Member Functions
otlp_exporter (const trace_export_config &config, const otel_resource &resource)
result_void export_spans (const std::vector< trace_span > &spans) override
Export a batch of spans.
result_void flush () override
Flush any pending spans.
result_void shutdown () override
Shutdown the exporter.
std::unordered_map< std::string, std::size_t > get_stats () const override
Get exporter statistics.
Public Member Functions inherited from monitoring_system::trace_exporter_interface
virtual ~trace_exporter_interface ()=default
Detailed Description
OpenTelemetry Protocol (OTLP) trace exporter implementation.
Definition at line 416 of file trace_exporters.h.
Constructor & Destructor Documentation
otlp_exporter()
monitoring_system::otlp_exporter::otlp_exporter (const trace_export_config & config, const otel_resource & resource) inline explicit
Definition at line 425 of file trace_exporters.h.
Member Function Documentation
export_spans()
result_void monitoring_system::otlp_exporter::export_spans (const std::vector< trace_span > & spans) inline override virtual
Export a batch of spans.
Implements monitoring_system::trace_exporter_interface.
Definition at line 428 of file trace_exporters.h.
References monitoring_system::trace_export_config::format, monitoring_system::invalid_configuration, monitoring_system::operation_failed, monitoring_system::otlp_grpc, monitoring_system::otlp_http_json, monitoring_system::otlp_http_protobuf, and monitoring_system::processing_failed.
Referenced by TEST_F(), TEST_F(), and TEST_F().
flush()
result_void monitoring_system::otlp_exporter::flush () inline override virtual
Flush any pending spans.
Implements monitoring_system::trace_exporter_interface.
Definition at line 469 of file trace_exporters.h.
Referenced by shutdown(), and TEST_F().
get_stats()
std::unordered_map< std::string, std::size_t > monitoring_system::otlp_exporter::get_stats () const inline override virtual
Get exporter statistics.
Implements monitoring_system::trace_exporter_interface.
Definition at line 478 of file trace_exporters.h.
Referenced by TEST_F(), and TEST_F().
shutdown()
result_void monitoring_system::otlp_exporter::shutdown () inline override virtual
Shutdown the exporter.
Implements monitoring_system::trace_exporter_interface.
Definition at line 474 of file trace_exporters.h.
References flush().
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/exporters/trace_exporters.h