Messaging System: network_system::integration::logger_integration_manager::impl Class Reference
network_system::integration::logger_integration_manager::impl Class Reference
Public Member Functions
impl ()
void set_logger (std::shared_ptr< logger_interface > logger)
std::shared_ptr< logger_interface > get_logger ()
void log (log_level level, const std::string &message)
void log (log_level level, const std::string &message, const std::string &file, int line, const std::string &function)
Detailed Description
Definition at line 277 of file logger_integration.cpp.
Constructor & Destructor Documentation
impl()
network_system::integration::logger_integration_manager::impl::impl () inline
Definition at line 279 of file logger_integration.cpp.
Member Function Documentation
get_logger()
std::shared_ptr< logger_interface > network_system::integration::logger_integration_manager::impl::get_logger () inline
Definition at line 293 of file logger_integration.cpp.
Referenced by log(), and log().
log() [1/2]
void network_system::integration::logger_integration_manager::impl::log (log_level level, const std::string & message) inline
Definition at line 301 of file logger_integration.cpp.
References get_logger().
log() [2/2]
void network_system::integration::logger_integration_manager::impl::log (log_level level, const std::string & message, const std::string & file, int line, const std::string & function) inline
Definition at line 308 of file logger_integration.cpp.
References get_logger().
set_logger()
void network_system::integration::logger_integration_manager::impl::set_logger (std::shared_ptr< logger_interface > logger) inline
Definition at line 288 of file logger_integration.cpp.
The documentation for this class was generated from the following file:
libraries/network_system/src/integration/logger_integration.cpp