Messaging System: logger_module::logger Class Reference
logger_module::logger Class Reference
Main logger implementation that implements thread_system's logger_interface.
#include <logger.h>
Classes
class impl
Public Member Functions
logger (bool async=true, std::size_t buffer_size=8192)
Constructor with optional configuration.
~logger () override
Destructor - ensures all logs are flushed.
void log (thread_module::log_level level, const std::string &message) override
Log a message with specified level.
void log (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function) override
Log a message with source location information.
bool is_enabled (thread_module::log_level level) const override
Check if logging is enabled for the specified level.
void flush () override
Flush any buffered log messages.
void add_writer (std::unique_ptr< base_writer > writer)
Add a writer to output logs.
void clear_writers ()
Remove all writers.
void set_min_level (thread_module::log_level level)
Set the minimum log level.
thread_module::log_level get_min_level () const
Get the minimum log level.
void start ()
Start the logger (for async mode)
void stop ()
Stop the logger.
bool is_running () const
Check if logger is running.
void enable_metrics_collection (bool enable=true)
Enable or disable metrics collection.
bool is_metrics_collection_enabled () const
Check if metrics collection is enabled.
performance_metrics get_current_metrics () const
Get current performance metrics.
std::unique_ptr< performance_metrics > get_metrics_history (std::chrono::seconds duration) const
Get metrics history for a specific duration.
void reset_metrics ()
Reset performance metrics.
logger_metrics_collector * get_metrics_collector ()
Get metrics collector for direct access.
void add_writer (const std::string &name, std::unique_ptr< base_writer > writer)
Add a writer with a specific name.
bool remove_writer (const std::string &name)
Remove a writer by name.
base_writer * get_writer (const std::string &name)
Get a writer by name.
void set_filter (std::unique_ptr< log_filter > filter)
Set global filter.
log_router & get_router ()
Get the log router for configuration.
Public Member Functions inherited from thread_module::logger_interface
virtual ~logger_interface ()=default
virtual ~logger_interface ()=default
virtual ~logger_interface ()=default
Detailed Description
Main logger implementation that implements thread_system's logger_interface.
This logger provides:
Lock-free logging for high performance
Multiple writer support (console, file, custom)
Asynchronous processing
Thread-safe operations
Definition at line 65 of file logger.h.
Constructor & Destructor Documentation
logger()
logger_module::logger::logger (bool async = true, std::size_t buffer_size = 8192) explicit
Constructor with optional configuration.
Parameters
async Enable asynchronous logging (default: true)
buffer_size Size of the log buffer (default: 8192)
Definition at line 293 of file logger.cpp.
~logger()
logger_module::logger::~logger () override default
Destructor - ensures all logs are flushed.
Member Function Documentation
add_writer() [1/2]
void logger_module::logger::add_writer (const std::string & name, std::unique_ptr< base_writer > writer)
Add a writer with a specific name.
Parameters
name Name for the writer
writer Unique pointer to the writer
Definition at line 368 of file logger.cpp.
add_writer() [2/2]
void logger_module::logger::add_writer (std::unique_ptr< base_writer > writer)
Add a writer to output logs.
Parameters
writer Unique pointer to the writer
Definition at line 316 of file logger.cpp.
Referenced by main(), simulate_client(), test_access_control(), test_combined_security(), test_encryption(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), test_sanitization(), and test_sanitizing_filter().
clear_writers()
void logger_module::logger::clear_writers ()
Remove all writers.
Definition at line 320 of file logger.cpp.
enable_metrics_collection()
void logger_module::logger::enable_metrics_collection (bool enable = true)
Enable or disable metrics collection.
Parameters
enable true to enable metrics collection
Definition at line 344 of file logger.cpp.
Referenced by main(), TEST_F(), and TEST_F().
flush()
void logger_module::logger::flush () override virtual
Flush any buffered log messages.
Implements thread_module::logger_interface.
Definition at line 312 of file logger.cpp.
Referenced by main(), simulate_client(), test_combined_security(), test_encryption(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
get_current_metrics()
performance_metrics logger_module::logger::get_current_metrics () const
Get current performance metrics.
Returns
Snapshot of current metrics
Definition at line 352 of file logger.cpp.
Referenced by main(), TEST_F(), and TEST_F().
get_metrics_collector()
logger_metrics_collector * logger_module::logger::get_metrics_collector ()
Get metrics collector for direct access.
Returns
Pointer to metrics collector (may be null if not enabled)
Definition at line 364 of file logger.cpp.
get_metrics_history()
std::unique_ptr< performance_metrics > logger_module::logger::get_metrics_history (std::chrono::seconds duration) const
Get metrics history for a specific duration.
Parameters
duration How far back to retrieve metrics
Returns
Unique pointer to metrics snapshot (for Phase 1, only current snapshot)
Definition at line 356 of file logger.cpp.
get_min_level()
thread_module::log_level logger_module::logger::get_min_level () const
Get the minimum log level.
Returns
Current minimum log level
Definition at line 328 of file logger.cpp.
get_router()
log_router & logger_module::logger::get_router ()
Get the log router for configuration.
Returns
Reference to the log router
Definition at line 384 of file logger.cpp.
Referenced by main(), and TEST_F().
get_writer()
base_writer * logger_module::logger::get_writer (const std::string & name)
Get a writer by name.
Parameters
name Name of the writer
Returns
Pointer to writer or nullptr if not found
Definition at line 376 of file logger.cpp.
is_enabled()
bool logger_module::logger::is_enabled (thread_module::log_level level) const override virtual
Check if logging is enabled for the specified level.
Parameters
level Log level to check
Returns
true if logging is enabled for this level
Implements thread_module::logger_interface.
Definition at line 308 of file logger.cpp.
is_metrics_collection_enabled()
bool logger_module::logger::is_metrics_collection_enabled () const
Check if metrics collection is enabled.
Returns
true if metrics collection is enabled
Definition at line 348 of file logger.cpp.
is_running()
bool logger_module::logger::is_running () const
Check if logger is running.
Returns
true if running
Definition at line 340 of file logger.cpp.
log() [1/2]
void logger_module::logger::log (thread_module::log_level level, const std::string & message) override virtual
Log a message with specified level.
Parameters
level Log level
message Log message
Implements thread_module::logger_interface.
Definition at line 299 of file logger.cpp.
Referenced by generate_logs(), main(), simulate_client(), test_access_control(), test_encryption(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and test_sanitizing_filter().
log() [2/2]
void logger_module::logger::log (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function) override virtual
Log a message with source location information.
Parameters
level Log level
message Log message
file Source file name
line Source line number
function Function name
Implements thread_module::logger_interface.
Definition at line 303 of file logger.cpp.
remove_writer()
bool logger_module::logger::remove_writer (const std::string & name)
Remove a writer by name.
Parameters
name Name of the writer to remove
Returns
true if writer was found and removed
Definition at line 372 of file logger.cpp.
reset_metrics()
void logger_module::logger::reset_metrics ()
Reset performance metrics.
Definition at line 360 of file logger.cpp.
set_filter()
void logger_module::logger::set_filter (std::unique_ptr< log_filter > filter)
Set global filter.
Parameters
filter Filter to apply to all logs
Definition at line 380 of file logger.cpp.
Referenced by main(), test_access_control(), TEST_F(), and test_sanitizing_filter().
set_min_level()
void logger_module::logger::set_min_level (thread_module::log_level level)
Set the minimum log level.
Parameters
level Minimum level to log
Definition at line 324 of file logger.cpp.
start()
void logger_module::logger::start ()
Start the logger (for async mode)
Definition at line 332 of file logger.cpp.
Referenced by main(), and simulate_client().
stop()
void logger_module::logger::stop ()
Stop the logger.
Definition at line 336 of file logger.cpp.
Referenced by main(), and simulate_client().
The documentation for this class was generated from the following files:
libraries/logger_system/sources/logger/logger.h
libraries/logger_system/sources/logger/logger.cpp