Messaging System: libraries/logger_system/tests/benchmarks/logger_benchmarks/batch_processing_benchmark.cpp File Reference
batch_processing_benchmark.cpp File Reference
#include <benchmark/benchmark.h>
#include <logger/config/logger_builder.h>
#include <logger/writers/console_writer.h>
#include <memory>
#include <thread>
#include <vector>
Classes
class benchmark_writer
Placeholder benchmark for batch processing.
Functions
static void BM_SimulatedBatchWriting (benchmark::State &state)
Benchmark simulating batch vs direct writing.
Args ({0, 0}) -> Args({1, 10}) ->Args({1, 50}) ->Args({1, 100}) ->Args({1, 500})
static void BM_LoggerWithBatchConfig (benchmark::State &state)
Benchmark logger with batch configuration.
Arg (1) -> Arg(10) ->Arg(50) ->Arg(100) ->Arg(500)
static void BM_MultithreadedBatchSimulation (benchmark::State &state)
Benchmark multi-threaded logging with batching.
Args ({1, 10}) -> Args({2, 10}) ->Args({4, 10}) ->Args({1, 100}) ->Args({2, 100}) ->Args({4, 100})
BENCHMARK_MAIN ()
Function Documentation
Arg()
Arg (1) -> Arg(10) ->Arg(50) ->Arg(100) ->Arg(500)
Args() [1/2]
Args ({0, 0}) -> Args({1, 10}) ->Args({1, 50}) ->Args({1, 100}) ->Args({1, 500})
Referenced by database::async::async_executor::submit().
Args() [2/2]
Args ({1, 10}) -> Args({2, 10}) ->Args({4, 10}) ->Args({1, 100}) ->Args({2, 100}) ->Args({4, 100})
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_LoggerWithBatchConfig()
static void BM_LoggerWithBatchConfig (benchmark::State & state) static
Benchmark logger with batch configuration.
Definition at line 133 of file batch_processing_benchmark.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger::start(), kcenon::logger::logger_builder::with_async(), and kcenon::logger::logger_builder::with_batch_size().
BM_MultithreadedBatchSimulation()
static void BM_MultithreadedBatchSimulation (benchmark::State & state) static
Benchmark multi-threaded logging with batching.
Definition at line 172 of file batch_processing_benchmark.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger::start(), kcenon::logger::logger_builder::with_async(), and kcenon::logger::logger_builder::with_batch_size().
BM_SimulatedBatchWriting()
static void BM_SimulatedBatchWriting (benchmark::State & state) static
Benchmark simulating batch vs direct writing.
Definition at line 80 of file batch_processing_benchmark.cpp.