Messaging System: network_system::internal::detail Namespace Reference
network_system::internal::detail Namespace Reference
Functions
auto default_compress_stub (const std::vector< uint8_t > &data) -> std::vector< uint8_t >
auto default_decompress_stub (const std::vector< uint8_t > &data) -> std::vector< uint8_t >
auto default_encrypt_stub (const std::vector< uint8_t > &data) -> std::vector< uint8_t >
auto default_decrypt_stub (const std::vector< uint8_t > &data) -> std::vector< uint8_t >
Variables
constexpr std::string_view compress_debug_msg = "[debug] default_compress_stub"
constexpr std::string_view decompress_debug_msg = "[debug] default_decompress_stub"
constexpr std::string_view encrypt_debug_msg = "[debug] default_encrypt_stub"
constexpr std::string_view decrypt_debug_msg = "[debug] default_decrypt_stub"
Function Documentation
default_compress_stub()
auto network_system::internal::detail::default_compress_stub (const std::vector< uint8_t > & data) -> std::vector<uint8_t>
Definition at line 47 of file pipeline.cpp.
References compress_debug_msg, and NETWORK_LOG_TRACE.
Referenced by network_system::internal::make_default_pipeline().
default_decompress_stub()
auto network_system::internal::detail::default_decompress_stub (const std::vector< uint8_t > & data) -> std::vector<uint8_t>
Definition at line 55 of file pipeline.cpp.
References decompress_debug_msg, and NETWORK_LOG_TRACE.
Referenced by network_system::internal::make_default_pipeline().
default_decrypt_stub()
auto network_system::internal::detail::default_decrypt_stub (const std::vector< uint8_t > & data) -> std::vector<uint8_t>
Definition at line 71 of file pipeline.cpp.
References decrypt_debug_msg, and NETWORK_LOG_TRACE.
Referenced by network_system::internal::make_default_pipeline().
default_encrypt_stub()
auto network_system::internal::detail::default_encrypt_stub (const std::vector< uint8_t > & data) -> std::vector<uint8_t>
Definition at line 63 of file pipeline.cpp.
References encrypt_debug_msg, and NETWORK_LOG_TRACE.
Referenced by network_system::internal::make_default_pipeline().
Variable Documentation
compress_debug_msg
constexpr std::string_view network_system::internal::detail::compress_debug_msg = "[debug] default_compress_stub" inline constexpr
Definition at line 41 of file pipeline.cpp.
Referenced by default_compress_stub().
decompress_debug_msg
constexpr std::string_view network_system::internal::detail::decompress_debug_msg = "[debug] default_decompress_stub" inline constexpr
Definition at line 42 of file pipeline.cpp.
Referenced by default_decompress_stub().
decrypt_debug_msg
constexpr std::string_view network_system::internal::detail::decrypt_debug_msg = "[debug] default_decrypt_stub" inline constexpr
Definition at line 44 of file pipeline.cpp.
Referenced by default_decrypt_stub().
encrypt_debug_msg
constexpr std::string_view network_system::internal::detail::encrypt_debug_msg = "[debug] default_encrypt_stub" inline constexpr
Definition at line 43 of file pipeline.cpp.
Referenced by default_encrypt_stub().