Messaging System: typed_thread_pool_module::typed_thread_pool_builder< job_type > Class Template Reference
typed_thread_pool_module::typed_thread_pool_builder< job_type > Class Template Reference
Builder class for constructing typed thread pools.
#include <pool_builder.h>
Public Member Functions
typed_thread_pool_builder ()=default
Construct a new builder with default settings.
typed_thread_pool_builder & with_title (const std::string &title)
Set the title/name for the thread pool.
typed_thread_pool_builder & with_worker_count (size_t count)
Set the number of worker threads.
typed_thread_pool_builder & with_queue_size (size_t size)
Set the queue size for the thread pool.
typed_thread_pool_builder & with_job_types (const std::vector< job_type > &types)
Set the job types that workers should handle.
typed_thread_pool_builder & with_time_tagging (bool enable)
Enable or disable time tagging for workers.
typed_thread_pool_builder & with_auto_start (bool auto_start)
Enable or disable automatic pool startup.
bool validate () const
Validate the current configuration.
std::shared_ptr< typed_thread_pool_t< job_type > > build ()
Build the typed thread pool with current configuration.
typed_thread_pool_builder & reset ()
Reset the builder to default values.
typed_thread_pool_builder ()=default
Construct a new builder with default settings.
typed_thread_pool_builder & with_title (const std::string &title)
Set the title/name for the thread pool.
typed_thread_pool_builder & with_worker_count (size_t count)
Set the number of worker threads.
typed_thread_pool_builder & with_queue_size (size_t size)
Set the queue size for the thread pool.
typed_thread_pool_builder & with_job_types (const std::vector< job_type > &types)
Set the job types that workers should handle.
typed_thread_pool_builder & with_time_tagging (bool enable)
Enable or disable time tagging for workers.
typed_thread_pool_builder & with_auto_start (bool auto_start)
Enable or disable automatic pool startup.
bool validate () const
Validate the current configuration.
std::shared_ptr< typed_thread_pool_t< job_type > > build ()
Build the typed thread pool with current configuration.
typed_thread_pool_builder & reset ()
Reset the builder to default values.
typed_thread_pool_builder ()=default
Construct a new builder with default settings.
typed_thread_pool_builder & with_title (const std::string &title)
Set the title/name for the thread pool.
typed_thread_pool_builder & with_worker_count (size_t count)
Set the number of worker threads.
typed_thread_pool_builder & with_queue_size (size_t size)
Set the queue size for the thread pool.
typed_thread_pool_builder & with_job_types (const std::vector< job_type > &types)
Set the job types that workers should handle.
typed_thread_pool_builder & with_time_tagging (bool enable)
Enable or disable time tagging for workers.
typed_thread_pool_builder & with_auto_start (bool auto_start)
Enable or disable automatic pool startup.
bool validate () const
Validate the current configuration.
std::shared_ptr< typed_thread_pool_t< job_type > > build ()
Build the typed thread pool with current configuration.
typed_thread_pool_builder & reset ()
Reset the builder to default values.
Detailed Description
template<detail::JobType job_type = job_types>
class typed_thread_pool_module::typed_thread_pool_builder< job_type >
Builder class for constructing typed thread pools.
This class provides a fluent interface for building typed thread pools with various configuration options. It ensures consistent construction and validation of pool parameters.
Definition at line 59 of file pool_builder.h.
Constructor & Destructor Documentation
typed_thread_pool_builder() [1/3]
template<detail::JobType job_type = job_types> typed_thread_pool_module::typed_thread_pool_builder< job_type >::typed_thread_pool_builder () default
Construct a new builder with default settings.
typed_thread_pool_builder() [2/3]
template<detail::JobType job_type = job_types> typed_thread_pool_module::typed_thread_pool_builder< job_type >::typed_thread_pool_builder () default
Construct a new builder with default settings.
typed_thread_pool_builder() [3/3]
template<detail::JobType job_type = job_types> typed_thread_pool_module::typed_thread_pool_builder< job_type >::typed_thread_pool_builder () default
Construct a new builder with default settings.
Member Function Documentation
build() [1/3]
template<detail::JobType job_type = job_types> std::shared_ptr< typed_thread_pool_t< job_type > > typed_thread_pool_module::typed_thread_pool_builder< job_type >::build () inline
Build the typed thread pool with current configuration.
Returns
Shared pointer to the constructed thread pool
Exceptions
std::invalid_argument if configuration is invalid
Definition at line 142 of file pool_builder.h.
References thread_module::result< T >::get_error(), thread_module::error::message(), and typed_thread_pool_module::typed_thread_pool_builder< job_type >::validate().
build() [2/3]
template<detail::JobType job_type = job_types> std::shared_ptr< typed_thread_pool_t< job_type > > typed_thread_pool_module::typed_thread_pool_builder< job_type >::build () inline
Build the typed thread pool with current configuration.
Returns
Shared pointer to the constructed thread pool
Exceptions
std::invalid_argument if configuration is invalid
Definition at line 142 of file pool_builder.h.
References thread_module::result< T >::get_error(), thread_module::error::message(), and typed_thread_pool_module::typed_thread_pool_builder< job_type >::validate().
build() [3/3]
template<detail::JobType job_type = job_types> std::shared_ptr< typed_thread_pool_t< job_type > > typed_thread_pool_module::typed_thread_pool_builder< job_type >::build () inline
Build the typed thread pool with current configuration.
Returns
Shared pointer to the constructed thread pool
Exceptions
std::invalid_argument if configuration is invalid
Definition at line 142 of file pool_builder.h.
References thread_module::result< T >::get_error(), thread_module::error::message(), and typed_thread_pool_module::typed_thread_pool_builder< job_type >::validate().
reset() [1/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::reset () inline
Reset the builder to default values.
Returns
Reference to this builder for chaining
Definition at line 172 of file pool_builder.h.
References typed_thread_pool_module::config::default_queue_size, and typed_thread_pool_module::config::default_worker_count.
reset() [2/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::reset () inline
Reset the builder to default values.
Returns
Reference to this builder for chaining
Definition at line 172 of file pool_builder.h.
References typed_thread_pool_module::config::default_queue_size, and typed_thread_pool_module::config::default_worker_count.
reset() [3/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::reset () inline
Reset the builder to default values.
Returns
Reference to this builder for chaining
Definition at line 172 of file pool_builder.h.
References typed_thread_pool_module::config::default_queue_size, and typed_thread_pool_module::config::default_worker_count.
validate() [1/3]
template<detail::JobType job_type = job_types> bool typed_thread_pool_module::typed_thread_pool_builder< job_type >::validate () const inline
Validate the current configuration.
Returns
true if configuration is valid, false otherwise
Definition at line 130 of file pool_builder.h.
References typed_thread_pool_module::config::max_workers, and typed_thread_pool_module::config::min_workers.
Referenced by typed_thread_pool_module::typed_thread_pool_builder< job_type >::build().
validate() [2/3]
template<detail::JobType job_type = job_types> bool typed_thread_pool_module::typed_thread_pool_builder< job_type >::validate () const inline
Validate the current configuration.
Returns
true if configuration is valid, false otherwise
Definition at line 130 of file pool_builder.h.
References typed_thread_pool_module::config::max_workers, and typed_thread_pool_module::config::min_workers.
validate() [3/3]
template<detail::JobType job_type = job_types> bool typed_thread_pool_module::typed_thread_pool_builder< job_type >::validate () const inline
Validate the current configuration.
Returns
true if configuration is valid, false otherwise
Definition at line 130 of file pool_builder.h.
References typed_thread_pool_module::config::max_workers, and typed_thread_pool_module::config::min_workers.
with_auto_start() [1/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_auto_start (bool auto_start) inline
Enable or disable automatic pool startup.
Parameters
auto_start Whether to start the pool immediately after building
Returns
Reference to this builder for chaining
Definition at line 121 of file pool_builder.h.
with_auto_start() [2/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_auto_start (bool auto_start) inline
Enable or disable automatic pool startup.
Parameters
auto_start Whether to start the pool immediately after building
Returns
Reference to this builder for chaining
Definition at line 121 of file pool_builder.h.
with_auto_start() [3/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_auto_start (bool auto_start) inline
Enable or disable automatic pool startup.
Parameters
auto_start Whether to start the pool immediately after building
Returns
Reference to this builder for chaining
Definition at line 121 of file pool_builder.h.
with_job_types() [1/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_job_types (const std::vector< job_type > & types) inline
Set the job types that workers should handle.
Parameters
types Vector of job types for worker filtering
Returns
Reference to this builder for chaining
Definition at line 101 of file pool_builder.h.
with_job_types() [2/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_job_types (const std::vector< job_type > & types) inline
Set the job types that workers should handle.
Parameters
types Vector of job types for worker filtering
Returns
Reference to this builder for chaining
Definition at line 101 of file pool_builder.h.
with_job_types() [3/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_job_types (const std::vector< job_type > & types) inline
Set the job types that workers should handle.
Parameters
types Vector of job types for worker filtering
Returns
Reference to this builder for chaining
Definition at line 101 of file pool_builder.h.
with_queue_size() [1/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_queue_size (size_t size) inline
Set the queue size for the thread pool.
Parameters
size Maximum number of jobs that can be queued
Returns
Reference to this builder for chaining
Definition at line 91 of file pool_builder.h.
with_queue_size() [2/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_queue_size (size_t size) inline
Set the queue size for the thread pool.
Parameters
size Maximum number of jobs that can be queued
Returns
Reference to this builder for chaining
Definition at line 91 of file pool_builder.h.
with_queue_size() [3/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_queue_size (size_t size) inline
Set the queue size for the thread pool.
Parameters
size Maximum number of jobs that can be queued
Returns
Reference to this builder for chaining
Definition at line 91 of file pool_builder.h.
with_time_tagging() [1/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_time_tagging (bool enable) inline
Enable or disable time tagging for workers.
Parameters
enable Whether to use time tags in worker threads
Returns
Reference to this builder for chaining
Definition at line 111 of file pool_builder.h.
with_time_tagging() [2/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_time_tagging (bool enable) inline
Enable or disable time tagging for workers.
Parameters
enable Whether to use time tags in worker threads
Returns
Reference to this builder for chaining
Definition at line 111 of file pool_builder.h.
with_time_tagging() [3/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_time_tagging (bool enable) inline
Enable or disable time tagging for workers.
Parameters
enable Whether to use time tags in worker threads
Returns
Reference to this builder for chaining
Definition at line 111 of file pool_builder.h.
with_title() [1/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_title (const std::string & title) inline
Set the title/name for the thread pool.
Parameters
title The human-readable name for the pool
Returns
Reference to this builder for chaining
Definition at line 71 of file pool_builder.h.
with_title() [2/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_title (const std::string & title) inline
Set the title/name for the thread pool.
Parameters
title The human-readable name for the pool
Returns
Reference to this builder for chaining
Definition at line 71 of file pool_builder.h.
with_title() [3/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_title (const std::string & title) inline
Set the title/name for the thread pool.
Parameters
title The human-readable name for the pool
Returns
Reference to this builder for chaining
Definition at line 71 of file pool_builder.h.
with_worker_count() [1/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_worker_count (size_t count) inline
Set the number of worker threads.
Parameters
count Number of worker threads to create
Returns
Reference to this builder for chaining
Definition at line 81 of file pool_builder.h.
with_worker_count() [2/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_worker_count (size_t count) inline
Set the number of worker threads.
Parameters
count Number of worker threads to create
Returns
Reference to this builder for chaining
Definition at line 81 of file pool_builder.h.
with_worker_count() [3/3]
template<detail::JobType job_type = job_types> typed_thread_pool_builder & typed_thread_pool_module::typed_thread_pool_builder< job_type >::with_worker_count (size_t count) inline
Set the number of worker threads.
Parameters
count Number of worker threads to create
Returns
Reference to this builder for chaining
Definition at line 81 of file pool_builder.h.
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/typed_thread_pool/detail/forward_declarations.h
libraries/thread_system/modular_structure/core/include/thread_system_core/typed_thread_pool/pool/pool_builder.h
libraries/thread_system/modular_structure/core/src/typed_thread_pool/pool/pool_builder.h
libraries/thread_system/sources/typed_thread_pool/pool/pool_builder.h