Messaging System: libraries/container_system/tests/benchmark_tests.cpp File Reference
benchmark_tests.cpp File Reference
Performance benchmarks for the container system.
#include <benchmark/benchmark.h>
#include <container.h>
#include <values/bool_value.h>
#include <values/string_value.h>
#include <values/bytes_value.h>
#include <values/numeric_value.h>
#include <internal/thread_safe_container.h>
#include <thread>
#include <vector>
#include <random>
#include <sstream>
#include <cstring>
Functions
std::string generate_random_string (size_t length)
static void BM_ValueCreation_Null (benchmark::State &state)
BENCHMARK (BM_ValueCreation_Null)
static void BM_ValueCreation_Bool (benchmark::State &state)
BENCHMARK (BM_ValueCreation_Bool)
static void BM_ValueCreation_Int32 (benchmark::State &state)
BENCHMARK (BM_ValueCreation_Int32)
static void BM_ValueCreation_Double (benchmark::State &state)
BENCHMARK (BM_ValueCreation_Double)
static void BM_ValueCreation_String (benchmark::State &state)
BENCHMARK (BM_ValueCreation_String) -> Range(8, 8<< 10)
static void BM_ValueCreation_Bytes (benchmark::State &state)
BENCHMARK (BM_ValueCreation_Bytes) -> Range(8, 8<< 10)
static void BM_ValueConversion_StringToInt (benchmark::State &state)
BENCHMARK (BM_ValueConversion_StringToInt)
static void BM_ValueConversion_IntToString (benchmark::State &state)
BENCHMARK (BM_ValueConversion_IntToString)
static void BM_ValueConversion_DoubleToString (benchmark::State &state)
BENCHMARK (BM_ValueConversion_DoubleToString)
static void BM_ContainerCreation_Empty (benchmark::State &state)
BENCHMARK (BM_ContainerCreation_Empty)
static void BM_ContainerAddValue (benchmark::State &state)
BENCHMARK (BM_ContainerAddValue)
static void BM_ContainerAddMultipleValues (benchmark::State &state)
BENCHMARK (BM_ContainerAddMultipleValues) -> Range(10, 1000)
static void BM_ContainerGetValue (benchmark::State &state)
BENCHMARK (BM_ContainerGetValue) -> Range(10, 1000)
static void BM_ContainerSerialize (benchmark::State &state)
BENCHMARK (BM_ContainerSerialize) -> Range(1, 1000)
static void BM_ContainerDeserialize (benchmark::State &state)
BENCHMARK (BM_ContainerDeserialize) -> Range(1, 1000)
static void BM_ContainerToJSON (benchmark::State &state)
BENCHMARK (BM_ContainerToJSON) -> Range(1, 100)
static void BM_ContainerToXML (benchmark::State &state)
BENCHMARK (BM_ContainerToXML) -> Range(1, 100)
static void BM_LargeStringHandling (benchmark::State &state)
BENCHMARK (BM_LargeStringHandling) -> Range(1024, 1024 *1024)
static void BM_LargeBinaryHandling (benchmark::State &state)
BENCHMARK (BM_LargeBinaryHandling) -> Range(1024, 1024 *1024)
static void BM_ThreadSafeContainer_SingleThread (benchmark::State &state)
BENCHMARK (BM_ThreadSafeContainer_SingleThread)
static void BM_ThreadSafeContainer_MultiThread (benchmark::State &state)
BENCHMARK (BM_ThreadSafeContainer_MultiThread) -> Range(1, 8)
static void BM_MemoryPattern_SmallValues (benchmark::State &state)
BENCHMARK (BM_MemoryPattern_SmallValues) -> Range(100, 10000)
static void BM_MemoryPattern_LargeValues (benchmark::State &state)
BENCHMARK (BM_MemoryPattern_LargeValues) -> Range(10, 1000)
static void BM_NestedContainer_Create (benchmark::State &state)
BENCHMARK (BM_NestedContainer_Create) -> Range(1, 10)
static void BM_NestedContainer_Serialize (benchmark::State &state)
BENCHMARK (BM_NestedContainer_Serialize) -> Range(1, 10)
static void BM_SIMD_StringSearch (benchmark::State &state)
BENCHMARK (BM_SIMD_StringSearch)
static void BM_WorstCase_ManyDuplicateKeys (benchmark::State &state)
BENCHMARK (BM_WorstCase_ManyDuplicateKeys) -> Range(10, 1000)
static void BM_WorstCase_DeepNesting (benchmark::State &state)
BENCHMARK (BM_WorstCase_DeepNesting)
BENCHMARK_MAIN ()
Detailed Description
Performance benchmarks for the container system.
Measures performance characteristics including:
Serialization/deserialization speed
Memory usage patterns
SIMD optimization effectiveness
Thread scalability
Type conversion overhead
Definition in file benchmark_tests.cpp.
Function Documentation
BENCHMARK() [1/28]
BENCHMARK (BM_ContainerAddMultipleValues) -> Range(10, 1000)
BENCHMARK() [2/28]
BENCHMARK (BM_ContainerAddValue)
BENCHMARK() [3/28]
BENCHMARK (BM_ContainerCreation_Empty)
BENCHMARK() [4/28]
BENCHMARK (BM_ContainerDeserialize) -> Range(1, 1000)
BENCHMARK() [5/28]
BENCHMARK (BM_ContainerGetValue) -> Range(10, 1000)
BENCHMARK() [6/28]
BENCHMARK (BM_ContainerSerialize) -> Range(1, 1000)
BENCHMARK() [7/28]
BENCHMARK (BM_ContainerToJSON) -> Range(1, 100)
BENCHMARK() [8/28]
BENCHMARK (BM_ContainerToXML) -> Range(1, 100)
BENCHMARK() [9/28]
BENCHMARK (BM_LargeBinaryHandling) -> Range(1024, 1024 *1024)
BENCHMARK() [10/28]
BENCHMARK (BM_LargeStringHandling) -> Range(1024, 1024 *1024)
BENCHMARK() [11/28]
BENCHMARK (BM_MemoryPattern_LargeValues) -> Range(10, 1000)
BENCHMARK() [12/28]
BENCHMARK (BM_MemoryPattern_SmallValues) -> Range(100, 10000)
BENCHMARK() [13/28]
BENCHMARK (BM_NestedContainer_Create) -> Range(1, 10)
BENCHMARK() [14/28]
BENCHMARK (BM_NestedContainer_Serialize) -> Range(1, 10)
BENCHMARK() [15/28]
BENCHMARK (BM_SIMD_StringSearch)
BENCHMARK() [16/28]
BENCHMARK (BM_ThreadSafeContainer_MultiThread) -> Range(1, 8)
BENCHMARK() [17/28]
BENCHMARK (BM_ThreadSafeContainer_SingleThread)
BENCHMARK() [18/28]
BENCHMARK (BM_ValueConversion_DoubleToString)
BENCHMARK() [19/28]
BENCHMARK (BM_ValueConversion_IntToString)
BENCHMARK() [20/28]
BENCHMARK (BM_ValueConversion_StringToInt)
BENCHMARK() [21/28]
BENCHMARK (BM_ValueCreation_Bool)
BENCHMARK() [22/28]
BENCHMARK (BM_ValueCreation_Bytes) -> Range(8, 8<< 10)
BENCHMARK() [23/28]
BENCHMARK (BM_ValueCreation_Double)
BENCHMARK() [24/28]
BENCHMARK (BM_ValueCreation_Int32)
BENCHMARK() [25/28]
BENCHMARK (BM_ValueCreation_Null)
BENCHMARK() [26/28]
BENCHMARK (BM_ValueCreation_String) -> Range(8, 8<< 10)
BENCHMARK() [27/28]
BENCHMARK (BM_WorstCase_DeepNesting)
BENCHMARK() [28/28]
BENCHMARK (BM_WorstCase_ManyDuplicateKeys) -> Range(10, 1000)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_ContainerAddMultipleValues()
static void BM_ContainerAddMultipleValues (benchmark::State & state) static
Definition at line 165 of file benchmark_tests.cpp.
BM_ContainerAddValue()
static void BM_ContainerAddValue (benchmark::State & state) static
Definition at line 148 of file benchmark_tests.cpp.
BM_ContainerCreation_Empty()
static void BM_ContainerCreation_Empty (benchmark::State & state) static
Definition at line 140 of file benchmark_tests.cpp.
BM_ContainerDeserialize()
static void BM_ContainerDeserialize (benchmark::State & state) static
Definition at line 238 of file benchmark_tests.cpp.
BM_ContainerGetValue()
static void BM_ContainerGetValue (benchmark::State & state) static
Definition at line 191 of file benchmark_tests.cpp.
BM_ContainerSerialize()
static void BM_ContainerSerialize (benchmark::State & state) static
Definition at line 216 of file benchmark_tests.cpp.
BM_ContainerToJSON()
static void BM_ContainerToJSON (benchmark::State & state) static
Definition at line 266 of file benchmark_tests.cpp.
BM_ContainerToXML()
static void BM_ContainerToXML (benchmark::State & state) static
Definition at line 286 of file benchmark_tests.cpp.
BM_LargeBinaryHandling()
static void BM_LargeBinaryHandling (benchmark::State & state) static
Definition at line 326 of file benchmark_tests.cpp.
BM_LargeStringHandling()
static void BM_LargeStringHandling (benchmark::State & state) static
Definition at line 310 of file benchmark_tests.cpp.
References generate_random_string().
BM_MemoryPattern_LargeValues()
static void BM_MemoryPattern_LargeValues (benchmark::State & state) static
Definition at line 436 of file benchmark_tests.cpp.
BM_MemoryPattern_SmallValues()
static void BM_MemoryPattern_SmallValues (benchmark::State & state) static
Definition at line 419 of file benchmark_tests.cpp.
BM_NestedContainer_Create()
static void BM_NestedContainer_Create (benchmark::State & state) static
Definition at line 459 of file benchmark_tests.cpp.
BM_NestedContainer_Serialize()
static void BM_NestedContainer_Serialize (benchmark::State & state) static
Definition at line 487 of file benchmark_tests.cpp.
References container_module::value_container::add().
BM_SIMD_StringSearch()
static void BM_SIMD_StringSearch (benchmark::State & state) static
Definition at line 521 of file benchmark_tests.cpp.
References generate_random_string().
BM_ThreadSafeContainer_MultiThread()
static void BM_ThreadSafeContainer_MultiThread (benchmark::State & state) static
Definition at line 373 of file benchmark_tests.cpp.
BM_ThreadSafeContainer_SingleThread()
static void BM_ThreadSafeContainer_SingleThread (benchmark::State & state) static
Definition at line 348 of file benchmark_tests.cpp.
BM_ValueConversion_DoubleToString()
static void BM_ValueConversion_DoubleToString (benchmark::State & state) static
Definition at line 126 of file benchmark_tests.cpp.
BM_ValueConversion_IntToString()
static void BM_ValueConversion_IntToString (benchmark::State & state) static
Definition at line 116 of file benchmark_tests.cpp.
BM_ValueConversion_StringToInt()
static void BM_ValueConversion_StringToInt (benchmark::State & state) static
Definition at line 106 of file benchmark_tests.cpp.
BM_ValueCreation_Bool()
static void BM_ValueCreation_Bool (benchmark::State & state) static
Definition at line 57 of file benchmark_tests.cpp.
BM_ValueCreation_Bytes()
static void BM_ValueCreation_Bytes (benchmark::State & state) static
Definition at line 91 of file benchmark_tests.cpp.
BM_ValueCreation_Double()
static void BM_ValueCreation_Double (benchmark::State & state) static
Definition at line 73 of file benchmark_tests.cpp.
BM_ValueCreation_Int32()
static void BM_ValueCreation_Int32 (benchmark::State & state) static
Definition at line 65 of file benchmark_tests.cpp.
BM_ValueCreation_Null()
static void BM_ValueCreation_Null (benchmark::State & state) static
Definition at line 49 of file benchmark_tests.cpp.
BM_ValueCreation_String()
static void BM_ValueCreation_String (benchmark::State & state) static
Definition at line 81 of file benchmark_tests.cpp.
References generate_random_string().
BM_WorstCase_DeepNesting()
static void BM_WorstCase_DeepNesting (benchmark::State & state) static
Definition at line 566 of file benchmark_tests.cpp.
BM_WorstCase_ManyDuplicateKeys()
static void BM_WorstCase_ManyDuplicateKeys (benchmark::State & state) static
Definition at line 548 of file benchmark_tests.cpp.
generate_random_string()
std::string generate_random_string (size_t length)
Definition at line 29 of file benchmark_tests.cpp.
Referenced by BM_LargeStringHandling(), BM_SIMD_StringSearch(), and BM_ValueCreation_String().