Messaging System: monitoring_system::metric_storage Class Reference
monitoring_system::metric_storage Class Reference
Memory-efficient metric storage using ring buffers.
#include <metric_storage.h>
Public Member Functions
metric_storage (const metric_storage_config &config={})
Constructor.
~metric_storage ()
Destructor.
metric_storage (const metric_storage &)=delete
metric_storage & operator= (const metric_storage &)=delete
metric_storage (metric_storage &&)=delete
metric_storage & operator= (metric_storage &&)=delete
result_void store_metric (const std::string &name, double value, metric_type type=metric_type::gauge, std::chrono::system_clock::time_point timestamp=std::chrono::system_clock::now())
Store a metric value.
size_t store_metrics_batch (const metric_batch &batch)
Store multiple metrics in batch.
result< aggregation_result > query_metric (const std::string &name, const time_series_query &query) const
Query time series data for a metric.
result< double > get_latest_value (const std::string &name) const
Get latest value for a metric.
std::vector< std::string > get_metric_names () const
Get list of all metric names.
const metric_storage_stats & get_stats () const noexcept
Get storage statistics.
const metric_storage_config & get_config () const noexcept
Get storage configuration.
void flush ()
Flush all ring buffers to time series immediately.
void clear ()
Clear all stored data.
void shutdown ()
Shutdown background processing.
size_t memory_footprint () const
Get current memory footprint.
Detailed Description
Memory-efficient metric storage using ring buffers.
Definition at line 116 of file metric_storage.h.
Constructor & Destructor Documentation
metric_storage() [1/3]
monitoring_system::metric_storage::metric_storage (const metric_storage_config & config = {}) inline explicit
Constructor.
Definition at line 299 of file metric_storage.h.
~metric_storage()
monitoring_system::metric_storage::~metric_storage () inline
Destructor.
Definition at line 317 of file metric_storage.h.
References shutdown().
metric_storage() [2/3]
monitoring_system::metric_storage::metric_storage (const metric_storage &) delete
metric_storage() [3/3]
monitoring_system::metric_storage::metric_storage (metric_storage &&) delete
Member Function Documentation
clear()
void monitoring_system::metric_storage::clear () inline
Clear all stored data.
Definition at line 457 of file metric_storage.h.
References monitoring_system::metric_storage_stats::active_metric_series, and monitoring_system::metric_storage_stats::memory_usage_bytes.
flush()
void monitoring_system::metric_storage::flush () inline
Flush all ring buffers to time series immediately.
Definition at line 450 of file metric_storage.h.
Referenced by TEST_F(), TEST_F(), and TEST_F().
get_config()
const metric_storage_config & monitoring_system::metric_storage::get_config () const inline noexcept
Get storage configuration.
Definition at line 443 of file metric_storage.h.
get_latest_value()
result< double > monitoring_system::metric_storage::get_latest_value (const std::string & name) const inline
Get latest value for a metric.
Definition at line 403 of file metric_storage.h.
References monitoring_system::collector_not_found, and monitoring_system::hash_metric_name().
Referenced by TEST_F().
get_metric_names()
std::vector< std::string > monitoring_system::metric_storage::get_metric_names () const inline
Get list of all metric names.
Definition at line 420 of file metric_storage.h.
Referenced by TEST_F(), and TEST_F().
get_stats()
const metric_storage_stats & monitoring_system::metric_storage::get_stats () const inline noexcept
Get storage statistics.
Definition at line 436 of file metric_storage.h.
Referenced by TEST_F(), TEST_F(), and TEST_F().
memory_footprint()
size_t monitoring_system::metric_storage::memory_footprint () const inline
Get current memory footprint.
Definition at line 484 of file metric_storage.h.
References monitoring_system::metric_storage_stats::memory_usage_bytes.
operator=() [1/2]
metric_storage & monitoring_system::metric_storage::operator= (const metric_storage &) delete
operator=() [2/2]
metric_storage & monitoring_system::metric_storage::operator= (metric_storage &&) delete
query_metric()
result< aggregation_result > monitoring_system::metric_storage::query_metric (const std::string & name, const time_series_query & query) const inline
Query time series data for a metric.
Definition at line 385 of file metric_storage.h.
References monitoring_system::collector_not_found, and monitoring_system::hash_metric_name().
Referenced by TEST_F().
shutdown()
void monitoring_system::metric_storage::shutdown () inline
Shutdown background processing.
Definition at line 467 of file metric_storage.h.
Referenced by ~metric_storage().
store_metric()
result_void monitoring_system::metric_storage::store_metric (const std::string & name, double value, metric_type type = metric_type::gauge, std::chrono::system_clock::time_point timestamp = std::chrono::system_clock::now()) inline
Store a metric value.
Definition at line 330 of file metric_storage.h.
References monitoring_system::create_metric_metadata(), monitoring_system::storage_full, monitoring_system::metric_storage_stats::total_metrics_dropped, and monitoring_system::metric_storage_stats::total_metrics_stored.
Referenced by TEST_F(), TEST_F(), and TEST_F().
store_metrics_batch()
size_t monitoring_system::metric_storage::store_metrics_batch (const metric_batch & batch) inline
Store multiple metrics in batch.
Definition at line 361 of file metric_storage.h.
References monitoring_system::metric_batch::metrics, monitoring_system::metric_storage_stats::total_metrics_dropped, and monitoring_system::metric_storage_stats::total_metrics_stored.
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/metric_storage.h