Messaging System: libraries/monitoring_system/tests/test_buffering_strategies.cpp File Reference
test_buffering_strategies.cpp File Reference
#include <gtest/gtest.h>
#include <monitoring/utils/buffering_strategy.h>
#include <monitoring/utils/buffer_manager.h>
#include <monitoring/utils/metric_storage.h>
#include <chrono>
#include <thread>
#include <vector>
#include <random>
#include <functional>
Classes
class BufferingStrategiesTest
Test suite for Phase 3 P3: Configurable buffering strategies.
Functions
TEST_F (BufferingStrategiesTest, BufferingConfigValidation)
TEST_F (BufferingStrategiesTest, ImmediateStrategy)
TEST_F (BufferingStrategiesTest, FixedSizeStrategy)
TEST_F (BufferingStrategiesTest, FixedSizeStrategyDropNewest)
TEST_F (BufferingStrategiesTest, TimeBasedStrategy)
TEST_F (BufferingStrategiesTest, TimeBasedStrategyBufferFull)
TEST_F (BufferingStrategiesTest, PriorityBasedStrategy)
TEST_F (BufferingStrategiesTest, PriorityBasedStrategyOverflow)
TEST_F (BufferingStrategiesTest, AdaptiveStrategy)
TEST_F (BufferingStrategiesTest, StrategyFactory)
TEST_F (BufferingStrategiesTest, DefaultConfigurations)
TEST_F (BufferingStrategiesTest, BufferManagerBasic)
TEST_F (BufferingStrategiesTest, BufferManagerMultipleMetrics)
TEST_F (BufferingStrategiesTest, BufferManagerCustomStrategy)
TEST_F (BufferingStrategiesTest, BufferManagerBackgroundProcessing)
TEST_F (BufferingStrategiesTest, ThreadSafety)
Function Documentation
TEST_F() [1/16]
TEST_F (BufferingStrategiesTest , AdaptiveStrategy)
Definition at line 296 of file test_buffering_strategies.cpp.
References monitoring_system::buffering_config::adaptive_check_interval, monitoring_system::adaptive_strategy::add_metric(), monitoring_system::buffering_config::load_factor_threshold, monitoring_system::buffering_config::max_buffer_size, monitoring_system::adaptive_strategy::should_flush(), monitoring_system::adaptive_strategy::size(), and monitoring_system::buffering_config::strategy.
TEST_F() [2/16]
TEST_F (BufferingStrategiesTest , BufferingConfigValidation)
Definition at line 55 of file test_buffering_strategies.cpp.
References monitoring_system::buffering_config::flush_interval, monitoring_system::buffering_config::flush_threshold_size, monitoring_system::buffering_config::max_buffer_size, and monitoring_system::buffering_config::validate().
TEST_F() [3/16]
TEST_F (BufferingStrategiesTest , BufferManagerBackgroundProcessing)
Definition at line 461 of file test_buffering_strategies.cpp.
References monitoring_system::buffer_manager::add_metric(), monitoring_system::buffer_manager_config::background_check_interval, monitoring_system::buffer_manager::configure_metric_buffer(), monitoring_system::create_metric_metadata(), monitoring_system::buffer_manager_config::enable_automatic_flushing, monitoring_system::buffering_config::flush_interval, monitoring_system::buffer_manager::get_buffer_size(), monitoring_system::buffering_config::max_buffer_size, monitoring_system::buffer_manager::start_background_processing(), monitoring_system::buffer_manager::stop_background_processing(), and monitoring_system::buffering_config::strategy.
TEST_F() [4/16]
TEST_F (BufferingStrategiesTest , BufferManagerBasic)
Definition at line 366 of file test_buffering_strategies.cpp.
References monitoring_system::buffer_manager::add_metric(), monitoring_system::create_metric_metadata(), monitoring_system::buffer_manager_config::enable_automatic_flushing, monitoring_system::buffer_manager::force_flush(), and monitoring_system::buffer_manager::get_buffer_size().
TEST_F() [5/16]
TEST_F (BufferingStrategiesTest , BufferManagerCustomStrategy)
Definition at line 433 of file test_buffering_strategies.cpp.
References monitoring_system::buffer_manager::add_metric(), monitoring_system::buffer_manager::configure_metric_buffer(), monitoring_system::create_metric_metadata(), monitoring_system::buffering_config::flush_priority_threshold, monitoring_system::buffer_manager::get_buffer_statistics(), monitoring_system::buffering_config::max_buffer_size, and monitoring_system::buffering_config::strategy.
TEST_F() [6/16]
TEST_F (BufferingStrategiesTest , BufferManagerMultipleMetrics)
Definition at line 398 of file test_buffering_strategies.cpp.
References monitoring_system::buffer_manager::add_metric(), monitoring_system::create_metric_metadata(), monitoring_system::buffer_manager::force_flush_all(), monitoring_system::buffer_manager::get_buffer_size(), and monitoring_system::buffer_manager::get_buffered_metrics().
TEST_F() [7/16]
TEST_F (BufferingStrategiesTest , DefaultConfigurations)
Definition at line 350 of file test_buffering_strategies.cpp.
References monitoring_system::create_buffering_strategy(), and monitoring_system::create_default_buffering_configs().
TEST_F() [8/16]
TEST_F (BufferingStrategiesTest , FixedSizeStrategy)
Definition at line 113 of file test_buffering_strategies.cpp.
References monitoring_system::fixed_size_strategy::add_metric(), monitoring_system::fixed_size_strategy::flush(), monitoring_system::buffering_config::flush_threshold_size, monitoring_system::fixed_size_strategy::get_statistics(), monitoring_system::buffering_config::max_buffer_size, monitoring_system::buffering_config::overflow_policy, monitoring_system::fixed_size_strategy::should_flush(), monitoring_system::fixed_size_strategy::size(), and monitoring_system::buffering_config::strategy.
TEST_F() [9/16]
TEST_F (BufferingStrategiesTest , FixedSizeStrategyDropNewest)
Definition at line 157 of file test_buffering_strategies.cpp.
References monitoring_system::fixed_size_strategy::add_metric(), monitoring_system::fixed_size_strategy::get_statistics(), monitoring_system::buffering_config::max_buffer_size, monitoring_system::buffering_config::overflow_policy, monitoring_system::fixed_size_strategy::size(), and monitoring_system::buffering_config::strategy.
TEST_F() [10/16]
TEST_F (BufferingStrategiesTest , ImmediateStrategy)
Definition at line 82 of file test_buffering_strategies.cpp.
References monitoring_system::immediate_strategy::add_metric(), monitoring_system::immediate_strategy::flush(), monitoring_system::immediate_strategy::get_statistics(), monitoring_system::immediate_strategy::should_flush(), monitoring_system::immediate_strategy::size(), and monitoring_system::buffering_config::strategy.
TEST_F() [11/16]
TEST_F (BufferingStrategiesTest , PriorityBasedStrategy)
Definition at line 232 of file test_buffering_strategies.cpp.
References monitoring_system::priority_based_strategy::add_metric(), monitoring_system::priority_based_strategy::flush(), monitoring_system::buffering_config::flush_priority_threshold, monitoring_system::buffering_config::max_buffer_size, monitoring_system::priority_based_strategy::should_flush(), monitoring_system::priority_based_strategy::size(), and monitoring_system::buffering_config::strategy.
TEST_F() [12/16]
TEST_F (BufferingStrategiesTest , PriorityBasedStrategyOverflow)
Definition at line 264 of file test_buffering_strategies.cpp.
References monitoring_system::priority_based_strategy::add_metric(), monitoring_system::priority_based_strategy::flush(), monitoring_system::buffering_config::max_buffer_size, monitoring_system::buffering_config::overflow_policy, monitoring_system::priority_based_strategy::size(), and monitoring_system::buffering_config::strategy.
TEST_F() [13/16]
TEST_F (BufferingStrategiesTest , StrategyFactory)
Definition at line 324 of file test_buffering_strategies.cpp.
References monitoring_system::create_buffering_strategy(), monitoring_system::immediate_strategy::get_config(), monitoring_system::buffering_config::max_buffer_size, and monitoring_system::buffering_config::strategy.
TEST_F() [14/16]
TEST_F (BufferingStrategiesTest , ThreadSafety)
Definition at line 503 of file test_buffering_strategies.cpp.
References monitoring_system::buffer_manager::add_metric(), monitoring_system::create_metric_metadata(), monitoring_system::buffer_manager::get_buffer_size(), and monitoring_system::buffer_manager::get_buffered_metrics().
TEST_F() [15/16]
TEST_F (BufferingStrategiesTest , TimeBasedStrategy)
Definition at line 184 of file test_buffering_strategies.cpp.
References monitoring_system::time_based_strategy::add_metric(), monitoring_system::time_based_strategy::flush(), monitoring_system::buffering_config::flush_interval, monitoring_system::buffering_config::max_buffer_size, monitoring_system::time_based_strategy::should_flush(), monitoring_system::time_based_strategy::size(), and monitoring_system::buffering_config::strategy.
TEST_F() [16/16]
TEST_F (BufferingStrategiesTest , TimeBasedStrategyBufferFull)
Definition at line 213 of file test_buffering_strategies.cpp.
References monitoring_system::time_based_strategy::add_metric(), monitoring_system::buffering_config::flush_interval, monitoring_system::buffering_config::max_buffer_size, monitoring_system::time_based_strategy::should_flush(), and monitoring_system::buffering_config::strategy.