Messaging System: monitoring_system::error_boundary< T > Class Template Reference
monitoring_system::error_boundary< T > Class Template Reference
Basic error boundary implementation - stub.
#include <error_boundary.h>
Public Types
using config = error_boundary_config
Public Member Functions
error_boundary ()
error_boundary (const std::string &name)
error_boundary (const std::string &name, const config &cfg)
template<typename Func >
auto execute (Func &&func) -> decltype(func())
void set_error_handler (std::function< void(const error_info &, degradation_level)> handler)
error_boundary_metrics get_metrics () const
Detailed Description
template<typename T = void>
class monitoring_system::error_boundary< T >
Basic error boundary implementation - stub.
Definition at line 46 of file error_boundary.h.
Member Typedef Documentation
config
template<typename T = void> using monitoring_system::error_boundary< T >::config = error_boundary_config
Definition at line 48 of file error_boundary.h.
Constructor & Destructor Documentation
error_boundary() [1/3]
template<typename T = void> monitoring_system::error_boundary< T >::error_boundary () inline
Definition at line 50 of file error_boundary.h.
error_boundary() [2/3]
template<typename T = void> monitoring_system::error_boundary< T >::error_boundary (const std::string & name) inline explicit
Definition at line 51 of file error_boundary.h.
error_boundary() [3/3]
template<typename T = void> monitoring_system::error_boundary< T >::error_boundary (const std::string & name, const config & cfg) inline explicit
Definition at line 52 of file error_boundary.h.
Member Function Documentation
execute()
template<typename T = void> template<typename Func > auto monitoring_system::error_boundary< T >::execute (Func && func) -> decltype(func()) inline
Definition at line 55 of file error_boundary.h.
References monitoring_system::error_boundary_metrics::failed_operations, and monitoring_system::error_boundary_metrics::total_operations.
Referenced by demonstrate_error_boundaries(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
get_metrics()
template<typename T = void> error_boundary_metrics monitoring_system::error_boundary< T >::get_metrics () const inline
Definition at line 69 of file error_boundary.h.
Referenced by demonstrate_error_boundaries(), TEST_F(), and TEST_F().
set_error_handler()
template<typename T = void> void monitoring_system::error_boundary< T >::set_error_handler (std::function< void(const error_info &, degradation_level)> handler) inline
Definition at line 65 of file error_boundary.h.
Referenced by demonstrate_error_boundaries().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/monitoring/reliability/error_boundary.h