Messaging System: libraries/monitoring_system/tests/test_event_bus.cpp File Reference
test_event_bus.cpp File Reference
Test for event-driven communication system.
#include <monitoring/core/event_bus.h>
#include <monitoring/core/event_types.h>
#include <monitoring/adapters/thread_system_adapter.h>
#include <monitoring/adapters/logger_system_adapter.h>
#include <gtest/gtest.h>
#include <atomic>
#include <chrono>
#include <thread>
Classes
class EventBusTest
Functions
TEST_F (EventBusTest, PublishSubscribe)
TEST_F (EventBusTest, MultipleSubscribers)
TEST_F (EventBusTest, EventPriority)
TEST_F (EventBusTest, Unsubscribe)
TEST_F (EventBusTest, ThreadSystemAdapter)
TEST_F (EventBusTest, LoggerSystemAdapter)
TEST_F (EventBusTest, Statistics)
TEST_F (EventBusTest, ConcurrentPublishing)
int main (int argc, char **argv)
Detailed Description
Test for event-driven communication system.
Definition in file test_event_bus.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 283 of file test_event_bus.cpp.
TEST_F() [1/8]
TEST_F (EventBusTest , ConcurrentPublishing)
Definition at line 237 of file test_event_bus.cpp.
TEST_F() [2/8]
TEST_F (EventBusTest , EventPriority)
Definition at line 103 of file test_event_bus.cpp.
TEST_F() [3/8]
TEST_F (EventBusTest , LoggerSystemAdapter)
Definition at line 195 of file test_event_bus.cpp.
References monitoring_system::result< T >::has_value(), and monitoring_system::result< T >::value().
TEST_F() [4/8]
TEST_F (EventBusTest , MultipleSubscribers)
Definition at line 72 of file test_event_bus.cpp.
References monitoring_system::system_resource_event::resource_stats::cpu_usage_percent.
TEST_F() [5/8]
TEST_F (EventBusTest , PublishSubscribe)
Definition at line 39 of file test_event_bus.cpp.
TEST_F() [6/8]
TEST_F (EventBusTest , Statistics)
Definition at line 214 of file test_event_bus.cpp.
TEST_F() [7/8]
TEST_F (EventBusTest , ThreadSystemAdapter)
Definition at line 178 of file test_event_bus.cpp.
References monitoring_system::result< T >::has_value(), and monitoring_system::result< T >::value().
TEST_F() [8/8]
TEST_F (EventBusTest , Unsubscribe)
Definition at line 147 of file test_event_bus.cpp.