Messaging System: libraries/logger_system/samples/advanced_features_demo.cpp File Reference
advanced_features_demo.cpp File Reference
#include <logger/logger.h>
#include <logger/writers/console_writer.h>
#include <logger/writers/file_writer.h>
#include <logger/writers/rotating_file_writer.h>
#include <logger/filters/log_filter.h>
#include <logger/routing/log_router.h>
#include <iostream>
#include <thread>
#include <chrono>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 21 of file advanced_features_demo.cpp.
References logger_module::logger::add_writer(), logger_module::logger::flush(), logger_module::logger::get_router(), logger_module::logger::log(), logger_module::router_builder::route_to(), logger_module::logger::set_filter(), logger_module::logger::start(), logger_module::logger::stop(), logger_module::router_builder::when_level(), and logger_module::router_builder::when_matches().