Messaging System: monitoring_system::quantile_estimator Class Reference
monitoring_system::quantile_estimator Class Reference
P² algorithm for quantile estimation.
#include <stream_aggregator.h>
Public Member Functions
quantile_estimator (double p)
Constructor.
void add_observation (double x)
Add observation.
double get_quantile () const
Get quantile estimate.
void reset ()
Reset estimator.
Detailed Description
P² algorithm for quantile estimation.
Definition at line 234 of file stream_aggregator.h.
Constructor & Destructor Documentation
quantile_estimator()
monitoring_system::quantile_estimator::quantile_estimator (double p) inline explicit
Constructor.
Definition at line 263 of file stream_aggregator.h.
Member Function Documentation
add_observation()
void monitoring_system::quantile_estimator::add_observation (double x) inline
Add observation.
Definition at line 280 of file stream_aggregator.h.
Referenced by TEST_F(), and TEST_F().
get_quantile()
double monitoring_system::quantile_estimator::get_quantile () const inline
Get quantile estimate.
Definition at line 347 of file stream_aggregator.h.
Referenced by TEST_F(), and TEST_F().
reset()
void monitoring_system::quantile_estimator::reset () inline
Reset estimator.
Definition at line 354 of file stream_aggregator.h.
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/stream_aggregator.h