Messaging System: monitoring_module::compressed_metrics_storage Class Reference
monitoring_module::compressed_metrics_storage Class Reference
압축된 메트릭 저장소
#include <optimized_storage.h>
Classes
struct compressed_metric
압축된 메트릭 데이터
Public Member Functions
struct monitoring_module::compressed_metrics_storage::compressed_metric __attribute__ ((packed))
compressed_metrics_storage (std::size_t capacity, std::chrono::steady_clock::time_point base_time)
생성자
bool store (const monitoring_interface::metrics_snapshot &snapshot)
메트릭 압축 및 저장
std::optional< monitoring_interface::metrics_snapshot > retrieve (std::size_t index) const
압축된 메트릭 복원
std::vector< monitoring_interface::metrics_snapshot > retrieve_range (std::chrono::steady_clock::time_point start_time, std::chrono::steady_clock::time_point end_time) const
시간 범위로 메트릭 조회
std::size_t size () const
현재 저장된 메트릭 수
std::size_t memory_usage () const
사용된 메모리 크기
double compression_ratio () const
압축률 계산
Detailed Description
압축된 메트릭 저장소
메모리 효율적인 메트릭 저장을 위한 압축 스토리지
Definition at line 30 of file optimized_storage.h.
Constructor & Destructor Documentation
compressed_metrics_storage()
monitoring_module::compressed_metrics_storage::compressed_metrics_storage (std::size_t capacity, std::chrono::steady_clock::time_point base_time) explicit
생성자
Parameters
capacity 저장 용량
base_time 기준 시간
Definition at line 15 of file optimized_storage.cpp.
Member Function Documentation
__attribute__()
struct monitoring_module::compressed_metrics_storage::compressed_metric monitoring_module::compressed_metrics_storage::__attribute__ ((packed))
compression_ratio()
double monitoring_module::compressed_metrics_storage::compression_ratio () const
압축률 계산
Returns
압축률 (0-1, 1이 압축 안됨)
Definition at line 66 of file optimized_storage.cpp.
memory_usage()
std::size_t monitoring_module::compressed_metrics_storage::memory_usage () const inline
사용된 메모리 크기
Returns
바이트 단위 메모리 사용량
Definition at line 91 of file optimized_storage.h.
retrieve()
std::optional< monitoring_interface::metrics_snapshot > monitoring_module::compressed_metrics_storage::retrieve (std::size_t index) const
압축된 메트릭 복원
Parameters
index 인덱스
Returns
복원된 메트릭 (없으면 nullopt)
Definition at line 39 of file optimized_storage.cpp.
Referenced by retrieve_range().
retrieve_range()
std::vector< monitoring_interface::metrics_snapshot > monitoring_module::compressed_metrics_storage::retrieve_range (std::chrono::steady_clock::time_point start_time, std::chrono::steady_clock::time_point end_time) const
시간 범위로 메트릭 조회
Parameters
start_time 시작 시간
end_time 종료 시간
Returns
해당 범위의 메트릭들
Definition at line 48 of file optimized_storage.cpp.
References retrieve(), and size().
size()
std::size_t monitoring_module::compressed_metrics_storage::size () const inline
현재 저장된 메트릭 수
Returns
메트릭 개수
Definition at line 85 of file optimized_storage.h.
Referenced by retrieve_range().
store()
bool monitoring_module::compressed_metrics_storage::store (const monitoring_interface::metrics_snapshot & snapshot)
메트릭 압축 및 저장
Parameters
snapshot 원본 메트릭 스냅샷
Returns
저장 성공 여부
Definition at line 23 of file optimized_storage.cpp.
The documentation for this class was generated from the following files:
libraries/monitoring_system/sources/monitoring/optimized_storage.h
libraries/monitoring_system/sources/monitoring/optimized_storage.cpp