Messaging System: database::monitoring::performance_monitor Class Reference
database::monitoring::performance_monitor Class Reference
Main performance monitoring system.
#include <performance_monitor.h>
Public Member Functions
~performance_monitor ()
void set_monitoring_enabled (bool enabled)
void set_metrics_retention_period (std::chrono::minutes period)
void set_alert_thresholds (double error_rate_threshold, std::chrono::microseconds latency_threshold)
void record_query_metrics (const query_metrics &metrics)
void record_connection_metrics (database_types db_type, const connection_metrics &metrics)
void record_slow_query (const std::string &query, std::chrono::microseconds execution_time)
performance_summary get_performance_summary () const
performance_summary get_performance_summary (database_types db_type) const
std::vector< query_metrics > get_recent_queries (std::chrono::minutes window) const
std::vector< query_metrics > get_slow_queries (std::chrono::microseconds threshold) const
void update_connection_count (database_types db_type, size_t active, size_t total)
connection_metrics get_connection_metrics (database_types db_type) const
void register_alert_handler (std::function< void(const performance_alert &)> handler)
std::vector< performance_alert > get_recent_alerts (std::chrono::minutes window) const
void clear_metrics ()
void cleanup_old_metrics ()
std::string get_metrics_json () const
std::string get_dashboard_html () const
Static Public Member Functions
static performance_monitor & instance ()
Detailed Description
Main performance monitoring system.
Definition at line 212 of file performance_monitor.h.
Constructor & Destructor Documentation
~performance_monitor()
database::monitoring::performance_monitor::~performance_monitor ()
Definition at line 86 of file performance_monitor.cpp.
Member Function Documentation
cleanup_old_metrics()
void database::monitoring::performance_monitor::cleanup_old_metrics ()
Definition at line 372 of file performance_monitor.cpp.
clear_metrics()
void database::monitoring::performance_monitor::clear_metrics ()
Definition at line 362 of file performance_monitor.cpp.
get_connection_metrics()
connection_metrics database::monitoring::performance_monitor::get_connection_metrics (database_types db_type) const
Definition at line 323 of file performance_monitor.cpp.
References database::monitoring::connection_metrics::active_connections, database::monitoring::connection_metrics::avg_acquisition_time, database::monitoring::connection_metrics::failed_connections, database::monitoring::connection_metrics::idle_connections, database::monitoring::connection_metrics::last_update, database::monitoring::connection_metrics::max_acquisition_time, and database::monitoring::connection_metrics::total_connections.
get_dashboard_html()
std::string database::monitoring::performance_monitor::get_dashboard_html () const
get_metrics_json()
std::string database::monitoring::performance_monitor::get_metrics_json () const
Definition at line 395 of file performance_monitor.cpp.
References get_performance_summary().
get_performance_summary() [1/2]
performance_summary database::monitoring::performance_monitor::get_performance_summary () const
Definition at line 158 of file performance_monitor.cpp.
Referenced by get_metrics_json().
get_performance_summary() [2/2]
performance_summary database::monitoring::performance_monitor::get_performance_summary (database_types db_type) const
Definition at line 233 of file performance_monitor.cpp.
get_recent_alerts()
std::vector< performance_alert > database::monitoring::performance_monitor::get_recent_alerts (std::chrono::minutes window) const
Definition at line 347 of file performance_monitor.cpp.
get_recent_queries()
std::vector< query_metrics > database::monitoring::performance_monitor::get_recent_queries (std::chrono::minutes window) const
Definition at line 284 of file performance_monitor.cpp.
get_slow_queries()
std::vector< query_metrics > database::monitoring::performance_monitor::get_slow_queries (std::chrono::microseconds threshold) const
Definition at line 299 of file performance_monitor.cpp.
instance()
performance_monitor & database::monitoring::performance_monitor::instance () static
Definition at line 75 of file performance_monitor.cpp.
References instance().
Referenced by BM_ConnectionMetricsRecording(), BM_IntegratedSystemPerformance(), BM_PerformanceMonitorConfiguration(), BM_QueryMetricsRecording(), BM_SystemMetricsAccess(), demonstrate_alerting_system(), demonstrate_basic_metrics(), demonstrate_connection_pool_metrics(), demonstrate_metrics_export(), demonstrate_performance_analysis(), demonstrate_query_metrics(), demonstrate_real_time_monitoring(), instance(), PerformanceMonitorTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and database::monitoring::query_timer::~query_timer().
record_connection_metrics()
void database::monitoring::performance_monitor::record_connection_metrics (database_types db_type, const connection_metrics & metrics)
Definition at line 126 of file performance_monitor.cpp.
References database::monitoring::connection_metrics::active_connections, database::monitoring::connection_metrics::avg_acquisition_time, database::monitoring::performance_alert::connection_pool_exhaustion, database::monitoring::connection_metrics::failed_connections, database::monitoring::connection_metrics::idle_connections, database::monitoring::connection_metrics::last_update, database::monitoring::connection_metrics::max_acquisition_time, and database::monitoring::connection_metrics::total_connections.
Referenced by demonstrate_connection_pool_metrics().
record_query_metrics()
void database::monitoring::performance_monitor::record_query_metrics (const query_metrics & metrics)
Definition at line 102 of file performance_monitor.cpp.
References database::monitoring::query_metrics::execution_time, database::monitoring::query_metrics::query_hash, and database::monitoring::performance_alert::slow_query.
Referenced by database::monitoring::query_timer::~query_timer().
record_slow_query()
void database::monitoring::performance_monitor::record_slow_query (const std::string & query, std::chrono::microseconds execution_time)
Definition at line 149 of file performance_monitor.cpp.
References database::monitoring::performance_alert::slow_query.
register_alert_handler()
void database::monitoring::performance_monitor::register_alert_handler (std::function< void(const performance_alert &)> handler)
Definition at line 341 of file performance_monitor.cpp.
set_alert_thresholds()
void database::monitoring::performance_monitor::set_alert_thresholds (double error_rate_threshold, std::chrono::microseconds latency_threshold)
Definition at line 95 of file performance_monitor.cpp.
set_metrics_retention_period()
void database::monitoring::performance_monitor::set_metrics_retention_period (std::chrono::minutes period) inline
Definition at line 220 of file performance_monitor.h.
set_monitoring_enabled()
void database::monitoring::performance_monitor::set_monitoring_enabled (bool enabled) inline
Definition at line 219 of file performance_monitor.h.
update_connection_count()
void database::monitoring::performance_monitor::update_connection_count (database_types db_type, size_t active, size_t total)
Definition at line 312 of file performance_monitor.cpp.
The documentation for this class was generated from the following files:
libraries/database_system/database/monitoring/performance_monitor.h
libraries/database_system/database/monitoring/performance_monitor.cpp