Messaging System: monitoring_system::result< T > Class Template Reference
monitoring_system::result< T > Class Template Reference
Result type for operations that may fail.
#include <result_types.h>
Public Member Functions
result (T &&value)
result (const T &value)
result (error_info &&error)
result (const error_info &error)
result (monitoring_error_code code, const std::string &message="", const std::source_location &loc=std::source_location::current())
bool has_value () const
operator bool () const
T & value ()
const T & value () const
T value_or (T &&default_value) const
const error_info & get_error () const
T * operator-> ()
const T * operator-> () const
T & operator* ()
const T & operator* () const
template<typename F >
auto map (F &&f) -> result< decltype(f(std::declval< T >()))>
template<typename F >
auto and_then (F &&f) -> decltype(f(std::declval< T >()))
template<typename F >
result or_else (F &&f)
result (T value)
result ()
operator bool () const
T & value ()
const T & value () const
result (T value)
result ()
operator bool () const
T & value ()
const T & value () const
const error_info & get_error () const
Detailed Description
template<typename T>
class monitoring_system::result< T >
Result type for operations that may fail.
Template Parameters
T The success value type
This class follows the Result pattern used in thread_system, providing explicit error handling without exceptions.
Definition at line 73 of file result_types.h.
Constructor & Destructor Documentation
result() [1/9]
template<typename T > monitoring_system::result< T >::result (T && value) inline
Definition at line 83 of file result_types.h.
result() [2/9]
template<typename T > monitoring_system::result< T >::result (const T & value) inline
Definition at line 84 of file result_types.h.
result() [3/9]
template<typename T > monitoring_system::result< T >::result (error_info && error) inline
Definition at line 85 of file result_types.h.
result() [4/9]
template<typename T > monitoring_system::result< T >::result (const error_info & error) inline
Definition at line 86 of file result_types.h.
result() [5/9]
template<typename T > monitoring_system::result< T >::result (monitoring_error_code code, const std::string & message = "", const std::source_location & loc = std::source_location::current()) inline
Definition at line 89 of file result_types.h.
result() [6/9]
template<typename T > monitoring_system::result< T >::result (T value) inline
Definition at line 92 of file distributed_tracer.h.
result() [7/9]
template<typename T > monitoring_system::result< T >::result () inline
Definition at line 93 of file distributed_tracer.h.
result() [8/9]
template<typename T > monitoring_system::result< T >::result (T value) inline
Definition at line 55 of file test_di_container.cpp.
result() [9/9]
template<typename T > monitoring_system::result< T >::result () inline
Definition at line 56 of file test_di_container.cpp.
Member Function Documentation
and_then()
template<typename T > template<typename F > auto monitoring_system::result< T >::and_then (F && f) -> decltype(f(std::declval<T>())) inline
Definition at line 158 of file result_types.h.
References monitoring_system::result< T >::get_error(), and monitoring_system::result< T >::has_value().
Referenced by TEST_F().
get_error() [1/2]
template<typename T > const error_info & monitoring_system::result< T >::get_error () const inline
Definition at line 125 of file result_types.h.
Referenced by monitoring_system::result< T >::and_then(), monitoring_system::performance_monitor::cleanup(), monitoring_system::monitoring_aggregator::collect_all(), demonstrate_circuit_breaker(), demonstrate_error_boundaries(), demonstrate_health_monitoring(), demonstrate_retry_policy(), monitoring_system::distributed_tracer::export_spans(), monitoring_system::performance_monitor::initialize(), main(), monitoring_system::result< T >::map(), monitoring_system::result< T >::or_else(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), monitoring_system::result< T >::value(), and monitoring_system::result< T >::value().
get_error() [2/2]
template<typename T > const error_info & monitoring_system::result< T >::get_error () const inline
Definition at line 61 of file test_di_container.cpp.
has_value()
template<typename T > bool monitoring_system::result< T >::has_value () const inline
Definition at line 95 of file result_types.h.
Referenced by monitoring_system::result< T >::and_then(), monitoring_system::result< T >::map(), monitoring_system::result< T >::operator bool(), monitoring_system::result< T >::or_else(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), monitoring_system::result< T >::value(), monitoring_system::result< T >::value(), and monitoring_system::result< T >::value_or().
map()
template<typename T > template<typename F > auto monitoring_system::result< T >::map (F && f) -> result<decltype(f(std::declval<T>()))> inline
Definition at line 149 of file result_types.h.
References monitoring_system::result< T >::get_error(), and monitoring_system::result< T >::has_value().
Referenced by process_metric(), TEST_F(), and TEST_F().
operator bool() [1/3]
template<typename T > monitoring_system::result< T >::operator bool () const inline
Definition at line 100 of file result_types.h.
References monitoring_system::result< T >::has_value().
operator bool() [2/3]
template<typename T > monitoring_system::result< T >::operator bool () const inline explicit
Definition at line 95 of file distributed_tracer.h.
operator bool() [3/3]
template<typename T > monitoring_system::result< T >::operator bool () const inline
Definition at line 58 of file test_di_container.cpp.
operator*() [1/2]
template<typename T > T & monitoring_system::result< T >::operator* () inline
Definition at line 139 of file result_types.h.
References monitoring_system::result< T >::value().
operator*() [2/2]
template<typename T > const T & monitoring_system::result< T >::operator* () const inline
Definition at line 143 of file result_types.h.
References monitoring_system::result< T >::value().
operator->() [1/2]
template<typename T > T * monitoring_system::result< T >::operator-> () inline
Definition at line 130 of file result_types.h.
References monitoring_system::result< T >::value().
operator->() [2/2]
template<typename T > const T * monitoring_system::result< T >::operator-> () const inline
Definition at line 134 of file result_types.h.
References monitoring_system::result< T >::value().
or_else()
template<typename T > template<typename F > result monitoring_system::result< T >::or_else (F && f) inline
Definition at line 167 of file result_types.h.
References monitoring_system::result< T >::get_error(), and monitoring_system::result< T >::has_value().
value() [1/6]
template<typename T > T & monitoring_system::result< T >::value () inline
Definition at line 105 of file result_types.h.
References monitoring_system::result< T >::get_error(), monitoring_system::result< T >::has_value(), and to_string().
Referenced by monitoring_system::monitoring_aggregator::collect_all(), demonstrate_circuit_breaker(), demonstrate_retry_policy(), monitoring_system::aggregation_processor::force_all_aggregations(), monitoring_system::result< T >::operator*(), monitoring_system::result< T >::operator*(), monitoring_system::result< T >::operator->(), monitoring_system::result< T >::operator->(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and monitoring_system::error_info::to_string().
value() [2/6]
template<typename T > T & monitoring_system::result< T >::value () inline
Definition at line 96 of file distributed_tracer.h.
value() [3/6]
template<typename T > T & monitoring_system::result< T >::value () inline
Definition at line 59 of file test_di_container.cpp.
value() [4/6]
template<typename T > const T & monitoring_system::result< T >::value () const inline
Definition at line 112 of file result_types.h.
References monitoring_system::result< T >::get_error(), monitoring_system::result< T >::has_value(), and to_string().
value() [5/6]
template<typename T > const T & monitoring_system::result< T >::value () const inline
Definition at line 97 of file distributed_tracer.h.
value() [6/6]
template<typename T > const T & monitoring_system::result< T >::value () const inline
Definition at line 60 of file test_di_container.cpp.
value_or()
template<typename T > T monitoring_system::result< T >::value_or (T && default_value) const inline
Definition at line 120 of file result_types.h.
References monitoring_system::result< T >::has_value().
The documentation for this class was generated from the following files:
libraries/monitoring_system/include/kcenon/monitoring/core/result_types.h
libraries/monitoring_system/include/monitoring/tracing/distributed_tracer.h
libraries/monitoring_system/tests/test_di_container.cpp