Messaging System: kcenon::monitoring::alerting::AlertDeduplication Class Reference
kcenon::monitoring::alerting::AlertDeduplication Class Reference
#include <alert_deduplication.h>
Public Member Functions
AlertDeduplication ()
~AlertDeduplication ()
bool is_duplicate (const Alert &alert)
std::optional< DeduplicationEntry > find_duplicate (const Alert &alert)
void record_alert (const Alert &alert)
void clear_old_entries (std::chrono::seconds age_limit)
void set_deduplication_strategy (DeduplicationStrategy strategy)
void set_deduplication_window (std::chrono::seconds window)
void set_similarity_threshold (double threshold)
void set_max_entries (size_t max_entries)
std::string generate_fingerprint (const Alert &alert) const
std::string generate_fuzzy_fingerprint (const Alert &alert) const
double calculate_similarity (const Alert &alert1, const Alert &alert2) const
SimilarityMetrics calculate_detailed_similarity (const Alert &alert1, const Alert &alert2) const
double calculate_label_similarity (const std::unordered_map< std::string, std::string > &labels1, const std::unordered_map< std::string, std::string > &labels2) const
double calculate_string_similarity (const std::string &s1, const std::string &s2) const
size_t get_deduplication_count () const
size_t get_entry_count () const
double get_deduplication_rate () const
std::vector< DeduplicationEntry > get_top_duplicates (size_t count) const
Detailed Description
Definition at line 85 of file alert_deduplication.h.
Constructor & Destructor Documentation
AlertDeduplication()
kcenon::monitoring::alerting::AlertDeduplication::AlertDeduplication ()
~AlertDeduplication()
kcenon::monitoring::alerting::AlertDeduplication::~AlertDeduplication ()
Member Function Documentation
calculate_detailed_similarity()
SimilarityMetrics kcenon::monitoring::alerting::AlertDeduplication::calculate_detailed_similarity (const Alert & alert1, const Alert & alert2) const
calculate_label_similarity()
double kcenon::monitoring::alerting::AlertDeduplication::calculate_label_similarity (const std::unordered_map< std::string, std::string > & labels1, const std::unordered_map< std::string, std::string > & labels2) const
calculate_similarity()
double kcenon::monitoring::alerting::AlertDeduplication::calculate_similarity (const Alert & alert1, const Alert & alert2) const
calculate_string_similarity()
double kcenon::monitoring::alerting::AlertDeduplication::calculate_string_similarity (const std::string & s1, const std::string & s2) const
clear_old_entries()
void kcenon::monitoring::alerting::AlertDeduplication::clear_old_entries (std::chrono::seconds age_limit)
find_duplicate()
std::optional< DeduplicationEntry > kcenon::monitoring::alerting::AlertDeduplication::find_duplicate (const Alert & alert)
generate_fingerprint()
std::string kcenon::monitoring::alerting::AlertDeduplication::generate_fingerprint (const Alert & alert) const
generate_fuzzy_fingerprint()
std::string kcenon::monitoring::alerting::AlertDeduplication::generate_fuzzy_fingerprint (const Alert & alert) const
get_deduplication_count()
size_t kcenon::monitoring::alerting::AlertDeduplication::get_deduplication_count () const inline
Definition at line 115 of file alert_deduplication.h.
get_deduplication_rate()
double kcenon::monitoring::alerting::AlertDeduplication::get_deduplication_rate () const
get_entry_count()
size_t kcenon::monitoring::alerting::AlertDeduplication::get_entry_count () const
get_top_duplicates()
std::vector< DeduplicationEntry > kcenon::monitoring::alerting::AlertDeduplication::get_top_duplicates (size_t count) const
is_duplicate()
bool kcenon::monitoring::alerting::AlertDeduplication::is_duplicate (const Alert & alert)
record_alert()
void kcenon::monitoring::alerting::AlertDeduplication::record_alert (const Alert & alert)
set_deduplication_strategy()
void kcenon::monitoring::alerting::AlertDeduplication::set_deduplication_strategy (DeduplicationStrategy strategy)
Referenced by kcenon::monitoring::alerting::DeduplicationConfigBuilder::apply_to().
set_deduplication_window()
void kcenon::monitoring::alerting::AlertDeduplication::set_deduplication_window (std::chrono::seconds window)
Referenced by kcenon::monitoring::alerting::DeduplicationConfigBuilder::apply_to().
set_max_entries()
void kcenon::monitoring::alerting::AlertDeduplication::set_max_entries (size_t max_entries)
Referenced by kcenon::monitoring::alerting::DeduplicationConfigBuilder::apply_to().
set_similarity_threshold()
void kcenon::monitoring::alerting::AlertDeduplication::set_similarity_threshold (double threshold)
Referenced by kcenon::monitoring::alerting::DeduplicationConfigBuilder::apply_to().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/impl/alerting/alert_deduplication.h