Messaging System: dashboard_renderer Class Reference
dashboard_renderer Class Reference
Static Public Member Functions
static void render_header ()
static void render_health_section (const analysis_dashboard::system_health_report &health)
static void render_forecast_section (const analysis_dashboard::performance_forecast &forecast)
static void render_correlation_section (const analysis_dashboard::correlation_matrix &matrix)
static void render_alerts_section (alert_manager &alert_mgr)
static void render_optimization_section (const std::vector< std::pair< int, std::string > > &suggestions)
Detailed Description
Definition at line 193 of file advanced_analysis_example.cpp.
Member Function Documentation
render_alerts_section()
static void dashboard_renderer::render_alerts_section (alert_manager & alert_mgr) inline static
Definition at line 259 of file advanced_analysis_example.cpp.
References monitoring_module::alert_manager::get_recent_alerts(), and alert::message.
Referenced by main().
render_correlation_section()
static void dashboard_renderer::render_correlation_section (const analysis_dashboard::correlation_matrix & matrix) inline static
Definition at line 250 of file advanced_analysis_example.cpp.
References monitoring_module::analysis_dashboard::correlation_matrix::strong_correlations.
Referenced by main().
render_forecast_section()
static void dashboard_renderer::render_forecast_section (const analysis_dashboard::performance_forecast & forecast) inline static
Definition at line 234 of file advanced_analysis_example.cpp.
References monitoring_module::analysis_dashboard::performance_forecast::capacity_warning_time, and monitoring_module::analysis_dashboard::performance_forecast::cpu_predictions.
Referenced by main().
render_header()
static void dashboard_renderer::render_header () inline static
Definition at line 195 of file advanced_analysis_example.cpp.
Referenced by main().
render_health_section()
static void dashboard_renderer::render_health_section (const analysis_dashboard::system_health_report & health) inline static
Definition at line 204 of file advanced_analysis_example.cpp.
References monitoring_module::analysis_dashboard::system_health_report::health_status, monitoring_module::analysis_dashboard::system_health_report::issues, and monitoring_module::analysis_dashboard::system_health_report::overall_health_score.
Referenced by main().
render_optimization_section()
static void dashboard_renderer::render_optimization_section (const std::vector< std::pair< int, std::string > > & suggestions) inline static
Definition at line 286 of file advanced_analysis_example.cpp.
Referenced by main().
The documentation for this class was generated from the following file:
libraries/monitoring_system/samples/advanced_analysis_example.cpp