Messaging System: libraries/monitoring_system/tests/test_resource_management.cpp File Reference
test_resource_management.cpp File Reference
#include <gtest/gtest.h>
#include <thread>
#include <chrono>
#include <atomic>
#include <monitoring/reliability/resource_manager.h>
Classes
class ResourceManagementTest
Functions
TEST_F (ResourceManagementTest, TokenBucketBasicOperation)
TEST_F (ResourceManagementTest, TokenBucketRefill)
TEST_F (ResourceManagementTest, TokenBucketExecute)
TEST_F (ResourceManagementTest, LeakyBucketBasicOperation)
TEST_F (ResourceManagementTest, LeakyBucketLeak)
TEST_F (ResourceManagementTest, MemoryQuotaBasicAllocation)
TEST_F (ResourceManagementTest, MemoryQuotaDeallocation)
TEST_F (ResourceManagementTest, MemoryQuotaThresholds)
TEST_F (ResourceManagementTest, MemoryQuotaMetrics)
TEST_F (ResourceManagementTest, CPUThrottlerBasicOperation)
TEST_F (ResourceManagementTest, CPUThrottlerMetrics)
TEST_F (ResourceManagementTest, ResourceManagerRateLimiter)
TEST_F (ResourceManagementTest, ResourceManagerMemoryQuota)
TEST_F (ResourceManagementTest, ResourceManagerCPUThrottler)
TEST_F (ResourceManagementTest, ResourceManagerDuplicateNames)
TEST_F (ResourceManagementTest, ResourceManagerHealthCheck)
TEST_F (ResourceManagementTest, ResourceManagerMetrics)
TEST_F (ResourceManagementTest, RateLimitConfigValidation)
TEST_F (ResourceManagementTest, ResourceQuotaValidation)
TEST_F (ResourceManagementTest, CPUThrottleConfigValidation)
TEST_F (ResourceManagementTest, RateLimiterConcurrency)
TEST_F (ResourceManagementTest, MemoryQuotaConcurrency)
TEST_F (ResourceManagementTest, RateLimiterPerformance)
TEST_F (ResourceManagementTest, MemoryQuotaPerformance)
Function Documentation
TEST_F() [1/24]
TEST_F (ResourceManagementTest , CPUThrottleConfigValidation)
Definition at line 361 of file test_resource_management.cpp.
TEST_F() [2/24]
TEST_F (ResourceManagementTest , CPUThrottlerBasicOperation)
Definition at line 192 of file test_resource_management.cpp.
References monitoring_system::result< T >::value().
TEST_F() [3/24]
TEST_F (ResourceManagementTest , CPUThrottlerMetrics)
Definition at line 206 of file test_resource_management.cpp.
TEST_F() [4/24]
TEST_F (ResourceManagementTest , LeakyBucketBasicOperation)
Definition at line 82 of file test_resource_management.cpp.
TEST_F() [5/24]
TEST_F (ResourceManagementTest , LeakyBucketLeak)
Definition at line 93 of file test_resource_management.cpp.
TEST_F() [6/24]
TEST_F (ResourceManagementTest , MemoryQuotaBasicAllocation)
Definition at line 110 of file test_resource_management.cpp.
TEST_F() [7/24]
TEST_F (ResourceManagementTest , MemoryQuotaConcurrency)
Definition at line 411 of file test_resource_management.cpp.
TEST_F() [8/24]
TEST_F (ResourceManagementTest , MemoryQuotaDeallocation)
Definition at line 130 of file test_resource_management.cpp.
TEST_F() [9/24]
TEST_F (ResourceManagementTest , MemoryQuotaMetrics)
Definition at line 170 of file test_resource_management.cpp.
TEST_F() [10/24]
TEST_F (ResourceManagementTest , MemoryQuotaPerformance)
Definition at line 460 of file test_resource_management.cpp.
TEST_F() [11/24]
TEST_F (ResourceManagementTest , MemoryQuotaThresholds)
Definition at line 148 of file test_resource_management.cpp.
TEST_F() [12/24]
TEST_F (ResourceManagementTest , RateLimitConfigValidation)
Definition at line 319 of file test_resource_management.cpp.
TEST_F() [13/24]
TEST_F (ResourceManagementTest , RateLimiterConcurrency)
Definition at line 383 of file test_resource_management.cpp.
TEST_F() [14/24]
TEST_F (ResourceManagementTest , RateLimiterPerformance)
Definition at line 442 of file test_resource_management.cpp.
TEST_F() [15/24]
TEST_F (ResourceManagementTest , ResourceManagerCPUThrottler)
Definition at line 249 of file test_resource_management.cpp.
TEST_F() [16/24]
TEST_F (ResourceManagementTest , ResourceManagerDuplicateNames)
Definition at line 264 of file test_resource_management.cpp.
TEST_F() [17/24]
TEST_F (ResourceManagementTest , ResourceManagerHealthCheck)
Definition at line 281 of file test_resource_management.cpp.
TEST_F() [18/24]
TEST_F (ResourceManagementTest , ResourceManagerMemoryQuota)
Definition at line 236 of file test_resource_management.cpp.
TEST_F() [19/24]
TEST_F (ResourceManagementTest , ResourceManagerMetrics)
Definition at line 298 of file test_resource_management.cpp.
TEST_F() [20/24]
TEST_F (ResourceManagementTest , ResourceManagerRateLimiter)
Definition at line 221 of file test_resource_management.cpp.
TEST_F() [21/24]
TEST_F (ResourceManagementTest , ResourceQuotaValidation)
Definition at line 337 of file test_resource_management.cpp.
TEST_F() [22/24]
TEST_F (ResourceManagementTest , TokenBucketBasicOperation)
Definition at line 37 of file test_resource_management.cpp.
TEST_F() [23/24]
TEST_F (ResourceManagementTest , TokenBucketExecute)
Definition at line 64 of file test_resource_management.cpp.
References monitoring_system::error_info::code, monitoring_system::result< T >::get_error(), and monitoring_system::result< T >::value().
TEST_F() [24/24]
TEST_F (ResourceManagementTest , TokenBucketRefill)
Definition at line 48 of file test_resource_management.cpp.