Messaging System: chat_server Class Reference
chat_server Class Reference
Public Member Functions
chat_server ()
~chat_server ()
void setupMessageHandlers ()
void handleUserConnect (const core::message &connect_message)
void handleUserDisconnect (const core::message &disconnect_message)
void handleChatMessage (const core::message &chat_message)
void handlePrivateMessage (const core::message &private_message)
void handleRoomJoin (const core::message &join_message)
void handleRoomLeave (const core::message &leave_message)
void broadcastToAll (const core::message &broadcast_message)
void broadcastToRoom (const std::string &room_id, const core::message &room_message)
void sendToUser (const std::string &recipient_user_id, const core::message &user_message)
void sendRoomHistory (const std::string &user_id, const std::string &room_id)
void logMessage (const std::string &sender_nickname, const std::string &message_text, const std::string &room_id)
void cleanupInactiveUsers ()
void startRetryWorker ()
void queueForRetry (std::function< void()> task)
void startHealthMonitor ()
void attemptRecovery ()
void attemptUserReconnection (const std::string &user_id)
void reportMetrics ()
void start (int port=8080)
void stop ()
void printStats ()
Detailed Description
Definition at line 42 of file chat_server.cpp.
Constructor & Destructor Documentation
chat_server()
chat_server::chat_server () inline
Definition at line 75 of file chat_server.cpp.
References kcenon::messaging::config::config_builder::build(), kcenon::messaging::config::config_builder::enable_external_monitoring(), kcenon::messaging::config::config_builder::set_container_max_size(), kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), kcenon::messaging::config::config_builder::set_worker_threads(), setupMessageHandlers(), signal_handler(), startHealthMonitor(), and startRetryWorker().
~chat_server()
chat_server::~chat_server () inline
Definition at line 119 of file chat_server.cpp.
References stop().
Member Function Documentation
attemptRecovery()
void chat_server::attemptRecovery () inline
Definition at line 487 of file chat_server.cpp.
References attemptUserReconnection(), queueForRetry(), and setupMessageHandlers().
Referenced by startHealthMonitor().
attemptUserReconnection()
void chat_server::attemptUserReconnection (const std::string & user_id) inline
Definition at line 510 of file chat_server.cpp.
Referenced by attemptRecovery().
broadcastToAll()
void chat_server::broadcastToAll (const core::message & broadcast_message) inline
Definition at line 360 of file chat_server.cpp.
Referenced by broadcastToRoom(), handleChatMessage(), handleUserConnect(), handleUserDisconnect(), and stop().
broadcastToRoom()
void chat_server::broadcastToRoom (const std::string & room_id, const core::message & room_message) inline
Definition at line 367 of file chat_server.cpp.
References broadcastToAll().
Referenced by handleChatMessage().
cleanupInactiveUsers()
void chat_server::cleanupInactiveUsers () inline
Definition at line 394 of file chat_server.cpp.
Referenced by start().
handleChatMessage()
void chat_server::handleChatMessage (const core::message & chat_message) inline
Definition at line 227 of file chat_server.cpp.
References broadcastToAll(), broadcastToRoom(), kcenon::messaging::core::message_payload::get(), kcenon::messaging::core::message_metadata::headers, logMessage(), kcenon::messaging::core::message::metadata, kcenon::messaging::core::message::payload, queueForRetry(), kcenon::messaging::core::message_payload::set(), and kcenon::messaging::core::message_payload::topic.
Referenced by setupMessageHandlers().
handlePrivateMessage()
void chat_server::handlePrivateMessage (const core::message & private_message) inline
Definition at line 300 of file chat_server.cpp.
References kcenon::messaging::core::message_payload::get(), kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, kcenon::messaging::core::message::payload, sendToUser(), kcenon::messaging::core::message_payload::set(), and kcenon::messaging::core::message_payload::topic.
Referenced by setupMessageHandlers().
handleRoomJoin()
void chat_server::handleRoomJoin (const core::message & join_message) inline
Definition at line 338 of file chat_server.cpp.
References kcenon::messaging::core::message_payload::get(), kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, kcenon::messaging::core::message::payload, and sendRoomHistory().
Referenced by setupMessageHandlers().
handleRoomLeave()
void chat_server::handleRoomLeave (const core::message & leave_message) inline
Definition at line 351 of file chat_server.cpp.
References kcenon::messaging::core::message_payload::get(), kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, and kcenon::messaging::core::message::payload.
Referenced by setupMessageHandlers().
handleUserConnect()
void chat_server::handleUserConnect (const core::message & connect_message) inline
Definition at line 156 of file chat_server.cpp.
References broadcastToAll(), kcenon::messaging::core::message_payload::get(), kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, and kcenon::messaging::core::message::payload.
Referenced by setupMessageHandlers().
handleUserDisconnect()
void chat_server::handleUserDisconnect (const core::message & disconnect_message) inline
Definition at line 202 of file chat_server.cpp.
References broadcastToAll(), kcenon::messaging::core::message_metadata::headers, and kcenon::messaging::core::message::metadata.
Referenced by setupMessageHandlers().
logMessage()
void chat_server::logMessage (const std::string & sender_nickname, const std::string & message_text, const std::string & room_id) inline
Definition at line 387 of file chat_server.cpp.
Referenced by handleChatMessage().
printStats()
void chat_server::printStats () inline
Definition at line 628 of file chat_server.cpp.
Referenced by main().
queueForRetry()
void chat_server::queueForRetry (std::function< void()> task) inline
Definition at line 449 of file chat_server.cpp.
Referenced by attemptRecovery(), and handleChatMessage().
reportMetrics()
void chat_server::reportMetrics () inline
Definition at line 521 of file chat_server.cpp.
Referenced by startHealthMonitor(), and stop().
sendRoomHistory()
void chat_server::sendRoomHistory (const std::string & user_id, const std::string & room_id) inline
Definition at line 377 of file chat_server.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, kcenon::messaging::core::message::payload, sendToUser(), kcenon::messaging::core::message_payload::set(), and kcenon::messaging::core::message_payload::topic.
Referenced by handleRoomJoin().
sendToUser()
void chat_server::sendToUser (const std::string & recipient_user_id, const core::message & user_message) inline
Definition at line 373 of file chat_server.cpp.
Referenced by handlePrivateMessage(), and sendRoomHistory().
setupMessageHandlers()
void chat_server::setupMessageHandlers () inline
Definition at line 123 of file chat_server.cpp.
References handleChatMessage(), handlePrivateMessage(), handleRoomJoin(), handleRoomLeave(), handleUserConnect(), and handleUserDisconnect().
Referenced by attemptRecovery(), and chat_server().
start()
void chat_server::start (int port = 8080) inline
Definition at line 532 of file chat_server.cpp.
References cleanupInactiveUsers(), g_shutdown_cv, g_shutdown_mutex, g_shutdown_requested, and stop().
Referenced by main().
startHealthMonitor()
void chat_server::startHealthMonitor () inline
Definition at line 459 of file chat_server.cpp.
References attemptRecovery(), g_shutdown_cv, g_shutdown_mutex, g_shutdown_requested, and reportMetrics().
Referenced by chat_server().
startRetryWorker()
void chat_server::startRetryWorker () inline
Definition at line 423 of file chat_server.cpp.
References g_shutdown_requested.
Referenced by chat_server().
stop()
void chat_server::stop () inline
Definition at line 588 of file chat_server.cpp.
References broadcastToAll(), kcenon::messaging::core::message::payload, reportMetrics(), kcenon::messaging::core::message_payload::set(), and kcenon::messaging::core::message_payload::topic.
Referenced by start(), and ~chat_server().
The documentation for this class was generated from the following file:
application_layer/samples/chat_server.cpp