Messaging System: database::sqlite_manager Class Reference
database::sqlite_manager Class Reference
Manages SQLite database operations.
#include <sqlite_manager.h>
Public Member Functions
sqlite_manager (void)
Default constructor.
virtual ~sqlite_manager (void)
Destructor.
database_types database_type (void) override
Returns the specific type of the database.
bool connect (const std::string &connect_string) override
Establishes a connection to a SQLite database using the provided database path.
bool create_query (const std::string &query_string) override
Creates a query (e.g., executes DDL) using the provided SQL query string.
unsigned int insert_query (const std::string &query_string) override
Executes an INSERT query on the connected SQLite database.
unsigned int update_query (const std::string &query_string) override
Executes an UPDATE query on the connected SQLite database.
unsigned int delete_query (const std::string &query_string) override
Executes a DELETE query on the connected SQLite database.
database_result select_query (const std::string &query_string) override
Executes a SELECT query on the connected SQLite database and returns the resulting data.
bool execute_query (const std::string &query_string) override
Executes a general SQL query (DDL, DML) on SQLite.
bool disconnect (void) override
Closes the connection to the SQLite database.
Public Member Functions inherited from database::database_base
database_base (void)
Default constructor.
virtual ~database_base (void)
Virtual destructor.
Detailed Description
Manages SQLite database operations.
This class provides an implementation of the database_base interface for SQLite databases. It defines methods for connecting, querying, and disconnecting from a SQLite database using the SQLite3 C API.
Definition at line 48 of file sqlite_manager.h.
Constructor & Destructor Documentation
sqlite_manager()
database::sqlite_manager::sqlite_manager (void)
Default constructor.
Definition at line 45 of file sqlite_manager.cpp.
~sqlite_manager()
database::sqlite_manager::~sqlite_manager (void) virtual
Destructor.
Definition at line 47 of file sqlite_manager.cpp.
References disconnect().
Member Function Documentation
connect()
bool database::sqlite_manager::connect (const std::string & connect_string) override virtual
Establishes a connection to a SQLite database using the provided database path.
Parameters
connect_string A string containing the database path. Examples: "./database.db", ":memory:"
Returns
true if the connection is successfully established, false otherwise.
Implements database::database_base.
Definition at line 57 of file sqlite_manager.cpp.
References create_query().
create_query()
bool database::sqlite_manager::create_query (const std::string & query_string) override virtual
Creates a query (e.g., executes DDL) using the provided SQL query string.
Parameters
query_string The SQL query to create or execute.
Returns
true if the query is successfully executed, false otherwise.
Implements database::database_base.
Definition at line 92 of file sqlite_manager.cpp.
Referenced by connect().
database_type()
database_types database::sqlite_manager::database_type (void) override virtual
Returns the specific type of the database.
Returns
An enum value of type database_types indicating that this is a SQLite database.
Implements database::database_base.
Definition at line 52 of file sqlite_manager.cpp.
References database::sqlite.
delete_query()
unsigned int database::sqlite_manager::delete_query (const std::string & query_string) override virtual
Executes a DELETE query on the connected SQLite database.
Parameters
query_string The SQL DELETE query to be executed.
Returns
The number of rows deleted, or 0 if failed.
Implements database::database_base.
Definition at line 129 of file sqlite_manager.cpp.
disconnect()
bool database::sqlite_manager::disconnect (void) override virtual
Closes the connection to the SQLite database.
Returns
true if the disconnection is successful, false otherwise.
Implements database::database_base.
Definition at line 189 of file sqlite_manager.cpp.
Referenced by ~sqlite_manager().
execute_query()
bool database::sqlite_manager::execute_query (const std::string & query_string) override virtual
Executes a general SQL query (DDL, DML) on SQLite.
Parameters
query_string The SQL query string to execute.
Returns
true if the query executed successfully, false otherwise.
Implements database::database_base.
Definition at line 203 of file sqlite_manager.cpp.
insert_query()
unsigned int database::sqlite_manager::insert_query (const std::string & query_string) override virtual
Executes an INSERT query on the connected SQLite database.
Parameters
query_string The SQL INSERT query to be executed.
Returns
The number of rows inserted, or 0 if failed.
Implements database::database_base.
Definition at line 119 of file sqlite_manager.cpp.
select_query()
database_result database::sqlite_manager::select_query (const std::string & query_string) override virtual
Executes a SELECT query on the connected SQLite database and returns the resulting data.
Parameters
query_string The SQL SELECT query to be executed.
Returns
A database_result containing rows of data as key-value pairs.
Implements database::database_base.
Definition at line 134 of file sqlite_manager.cpp.
update_query()
unsigned int database::sqlite_manager::update_query (const std::string & query_string) override virtual
Executes an UPDATE query on the connected SQLite database.
Parameters
query_string The SQL UPDATE query to be executed.
Returns
The number of rows updated, or 0 if failed.
Implements database::database_base.
Definition at line 124 of file sqlite_manager.cpp.
The documentation for this class was generated from the following files:
libraries/database_system/database/backends/sqlite/sqlite_manager.h
libraries/database_system/database/backends/sqlite/sqlite_manager.cpp