Messaging System: libraries/logger_system/benchmarks/logger_benchmarks/logger_performance_benchmark.cpp File Reference
logger_performance_benchmark.cpp File Reference
#include <benchmark/benchmark.h>
#include <logger/logger.h>
#include <logger/writers/console_writer.h>
#include <memory>
#include <string>
Classes
class null_writer
Functions
static void setup_loggers ()
static void cleanup_loggers ()
static void BM_SyncLogging (benchmark::State &state)
BENCHMARK (BM_SyncLogging)
static void BM_AsyncLogging (benchmark::State &state)
BENCHMARK (BM_AsyncLogging)
static void BM_LoggingMessageSize (benchmark::State &state)
BENCHMARK (BM_LoggingMessageSize) -> Range(8, 8192)
static void BM_LoggingLevels (benchmark::State &state)
BENCHMARK (BM_LoggingLevels)
static void BM_LoggingWithSourceLocation (benchmark::State &state)
BENCHMARK (BM_LoggingWithSourceLocation)
static void BM_LoggerConstruction (benchmark::State &state)
BENCHMARK (BM_LoggerConstruction)
static void BM_AsyncLoggerConstruction (benchmark::State &state)
BENCHMARK (BM_AsyncLoggerConstruction)
static void BM_LogLevelCheck (benchmark::State &state)
BENCHMARK (BM_LogLevelCheck)
static void BM_FlushOperation (benchmark::State &state)
BENCHMARK (BM_FlushOperation)
int main (int argc, char **argv)
Variables
static std::unique_ptr< logger > sync_logger
static std::unique_ptr< logger > async_logger
Function Documentation
BENCHMARK() [1/9]
BENCHMARK (BM_AsyncLoggerConstruction)
BENCHMARK() [2/9]
BENCHMARK (BM_AsyncLogging)
BENCHMARK() [3/9]
BENCHMARK (BM_FlushOperation)
BENCHMARK() [4/9]
BENCHMARK (BM_LoggerConstruction)
BENCHMARK() [5/9]
BENCHMARK (BM_LoggingLevels)
BENCHMARK() [6/9]
BENCHMARK (BM_LoggingMessageSize) -> Range(8, 8192)
BENCHMARK() [7/9]
BENCHMARK (BM_LoggingWithSourceLocation)
BENCHMARK() [8/9]
BENCHMARK (BM_LogLevelCheck)
BENCHMARK() [9/9]
BENCHMARK (BM_SyncLogging)
BM_AsyncLoggerConstruction()
static void BM_AsyncLoggerConstruction (benchmark::State & state) static
Definition at line 178 of file logger_performance_benchmark.cpp.
BM_AsyncLogging()
static void BM_AsyncLogging (benchmark::State & state) static
Definition at line 96 of file logger_performance_benchmark.cpp.
References async_logger, thread_module::info, and setup_loggers().
BM_FlushOperation()
static void BM_FlushOperation (benchmark::State & state) static
Definition at line 205 of file logger_performance_benchmark.cpp.
References async_logger, thread_module::info, and setup_loggers().
BM_LoggerConstruction()
static void BM_LoggerConstruction (benchmark::State & state) static
Definition at line 168 of file logger_performance_benchmark.cpp.
BM_LoggingLevels()
static void BM_LoggingLevels (benchmark::State & state) static
Definition at line 127 of file logger_performance_benchmark.cpp.
References thread_module::critical, thread_module::debug, thread_module::error, thread_module::info, setup_loggers(), sync_logger, thread_module::trace, and thread_module::warning.
BM_LoggingMessageSize()
static void BM_LoggingMessageSize (benchmark::State & state) static
Definition at line 112 of file logger_performance_benchmark.cpp.
References thread_module::info, setup_loggers(), and sync_logger.
BM_LoggingWithSourceLocation()
static void BM_LoggingWithSourceLocation (benchmark::State & state) static
Definition at line 153 of file logger_performance_benchmark.cpp.
References thread_module::info, setup_loggers(), and sync_logger.
BM_LogLevelCheck()
static void BM_LogLevelCheck (benchmark::State & state) static
Definition at line 190 of file logger_performance_benchmark.cpp.
References thread_module::info, setup_loggers(), sync_logger, and thread_module::warning.
BM_SyncLogging()
static void BM_SyncLogging (benchmark::State & state) static
Definition at line 82 of file logger_performance_benchmark.cpp.
References thread_module::info, setup_loggers(), and sync_logger.
cleanup_loggers()
static void cleanup_loggers () static
Definition at line 75 of file logger_performance_benchmark.cpp.
References async_logger.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 220 of file logger_performance_benchmark.cpp.
References cleanup_loggers(), and setup_loggers().
setup_loggers()
static void setup_loggers () static
Definition at line 64 of file logger_performance_benchmark.cpp.
References async_logger, and sync_logger.
Referenced by BM_AsyncLogging(), BM_FlushOperation(), BM_LoggingLevels(), BM_LoggingMessageSize(), BM_LoggingWithSourceLocation(), BM_LogLevelCheck(), BM_SyncLogging(), and main().
Variable Documentation
async_logger
std::unique_ptr<logger> async_logger static
Definition at line 61 of file logger_performance_benchmark.cpp.
Referenced by BM_AsyncLogging(), BM_FlushOperation(), cleanup_loggers(), setup_loggers(), and sync_vs_async_example().
sync_logger
std::unique_ptr<logger> sync_logger static
Definition at line 60 of file logger_performance_benchmark.cpp.
Referenced by BM_LoggingLevels(), BM_LoggingMessageSize(), BM_LoggingWithSourceLocation(), BM_LogLevelCheck(), BM_SyncLogging(), setup_loggers(), and sync_vs_async_example().