Messaging System: libraries/network_system/tests/unit_tests.cpp File Reference
unit_tests.cpp File Reference
#include <gtest/gtest.h>
#include <memory>
#include <thread>
#include <chrono>
#include <vector>
#include <string>
#include <future>
#include <atomic>
#include "../network.h"
#include <container.h>
#include <values/string_value.h>
#include <values/numeric_value.h>
Classes
class NetworkTest
Functions
TEST_F (NetworkTest, ServerConstruction)
TEST_F (NetworkTest, ServerStartStop)
TEST_F (NetworkTest, ServerMultipleStartStop)
TEST_F (NetworkTest, ServerPortAlreadyInUse)
TEST_F (NetworkTest, ClientConstruction)
TEST_F (NetworkTest, ClientConnectToNonExistentServer)
TEST_F (NetworkTest, ClientServerBasicConnection)
TEST_F (NetworkTest, MultipleClientsConnection)
TEST_F (NetworkTest, BasicMessageTransfer)
TEST_F (NetworkTest, LargeMessageTransfer)
TEST_F (NetworkTest, MultipleMessageTransfer)
TEST (NetworkStressTest, RapidConnectionDisconnection)
TEST (NetworkStressTest, ConcurrentClients)
TEST_F (NetworkTest, SendWithoutConnection)
TEST_F (NetworkTest, ServerStopWhileClientsConnected)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 488 of file unit_tests.cpp.
TEST() [1/2]
TEST (NetworkStressTest , ConcurrentClients)
Definition at line 378 of file unit_tests.cpp.
TEST() [2/2]
TEST (NetworkStressTest , RapidConnectionDisconnection)
Definition at line 338 of file unit_tests.cpp.
TEST_F() [1/13]
TEST_F (NetworkTest , BasicMessageTransfer)
Definition at line 227 of file unit_tests.cpp.
References FindAvailablePort().
TEST_F() [2/13]
TEST_F (NetworkTest , ClientConnectToNonExistentServer)
Definition at line 150 of file unit_tests.cpp.
TEST_F() [3/13]
TEST_F (NetworkTest , ClientConstruction)
Definition at line 145 of file unit_tests.cpp.
TEST_F() [4/13]
TEST_F (NetworkTest , ClientServerBasicConnection)
Definition at line 168 of file unit_tests.cpp.
References FindAvailablePort().
TEST_F() [5/13]
TEST_F (NetworkTest , LargeMessageTransfer)
Definition at line 264 of file unit_tests.cpp.
References FindAvailablePort().
TEST_F() [6/13]
TEST_F (NetworkTest , MultipleClientsConnection)
Definition at line 190 of file unit_tests.cpp.
References FindAvailablePort().
TEST_F() [7/13]
TEST_F (NetworkTest , MultipleMessageTransfer)
Definition at line 298 of file unit_tests.cpp.
References FindAvailablePort().
TEST_F() [8/13]
TEST_F (NetworkTest , SendWithoutConnection)
Definition at line 444 of file unit_tests.cpp.
TEST_F() [9/13]
TEST_F (NetworkTest , ServerConstruction)
Definition at line 86 of file unit_tests.cpp.
TEST_F() [10/13]
TEST_F (NetworkTest , ServerMultipleStartStop)
Definition at line 107 of file unit_tests.cpp.
References FindAvailablePort().
TEST_F() [11/13]
TEST_F (NetworkTest , ServerPortAlreadyInUse)
Definition at line 122 of file unit_tests.cpp.
References FindAvailablePort().
TEST_F() [12/13]
TEST_F (NetworkTest , ServerStartStop)
Definition at line 91 of file unit_tests.cpp.
References FindAvailablePort().
TEST_F() [13/13]
TEST_F (NetworkTest , ServerStopWhileClientsConnected)
Definition at line 457 of file unit_tests.cpp.
References FindAvailablePort().