Messaging System: fmt::formatter< typed_thread_pool_module::typed_thread_pool_t< job_type > > Struct Template Reference
fmt::formatter< typed_thread_pool_module::typed_thread_pool_t< job_type > > Struct Template Reference
Specialization of fmt::formatter for typed_thread_pool_t<job_type>.
#include <typed_thread_pool.h>
Public Member Functions
template<typename FormatContext >
auto format (const typed_thread_pool_module::typed_thread_pool_t< job_type > &item, FormatContext &ctx) const
Formats a typed_thread_pool_t<job_type> object as a string.
template<typename FormatContext >
auto format (const typed_thread_pool_module::typed_thread_pool_t< job_type > &item, FormatContext &ctx) const
Formats a typed_thread_pool_t<job_type> object as a string.
template<typename FormatContext >
auto format (const typed_thread_pool_module::typed_thread_pool_t< job_type > &item, FormatContext &ctx) const
Formats a typed_thread_pool_t<job_type> object as a string.
Detailed Description
template<typename job_type>
struct fmt::formatter< typed_thread_pool_module::typed_thread_pool_t< job_type > >
Specialization of fmt::formatter for typed_thread_pool_t<job_type>.
Allows formatting of typed_thread_pool_t<job_type> objects as strings using the {fmt} library (https://github.com/fmtlib/fmt).
Definition at line 413 of file typed_thread_pool.h.
Member Function Documentation
format() [1/3]
template<typename job_type > template<typename FormatContext > auto fmt::formatter< typed_thread_pool_module::typed_thread_pool_t< job_type > >::format (const typed_thread_pool_module::typed_thread_pool_t< job_type > & item, FormatContext & ctx) const inline
Formats a typed_thread_pool_t<job_type> object as a string.
Template Parameters
FormatContext Type of the format context.
Parameters
item The typed_thread_pool_t<job_type> object to format.
ctx The format context for the output.
Returns
An iterator to the end of the formatted output.
Definition at line 425 of file typed_thread_pool.h.
References typed_thread_pool_module::typed_thread_pool_t< job_type >::to_string().
format() [2/3]
template<typename job_type > template<typename FormatContext > auto fmt::formatter< typed_thread_pool_module::typed_thread_pool_t< job_type > >::format (const typed_thread_pool_module::typed_thread_pool_t< job_type > & item, FormatContext & ctx) const inline
Formats a typed_thread_pool_t<job_type> object as a string.
Template Parameters
FormatContext Type of the format context.
Parameters
item The typed_thread_pool_t<job_type> object to format.
ctx The format context for the output.
Returns
An iterator to the end of the formatted output.
Definition at line 425 of file typed_thread_pool.h.
References typed_thread_pool_module::typed_thread_pool_t< job_type >::to_string().
format() [3/3]
template<typename job_type > template<typename FormatContext > auto fmt::formatter< typed_thread_pool_module::typed_thread_pool_t< job_type > >::format (const typed_thread_pool_module::typed_thread_pool_t< job_type > & item, FormatContext & ctx) const inline
Formats a typed_thread_pool_t<job_type> object as a string.
Template Parameters
FormatContext Type of the format context.
Parameters
item The typed_thread_pool_t<job_type> object to format.
ctx The format context for the output.
Returns
An iterator to the end of the formatted output.
Definition at line 425 of file typed_thread_pool.h.
References typed_thread_pool_module::typed_thread_pool_t< job_type >::to_string().
The documentation for this struct was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/typed_thread_pool/pool/typed_thread_pool.h
libraries/thread_system/modular_structure/core/src/typed_thread_pool/pool/typed_thread_pool.h
libraries/thread_system/sources/typed_thread_pool/pool/typed_thread_pool.h