Messaging System: network_system::integration::container_manager Class Reference
network_system::integration::container_manager Class Reference
Manager for container system integration.
#include <container_integration.h>
Classes
class impl
Public Member Functions
void register_container (const std::string &name, std::shared_ptr< container_interface > container)
Register a container implementation.
std::shared_ptr< container_interface > get_container (const std::string &name) const
Get a registered container.
void set_default_container (std::shared_ptr< container_interface > container)
Set default container.
std::shared_ptr< container_interface > get_default_container ()
Get default container.
std::vector< uint8_t > serialize (const std::any &data)
Serialize using default container.
std::any deserialize (const std::vector< uint8_t > &bytes)
Deserialize using default container.
std::vector< std::string > list_containers () const
Get list of registered container names.
Static Public Member Functions
static container_manager & instance ()
Get the singleton instance.
Detailed Description
Manager for container system integration.
This class manages the integration between network_system and container implementations.
Definition at line 148 of file container_integration.h.
Member Function Documentation
deserialize()
std::any network_system::integration::container_manager::deserialize (const std::vector< uint8_t > & bytes)
Deserialize using default container.
Parameters
bytes Bytes to deserialize
Returns
Deserialized data
Definition at line 271 of file container_integration.cpp.
get_container()
std::shared_ptr< container_interface > network_system::integration::container_manager::get_container (const std::string & name) const
Get a registered container.
Parameters
name Container name
Returns
Container implementation or nullptr if not found
Definition at line 251 of file container_integration.cpp.
get_default_container()
std::shared_ptr< container_interface > network_system::integration::container_manager::get_default_container ()
Get default container.
Returns
Default container (creates basic container if none set)
Definition at line 263 of file container_integration.cpp.
instance()
container_manager & network_system::integration::container_manager::instance () static
Get the singleton instance.
Returns
Reference to the singleton instance
Definition at line 233 of file container_integration.cpp.
References instance().
Referenced by benchmark_container_serialization(), demonstrate_integration_features(), network_system::compat::initialize(), instance(), test_container_integration(), test_container_integration(), test_init_shutdown(), and test_legacy_container_integration().
list_containers()
std::vector< std::string > network_system::integration::container_manager::list_containers () const
Get list of registered container names.
Returns
Vector of container names
Definition at line 275 of file container_integration.cpp.
register_container()
void network_system::integration::container_manager::register_container (const std::string & name, std::shared_ptr< container_interface > container)
Register a container implementation.
Parameters
name Container name
container Container implementation
Definition at line 244 of file container_integration.cpp.
serialize()
std::vector< uint8_t > network_system::integration::container_manager::serialize (const std::any & data)
Serialize using default container.
Parameters
data Data to serialize
Returns
Serialized bytes
Definition at line 267 of file container_integration.cpp.
set_default_container()
void network_system::integration::container_manager::set_default_container (std::shared_ptr< container_interface > container)
Set default container.
Parameters
container Default container to use
Definition at line 257 of file container_integration.cpp.
The documentation for this class was generated from the following files:
libraries/network_system/include/network_system/integration/container_integration.h
libraries/network_system/src/integration/container_integration.cpp