Messaging System: monitoring_system::monitorable_component Class Reference
monitoring_system::monitorable_component Class Reference
Base class providing default monitorable implementation.
#include <monitorable_interface.h>
Public Member Functions
monitorable_component (const std::string &id)
Constructor.
std::string get_monitoring_id () const override
Get monitoring identifier.
bool is_monitoring_enabled () const override
Check if monitoring is enabled.
result_void set_monitoring_enabled (bool enable) override
Enable or disable monitoring.
result_void reset_monitoring () override
Reset monitoring data.
Public Member Functions inherited from monitoring_system::monitorable_interface
virtual ~monitorable_interface ()=default
virtual result< monitoring_data > get_monitoring_data () const =0
Get current monitoring data from the component.
Protected Member Functions
void update_metric (const std::string &key, double value) const
Helper to update a metric.
void update_tag (const std::string &key, const std::string &value) const
Helper to update a tag.
Protected Attributes
std::string monitoring_id_
bool monitoring_enabled_ = true
monitoring_data cached_data_
Detailed Description
Base class providing default monitorable implementation.
This class provides a convenient base for components that want to implement the monitorable interface with common functionality.
Definition at line 263 of file monitorable_interface.h.
Constructor & Destructor Documentation
monitorable_component()
monitoring_system::monitorable_component::monitorable_component (const std::string & id) inline explicit
Constructor.
Parameters
id Monitoring identifier for this component
Definition at line 274 of file monitorable_interface.h.
Member Function Documentation
get_monitoring_id()
std::string monitoring_system::monitorable_component::get_monitoring_id () const inline override virtual
Get monitoring identifier.
Returns
Component's monitoring ID
Implements monitoring_system::monitorable_interface.
Definition at line 282 of file monitorable_interface.h.
References monitoring_id_.
Referenced by test_monitorable_component::get_monitoring_data(), and TEST_F().
is_monitoring_enabled()
bool monitoring_system::monitorable_component::is_monitoring_enabled () const inline override virtual
Check if monitoring is enabled.
Returns
true if monitoring is active
Reimplemented from monitoring_system::monitorable_interface.
Definition at line 290 of file monitorable_interface.h.
References monitoring_enabled_.
Referenced by test_monitorable_component::get_monitoring_data(), TEST_F(), and TEST_F().
reset_monitoring()
result_void monitoring_system::monitorable_component::reset_monitoring () inline override virtual
Reset monitoring data.
Returns
Result indicating success
Reimplemented from monitoring_system::monitorable_interface.
Definition at line 308 of file monitorable_interface.h.
References cached_data_, monitoring_system::monitoring_data::clear(), monitoring_id_, and monitoring_system::monitoring_data::set_component_name().
Referenced by TEST_F().
set_monitoring_enabled()
result_void monitoring_system::monitorable_component::set_monitoring_enabled (bool enable) inline override virtual
Enable or disable monitoring.
Parameters
enable true to enable, false to disable
Returns
Result indicating success
Reimplemented from monitoring_system::monitorable_interface.
Definition at line 299 of file monitorable_interface.h.
References monitoring_enabled_.
Referenced by TEST_F().
update_metric()
void monitoring_system::monitorable_component::update_metric (const std::string & key, double value) const inline protected
Helper to update a metric.
Parameters
key Metric name
value Metric value
Definition at line 320 of file monitorable_interface.h.
References monitoring_system::monitoring_data::add_metric(), and cached_data_.
update_tag()
void monitoring_system::monitorable_component::update_tag (const std::string & key, const std::string & value) const inline protected
Helper to update a tag.
Parameters
key Tag name
value Tag value
Definition at line 329 of file monitorable_interface.h.
References monitoring_system::monitoring_data::add_tag(), and cached_data_.
Member Data Documentation
cached_data_
monitoring_data monitoring_system::monitorable_component::cached_data_ mutable protected
Definition at line 267 of file monitorable_interface.h.
Referenced by reset_monitoring(), update_metric(), and update_tag().
monitoring_enabled_
bool monitoring_system::monitorable_component::monitoring_enabled_ = true protected
Definition at line 266 of file monitorable_interface.h.
Referenced by is_monitoring_enabled(), and set_monitoring_enabled().
monitoring_id_
std::string monitoring_system::monitorable_component::monitoring_id_ protected
Definition at line 265 of file monitorable_interface.h.
Referenced by get_monitoring_id(), and reset_monitoring().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/interfaces/monitorable_interface.h