Messaging System: monitoring_system::adaptive_scope Class Reference
monitoring_system::adaptive_scope Class Reference
Adaptive monitoring scope.
#include <adaptive_monitor.h>
Public Member Functions
adaptive_scope (const std::string &name, std::shared_ptr< monitoring_system::metrics_collector > collector, const adaptive_config &config={})
~adaptive_scope ()
adaptive_scope (const adaptive_scope &)=delete
adaptive_scope & operator= (const adaptive_scope &)=delete
adaptive_scope (adaptive_scope &&other) noexcept
adaptive_scope & operator= (adaptive_scope &&other) noexcept
bool is_registered () const
Detailed Description
Adaptive monitoring scope.
Definition at line 407 of file adaptive_monitor.h.
Constructor & Destructor Documentation
adaptive_scope() [1/3]
monitoring_system::adaptive_scope::adaptive_scope (const std::string & name, std::shared_ptr< monitoring_system::metrics_collector > collector, const adaptive_config & config = {}) inline
Definition at line 414 of file adaptive_monitor.h.
~adaptive_scope()
monitoring_system::adaptive_scope::~adaptive_scope () inline
Definition at line 423 of file adaptive_monitor.h.
References monitoring_system::adaptive_monitor::unregister_collector().
adaptive_scope() [2/3]
monitoring_system::adaptive_scope::adaptive_scope (const adaptive_scope &) delete
adaptive_scope() [3/3]
monitoring_system::adaptive_scope::adaptive_scope (adaptive_scope && other) inline noexcept
Definition at line 434 of file adaptive_monitor.h.
Member Function Documentation
is_registered()
bool monitoring_system::adaptive_scope::is_registered () const inline
Definition at line 456 of file adaptive_monitor.h.
Referenced by TEST_F().
operator=() [1/2]
adaptive_scope & monitoring_system::adaptive_scope::operator= (adaptive_scope && other) inline noexcept
Definition at line 442 of file adaptive_monitor.h.
References monitoring_system::adaptive_monitor::unregister_collector().
operator=() [2/2]
adaptive_scope & monitoring_system::adaptive_scope::operator= (const adaptive_scope &) delete
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/impl/adaptive_monitor.h