Messaging System: kcenon::thread::error Class Reference
kcenon::thread::error Class Reference
Represents an error in the thread system.
#include <error_handling.h>
Public Member Functions
error (error_code code, std::string message={})
Constructs an error with a code and optional message.
error_code code () const noexcept
Gets the error code.
const std::string & message () const noexcept
Gets the error message.
std::string to_string () const
Converts the error to a string representation.
operator std::string () const
Implicit conversion to string.
error (error_code code, std::string message={})
Constructs an error with a code and optional message.
error_code code () const noexcept
Gets the error code.
const std::string & message () const noexcept
Gets the error message.
std::string to_string () const
Converts the error to a string representation.
operator std::string () const
Implicit conversion to string.
Detailed Description
Represents an error in the thread system.
This class encapsulates an error code and an optional message.
Definition at line 139 of file error_handling.h.
Constructor & Destructor Documentation
error() [1/2]
kcenon::thread::error::error (error_code code, std::string message = {}) inline explicit
Constructs an error with a code and optional message.
Parameters
code The error code
message Optional detailed message about the error
Definition at line 146 of file error_handling.h.
error() [2/2]
kcenon::thread::error::error (error_code code, std::string message = {}) inline explicit
Constructs an error with a code and optional message.
Parameters
code The error code
message Optional detailed message about the error
Definition at line 146 of file error_handling.h.
Member Function Documentation
code() [1/2]
error_code kcenon::thread::error::code () const inline noexcept
Gets the error code.
Returns
The error code
Definition at line 153 of file error_handling.h.
Referenced by kcenon::thread::test::TEST_F(), TEST_F(), and TEST_F().
code() [2/2]
error_code kcenon::thread::error::code () const inline noexcept
Gets the error code.
Returns
The error code
Definition at line 153 of file error_handling.h.
message() [1/2]
const std::string & kcenon::thread::error::message () const inline noexcept
Gets the error message.
Returns
The error message
Definition at line 159 of file error_handling.h.
Referenced by basic_spsc_example(), basic_typed_queue_example(), batch_operations_example(), kcenon::thread::typed_thread_pool_builder< job_type >::build(), create_priority_default(), different_strategies_example(), mpmc_typed_queue_example(), task_scheduling_example(), TEST_F(), and web_server_simulation().
message() [2/2]
const std::string & kcenon::thread::error::message () const inline noexcept
Gets the error message.
Returns
The error message
Definition at line 159 of file error_handling.h.
operator std::string() [1/2]
kcenon::thread::error::operator std::string () const inline
Implicit conversion to string.
Definition at line 175 of file error_handling.h.
References to_string().
operator std::string() [2/2]
kcenon::thread::error::operator std::string () const inline
Implicit conversion to string.
Definition at line 175 of file error_handling.h.
References to_string().
to_string() [1/2]
std::string kcenon::thread::error::to_string () const inline
Converts the error to a string representation.
Returns
A string describing the error
Definition at line 165 of file error_handling.h.
References kcenon::thread::error_code_to_string().
Referenced by main(), main(), operator std::string(), kcenon::thread::result< T >::value_or_throw(), kcenon::thread::result< void >::value_or_throw(), and kcenon::thread::result< T >::value_or_throw().
to_string() [2/2]
std::string kcenon::thread::error::to_string () const inline
Converts the error to a string representation.
Returns
A string describing the error
Definition at line 165 of file error_handling.h.
References kcenon::thread::error_code_to_string().
The documentation for this class was generated from the following files:
libraries/thread_system/core/sync/include/error_handling.h
libraries/thread_system/include/kcenon/thread/core/error_handling.h