Messaging System: thread_module::thread_base Class Reference
thread_module::thread_base Class Reference
A foundational class for implementing custom worker threads.
#include <thread_base.h>
Public Member Functions
thread_base (const thread_base &)=delete
thread_base & operator= (const thread_base &)=delete
thread_base (thread_base &&)=delete
thread_base & operator= (thread_base &&)=delete
thread_base (const std::string &thread_title="thread_base")
Constructs a new thread_base object.
virtual ~thread_base (void)
Virtual destructor.
auto set_wake_interval (const std::optional< std::chrono::milliseconds > &wake_interval) -> void
Sets the interval at which the worker thread should wake up (if any).
auto get_wake_interval () const -> std::optional< std::chrono::milliseconds >
Gets the current wake interval setting.
auto start (void) -> result_void
Starts the worker thread.
auto stop (void) -> result_void
Requests the worker thread to stop and waits for it to finish.
auto get_thread_title () const -> std::string
Returns the worker thread's title.
auto is_running () const -> bool
Checks whether the worker thread is currently running.
virtual auto to_string (void) const -> std::string
Returns a string representation of this thread_base object.
thread_base (const thread_base &)=delete
thread_base & operator= (const thread_base &)=delete
thread_base (thread_base &&)=delete
thread_base & operator= (thread_base &&)=delete
thread_base (const std::string &thread_title="thread_base")
Constructs a new thread_base object.
virtual ~thread_base (void)
Virtual destructor.
auto set_wake_interval (const std::optional< std::chrono::milliseconds > &wake_interval) -> void
Sets the interval at which the worker thread should wake up (if any).
auto get_wake_interval () const -> std::optional< std::chrono::milliseconds >
Gets the current wake interval setting.
auto start (void) -> result_void
Starts the worker thread.
auto stop (void) -> result_void
Requests the worker thread to stop and waits for it to finish.
auto get_thread_title () const -> std::string
Returns the worker thread's title.
auto is_running () const -> bool
Checks whether the worker thread is currently running.
virtual auto to_string (void) const -> std::string
Returns a string representation of this thread_base object.
thread_base (const thread_base &)=delete
thread_base & operator= (const thread_base &)=delete
thread_base (thread_base &&)=delete
thread_base & operator= (thread_base &&)=delete
thread_base (const std::string &thread_title="thread_base")
Constructs a new thread_base object.
virtual ~thread_base (void)
Virtual destructor.
auto set_wake_interval (const std::optional< std::chrono::milliseconds > &wake_interval) -> void
Sets the interval at which the worker thread should wake up (if any).
auto get_wake_interval () const -> std::optional< std::chrono::milliseconds >
Gets the current wake interval setting.
auto start (void) -> result_void
Starts the worker thread.
auto stop (void) -> result_void
Requests the worker thread to stop and waits for it to finish.
auto get_thread_title () const -> std::string
Returns the worker thread's title.
auto is_running () const -> bool
Checks whether the worker thread is currently running.
virtual auto to_string (void) const -> std::string
Returns a string representation of this thread_base object.
Protected Member Functions
virtual auto should_continue_work (void) const -> bool
Determines whether the thread should continue doing work.
virtual auto before_start (void) -> result_void
Called just before the worker thread starts running.
virtual auto do_work (void) -> result_void
The main work routine for the worker thread.
virtual auto after_stop (void) -> result_void
Called immediately after the worker thread has stopped.
virtual auto should_continue_work (void) const -> bool
Determines whether the thread should continue doing work.
virtual auto before_start (void) -> result_void
Called just before the worker thread starts running.
virtual auto do_work (void) -> result_void
The main work routine for the worker thread.
virtual auto after_stop (void) -> result_void
Called immediately after the worker thread has stopped.
virtual auto should_continue_work (void) const -> bool
Determines whether the thread should continue doing work.
virtual auto before_start (void) -> result_void
Called just before the worker thread starts running.
virtual auto do_work (void) -> result_void
The main work routine for the worker thread.
virtual auto after_stop (void) -> result_void
Called immediately after the worker thread has stopped.
Protected Attributes
std::optional< std::chrono::milliseconds > wake_interval_
Interval at which the thread is optionally awakened.
Detailed Description
A foundational class for implementing custom worker threads.
The thread_base class provides a framework for managing a single worker thread, offering lifecycle methods (start, stop), optional wake intervals, and hooks (before_start, do_work, after_stop) for derived classes to customize behavior.
This class abstracts platform-specific thread management details and provides a unified interface for both C++20 std::jthread and traditional std::thread, selected at compile time via the USE_STD_JTHREAD macro.
Key Features
Standardized thread lifecycle management (start/stop)
Thread condition monitoring
Customizable worker behavior through virtual method overrides
Optional periodic wake intervals for recurring tasks
Built-in cancellation support (via std::jthread or custom mechanism)
Thread-safe signaling and state management
Thread Safety
All public methods in thread_base are thread-safe. The class uses internal synchronization mechanisms to protect its state.
Typical Usage
Inherit from thread_base and override do_work(), before_start(), and/or after_stop() as needed.
Instantiate your derived class, set a wake interval if desired, then call start() to launch the thread.
When shutting down or no longer needing the thread's work, call stop().
The thread can periodically check should_continue_work() or internal conditions to determine if it should continue running.
Example
class my_worker : public thread_base {
public:
    my_worker() : thread_base("my_worker") {}
protected:
    result_void before_start() override {
        // Initialize resources
        return {};
    }
    result_void do_work() override {
        // Perform work
        return {};
    }
    result_void after_stop() override {
        // Clean up resources
        return {};
    }
};
int main() {
    auto worker = std::make_unique<my_worker>();
    worker->set_wake_interval(std::chrono::milliseconds(100)); // Wake every 100ms
    auto result = worker->start();
    // Do other work...
    worker->stop();
    return 0;
}
See also
thread_module::job For the work unit class processed by workers
thread_module::job_queue For the thread-safe queue used with workers
thread_pool_module::thread_worker For a specialized worker implementation
The thread_base class provides a framework for managing a single worker thread, offering lifecycle methods (start, stop), optional wake intervals, and hooks (before_start, do_work, after_stop) for derived classes to customize behavior.
This class abstracts platform-specific thread management details and provides a unified interface for both C++20 std::jthread and traditional std::thread, selected at compile time via the USE_STD_JTHREAD macro.
Key Features
Standardized thread lifecycle management (start/stop)
Thread condition monitoring
Customizable worker behavior through virtual method overrides
Optional periodic wake intervals for recurring tasks
Built-in cancellation support (via std::jthread or custom mechanism)
Thread-safe signaling and state management
Thread Safety
All public methods in thread_base are thread-safe. The class uses internal synchronization mechanisms to protect its state.
Typical Usage
Inherit from thread_base and override do_work(), before_start(), and/or after_stop() as needed.
Instantiate your derived class, set a wake interval if desired, then call start() to launch the thread.
When shutting down or no longer needing the thread's work, call stop().
The thread can periodically check should_continue_work() or internal conditions to determine if it should continue running.
Example
class my_worker : public thread_base {
public:
    my_worker() : thread_base("my_worker") {}
protected:
    result_void before_start() override {
        // Initialize resources
        return {};
    }
    result_void do_work() override {
        // Perform work
        return {};
    }
    result_void after_stop() override {
        // Clean up resources
        return {};
    }
};
int main() {
    auto worker = std::make_unique<my_worker>();
    worker->set_wake_interval(std::chrono::milliseconds(100)); // Wake every 100ms
    auto result = worker->start();
    // Do other work...
    worker->stop();
    return 0;
}
See also
thread_module::job For the work unit class processed by workers
thread_module::job_queue For the thread-safe queue used with workers
thread_pool_module::thread_worker For a specialized worker implementation
The thread_base class provides a framework for managing a single worker thread, offering lifecycle methods (start, stop), optional wake intervals, and hooks (before_start, do_work, after_stop) for derived classes to customize behavior.
This class abstracts platform-specific thread management details and provides a unified interface for both C++20 std::jthread and traditional std::thread, selected at compile time via the USE_STD_JTHREAD macro.
Key Features
Standardized thread lifecycle management (start/stop)
Thread condition monitoring
Customizable worker behavior through virtual method overrides
Optional periodic wake intervals for recurring tasks
Built-in cancellation support (via std::jthread or custom mechanism)
Thread-safe signaling and state management
Thread Safety
All public methods in thread_base are thread-safe. The class uses internal synchronization mechanisms to protect its state.
Typical Usage
Inherit from thread_base and override do_work(), before_start(), and/or after_stop() as needed.
Instantiate your derived class, set a wake interval if desired, then call start() to launch the thread.
When shutting down or no longer needing the thread's work, call stop().
The thread can periodically check should_continue_work() or internal conditions to determine if it should continue running.
Example
class my_worker : public thread_base {
public:
    my_worker() : thread_base("my_worker") {}
protected:
    result_void before_start() override {
        // Initialize resources
        return {};
    }
    result_void do_work() override {
        // Perform work
        return {};
    }
    result_void after_stop() override {
        // Clean up resources
        return {};
    }
};
int main() {
    auto worker = std::make_unique<my_worker>();
    worker->set_wake_interval(std::chrono::milliseconds(100)); // Wake every 100ms
    auto result = worker->start();
    // Do other work...
    worker->stop();
    return 0;
}
See also
thread_module::job For the work unit class processed by workers
thread_module::job_queue For the thread-safe queue used with workers
thread_pool_module::thread_worker For a specialized worker implementation
Definition at line 150 of file thread_base.h.
Constructor & Destructor Documentation
thread_base() [1/9]
thread_module::thread_base::thread_base (const thread_base &) delete
thread_base() [2/9]
thread_module::thread_base::thread_base (thread_base &&) delete
thread_base() [3/9]
thread_module::thread_base::thread_base (const std::string & thread_title = "thread_base")
Constructs a new thread_base object.
Constructs a new thread_base instance with the specified title.
Parameters
thread_title A human-readable title for this worker thread (default: "thread_base").
The thread_title can be useful for logging, debugging, or thread naming (where the platform supports it).
Implementation details:
Initializes the worker_thread_ pointer to nullptr (thread not started)
Sets up thread control mechanisms based on configuration:
In C++20 mode (USE_STD_JTHREAD), initializes stop_source_ to std::nullopt
In legacy mode, initializes stop_requested_ to false
Sets wake_interval_ to std::nullopt (no periodic wake-ups by default)
Sets thread_title_ to the provided title
Sets initial thread_condition_ to Created
Definition at line 57 of file thread_base.cpp.
~thread_base() [1/3]
thread_module::thread_base::~thread_base (void) virtual
Virtual destructor.
Destroys the thread_base instance, stopping the thread if needed.
Ensures proper cleanup of derived classes.
If the thread is still running when the destructor is called, stop() is typically called internally to join the thread before destruction.
Implementation details:
Calls stop() to ensure the thread is properly terminated
The stop() method handles joining the thread and cleaning up resources
This ensures no thread resources are leaked when the object is destroyed
Note
This destructor is virtual, allowing derived classes to perform their own cleanup operations in their destructors.
Definition at line 81 of file thread_base.cpp.
References stop().
thread_base() [4/9]
thread_module::thread_base::thread_base (const thread_base &) delete
thread_base() [5/9]
thread_module::thread_base::thread_base (thread_base &&) delete
thread_base() [6/9]
thread_module::thread_base::thread_base (const std::string & thread_title = "thread_base")
Constructs a new thread_base object.
Parameters
thread_title A human-readable title for this worker thread (default: "thread_base").
The thread_title can be useful for logging, debugging, or thread naming (where the platform supports it).
~thread_base() [2/3]
virtual thread_module::thread_base::~thread_base (void) virtual
Virtual destructor.
Ensures proper cleanup of derived classes.
If the thread is still running when the destructor is called, stop() is typically called internally to join the thread before destruction.
thread_base() [7/9]
thread_module::thread_base::thread_base (const thread_base &) delete
thread_base() [8/9]
thread_module::thread_base::thread_base (thread_base &&) delete
thread_base() [9/9]
thread_module::thread_base::thread_base (const std::string & thread_title = "thread_base")
Constructs a new thread_base object.
Parameters
thread_title A human-readable title for this worker thread (default: "thread_base").
The thread_title can be useful for logging, debugging, or thread naming (where the platform supports it).
~thread_base() [3/3]
virtual thread_module::thread_base::~thread_base (void) virtual
Virtual destructor.
Ensures proper cleanup of derived classes.
If the thread is still running when the destructor is called, stop() is typically called internally to join the thread before destruction.
Member Function Documentation
after_stop() [1/3]
virtual auto thread_module::thread_base::after_stop (void) -> result_void inline protected virtual
Called immediately after the worker thread has stopped.
Returns
result_void containing an error on failure, or success value if successful.
Override this method in derived classes to perform any cleanup or finalization tasks once the worker thread has fully exited.
Definition at line 281 of file thread_base.h.
after_stop() [2/3]
virtual auto thread_module::thread_base::after_stop (void) -> result_void inline protected virtual
Called immediately after the worker thread has stopped.
Returns
result_void containing an error on failure, or success value if successful.
Override this method in derived classes to perform any cleanup or finalization tasks once the worker thread has fully exited.
Definition at line 281 of file thread_base.h.
after_stop() [3/3]
virtual auto thread_module::thread_base::after_stop (void) -> result_void inline protected virtual
Called immediately after the worker thread has stopped.
Returns
result_void containing an error on failure, or success value if successful.
Override this method in derived classes to perform any cleanup or finalization tasks once the worker thread has fully exited.
Definition at line 281 of file thread_base.h.
before_start() [1/3]
virtual auto thread_module::thread_base::before_start (void) -> result_void inline protected virtual
Called just before the worker thread starts running.
Returns
result_void containing an error on failure, or success value if successful.
Override this method in derived classes to perform any initialization or setup required before the worker thread begins its main loop.
Definition at line 262 of file thread_base.h.
before_start() [2/3]
virtual auto thread_module::thread_base::before_start (void) -> result_void inline protected virtual
Called just before the worker thread starts running.
Returns
result_void containing an error on failure, or success value if successful.
Override this method in derived classes to perform any initialization or setup required before the worker thread begins its main loop.
Definition at line 262 of file thread_base.h.
before_start() [3/3]
virtual auto thread_module::thread_base::before_start (void) -> result_void inline protected virtual
Called just before the worker thread starts running.
Returns
result_void containing an error on failure, or success value if successful.
Override this method in derived classes to perform any initialization or setup required before the worker thread begins its main loop.
Definition at line 262 of file thread_base.h.
do_work() [1/3]
virtual auto thread_module::thread_base::do_work (void) -> result_void inline protected virtual
The main work routine for the worker thread.
Returns
result_void containing an error on failure, or success value if successful.
Derived classes should override this method to implement the actual work the thread needs to perform. This method is called repeatedly (in an internal loop) until the thread is signaled to stop or should_continue_work() returns false.
Reimplemented in WakeIntervalTestWorker, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, and typed_thread_pool_module::typed_thread_worker_t< priority_job_types >.
Definition at line 272 of file thread_base.h.
Referenced by TEST_F().
do_work() [2/3]
virtual auto thread_module::thread_base::do_work (void) -> result_void inline protected virtual
The main work routine for the worker thread.
Returns
result_void containing an error on failure, or success value if successful.
Derived classes should override this method to implement the actual work the thread needs to perform. This method is called repeatedly (in an internal loop) until the thread is signaled to stop or should_continue_work() returns false.
Reimplemented in WakeIntervalTestWorker, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, and typed_thread_pool_module::typed_thread_worker_t< priority_job_types >.
Definition at line 272 of file thread_base.h.
do_work() [3/3]
virtual auto thread_module::thread_base::do_work (void) -> result_void inline protected virtual
The main work routine for the worker thread.
Returns
result_void containing an error on failure, or success value if successful.
Derived classes should override this method to implement the actual work the thread needs to perform. This method is called repeatedly (in an internal loop) until the thread is signaled to stop or should_continue_work() returns false.
Reimplemented in WakeIntervalTestWorker, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, and typed_thread_pool_module::typed_thread_worker_t< priority_job_types >.
Definition at line 272 of file thread_base.h.
get_thread_title() [1/3]
auto thread_module::thread_base::get_thread_title () const -> std::string inline
Returns the worker thread's title.
Returns
A string representing the thread's title.
Definition at line 224 of file thread_base.h.
get_thread_title() [2/3]
auto thread_module::thread_base::get_thread_title () const -> std::string inline
Returns the worker thread's title.
Returns
A string representing the thread's title.
Definition at line 224 of file thread_base.h.
get_thread_title() [3/3]
auto thread_module::thread_base::get_thread_title () const -> std::string inline
Returns the worker thread's title.
Returns
A string representing the thread's title.
Definition at line 224 of file thread_base.h.
get_wake_interval() [1/3]
auto thread_module::thread_base::get_wake_interval () const -> std::optional<std::chrono::milliseconds>
Gets the current wake interval setting.
Returns
The wake interval if set, or std::nullopt if periodic wake-ups are disabled.
Note
This method is thread-safe.
Implementation details:
Uses the same mutex as set_wake_interval() for consistency
Returns a copy of the current wake_interval_ value
std::nullopt indicates no periodic wake-ups are configured
Thread Safety:
Safe to call from any thread concurrently with set_wake_interval()
The mutex ensures consistent reads even during concurrent modifications
Returns
Current wake interval or std::nullopt if disabled
Definition at line 118 of file thread_base.cpp.
References wake_interval_.
get_wake_interval() [2/3]
auto thread_module::thread_base::get_wake_interval () const -> std::optional< std::chrono::milliseconds >
Gets the current wake interval setting.
Returns
The wake interval if set, or std::nullopt if periodic wake-ups are disabled.
Note
This method is thread-safe.
get_wake_interval() [3/3]
auto thread_module::thread_base::get_wake_interval () const -> std::optional< std::chrono::milliseconds >
Gets the current wake interval setting.
Returns
The wake interval if set, or std::nullopt if periodic wake-ups are disabled.
Note
This method is thread-safe.
is_running() [1/3]
auto thread_module::thread_base::is_running (void) const -> bool
Checks whether the worker thread is currently running.
Checks if the worker thread is currently active.
Returns
true if the thread is running, false otherwise.
This depends on the thread's internal condition state (e.g., thread_conditions::running).
Implementation details:
Uses the atomic thread_condition_ member instead of checking thread pointers
This is more reliable as it reflects the actual thread state
Considers both Working and Waiting states as "running"
Thread-safe operation due to atomic load
Thread States Considered "Running":
Working: Thread is actively executing do_work()
Waiting: Thread is alive but waiting for work or timeout
Thread States NOT Considered "Running":
Created: Thread object created but not started
Stopping: Thread is in shutdown sequence
Stopped: Thread has completely finished
Returns
true if thread is actively running (Working or Waiting)
Definition at line 396 of file thread_base.cpp.
References thread_module::Waiting, and thread_module::Working.
is_running() [2/3]
auto thread_module::thread_base::is_running () const -> bool
Checks whether the worker thread is currently running.
Returns
true if the thread is running, false otherwise.
This depends on the thread's internal condition state (e.g., thread_conditions::running).
is_running() [3/3]
auto thread_module::thread_base::is_running () const -> bool
Checks whether the worker thread is currently running.
Returns
true if the thread is running, false otherwise.
This depends on the thread's internal condition state (e.g., thread_conditions::running).
operator=() [1/6]
thread_base & thread_module::thread_base::operator= (const thread_base &) delete
operator=() [2/6]
thread_base & thread_module::thread_base::operator= (const thread_base &) delete
operator=() [3/6]
thread_base & thread_module::thread_base::operator= (const thread_base &) delete
operator=() [4/6]
thread_base & thread_module::thread_base::operator= (thread_base &&) delete
operator=() [5/6]
thread_base & thread_module::thread_base::operator= (thread_base &&) delete
operator=() [6/6]
thread_base & thread_module::thread_base::operator= (thread_base &&) delete
set_wake_interval() [1/3]
auto thread_module::thread_base::set_wake_interval (const std::optional< std::chrono::milliseconds > & wake_interval) -> void
Sets the interval at which the worker thread should wake up (if any).
Sets the wake interval for periodic thread wake-ups.
Parameters
wake_interval Duration in milliseconds for periodic wake-ups, or std::nullopt to disable periodic wake-ups.
If a wake interval is set, the worker thread can periodically perform some action (e.g., housekeeping tasks) even if there's no immediate external signal.
Note
This method is thread-safe.
Implementation details:
Uses a dedicated mutex (wake_interval_mutex_) to ensure thread-safe access
The scoped_lock ensures automatic release when the function exits
This interval controls how often the thread wakes up even when idle
Setting std::nullopt disables periodic wake-ups (thread only wakes on signals)
Thread Safety:
Safe to call from any thread while the worker thread is running
The wake_interval_mutex_ protects against data races with get_wake_interval()
Definition at line 96 of file thread_base.cpp.
set_wake_interval() [2/3]
auto thread_module::thread_base::set_wake_interval (const std::optional< std::chrono::milliseconds > & wake_interval) -> void
Sets the interval at which the worker thread should wake up (if any).
Parameters
wake_interval Duration in milliseconds for periodic wake-ups, or std::nullopt to disable periodic wake-ups.
If a wake interval is set, the worker thread can periodically perform some action (e.g., housekeeping tasks) even if there's no immediate external signal.
Note
This method is thread-safe.
set_wake_interval() [3/3]
auto thread_module::thread_base::set_wake_interval (const std::optional< std::chrono::milliseconds > & wake_interval) -> void
Sets the interval at which the worker thread should wake up (if any).
Parameters
wake_interval Duration in milliseconds for periodic wake-ups, or std::nullopt to disable periodic wake-ups.
If a wake interval is set, the worker thread can periodically perform some action (e.g., housekeeping tasks) even if there's no immediate external signal.
Note
This method is thread-safe.
should_continue_work() [1/3]
virtual auto thread_module::thread_base::should_continue_work (void) const -> bool inline protected virtual
Determines whether the thread should continue doing work.
Returns
true if there is work to do, false otherwise.
The default implementation always returns false (indicating no ongoing work). Override this in derived classes if you wish the thread to perform repeated tasks until some condition changes.
Reimplemented in WakeIntervalTestWorker, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, and typed_thread_pool_module::typed_thread_worker_t< priority_job_types >.
Definition at line 253 of file thread_base.h.
Referenced by TEST_F().
should_continue_work() [2/3]
virtual auto thread_module::thread_base::should_continue_work (void) const -> bool inline protected virtual
Determines whether the thread should continue doing work.
Returns
true if there is work to do, false otherwise.
The default implementation always returns false (indicating no ongoing work). Override this in derived classes if you wish the thread to perform repeated tasks until some condition changes.
Reimplemented in WakeIntervalTestWorker, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, and typed_thread_pool_module::typed_thread_worker_t< priority_job_types >.
Definition at line 253 of file thread_base.h.
should_continue_work() [3/3]
virtual auto thread_module::thread_base::should_continue_work (void) const -> bool inline protected virtual
Determines whether the thread should continue doing work.
Returns
true if there is work to do, false otherwise.
The default implementation always returns false (indicating no ongoing work). Override this in derived classes if you wish the thread to perform repeated tasks until some condition changes.
Reimplemented in WakeIntervalTestWorker, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, typed_thread_pool_module::typed_thread_worker_t< priority_job_types >, thread_pool_module::thread_worker, typed_thread_pool_module::typed_thread_worker_t< job_type >, typed_thread_pool_module::typed_thread_worker_t< job_types >, and typed_thread_pool_module::typed_thread_worker_t< priority_job_types >.
Definition at line 253 of file thread_base.h.
start() [1/3]
auto thread_module::thread_base::start (void) -> result_void
Starts the worker thread.
Starts the worker thread and begins execution loop.
Returns
result_void containing an error on failure, or success value if successful.
Internally, this method:
Calls before_start() to allow derived classes to perform setup.
Spawns a new thread (using either std::jthread or std::thread).
Repeatedly calls do_work() until the thread is signaled to stop.
Implementation details:
First checks if thread is already running using different methods:
C++20: stop_source_.has_value() indicates active thread
Legacy: worker_thread_->joinable() indicates active thread
Calls stop() first to ensure clean state (idempotent operation)
Initializes stop control mechanism:
C++20: Creates new std::stop_source for cooperative cancellation
Legacy: Resets atomic stop_requested_ flag to false
Creates worker thread that executes the main work loop
Main Work Loop Logic:
Calls before_start() hook for derived class initialization
Enters main loop while not stopped and has work to do
Sets thread_condition_ to Waiting before sleep
Waits on condition variable with optional timeout (wake_interval)
Sets thread_condition_ to Working before calling do_work()
Calls do_work() hook for actual work execution
Handles exceptions from do_work() gracefully
Calls after_stop() hook for cleanup when exiting
Error Handling:
Returns error if thread is already running
Catches std::bad_alloc during thread creation
Logs errors from hooks using std::cerr
Exception-safe cleanup in catch blocks
Returns
Empty result on success, error on failure
Definition at line 157 of file thread_base.cpp.
References thread_module::resource_allocation_failed, thread_module::Stopping, thread_module::thread_already_running, thread_module::Waiting, and thread_module::Working.
start() [2/3]
auto thread_module::thread_base::start (void) -> result_void
Starts the worker thread.
Returns
result_void containing an error on failure, or success value if successful.
Internally, this method:
Calls before_start() to allow derived classes to perform setup.
Spawns a new thread (using either std::jthread or std::thread).
Repeatedly calls do_work() until the thread is signaled to stop.
start() [3/3]
auto thread_module::thread_base::start (void) -> result_void
Starts the worker thread.
Returns
result_void containing an error on failure, or success value if successful.
Internally, this method:
Calls before_start() to allow derived classes to perform setup.
Spawns a new thread (using either std::jthread or std::thread).
Repeatedly calls do_work() until the thread is signaled to stop.
stop() [1/3]
auto thread_module::thread_base::stop (void) -> result_void
Requests the worker thread to stop and waits for it to finish.
Stops the worker thread and waits for it to complete.
Returns
result_void containing an error on failure, or success value if successful.
Internally, this method:
Signals the thread to stop (via stop_source_ or stop_requested_).
Joins the thread, ensuring it has fully exited.
Calls after_stop() for post-shutdown cleanup in derived classes.
Implementation details:
This method is idempotent - safe to call multiple times
First checks if there's actually a thread to stop
Uses platform-specific stop signaling:
C++20: Uses std::stop_source for cooperative cancellation
Legacy: Sets atomic flag stop_requested_ to true
Notifies condition variable to wake up waiting thread
Joins the thread to wait for complete shutdown
Cleans up all thread-related resources
Shutdown Sequence:
Signal stop request using appropriate mechanism
Notify condition variable to wake sleeping thread
Wait for thread to exit its main loop and complete after_stop()
Clean up thread object and stop control mechanism
Update thread_condition_ to Stopped state
Thread Safety:
Safe to call from any thread including the worker thread itself
Uses proper synchronization to avoid race conditions
join() ensures thread resources are properly released
Returns
Empty result on success, error if thread wasn't running
Definition at line 333 of file thread_base.cpp.
References thread_module::Stopped, and thread_module::thread_not_running.
Referenced by ~thread_base().
stop() [2/3]
auto thread_module::thread_base::stop (void) -> result_void
Requests the worker thread to stop and waits for it to finish.
Returns
result_void containing an error on failure, or success value if successful.
Internally, this method:
Signals the thread to stop (via stop_source_ or stop_requested_).
Joins the thread, ensuring it has fully exited.
Calls after_stop() for post-shutdown cleanup in derived classes.
stop() [3/3]
auto thread_module::thread_base::stop (void) -> result_void
Requests the worker thread to stop and waits for it to finish.
Returns
result_void containing an error on failure, or success value if successful.
Internally, this method:
Signals the thread to stop (via stop_source_ or stop_requested_).
Joins the thread, ensuring it has fully exited.
Calls after_stop() for post-shutdown cleanup in derived classes.
to_string() [1/3]
auto thread_module::thread_base::to_string (void) const -> std::string virtual
Returns a string representation of this thread_base object.
Provides a string representation of the thread's current state.
Returns
A string containing descriptive or diagnostic information about the thread.
Derived classes may override this to include additional details (e.g., current status, counters, or other state).
Implementation details:
Uses the formatter utility to create consistent output format
Includes both thread title and current condition
Useful for logging and debugging purposes
Thread-safe due to atomic load of thread_condition_
Returns
Formatted string showing thread title and current state
Definition at line 415 of file thread_base.cpp.
References utility_module::formatter::format().
Referenced by typed_thread_pool_module::typed_thread_worker_t< job_type >::do_work(), fmt::formatter< thread_pool_module::thread_worker >::format(), and fmt::formatter< typed_thread_pool_module::typed_thread_worker_t< job_type > >::format().
to_string() [2/3]
virtual auto thread_module::thread_base::to_string (void) const -> std::string virtual
Returns a string representation of this thread_base object.
Returns
A string containing descriptive or diagnostic information about the thread.
Derived classes may override this to include additional details (e.g., current status, counters, or other state).
to_string() [3/3]
virtual auto thread_module::thread_base::to_string (void) const -> std::string virtual
Returns a string representation of this thread_base object.
Returns
A string containing descriptive or diagnostic information about the thread.
Derived classes may override this to include additional details (e.g., current status, counters, or other state).
Member Data Documentation
wake_interval_
std::optional< std::chrono::milliseconds > thread_module::thread_base::wake_interval_ protected
Interval at which the thread is optionally awakened.
If set, the worker thread can wake periodically (in addition to any other wake conditions) to perform tasks at regular intervals.
Note
Access to this member must be synchronized using wake_interval_mutex_
Definition at line 292 of file thread_base.h.
Referenced by get_wake_interval().
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/thread_base/core/thread_base.h
libraries/thread_system/modular_structure/core/src/thread_base/core/thread_base.h
libraries/thread_system/sources/thread_base/core/thread_base.h
libraries/thread_system/modular_structure/core/src/thread_base/core/thread_base.cpp
libraries/thread_system/sources/thread_base/core/thread_base.cpp