Messaging System: monitoring_system::opentelemetry_tracer_adapter Class Reference
monitoring_system::opentelemetry_tracer_adapter Class Reference
Adapter for converting monitoring system traces to OpenTelemetry format.
#include <opentelemetry_adapter.h>
Public Member Functions
opentelemetry_tracer_adapter (const otel_resource &resource)
result< otel_span_data > convert_span (const trace_span &span)
Convert internal span to OpenTelemetry span data.
result< std::vector< otel_span_data > > convert_spans (const std::vector< trace_span > &spans)
Convert multiple spans to OpenTelemetry format.
result< otel_span_context > create_context (const trace_context &context)
Create OpenTelemetry context from internal trace context.
Detailed Description
Adapter for converting monitoring system traces to OpenTelemetry format.
Definition at line 186 of file opentelemetry_adapter.h.
Constructor & Destructor Documentation
opentelemetry_tracer_adapter()
monitoring_system::opentelemetry_tracer_adapter::opentelemetry_tracer_adapter (const otel_resource & resource) inline explicit
Definition at line 188 of file opentelemetry_adapter.h.
Member Function Documentation
convert_span()
result< otel_span_data > monitoring_system::opentelemetry_tracer_adapter::convert_span (const trace_span & span) inline
Convert internal span to OpenTelemetry span data.
Definition at line 194 of file opentelemetry_adapter.h.
References monitoring_system::otel_span_data::add_attribute(), monitoring_system::otel_span_data::context, monitoring_system::otel_span_data::end_time, monitoring_system::error, monitoring_system::otel_span_data::kind, monitoring_system::make_success(), monitoring_system::otel_span_data::name, monitoring_system::ok, monitoring_system::otel_span_data::parent_context, monitoring_system::otel_span_data::resource, monitoring_system::otel_span_data::start_time, monitoring_system::otel_span_data::status_code, and monitoring_system::otel_span_data::status_message.
Referenced by convert_spans(), TEST_F(), and TEST_F().
convert_spans()
result< std::vector< otel_span_data > > monitoring_system::opentelemetry_tracer_adapter::convert_spans (const std::vector< trace_span > & spans) inline
Convert multiple spans to OpenTelemetry format.
Definition at line 241 of file opentelemetry_adapter.h.
References convert_span(), and monitoring_system::make_success().
Referenced by monitoring_system::opentelemetry_compatibility_layer::export_spans(), and TEST_F().
create_context()
result< otel_span_context > monitoring_system::opentelemetry_tracer_adapter::create_context (const trace_context & context) inline
Create OpenTelemetry context from internal trace context.
Definition at line 261 of file opentelemetry_adapter.h.
References monitoring_system::make_success(), monitoring_system::trace_context::span_id, and monitoring_system::trace_context::trace_id.
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/exporters/opentelemetry_adapter.h