Messaging System: libraries/monitoring_system/tests/test_thread_context.cpp File Reference
test_thread_context.cpp File Reference
Unit tests for thread context and metadata.
#include <gtest/gtest.h>
#include <kcenon/monitoring/context/thread_context.h>
#include <thread>
#include <vector>
#include <set>
#include <future>
Classes
class ThreadContextTest
Test fixture for thread context tests.
Functions
TEST_F (ThreadContextTest, ContextMetadataBasicOperations)
Test context_metadata basic operations.
TEST_F (ThreadContextTest, DISABLED_ContextMetadataMerge)
Test context_metadata copy and comparison.
TEST_F (ThreadContextTest, ThreadContextBasicOperations)
Test thread_context basic operations.
TEST_F (ThreadContextTest, RequestIdGeneration)
Test automatic request ID generation.
TEST_F (ThreadContextTest, CorrelationIdGeneration)
Test correlation ID generation.
TEST_F (ThreadContextTest, ContextScope)
Test context_scope RAII wrapper.
TEST_F (ThreadContextTest, ContextScopeWithPreservation)
Test context_scope with preservation.
TEST_F (ThreadContextTest, ContextPropagator)
Test context_propagator.
TEST_F (ThreadContextTest, CrossThreadPropagation)
Test context propagation across threads.
TEST_F (ThreadContextTest, ContextAwareEnrichment)
Test context_aware_monitoring enrichment.
TEST_F (ThreadContextTest, ContextMetricsCollector)
Test context_metrics_collector.
TEST_F (ThreadContextTest, ThreadIsolation)
Test thread isolation.
TEST_F (ThreadContextTest, CopyFromContext)
Test copy_from functionality.
Detailed Description
Unit tests for thread context and metadata.
Definition in file test_thread_context.cpp.
Function Documentation
TEST_F() [1/13]
TEST_F (ThreadContextTest , ContextAwareEnrichment)
Test context_aware_monitoring enrichment.
Definition at line 293 of file test_thread_context.cpp.
References monitoring_system::monitoring_data::add_metric(), monitoring_system::thread_context_data::add_tag(), monitoring_system::thread_context_data::correlation_id, monitoring_system::thread_context::create(), monitoring_system::thread_context::current(), monitoring_system::monitoring_data::get_metric(), monitoring_system::monitoring_data::get_tag(), monitoring_system::thread_context_data::user_id, and monitoring_system::metric::value.
TEST_F() [2/13]
TEST_F (ThreadContextTest , ContextMetadataBasicOperations)
Test context_metadata basic operations.
Definition at line 41 of file test_thread_context.cpp.
References monitoring_system::context_metadata::correlation_id, monitoring_system::context_metadata::empty(), monitoring_system::context_metadata::get_tag(), monitoring_system::context_metadata::request_id, monitoring_system::context_metadata::set_tag(), monitoring_system::context_metadata::tags, and monitoring_system::context_metadata::user_id.
TEST_F() [3/13]
TEST_F (ThreadContextTest , ContextMetricsCollector)
Test context_metrics_collector.
Definition at line 348 of file test_thread_context.cpp.
References monitoring_system::thread_context::create(), monitoring_system::thread_context::current(), monitoring_system::make_success(), monitoring_system::thread_context_data::user_id, and monitoring_system::metric::value.
TEST_F() [4/13]
TEST_F (ThreadContextTest , ContextPropagator)
Test context_propagator.
Definition at line 219 of file test_thread_context.cpp.
References monitoring_system::thread_context_data::add_tag(), monitoring_system::thread_context::clear(), monitoring_system::thread_context::create(), monitoring_system::thread_context::current(), monitoring_system::thread_context_data::get_tag(), monitoring_system::thread_context::has_context(), and monitoring_system::thread_context_data::user_id.
TEST_F() [5/13]
TEST_F (ThreadContextTest , ContextScope)
Test context_scope RAII wrapper.
Definition at line 172 of file test_thread_context.cpp.
References monitoring_system::thread_context::current(), monitoring_system::thread_context::has_context(), and monitoring_system::thread_context_data::user_id.
TEST_F() [6/13]
TEST_F (ThreadContextTest , ContextScopeWithPreservation)
Test context_scope with preservation.
Definition at line 194 of file test_thread_context.cpp.
References monitoring_system::thread_context::create(), monitoring_system::thread_context::current(), monitoring_system::thread_context::has_context(), and monitoring_system::thread_context_data::user_id.
TEST_F() [7/13]
TEST_F (ThreadContextTest , CopyFromContext)
Test copy_from functionality.
Definition at line 446 of file test_thread_context.cpp.
References monitoring_system::thread_context::copy_from(), monitoring_system::context_metadata::correlation_id, monitoring_system::thread_context::current(), monitoring_system::thread_context::has_context(), and monitoring_system::context_metadata::user_id.
TEST_F() [8/13]
TEST_F (ThreadContextTest , CorrelationIdGeneration)
Test correlation ID generation.
Definition at line 156 of file test_thread_context.cpp.
References monitoring_system::thread_context::generate_correlation_id().
TEST_F() [9/13]
TEST_F (ThreadContextTest , CrossThreadPropagation)
Test context propagation across threads.
Definition at line 251 of file test_thread_context.cpp.
References monitoring_system::thread_context_data::add_tag(), monitoring_system::thread_context_data::correlation_id, monitoring_system::thread_context::create(), monitoring_system::thread_context::current(), monitoring_system::thread_context_data::get_tag(), and monitoring_system::thread_context::has_context().
TEST_F() [10/13]
TEST_F (ThreadContextTest , DISABLED_ContextMetadataMerge)
Test context_metadata copy and comparison.
Definition at line 79 of file test_thread_context.cpp.
References monitoring_system::context_metadata::correlation_id, monitoring_system::context_metadata::get_tag(), monitoring_system::context_metadata::request_id, monitoring_system::context_metadata::set_tag(), and monitoring_system::context_metadata::user_id.
TEST_F() [11/13]
TEST_F (ThreadContextTest , RequestIdGeneration)
Test automatic request ID generation.
Definition at line 134 of file test_thread_context.cpp.
References monitoring_system::thread_context::create(), and monitoring_system::thread_context::generate_request_id().
TEST_F() [12/13]
TEST_F (ThreadContextTest , ThreadContextBasicOperations)
Test thread_context basic operations.
Definition at line 102 of file test_thread_context.cpp.
References monitoring_system::thread_context::clear(), monitoring_system::thread_context::create(), monitoring_system::thread_context::current(), monitoring_system::thread_context_data::get_tag(), and monitoring_system::thread_context::has_context().
TEST_F() [13/13]
TEST_F (ThreadContextTest , ThreadIsolation)
Test thread isolation.
Definition at line 394 of file test_thread_context.cpp.
References monitoring_system::thread_context::create(), monitoring_system::thread_context::current(), and monitoring_system::thread_context_data::user_id.