Messaging System: monitoring_module::multi_process_monitoring Class Reference
monitoring_module::multi_process_monitoring Class Reference
다중 프로세스 모니터링 구현 클래스
#include <multi_process_monitoring.h>
Classes
class multi_process_impl
다중 프로세스 모니터링 구현 세부사항
Public Member Functions
multi_process_monitoring (std::size_t history_size=1000, std::uint32_t collection_interval_ms=1000, std::size_t max_processes=100, std::size_t max_pools_per_process=50)
생성자
~multi_process_monitoring () override
void update_system_metrics (const ::monitoring_interface::system_metrics &metrics) override
void update_thread_pool_metrics (const ::monitoring_interface::thread_pool_metrics &metrics) override
void update_worker_metrics (std::size_t worker_id, const ::monitoring_interface::worker_metrics &metrics) override
::monitoring_interface::metrics_snapshot get_current_snapshot () const override
Retrieves the most recent metrics snapshot.
std::vector<::monitoring_interface::metrics_snapshot > get_recent_snapshots (std::size_t count) const override
Retrieves multiple recent metrics snapshots.
bool is_active () const override
Checks if monitoring is currently active.
void start () override
void stop () override
double get_average_cpu_usage (std::chrono::steady_clock::duration duration) const override
std::uint64_t get_peak_memory_usage (std::chrono::steady_clock::duration duration) const override
double get_average_job_latency (std::chrono::steady_clock::duration duration) const override
std::unordered_map< std::string, double > get_statistics () const override
void register_process (const ::monitoring_interface::process_identifier &process_id) override
void unregister_process (const ::monitoring_interface::process_identifier &process_id) override
void register_thread_pool (const ::monitoring_interface::thread_pool_identifier &pool_id) override
void unregister_thread_pool (const ::monitoring_interface::thread_pool_identifier &pool_id) override
void update_process_system_metrics (const ::monitoring_interface::process_identifier &process_id, const ::monitoring_interface::system_metrics &metrics) override
void update_thread_pool_metrics (const ::monitoring_interface::thread_pool_identifier &pool_id, const ::monitoring_interface::process_thread_pool_metrics &metrics) override
void update_process_worker_metrics (const ::monitoring_interface::process_identifier &process_id, std::size_t worker_id, const ::monitoring_interface::worker_metrics &metrics) override
::monitoring_interface::multi_process_metrics_snapshot get_multi_process_snapshot () const override
다중 프로세스 스냅샷 조회
::monitoring_interface::metrics_snapshot get_process_snapshot (const ::monitoring_interface::process_identifier &process_id) const override
::monitoring_interface::process_thread_pool_metrics get_thread_pool_metrics (const ::monitoring_interface::thread_pool_identifier &pool_id) const override
std::vector<::monitoring_interface::process_identifier > get_registered_processes () const override
등록된 모든 프로세스 조회
std::vector<::monitoring_interface::thread_pool_identifier > get_process_thread_pools (const ::monitoring_interface::process_identifier &process_id) const override
std::unordered_map< std::string, double > compare_process_performance (const std::vector<::monitoring_interface::process_identifier > &process_ids) const override
void set_process_monitoring_enabled (const ::monitoring_interface::process_identifier &process_id, bool enabled)
void set_thread_pool_monitoring_enabled (const ::monitoring_interface::thread_pool_identifier &pool_id, bool enabled)
void set_process_alert_thresholds (const ::monitoring_interface::process_identifier &process_id, double cpu_threshold, std::uint64_t memory_threshold, std::uint64_t latency_threshold_ns)
프로세스별 알림 임계값 설정
void set_thread_pool_alert_thresholds (const ::monitoring_interface::thread_pool_identifier &pool_id, std::uint64_t queue_size_threshold, std::uint64_t latency_threshold_ns, double worker_utilization_threshold)
Thread pool별 알림 임계값 설정
void set_default_process (const ::monitoring_interface::process_identifier &process_id)
현재 프로세스를 기본 프로세스로 설정
void set_default_thread_pool (const ::monitoring_interface::thread_pool_identifier &pool_id)
기본 thread pool 설정
virtual void update_thread_pool_metrics (const thread_pool_identifier &pool_id, const process_thread_pool_metrics &metrics)=0
Thread pool별 메트릭 업데이트
virtual void update_thread_pool_metrics (const thread_pool_metrics &metrics)=0
Updates thread pool metrics.
virtual void update_thread_pool_metrics (const thread_pool_metrics &metrics)=0
Updates thread pool metrics.
virtual void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const thread_pool_metrics &metrics)
Updates thread pool metrics with pool identifier (for multi-pool scenarios).
virtual void update_thread_pool_metrics (const thread_pool_metrics &metrics)=0
Updates thread pool metrics.
virtual void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const thread_pool_metrics &metrics)
Updates thread pool metrics with pool identifier (for multi-pool scenarios).
Public Member Functions inherited from monitoring_interface::multi_process_monitoring_interface
virtual ~multi_process_monitoring_interface ()=default
virtual void register_process (const process_identifier &process_id)=0
프로세스 등록
virtual void unregister_process (const process_identifier &process_id)=0
프로세스 등록 해제
virtual void register_thread_pool (const thread_pool_identifier &pool_id)=0
Thread pool 등록
virtual void unregister_thread_pool (const thread_pool_identifier &pool_id)=0
Thread pool 등록 해제
virtual void update_process_system_metrics (const process_identifier &process_id, const system_metrics &metrics)=0
프로세스별 시스템 메트릭 업데이트
virtual void update_process_worker_metrics (const process_identifier &process_id, std::size_t worker_id, const worker_metrics &metrics)=0
프로세스별 worker 메트릭 업데이트
virtual metrics_snapshot get_process_snapshot (const process_identifier &process_id) const =0
특정 프로세스 메트릭 조회
virtual process_thread_pool_metrics get_thread_pool_metrics (const thread_pool_identifier &pool_id) const =0
특정 thread pool 메트릭 조회
virtual std::vector< thread_pool_identifier > get_process_thread_pools (const process_identifier &process_id) const =0
프로세스별 thread pool 목록 조회
virtual std::unordered_map< std::string, double > compare_process_performance (const std::vector< process_identifier > &process_ids) const =0
프로세스간 성능 비교 분석
virtual void update_thread_pool_metrics (const thread_pool_metrics &metrics)=0
Updates thread pool metrics.
virtual void update_thread_pool_metrics (const thread_pool_metrics &metrics)=0
Updates thread pool metrics.
virtual void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const thread_pool_metrics &metrics)
Updates thread pool metrics with pool identifier (for multi-pool scenarios).
virtual void update_thread_pool_metrics (const thread_pool_metrics &metrics)=0
Updates thread pool metrics.
virtual void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const thread_pool_metrics &metrics)
Updates thread pool metrics with pool identifier (for multi-pool scenarios).
Public Member Functions inherited from monitoring_interface::monitoring_interface
virtual ~monitoring_interface ()=default
virtual void update_system_metrics (const system_metrics &metrics)=0
Updates system metrics.
virtual void update_worker_metrics (std::size_t worker_id, const worker_metrics &metrics)=0
Updates worker thread metrics.
virtual ~monitoring_interface ()=default
virtual void update_system_metrics (const system_metrics &metrics)=0
Updates system metrics.
virtual void update_worker_metrics (std::size_t worker_id, const worker_metrics &metrics)=0
Updates worker thread metrics.
virtual ~monitoring_interface ()=default
virtual void update_system_metrics (const system_metrics &metrics)=0
Updates system metrics.
virtual void update_worker_metrics (std::size_t worker_id, const worker_metrics &metrics)=0
Updates worker thread metrics.
Detailed Description
다중 프로세스 모니터링 구현 클래스
프로세스별, thread pool별 독립적인 모니터링을 지원하며 기존 인터페이스와의 하위 호환성을 유지
Definition at line 23 of file multi_process_monitoring.h.
Constructor & Destructor Documentation
multi_process_monitoring()
monitoring_module::multi_process_monitoring::multi_process_monitoring (std::size_t history_size = 1000, std::uint32_t collection_interval_ms = 1000, std::size_t max_processes = 100, std::size_t max_pools_per_process = 50) explicit
생성자
Parameters
history_size 히스토리 크기
collection_interval_ms 수집 간격 (밀리초)
max_processes 최대 프로세스 수
max_pools_per_process 프로세스당 최대 thread pool 수
Definition at line 482 of file multi_process_monitoring.cpp.
~multi_process_monitoring()
monitoring_module::multi_process_monitoring::~multi_process_monitoring () override default
Member Function Documentation
compare_process_performance()
std::unordered_map< std::string, double > monitoring_module::multi_process_monitoring::compare_process_performance (const std::vector<::monitoring_interface::process_identifier > & process_ids) const override
Definition at line 623 of file multi_process_monitoring.cpp.
get_average_cpu_usage()
double monitoring_module::multi_process_monitoring::get_average_cpu_usage (std::chrono::steady_clock::duration duration) const override virtual
Implements monitoring_interface::multi_process_monitoring_interface.
Definition at line 530 of file multi_process_monitoring.cpp.
References monitoring_interface::system_metrics::cpu_usage_percent, get_current_snapshot(), and monitoring_interface::metrics_snapshot::system.
get_average_job_latency()
double monitoring_module::multi_process_monitoring::get_average_job_latency (std::chrono::steady_clock::duration duration) const override virtual
Implements monitoring_interface::multi_process_monitoring_interface.
Definition at line 540 of file multi_process_monitoring.cpp.
References monitoring_interface::thread_pool_metrics::average_latency_ns, get_current_snapshot(), monitoring_interface::thread_pool_metrics::jobs_completed, and monitoring_interface::metrics_snapshot::thread_pool.
get_current_snapshot()
metrics_snapshot monitoring_module::multi_process_monitoring::get_current_snapshot () const override virtual
Retrieves the most recent metrics snapshot.
Returns
Current metrics snapshot
Implements monitoring_interface::monitoring_interface.
Definition at line 507 of file multi_process_monitoring.cpp.
Referenced by get_average_cpu_usage(), get_average_job_latency(), get_peak_memory_usage(), get_recent_snapshots(), and get_statistics().
get_multi_process_snapshot()
multi_process_metrics_snapshot monitoring_module::multi_process_monitoring::get_multi_process_snapshot () const override virtual
다중 프로세스 스냅샷 조회
Returns
현재 다중 프로세스 메트릭 스냅샷
Implements monitoring_interface::multi_process_monitoring_interface.
Definition at line 595 of file multi_process_monitoring.cpp.
get_peak_memory_usage()
std::uint64_t monitoring_module::multi_process_monitoring::get_peak_memory_usage (std::chrono::steady_clock::duration duration) const override virtual
Implements monitoring_interface::multi_process_monitoring_interface.
Definition at line 535 of file multi_process_monitoring.cpp.
References get_current_snapshot(), monitoring_interface::system_metrics::memory_usage_bytes, and monitoring_interface::metrics_snapshot::system.
get_process_snapshot()
metrics_snapshot monitoring_module::multi_process_monitoring::get_process_snapshot (const ::monitoring_interface::process_identifier & process_id) const override
Definition at line 599 of file multi_process_monitoring.cpp.
get_process_thread_pools()
std::vector< thread_pool_identifier > monitoring_module::multi_process_monitoring::get_process_thread_pools (const ::monitoring_interface::process_identifier & process_id) const override
Definition at line 618 of file multi_process_monitoring.cpp.
get_recent_snapshots()
std::vector< metrics_snapshot > monitoring_module::multi_process_monitoring::get_recent_snapshots (std::size_t count) const override virtual
Retrieves multiple recent metrics snapshots.
Parameters
count Number of snapshots to retrieve
Returns
Vector of metrics snapshots, newest first
Implements monitoring_interface::monitoring_interface.
Definition at line 511 of file multi_process_monitoring.cpp.
References get_current_snapshot().
get_registered_processes()
std::vector< process_identifier > monitoring_module::multi_process_monitoring::get_registered_processes () const override virtual
등록된 모든 프로세스 조회
Returns
프로세스 식별자 벡터
Implements monitoring_interface::multi_process_monitoring_interface.
Definition at line 614 of file multi_process_monitoring.cpp.
get_statistics()
std::unordered_map< std::string, double > monitoring_module::multi_process_monitoring::get_statistics () const override virtual
Implements monitoring_interface::multi_process_monitoring_interface.
Definition at line 548 of file multi_process_monitoring.cpp.
References monitoring_interface::system_metrics::active_threads, monitoring_interface::thread_pool_metrics::average_latency_ns, monitoring_interface::system_metrics::cpu_usage_percent, get_current_snapshot(), monitoring_interface::thread_pool_metrics::jobs_completed, monitoring_interface::thread_pool_metrics::jobs_pending, monitoring_interface::system_metrics::memory_usage_bytes, monitoring_interface::metrics_snapshot::system, and monitoring_interface::metrics_snapshot::thread_pool.
get_thread_pool_metrics()
process_thread_pool_metrics monitoring_module::multi_process_monitoring::get_thread_pool_metrics (const ::monitoring_interface::thread_pool_identifier & pool_id) const override
Definition at line 603 of file multi_process_monitoring.cpp.
is_active()
bool monitoring_module::multi_process_monitoring::is_active () const override virtual
Checks if monitoring is currently active.
Returns
true if monitoring is active
Implements monitoring_interface::monitoring_interface.
Definition at line 518 of file multi_process_monitoring.cpp.
register_process()
void monitoring_module::multi_process_monitoring::register_process (const ::monitoring_interface::process_identifier & process_id) override
Definition at line 563 of file multi_process_monitoring.cpp.
register_thread_pool()
void monitoring_module::multi_process_monitoring::register_thread_pool (const ::monitoring_interface::thread_pool_identifier & pool_id) override
Definition at line 571 of file multi_process_monitoring.cpp.
set_default_process()
void monitoring_module::multi_process_monitoring::set_default_process (const ::monitoring_interface::process_identifier & process_id)
현재 프로세스를 기본 프로세스로 설정
Parameters
process_id 기본 프로세스 식별자
Definition at line 650 of file multi_process_monitoring.cpp.
set_default_thread_pool()
void monitoring_module::multi_process_monitoring::set_default_thread_pool (const ::monitoring_interface::thread_pool_identifier & pool_id)
기본 thread pool 설정
Parameters
pool_id 기본 thread pool 식별자
Definition at line 654 of file multi_process_monitoring.cpp.
set_process_alert_thresholds()
void monitoring_module::multi_process_monitoring::set_process_alert_thresholds (const ::monitoring_interface::process_identifier & process_id, double cpu_threshold, std::uint64_t memory_threshold, std::uint64_t latency_threshold_ns)
프로세스별 알림 임계값 설정
Definition at line 636 of file multi_process_monitoring.cpp.
set_process_monitoring_enabled()
void monitoring_module::multi_process_monitoring::set_process_monitoring_enabled (const ::monitoring_interface::process_identifier & process_id, bool enabled)
Definition at line 628 of file multi_process_monitoring.cpp.
set_thread_pool_alert_thresholds()
void monitoring_module::multi_process_monitoring::set_thread_pool_alert_thresholds (const ::monitoring_interface::thread_pool_identifier & pool_id, std::uint64_t queue_size_threshold, std::uint64_t latency_threshold_ns, double worker_utilization_threshold)
Thread pool별 알림 임계값 설정
Definition at line 643 of file multi_process_monitoring.cpp.
set_thread_pool_monitoring_enabled()
void monitoring_module::multi_process_monitoring::set_thread_pool_monitoring_enabled (const ::monitoring_interface::thread_pool_identifier & pool_id, bool enabled)
Definition at line 632 of file multi_process_monitoring.cpp.
start()
void monitoring_module::multi_process_monitoring::start () override virtual
Implements monitoring_interface::multi_process_monitoring_interface.
Definition at line 522 of file multi_process_monitoring.cpp.
stop()
void monitoring_module::multi_process_monitoring::stop () override virtual
Implements monitoring_interface::multi_process_monitoring_interface.
Definition at line 526 of file multi_process_monitoring.cpp.
unregister_process()
void monitoring_module::multi_process_monitoring::unregister_process (const ::monitoring_interface::process_identifier & process_id) override
Definition at line 567 of file multi_process_monitoring.cpp.
unregister_thread_pool()
void monitoring_module::multi_process_monitoring::unregister_thread_pool (const ::monitoring_interface::thread_pool_identifier & pool_id) override
Definition at line 575 of file multi_process_monitoring.cpp.
update_process_system_metrics()
void monitoring_module::multi_process_monitoring::update_process_system_metrics (const ::monitoring_interface::process_identifier & process_id, const ::monitoring_interface::system_metrics & metrics) override
Definition at line 579 of file multi_process_monitoring.cpp.
update_process_worker_metrics()
void monitoring_module::multi_process_monitoring::update_process_worker_metrics (const ::monitoring_interface::process_identifier & process_id, std::size_t worker_id, const ::monitoring_interface::worker_metrics & metrics) override
Definition at line 589 of file multi_process_monitoring.cpp.
update_system_metrics()
void monitoring_module::multi_process_monitoring::update_system_metrics (const ::monitoring_interface::system_metrics & metrics) override
Definition at line 495 of file multi_process_monitoring.cpp.
update_thread_pool_metrics() [1/8]
void monitoring_module::multi_process_monitoring::update_thread_pool_metrics (const ::monitoring_interface::thread_pool_identifier & pool_id, const ::monitoring_interface::process_thread_pool_metrics & metrics) override
update_thread_pool_metrics() [2/8]
void monitoring_module::multi_process_monitoring::update_thread_pool_metrics (const ::monitoring_interface::thread_pool_metrics & metrics) override
update_thread_pool_metrics() [3/8]
virtual void monitoring_interface::monitoring_interface::update_thread_pool_metrics (const std::string & pool_name, std::uint32_t pool_instance_id, const thread_pool_metrics & metrics) inline virtual
Updates thread pool metrics with pool identifier (for multi-pool scenarios).
Parameters
pool_name Name of the thread pool
pool_instance_id Instance ID for multiple pools with same name
metrics The thread pool metrics to record
Reimplemented from monitoring_interface::monitoring_interface.
Definition at line 69 of file monitoring_interface.h.
update_thread_pool_metrics() [4/8]
virtual void monitoring_interface::monitoring_interface::update_thread_pool_metrics (const std::string & pool_name, std::uint32_t pool_instance_id, const thread_pool_metrics & metrics) inline virtual
Updates thread pool metrics with pool identifier (for multi-pool scenarios).
Parameters
pool_name Name of the thread pool
pool_instance_id Instance ID for multiple pools with same name
metrics The thread pool metrics to record
Reimplemented from monitoring_interface::monitoring_interface.
Definition at line 69 of file monitoring_interface.h.
update_thread_pool_metrics() [5/8]
virtual void monitoring_interface::multi_process_monitoring_interface::update_thread_pool_metrics (const thread_pool_identifier & pool_id, const process_thread_pool_metrics & metrics) virtual
Thread pool별 메트릭 업데이트
Parameters
pool_id Thread pool 식별자
metrics Thread pool 메트릭
Implements monitoring_interface::multi_process_monitoring_interface.
update_thread_pool_metrics() [6/8]
virtual void monitoring_interface::monitoring_interface::update_thread_pool_metrics (const thread_pool_metrics & metrics) virtual
Updates thread pool metrics.
Parameters
metrics The thread pool metrics to record
Implements monitoring_interface::monitoring_interface.
update_thread_pool_metrics() [7/8]
virtual void monitoring_interface::monitoring_interface::update_thread_pool_metrics (const thread_pool_metrics & metrics) virtual
Updates thread pool metrics.
Parameters
metrics The thread pool metrics to record
Implements monitoring_interface::monitoring_interface.
References monitoring_interface::thread_pool_metrics::average_latency_ns, monitoring_interface::thread_pool_metrics::idle_threads, monitoring_interface::thread_pool_metrics::jobs_completed, monitoring_interface::thread_pool_metrics::jobs_pending, monitoring_interface::thread_pool_metrics::timestamp, monitoring_interface::thread_pool_metrics::total_execution_time_ns, and monitoring_interface::thread_pool_metrics::worker_threads.
update_thread_pool_metrics() [8/8]
virtual void monitoring_interface::monitoring_interface::update_thread_pool_metrics (const thread_pool_metrics & metrics) virtual
Updates thread pool metrics.
Parameters
metrics The thread pool metrics to record
Implements monitoring_interface::monitoring_interface.
References monitoring_interface::thread_pool_metrics::average_latency_ns, monitoring_interface::thread_pool_metrics::idle_threads, monitoring_interface::thread_pool_metrics::jobs_completed, monitoring_interface::thread_pool_metrics::jobs_pending, monitoring_interface::thread_pool_metrics::pool_instance_id, monitoring_interface::thread_pool_metrics::pool_name, monitoring_interface::thread_pool_metrics::timestamp, monitoring_interface::thread_pool_metrics::total_execution_time_ns, and monitoring_interface::thread_pool_metrics::worker_threads.
update_worker_metrics()
void monitoring_module::multi_process_monitoring::update_worker_metrics (std::size_t worker_id, const ::monitoring_interface::worker_metrics & metrics) override
Definition at line 503 of file multi_process_monitoring.cpp.
The documentation for this class was generated from the following files:
libraries/monitoring_system/sources/monitoring/multi_process_monitoring.h
libraries/monitoring_system/sources/monitoring/multi_process_monitoring.cpp