Messaging System: container_module::container_value Class Reference
container_module::container_value Class Reference
A specialized value that can hold child values, i.e.
#include <container_value.h>
Public Member Functions
container_value ()
container_value (const std::string &name, long reserved_count)
container_value (const std::string &name, const std::vector< std::shared_ptr< value > > &units={})
~container_value () override
std::shared_ptr< value > add (const value &item, bool update_count=true) override
Override the base add(...) and remove(...) methods.
std::shared_ptr< value > add (std::shared_ptr< value > item, bool update_count=true) override
void add (const std::vector< value > &target_values, bool update_count=true) override
void add (const std::vector< std::shared_ptr< value > > &target_values, bool update_count=true) override
void remove (std::string_view target_name, bool update_count=true) override
void remove (std::shared_ptr< value > item, bool update_count=true) override
void remove_all () override
long to_long () const override
std::string to_string (const bool &original=true) const override
Public Member Functions inherited from container_module::value
value ()
value (std::shared_ptr< value > object)
value (const std::string &name, std::vector< std::shared_ptr< value > > units={})
value (const std::string &name, const value_types &type, const std::string &data)
value (const std::string &name, const unsigned char *data, const size_t &size, const value_types &type=value_types::null_value)
value (value &&other) noexcept
value & operator= (value &&other) noexcept
virtual ~value ()
std::shared_ptr< value > get_ptr ()
void set_parent (std::shared_ptr< value > parent)
void set_data (const unsigned char *data, const size_t &size, const value_types &type)
Set raw data with a known type.
void set_data (const std::string &name, const value_types &type, const std::string &data)
Set this value from a string form, specifying a type.
std::string name () const
value_types type () const
std::string data () const
size_t size () const
std::shared_ptr< value > parent ()
size_t child_count () const
std::vector< std::shared_ptr< value > > children (const bool &only_container=false)
std::vector< std::shared_ptr< value > > value_array (std::string_view key)
const std::vector< uint8_t > to_bytes () const
bool is_null () const
bool is_bytes () const
bool is_boolean () const
bool is_numeric () const
bool is_string () const
bool is_container () const
const std::string to_xml ()
const std::string to_json ()
const std::string serialize ()
template<typename T >
T safe_convert (const char *type_name, T default_value) const
Template method for safe type conversion with null checking.
virtual bool to_boolean () const
Virtual numeric/string conversion methods.
virtual short to_short () const
virtual unsigned short to_ushort () const
virtual int to_int () const
virtual unsigned int to_uint () const
virtual unsigned long to_ulong () const
virtual long long to_llong () const
virtual unsigned long long to_ullong () const
virtual float to_float () const
virtual double to_double () const
std::shared_ptr< value > operator[] (std::string_view key)
An index operator to get the first matching child by name (if any).
Additional Inherited Members
Protected Member Functions inherited from container_module::value
template<typename T >
void set_data (T data)
std::string convert_specific_string (const std::vector< uint8_t > &data) const
std::vector< uint8_t > convert_specific_string (std::string data) const
void set_byte_string (const std::string &data)
void set_string (const std::string &data)
void set_boolean (const std::string &data)
void set_short (const std::string &data)
void set_ushort (const std::string &data)
void set_int (const std::string &data)
void set_uint (const std::string &data)
void set_long (const std::string &data)
void set_ulong (const std::string &data)
void set_llong (const std::string &data)
void set_ullong (const std::string &data)
void set_float (const std::string &data)
void set_double (const std::string &data)
Protected Attributes inherited from container_module::value
size_t size_
value_types type_
std::string name_
std::vector< uint8_t > data_
std::weak_ptr< value > parent_
std::vector< std::shared_ptr< value > > units_
std::map< value_types, std::function< void(const std::string &)> > data_type_map_
Detailed Description
A specialized value that can hold child values, i.e.
a hierarchical container.
Definition at line 46 of file container_value.h.
Constructor & Destructor Documentation
container_value() [1/3]
container_module::container_value::container_value ()
Definition at line 47 of file container_value.cpp.
References container_module::bool_value, container_module::bytes_value, container_module::container_value, container_module::double_value, container_module::float_value, container_module::int_value, container_module::llong_value, container_module::long_value, container_module::value::set_data(), container_module::short_value, container_module::string_value, container_module::value::type_, container_module::uint_value, container_module::ullong_value, container_module::ulong_value, and container_module::ushort_value.
container_value() [2/3]
container_module::container_value::container_value (const std::string & name, long reserved_count)
Definition at line 113 of file container_value.cpp.
References container_module::container_value, container_module::value::name(), container_module::value::name_, and container_module::value::set_data().
container_value() [3/3]
container_module::container_value::container_value (const std::string & name, const std::vector< std::shared_ptr< value > > & units = {})
Definition at line 122 of file container_value.cpp.
References container_module::container_value, container_module::value::name(), container_module::value::name_, container_module::value::set_data(), and container_module::value::units_.
~container_value()
container_module::container_value::~container_value () override
Definition at line 142 of file container_value.cpp.
References container_module::value::units_.
Member Function Documentation
add() [1/4]
void container_module::container_value::add (const std::vector< std::shared_ptr< value > > & target_values, bool update_count = true) override virtual
Reimplemented from container_module::value.
Definition at line 206 of file container_value.cpp.
References add(), container_module::container_value, container_module::value::set_data(), and container_module::value::units_.
add() [2/4]
void container_module::container_value::add (const std::vector< value > & target_values, bool update_count = true) override virtual
Reimplemented from container_module::value.
Definition at line 191 of file container_value.cpp.
References add(), container_module::container_value, container_module::value::set_data(), and container_module::value::units_.
add() [3/4]
std::shared_ptr< value > container_module::container_value::add (const value & item, bool update_count = true) override virtual
Override the base add(...) and remove(...) methods.
Reimplemented from container_module::value.
Definition at line 144 of file container_value.cpp.
References add(), container_module::bool_value, container_module::value::name(), container_module::short_value, container_module::value::to_boolean(), container_module::value::to_short(), and container_module::value::type().
Referenced by add(), add(), and add().
add() [4/4]
std::shared_ptr< value > container_module::container_value::add (std::shared_ptr< value > item, bool update_count = true) override virtual
Reimplemented from container_module::value.
Definition at line 171 of file container_value.cpp.
References container_module::container_value, container_module::value::set_data(), and container_module::value::units_.
remove() [1/2]
void container_module::container_value::remove (std::shared_ptr< value > item, bool update_count = true) override virtual
Reimplemented from container_module::value.
Definition at line 246 of file container_value.cpp.
References container_module::container_value, container_module::value::set_data(), and container_module::value::units_.
remove() [2/2]
void container_module::container_value::remove (std::string_view target_name, bool update_count = true) override virtual
Reimplemented from container_module::value.
Definition at line 222 of file container_value.cpp.
References container_module::container_value, container_module::value::set_data(), and container_module::value::units_.
remove_all()
void container_module::container_value::remove_all () override virtual
Reimplemented from container_module::value.
Definition at line 261 of file container_value.cpp.
References container_module::container_value, container_module::value::set_data(), and container_module::value::units_.
to_long()
long container_module::container_value::to_long (void) const override virtual
Reimplemented from container_module::value.
Definition at line 269 of file container_value.cpp.
References container_module::value::data_.
Referenced by to_string().
to_string()
std::string container_module::container_value::to_string (const bool & original = true) const override virtual
Reimplemented from container_module::value.
Definition at line 279 of file container_value.cpp.
References kcenon::thread::utils::formatter::format(), and to_long().
The documentation for this class was generated from the following files:
libraries/container_system/values/container_value.h
libraries/container_system/values/container_value.cpp