Messaging System: monitoring_system::result_void Class Reference
monitoring_system::result_void Class Reference
Specialization for operations with no return value.
#include <result_types.h>
Public Member Functions
result_void ()=default
result_void (error_info &&error)
result_void (const error_info &error)
result_void (monitoring_error_code code, const std::string &message="", const std::source_location &loc=std::source_location::current())
bool is_success () const
operator bool () const
const error_info & get_error () const
bool is_error (monitoring_error_code code) const
Static Public Member Functions
static result_void success ()
static result_void error (monitoring_error_code code, const std::string &message="")
Detailed Description
Specialization for operations with no return value.
Definition at line 179 of file result_types.h.
Constructor & Destructor Documentation
result_void() [1/4]
monitoring_system::result_void::result_void () default
Referenced by error(), and success().
result_void() [2/4]
monitoring_system::result_void::result_void (error_info && error) inline
Definition at line 186 of file result_types.h.
result_void() [3/4]
monitoring_system::result_void::result_void (const error_info & error) inline
Definition at line 187 of file result_types.h.
result_void() [4/4]
monitoring_system::result_void::result_void (monitoring_error_code code, const std::string & message = "", const std::source_location & loc = std::source_location::current()) inline
Definition at line 190 of file result_types.h.
Member Function Documentation
error()
static result_void monitoring_system::result_void::error (monitoring_error_code code, const std::string & message = "") inline static
Definition at line 201 of file result_types.h.
References result_void().
get_error()
const error_info & monitoring_system::result_void::get_error () const inline
Definition at line 217 of file result_types.h.
is_error()
bool monitoring_system::result_void::is_error (monitoring_error_code code) const inline
Definition at line 222 of file result_types.h.
is_success()
bool monitoring_system::result_void::is_success () const inline
Definition at line 207 of file result_types.h.
Referenced by operator bool().
operator bool()
monitoring_system::result_void::operator bool () const inline
Definition at line 212 of file result_types.h.
References is_success().
success()
static result_void monitoring_system::result_void::success () inline static
Definition at line 196 of file result_types.h.
References result_void().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/core/result_types.h