Messaging System: libraries/monitoring_system/samples/thread_pool_analysis_example.cpp File Reference
thread_pool_analysis_example.cpp File Reference
#include <monitoring/multi_process_monitoring.h>
#include <monitoring/thread_pool_analyzer.h>
#include <thread>
#include <iostream>
#include <iomanip>
#include <chrono>
#include <random>
#include <unistd.h>
Classes
class workload_generator
class analysis_visualizer
Namespaces
namespace colors
Functions
int main ()
Variables
const char * colors::reset = "\033[0m"
const char * colors::red = "\033[31m"
const char * colors::green = "\033[32m"
const char * colors::yellow = "\033[33m"
const char * colors::blue = "\033[34m"
const char * colors::magenta = "\033[35m"
const char * colors::cyan = "\033[36m"
const char * colors::bold = "\033[1m"
Function Documentation
main()
int main ()
Definition at line 211 of file thread_pool_analysis_example.cpp.
References monitoring_module::thread_pool_analyzer::analyze_pool(), workload_generator::balanced, colors::bold, workload_generator::bursty, monitoring_module::thread_pool_analyzer::calculate_health_score(), monitoring_module::thread_pool_analyzer::classify_pool_type(), monitoring_module::thread_pool_analyzer::compare_pools(), workload_generator::cpu_intensive, monitoring_module::thread_pool_analyzer::detect_bottleneck(), workload_generator::generate_metrics(), colors::green, workload_generator::io_bound, monitoring_interface::process_identifier::pid, analysis_visualizer::print_bottleneck(), analysis_visualizer::print_comparison(), analysis_visualizer::print_header(), analysis_visualizer::print_health_score(), analysis_visualizer::print_pool_summary(), analysis_visualizer::print_pool_type(), analysis_visualizer::print_suggestions(), colors::reset, and monitoring_module::thread_pool_analyzer::suggest_optimizations().