Messaging System: kcenon::thread::configuration_manager Class Reference
kcenon::thread::configuration_manager Class Reference
Configuration manager for unified system configuration.
#include <configuration_manager.h>
Public Types
using change_callback = std::function< void(const std::string &, const config_value &)>
Configuration change callback.
using validator_func = std::function< validation_result(const std::string &, const config_value &)>
Configuration validator.
Public Member Functions
configuration_manager (std::shared_ptr< event_bus > bus=nullptr)
Constructor.
bool load_from_file (const std::filesystem::path &config_file)
Load configuration from file.
bool save_to_file (const std::filesystem::path &config_file) const
Save configuration to file.
bool set (const std::string &path, const config_value &value)
Set a configuration value.
template<typename T >
T get (const std::string &path, const T &default_value=T{}) const
Get a configuration value.
template<typename T >
std::optional< T > get_optional (const std::string &path) const
Get a configuration value as optional.
bool has (const std::string &path) const
Check if configuration exists.
bool remove (const std::string &path)
Remove a configuration value.
std::size_t on_change (const std::string &path, change_callback callback)
Register a change callback.
void remove_callback (const std::string &path, std::size_t id)
Unregister a change callback.
void add_validator (const std::string &path, validator_func validator)
Register a configuration validator.
validation_result validate_all () const
Validate all configuration.
void apply_system_config (const std::string &system_name, const std::unordered_map< std::string, config_value > &config)
Apply configuration for a specific system.
std::unordered_map< std::string, config_value > get_system_config (const std::string &system_name) const
Get configuration for a specific system.
void clear ()
Clear all configuration.
Static Public Member Functions
static configuration_manager & instance ()
Get singleton instance.
Detailed Description
Configuration manager for unified system configuration.
Definition at line 51 of file configuration_manager.h.
Member Typedef Documentation
change_callback
using kcenon::thread::configuration_manager::change_callback = std::function<void(const std::string&, const config_value&)>
Configuration change callback.
Definition at line 56 of file configuration_manager.h.
validator_func
using kcenon::thread::configuration_manager::validator_func = std::function<validation_result(const std::string&, const config_value&)>
Configuration validator.
Definition at line 61 of file configuration_manager.h.
Constructor & Destructor Documentation
configuration_manager()
kcenon::thread::configuration_manager::configuration_manager (std::shared_ptr< event_bus > bus = nullptr) inline explicit
Constructor.
Parameters
event_bus Optional event bus for change notifications
Definition at line 67 of file configuration_manager.h.
Member Function Documentation
add_validator()
void kcenon::thread::configuration_manager::add_validator (const std::string & path, validator_func validator) inline
Register a configuration validator.
Parameters
path Configuration path
validator Validator function
Definition at line 258 of file configuration_manager.h.
apply_system_config()
void kcenon::thread::configuration_manager::apply_system_config (const std::string & system_name, const std::unordered_map< std::string, config_value > & config) inline
Apply configuration for a specific system.
Parameters
system_name System name (e.g., "thread_system")
config Configuration map
Definition at line 294 of file configuration_manager.h.
References set().
clear()
void kcenon::thread::configuration_manager::clear () inline
Clear all configuration.
Definition at line 324 of file configuration_manager.h.
get()
template<typename T > T kcenon::thread::configuration_manager::get (const std::string & path, const T & default_value = T{}) const inline
Get a configuration value.
Template Parameters
T Value type
Parameters
path Configuration path
default_value Default value if not found
Returns
Configuration value
Definition at line 172 of file configuration_manager.h.
get_optional()
template<typename T > std::optional< T > kcenon::thread::configuration_manager::get_optional (const std::string & path) const inline
Get a configuration value as optional.
Template Parameters
T Value type
Parameters
path Configuration path
Returns
Optional configuration value
Definition at line 192 of file configuration_manager.h.
get_system_config()
std::unordered_map< std::string, config_value > kcenon::thread::configuration_manager::get_system_config (const std::string & system_name) const inline
Get configuration for a specific system.
Parameters
system_name System name
Returns
Configuration map
Definition at line 306 of file configuration_manager.h.
has()
bool kcenon::thread::configuration_manager::has (const std::string & path) const inline
Check if configuration exists.
Parameters
path Configuration path
Returns
True if exists
Definition at line 210 of file configuration_manager.h.
instance()
static configuration_manager & kcenon::thread::configuration_manager::instance () inline static
Get singleton instance.
Returns
Configuration manager instance
Definition at line 333 of file configuration_manager.h.
References instance().
Referenced by instance().
load_from_file()
bool kcenon::thread::configuration_manager::load_from_file (const std::filesystem::path & config_file) inline
Load configuration from file.
Parameters
config_file Path to configuration file
Returns
True if successful
Definition at line 79 of file configuration_manager.h.
on_change()
std::size_t kcenon::thread::configuration_manager::on_change (const std::string & path, change_callback callback) inline
Register a change callback.
Parameters
path Configuration path (empty for all changes)
callback Callback function
Returns
Callback ID for unregistration
Definition at line 231 of file configuration_manager.h.
remove()
bool kcenon::thread::configuration_manager::remove (const std::string & path) inline
Remove a configuration value.
Parameters
path Configuration path
Returns
True if removed
Definition at line 220 of file configuration_manager.h.
remove_callback()
void kcenon::thread::configuration_manager::remove_callback (const std::string & path, std::size_t id) inline
Unregister a change callback.
Parameters
path Configuration path
id Callback ID
Definition at line 243 of file configuration_manager.h.
save_to_file()
bool kcenon::thread::configuration_manager::save_to_file (const std::filesystem::path & config_file) const inline
Save configuration to file.
Parameters
config_file Path to configuration file
Returns
True if successful
Definition at line 108 of file configuration_manager.h.
set()
bool kcenon::thread::configuration_manager::set (const std::string & path, const config_value & value) inline
Set a configuration value.
Parameters
path Configuration path (e.g., "thread_system.pool_size")
value Configuration value
Returns
True if successful
Definition at line 132 of file configuration_manager.h.
Referenced by apply_system_config().
validate_all()
validation_result kcenon::thread::configuration_manager::validate_all () const inline
Validate all configuration.
Returns
Validation result
Definition at line 267 of file configuration_manager.h.
References kcenon::thread::warning.
The documentation for this class was generated from the following file:
libraries/thread_system/include/kcenon/thread/core/configuration_manager.h