Messaging System: GradualMigrationExample Class Reference
GradualMigrationExample Class Reference
Example of gradual migration strategy.
Public Member Functions
GradualMigrationExample ()
void old_interface_method ()
void transitional_method ()
void new_interface_method ()
void demonstrate_migration ()
Detailed Description
Example of gradual migration strategy.
Definition at line 166 of file migration_example.cpp.
Constructor & Destructor Documentation
GradualMigrationExample()
GradualMigrationExample::GradualMigrationExample () inline
Definition at line 171 of file migration_example.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), and kcenon::logger::result< T >::value().
Member Function Documentation
demonstrate_migration()
void GradualMigrationExample::demonstrate_migration () inline
Definition at line 206 of file migration_example.cpp.
References new_interface_method(), old_interface_method(), and transitional_method().
Referenced by main().
new_interface_method()
void GradualMigrationExample::new_interface_method () inline
Definition at line 200 of file migration_example.cpp.
Referenced by demonstrate_migration().
old_interface_method()
void GradualMigrationExample::old_interface_method () inline
Definition at line 183 of file migration_example.cpp.
Referenced by demonstrate_migration().
transitional_method()
void GradualMigrationExample::transitional_method () inline
Definition at line 190 of file migration_example.cpp.
Referenced by demonstrate_migration().
The documentation for this class was generated from the following file:
libraries/logger_system/examples/migration_example.cpp