Messaging System: utility_module::span< T, Extent > Class Template Reference
utility_module::span< T, Extent > Class Template Reference
A fallback span implementation for C++17 and earlier compilers.
#include <span.h>
Public Types
using element_type = T
using value_type = std::remove_cv_t< T >
using size_type = size_t
using difference_type = ptrdiff_t
using pointer = T *
using const_pointer = const T *
using reference = T &
using const_reference = const T &
using iterator = pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using element_type = T
using value_type = std::remove_cv_t< T >
using size_type = size_t
using difference_type = ptrdiff_t
using pointer = T *
using const_pointer = const T *
using reference = T &
using const_reference = const T &
using iterator = pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator< iterator >
using const_reverse_iterator = std::reverse_iterator< const_iterator >
Public Member Functions
constexpr span () noexcept
constexpr span (pointer ptr, size_type count) noexcept
constexpr span (pointer first, pointer last) noexcept
template<size_t N>
constexpr span (std::array< value_type, N > &arr) noexcept
template<size_t N>
constexpr span (const std::array< value_type, N > &arr) noexcept
template<typename Allocator >
constexpr span (std::vector< value_type, Allocator > &vec) noexcept
template<typename Allocator >
constexpr span (const std::vector< value_type, Allocator > &vec) noexcept
template<size_t N>
constexpr span (element_type(&arr)[N]) noexcept
constexpr span & operator= (const span &other) noexcept=default
constexpr size_type size () const noexcept
constexpr size_type size_bytes () const noexcept
constexpr bool empty () const noexcept
constexpr reference operator[] (size_type idx) const noexcept
constexpr reference front () const noexcept
constexpr reference back () const noexcept
constexpr pointer data () const noexcept
constexpr iterator begin () const noexcept
constexpr iterator end () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr const_iterator cend () const noexcept
constexpr reverse_iterator rbegin () const noexcept
constexpr reverse_iterator rend () const noexcept
constexpr const_reverse_iterator crbegin () const noexcept
constexpr const_reverse_iterator crend () const noexcept
template<size_t Count>
constexpr span< element_type, Count > first () const noexcept
constexpr span< element_type, dynamic_extent > first (size_type count) const noexcept
template<size_t Count>
constexpr span< element_type, Count > last () const noexcept
constexpr span< element_type, dynamic_extent > last (size_type count) const noexcept
template<size_t Offset, size_t Count = dynamic_extent>
constexpr auto subspan () const noexcept
constexpr span< element_type, dynamic_extent > subspan (size_type offset, size_type count=dynamic_extent) const noexcept
constexpr span () noexcept
constexpr span (pointer ptr, size_type count) noexcept
constexpr span (pointer first, pointer last) noexcept
template<size_t N>
constexpr span (std::array< value_type, N > &arr) noexcept
template<size_t N>
constexpr span (const std::array< value_type, N > &arr) noexcept
template<typename Allocator >
constexpr span (std::vector< value_type, Allocator > &vec) noexcept
template<typename Allocator >
constexpr span (const std::vector< value_type, Allocator > &vec) noexcept
template<size_t N>
constexpr span (element_type(&arr)[N]) noexcept
constexpr span & operator= (const span &other) noexcept=default
constexpr size_type size () const noexcept
constexpr size_type size_bytes () const noexcept
constexpr bool empty () const noexcept
constexpr reference operator[] (size_type idx) const noexcept
constexpr reference front () const noexcept
constexpr reference back () const noexcept
constexpr pointer data () const noexcept
constexpr iterator begin () const noexcept
constexpr iterator end () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr const_iterator cend () const noexcept
constexpr reverse_iterator rbegin () const noexcept
constexpr reverse_iterator rend () const noexcept
constexpr const_reverse_iterator crbegin () const noexcept
constexpr const_reverse_iterator crend () const noexcept
template<size_t Count>
constexpr span< element_type, Count > first () const noexcept
constexpr span< element_type, dynamic_extent > first (size_type count) const noexcept
template<size_t Count>
constexpr span< element_type, Count > last () const noexcept
constexpr span< element_type, dynamic_extent > last (size_type count) const noexcept
template<size_t Offset, size_t Count = dynamic_extent>
constexpr auto subspan () const noexcept
constexpr span< element_type, dynamic_extent > subspan (size_type offset, size_type count=dynamic_extent) const noexcept
Static Public Attributes
static constexpr size_t dynamic_extent = size_t(-1)
Detailed Description
template<typename T, size_t Extent = size_t(-1)>
class utility_module::span< T, Extent >
A fallback span implementation for C++17 and earlier compilers.
Provides a view over a contiguous sequence of objects, similar to C++20's std::span. This implementation offers a compatible subset of the std::span interface.
Template Parameters
T The type of elements in the span.
Extent The extent (size) of the span, or dynamic_extent if determined at runtime.
Definition at line 67 of file span.h.
Member Typedef Documentation
const_iterator [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::const_iterator = const_pointer
Definition at line 80 of file span.h.
const_iterator [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::const_iterator = const_pointer
Definition at line 80 of file span.h.
const_pointer [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::const_pointer = const T*
Definition at line 76 of file span.h.
const_pointer [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::const_pointer = const T*
Definition at line 76 of file span.h.
const_reference [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::const_reference = const T&
Definition at line 78 of file span.h.
const_reference [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::const_reference = const T&
Definition at line 78 of file span.h.
const_reverse_iterator [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 82 of file span.h.
const_reverse_iterator [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 82 of file span.h.
difference_type [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::difference_type = ptrdiff_t
Definition at line 74 of file span.h.
difference_type [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::difference_type = ptrdiff_t
Definition at line 74 of file span.h.
element_type [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::element_type = T
Definition at line 71 of file span.h.
element_type [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::element_type = T
Definition at line 71 of file span.h.
iterator [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::iterator = pointer
Definition at line 79 of file span.h.
iterator [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::iterator = pointer
Definition at line 79 of file span.h.
pointer [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::pointer = T*
Definition at line 75 of file span.h.
pointer [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::pointer = T*
Definition at line 75 of file span.h.
reference [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::reference = T&
Definition at line 77 of file span.h.
reference [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::reference = T&
Definition at line 77 of file span.h.
reverse_iterator [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 81 of file span.h.
reverse_iterator [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 81 of file span.h.
size_type [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::size_type = size_t
Definition at line 73 of file span.h.
size_type [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::size_type = size_t
Definition at line 73 of file span.h.
value_type [1/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::value_type = std::remove_cv_t<T>
Definition at line 72 of file span.h.
value_type [2/2]
template<typename T , size_t Extent = size_t(-1)> using utility_module::span< T, Extent >::value_type = std::remove_cv_t<T>
Definition at line 72 of file span.h.
Constructor & Destructor Documentation
span() [1/16]
template<typename T , size_t Extent = size_t(-1)> constexpr utility_module::span< T, Extent >::span () inline constexpr noexcept
Definition at line 88 of file span.h.
span() [2/16]
template<typename T , size_t Extent = size_t(-1)> constexpr utility_module::span< T, Extent >::span (pointer ptr, size_type count) inline constexpr noexcept
Definition at line 94 of file span.h.
span() [3/16]
template<typename T , size_t Extent = size_t(-1)> constexpr utility_module::span< T, Extent >::span (pointer first, pointer last) inline constexpr noexcept
Definition at line 100 of file span.h.
span() [4/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> constexpr utility_module::span< T, Extent >::span (std::array< value_type, N > & arr) inline constexpr noexcept
Definition at line 108 of file span.h.
span() [5/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> constexpr utility_module::span< T, Extent >::span (const std::array< value_type, N > & arr) inline constexpr noexcept
Definition at line 116 of file span.h.
span() [6/16]
template<typename T , size_t Extent = size_t(-1)> template<typename Allocator > constexpr utility_module::span< T, Extent >::span (std::vector< value_type, Allocator > & vec) inline constexpr noexcept
Definition at line 125 of file span.h.
span() [7/16]
template<typename T , size_t Extent = size_t(-1)> template<typename Allocator > constexpr utility_module::span< T, Extent >::span (const std::vector< value_type, Allocator > & vec) inline constexpr noexcept
Definition at line 133 of file span.h.
span() [8/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> constexpr utility_module::span< T, Extent >::span (element_type(&) arr[N]) inline constexpr noexcept
Definition at line 142 of file span.h.
span() [9/16]
template<typename T , size_t Extent = size_t(-1)> constexpr utility_module::span< T, Extent >::span () inline constexpr noexcept
Definition at line 88 of file span.h.
span() [10/16]
template<typename T , size_t Extent = size_t(-1)> constexpr utility_module::span< T, Extent >::span (pointer ptr, size_type count) inline constexpr noexcept
Definition at line 94 of file span.h.
span() [11/16]
template<typename T , size_t Extent = size_t(-1)> constexpr utility_module::span< T, Extent >::span (pointer first, pointer last) inline constexpr noexcept
Definition at line 100 of file span.h.
span() [12/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> constexpr utility_module::span< T, Extent >::span (std::array< value_type, N > & arr) inline constexpr noexcept
Definition at line 108 of file span.h.
span() [13/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> constexpr utility_module::span< T, Extent >::span (const std::array< value_type, N > & arr) inline constexpr noexcept
Definition at line 116 of file span.h.
span() [14/16]
template<typename T , size_t Extent = size_t(-1)> template<typename Allocator > constexpr utility_module::span< T, Extent >::span (std::vector< value_type, Allocator > & vec) inline constexpr noexcept
Definition at line 125 of file span.h.
span() [15/16]
template<typename T , size_t Extent = size_t(-1)> template<typename Allocator > constexpr utility_module::span< T, Extent >::span (const std::vector< value_type, Allocator > & vec) inline constexpr noexcept
Definition at line 133 of file span.h.
span() [16/16]
template<typename T , size_t Extent = size_t(-1)> template<size_t N> constexpr utility_module::span< T, Extent >::span (element_type(&) arr[N]) inline constexpr noexcept
Definition at line 142 of file span.h.
Member Function Documentation
back() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reference utility_module::span< T, Extent >::back () const inline constexpr noexcept
Definition at line 168 of file span.h.
back() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reference utility_module::span< T, Extent >::back () const inline constexpr noexcept
Definition at line 168 of file span.h.
begin() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr iterator utility_module::span< T, Extent >::begin () const inline constexpr noexcept
Definition at line 176 of file span.h.
Referenced by utility_module::span< T, Extent >::rend().
begin() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr iterator utility_module::span< T, Extent >::begin () const inline constexpr noexcept
Definition at line 176 of file span.h.
cbegin() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr const_iterator utility_module::span< T, Extent >::cbegin () const inline constexpr noexcept
Definition at line 178 of file span.h.
Referenced by utility_module::span< T, Extent >::crend().
cbegin() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr const_iterator utility_module::span< T, Extent >::cbegin () const inline constexpr noexcept
Definition at line 178 of file span.h.
cend() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr const_iterator utility_module::span< T, Extent >::cend () const inline constexpr noexcept
Definition at line 179 of file span.h.
Referenced by utility_module::span< T, Extent >::crbegin().
cend() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr const_iterator utility_module::span< T, Extent >::cend () const inline constexpr noexcept
Definition at line 179 of file span.h.
crbegin() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr const_reverse_iterator utility_module::span< T, Extent >::crbegin () const inline constexpr noexcept
Definition at line 182 of file span.h.
References utility_module::span< T, Extent >::cend().
crbegin() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr const_reverse_iterator utility_module::span< T, Extent >::crbegin () const inline constexpr noexcept
Definition at line 182 of file span.h.
References utility_module::span< T, Extent >::cend().
crend() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr const_reverse_iterator utility_module::span< T, Extent >::crend () const inline constexpr noexcept
Definition at line 183 of file span.h.
References utility_module::span< T, Extent >::cbegin().
crend() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr const_reverse_iterator utility_module::span< T, Extent >::crend () const inline constexpr noexcept
Definition at line 183 of file span.h.
References utility_module::span< T, Extent >::cbegin().
data() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr pointer utility_module::span< T, Extent >::data () const inline constexpr noexcept
Definition at line 173 of file span.h.
data() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr pointer utility_module::span< T, Extent >::data () const inline constexpr noexcept
Definition at line 173 of file span.h.
empty() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr bool utility_module::span< T, Extent >::empty () const inline constexpr noexcept
Definition at line 155 of file span.h.
empty() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr bool utility_module::span< T, Extent >::empty () const inline constexpr noexcept
Definition at line 155 of file span.h.
end() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr iterator utility_module::span< T, Extent >::end () const inline constexpr noexcept
Definition at line 177 of file span.h.
Referenced by utility_module::span< T, Extent >::rbegin().
end() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr iterator utility_module::span< T, Extent >::end () const inline constexpr noexcept
Definition at line 177 of file span.h.
first() [1/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Count> constexpr span< element_type, Count > utility_module::span< T, Extent >::first () const inline constexpr noexcept
Definition at line 187 of file span.h.
first() [2/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Count> constexpr span< element_type, Count > utility_module::span< T, Extent >::first () const inline constexpr noexcept
Definition at line 187 of file span.h.
first() [3/4]
template<typename T , size_t Extent = size_t(-1)> constexpr span< element_type, dynamic_extent > utility_module::span< T, Extent >::first (size_type count) const inline constexpr noexcept
Definition at line 192 of file span.h.
first() [4/4]
template<typename T , size_t Extent = size_t(-1)> constexpr span< element_type, dynamic_extent > utility_module::span< T, Extent >::first (size_type count) const inline constexpr noexcept
Definition at line 192 of file span.h.
front() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reference utility_module::span< T, Extent >::front () const inline constexpr noexcept
Definition at line 163 of file span.h.
front() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reference utility_module::span< T, Extent >::front () const inline constexpr noexcept
Definition at line 163 of file span.h.
last() [1/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Count> constexpr span< element_type, Count > utility_module::span< T, Extent >::last () const inline constexpr noexcept
Definition at line 198 of file span.h.
last() [2/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Count> constexpr span< element_type, Count > utility_module::span< T, Extent >::last () const inline constexpr noexcept
Definition at line 198 of file span.h.
last() [3/4]
template<typename T , size_t Extent = size_t(-1)> constexpr span< element_type, dynamic_extent > utility_module::span< T, Extent >::last (size_type count) const inline constexpr noexcept
Definition at line 203 of file span.h.
last() [4/4]
template<typename T , size_t Extent = size_t(-1)> constexpr span< element_type, dynamic_extent > utility_module::span< T, Extent >::last (size_type count) const inline constexpr noexcept
Definition at line 203 of file span.h.
operator=() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr span & utility_module::span< T, Extent >::operator= (const span< T, Extent > & other) constexpr default noexcept
operator=() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr span & utility_module::span< T, Extent >::operator= (const span< T, Extent > & other) constexpr default noexcept
operator[]() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reference utility_module::span< T, Extent >::operator[] (size_type idx) const inline constexpr noexcept
Definition at line 158 of file span.h.
operator[]() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reference utility_module::span< T, Extent >::operator[] (size_type idx) const inline constexpr noexcept
Definition at line 158 of file span.h.
rbegin() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reverse_iterator utility_module::span< T, Extent >::rbegin () const inline constexpr noexcept
Definition at line 180 of file span.h.
References utility_module::span< T, Extent >::end().
rbegin() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reverse_iterator utility_module::span< T, Extent >::rbegin () const inline constexpr noexcept
Definition at line 180 of file span.h.
References utility_module::span< T, Extent >::end().
rend() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reverse_iterator utility_module::span< T, Extent >::rend () const inline constexpr noexcept
Definition at line 181 of file span.h.
References utility_module::span< T, Extent >::begin().
rend() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr reverse_iterator utility_module::span< T, Extent >::rend () const inline constexpr noexcept
Definition at line 181 of file span.h.
References utility_module::span< T, Extent >::begin().
size() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr size_type utility_module::span< T, Extent >::size () const inline constexpr noexcept
Definition at line 153 of file span.h.
size() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr size_type utility_module::span< T, Extent >::size () const inline constexpr noexcept
Definition at line 153 of file span.h.
size_bytes() [1/2]
template<typename T , size_t Extent = size_t(-1)> constexpr size_type utility_module::span< T, Extent >::size_bytes () const inline constexpr noexcept
Definition at line 154 of file span.h.
size_bytes() [2/2]
template<typename T , size_t Extent = size_t(-1)> constexpr size_type utility_module::span< T, Extent >::size_bytes () const inline constexpr noexcept
Definition at line 154 of file span.h.
subspan() [1/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Offset, size_t Count = dynamic_extent> constexpr auto utility_module::span< T, Extent >::subspan () const inline constexpr noexcept
Definition at line 209 of file span.h.
subspan() [2/4]
template<typename T , size_t Extent = size_t(-1)> template<size_t Offset, size_t Count = dynamic_extent> constexpr auto utility_module::span< T, Extent >::subspan () const inline constexpr noexcept
Definition at line 209 of file span.h.
subspan() [3/4]
template<typename T , size_t Extent = size_t(-1)> constexpr span< element_type, dynamic_extent > utility_module::span< T, Extent >::subspan (size_type offset, size_type count = dynamic_extent) const inline constexpr noexcept
Definition at line 219 of file span.h.
subspan() [4/4]
template<typename T , size_t Extent = size_t(-1)> constexpr span< element_type, dynamic_extent > utility_module::span< T, Extent >::subspan (size_type offset, size_type count = dynamic_extent) const inline constexpr noexcept
Definition at line 219 of file span.h.
Member Data Documentation
dynamic_extent
template<typename T , size_t Extent = size_t(-1)> static constexpr size_t kcenon::thread::utils::span::dynamic_extent = size_t(-1) static constexpr
Definition at line 85 of file span.h.
The documentation for this class was generated from the following files:
libraries/thread_system/include/kcenon/thread/utils/span.h
libraries/thread_system/utilities/include/span.h