Messaging System: libraries/logger_system/tests/benchmarks/logger_benchmarks/comprehensive_benchmark.cpp File Reference
comprehensive_benchmark.cpp File Reference
#include <benchmark/benchmark.h>
#include <logger/config/logger_builder.h>
#include <logger/logger.h>
#include <memory>
#include <vector>
#include <random>
#include <sstream>
Classes
class null_writer
Comprehensive benchmark suite for logger system.
Functions
std::string generate_message (size_t size)
Generate random log message of specified size.
static void BM_ConfigurationTemplates (benchmark::State &state)
Benchmark different configuration templates.
Arg (0) -> Arg(1) ->Arg(2) ->Arg(3) ->Arg(4)
static void BM_MessageSize (benchmark::State &state)
Benchmark message size impact.
Arg (10) -> Arg(100) ->Arg(256) ->Arg(1024) ->Arg(4096) ->Arg(16384)
static void BM_QueueBehavior (benchmark::State &state)
Benchmark queue behavior under different loads.
Args ({1000, 10}) -> Args({1000, 100}) ->Args({10000, 100}) ->Args({10000, 1000}) ->Args({100000, 5000})
static void BM_MultipleWriters (benchmark::State &state)
Benchmark logging with different numbers of writers.
Arg (1) -> Arg(2) ->Arg(5) ->Arg(10)
static void BM_FilterImpact (benchmark::State &state)
Benchmark filter performance impact.
static void BM_StructuredLogging (benchmark::State &state)
Benchmark structured logging overhead.
BENCHMARK_MAIN ()
Function Documentation
Arg() [1/3]
Arg (0) -> Arg(1) ->Arg(2) ->Arg(3) ->Arg(4)
Arg() [2/3]
Arg (1) -> Arg(2) ->Arg(5) ->Arg(10)
Arg() [3/3]
Arg (10) -> Arg(100) ->Arg(256) ->Arg(1024) ->Arg(4096) ->Arg(16384)
Args()
Args ({1000, 10}) -> Args({1000, 100}) ->Args({10000, 100}) ->Args({10000, 1000}) ->Args({100000, 5000})
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_ConfigurationTemplates()
static void BM_ConfigurationTemplates (benchmark::State & state) static
Benchmark different configuration templates.
Definition at line 96 of file comprehensive_benchmark.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_config::async, kcenon::logger::logger_builder::build(), kcenon::logger::logger_config::debug_config(), kcenon::logger::logger_config::default_config(), kcenon::logger::logger_config::high_performance(), kcenon::logger::logger_config::low_latency(), kcenon::logger::logger_config::production(), kcenon::logger::logger::start(), and kcenon::logger::logger_builder::with_config().
BM_FilterImpact()
static void BM_FilterImpact (benchmark::State & state) static
Benchmark filter performance impact.
Definition at line 300 of file comprehensive_benchmark.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger::start(), kcenon::logger::logger_builder::with_async(), and kcenon::logger::logger_builder::with_min_level().
BM_MessageSize()
static void BM_MessageSize (benchmark::State & state) static
Benchmark message size impact.
Definition at line 165 of file comprehensive_benchmark.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), generate_message(), kcenon::logger::logger::start(), kcenon::logger::logger_builder::with_async(), kcenon::logger::logger_builder::with_batch_size(), kcenon::logger::logger_builder::with_batch_writing(), and kcenon::logger::logger_builder::with_buffer_size().
BM_MultipleWriters()
static void BM_MultipleWriters (benchmark::State & state) static
Benchmark logging with different numbers of writers.
Definition at line 256 of file comprehensive_benchmark.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger::start(), kcenon::logger::logger_builder::with_async(), kcenon::logger::logger_builder::with_batch_size(), and kcenon::logger::logger_builder::with_batch_writing().
BM_QueueBehavior()
static void BM_QueueBehavior (benchmark::State & state) static
Benchmark queue behavior under different loads.
Definition at line 208 of file comprehensive_benchmark.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger::start(), kcenon::logger::logger_builder::with_async(), kcenon::logger::logger_builder::with_max_queue_size(), and kcenon::logger::logger_builder::with_overflow_policy().
BM_StructuredLogging()
static void BM_StructuredLogging (benchmark::State & state) static
Benchmark structured logging overhead.
Definition at line 346 of file comprehensive_benchmark.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger::start(), kcenon::logger::logger_builder::with_async(), and kcenon::logger::logger_builder::with_structured_logging().
generate_message()
std::string generate_message (size_t size)
Generate random log message of specified size.
Definition at line 74 of file comprehensive_benchmark.cpp.
Referenced by BM_MessageSize().