Messaging System: kcenon::messaging::cluster::cluster_membership Class Reference
kcenon::messaging::cluster::cluster_membership Class Reference
#include <distributed_messaging.h>
Public Member Functions
cluster_membership (const std::string &local_id)
~cluster_membership ()
void add_node (std::unique_ptr< cluster_node > node)
bool remove_node (const std::string &node_id)
cluster_node * get_node (const std::string &node_id) const
std::vector< cluster_node * > get_all_nodes () const
std::vector< cluster_node * > get_active_nodes () const
size_t get_cluster_size () const
const std::string & get_local_node_id () const
void start_heartbeat ()
void stop_heartbeat ()
void update_heartbeat (const std::string &node_id)
void set_node_joined_callback (std::function< void(const cluster_node &)> callback)
void set_node_left_callback (std::function< void(const cluster_node &)> callback)
void set_node_failed_callback (std::function< void(const cluster_node &)> callback)
Detailed Description
Definition at line 58 of file distributed_messaging.h.
Constructor & Destructor Documentation
cluster_membership()
kcenon::messaging::cluster::cluster_membership::cluster_membership (const std::string & local_id) inline explicit
Definition at line 76 of file distributed_messaging.h.
~cluster_membership()
kcenon::messaging::cluster::cluster_membership::~cluster_membership () inline
Definition at line 78 of file distributed_messaging.h.
References stop_heartbeat().
Member Function Documentation
add_node()
void kcenon::messaging::cluster::cluster_membership::add_node (std::unique_ptr< cluster_node > node) inline
Definition at line 83 of file distributed_messaging.h.
References kcenon::messaging::cluster::active.
get_active_nodes()
std::vector< cluster_node * > kcenon::messaging::cluster::cluster_membership::get_active_nodes () const inline
Definition at line 124 of file distributed_messaging.h.
References kcenon::messaging::cluster::active.
get_all_nodes()
std::vector< cluster_node * > kcenon::messaging::cluster::cluster_membership::get_all_nodes () const inline
Definition at line 115 of file distributed_messaging.h.
get_cluster_size()
size_t kcenon::messaging::cluster::cluster_membership::get_cluster_size () const inline
Definition at line 135 of file distributed_messaging.h.
get_local_node_id()
const std::string & kcenon::messaging::cluster::cluster_membership::get_local_node_id () const inline
Definition at line 136 of file distributed_messaging.h.
get_node()
cluster_node * kcenon::messaging::cluster::cluster_membership::get_node (const std::string & node_id) const inline
Definition at line 109 of file distributed_messaging.h.
Referenced by update_heartbeat().
remove_node()
bool kcenon::messaging::cluster::cluster_membership::remove_node (const std::string & node_id) inline
Definition at line 95 of file distributed_messaging.h.
set_node_failed_callback()
void kcenon::messaging::cluster::cluster_membership::set_node_failed_callback (std::function< void(const cluster_node &)> callback) inline
Definition at line 172 of file distributed_messaging.h.
set_node_joined_callback()
void kcenon::messaging::cluster::cluster_membership::set_node_joined_callback (std::function< void(const cluster_node &)> callback) inline
Definition at line 164 of file distributed_messaging.h.
set_node_left_callback()
void kcenon::messaging::cluster::cluster_membership::set_node_left_callback (std::function< void(const cluster_node &)> callback) inline
Definition at line 168 of file distributed_messaging.h.
start_heartbeat()
void kcenon::messaging::cluster::cluster_membership::start_heartbeat () inline
Definition at line 139 of file distributed_messaging.h.
stop_heartbeat()
void kcenon::messaging::cluster::cluster_membership::stop_heartbeat () inline
Definition at line 146 of file distributed_messaging.h.
Referenced by ~cluster_membership().
update_heartbeat()
void kcenon::messaging::cluster::cluster_membership::update_heartbeat (const std::string & node_id) inline
Definition at line 156 of file distributed_messaging.h.
References get_node().
The documentation for this class was generated from the following file:
application_layer/include/kcenon/messaging/cluster/distributed_messaging.h