Messaging System: monitoring_system::ring_buffer< T > Class Template Reference
monitoring_system::ring_buffer< T > Class Template Reference
Lock-free ring buffer with atomic operations.
#include <ring_buffer.h>
Public Member Functions
ring_buffer (const ring_buffer_config &config={})
Constructor with configuration.
ring_buffer (const ring_buffer &)=delete
ring_buffer & operator= (const ring_buffer &)=delete
ring_buffer (ring_buffer &&)=default
ring_buffer & operator= (ring_buffer &&)=default
result_void write (T &&item)
Write a single element to the buffer.
size_t write_batch (std::vector< T > &&items)
Write multiple elements in batch.
result_void read (T &item)
Read a single element from the buffer.
size_t read_batch (std::vector< T > &items, size_t max_count=SIZE_MAX)
Read multiple elements in batch.
result_void peek (T &item) const
Peek at the next item without removing it.
size_t size () const noexcept
Get current number of elements in buffer.
bool empty () const noexcept
Check if buffer is empty.
bool full () const noexcept
Check if buffer is full.
size_t capacity () const noexcept
Get buffer capacity.
void clear () noexcept
Clear all elements in the buffer.
const ring_buffer_config & get_config () const noexcept
Get buffer configuration.
const ring_buffer_stats & get_stats () const noexcept
Get buffer statistics.
void reset_stats () noexcept
Reset statistics.
Detailed Description
template<typename T>
class monitoring_system::ring_buffer< T >
Lock-free ring buffer with atomic operations.
Template Parameters
T The type of elements to store
This implementation uses atomic operations for thread-safety and provides efficient circular buffer semantics with configurable overflow behavior.
Definition at line 104 of file ring_buffer.h.
Constructor & Destructor Documentation
ring_buffer() [1/3]
template<typename T > monitoring_system::ring_buffer< T >::ring_buffer (const ring_buffer_config & config = {}) inline explicit
Constructor with configuration.
Definition at line 141 of file ring_buffer.h.
ring_buffer() [2/3]
template<typename T > monitoring_system::ring_buffer< T >::ring_buffer (const ring_buffer< T > &) delete
ring_buffer() [3/3]
template<typename T > monitoring_system::ring_buffer< T >::ring_buffer (ring_buffer< T > &&) default
Member Function Documentation
capacity()
template<typename T > size_t monitoring_system::ring_buffer< T >::capacity () const inline noexcept
Get buffer capacity.
Definition at line 325 of file ring_buffer.h.
References monitoring_system::ring_buffer_config::capacity.
Referenced by TEST_F().
clear()
template<typename T > void monitoring_system::ring_buffer< T >::clear () inline noexcept
Clear all elements in the buffer.
Definition at line 332 of file ring_buffer.h.
empty()
template<typename T > bool monitoring_system::ring_buffer< T >::empty () const inline noexcept
Check if buffer is empty.
Definition at line 309 of file ring_buffer.h.
References monitoring_system::ring_buffer< T >::size().
Referenced by TEST_F().
full()
template<typename T > bool monitoring_system::ring_buffer< T >::full () const inline noexcept
Check if buffer is full.
Definition at line 316 of file ring_buffer.h.
Referenced by TEST_F().
get_config()
template<typename T > const ring_buffer_config & monitoring_system::ring_buffer< T >::get_config () const inline noexcept
Get buffer configuration.
Definition at line 340 of file ring_buffer.h.
get_stats()
template<typename T > const ring_buffer_stats & monitoring_system::ring_buffer< T >::get_stats () const inline noexcept
Get buffer statistics.
Definition at line 347 of file ring_buffer.h.
operator=() [1/2]
template<typename T > ring_buffer & monitoring_system::ring_buffer< T >::operator= (const ring_buffer< T > &) delete
operator=() [2/2]
template<typename T > ring_buffer & monitoring_system::ring_buffer< T >::operator= (ring_buffer< T > &&) default
peek()
template<typename T > result_void monitoring_system::ring_buffer< T >::peek (T & item) const inline
Peek at the next item without removing it.
Parameters
item Reference to store the peeked item
Returns
Result indicating success or failure
Definition at line 279 of file ring_buffer.h.
References monitoring_system::collection_failed.
Referenced by TEST_F().
read()
template<typename T > result_void monitoring_system::ring_buffer< T >::read (T & item) inline
Read a single element from the buffer.
Parameters
item Reference to store the read item
Returns
Result indicating success or failure
Definition at line 222 of file ring_buffer.h.
References monitoring_system::collection_failed, monitoring_system::ring_buffer_stats::failed_reads, and monitoring_system::ring_buffer_stats::total_reads.
Referenced by monitoring_system::ring_buffer< T >::read_batch(), TEST_F(), TEST_F(), and TEST_F().
read_batch()
template<typename T > size_t monitoring_system::ring_buffer< T >::read_batch (std::vector< T > & items, size_t max_count = SIZE_MAX) inline
Read multiple elements in batch.
Parameters
items Vector to store read items
max_count Maximum number of items to read
Returns
Number of items actually read
Definition at line 250 of file ring_buffer.h.
References monitoring_system::ring_buffer_config::batch_size, and monitoring_system::ring_buffer< T >::read().
Referenced by TEST_F().
reset_stats()
template<typename T > void monitoring_system::ring_buffer< T >::reset_stats () inline noexcept
Reset statistics.
Definition at line 354 of file ring_buffer.h.
References monitoring_system::ring_buffer_stats::creation_time, monitoring_system::ring_buffer_stats::failed_reads, monitoring_system::ring_buffer_stats::failed_writes, monitoring_system::ring_buffer_stats::overwrites, monitoring_system::ring_buffer_stats::total_reads, and monitoring_system::ring_buffer_stats::total_writes.
size()
template<typename T > size_t monitoring_system::ring_buffer< T >::size () const inline noexcept
Get current number of elements in buffer.
Definition at line 295 of file ring_buffer.h.
References monitoring_system::ring_buffer_config::capacity.
Referenced by monitoring_system::ring_buffer< T >::empty(), TEST_F(), and TEST_F().
write()
template<typename T > result_void monitoring_system::ring_buffer< T >::write (T && item) inline
Write a single element to the buffer.
Parameters
item Item to write
Returns
Result indicating success or failure
Definition at line 164 of file ring_buffer.h.
References monitoring_system::ring_buffer_stats::failed_writes, monitoring_system::ring_buffer_config::overwrite_old, monitoring_system::ring_buffer_stats::overwrites, monitoring_system::storage_full, and monitoring_system::ring_buffer_stats::total_writes.
Referenced by TEST_F(), TEST_F(), TEST_F(), and monitoring_system::ring_buffer< T >::write_batch().
write_batch()
template<typename T > size_t monitoring_system::ring_buffer< T >::write_batch (std::vector< T > && items) inline
Write multiple elements in batch.
Parameters
items Vector of items to write
Returns
Number of items successfully written
Definition at line 199 of file ring_buffer.h.
References monitoring_system::ring_buffer_config::overwrite_old, and monitoring_system::ring_buffer< T >::write().
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/utils/ring_buffer.h