Messaging System: retry_handler Class Reference
retry_handler Class Reference
Public Member Functions
retry_handler (std::shared_ptr< kcenon::logger::logger > logger, metrics_collector *metrics, int max_retries=3, std::chrono::milliseconds retry_delay=100ms)
template<typename Func >
bool execute_with_retry (Func &&func, const std::string &operation_name)
Detailed Description
Definition at line 232 of file production_ready_example.cpp.
Constructor & Destructor Documentation
retry_handler()
retry_handler::retry_handler (std::shared_ptr< kcenon::logger::logger > logger, metrics_collector * metrics, int max_retries = 3, std::chrono::milliseconds retry_delay = 100ms) inline
Definition at line 240 of file production_ready_example.cpp.
Member Function Documentation
execute_with_retry()
template<typename Func > bool retry_handler::execute_with_retry (Func && func, const std::string & operation_name) inline
Definition at line 250 of file production_ready_example.cpp.
References metrics_collector::increment_errors(), metrics_collector::increment_retries(), and metrics_collector::increment_successful_retries().
Referenced by main().
The documentation for this class was generated from the following file:
application_layer/samples/production_ready_example.cpp