Messaging System: AdvancedContainerExample Class Reference
AdvancedContainerExample Class Reference
Advanced Container System Example.
Public Member Functions
AdvancedContainerExample ()
~AdvancedContainerExample ()
void demonstrate_basic_operations ()
Demonstrates basic container operations.
void demonstrate_multithreaded_operations ()
Demonstrates multi-threaded producer-consumer pattern.
void demonstrate_error_handling ()
Demonstrates error handling scenarios.
void demonstrate_performance_scenarios ()
Demonstrates performance scenarios.
void print_final_statistics ()
Prints final statistics.
void run_all_demonstrations ()
Runs all demonstrations.
Detailed Description
Advanced Container System Example.
Demonstrates comprehensive usage of the container system including:
Multi-threaded producer-consumer patterns
Complex data structures
Performance monitoring
Error handling
Serialization/deserialization
Integration features (when available)
Definition at line 33 of file advanced_container_example.cpp.
Constructor & Destructor Documentation
AdvancedContainerExample()
AdvancedContainerExample::AdvancedContainerExample () inline
Definition at line 49 of file advanced_container_example.cpp.
~AdvancedContainerExample()
AdvancedContainerExample::~AdvancedContainerExample () inline
Definition at line 66 of file advanced_container_example.cpp.
References print_final_statistics().
Member Function Documentation
demonstrate_basic_operations()
void AdvancedContainerExample::demonstrate_basic_operations () inline
Demonstrates basic container operations.
Definition at line 74 of file advanced_container_example.cpp.
Referenced by run_all_demonstrations().
demonstrate_error_handling()
void AdvancedContainerExample::demonstrate_error_handling () inline
Demonstrates error handling scenarios.
Definition at line 357 of file advanced_container_example.cpp.
Referenced by run_all_demonstrations().
demonstrate_multithreaded_operations()
void AdvancedContainerExample::demonstrate_multithreaded_operations () inline
Demonstrates multi-threaded producer-consumer pattern.
Definition at line 226 of file advanced_container_example.cpp.
References container_module::integration::messaging_container_builder::add_value(), container_module::integration::messaging_container_builder::build(), container_module::integration::messaging_container_builder::message_type(), container_module::integration::messaging_container_builder::optimize_for_speed(), container_module::integration::messaging_container_builder::source(), and container_module::integration::messaging_container_builder::target().
Referenced by run_all_demonstrations().
demonstrate_performance_scenarios()
void AdvancedContainerExample::demonstrate_performance_scenarios () inline
Demonstrates performance scenarios.
Definition at line 407 of file advanced_container_example.cpp.
Referenced by run_all_demonstrations().
print_final_statistics()
void AdvancedContainerExample::print_final_statistics () inline
Prints final statistics.
Definition at line 531 of file advanced_container_example.cpp.
Referenced by ~AdvancedContainerExample().
run_all_demonstrations()
void AdvancedContainerExample::run_all_demonstrations () inline
Runs all demonstrations.
Definition at line 558 of file advanced_container_example.cpp.
References demonstrate_basic_operations(), demonstrate_error_handling(), demonstrate_multithreaded_operations(), and demonstrate_performance_scenarios().
Referenced by main().
The documentation for this class was generated from the following file:
libraries/container_system/examples/advanced_container_example.cpp