Messaging System: ModernServer Class Reference
ModernServer Class Reference
Modern server using new API.
Public Member Functions
ModernServer (const std::string &id)
void start (uint16_t port)
void stop ()
void enable_async_processing ()
void show_statistics ()
Detailed Description
Modern server using new API.
Definition at line 29 of file modern_usage.cpp.
Constructor & Destructor Documentation
ModernServer()
ModernServer::ModernServer (const std::string & id) inline
Definition at line 31 of file modern_usage.cpp.
References network_system::integration::thread_integration_manager::instance().
Member Function Documentation
enable_async_processing()
void ModernServer::enable_async_processing () inline
Definition at line 55 of file modern_usage.cpp.
show_statistics()
void ModernServer::show_statistics () inline
Definition at line 60 of file modern_usage.cpp.
References network_system::integration::thread_integration_manager::get_metrics(), network_system::integration::thread_integration_manager::instance(), and network_system::integration::thread_integration_manager::metrics::worker_threads.
start()
void ModernServer::start (uint16_t port) inline
Definition at line 43 of file modern_usage.cpp.
stop()
void ModernServer::stop () inline
Definition at line 50 of file modern_usage.cpp.
The documentation for this class was generated from the following file:
libraries/network_system/samples/messaging_system_integration/modern_usage.cpp