Messaging System: container_module::bytes_value Class Reference
container_module::bytes_value Class Reference
A specialized value that stores an arbitrary byte array (Base64-encoded in string form).
#include <bytes_value.h>
Public Member Functions
bytes_value ()
bytes_value (const std::string &name, const std::vector< uint8_t > &data)
bytes_value (const std::string &name, const unsigned char *data, size_t size)
~bytes_value () override=default
std::string to_string (const bool &original=true) const override
Public Member Functions inherited from container_module::value
value ()
value (std::shared_ptr< value > object)
value (const std::string &name, std::vector< std::shared_ptr< value > > units={})
value (const std::string &name, const value_types &type, const std::string &data)
value (const std::string &name, const unsigned char *data, const size_t &size, const value_types &type=value_types::null_value)
value (value &&other) noexcept
value & operator= (value &&other) noexcept
virtual ~value ()
std::shared_ptr< value > get_ptr ()
void set_parent (std::shared_ptr< value > parent)
void set_data (const unsigned char *data, const size_t &size, const value_types &type)
Set raw data with a known type.
void set_data (const std::string &name, const value_types &type, const std::string &data)
Set this value from a string form, specifying a type.
std::string name () const
value_types type () const
std::string data () const
size_t size () const
std::shared_ptr< value > parent ()
size_t child_count () const
std::vector< std::shared_ptr< value > > children (const bool &only_container=false)
std::vector< std::shared_ptr< value > > value_array (std::string_view key)
const std::vector< uint8_t > to_bytes () const
bool is_null () const
bool is_bytes () const
bool is_boolean () const
bool is_numeric () const
bool is_string () const
bool is_container () const
const std::string to_xml ()
const std::string to_json ()
const std::string serialize ()
template<typename T >
T safe_convert (const char *type_name, T default_value) const
Template method for safe type conversion with null checking.
virtual bool to_boolean () const
Virtual numeric/string conversion methods.
virtual short to_short () const
virtual unsigned short to_ushort () const
virtual int to_int () const
virtual unsigned int to_uint () const
virtual long to_long () const
virtual unsigned long to_ulong () const
virtual long long to_llong () const
virtual unsigned long long to_ullong () const
virtual float to_float () const
virtual double to_double () const
virtual std::shared_ptr< value > add (const value &item, bool update_count=true)
Virtual methods for adding/removing child values.
virtual std::shared_ptr< value > add (std::shared_ptr< value > item, bool update_count=true)
virtual void add (const std::vector< value > &items, bool update_count=true)
virtual void add (const std::vector< std::shared_ptr< value > > &items, bool update_count=true)
virtual void remove (std::string_view name, bool update_count=true)
virtual void remove (std::shared_ptr< value > item, bool update_count=true)
virtual void remove_all ()
std::shared_ptr< value > operator[] (std::string_view key)
An index operator to get the first matching child by name (if any).
Additional Inherited Members
Protected Member Functions inherited from container_module::value
template<typename T >
void set_data (T data)
std::string convert_specific_string (const std::vector< uint8_t > &data) const
std::vector< uint8_t > convert_specific_string (std::string data) const
void set_byte_string (const std::string &data)
void set_string (const std::string &data)
void set_boolean (const std::string &data)
void set_short (const std::string &data)
void set_ushort (const std::string &data)
void set_int (const std::string &data)
void set_uint (const std::string &data)
void set_long (const std::string &data)
void set_ulong (const std::string &data)
void set_llong (const std::string &data)
void set_ullong (const std::string &data)
void set_float (const std::string &data)
void set_double (const std::string &data)
Protected Attributes inherited from container_module::value
size_t size_
value_types type_
std::string name_
std::vector< uint8_t > data_
std::weak_ptr< value > parent_
std::vector< std::shared_ptr< value > > units_
std::map< value_types, std::function< void(const std::string &)> > data_type_map_
Detailed Description
A specialized value that stores an arbitrary byte array (Base64-encoded in string form).
Definition at line 44 of file bytes_value.h.
Constructor & Destructor Documentation
bytes_value() [1/3]
container_module::bytes_value::bytes_value ()
Definition at line 41 of file bytes_value.cpp.
References container_module::bytes_value, container_module::value::size_, and container_module::value::type_.
bytes_value() [2/3]
container_module::bytes_value::bytes_value (const std::string & name, const std::vector< uint8_t > & data)
Definition at line 47 of file bytes_value.cpp.
References container_module::value::data_, container_module::value::name(), container_module::value::name_, container_module::value::size(), and container_module::value::size_.
bytes_value() [3/3]
container_module::bytes_value::bytes_value (const std::string & name, const unsigned char * data, size_t size)
Definition at line 56 of file bytes_value.cpp.
References container_module::value::data_, container_module::value::name(), container_module::value::name_, container_module::value::size(), and container_module::value::size_.
~bytes_value()
container_module::bytes_value::~bytes_value () override default
Member Function Documentation
to_string()
std::string container_module::bytes_value::to_string (const bool & original = true) const override virtual
Reimplemented from container_module::value.
Definition at line 69 of file bytes_value.cpp.
References container_module::value::data_.
The documentation for this class was generated from the following files:
libraries/container_system/values/bytes_value.h
libraries/container_system/values/bytes_value.cpp