Messaging System: LogFileRecoveryTest Class Reference
LogFileRecoveryTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
void cleanup_files ()
Protected Attributes
std::string test_file_
std::string recovery_file_
std::string backup_file_
std::string checksum_file_
Detailed Description
Definition at line 191 of file crash_safety_test.cpp.
Member Function Documentation
cleanup_files()
void LogFileRecoveryTest::cleanup_files () inline protected
Definition at line 206 of file crash_safety_test.cpp.
References backup_file_, checksum_file_, recovery_file_, and test_file_.
Referenced by SetUp(), and TearDown().
SetUp()
void LogFileRecoveryTest::SetUp () inline override protected
Definition at line 193 of file crash_safety_test.cpp.
References backup_file_, checksum_file_, cleanup_files(), recovery_file_, and test_file_.
TearDown()
void LogFileRecoveryTest::TearDown () inline override protected
Definition at line 202 of file crash_safety_test.cpp.
References cleanup_files().
Member Data Documentation
backup_file_
std::string LogFileRecoveryTest::backup_file_ protected
Definition at line 216 of file crash_safety_test.cpp.
Referenced by cleanup_files(), and SetUp().
checksum_file_
std::string LogFileRecoveryTest::checksum_file_ protected
Definition at line 217 of file crash_safety_test.cpp.
Referenced by cleanup_files(), and SetUp().
recovery_file_
std::string LogFileRecoveryTest::recovery_file_ protected
Definition at line 215 of file crash_safety_test.cpp.
Referenced by cleanup_files(), and SetUp().
test_file_
std::string LogFileRecoveryTest::test_file_ protected
Definition at line 214 of file crash_safety_test.cpp.
Referenced by cleanup_files(), and SetUp().
The documentation for this class was generated from the following file:
libraries/logger_system/tests/unit/safety_test/crash_safety_test.cpp