Messaging System: libraries/monitoring_system/examples/result_pattern_example.cpp File Reference
result_pattern_example.cpp File Reference
#include <iostream>
#include <monitoring/core/result_types.h>
#include <monitoring/core/error_codes.h>
#include <monitoring/interfaces/monitoring_interface.h>
Functions
result< double > divide (double a, double b)
Example demonstrating Result pattern usage.
result_void validate_range (double value, double min, double max)
result< std::string > process_metric (double value)
int main ()
Function Documentation
divide()
result< double > divide (double a, double b)
Example demonstrating Result pattern usage.
Definition at line 13 of file result_pattern_example.cpp.
Referenced by monitoring_system::query_parser::parse_expression().
main()
int main ()
Definition at line 47 of file result_pattern_example.cpp.
References monitoring_system::metrics_snapshot::add_metric(), monitoring_system::monitoring_config::buffer_size, monitoring_system::monitoring_config::collection_interval, monitoring_system::divide, monitoring_system::metrics_snapshot::get_metric(), monitoring_system::monitoring_config::history_size, monitoring_system::metrics_snapshot::metrics, process_metric(), monitoring_system::monitoring_config::validate(), and validate_range().
process_metric()
result< std::string > process_metric (double value)
Definition at line 35 of file result_pattern_example.cpp.
References monitoring_system::divide, and monitoring_system::result< T >::map().
Referenced by main().
validate_range()
result_void validate_range (double value, double min, double max)
Definition at line 24 of file result_pattern_example.cpp.
References monitoring_system::max, and monitoring_system::min.
Referenced by main().