Messaging System: platform_test Namespace Reference
platform_test Namespace Reference
Classes
class AtomicOperationsTest
class CachePerformanceTest
class PlatformSpecificTest
Functions
TEST_F (AtomicOperationsTest, AtomicSizeSupport)
TEST_F (AtomicOperationsTest, MemoryOrdering)
TEST_F (AtomicOperationsTest, CompareAndSwapPatterns)
TEST_F (AtomicOperationsTest, AtomicFetchOperations)
TEST_F (AtomicOperationsTest, AtomicPointers)
TEST_F (AtomicOperationsTest, AtomicFlag)
TEST_F (AtomicOperationsTest, PerformanceCharacteristics)
TEST_F (AtomicOperationsTest, WaitNotifyOperations)
TEST_F (AtomicOperationsTest, CustomAtomicTypes)
TEST_F (CachePerformanceTest, FalseSharingImpact)
TEST_F (CachePerformanceTest, CacheLineBouncing)
TEST_F (CachePerformanceTest, MemoryAccessPatterns)
TEST_F (CachePerformanceTest, DataStructureLayout)
TEST_F (CachePerformanceTest, PrefetchingBehavior)
TEST_F (CachePerformanceTest, CacheObliviousTraversal)
TEST_F (PlatformSpecificTest, DISABLED_ThreadPriorityControl)
TEST_F (PlatformSpecificTest, DISABLED_CPUAffinityControl)
TEST_F (PlatformSpecificTest, HighResolutionTimer)
TEST_F (PlatformSpecificTest, MemoryAlignment)
TEST_F (PlatformSpecificTest, ThreadLocalStorage)
TEST_F (PlatformSpecificTest, MemoryBarriers)
TEST_F (PlatformSpecificTest, CompilerAttributes)
TEST_F (PlatformSpecificTest, PlatformAtomics)
TEST_F (PlatformSpecificTest, EndiannessDetection)
Function Documentation
TEST_F() [1/24]
platform_test::TEST_F (AtomicOperationsTest , AtomicFetchOperations)
Definition at line 230 of file atomic_operations_test.cpp.
TEST_F() [2/24]
platform_test::TEST_F (AtomicOperationsTest , AtomicFlag)
Definition at line 312 of file atomic_operations_test.cpp.
TEST_F() [3/24]
platform_test::TEST_F (AtomicOperationsTest , AtomicPointers)
Definition at line 269 of file atomic_operations_test.cpp.
TEST_F() [4/24]
platform_test::TEST_F (AtomicOperationsTest , AtomicSizeSupport)
Definition at line 54 of file atomic_operations_test.cpp.
Referenced by TEST_F(), and TEST_F().
TEST_F() [5/24]
platform_test::TEST_F (AtomicOperationsTest , CompareAndSwapPatterns)
Definition at line 180 of file atomic_operations_test.cpp.
TEST_F() [6/24]
platform_test::TEST_F (AtomicOperationsTest , CustomAtomicTypes)
Definition at line 452 of file atomic_operations_test.cpp.
References Point::x, and Point::y.
TEST_F() [7/24]
platform_test::TEST_F (AtomicOperationsTest , MemoryOrdering)
Definition at line 124 of file atomic_operations_test.cpp.
TEST_F() [8/24]
platform_test::TEST_F (AtomicOperationsTest , PerformanceCharacteristics)
Definition at line 370 of file atomic_operations_test.cpp.
TEST_F() [9/24]
platform_test::TEST_F (AtomicOperationsTest , WaitNotifyOperations)
Definition at line 429 of file atomic_operations_test.cpp.
TEST_F() [10/24]
platform_test::TEST_F (CachePerformanceTest , CacheLineBouncing)
Definition at line 140 of file cache_performance_test.cpp.
TEST_F() [11/24]
platform_test::TEST_F (CachePerformanceTest , CacheObliviousTraversal)
Definition at line 406 of file cache_performance_test.cpp.
TEST_F() [12/24]
platform_test::TEST_F (CachePerformanceTest , DataStructureLayout)
Definition at line 261 of file cache_performance_test.cpp.
TEST_F() [13/24]
platform_test::TEST_F (CachePerformanceTest , FalseSharingImpact)
Definition at line 60 of file cache_performance_test.cpp.
TEST_F() [14/24]
platform_test::TEST_F (CachePerformanceTest , MemoryAccessPatterns)
Definition at line 204 of file cache_performance_test.cpp.
TEST_F() [15/24]
platform_test::TEST_F (CachePerformanceTest , PrefetchingBehavior)
Definition at line 341 of file cache_performance_test.cpp.
TEST_F() [16/24]
platform_test::TEST_F (PlatformSpecificTest , CompilerAttributes)
Definition at line 393 of file platform_specific_test.cpp.
TEST_F() [17/24]
platform_test::TEST_F (PlatformSpecificTest , DISABLED_CPUAffinityControl)
Definition at line 157 of file platform_specific_test.cpp.
References TEST_F().
TEST_F() [18/24]
platform_test::TEST_F (PlatformSpecificTest , DISABLED_ThreadPriorityControl)
Definition at line 78 of file platform_specific_test.cpp.
References TEST_F().
TEST_F() [19/24]
platform_test::TEST_F (PlatformSpecificTest , EndiannessDetection)
Definition at line 472 of file platform_specific_test.cpp.
TEST_F() [20/24]
platform_test::TEST_F (PlatformSpecificTest , HighResolutionTimer)
Definition at line 213 of file platform_specific_test.cpp.
TEST_F() [21/24]
platform_test::TEST_F (PlatformSpecificTest , MemoryAlignment)
Definition at line 256 of file platform_specific_test.cpp.
TEST_F() [22/24]
platform_test::TEST_F (PlatformSpecificTest , MemoryBarriers)
Definition at line 347 of file platform_specific_test.cpp.
TEST_F() [23/24]
platform_test::TEST_F (PlatformSpecificTest , PlatformAtomics)
Definition at line 425 of file platform_specific_test.cpp.
TEST_F() [24/24]
platform_test::TEST_F (PlatformSpecificTest , ThreadLocalStorage)
Definition at line 306 of file platform_specific_test.cpp.