Messaging System: libraries/logger_system/tests/integration_test.cpp File Reference
integration_test.cpp File Reference
#include <gtest/gtest.h>
#include <kcenon/logger/core/logger.h>
#include <kcenon/logger/writers/console_writer.h>
#include <kcenon/logger/writers/file_writer.h>
#include <kcenon/logger/writers/rotating_file_writer.h>
#include <kcenon/logger/writers/network_writer.h>
#include <kcenon/logger/writers/encrypted_writer.h>
#include <kcenon/logger/structured/structured_logger.h>
#include <kcenon/logger/filters/log_filter.h>
#include <kcenon/logger/routing/log_router.h>
#include <kcenon/logger/server/log_server.h>
#include <kcenon/logger/analysis/log_analyzer.h>
#include <kcenon/logger/security/log_sanitizer.h>
#include <thread>
#include <chrono>
#include <filesystem>
Classes
class IntegrationTest
Functions
TEST_F (IntegrationTest, FullPipelineTest)
TEST_F (IntegrationTest, StructuredLoggingTest)
TEST_F (IntegrationTest, DISABLED_NetworkLoggingTest)
TEST_F (IntegrationTest, SecurityFeaturesTest)
TEST_F (IntegrationTest, AnalysisTest)
TEST_F (IntegrationTest, StressTest)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 388 of file integration_test.cpp.
TEST_F() [1/6]
TEST_F (IntegrationTest , AnalysisTest)
Definition at line 253 of file integration_test.cpp.
TEST_F() [2/6]
TEST_F (IntegrationTest , DISABLED_NetworkLoggingTest)
Definition at line 164 of file integration_test.cpp.
References kcenon::logger::logger::add_writer(), kcenon::logger::logger::flush(), and kcenon::logger::logger::log().
TEST_F() [3/6]
TEST_F (IntegrationTest , FullPipelineTest)
Definition at line 64 of file integration_test.cpp.
References kcenon::logger::logger::add_writer(), kcenon::logger::logger::enable_metrics_collection(), kcenon::logger::logger::flush(), kcenon::logger::logger::get_current_metrics(), kcenon::logger::logger::get_router(), kcenon::logger::logger::log(), kcenon::logger::logger::set_filter(), kcenon::logger::logger::start(), and kcenon::logger::logger::stop().
TEST_F() [4/6]
TEST_F (IntegrationTest , SecurityFeaturesTest)
Definition at line 200 of file integration_test.cpp.
References kcenon::logger::logger::add_writer(), kcenon::logger::logger::flush(), kcenon::logger::encrypted_writer::generate_key(), kcenon::logger::encrypted_writer::load_key(), kcenon::logger::logger::log(), kcenon::logger::encrypted_writer::save_key(), kcenon::logger::logger::start(), and kcenon::logger::logger::stop().
TEST_F() [5/6]
TEST_F (IntegrationTest , StressTest)
Definition at line 306 of file integration_test.cpp.
References kcenon::logger::logger::add_writer(), kcenon::logger::logger::enable_metrics_collection(), kcenon::logger::logger::flush(), kcenon::logger::logger::get_current_metrics(), kcenon::logger::logger::log(), kcenon::logger::logger::start(), and kcenon::logger::logger::stop().
TEST_F() [6/6]
TEST_F (IntegrationTest , StructuredLoggingTest)
Definition at line 125 of file integration_test.cpp.
References kcenon::logger::logger::add_writer(), kcenon::logger::logger::flush(), kcenon::logger::logger::start(), and kcenon::logger::logger::stop().