Messaging System: libraries/monitoring_system/tests/test_thread_context_simple.cpp File Reference
test_thread_context_simple.cpp File Reference
Simple unit tests for thread context and metadata.
#include <gtest/gtest.h>
#include <kcenon/monitoring/context/thread_context.h>
Functions
TEST (ThreadContextSimpleTest, ContextMetadataBasics)
Test context_metadata basic functionality.
TEST (ThreadContextSimpleTest, ContextMetadataEmpty)
Test context_metadata empty functionality.
TEST (ThreadContextSimpleTest, ThreadContextData)
Test thread_context_data structure.
Detailed Description
Simple unit tests for thread context and metadata.
Definition in file test_thread_context_simple.cpp.
Function Documentation
TEST() [1/3]
TEST (ThreadContextSimpleTest , ContextMetadataBasics)
Test context_metadata basic functionality.
Definition at line 21 of file test_thread_context_simple.cpp.
References monitoring_system::context_metadata::correlation_id, monitoring_system::context_metadata::empty(), monitoring_system::context_metadata::get_tag(), monitoring_system::context_metadata::request_id, monitoring_system::context_metadata::set_tag(), and monitoring_system::context_metadata::user_id.
TEST() [2/3]
TEST (ThreadContextSimpleTest , ContextMetadataEmpty)
Test context_metadata empty functionality.
Definition at line 48 of file test_thread_context_simple.cpp.
References monitoring_system::context_metadata::correlation_id, monitoring_system::context_metadata::empty(), monitoring_system::context_metadata::request_id, monitoring_system::context_metadata::set_tag(), monitoring_system::context_metadata::tags, and monitoring_system::context_metadata::user_id.
TEST() [3/3]
TEST (ThreadContextSimpleTest , ThreadContextData)
Test thread_context_data structure.
Definition at line 65 of file test_thread_context_simple.cpp.
References monitoring_system::thread_context_data::correlation_id, monitoring_system::thread_context_data::parent_span_id, monitoring_system::thread_context_data::request_id, monitoring_system::thread_context_data::span_id, monitoring_system::thread_context_data::tags, monitoring_system::thread_context_data::trace_id, and monitoring_system::thread_context_data::user_id.