Messaging System: kcenon::thread::result_void Class Reference
kcenon::thread::result_void Class Reference
Wrapper for void result.
#include <error_handling.h>
Public Member Functions
result_void ()=default
Constructs a successful result.
result_void (const error &err)
Constructs a result with an error.
bool has_error () const
Checks if the result contains an error.
const error & get_error () const
Gets the error.
operator bool () const
Converts to bool for condition checking.
result_void ()=default
Constructs a successful result.
result_void (const error &err)
Constructs a result with an error.
bool has_error () const
Checks if the result contains an error.
const error & get_error () const
Gets the error.
operator bool () const
Converts to bool for condition checking.
Detailed Description
Wrapper for void result.
This class represents a result that doesn't return a value (void), but can indicate success or failure.
Definition at line 194 of file error_handling.h.
Constructor & Destructor Documentation
result_void() [1/4]
kcenon::thread::result_void::result_void () default
Constructs a successful result.
result_void() [2/4]
kcenon::thread::result_void::result_void (const error & err) inline
Constructs a result with an error.
Parameters
err The error
Definition at line 205 of file error_handling.h.
result_void() [3/4]
kcenon::thread::result_void::result_void () default
Constructs a successful result.
result_void() [4/4]
kcenon::thread::result_void::result_void (const error & err) inline
Constructs a result with an error.
Parameters
err The error
Definition at line 205 of file error_handling.h.
Member Function Documentation
get_error() [1/2]
const error & kcenon::thread::result_void::get_error () const inline
Gets the error.
Returns
A reference to the contained error
Definition at line 217 of file error_handling.h.
Referenced by create_default(), and main().
get_error() [2/2]
const error & kcenon::thread::result_void::get_error () const inline
Gets the error.
Returns
A reference to the contained error
Definition at line 217 of file error_handling.h.
has_error() [1/2]
bool kcenon::thread::result_void::has_error () const inline
Checks if the result contains an error.
Returns
true if the result contains an error, false otherwise
Definition at line 211 of file error_handling.h.
Referenced by main(), and kcenon::thread::test::TEST_F().
has_error() [2/2]
bool kcenon::thread::result_void::has_error () const inline
Checks if the result contains an error.
Returns
true if the result contains an error, false otherwise
Definition at line 211 of file error_handling.h.
operator bool() [1/2]
kcenon::thread::result_void::operator bool () const inline explicit
Converts to bool for condition checking.
Returns
true if successful (no error), false otherwise
Definition at line 223 of file error_handling.h.
operator bool() [2/2]
kcenon::thread::result_void::operator bool () const inline explicit
Converts to bool for condition checking.
Returns
true if successful (no error), false otherwise
Definition at line 223 of file error_handling.h.
The documentation for this class was generated from the following files:
libraries/thread_system/core/sync/include/error_handling.h
libraries/thread_system/include/kcenon/thread/core/error_handling.h