Messaging System: monitoring_system::adaptive_collector Class Reference
monitoring_system::adaptive_collector Class Reference
Adaptive collector wrapper.
#include <adaptive_monitor.h>
Public Member Functions
adaptive_collector (std::shared_ptr< monitoring_system::metrics_collector > collector, const adaptive_config &config={})
monitoring_system::result< monitoring_system::metrics_snapshot > collect ()
Collect metrics with adaptive sampling.
void adapt (const monitoring_system::system_metrics &sys_metrics)
Adapt collection behavior based on load.
adaptation_stats get_stats () const
Get current adaptation statistics.
std::chrono::milliseconds get_current_interval () const
Get current collection interval.
void set_config (const adaptive_config &config)
Set adaptive configuration.
adaptive_config get_config () const
Get adaptive configuration.
void set_enabled (bool enabled)
Enable or disable adaptive behavior.
bool is_enabled () const
Check if adaptive behavior is enabled.
Detailed Description
Adaptive collector wrapper.
Definition at line 135 of file adaptive_monitor.h.
Constructor & Destructor Documentation
adaptive_collector()
monitoring_system::adaptive_collector::adaptive_collector (std::shared_ptr< monitoring_system::metrics_collector > collector, const adaptive_config & config = {}) inline
Definition at line 145 of file adaptive_monitor.h.
Member Function Documentation
adapt()
void monitoring_system::adaptive_collector::adapt (const monitoring_system::system_metrics & sys_metrics) inline
Adapt collection behavior based on load.
Definition at line 172 of file adaptive_monitor.h.
References monitoring_system::adaptation_stats::average_cpu_usage, monitoring_system::adaptation_stats::average_memory_usage, monitoring_system::system_metrics::cpu_usage_percent, monitoring_system::adaptation_stats::current_interval, monitoring_system::adaptation_stats::current_load_level, monitoring_system::adaptation_stats::current_sampling_rate, monitoring_system::adaptation_stats::downscale_count, monitoring_system::adaptive_config::get_interval_for_load(), monitoring_system::adaptive_config::get_sampling_rate_for_load(), monitoring_system::adaptation_stats::last_adaptation, monitoring_system::system_metrics::memory_usage_percent, monitoring_system::adaptive_config::smoothing_factor, monitoring_system::adaptation_stats::total_adaptations, and monitoring_system::adaptation_stats::upscale_count.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
collect()
monitoring_system::result< monitoring_system::metrics_snapshot > monitoring_system::adaptive_collector::collect () inline
Collect metrics with adaptive sampling.
Definition at line 156 of file adaptive_monitor.h.
References monitoring_system::operation_cancelled, monitoring_system::adaptation_stats::samples_collected, and monitoring_system::adaptation_stats::samples_dropped.
Referenced by TEST_F(), and TEST_F().
get_config()
adaptive_config monitoring_system::adaptive_collector::get_config () const inline
Get adaptive configuration.
Definition at line 239 of file adaptive_monitor.h.
get_current_interval()
std::chrono::milliseconds monitoring_system::adaptive_collector::get_current_interval () const inline
Get current collection interval.
Definition at line 224 of file adaptive_monitor.h.
References monitoring_system::adaptation_stats::current_interval.
get_stats()
adaptation_stats monitoring_system::adaptive_collector::get_stats () const inline
Get current adaptation statistics.
Definition at line 216 of file adaptive_monitor.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
is_enabled()
bool monitoring_system::adaptive_collector::is_enabled () const inline
Check if adaptive behavior is enabled.
Definition at line 253 of file adaptive_monitor.h.
Referenced by TEST_F().
set_config()
void monitoring_system::adaptive_collector::set_config (const adaptive_config & config) inline
Set adaptive configuration.
Definition at line 232 of file adaptive_monitor.h.
Referenced by TEST_F().
set_enabled()
void monitoring_system::adaptive_collector::set_enabled (bool enabled) inline
Enable or disable adaptive behavior.
Definition at line 246 of file adaptive_monitor.h.
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/src/impl/adaptive_monitor.h