Messaging System: monitoring_system::health_monitor Class Reference
monitoring_system::health_monitor Class Reference
Basic health monitor interface - stub implementation.
#include <health_monitor.h>
Public Member Functions
health_monitor ()=default
health_monitor (const health_monitor_config &config)
virtual ~health_monitor ()=default
virtual health_check_result check_health () const
virtual void start ()
virtual void stop ()
virtual bool is_running () const
virtual void register_check (const std::string &name, std::shared_ptr< functional_health_check > check)
virtual std::unordered_map< std::string, health_check_result > check_all ()
virtual health_status get_overall_status ()
virtual void register_recovery_handler (const std::string &check_name, std::function< bool()> handler)
virtual void refresh ()
virtual std::string get_health_report ()
Detailed Description
Basic health monitor interface - stub implementation.
Definition at line 111 of file health_monitor.h.
Constructor & Destructor Documentation
health_monitor() [1/2]
monitoring_system::health_monitor::health_monitor () default
health_monitor() [2/2]
monitoring_system::health_monitor::health_monitor (const health_monitor_config & config) inline explicit
Definition at line 114 of file health_monitor.h.
~health_monitor()
virtual monitoring_system::health_monitor::~health_monitor () virtual default
Member Function Documentation
check_all()
virtual std::unordered_map< std::string, health_check_result > monitoring_system::health_monitor::check_all () inline virtual
Definition at line 134 of file health_monitor.h.
Referenced by get_health_report(), get_overall_status(), and refresh().
check_health()
virtual health_check_result monitoring_system::health_monitor::check_health () const inline virtual
Definition at line 117 of file health_monitor.h.
References monitoring_system::healthy.
get_health_report()
virtual std::string monitoring_system::health_monitor::get_health_report () inline virtual
Definition at line 177 of file health_monitor.h.
References check_all(), monitoring_system::degraded, monitoring_system::healthy, and monitoring_system::unhealthy.
get_overall_status()
virtual health_status monitoring_system::health_monitor::get_overall_status () inline virtual
Definition at line 142 of file health_monitor.h.
References check_all(), monitoring_system::degraded, monitoring_system::healthy, and monitoring_system::unhealthy.
is_running()
virtual bool monitoring_system::health_monitor::is_running () const inline virtual
Definition at line 127 of file health_monitor.h.
refresh()
virtual void monitoring_system::health_monitor::refresh () inline virtual
Definition at line 164 of file health_monitor.h.
References check_all(), and monitoring_system::unhealthy.
register_check()
virtual void monitoring_system::health_monitor::register_check (const std::string & name, std::shared_ptr< functional_health_check > check) inline virtual
Definition at line 130 of file health_monitor.h.
register_recovery_handler()
virtual void monitoring_system::health_monitor::register_recovery_handler (const std::string & check_name, std::function< bool()> handler) inline virtual
Definition at line 160 of file health_monitor.h.
start()
virtual void monitoring_system::health_monitor::start () inline virtual
Definition at line 125 of file health_monitor.h.
stop()
virtual void monitoring_system::health_monitor::stop () inline virtual
Definition at line 126 of file health_monitor.h.
Referenced by HealthMonitoringTest::SetUp(), and HealthMonitoringTest::TearDown().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/monitoring/health/health_monitor.h