Messaging System: libraries/monitoring_system/tests/test_di_container.cpp File Reference
test_di_container.cpp File Reference
Unit tests for dependency injection container.
#include <gtest/gtest.h>
#include <thread>
#include <atomic>
#include <stdexcept>
#include <memory>
#include <string>
#include <functional>
#include <unordered_map>
#include <typeinfo>
Classes
struct monitoring_system::error_info
Extended error information with context.
class monitoring_system::result< T >
Result type for operations that may fail.
class monitoring_system::service_container_interface
class monitoring_system::service_locator
class IService
Test interfaces and implementations.
class ServiceA
class ServiceB
class DIContainerTest
Test fixture for DI container tests.
Namespaces
namespace monitoring_system
Enumerations
enum class monitoring_system::monitoring_error_code {
monitoring_system::success = 0 , monitoring_system::collector_not_found = 1000 , monitoring_system::collection_failed = 1001 , monitoring_system::collector_initialization_failed = 1002 ,
monitoring_system::collector_already_exists = 1003 , monitoring_system::collector_disabled = 1004 , monitoring_system::invalid_collector_config = 1005 , monitoring_system::monitoring_disabled = 1006 ,
monitoring_system::storage_full = 2000 , monitoring_system::storage_corrupted = 2001 , monitoring_system::compression_failed = 2002 , monitoring_system::storage_not_initialized = 2003 ,
monitoring_system::storage_write_failed = 2004 , monitoring_system::storage_read_failed = 2005 , monitoring_system::storage_empty = 2006 , monitoring_system::invalid_configuration = 3000 ,
monitoring_system::invalid_interval = 3001 , monitoring_system::invalid_capacity = 3002 , monitoring_system::configuration_not_found = 3003 , monitoring_system::configuration_parse_error = 3004 ,
monitoring_system::system_resource_unavailable = 4000 , monitoring_system::permission_denied = 4001 , monitoring_system::out_of_memory = 4002 , monitoring_system::memory_allocation_failed = 4003 ,
monitoring_system::operation_timeout = 4004 , monitoring_system::operation_cancelled = 4005 , monitoring_system::thread_system_not_available = 5000 , monitoring_system::logger_system_not_available = 5001 ,
monitoring_system::incompatible_version = 5002 , monitoring_system::adapter_initialization_failed = 5003 , monitoring_system::metric_not_found = 6000 , monitoring_system::invalid_metric_type = 6001 ,
monitoring_system::metric_overflow = 6002 , monitoring_system::aggregation_failed = 6003 , monitoring_system::processing_failed = 6004 , monitoring_system::health_check_failed = 7000 ,
monitoring_system::health_check_timeout = 7001 , monitoring_system::health_check_not_registered = 7002 , monitoring_system::circuit_breaker_open = 8000 , monitoring_system::circuit_breaker_half_open = 8001 ,
monitoring_system::retry_attempts_exhausted = 8002 , monitoring_system::operation_failed = 8003 , monitoring_system::network_error = 8004 , monitoring_system::service_unavailable = 8005 ,
monitoring_system::service_degraded = 8006 , monitoring_system::error_boundary_triggered = 8007 , monitoring_system::fallback_failed = 8008 , monitoring_system::recovery_failed = 8009 ,
monitoring_system::invalid_argument = 8100 , monitoring_system::invalid_state = 8101 , monitoring_system::not_found = 8102 , monitoring_system::already_exists = 8103 ,
monitoring_system::resource_exhausted = 8104 , monitoring_system::already_started = 8105 , monitoring_system::dependency_missing = 8106 , monitoring_system::quota_exceeded = 8200 ,
monitoring_system::rate_limit_exceeded = 8201 , monitoring_system::cpu_throttled = 8202 , monitoring_system::memory_quota_exceeded = 8203 , monitoring_system::bandwidth_exceeded = 8204 ,
monitoring_system::resource_unavailable = 8205 , monitoring_system::transaction_failed = 8300 , monitoring_system::transaction_timeout = 8301 , monitoring_system::transaction_aborted = 8302 ,
monitoring_system::validation_failed = 8303 , monitoring_system::data_corrupted = 8304 , monitoring_system::state_inconsistent = 8305 , monitoring_system::deadlock_detected = 8306 ,
monitoring_system::rollback_failed = 8307 , monitoring_system::unknown_error = 9999 , monitoring_system::collector_not_found = 1000
}
enum class monitoring_system::service_lifetime { monitoring_system::transient , monitoring_system::singleton , monitoring_system::scoped }
Functions
template<typename T >
result< T > monitoring_system::make_success (T &&value)
std::unique_ptr< service_container_interface > monitoring_system::create_lightweight_container ()
std::unique_ptr< service_container_interface > monitoring_system::create_thread_system_adapter ()
TEST_F (DIContainerTest, RegisterAndResolveTransient)
Test basic service registration and resolution.
TEST_F (DIContainerTest, RegisterAndResolveSingleton)
Test singleton lifetime.
TEST_F (DIContainerTest, RegisterSingletonInstance)
Test direct singleton registration.
TEST_F (DIContainerTest, NamedServiceRegistration)
Test named service registration.
TEST_F (DIContainerTest, DISABLED_ServiceWithDependencies)
Test service with dependencies.
TEST_F (DIContainerTest, DISABLED_ScopedContainer)
Test scoped container.
TEST_F (DIContainerTest, ResolveUnregisteredService)
Test error handling - unregistered service.
TEST_F (DIContainerTest, ResolveUnregisteredNamedService)
Test error handling - unregistered named service.
TEST_F (DIContainerTest, ClearContainer)
Test clear functionality.
TEST_F (DIContainerTest, DISABLED_ThreadSafety)
Test thread safety.
TEST_F (DIContainerTest, ServiceLocator)
Test service locator.
TEST_F (DIContainerTest, ThreadSystemAdapterFactory)
Test factory function for thread_system adapter.
Detailed Description
Unit tests for dependency injection container.
Definition in file test_di_container.cpp.
Function Documentation
TEST_F() [1/12]
TEST_F (DIContainerTest , ClearContainer)
Test clear functionality.
Definition at line 537 of file test_di_container.cpp.
TEST_F() [2/12]
TEST_F (DIContainerTest , DISABLED_ScopedContainer)
Test scoped container.
Definition at line 470 of file test_di_container.cpp.
TEST_F() [3/12]
TEST_F (DIContainerTest , DISABLED_ServiceWithDependencies)
Test service with dependencies.
Definition at line 433 of file test_di_container.cpp.
References monitoring_system::service.
TEST_F() [4/12]
TEST_F (DIContainerTest , DISABLED_ThreadSafety)
Test thread safety.
Definition at line 569 of file test_di_container.cpp.
References ServiceA::get_instance_count(), and monitoring_system::result< T >::value().
TEST_F() [5/12]
TEST_F (DIContainerTest , NamedServiceRegistration)
Test named service registration.
Definition at line 394 of file test_di_container.cpp.
TEST_F() [6/12]
TEST_F (DIContainerTest , RegisterAndResolveSingleton)
Test singleton lifetime.
Definition at line 345 of file test_di_container.cpp.
References ServiceA::get_instance_count().
TEST_F() [7/12]
TEST_F (DIContainerTest , RegisterAndResolveTransient)
Test basic service registration and resolution.
Definition at line 314 of file test_di_container.cpp.
References ServiceA::get_instance_count().
TEST_F() [8/12]
TEST_F (DIContainerTest , RegisterSingletonInstance)
Test direct singleton registration.
Definition at line 374 of file test_di_container.cpp.
TEST_F() [9/12]
TEST_F (DIContainerTest , ResolveUnregisteredNamedService)
Test error handling - unregistered named service.
Definition at line 520 of file test_di_container.cpp.
References monitoring_system::error_info::code, and monitoring_system::result< T >::get_error().
TEST_F() [10/12]
TEST_F (DIContainerTest , ResolveUnregisteredService)
Test error handling - unregistered service.
Definition at line 509 of file test_di_container.cpp.
References monitoring_system::error_info::code, and monitoring_system::result< T >::get_error().
TEST_F() [11/12]
TEST_F (DIContainerTest , ServiceLocator)
Test service locator.
Definition at line 611 of file test_di_container.cpp.
References monitoring_system::container, monitoring_system::create_lightweight_container(), monitoring_system::service_locator::get_container(), monitoring_system::service_locator::has_container(), monitoring_system::service_locator::reset(), and monitoring_system::service_locator::set_container().
TEST_F() [12/12]
TEST_F (DIContainerTest , ThreadSystemAdapterFactory)
Test factory function for thread_system adapter.
Definition at line 645 of file test_di_container.cpp.
References monitoring_system::create_thread_system_adapter().