Messaging System: database::database_manager Class Reference
database::database_manager Class Reference
Manages database connections and operations in a singleton pattern.
#include <database_manager.h>
Public Member Functions
database_manager ()
Default constructor.
virtual ~database_manager ()
Destructor.
bool set_mode (const database_types &database_type)
Sets the database mode (type) for the manager.
database_types database_type (void)
Retrieves the current database type used by the manager.
bool connect (const std::string &connect_string)
Establishes a connection to the database using the currently set mode.
bool create_query (const std::string &query_string)
Creates or prepares a query using the provided SQL statement.
unsigned int insert_query (const std::string &query_string)
Executes an SQL INSERT statement.
unsigned int update_query (const std::string &query_string)
Executes an SQL UPDATE statement.
unsigned int delete_query (const std::string &query_string)
Executes an SQL DELETE statement.
database_result select_query (const std::string &query_string)
Executes an SQL SELECT statement and returns the results.
bool disconnect (void)
Disconnects from the currently active database.
bool create_connection_pool (database_types db_type, const connection_pool_config &config)
Creates a connection pool for the specified database type.
std::shared_ptr< connection_pool_base > get_connection_pool (database_types db_type)
Gets the connection pool for the specified database type.
std::map< database_types, connection_stats > get_pool_stats () const
Gets connection pool statistics for all active pools.
query_builder create_query_builder ()
Creates a query builder for the current database type.
query_builder create_query_builder (database_types db_type)
Creates a query builder for a specific database type.
Static Public Member Functions
static database_manager & handle (void)
Provides access to the single database_manager instance.
Detailed Description
Manages database connections and operations in a singleton pattern.
The database_manager class provides a high-level interface for controlling database connections and executing queries. It wraps a database_base instance and exposes methods such as connect, disconnect, create_query, insert_query, etc. This class also follows the singleton design pattern, allowing only one instance of the manager to exist at a time.
Definition at line 56 of file database_manager.h.
Constructor & Destructor Documentation
database_manager()
database::database_manager::database_manager ()
Default constructor.
Initializes the manager with no active database connection. This constructor is private in many singleton implementations, but can remain public if the design requires it.
Definition at line 43 of file database_manager.cpp.
~database_manager()
database::database_manager::~database_manager () virtual
Destructor.
Cleans up resources and disconnects from the database if an active connection exists.
Definition at line 47 of file database_manager.cpp.
Member Function Documentation
connect()
bool database::database_manager::connect (const std::string & connect_string)
Establishes a connection to the database using the currently set mode.
Parameters
connect_string A string containing connection parameters such as host, port, username, password, and database name.
Returns
true if the connection was established successfully, false otherwise.
Definition at line 97 of file database_manager.cpp.
create_connection_pool()
bool database::database_manager::create_connection_pool (database_types db_type, const connection_pool_config & config)
Creates a connection pool for the specified database type.
Parameters
db_type The database type to create a pool for
config Connection pool configuration parameters
Returns
true if the pool was created successfully, false otherwise
Definition at line 167 of file database_manager.cpp.
References database::connection_pool_manager::create_pool(), and database::connection_pool_manager::instance().
create_query()
bool database::database_manager::create_query (const std::string & query_string)
Creates or prepares a query using the provided SQL statement.
Parameters
query_string The SQL query to be prepared or created.
Returns
true if the query was prepared successfully, false otherwise.
This method may handle prepared statements in some database implementations.
Definition at line 107 of file database_manager.cpp.
create_query_builder() [1/2]
query_builder database::database_manager::create_query_builder ()
Creates a query builder for the current database type.
Returns
A query builder configured for the current database
Definition at line 182 of file database_manager.cpp.
References database_type().
create_query_builder() [2/2]
query_builder database::database_manager::create_query_builder (database_types db_type)
Creates a query builder for a specific database type.
Parameters
db_type The database type to create a builder for
Returns
A query builder configured for the specified database
Definition at line 187 of file database_manager.cpp.
database_type()
database_types database::database_manager::database_type (void)
Retrieves the current database type used by the manager.
Returns
An enum value of database_types representing the current database mode.
Definition at line 87 of file database_manager.cpp.
References database::none.
Referenced by create_query_builder(), and set_mode().
delete_query()
unsigned int database::database_manager::delete_query (const std::string & query_string)
Executes an SQL DELETE statement.
Parameters
query_string The SQL DELETE statement.
Returns
The number of rows deleted, or an implementation-specific value if row counts are not supported.
Definition at line 137 of file database_manager.cpp.
disconnect()
bool database::database_manager::disconnect (void)
Disconnects from the currently active database.
Returns
true if successfully disconnected, false otherwise (e.g., no active connection).
Definition at line 157 of file database_manager.cpp.
get_connection_pool()
std::shared_ptr< connection_pool_base > database::database_manager::get_connection_pool (database_types db_type)
Gets the connection pool for the specified database type.
Parameters
db_type The database type to get a pool for
Returns
Shared pointer to the connection pool, nullptr if not found
Definition at line 172 of file database_manager.cpp.
References database::connection_pool_manager::get_pool(), and database::connection_pool_manager::instance().
get_pool_stats()
std::map< database_types, connection_stats > database::database_manager::get_pool_stats () const
Gets connection pool statistics for all active pools.
Returns
Map of database type to connection statistics
Definition at line 177 of file database_manager.cpp.
References database::connection_pool_manager::get_all_stats(), and database::connection_pool_manager::instance().
handle()
database_manager & database::database_manager::handle (void) static
Provides access to the single database_manager instance.
This static method returns a reference to the singleton instance, ensuring that only one instance of database_manager exists throughout the application.
Returns
A reference to the singleton database_manager instance.
Definition at line 196 of file database_manager.cpp.
Referenced by BM_ConnectionPoolCreation(), BM_ConnectionPoolStats(), BM_DatabaseManagerAccess(), BM_DatabaseTypeSettings(), BM_IntegratedSystemPerformance(), BM_QueryCreation(), BM_SelectQuery(), BM_SQLQueryBuilderCreation(), BM_SQLQueryBuilding(), main(), DatabaseTest::TearDown(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
insert_query()
unsigned int database::database_manager::insert_query (const std::string & query_string)
Executes an SQL INSERT statement.
Parameters
query_string The SQL INSERT statement.
Returns
The number of rows inserted, or an implementation-specific value if row counts are not supported.
Definition at line 117 of file database_manager.cpp.
select_query()
database_result database::database_manager::select_query (const std::string & query_string)
Executes an SQL SELECT statement and returns the results.
Parameters
query_string The SQL SELECT statement.
Returns
A database_result containing rows of data as key-value pairs. Returns empty vector if query fails or returns no results.
Definition at line 147 of file database_manager.cpp.
set_mode()
bool database::database_manager::set_mode (const database_types & database_type)
Sets the database mode (type) for the manager.
Parameters
database_type An enum value of database_types that specifies the target database type (e.g., PostgreSQL, MySQL, SQLite).
Returns
true on success (e.g., if a corresponding database implementation is available), false otherwise.
Definition at line 49 of file database_manager.cpp.
References database_type(), database::mongodb, database::mysql, database::postgres, database::redis, and database::sqlite.
update_query()
unsigned int database::database_manager::update_query (const std::string & query_string)
Executes an SQL UPDATE statement.
Parameters
query_string The SQL UPDATE statement.
Returns
The number of rows updated, or an implementation-specific value if row counts are not supported.
Definition at line 127 of file database_manager.cpp.
The documentation for this class was generated from the following files:
libraries/database_system/database/database_manager.h
libraries/database_system/database/database_manager.cpp