Messaging System: monitoring_system::service_locator Class Reference
monitoring_system::service_locator Class Reference
Static Public Member Functions
static bool has_container ()
static service_container_interface * get_container ()
static void set_container (std::unique_ptr< service_container_interface > container)
static void reset ()
Detailed Description
Definition at line 213 of file test_di_container.cpp.
Member Function Documentation
get_container()
static service_container_interface * monitoring_system::service_locator::get_container () inline static
Definition at line 221 of file test_di_container.cpp.
Referenced by TEST_F().
has_container()
static bool monitoring_system::service_locator::has_container () inline static
Definition at line 217 of file test_di_container.cpp.
Referenced by TEST_F().
reset()
static void monitoring_system::service_locator::reset () inline static
Definition at line 229 of file test_di_container.cpp.
Referenced by TEST_F().
set_container()
static void monitoring_system::service_locator::set_container (std::unique_ptr< service_container_interface > container) inline static
Definition at line 225 of file test_di_container.cpp.
References monitoring_system::container.
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/tests/test_di_container.cpp