Messaging System: kcenon::logger::lightweight_di_container< T > Class Template Reference
kcenon::logger::lightweight_di_container< T > Class Template Reference
Lightweight implementation of DI container.
#include <lightweight_di_container.h>
Public Member Functions
lightweight_di_container ()=default
Default constructor.
~lightweight_di_container () override=default
Destructor.
result< std::shared_ptr< T > > resolve (const std::string &name) override
Resolve a component by name.
result_void register_factory (const std::string &name, std::function< std::shared_ptr< T >()> factory) override
Register a factory function for creating components.
result_void register_singleton (const std::string &name, std::shared_ptr< T > instance) override
Register a singleton instance.
bool is_registered (const std::string &name) const override
Check if a component is registered.
result_void clear () override
Clear all registrations.
size_t size () const override
Get the number of registered components.
template<typename ComponentType >
result_void register_type (const std::string &name)
Register a component type with default constructor.
template<typename ComponentType , typename... Args>
result_void register_type_with_args (const std::string &name, Args... args)
Register a component type with constructor arguments.
Public Member Functions inherited from kcenon::logger::di_container_interface< T >
virtual ~di_container_interface ()=default
Virtual destructor.
Detailed Description
template<typename T>
class kcenon::logger::lightweight_di_container< T >
Lightweight implementation of DI container.
Template Parameters
T The type of objects this container manages
This container provides thread-safe registration and resolution of components using factories and singletons, with no external dependencies.
Definition at line 33 of file lightweight_di_container.h.
Constructor & Destructor Documentation
lightweight_di_container()
template<typename T > kcenon::logger::lightweight_di_container< T >::lightweight_di_container () default
Default constructor.
~lightweight_di_container()
template<typename T > kcenon::logger::lightweight_di_container< T >::~lightweight_di_container () override default
Destructor.
Member Function Documentation
clear()
template<typename T > result_void kcenon::logger::lightweight_di_container< T >::clear () inline override virtual
Clear all registrations.
Returns
Result indicating success or error
Implements kcenon::logger::di_container_interface< T >.
Definition at line 148 of file lightweight_di_container.h.
is_registered()
template<typename T > bool kcenon::logger::lightweight_di_container< T >::is_registered (const std::string & name) const inline override virtual
Check if a component is registered.
Parameters
name The name to check
Returns
true if registered, false otherwise
Implements kcenon::logger::di_container_interface< T >.
Definition at line 138 of file lightweight_di_container.h.
register_factory()
template<typename T > result_void kcenon::logger::lightweight_di_container< T >::register_factory (const std::string & name, std::function< std::shared_ptr< T >()> factory) inline override virtual
Register a factory function for creating components.
Parameters
name The name to register the factory under
factory Function that creates instances of T
Returns
Result indicating success or error
Implements kcenon::logger::di_container_interface< T >.
Definition at line 88 of file lightweight_di_container.h.
References kcenon::logger::invalid_argument, and kcenon::logger::make_logger_error().
Referenced by kcenon::logger::lightweight_di_container< T >::register_type(), and kcenon::logger::lightweight_di_container< T >::register_type_with_args().
register_singleton()
template<typename T > result_void kcenon::logger::lightweight_di_container< T >::register_singleton (const std::string & name, std::shared_ptr< T > instance) inline override virtual
Register a singleton instance.
Parameters
name The name to register the instance under
instance The singleton instance to register
Returns
Result indicating success or error
Implements kcenon::logger::di_container_interface< T >.
Definition at line 114 of file lightweight_di_container.h.
References kcenon::logger::invalid_argument, and kcenon::logger::make_logger_error().
register_type()
template<typename T > template<typename ComponentType > result_void kcenon::logger::lightweight_di_container< T >::register_type (const std::string & name) inline
Register a component type with default constructor.
Convenience method for registering types that have default constructors.
Template Parameters
ComponentType The concrete type to register
Parameters
name The name to register under
Returns
Result indicating success or error
Definition at line 175 of file lightweight_di_container.h.
References kcenon::logger::lightweight_di_container< T >::register_factory().
register_type_with_args()
template<typename T > template<typename ComponentType , typename... Args> result_void kcenon::logger::lightweight_di_container< T >::register_type_with_args (const std::string & name, Args... args) inline
Register a component type with constructor arguments.
Template Parameters
ComponentType The concrete type to register
Args Constructor argument types
Parameters
name The name to register under
args Constructor arguments
Returns
Result indicating success or error
Definition at line 194 of file lightweight_di_container.h.
References kcenon::logger::lightweight_di_container< T >::register_factory().
resolve()
template<typename T > result< std::shared_ptr< T > > kcenon::logger::lightweight_di_container< T >::resolve (const std::string & name) inline override virtual
Resolve a component by name.
First checks singletons, then tries factories if not found.
Parameters
name The registered name of the component
Returns
Result containing the resolved component or error
Implements kcenon::logger::di_container_interface< T >.
Definition at line 58 of file lightweight_di_container.h.
References kcenon::logger::component_not_found, and kcenon::logger::creation_failed.
size()
template<typename T > size_t kcenon::logger::lightweight_di_container< T >::size () const inline override virtual
Get the number of registered components.
Returns
Total number of registered factories and singletons
Implements kcenon::logger::di_container_interface< T >.
Definition at line 160 of file lightweight_di_container.h.
The documentation for this class was generated from the following file:
libraries/logger_system/src/impl/di/lightweight_di_container.h