Messaging System: monitoring_system::event_bus Class Reference
monitoring_system::event_bus Class Reference
Thread-safe event bus implementation.
#include <event_bus.h>
Classes
struct stats
Public Types
using config = event_bus_config
Public Member Functions
event_bus (const config &cfg=config())
~event_bus ()
result_void start () override
Start the event bus.
result_void stop () override
Stop the event bus.
bool is_active () const override
Check if event bus is active.
size_t get_pending_event_count () const override
Get pending event count.
result_void process_pending_events () override
Process all pending events synchronously.
result_void unsubscribe_event (const subscription_token &token) override
Unsubscribe from events using subscription token.
stats get_stats () const
Public Member Functions inherited from monitoring_system::interface_event_bus
virtual ~interface_event_bus ()=default
template<typename EventType >
result_void publish_event (const EventType &event)
Publish an event to all subscribers.
template<typename EventType >
result< subscription_token > subscribe_event (std::function< void(const EventType &)> handler, event_priority priority=event_priority::normal)
Subscribe to events of a specific type.
template<typename EventType >
result_void clear_subscriptions ()
Clear all subscriptions for a specific event type.
template<typename EventType >
size_t get_subscriber_count () const
Get the number of subscribers for an event type.
Protected Member Functions
result_void publish_event_impl (std::type_index event_type, std::any event) override
result< subscription_token > subscribe_event_impl (std::type_index event_type, std::function< void(const std::any &)> handler, uint64_t handler_id, event_priority priority) override
result_void clear_subscriptions_impl (std::type_index event_type) override
size_t get_subscriber_count_impl (std::type_index event_type) const override
Detailed Description
Thread-safe event bus implementation.
Provides high-performance event distribution with:
Priority-based event processing
Back-pressure management
Async and sync processing modes
Type-safe publish/subscribe
Definition at line 101 of file event_bus.h.
Member Typedef Documentation
config
using monitoring_system::event_bus::config = event_bus_config
Definition at line 103 of file event_bus.h.
Constructor & Destructor Documentation
event_bus()
monitoring_system::event_bus::event_bus (const config & cfg = config()) inline explicit
Definition at line 105 of file event_bus.h.
References monitoring_system::event_bus_config::auto_start, and start().
~event_bus()
monitoring_system::event_bus::~event_bus () inline
Definition at line 115 of file event_bus.h.
References stop().
Member Function Documentation
clear_subscriptions_impl()
result_void monitoring_system::event_bus::clear_subscriptions_impl (std::type_index event_type) inline override protected virtual
Implements monitoring_system::interface_event_bus.
Definition at line 289 of file event_bus.h.
get_pending_event_count()
size_t monitoring_system::event_bus::get_pending_event_count () const inline override virtual
Get pending event count.
Returns
Number of events waiting to be processed
Implements monitoring_system::interface_event_bus.
Definition at line 175 of file event_bus.h.
get_stats()
stats monitoring_system::event_bus::get_stats () const inline
Definition at line 219 of file event_bus.h.
References monitoring_system::event_bus_config::back_pressure_threshold.
get_subscriber_count_impl()
size_t monitoring_system::event_bus::get_subscriber_count_impl (std::type_index event_type) const inline override protected virtual
Implements monitoring_system::interface_event_bus.
Definition at line 296 of file event_bus.h.
is_active()
bool monitoring_system::event_bus::is_active () const inline override virtual
Check if event bus is active.
Returns
True if active, false otherwise
Implements monitoring_system::interface_event_bus.
Definition at line 169 of file event_bus.h.
process_pending_events()
result_void monitoring_system::event_bus::process_pending_events () inline override virtual
Process all pending events synchronously.
Returns
Result indicating success or failure
Implements monitoring_system::interface_event_bus.
Definition at line 181 of file event_bus.h.
publish_event_impl()
result_void monitoring_system::event_bus::publish_event_impl (std::type_index event_type, std::any event) inline override protected virtual
Implements monitoring_system::interface_event_bus.
Definition at line 240 of file event_bus.h.
References monitoring_system::event_bus_config::back_pressure_threshold, monitoring_system::event_bus_config::enable_back_pressure, monitoring_system::event_bus_config::max_queue_size, monitoring_system::normal, and monitoring_system::resource_exhausted.
start()
result_void monitoring_system::event_bus::start () inline override virtual
Start the event bus.
Returns
Result indicating success or failure
Implements monitoring_system::interface_event_bus.
Definition at line 120 of file event_bus.h.
References monitoring_system::already_started, and monitoring_system::event_bus_config::worker_thread_count.
Referenced by event_bus().
stop()
result_void monitoring_system::event_bus::stop () inline override virtual
Stop the event bus.
Returns
Result indicating success or failure
Implements monitoring_system::interface_event_bus.
Definition at line 140 of file event_bus.h.
Referenced by ~event_bus().
subscribe_event_impl()
result< subscription_token > monitoring_system::event_bus::subscribe_event_impl (std::type_index event_type, std::function< void(const std::any &)> handler, uint64_t handler_id, event_priority priority) inline override protected virtual
Implements monitoring_system::interface_event_bus.
Definition at line 269 of file event_bus.h.
References monitoring_system::event_handler_wrapper::priority.
unsubscribe_event()
result_void monitoring_system::event_bus::unsubscribe_event (const subscription_token & token) inline override virtual
Unsubscribe from events using subscription token.
Parameters
token The subscription token
Returns
Result indicating success or failure
Implements monitoring_system::interface_event_bus.
Definition at line 187 of file event_bus.h.
References monitoring_system::subscription_token::get_event_type().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/core/event_bus.h