Messaging System: monitoring_system::zipkin_exporter Class Reference
monitoring_system::zipkin_exporter Class Reference
Zipkin trace exporter implementation.
#include <trace_exporters.h>
Public Member Functions
zipkin_exporter (const trace_export_config &config)
zipkin_span_data convert_span (const trace_span &span) const
Convert internal span to Zipkin format.
result_void export_spans (const std::vector< trace_span > &spans) override
Export a batch of spans.
result_void flush () override
Flush any pending spans.
result_void shutdown () override
Shutdown the exporter.
std::unordered_map< std::string, std::size_t > get_stats () const override
Get exporter statistics.
Public Member Functions inherited from monitoring_system::trace_exporter_interface
virtual ~trace_exporter_interface ()=default
Detailed Description
Zipkin trace exporter implementation.
Definition at line 296 of file trace_exporters.h.
Constructor & Destructor Documentation
zipkin_exporter()
monitoring_system::zipkin_exporter::zipkin_exporter (const trace_export_config & config) inline explicit
Definition at line 304 of file trace_exporters.h.
Member Function Documentation
convert_span()
zipkin_span_data monitoring_system::zipkin_exporter::convert_span (const trace_span & span) const inline
Convert internal span to Zipkin format.
Definition at line 310 of file trace_exporters.h.
References monitoring_system::zipkin_span_data::duration, monitoring_system::zipkin_span_data::kind, monitoring_system::zipkin_span_data::local_endpoint_service_name, monitoring_system::zipkin_span_data::name, monitoring_system::zipkin_span_data::parent_id, monitoring_system::trace_export_config::service_name, monitoring_system::zipkin_span_data::span_id, monitoring_system::zipkin_span_data::tags, monitoring_system::zipkin_span_data::timestamp, and monitoring_system::zipkin_span_data::trace_id.
Referenced by export_spans(), and TEST_F().
export_spans()
result_void monitoring_system::zipkin_exporter::export_spans (const std::vector< trace_span > & spans) inline override virtual
Export a batch of spans.
Implements monitoring_system::trace_exporter_interface.
Definition at line 343 of file trace_exporters.h.
References convert_span(), monitoring_system::trace_export_config::format, monitoring_system::invalid_configuration, monitoring_system::operation_failed, monitoring_system::zipkin_json, and monitoring_system::zipkin_protobuf.
Referenced by TEST_F(), and TEST_F().
flush()
result_void monitoring_system::zipkin_exporter::flush () inline override virtual
Flush any pending spans.
Implements monitoring_system::trace_exporter_interface.
Definition at line 379 of file trace_exporters.h.
Referenced by shutdown(), and TEST_F().
get_stats()
std::unordered_map< std::string, std::size_t > monitoring_system::zipkin_exporter::get_stats () const inline override virtual
Get exporter statistics.
Implements monitoring_system::trace_exporter_interface.
Definition at line 388 of file trace_exporters.h.
Referenced by TEST_F().
shutdown()
result_void monitoring_system::zipkin_exporter::shutdown () inline override virtual
Shutdown the exporter.
Implements monitoring_system::trace_exporter_interface.
Definition at line 384 of file trace_exporters.h.
References flush().
Referenced by TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/include/kcenon/monitoring/exporters/trace_exporters.h