Messaging System: distributed_worker Class Reference
distributed_worker Class Reference
Public Member Functions
distributed_worker (const std::string &id="")
void setupProcessors ()
void setupMessageHandlers ()
void handleNewTask (const core::message &task_message)
bool processTask (const task &t)
bool processData (const task &t)
bool analyzeImage (const task &t)
bool generateReport (const task &t)
bool sendEmail (const task &t)
bool warmCache (const task &t)
void handleTaskCancel (const core::message &cancel_message)
void handleRebalance (const core::message &msg)
void respondHealthCheck (const core::message &msg)
void retryTask (task t)
void sendTaskComplete (const task &completed_task)
void sendTaskFailed (const task &failed_task)
void logTaskReceived (const task &received_task)
void updateMetrics (const std::chrono::steady_clock::time_point &start, const std::chrono::steady_clock::time_point &end)
int getUptime () const
std::string generateWorkerId () const
void start ()
void stop ()
void printStatus () const
Detailed Description
Definition at line 58 of file distributed_worker.cpp.
Constructor & Destructor Documentation
distributed_worker()
distributed_worker::distributed_worker (const std::string & id = "") inline
Definition at line 81 of file distributed_worker.cpp.
References kcenon::messaging::config::config_builder::build(), kcenon::messaging::config::config_builder::enable_compression(), kcenon::messaging::config::config_builder::enable_external_monitoring(), kcenon::messaging::config::config_builder::set_container_max_size(), kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), kcenon::messaging::config::config_builder::set_worker_threads(), setupMessageHandlers(), and setupProcessors().
Member Function Documentation
analyzeImage()
bool distributed_worker::analyzeImage (const task & t) inline
Definition at line 225 of file distributed_worker.cpp.
References task::id.
Referenced by setupProcessors().
generateReport()
bool distributed_worker::generateReport (const task & t) inline
Definition at line 235 of file distributed_worker.cpp.
References task::id.
Referenced by setupProcessors().
generateWorkerId()
std::string distributed_worker::generateWorkerId () const inline
Definition at line 351 of file distributed_worker.cpp.
getUptime()
int distributed_worker::getUptime () const inline
Definition at line 344 of file distributed_worker.cpp.
Referenced by printStatus(), and respondHealthCheck().
handleNewTask()
void distributed_worker::handleNewTask (const core::message & task_message) inline
Definition at line 160 of file distributed_worker.cpp.
References task::deserialize(), kcenon::messaging::core::message_payload::get(), logTaskReceived(), kcenon::messaging::core::message::payload, processTask(), retryTask(), sendTaskComplete(), sendTaskFailed(), and updateMetrics().
Referenced by setupMessageHandlers().
handleRebalance()
void distributed_worker::handleRebalance (const core::message & msg) inline
Definition at line 275 of file distributed_worker.cpp.
Referenced by setupMessageHandlers().
handleTaskCancel()
void distributed_worker::handleTaskCancel (const core::message & cancel_message) inline
Definition at line 269 of file distributed_worker.cpp.
References kcenon::messaging::core::message_payload::get(), and kcenon::messaging::core::message::payload.
Referenced by setupMessageHandlers().
logTaskReceived()
void distributed_worker::logTaskReceived (const task & received_task) inline
Definition at line 325 of file distributed_worker.cpp.
References task::id, and task::priority.
Referenced by handleNewTask().
printStatus()
void distributed_worker::printStatus () const inline
Definition at line 399 of file distributed_worker.cpp.
References getUptime().
Referenced by start().
processData()
bool distributed_worker::processData (const task & t) inline
Definition at line 210 of file distributed_worker.cpp.
References task::payload.
Referenced by setupProcessors().
processTask()
bool distributed_worker::processTask (const task & t) inline
Definition at line 195 of file distributed_worker.cpp.
References task::id, and task::type.
Referenced by handleNewTask().
respondHealthCheck()
void distributed_worker::respondHealthCheck (const core::message & msg) inline
Definition at line 280 of file distributed_worker.cpp.
References getUptime().
Referenced by setupMessageHandlers().
retryTask()
void distributed_worker::retryTask (task t) inline
Definition at line 291 of file distributed_worker.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, kcenon::messaging::core::message::payload, task::retry_count, task::serialize(), kcenon::messaging::core::message_payload::set(), and kcenon::messaging::core::message::set_priority().
Referenced by handleNewTask().
sendEmail()
bool distributed_worker::sendEmail (const task & t) inline
Definition at line 247 of file distributed_worker.cpp.
References task::id.
Referenced by setupProcessors().
sendTaskComplete()
void distributed_worker::sendTaskComplete (const task & completed_task) inline
Definition at line 304 of file distributed_worker.cpp.
References task::created_at, kcenon::messaging::core::message_metadata::headers, task::id, and kcenon::messaging::core::message::metadata.
Referenced by handleNewTask().
sendTaskFailed()
void distributed_worker::sendTaskFailed (const task & failed_task) inline
Definition at line 316 of file distributed_worker.cpp.
References kcenon::messaging::core::message_metadata::headers, task::id, and kcenon::messaging::core::message::metadata.
Referenced by handleNewTask().
setupMessageHandlers()
void distributed_worker::setupMessageHandlers () inline
Definition at line 136 of file distributed_worker.cpp.
References handleNewTask(), handleRebalance(), handleTaskCancel(), and respondHealthCheck().
Referenced by distributed_worker().
setupProcessors()
void distributed_worker::setupProcessors () inline
Definition at line 113 of file distributed_worker.cpp.
References analyzeImage(), CACHE_WARMING, DATA_PROCESSING, EMAIL_SENDING, generateReport(), IMAGE_ANALYSIS, processData(), REPORT_GENERATION, sendEmail(), and warmCache().
Referenced by distributed_worker().
start()
void distributed_worker::start () inline
Definition at line 358 of file distributed_worker.cpp.
References kcenon::messaging::core::message_metadata::headers, kcenon::messaging::core::message::metadata, and printStatus().
Referenced by updateMetrics().
stop()
void distributed_worker::stop () inline
Definition at line 390 of file distributed_worker.cpp.
updateMetrics()
void distributed_worker::updateMetrics (const std::chrono::steady_clock::time_point & start, const std::chrono::steady_clock::time_point & end) inline
Definition at line 331 of file distributed_worker.cpp.
References start().
Referenced by handleNewTask().
warmCache()
bool distributed_worker::warmCache (const task & t) inline
Definition at line 256 of file distributed_worker.cpp.
References task::payload.
Referenced by setupProcessors().
The documentation for this class was generated from the following file:
application_layer/samples/distributed_worker.cpp