Messaging System: libraries/thread_system/samples/crash_protection/main.cpp File Reference
main.cpp File Reference
Crash protection demonstration for thread system.
#include <iostream>
#include <thread>
#include <chrono>
#include <random>
#include <vector>
#include <memory>
#include <atomic>
#include "interfaces/crash_handler.h"
#include "thread_pool/thread_pool.h"
Classes
class critical_resource
Functions
void simulate_segmentation_fault ()
void simulate_division_by_zero ()
void simulate_abort ()
void normal_task (int task_id)
void potentially_crashing_task (int task_id)
void on_system_crash (const crash_context &context)
void cleanup_global_resources ()
void emergency_state_save ()
int main ()
Variables
std::atomic< bool > system_running {true}
std::atomic< int > tasks_completed {0}
std::atomic< int > tasks_failed {0}
std::vector< std::shared_ptr< critical_resource > > global_resources
Detailed Description
Crash protection demonstration for thread system.
This example demonstrates comprehensive crash protection mechanisms including signal handling, graceful shutdown, resource cleanup, and automatic recovery capabilities.
Definition in file main.cpp.
Function Documentation
cleanup_global_resources()
void cleanup_global_resources ()
Definition at line 134 of file main.cpp.
References global_resources.
Referenced by main().
emergency_state_save()
void emergency_state_save ()
Definition at line 144 of file main.cpp.
References global_resources, tasks_completed, and tasks_failed.
Referenced by main().
main()
int main ()
Definition at line 151 of file main.cpp.
References cleanup_global_resources(), emergency_state_save(), thread_module::thread_pool_crash_safety::enable_for_pool(), global_resources, thread_module::crash_handler::initialize(), thread_module::crash_handler::instance(), on_system_crash(), thread_module::crash_handler::register_cleanup(), thread_module::crash_handler::register_crash_callback(), thread_module::crash_handler::set_crash_log_directory(), thread_module::thread_pool_crash_safety::set_job_crash_handler(), and thread_module::crash_context::signal_name.
normal_task()
void normal_task (int task_id)
Definition at line 78 of file main.cpp.
References tasks_completed.
on_system_crash()
void on_system_crash (const crash_context & context)
Definition at line 119 of file main.cpp.
References thread_module::crash_context::crash_time, thread_module::crash_context::crashing_thread, thread_module::crash_context::signal_name, thread_module::crash_context::signal_number, thread_module::crash_context::stack_trace, and system_running.
Referenced by main().
potentially_crashing_task()
void potentially_crashing_task (int task_id)
Definition at line 88 of file main.cpp.
References simulate_abort(), simulate_division_by_zero(), simulate_segmentation_fault(), tasks_completed, and tasks_failed.
simulate_abort()
void simulate_abort ()
Definition at line 72 of file main.cpp.
Referenced by potentially_crashing_task().
simulate_division_by_zero()
void simulate_division_by_zero ()
Definition at line 65 of file main.cpp.
Referenced by potentially_crashing_task().
simulate_segmentation_fault()
void simulate_segmentation_fault ()
Definition at line 59 of file main.cpp.
Referenced by potentially_crashing_task().
Variable Documentation
global_resources
std::vector<std::shared_ptr<critical_resource> > global_resources
Definition at line 56 of file main.cpp.
Referenced by cleanup_global_resources(), emergency_state_save(), and main().
system_running
std::atomic<bool> system_running {true}
Definition at line 25 of file main.cpp.
Referenced by on_system_crash(), and task_scheduling_example().
tasks_completed
std::atomic<int> tasks_completed {0}
Definition at line 26 of file main.cpp.
Referenced by emergency_state_save(), normal_task(), and potentially_crashing_task().
tasks_failed
std::atomic<int> tasks_failed {0}
Definition at line 27 of file main.cpp.
Referenced by emergency_state_save(), and potentially_crashing_task().