Messaging System: libraries/logger_system/tests/unit/config_test/config_test.cpp File Reference
config_test.cpp File Reference
#include <gtest/gtest.h>
#include <logger/config/logger_config.h>
#include <logger/config/logger_builder.h>
#include <logger/writers/console_writer.h>
#include <logger/filters/log_filter.h>
Classes
class ConfigTest
Functions
TEST_F (ConfigTest, DefaultConfigValidation)
TEST_F (ConfigTest, InvalidBufferSize)
TEST_F (ConfigTest, InvalidBatchSize)
TEST_F (ConfigTest, InvalidFlushInterval)
TEST_F (ConfigTest, InvalidQueueSettings)
TEST_F (ConfigTest, InvalidFileSettings)
TEST_F (ConfigTest, InvalidNetworkSettings)
TEST_F (ConfigTest, InvalidWriterSettings)
TEST_F (ConfigTest, InvalidThreadCount)
TEST_F (ConfigTest, InvalidFeatureCombinations)
TEST_F (ConfigTest, PredefinedConfigurations)
TEST_F (ConfigTest, LoggerBuilderBasic)
TEST_F (ConfigTest, LoggerBuilderWithWriters)
TEST_F (ConfigTest, LoggerBuilderWithFilters)
TEST_F (ConfigTest, LoggerBuilderTemplates)
TEST_F (ConfigTest, LoggerBuilderInvalidConfig)
TEST_F (ConfigTest, LoggerBuilderFluentInterface)
TEST_F (ConfigTest, ConfigModificationTracking)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 344 of file config_test.cpp.
TEST_F() [1/18]
TEST_F (ConfigTest , ConfigModificationTracking)
Definition at line 325 of file config_test.cpp.
References kcenon::logger::logger_config::buffer_size, and kcenon::logger::logger_config::validate().
TEST_F() [2/18]
TEST_F (ConfigTest , DefaultConfigValidation)
Definition at line 28 of file config_test.cpp.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::buffer_size, kcenon::logger::logger_config::default_config(), kcenon::logger::logger_config::flush_interval, kcenon::logger::logger_config::min_level, kcenon::logger::logger_config::use_lock_free, and kcenon::logger::logger_config::validate().
TEST_F() [3/18]
TEST_F (ConfigTest , InvalidBatchSize)
Definition at line 60 of file config_test.cpp.
References kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::buffer_size, and kcenon::logger::logger_config::validate().
TEST_F() [4/18]
TEST_F (ConfigTest , InvalidBufferSize)
Definition at line 45 of file config_test.cpp.
References kcenon::logger::logger_config::buffer_size, and kcenon::logger::logger_config::validate().
TEST_F() [5/18]
TEST_F (ConfigTest , InvalidFeatureCombinations)
Definition at line 181 of file config_test.cpp.
References kcenon::logger::logger_config::async, kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::queue_overflow_policy, kcenon::logger::logger_config::use_lock_free, and kcenon::logger::logger_config::validate().
TEST_F() [6/18]
TEST_F (ConfigTest , InvalidFileSettings)
Definition at line 107 of file config_test.cpp.
References kcenon::logger::logger_config::max_file_count, kcenon::logger::logger_config::max_file_size, and kcenon::logger::logger_config::validate().
TEST_F() [7/18]
TEST_F (ConfigTest , InvalidFlushInterval)
Definition at line 76 of file config_test.cpp.
References kcenon::logger::logger_config::flush_interval, and kcenon::logger::logger_config::validate().
TEST_F() [8/18]
TEST_F (ConfigTest , InvalidNetworkSettings)
Definition at line 128 of file config_test.cpp.
References kcenon::logger::logger_config::network_retry_count, kcenon::logger::logger_config::network_timeout, kcenon::logger::logger_config::remote_host, kcenon::logger::logger_config::remote_port, and kcenon::logger::logger_config::validate().
TEST_F() [9/18]
TEST_F (ConfigTest , InvalidQueueSettings)
Definition at line 91 of file config_test.cpp.
References kcenon::logger::logger_config::batch_size, kcenon::logger::logger_config::max_queue_size, and kcenon::logger::logger_config::validate().
TEST_F() [10/18]
TEST_F (ConfigTest , InvalidThreadCount)
Definition at line 166 of file config_test.cpp.
References kcenon::logger::logger_config::validate(), and kcenon::logger::logger_config::writer_thread_count.
TEST_F() [11/18]
TEST_F (ConfigTest , InvalidWriterSettings)
Definition at line 151 of file config_test.cpp.
References kcenon::logger::logger_config::max_writers, and kcenon::logger::logger_config::validate().
TEST_F() [12/18]
TEST_F (ConfigTest , LoggerBuilderBasic)
Definition at line 227 of file config_test.cpp.
References kcenon::logger::logger_builder::build(), kcenon::logger::logger_builder::validate(), kcenon::logger::result< T >::value(), kcenon::logger::logger_builder::with_async(), kcenon::logger::logger_builder::with_buffer_size(), kcenon::logger::logger_builder::with_metrics(), and kcenon::logger::logger_builder::with_min_level().
TEST_F() [13/18]
TEST_F (ConfigTest , LoggerBuilderFluentInterface)
Definition at line 310 of file config_test.cpp.
References kcenon::logger::logger_builder::add_writer(), kcenon::logger::logger_builder::build(), kcenon::logger::logger_builder::use_template(), kcenon::logger::result< T >::value(), kcenon::logger::logger_builder::with_buffer_size(), kcenon::logger::logger_builder::with_crash_handler(), kcenon::logger::logger_builder::with_metrics(), and kcenon::logger::logger_builder::with_min_level().
TEST_F() [14/18]
TEST_F (ConfigTest , LoggerBuilderInvalidConfig)
Definition at line 294 of file config_test.cpp.
References kcenon::logger::logger_builder::build(), kcenon::logger::logger_builder::validate(), and kcenon::logger::logger_builder::with_buffer_size().
TEST_F() [15/18]
TEST_F (ConfigTest , LoggerBuilderTemplates)
Definition at line 271 of file config_test.cpp.
References kcenon::logger::logger_builder::build(), kcenon::logger::logger_builder::use_template(), and kcenon::logger::logger_builder::validate().
TEST_F() [16/18]
TEST_F (ConfigTest , LoggerBuilderWithFilters)
Definition at line 259 of file config_test.cpp.
References kcenon::logger::logger_builder::add_filter(), and kcenon::logger::logger_builder::build().
TEST_F() [17/18]
TEST_F (ConfigTest , LoggerBuilderWithWriters)
Definition at line 247 of file config_test.cpp.
References kcenon::logger::logger_builder::add_writer(), and kcenon::logger::logger_builder::build().
TEST_F() [18/18]
TEST_F (ConfigTest , PredefinedConfigurations)
Definition at line 200 of file config_test.cpp.
References kcenon::logger::logger_config::debug_config(), kcenon::logger::logger_config::high_performance(), kcenon::logger::logger_config::low_latency(), and kcenon::logger::logger_config::production().