Messaging System: kcenon::messaging::config::config_builder Class Reference
kcenon::messaging::config::config_builder Class Reference
#include <config.h>
Public Member Functions
config_builder ()=default
config_builder & set_worker_threads (size_t threads)
config_builder & set_queue_size (size_t size)
config_builder & enable_priority_queue (bool enable=true)
config_builder & set_container_max_size (size_t size)
config_builder & enable_compression (bool enable=true)
config_builder & set_network_port (uint16_t port)
config_builder & enable_ssl (bool enable=true)
config_builder & enable_external_logger (bool enable=true)
config_builder & enable_external_monitoring (bool enable=true)
config_builder & enable_external_thread_system (bool enable=true)
config_builder & set_environment (const std::string &env)
config_builder & set_system_name (const std::string &name)
messaging_config build ()
config_builder & load_from_env ()
config_builder & load_from_file (const std::string &filepath)
Detailed Description
Definition at line 58 of file config.h.
Constructor & Destructor Documentation
config_builder()
kcenon::messaging::config::config_builder::config_builder () default
Member Function Documentation
build()
messaging_config kcenon::messaging::config::config_builder::build () inline
Definition at line 139 of file config.h.
Referenced by chat_server::chat_server(), kcenon::messaging::integrations::system_integrator::create_default(), kcenon::messaging::integrations::system_integrator::create_for_environment(), distributed_worker::distributed_worker(), event_pipeline::event_pipeline(), iot_monitoring_system::iot_monitoring_system(), main(), main(), microservices_orchestrator::microservices_orchestrator(), PYBIND11_MODULE(), MessagingIntegrationTest::SetUp(), SystemIntegratorTest::SetUp(), and task_generator::task_generator().
enable_compression()
config_builder & kcenon::messaging::config::config_builder::enable_compression (bool enable = true) inline
Definition at line 85 of file config.h.
References kcenon::messaging::config::messaging_config::container, and kcenon::messaging::services::container::container_config::enable_compression.
Referenced by kcenon::messaging::integrations::system_integrator::create_default(), distributed_worker::distributed_worker(), event_pipeline::event_pipeline(), iot_monitoring_system::iot_monitoring_system(), main(), main(), microservices_orchestrator::microservices_orchestrator(), PYBIND11_MODULE(), MessagingIntegrationTest::SetUp(), and SystemIntegratorTest::SetUp().
enable_external_logger()
config_builder & kcenon::messaging::config::config_builder::enable_external_logger (bool enable = true) inline
Definition at line 101 of file config.h.
References kcenon::messaging::config::messaging_config::enable_logger_system.
Referenced by PYBIND11_MODULE().
enable_external_monitoring()
config_builder & kcenon::messaging::config::config_builder::enable_external_monitoring (bool enable = true) inline
Definition at line 106 of file config.h.
References kcenon::messaging::config::messaging_config::enable_monitoring_system.
Referenced by chat_server::chat_server(), distributed_worker::distributed_worker(), event_pipeline::event_pipeline(), iot_monitoring_system::iot_monitoring_system(), microservices_orchestrator::microservices_orchestrator(), and PYBIND11_MODULE().
enable_external_thread_system()
config_builder & kcenon::messaging::config::config_builder::enable_external_thread_system (bool enable = true) inline
Definition at line 111 of file config.h.
References kcenon::messaging::config::messaging_config::enable_thread_system.
enable_priority_queue()
config_builder & kcenon::messaging::config::config_builder::enable_priority_queue (bool enable = true) inline
Definition at line 74 of file config.h.
References kcenon::messaging::core::message_bus_config::enable_priority_queue, and kcenon::messaging::config::messaging_config::message_bus.
Referenced by PYBIND11_MODULE().
enable_ssl()
config_builder & kcenon::messaging::config::config_builder::enable_ssl (bool enable = true) inline
Definition at line 95 of file config.h.
References kcenon::messaging::services::network::network_config::enable_ssl, and kcenon::messaging::config::messaging_config::network.
load_from_env()
config_builder & kcenon::messaging::config::config_builder::load_from_env ()
load_from_file()
config_builder & kcenon::messaging::config::config_builder::load_from_file (const std::string & filepath)
set_container_max_size()
config_builder & kcenon::messaging::config::config_builder::set_container_max_size (size_t size) inline
Definition at line 80 of file config.h.
References kcenon::messaging::config::messaging_config::container, and kcenon::messaging::services::container::container_config::max_message_size.
Referenced by chat_server::chat_server(), distributed_worker::distributed_worker(), event_pipeline::event_pipeline(), iot_monitoring_system::iot_monitoring_system(), and microservices_orchestrator::microservices_orchestrator().
set_environment()
config_builder & kcenon::messaging::config::config_builder::set_environment (const std::string & env) inline
Definition at line 117 of file config.h.
References kcenon::messaging::config::messaging_config::collection_interval, kcenon::messaging::config::messaging_config::enable, kcenon::messaging::config::messaging_config::environment, kcenon::messaging::config::messaging_config::health_check_interval, kcenon::messaging::config::messaging_config::level, kcenon::messaging::config::messaging_config::logging, kcenon::messaging::config::messaging_config::monitoring, and kcenon::messaging::config::messaging_config::performance.
Referenced by chat_server::chat_server(), kcenon::messaging::integrations::system_integrator::create_default(), kcenon::messaging::integrations::system_integrator::create_for_environment(), distributed_worker::distributed_worker(), event_pipeline::event_pipeline(), iot_monitoring_system::iot_monitoring_system(), main(), main(), microservices_orchestrator::microservices_orchestrator(), PYBIND11_MODULE(), MessagingIntegrationTest::SetUp(), SystemIntegratorTest::SetUp(), and task_generator::task_generator().
set_network_port()
config_builder & kcenon::messaging::config::config_builder::set_network_port (uint16_t port) inline
Definition at line 90 of file config.h.
References kcenon::messaging::services::network::network_config::listen_port, and kcenon::messaging::config::messaging_config::network.
set_queue_size()
config_builder & kcenon::messaging::config::config_builder::set_queue_size (size_t size) inline
Definition at line 69 of file config.h.
References kcenon::messaging::core::message_bus_config::max_queue_size, and kcenon::messaging::config::messaging_config::message_bus.
Referenced by chat_server::chat_server(), kcenon::messaging::integrations::system_integrator::create_default(), distributed_worker::distributed_worker(), event_pipeline::event_pipeline(), iot_monitoring_system::iot_monitoring_system(), main(), main(), microservices_orchestrator::microservices_orchestrator(), PYBIND11_MODULE(), MessagingIntegrationTest::SetUp(), and SystemIntegratorTest::SetUp().
set_system_name()
config_builder & kcenon::messaging::config::config_builder::set_system_name (const std::string & name) inline
Definition at line 133 of file config.h.
References kcenon::messaging::config::messaging_config::system_name.
Referenced by PYBIND11_MODULE().
set_worker_threads()
config_builder & kcenon::messaging::config::config_builder::set_worker_threads (size_t threads) inline
Definition at line 63 of file config.h.
References kcenon::messaging::config::messaging_config::message_bus, kcenon::messaging::config::messaging_config::performance, kcenon::messaging::config::messaging_config::worker_threads, and kcenon::messaging::core::message_bus_config::worker_threads.
Referenced by chat_server::chat_server(), kcenon::messaging::integrations::system_integrator::create_default(), distributed_worker::distributed_worker(), event_pipeline::event_pipeline(), iot_monitoring_system::iot_monitoring_system(), main(), main(), microservices_orchestrator::microservices_orchestrator(), PYBIND11_MODULE(), MessagingIntegrationTest::SetUp(), SystemIntegratorTest::SetUp(), and task_generator::task_generator().
The documentation for this class was generated from the following file:
application_layer/include/kcenon/messaging/core/config.h