Messaging System: libraries/network_system/tests/integration/test_compatibility.cpp File Reference
test_compatibility.cpp File Reference
Enhanced compatibility tests for network_system.
#include <iostream>
#include <cassert>
#include <vector>
#include <string>
#include <memory>
#include <thread>
#include <chrono>
#include "network_system/compatibility.h"
Classes
struct TestResults
Functions
void test_legacy_namespaces (TestResults &results)
void test_type_aliases (TestResults &results)
void test_feature_detection (TestResults &results)
void test_init_shutdown (TestResults &results)
void test_cross_compatibility (TestResults &results)
void test_message_passing (TestResults &results)
void test_legacy_container_integration (TestResults &results)
void test_legacy_thread_integration (TestResults &results)
int main ()
Detailed Description
Enhanced compatibility tests for network_system.
Tests comprehensive compatibility between legacy messaging_system code and the new network_system implementation.
Author
kcenon
Date
2025-09-20
Definition in file test_compatibility.cpp.
Function Documentation
main()
int main ()
Definition at line 375 of file test_compatibility.cpp.
References TestResults::failed, network_system::compat::initialize(), TestResults::print_summary(), network_system::compat::shutdown(), test_cross_compatibility(), test_feature_detection(), test_init_shutdown(), test_legacy_container_integration(), test_legacy_namespaces(), test_legacy_thread_integration(), test_message_passing(), and test_type_aliases().
test_cross_compatibility()
void test_cross_compatibility (TestResults & results)
Definition at line 213 of file test_compatibility.cpp.
References network_module::create_bridge(), network_module::create_server(), TestResults::record_fail(), and TestResults::record_pass().
Referenced by main().
test_feature_detection()
void test_feature_detection (TestResults & results)
Definition at line 135 of file test_compatibility.cpp.
References network_system::compat::has_container_support(), network_system::compat::has_thread_support(), TestResults::record_fail(), and TestResults::record_pass().
Referenced by main().
test_init_shutdown()
void test_init_shutdown (TestResults & results)
Definition at line 177 of file test_compatibility.cpp.
References network_system::compat::initialize(), network_system::integration::container_manager::instance(), network_system::integration::thread_integration_manager::instance(), TestResults::record_fail(), TestResults::record_pass(), and network_system::compat::shutdown().
Referenced by main().
test_legacy_container_integration()
void test_legacy_container_integration (TestResults & results)
Definition at line 283 of file test_compatibility.cpp.
References network_system::integration::container_manager::instance(), TestResults::record_fail(), and TestResults::record_pass().
Referenced by main().
test_legacy_namespaces()
void test_legacy_namespaces (TestResults & results)
Definition at line 57 of file test_compatibility.cpp.
References network_module::create_bridge(), network_module::create_client(), network_module::create_server(), TestResults::record_fail(), and TestResults::record_pass().
Referenced by main().
test_legacy_thread_integration()
void test_legacy_thread_integration (TestResults & results)
Definition at line 330 of file test_compatibility.cpp.
References network_system::integration::thread_integration_manager::instance(), TestResults::record_fail(), and TestResults::record_pass().
Referenced by main().
test_message_passing()
void test_message_passing (TestResults & results)
Definition at line 243 of file test_compatibility.cpp.
References network_module::create_client(), network_module::create_server(), TestResults::record_fail(), and TestResults::record_pass().
Referenced by main().
test_type_aliases()
void test_type_aliases (TestResults & results)
Definition at line 100 of file test_compatibility.cpp.
References TestResults::record_fail(), and TestResults::record_pass().
Referenced by main().