Messaging System: kcenon::logger::file_writer Class Reference
kcenon::logger::file_writer Class Reference
Basic file writer for logging to files.
#include <file_writer.h>
Public Member Functions
file_writer (const std::string &filename, bool append=true, size_t buffer_size=8192)
Constructor.
~file_writer () override
Destructor.
result_void write (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp) override
Write log entry to file.
result_void flush () override
Flush file buffer.
std::string get_name () const override
Get writer name.
bool is_open () const
Check if file is open.
size_t get_file_size () const
Get current file size.
result_void reopen ()
Reopen the file.
Public Member Functions inherited from kcenon::logger::base_writer
virtual ~base_writer ()=default
virtual result_void write (const log_entry &entry) override
Write a log entry using the new interface.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get current color output setting.
virtual bool is_healthy () const override
Check if the writer is healthy and operational.
Public Member Functions inherited from kcenon::logger::log_writer_interface
virtual ~log_writer_interface ()=default
Protected Member Functions
void close ()
Close the current file.
result_void open ()
Open the file.
Protected Member Functions inherited from kcenon::logger::base_writer
std::string format_log_entry (logger_system::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
std::string level_to_string (logger_system::log_level level) const
Convert log level to string representation.
std::string level_to_color (logger_system::log_level level) const
Get ANSI color code for the specified log level.
Protected Attributes
std::string filename_
bool append_mode_
size_t buffer_size_
std::ofstream file_stream_
std::unique_ptr< char[]> buffer_
std::mutex write_mutex_
std::atomic< size_t > bytes_written_ {0}
Detailed Description
Basic file writer for logging to files.
Definition at line 22 of file file_writer.h.
Constructor & Destructor Documentation
file_writer()
kcenon::logger::file_writer::file_writer (const std::string & filename, bool append = true, size_t buffer_size = 8192) explicit
Constructor.
Parameters
filename Path to the log file
append Whether to append to existing file (default: true)
buffer_size Output buffer size in bytes (default: 8192)
Definition at line 15 of file file_writer.cpp.
References open().
~file_writer()
kcenon::logger::file_writer::~file_writer () override
Destructor.
Definition at line 23 of file file_writer.cpp.
References close().
Member Function Documentation
close()
void kcenon::logger::file_writer::close () protected
Close the current file.
Definition at line 74 of file file_writer.cpp.
References file_stream_.
Referenced by kcenon::logger::rotating_file_writer::perform_rotation(), reopen(), and ~file_writer().
flush()
result_void kcenon::logger::file_writer::flush () override virtual
Flush file buffer.
Implements kcenon::logger::base_writer.
Definition at line 56 of file file_writer.cpp.
References file_stream_, kcenon::logger::flush_timeout, kcenon::logger::make_logger_error(), and write_mutex_.
get_file_size()
size_t kcenon::logger::file_writer::get_file_size () const inline
Get current file size.
Definition at line 67 of file file_writer.h.
References bytes_written_.
Referenced by kcenon::logger::rotating_file_writer::should_rotate().
get_name()
std::string kcenon::logger::file_writer::get_name () const inline override virtual
Get writer name.
Implements kcenon::logger::base_writer.
Reimplemented in kcenon::logger::rotating_file_writer.
Definition at line 57 of file file_writer.h.
is_open()
bool kcenon::logger::file_writer::is_open () const inline
Check if file is open.
Definition at line 62 of file file_writer.h.
References file_stream_.
open()
result_void kcenon::logger::file_writer::open () protected
Open the file.
Definition at line 81 of file file_writer.cpp.
References append_mode_, buffer_, buffer_size_, bytes_written_, kcenon::logger::file_open_failed, kcenon::logger::file_permission_denied, file_stream_, filename_, and kcenon::logger::make_logger_error().
Referenced by file_writer(), kcenon::logger::rotating_file_writer::perform_rotation(), and reopen().
reopen()
result_void kcenon::logger::file_writer::reopen ()
Reopen the file.
Definition at line 68 of file file_writer.cpp.
References close(), open(), and write_mutex_.
write()
result_void kcenon::logger::file_writer::write (logger_system::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) override virtual
Write log entry to file.
Implements kcenon::logger::base_writer.
Reimplemented in kcenon::logger::rotating_file_writer.
Definition at line 27 of file file_writer.cpp.
References bytes_written_, file_stream_, kcenon::logger::file_write_failed, kcenon::logger::base_writer::format_log_entry(), kcenon::logger::make_logger_error(), and write_mutex_.
Referenced by kcenon::logger::rotating_file_writer::write().
Member Data Documentation
append_mode_
bool kcenon::logger::file_writer::append_mode_ protected
Definition at line 87 of file file_writer.h.
Referenced by open().
buffer_
std::unique_ptr<char[]> kcenon::logger::file_writer::buffer_ protected
Definition at line 91 of file file_writer.h.
Referenced by open().
buffer_size_
size_t kcenon::logger::file_writer::buffer_size_ protected
Definition at line 88 of file file_writer.h.
Referenced by open().
bytes_written_
std::atomic<size_t> kcenon::logger::file_writer::bytes_written_ {0} protected
Definition at line 94 of file file_writer.h.
Referenced by get_file_size(), open(), and write().
file_stream_
std::ofstream kcenon::logger::file_writer::file_stream_ protected
Definition at line 90 of file file_writer.h.
Referenced by close(), flush(), is_open(), open(), and write().
filename_
std::string kcenon::logger::file_writer::filename_ protected
Definition at line 86 of file file_writer.h.
Referenced by kcenon::logger::rotating_file_writer::generate_rotated_filename(), kcenon::logger::rotating_file_writer::get_backup_files(), open(), and kcenon::logger::rotating_file_writer::perform_rotation().
write_mutex_
std::mutex kcenon::logger::file_writer::write_mutex_ mutable protected
Definition at line 92 of file file_writer.h.
Referenced by flush(), reopen(), kcenon::logger::rotating_file_writer::rotate(), and write().
The documentation for this class was generated from the following files:
libraries/logger_system/include/kcenon/logger/writers/file_writer.h
libraries/logger_system/src/impl/writers/file_writer.cpp