Messaging System: libraries/network_system/tests/integration/test_integration.cpp File Reference
test_integration.cpp File Reference
Integration tests for network_system.
#include <iostream>
#include <cassert>
#include <future>
#include <chrono>
#include "network_system/network_system.h"
#include "network_system/compatibility.h"
Functions
bool test_thread_integration ()
bool test_container_integration ()
bool test_compatibility_api ()
bool test_messaging_bridge ()
int main ()
Detailed Description
Integration tests for network_system.
Tests the integration between various components including thread pool, container system, and messaging bridge.
Author
kcenon
Date
2025-09-20
Definition in file test_integration.cpp.
Function Documentation
main()
int main ()
Definition at line 158 of file test_integration.cpp.
References network_system::compat::initialize(), network_system::compat::shutdown(), test_compatibility_api(), test_container_integration(), test_messaging_bridge(), and test_thread_integration().
test_compatibility_api()
bool test_compatibility_api ()
Definition at line 98 of file test_integration.cpp.
References network_module::create_bridge(), network_module::create_client(), network_module::create_server(), network_system::compat::has_container_support(), and network_system::compat::has_thread_support().
Referenced by main().
test_container_integration()
bool test_container_integration ()
Definition at line 60 of file test_integration.cpp.
References network_system::integration::container_manager::instance().
Referenced by main(), and main().
test_messaging_bridge()
bool test_messaging_bridge ()
Definition at line 126 of file test_integration.cpp.
Referenced by main().
test_thread_integration()
bool test_thread_integration ()
Definition at line 24 of file test_integration.cpp.
References network_system::integration::thread_integration_manager::instance().
Referenced by main().