Messaging System: libraries/monitoring_system/examples/basic_monitoring_example.cpp File Reference
basic_monitoring_example.cpp File Reference
Basic example demonstrating simple monitoring setup.
#include <iostream>
#include <thread>
#include <chrono>
#include "monitoring/interfaces/monitoring_interface.h"
#include "monitoring/performance/performance_monitor.h"
#include "monitoring/storage/storage_backends.h"
#include "monitoring/core/result_types.h"
Functions
int main ()
Detailed Description
Basic example demonstrating simple monitoring setup.
This example shows how to:
Initialize the monitoring system
Collect basic metrics
Store metrics to a file
Query and display metrics
Definition in file basic_monitoring_example.cpp.
Function Documentation
main()
int main ()
Definition at line 24 of file basic_monitoring_example.cpp.
References monitoring_system::performance_monitor::cleanup(), monitoring_system::performance_monitor::collect(), monitoring_system::monitoring_config::collection_interval, monitoring_system::system_metrics::cpu_usage_percent, monitoring_system::monitoring_config::enable_compression, monitoring_system::system_monitor::get_current_metrics(), monitoring_system::result< T >::get_error(), monitoring_system::performance_monitor::get_system_monitor(), monitoring_system::monitoring_config::history_size, monitoring_system::performance_monitor::initialize(), monitoring_system::system_metrics::memory_usage_bytes, monitoring_system::error_info::message, monitoring_system::metric::name, monitoring_system::storage_config::path, monitoring_system::performance_monitor::time_operation(), monitoring_system::timer, and monitoring_system::storage_config::type.