Messaging System: logger_module::base_writer Class Reference
logger_module::base_writer Class Reference abstract
Base class for all log writers.
#include <base_writer.h>
Public Member Functions
virtual ~base_writer ()=default
virtual bool write (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)=0
Write a log entry.
virtual void flush ()=0
Flush any buffered data.
virtual void set_use_color (bool use_color)
Set whether to use color output (if supported)
bool use_color () const
Get color setting.
virtual std::string get_name () const =0
Get writer name.
Protected Member Functions
std::string format_log_entry (thread_module::log_level level, const std::string &message, const std::string &file, int line, const std::string &function, const std::chrono::system_clock::time_point &timestamp)
Format a log entry to string.
std::string level_to_string (thread_module::log_level level) const
Convert log level to string.
std::string level_to_color (thread_module::log_level level) const
Get ANSI color code for log level.
Detailed Description
Base class for all log writers.
Writers are responsible for outputting log messages to various destinations such as console, files, network, etc.
Definition at line 47 of file base_writer.h.
Constructor & Destructor Documentation
~base_writer()
virtual logger_module::base_writer::~base_writer () virtual default
Member Function Documentation
flush()
virtual void logger_module::base_writer::flush () pure virtual
Flush any buffered data.
Implemented in null_writer, null_writer, null_writer, null_writer, null_writer, null_writer, null_writer, logger_module::console_writer, logger_module::encrypted_writer, logger_module::file_writer, logger_module::network_writer, MockCollectorWriter, and MockWriter.
format_log_entry()
std::string logger_module::base_writer::format_log_entry (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) protected
Format a log entry to string.
Parameters
level Log level
message Log message
file Source file
line Source line
function Function name
timestamp Time of log entry
Returns
Formatted log string
Definition at line 118 of file console_writer.cpp.
References level_to_string().
Referenced by logger_module::console_writer::write(), logger_module::encrypted_writer::write(), logger_module::file_writer::write(), and MockWriter::write().
get_name()
virtual std::string logger_module::base_writer::get_name () const pure virtual
Get writer name.
Returns
Name of the writer
Implemented in logger_module::console_writer, logger_module::encrypted_writer, logger_module::file_writer, logger_module::network_writer, logger_module::rotating_file_writer, MockCollectorWriter, and MockWriter.
level_to_color()
std::string logger_module::base_writer::level_to_color (thread_module::log_level level) const protected
Get ANSI color code for log level.
Parameters
level Log level
Returns
ANSI color code or empty string if color disabled
Definition at line 157 of file console_writer.cpp.
References thread_module::critical, thread_module::debug, thread_module::error, thread_module::info, thread_module::trace, use_color(), and thread_module::warning.
Referenced by logger_module::console_writer::write().
level_to_string()
std::string logger_module::base_writer::level_to_string (thread_module::log_level level) const protected
Convert log level to string.
Parameters
level Log level
Returns
String representation
Definition at line 145 of file console_writer.cpp.
References thread_module::critical, thread_module::debug, thread_module::error, thread_module::info, thread_module::trace, and thread_module::warning.
Referenced by format_log_entry().
set_use_color()
virtual void logger_module::base_writer::set_use_color (bool use_color) inline virtual
Set whether to use color output (if supported)
Parameters
use_color Enable/disable color
Definition at line 77 of file base_writer.h.
References use_color().
Referenced by logger_module::console_writer::console_writer().
use_color()
bool logger_module::base_writer::use_color () const inline
Get color setting.
Returns
true if color is enabled
Definition at line 85 of file base_writer.h.
Referenced by level_to_color(), set_use_color(), and logger_module::console_writer::write().
write()
virtual bool logger_module::base_writer::write (thread_module::log_level level, const std::string & message, const std::string & file, int line, const std::string & function, const std::chrono::system_clock::time_point & timestamp) pure virtual
Write a log entry.
Parameters
level Log level
message Log message
file Source file (optional)
line Source line (optional)
function Function name (optional)
timestamp Time of log entry
Returns
true if write was successful
Implemented in MockCollectorWriter, null_writer, null_writer, null_writer, null_writer, null_writer, null_writer, null_writer, logger_module::console_writer, logger_module::encrypted_writer, logger_module::file_writer, logger_module::network_writer, logger_module::rotating_file_writer, and MockWriter.
The documentation for this class was generated from the following files:
libraries/logger_system/sources/logger/writers/base_writer.h
libraries/logger_system/sources/logger/writers/console_writer.cpp