Messaging System: libraries/database_system/samples/run_all_samples.cpp File Reference
run_all_samples.cpp File Reference
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <functional>
#include <memory>
#include <chrono>
#include <iomanip>
Classes
struct sample_info
class sample_runner
Functions
void run_basic_usage_sample ()
BSD 3-Clause License Copyright (c) 2024, Database System Project.
void run_postgres_advanced_sample ()
void run_connection_pool_demo_sample ()
void print_usage (const char *program_name)
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 169 of file run_all_samples.cpp.
References sample_runner::list_available_samples(), print_usage(), sample_runner::run_all_samples(), and sample_runner::run_specific_sample().
print_usage()
void print_usage (const char * program_name)
Definition at line 152 of file run_all_samples.cpp.
Referenced by main().
run_basic_usage_sample()
void run_basic_usage_sample ()
BSD 3-Clause License Copyright (c) 2024, Database System Project.
Definition at line 137 of file run_all_samples.cpp.
run_connection_pool_demo_sample()
void run_connection_pool_demo_sample ()
Definition at line 147 of file run_all_samples.cpp.
run_postgres_advanced_sample()
void run_postgres_advanced_sample ()
Definition at line 142 of file run_all_samples.cpp.