Messaging System: sample_runner Class Reference
sample_runner Class Reference
Public Member Functions
sample_runner ()
void run_all_samples ()
void run_specific_sample (const std::string &sample_name)
void list_available_samples ()
sample_runner ()
void run_all_samples ()
void run_specific_sample (const std::string &sample_name)
void list_available_samples ()
Detailed Description
Definition at line 27 of file run_all_samples.cpp.
Constructor & Destructor Documentation
sample_runner() [1/2]
sample_runner::sample_runner () inline
Definition at line 29 of file run_all_samples.cpp.
sample_runner() [2/2]
sample_runner::sample_runner () inline
Definition at line 29 of file run_all_samples.cpp.
Member Function Documentation
list_available_samples() [1/2]
void sample_runner::list_available_samples () inline
Definition at line 101 of file run_all_samples.cpp.
Referenced by main(), and run_specific_sample().
list_available_samples() [2/2]
void sample_runner::list_available_samples () inline
Definition at line 101 of file run_all_samples.cpp.
run_all_samples() [1/2]
void sample_runner::run_all_samples () inline
Definition at line 33 of file run_all_samples.cpp.
Referenced by main().
run_all_samples() [2/2]
void sample_runner::run_all_samples () inline
Definition at line 33 of file run_all_samples.cpp.
run_specific_sample() [1/2]
void sample_runner::run_specific_sample (const std::string & sample_name) inline
Definition at line 70 of file run_all_samples.cpp.
References list_available_samples().
Referenced by main().
run_specific_sample() [2/2]
void sample_runner::run_specific_sample (const std::string & sample_name) inline
Definition at line 70 of file run_all_samples.cpp.
References list_available_samples().
The documentation for this class was generated from the following files:
libraries/database_system/samples/run_all_samples.cpp
libraries/network_system/samples/run_all_samples.cpp