Messaging System: application_layer/tests/unit/test_system_integrator.cpp File Reference
test_system_integrator.cpp File Reference
#include <gtest/gtest.h>
#include <kcenon/messaging/integrations/system_integrator.h>
#include <kcenon/messaging/core/config.h>
#include <thread>
#include <chrono>
#include <atomic>
Classes
class SystemIntegratorTest
Functions
TEST_F (SystemIntegratorTest, InitializationAndShutdown)
TEST_F (SystemIntegratorTest, ConfigurationAccess)
TEST_F (SystemIntegratorTest, MessageBusAccess)
TEST_F (SystemIntegratorTest, ServiceContainerAccess)
TEST_F (SystemIntegratorTest, PublishSubscribeIntegration)
TEST_F (SystemIntegratorTest, SystemHealthCheck)
TEST_F (SystemIntegratorTest, DefaultSystemCreation)
TEST_F (SystemIntegratorTest, EnvironmentSpecificCreation)
TEST_F (SystemIntegratorTest, ServiceResolution)
TEST_F (SystemIntegratorTest, MultipleInstances)
TEST_F (SystemIntegratorTest, ConcurrentOperations)
Function Documentation
TEST_F() [1/11]
TEST_F (SystemIntegratorTest , ConcurrentOperations)
Definition at line 220 of file test_system_integrator.cpp.
References kcenon::messaging::core::message_payload::data, and kcenon::messaging::core::message_payload::topic.
TEST_F() [2/11]
TEST_F (SystemIntegratorTest , ConfigurationAccess)
Definition at line 46 of file test_system_integrator.cpp.
TEST_F() [3/11]
TEST_F (SystemIntegratorTest , DefaultSystemCreation)
Definition at line 132 of file test_system_integrator.cpp.
References kcenon::messaging::integrations::system_integrator::create_default().
TEST_F() [4/11]
TEST_F (SystemIntegratorTest , EnvironmentSpecificCreation)
Definition at line 147 of file test_system_integrator.cpp.
References kcenon::messaging::integrations::system_integrator::create_for_environment().
TEST_F() [5/11]
TEST_F (SystemIntegratorTest , InitializationAndShutdown)
Definition at line 36 of file test_system_integrator.cpp.
TEST_F() [6/11]
TEST_F (SystemIntegratorTest , MessageBusAccess)
Definition at line 55 of file test_system_integrator.cpp.
References kcenon::messaging::core::message_bus::is_running().
TEST_F() [7/11]
TEST_F (SystemIntegratorTest , MultipleInstances)
Definition at line 179 of file test_system_integrator.cpp.
References kcenon::messaging::core::message_payload::data, and kcenon::messaging::core::message_payload::topic.
TEST_F() [8/11]
TEST_F (SystemIntegratorTest , PublishSubscribeIntegration)
Definition at line 77 of file test_system_integrator.cpp.
References kcenon::messaging::core::message_payload::data, and kcenon::messaging::core::message::payload.
TEST_F() [9/11]
TEST_F (SystemIntegratorTest , ServiceContainerAccess)
Definition at line 63 of file test_system_integrator.cpp.
TEST_F() [10/11]
TEST_F (SystemIntegratorTest , ServiceResolution)
Definition at line 163 of file test_system_integrator.cpp.
TEST_F() [11/11]
TEST_F (SystemIntegratorTest , SystemHealthCheck)
Definition at line 108 of file test_system_integrator.cpp.
References kcenon::messaging::core::message_payload::data, and kcenon::messaging::core::message_payload::topic.