Messaging System: libraries/thread_system/benchmarks/thread_pool_benchmarks/memory_benchmark.cpp File Reference
memory_benchmark.cpp File Reference
Memory usage benchmarks for Thread System.
#include <benchmark/benchmark.h>
#include <iomanip>
#include <thread>
#include <vector>
#include <cstring>
#include <windows.h>
#include <psapi.h>
#include "../../sources/thread_pool/core/thread_pool.h"
#include "../../sources/thread_pool/workers/thread_worker.h"
#include "../../sources/typed_thread_pool/pool/typed_thread_pool.h"
#include "../../sources/utilities/core/formatter.h"
Classes
class MemoryMonitor
struct MemoryMonitor::MemoryStats
Functions
auto create_default (const uint16_t &worker_counts) -> std::tuple< std::shared_ptr< thread_pool_module::thread_pool >, std::optional< std::string > >
template<typename Type >
auto create_priority_default (const uint16_t &worker_counts)
static void BM_BaseMemory (benchmark::State &state)
Benchmark base memory usage.
BENCHMARK (BM_BaseMemory)
static void BM_ThreadPoolMemory (benchmark::State &state)
Benchmark thread pool memory usage.
Arg (1) -> Arg(4) ->Arg(8) ->Arg(16) ->Arg(32) ->Unit(benchmark::kMillisecond)
static void BM_TypedThreadPoolMemory (benchmark::State &state)
Benchmark typed thread pool memory usage.
Arg (4) -> Arg(8) ->Arg(16) ->Unit(benchmark::kMillisecond)
static void BM_JobQueueMemory (benchmark::State &state)
Benchmark job queue memory usage.
Arg (1000) -> Arg(10000) ->Arg(50000) ->Arg(100000) ->Unit(benchmark::kMillisecond)
static void BM_MemoryAllocationPattern (benchmark::State &state)
Benchmark memory allocation patterns.
Args ({1024, 1000}) -> Args({4096, 1000}) ->Args({65536, 100}) ->Args({1048576, 10}) ->Unit(benchmark::kMillisecond)
BENCHMARK_MAIN ()
Detailed Description
Memory usage benchmarks for Thread System.
Definition in file memory_benchmark.cpp.
Function Documentation
Arg() [1/3]
Arg (1) -> Arg(4) ->Arg(8) ->Arg(16) ->Arg(32) ->Unit(benchmark::kMillisecond)
Arg() [2/3]
Arg (1000) -> Arg(10000) ->Arg(50000) ->Arg(100000) ->Unit(benchmark::kMillisecond)
Arg() [3/3]
Arg (4) -> Arg(8) ->Arg(16) ->Unit(benchmark::kMillisecond)
Args()
Args ({1024, 1000}) -> Args({4096, 1000}) ->Args({65536, 100}) ->Args({1048576, 10}) ->Unit(benchmark::kMillisecond)
BENCHMARK()
BENCHMARK (BM_BaseMemory)
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_BaseMemory()
static void BM_BaseMemory (benchmark::State & state) static
Benchmark base memory usage.
Definition at line 158 of file memory_benchmark.cpp.
References MemoryMonitor::get_current_memory().
BM_JobQueueMemory()
static void BM_JobQueueMemory (benchmark::State & state) static
Benchmark job queue memory usage.
Definition at line 250 of file memory_benchmark.cpp.
References create_default(), and MemoryMonitor::get_current_memory().
BM_MemoryAllocationPattern()
static void BM_MemoryAllocationPattern (benchmark::State & state) static
Benchmark memory allocation patterns.
Definition at line 300 of file memory_benchmark.cpp.
References MemoryMonitor::get_current_memory().
BM_ThreadPoolMemory()
static void BM_ThreadPoolMemory (benchmark::State & state) static
Benchmark thread pool memory usage.
Definition at line 174 of file memory_benchmark.cpp.
References create_default(), and MemoryMonitor::get_current_memory().
BM_TypedThreadPoolMemory()
static void BM_TypedThreadPoolMemory (benchmark::State & state) static
Benchmark typed thread pool memory usage.
Definition at line 212 of file memory_benchmark.cpp.
References typed_thread_pool_module::Background, MemoryMonitor::get_current_memory(), Medium, and typed_thread_pool_module::RealTime.
create_default()
auto create_default (const uint16_t & worker_counts) -> std::tuple<std::shared_ptr<thread_pool_module::thread_pool>, std::optional<std::string>>
Definition at line 60 of file memory_benchmark.cpp.
References utility_module::formatter::format().
Referenced by BM_JobQueueMemory(), BM_ThreadPoolMemory(), and create_priority_default().
create_priority_default()
template<typename Type > auto create_priority_default (const uint16_t & worker_counts)
Definition at line 88 of file memory_benchmark.cpp.
References create_default().