Messaging System: database::sql_query_builder Class Reference
database::sql_query_builder Class Reference
Builder for SQL queries (PostgreSQL, MySQL, SQLite).
#include <query_builder.h>
Public Member Functions
sql_query_builder ()
~sql_query_builder ()=default
sql_query_builder & select (const std::vector< std::string > &columns)
sql_query_builder & select (const std::string &column)
sql_query_builder & select_raw (const std::string &raw_select)
sql_query_builder & from (const std::string &table)
sql_query_builder & where (const std::string &field, const std::string &op, const database_value &value)
sql_query_builder & where (const query_condition &condition)
sql_query_builder & where_raw (const std::string &raw_where)
sql_query_builder & or_where (const std::string &field, const std::string &op, const database_value &value)
sql_query_builder & join (const std::string &table, const std::string &condition, join_type type=join_type::inner)
sql_query_builder & left_join (const std::string &table, const std::string &condition)
sql_query_builder & right_join (const std::string &table, const std::string &condition)
sql_query_builder & group_by (const std::vector< std::string > &columns)
sql_query_builder & group_by (const std::string &column)
sql_query_builder & having (const std::string &condition)
sql_query_builder & order_by (const std::string &column, sort_order order=sort_order::asc)
sql_query_builder & order_by_raw (const std::string &raw_order)
sql_query_builder & limit (size_t count)
sql_query_builder & offset (size_t count)
sql_query_builder & insert_into (const std::string &table)
sql_query_builder & values (const std::map< std::string, database_value > &data)
sql_query_builder & values (const std::vector< std::map< std::string, database_value > > &rows)
sql_query_builder & update (const std::string &table)
sql_query_builder & set (const std::string &field, const database_value &value)
sql_query_builder & set (const std::map< std::string, database_value > &data)
sql_query_builder & delete_from (const std::string &table)
std::string build () const
std::string build_for_database (database_types db_type) const
void reset ()
Detailed Description
Builder for SQL queries (PostgreSQL, MySQL, SQLite).
Definition at line 100 of file query_builder.h.
Constructor & Destructor Documentation
sql_query_builder()
database::sql_query_builder::sql_query_builder ()
Definition at line 182 of file query_builder.cpp.
~sql_query_builder()
database::sql_query_builder::~sql_query_builder () default
References select(), and update().
Member Function Documentation
build()
std::string database::sql_query_builder::build () const
Definition at line 353 of file query_builder.cpp.
References build_for_database(), and database::postgres.
build_for_database()
std::string database::sql_query_builder::build_for_database (database_types db_type) const
Definition at line 358 of file query_builder.cpp.
References join().
Referenced by build().
delete_from()
sql_query_builder & database::sql_query_builder::delete_from (const std::string & table)
Definition at line 346 of file query_builder.cpp.
from()
sql_query_builder & database::sql_query_builder::from (const std::string & table)
Definition at line 211 of file query_builder.cpp.
group_by() [1/2]
sql_query_builder & database::sql_query_builder::group_by (const std::string & column)
Definition at line 270 of file query_builder.cpp.
group_by() [2/2]
sql_query_builder & database::sql_query_builder::group_by (const std::vector< std::string > & columns)
Definition at line 264 of file query_builder.cpp.
having()
sql_query_builder & database::sql_query_builder::having (const std::string & condition)
Definition at line 276 of file query_builder.cpp.
insert_into()
sql_query_builder & database::sql_query_builder::insert_into (const std::string & table)
Definition at line 308 of file query_builder.cpp.
join()
sql_query_builder & database::sql_query_builder::join (const std::string & table, const std::string & condition, join_type type = join_type::inner)
Definition at line 246 of file query_builder.cpp.
Referenced by build_for_database(), left_join(), and right_join().
left_join()
sql_query_builder & database::sql_query_builder::left_join (const std::string & table, const std::string & condition)
Definition at line 254 of file query_builder.cpp.
References join(), and database::left.
limit()
sql_query_builder & database::sql_query_builder::limit (size_t count)
Definition at line 296 of file query_builder.cpp.
offset()
sql_query_builder & database::sql_query_builder::offset (size_t count)
Definition at line 302 of file query_builder.cpp.
or_where()
sql_query_builder & database::sql_query_builder::or_where (const std::string & field, const std::string & op, const database_value & value)
Definition at line 235 of file query_builder.cpp.
order_by()
sql_query_builder & database::sql_query_builder::order_by (const std::string & column, sort_order order = sort_order::asc)
Definition at line 282 of file query_builder.cpp.
References database::asc.
order_by_raw()
sql_query_builder & database::sql_query_builder::order_by_raw (const std::string & raw_order)
Definition at line 290 of file query_builder.cpp.
reset()
void database::sql_query_builder::reset ()
Definition at line 488 of file query_builder.cpp.
right_join()
sql_query_builder & database::sql_query_builder::right_join (const std::string & table, const std::string & condition)
Definition at line 259 of file query_builder.cpp.
References join(), and database::right.
select() [1/2]
sql_query_builder & database::sql_query_builder::select (const std::string & column)
Definition at line 196 of file query_builder.cpp.
select() [2/2]
sql_query_builder & database::sql_query_builder::select (const std::vector< std::string > & columns)
Definition at line 189 of file query_builder.cpp.
Referenced by ~sql_query_builder().
select_raw()
sql_query_builder & database::sql_query_builder::select_raw (const std::string & raw_select)
Definition at line 203 of file query_builder.cpp.
set() [1/2]
sql_query_builder & database::sql_query_builder::set (const std::map< std::string, database_value > & data)
Definition at line 340 of file query_builder.cpp.
set() [2/2]
sql_query_builder & database::sql_query_builder::set (const std::string & field, const database_value & value)
Definition at line 334 of file query_builder.cpp.
update()
sql_query_builder & database::sql_query_builder::update (const std::string & table)
Definition at line 327 of file query_builder.cpp.
Referenced by ~sql_query_builder().
values() [1/2]
sql_query_builder & database::sql_query_builder::values (const std::map< std::string, database_value > & data)
Definition at line 315 of file query_builder.cpp.
values() [2/2]
sql_query_builder & database::sql_query_builder::values (const std::vector< std::map< std::string, database_value > > & rows)
Definition at line 321 of file query_builder.cpp.
where() [1/2]
sql_query_builder & database::sql_query_builder::where (const query_condition & condition)
Definition at line 223 of file query_builder.cpp.
where() [2/2]
sql_query_builder & database::sql_query_builder::where (const std::string & field, const std::string & op, const database_value & value)
Definition at line 217 of file query_builder.cpp.
where_raw()
sql_query_builder & database::sql_query_builder::where_raw (const std::string & raw_where)
Definition at line 229 of file query_builder.cpp.
The documentation for this class was generated from the following files:
libraries/database_system/database/query_builder.h
libraries/database_system/database/query_builder.cpp