Messaging System: kcenon::monitoring::core::monitor Class Reference
kcenon::monitoring::core::monitor Class Reference
#include <monitor.h>
Public Member Functions
monitor (std::string name="default")
virtual ~monitor ()=default
void enable ()
void disable ()
bool is_enabled () const
std::shared_ptr< counter > create_counter (const std::string &name, const std::string &description="", const labels &labels={})
std::shared_ptr< gauge > create_gauge (const std::string &name, const std::string &description="", const labels &labels={})
std::shared_ptr< timer > create_timer (const std::string &name, const std::string &description="", const labels &labels={})
std::shared_ptr< metric > get_metric (const std::string &name) const
std::vector< std::shared_ptr< metric > > get_all_metrics () const
void clear ()
std::string name () const
Detailed Description
Definition at line 188 of file monitor.h.
Constructor & Destructor Documentation
monitor()
kcenon::monitoring::core::monitor::monitor (std::string name = "default") inline explicit
Definition at line 196 of file monitor.h.
~monitor()
virtual kcenon::monitoring::core::monitor::~monitor () virtual default
Member Function Documentation
clear()
void kcenon::monitoring::core::monitor::clear () inline
Definition at line 268 of file monitor.h.
create_counter()
std::shared_ptr< counter > kcenon::monitoring::core::monitor::create_counter (const std::string & name, const std::string & description = "", const labels & labels = {}) inline
Definition at line 207 of file monitor.h.
create_gauge()
std::shared_ptr< gauge > kcenon::monitoring::core::monitor::create_gauge (const std::string & name, const std::string & description = "", const labels & labels = {}) inline
Definition at line 220 of file monitor.h.
create_timer()
std::shared_ptr< timer > kcenon::monitoring::core::monitor::create_timer (const std::string & name, const std::string & description = "", const labels & labels = {}) inline
Definition at line 233 of file monitor.h.
disable()
void kcenon::monitoring::core::monitor::disable () inline
Definition at line 203 of file monitor.h.
enable()
void kcenon::monitoring::core::monitor::enable () inline
Definition at line 202 of file monitor.h.
get_all_metrics()
std::vector< std::shared_ptr< metric > > kcenon::monitoring::core::monitor::get_all_metrics () const inline
Definition at line 257 of file monitor.h.
References name().
get_metric()
std::shared_ptr< metric > kcenon::monitoring::core::monitor::get_metric (const std::string & name) const inline
Definition at line 247 of file monitor.h.
References name().
is_enabled()
bool kcenon::monitoring::core::monitor::is_enabled () const inline
Definition at line 204 of file monitor.h.
name()
std::string kcenon::monitoring::core::monitor::name () const inline
Definition at line 274 of file monitor.h.
Referenced by get_all_metrics(), and get_metric().
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/monitoring/core/monitor.h