Messaging System: logger_module::scoped_logger_crash_protection Class Reference
logger_module::scoped_logger_crash_protection Class Reference
RAII helper for automatic logger registration.
#include <logger_crash_safety.h>
Public Member Functions
scoped_logger_crash_protection (const std::string &name, std::function< void()> flush_callback, std::function< void(const std::string &)> backup_callback=nullptr)
~scoped_logger_crash_protection ()
scoped_logger_crash_protection (const scoped_logger_crash_protection &)=delete
scoped_logger_crash_protection & operator= (const scoped_logger_crash_protection &)=delete
scoped_logger_crash_protection (scoped_logger_crash_protection &&)=default
scoped_logger_crash_protection & operator= (scoped_logger_crash_protection &&)=default
Detailed Description
RAII helper for automatic logger registration.
Definition at line 215 of file logger_crash_safety.h.
Constructor & Destructor Documentation
scoped_logger_crash_protection() [1/3]
logger_module::scoped_logger_crash_protection::scoped_logger_crash_protection (const std::string & name, std::function< void()> flush_callback, std::function< void(const std::string &)> backup_callback = nullptr) inline
Definition at line 217 of file logger_crash_safety.h.
References logger_module::logger_crash_safety::instance(), and logger_module::logger_crash_safety::register_logger().
~scoped_logger_crash_protection()
logger_module::scoped_logger_crash_protection::~scoped_logger_crash_protection () inline
Definition at line 224 of file logger_crash_safety.h.
References logger_module::logger_crash_safety::instance(), and logger_module::logger_crash_safety::unregister_logger().
scoped_logger_crash_protection() [2/3]
logger_module::scoped_logger_crash_protection::scoped_logger_crash_protection (const scoped_logger_crash_protection &) delete
scoped_logger_crash_protection() [3/3]
logger_module::scoped_logger_crash_protection::scoped_logger_crash_protection (scoped_logger_crash_protection &&) default
Member Function Documentation
operator=() [1/2]
scoped_logger_crash_protection & logger_module::scoped_logger_crash_protection::operator= (const scoped_logger_crash_protection &) delete
operator=() [2/2]
scoped_logger_crash_protection & logger_module::scoped_logger_crash_protection::operator= (scoped_logger_crash_protection &&) default
The documentation for this class was generated from the following file:
libraries/logger_system/sources/interfaces/logger_crash_safety.h