Messaging System: ServiceA Class Reference
ServiceA Class Reference
Public Member Functions
ServiceA ()
~ServiceA ()
std::string get_name () const override
int get_id () const
Public Member Functions inherited from IService
virtual ~IService ()=default
Static Public Member Functions
static int get_instance_count ()
static void reset_count ()
Detailed Description
Definition at line 251 of file test_di_container.cpp.
Constructor & Destructor Documentation
ServiceA()
ServiceA::ServiceA () inline
Definition at line 257 of file test_di_container.cpp.
~ServiceA()
ServiceA::~ServiceA () inline
Definition at line 258 of file test_di_container.cpp.
Member Function Documentation
get_id()
int ServiceA::get_id () const inline
Definition at line 264 of file test_di_container.cpp.
get_instance_count()
static int ServiceA::get_instance_count () inline static
Definition at line 266 of file test_di_container.cpp.
Referenced by TEST_F(), TEST_F(), and TEST_F().
get_name()
std::string ServiceA::get_name () const inline override virtual
Implements IService.
Definition at line 260 of file test_di_container.cpp.
reset_count()
static void ServiceA::reset_count () inline static
Definition at line 270 of file test_di_container.cpp.
Referenced by DIContainerTest::SetUp().
The documentation for this class was generated from the following file:
libraries/monitoring_system/tests/test_di_container.cpp