Messaging System: thread_module::lockfree_job_queue Class Reference
thread_module::lockfree_job_queue Class Reference
High-performance lock-free Multiple Producer Multiple Consumer job queue.
#include <lockfree_job_queue.h>
Classes
struct atomic_statistics
Internal atomic statistics structure.
struct queue_statistics
Performance statistics structure (non-atomic version for returning)
Public Member Functions
lockfree_job_queue (size_t max_threads=128)
Constructor.
virtual ~lockfree_job_queue ()
Destructor.
lockfree_job_queue (const lockfree_job_queue &)=delete
lockfree_job_queue & operator= (const lockfree_job_queue &)=delete
lockfree_job_queue (lockfree_job_queue &&)=delete
lockfree_job_queue & operator= (lockfree_job_queue &&)=delete
auto enqueue (std::unique_ptr< job > &&value) -> result_void override
Enqueue a single job.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void override
Enqueue multiple jobs as a batch.
auto dequeue () -> result< std::unique_ptr< job > > override
Dequeue a single job.
auto dequeue_batch () -> std::deque< std::unique_ptr< job > > override
Dequeue all available jobs.
auto try_enqueue (std::unique_ptr< job > &&value) -> result_void
Try to enqueue without blocking.
auto try_dequeue () -> result< std::unique_ptr< job > >
Try to dequeue without blocking.
auto clear () -> void override
Clear all jobs from the queue.
auto empty () const -> bool
Check if the queue is empty.
auto size () const -> std::size_t
Get the current size of the queue.
auto get_statistics () const -> queue_statistics
Get performance statistics.
auto reset_statistics () -> void
Reset performance statistics.
auto to_string () const -> std::string override
Get string representation of the queue.
lockfree_job_queue (size_t max_threads=128)
Constructor.
virtual ~lockfree_job_queue ()
Destructor.
lockfree_job_queue (const lockfree_job_queue &)=delete
lockfree_job_queue & operator= (const lockfree_job_queue &)=delete
lockfree_job_queue (lockfree_job_queue &&)=delete
lockfree_job_queue & operator= (lockfree_job_queue &&)=delete
auto enqueue (std::unique_ptr< job > &&value) -> result_void override
Enqueue a single job.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void override
Enqueue multiple jobs as a batch.
auto dequeue () -> result< std::unique_ptr< job > > override
Dequeue a single job.
auto dequeue_batch () -> std::deque< std::unique_ptr< job > > override
Dequeue all available jobs.
auto try_enqueue (std::unique_ptr< job > &&value) -> result_void
Try to enqueue without blocking.
auto try_dequeue () -> result< std::unique_ptr< job > >
Try to dequeue without blocking.
auto clear () -> void override
Clear all jobs from the queue.
auto empty () const -> bool
Check if the queue is empty.
auto size () const -> std::size_t
Get the current size of the queue.
auto get_statistics () const -> queue_statistics
Get performance statistics.
auto reset_statistics () -> void
Reset performance statistics.
auto to_string () const -> std::string override
Get string representation of the queue.
lockfree_job_queue (size_t max_threads=128)
Constructor.
virtual ~lockfree_job_queue ()
Destructor.
lockfree_job_queue (const lockfree_job_queue &)=delete
lockfree_job_queue & operator= (const lockfree_job_queue &)=delete
lockfree_job_queue (lockfree_job_queue &&)=delete
lockfree_job_queue & operator= (lockfree_job_queue &&)=delete
auto enqueue (std::unique_ptr< job > &&value) -> result_void override
Enqueue a single job.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void override
Enqueue multiple jobs as a batch.
auto dequeue () -> result< std::unique_ptr< job > > override
Dequeue a single job.
auto dequeue_batch () -> std::deque< std::unique_ptr< job > > override
Dequeue all available jobs.
auto try_enqueue (std::unique_ptr< job > &&value) -> result_void
Try to enqueue without blocking.
auto try_dequeue () -> result< std::unique_ptr< job > >
Try to dequeue without blocking.
auto clear () -> void override
Clear all jobs from the queue.
auto empty () const -> bool
Check if the queue is empty.
auto size () const -> std::size_t
Get the current size of the queue.
auto get_statistics () const -> queue_statistics
Get performance statistics.
auto reset_statistics () -> void
Reset performance statistics.
auto to_string () const -> std::string override
Get string representation of the queue.
Public Member Functions inherited from thread_module::job_queue
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
Additional Inherited Members
Protected Attributes inherited from thread_module::job_queue
std::atomic_bool notify_
If true, threads waiting for new jobs are notified when a new job is enqueued.
std::atomic_bool stop_
Indicates whether the queue has been signaled to stop.
std::mutex mutex_
Mutex to protect access to the underlying queue_ container and related state.
std::condition_variable condition_
Condition variable used to signal worker threads.
Detailed Description
High-performance lock-free Multiple Producer Multiple Consumer job queue.
This implementation is based on the Michael & Scott algorithm with optimizations for the Thread System including:
Hazard pointers for safe memory reclamation
Node pooling for reduced allocation overhead
Batch operations for improved throughput
Performance statistics collection
Note
This queue is designed to be a drop-in replacement for job_queue with significantly better performance under high contention.
Definition at line 66 of file lockfree_job_queue.h.
Constructor & Destructor Documentation
lockfree_job_queue() [1/9]
thread_module::lockfree_job_queue::lockfree_job_queue (size_t max_threads = 128) explicit
Constructor.
Constructs a lock-free job queue with hazard pointer protection.
Parameters
max_threads Maximum number of threads that will access the queue
Implementation details:
Creates custom node pool for efficient memory management
Initializes hazard pointer manager for thread-safe reclamation
Sets up initial dummy node to simplify queue operations
Configures queue for specified maximum thread count
Dummy Node Purpose:
Eliminates special cases for empty queue handling
Ensures head and tail pointers are never null
Simplifies enqueue/dequeue logic and reduces branches
Memory Initialization:
Node pool pre-allocates nodes for better performance
Hazard pointer slots are reserved for each thread
Initial queue state: head == tail == dummy_node
Parameters
max_threads Maximum number of concurrent threads using the queue
Exceptions
std::runtime_error if initial dummy node allocation fails
Definition at line 94 of file lockfree_job_queue.cpp.
~lockfree_job_queue() [1/3]
thread_module::lockfree_job_queue::~lockfree_job_queue () virtual
Destructor.
Destroys the lock-free job queue and reclaims all resources.
Implementation details:
Drains all remaining jobs from the queue
Deallocates the final dummy node
Hazard pointer manager cleanup is automatic
Node pool cleanup is automatic via RAII
Cleanup Order:
Clear all queued jobs and their nodes
Deallocate the dummy node
Hazard pointer manager destructor runs
Node pool destructor runs
Thread Safety:
Safe to destroy even if other threads might access
Hazard pointers protect against use-after-free
No explicit synchronization required
Definition at line 127 of file lockfree_job_queue.cpp.
References clear().
lockfree_job_queue() [2/9]
thread_module::lockfree_job_queue::lockfree_job_queue (const lockfree_job_queue &) delete
lockfree_job_queue() [3/9]
thread_module::lockfree_job_queue::lockfree_job_queue (lockfree_job_queue &&) delete
lockfree_job_queue() [4/9]
thread_module::lockfree_job_queue::lockfree_job_queue (size_t max_threads = 128) explicit
Constructor.
Parameters
max_threads Maximum number of threads that will access the queue
~lockfree_job_queue() [2/3]
virtual thread_module::lockfree_job_queue::~lockfree_job_queue () virtual
Destructor.
lockfree_job_queue() [5/9]
thread_module::lockfree_job_queue::lockfree_job_queue (const lockfree_job_queue &) delete
lockfree_job_queue() [6/9]
thread_module::lockfree_job_queue::lockfree_job_queue (lockfree_job_queue &&) delete
lockfree_job_queue() [7/9]
thread_module::lockfree_job_queue::lockfree_job_queue (size_t max_threads = 128) explicit
Constructor.
Parameters
max_threads Maximum number of threads that will access the queue
~lockfree_job_queue() [3/3]
virtual thread_module::lockfree_job_queue::~lockfree_job_queue () virtual
Destructor.
lockfree_job_queue() [8/9]
thread_module::lockfree_job_queue::lockfree_job_queue (const lockfree_job_queue &) delete
lockfree_job_queue() [9/9]
thread_module::lockfree_job_queue::lockfree_job_queue (lockfree_job_queue &&) delete
Member Function Documentation
clear() [1/3]
auto thread_module::lockfree_job_queue::clear (void) -> void override virtual
Clear all jobs from the queue.
Reimplemented from thread_module::job_queue.
Definition at line 354 of file lockfree_job_queue.cpp.
References thread_module::result< T >::has_value().
Referenced by ~lockfree_job_queue().
clear() [2/3]
auto thread_module::lockfree_job_queue::clear () -> void override virtual
Clear all jobs from the queue.
Reimplemented from thread_module::job_queue.
clear() [3/3]
auto thread_module::lockfree_job_queue::clear () -> void override virtual
Clear all jobs from the queue.
Reimplemented from thread_module::job_queue.
dequeue() [1/3]
auto thread_module::lockfree_job_queue::dequeue (void) -> result<std::unique_ptr<job>> override virtual
Dequeue a single job.
Returns
The dequeued job or error
Reimplemented from thread_module::job_queue.
Definition at line 303 of file lockfree_job_queue.cpp.
References thread_module::result< T >::has_value(), and thread_module::queue_stopped.
Referenced by basic_spsc_example(), mpmc_example(), performance_example(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
dequeue() [2/3]
auto thread_module::lockfree_job_queue::dequeue () -> result< std::unique_ptr< job > > override virtual
Dequeue a single job.
Returns
The dequeued job or error
Reimplemented from thread_module::job_queue.
dequeue() [3/3]
auto thread_module::lockfree_job_queue::dequeue () -> result< std::unique_ptr< job > > override virtual
Dequeue a single job.
Returns
The dequeued job or error
Reimplemented from thread_module::job_queue.
dequeue_batch() [1/3]
auto thread_module::lockfree_job_queue::dequeue_batch (void) -> std::deque<std::unique_ptr<job>> override virtual
Dequeue all available jobs.
Returns
Deque containing all dequeued jobs
Reimplemented from thread_module::job_queue.
Definition at line 323 of file lockfree_job_queue.cpp.
Referenced by batch_operations_example(), and TEST_F().
dequeue_batch() [2/3]
auto thread_module::lockfree_job_queue::dequeue_batch () -> std::deque< std::unique_ptr< job > > override virtual
Dequeue all available jobs.
Returns
Deque containing all dequeued jobs
Reimplemented from thread_module::job_queue.
dequeue_batch() [3/3]
auto thread_module::lockfree_job_queue::dequeue_batch () -> std::deque< std::unique_ptr< job > > override virtual
Dequeue all available jobs.
Returns
Deque containing all dequeued jobs
Reimplemented from thread_module::job_queue.
empty() [1/3]
auto thread_module::lockfree_job_queue::empty (void) const -> bool
Check if the queue is empty.
Returns
true if empty, false otherwise
Definition at line 368 of file lockfree_job_queue.cpp.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
empty() [2/3]
auto thread_module::lockfree_job_queue::empty () const -> bool
Check if the queue is empty.
Returns
true if empty, false otherwise
empty() [3/3]
auto thread_module::lockfree_job_queue::empty () const -> bool
Check if the queue is empty.
Returns
true if empty, false otherwise
enqueue() [1/3]
auto thread_module::lockfree_job_queue::enqueue (std::unique_ptr< job > && value) -> result_void override virtual
Enqueue a single job.
Adds a job to the queue in a lock-free manner.
Parameters
value The job to enqueue
Returns
Success or error result
Implementation details:
Validates job pointer and queue state before processing
Allocates wrapper storage for the job pointer
Uses lock-free Michael & Scott enqueue algorithm
Records timing metrics for performance monitoring
Handles exceptions gracefully with proper cleanup
Lock-free Algorithm:
Allocate new node and prepare job data
Loop: Read current tail pointer with hazard protection
Attempt to link new node to tail's next pointer
If successful, advance tail pointer to new node
Retry if concurrent modification detected
Error Conditions:
Null job pointer: Invalid argument error
Queue stopped: Operation not permitted
Memory allocation failure: Handled via exception
Concurrent modification: Automatic retry
Performance Characteristics:
O(1) expected time complexity
Wait-free progress guarantee
Scales with concurrent producers
Minimal cache line bouncing
Parameters
value Unique pointer to job being enqueued
Returns
result_void indicating success or detailed error
Reimplemented from thread_module::job_queue.
Definition at line 171 of file lockfree_job_queue.cpp.
References thread_module::invalid_argument, thread_module::queue_stopped, and thread_module::unknown_error.
Referenced by basic_spsc_example(), BM_LockFreeQueue_SPSC(), mpmc_example(), performance_example(), TEST(), TEST(), TEST(), TEST(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
enqueue() [2/3]
auto thread_module::lockfree_job_queue::enqueue (std::unique_ptr< job > && value) -> result_void override virtual
Enqueue a single job.
Parameters
value The job to enqueue
Returns
Success or error result
Reimplemented from thread_module::job_queue.
enqueue() [3/3]
auto thread_module::lockfree_job_queue::enqueue (std::unique_ptr< job > && value) -> result_void override virtual
Enqueue a single job.
Parameters
value The job to enqueue
Returns
Success or error result
Reimplemented from thread_module::job_queue.
enqueue_batch() [1/3]
auto thread_module::lockfree_job_queue::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void override virtual
Enqueue multiple jobs as a batch.
Parameters
jobs Vector of jobs to enqueue
Returns
Success or error result
Reimplemented from thread_module::job_queue.
Definition at line 201 of file lockfree_job_queue.cpp.
References thread_module::invalid_argument, thread_module::queue_stopped, and thread_module::unknown_error.
Referenced by batch_operations_example(), and TEST_F().
enqueue_batch() [2/3]
auto thread_module::lockfree_job_queue::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void override virtual
Enqueue multiple jobs as a batch.
Parameters
jobs Vector of jobs to enqueue
Returns
Success or error result
Reimplemented from thread_module::job_queue.
enqueue_batch() [3/3]
auto thread_module::lockfree_job_queue::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void override virtual
Enqueue multiple jobs as a batch.
Parameters
jobs Vector of jobs to enqueue
Returns
Success or error result
Reimplemented from thread_module::job_queue.
get_statistics() [1/3]
auto thread_module::lockfree_job_queue::get_statistics () const -> queue_statistics
Get performance statistics.
Returns
Current statistics
Definition at line 380 of file lockfree_job_queue.cpp.
References thread_module::lockfree_job_queue::queue_statistics::current_size, thread_module::lockfree_job_queue::atomic_statistics::current_size, thread_module::lockfree_job_queue::queue_statistics::dequeue_batch_count, thread_module::lockfree_job_queue::atomic_statistics::dequeue_batch_count, thread_module::lockfree_job_queue::queue_statistics::dequeue_count, thread_module::lockfree_job_queue::atomic_statistics::dequeue_count, thread_module::lockfree_job_queue::queue_statistics::enqueue_batch_count, thread_module::lockfree_job_queue::atomic_statistics::enqueue_batch_count, thread_module::lockfree_job_queue::queue_statistics::enqueue_count, thread_module::lockfree_job_queue::atomic_statistics::enqueue_count, thread_module::lockfree_job_queue::queue_statistics::retry_count, thread_module::lockfree_job_queue::atomic_statistics::retry_count, thread_module::lockfree_job_queue::queue_statistics::total_dequeue_time, thread_module::lockfree_job_queue::atomic_statistics::total_dequeue_time, thread_module::lockfree_job_queue::queue_statistics::total_enqueue_time, and thread_module::lockfree_job_queue::atomic_statistics::total_enqueue_time.
Referenced by performance_example(), TEST_F(), TEST_F(), and to_string().
get_statistics() [2/3]
auto thread_module::lockfree_job_queue::get_statistics () const -> queue_statistics
Get performance statistics.
Returns
Current statistics
get_statistics() [3/3]
auto thread_module::lockfree_job_queue::get_statistics () const -> queue_statistics
Get performance statistics.
Returns
Current statistics
operator=() [1/6]
lockfree_job_queue & thread_module::lockfree_job_queue::operator= (const lockfree_job_queue &) delete
operator=() [2/6]
lockfree_job_queue & thread_module::lockfree_job_queue::operator= (const lockfree_job_queue &) delete
operator=() [3/6]
lockfree_job_queue & thread_module::lockfree_job_queue::operator= (const lockfree_job_queue &) delete
operator=() [4/6]
lockfree_job_queue & thread_module::lockfree_job_queue::operator= (lockfree_job_queue &&) delete
operator=() [5/6]
lockfree_job_queue & thread_module::lockfree_job_queue::operator= (lockfree_job_queue &&) delete
operator=() [6/6]
lockfree_job_queue & thread_module::lockfree_job_queue::operator= (lockfree_job_queue &&) delete
reset_statistics() [1/3]
auto thread_module::lockfree_job_queue::reset_statistics () -> void
Reset performance statistics.
Definition at line 394 of file lockfree_job_queue.cpp.
References thread_module::lockfree_job_queue::queue_statistics::enqueue_count.
reset_statistics() [2/3]
auto thread_module::lockfree_job_queue::reset_statistics () -> void
Reset performance statistics.
reset_statistics() [3/3]
auto thread_module::lockfree_job_queue::reset_statistics () -> void
Reset performance statistics.
size() [1/3]
auto thread_module::lockfree_job_queue::size (void) const -> std::size_t
Get the current size of the queue.
Returns
Number of jobs in the queue
Definition at line 375 of file lockfree_job_queue.cpp.
References thread_module::lockfree_job_queue::atomic_statistics::current_size.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
size() [2/3]
auto thread_module::lockfree_job_queue::size () const -> std::size_t
Get the current size of the queue.
Returns
Number of jobs in the queue
size() [3/3]
auto thread_module::lockfree_job_queue::size () const -> std::size_t
Get the current size of the queue.
Returns
Number of jobs in the queue
to_string() [1/3]
auto thread_module::lockfree_job_queue::to_string (void) const -> std::string override virtual
Get string representation of the queue.
Returns
String describing the queue state
Reimplemented from thread_module::job_queue.
Definition at line 405 of file lockfree_job_queue.cpp.
References utility_module::formatter::format(), and get_statistics().
to_string() [2/3]
auto thread_module::lockfree_job_queue::to_string () const -> std::string override virtual
Get string representation of the queue.
Returns
String describing the queue state
Reimplemented from thread_module::job_queue.
to_string() [3/3]
auto thread_module::lockfree_job_queue::to_string () const -> std::string override virtual
Get string representation of the queue.
Returns
String describing the queue state
Reimplemented from thread_module::job_queue.
try_dequeue() [1/3]
auto thread_module::lockfree_job_queue::try_dequeue () -> result<std::unique_ptr<job>>
Try to dequeue without blocking.
Returns
The dequeued job or error
Definition at line 349 of file lockfree_job_queue.cpp.
try_dequeue() [2/3]
auto thread_module::lockfree_job_queue::try_dequeue () -> result< std::unique_ptr< job > >
Try to dequeue without blocking.
Returns
The dequeued job or error
try_dequeue() [3/3]
auto thread_module::lockfree_job_queue::try_dequeue () -> result< std::unique_ptr< job > >
Try to dequeue without blocking.
Returns
The dequeued job or error
try_enqueue() [1/3]
auto thread_module::lockfree_job_queue::try_enqueue (std::unique_ptr< job > && value) -> result_void
Try to enqueue without blocking.
Parameters
value The job to enqueue
Returns
Success or error result
Definition at line 344 of file lockfree_job_queue.cpp.
try_enqueue() [2/3]
auto thread_module::lockfree_job_queue::try_enqueue (std::unique_ptr< job > && value) -> result_void
Try to enqueue without blocking.
Parameters
value The job to enqueue
Returns
Success or error result
try_enqueue() [3/3]
auto thread_module::lockfree_job_queue::try_enqueue (std::unique_ptr< job > && value) -> result_void
Try to enqueue without blocking.
Parameters
value The job to enqueue
Returns
Success or error result
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/thread_base/lockfree/queues/lockfree_job_queue.h
libraries/thread_system/modular_structure/core/src/thread_base/lockfree/queues/lockfree_job_queue.h
libraries/thread_system/sources/thread_base/lockfree/queues/lockfree_job_queue.h
libraries/thread_system/modular_structure/core/src/thread_base/lockfree/queues/lockfree_job_queue.cpp
libraries/thread_system/sources/thread_base/lockfree/queues/lockfree_job_queue.cpp