Messaging System: libraries/network_system/samples/messaging_system_integration/modern_usage.cpp File Reference
modern_usage.cpp File Reference
Example of using network_system with modern API.
#include <iostream>
#include <memory>
#include <thread>
#include <chrono>
#include <vector>
#include <future>
#include "network_system/network_system.h"
Classes
class ModernServer
Modern server using new API.
class ModernClient
Modern client using new API.
Functions
void demonstrate_advanced_features ()
Demonstrate advanced features.
int main (int argc, char *argv[])
Main function demonstrating modern usage.
Detailed Description
Example of using network_system with modern API.
This example shows how to use the new network_system API directly with all modern features including integration interfaces.
Author
kcenon
Date
2025-09-20
Definition in file modern_usage.cpp.
Function Documentation
demonstrate_advanced_features()
void demonstrate_advanced_features ()
Demonstrate advanced features.
Definition at line 167 of file modern_usage.cpp.
Referenced by main().
main()
int main (int argc, char * argv[])
Main function demonstrating modern usage.
Definition at line 224 of file modern_usage.cpp.
References demonstrate_advanced_features(), network_system::compat::initialize(), and network_system::compat::shutdown().