Messaging System: monitoring_module::alert_system_crash_safety Class Reference
monitoring_module::alert_system_crash_safety Class Reference
Alert system crash safety.
#include <monitoring_crash_safety.h>
Static Public Member Functions
static void configure_alert_safety (const std::string &alert_system_name, bool immediate_alert_on_crash=true, bool persistent_alert_queue=true)
Configure crash safety for alert system.
static void set_crash_alert_handler (std::function< void(const std::string &crash_info)> handler)
Set crash alert handler.
static void preserve_pending_alerts (const std::vector< std::string > &alerts)
Preserve pending alerts before crash.
static std::vector< std::string > restore_preserved_alerts ()
Restore preserved alerts after recovery.
Detailed Description
Alert system crash safety.
Definition at line 290 of file monitoring_crash_safety.h.
Member Function Documentation
configure_alert_safety()
static void monitoring_module::alert_system_crash_safety::configure_alert_safety (const std::string & alert_system_name, bool immediate_alert_on_crash = true, bool persistent_alert_queue = true) static
Configure crash safety for alert system.
Parameters
alert_system_name Name of the alert system
immediate_alert_on_crash Whether to send immediate crash alert
persistent_alert_queue Whether to persist pending alerts
Referenced by main().
preserve_pending_alerts()
static void monitoring_module::alert_system_crash_safety::preserve_pending_alerts (const std::vector< std::string > & alerts) static
Preserve pending alerts before crash.
Parameters
alerts Vector of pending alert messages
Referenced by main().
restore_preserved_alerts()
static std::vector< std::string > monitoring_module::alert_system_crash_safety::restore_preserved_alerts () static
Restore preserved alerts after recovery.
Returns
Vector of restored alert messages
Referenced by main().
set_crash_alert_handler()
static void monitoring_module::alert_system_crash_safety::set_crash_alert_handler (std::function< void(const std::string &crash_info)> handler) static
Set crash alert handler.
Parameters
handler Function to handle crash alerts
Referenced by main().
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/interfaces/monitoring_crash_safety.h