Messaging System: sample_monitoring Class Reference
sample_monitoring Class Reference
Public Member Functions
void update_system_metrics (const ::monitoring_interface::system_metrics &metrics) override
void update_thread_pool_metrics (const ::monitoring_interface::thread_pool_metrics &metrics) override
void update_worker_metrics (std::size_t worker_id, const ::monitoring_interface::worker_metrics &metrics) override
::monitoring_interface::metrics_snapshot get_current_snapshot () const override
Retrieves the most recent metrics snapshot.
std::vector<::monitoring_interface::metrics_snapshot > get_recent_snapshots (std::size_t) const override
Retrieves multiple recent metrics snapshots.
bool is_active () const override
Checks if monitoring is currently active.
Public Member Functions inherited from monitoring_interface::monitoring_interface
virtual ~monitoring_interface ()=default
virtual void update_system_metrics (const system_metrics &metrics)=0
Updates system metrics.
virtual void update_thread_pool_metrics (const thread_pool_metrics &metrics)=0
Updates thread pool metrics.
virtual void update_worker_metrics (std::size_t worker_id, const worker_metrics &metrics)=0
Updates worker thread metrics.
virtual ~monitoring_interface ()=default
virtual void update_system_metrics (const system_metrics &metrics)=0
Updates system metrics.
virtual void update_thread_pool_metrics (const thread_pool_metrics &metrics)=0
Updates thread pool metrics.
virtual void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const thread_pool_metrics &metrics)
Updates thread pool metrics with pool identifier (for multi-pool scenarios).
virtual void update_worker_metrics (std::size_t worker_id, const worker_metrics &metrics)=0
Updates worker thread metrics.
virtual ~monitoring_interface ()=default
virtual void update_system_metrics (const system_metrics &metrics)=0
Updates system metrics.
virtual void update_thread_pool_metrics (const thread_pool_metrics &metrics)=0
Updates thread pool metrics.
virtual void update_thread_pool_metrics (const std::string &pool_name, std::uint32_t pool_instance_id, const thread_pool_metrics &metrics)
Updates thread pool metrics with pool identifier (for multi-pool scenarios).
virtual void update_worker_metrics (std::size_t worker_id, const worker_metrics &metrics)=0
Updates worker thread metrics.
Detailed Description
Definition at line 36 of file multi_process_monitoring_integration.cpp.
Member Function Documentation
get_current_snapshot()
::monitoring_interface::metrics_snapshot sample_monitoring::get_current_snapshot () const inline override virtual
Retrieves the most recent metrics snapshot.
Returns
Current metrics snapshot
Implements monitoring_interface::monitoring_interface.
Definition at line 54 of file multi_process_monitoring_integration.cpp.
get_recent_snapshots()
std::vector<::monitoring_interface::metrics_snapshot > sample_monitoring::get_recent_snapshots (std::size_t count) const inline override virtual
Retrieves multiple recent metrics snapshots.
Parameters
count Number of snapshots to retrieve
Returns
Vector of metrics snapshots, newest first
Implements monitoring_interface::monitoring_interface.
Definition at line 55 of file multi_process_monitoring_integration.cpp.
is_active()
bool sample_monitoring::is_active () const inline override virtual
Checks if monitoring is currently active.
Returns
true if monitoring is active
Implements monitoring_interface::monitoring_interface.
Definition at line 56 of file multi_process_monitoring_integration.cpp.
update_system_metrics()
void sample_monitoring::update_system_metrics (const ::monitoring_interface::system_metrics & metrics) inline override
Definition at line 38 of file multi_process_monitoring_integration.cpp.
References utility_module::formatter::format().
update_thread_pool_metrics()
void sample_monitoring::update_thread_pool_metrics (const ::monitoring_interface::thread_pool_metrics & metrics) inline override
Definition at line 43 of file multi_process_monitoring_integration.cpp.
References utility_module::formatter::format().
update_worker_metrics()
void sample_monitoring::update_worker_metrics (std::size_t worker_id, const ::monitoring_interface::worker_metrics & metrics) inline override
Definition at line 49 of file multi_process_monitoring_integration.cpp.
References utility_module::formatter::format().
The documentation for this class was generated from the following file:
libraries/thread_system/samples/multi_process_monitoring_integration/multi_process_monitoring_integration.cpp