Messaging System: libraries/thread_system/benchmarks/thread_pool_benchmarks/throughput_detailed_benchmark.cpp File Reference
throughput_detailed_benchmark.cpp File Reference
#include <benchmark/benchmark.h>
#include <chrono>
#include <vector>
#include <atomic>
#include <random>
#include <iomanip>
#include <map>
#include <cmath>
#include <numeric>
#include <algorithm>
#include <memory>
#include <fstream>
#include <future>
#include "../../sources/thread_pool/core/thread_pool.h"
#include "../../sources/thread_pool/workers/thread_worker.h"
#include "../../sources/typed_thread_pool/pool/typed_thread_pool.h"
#include "../../sources/typed_thread_pool/scheduling/typed_thread_worker.h"
#include "../../sources/typed_thread_pool/jobs/callback_typed_job.h"
#include "../../sources/utilities/core/formatter.h"
Enumerations
enum class JobComplexity {
Empty , Trivial , Light , Medium ,
Heavy , VeryHeavy , Mixed , Empty ,
Trivial , Light , Medium , Heavy ,
VeryHeavy , Mixed
}
enum class MemoryPattern {
None , Small , Medium , Large ,
VeryLarge , Random , None , Small ,
Medium , Large , VeryLarge , Random
}
Functions
auto create_default (const uint16_t &worker_counts) -> std::tuple< std::shared_ptr< kcenon::thread::thread_pool >, std::optional< std::string > >
template<typename Type >
auto create_priority_default (const uint16_t &worker_counts) -> std::tuple< std::shared_ptr< typed_kcenon::thread::typed_thread_pool_t< Type > >, std::optional< std::string > >
static void execute_job_with_complexity (JobComplexity complexity)
static std::unique_ptr< char[]> allocate_with_pattern (MemoryPattern pattern)
static void BM_JobComplexity (benchmark::State &state)
Benchmark job complexity impact on throughput.
Args ({static_cast< int >(JobComplexity::Empty), 100000}) -> Args({static_cast< int >(JobComplexity::Trivial), 50000}) ->Args({static_cast< int >(JobComplexity::Light), 10000}) ->Args({static_cast< int >(JobComplexity::Medium), 5000}) ->Args({static_cast< int >(JobComplexity::Heavy), 500}) ->Args({static_cast< int >(JobComplexity::VeryHeavy), 50}) ->Unit(benchmark::kMillisecond)
static void BM_WorkerScaling (benchmark::State &state)
Benchmark worker count scaling.
Args ({1, static_cast< int >(JobComplexity::Light)}) -> Args({2, static_cast< int >(JobComplexity::Light)}) ->Args({4, static_cast< int >(JobComplexity::Light)}) ->Args({8, static_cast< int >(JobComplexity::Light)}) ->Args({16, static_cast< int >(JobComplexity::Light)}) ->Args({1, static_cast< int >(JobComplexity::Medium)}) ->Args({2, static_cast< int >(JobComplexity::Medium)}) ->Args({4, static_cast< int >(JobComplexity::Medium)}) ->Args({8, static_cast< int >(JobComplexity::Medium)}) ->Args({16, static_cast< int >(JobComplexity::Medium)}) ->Unit(benchmark::kMillisecond)
static void BM_MemoryAllocationImpact (benchmark::State &state)
Benchmark memory allocation impact.
Args ({static_cast< int >(MemoryPattern::None), 50000}) -> Args({static_cast< int >(MemoryPattern::Small), 50000}) ->Args({static_cast< int >(MemoryPattern::Medium), 25000}) ->Args({static_cast< int >(MemoryPattern::Large), 5000}) ->Args({static_cast< int >(MemoryPattern::VeryLarge), 500}) ->Unit(benchmark::kMillisecond)
static void BM_QueueDepth (benchmark::State &state)
Benchmark queue depth impact.
Args ({1, 10000}) -> Args({10, 10000}) ->Args({100, 10000}) ->Args({1000, 10000}) ->Args({10000, 10000}) ->Unit(benchmark::kMillisecond)
static void BM_BurstPattern (benchmark::State &state)
Benchmark burst pattern handling.
Args ({100, 10}) -> Args({1000, 10}) ->Args({1000, 100}) ->Args({10000, 100}) ->Unit(benchmark::kMillisecond)
static void BM_JobDependencies (benchmark::State &state)
Benchmark job dependencies impact.
static void BM_PriorityImpact (benchmark::State &state)
Benchmark typed thread pool priority impact.
Arg (2000) -> Unit(benchmark::kMillisecond)
static void BM_MixedWorkload (benchmark::State &state)
Benchmark mixed workload throughput.
Args ({100, 0, 0}) -> Args({0, 100, 0}) ->Args({0, 0, 100}) ->Args({25, 25, 25}) ->Args({60, 10, 25}) ->Args({20, 50, 10}) ->Unit(benchmark::kMillisecond)
static void BM_SustainedThroughput (benchmark::State &state)
Benchmark sustained throughput over time.
Arg (5) -> Arg(10) ->UseManualTime() ->Unit(benchmark::kSecond)
BENCHMARK_MAIN ()
Enumeration Type Documentation
JobComplexity
enum class JobComplexity strong
Enumerator
Empty
Trivial
Light
Medium
Heavy
VeryHeavy
Mixed
Empty
Trivial
Light
Medium
Heavy
VeryHeavy
Mixed
Definition at line 123 of file throughput_detailed_benchmark.cpp.
MemoryPattern
enum class MemoryPattern strong
Enumerator
None
Small
Medium
Large
VeryLarge
Random
None
Small
Medium
Large
VeryLarge
Random
Definition at line 134 of file throughput_detailed_benchmark.cpp.
Function Documentation
allocate_with_pattern()
static std::unique_ptr< char[]> allocate_with_pattern (MemoryPattern pattern) static
Definition at line 207 of file throughput_detailed_benchmark.cpp.
References Large, Medium, None, Random, Small, and VeryLarge.
Referenced by BM_MemoryAllocationImpact(), and BM_MixedWorkload().
Arg() [1/2]
Arg (2000) -> Unit(benchmark::kMillisecond)
Arg() [2/2]
Arg (5) -> Arg(10) ->UseManualTime() ->Unit(benchmark::kSecond)
Args() [1/6]
Args ({1, 10000}) -> Args({10, 10000}) ->Args({100, 10000}) ->Args({1000, 10000}) ->Args({10000, 10000}) ->Unit(benchmark::kMillisecond)
Args() [2/6]
Args ({1, static_cast< int >(JobComplexity::Light)}) -> Args({2, static_cast< int >(JobComplexity::Light)}) ->Args({4, static_cast< int >(JobComplexity::Light)}) ->Args({8, static_cast< int >(JobComplexity::Light)}) ->Args({16, static_cast< int >(JobComplexity::Light)}) ->Args({1, static_cast< int >(JobComplexity::Medium)}) ->Args({2, static_cast< int >(JobComplexity::Medium)}) ->Args({4, static_cast< int >(JobComplexity::Medium)}) ->Args({8, static_cast< int >(JobComplexity::Medium)}) ->Args({16, static_cast< int >(JobComplexity::Medium)}) ->Unit(benchmark::kMillisecond)
References Light.
Args() [3/6]
Args ({100, 0, 0}) -> Args({0, 100, 0}) ->Args({0, 0, 100}) ->Args({25, 25, 25}) ->Args({60, 10, 25}) ->Args({20, 50, 10}) ->Unit(benchmark::kMillisecond)
Args() [4/6]
Args ({100, 10}) -> Args({1000, 10}) ->Args({1000, 100}) ->Args({10000, 100}) ->Unit(benchmark::kMillisecond)
Args() [5/6]
Args ({static_cast< int >(JobComplexity::Empty), 100000}) -> Args({static_cast< int >(JobComplexity::Trivial), 50000}) ->Args({static_cast< int >(JobComplexity::Light), 10000}) ->Args({static_cast< int >(JobComplexity::Medium), 5000}) ->Args({static_cast< int >(JobComplexity::Heavy), 500}) ->Args({static_cast< int >(JobComplexity::VeryHeavy), 50}) ->Unit(benchmark::kMillisecond)
References Empty.
Args() [6/6]
Args ({static_cast< int >(MemoryPattern::None), 50000}) -> Args({static_cast< int >(MemoryPattern::Small), 50000}) ->Args({static_cast< int >(MemoryPattern::Medium), 25000}) ->Args({static_cast< int >(MemoryPattern::Large), 5000}) ->Args({static_cast< int >(MemoryPattern::VeryLarge), 500}) ->Unit(benchmark::kMillisecond)
References None.
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
BM_BurstPattern()
static void BM_BurstPattern (benchmark::State & state) static
Benchmark burst pattern handling.
Definition at line 436 of file throughput_detailed_benchmark.cpp.
References create_default(), execute_job_with_complexity(), and Light.
BM_JobComplexity()
static void BM_JobComplexity (benchmark::State & state) static
Benchmark job complexity impact on throughput.
Definition at line 253 of file throughput_detailed_benchmark.cpp.
References create_default(), and execute_job_with_complexity().
BM_JobDependencies()
static void BM_JobDependencies (benchmark::State & state) static
Benchmark job dependencies impact.
Definition at line 487 of file throughput_detailed_benchmark.cpp.
References create_default(), execute_job_with_complexity(), and Light.
BM_MemoryAllocationImpact()
static void BM_MemoryAllocationImpact (benchmark::State & state) static
Benchmark memory allocation impact.
Definition at line 346 of file throughput_detailed_benchmark.cpp.
References allocate_with_pattern(), create_default(), execute_job_with_complexity(), and Light.
BM_MixedWorkload()
static void BM_MixedWorkload (benchmark::State & state) static
Benchmark mixed workload throughput.
Definition at line 609 of file throughput_detailed_benchmark.cpp.
References allocate_with_pattern(), create_default(), execute_job_with_complexity(), Heavy, Light, and Medium.
BM_PriorityImpact()
static void BM_PriorityImpact (benchmark::State & state) static
Benchmark typed thread pool priority impact.
Definition at line 554 of file throughput_detailed_benchmark.cpp.
References kcenon::thread::Background, execute_job_with_complexity(), High, Light, Low, and kcenon::thread::priority.
BM_QueueDepth()
static void BM_QueueDepth (benchmark::State & state) static
Benchmark queue depth impact.
Definition at line 389 of file throughput_detailed_benchmark.cpp.
References create_default(), execute_job_with_complexity(), and Medium.
BM_SustainedThroughput()
static void BM_SustainedThroughput (benchmark::State & state) static
Benchmark sustained throughput over time.
Definition at line 678 of file throughput_detailed_benchmark.cpp.
References create_default().
BM_WorkerScaling()
static void BM_WorkerScaling (benchmark::State & state) static
Benchmark worker count scaling.
Definition at line 298 of file throughput_detailed_benchmark.cpp.
References create_default(), and execute_job_with_complexity().
create_default()
auto create_default (const uint16_t & worker_counts) -> std::tuple<std::shared_ptr<kcenon::thread::thread_pool>, std::optional<std::string>>
Definition at line 66 of file throughput_detailed_benchmark.cpp.
Referenced by BM_BurstPattern(), BM_JobComplexity(), BM_JobDependencies(), BM_MemoryAllocationImpact(), BM_MixedWorkload(), BM_QueueDepth(), BM_SustainedThroughput(), and BM_WorkerScaling().
create_priority_default()
template<typename Type > auto create_priority_default (const uint16_t & worker_counts) -> std::tuple<std::shared_ptr<typed_kcenon::thread::typed_thread_pool_t<Type>>, std::optional<std::string>>
Definition at line 93 of file throughput_detailed_benchmark.cpp.
execute_job_with_complexity()
static void execute_job_with_complexity (JobComplexity complexity) static
Definition at line 144 of file throughput_detailed_benchmark.cpp.
References Empty, execute_job_with_complexity(), Heavy, Light, Medium, Mixed, Trivial, and VeryHeavy.
Referenced by BM_BurstPattern(), BM_JobComplexity(), BM_JobDependencies(), BM_MemoryAllocationImpact(), BM_MixedWorkload(), BM_PriorityImpact(), BM_QueueDepth(), BM_WorkerScaling(), and execute_job_with_complexity().