Messaging System: monitoring_system::metric_batch Struct Reference
monitoring_system::metric_batch Struct Reference
Batch of metrics for efficient processing.
#include <metric_types.h>
Public Member Functions
metric_batch ()
metric_batch (size_t id)
void add_metric (compact_metric_value &&metric)
Add metric to batch.
size_t memory_footprint () const noexcept
Get batch size in bytes.
void reserve (size_t count)
Reserve space for metrics.
void clear ()
Clear all metrics.
bool empty () const noexcept
Check if batch is empty.
size_t size () const noexcept
Get number of metrics in batch.
metric_batch ()
metric_batch (size_t id)
void add_metric (compact_metric_value &&metric)
Add metric to batch.
size_t memory_footprint () const noexcept
Get batch size in bytes.
void reserve (size_t count)
Reserve space for metrics.
void clear ()
Clear all metrics.
bool empty () const noexcept
Check if batch is empty.
size_t size () const noexcept
Get number of metrics in batch.
Public Attributes
std::vector< compact_metric_value > metrics
std::chrono::system_clock::time_point batch_timestamp
size_t batch_id
Detailed Description
Batch of metrics for efficient processing.
Definition at line 179 of file metric_types.h.
Constructor & Destructor Documentation
metric_batch() [1/4]
monitoring_system::metric_batch::metric_batch () inline
Definition at line 184 of file metric_types.h.
Referenced by memory_footprint().
metric_batch() [2/4]
monitoring_system::metric_batch::metric_batch (size_t id) inline explicit
Definition at line 186 of file metric_types.h.
metric_batch() [3/4]
monitoring_system::metric_batch::metric_batch () inline
Definition at line 184 of file metric_types.h.
metric_batch() [4/4]
monitoring_system::metric_batch::metric_batch (size_t id) inline explicit
Definition at line 186 of file metric_types.h.
Member Function Documentation
add_metric() [1/2]
void monitoring_system::metric_batch::add_metric (compact_metric_value && metric) inline
Add metric to batch.
Definition at line 192 of file metric_types.h.
References metrics.
Referenced by monitoring_system::buffer_manager::configure_metric_buffer(), monitoring_system::buffer_manager::remove_buffer(), TEST_F(), and TEST_F().
add_metric() [2/2]
void monitoring_system::metric_batch::add_metric (compact_metric_value && metric) inline
Add metric to batch.
Definition at line 192 of file metric_types.h.
References metrics.
clear() [1/2]
void monitoring_system::metric_batch::clear () inline
Clear all metrics.
Definition at line 217 of file metric_types.h.
References batch_timestamp, and metrics.
Referenced by TEST_F().
clear() [2/2]
void monitoring_system::metric_batch::clear () inline
Clear all metrics.
Definition at line 217 of file metric_types.h.
References batch_timestamp, and metrics.
empty() [1/2]
bool monitoring_system::metric_batch::empty () const inline noexcept
Check if batch is empty.
Definition at line 225 of file metric_types.h.
References metrics.
Referenced by TEST_F().
empty() [2/2]
bool monitoring_system::metric_batch::empty () const inline noexcept
Check if batch is empty.
Definition at line 225 of file metric_types.h.
References metrics.
memory_footprint() [1/2]
size_t monitoring_system::metric_batch::memory_footprint () const inline noexcept
Get batch size in bytes.
Definition at line 199 of file metric_types.h.
References metric_batch(), and metrics.
Referenced by TEST_F().
memory_footprint() [2/2]
size_t monitoring_system::metric_batch::memory_footprint () const inline noexcept
Get batch size in bytes.
Definition at line 199 of file metric_types.h.
References metric_batch(), and metrics.
reserve() [1/2]
void monitoring_system::metric_batch::reserve (size_t count) inline
Reserve space for metrics.
Definition at line 210 of file metric_types.h.
References monitoring_system::count, and metrics.
reserve() [2/2]
void monitoring_system::metric_batch::reserve (size_t count) inline
Reserve space for metrics.
Definition at line 210 of file metric_types.h.
References monitoring_system::count, and metrics.
size() [1/2]
size_t monitoring_system::metric_batch::size () const inline noexcept
Get number of metrics in batch.
Definition at line 232 of file metric_types.h.
References metrics.
Referenced by TEST_F().
size() [2/2]
size_t monitoring_system::metric_batch::size () const inline noexcept
Get number of metrics in batch.
Definition at line 232 of file metric_types.h.
References metrics.
Member Data Documentation
batch_id
size_t monitoring_system::metric_batch::batch_id
Definition at line 182 of file metric_types.h.
batch_timestamp
std::chrono::system_clock::time_point monitoring_system::metric_batch::batch_timestamp
Definition at line 181 of file metric_types.h.
Referenced by clear().
metrics
std::vector< compact_metric_value > monitoring_system::metric_batch::metrics
Definition at line 180 of file metric_types.h.
Referenced by add_metric(), clear(), empty(), memory_footprint(), reserve(), size(), and monitoring_system::metric_storage::store_metrics_batch().
The documentation for this struct was generated from the following files:
libraries/monitoring_system/include/kcenon/monitoring/utils/metric_types.h
libraries/monitoring_system/src/utils/metric_types.h