Messaging System: libraries/logger_system/samples/crash_protection/main.cpp File Reference
main.cpp File Reference
Logger crash protection demonstration.
#include <iostream>
#include <thread>
#include <chrono>
#include <random>
#include <vector>
#include <memory>
#include <atomic>
#include <fstream>
#include "interfaces/logger_crash_safety.h"
#include "logger/logger.h"
#include "logger/writers/console_writer.h"
#include "logger/writers/file_writer.h"
Functions
void simulate_logger_crash ()
void simulate_file_corruption ()
void simulate_disk_full ()
void normal_logging_task (int task_id, std::shared_ptr< logger > logger_instance)
void heavy_logging_task (int task_id, std::shared_ptr< logger > logger_instance)
void potentially_crashing_logging_task (int task_id, std::shared_ptr< logger > logger_instance)
void on_logger_crash (const std::string &logger_name)
void flush_main_logger ()
void backup_main_logger (const std::string &backup_path)
void save_emergency_state ()
int main ()
Variables
std::atomic< bool > logging_active {true}
std::atomic< int > logs_written {0}
std::atomic< int > emergency_logs {0}
Detailed Description
Logger crash protection demonstration.
This example demonstrates comprehensive crash protection mechanisms for logging systems including emergency logging, log file recovery, automatic backups, and signal-safe logging operations.
Definition in file main.cpp.
Function Documentation
backup_main_logger()
void backup_main_logger (const std::string & backup_path)
Definition at line 147 of file main.cpp.
Referenced by main().
flush_main_logger()
void flush_main_logger ()
Definition at line 143 of file main.cpp.
Referenced by main().
heavy_logging_task()
void heavy_logging_task (int task_id, std::shared_ptr< logger > logger_instance)
Definition at line 72 of file main.cpp.
References logs_written.
Referenced by main().
main()
int main ()
Definition at line 164 of file main.cpp.
References backup_main_logger(), logger_module::async_logger_crash_safety::configure_async_safety(), logger_module::log_file_recovery::create_backup_with_checksum(), emergency_logs, flush_main_logger(), heavy_logging_task(), logger_module::logger_crash_safety::instance(), logger_module::log_file_recovery::is_corrupted(), logging_active, logs_written, normal_logging_task(), potentially_crashing_logging_task(), logger_module::log_file_recovery::recover_file(), logger_module::async_logger_crash_safety::set_overflow_handler(), simulate_file_corruption(), and logger_module::log_file_recovery::verify_integrity().
normal_logging_task()
void normal_logging_task (int task_id, std::shared_ptr< logger > logger_instance)
Definition at line 56 of file main.cpp.
References logs_written.
Referenced by main().
on_logger_crash()
void on_logger_crash (const std::string & logger_name)
Definition at line 133 of file main.cpp.
References logger_module::logger_crash_safety::emergency_log(), emergency_logs, logger_module::logger_crash_safety::instance(), and logging_active.
potentially_crashing_logging_task()
void potentially_crashing_logging_task (int task_id, std::shared_ptr< logger > logger_instance)
Definition at line 94 of file main.cpp.
References logger_module::logger_crash_safety::emergency_log(), emergency_logs, logger_module::logger_crash_safety::instance(), logs_written, simulate_file_corruption(), and simulate_logger_crash().
Referenced by main().
save_emergency_state()
void save_emergency_state ()
Definition at line 158 of file main.cpp.
References emergency_logs, and logs_written.
simulate_disk_full()
void simulate_disk_full ()
Definition at line 48 of file main.cpp.
References logger_module::logger_crash_safety::emergency_log(), and logger_module::logger_crash_safety::instance().
simulate_file_corruption()
void simulate_file_corruption ()
Definition at line 38 of file main.cpp.
Referenced by main(), and potentially_crashing_logging_task().
simulate_logger_crash()
void simulate_logger_crash ()
Definition at line 33 of file main.cpp.
Referenced by potentially_crashing_logging_task().
Variable Documentation
emergency_logs
std::atomic<int> emergency_logs {0}
Definition at line 30 of file main.cpp.
Referenced by main(), on_logger_crash(), potentially_crashing_logging_task(), and save_emergency_state().
logging_active
std::atomic<bool> logging_active {true}
Definition at line 28 of file main.cpp.
Referenced by main(), and on_logger_crash().
logs_written
std::atomic<int> logs_written {0}
Definition at line 29 of file main.cpp.
Referenced by heavy_logging_task(), main(), normal_logging_task(), potentially_crashing_logging_task(), and save_emergency_state().