Messaging System: application_layer/tests/unit/test_service_container.cpp File Reference
test_service_container.cpp File Reference
#include <gtest/gtest.h>
#include <kcenon/messaging/integrations/service_container.h>
#include <memory>
#include <string>
Classes
class MockService
class MockDependentService
class ServiceContainerTest
Functions
TEST_F (ServiceContainerTest, RegisterAndResolveTransientService)
TEST_F (ServiceContainerTest, RegisterAndResolveSingletonService)
TEST_F (ServiceContainerTest, RegisterSingletonInstance)
TEST_F (ServiceContainerTest, ResolveByType)
TEST_F (ServiceContainerTest, DependencyInjection)
TEST_F (ServiceContainerTest, NonExistentService)
TEST_F (ServiceContainerTest, ServiceRegistrationList)
TEST_F (ServiceContainerTest, ClearContainer)
TEST_F (ServiceContainerTest, ThreadSafety)
Function Documentation
TEST_F() [1/9]
TEST_F (ServiceContainerTest , ClearContainer)
Definition at line 175 of file test_service_container.cpp.
TEST_F() [2/9]
TEST_F (ServiceContainerTest , DependencyInjection)
Definition at line 115 of file test_service_container.cpp.
References MockDependentService::get_dependency_value().
TEST_F() [3/9]
TEST_F (ServiceContainerTest , NonExistentService)
Definition at line 136 of file test_service_container.cpp.
TEST_F() [4/9]
TEST_F (ServiceContainerTest , RegisterAndResolveSingletonService)
Definition at line 65 of file test_service_container.cpp.
References MockService::get_value(), and MockService::set_value().
TEST_F() [5/9]
TEST_F (ServiceContainerTest , RegisterAndResolveTransientService)
Definition at line 41 of file test_service_container.cpp.
References MockService::get_value().
TEST_F() [6/9]
TEST_F (ServiceContainerTest , RegisterSingletonInstance)
Definition at line 89 of file test_service_container.cpp.
TEST_F() [7/9]
TEST_F (ServiceContainerTest , ResolveByType)
Definition at line 102 of file test_service_container.cpp.
References MockService::get_value().
TEST_F() [8/9]
TEST_F (ServiceContainerTest , ServiceRegistrationList)
Definition at line 148 of file test_service_container.cpp.
TEST_F() [9/9]
TEST_F (ServiceContainerTest , ThreadSafety)
Definition at line 201 of file test_service_container.cpp.