Messaging System: typed_thread_pool_module::typed_lockfree_job_queue_t< job_type > Class Template Reference
typed_thread_pool_module::typed_lockfree_job_queue_t< job_type > Class Template Reference
High-performance lock-free priority-based job queue.
#include <typed_lockfree_job_queue.h>
Classes
struct typed_queue_statistics
Extended statistics for typed queues.
Public Member Functions
typed_lockfree_job_queue_t (size_t max_threads=128)
Constructs a typed lock-free job queue.
virtual ~typed_lockfree_job_queue_t ()
Destructor.
typed_lockfree_job_queue_t (const typed_lockfree_job_queue_t &)=delete
typed_lockfree_job_queue_t & operator= (const typed_lockfree_job_queue_t &)=delete
typed_lockfree_job_queue_t (typed_lockfree_job_queue_t &&)=delete
typed_lockfree_job_queue_t & operator= (typed_lockfree_job_queue_t &&)=delete
auto enqueue (std::unique_ptr< typed_job_t< job_type > > &&value) -> thread_module::result_void
Enqueues a typed job with priority.
auto enqueue (std::unique_ptr< thread_module::job > &&value) -> thread_module::result_void override
Enqueues a generic job (attempts to cast to typed_job)
auto enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > &&jobs) -> thread_module::result_void
Enqueues multiple typed jobs.
auto enqueue_batch (std::vector< std::unique_ptr< thread_module::job > > &&jobs) -> thread_module::result_void override
Enqueues multiple generic jobs.
auto dequeue () -> thread_module::result< std::unique_ptr< thread_module::job > > override
Dequeues a job with highest priority.
auto dequeue (const job_type &type) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job of specific type.
auto dequeue (utility_module::span< const job_type > types) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues jobs from multiple types.
auto dequeue_batch () -> std::deque< std::unique_ptr< thread_module::job > > override
Dequeues all available jobs.
auto clear () -> void override
Clears all jobs from all priority queues.
auto empty () const -> bool
Checks if all queues are empty.
auto empty (const std::vector< job_type > &types) const -> bool
Checks if specific types are empty.
auto size () const -> std::size_t
Gets the total number of jobs across all queues.
auto size (const job_type &type) const -> std::size_t
Gets the number of jobs for a specific type.
auto get_sizes () const -> std::unordered_map< job_type, std::size_t >
Gets sizes for all job types.
auto to_string () const -> std::string override
Gets string representation of the queue.
auto get_typed_statistics () const -> typed_queue_statistics_t< job_type >
Get detailed statistics including per-type metrics.
auto reset_statistics () -> void
Reset all statistics.
auto stop () -> void
Stop the queue (for interface compatibility)
typed_lockfree_job_queue_t (size_t max_threads=128)
Constructs a typed lock-free job queue.
virtual ~typed_lockfree_job_queue_t ()
Destructor.
typed_lockfree_job_queue_t (const typed_lockfree_job_queue_t &)=delete
typed_lockfree_job_queue_t & operator= (const typed_lockfree_job_queue_t &)=delete
typed_lockfree_job_queue_t (typed_lockfree_job_queue_t &&)=delete
typed_lockfree_job_queue_t & operator= (typed_lockfree_job_queue_t &&)=delete
auto enqueue (std::unique_ptr< typed_job_t< job_type > > &&value) -> thread_module::result_void
Enqueues a typed job with priority.
auto enqueue (std::unique_ptr< thread_module::job > &&value) -> thread_module::result_void override
Enqueues a generic job (attempts to cast to typed_job)
auto enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > &&jobs) -> thread_module::result_void
Enqueues multiple typed jobs.
auto enqueue_batch (std::vector< std::unique_ptr< thread_module::job > > &&jobs) -> thread_module::result_void override
Enqueues multiple generic jobs.
auto dequeue () -> thread_module::result< std::unique_ptr< thread_module::job > > override
Dequeues a job with highest priority.
auto dequeue (const job_type &type) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job of specific type.
auto dequeue (utility_module::span< const job_type > types) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues jobs from multiple types.
auto dequeue_batch () -> std::deque< std::unique_ptr< thread_module::job > > override
Dequeues all available jobs.
auto clear () -> void override
Clears all jobs from all priority queues.
auto empty () const -> bool
Checks if all queues are empty.
auto empty (const std::vector< job_type > &types) const -> bool
Checks if specific types are empty.
auto size () const -> std::size_t
Gets the total number of jobs across all queues.
auto size (const job_type &type) const -> std::size_t
Gets the number of jobs for a specific type.
auto get_sizes () const -> std::unordered_map< job_type, std::size_t >
Gets sizes for all job types.
auto to_string () const -> std::string override
Gets string representation of the queue.
auto get_typed_statistics () const -> typed_queue_statistics_t< job_type >
Get detailed statistics including per-type metrics.
auto reset_statistics () -> void
Reset all statistics.
auto stop () -> void
Stop the queue (for interface compatibility)
typed_lockfree_job_queue_t (size_t max_threads=128)
Constructs a typed lock-free job queue.
virtual ~typed_lockfree_job_queue_t ()
Destructor.
typed_lockfree_job_queue_t (const typed_lockfree_job_queue_t &)=delete
typed_lockfree_job_queue_t & operator= (const typed_lockfree_job_queue_t &)=delete
typed_lockfree_job_queue_t (typed_lockfree_job_queue_t &&)=delete
typed_lockfree_job_queue_t & operator= (typed_lockfree_job_queue_t &&)=delete
auto enqueue (std::unique_ptr< typed_job_t< job_type > > &&value) -> thread_module::result_void
Enqueues a typed job with priority.
auto enqueue (std::unique_ptr< thread_module::job > &&value) -> thread_module::result_void override
Enqueues a generic job (attempts to cast to typed_job)
auto enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > &&jobs) -> thread_module::result_void
Enqueues multiple typed jobs.
auto enqueue_batch (std::vector< std::unique_ptr< thread_module::job > > &&jobs) -> thread_module::result_void override
Enqueues multiple generic jobs.
auto dequeue () -> thread_module::result< std::unique_ptr< thread_module::job > > override
Dequeues a job with highest priority.
auto dequeue (const job_type &type) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job of specific type.
auto dequeue (utility_module::span< const job_type > types) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues jobs from multiple types.
auto dequeue_batch () -> std::deque< std::unique_ptr< thread_module::job > > override
Dequeues all available jobs.
auto clear () -> void override
Clears all jobs from all priority queues.
auto empty () const -> bool
Checks if all queues are empty.
auto empty (const std::vector< job_type > &types) const -> bool
Checks if specific types are empty.
auto size () const -> std::size_t
Gets the total number of jobs across all queues.
auto size (const job_type &type) const -> std::size_t
Gets the number of jobs for a specific type.
auto get_sizes () const -> std::unordered_map< job_type, std::size_t >
Gets sizes for all job types.
auto to_string () const -> std::string override
Gets string representation of the queue.
auto get_typed_statistics () const -> typed_queue_statistics_t< job_type >
Get detailed statistics including per-type metrics.
auto reset_statistics () -> void
Reset all statistics.
auto stop () -> void
Stop the queue (for interface compatibility)
Public Member Functions inherited from thread_module::job_queue
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
job_queue ()
Constructs a new, empty job_queue.
virtual ~job_queue (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< job_queue >
Obtains a std::shared_ptr that points to this queue instance.
auto is_stopped () const -> bool
Checks if the queue is in a "stopped" state.
auto set_notify (bool notify) -> void
Sets the 'notify' flag for this queue.
auto empty (void) const -> bool
Checks if the queue is currently empty.
auto size (void) const -> std::size_t
Returns the current number of jobs in the queue.
auto stop_waiting_dequeue (void) -> void
Signals the queue to stop waiting for new jobs (e.g., during shutdown).
Additional Inherited Members
Protected Attributes inherited from thread_module::job_queue
std::atomic_bool notify_
If true, threads waiting for new jobs are notified when a new job is enqueued.
std::atomic_bool stop_
Indicates whether the queue has been signaled to stop.
std::mutex mutex_
Mutex to protect access to the underlying queue_ container and related state.
std::condition_variable condition_
Condition variable used to signal worker threads.
Detailed Description
template<typename job_type = job_types>
class typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >
High-performance lock-free priority-based job queue.
This class provides a lock-free implementation of a typed job queue that manages jobs with distinct priority levels. It maintains separate lock-free queues for each job type/priority, ensuring thread-safe operations with minimal contention.
Template Parameters
job_type The type used to represent job priority levels. Defaults to job_types.
Note
This implementation is optimized for high-concurrency scenarios where traditional mutex-based queues would become a bottleneck.
Definition at line 103 of file typed_lockfree_job_queue.h.
Constructor & Destructor Documentation
typed_lockfree_job_queue_t() [1/9]
template<typename job_type = job_types> typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_lockfree_job_queue_t (size_t max_threads = 128) explicit
Constructs a typed lock-free job queue.
Parameters
max_threads Maximum number of threads that will access the queue
~typed_lockfree_job_queue_t() [1/3]
template<typename job_type = job_types> virtual typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::~typed_lockfree_job_queue_t () virtual
Destructor.
typed_lockfree_job_queue_t() [2/9]
template<typename job_type = job_types> typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_lockfree_job_queue_t (const typed_lockfree_job_queue_t< job_type > &) delete
typed_lockfree_job_queue_t() [3/9]
template<typename job_type = job_types> typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_lockfree_job_queue_t (typed_lockfree_job_queue_t< job_type > &&) delete
typed_lockfree_job_queue_t() [4/9]
template<typename job_type = job_types> typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_lockfree_job_queue_t (size_t max_threads = 128) explicit
Constructs a typed lock-free job queue.
Parameters
max_threads Maximum number of threads that will access the queue
~typed_lockfree_job_queue_t() [2/3]
template<typename job_type = job_types> virtual typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::~typed_lockfree_job_queue_t () virtual
Destructor.
typed_lockfree_job_queue_t() [5/9]
template<typename job_type = job_types> typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_lockfree_job_queue_t (const typed_lockfree_job_queue_t< job_type > &) delete
typed_lockfree_job_queue_t() [6/9]
template<typename job_type = job_types> typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_lockfree_job_queue_t (typed_lockfree_job_queue_t< job_type > &&) delete
typed_lockfree_job_queue_t() [7/9]
template<typename job_type = job_types> typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_lockfree_job_queue_t (size_t max_threads = 128) explicit
Constructs a typed lock-free job queue.
Parameters
max_threads Maximum number of threads that will access the queue
~typed_lockfree_job_queue_t() [3/3]
template<typename job_type = job_types> virtual typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::~typed_lockfree_job_queue_t () virtual
Destructor.
typed_lockfree_job_queue_t() [8/9]
template<typename job_type = job_types> typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_lockfree_job_queue_t (const typed_lockfree_job_queue_t< job_type > &) delete
typed_lockfree_job_queue_t() [9/9]
template<typename job_type = job_types> typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::typed_lockfree_job_queue_t (typed_lockfree_job_queue_t< job_type > &&) delete
Member Function Documentation
clear() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::clear () -> void override virtual
Clears all jobs from all priority queues.
Reimplemented from thread_module::job_queue.
clear() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::clear () -> void override virtual
Clears all jobs from all priority queues.
Reimplemented from thread_module::job_queue.
clear() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::clear () -> void override virtual
Clears all jobs from all priority queues.
Reimplemented from thread_module::job_queue.
dequeue() [1/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue () -> thread_module::result< std::unique_ptr< thread_module::job > > override virtual
Dequeues a job with highest priority.
Returns
The dequeued job or error
Reimplemented from thread_module::job_queue.
Referenced by BM_TypedLockfreeJobQueue_EnqueueDequeue(), BM_TypedLockfreeJobQueue_HighContention(), BM_TypedLockfreeJobQueue_MemoryUsage(), and BM_TypedLockfreeJobQueue_PriorityDequeue().
dequeue() [2/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue () -> thread_module::result< std::unique_ptr< thread_module::job > > override virtual
Dequeues a job with highest priority.
Returns
The dequeued job or error
Reimplemented from thread_module::job_queue.
dequeue() [3/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue () -> thread_module::result< std::unique_ptr< thread_module::job > > override virtual
Dequeues a job with highest priority.
Returns
The dequeued job or error
Reimplemented from thread_module::job_queue.
dequeue() [4/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue (const job_type & type) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job of specific type.
Parameters
type The job type to dequeue
Returns
The dequeued job or error
dequeue() [5/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue (const job_type & type) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job of specific type.
Parameters
type The job type to dequeue
Returns
The dequeued job or error
dequeue() [6/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue (const job_type & type) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues a job of specific type.
Parameters
type The job type to dequeue
Returns
The dequeued job or error
dequeue() [7/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue (utility_module::span< const job_type > types) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues jobs from multiple types.
Parameters
types Span of job types to consider
Returns
The dequeued job or error
dequeue() [8/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue (utility_module::span< const job_type > types) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues jobs from multiple types.
Parameters
types Span of job types to consider
Returns
The dequeued job or error
dequeue() [9/9]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue (utility_module::span< const job_type > types) -> thread_module::result< std::unique_ptr< typed_job_t< job_type > > >
Dequeues jobs from multiple types.
Parameters
types Span of job types to consider
Returns
The dequeued job or error
dequeue_batch() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue_batch () -> std::deque< std::unique_ptr< thread_module::job > > override virtual
Dequeues all available jobs.
Returns
Deque containing all dequeued jobs
Reimplemented from thread_module::job_queue.
dequeue_batch() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue_batch () -> std::deque< std::unique_ptr< thread_module::job > > override virtual
Dequeues all available jobs.
Returns
Deque containing all dequeued jobs
Reimplemented from thread_module::job_queue.
dequeue_batch() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::dequeue_batch () -> std::deque< std::unique_ptr< thread_module::job > > override virtual
Dequeues all available jobs.
Returns
Deque containing all dequeued jobs
Reimplemented from thread_module::job_queue.
empty() [1/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::empty () const -> bool
Checks if all queues are empty.
Returns
true if empty, false otherwise
Referenced by BM_TypedLockfreeJobQueue_MemoryUsage().
empty() [2/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::empty () const -> bool
Checks if all queues are empty.
Returns
true if empty, false otherwise
empty() [3/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::empty () const -> bool
Checks if all queues are empty.
Returns
true if empty, false otherwise
empty() [4/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::empty (const std::vector< job_type > & types) const -> bool
Checks if specific types are empty.
Parameters
types Vector of job types to check
Returns
True if all specified types have no jobs
empty() [5/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::empty (const std::vector< job_type > & types) const -> bool
Checks if specific types are empty.
Parameters
types Vector of job types to check
Returns
True if all specified types have no jobs
empty() [6/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::empty (const std::vector< job_type > & types) const -> bool
Checks if specific types are empty.
Parameters
types Vector of job types to check
Returns
True if all specified types have no jobs
enqueue() [1/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue (std::unique_ptr< thread_module::job > && value) -> thread_module::result_void override virtual
Enqueues a generic job (attempts to cast to typed_job)
Parameters
value Unique pointer to a job
Returns
Success or error result
Reimplemented from thread_module::job_queue.
enqueue() [2/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue (std::unique_ptr< thread_module::job > && value) -> thread_module::result_void override virtual
Enqueues a generic job (attempts to cast to typed_job)
Parameters
value Unique pointer to a job
Returns
Success or error result
Reimplemented from thread_module::job_queue.
enqueue() [3/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue (std::unique_ptr< thread_module::job > && value) -> thread_module::result_void override virtual
Enqueues a generic job (attempts to cast to typed_job)
Parameters
value Unique pointer to a job
Returns
Success or error result
Reimplemented from thread_module::job_queue.
enqueue() [4/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue (std::unique_ptr< typed_job_t< job_type > > && value) -> thread_module::result_void
Enqueues a typed job with priority.
Parameters
value Unique pointer to a typed job
Returns
Success or error result
Referenced by BM_TypedLockfreeJobQueue_Enqueue(), BM_TypedLockfreeJobQueue_EnqueueDequeue(), BM_TypedLockfreeJobQueue_HighContention(), BM_TypedLockfreeJobQueue_MemoryUsage(), and BM_TypedLockfreeJobQueue_PriorityDequeue().
enqueue() [5/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue (std::unique_ptr< typed_job_t< job_type > > && value) -> thread_module::result_void
Enqueues a typed job with priority.
Parameters
value Unique pointer to a typed job
Returns
Success or error result
enqueue() [6/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue (std::unique_ptr< typed_job_t< job_type > > && value) -> thread_module::result_void
Enqueues a typed job with priority.
Parameters
value Unique pointer to a typed job
Returns
Success or error result
enqueue_batch() [1/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< thread_module::job > > && jobs) -> thread_module::result_void override virtual
Enqueues multiple generic jobs.
Parameters
jobs Vector of jobs to enqueue
Returns
Success or error result
Reimplemented from thread_module::job_queue.
enqueue_batch() [2/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< thread_module::job > > && jobs) -> thread_module::result_void override virtual
Enqueues multiple generic jobs.
Parameters
jobs Vector of jobs to enqueue
Returns
Success or error result
Reimplemented from thread_module::job_queue.
enqueue_batch() [3/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< thread_module::job > > && jobs) -> thread_module::result_void override virtual
Enqueues multiple generic jobs.
Parameters
jobs Vector of jobs to enqueue
Returns
Success or error result
Reimplemented from thread_module::job_queue.
enqueue_batch() [4/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > && jobs) -> thread_module::result_void
Enqueues multiple typed jobs.
Parameters
jobs Vector of typed jobs to enqueue
Returns
Success or error result
Referenced by BM_TypedLockfreeJobQueue_BatchEnqueue().
enqueue_batch() [5/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > && jobs) -> thread_module::result_void
Enqueues multiple typed jobs.
Parameters
jobs Vector of typed jobs to enqueue
Returns
Success or error result
enqueue_batch() [6/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::enqueue_batch (std::vector< std::unique_ptr< typed_job_t< job_type > > > && jobs) -> thread_module::result_void
Enqueues multiple typed jobs.
Parameters
jobs Vector of typed jobs to enqueue
Returns
Success or error result
get_sizes() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::get_sizes () const -> std::unordered_map< job_type, std::size_t >
Gets sizes for all job types.
Returns
Map of job types to their queue sizes
get_sizes() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::get_sizes () const -> std::unordered_map< job_type, std::size_t >
Gets sizes for all job types.
Returns
Map of job types to their queue sizes
get_sizes() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::get_sizes () const -> std::unordered_map< job_type, std::size_t >
Gets sizes for all job types.
Returns
Map of job types to their queue sizes
get_typed_statistics() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::get_typed_statistics () const -> typed_queue_statistics_t< job_type >
Get detailed statistics including per-type metrics.
Returns
Extended statistics
get_typed_statistics() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::get_typed_statistics () const -> typed_queue_statistics_t< job_type >
Get detailed statistics including per-type metrics.
Returns
Extended statistics
get_typed_statistics() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::get_typed_statistics () const -> typed_queue_statistics_t< job_type >
Get detailed statistics including per-type metrics.
Returns
Extended statistics
operator=() [1/6]
template<typename job_type = job_types> typed_lockfree_job_queue_t & typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::operator= (const typed_lockfree_job_queue_t< job_type > &) delete
operator=() [2/6]
template<typename job_type = job_types> typed_lockfree_job_queue_t & typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::operator= (const typed_lockfree_job_queue_t< job_type > &) delete
operator=() [3/6]
template<typename job_type = job_types> typed_lockfree_job_queue_t & typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::operator= (const typed_lockfree_job_queue_t< job_type > &) delete
operator=() [4/6]
template<typename job_type = job_types> typed_lockfree_job_queue_t & typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::operator= (typed_lockfree_job_queue_t< job_type > &&) delete
operator=() [5/6]
template<typename job_type = job_types> typed_lockfree_job_queue_t & typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::operator= (typed_lockfree_job_queue_t< job_type > &&) delete
operator=() [6/6]
template<typename job_type = job_types> typed_lockfree_job_queue_t & typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::operator= (typed_lockfree_job_queue_t< job_type > &&) delete
reset_statistics() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::reset_statistics () -> void
Reset all statistics.
reset_statistics() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::reset_statistics () -> void
Reset all statistics.
reset_statistics() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::reset_statistics () -> void
Reset all statistics.
size() [1/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::size () const -> std::size_t
Gets the total number of jobs across all queues.
Returns
Total number of jobs
Referenced by BM_TypedLockfreeJobQueue_MemoryUsage().
size() [2/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::size () const -> std::size_t
Gets the total number of jobs across all queues.
Returns
Total number of jobs
size() [3/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::size () const -> std::size_t
Gets the total number of jobs across all queues.
Returns
Total number of jobs
size() [4/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::size (const job_type & type) const -> std::size_t
Gets the number of jobs for a specific type.
Parameters
type The job type to query
Returns
Number of jobs of that type
size() [5/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::size (const job_type & type) const -> std::size_t
Gets the number of jobs for a specific type.
Parameters
type The job type to query
Returns
Number of jobs of that type
size() [6/6]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::size (const job_type & type) const -> std::size_t
Gets the number of jobs for a specific type.
Parameters
type The job type to query
Returns
Number of jobs of that type
stop() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::stop () -> void
Stop the queue (for interface compatibility)
stop() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::stop () -> void
Stop the queue (for interface compatibility)
stop() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::stop () -> void
Stop the queue (for interface compatibility)
to_string() [1/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::to_string () const -> std::string override virtual
Gets string representation of the queue.
Returns
String describing the queue state
Reimplemented from thread_module::job_queue.
to_string() [2/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::to_string () const -> std::string override virtual
Gets string representation of the queue.
Returns
String describing the queue state
Reimplemented from thread_module::job_queue.
to_string() [3/3]
template<typename job_type = job_types> auto typed_thread_pool_module::typed_lockfree_job_queue_t< job_type >::to_string () const -> std::string override virtual
Gets string representation of the queue.
Returns
String describing the queue state
Reimplemented from thread_module::job_queue.
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/typed_thread_pool/scheduling/typed_lockfree_job_queue.h
libraries/thread_system/modular_structure/core/src/typed_thread_pool/scheduling/typed_lockfree_job_queue.h
libraries/thread_system/sources/typed_thread_pool/scheduling/typed_lockfree_job_queue.h