Messaging System: libraries/monitoring_system/tests/test_distributed_tracing.cpp File Reference
test_distributed_tracing.cpp File Reference
Unit tests for distributed tracing functionality.
#include <gtest/gtest.h>
#include <thread>
#include <chrono>
#include <unordered_map>
Classes
class DistributedTracingTest
Functions
TEST_F (DistributedTracingTest, CreateRootSpan)
TEST_F (DistributedTracingTest, CreateChildSpan)
TEST_F (DistributedTracingTest, FinishSpan)
TEST_F (DistributedTracingTest, CannotFinishSpanTwice)
TEST_F (DistributedTracingTest, TraceContextPropagation)
TEST_F (DistributedTracingTest, W3CTraceContextFormat)
TEST_F (DistributedTracingTest, InjectExtractContext)
TEST_F (DistributedTracingTest, StartSpanFromContext)
TEST_F (DistributedTracingTest, CurrentSpanManagement)
TEST_F (DistributedTracingTest, ScopedSpan)
TEST_F (DistributedTracingTest, GetTrace)
TEST_F (DistributedTracingTest, SpanTags)
TEST_F (DistributedTracingTest, SpanStatus)
TEST_F (DistributedTracingTest, BaggagePropagation)
TEST_F (DistributedTracingTest, ExportSpans)
TEST_F (DistributedTracingTest, TraceMacros)
Detailed Description
Unit tests for distributed tracing functionality.
Definition in file test_distributed_tracing.cpp.
Function Documentation
TEST_F() [1/16]
TEST_F (DistributedTracingTest , BaggagePropagation)
Definition at line 274 of file test_distributed_tracing.cpp.
TEST_F() [2/16]
TEST_F (DistributedTracingTest , CannotFinishSpanTwice)
Definition at line 72 of file test_distributed_tracing.cpp.
TEST_F() [3/16]
TEST_F (DistributedTracingTest , CreateChildSpan)
Definition at line 41 of file test_distributed_tracing.cpp.
TEST_F() [4/16]
TEST_F (DistributedTracingTest , CreateRootSpan)
Definition at line 28 of file test_distributed_tracing.cpp.
TEST_F() [5/16]
TEST_F (DistributedTracingTest , CurrentSpanManagement)
Definition at line 163 of file test_distributed_tracing.cpp.
TEST_F() [6/16]
TEST_F (DistributedTracingTest , ExportSpans)
Definition at line 303 of file test_distributed_tracing.cpp.
References monitoring_system::trace.
TEST_F() [7/16]
TEST_F (DistributedTracingTest , FinishSpan)
Definition at line 56 of file test_distributed_tracing.cpp.
TEST_F() [8/16]
TEST_F (DistributedTracingTest , GetTrace)
Definition at line 206 of file test_distributed_tracing.cpp.
References monitoring_system::trace.
TEST_F() [9/16]
TEST_F (DistributedTracingTest , InjectExtractContext)
Definition at line 121 of file test_distributed_tracing.cpp.
TEST_F() [10/16]
TEST_F (DistributedTracingTest , ScopedSpan)
Definition at line 190 of file test_distributed_tracing.cpp.
References monitoring_system::scoped.
TEST_F() [11/16]
TEST_F (DistributedTracingTest , SpanStatus)
Definition at line 257 of file test_distributed_tracing.cpp.
TEST_F() [12/16]
TEST_F (DistributedTracingTest , SpanTags)
Definition at line 238 of file test_distributed_tracing.cpp.
TEST_F() [13/16]
TEST_F (DistributedTracingTest , StartSpanFromContext)
Definition at line 146 of file test_distributed_tracing.cpp.
References monitoring_system::trace_context::baggage, monitoring_system::trace_context::span_id, and monitoring_system::trace_context::trace_id.
TEST_F() [14/16]
TEST_F (DistributedTracingTest , TraceContextPropagation)
Definition at line 85 of file test_distributed_tracing.cpp.
TEST_F() [15/16]
TEST_F (DistributedTracingTest , TraceMacros)
Definition at line 329 of file test_distributed_tracing.cpp.
References monitoring_system::distributed_tracer::get_current_span(), monitoring_system::global_tracer(), TRACE_CHILD_SPAN, and TRACE_SPAN.
TEST_F() [16/16]
TEST_F (DistributedTracingTest , W3CTraceContextFormat)
Definition at line 103 of file test_distributed_tracing.cpp.
References monitoring_system::trace_context::from_w3c_traceparent(), monitoring_system::trace_context::span_id, monitoring_system::trace_context::to_w3c_traceparent(), monitoring_system::trace_context::trace_flags, and monitoring_system::trace_context::trace_id.