Messaging System: container_module::integration::messaging_container_builder Class Reference
container_module::integration::messaging_container_builder Class Reference
Builder pattern for messaging containers.
#include <messaging_integration.h>
Public Member Functions
messaging_container_builder ()
messaging_container_builder & source (const std::string &id, const std::string &sub_id="")
messaging_container_builder & target (const std::string &id, const std::string &sub_id="")
messaging_container_builder & message_type (const std::string &type)
template<typename T >
messaging_container_builder & add_value (const std::string &key, T &&value)
messaging_container_builder & optimize_for_size ()
messaging_container_builder & optimize_for_speed ()
std::shared_ptr< value_container > build ()
Detailed Description
Builder pattern for messaging containers.
Definition at line 125 of file messaging_integration.h.
Constructor & Destructor Documentation
messaging_container_builder()
container_module::integration::messaging_container_builder::messaging_container_builder ()
Definition at line 205 of file messaging_integration.cpp.
Member Function Documentation
add_value()
template<typename T > messaging_container_builder & container_module::integration::messaging_container_builder::add_value (const std::string & key, T && value)
Definition at line 167 of file messaging_integration.h.
Referenced by AdvancedContainerExample::demonstrate_multithreaded_operations().
build()
std::shared_ptr< value_container > container_module::integration::messaging_container_builder::build ()
Definition at line 238 of file messaging_integration.cpp.
Referenced by AdvancedContainerExample::demonstrate_multithreaded_operations().
message_type()
messaging_container_builder & container_module::integration::messaging_container_builder::message_type (const std::string & type)
Definition at line 221 of file messaging_integration.cpp.
Referenced by AdvancedContainerExample::demonstrate_multithreaded_operations().
optimize_for_size()
messaging_container_builder & container_module::integration::messaging_container_builder::optimize_for_size ()
Definition at line 226 of file messaging_integration.cpp.
optimize_for_speed()
messaging_container_builder & container_module::integration::messaging_container_builder::optimize_for_speed ()
Definition at line 232 of file messaging_integration.cpp.
Referenced by AdvancedContainerExample::demonstrate_multithreaded_operations().
source()
messaging_container_builder & container_module::integration::messaging_container_builder::source (const std::string & id, const std::string & sub_id = "")
Definition at line 209 of file messaging_integration.cpp.
Referenced by AdvancedContainerExample::demonstrate_multithreaded_operations().
target()
messaging_container_builder & container_module::integration::messaging_container_builder::target (const std::string & id, const std::string & sub_id = "")
Definition at line 215 of file messaging_integration.cpp.
Referenced by AdvancedContainerExample::demonstrate_multithreaded_operations().
The documentation for this class was generated from the following files:
libraries/container_system/integration/messaging_integration.h
libraries/container_system/integration/messaging_integration.cpp