Messaging System: utility_module::convert_string Class Reference
utility_module::convert_string Class Reference
Provides utilities for string encoding conversion, Base64 encoding/decoding, and substring operations like splitting or replacing.
#include <convert_string.h>
Static Public Member Functions
static std::tuple< result_wrapper< std::string >, result_wrapper< bool > > to_string (const std::vector< uint8_t > &data)
template<typename T >
static std::tuple< result_wrapper< std::string >, result_wrapper< bool > > to_string (const T &value)
static std::tuple< result_wrapper< std::string >, result_wrapper< bool > > to_base64 (const std::vector< uint8_t > &data)
static std::tuple< result_wrapper< std::vector< uint8_t > >, result_wrapper< bool > > from_base64 (const std::string &encoded)
static void replace (std::string &str, const std::string &from, const std::string &to)
static std::tuple< result_wrapper< std::string >, result_wrapper< bool > > utf8_to_system (const std::string &utf8_str)
static std::tuple< result_wrapper< std::vector< uint8_t > >, result_wrapper< bool > > to_array (const std::string &str)
static auto to_string (const std::wstring &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a std::wstring to a std::string using the system encoding.
static auto to_string (std::wstring_view value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a std::wstring_view to a std::string using the system encoding.
static auto to_wstring (const std::string &value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > >
Converts a std::string (system-encoded) to a std::wstring.
static auto to_wstring (std::string_view value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > >
Converts a std::string_view (system-encoded) to a std::wstring.
static auto get_system_code_page () -> int
Retrieves the system code page used for conversions.
static auto system_to_utf8 (const std::string &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a system-encoded string to UTF-8.
static auto utf8_to_system (const std::string &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a UTF-8 encoded string to the system encoding.
static auto split (const std::string &source, const std::string &token) -> std::tuple< std::optional< std::vector< std::string > >, std::optional< std::string > >
Splits a string by a given delimiter.
static auto to_array (const std::string &value) -> std::tuple< std::optional< std::vector< uint8_t > >, std::optional< std::string > >
Converts a system-encoded string to a UTF-8 byte array.
static auto to_string (const std::vector< uint8_t > &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a UTF-8 byte array to a system-encoded string.
static auto to_base64 (const std::vector< uint8_t > &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Encodes a byte array into a Base64 string.
static auto from_base64 (const std::string &base64_str) -> std::tuple< std::vector< uint8_t >, std::optional< std::string > >
Decodes a Base64 string into a byte array.
static auto replace (std::string &source, const std::string &token, const std::string &target) -> std::optional< std::string >
Replaces all occurrences of token in source with target, in place.
static auto replace2 (const std::string &source, const std::string &token, const std::string &target) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Replaces all occurrences of token in source with target, returning a new string.
static auto to_string (const std::wstring &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a std::wstring to a std::string using the system encoding.
static auto to_string (std::wstring_view value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a std::wstring_view to a std::string using the system encoding.
static auto to_wstring (const std::string &value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > >
Converts a std::string (system-encoded) to a std::wstring.
static auto to_wstring (std::string_view value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > >
Converts a std::string_view (system-encoded) to a std::wstring.
static auto get_system_code_page () -> int
Retrieves the system code page used for conversions.
static auto system_to_utf8 (const std::string &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a system-encoded string to UTF-8.
static auto utf8_to_system (const std::string &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a UTF-8 encoded string to the system encoding.
static auto split (const std::string &source, const std::string &token) -> std::tuple< std::optional< std::vector< std::string > >, std::optional< std::string > >
Splits a string by a given delimiter.
static auto to_array (const std::string &value) -> std::tuple< std::optional< std::vector< uint8_t > >, std::optional< std::string > >
Converts a system-encoded string to a UTF-8 byte array.
static auto to_string (const std::vector< uint8_t > &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a UTF-8 byte array to a system-encoded string.
static auto to_base64 (const std::vector< uint8_t > &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Encodes a byte array into a Base64 string.
static auto from_base64 (const std::string &base64_str) -> std::tuple< std::vector< uint8_t >, std::optional< std::string > >
Decodes a Base64 string into a byte array.
static auto replace (std::string &source, const std::string &token, const std::string &target) -> std::optional< std::string >
Replaces all occurrences of token in source with target, in place.
static auto replace2 (const std::string &source, const std::string &token, const std::string &target) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Replaces all occurrences of token in source with target, returning a new string.
static auto to_string (const std::wstring &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a std::wstring to a std::string using the system encoding.
static auto to_string (std::wstring_view value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a std::wstring_view to a std::string using the system encoding.
static auto to_wstring (const std::string &value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > >
Converts a std::string (system-encoded) to a std::wstring.
static auto to_wstring (std::string_view value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > >
Converts a std::string_view (system-encoded) to a std::wstring.
static auto get_system_code_page () -> int
Retrieves the system code page used for conversions.
static auto system_to_utf8 (const std::string &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a system-encoded string to UTF-8.
static auto utf8_to_system (const std::string &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a UTF-8 encoded string to the system encoding.
static auto split (const std::string &source, const std::string &token) -> std::tuple< std::optional< std::vector< std::string > >, std::optional< std::string > >
Splits a string by a given delimiter.
static auto to_array (const std::string &value) -> std::tuple< std::optional< std::vector< uint8_t > >, std::optional< std::string > >
Converts a system-encoded string to a UTF-8 byte array.
static auto to_string (const std::vector< uint8_t > &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Converts a UTF-8 byte array to a system-encoded string.
static auto to_base64 (const std::vector< uint8_t > &value) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Encodes a byte array into a Base64 string.
static auto from_base64 (const std::string &base64_str) -> std::tuple< std::vector< uint8_t >, std::optional< std::string > >
Decodes a Base64 string into a byte array.
static auto replace (std::string &source, const std::string &token, const std::string &target) -> std::optional< std::string >
Replaces all occurrences of token in source with target, in place.
static auto replace2 (const std::string &source, const std::string &token, const std::string &target) -> std::tuple< std::optional< std::string >, std::optional< std::string > >
Replaces all occurrences of token in source with target, returning a new string.
Detailed Description
Provides utilities for string encoding conversion, Base64 encoding/decoding, and substring operations like splitting or replacing.
This class relies on platform-specific APIs or iconv (when available) to convert strings between different encodings such as UTF-8, UTF-16, UTF-32, and the local system encoding. It also provides methods to handle Base64 encoding/decoding and some basic string manipulation (split, replace).
Encoding Conversions
Typically returns a tuple containing either a successful result (std::optional<T>) and an empty error (std::nullopt), or std::nullopt with an error message describing the failure.
BOM (Byte Order Mark) is handled in certain functions for UTF-8, UTF-16, and UTF-32.
Base64
Encodes and decodes raw byte arrays (std::vector<uint8_t>).
Usage Example
// Converting a wstring to system-encoded string
auto [strOpt, errMsg] = convert_string::to_string(L"안녕하세요");
if (!strOpt) {
    std::cerr << "Error: " << *errMsg << std::endl;
} else {
    std::cout << "Converted string: " << *strOpt << std::endl;
}
This class relies on platform-specific APIs or iconv (when available) to convert strings between different encodings such as UTF-8, UTF-16, UTF-32, and the local system encoding. It also provides methods to handle Base64 encoding/decoding and some basic string manipulation (split, replace).
Encoding Conversions
Typically returns a tuple containing either a successful result (std::optional<T>) and an empty error (std::nullopt), or std::nullopt with an error message describing the failure.
BOM (Byte Order Mark) is handled in certain functions for UTF-8, UTF-16, and UTF-32.
Base64
Encodes and decodes raw byte arrays (std::vector<uint8_t>).
Usage Example
// Converting a wstring to system-encoded string
auto [strOpt, errMsg] = convert_string::to_string(L"안녕하세요");
if (!strOpt) {
    std::cerr << "Error: " << *errMsg << std::endl;
} else {
    std::cout << "Converted string: " << *strOpt << std::endl;
}
This class relies on platform-specific APIs or iconv (when available) to convert strings between different encodings such as UTF-8, UTF-16, UTF-32, and the local system encoding. It also provides methods to handle Base64 encoding/decoding and some basic string manipulation (split, replace).
Encoding Conversions
Typically returns a tuple containing either a successful result (std::optional<T>) and an empty error (std::nullopt), or std::nullopt with an error message describing the failure.
BOM (Byte Order Mark) is handled in certain functions for UTF-8, UTF-16, and UTF-32.
Base64
Encodes and decodes raw byte arrays (std::vector<uint8_t>).
Usage Example
// Converting a wstring to system-encoded string
auto [strOpt, errMsg] = convert_string::to_string(L"안녕하세요");
if (!strOpt) {
    std::cerr << "Error: " << *errMsg << std::endl;
} else {
    std::cout << "Converted string: " << *strOpt << std::endl;
}
Definition at line 114 of file convert_string.h.
Member Function Documentation
from_base64() [1/4]
static auto utility_module::convert_string::from_base64 (const std::string & base64_str) -> std::tuple< std::vector< uint8_t >, std::optional< std::string > > static
Decodes a Base64 string into a byte array.
Parameters
base64_str The Base64-encoded string.
Returns
A tuple of:
std::vector<uint8_t>: The decoded data. May be empty if decoding fails.
std::optional<std::string>: An error message on failure, or std::nullopt on success.
from_base64() [2/4]
static auto utility_module::convert_string::from_base64 (const std::string & base64_str) -> std::tuple< std::vector< uint8_t >, std::optional< std::string > > static
Decodes a Base64 string into a byte array.
Parameters
base64_str The Base64-encoded string.
Returns
A tuple of:
std::vector<uint8_t>: The decoded data. May be empty if decoding fails.
std::optional<std::string>: An error message on failure, or std::nullopt on success.
from_base64() [3/4]
static auto utility_module::convert_string::from_base64 (const std::string & base64_str) -> std::tuple< std::vector< uint8_t >, std::optional< std::string > > static
Decodes a Base64 string into a byte array.
Parameters
base64_str The Base64-encoded string.
Returns
A tuple of:
std::vector<uint8_t>: The decoded data. May be empty if decoding fails.
std::optional<std::string>: An error message on failure, or std::nullopt on success.
from_base64() [4/4]
auto utility_module::convert_string::from_base64 (const std::string & encoded) inline static
Definition at line 194 of file convert_string.h.
Referenced by container_module::value::set_byte_string(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
get_system_code_page() [1/3]
auto utility_module::convert_string::get_system_code_page () -> int static
Retrieves the system code page used for conversions.
Returns
An integer representing the system code page (e.g., CP_ACP on Windows).
On Unix-like systems using iconv, this may return an approximation based on locale info, or a default if detection fails.
Definition at line 313 of file convert_string.cpp.
get_system_code_page() [2/3]
static auto utility_module::convert_string::get_system_code_page () -> int static
Retrieves the system code page used for conversions.
Returns
An integer representing the system code page (e.g., CP_ACP on Windows).
On Unix-like systems using iconv, this may return an approximation based on locale info, or a default if detection fails.
get_system_code_page() [3/3]
static auto utility_module::convert_string::get_system_code_page () -> int static
Retrieves the system code page used for conversions.
Returns
An integer representing the system code page (e.g., CP_ACP on Windows).
On Unix-like systems using iconv, this may return an approximation based on locale info, or a default if detection fails.
replace() [1/4]
static auto utility_module::convert_string::replace (std::string & source, const std::string & token, const std::string & target) -> std::optional< std::string > static
Replaces all occurrences of token in source with target, in place.
Parameters
source The string to modify.
token The substring to find.
target The substring to replace token with.
Returns
std::optional<std::string> containing an error message if replacement fails, or std::nullopt on success.
This function modifies source directly. If token is empty, it returns an error.
replace() [2/4]
static auto utility_module::convert_string::replace (std::string & source, const std::string & token, const std::string & target) -> std::optional< std::string > static
Replaces all occurrences of token in source with target, in place.
Parameters
source The string to modify.
token The substring to find.
target The substring to replace token with.
Returns
std::optional<std::string> containing an error message if replacement fails, or std::nullopt on success.
This function modifies source directly. If token is empty, it returns an error.
replace() [3/4]
static auto utility_module::convert_string::replace (std::string & source, const std::string & token, const std::string & target) -> std::optional< std::string > static
Replaces all occurrences of token in source with target, in place.
Parameters
source The string to modify.
token The substring to find.
target The substring to replace token with.
Returns
std::optional<std::string> containing an error message if replacement fails, or std::nullopt on success.
This function modifies source directly. If token is empty, it returns an error.
replace() [4/4]
auto utility_module::convert_string::replace (std::string & str, const std::string & from, const std::string & to) inline static
Definition at line 270 of file convert_string.h.
Referenced by container_module::value::convert_specific_string(), container_module::value::convert_specific_string(), and TEST_F().
replace2() [1/3]
auto utility_module::convert_string::replace2 (const std::string & source, const std::string & token, const std::string & target) -> std::tuple<std::optional<std::string>, std::optional<std::string>> static
Replaces all occurrences of token in source with target, returning a new string.
Parameters
source The source string (unchanged).
token The substring to find.
target The substring to replace token with.
Returns
A tuple of:
std::optional<std::string>: The modified string on success.
std::optional<std::string>: An error message if replacement fails.
Definition at line 438 of file convert_string.cpp.
References utility_module::formatter::format_to().
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
replace2() [2/3]
static auto utility_module::convert_string::replace2 (const std::string & source, const std::string & token, const std::string & target) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Replaces all occurrences of token in source with target, returning a new string.
Parameters
source The source string (unchanged).
token The substring to find.
target The substring to replace token with.
Returns
A tuple of:
std::optional<std::string>: The modified string on success.
std::optional<std::string>: An error message if replacement fails.
replace2() [3/3]
static auto utility_module::convert_string::replace2 (const std::string & source, const std::string & token, const std::string & target) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Replaces all occurrences of token in source with target, returning a new string.
Parameters
source The source string (unchanged).
token The substring to find.
target The substring to replace token with.
Returns
A tuple of:
std::optional<std::string>: The modified string on success.
std::optional<std::string>: An error message if replacement fails.
split() [1/3]
auto utility_module::convert_string::split (const std::string & source, const std::string & token) -> std::tuple<std::optional<std::vector<std::string>>, std::optional<std::string>> static
Splits a string by a given delimiter.
Parameters
source The source string to split.
token The delimiter substring.
Returns
A tuple of:
std::optional<std::vector<std::string>>: A vector of tokens on success.
std::optional<std::string>: An error message if splitting fails.
If token is empty, splitting cannot proceed and an error is returned.
Definition at line 357 of file convert_string.cpp.
split() [2/3]
static auto utility_module::convert_string::split (const std::string & source, const std::string & token) -> std::tuple< std::optional< std::vector< std::string > >, std::optional< std::string > > static
Splits a string by a given delimiter.
Parameters
source The source string to split.
token The delimiter substring.
Returns
A tuple of:
std::optional<std::vector<std::string>>: A vector of tokens on success.
std::optional<std::string>: An error message if splitting fails.
If token is empty, splitting cannot proceed and an error is returned.
split() [3/3]
static auto utility_module::convert_string::split (const std::string & source, const std::string & token) -> std::tuple< std::optional< std::vector< std::string > >, std::optional< std::string > > static
Splits a string by a given delimiter.
Parameters
source The source string to split.
token The delimiter substring.
Returns
A tuple of:
std::optional<std::vector<std::string>>: A vector of tokens on success.
std::optional<std::string>: An error message if splitting fails.
If token is empty, splitting cannot proceed and an error is returned.
system_to_utf8() [1/3]
auto utility_module::convert_string::system_to_utf8 (const std::string & value) -> std::tuple<std::optional<std::string>, std::optional<std::string>> static
Converts a system-encoded string to UTF-8.
Parameters
value The input string in system encoding.
Returns
A tuple of:
std::optional<std::string>: The UTF-8 encoded string on success.
std::optional<std::string>: An error message on failure.
Definition at line 333 of file convert_string.cpp.
system_to_utf8() [2/3]
static auto utility_module::convert_string::system_to_utf8 (const std::string & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a system-encoded string to UTF-8.
Parameters
value The input string in system encoding.
Returns
A tuple of:
std::optional<std::string>: The UTF-8 encoded string on success.
std::optional<std::string>: An error message on failure.
system_to_utf8() [3/3]
static auto utility_module::convert_string::system_to_utf8 (const std::string & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a system-encoded string to UTF-8.
Parameters
value The input string in system encoding.
Returns
A tuple of:
std::optional<std::string>: The UTF-8 encoded string on success.
std::optional<std::string>: An error message on failure.
to_array() [1/4]
auto utility_module::convert_string::to_array (const std::string & str) inline static
Definition at line 296 of file convert_string.h.
Referenced by container_module::value::convert_specific_string(), container_module::value_container::serialize_array(), container_module::value::set_string(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
to_array() [2/4]
static auto utility_module::convert_string::to_array (const std::string & value) -> std::tuple< std::optional< std::vector< uint8_t > >, std::optional< std::string > > static
Converts a system-encoded string to a UTF-8 byte array.
Parameters
value The input string in system encoding.
Returns
A tuple of:
std::optional<std::vector<uint8_t>>: The UTF-8 byte array on success.
std::optional<std::string>: An error message on failure.
to_array() [3/4]
static auto utility_module::convert_string::to_array (const std::string & value) -> std::tuple< std::optional< std::vector< uint8_t > >, std::optional< std::string > > static
Converts a system-encoded string to a UTF-8 byte array.
Parameters
value The input string in system encoding.
Returns
A tuple of:
std::optional<std::vector<uint8_t>>: The UTF-8 byte array on success.
std::optional<std::string>: An error message on failure.
to_array() [4/4]
static auto utility_module::convert_string::to_array (const std::string & value) -> std::tuple< std::optional< std::vector< uint8_t > >, std::optional< std::string > > static
Converts a system-encoded string to a UTF-8 byte array.
Parameters
value The input string in system encoding.
Returns
A tuple of:
std::optional<std::vector<uint8_t>>: The UTF-8 byte array on success.
std::optional<std::string>: An error message on failure.
to_base64() [1/4]
auto utility_module::convert_string::to_base64 (const std::vector< uint8_t > & data) inline static
Definition at line 155 of file convert_string.h.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and container_module::bytes_value::to_string().
to_base64() [2/4]
static auto utility_module::convert_string::to_base64 (const std::vector< uint8_t > & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Encodes a byte array into a Base64 string.
Parameters
value The raw byte array to encode.
Returns
A tuple of:
std::optional<std::string>: The Base64-encoded string on success.
std::optional<std::string>: An error message if encoding fails.
Typically, Base64 encoding should not fail unless the input is extremely large and memory allocation fails.
to_base64() [3/4]
static auto utility_module::convert_string::to_base64 (const std::vector< uint8_t > & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Encodes a byte array into a Base64 string.
Parameters
value The raw byte array to encode.
Returns
A tuple of:
std::optional<std::string>: The Base64-encoded string on success.
std::optional<std::string>: An error message if encoding fails.
Typically, Base64 encoding should not fail unless the input is extremely large and memory allocation fails.
to_base64() [4/4]
static auto utility_module::convert_string::to_base64 (const std::vector< uint8_t > & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Encodes a byte array into a Base64 string.
Parameters
value The raw byte array to encode.
Returns
A tuple of:
std::optional<std::string>: The Base64-encoded string on success.
std::optional<std::string>: An error message if encoding fails.
Typically, Base64 encoding should not fail unless the input is extremely large and memory allocation fails.
to_string() [1/11]
auto utility_module::convert_string::to_string (const std::vector< uint8_t > & data) inline static
Definition at line 117 of file convert_string.h.
Referenced by container_module::value::convert_specific_string(), container_module::value_container::deserialize(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and container_module::string_value::to_string().
to_string() [2/11]
static auto utility_module::convert_string::to_string (const std::vector< uint8_t > & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a UTF-8 byte array to a system-encoded string.
Parameters
value The input byte array.
Returns
A tuple with:
std::optional<std::string>: The system-encoded string on success.
std::optional<std::string>: An error message on failure.
to_string() [3/11]
static auto utility_module::convert_string::to_string (const std::vector< uint8_t > & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a UTF-8 byte array to a system-encoded string.
Parameters
value The input byte array.
Returns
A tuple with:
std::optional<std::string>: The system-encoded string on success.
std::optional<std::string>: An error message on failure.
to_string() [4/11]
static auto utility_module::convert_string::to_string (const std::vector< uint8_t > & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a UTF-8 byte array to a system-encoded string.
Parameters
value The input byte array.
Returns
A tuple with:
std::optional<std::string>: The system-encoded string on success.
std::optional<std::string>: An error message on failure.
to_string() [5/11]
auto utility_module::convert_string::to_string (const std::wstring & value) -> std::tuple<std::optional<std::string>, std::optional<std::string>> static
Converts a std::wstring to a std::string using the system encoding.
Parameters
value The wide-string input.
Returns
A tuple of:
std::optional<std::string>: The converted narrow string on success, or std::nullopt on failure.
std::optional<std::string>: The error message if conversion fails, otherwise std::nullopt.
On Windows, this typically uses the current code page. On Unix-like systems, it may use iconv or locale-based conversion functions.
Definition at line 136 of file convert_string.cpp.
to_string() [6/11]
static auto utility_module::convert_string::to_string (const std::wstring & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a std::wstring to a std::string using the system encoding.
Parameters
value The wide-string input.
Returns
A tuple of:
std::optional<std::string>: The converted narrow string on success, or std::nullopt on failure.
std::optional<std::string>: The error message if conversion fails, otherwise std::nullopt.
On Windows, this typically uses the current code page. On Unix-like systems, it may use iconv or locale-based conversion functions.
to_string() [7/11]
static auto utility_module::convert_string::to_string (const std::wstring & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a std::wstring to a std::string using the system encoding.
Parameters
value The wide-string input.
Returns
A tuple of:
std::optional<std::string>: The converted narrow string on success, or std::nullopt on failure.
std::optional<std::string>: The error message if conversion fails, otherwise std::nullopt.
On Windows, this typically uses the current code page. On Unix-like systems, it may use iconv or locale-based conversion functions.
to_string() [8/11]
template<typename T > static std::tuple< result_wrapper< std::string >, result_wrapper< bool > > utility_module::convert_string::to_string (const T & value) inline static
Definition at line 138 of file convert_string.h.
to_string() [9/11]
auto utility_module::convert_string::to_string (std::wstring_view value) -> std::tuple<std::optional<std::string>, std::optional<std::string>> static
Converts a std::wstring_view to a std::string using the system encoding.
Parameters
value The wide-string view.
Returns
Same tuple semantics as to_string(const std::wstring&).
This is a convenience overload for handling string views without copying the entire wide string first.
Definition at line 151 of file convert_string.cpp.
to_string() [10/11]
static auto utility_module::convert_string::to_string (std::wstring_view value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a std::wstring_view to a std::string using the system encoding.
Parameters
value The wide-string view.
Returns
Same tuple semantics as to_string(const std::wstring&).
This is a convenience overload for handling string views without copying the entire wide string first.
to_string() [11/11]
static auto utility_module::convert_string::to_string (std::wstring_view value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a std::wstring_view to a std::string using the system encoding.
Parameters
value The wide-string view.
Returns
Same tuple semantics as to_string(const std::wstring&).
This is a convenience overload for handling string views without copying the entire wide string first.
to_wstring() [1/6]
auto utility_module::convert_string::to_wstring (const std::string & value) -> std::tuple<std::optional<std::wstring>, std::optional<std::string>> static
Converts a std::string (system-encoded) to a std::wstring.
Parameters
value The narrow string in system encoding.
Returns
A tuple containing:
std::optional<std::wstring>: The converted wide string on success.
std::optional<std::string>: An error message if conversion fails.
Definition at line 166 of file convert_string.cpp.
Referenced by fmt::formatter< typed_thread_pool_module::job_types, wchar_t >::format(), and TEST_F().
to_wstring() [2/6]
static auto utility_module::convert_string::to_wstring (const std::string & value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > > static
Converts a std::string (system-encoded) to a std::wstring.
Parameters
value The narrow string in system encoding.
Returns
A tuple containing:
std::optional<std::wstring>: The converted wide string on success.
std::optional<std::string>: An error message if conversion fails.
to_wstring() [3/6]
static auto utility_module::convert_string::to_wstring (const std::string & value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > > static
Converts a std::string (system-encoded) to a std::wstring.
Parameters
value The narrow string in system encoding.
Returns
A tuple containing:
std::optional<std::wstring>: The converted wide string on success.
std::optional<std::string>: An error message if conversion fails.
to_wstring() [4/6]
auto utility_module::convert_string::to_wstring (std::string_view value) -> std::tuple<std::optional<std::wstring>, std::optional<std::string>> static
Converts a std::string_view (system-encoded) to a std::wstring.
Parameters
value The narrow string view in system encoding.
Returns
Same tuple semantics as to_wstring(const std::string&).
Definition at line 181 of file convert_string.cpp.
to_wstring() [5/6]
static auto utility_module::convert_string::to_wstring (std::string_view value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > > static
Converts a std::string_view (system-encoded) to a std::wstring.
Parameters
value The narrow string view in system encoding.
Returns
Same tuple semantics as to_wstring(const std::string&).
to_wstring() [6/6]
static auto utility_module::convert_string::to_wstring (std::string_view value) -> std::tuple< std::optional< std::wstring >, std::optional< std::string > > static
Converts a std::string_view (system-encoded) to a std::wstring.
Parameters
value The narrow string view in system encoding.
Returns
Same tuple semantics as to_wstring(const std::string&).
utf8_to_system() [1/4]
auto utility_module::convert_string::utf8_to_system (const std::string & utf8_str) inline static
Definition at line 279 of file convert_string.h.
Referenced by database::postgres_manager::connect().
utf8_to_system() [2/4]
static auto utility_module::convert_string::utf8_to_system (const std::string & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a UTF-8 encoded string to the system encoding.
Parameters
value The UTF-8 encoded input string.
Returns
Same tuple semantics as system_to_utf8().
utf8_to_system() [3/4]
static auto utility_module::convert_string::utf8_to_system (const std::string & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a UTF-8 encoded string to the system encoding.
Parameters
value The UTF-8 encoded input string.
Returns
Same tuple semantics as system_to_utf8().
utf8_to_system() [4/4]
static auto utility_module::convert_string::utf8_to_system (const std::string & value) -> std::tuple< std::optional< std::string >, std::optional< std::string > > static
Converts a UTF-8 encoded string to the system encoding.
Parameters
value The UTF-8 encoded input string.
Returns
Same tuple semantics as system_to_utf8().
The documentation for this class was generated from the following files:
libraries/container_system/utilities/conversion/convert_string.h
libraries/thread_system/modular_structure/core/include/thread_system_core/utilities/conversion/convert_string.h
libraries/thread_system/modular_structure/core/src/utilities/conversion/convert_string.h
libraries/thread_system/sources/utilities/conversion/convert_string.h
libraries/thread_system/modular_structure/core/src/utilities/conversion/convert_string.cpp
libraries/thread_system/sources/utilities/conversion/convert_string.cpp