Messaging System: fmt::formatter< typed_thread_pool_module::typed_job_queue_t< job_type > > Struct Template Reference
fmt::formatter< typed_thread_pool_module::typed_job_queue_t< job_type > > Struct Template Reference
Specialization of fmt::formatter for typed_job_queue_t<job_type> when using the {fmt} library.
#include <typed_job_queue.h>
Public Member Functions
template<typename FormatContext >
auto format (const typed_thread_pool_module::typed_job_queue_t< job_type > &item, FormatContext &ctx) const
Formats a typed_job_queue_t<job_type> into a string view for {fmt}.
template<typename FormatContext >
auto format (const typed_thread_pool_module::typed_job_queue_t< job_type > &item, FormatContext &ctx) const
Formats a typed_job_queue_t<job_type> into a string view for {fmt}.
template<typename FormatContext >
auto format (const typed_thread_pool_module::typed_job_queue_t< job_type > &item, FormatContext &ctx) const
Formats a typed_job_queue_t<job_type> into a string view for {fmt}.
Detailed Description
template<typename job_type>
struct fmt::formatter< typed_thread_pool_module::typed_job_queue_t< job_type > >
Specialization of fmt::formatter for typed_job_queue_t<job_type> when using the {fmt} library.
This allows a typed_job_queue_t<job_type> to be formatted using the {fmt} library, by invoking the to_string() method on the instance.
Template Parameters
job_type The type representing priority levels.
Definition at line 352 of file typed_job_queue.h.
Member Function Documentation
format() [1/3]
template<typename job_type > template<typename FormatContext > auto fmt::formatter< typed_thread_pool_module::typed_job_queue_t< job_type > >::format (const typed_thread_pool_module::typed_job_queue_t< job_type > & item, FormatContext & ctx) const inline
Formats a typed_job_queue_t<job_type> into a string view for {fmt}.
Template Parameters
FormatContext The context type provided by {fmt}.
Parameters
item The typed_job_queue_t instance to format.
ctx The {fmt} context where the output will be appended.
Returns
An iterator to the end of the formatted output.
Definition at line 363 of file typed_job_queue.h.
References typed_thread_pool_module::typed_job_queue_t< job_type >::to_string().
format() [2/3]
template<typename job_type > template<typename FormatContext > auto fmt::formatter< typed_thread_pool_module::typed_job_queue_t< job_type > >::format (const typed_thread_pool_module::typed_job_queue_t< job_type > & item, FormatContext & ctx) const inline
Formats a typed_job_queue_t<job_type> into a string view for {fmt}.
Template Parameters
FormatContext The context type provided by {fmt}.
Parameters
item The typed_job_queue_t instance to format.
ctx The {fmt} context where the output will be appended.
Returns
An iterator to the end of the formatted output.
Definition at line 363 of file typed_job_queue.h.
References typed_thread_pool_module::typed_job_queue_t< job_type >::to_string().
format() [3/3]
template<typename job_type > template<typename FormatContext > auto fmt::formatter< typed_thread_pool_module::typed_job_queue_t< job_type > >::format (const typed_thread_pool_module::typed_job_queue_t< job_type > & item, FormatContext & ctx) const inline
Formats a typed_job_queue_t<job_type> into a string view for {fmt}.
Template Parameters
FormatContext The context type provided by {fmt}.
Parameters
item The typed_job_queue_t instance to format.
ctx The {fmt} context where the output will be appended.
Returns
An iterator to the end of the formatted output.
Definition at line 363 of file typed_job_queue.h.
References typed_thread_pool_module::typed_job_queue_t< job_type >::to_string().
The documentation for this struct was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/typed_thread_pool/scheduling/typed_job_queue.h
libraries/thread_system/modular_structure/core/src/typed_thread_pool/scheduling/typed_job_queue.h
libraries/thread_system/sources/typed_thread_pool/scheduling/typed_job_queue.h