Messaging System: kcenon::messaging::integrations::system_integrator Class Reference
kcenon::messaging::integrations::system_integrator Class Reference
#include <system_integrator.h>
Classes
struct system_health
Public Member Functions
system_integrator (const config::messaging_config &config={})
~system_integrator ()
bool initialize ()
void shutdown ()
bool is_running () const
messaging_system_orchestrator & get_orchestrator ()
const messaging_system_orchestrator & get_orchestrator () const
core::message_bus * get_message_bus () const
service_container & get_container ()
template<typename T >
std::shared_ptr< T > get_service (const std::string &name)
template<typename T >
std::shared_ptr< T > get_service ()
bool publish (const std::string &topic, const core::message_payload &payload, const std::string &sender="")
void subscribe (const std::string &topic, core::message_handler handler)
class external_system_manager & get_external_systems ()
const config::messaging_config & get_config () const
system_health check_system_health () const
Static Public Member Functions
static std::unique_ptr< system_integrator > create_default ()
static std::unique_ptr< system_integrator > create_for_environment (const std::string &environment)
Detailed Description
Definition at line 9 of file system_integrator.h.
Constructor & Destructor Documentation
system_integrator()
kcenon::messaging::integrations::system_integrator::system_integrator (const config::messaging_config & config = {}) explicit
Definition at line 210 of file system_integrator.cpp.
~system_integrator()
kcenon::messaging::integrations::system_integrator::~system_integrator ()
Definition at line 214 of file system_integrator.cpp.
References shutdown().
Member Function Documentation
check_system_health()
system_integrator::system_health kcenon::messaging::integrations::system_integrator::check_system_health () const
Definition at line 254 of file system_integrator.cpp.
References kcenon::messaging::integrations::system_integrator::system_health::active_services, kcenon::messaging::integrations::system_integrator::system_health::all_services_healthy, get_message_bus(), kcenon::messaging::integrations::messaging_system_orchestrator::get_registered_adapters(), kcenon::messaging::integrations::system_integrator::system_health::last_check, kcenon::messaging::integrations::system_integrator::system_health::message_bus_healthy, and kcenon::messaging::integrations::system_integrator::system_health::total_messages_processed.
Referenced by PYBIND11_MODULE().
create_default()
std::unique_ptr< system_integrator > kcenon::messaging::integrations::system_integrator::create_default () static
Definition at line 274 of file system_integrator.cpp.
References kcenon::messaging::config::config_builder::build(), kcenon::messaging::config::config_builder::enable_compression(), kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), and kcenon::messaging::config::config_builder::set_worker_threads().
Referenced by PYBIND11_MODULE(), SystemIntegratorPerformanceTest::SetUp(), and TEST_F().
create_for_environment()
std::unique_ptr< system_integrator > kcenon::messaging::integrations::system_integrator::create_for_environment (const std::string & environment) static
Definition at line 286 of file system_integrator.cpp.
References kcenon::messaging::config::config_builder::build(), and kcenon::messaging::config::config_builder::set_environment().
Referenced by PYBIND11_MODULE(), and TEST_F().
get_config()
const config::messaging_config & kcenon::messaging::integrations::system_integrator::get_config () const inline
Definition at line 53 of file system_integrator.h.
References kcenon::messaging::integrations::messaging_system_orchestrator::get_config().
get_container()
service_container & kcenon::messaging::integrations::system_integrator::get_container () inline
Definition at line 27 of file system_integrator.h.
References kcenon::messaging::integrations::messaging_system_orchestrator::get_container().
get_external_systems()
class external_system_manager & kcenon::messaging::integrations::system_integrator::get_external_systems () inline
Definition at line 48 of file system_integrator.h.
References kcenon::messaging::integrations::messaging_system_orchestrator::get_external_systems().
get_message_bus()
core::message_bus * kcenon::messaging::integrations::system_integrator::get_message_bus () const inline
Definition at line 23 of file system_integrator.h.
References kcenon::messaging::integrations::messaging_system_orchestrator::get_message_bus().
Referenced by check_system_health(), publish(), and subscribe().
get_orchestrator() [1/2]
messaging_system_orchestrator & kcenon::messaging::integrations::system_integrator::get_orchestrator () inline
Definition at line 20 of file system_integrator.h.
get_orchestrator() [2/2]
const messaging_system_orchestrator & kcenon::messaging::integrations::system_integrator::get_orchestrator () const inline
Definition at line 21 of file system_integrator.h.
get_service() [1/2]
template<typename T > std::shared_ptr< T > kcenon::messaging::integrations::system_integrator::get_service () inline
Definition at line 38 of file system_integrator.h.
References kcenon::messaging::integrations::messaging_system_orchestrator::get_container(), and kcenon::messaging::integrations::service_container::resolve().
get_service() [2/2]
template<typename T > std::shared_ptr< T > kcenon::messaging::integrations::system_integrator::get_service (const std::string & name) inline
Definition at line 33 of file system_integrator.h.
References kcenon::messaging::integrations::messaging_system_orchestrator::get_container(), and kcenon::messaging::integrations::service_container::resolve().
initialize()
bool kcenon::messaging::integrations::system_integrator::initialize ()
Definition at line 218 of file system_integrator.cpp.
References kcenon::messaging::integrations::messaging_system_orchestrator::initialize().
Referenced by PYBIND11_MODULE().
is_running()
bool kcenon::messaging::integrations::system_integrator::is_running () const
Definition at line 237 of file system_integrator.cpp.
References kcenon::messaging::integrations::messaging_system_orchestrator::is_running().
Referenced by PYBIND11_MODULE().
publish()
bool kcenon::messaging::integrations::system_integrator::publish (const std::string & topic, const core::message_payload & payload, const std::string & sender = "")
Definition at line 241 of file system_integrator.cpp.
References get_message_bus().
Referenced by PYBIND11_MODULE().
shutdown()
void kcenon::messaging::integrations::system_integrator::shutdown ()
Definition at line 230 of file system_integrator.cpp.
References kcenon::messaging::integrations::messaging_system_orchestrator::shutdown().
Referenced by PYBIND11_MODULE(), and ~system_integrator().
subscribe()
void kcenon::messaging::integrations::system_integrator::subscribe (const std::string & topic, core::message_handler handler)
Definition at line 247 of file system_integrator.cpp.
References get_message_bus().
Referenced by PYBIND11_MODULE().
The documentation for this class was generated from the following files:
application_layer/include/kcenon/messaging/integrations/system_integrator.h
application_layer/src/kcenon/messaging/integrations/system_integrator.cpp