Messaging System: thread_module::hazard_pointer_manager Class Reference
thread_module::hazard_pointer_manager Class Reference
Thread-safe memory reclamation using hazard pointers.
#include <hazard_pointer.h>
Classes
class hazard_pointer
RAII wrapper for a hazard pointer slot.
struct statistics
Get statistics about the hazard pointer system.
Public Member Functions
hazard_pointer_manager (size_t max_threads=128, size_t pointers_per_thread=4)
Constructor.
~hazard_pointer_manager ()
Destructor - ensures all retired objects are reclaimed.
hazard_pointer_manager (const hazard_pointer_manager &)=delete
hazard_pointer_manager & operator= (const hazard_pointer_manager &)=delete
hazard_pointer_manager (hazard_pointer_manager &&)=delete
hazard_pointer_manager & operator= (hazard_pointer_manager &&)=delete
auto acquire () -> hazard_pointer
Acquire a hazard pointer.
template<typename T >
auto retire (T *ptr, std::function< void(T *)> deleter=std::default_delete< T >{}) -> void
Retire a pointer for later reclamation.
auto scan_and_reclaim () -> void
Force a scan and reclaim cycle.
auto get_statistics () const -> statistics
hazard_pointer_manager (size_t max_threads=128, size_t pointers_per_thread=4)
Constructor.
~hazard_pointer_manager ()
Destructor - ensures all retired objects are reclaimed.
hazard_pointer_manager (const hazard_pointer_manager &)=delete
hazard_pointer_manager & operator= (const hazard_pointer_manager &)=delete
hazard_pointer_manager (hazard_pointer_manager &&)=delete
hazard_pointer_manager & operator= (hazard_pointer_manager &&)=delete
auto acquire () -> hazard_pointer
Acquire a hazard pointer.
template<typename T >
auto retire (T *ptr, std::function< void(T *)> deleter=std::default_delete< T >{}) -> void
Retire a pointer for later reclamation.
auto scan_and_reclaim () -> void
Force a scan and reclaim cycle.
auto get_statistics () const -> statistics
hazard_pointer_manager (size_t max_threads=128, size_t pointers_per_thread=4)
Constructor.
~hazard_pointer_manager ()
Destructor - ensures all retired objects are reclaimed.
hazard_pointer_manager (const hazard_pointer_manager &)=delete
hazard_pointer_manager & operator= (const hazard_pointer_manager &)=delete
hazard_pointer_manager (hazard_pointer_manager &&)=delete
hazard_pointer_manager & operator= (hazard_pointer_manager &&)=delete
auto acquire () -> hazard_pointer
Acquire a hazard pointer.
template<typename T >
auto retire (T *ptr, std::function< void(T *)> deleter=std::default_delete< T >{}) -> void
Retire a pointer for later reclamation.
auto scan_and_reclaim () -> void
Force a scan and reclaim cycle.
auto get_statistics () const -> statistics
Detailed Description
Thread-safe memory reclamation using hazard pointers.
This class implements the hazard pointer technique for safe memory reclamation in lock-free data structures. It prevents the ABA problem and ensures that memory is not freed while other threads might still be accessing it.
Definition at line 59 of file hazard_pointer.h.
Constructor & Destructor Documentation
hazard_pointer_manager() [1/9]
thread_module::hazard_pointer_manager::hazard_pointer_manager (size_t max_threads = 128, size_t pointers_per_thread = 4) explicit
Constructor.
Constructs a hazard pointer manager with specified capacity.
Parameters
max_threads Maximum number of threads that will use hazard pointers
pointers_per_thread Number of hazard pointers per thread
Implementation details:
Pre-allocates hazard records for maximum thread count
Each record can hold multiple hazard pointers per thread
Records are linked in a lock-free list for efficient access
Uses compare-and-swap to build the record list atomically
Memory Layout:
Each HazardRecord contains an array of atomic pointers
Records are organized as a singly-linked list
Thread ownership is tracked per record
Parameters
max_threads Maximum number of threads that will use hazard pointers
pointers_per_thread Number of hazard pointers available per thread
Definition at line 93 of file hazard_pointer.cpp.
~hazard_pointer_manager() [1/3]
thread_module::hazard_pointer_manager::~hazard_pointer_manager ()
Destructor - ensures all retired objects are reclaimed.
Destroys the hazard pointer manager and reclaims all memory.
Implementation details:
Performs final scan to reclaim all possible retired memory
Deallocates all hazard records in the global list
Ensures no memory leaks from hazard pointer infrastructure
Safe to call even if threads are still using hazard pointers
Definition at line 120 of file hazard_pointer.cpp.
References scan_and_reclaim().
hazard_pointer_manager() [2/9]
thread_module::hazard_pointer_manager::hazard_pointer_manager (const hazard_pointer_manager &) delete
hazard_pointer_manager() [3/9]
thread_module::hazard_pointer_manager::hazard_pointer_manager (hazard_pointer_manager &&) delete
hazard_pointer_manager() [4/9]
thread_module::hazard_pointer_manager::hazard_pointer_manager (size_t max_threads = 128, size_t pointers_per_thread = 4) explicit
Constructor.
Parameters
max_threads Maximum number of threads that will use hazard pointers
pointers_per_thread Number of hazard pointers per thread
~hazard_pointer_manager() [2/3]
thread_module::hazard_pointer_manager::~hazard_pointer_manager ()
Destructor - ensures all retired objects are reclaimed.
hazard_pointer_manager() [5/9]
thread_module::hazard_pointer_manager::hazard_pointer_manager (const hazard_pointer_manager &) delete
hazard_pointer_manager() [6/9]
thread_module::hazard_pointer_manager::hazard_pointer_manager (hazard_pointer_manager &&) delete
hazard_pointer_manager() [7/9]
thread_module::hazard_pointer_manager::hazard_pointer_manager (size_t max_threads = 128, size_t pointers_per_thread = 4) explicit
Constructor.
Parameters
max_threads Maximum number of threads that will use hazard pointers
pointers_per_thread Number of hazard pointers per thread
~hazard_pointer_manager() [3/3]
thread_module::hazard_pointer_manager::~hazard_pointer_manager ()
Destructor - ensures all retired objects are reclaimed.
hazard_pointer_manager() [8/9]
thread_module::hazard_pointer_manager::hazard_pointer_manager (const hazard_pointer_manager &) delete
hazard_pointer_manager() [9/9]
thread_module::hazard_pointer_manager::hazard_pointer_manager (hazard_pointer_manager &&) delete
Member Function Documentation
acquire() [1/3]
auto thread_module::hazard_pointer_manager::acquire () -> hazard_pointer
Acquire a hazard pointer.
Acquires a new hazard pointer for protecting shared data.
Returns
RAII hazard pointer object
Implementation details:
Obtains a free hazard pointer slot from the current thread's record
Creates a hazard_pointer object that manages the slot lifetime
May throw if no slots are available (thread exhaustion)
Usage Pattern:
auto hp = manager.acquire();
auto* ptr = hp.protect(shared_data_pointer);
// Use ptr safely...
Returns
A hazard_pointer object for protecting shared data
Exceptions
std::runtime_error if no hazard pointer slots available
Definition at line 219 of file hazard_pointer.cpp.
Referenced by demonstrate_basic_usage(), demonstrate_memory_safety(), and LockFreeStack::pop().
acquire() [2/3]
auto thread_module::hazard_pointer_manager::acquire () -> hazard_pointer
Acquire a hazard pointer.
Returns
RAII hazard pointer object
acquire() [3/3]
auto thread_module::hazard_pointer_manager::acquire () -> hazard_pointer
Acquire a hazard pointer.
Returns
RAII hazard pointer object
get_statistics() [1/3]
auto thread_module::hazard_pointer_manager::get_statistics () const -> statistics
Definition at line 275 of file hazard_pointer.cpp.
References thread_module::hazard_pointer_manager::statistics::active_hazard_pointers, thread_module::hazard_pointer_manager::statistics::retired_list_size, thread_module::hazard_pointer_manager::statistics::total_reclaimed, and thread_module::hazard_pointer_manager::statistics::total_retired.
Referenced by demonstrate_basic_usage(), demonstrate_concurrent_access(), and demonstrate_memory_safety().
get_statistics() [2/3]
auto thread_module::hazard_pointer_manager::get_statistics () const -> statistics
get_statistics() [3/3]
auto thread_module::hazard_pointer_manager::get_statistics () const -> statistics
operator=() [1/6]
hazard_pointer_manager & thread_module::hazard_pointer_manager::operator= (const hazard_pointer_manager &) delete
operator=() [2/6]
hazard_pointer_manager & thread_module::hazard_pointer_manager::operator= (const hazard_pointer_manager &) delete
operator=() [3/6]
hazard_pointer_manager & thread_module::hazard_pointer_manager::operator= (const hazard_pointer_manager &) delete
operator=() [4/6]
hazard_pointer_manager & thread_module::hazard_pointer_manager::operator= (hazard_pointer_manager &&) delete
operator=() [5/6]
hazard_pointer_manager & thread_module::hazard_pointer_manager::operator= (hazard_pointer_manager &&) delete
operator=() [6/6]
hazard_pointer_manager & thread_module::hazard_pointer_manager::operator= (hazard_pointer_manager &&) delete
retire() [1/3]
template<typename T > auto thread_module::hazard_pointer_manager::retire (T * ptr, std::function< void(T *)> deleter = std::default_delete<T>{}) -> void inline
Retire a pointer for later reclamation.
Template Parameters
T Type of the object to retire
Parameters
ptr Pointer to retire
deleter Custom deleter (defaults to delete)
Definition at line 155 of file hazard_pointer.h.
Referenced by demonstrate_basic_usage(), demonstrate_memory_safety(), and LockFreeStack::pop().
retire() [2/3]
template<typename T > auto thread_module::hazard_pointer_manager::retire (T * ptr, std::function< void(T *)> deleter = std::default_delete<T>{}) -> void inline
Retire a pointer for later reclamation.
Template Parameters
T Type of the object to retire
Parameters
ptr Pointer to retire
deleter Custom deleter (defaults to delete)
Definition at line 155 of file hazard_pointer.h.
retire() [3/3]
template<typename T > auto thread_module::hazard_pointer_manager::retire (T * ptr, std::function< void(T *)> deleter = std::default_delete<T>{}) -> void inline
Retire a pointer for later reclamation.
Template Parameters
T Type of the object to retire
Parameters
ptr Pointer to retire
deleter Custom deleter (defaults to delete)
Definition at line 155 of file hazard_pointer.h.
scan_and_reclaim() [1/3]
auto thread_module::hazard_pointer_manager::scan_and_reclaim () -> void
Force a scan and reclaim cycle.
Scans hazard pointers and reclaims unprotected retired memory.
Implementation details:
Collects all active hazard pointers from all thread records
Sorts hazard pointers for efficient binary search
Compares each retired node against the hazard pointer list
Reclaims memory not protected by any hazard pointer
Defers reclamation of still-protected memory
Algorithm Complexity:
O(H log H) for sorting hazard pointers (H = active hazard pointers)
O(R log H) for scanning retired list (R = retired nodes)
Total: O((H + R) log H)
Reclamation Safety:
Only reclaims memory with no active hazard pointer protection
Uses custom deleter functions for proper cleanup
Updates statistics for monitoring and debugging
Performance Considerations:
Called automatically when retired list grows large
Can be called manually for immediate reclamation
Thread-local retired lists minimize contention
Definition at line 250 of file hazard_pointer.cpp.
Referenced by demonstrate_basic_usage(), demonstrate_memory_safety(), and ~hazard_pointer_manager().
scan_and_reclaim() [2/3]
auto thread_module::hazard_pointer_manager::scan_and_reclaim () -> void
Force a scan and reclaim cycle.
References thread_module::hazard_pointer_manager::statistics::active_hazard_pointers, thread_module::hazard_pointer_manager::statistics::retired_list_size, thread_module::hazard_pointer_manager::statistics::total_reclaimed, and thread_module::hazard_pointer_manager::statistics::total_retired.
scan_and_reclaim() [3/3]
auto thread_module::hazard_pointer_manager::scan_and_reclaim () -> void
Force a scan and reclaim cycle.
References thread_module::hazard_pointer_manager::statistics::active_hazard_pointers, thread_module::hazard_pointer_manager::statistics::retired_list_size, thread_module::hazard_pointer_manager::statistics::total_reclaimed, and thread_module::hazard_pointer_manager::statistics::total_retired.
The documentation for this class was generated from the following files:
libraries/thread_system/modular_structure/core/include/thread_system_core/thread_base/lockfree/memory/hazard_pointer.h
libraries/thread_system/modular_structure/core/src/thread_base/lockfree/memory/hazard_pointer.h
libraries/thread_system/sources/thread_base/lockfree/memory/hazard_pointer.h
libraries/thread_system/modular_structure/core/src/thread_base/lockfree/memory/hazard_pointer.cpp
libraries/thread_system/sources/thread_base/lockfree/memory/hazard_pointer.cpp