Messaging System: network_module::messaging_session Class Reference
network_module::messaging_session Class Reference
Manages a single connected client session on the server side, providing asynchronous read/write operations and pipeline transformations.
#include <messaging_session.h>
Public Member Functions
messaging_session (asio::ip::tcp::socket socket, std::string_view server_id)
Constructs a session with a given socket and server_id.
~messaging_session ()
Destructor; calls stop_session() if not already stopped.
auto start_session () -> void
Starts the session: sets up read/error callbacks and begins reading data.
auto stop_session () -> void
Stops the session by closing the socket and marking the session as inactive.
auto send_packet (std::vector< uint8_t > data) -> void
Sends data to the connected client, optionally using compression/encryption.
Detailed Description
Manages a single connected client session on the server side, providing asynchronous read/write operations and pipeline transformations.
Responsibilities
Owns a tcp_socket for non-blocking I/O.
Optionally applies compression/encryption via pipeline_ before sending, and can do the reverse upon receiving data (if needed).
Provides callbacks (on_receive, on_error) for data handling and error detection.
Lifecycle
Constructed with an accepted asio::ip::tcp::socket.
start_session() sets up callbacks and begins socket_->start_read().
stop_session() closes the underlying socket, stopping further I/O.
Definition at line 70 of file messaging_session.h.
Constructor & Destructor Documentation
messaging_session()
network_module::messaging_session::messaging_session (asio::ip::tcp::socket socket, std::string_view server_id)
Constructs a session with a given socket and server_id.
Parameters
socket The asio::ip::tcp::socket (already connected).
server_id An identifier for this server instance or context.
Definition at line 44 of file messaging_session.cpp.
References network_module::make_default_pipeline().
~messaging_session()
network_module::messaging_session::~messaging_session ()
Destructor; calls stop_session() if not already stopped.
Definition at line 59 of file messaging_session.cpp.
References stop_session().
Member Function Documentation
send_packet()
auto network_module::messaging_session::send_packet (std::vector< uint8_t > data) -> void
Sends data to the connected client, optionally using compression/encryption.
Parameters
data The raw bytes to transmit.
Notes
If compress_mode_ or encrypt_mode_ is true, the data will be processed by the pipeline's compress/encrypt functions before writing.
Definition at line 97 of file messaging_session.cpp.
References network_module::async_send_with_pipeline_no_co().
start_session()
auto network_module::messaging_session::start_session () -> void
Starts the session: sets up read/error callbacks and begins reading data.
Definition at line 61 of file messaging_session.cpp.
stop_session()
auto network_module::messaging_session::stop_session () -> void
Stops the session by closing the socket and marking the session as inactive.
Definition at line 83 of file messaging_session.cpp.
Referenced by ~messaging_session().
The documentation for this class was generated from the following files:
libraries/network_system/session/messaging_session.h
libraries/network_system/session/messaging_session.cpp