Messaging System: libraries/network_system/tests/stress/stress_test.cpp File Reference
stress_test.cpp File Reference
Stress testing for network_system.
#include <iostream>
#include <vector>
#include <thread>
#include <chrono>
#include <atomic>
#include <memory>
#include <random>
#include <iomanip>
#include <cstring>
#include "network_system/network_system.h"
Classes
struct StressConfig
struct StressMetrics
class MemoryMonitor
Memory usage monitor.
Functions
void stress_client_worker (size_t client_id, const StressConfig &config, StressMetrics &metrics, std::atomic< bool > &stop_flag)
Stress test client worker.
bool run_stress_test (const StressConfig &config, StressMetrics &metrics)
Run stress test.
bool connection_storm_test (StressMetrics &metrics)
Connection storm test.
int main (int argc, char *argv[])
Main stress test runner.
Detailed Description
Stress testing for network_system.
Tests system behavior under heavy load including:
High message throughput
Many concurrent connections
Memory usage under stress
CPU utilization patterns
Author
kcenon
Date
2025-09-20
Definition in file stress_test.cpp.
Function Documentation
connection_storm_test()
bool connection_storm_test (StressMetrics & metrics)
Connection storm test.
Definition at line 305 of file stress_test.cpp.
References StressMetrics::failed_connections, and StressMetrics::total_connections.
Referenced by main().
main()
int main (int argc, char * argv[])
Main stress test runner.
Definition at line 362 of file stress_test.cpp.
References connection_storm_test(), StressConfig::duration, network_system::compat::initialize(), StressMetrics::is_successful(), StressConfig::messages_per_client, StressConfig::num_clients, StressMetrics::print(), run_stress_test(), and network_system::compat::shutdown().
run_stress_test()
bool run_stress_test (const StressConfig & config, StressMetrics & metrics)
Run stress test.
Definition at line 210 of file stress_test.cpp.
References StressConfig::base_port, StressConfig::duration, StressMetrics::end_time, MemoryMonitor::get_current_memory(), MemoryMonitor::get_peak_memory(), StressConfig::message_size, StressConfig::messages_per_client, StressConfig::num_clients, StressMetrics::start_time, stress_client_worker(), StressMetrics::total_errors, and StressMetrics::total_messages_sent.
Referenced by main().
stress_client_worker()
void stress_client_worker (size_t client_id, const StressConfig & config, StressMetrics & metrics, std::atomic< bool > & stop_flag)
Stress test client worker.
Definition at line 147 of file stress_test.cpp.
References StressConfig::base_port, StressConfig::enable_random_delays, StressConfig::enable_random_sizes, StressMetrics::failed_connections, StressConfig::max_message_size, StressConfig::message_size, StressConfig::messages_per_client, StressMetrics::total_bytes_sent, StressMetrics::total_connections, StressMetrics::total_errors, StressMetrics::total_messages_failed, and StressMetrics::total_messages_sent.
Referenced by run_stress_test().