Messaging System: kcenon::thread::thread_pool Class Reference
kcenon::thread::thread_pool Class Reference
A thread pool for concurrent execution of jobs using multiple worker threads.
#include <thread_pool.h>
Public Member Functions
thread_pool (const std::string &thread_title="thread_pool", const thread_context &context=thread_context())
Constructs a new thread_pool instance.
virtual ~thread_pool (void)
Virtual destructor.
auto get_ptr (void) -> std::shared_ptr< thread_pool >
Retrieves a std::shared_ptr to this thread_pool instance.
auto execute (std::unique_ptr< job > &&work) -> result_void override
Submit a unit of work for asynchronous execution.
auto shutdown () -> result_void override
Initiate a cooperative shutdown.
auto start (void) -> result_void
Starts the thread pool and all associated workers.
auto get_job_queue (void) -> std::shared_ptr< job_queue >
Returns the shared job_queue used by this thread pool.
auto enqueue (std::unique_ptr< job > &&job) -> result_void
Enqueues a new job into the shared job_queue.
auto enqueue_batch (std::vector< std::unique_ptr< job > > &&jobs) -> result_void
Enqueues a batch of jobs into the shared job_queue.
auto enqueue (std::unique_ptr< thread_worker > &&worker) -> result_void
Adds a thread_worker to the thread pool for specialized or additional processing.
auto enqueue_batch (std::vector< std::unique_ptr< thread_worker > > &&workers) -> result_void
Adds a batch of thread_worker objects to the thread pool.
auto stop (const bool &immediately_stop=false) -> result_void
Stops the thread pool and all worker threads.
auto to_string (void) const -> std::string
Provides a string representation of this thread_pool.
std::uint32_t get_pool_instance_id () const
Get the pool instance id.
void report_metrics ()
Collect and report current thread pool metrics.
std::size_t get_idle_worker_count () const
Get the number of idle workers.
auto get_context (void) const -> const thread_context &
Gets the thread context for this pool.
auto submit_task (std::function< void()> task) -> bool
Submit a task to the thread pool.
auto get_thread_count () const -> std::size_t
Get the number of worker threads in the pool.
auto shutdown_pool (bool immediate=false) -> bool
Shutdown the thread pool.
auto is_running () const -> bool
Check if the thread pool is currently running.
auto get_pending_task_count () const -> std::size_t
Get the number of pending tasks in the queue.
Public Member Functions inherited from kcenon::thread::executor_interface
virtual ~executor_interface ()=default
Detailed Description
A thread pool for concurrent execution of jobs using multiple worker threads.
The thread_pool class manages a group of worker threads that process jobs from a shared job_queue. This implementation provides:
Efficient reuse of threads to reduce thread creation/destruction overhead
Controlled concurrency through a fixed or dynamic thread count
A simple interface for submitting jobs of various types
Graceful handling of thread startup, execution, and shutdown
The thread pool is designed for scenarios where many short-lived tasks need to be executed asynchronously without creating a new thread for each task.
Design Principles
Worker Thread Model: Each worker runs in its own thread, processing jobs from the shared queue.
Shared Job Queue: A single, thread-safe queue holds all pending jobs.
Job-Based Work Units: Jobs encapsulate work to be executed.
Non-Blocking Submission: Adding jobs to the pool never blocks the caller thread.
Cooperative Shutdown: Workers can complete current jobs before stopping.
Thread Safety
All public methods of this class are thread-safe and can be called from any thread. The underlying job_queue is also thread-safe, allowing multiple workers to dequeue jobs concurrently.
Performance Considerations
The number of worker threads should typically be close to the number of available CPU cores for CPU-bound tasks.
For I/O-bound tasks, more threads may be beneficial to maximize throughput while some threads are blocked on I/O.
Very large thread pools (significantly more threads than cores) may degrade performance due to context switching overhead.
See also
thread_worker The worker thread class used by the pool
job_queue The shared queue for storing pending jobs
typed_kcenon::thread::typed_thread_pool For a priority-based version
Definition at line 117 of file thread_pool.h.
Constructor & Destructor Documentation
thread_pool()
kcenon::thread::thread_pool::thread_pool (const std::string & thread_title = "thread_pool", const thread_context & context = thread_context())
Constructs a new thread_pool instance.
Constructs a thread pool with adaptive job queue.
Parameters
thread_title An optional title or identifier for the thread pool (defaults to "thread_pool").
context Optional thread context for logging and monitoring (defaults to empty context).
This title can be used for logging or debugging purposes. The context provides access to logging and monitoring services.
Implementation details:
Initializes with provided thread title for identification
Creates adaptive job queue that automatically optimizes based on contention
Pool starts in stopped state (start_pool_ = false)
No workers are initially assigned (workers_ is empty)
Stores thread context for logging and monitoring
Adaptive Queue Strategy:
ADAPTIVE mode automatically switches between mutex and lock-free implementations
Provides optimal performance across different contention levels
Eliminates need for manual queue strategy selection
Parameters
thread_title Descriptive name for this thread pool instance
context Thread context providing logging and monitoring services
Definition at line 72 of file thread_pool.cpp.
References kcenon::thread::thread_context::monitoring(), monitoring_interface::thread_pool_metrics::pool_instance_id, monitoring_interface::thread_pool_metrics::pool_name, monitoring_interface::thread_pool_metrics::timestamp, kcenon::thread::thread_context::update_thread_pool_metrics(), and monitoring_interface::thread_pool_metrics::worker_threads.
~thread_pool()
kcenon::thread::thread_pool::~thread_pool (void) virtual
Virtual destructor.
Destroys the thread pool, ensuring all workers are stopped.
Cleans up resources used by the thread pool.
If the pool is still running, this typically calls stop() internally to ensure all worker threads are properly shut down.
Implementation details:
Automatically calls stop() to ensure clean shutdown
Workers will complete current jobs before terminating
Prevents resource leaks from running threads
Definition at line 99 of file thread_pool.cpp.
References stop().
Member Function Documentation
enqueue() [1/2]
auto kcenon::thread::thread_pool::enqueue (std::unique_ptr< job > && job) -> result_void
Enqueues a new job into the shared job_queue.
Adds a single job to the thread pool for processing.
Parameters
job A std::unique_ptr<job> representing the work to be done.
Returns
result_void containing an error on failure, or success value on success.
Implementation details:
Validates job pointer before submission
Validates queue availability
Delegates to adaptive job queue for optimal scheduling
Job will be processed by next available worker thread
Queue Behavior:
Adaptive queue automatically selects best strategy (mutex/lock-free)
Jobs are processed in FIFO order within the selected strategy
Workers are notified when jobs become available
Thread Safety:
Safe to call from multiple threads simultaneously
Adaptive queue handles contention efficiently
Parameters
job Unique pointer to job (ownership transferred)
Returns
std::nullopt on success, error message on failure
Definition at line 206 of file thread_pool.cpp.
References kcenon::thread::invalid_argument, and kcenon::thread::resource_allocation_failed.
Referenced by main().
enqueue() [2/2]
auto kcenon::thread::thread_pool::enqueue (std::unique_ptr< thread_worker > && worker) -> result_void
Adds a thread_worker to the thread pool for specialized or additional processing.
Parameters
worker A std::unique_ptr<thread_worker> object.
Returns
result_void containing an error on failure, or success value on success.
Definition at line 251 of file thread_pool.cpp.
References kcenon::thread::invalid_argument, and kcenon::thread::resource_allocation_failed.
enqueue_batch() [1/2]
auto kcenon::thread::thread_pool::enqueue_batch (std::vector< std::unique_ptr< job > > && jobs) -> result_void
Enqueues a batch of jobs into the shared job_queue.
Parameters
jobs A vector of std::unique_ptr<job> objects to be added.
Returns
result_void containing an error on failure, or success value on success.
Definition at line 229 of file thread_pool.cpp.
References kcenon::thread::invalid_argument, and kcenon::thread::resource_allocation_failed.
Referenced by main(), store_job(), store_job(), and store_job().
enqueue_batch() [2/2]
auto kcenon::thread::thread_pool::enqueue_batch (std::vector< std::unique_ptr< thread_worker > > && workers) -> result_void
Adds a batch of thread_worker objects to the thread pool.
Parameters
workers A vector of std::unique_ptr<thread_worker> objects.
Returns
result_void containing an error on failure, or success value on success.
Definition at line 281 of file thread_pool.cpp.
References kcenon::thread::invalid_argument, and kcenon::thread::resource_allocation_failed.
execute()
auto kcenon::thread::thread_pool::execute (std::unique_ptr< job > && work) -> result_void override virtual
Submit a unit of work for asynchronous execution.
Implements kcenon::thread::executor_interface.
Definition at line 178 of file thread_pool.cpp.
get_context()
auto kcenon::thread::thread_pool::get_context (void) const -> const thread_context&
Gets the thread context for this pool.
Returns
The thread context providing access to logging and monitoring services.
Definition at line 364 of file thread_pool.cpp.
get_idle_worker_count()
std::size_t kcenon::thread::thread_pool::get_idle_worker_count () const
Get the number of idle workers.
Returns
Number of workers currently not processing jobs.
Definition at line 398 of file thread_pool.cpp.
Referenced by report_metrics().
get_job_queue()
auto kcenon::thread::thread_pool::get_job_queue (void) -> std::shared_ptr<job_queue>
Returns the shared job_queue used by this thread pool.
Returns the shared job queue used by all workers.
Returns
A std::shared_ptr<job_queue> that stores the queued jobs.
The returned queue is shared among all worker threads in the pool, which can concurrently dequeue and process jobs.
Implementation details:
Provides access to the adaptive job queue for external job submission
Queue is shared among all workers for load balancing
Adaptive queue automatically optimizes based on contention patterns
Returns
Shared pointer to the job queue
Definition at line 175 of file thread_pool.cpp.
get_pending_task_count()
auto kcenon::thread::thread_pool::get_pending_task_count () const -> std::size_t
Get the number of pending tasks in the queue.
Returns
Number of tasks waiting to be processed
Definition at line 440 of file thread_pool.cpp.
get_pool_instance_id()
std::uint32_t kcenon::thread::thread_pool::get_pool_instance_id () const
Get the pool instance id.
Returns
Returns the unique instance id for this pool.
Definition at line 369 of file thread_pool.cpp.
get_ptr()
auto kcenon::thread::thread_pool::get_ptr (void) -> std::shared_ptr<thread_pool>
Retrieves a std::shared_ptr to this thread_pool instance.
Returns a shared pointer to this thread pool instance.
Returns
A shared pointer to the current thread_pool object.
By inheriting from std::enable_shared_from_this, you can call get_ptr() within member functions to avoid storing a separate shared pointer.
Implementation details:
Uses std::enable_shared_from_this for safe shared_ptr creation
Required for passing pool reference to workers or other components
Ensures proper lifetime management in multi-threaded environment
Returns
Shared pointer to this thread_pool
Definition at line 111 of file thread_pool.cpp.
get_thread_count()
auto kcenon::thread::thread_pool::get_thread_count () const -> std::size_t
Get the number of worker threads in the pool.
Returns
Number of active worker threads
Definition at line 424 of file thread_pool.cpp.
is_running()
auto kcenon::thread::thread_pool::is_running () const -> bool
Check if the thread pool is currently running.
Returns
true if the pool is active, false otherwise
Definition at line 435 of file thread_pool.cpp.
report_metrics()
void kcenon::thread::thread_pool::report_metrics ()
Collect and report current thread pool metrics.
This method gathers current metrics from the pool and reports them through the monitoring interface if available.
Definition at line 374 of file thread_pool.cpp.
References get_idle_worker_count(), monitoring_interface::thread_pool_metrics::idle_threads, monitoring_interface::thread_pool_metrics::jobs_pending, kcenon::thread::thread_context::monitoring(), monitoring_interface::thread_pool_metrics::pool_instance_id, monitoring_interface::thread_pool_metrics::pool_name, monitoring_interface::thread_pool_metrics::timestamp, kcenon::thread::thread_context::update_thread_pool_metrics(), and monitoring_interface::thread_pool_metrics::worker_threads.
shutdown()
auto kcenon::thread::thread_pool::shutdown () -> result_void override virtual
Initiate a cooperative shutdown.
Implements kcenon::thread::executor_interface.
Definition at line 183 of file thread_pool.cpp.
shutdown_pool()
auto kcenon::thread::thread_pool::shutdown_pool (bool immediate = false) -> bool
Shutdown the thread pool.
Parameters
immediate If true, stop immediately; if false, wait for current tasks to complete
Returns
true if shutdown was successful, false otherwise
Definition at line 429 of file thread_pool.cpp.
start()
auto kcenon::thread::thread_pool::start (void) -> result_void
Starts the thread pool and all associated workers.
Starts all worker threads in the pool.
Returns
result_void containing an error on failure, or success value on success.
If the pool is already running, a subsequent call to start() may return an error. On success, each thread_worker in workers_ is started, enabling them to process jobs from the job_queue_.
Implementation details:
Validates that workers have been added to the pool
Starts each worker thread individually
If any worker fails to start, stops all workers and returns error
Sets start_pool_ flag to true on successful startup
Workers begin processing jobs from the shared queue immediately
Startup Sequence:
Check that workers exist
Start each worker sequentially
On failure: stop all workers and return error message
On success: mark pool as started
Error Handling:
All-or-nothing startup (if one fails, all stop)
Provides detailed error message from failed worker
Ensures consistent pool state (either all running or all stopped)
Returns
std::nullopt on success, error message on failure
Definition at line 139 of file thread_pool.cpp.
References kcenon::thread::invalid_argument.
Referenced by main(), and main().
stop()
auto kcenon::thread::thread_pool::stop (const bool & immediately_stop = false) -> result_void
Stops the thread pool and all worker threads.
Parameters
immediately_stop If true, any ongoing jobs may be interrupted; if false (default), each worker attempts to finish its current job before stopping.
Returns
result_void containing an error on failure, or success value on success.
Definition at line 315 of file thread_pool.cpp.
References kcenon::thread::utils::formatter::format().
Referenced by main(), main(), and ~thread_pool().
submit_task()
auto kcenon::thread::thread_pool::submit_task (std::function< void()> task) -> bool
Submit a task to the thread pool.
Parameters
task The task to be executed
Returns
true if task was successfully submitted, false otherwise
Definition at line 407 of file thread_pool.cpp.
to_string()
auto kcenon::thread::thread_pool::to_string (void) const -> std::string
Provides a string representation of this thread_pool.
Returns
A string describing the pool, including its title and other optional details.
Derived classes may override this to include more diagnostic or state-related info.
Definition at line 347 of file thread_pool.cpp.
References kcenon::thread::utils::formatter::format_to().
Referenced by fmt::formatter< kcenon::thread::thread_pool >::format(), and main().
The documentation for this class was generated from the following files:
libraries/thread_system/include/kcenon/thread/core/thread_pool.h
libraries/thread_system/src/impl/thread_pool/thread_pool.cpp