Messaging System: database::connection_pool_manager Class Reference
database::connection_pool_manager Class Reference
Manages multiple connection pools for different database types.
#include <connection_pool.h>
Public Member Functions
bool create_pool (database_types db_type, const connection_pool_config &config)
Creates a connection pool for a database type.
std::shared_ptr< connection_pool_base > get_pool (database_types db_type)
Gets a connection pool for a database type.
void remove_pool (database_types db_type)
Removes a connection pool.
void shutdown_all ()
Shuts down all connection pools.
std::map< database_types, connection_stats > get_all_stats () const
Gets statistics for all pools.
Static Public Member Functions
static connection_pool_manager & instance ()
Gets the singleton instance.
Detailed Description
Manages multiple connection pools for different database types.
Definition at line 235 of file connection_pool.h.
Member Function Documentation
create_pool()
bool database::connection_pool_manager::create_pool (database_types db_type, const connection_pool_config & config)
Creates a connection pool for a database type.
Parameters
db_type Database type
config Pool configuration
Returns
true if pool created successfully, false otherwise
Definition at line 386 of file connection_pool.cpp.
References database::connection_pool_config::connection_string.
Referenced by database::database_manager::create_connection_pool().
get_all_stats()
std::map< database_types, connection_stats > database::connection_pool_manager::get_all_stats () const
Gets statistics for all pools.
Returns
Map of database type to connection stats
Definition at line 437 of file connection_pool.cpp.
Referenced by database::database_manager::get_pool_stats().
get_pool()
std::shared_ptr< connection_pool_base > database::connection_pool_manager::get_pool (database_types db_type)
Gets a connection pool for a database type.
Parameters
db_type Database type
Returns
Shared pointer to connection pool, nullptr if not found
Definition at line 411 of file connection_pool.cpp.
Referenced by database::database_manager::get_connection_pool().
instance()
connection_pool_manager & database::connection_pool_manager::instance () static
Gets the singleton instance.
Returns
Reference to the connection pool manager
Definition at line 375 of file connection_pool.cpp.
References instance().
Referenced by database::database_manager::create_connection_pool(), database::database_manager::get_connection_pool(), database::database_manager::get_pool_stats(), and instance().
remove_pool()
void database::connection_pool_manager::remove_pool (database_types db_type)
Removes a connection pool.
Parameters
db_type Database type
Definition at line 418 of file connection_pool.cpp.
shutdown_all()
void database::connection_pool_manager::shutdown_all ()
Shuts down all connection pools.
Definition at line 428 of file connection_pool.cpp.
The documentation for this class was generated from the following files:
libraries/database_system/database/connection_pool.h
libraries/database_system/database/connection_pool.cpp