Messaging System: monitoring_module::alert_manager Class Reference
monitoring_module::alert_manager Class Reference
알림 관리 시스템
#include <trend_analyzer.h>
Classes
struct alert_condition
알림 조건
struct alert_event
발생한 알림 이벤트
Public Types
enum class alert_severity { info , warning , critical , emergency }
알림 심각도
Public Member Functions
void add_condition (const alert_condition &condition)
알림 조건 추가
std::vector< alert_event > evaluate (const std::string &metric_name, double value)
메트릭 평가 및 알림 생성
std::vector< alert_event > get_recent_alerts (std::size_t count=10) const
최근 알림 조회
std::unordered_map< alert_severity, std::size_t > get_alert_statistics () const
심각도별 알림 통계
void clear_history ()
알림 히스토리 초기화
Detailed Description
알림 관리 시스템
임계값 기반 알림 및 트렌드 기반 조기 경고
Definition at line 181 of file trend_analyzer.h.
Member Enumeration Documentation
alert_severity
enum class monitoring_module::alert_manager::alert_severity strong
알림 심각도
Enumerator
info
warning
critical
emergency
Definition at line 187 of file trend_analyzer.h.
Member Function Documentation
add_condition()
void monitoring_module::alert_manager::add_condition (const alert_condition & condition)
알림 조건 추가
Parameters
condition 알림 조건
Definition at line 397 of file trend_analyzer.cpp.
clear_history()
void monitoring_module::alert_manager::clear_history ()
알림 히스토리 초기화
Definition at line 474 of file trend_analyzer.cpp.
evaluate()
std::vector< alert_manager::alert_event > monitoring_module::alert_manager::evaluate (const std::string & metric_name, double value)
메트릭 평가 및 알림 생성
Parameters
metric_name 메트릭 이름
value 현재 값
Returns
발생한 알림들
Definition at line 402 of file trend_analyzer.cpp.
References monitoring_module::alert_manager::alert_event::condition_name.
get_alert_statistics()
std::unordered_map< alert_manager::alert_severity, std::size_t > monitoring_module::alert_manager::get_alert_statistics () const
심각도별 알림 통계
Returns
심각도별 알림 개수
Definition at line 464 of file trend_analyzer.cpp.
Referenced by monitoring_module::analysis_dashboard::export_json().
get_recent_alerts()
std::vector< alert_manager::alert_event > monitoring_module::alert_manager::get_recent_alerts (std::size_t count = 10) const
최근 알림 조회
Parameters
count 조회할 개수
Returns
최근 알림 이벤트들
Definition at line 453 of file trend_analyzer.cpp.
Referenced by dashboard_renderer::render_alerts_section(), and monitoring_module::analysis_dashboard::render_text_dashboard().
The documentation for this class was generated from the following files:
libraries/monitoring_system/sources/monitoring/trend_analyzer.h
libraries/monitoring_system/sources/monitoring/trend_analyzer.cpp