Messaging System: network_system::integration Namespace Reference
network_system::integration Namespace Reference
Classes
class basic_container
Basic container implementation for standalone use.
class basic_logger
Basic console logger implementation for standalone use.
class basic_thread_pool
Basic thread pool implementation for standalone use.
class container_interface
Abstract interface for container operations.
class container_manager
Manager for container system integration.
class logger_integration_manager
Manager for logger system integration.
class logger_interface
Abstract interface for logger integration.
class messaging_bridge
Bridge class for messaging_system compatibility.
class thread_integration_manager
Manager for thread system integration.
class thread_pool_interface
Abstract interface for thread pool integration.
Enumerations
enum class log_level : int {
trace = 0 , debug = 1 , info = 2 , warn = 3 ,
error = 4 , fatal = 5
}
Log severity levels matching logger_system.
Functions
static const char * level_to_string (log_level level)
static std::string get_timestamp ()
Enumeration Type Documentation
log_level
enum class network_system::integration::log_level : int strong
Log severity levels matching logger_system.
Enumerator
trace
debug
info
warn
error
fatal
Definition at line 56 of file logger_integration.h.
Function Documentation
get_timestamp()
static std::string network_system::integration::get_timestamp () static
Definition at line 70 of file logger_integration.cpp.
Referenced by network_system::integration::basic_logger::impl::log(), and network_system::integration::basic_logger::impl::log().
level_to_string()
static const char * network_system::integration::level_to_string (log_level level) static
Definition at line 57 of file logger_integration.cpp.
Referenced by network_system::integration::basic_logger::impl::log(), and network_system::integration::basic_logger::impl::log().