Messaging System: libraries/thread_system/cmake/test_std_span.cpp File Reference
test_std_span.cpp File Reference
#include <span>
#include <vector>
#include <array>
#include <algorithm>
#include <numeric>
Functions
int test_basic_span ()
int test_container_span ()
int test_subspan ()
int test_const_span ()
int test_span_algorithms ()
int test_dynamic_extent ()
int main ()
Function Documentation
main()
int main ()
Definition at line 136 of file test_std_span.cpp.
References test_basic_span(), test_const_span(), test_container_span(), test_dynamic_extent(), test_span_algorithms(), and test_subspan().
test_basic_span()
int test_basic_span ()
Definition at line 40 of file test_std_span.cpp.
Referenced by main().
test_const_span()
int test_const_span ()
Definition at line 93 of file test_std_span.cpp.
Referenced by main().
test_container_span()
int test_container_span ()
Definition at line 57 of file test_std_span.cpp.
Referenced by main().
test_dynamic_extent()
int test_dynamic_extent ()
Definition at line 124 of file test_std_span.cpp.
Referenced by main().
test_span_algorithms()
int test_span_algorithms ()
Definition at line 106 of file test_std_span.cpp.
Referenced by main().
test_subspan()
int test_subspan ()
Definition at line 74 of file test_std_span.cpp.
Referenced by main().