Messaging System: load_simulator Class Reference
load_simulator Class Reference
Public Types
enum class load_pattern { steady , spiky , gradual , random }
Public Member Functions
load_simulator (load_pattern pattern=load_pattern::steady)
double get_cpu_load ()
std::uint64_t get_memory_usage ()
void advance ()
Detailed Description
Definition at line 32 of file optimization_demo.cpp.
Member Enumeration Documentation
load_pattern
enum class load_simulator::load_pattern strong
Enumerator
steady
spiky
gradual
random
Definition at line 34 of file optimization_demo.cpp.
Constructor & Destructor Documentation
load_simulator()
load_simulator::load_simulator (load_pattern pattern = load_pattern::steady) inline
Definition at line 41 of file optimization_demo.cpp.
Member Function Documentation
advance()
void load_simulator::advance () inline
Definition at line 70 of file optimization_demo.cpp.
Referenced by main().
get_cpu_load()
double load_simulator::get_cpu_load () inline
Definition at line 44 of file optimization_demo.cpp.
References gradual, random, spiky, and steady.
Referenced by get_memory_usage(), and main().
get_memory_usage()
std::uint64_t load_simulator::get_memory_usage () inline
Definition at line 64 of file optimization_demo.cpp.
References get_cpu_load().
Referenced by main().
The documentation for this class was generated from the following file:
libraries/monitoring_system/samples/optimization_demo.cpp