Messaging System: libraries/logger_system/samples/security_demo.cpp File Reference
security_demo.cpp File Reference
#include <logger/logger.h>
#include <logger/writers/console_writer.h>
#include <logger/writers/file_writer.h>
#include <logger/writers/encrypted_writer.h>
#include <logger/security/log_sanitizer.h>
#include <logger/structured/structured_logger.h>
#include <thread>
#include <iostream>
#include <fstream>
Functions
void test_encryption ()
void test_sanitization ()
void test_sanitizing_filter ()
void test_access_control ()
void test_combined_security ()
int main ()
Function Documentation
main()
int main ()
Definition at line 231 of file security_demo.cpp.
References test_access_control(), test_combined_security(), test_encryption(), test_sanitization(), and test_sanitizing_filter().
test_access_control()
void test_access_control ()
Definition at line 112 of file security_demo.cpp.
References logger_module::logger::add_writer(), thread_module::debug, thread_module::error, thread_module::info, logger_module::logger::log(), and logger_module::logger::set_filter().
Referenced by main().
test_combined_security()
void test_combined_security ()
Definition at line 179 of file security_demo.cpp.
References logger_module::logger::add_writer(), logger_module::logger::flush(), and logger_module::encrypted_writer::generate_key().
Referenced by main().
test_encryption()
void test_encryption ()
Definition at line 20 of file security_demo.cpp.
References logger_module::logger::add_writer(), thread_module::error, logger_module::logger::flush(), logger_module::encrypted_writer::generate_key(), thread_module::info, logger_module::logger::log(), logger_module::encrypted_writer::save_key(), and thread_module::warning.
Referenced by main().
test_sanitization()
void test_sanitization ()
Definition at line 50 of file security_demo.cpp.
References logger_module::logger::add_writer().
Referenced by main().
test_sanitizing_filter()
void test_sanitizing_filter ()
Definition at line 82 of file security_demo.cpp.
References logger_module::logger::add_writer(), thread_module::error, thread_module::info, logger_module::logger::log(), logger_module::logger::set_filter(), and thread_module::warning.
Referenced by main().