Messaging System: database::orm::field_metadata Class Reference
database::orm::field_metadata Class Reference
Metadata for entity fields including constraints and relationships.
#include <entity.h>
Public Member Functions
field_metadata (const std::string &name, const std::string &type_name, field_constraint constraints=field_constraint::none, const std::string &index_name="", const std::string &foreign_table="", const std::string &foreign_field="")
const std::string & name () const
const std::string & type_name () const
field_constraint constraints () const
const std::string & index_name () const
const std::string & foreign_table () const
const std::string & foreign_field () const
bool is_primary_key () const
bool is_not_null () const
bool is_unique () const
bool is_auto_increment () const
bool has_index () const
bool is_foreign_key () const
bool has_default_now () const
std::string to_sql_definition () const
Detailed Description
Metadata for entity fields including constraints and relationships.
Definition at line 97 of file entity.h.
Constructor & Destructor Documentation
field_metadata()
database::orm::field_metadata::field_metadata (const std::string & name, const std::string & type_name, field_constraint constraints = field_constraint::none, const std::string & index_name = "", const std::string & foreign_table = "", const std::string & foreign_field = "")
Definition at line 41 of file entity.cpp.
Member Function Documentation
constraints()
field_constraint database::orm::field_metadata::constraints () const inline
Definition at line 109 of file entity.h.
foreign_field()
const std::string & database::orm::field_metadata::foreign_field () const inline
Definition at line 112 of file entity.h.
foreign_table()
const std::string & database::orm::field_metadata::foreign_table () const inline
Definition at line 111 of file entity.h.
has_default_now()
bool database::orm::field_metadata::has_default_now () const inline
Definition at line 120 of file entity.h.
References database::orm::default_now, and database::orm::has_constraint().
Referenced by to_sql_definition().
has_index()
bool database::orm::field_metadata::has_index () const inline
Definition at line 118 of file entity.h.
References database::orm::has_constraint(), and database::orm::index.
index_name()
const std::string & database::orm::field_metadata::index_name () const inline
Definition at line 110 of file entity.h.
is_auto_increment()
bool database::orm::field_metadata::is_auto_increment () const inline
Definition at line 117 of file entity.h.
References database::orm::auto_increment, and database::orm::has_constraint().
Referenced by to_sql_definition().
is_foreign_key()
bool database::orm::field_metadata::is_foreign_key () const inline
Definition at line 119 of file entity.h.
References database::orm::foreign_key, and database::orm::has_constraint().
is_not_null()
bool database::orm::field_metadata::is_not_null () const inline
Definition at line 115 of file entity.h.
References database::orm::has_constraint(), and database::orm::not_null.
Referenced by to_sql_definition().
is_primary_key()
bool database::orm::field_metadata::is_primary_key () const inline
Definition at line 114 of file entity.h.
References database::orm::has_constraint(), and database::orm::primary_key.
Referenced by to_sql_definition().
is_unique()
bool database::orm::field_metadata::is_unique () const inline
Definition at line 116 of file entity.h.
References database::orm::has_constraint(), and database::orm::unique.
Referenced by to_sql_definition().
name()
const std::string & database::orm::field_metadata::name () const inline
Definition at line 107 of file entity.h.
to_sql_definition()
std::string database::orm::field_metadata::to_sql_definition () const
Definition at line 56 of file entity.cpp.
References has_default_now(), is_auto_increment(), is_not_null(), is_primary_key(), and is_unique().
type_name()
const std::string & database::orm::field_metadata::type_name () const inline
Definition at line 108 of file entity.h.
The documentation for this class was generated from the following files:
libraries/database_system/database/orm/entity.h
libraries/database_system/database/orm/entity.cpp