Messaging System: network_system::integration::basic_thread_pool::impl Class Reference
network_system::integration::basic_thread_pool::impl Class Reference
Public Member Functions
impl (size_t num_threads)
~impl ()
std::future< void > submit (std::function< void()> task)
std::future< void > submit_delayed (std::function< void()> task, std::chrono::milliseconds delay)
size_t worker_count () const
bool is_running () const
size_t pending_tasks () const
void stop (bool wait_for_tasks)
size_t get_completed_tasks () const
Detailed Description
Definition at line 21 of file thread_integration.cpp.
Constructor & Destructor Documentation
impl()
network_system::integration::basic_thread_pool::impl::impl (size_t num_threads) inline
Definition at line 23 of file thread_integration.cpp.
~impl()
network_system::integration::basic_thread_pool::impl::~impl () inline
Definition at line 37 of file thread_integration.cpp.
References stop().
Member Function Documentation
get_completed_tasks()
size_t network_system::integration::basic_thread_pool::impl::get_completed_tasks () const inline
Definition at line 115 of file thread_integration.cpp.
is_running()
bool network_system::integration::basic_thread_pool::impl::is_running () const inline
Definition at line 84 of file thread_integration.cpp.
pending_tasks()
size_t network_system::integration::basic_thread_pool::impl::pending_tasks () const inline
Definition at line 88 of file thread_integration.cpp.
stop()
void network_system::integration::basic_thread_pool::impl::stop (bool wait_for_tasks) inline
Definition at line 93 of file thread_integration.cpp.
Referenced by ~impl().
submit()
std::future< void > network_system::integration::basic_thread_pool::impl::submit (std::function< void()> task) inline
Definition at line 41 of file thread_integration.cpp.
Referenced by submit_delayed().
submit_delayed()
std::future< void > network_system::integration::basic_thread_pool::impl::submit_delayed (std::function< void()> task, std::chrono::milliseconds delay) inline
Definition at line 70 of file thread_integration.cpp.
References submit().
worker_count()
size_t network_system::integration::basic_thread_pool::impl::worker_count () const inline
Definition at line 80 of file thread_integration.cpp.
The documentation for this class was generated from the following file:
libraries/network_system/src/integration/thread_integration.cpp