Messaging System: database::orm Namespace Reference
database::orm Namespace Reference
Classes
class entity_base
Base class for all ORM entities.
class entity_manager
Manages entity metadata and provides factory methods.
class entity_metadata
Metadata for entire entities including table mapping and relationships.
class field_accessor
Template class for type-safe field access.
class field_metadata
Metadata for entity fields including constraints and relationships.
class query_builder
Template query builder for type-safe ORM queries.
Concepts
concept Entity
concept FieldType
Enumerations
enum class field_constraint {
none = 0 , primary_key = 1 , not_null = 2 , unique = 4 ,
auto_increment = 8 , index = 16 , foreign_key = 32 , default_now = 64
}
Functions
field_constraint operator| (field_constraint a, field_constraint b)
bool has_constraint (field_constraint constraints, field_constraint check)
field_constraint primary_key ()
field_constraint not_null ()
field_constraint unique ()
field_constraint auto_increment ()
field_constraint default_now ()
field_constraint index (const std::string &name="")
field_constraint foreign_key (const std::string &table, const std::string &field)
Enumeration Type Documentation
field_constraint
enum class database::orm::field_constraint strong
Enumerator
none
primary_key
not_null
unique
auto_increment
index
foreign_key
default_now
Definition at line 74 of file entity.h.
Function Documentation
auto_increment()
field_constraint database::orm::auto_increment () inline
Definition at line 314 of file entity.h.
References auto_increment.
default_now()
field_constraint database::orm::default_now () inline
Definition at line 315 of file entity.h.
References default_now.
foreign_key()
field_constraint database::orm::foreign_key (const std::string & table, const std::string & field) inline
Definition at line 321 of file entity.h.
References foreign_key.
has_constraint()
bool database::orm::has_constraint (field_constraint constraints, field_constraint check) inline
Definition at line 89 of file entity.h.
Referenced by database::orm::field_metadata::has_default_now(), database::orm::field_metadata::has_index(), database::orm::field_metadata::is_auto_increment(), database::orm::field_metadata::is_foreign_key(), database::orm::field_metadata::is_not_null(), database::orm::field_metadata::is_primary_key(), and database::orm::field_metadata::is_unique().
index()
field_constraint database::orm::index (const std::string & name = "") inline
Definition at line 317 of file entity.h.
References index.
not_null()
field_constraint database::orm::not_null () inline
Definition at line 312 of file entity.h.
References not_null.
operator|()
field_constraint database::orm::operator| (field_constraint a, field_constraint b) inline
Definition at line 85 of file entity.h.
primary_key()
field_constraint database::orm::primary_key () inline
Definition at line 311 of file entity.h.
References primary_key.
unique()
field_constraint database::orm::unique () inline
Definition at line 313 of file entity.h.
References unique.