Messaging System: monitoring_module::trend_analyzer Class Reference
monitoring_module::trend_analyzer Class Reference
메트릭 트렌드 분석 및 예측 도구
#include <trend_analyzer.h>
Classes
struct anomaly_result
이상 징후 탐지 결과
struct prediction_result
예측 결과
struct trend_point
시계열 데이터 포인트
struct trend_result
트렌드 분석 결과
Public Types
using time_point = std::chrono::steady_clock::time_point
using duration = std::chrono::steady_clock::duration
Static Public Member Functions
static trend_result analyze_trend (const std::vector< trend_point > &points)
선형 회귀를 사용한 트렌드 분석
static std::vector< trend_point > calculate_moving_average (const std::vector< trend_point > &points, std::size_t window_size)
이동 평균 계산
static std::vector< trend_point > calculate_ema (const std::vector< trend_point > &points, double alpha=0.3)
지수 이동 평균 계산
static std::vector< anomaly_result > detect_anomalies (const std::vector< trend_point > &points, double threshold=3.0)
Z-score 기반 이상 징후 탐지
static std::vector< prediction_result > predict_linear (const std::vector< trend_point > &points, duration future_duration, std::size_t num_predictions=10)
선형 예측
static std::size_t detect_seasonality (const std::vector< trend_point > &points, std::size_t period_hint=0)
계절성 탐지
static std::vector< std::size_t > detect_change_points (const std::vector< trend_point > &points, double sensitivity=0.5)
변화점 탐지
static double calculate_correlation (const std::vector< trend_point > &series1, const std::vector< trend_point > &series2)
메트릭 상관관계 분석
static std::optional< time_point > predict_capacity_exhaustion (const std::vector< trend_point > &points, double capacity_limit)
용량 계획을 위한 성장률 예측
static double calculate_health_trend (const std::vector< trend_point > &points)
메트릭 건강도 점수 트렌드
Detailed Description
메트릭 트렌드 분석 및 예측 도구
시계열 데이터를 분석하여 트렌드, 이상 징후, 예측 제공
Definition at line 25 of file trend_analyzer.h.
Member Typedef Documentation
duration
using monitoring_module::trend_analyzer::duration = std::chrono::steady_clock::duration
Definition at line 28 of file trend_analyzer.h.
time_point
using monitoring_module::trend_analyzer::time_point = std::chrono::steady_clock::time_point
Definition at line 27 of file trend_analyzer.h.
Member Function Documentation
analyze_trend()
trend_analyzer::trend_result monitoring_module::trend_analyzer::analyze_trend (const std::vector< trend_point > & points) static
선형 회귀를 사용한 트렌드 분석
Parameters
points 시계열 데이터
Returns
트렌드 분석 결과
Definition at line 17 of file trend_analyzer.cpp.
References monitoring_module::trend_analyzer::trend_result::mean.
Referenced by calculate_health_trend(), predict_capacity_exhaustion(), and predict_linear().
calculate_correlation()
double monitoring_module::trend_analyzer::calculate_correlation (const std::vector< trend_point > & series1, const std::vector< trend_point > & series2) static
메트릭 상관관계 분석
Parameters
series1 첫 번째 시계열
series2 두 번째 시계열
Returns
상관계수 (-1 ~ 1)
Definition at line 315 of file trend_analyzer.cpp.
Referenced by monitoring_module::analysis_dashboard::analyze_correlations().
calculate_ema()
std::vector< trend_analyzer::trend_point > monitoring_module::trend_analyzer::calculate_ema (const std::vector< trend_point > & points, double alpha = 0.3) static
지수 이동 평균 계산
Parameters
points 시계열 데이터
alpha 평활 계수 (0-1)
Returns
EMA 값들
Definition at line 105 of file trend_analyzer.cpp.
References monitoring_module::trend_analyzer::trend_point::timestamp, and monitoring_module::trend_analyzer::trend_point::value.
calculate_health_trend()
double monitoring_module::trend_analyzer::calculate_health_trend (const std::vector< trend_point > & points) static
메트릭 건강도 점수 트렌드
Parameters
points 건강도 점수 시계열
Returns
개선/악화 트렌드 (-100 ~ 100)
Definition at line 379 of file trend_analyzer.cpp.
References analyze_trend().
calculate_moving_average()
std::vector< trend_analyzer::trend_point > monitoring_module::trend_analyzer::calculate_moving_average (const std::vector< trend_point > & points, std::size_t window_size) static
이동 평균 계산
Parameters
points 시계열 데이터
window_size 윈도우 크기
Returns
이동 평균 값들
Definition at line 80 of file trend_analyzer.cpp.
References monitoring_module::trend_analyzer::trend_point::timestamp, and monitoring_module::trend_analyzer::trend_point::value.
detect_anomalies()
std::vector< trend_analyzer::anomaly_result > monitoring_module::trend_analyzer::detect_anomalies (const std::vector< trend_point > & points, double threshold = 3.0) static
Z-score 기반 이상 징후 탐지
Parameters
points 시계열 데이터
threshold Z-score 임계값 (기본 3.0)
Returns
이상 징후 목록
Definition at line 125 of file trend_analyzer.cpp.
References monitoring_module::trend_analyzer::anomaly_result::description, monitoring_module::trend_analyzer::anomaly_result::deviation, monitoring_module::trend_analyzer::anomaly_result::expected_value, monitoring_module::trend_analyzer::anomaly_result::severity, monitoring_module::trend_analyzer::anomaly_result::timestamp, and monitoring_module::trend_analyzer::anomaly_result::value.
Referenced by monitoring_module::analysis_dashboard::detect_real_time_anomalies().
detect_change_points()
std::vector< std::size_t > monitoring_module::trend_analyzer::detect_change_points (const std::vector< trend_point > & points, double sensitivity = 0.5) static
변화점 탐지
Parameters
points 시계열 데이터
sensitivity 민감도 (0-1, 높을수록 민감)
Returns
변화점 인덱스들
Definition at line 273 of file trend_analyzer.cpp.
detect_seasonality()
std::size_t monitoring_module::trend_analyzer::detect_seasonality (const std::vector< trend_point > & points, std::size_t period_hint = 0) static
계절성 탐지
Parameters
points 시계열 데이터
period_hint 예상 주기 (옵션)
Returns
탐지된 주기 (없으면 0)
Definition at line 225 of file trend_analyzer.cpp.
predict_capacity_exhaustion()
std::optional< trend_analyzer::time_point > monitoring_module::trend_analyzer::predict_capacity_exhaustion (const std::vector< trend_point > & points, double capacity_limit) static
용량 계획을 위한 성장률 예측
Parameters
points 과거 사용량 데이터
capacity_limit 용량 한계
Returns
한계 도달 예상 시점 (없으면 nullopt)
Definition at line 348 of file trend_analyzer.cpp.
References analyze_trend().
Referenced by monitoring_module::analysis_dashboard::analyze_capacity_planning(), and monitoring_module::analysis_dashboard::generate_forecast().
predict_linear()
std::vector< trend_analyzer::prediction_result > monitoring_module::trend_analyzer::predict_linear (const std::vector< trend_point > & points, duration future_duration, std::size_t num_predictions = 10) static
선형 예측
Parameters
points 과거 데이터
future_duration 예측할 미래 시간
num_predictions 예측 포인트 수
Returns
예측 결과들
Definition at line 177 of file trend_analyzer.cpp.
References analyze_trend(), monitoring_module::trend_analyzer::prediction_result::confidence_level, monitoring_module::trend_analyzer::prediction_result::confidence_lower, monitoring_module::trend_analyzer::prediction_result::confidence_upper, monitoring_module::trend_analyzer::prediction_result::predicted_value, and monitoring_module::trend_analyzer::prediction_result::timestamp.
Referenced by monitoring_module::analysis_dashboard::generate_forecast().
The documentation for this class was generated from the following files:
libraries/monitoring_system/sources/monitoring/trend_analyzer.h
libraries/monitoring_system/sources/monitoring/trend_analyzer.cpp