Messaging System: network_system::core::messaging_client Class Reference
network_system::core::messaging_client Class Reference
A basic TCP client that connects to a remote host, sends/receives data using asynchronous operations, and can apply a pipeline for transformations.
#include <messaging_client.h>
Public Member Functions
messaging_client (std::string_view client_id)
Constructs a client with a given client_id used for logging or identification.
~messaging_client ()
Destructor; automatically calls stop_client() if the client is still running.
auto start_client (std::string_view host, unsigned short port) -> void
Starts the client by resolving host and port, connecting asynchronously, and spawning a thread to run io_context_.
auto stop_client () -> void
Stops the client: closes the socket, stops the io_context_, and joins the worker thread.
auto wait_for_stop () -> void
Blocks until stop_client() is invoked, i.e., a synchronization mechanism.
auto send_packet (std::vector< uint8_t > data) -> void
Sends data over the connection, optionally compressing/encrypting via the pipeline.
Detailed Description
A basic TCP client that connects to a remote host, sends/receives data using asynchronous operations, and can apply a pipeline for transformations.
Key Features
Uses asio::io_context in a dedicated thread to handle I/O events.
Connects via async_connect, then wraps the socket in a tcp_socket for asynchronous reads and writes.
Optionally compresses/encrypts data before sending, and can similarly decompress/decrypt incoming data if extended.
Provides start_client(), stop_client(), and wait_for_stop() to control lifecycle.
Definition at line 68 of file messaging_client.h.
Constructor & Destructor Documentation
messaging_client()
network_system::core::messaging_client::messaging_client (std::string_view client_id)
Constructs a client with a given client_id used for logging or identification.
Parameters
client_id A string identifier for this client instance.
Definition at line 47 of file messaging_client.cpp.
References network_system::internal::make_default_pipeline().
~messaging_client()
network_system::core::messaging_client::~messaging_client ()
Destructor; automatically calls stop_client() if the client is still running.
Definition at line 56 of file messaging_client.cpp.
References stop_client().
Member Function Documentation
send_packet()
auto network_system::core::messaging_client::send_packet (std::vector< uint8_t > data) -> void
Sends data over the connection, optionally compressing/encrypting via the pipeline.
Parameters
data The buffer to send.
If not connected or not running, this call does nothing. Otherwise, prepare_data_async() + tcp_socket::async_send is used to deliver the bytes.
Definition at line 193 of file messaging_client.cpp.
References NETWORK_LOG_ERROR.
start_client()
auto network_system::core::messaging_client::start_client (std::string_view host, unsigned short port) -> void
Starts the client by resolving host and port, connecting asynchronously, and spawning a thread to run io_context_.
Parameters
host The remote hostname or IP address.
port The remote port number to connect.
Steps:
Create io_context_.
Launch client_thread_ running io_context_->run().
Resolve & connect, on success calling on_connect().
on_connect() sets up the tcp_socket and starts reading.
Definition at line 59 of file messaging_client.cpp.
References NETWORK_LOG_INFO.
stop_client()
auto network_system::core::messaging_client::stop_client () -> void
Stops the client: closes the socket, stops the io_context_, and joins the worker thread.
Definition at line 94 of file messaging_client.cpp.
References NETWORK_LOG_INFO.
Referenced by ~messaging_client().
wait_for_stop()
auto network_system::core::messaging_client::wait_for_stop () -> void
Blocks until stop_client() is invoked, i.e., a synchronization mechanism.
Definition at line 127 of file messaging_client.cpp.
The documentation for this class was generated from the following files:
libraries/network_system/include/network_system/core/messaging_client.h
libraries/network_system/src/core/messaging_client.cpp