Messaging System: libraries/network_system/tests/unit_tests_original.cpp File Reference
unit_tests_original.cpp File Reference
#include <gtest/gtest.h>
#include <memory>
#include <thread>
#include <chrono>
#include <vector>
#include <string>
#include <future>
#include <atomic>
#include "../network.h"
#include <container.h>
#include <values/string_value.h>
#include <values/numeric_value.h>
Classes
class NetworkTest
Functions
TEST_F (NetworkTest, ServerConstruction)
TEST_F (NetworkTest, ServerStartStop)
TEST_F (NetworkTest, ServerMultipleStartStop)
TEST_F (NetworkTest, ServerDoubleStart)
TEST_F (NetworkTest, ServerDoubleStop)
TEST_F (NetworkTest, ClientConstruction)
TEST_F (NetworkTest, ClientConnectToNonExistentServer)
TEST_F (NetworkTest, ClientServerBasicConnection)
TEST_F (NetworkTest, MultipleClientsConnection)
TEST_F (NetworkTest, ClientServerMessageExchange)
TEST_F (NetworkTest, LargeMessageExchange)
TEST_F (NetworkTest, ClientMessageHandler)
TEST_F (NetworkTest, ClientReconnection)
TEST_F (NetworkTest, SendWithoutConnection)
TEST_F (NetworkTest, NullMessageSend)
TEST_F (NetworkTest, RapidMessageSending)
TEST_F (NetworkTest, ConcurrentClientOperations)
TEST_F (NetworkTest, ServerSessionCleanup)
TEST_F (NetworkTest, IPv6Connection)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 585 of file unit_tests_original.cpp.
TEST_F() [1/19]
TEST_F (NetworkTest , ClientConnectToNonExistentServer)
Definition at line 155 of file unit_tests_original.cpp.
TEST_F() [2/19]
TEST_F (NetworkTest , ClientConstruction)
Definition at line 149 of file unit_tests_original.cpp.
TEST_F() [3/19]
TEST_F (NetworkTest , ClientMessageHandler)
Definition at line 301 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [4/19]
TEST_F (NetworkTest , ClientReconnection)
Definition at line 347 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [5/19]
TEST_F (NetworkTest , ClientServerBasicConnection)
Definition at line 165 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [6/19]
TEST_F (NetworkTest , ClientServerMessageExchange)
Definition at line 228 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [7/19]
TEST_F (NetworkTest , ConcurrentClientOperations)
Definition at line 461 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [8/19]
TEST_F (NetworkTest , IPv6Connection)
Definition at line 546 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [9/19]
TEST_F (NetworkTest , LargeMessageExchange)
Definition at line 263 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [10/19]
TEST_F (NetworkTest , MultipleClientsConnection)
Definition at line 190 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [11/19]
TEST_F (NetworkTest , NullMessageSend)
Definition at line 391 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [12/19]
TEST_F (NetworkTest , RapidMessageSending)
Definition at line 418 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [13/19]
TEST_F (NetworkTest , SendWithoutConnection)
Definition at line 378 of file unit_tests_original.cpp.
TEST_F() [14/19]
TEST_F (NetworkTest , ServerConstruction)
Definition at line 83 of file unit_tests_original.cpp.
TEST_F() [15/19]
TEST_F (NetworkTest , ServerDoubleStart)
Definition at line 121 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [16/19]
TEST_F (NetworkTest , ServerDoubleStop)
Definition at line 135 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [17/19]
TEST_F (NetworkTest , ServerMultipleStartStop)
Definition at line 106 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [18/19]
TEST_F (NetworkTest , ServerSessionCleanup)
Definition at line 515 of file unit_tests_original.cpp.
References FindAvailablePort().
TEST_F() [19/19]
TEST_F (NetworkTest , ServerStartStop)
Definition at line 88 of file unit_tests_original.cpp.
References FindAvailablePort().