Messaging System: database::query_builder Class Reference
database::query_builder Class Reference
Universal query builder that adapts to different database types.
#include <query_builder.h>
Public Member Functions
query_builder (database_types db_type=database_types::none)
~query_builder ()=default
query_builder & for_database (database_types db_type)
query_builder & select (const std::vector< std::string > &columns)
query_builder & from (const std::string &table)
query_builder & where (const std::string &field, const std::string &op, const database_value &value)
query_builder & join (const std::string &table, const std::string &condition)
query_builder & order_by (const std::string &column, sort_order order=sort_order::asc)
query_builder & limit (size_t count)
query_builder & collection (const std::string &name)
query_builder & key (const std::string &key)
query_builder & insert (const std::map< std::string, database_value > &data)
query_builder & update (const std::map< std::string, database_value > &data)
query_builder & remove ()
std::string build () const
database_result execute (database_base *db) const
void reset ()
Detailed Description
Universal query builder that adapts to different database types.
Definition at line 313 of file query_builder.h.
Constructor & Destructor Documentation
query_builder()
database::query_builder::query_builder (database_types db_type = database_types::none) explicit
Definition at line 994 of file query_builder.cpp.
~query_builder()
database::query_builder::~query_builder () default
Member Function Documentation
build()
std::string database::query_builder::build () const
Definition at line 1114 of file query_builder.cpp.
Referenced by execute().
collection()
query_builder & database::query_builder::collection (const std::string & name)
Definition at line 1063 of file query_builder.cpp.
execute()
database_result database::query_builder::execute (database_base * db) const
Definition at line 1126 of file query_builder.cpp.
References build(), and database::database_base::select_query().
for_database()
query_builder & database::query_builder::for_database (database_types db_type)
Definition at line 1000 of file query_builder.cpp.
from()
query_builder & database::query_builder::from (const std::string & table)
Definition at line 1016 of file query_builder.cpp.
insert()
query_builder & database::query_builder::insert (const std::map< std::string, database_value > & data)
Definition at line 1081 of file query_builder.cpp.
join()
query_builder & database::query_builder::join (const std::string & table, const std::string & condition)
Definition at line 1034 of file query_builder.cpp.
key()
query_builder & database::query_builder::key (const std::string & key)
Definition at line 1072 of file query_builder.cpp.
References key().
Referenced by key().
limit()
query_builder & database::query_builder::limit (size_t count)
Definition at line 1052 of file query_builder.cpp.
order_by()
query_builder & database::query_builder::order_by (const std::string & column, sort_order order = sort_order::asc)
Definition at line 1043 of file query_builder.cpp.
remove()
query_builder & database::query_builder::remove ()
Definition at line 1103 of file query_builder.cpp.
reset()
void database::query_builder::reset ()
Definition at line 1140 of file query_builder.cpp.
select()
query_builder & database::query_builder::select (const std::vector< std::string > & columns)
Definition at line 1007 of file query_builder.cpp.
update()
query_builder & database::query_builder::update (const std::map< std::string, database_value > & data)
Definition at line 1092 of file query_builder.cpp.
where()
query_builder & database::query_builder::where (const std::string & field, const std::string & op, const database_value & value)
Definition at line 1025 of file query_builder.cpp.
The documentation for this class was generated from the following files:
libraries/database_system/database/query_builder.h
libraries/database_system/database/query_builder.cpp