Messaging System: monitoring_module::ring_buffer< T > Class Template Reference
monitoring_module::ring_buffer< T > Class Template Reference
Thread-safe circular buffer for storing historical data.
#include <ring_buffer.h>
Public Member Functions
ring_buffer (std::size_t capacity)
Constructor.
bool push (const T &value)
Push an element to the buffer.
std::vector< T > get_recent (std::size_t count) const
Get recent elements from the buffer.
std::vector< T > get_all () const
Get all elements in the buffer.
void clear ()
Clear all elements from the buffer.
std::size_t size () const
Get the number of elements in the buffer.
std::size_t capacity () const
Get the capacity of the buffer.
bool empty () const
Check if the buffer is empty.
bool full () const
Check if the buffer is full.
Detailed Description
template<typename T>
class monitoring_module::ring_buffer< T >
Thread-safe circular buffer for storing historical data.
Template Parameters
T Type of elements to store
Definition at line 47 of file ring_buffer.h.
Constructor & Destructor Documentation
ring_buffer()
template<typename T > monitoring_module::ring_buffer< T >::ring_buffer (std::size_t capacity) inline explicit
Constructor.
Parameters
capacity Maximum number of elements to store
Definition at line 53 of file ring_buffer.h.
Member Function Documentation
capacity()
template<typename T > std::size_t monitoring_module::ring_buffer< T >::capacity () const inline
Get the capacity of the buffer.
Returns
Maximum capacity
Definition at line 151 of file ring_buffer.h.
clear()
template<typename T > void monitoring_module::ring_buffer< T >::clear () inline
Clear all elements from the buffer.
Definition at line 131 of file ring_buffer.h.
empty()
template<typename T > bool monitoring_module::ring_buffer< T >::empty () const inline
Check if the buffer is empty.
Returns
true if empty
Definition at line 159 of file ring_buffer.h.
full()
template<typename T > bool monitoring_module::ring_buffer< T >::full () const inline
Check if the buffer is full.
Returns
true if full
Definition at line 168 of file ring_buffer.h.
Referenced by TEST(), and TEST_F().
get_all()
template<typename T > std::vector< T > monitoring_module::ring_buffer< T >::get_all () const inline
Get all elements in the buffer.
Returns
Vector of all elements, oldest first
Definition at line 109 of file ring_buffer.h.
get_recent()
template<typename T > std::vector< T > monitoring_module::ring_buffer< T >::get_recent (std::size_t count) const inline
Get recent elements from the buffer.
Parameters
count Number of elements to retrieve
Returns
Vector of elements, newest first
Definition at line 87 of file ring_buffer.h.
Referenced by BM_RingBufferGetRecent(), TEST(), TEST(), and TEST_F().
push()
template<typename T > bool monitoring_module::ring_buffer< T >::push (const T & value) inline
Push an element to the buffer.
Parameters
value Element to add
Returns
true if successful, false if buffer is full
Definition at line 66 of file ring_buffer.h.
Referenced by BM_RingBufferGetRecent(), BM_RingBufferMultithreaded(), BM_RingBufferPush(), TEST(), TEST(), and TEST_F().
size()
template<typename T > std::size_t monitoring_module::ring_buffer< T >::size () const inline
Get the number of elements in the buffer.
Returns
Current size
Definition at line 142 of file ring_buffer.h.
Referenced by TEST(), TEST(), and TEST_F().
The documentation for this class was generated from the following file:
libraries/monitoring_system/sources/monitoring/storage/ring_buffer.h