Messaging System: SystemIntegratorTest Class Reference
SystemIntegratorTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
Protected Attributes
messaging_config config_
std::unique_ptr< system_integrator > integrator_
Detailed Description
Definition at line 12 of file test_system_integrator.cpp.
Member Function Documentation
SetUp()
void SystemIntegratorTest::SetUp () inline override protected
Definition at line 14 of file test_system_integrator.cpp.
References kcenon::messaging::config::config_builder::build(), config_, kcenon::messaging::config::config_builder::enable_compression(), integrator_, kcenon::messaging::config::config_builder::set_environment(), kcenon::messaging::config::config_builder::set_queue_size(), and kcenon::messaging::config::config_builder::set_worker_threads().
TearDown()
void SystemIntegratorTest::TearDown () inline override protected
Definition at line 26 of file test_system_integrator.cpp.
References integrator_.
Member Data Documentation
config_
messaging_config SystemIntegratorTest::config_ protected
Definition at line 32 of file test_system_integrator.cpp.
Referenced by SetUp().
integrator_
std::unique_ptr<system_integrator> SystemIntegratorTest::integrator_ protected
Definition at line 33 of file test_system_integrator.cpp.
Referenced by SetUp(), and TearDown().
The documentation for this class was generated from the following file:
application_layer/tests/unit/test_system_integrator.cpp