Messaging System: network_system::internal Namespace Reference
network_system::internal Namespace Reference
Namespaces
namespace detail
Classes
struct pipeline
Holds function objects for compressing, decompressing, encrypting, and decrypting data.
class tcp_socket
A lightweight wrapper around asio::ip::tcp::socket, enabling asynchronous read and write operations.
Enumerations
enum class data_mode : std::uint8_t {
packet_mode = 1 , file_mode = 2 , binary_mode = 3 , packet_mode = 1 ,
file_mode = 2 , binary_mode = 3 , packet_mode = 1 , file_mode = 2 ,
binary_mode = 3
}
Represents a simple enumeration for differentiating data transmission modes.
enum class data_mode : std::uint8_t {
packet_mode = 1 , file_mode = 2 , binary_mode = 3 , packet_mode = 1 ,
file_mode = 2 , binary_mode = 3 , packet_mode = 1 , file_mode = 2 ,
binary_mode = 3
}
enum class data_mode : std::uint8_t {
packet_mode = 1 , file_mode = 2 , binary_mode = 3 , packet_mode = 1 ,
file_mode = 2 , binary_mode = 3 , packet_mode = 1 , file_mode = 2 ,
binary_mode = 3
}
Functions
auto make_default_pipeline () -> pipeline
Creates a default pipeline with trivial (no-op) implementations for compress, decompress, encrypt, and decrypt.
auto prepare_data_async (const std::vector< uint8_t > &input_data, const pipeline &pl, bool use_compress, bool use_encrypt) -> std::future< std::vector< uint8_t > >
Launches a separate thread (via std::async) to apply compression/encryption to input_data using pl, returning a future for the processed data.
auto async_send_with_pipeline_no_co (std::shared_ptr< tcp_socket > sock, std::vector< uint8_t > data, const pipeline &pl, bool use_compress, bool use_encrypt) -> std::future< std::error_code >
Non-coroutine version that prepares data and then sends it asynchronously, returning a std::future<std::error_code>.
Variables
constexpr std::size_t default_buffer_size = 4096
constexpr std::size_t default_timeout_ms = 5000
constexpr std::string_view default_client_id = "default_client"
constexpr std::string_view default_server_id = "default_server"
Enumeration Type Documentation
data_mode [1/3]
enum class network_system::internal::data_mode : std::uint8_t strong
Represents a simple enumeration for differentiating data transmission modes.
A higher-level code might use these to switch between packet-based, file-based, or binary data logic. They are optional stubs and can be extended as needed.
Enumerator
packet_mode
Regular messaging/packet mode.
file_mode
File transfer mode.
binary_mode
Raw binary data mode.
packet_mode
Regular messaging/packet mode.
file_mode
File transfer mode.
binary_mode
Raw binary data mode.
packet_mode
Regular messaging/packet mode.
file_mode
File transfer mode.
binary_mode
Raw binary data mode.
Definition at line 50 of file common_defs.h.
data_mode [2/3]
enum class network_system::internal::data_mode : std::uint8_t strong
Enumerator
packet_mode
Regular messaging/packet mode.
file_mode
File transfer mode.
binary_mode
Raw binary data mode.
packet_mode
Regular messaging/packet mode.
file_mode
File transfer mode.
binary_mode
Raw binary data mode.
packet_mode
Regular messaging/packet mode.
file_mode
File transfer mode.
binary_mode
Raw binary data mode.
Definition at line 50 of file common_defs.h.
data_mode [3/3]
enum class network_system::internal::data_mode : std::uint8_t strong
Enumerator
packet_mode
Regular messaging/packet mode.
file_mode
File transfer mode.
binary_mode
Raw binary data mode.
packet_mode
Regular messaging/packet mode.
file_mode
File transfer mode.
binary_mode
Raw binary data mode.
packet_mode
Regular messaging/packet mode.
file_mode
File transfer mode.
binary_mode
Raw binary data mode.
Definition at line 50 of file common_defs.h.
Function Documentation
async_send_with_pipeline_no_co()
auto network_system::internal::async_send_with_pipeline_no_co (std::shared_ptr< tcp_socket > sock, std::vector< uint8_t > data, const pipeline & pl, bool use_compress, bool use_encrypt) -> std::future< std::error_code >
Non-coroutine version that prepares data and then sends it asynchronously, returning a std::future<std::error_code>.
Parameters
sock The tcp_socket to write on.
data The raw data (moved) for sending.
pl The pipeline for optional compression/encryption.
use_compress If true, compress data before sending.
use_encrypt If true, encrypt data after compression.
Returns
A std::future that eventually yields the std::error_code from async_write.
Example
auto fut = async_send_with_pipeline_no_co(socket, std::move(data), pl,
true, false); std::error_code ec = fut.get(); // blocking if(ec) { //
handle error }
Parameters
sock The tcp_socket to write on.
data The raw data (moved) for sending.
pl The pipeline for optional compression/encryption.
use_compress If true, compress data before sending.
use_encrypt If true, encrypt data after compression.
Returns
A std::future that eventually yields the std::error_code from async_write.
Example
auto fut = async_send_with_pipeline_no_co(socket, std::move(data), pl,
true, false); std::error_code ec = fut.get(); // blocking if(ec) { //
handle error }
Parameters
sock The tcp_socket to write on.
data The raw data (moved) for sending.
pl The pipeline for optional compression/encryption.
use_compress If true, compress data before sending.
use_encrypt If true, encrypt data after compression.
Returns
A std::future that eventually yields the std::error_code from async_write.
Example
auto fut = async_send_with_pipeline_no_co(socket, std::move(data), pl,
true, false); std::error_code ec = fut.get(); // blocking if(ec) { //
handle error }
Definition at line 97 of file send_coroutine.cpp.
References NETWORK_LOG_ERROR, and prepare_data_async().
make_default_pipeline()
auto network_system::internal::make_default_pipeline () -> pipeline
Creates a default pipeline with trivial (no-op) implementations for compress, decompress, encrypt, and decrypt.
Returns
A pipeline struct with stubbed function objects.
Definition at line 84 of file pipeline.cpp.
References network_system::internal::pipeline::compress, network_system::internal::detail::default_compress_stub(), network_system::internal::detail::default_decompress_stub(), network_system::internal::detail::default_decrypt_stub(), and network_system::internal::detail::default_encrypt_stub().
prepare_data_async()
auto network_system::internal::prepare_data_async (const std::vector< uint8_t > & input_data, const pipeline & pl, bool use_compress, bool use_encrypt) -> std::future< std::vector< uint8_t > >
Launches a separate thread (via std::async) to apply compression/encryption to input_data using pl, returning a future for the processed data.
Parameters
input_data The raw buffer to be processed.
pl The pipeline containing compress/encrypt functions.
use_compress If true, calls pl.compress().
use_encrypt If true, calls pl.encrypt().
Returns
A std::future that eventually yields the transformed data.
Definition at line 44 of file send_coroutine.cpp.
Referenced by async_send_with_pipeline_no_co().
Variable Documentation
default_buffer_size
constexpr std::size_t network_system::internal::default_buffer_size = 4096 inline constexpr
Definition at line 57 of file common_defs.h.
default_client_id
constexpr std::string_view network_system::internal::default_client_id = "default_client" inline constexpr
Definition at line 59 of file common_defs.h.
default_server_id
constexpr std::string_view network_system::internal::default_server_id = "default_server" inline constexpr
Definition at line 60 of file common_defs.h.
default_timeout_ms
constexpr std::size_t network_system::internal::default_timeout_ms = 5000 inline constexpr
Definition at line 58 of file common_defs.h.